### ISSUE TITLE
Отдавать JSON при загрузке файла на сервер

### ISSUE THREAD

**Issue by admiral-diver** [e-government-ua/i#100]
Метод: "/file/upload_file_to_redis"

Предусмотреть обратную совместимость для сервиса ввиду его текущего использования фронтом.

**Comment by bvv4ik** [comment]
почему-то  перестал работать сервис... не отдает ИД редис-а.. из-за этого опять не работает ПХП фронт

**Comment by bvv4ik** [comment]
не актуально
