### ISSUE TITLE
Реализовать отображение Крок 1 в профиле услуги, когда выбрана страна

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1000]

**Comment by bvv4ik** [comment]
готово:
https://test.igov.org.ua/service/1397/general

нужно убедиться, что не поламались остальные кейсы, с регионами и городдами, , в т.ч. редактированием их выбранности

**Comment by VadimGulich** [comment]
Копка изменить не активна
![image](https://cloud.githubusercontent.com/assets/12964120/11870835/d127648e-a4d3-11e5-9f5b-72364e6258b0.png)

А так все на 17.12.2015 работает =)
