### ISSUE TITLE
noreplay@igov.org.ua as the sender address for email notifications

### ISSUE THREAD

**Issue by bubenkoff** [e-government-ua/i#1002]
Hi
just noticed that there are quite a few typos in the codebase:
https://github.com/e-government-ua/i/search?utf8=%E2%9C%93&q=noreplay%40igov.org.ua

so it should be:

noreply@igov.org.ua

**Comment by bvv4ik** [comment]
были временные проблемы
уже устранили, спасибо за быструю реакцию)
