### ISSUE TITLE
Правка текста "Надання витягу з Єдиного державного реєстру МВС"  закладка "Як працює"

### ISSUE THREAD

**Issue by chemfind** [e-government-ua/i#1003]
Правка текста "Надання витягу з Єдиного державного реєстру МВС"  закладка "Як працює"
![igov_org_ua_ _ _ _](https://cloud.githubusercontent.com/assets/7547101/11850841/62447d68-a438-11e5-8b09-62acb6e7c271.jpg)
отримаэте э=є
https://igov.org.ua/service/1397/instruction

**Comment by ezhikus** [comment]
Уже поправлено в 456ccee456f3471cb47238ea00f55b0078f1c6ae , кроме того аналогичный баг для https://igov.org.ua/service/343/instruction поправлен в cd121007623aec32159241ec57672cc453f4a2f2 . Предлагаю закрыть.
