### ISSUE TITLE
Добавить в класс Interceptor обработку того метода закрытия таски, который использутся МВД

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1004]
Для сохранения статуса "Отработано" в центральном хистори (и персональном хистори)

И ОБЯЗАТЕЛЬНЫМ подсчетом и сохранением тайминга

**Comment by OlgaTurenko** [comment]
Для теста заказать услугу:
https://test.igov.org.ua/service/1397/general

Далее получить через гет запрос ее ид:
https://test.region.igov.org.ua/wf/service/runtime/tasks?processDefinitionKey=common_mreo_2

Подождать минут 5. Ид подставить в пост запрос в урл:
https://test.region.igov.org.ua/wf/service/runtime/tasks/4707548
В тело передать:
 {"action" : "complete"}

Должно в статистике отобразится время отработки задачи

**Comment by VadimGulich** [comment]
Подал- получил ИД
![image](https://cloud.githubusercontent.com/assets/12964120/12019652/a3e1e0d4-ad7b-11e5-8fb4-0e28a5289135.png)
Не отправляется запрос:
![image](https://cloud.githubusercontent.com/assets/12964120/12019813/b9f61c9e-ad7d-11e5-9150-556b7cfa9375.png)

**Comment by VadimGulich** [comment]
Нашел в чем бок был =)
Content-Type нужно application/json

Все ок , работает согласно описанию
