### ISSUE TITLE
Добавить детализации таймингов отработки заявки - до минут

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1005]
в сущности HistoryEvent_Service, поле nTimeHours
в идеале переименовать поле и заменит ьв нем данные пересчитвнные + поправить сущности (в сервисах пока возвращать в часах)

а если сложно, то просто добавить новое поле, и везде паралельно подвязаться к нему... а потом старое уже удалить, как заработает везде.

**Comment by chik** [comment]
Что делать с сервисом? Добавлять новое поле туда или пересчитывать для старого? Или старое удалить?

**Comment by chik** [comment]
Все сервисы изменены. Вместо поля nTimeHours теперь и возвращается и принимается nTimeMinutes. На данный момент поле из базы НЕ удалено, данные перенесены и пересчитаны в новое поле. Клиент изменен в соответствии с новым полем.

**Comment by RoOmel** [comment]
По запросу
http://test.igov.org.ua/wf/service/services/getHistoryEvent_Service?nID_Protected=22
возвращается ответ
{
    "sID": null,
    "nID_Task": 2,
    "nID_Subject": 2,
    "sStatus": "new",
    "sID_Status": "new",
    "sDate": "2015-11-09 18:50:02.772",
    "nID_Service": null,
    "nID_Region": null,
    "sID_UA": null,
    "nRate": 5,
    "soData": "[]",
    "sToken": null,
    "sHead": null,
    "sBody": null,
    "nTimeMinutes": null,
    "sID_Order": "0-22",
    "nID_Server": 0,
    "nID_Proccess_Feedback": null,
    "nID_Proccess_Escalation": null,
    "sID_Rate_Indirectly": null,
    "nID_Protected": 22,
    "nID": 40648
}
Реализовано согласно ТЗ.
