### ISSUE TITLE
Дописать, при сохранении в сервисе фидбэка "оценки" - находить порожденный БП фидбэка и проставлять там эту оценку в соотв.поле

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1006]
- сервис: /service/messages/setMessageRate
- БП фидбэка system_feedback а в нем поле nID_Proccess_Feedback
- поле привязки к БП nID_Proccess_Feedback в сущности HistoryEvent_Service

**Comment by bvv4ik** [comment]
так можно считать таску завершенной?)

**Comment by LamronNu** [comment]
)) почти. в процессе отладки и написания "схемы теста"

**Comment by LamronNu** [comment]
что сделано:
А. при создании бп по фидбеку в него передается оценка исходного бп (если она уже была проставлена)
Б. при установке оценки через сервис проверяется, есть ли запущенный НЕзавершенный бп фидбека, если да -- то в него проставляется указанная оценка.

исходя из этого, нужно проверить п. А и п. Б.
для этого,

1) создаем любую заявку, например, заказ справки о несудимости:
https://test.igov.org.ua/service/1/general
запоминаем ее номер (nID_Protected=91001466 )

2) проверка п. А:

2.1) устанавливаем оценку: 
https://test.igov.org.ua/wf/service/messages/setMessageRate?sHead=test&nID_Protected=91001466&sID_Rate=5
оценка должна быть от 1 до 5, параметр sHead -- произвольный, nID_Protected -- номер заявки из п.1
примечание. сейчас при переходе по данному урл предлагается в форму ввести отзыв об услуге -- вводим произвольный текст.
2.2) проверяем, что оценка проставилась:
https://test.igov.org.ua/wf/service/services/getHistoryEvent_Service?nID_Protected=91001466
в респонсе поле nRate должно равняться оценке, которая была передана в п. 2.1.
2.3) заходим в дашборд чиновника: https://test.region.igov.org.ua/tasks, ищем свою заявку (из п.1), переводим ее в работу, а потом "завершаем".
после завершения в Необроблених должен появится БП по фидбеку (обробка зворотнього зв’язку) -- проверяем поле "Оцінка громадянина": должно совпадать с оценкой из п.2.1.

3) проверка п. Б

3.1) устанавливаем другую оценку:
https://test.igov.org.ua/wf/service/messages/setMessageRate?sHead=test&nID_Protected=91001466&sID_Rate=2
3.2) убеждаемся, что она проставилась:
https://test.igov.org.ua/wf/service/services/getHistoryEvent_Service?nID_Protected=91001466
3.3) идем в дашборд, ищем наш процесс фидбека (из п.2.3.) -- проверяем, что оценка поменялась.
важно!! проверить, когда фидбек-процесс находится в разделе "Необроблені" и в разделе "В роботі".
3.4) завершаем бп по фидбеку. снова меняем оценку:
https://test.igov.org.ua/wf/service/messages/setMessageRate?sHead=test&nID_Protected=91001466&sID_Rate=3
а потом в дашборде в разделе "Оброблені" проверяем: оценка НЕ должна измениться.

**Comment by nazarenkod** [comment]
п.А: при установке оценки ошибка 
{"code":"404","message":"[setMessageRate](sID_Order: 0-94775059, nRate: 5): Unknown exception: Record with nID_Server=0 and nID_Process=9477505 not found!"}

**Comment by LamronNu** [comment]
какая заявка, какой именно запрос, какие шаги выполнены?

**Comment by nazarenkod** [comment]
справка о несудимости https://test.igov.org.ua/service/1/general
сохранил ее реф 0-95277219
устанавливаю оценку запросом
https://test.igov.org.ua/wf/service/messages/setMessageRate?sHead=test&nID_Protected=0-95277219&sID_Rate=4
ошибка 
{"code":"SYSTEM_ERR","message":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"0-95277219\""}

**Comment by LamronNu** [comment]
этот сервис (setMessageRate) сейчас в процессе переделки (#1051)
там другой параметр уже нужно писать, sID_Order, а не  nID_Protected
В общем, когда доделаю ту задачу, то обновлю схему теста в соответствии с изменениями в этом сервисе и отпишусь здесь.
