### ISSUE TITLE
Доработать на странице "Отчеты" блок Экспорта, с учетом доработанного унифицированного сервиса экспорта (статистики)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1008]
Учитывая доработанный сервис (реализовано по: https://github.com/e-government-ua/i/issues/977 )

- [x] 1) добавить в проперти и пробросить в коде 2 дополнительных поля:
bHeader = false // есть/нет хеадера
saFieldSummary = // поля для агрегатов

- [x] 2) добавить чекбокс "Все поля", который позволит передаст вместо поля для списка полей (параметр saFields) "пустоту", чтоб в итоге загрузились все поля.

- [x] 3) возле второго блока (статистики) добавить пометку "неактуально"

ВАЖНО:
образец проперти файла лежит тут:
\i\wf-region\src\main\resources\pattern\export\dnepr_spravka_o_doxodax.properties
название файла должно соответствовать ИД БП, тогда он подтянется с пропертями

**Comment by dmitrijzabrudskij** [comment]
выгрузка работает корректно
не работает чекбокс "все" - при его выборе выгружаются все равно те поля, которые прописаны в проперти-файле к этому бизнес-процессу
