### ISSUE TITLE
Реализовать механизм валидации маркеров

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1009]
Чтоб когда маркеры вытягиваются из полей с типом markers, из загруженной формі услуги, и начинают мержиться в основной объект с маркерами:
ОБЯЗАТЕЛЬНО проверялось - а узнался-ли этот маркер системой и узнались-ли все его параметры

- как вариант, можно проверяя число работающих маркеров(реально работающих) в базовом обьектк, и проверив число в мержуемом - после мержа сверять число в базовом(реально работающих). и если сумма по отдельности не совпадает с итоговой суммой - відавать ошибку, о том, что "не все маркеры успешно импортированы"

- можно по той-же схеме, что и выше, только сверять число реально привязанных ИД-шинков, из элемантов-массивов, типа:
"aField_ID":["reqPhis"],

- выводить ошибку в виде диалога (стандартного), а в консоле можно выводить подробности

Например:
работающий из тестовой услуги объект:
"RequiredFieldsOnCondition_1": {
         "aField_ID":["info1","file1"],
         "asID_Field": {
         "sClient":"client"
         },
         "sCondition":"[sClient] == 'attr1'"
         }

не работающий:
{
"motion": {
"RequredFieldsOnCondition_5": {
"aField_ID":["reqPhis"],
"asID_Field": {
"sCond1":"reqType"
},
"sCondition":"[sCond1]=='phis'"
},

ошибка в одной букве:
RequiredFieldsOnCondition
RequredFieldsOnCondition

по итогу второй вроде и загружался но не "вешался" на соответствующие ИД-шники

**Comment by serdyuk-alex** [comment]
Добавил схему и валидацию для attributes и motion, для валидаторов нужно разбираться, там много структур

**Comment by GFalcon-UA** [comment]
Доделал валидатор для проверки маркеров-валидаторов.
Проверка происходит в три этапа:

- соответствие имени маркера базовому шаблону
- соответствие структуры маркера базовму
- соответствие полей, указанных в маркере, полям формы, которая будет валидироваться

В случае нахождения какого-либо несоответствия - сообщение об ошибке выводится в консоли
После окончания валидации всех маркеров, в случае наличия ошибок - выводится модальное окно с итоговым сообщением

**Comment by GFalcon-UA** [comment]
Валидация выполняется в два этапа

1. проверка соответствия идентификаторов полей, которые указаны в подключаемых маркерах, на соответствие полям, которые присутствуют на форме (идентификаторы полей, которые указаны в дефолтных маркерах - не рассматриваются);
2. после мержа маркеров, проверяется их структура на соответствие шаблонам, которые описаны в файле https://github.com/e-government-ua/i/blob/test/public-js/markers/schema.js

Успешность валидации подтверждается двумя информационными сообщениями в консоли:
![image](https://cloud.githubusercontent.com/assets/13604023/16659180/afab525a-4471-11e6-9cd9-d9b3e54f9424.png)

В случае, если по какому-то из пунктов валидация не прошла - будет всплывающее окно с описанием ошибки и дублированием отображения подробной информации в консоли.
