### ISSUE TITLE
Актуалиазция спецификации интерфейсов Activity RESTful API

### ISSUE THREAD

**Issue by admiral-diver** [e-government-ua/i#101]
1. Найти хошорий шаблон для описания сепцификации REST сервисов
2. Актуализировать текущую спецификацию согласно этого шаблона

Ссылка на спецификацию: https://github.com/e-government-ua/i/blob/test/docs/specification.md

**Comment by azolotko** [comment]
Как на счет https://apiblueprint.org/ ?

**Comment by admiral-diver** [comment]
Почему бы и нет. Спасибо!

**Comment by nakolkin** [comment]
А мы на работе используем http://raml.org/ 
C blueprint/swagger, честно говоря, не сравнивал.

**Comment by paul-lysak** [comment]
Swagger - не только спецификация, но и UI, которым можно "пощупать" рестовое АПИ. Недавно, кстати, на работе занимался интеграцией со Spring MVC - сработало норм.

**Comment by nakolkin** [comment]
RAML тоже с UI, которым можно "пощупать". :)

**Comment by paul-lysak** [comment]
Метаданные для Swagger где-то на 90% генерится из спринговых аннотаций

**Comment by nakolkin** [comment]
Где то читал, что Swagger лучше подходит для описания (генерирования) уже существующего рест-апи. Raml мы в основном использовали для описания и прототипирования нового апи на базе ошибок и неудобств старого. 
Вот еще такое сравнение нашел http://www.mikestowe.com/2014/07/raml-vs-swagger-vs-api-blueprint.php
