### ISSUE TITLE
Реализовать механизм автоматического пред-заполнения полей формы услуги, теми данными, которыми гражданин в последний раз заполнял эту-же услугу

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1010]
- [x] 1) При заходе в форму услуги - проверять через сервис getCountOrders ( https://github.com/e-government-ua/i/issues/1047 ) - наличие такой-же поданной заявки (при заданном nLimit=1 в ответе должно быть nOpened=1) в месте у данного гражданина, и при ее наличии отображать в верхнем-правом углу надпись-ссылку "Предзаполнить по прошлой"
(иначе скрывать)

- [x] 2) При клике на ссылку "Предзаполнить по прошлой" - проставлять данные в полях формы, подгруженные через сервис https://github.com/e-government-ua/i/issues/922 (только те, что совпадут по id и type)

**Comment by Sokhatsky** [comment]
Для послуги https://test.igov.org.ua/service/724/general даний механізм не працює

**Comment by Sokhatsky** [comment]
Для послуги https://test.igov.org.ua/service/762/general не заповнюються наступні поля:
Оберіть свій район або місто:
Місце реєстрації (вкажіть область, місто, вулицю, будинок, квартиру):

**Comment by Sokhatsky** [comment]
Для послуги https://test.igov.org.ua/service/778/general не заповнюються наступні поля:
Оберіть свій район або місто:
Місце реєстрації (вкажіть область, місто, вулицю, будинок, квартиру):
У Вас українське громадянство:

**Comment by Koffeek** [comment]
Не работает связка предзаполнение по конкретной услуге+город. Впечатление, что просто подбрасывает последние значения по данному ID для данного пользователя, какую бы заявку он не заполнял.

**Comment by bvv4ik** [comment]
Поправлено, прошу перепроверить!
проверять на бете

**Comment by Koffeek** [comment]
Привязка к услуге - работает, привязка услуга-город - нет. Но это пока не критично.

**Comment by Sokhatsky** [comment]
По услуге https://test-version.igov.org.ua/service/654/general
Не заполняются поля:
- Оберіть свій район або місто:
-*Разом з Вами мешкають інші особи?:

**Comment by Sokhatsky** [comment]
Для послуги: https://test-version.igov.org.ua/service/775/general
Не заповнюються автоматично поля:
1. Оберіть свій район або місто;
2. Місце реєстрації (вкажіть область, місто, вулицю, будинок, квартиру);
3. У Вас є у володінні земельна частка (пай)

**Comment by Sokhatsky** [comment]
Для услуги https://test-version.igov.org.ua/service/1460/general пред-заполнение полей не осуществляется. 
Отсутствует надпись ссылка пред-заполнение по прошлой
