### ISSUE TITLE
Реализовать сервис получения данных по Таске (в начале базовая реализация)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1011]
1) Название getTaskData
2) Параметры
nID_Task номер-ИД таски (обязательный)
nID_Order - номер-ИД заявки (опциональный, но обязательный если не задан nID_Task )
3) Ответ:
{
oProcess : {
sName: "Услуга номер 1", //Название услуги (БП)
sBP: "serv_1", //id-бизнеспроцесса (БП)
nID: 3424235, //номер-ИД процесса
sDateCreate: "2015-11-12 12:12:56.001" //дата создания процесса
}
}

где 
sDateCreate - определяется через поиск базовой юзертаски через заданную в запросе, и определении ее даты создания (это и будет первичная дата создания процесса)

4) Описать в комментариях к сервису все его параметры и назначение
(чтоб все попало в авто-сгенеренную доку)

П.С.: образец механизма поиска исходной таски есть
-  в классе RequestProcessingInterceptor, гв методе saveUpdatedTaskInfo или saveClosedTaskInfo, где идет сохранение истории, при апдейте или закрытии таски (и ищется базовый id процесса)...
- и так-же в классе Abstract_MailTaskCustom, методе replaceTags_Catalog, когда идет рекурсивный переход вплоть до корневой таски.

например:
        HistoricTaskInstance historicTaskInstance = historyService.createHistoricTaskInstanceQuery().taskId(
                task_ID).singleResult();
        String sID_Process = historicTaskInstance.getProcessInstanceId();
где task_ID - ИД исходной таски
sID_Process - ИД процесса
а остальные данные можно получить из обьекта historicTaskInstance

**Comment by bvv4ik** [comment]
Добрый день,
как там успехи по задаче?
может есть какие-то сложности и помощь нужна?

**Comment by Khalikov** [comment]
осталось сделать поиск данных по ID_Order

**Comment by bvv4ik** [comment]
Привет,
как там дела с таской обстоят?

**Comment by Khalikov** [comment]
Вроде как что-то заработало
Вот я беру рабочий запрос из своего же контроллера
https://test.region.igov.org.ua/wf/service/action/task/getTasksByText?sFind=будинк
и получаю список номеров тасок:
["8948078","9359006","9282806","9360306","8948520","9397569","8730378","9405504","8750306"]
это чтоб наверняка взять существующий номер
Теперь беру, и ввожу СВОЙ запрос с одним из этих номеров
https://test.region.igov.org.ua/wf/service/action/task/getTaskData?nID_Task=8948078
и получаю вот такой ответ:
 {"dateCreate":"2015-12-26 16:29:09.977","bp":"subsidiesUkraine:3:8747504","name":"Отримання субсидії на оплату житлово-комунальних послуг","id":8947773}
Надеюсь, это именно то, что и требовалось получить?

**Comment by Khalikov** [comment]
Исправил названия геттеров. Теперь ответ приходит такой:
{"sName":"Отримання субсидії на оплату житлово-комунальних послуг","sBP":"subsidiesUkraine:3:8747504","nID":8947773,"sDateCreate":"2015-12-26 16:29:09.977"}

**Comment by GFalcon-UA** [comment]
Добавил возможность получения данных по nID_Process:

**Comment by GFalcon-UA** [comment]
Тестировал так:
Создал новую заявку на тестовом альфа
Получил номер своей заявки 0-100825010
С помощью запроса определяю номер Таски
https://test.region.igov.org.ua/wf/service/action/task/getTasksByOrder?nID_Order=100825010
nID_Task = 10082846

Варианты запросов для получения тестового ответа:
https://test.region.igov.org.ua/wf/service/action/task/getTaskData?nID_Task=10082846
https://test.region.igov.org.ua/wf/service/action/task/getTaskData?nID_Task&nID_Process=10082501
https://test.region.igov.org.ua/wf/service/action/task/getTaskData?nID_Task&sID_Order=0-100825010
https://test.region.igov.org.ua/wf/service/action/task/getTaskData?nID_Task&sID_Order=100825010

Получаемый ответ:
{"sName":"Отримання субсидії на оплату житлово-комунальних послуг","sBP":"subsidiesUkraine:3:8747504","nID":10082501,"sDateCreate":"2016-01-23 23:44:38.380"}

Захожу в дашборд чиновника и принимаю заявку в обработку.
По известному nID_Order получаю новый nID_Task
При выполнении всех предыдущих запросов (в первый подставлять новый nID_Task), ответ должен быть такой же, как и до взятия заявки в обработку.

**Comment by bvv4ik** [comment]
ключевое реализовано, можо закрівать
