### ISSUE TITLE
Доработать сущность сообщения субьекта и реализовать сервисы сообщений по заявкам

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1012]
- [x] 1) Доработать сущность: SubjectMessage
1.1. Добавить поле:
nID_HistoryEvent_Service //номер-ИД связки записи события сервиса //null-эйбл

- [x] 2) Создать сервис "Получение сообщения-фидбека заявки"
/messages/getMessageFeedbackExtended (GET)
Параметры:
- sID_Order //строковой-ИД заявки
- sToken //строковой секрет

По которому находить запись в HistoryEvent_Service
и через nID_HistoryEvent_Service в сущности SubjectMessage
искать запись с сообщением где nID_SubjectMessageType=1.

- Если найдена строка SubjectMessage, то возвращать объект:
```json
{
sDate: "2015-11-10 23:23:59 001" //строка дата заявки //SubjectMessage.sDate
, sHead: "Получение справки о доходах" //строка заголовка //SubjectMessage.sHead
, sID_Order: "1-654326" //строковой-ИД заявки
}
```
ВАЖНО: если в найденной строке будет sBody="", то sDate нужно ставить null
- Если не найден - возвращать 404 статус и сообщение "Record Not Found"
- Если sToken<>"" && sToken<>null && sTokenне совпадет с HistoryEvent_Service.sToken то выводить 403 статус и сообщение "Security Error"

- [x] 3) Создать сервис "Сохранение сообщения-фидбека заявки"
/messages/setMessageFeedbackExtended (POST)
Параметры:
- sID_Order //строковой-ИД заявки
- sToken //строковой секрет
- sBody //строка текста фидбэка

По которому находить запись в HistoryEvent_Service
и через nID_HistoryEvent_Service в сущности SubjectMessage
искать запись с сообщением где nID_SubjectMessageType=1.

- Если строка SubjectMessage найдена и sBody="", то обновлять. (ставить nID_SubjectMessageType=1)

ВАЖНО: если успешно добавлена/обновлена то устанавливать sToken="" и sDate установить текущую.
- Если найдена и sBody<>"", то возвращать 403 статус и сообщение "Already exist"
- Если не найден - возвращать 404 статус и сообщение "Record Not Found"
- Если sToken<>"" && sToken<>null && sToken не совпадет с HistoryEvent_Service.sToken то выводить 403 статус и сообщение "Security Error"

- [x] 4) Описать все параметры сервиса и сами их в комментах, для автогенерации доков по АПИ

**Comment by ASkosyr** [comment]
Пример запроса для получения сообщения

https://test.igov.org.ua/wf/service/messages/getMessageFeedbackExtended?sID_Order=0-4446&sToken=TokenValue

Ответ

```{"sHead":"head","sDate":"2015-12-21 12:09:56 235","sID_Order":"0-4446"}
```

Пример запроса, который возвращает ошибку 403

https://test.igov.org.ua/wf/service/messages/getMessageFeedbackExtended?sID_Order=0-33&sToken=TokenValue

```{"code":"BUSINESS_ERR","message":"Security Error"}
```

Пример запроса, который возвращает ошибку 404

https://test.igov.org.ua/wf/service/messages/getMessageFeedbackExtended?sID_Order=0-331&sToken=TokenValue

```{"code":"BUSINESS_ERR","message":"Record Not Found"}
```

**Comment by bvv4ik** [comment]
Кажись ошибочку нашел:
,
https://test.igov.org.ua/wf/service/messages/getMessageFeedbackExtended?sID_Order=0-5551&sToken=TokenValue2

возвращает:

{
"sHead": "head2",
"sDate": "2015-12-21 12:09:56 235",
"sID_Order": "0-5551"
}

хотя:
ВАЖНО: если в найденной строке будет sBody="", то sDate нужно ставить null

и при этом в SubjectMessage.csv:
nID;sHead;sBody;sDate;nID_Subject;sMail;sContacts;sData;nID_SubjectMessageType;sBody_Indirectly;nID_HistoryEvent_Service
2;head2;;2015-12-21 12:09:56.235;1;test@igov.org.ua;contact;data;1;Body Inderectly;4

т.е. sBody именно = ""

**Comment by ASkosyr** [comment]
Задача уже подправлена.
Теперь только немного поменялся урл для вызова метода

https://test.igov.org.ua/wf/service/subject/message/getMessageFeedbackExtended?sID_Order=0-5551&sToken=TokenValue2

```
{"sHead":"Відгук по відпрацьованій послузі за заявою 0-5551","sDate":null,"sID_Order":"0-5551"}
```

**Comment by RoOmel** [comment]
1.1. Добавить поле:
nID_HistoryEvent_Service //номер-ИД связки записи события сервиса //null-эйбл
Как проверить реализацию?

2) Создать сервис "Получение сообщения-фидбека заявки"
/messages/getMessageFeedbackExtended (GET)
ВАЖНО: если в найденной строке будет sBody="", то sDate нужно ставить null
Как проверить реализацию?

3) Создать сервис "Сохранение сообщения-фидбека заявки"
/messages/setMessageFeedbackExtended (POST)
Как проверить реализацию?

**Comment by ASkosyr** [comment]
Чтобы проверить вот рабочие запросы:

https://test.igov.org.ua/wf/service/subject/message/setMessageFeedbackExtended?sID_Order=0-5551&sToken=TokenValue2&sBody=text_feedback

https://test.igov.org.ua/wf/service/subject/message/getMessageFeedbackExtended?sID_Order=0-5551&sToken=TokenValue2

по-поводу первого вопроса - Как проверить реализацию nID_HistoryEvent_Service?.
при обработке запроса getMessageFeedbackExtended вытягивается значение из SubjectMessage по айдишнику nID_HistoryEvent_Service и в результат подставляется значение date.

я проверял на тестовых значениях, которые грузятся из тестовых данных.

Как проверит на сторефронте - наврное лучше спросить у веб-разработчиков, которые эти методы использовали.

**Comment by RoOmel** [comment]
При запросе
https://test.igov.org.ua/wf/service/subject/message/setMessageFeedbackExtended?sID_Order=0-5551&sToken=TokenValue2&sBody=text_feedback
ответ сервера
{
    "code": "BUSINESS_ERR",
    "message": "Request method 'GET' not supported"
}
При запросе
https://test.igov.org.ua/wf/service/subject/message/getMessageFeedbackExtended?sID_Order=0-5551&sToken=TokenValue2
ответ сервера
{
    "sHead": "Відгук по відпрацьованій послузі за заявою 0-5551",
    "sDate": null,
    "sID_Order": "0-5551"
}

**Comment by RoOmel** [comment]
Реализовано согласно ТЗ
