### ISSUE TITLE
Добавить еще одну закладку "Все", в которую выводить в т.ч. таски, которые ассайнуты не того, кто авторизован в данный момент

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1014]
При этом:

- [x] 1) Список тасок выводить так-же в привязке к связанным с юзером группам (как и сейчас, только отображать задачи ассайнутые не только на себя)

- [x] 2) Отображать закладку только если юзер входит в группу manager или admin или kermit

- [x] 3) Не отображать при выбранной в списке таске - кнопки обработки заявки

- [x] 4) Отображать так-же, выше всех полей заявки строку, с ассайнутым юзером(с лейблом "Ассайнута на"(если ни на кого то в значении "ни на кого", иначе логин того, на кого ассайнута)) и рядом с ним кнопку "открепить", при клике на которую будет вызываться сервис https://github.com/e-government-ua/i/issues/1026 после чего будет рефрешиться форма с заявкой (чтоб сразу было видно что больше ни к кому не прикреплена)

**Comment by dmitrijzabrudskij** [comment]
предусмотреть порционность отображения - потому что сейчас отображается максимум 500 заявок на странице, по некоторым услугам будет гораздо больше - то есть нужно либо дать выбрать "следующие 500" или же фильтровать по дате

**Comment by bvv4ik** [comment]
учтено п.6

**Comment by AleksejDomash** [comment]
Закладка должна быть на уровне фильтров как Тікети 0
В роботі 2
Необроблені 6
Оброблені 7?

**Comment by bvv4ik** [comment]
да, это равноценная им закладка

**Comment by bvv4ik** [comment]
фильтры на отдельной ишью:
https://github.com/e-government-ua/i/issues/1093

**Comment by kurbpa** [comment]
*Отображать закладку только если юзер входит в группу manager или admin или kermit* - **работает**
