### ISSUE TITLE
В профиле киева, при заходе в профиль услуги - автоматически предустанавливать место "Область" = Киев

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1016]
(там можно задавать как отдельным параметром названия так и ИД-шником sID_UA. в УРЛ-е 

зайти на тестовый профиль кКиева можно так:
https://test.kiev.igov.org.ua

**Comment by bvv4ik** [comment]
Добрый день,
как там успехи с таской?

**Comment by bvv4ik** [comment]
может помощь нужна?

**Comment by iRipVanWinkle** [comment]
Во вторник доделаю. Все понятно,  но как по мне оно немного на костылях сделано будет. 

Я только не разобрался как можно запустить локально на киевский профиль.

**Comment by bvv4ik** [comment]
ок, будем очень ждать, т.к. очень вероятно, что как раз во вторник и деплоиться в продакшин будем... очень хотелось-бы чтоб эта реализация попала в бой... а то Киевляне достаточно ддавно ожидают такую возможность


логально, только через правку кода без комита...

**Comment by iRipVanWinkle** [comment]
А почему Киев вынесен в область?

**Comment by kurbpa** [comment]
Область предустанавливается.
