### ISSUE TITLE
В форме услуги, при подтяжке данных через сервис getSubjectOrganJoin (уже реализовано) - проставлять по атрибутам значения соответствующих полей

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1017]
- [ ] 1) заполнять передаваемый в сервис /getSubjectOrganJoin параметр &bIncludeAttributes=true и mAttributeCustom с объектом из полей формы
Например: &mAttributeCustom={"n1":"5","n2":"3"}
это означает, что есть поля на форме, у которых id=n1 со значением 5, и id=n2 со значением 3

- [ ] 2) проставлять значения в полях ИД-шники которых совпадают с названиями атрибутов.
Например: пришел объект с элементом:
"aAttribute": [
{
"subjectOrganJoinId": 1167,
"nID": null,
"sName": "n1",
"sValue": "5"
},
{
"subjectOrganJoinId": 1167,
"nID": null,
"sName": "n2",
"sValue": "3"
}]
что означает что нужно на форме заполнить у элементов с id=n1 установить значение "5" а у id=n2 установить значение "3"

- [ ] 3) проставлять сразу после выбора какого-то из пунктов SubjectOrganJoin (в комбобоксе) и именно его значения атрибутов проставлять (а не все в списке SubjectOrganJoin).

- [ ] 4) использовать тот-же метод getSubjectOrganJoin, который просто был доработан по задаче:
https://github.com/e-government-ua/i/issues/982

- [ ] 5) при каждом изменении любого поля - нужно перепосылать этот запрос со всеми параметрами (точно так-же, как это делается и при выборе пункта в комбобоксе, как в п.3), и так-же перепроставлять по полученным значениям значения полей формы

**Comment by kurbpa** [comment]
id процесса - common_mvd_1_urgent
ссылка на услуга на тестовом портале - https://test.igov.org.ua/service/1414/general
для Днепропетровской области

**Comment by kurbpa** [comment]
на стартовой таске указанного процесса есть поля с id, соответствующими  полям в аттрибутах для подстановки значений,  

 id="PaySum" 
 id="Bill" 
 id="MFO" 
 id="BillOKPO" 

значения не подтягиваются.

**Comment by bvv4ik** [comment]
дык еще-ж только создали ишью)
для фронта теперь...она еще в работе...
(бэк был готов вот недавно)

**Comment by Koffeek** [comment]
@bvv4ik Для полей 
id="Bill"
id="MFO"
id="BillOKPO" 
данные подтягиваются 
id="PaySum"
имеет тип label и там судя по всему формула - она не отрабатывает. 
Ещё момент: количество отображаемых адресов в поле "sID_Public_SubjectOrganJoin" для одного и того же пункта, равно количеству записей по нему в файле аттрибутов (т.е. один и тот же адрес отображается, например, 10 или 14 раз)

**Comment by hordesalik** [comment]
@Koffeek , @bvv4ik , количество отображаемых адресов в поле "sID_Public_SubjectOrganJoin" - это видимо с бека приходит их куча, я изменений не делал

**Comment by Koffeek** [comment]
@bvv4ik @hordesalik Услуга https://test.igov.org.ua/service/29/general  (Днепропетровская область, Днепропетровск, Бабушкинский район) в поле "nID_Department_visitDay" данные не передаются.

**Comment by hordesalik** [comment]
@Koffeek , @bvv4ik 
> данные подтягиваются 
> id="PaySum"
> имеет тип label и там судя по всему формула - она не отрабатывает. 

```
{subjectOrganJoinId: 1078, nID: 13, sName: "PaySum", sValue: null}
```
т.е. в это поле ничего и не загружается

**Comment by hordesalik** [comment]
@Koffeek @bvv4ik 
> Услуга https://test.igov.org.ua/service/29/general (Днепропетровская область, Днепропетровск, Бабушкинский район) в поле "nID_Department_visitDay" данные не передаются. Нужна какая-то особая форма записи для полей?

Добавил фикс. Деплоится

**Comment by kurbpa** [comment]
@bvv4ik 
@Koffeek 
@hordesalik 
 
В лейбл  данные записываются корректно для полей 
id="Bill"
id="MFO"
id="BillOKPO" 

Но значение не подтягивается в поле с формулой id="PaySum" 

Возможно как-то влияет тот момент, что в формуле анализируется значение  из enum **id=price_1200000000**, которое заполняется уже после того как  выбирается значение в селекте и не имеет никакого дефолтного значения изначально.

**Пример формул, используемый в SubjectOrganJoinAttribute**
296;1110;PaySum_Days1;5 днів<a href="  " target="blank"> (103.5 грн. + 1.8% комісія) сплатити онлайн </a>;
297;1110;PaySum_Days2;7 днів<a href="  " target="blank"> (74.4 грн. + 1.8% комісія) сплатити онлайн </a>;
298;1110;PaySum;=[price_1200000000]=1?[PaySum_Days1]:[price_1200000000]=2?[PaySum_Days2]

**Comment by hordesalik** [comment]
Возможно, да... Я думаю на беке можно это сделать, чтобы расчитанные значения учавствовали в формулах, как вроде они пришли  фронта

**Comment by bvv4ik** [comment]
"kurbpa:  Очень смущает, что  10 раз дублируются записи в селекте  в  услуге https://test.igov.org.ua/service/1414/general

в файле SubjectOrganJoin эти записи не дублируются и не  копировались мною по мере наполнения этого файла ранее....
пример 
1078;13;м.Луцьк, вул.Винниченка, 11;м.Луцьк, вул.Винниченка, 11;700000000_1;700000000_1; ; ;NULL;NULL;700000000

этас трока дублируется 10 раз в селекте, если выбрать  вышеуказаную услугу для Волынской области.
"

@kurbpa
да, тут дубли почемуто именно с бэка приходят...
сейчас разбираюсь...

если что, то проверять можно вот так:
https://test.igov.org.ua/wf/service/services/getSubjectOrganJoins?nID_SubjectOrgan=13&sID_UA=1200000000

**Comment by bvv4ik** [comment]
@kurbpa

такс, вроде удалось починить дубли на бєке

**Comment by kurbpa** [comment]
@bvv4ik 
 проверил - дубли пропали !
отлично!

Осталось дожать формулы.

**Comment by bvv4ik** [comment]
@kurbpa
по формулам, Павел, у тебя в ней ДВЕ ошибки)

1) посмотри внимательно:
298;1110;PaySum;=[price_1200000000]=1?[PaySum_Days1]:[price_1200000000]=2?[PaySum_Days2]

в:
"=[price_1200000000]=1?[PaySum_Days1]:[price_1200000000]=2?[PaySum_Days2]"
тут в конце стоит: "?[PaySum_Days2]"

а должно быть еще в конце, как минимум ";'чтототам'"

т.е. вид должен быть хотябы:
"=[price_1200000000]=1?[PaySum_Days1]:[price_1200000000]=2?[PaySum_Days2];'чтототам'"

2) и второй момент:
у тебя не обернуты в кавычки тэги, в которых должны быть стринговые значения(точнее их содержимое)...

в итоге у тебя формула превращается в набор текстов "в перемешку"
потому правильный вариант формулы, должен быть:
"=[price_1200000000]==1?'[PaySum_Days1]':[price_1200000000]==2?'[PaySum_Days2]':'чтототам'"
а не:
"=[price_1200000000]==1?[PaySum_Days1]:[price_1200000000]==2?[PaySum_Days2]:чтототам"

П.С.: по п.2. .есть альтернативный вариант, который юзается в маркерах ,а именно, когда первый символ названия переменной говорит о типе данных (n=Number или s=String, типа "nSum" или "sFamily")... тогда я мог-бы сделать автоматическое подставление кавычек там, где это стринга.... но тогда вам пришлось-бы все переменные, которые вы используете там - именовать исходя из этой логики (если помниш, я всегда так именую переменные, но вот у вас в БП там - сборная солянка, потому - думайте сами, решайте сами)))

**Comment by bvv4ik** [comment]
@kurbpa 
Паша, если все работает - прошу закрыть таску

**Comment by kurbpa** [comment]
Всё работает корректно.
