### ISSUE TITLE
Реализовать поддержку в сервисе getSubjectOrganJoins опционального параметра nID, при задаче которого должно выдавать только одну запись с заданным ИД

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1019]

**Comment by bvv4ik** [comment]
для проверки попробовать:

https://test.igov.org.ua/wf/service/services/getSubjectOrganJoins?nID=1167&nID_SubjectOrgan=284&sID_UA_=1&mAttributeCustom={%22n1%22:%225%22,%22n2%22:%223%22,%22n0%22:%22=[n1]%3E3?111:222%22,%22sMisc%22:%22test%22}&bIncludeAttributes=true

и:

https://test.igov.org.ua/wf/service/services/getSubjectOrganJoins?nID_SubjectOrgan=284&sID_UA_=1&mAttributeCustom={%22n1%22:%225%22,%22n2%22:%223%22,%22n0%22:%22=[n1]%3E3?111:222%22,%22sMisc%22:%22test%22}&bIncludeAttributes=true

**Comment by RoOmel** [comment]
Запрос
https://test.igov.org.ua/wf/service/services/getSubjectOrganJoins?nID=1167&nID_SubjectOrgan=284&sID_UA_=1&mAttributeCustom={%22n1%22:%225%22,%22n2%22:%223%22,%22n0%22:%22=[n1]%3E3?111:222%22,%22sMisc%22:%22test%22}&bIncludeAttributes=true
возвращает 
[
    {
        "subjectOrganId": 284,
        "aAttribute": [
            {
                "subjectOrganJoinId": 1167,
                "nID": null,
                "sName": "n0",
                "sValue": "111.0"
            }
        ],
        "nID": 1167,
        "sNameUa": "Тернопільська митниця",
        "sNameRu": "Тернопільська митниця",
        "sID_Privat": "40300 00 00",
        "sID_Public": "40300 00 00",
        "sGeoLongitude": " ",
        "sGeoLatitude": " ",
        "nID_Region": null,
        "nID_City": null,
        "sID_UA": "6100000000"
    }
]
Запрос
https://test.igov.org.ua/wf/service/services/getSubjectOrganJoins?nID_SubjectOrgan=284&sID_UA_=1&mAttributeCustom={%22n1%22:%225%22,%22n2%22:%223%22,%22n0%22:%22=[n1]%3E3?111:222%22,%22sMisc%22:%22test%22}&bIncludeAttributes=true
возвращает  много записей

**Comment by bvv4ik** [comment]
проверено уже в действвующем механизме
