### ISSUE TITLE
При вызове сервиса /setMessageRate добавить в конце его при успехе добавление записи в сущность SubjectMessage и редиректить на страницу фидбека

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1020]
Для обеспечения работы, в рамках задачи: https://github.com/e-government-ua/i/issues/991

Добавлять запись в сущность SubjectMessage.csv подобно:
nID;sHead;sBody;sDate;nID_Subject;sMail;sContacts;sData;nID_SubjectMessageType;sBody_Indirectly;nID_HistoryEvent_Service
2;head2;;2015-12-21 12:09:56.235;1;test@igov.org.ua;contact;data;1;Body Inderectly;4

т.е.
- с пустым полем sBody
- связкой nID_HistoryEvent_Service (найти по ИД заявки запись в HistoryEvent_Service)
- текущей датой в sDate
- в sHead писать "Оставить отзыв о отработанной заявке №____"
- в nID_SubjectMessageType задавать тип фидбека
- остальное можно скопировать с образца записи №2 (выше)

2) в записи HistoryEvent_Service - генерировать sToken из 15-ти символов (латинских букв(разного кейса) и цифр) и записывать в нее его

3) в конце редиректить по адресу:
https://test.igov.org.ua/feedback?sID_Order=0-5551&sSecret=TokenValue2
с соответствующими параметрами (и хост центрального сервера брать с гетера класса generalConfig)

**Comment by ASkosyr** [comment]
Логику добавил

Пример работающего урла
https://test.igov.org.ua/wf/service/messages/setMessageRate?sHead=TestHead&sID_Order=0-87329225

Редиректит на форму заполнения фидбека, однако номер заявки не отображается корректно
http://prntscr.com/9i4rqc

**Comment by RoOmel** [comment]
Прошу дать описание параметров запроса и ожидаемый ответ, т.к. запрос
https://test.igov.org.ua/wf/service/messages/setMessageRate?sHead=TestHead&sID_Order=0-87329225&nIdProtected=87329225
возвращает
{
    "code": "BUSINESS_ERR",
    "message": "Required String parameter 'sID_Rate' is not present"
}
При этом параметр sID_Rate не описан в задаче.

**Comment by bvv4ik** [comment]
проверено уже в действвующем механизме
