### ISSUE TITLE
Отработать пул задач в беклоге

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1021]
Каждый, у кого есть немного времени - может отработать один или несколько пунктов, и отметив это в самом файле - отписаться так-же в комментариях к этой ишью:

https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit

так-же, если обнаружите какие-то новые недоработки - просьба добавлять их в конец списка (прикрепленного файла), с указанием даты и гитхаб-логина того, кто обнаружил

**Comment by ezhikus** [comment]
Там в том файле треть уже давно исправлена (я такое зачеркиваю), и ещё треть касается внешних сервисов (bankId, гугл-форм) - с этим я не знаю что делать.
