### ISSUE TITLE
Переименовать системный тег (в отсылаемом письме) [nID_Protected] в [sID_Order]

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1024]
ОБЯЗАТЕЛЬНО: переименовать во всех БП (bpmn) и патернах /patterns/*

**Comment by chik** [comment]
"Удаление назначенного пользователя с задачи по ИД. #####\n\n"
            + "HTTP Context: https://server:port/wf/service/rest/tasks/resetUserTaskAssign?nID_UserTask=[nID_UserTask]\n\n"
            + "- nID_UserTask - ID таски для удаления пользователя с нее.\n\n"
            + "Request:\n"
            + "https://test.region.igov.org.ua/wf/service/rest/tasks/resetUserTaskAssign\n\n"
            + "- nID_UserTask=24\n"
            + "Responce if task assigned: HTTP STATUS 200\n\n"
            + noteCODE
            + "{}\n"
            + noteCODE
            + "Response if task is not assigned: HTTP STATUS 200\n\n"
            + noteCODE
            + "{\"Not assigned UserTask\"}\n\n"
            + noteCODE
            + "Response if task not found: HTTP STATUS 403 Forbidden\n\n"
            + noteCODE
            + "{\n"
            + "\"code\": \"BUSINESS_ERR\"\n"
            + "\"message\": \"Record not found\"\n"
            + "}"
            ;

**Comment by chik** [comment]
Sorry. Wrong ticket.
