### ISSUE TITLE
Реализовать сервис, который позволит по ИД юзертаски сбрасывать в ней ассайнутого юзера

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1026]
- [ ] 1) Сервис назвать /resetUserTaskAssign (в контроллере ActivitiRestTaskController)
- [ ] 2) Параметры:
nID_UserTask - номер-ИД юзертаски
- [ ] 3) Отдавать 200-тый код при успехе или объект JSON с текстом об ошибке (если не ассайнут, то писать "Not assigned UserTask""
- [ ] 4) в комментах описать сервис и параметры

**Comment by chik** [comment]
"Удаление назначенного пользователя с задачи по ИД. #####\n\n"
            + "HTTP Context: https://server:port/wf/service/rest/tasks/resetUserTaskAssign\n\n"
            + "- nID_UserTask - ID таски для удаления пользователя с нее.\n\n"
            + "Request:\n"
            + "https://test.region.igov.org.ua/wf/service/rest/tasks/resetUserTaskAssign\n\n"
            + "- nID_UserTask=24\n"
            + "Responce if task assigned: HTTP STATUS 200\n\n"
            + noteCODE
            + "{}\n"
            + noteCODE
            + "Response if task is not assigned: HTTP STATUS 200\n\n"
            + noteCODE
            + "{\"Not assigned UserTask\"}\n\n"
            + noteCODE
            + "Response if task not found: HTTP STATUS 403 Forbidden\n\n"
            + noteCODE
            + "{\n"
            + "\"code\": \"BUSINESS_ERR\"\n"
            + "\"message\": \"Record not found\"\n"
            + "}"

**Comment by bvv4ik** [comment]
п.4. я имел в виду в коментах кода) (в т.ч.аннотациях)
чтоб это все описание попало в авто-генерируемую документацию

**Comment by VadimGulich** [comment]
Забыли указать: метод POST использовать , чтоб тестировщикам было понятней))
А так все ок , работает корректно
