### ISSUE TITLE
Отображать во всплівающем окне сообщение (в т.ч. кастомное), сразу после после нажатия на кнопку "Опрацювати"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1027]
При наличии поля с id=sNotifyEvent_AfterSubmit - использовать его значение в качестве текста сообщения, иначе использовать дефолтный текст "форму відправлено".

**Comment by bvv4ik** [comment]
можно тестировать через 5 минут

**Comment by kurbpa** [comment]
Поле добавил в процесс _test_fields_bankid

**Comment by kurbpa** [comment]
функционирует, но без поддержки  ХТМЛ.
значение в поле: 
```<b> like </b> https://github.com/e-government-ua/i/issues/1027```
отображается в виде обычного текста

**Comment by Sokhatsky** [comment]
Доброго дня! Будь ласка опишіть задачу більш детальніше.

**Comment by Akylish88** [comment]
По идее надо так, писать нужный текст в дефаулт id="sNotifyEvent_AfterSubmit" name="сопроводительный текст" type="string" default="${tooltiptext}"

**Comment by kurbpa** [comment]
Релизовано. Без поддержки ХТМЛ.
Протестировано.
