### ISSUE TITLE
Реализовать доработку сервиса расширенного фидбека .чтоб после повторного обращения к сетеру - не выводило ошибку безопасности и немного доработать механизм

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1028]
1) 
- СЕЙЧАС: при вызове сервиса "Получения сообщения-фидбека заявки"
/messages/setMessageFeedbackExtended
( https://github.com/e-government-ua/i/issues/1012 )
и успешном сохранении данных - сбрасывается токен,
что приводит к тому, что при вызове сервиса:
/messages/getMessageFeedbackExtended - выдает ошибку безопасности (а это может понадобиться, когда человек просто "рефрешит" страничку с отзывом (на фронте), где в таком случае нужно отобразить только дату подачи отзыва.

- НУЖНО: чтоб при вызове сервиса /messages/getMessageFeedbackExtended, и и определении, что заявка уже подавалась (sBody!="") - ответный объект обязательно отдавался, даже если токен отсутствует или не совпадает (при этом в объекте не выводить поле sBody)

2) создание записи с собщением  вынести в сервис setMessageFeedbackExtended из /setMessageRate (чтоб не плодить пустые записи) и создать отдельный тип сообщений для Рейтинга

**Comment by bvv4ik** [comment]
для тестирования нужно:
-создать заявку на услугу,
-отработать ее
-поставить оценку из пришедшего письма
-после чего редиректит на страницу фидбека, где нужно заполнив текст отправить его
-в дополнениенужно потом рефрешнуть страницу и убедить ся что сохранится сообщение о дате фидбека (ошибка не должна выспетиться)

**Comment by VadimGulich** [comment]
На какой конкретной услуге реализован данный функционал ?

**Comment by nazarenkod** [comment]
после оценки ошибка:
{"code":"404","message":"[setMessageRate](sID_Order: 0-94826209, nRate: 4): Unknown exception: Record with nID_Server=0 and nID_Process=9482620 not found!"}
