### ISSUE TITLE
Добавить в сервис шаринга документа (/setDocumentAccessLink) обязательно проверку параметра nID_Subject, на принадлежность ему шарящегося документа

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1030]
Сейчас такая проверка по этому сервису отсутствует, в отличии от сервисов getDocumentFile и getDocuments

**Comment by lesha1980** [comment]
Я так понимаю, что эта проверка есть в getDocument, не в getDocuments. В getDocuments вообще проверки отсутствуют, тогда как в getDocumentFile проверка есть.

**Comment by bvv4ik** [comment]
а можно ссылку на комит, плиз?
(вообще, при сомите в комменте стоит писать ссылку на ишью, например https://github.com/e-government-ua/i/issues/1030 , тогда в коментах ишью автоматом появится ссылка на этот комит)

**Comment by lesha1980** [comment]
мой коммит https://github.com/e-government-ua/i/commit/f46507da775b361f31312022d6ef11662c4b62fc Если верно понял задание, то сделал так.

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/12019118/c1279fd2-ad74-11e5-96d7-563a2c8e3114.png)

![image](https://cloud.githubusercontent.com/assets/12964120/12019129/e2abf6da-ad74-11e5-8734-6632a159189f.png)

Нет возможности входа в документы!

**Comment by bvv4ik** [comment]
@lesha1980 глянь плиз

**Comment by lesha1980** [comment]
Подскажите, а почему проверка происходит для central-js, тогда как сервис нужно проверять для http://test.igov.org.ua/wf/service/setDocumentLink. Я никаких целенаправленных изменений в проект central-js не вносил. Если они были внесены, то только в результате сбоя, о котором говорил выше, но я надеюсь, что они не "болезненны".

Подумал, что может добавленный мной в метод аргумент не позволяет сделать нормально запрос через central-js. Так как в комментария о наличии аргумента nID_Subject в методе setDocumentAccessLink говорится, но реально его там не было. Поэтому его пришлось добавлять.Закомментировал свои изменения и проверил на тестовом портале. Но и в этом случае случае выпала ошибка, которую указал VadimGulich. Поэтому к данной ошибке, думаю, никакого отношения мои корректировки в wf-central не имеют.

**Comment by lesha1980** [comment]
О сбое. Мне Netbeans решила сначала предложить откат при извлечении данных с сервера, так как угрожала какими-то конфликтами. Затем, я фиксировал свои изменения в ActivitiDocumentAccess, но при этом начались зависания и подвисания IDE. Когда выталкивал на сервер данные, то и не подозревал, что IDE внесла какие-то коррективы и в другой проект, так как он не был даже открыт в IDE. Результатом стала необходимость полной переустановки Netbeans.

**Comment by lesha1980** [comment]
Не знаю, но кто-то исправил ошибки.
![screen1](https://cloud.githubusercontent.com/assets/12561441/12024654/da00cda0-adae-11e5-9f1d-08fad274f2fd.jpg)
![screen2](https://cloud.githubusercontent.com/assets/12561441/12024659/f03e0f7e-adae-11e5-8de5-6ebc0f2c0187.jpg)

**Comment by VadimGulich** [comment]
https://github.com/e-government-ua/i/blob/test/docs/specification.md#11-Предоставление-и-проверка-доступа-к-документам-описание-занесено-в-swagger
