### ISSUE TITLE
Доработать систему учета субьектов-людей для поддержки идентификацые через производную сущность контактов (электронный адрес и телефон)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1032]
- [ ] 1) Добавить энум SubjectHumanIdType и в него добавить следующие элементы:
INN
Passport
Email
Phone

- [ ] 2) Создать сущность SubjectContact с полями:
nID - Номер-ИД (уникальный-автоитерируемый)
nID_Subject - Номер-ИД связки с записями сущности Subject
nID_SubjectContactType - Номер-ИД связки с записью сущности SubjectContactType
sValue - строка со значением (непосредственно контактом)

- [ ] 3) Создать сущность SubjectContactType с полями:
nID - Номер-ИД (уникальный)
sName_EN - строка с названием, на английском
sName_UA - строка с названием, на украинском
sName_RU - строка с названием, на русском

- и в csv сразу добавить несколько базовых значений:
0;Phone;Телефон;Телефон
1;Email;Электнонный адрес;Електрона адреса
2;Skype;Скайп;Скайп
3;GitHub;Гитхаб;Гитхаб

- [ ] 4) в сущности SubjectHuman реализовать доработки:

- [ ] 4.1) Добавить опциональные поля (связанные с nID сущности SubjectContact):

- nID_SubjectContact_DefaultEmail - номер-ИД контакта-емэйла субъекта по умолчанию
- nID_SubjectContact_DefaultPhone - номер-ИД контакта-телефона субъекта по умолчанию

- [ ] 4.2) Добавить поле nID_SubjectHumanIdType, с дефолтным значением 0
в сетере которого проверять на соответствие индексу допустимых элементов энума SubjectHumanIdType (п.1), при не совпадении которого выводить эксепшин "Not Valid SubjectHumanIdType"

- [ ] 5) Доработать сервис /syncSubject

- [ ] 5.1) добавить туда опциональные параметры:
- nID_SubjectHumanIdType - номер-ИД типа идентификации субьекта-человека (если не задан считать равным 0)
sCode_Subject - строка-код, параметр-идентификатора субьекта (без префикса типа).

- [ ] 5.2)если заданы оба параметра п.5.1, то при поиске записи сущности Subject обязательно учитывать sCode_Subject и nID_SubjectHumanIdType (п.5.1), ищя в поле sID, сущности Subject, как-бы "композитное значение", прикрепляя nID_SubjectHumanIdType слева от sCode_Subject через разделитель ";" и дописывая перед ним еще символ "_" (ВАЖНО: только если он не равен 0)
Например, при входящих параметрах
- nID_SubjectHumanIdType=1 и sCode_Subject="АЕ4325324" искать в поле sID сущности Subject
"_1;АЕ4325324"
- nID_SubjectHumanIdType=2 и sCode_Subject="a@a.a" искать в поле sID сущности Subject
"_2;a@a.a"
- nID_SubjectHumanIdType=0 и sCode_Subject="34265456" искать в поле sID сущности Subject
"34265456"
ВАЖНО: Старая схема должна продолжить работать! (т.е. должна быть обратная совместимость)

- [ ] 5.3) при создании записи в сущности Subject:
сохранять в поле sID "композитное значение" (искомое в рамках п.5.2)

- [ ] 5.4) при создании записи в сущности SubjectHuman:

- [ ] 5.4.1) сохранять в поле nID_SubjectHumanIdType значение параметра nID_SubjectHumanIdType (из п.5.1)

- [ ] 5.4.2) если nID_SubjectHumanIdType = 2 или 3 (т.е. идентификаторы в виде почты или телефона), то создавать производную запись в сущности SubjectContact, где:
- в поле sValue записывать исхожный поступивший параметр sID,
- в поле nID_SubjectContactType простявлять значение, исходя из nID_SubjectHumanIdType т.е. если 2 (Email), то писать 1 (Email в SubjectContactType),
а если 3 (Phone), то 0 (Phone в SubjectContactType)
в сущности SubjectHuman 
- в поле nID_Subject писать значение поля nID, созданной записи сущности Subject

- [ ] 5.4.3) если этот тип=почта (по п.5.4.2), в сущности SubjectHuman сохранять в поле 
nID_SubjectContact_DefaultEmail - значение nID созданной записи  (по п.5.4.2)

- [ ] 5.3.4) если этот тип=телефон (по п.5.4.2), в сущности SubjectHuman сохранять в поле 
nID_SubjectContact_DefaultPhone - значение nID созданной записи  (по п.5.4.2)

**Comment by RoOmel** [comment]
Описания с примером запроса по ссылке
https://github.com/e-government-ua/i/blob/test/docs/specification.md#
не нашёл, поэтому прошу привести пример ссылки запроса, либо указать новую ссылку документации.
