### ISSUE TITLE
Создать сервис верификации контакта - электронного адреса

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1033]
- [x] 1) назвать:
verifyContactEmail

- [x] 2) Параметры:
- sQuestion - строка-запроса (сам электронный адрес)
- sAnswer - строка-ответа (тот код, что пришел на электронку) //опциональный 

- [x] 3) Ответ:
если без ошибок, то статус 200 и объект JSON:
{
bVerified: true //true=верифицирован (при запросе - валидность, при ответе - принадлежность)
}
если ошибка то тоже обьект но со статусом не 200

- [x] 4) Принцип работы:
4.1) если sAnswer не задан, то отсылать на адрес, указанный в sQuestion письмо(класс Mail) с:
темой: Верификация адреса
телом: Код подтверждения: ________
4.2) код подтверждения (для п.4.1) генерировать из больших и маленьких латинских символов и цифр, длиной 15 символов
4.3) так-же сохоанять этот-же код в Редис-хранилище с ключем, в виде присланного электронного адреса 
4.4) так-же проверять по маске сам формат электронного адреса при запросе, и если он не валидный, то возвращать в ответе bVerified: false
4.5) если sAnswer задан, то сверять его с сохраненным ранее в хранилище Редис (п.4.3) и при его совпадении выводить в ответе bVerified: true иначе bVerified: false

- [x] 5) в комментариях и анотациях кода заполнить название и описание сервиса и параметров ,чтоб это попало в автогенерируемую доку по АПИ

**Comment by ASkosyr** [comment]
https://test.region.igov.org.ua/wf/service/rest/verifyContactEmail?sQuestion=test@igov.org.ua

```json
{"bVerified":"true"}
```

**Comment by ASkosyr** [comment]
https://test.region.igov.org.ua/wf/service/rest/verifyContactEmail?sQuestion=test@igov.org.ua&sAnswer=ujHZfRRMYe0g5kK

```json
{"bVerified":"true"}
```

**Comment by RoOmel** [comment]
Задача реализована согласно ТЗ.
Запросы протестированы:
1) При не заданном значении параметра sAnswer 
2) При значении параметра sAnswer взятого из письма, отправленного на адрес email.
 
Прошу ASkosyr просмотреть коммент к задаче
https://github.com/e-government-ua/i/issues/897
