### ISSUE TITLE
Создать сервис /getSubjectHuman и  /getSubjectOrgan

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1034]
- [x] 1) Входящий параметр (у обоих):
nID_Subject - номер-ИД субьекта
- [x] 2) В ответ JSON-обьект сущности
- [x] 3) В комментариях и анотациях занести все описания сервиса и параметров, для автогенерации доки по АПИ

**Comment by ASkosyr** [comment]
https://test.igov.org.ua/wf/service/subject/getSubjectHuman?nID_Subject=1

https://test.igov.org.ua/wf/service/subject/getSubjectOrgan?nID_Subject=1

**Comment by RoOmel** [comment]
1) По запросу
https://test.igov.org.ua/wf/service/subject/getSubjectOrgan?nID_Subject=1
Ответ сервера
{
    "oSubject": {
        "sID": "ПАО",
        "sLabel": "ПАО ПриватБанк",
        "sLabelShort": "ПриватБанк",
        "nID": 1
    },
    "sOKPO": "093205",
    "sFormPrivacy": "ПАО",
    "sNameFull": "Банк ПриватБанк",
    "nID": 1,
    "sName": "ПриватБанк"
}

2) По запросу
https://test.igov.org.ua/wf/service/subject/getSubjectHuman?nID_Subject=1
Ответ сервера
{
    "code": "SYSTEM_ERR",
    "message": "could not extract ResultSet"
}
2) Ответ не соответствует ожидаемому.

ASkosyr, прошу просмотреть коммент к задаче
https://github.com/e-government-ua/i/issues/897

**Comment by ASkosyr** [comment]
что-то стало с объектом SubjectHuman.
вечером посмотрю

По тикету 897 тоже сегодня посмотрю и отвечу

**Comment by ASkosyr** [comment]
Ответ по запросу https://test.igov.org.ua/wf/service/subject/getSubjectHuman?nID_Subject=1 исправился.

**Comment by RoOmel** [comment]
Реализовано согласно ТЗ
