### ISSUE TITLE
Переделать механизм работы с сервисом /setMessageRate при вызове его из письма, чтоб была безлимитная авторизация

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1036]
СЕЙЧАС:
при формировании в письме ссылки на сервис, для сохранения оценки - используется одноразовый sAccessKey, из-за чего, после повторного клика в письме - требует ввести логин/пароль

НУЖНО
вместо типа контракта  AuthenticationTokenSelector.ACCESS_CONTRACT_REQUEST_AND_LOGIN
создать новый  AuthenticationTokenSelector.ACCESS_CONTRACT_REQUEST_AND_LOGIN_UNLIMITED
который не будет удалять ключ-доступа, после его использования
и соответственно, при вормировании ссылки на сервис рейтингования использовать уже этот тип контракта

Так-же, в сервисе /setMessageRate проверят ьустановленность в записи истории рейтинга, и нсли он уже установлен - новое сообщение не создавать и рейтинг не обновлять, а только переходить на последний этап - редиректить

**Comment by nazarenkod** [comment]
Пожалуйста, подскажите сценарий для теста

**Comment by bvv4ik** [comment]
реализовано
