### ISSUE TITLE
Реализовать создание двух отдельных сообщений в сущности SubjectMessage при вызове сервиса /setMessageFeedback_Indirectly

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1037]
подобно тому, как это реализовано в сервисе /setMessageRate

1) для рейтинга тип сообщения должен быть 2
Хеадер(sHead): Уточнююча оцінка о відпрацованій послузі по заяві " + sID_Order
Тело(sBody): Оцінка sID_Rate_Indirectly (по шкалі від 2 до 5)

2) для отзыва тип сообщения должен быть 1
Хеадер(sHead): Уточнюючий відгук о відпрацованій послузі по заяві " + sID_Order
Тело(sBody): sBody_Indirectly

**Comment by LamronNu** [comment]
1) создаем любую заявку, например, заказ справки о несудимости:
https://test.igov.org.ua/service/1/general
запоминаем ее номер (nID_Protected=91001466)


2) заходим в дашборд чиновника: https://test.region.igov.org.ua/tasks, ищем свою заявку (из п.1), переводим ее в работу, а потом "завершаем".
после завершения в Необроблених должен появится БП по фидбеку (обробка зворотнього зв’язку) -- запоминаем его ИД nID_Proccess_Feedback=9100231
так же можно посмотреть это ид в HistoryEvent_Service по этой заявке (там проще скопировать значение): 
https://test.igov.org.ua/wf/service/services/getHistoryEvent_Service?nID_Protected=91001466

3) устанавливаем оценку и отзыв: 
https://test.igov.org.ua/wf/service/messages/setMessageFeedback_Indirectly?nID_Protected=91001466&nID_Proccess_Feedback=9100231&sBody_Indirectly=test-Note-feedback&sID_Rate_Indirectly=5
где
nID_Protected -- номер-ИД заявки из п.1
nID_Proccess_Feedback -- Номер-ИД бп фидбека по заявке из п.2
sBody_Indirectly -- строка отзыв об услуге (вводим любое значение)
sID_Rate_Indirectly -- строка-ИД Рнйтинга/оценки (вводим любое число от 2 до 5)

4) вытягиваем список всех сообщений:
https://test.igov.org.ua/wf/service/messages/getMessages
в конце списка должны появиться два новых сообщения с текстами, указанными в таске,
 т.е. "Відгук по відпрацьованій послузі за заявою 0-91001466", тип 2:
```json
{
"nID": 45092,
"nID_Subject": 20045,
"oSubjectMessageType": {"sDescription": "Отзыв о услуге", "nID": 2, "sName": "ServiceFeedback"},
"sBody": "test-Note-feedback",
"sContacts": "",
"sData": "sID_Rate=5",
"sDate": "2016-01-05 14:27:18.783",
"sHead": "Відгук по відпрацьованій послузі за заявою 0-91001466",
"sMail": ""
}
```
 и "Оцінка по відпрацьованій послузі за заявою 0-91001466", тип 1
 ```json
{
"nID": 45093,
"nID_Subject": 20045,
"oSubjectMessageType": {"sDescription": "Оценка услуги", "nID": 1, "sName": "ServiceRate"},
"sBody": "Оцінка 5 (по шкалі від 2 до 5)",
"sContacts": "",
"sData": "sID_Rate=5",
"sDate": "2016-01-05 14:27:18.822",
"sHead": "Оцінка по відпрацьованій послузі за заявою 0-91001466",
"sMail": ""
}
 ```

**Comment by LamronNu** [comment]
в SubjectMessageType.csv добавлено 2 новых типа:
```
6;ServiceRate_Indirectly;Уточняющая оценка услуги
7;ServiceFeedback_Indirectly;Уточняющий отзыв об услуге
```
поскольку тип 1 и 2, описанный в задаче, используется для установки оценки и отзыва самим клиентом, у нас же -- это оценка, которая проставляется "сотрудником, отрабатывающим БП-фидбека, со слов гражданина"

схема теста обновлена (см. предыдущий комментарий)
