### ISSUE TITLE
Выяснить почему и исправить неверную кодировку вывода сообщений при использовании сервиса /cancelTask

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1040]
Из-за этого приходится выводить текст латиницей

**Comment by uncle-T0ny** [comment]
Не была задана кодировка респонса. 
В header-e Content-Type параметр charset устанавливался как ISO-8859-1,
который определн по умолчанию в StringHttpMessageConverter.

**Comment by RoOmel** [comment]
Прошу добавить сценарий для тестирования.

**Comment by uncle-T0ny** [comment]
ожидаемый результат:
запрос /cancelTask должен выводить не латиницу, а кирилические символы
