### ISSUE TITLE
"Прикрутить" к вызовам сервисов "замечаний по заявкам"(/setTaskQuestions и /setTaskAnswer_Central) - добавление сообщений с сообщениями и данными

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1042]
подобно тому, как это реализовано в сервисе /setMessageRate

только 
1) для чиновника (при его замечании)
тип сообщения должен быть 5
Хеадер(sHead): Зауваження по заяві " + sID_Order
Тело(sBody): sBody (комментарий работника)
Данные(sData): обьект с данными по полям (saData)
ВАЖНО:
при доработке регионального сервиса /setTaskQuestions - в нем вызывать сервис централа, по добавлению сообщения.

2) для гражданина (при его ответе)
тип сообщения должен быть 4
Хеадер(sHead): Відповідь на зауваження по заяві " + sID_Order
Тело(sBody): sBody (комментарий клиента)
Данные(sData): обїект с данными по заполненнім полям (saData)

**Comment by LamronNu** [comment]
схема теста:

1) создаем любую заявку, например, заказ справки о несудимости:
https://test.igov.org.ua/service/1/general
запоминаем ее номер (*nID_Protected=93052484*), 
также нам нужно знать её *sID_Order=0-93052484* 

**примечание**. если с этой услугой "проблемы" (у меня не хотело сохранятся, писало ошибку: SYSTEM_ERR Exception while invoking TaskListener: Exception while invoking TaskListener: null), 
то берем какую-то другую услугу. 
мною протестировано на _test_smart_print_form, https://test.igov.org.ua/service/769/general. (для нее нужно заходить в дашборд не под kermit\kermit, а под tester\tester)

2) заходим в дашборд чиновника: https://test.region.igov.org.ua/tasks, ищем свою заявку (из п.1), 
вносим замечания (кнопка "внести зауваження") -- отправляем.

3) проверяем, проставилось ли сообщение с типом 5 (п. 1 в таске). кидаем запрос:
https://test.igov.org.ua/wf/service/subject/message/getServiceMessages?sID_Order=0-93052484
где sID_Order -- ид нашей заявки
должна быть хотя бы одна запись (если там несколько сообщений -- то ищем по дате и типу):
```json
{
"mail":"",
"nID_HistoryEvent_Service":45186,
"nID":45209,
"sHead":"Зауваження по заяві 0-93052484",
"sBody":"test body",
"sDate":"2016-01-10 16:54:14.867",
"nID_Subject":20045,
"sContacts":"",
"sData":"[{\"id\":\"WhenCome\",\"type\":\"string\",\"value\":\"dddd\"},{\"id\":\"newAddress\",\"type\":\"textArea\",\"value\":\"dddd\"}]",
"oSubjectMessageType":
	{
		"sDescription":"Работника комментарий по услуге",
		"nID":5,
		"sName":"ServiceCommentEmployee"
	}
}
```
4) заходим на свою почту и "отвечаем" на запрос. 
снова проверяем, проставилось ли сообщение с типом 4 (п.2 в таске);

```json
{
"mail":"",
"nID_HistoryEvent_Service":45186,
"nID":45211,"sHead":"Відповідь на зауваження по заяві 0-93052484",
"sBody":"client comment",
"sDate":"2016-01-10 17:50:52.295",
"nID_Subject":20045,
"sContacts":"",
"sData":"[{\"id\":\"WhenCome\",\"type\":\"string\",\"value\":\"fffff\"},{\"id\":\"newAddress\",\"type\":\"textArea\",\"value\":\"ttttttt\"}]",
"oSubjectMessageType":
	{
		"sDescription":"Клиентский комментарий по услуге",
		"nID":4,
		"sName":"ServiceCommentClient"
	}
}

```

**Comment by RoOmel** [comment]
Блокер на пункте 2), согласно сценария выше.
После нажатия кнопки отправки замечания ничего не происходит, при этом все поля заполнены.

**Comment by LamronNu** [comment]
насчет логина-пароля -- я имела ввиду, что если тестировать на услуге _test_smart_print_form, то нужно заходить под тестер/тестер. для несудимости кермит/кермит подходит.

отправка замечаний -- только что проверила (на той своей услуге _test_smart_print_form) -- все отправилось.
там сначала кнопку "внести замечания" нажать, потом выделить галочками поля, которые нужно уточнить, ввести комментарии -- и потом нажать "отправить замечания". оно немного долго "думало", но потом выдало сообщение, что замечания успешно отправлены.

по Вашей заявке. попробовала отправить, выдало ошибку: {"code":"BUSINESS_ERR","message":"error during setTaskQuestions: Error happened when sending email ()(oID_Message=null), caused: Email and Phone are empty. At least one argument can't be empty."}
странно... у Вас там точно был указан емейл и он валидный (а то в дашборде не видно его среди полей)?

в общем, если не получится на этой услуге -- попробуйте на другой, задача проверить не отправку замечаний (то задача #835, наверное, если баг повторится, то лучше его там описать), а проставления сообщений по этим замечаниям

**Comment by RoOmel** [comment]
Странно, поля "Уточнити" не являются обязательными, по крайней мере никакие визуальные обозначения для этого не отображаются.

**Comment by RoOmel** [comment]
Даже при заполнении полей для уточнений и после нажатия кнопки отправки - ничего не происходит.

**Comment by LamronNu** [comment]
>Даже при заполнении полей для уточнений и после нажатия кнопки отправки - ничего не происходит.

Вы обе услуги имеете ввиду? или только справку о несудимости?
потому что на указанной мной услуге все отрабатывало...
