### ISSUE TITLE
В закладке статусы, при авторизованности, и выбранной заявке (принадлежащей авторизованному) - отображать список истории мессаджей заявки и давать возможность оставлять комментарии.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1045]
Подобно тому, как отображается диалог ответа на замечания чиновника, только без требуемых полей (отдельный блок) и без требования токена. (https://test.igov.org.ua/order/search?sID_Order=0-22)

- [ ] 1) Сверять  допустимость просмотра(иначе скрывать эти элементы) сообщений и отправки комментария по сверке nID_Subject в загруженном элементе истории (по введенному ИД заявки) с тем что в сессии (после авторизации по БанкИД он будет а если не авторизован то отображать кнопку авторизации БанкИД, и по ее завершении возвращаться обратно).

Подробней: если авторизация есть, нужно глянуть в сессию (или может уже на клиенте есть копия инфы, например в куке), и взять значение nID_Subject, использовав в качестве параметра в дополнение к параметру номера заявки - подтянуть с бэка явы через сервис - обьект-массив записей-истории по заявке

- [ ] 2) Блок с историей отображать ниже всего, с вертикальным скролом и высотой 200 пикселей и подгружать список через сервис  /getServiceMessages с параметром sID_Order ( https://github.com/e-government-ua/i/issues/1043 ) и в каждом сообщении на одной строке отображать три минуса, пробел, дату/время, двоеточие, Название (sHead), а ниже само тело (sBody).

Подробней: отображать скролируемый вертикально блок (можно и таблицу, наверно), где в каждой строке размещать по одному элементу массива (записи в истории)

- [ ] 3) Поле для ввода коментария должно остаться то-же что и было для ответа на замечание, но кнопка отсылки комментария должна быть отдельно с названием "Отправить комментарий" и вызвавать сервис /setServiceMessage с параметром nID_SubjectMessageType = 4, парметром sID_Order и sBody ( https://github.com/e-government-ua/i/issues/1052 ) и после успешной отправки поле нужно отчищать а список загруженных комментариев обновлять.

ВАЖНО:
Тестировать можно/нужно, на тестовой услуге:
https://test.igov.org.ua/service/720/general
для этого подать заявку, с указанием своего электронного адреса
потом зайти на дашбоард (http://test.region.igov.org.ua)
под учеткой: логин: tester , пароль: tester
там в закладке "Необроблени" - взять в работу
перейдя затем в закладку "В работе"
и уже там выбрав ее, справа внизу будет возможность нажать кнопку "внесения замечаний"
после внесения и отправки замечаний - на электронку(указанную в заявке) - вышлется письмо со ссылкой на заявку
перейдя по ссылку - попадем на главный портал, раздел "статус", где отобразится статус заявки и возможность ответить и внести  ответный комментарий

и ТАМ-же должно и появиться новое поле с историей комментариев, и возможностью написать любое количество коментариев

**Comment by bvv4ik** [comment]
Привет, сори что отвлекаю - сможешь сориентировать по временному прогнозу, в отношении таски?

**Comment by glebzhebrakov** [comment]
привет, начинаю делать

**Comment by GrekD** [comment]
коллеги, я извиняюсь, если мои некоторые комментарии будут не по теме, но вот:
1. письмо которое пришло на почту:
Поле / Тип / Поточне значення bankIdsID_Country string Прошу заповнити українською
https://test.igov.org.ua/order/search?sID_Order=0-99228137&sToken=Qs2v36I5HvDMae004jEp
мне как гражданину ничего не понятно что оно означает, мне кажется надо передавать не идшник поля, а его название, и вобще, мне кажется текст этого сообщения надо полностью переделать - описать что конкретно человеку надо сделать:
а)не хватает таких-то данных (тут передаем название поля), мы хотим уточнить (тут коммент чиновника)
а) перейдите по ссылке (ссылка)
б) там внесите то-то
....

2. перешла по ссылке, указанной в письме
статус заявки высвечивается - "тестирование новых полей bankId", т.е. это название услуги, а надо высвечивать (я так понимаю) этап. В данном случае он бы назывался "обробка заяви".
А вобще более правильно было бы высвечивать статус "уточнение данных"
вобщем мне как гражданину опять не понятно ))
нигде не высвечивается что я должна тут сделать, я уже забыла что мне надо исправить из письма  пока перешла, а потом меня отвлекли и т.д.

3. когда внесла комментарий и нажала "залишити коментар" он нигде не появился. Я (как гражданин) не уверена что это куда-то вобще ушло. Потом нажала кнопку "переглянути" - комментарий появился, но он не привязан ни к полю ни к вопросу - удобно было бы передавать на какое поле вносился комменатрий и на какой вопрос.
Затем когда оставляла следующие комментарии они автоматически появлялись в поле - гуд

4. знаю, что это скорее всего не относится к тестируемой задаче - но как чиновник получает уточненный ответ от гражданина? он же не будет заходить и мониторить каждую заявку.
Я видела к примеру по одному из районов 115 заявок на субсидию, которые отрабатывает 1 логин. Что-то мало верится что она будет заходить и периодически мониторить - не пришел ли ответ на 115 уточнений. Будет ли как-то чиновнику передаваться уточненные данные?
Может ли чиновник просматривать комментарии в разделе "статусы" по любой заявке?

**Comment by bvv4ik** [comment]
Для проверки можно авторизоваться на тестовом под тестовым акаунтом и зайти по очереди на эти ссылки:

https://test.igov.org.ua/order/search?sID_Order=0-99450058
- тут покажет историю и даст ввести коммент при авторизованности (без авторизованности - нет, только статус будет виден)

https://test.igov.org.ua/order/search?sID_Order=0-22
- тут всегда будет виден только статус, т.к. это чужая заявка

**Comment by Sokhatsky** [comment]
Після авторизації під тестовим аккаунтом і переходу за посиланням  https://test.igov.org.ua/order/search?sID_Order=0-99450058 з'являється повідомлення про помилку
![pic1_ 1045](https://cloud.githubusercontent.com/assets/16464887/12746938/e8567ce4-c9a9-11e5-9718-9dd41bf61a7a.png)
