### ISSUE TITLE
Доработать сущность Сервиса, для лимитирование одновременной подачи Н-ного числа заявок гражданином по определенной услуге

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1046]
В сущности Service добавляем поле:
nOpenedLimit - число возможных одновременно открытых заявок от гражданина (больше этого числа открытых заявок быть не может)

**Comment by nazarenkod** [comment]
Подскажите сценарий для тестирования

**Comment by bvv4ik** [comment]
закрыть по итогу тестирования услуги:
https://github.com/e-government-ua/i/issues/1048
