### ISSUE TITLE
Реализовать сервис определения числа заявок по определенной услуге в отношении субьекта

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1047]
- [ ] 1) Реализовать на wf-central и назвать getCountOrders
(взять за основу https://github.com/e-government-ua/i/issues/933 )

- [ ] 2) Поля сервиса:
nID_Subject - номер-ИД субьекта 
nID_Service - номер-ИД услуги
sID_UA - строка-ИД места Услуги
nLimit - число-лимит заявок //опциональный, по умолчанию без лимита
bExcludeClosed - булевый, true исключает закрытые из подсчета //опциональный

- [ ] 3) по заданным параметрам:

- [ ] 3.1)  находить в сущности HistoryEvent_Service.csv число записей (по nID_Subject + 
nID_Service + sID_UA), по которым статус не стоит "Закрыта":

- [ ] 3.2) возвращать это число найденных записей заявок, с учетом лимита и критериев, виде объекта {nOpened: 5}

- [ ] 4) Описать сервис и параметры в коментах для автогенерации доки АПИ

**Comment by bvv4ik** [comment]
для теста запрос:
https://test.igov.org.ua/wf/service/services/getCountOrders?nID_Subject=20045&nID_Service=654&sID_UA=1200000000&nLimit=3&bExcludeClosed=true

по лимитам и исключениям можно "поиграться"

**Comment by bvv4ik** [comment]
например:
https://test.igov.org.ua/wf/service/services/getCountOrders?nID_Subject=20045&nID_Service=654&sID_UA=1200000000&bExcludeClosed=true
или:
https://test.igov.org.ua/wf/service/services/getCountOrders?nID_Subject=20045&nID_Service=654&sID_UA=1200000000

**Comment by VadimGulich** [comment]
Протестировано
