### ISSUE TITLE
Реализовать лимитирование одновременной подачи Н-ного числа заявок гражданином по определенной услуге в профиле услуги

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1048]
- [x] 1) Сразу после авторизации (шаг 2), при попытке гражданина подать заявку, проверять число поданных НЕ ЗАКРЫТЫХ заявок проверять через сервис  getCountOrders ( https://github.com/e-government-ua/i/issues/1047 ), передавая туда так-же в качестве параметра nLimit значение параметра nOpenedLimit (из сущности Service  ( https://github.com/e-government-ua/i/issues/1046 ) ), и так-же параметр bExcludeClosed = true
ВАЖНО: если значение nOpenedLimit = 0, то пропускать эту проверку

- [x] 2) Если при этом полученное число в nOpened будет равняться исходному в nLimit, то значит уже лимит достигнут, и больше подавать заявок нельзя.
Соответственно, вместо перехода на форму заполнения услуги, писать уведомление(о запрете):
"Уже достигнуто число одновременно поданных и не закрытых заявок Вами по данной услуге для данного места. Вы можете перейти в закладку "Статусы" (https://test.igov.org.ua/order/search) где найдя одну из своих заявок - написать комментарий сотруднику по ней, для ее скорейшей отработке или закрытия.(чтоб разблокировать дельнейшую подачу)"
(вот задача по этому диалогу: https://github.com/e-government-ua/i/issues/1045 ).

**Comment by maxymshg** [comment]
Взял в работу

**Comment by maxymshg** [comment]
**Изменения:**
* добавлен вызов для получения текущего числа открытых заявок
* на уровне загрузки страницы добавлен блок логики для проверки описаных в задаче условий
* убран дубликат в `package.json`

**Тестирование:**
Проверял локально. Делал разный возврат переменной `allowOrder`, с помощью которой принимается решение о показе диалога с сообщением.

Пул реквест открыт: #1070

**Comment by nazarenkod** [comment]
Подскажите сценарий для тестирования

**Comment by bvv4ik** [comment]
в файле
Service.csv (тестировать на альфе, файл брать в корне а не в подпапках beta или prod)
выбрать услугу
в строчке с ней в поле nOpenedLimit проставить чиссло-лимит... например 2 (закомитить)
и попробовать подать заявку по этой услуге 3 раза

**Comment by msvidran** [comment]
Пробовал - не работает
Действия:
1. Заменил в файле Service.csv в поле nOpenedLimit лимит 2.
2. Подал 4 заявки - все были зарегистрированы.
Проходил на услуге https://test.igov.org.ua/service/1450/general
Подавал от нескольких человек по 4-раза.

**Comment by bvv4ik** [comment]
как выяснилось - длина поля сохранения истории была маленькой, уже поправили
прошу перепроверить (в простом варианте)
должно, вроде работать

**Comment by bvv4ik** [comment]
проверять на бете

**Comment by msvidran** [comment]
Не работает!!! 
проверял на бете https://test-version.igov.org.ua/service/1450/general  
подал заявку 4 раза все 4 раза заявка успешно зарегистрирована. 
Подавал от себя. 
В Service.csv в колонке nOpenedLimit стоит 2
