### ISSUE TITLE
Доработать сущность HistoryEvent_Service и реализовать энум типов для нее

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1050]
- [x] 1) создать в wf-base энум: HistoryEvent_Service_StatusType с элементами 
0 - Created - Заявка подана
1 - Opened - Заявка открыта
2 - Opened_Assigned - Заявка открыта и взята в работу
3 - Opened_RemarkEmployeeQuestion - Заявка открыта и получила замечание работника
4 - Opened_RemarkClientAnswer - Заявка открыта и получила ответ на замечание от клиента
5 - Opened_CommentClient - Заявка открыта и прокомментирована клиентом
6 - Opened_CommentEmployee - Заявка открыта и прокомментирована работником
7 - Opened_Escalation - Заявка открыта и запущена эскалация
8 - Closed - Заявка закрыта
9 - Closed_Rejected - Заявка закрыта и отклонена 
10 - Closed_Rated - Заявка закрыта и оценена
11 - Closed_Feedback - Заявка закрыта с отзывом
12 - Removed - Заявка удалена
13 - Unknown - Заявка в неизвестном статусе

в энуме гетеры
nID - 0
sID - Created
sName_RU - Заявка создана
sName_UA - Заявка створена

- [x] 2) поправить поля сущности HistoryEvent_Service:
- [x] 2.1) добавить в сущности HistoryEvent_Service поле nID_StatusType с дефолтным значением 13 (если не задается явно), и это-же значение сразу проставить во всех записях по дефолту

- [x] 2.2) поле sStatus переименовать в sUserTaskName

- [x] 3) доработать все сервисы и классы работы с сущностью

- [x] 3.1) через сервисы чтоб всегда дополнительно задавался параметр nID_StatusType и обязательно валидировать в сетере этого поля сущности - этот ИД-шник, чтоб он "не выбивался" из списка обозначенных элементов энума.

- [x] 3.1) найти класс RequestProcessingInterceptor, и там обязательно проставлять в трех кейсах - соответственное значение в новом поле  "nID_StatusType"

Для:
- "Заявка подана" (метод: saveNewTaskInfo) - ставить: 0 - Created - Заявка подана
- "* (у роботi)" (метод: saveUpdatedTaskInfo) - ставить: 2 - Opened_Assigned - Заявка открыта и взята в работу
- "Заявка виконана" (метод: saveClosedTaskInfo) - ставить: 8 - Closed - Заявка закрыта

А вместо сохранения там значения в поле "sID_Status" - сохранять его теперь в поле sUserTaskName (переименованное старое название поля sStatus)

ВАЖНО: 
Для:
0 - Created - Заявка подана
8 - Closed - Заявка закрыта
- в поле "sUserTaskName" больше ничего не сохранять (пустую строку или пробел)
А для:
2 - Opened_Assigned - Заявка открыта и взята в работу
- больше не добавлять туда " (у роботi)"

- [x] 4) добавить в сущности HistoryEvent_Service вывод высчитываемого поля:
- sID_StatusType (куда выводить значение sID)
и
- sName_UA_StatusType (куда выводить значение sName_UA)

- [x] 5) написать скрипт в чанджсете, который

- [x] 5.1) исходя из всех значений поля "sID_Status", проставить значения поля "nID_StatusType":
например, при значенниях:
- sID_Status="Заявка подана" => nID_StatusType=0 ("Created")
- sID_Status="Заявка виконана" => nID_StatusType=11 ("Closed")
- sID_Status заканчивается на "(в роботі)" => nID_StatusType=2 ("Opened_Assigned")
- "Запит на уточнення даних"  => 3 - Opened_RemarkEmployeeQuestion
- все остальные оставить дефолтными (т.е. 13 - Unknown)

- [x] 5.2) из всех записей "sID_Status", где встретится, удалить завершающий кусок текста " (у роботi)"

- [x] 5.3) из всех записей "sID_Status", где встретится, отчистить удалить текст записи (оставить пустым поле или один пробел): "Заявка подана", "Заявка виконана", "Запит на уточнення даних"

- [x] 5.4) после чего, все значения поля "sID_Status" - скопировать в поле sUserTaskName (старое название "sStatus") а само поле "sID_Status" удалить из базы и сущности.

**Comment by grigoriy-romanenko** [comment]
вопросы по ТЗ
п.1 : можно положить enum в wf-central?
п.4 : в БД этих полей не должно быть?
п.5 : как можно посмотреть все возможные значения sID_Status?

**Comment by bvv4ik** [comment]
"п.1 : можно положить enum в wf-central?"
нет, они должны быть обязательно, как и написано в задаче: в "wf-base", что быть во всех производных проектах!

**Comment by bvv4ik** [comment]
"п.4 : в БД этих полей не должно быть?"
не должно... в БД только "nID_StatusType", а эти два поля сущности должны по нему формироваться...

**Comment by bvv4ik** [comment]
"п.5 : как можно посмотреть все возможные значения sID_Status?"
Вот данные с тестового (первая колонка - это число записей):
nCount	sID_Status
2107	Заявка виконана
692	Заявка подана
119	<null>
73	надання адміністративної послуги (у роботi)
57	Взяти в роботу (у роботi)
31	Прийняття рішення: доцільність запиту (у роботi)
27	Перевірка наявності обтяжень (у роботi)
24	Візит громадянина (у роботi)
23	Обробка вхідної документації ЦНАПом (1-й крок) (у роботi)
21	Формування пакету документів для ДМС (у роботi)
20	прийняття рішення про надання послуги (у роботi)
20	рішення (у роботi)
20	Перевірка даних (у роботi)
18	Звернення на тему: Реєстрація нового місця проживання (у роботi)
18	new
17	обробка дмс
17	Обробка (у роботi)
17	Запит на уточнення даних
16	повідомлення громадянина про прийняте рішення (у роботi)
16	Обробка волонтером (у роботi)
15	рассмотрение и загрузка (у роботi)
15	Надання послуги: Огляд авто
15	Обробка ЦНАП м.Тернопіль (у роботi)
14	обробка дмс (у роботi)
13	обробка вхідних данних (у роботi)
12	Звернення на тему: Реєстрація нового місця проживання
11	Перевірка документів (у роботi)
11	Прийняття рішення: доцільність запиту
10	перевірка документів (у роботi)
10	Взяти в роботу
10	Перевірка (у роботi)
9	Заява поступає в роботу спеціалісту (у роботi)
8	Перевірка ЦНАП (у роботi)
8	обробка звернення (у роботi)
8	Заявка выполнена
8	Перевірка документів операціоністом (у роботi)
8	Прийняття рішення про надання послуги (у роботi)
7	Обробка після засвідчення її справжності (2-й крок) (у роботi)
6	Перевірка вхідних даних (у роботi)
6	Надання послуги: Огляд авто (у роботi)
6	рассмотрение и загрузка
6	ЕТАП I --- Перевірка даних і запрошення заявника (у роботi)
6	Підготовка відповіді після рішення Реєстраційної служби міського управління юстиції  (2-й крок) (у роботi)
6	Відповідь поступає до ЦНАП
6	Результат послуги (у роботi)
5	перевірка та пересилання документів (у роботi)
5	Надання послуги (у роботi)
5	Результат обробки (у роботi)
5	обработка этап 1 (у роботi)
5	Формування опису або відмова при неправильних документах (у роботi)
5	опрацювання звернення (у роботi)
5	Обробка документації після візиту комісії (у роботi)
5	Підготовка відповіді після рішення Управління інфраструктури (у роботi)
4	Опрацювання заявки (у роботi)
4	setTaskQuestions
4	перевірка  документів (у роботi)
4	Підготовка відповіді на запит: пошук документа
4	Обробка Тростянецьким МВК (у роботi)
4	Перевірка заявлених вимог в базі даних (1-й крок) (у роботi)
3	обробка заявки (у роботi)
3	Заявка была удалена (kermit): Test
3	Заява поступає в роботу операціоніста
3	Проверка почтой (у роботi)
3	Обробка заяви у РА на вихід Комісії (у роботi)
3	На розгляді комісії (у роботi)
3	Формування пакету документів в ЦНАП (у роботi)
3	Status
3	
3	Реєстрація звернення, результат обробки вхідних данних (у роботi)
3	Обробка після повернення документів від Управління архітектури, капітального будівництва та житлово-комунального господарства (2-й крок) (у роботi)
3	новая заявка
3	Заява поступає до ЦНАП (у роботi)
3	Обробка Управлінням (1 етап) (у роботi)
3	Взяття в роботу ЦНАП (у роботi)
3	Підготовка та завіряння документу (у роботi)
3	Принятие решения (у роботi)
3	Заява поступає в роботу комісії (у роботi)
3	Відповідь на запит по уточненню даних
3	Отримання рішення від спеціаліста (у роботi)
2	обробка кузнецовським мвк (у роботi)
2	Обробка Дніпродзержинським ЦНАП (1-й крок) (у роботi)
2	Перевірка відповідності документів (у роботi)
2	Перевірка документів для відправлення опису кліенту (у роботi)
2	Перевірка документів в Управлінні праці та соціального захисту населення (2-й крок) (у роботi)
2	Підготовка відповіді після рішення Відділу землекористування (2-й крок) (у роботi)
2	Обробка Тернопільським ЦНАП (1-й крок) (у роботi)
2	setTaskAnswer
2	Обробка після повернення документів від департаменту комунального господарства та капітального будівництва Дніпропетровської міської ради (2-й крок) (у роботi)
2	перевірка вхідних данних (у роботi)
2	надання адміністративної послуги
2	Підтвердження отримання ЦНАПом оригіналу довідки (у роботi)
2	Формування пакету документів в ЦНАП
2	прийняте рішення (у роботi)
2	Формування опису або відмова при неправильних документах Юр особа (у роботi)
2	Розгляд документів і прийняття рішення про опрацювання
2	Опрацювання звернення (у роботi)
2	Візит громадянина
2	Підтвердження видачі документів ЦНАПом заявнику (у роботi)
2	Перевірка пакету документів в РДА (у роботi)
2	Перевірка документів для опису (у роботi)
2	перевірка вхідних данних, прийняття рішення про надання послуги (у роботi)
2	обробка укрпоштою (у роботi)
2	Підтвердження отримання ЦНАПом документів від ДМС (у роботi)
2	Заява поступає в роботу операціоніста (у роботi)
2	Результати розгляду (у роботi)
2	заявка в обработке
2	Перевірка наданих документів
1	Підготовка відповіді на запит: підготовка витягу (у роботi)
1	новая заявка2
1	прийняте рішення
1	Прийняття рішення про надання послуги (1) (у роботi)
1	[Етап II] Отримання підписей від організацій + додаткові документи
1	Опрацювання документів комісією (у роботi)
1	Обробка профільним відділом (у роботi)
1	заявка в обработке 6
1	test
1	e
1	Підготовка відповіді на запит: пошук документа (у роботi)
1	Відповідь поступає до ЦНАП (у роботi)
1	User Task (у роботi)
1	Внесення до ЄДР запису про зміну відомостей (у роботi)
1	Підготовка відповіді після рішення Відділу землекористування (2-й крок)
1	Обробка відповіді (у роботi)
1	Обробка ЦНАП Дніпропетровськ (у роботi)
1	На розгляді комісії
1	ЕТАП III --- Отримання ЦНАПом документів від ДМС (у роботi)
1	Підготовка листа громадянину (у роботi)
1	Прийняття рішення про оформлення ліцензії
1	Перевірка даних службою (у роботi)
1	Обробка Управлінням (2 етап) (у роботi)
1	Надання довідки громадянину (у роботi)
1	Обробка ЦНАП Вільногірськ (1-й крок) (у роботi)
1	Підготовка відповіді після рішення УМАК (у роботi)
1	Заявка была удалена
1	заявка в обработке 8
1	обробка кузнецовським мвк
1	обработка этап 2
1	Підготовка відповіді (у роботi)
1	Перевірка Укрпоштою (у роботi)
1	обработка этап 2 (у роботi)
1	Перша перевірка документів в Управлінні праці та соціального захисту населення (у роботi)
1	заявка в обработке 5
1	Підготовка відповіді після рішення держсанепідслужби (2-й крок) (у роботi)
1	очікування відповіді (у роботi)
1	Підготовка відповіді на запит (у роботi)
1	Обробка ЦНАП Ужгород (1-й крок) (у роботi)
1	Перевірка Укрпоштий (у роботi)
1	прийняття рішення про надання послуги
1	Проверка документов (у роботi)
1	заявка в обработке 7
1	перевірка пакету документів, реєстрація заяви, прийняття рішення про надання послуги (у роботi)
1	Перевірка документів в Управлінні праці та соціального захисту населення (1-й крок) (у роботi)

По сути, нужно проставить только по первым двум пунктам, а для всех остальных проставить: 2 - Opened_Assigned - Заявка открыта и взята в работу

ВАЖНО:
в п.3 так-же найти класс RequestProcessingInterceptor, и там обязательно проставлять в трех кейсах - соответственное значение в новом поле  "nID_StatusType"

Для:
"Заявка подана" (метод: saveNewTaskInfo)
0 - Created - Заявка подана

"* (у роботi)" (метод: saveUpdatedTaskInfo)
2 - Opened_Assigned - Заявка открыта и взята в работу

"Заявка виконана" (метод: saveClosedTaskInfo)
8 - Closed - Заявка закрыта

А вместо сохранения там значения в поле "sID_Status" - сохранять его теперь в поле sUserTaskName (переименованное старое название поля sStatus)

(все это дописал в задаче)

Для всех остальных проставлений статусов - будет отдельная задача:
1 - Opened - Заявка открыта
3 - Opened_RemarkEmployeeQuestion - Заявка открыта и получила замечание работника
4 - Opened_RemarkClientAnswer - Заявка открыта и получила ответ на замечание от клиента
5 - Opened_CommentClient - Заявка открыта и прокомментирована клиентом
6 - Opened_CommentEmployee - Заявка открыта и прокомментирована работником
7 - Opened_Escalation - Заявка открыта и запущена эскалация
9 - Closed_Rejected - Заявка закрыта и отклонена 
10 - Closed_Rated - Заявка закрыта и оценена
11 - Closed_Feedback - Заявка закрыта с отзывом
12 - Removed - Заявка удалена
13 - Unknown - Заявка в неизвестном статусе

**Comment by grigoriy-romanenko** [comment]
@bvv4ik 
готово,
но сделайте, пожалуйста, ревью кода
я в test пока не делал push, оно в ветке #1050

**Comment by bvv4ik** [comment]
ой, только заметил коммент... надо было таки в ветку слить, т.к. сейчас произошли колосальные изменения структуры пэкэджей и классов проектов, и смержить это все в тест - может стать нереальный...

прошу сохранить себе локально копию проекта с разработкой, потом вытянуть проект из тест и потом аккуратненько наложив смою реализацию закомитить и запушить...

разве что пока закоментить только тот участок кода(например чанджсетов), который производит необратимые изменения в базе...

и после деплоя лишь убедиться что сервак не упал, и тогда поставить лейбл тест на эту ишью, чтоб коллеги могли начать тестировать... ну и я тогда подключусь

**Comment by bvv4ik** [comment]
блин, глянул на ту ветку... беда, почти вся работа "в пусттую"...
это теперь не получится смержить... придется как я и описал выше - ручками переносить построчно...

вроде уже "на всех перекрестках пишу - не пытаться создавать свои отдельные ветки, тем более не оставлять их на значительный промежуток времени без контроля... почему0то всеравно народ продолжает их юзать(

когда у тебя получится перенести код в новые структуры?

**Comment by bvv4ik** [comment]
вообщем, решил не откладывать и не перекладывать эту рутину на тебя, а сам взялся, и построчно все перенес.... заодно и проштудировал код, и кое-что даже докрутил)

**Comment by bvv4ik** [comment]
но в будущем, прошу, старайся не серез отдельную ветку, а через тестовую, периодически делая пул, чтоб актуальностьи совместимость не терялась...
а потом, максимально обезопасившись от необратимых действий - выливай и жди завершения деплоя, чтоб убедиться что ничего не упало, и ставь лейбл тест

за таску - огромное спасибо!
