### ISSUE TITLE
Избавиться от дублирующего использования полей nID_Server + nID_Protected во всех сервисах и методах, где уже есть sID_Order

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1051]
Везде заюзать комплексный параметр sID_Order
(в generalConfig есть соответствующий метод, и туда-же добавить вспомогательные, если понадобятся, например, для валидации sID_Order, подстановке в него префикса(если его нет) и сверки контрольной суммы по алгоритму Луна)

На РЕГИОНАЛЬНЫХ сервисах фактически сохранить на входе nID_Protected, НО единственным ключевым параметром сервиса, и под названием nID_Order

**Comment by LamronNu** [comment]
[12 января 2016 г. 23:26] Olga: 

<<<  там в основном, насколько я помню, ещё "пробегает" 4-й параметр, нИд-процесс. Если убирать нИд-протектед и нИд-сервер, то нужно и нИд-процесс тоже удалять...Olga, Вчорашні 23:26
да, везде все это убираем, оставляем только sID_Order, кроме:

/messages/setMessageRate, который именно в DebugCentralController
(это старая копия, чтоб поотрабатывали созданные ранее заявки)

а вот в SubjectMessageController я уже убрал этот параметр из /setMessageRate
в то время как: в /cancelTask (который в ActionTaskCommonController) и в /getTasksByOrder
- заменил на nID_Order (это как-бы тот-же nID_Protected)

ну где будут сомнения - лучше переспросите лишний раз)

[3:31:51] Igov. Belyavtsev Vladimir Vladimirovich (dn310780bvv): вообщим немножко поправил таску (последний уточняющий пункт)
[3:32:53] Igov. Belyavtsev Vladimir Vladimirovich (dn310780bvv): и залил правки на клиенте и сервисах (сразу поубирал ненужные параметры)
так что гляните комит и с учетом того что \ выше написал, думаю станет меньше вопросов

**Comment by LamronNu** [comment]
Список рест-сервисов, где ранее использовалось 4 параметра (sID_Order, nID_Protected, nID_Server и nID_Process), а сейчас остался лишь sID_Order:
центральный сервер (wf-central), урл *test.igov.org.ua/wf/service/*
**sID_Order**

№ | service| Note
----|------------- | -------------
   | **ActionEventController**| 
 1 | /action/event/getHistoryEvent_Service | +
 2 | /action/event/updateHistoryEvent_Service | +
  | **ActionTaskCentralController** |   
3 | /action/task/setTaskAnswer_Central | +
 | **SubjectMessageController** |  
4 | /subject/message/setMessageFeedback_Indirectly | есть только два параметра: nID_Protected и nID_Server, ничего не менялось
5| setMessageRate | уже было все ок, только sID_Order

региональный сервер (wf-base), урл *test.region.igov.org.ua/wf/service/*
**nID_Order**

№ | service| Note
----|------------- | -------------
 | **ActionTaskCommonController** |  
6 | /action/task/setTaskAnswer |
7 | /action/task/setTaskQuestions | nID_Server подставлять "текущий"? 
 | **DebugCentralController**| 
8 | /messages/setMessageRate | сейчас там имя параметра осталось nID_Protected -- менять на nID_Order ?

**Comment by LamronNu** [comment]
1e6492b5668a6789e29f8acd99e6fde53745c197
