### ISSUE TITLE
создать сервис отправки сообщения клиента по заявке

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1052]
1) Назвать setServiceMessage

2) параметры:
sID_Order
sBody
nID_SubjectMessageType

3) в ответ, если все гуд то статус 200 и объект с сообщением

**Comment by smit-pb** [comment]
На "фронте" пока нет возможности проверить.

**Comment by LamronNu** [comment]
@smit-pb , можно проверить задачу через рест-сервисы.
постМеном кинуть пост-запрос с нужными параметрами: https://test.igov.org.ua/wf/service/subject/message/setServiceMessage

а потом проверить, создалось ли сообщение, найдя его в списке по sID_Order
https://test.igov.org.ua/wf/service/subject/message/getServiceMessages?sID_Order=

описание еще можно посмотреть в авто-документации (в спецификации есть ссылки), раздел "SubjectMessageController : Сообщения субьектов", метод setServiceMessage.

**Comment by smit-pb** [comment]
С точки зрения сервиса - вроде как , вопросов нет.
а вот с точки зрения привязки к фронту вопросы есть.
Тем более при связки с задачей "В закладке статусы, при авторизованности, и выбранной заявке (принадлежащей авторизованному) - отображать список истории мессаджей заявки и давать возможность оставлять комментарии. #1045"
