### ISSUE TITLE
Доработать сущность SubjectHuman в связке с SubjectContact и соответствующие сервисы по сообщениям

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1053]
- [x] 1) в сущности SubjectContact добавить поле sDate с типом "дата", и автопроставлением его при создании записи и любом апдейте ее. (если авто-обновление невозможно, то реализовать это в соответствующих методах сущности)

- [x] 2) в дополнение к полю sMail сущности SubjectMessage, добавить опциональное поле nID_SubjectContact_Mail, по которому подвязывать записи в сущности SubjectContact

- [x] 3) При каждом новом добавлении записи в сущность SubjectMessage, и наличии электронного адреса (поле sMail)
- [x] 3.1) при отсутствии nID_Subject, используя внутренний механизм сервиса /syncSubject:
 - синхронизировать пользователя (через идентификатор sCode_Subject, в виде sMail, и соответствующий тип nID_SubjectHumanIdType, для почты), и полученный его nID_Subject прописывать в соответствующее поле SubjectMessage и SubjectContact.
- [x] 3.2) при наличии nID_Subject, получить по нему объект Subject и SubjectHuman, а к нему:
- если не привязано ни одного контакта: подвязывать новую запись SubjectContact (с соотв.типом, значением из sMail и nID_Subject), и сделать ее дефолтной через поле nID_SubjectContact_DefaultEmail, сущности SubjectHuman.
- если есть привязанные контакты, но такого адреса там нет: подвязывать новую запись SubjectContact (с соотв.типом и значением из sMail и nID_Subject), и сделать ее дефолтной через поле nID_SubjectContact_DefaultEmail, сущности SubjectHuman.
- если такая запись уже есть: просто обновить в сущности SubjectContact значение в поле sDate на текущую,
- [x] 3.3) после отработки механизма п.3.2, в поле nID_SubjectContact_Mail, сущности SubjectMessage записывать nID этой записи, сущности SubjectContact.

ВАЖНО:
- сразу вынести механизм п.3.1 и п.3.2 в отдельный метод, для дальнейшего использования из других участков кода.
- электронный адрес, после реализации нового механизма хранения не дублировать в поле "sMail"

- [x] 4) Доработать сущность SubjectMessage так, чтоб при ее отдаче, поле sMail формировалось и отдавалось именно через подвязанную структуру Subject - SubjectContact (а не бралось из сохраненного поля в базе)

- [x] 5) Написать сервис, который позволит уже сохраненные данные в поле sMail, сущности SubjectMessage перевести во вновь подвязанную структуру. (и каждое перенесенное значение потом отчищать в исходном поле sMail сущности SubjectMessage)

- [x] 6) ТОЛЬКО после полного переноса всех данных по п.5 - через чанджсет удалить поле sMail из сущности SubjectMessage

**Comment by bvv4ik** [comment]
удалось изучить таску? может есть вопросы?

**Comment by lesha1980** [comment]
удалось изучить таску? может есть вопросы?

Часть понятна, но вопросы будут. Просто пока стараюсь самостоятельно справиться...

В пункте 3.1. необходимо прописывать найденный nID_Subject в SubjectMessage и SubjectContact. По сути, я нахожу список SubjectContact. В каждом из этих контактов, связанных с определенным субъектом я прописываю nID_Subject. Или это необходимо делать только для контакта с Email?

Кроме того, если nID_Subject нет, а есть sMail, но этот почтовый адрес не связан с конкретным субъектом (его нет в базе), соответственно нельзя определить nID_Subject, тогда правомерно ли мне в качестве исключения выдавать ошибкой неавторизованного пользователя?

**Comment by lesha1980** [comment]
Подскажите по пункту 5. Чанджсетом здесь возможно вообще справиться или необходимо писать сервис? Так как попытался простой апдейт данных сделать через такую запись например:

![default](https://cloud.githubusercontent.com/assets/12561441/12091243/4fe8a8d6-b2fe-11e5-9bfe-970ade72dac8.jpg)

но ничего не выходит. Данные не применяются, очевидно, по той причине, что апдейтить собственно нечего, ведь подгрузка данных осуществляется в последнюю очередь из csv. Потому и sql-запрос не удастся для в чанджсете, так как база то еще пустая. В общем второй день голову себе морочу этой забавой. 

Однако если написать сервис  для переноса данных из sMail в nID_SubjectContact_Mail на java для MessageSubject. Тогда возникает вопрос. А как применить данный сервис? Ведь чанджсет с удалением колонки sMail следует делать после полного переноса данных — после применения сервиса.

**Comment by lesha1980** [comment]
А что такое? С ветки "Тест" клонируется обновленный проект, который собрать невозможно.

**Comment by lesha1980** [comment]
В текущем проекте потеряны зависимости на storage-static и storeg-temp для wf-base и storeg-static для wf-central.

**Comment by lesha1980** [comment]
После удаления поля sMail из таблицы проект ругается, что не может обнаружить поле sMail при подготовке запроса.

**Comment by RoOmel** [comment]
Прошу добавить сценарий для тестирования.

**Comment by lesha1980** [comment]
Хорошо, попробую. Только я думал, что сценарии — дело тестировщика...

**Comment by RoOmel** [comment]
По сути я выполняю тестирование Blackbox, т.е. нет кода, нет документации о модулях и структуре подукта, нет спека.
Чтобы тестировать любой модуль/функцию мне нужно знать требования, которым должен соответствовать ожидаемый результат выполнения модуля/функции.
В данном конкретном случае, что делает фнукция я могу только догадываться из постановки задачи девам.
Выдать необходимую мне инфу - это дело бизнес-аналитиков, продакт-менеджеров и девов.
После получения  и анализа инфы тестер (QA/QC) пишет тестовый сценарий, тест-кейсы и по результату - отчёт и заводит баги/фичи/патчи.

**Comment by lesha1980** [comment]
Добавил ряд сценариев тестов в файл SubjectMessageControllerScenario.

**Comment by RoOmel** [comment]
А где этот файл SubjectMessageControllerScenario я могу найти?

**Comment by lesha1980** [comment]
Вот. https://github.com/e-government-ua/i/blob/test/wf-central/src/test/java/org/igov/service/controller/SubjectMessageControllerScenario.java
