### ISSUE TITLE
При использовании сервиса /setDocumentAccessLink сохранять так-же электронный адрес и телефон субъекта в новую сущность SubjectContact, с соответствующей связкой

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1054]
- Используя механизм п.3.1 и п.3.2, таски: https://github.com/e-government-ua/i/issues/1053
- При этом само поле с электронкой и телефоном в сущности DocumentAccess - сохранить, как и сейчас.

**Comment by bvv4ik** [comment]
Привет,
тут только добавил последнюю таску из этой серии задач:
https://github.com/e-government-ua/i/issues/1116

как будет время/возможность - глянь плиз

**Comment by RoOmel** [comment]
Прошу указать ссылку на описание сервиса или сценарий тестирования

**Comment by lesha1980** [comment]
Здесь тестирование немного сложней, чем может показаться на первый взгляд. 

1. Тестировать нужно сразу несколько тасок: #1053, #1054, #1116, #1145, а также по отдельности каждую из них. Эти таски связанные и должны работать одинаково: в смысле, одинаково синхронизировать субъекта, сохраняя его контакты в базе данных, хотя реализованы они немного по-разному.  
2. Несмотря на то, что #1053 закрыта, но в нее вносятся изменения и, думаю, еще будут изменения, как и в выше перечисленные таски, так как, думается, что появится еще одна таска, позволяющая сохранять контакты по ФИО пользователя. В связи с этой таской придется еще вносить изменения сразу во все выше перечисленные таски.
3. Я здесь поставил лейблу тест, чтобы просто протестировать работу данной таски, но на другие таски такого лейбла не ставил в ожидании вынесения "приговора" по таске с сохранением контактов по ФИО.
4. Здесь не создавался новый сервис. Использовать нужно уже существующий setDocumentLink с минимальными параметрами: обязательным nID_Subject и с электронкой или же с номером телефона.
5. Для получения результата нужно смотреть логги Томката, так как написанный метод не возвращает результата, но осуществляет синхронизацию контактов. Если есть возможность посмотреть записываемые данные в SubjectContact и SubjectHuman, то это было бы хорошо...
6. Очевидно, что привычный вариант для вас обычного теста созданного сервиса здесь не подойдет. Тут надо "изворачиваться".

**Comment by lesha1980** [comment]
Здесь вот вам нужный сервис, но его описание ничего не даст вам... 
https://jenkins-new.igov.org.ua/job/central_alpha/ws/wf-central/target/generated-docs/central-igov.html#_documentaccesscontroller
