### ISSUE TITLE
Заменить вывод ошибок с блока "div" на модальный "диалог"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1056]
т.е. с:
![image](https://cloud.githubusercontent.com/assets/4208821/12025178/a7ac0620-adb4-11e5-8f8b-3ccbebb4144c.png)

на:
![image](https://cloud.githubusercontent.com/assets/4208821/12025125/15407d20-adb4-11e5-8996-a5e7a5585df1.png)

**Comment by iRipVanWinkle** [comment]
Задачу выполнил. Можно проверять.

**Comment by bvv4ik** [comment]
![image](https://cloud.githubusercontent.com/assets/4208821/12293589/40fe43c0-b9fd-11e5-93fd-0932fd3d030a.png)

таки работает)

**Comment by bvv4ik** [comment]
вот сам комит, для истории:
https://github.com/e-government-ua/i/commit/7b18f8541594b40b11f6fdf06e399e61e5560bed

**Comment by bvv4ik** [comment]
сам проверил - все работает
