### ISSUE TITLE
Видео - вступление!

### ISSUE THREAD

**Issue by anatooly** [e-government-ua/i#1057]
https://github.com/e-government-ua/i/wiki/%D0%AF%D0%BA-%D0%BF%D0%BE%D1%87%D0%B0%D1%82%D0%B8-%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D1%83

Ссылка на видео неработает.

https://pbank.webex.com/pbank-ru/ldr.php?RCID=8cdd26659085938889cae387d69ffd65

**Comment by bvv4ik** [comment]
работает, нужно просто что был плагин ВебЕкс-а
