### ISSUE TITLE
Реализовать отображение возможности быть референтом только для админа

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1058]
добавить ИНН Забрудского в админы

**Comment by Sokhatsky** [comment]
Как iGov найти данную доработку(задачу)?

**Comment by VadimGulich** [comment]
Зайти под своим логином - проверить нет ли реф.
Чистить КЭШ 
Зайти под тестовым акк +380102030405 /value/123456  проверить что есть реф.

**Comment by Sokhatsky** [comment]
Реалізується можливість бути референтом під особистим логіном для послуги https://test.igov.org.ua/service/729/general
![pic1_ 1058](https://cloud.githubusercontent.com/assets/16464887/12241527/56f46400-b89c-11e5-9f48-b8d0bc83ece7.png)

**Comment by nazarenkod** [comment]
Реализовано
