### ISSUE TITLE
Вынести ядро в wf-base, и отнаследоваться от него в репозитории Рад (вначале Днепрорады)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#106]
-скопировать вначале папку wf-dniprorada в wf-base, в рамках репозитория "i".
-потом вынести из wf-base все конфигурационные и настроечные файлы в репозиторий Dneprorad-ы.
-Написать POM проекта wf-base, для компиляции его в jar и сохранения в Nexus
-Написать POM проекта репозитория Dneprorad-ы, использовав jar - wf-base, и прописав в assembly копирование веб-контента АктивитиЭксплорера (передавая например его через архив из jar-ника)

**Comment by bvv4ik** [comment]
Так а разве в репозитории _Dnipropetrovsk_MVK уже заработала отнаследованная версия?

**Comment by admiral-diver** [comment]
Сделали только пример, рядом с wf-base. Нужно переоткрыть. В Днепр зальем в ближайшее время.

**Comment by bvv4ik** [comment]
все готово
