### ISSUE TITLE
Включить все выключенные при последнем глобальном рефакторинге - тесты

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1061]
Добиться чтоб тесты работали, и закоммитить их в ветку включенными!
(были временно выключены, т.к. перестали работать после последнего рефакторинга)

ВАЖНО: Обязательно вначале убедиться чтолокально все работает, собирается, проходят тесты, и поднимается приложение (собирая все начиная от wf-base, и заканчивая wf-central & wf-region)

- [x] 1) в классе SubjectHumanDaoTest (wf-central)
4*теста

- [x] 2) в классе EntityDaoQueriesTest (wf-central)
1*тест:
shouldFindAllDaoAndExecuteEachQueryMethod

- [x] 3) в классе Abstract_MailTaskCustomTest (wf-base)
1*тест:

**Comment by bvv4ik** [comment]
похоже нашел решение)
прошу пока не комитить правки, если они есть, как пролью - отпишусь...

**Comment by bvv4ik** [comment]
таки получилось)
https://github.com/e-government-ua/i/commit/571481f1d12acb55a81b0fff659f16735113383d

помогла конструкция типа:
    <aop:config>
        <aop:pointcut id="service.business" expression="execution(* org.igov.service.business.*.*.*(..))"/>
        <aop:advisor pointcut-ref="service.business" advice-ref="txAdvice"/>
    </aop:config>
    <aop:config>
        <aop:pointcut id="igov.model" expression="execution(* org.igov.model.*.*.*(..))"/>
        <aop:advisor pointcut-ref="igov.model" advice-ref="txAdvice"/>
    </aop:config>
    <aop:config>
        <aop:pointcut id="service.business2" expression="execution(* org.igov.service.business.*.*.*.*(..))"/>
        <aop:advisor pointcut-ref="service.business2" advice-ref="txAdvice"/>
    </aop:config>
    <aop:config>
        <aop:pointcut id="igov.model2" expression="execution(* org.igov.model.*.*.*.*(..))"/>
        <aop:advisor pointcut-ref="igov.model2" advice-ref="txAdvice"/>
    </aop:config>

**Comment by bvv4ik** [comment]
если есть немного времени, прошу помочь в: https://github.com/e-government-ua/i/issues/1075
это конечно не так интересно, понимаю, но зато получится хорошо обозреть весть проект....

**Comment by ilns** [comment]
Спасибо Вам за то что выполнили задание быстрее) 
Конечно возьмусь за следующие задание
