### ISSUE TITLE
"разнести" из пэкэджа org.igov.model классы

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1062]
"разнести" из пэкэджа org.igov.model классы:
(и обязательно это уесть в проперти логера)

- [ ] 1) в проекте: wf-central

- [ ] 1.1) с масками:
Document*
AccessURL
AbstractDocumentAccessHandler
в пэкэдж: org.igov.model.document

- [ ] 1.2) с масками:
Subject*
Server*
ServiceOperator_SubjectOrgan*
Merchant*
в пэкэдж: org.igov.model.subject

- [ ] 1.3) с масками:
Place*
Object*
Region
Currency*
Country*
City
в пэкэдж: org.igov.model.object

- [ ] 1.4) с масками:
Subcategory
ServiceType
ServiceData
Service
Subcategory
Category
History*
в пэкэдж: org.igov.model.action

- [ ] 2) в проекте: wf-base

- [ ] 2.1) с масками:
Access*
в пэкэдж: org.igov.model.access

ВАЖНО:
1) Пользоваться штатной функцией рефакторинга(переноса классов) самой IDE
2) После переноса перепроверять вручную
3) Переносить по одному пункту, убеждаясь что после переноса все точно продолжило локально работать, собираться и подниматься... (ранее ломались тесты)
4) Только полность собирая все начиная от wf-base, и заканчивая wf-central & wf-region - убеждаться что все нормально работает и тогда уже комитить и выливать в ветку тест.

**Comment by RoOmel** [comment]
Прошу добавить сценарий для тестирования.

**Comment by bvv4ik** [comment]
реализовано
