### ISSUE TITLE
Описать в вики назначение каждого из новых отдельных лог-файлов (после их разделения)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1064]
на вики дописать ссылку на файл .в котором ,в рамках проекта, описаны все инструкции по логированию в эти файлы:
https://github.com/e-government-ua/i/blob/test/wf-base/src/main/webapp/WEB-INF/log4j.properties

А в самом файле перед каждым блоком через знак решетки описать назначение раздела-файла

Краткие описания:

- вот тут все входящие запросы ко всем нашим сервисам, с параметрами, и ответы на них:
Service_Interceptor.log
- но "боди запросов" и "сонтент-ответы" лимитируются 200-тами символами (чтоб не загромождать лог), а полные версии ответов сливаются сюда:
LogBig_In.log

- Вот тут пишутся те логи, что фигурируют в самих сервисах/методах контроллерах:
Service_Controller.log

**Comment by bvv4ik** [comment]
ссылка добавлена к блоку с описаниями ФТП-логов:
https://github.com/e-government-ua/i/wiki/%D0%9D%D0%B0%D1%88%D0%B5-%D1%85%D0%BE%D0%B7%D1%8F%D0%B9%D1%81%D1%82%D0%B2%D0%BE

**Comment by nazarenkod** [comment]
Добавте,плиз,  сценарий для тестов

**Comment by bvv4ik** [comment]
реализовано
