### ISSUE TITLE
Перевести все логирование с log4j на slf4j

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1065]

**Comment by bvv4ik** [comment]
[18:50:03] (ext. 6703) Yurii Dubynka: вопрос №1
https://wiki.opendaylight.org/view/BestPractices/Logging_Best_Practices
[18:52:32] (ext. 6703) Yurii Dubynka: вопрос №2
https://github.com/dgroup/Swamp/blob/master/Swamp-parent/src/main/resources/logback.xml
Можно логеры конфигурировать как душе угодно

**Comment by VadimGulich** [comment]
https://github.com/e-government-ua/i/search?p=6&q=slf4j&type=Code&utf8=%E2%9C%93

По идее добавлено, полной проверкой будет получение/просмотр логов
