### ISSUE TITLE
Создать в backend-части центрального портала (e-gov.ua) сервисы работы с мерчантами.

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#107]
API:
getMerchant - получить объект с одним мерчантом.
Параметры:
sID_Owner //ОКПО организации/хозяина
или
sID //ИД самого мерчанта

setMerchant - установить объект с одним мерчантом.(если нету то создаст, если есть то апдейтит)
Параметры:
sID_Owner //ОКПО организации/хозяина
sOwnerName:”КМДА” //Название хозяина
sID //ИД самого мерчанта

removeMerchant - удалить объект с одним мерчантом.
Параметры:
sID_Owner //ОКПО организации/хозяина
или
sID //ИД самого мерчанта

getMerchants - получить массив объектов с мерчантами

Обьект связки мерчанта и субьекта:
{
sID_Owner:”6749324” //ОКПО организации/хозяина
sOwnerName:”КМДА” //Название хозяина
,sID:”jh45kl3h6ol546h43ihu” //ИД самого мерчанта
}

**Comment by bvv4ik** [comment]
готово, давно уже на central-js
