### ISSUE TITLE
Неможливо замовити послугу Надання довідки про відсутність (наявність) судимості або обмежень, передбачених кримінально-процесуальним законодавством (терміново). 

### ISSUE THREAD

**Issue by Sokhatsky** [e-government-ua/i#1073]

**Comment by Sokhatsky** [comment]
Серйозність помилки: [S2] 
Оточення: Windows 7 service pack 1, Mozilla Firefox версия 43.0.1
Детальний опис помилки: Помилка проявляється при замовлені послуги при заповнені з референтом і без. Файл потрібно добавлять обов’язково (воно є обов’язковим для замовлення послуги). Особливість якщо заходиш за власним логіном не Дубілет то чекбокс «референт» не існує. 
Кроки відтворення.
1. Зайти на сайт https://test.igov.org.ua/
2. Вибрати послугу Надання довідки про відсутність (наявність) судимості або обмежень, передбачених кримінально-процесуальним законодавством (терміново)
3. Успішно пройти крок 1 (вибрати область – Дніпропетровська)
4. Успішно пройти Крок 2. Увійдіть в систему через BankID (приват 24)
5. Заповнити всі необхідні поля 
6. Натиснути кнопку замовити послугу
7. Фактичний результат Помилка
Очікуваний результат: Послуга успішно замовлена
![1](https://cloud.githubusercontent.com/assets/16464887/12216764/7a8e2368-b6f5-11e5-8bff-45ea4c36b17b.png)

**Comment by Sokhatsky** [comment]
https://github.com/e-government-ua/i/issues/888

**Comment by bvv4ik** [comment]
функция референта на боевом включаться будет только для адмиистраторов (с определенными ИНН), а на тестовом в т.ч.  и для тестового логина... но спасибо за инфу - посмотрим что не так
там была только проблема с атачментами

**Comment by bvv4ik** [comment]
@kurbpa 
Павел, глянь плиз

**Comment by Sokhatsky** [comment]
Послуга працює
