### ISSUE TITLE
Написать тесты, по образу и подобию ControllerDeleteProcessScenario для всех оставшихся сервисов в контроллерах

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1077]
ВАЖНО:

Прежде чем начинать реализацию тестов - составить приблизительный список тех сервисов, на которые тесты еще не написано (чтоб была возможность откорректировать этот список, убрав те ,которые уже не столь актуальные)

**Comment by D-Zhuravlyov** [comment]
## wf-base:

Class | Test Class
------------ | -------------
 | ActivitiScenarioBase
AccessCommonController  |  AccessCommonControllerScenario, AccessCommonLoginControllerScenario, AccessCommonLogoutControllerScenario
ActionFlowController | ActionFlowControllerScenario
ActionTaskCommonController | ControllerDeleteProcessScenario, ControllerDownloadTasksDataScenario (fully commented test), ControllerDownloadTimingScenario, ControllerTasksScenario, ControllerStartProcessScenario, ProcessDefinitionsScenario
ObjectFileCommonController | ControllerFileUploadScenario
 | IntegrationTestsFixtures, IntegrationTestsApplicationConfiguration

## wf-central

Class | Test Class
------------ | -------------
AccessCentralController |  -
ActionEventController | -
ActionItemController | ActionItemControllerScenario
ActionTaskCentralController | -
DebugCentralController | -
DocumentAccessController | -
DocumentController | DocumentControllerTest
FinanceCentralController | FinanceCentralMerchantControllerScenario
ObjectController | ObjectCustomsControllerTest
ObjectPlaceController | ObjectPlaceControllerTest
SubjectController | SubjectServerControllerScenario
SubjectMessageController | SubjectMessageControllerScenario
