### ISSUE TITLE
Добавить в сущность Merchant и Currency - поля sID_Currency, где разместить международный строковой, трехсимвольный код валюты

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1079]
- например: UAH
- для сущности Currency - сделать это поле уникальным

**Comment by grigoriy-romanenko** [comment]
коды валют можно взять тут: http://search.ligazakon.ua/l_doc2.nsf/link1/FIN14565.html

**Comment by grigoriy-romanenko** [comment]
еще наверное нужно будет добавить поддержку этого поля в соответствующие сервисы

**Comment by SergeiShemshur** [comment]
Начал делать вот составил check list( https://docs.google.com/document/d/1wBcVJmS9BE9v6DglA2BlsTcizCAOjP2z-dO5Uexok5E/edit?usp=sharing ). Прошу посмотреть на коректность и порядок выполнения работ.

**Comment by LamronNu** [comment]
> Заменить  сhange set в .../local_2015.xml 

ченджсеты нужно не заменять/менять и т.п. -- а просто добавлять нужные, т.е. в Вашем случае, если Вы добавляете новую колонку, то в ченджсете указываете эту информацию. 
Примеры в том файле есть.
А те данные, что уже имеются в файле локал_2015 -- нельзя менять ни в коем случае)
Подробнее про ликвибейс и ченджсеты можете почитать в Наших стандартах на вики, кажется, п. 2. 

@bvv4ik 
кстати, может, нужно уже создать новые файлы, для "нового года", локал_2016 ?

**Comment by bvv4ik** [comment]
@SergeiShemshur а можно плиз логин скайпа и электронку?

**Comment by bvv4ik** [comment]
@LamronNu
"кстати, может, нужно уже создать новые файлы, для "нового года", локал_2016 ?"

да, добавить вспомогательным файлом его, но ОООЧЕНЬ осторожно, чтоб не задеть 15-й...
а то ни дай Бог попадет бок на боевой...

**Comment by SergeiShemshur** [comment]
@bvv4ik  нет проблем Skype : Sergeidyb  mail: shemshur90@gmail.com

**Comment by SergeiShemshur** [comment]
Обновил документацию  https://github.com/e-government-ua/i/blob/test/docs/specification.md#50 можно тестировать. В FinanceCentralController  добивил поле в такие методы
<ol>
<li>GET /finance/getCurrencies</li>
<li>GET /finance/setCurrency</li>
<li>GET /finance/getMerchant</li>
<li>GET /finance/getMerchants</li>
<li>POST /finance/setMerchant</li>
</ol>
можно тестировать

**Comment by RoOmel** [comment]
Описания с примером запроса по ссылке
https://github.com/e-government-ua/i/blob/test/docs/specification.md#50
не нашёл, поэтому прошу привести пример ссылки запроса, либо указать новую ссылку документации.

**Comment by SergeiShemshur** [comment]
@RoOmel  Примеры запросов можна найти здесь https://jenkins-new.igov.org.ua/job/central_alpha/ws/wf-central/target/generated-docs/central-igov.html  ключом поиска можно использовать поле " sID_Currency  "
или вот пример 1) GET /finance/getCurrencies : https://test.igov.org.ua/wf/service/finance/getCurrencies?sID_Currency=UAH
2)GET /finance/setCurrency  https://test.igov.org.ua/wf/service/finance/setCurrency?sID_UA=050&sName_UA=Така&sName_EN=Taka&sID_Currency=BDT
3)GET /finance/getMerchant https://test.igov.org.ua/wf/service/finance/getMerchant?sID=i10172968078

**Comment by RoOmel** [comment]
Реализовано согласно ТЗ
