### ISSUE TITLE
При подаче заявки - выводить номер заявки уже в соответствии с новым стандартом (с префиксом сервера)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1081]
Например:
- раньше было: Ваш номер заявки "34345345"
- стало: Ваш номер заявки "1-34345345"
(где "1-" - это префикс кода сервера, который берется из поля nID_Server, сущности Service)

**Comment by Sokhatsky** [comment]
Додається цифра 0 до номера заявки при виборі послуги "Отримання субсидії на оплату житлово-комунальних послуг " https://test.igov.org.ua/service/654/general 
![pic1_ 1081](https://cloud.githubusercontent.com/assets/16464887/12297427/d3875b24-ba15-11e5-89df-123bda7e2693.png)

**Comment by Sokhatsky** [comment]
Підкажіть будь-ласка цифра  0 яка додається перед префіксом до номера заявки при виборі послуги "Отримання субсидії на оплату житлово-комунальних послуг " https://test.igov.org.ua/service/654/general це помилка чи код сервера?

**Comment by LamronNu** [comment]
0 -- це id центрального сервера (за замовчанням).
Тому це не помилка, все вірно)

**Comment by Sokhatsky** [comment]
перевірив, працює

**Comment by Sokhatsky** [comment]
Підкажіть будь ласка, на пошту номер заявки повинен приходити з префіксом кода сервера чи без?
На пошту приходить у форматі: " Ваша заявка -97434144 прийнята!"

**Comment by LamronNu** [comment]
має бути з кодом сервера.

**Comment by Sokhatsky** [comment]
Дякую. Помилка виправлена. На пошту приходить у вірному формат з кодом сервераі: "Ваша заявка 0-98425010 прийнята!"
