### ISSUE TITLE
В выпадающем списке желаемой даты визита в МРЕО отсутствуют данные при оформелнии услуги "Реєстрація авто з пробігом в МРЕВ"

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#1083]
![bug_igov_20_02](https://cloud.githubusercontent.com/assets/12996514/12288755/a2d576f4-b9df-11e5-898d-c562028521a4.jpg)
![bug_igov_20_01](https://cloud.githubusercontent.com/assets/12996514/12288751/9cbf30e8-b9df-11e5-99cb-80bed91dee92.jpg)

**Comment by Yurijj** [comment]
Подтверждаю. Причем ввести дату нельзя ни с помощью клавиатуры, ни с помощью пикера.
А еще такой вопрос: с помощью услуги "Реєстрація авто з пробігом в МРЕВ" можно зарегестрировать только авто с пробегом? Как насчет мотоциклов/моторолеров? 
При вводе в поле "VIN-номер авто:"  VIN-номер мотороллера, получаю ошибку "Помилка у VIN-номері авто."

**Comment by GrekD** [comment]
@kurbpa посмотри, плиз

**Comment by Julia-tera** [comment]
"Реєстрація авто з пробігом в МРЕВ "
Не корректно отрабатывает выпадающий список выбора области при повторном использовании. Открывает только введенную область, изменить есть возможность только при ручном удалении текста названия выбранного варианта, после чего выпадающий список показывает полный перечень. В выпадающем списке нужно показывать все возможные варианты, для возможности выбора без ручного стирания текста.

http://clip2net.com/s/3v7Rf2w

**Comment by Julia-tera** [comment]
![10feb-clip-48kb](https://cloud.githubusercontent.com/assets/17043155/13503686/70272e3e-e179-11e5-9c30-85c96d15e0e9.png)

**Comment by Julia-tera** [comment]
Ошибка не устранена. Дата не выбирается и нет возможности ввести вручную.

**Comment by Julia-tera** [comment]
![2](https://cloud.githubusercontent.com/assets/17043155/14719658/28e93c66-0806-11e6-98f9-7b8b5c24f5e5.png)

**Comment by kurbpa** [comment]
"Ошибка не устранена. Дата не выбирается и нет возможности ввести вручную."

@Julia-tera 

Процесс закрыт. 
Услуга полностью реструктурирована и кроме тестового сервера нигде не присутствует.
