### ISSUE TITLE
Не можливо замовити послугу "Реєстрація авто з пробігом в МРЕВ м.Києва (вул. Братиславська, 52)" у зв'язку з неактивністю поля вводу "Бажана дата візиту до МРЕВ:"

### ISSUE THREAD

**Issue by Sokhatsky** [e-government-ua/i#1085]

**Comment by Koffeek** [comment]
В зв'язку з реогранізацією МРЕВ послуга наразі недоступна. На майбутнє усі подібні питання обговорюються у https://github.com/e-government-ua/iForum/issues

**Comment by Sokhatsky** [comment]
Зрозумів. Дякую
