### ISSUE TITLE
Для послуги "Видача довідки про відсутність заборгованості з платежів до бюджету, що контролюються органами державної фіскальної служби" не можливо завантажити файл для поля "*Заповнений бланк"

### ISSUE THREAD

**Issue by Sokhatsky** [e-government-ua/i#1086]

**Comment by Sokhatsky** [comment]
Серйозність помилки: [S2]
Оточення: Windows 7 service pack 1, Mozilla Firefox версия 43.0.1
Детальний опис помилки: Помилка проявляється при намаганні завантажити файл в поле "Заповнений бланк:".
Кроки відтворення.
1. Зайти на сайт https://test.igov.org.ua/
2. Вибрати послугу "Видача довідки про відсутність заборгованості з платежів до бюджету, що контролюються органами державної фіскальної служби"
3. Успішно пройти верифікацію та зайти в послугу 
4. Завантажити файл в поле "Заповнений бланк:"
5. Фактичний результат Помилка
Очікуваний результат: Файл успішно завантажений
![pic1_ 1086](https://cloud.githubusercontent.com/assets/16464887/12328786/b247264e-bae5-11e5-8401-4c18148a9dd0.png)

**Comment by bvv4ik** [comment]
это не в платформе дело, а в конкретной услуге, потому прошу оставить этот мессадж или в:
https://github.com/e-government-ua/iTest/issues
или в
https://github.com/e-government-ua/iBP/issues


НО обязательно в комменте упоминуть логин кого-то из наших бизнес-аналитиков....
