### ISSUE TITLE
Когда ожидать выплаты??

### ISSUE THREAD

**Issue by EvaSergeevna92** [e-government-ua/i#1087]
Заявка 21755724 и 21759363. Они были поданы еще в конце ноября 2015,были отвезены все документы в совбез и теперь глухо как в танке.ответ предыдущий ничего не объяснил "в том месяце когда назначена субсидия",какая к черту субсидия,я не на субсидию подавала,а на соц выплаты на рождение ребенка и по беременности и родам,хотелось бы получить нормальный,вразумительный ответ.спасибо заранее.

**Comment by bvv4ik** [comment]
прошу Вас оставить сообщение в нашем формуме:
https://github.com/e-government-ua/iForum/issues

там его могли-бы глянуть наши коллеги волонтеры-аналитики и начать разбираться - в чем дело...

а тут, ведут задачи только разработчики МТ-волонтеры самой платформы/проекта, и к сожалению - даже не контактируют с теми чиновниками, которые отрабатывают заявки.. потому там, когда оставите мессадж, ребята могли-бы что-то узнать...


от себя: на сколько я знаю незадолго до нового года и полторы недели как после - госслужбы эти почти не работали, и начали разгребать накопившиеся заявки только-только... потому, скорей всего Ваша заявка гдето среди этой накопившейся очереди...
