### ISSUE TITLE
Оставшиеся мелкие задачи по дашборду

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#109]
https://docs.google.com/document/d/1HrxG5w8BsVaZuLlSauxinyb3Vfm9-SV9F41ck74YrPA/edit#

только не взятые другими коллегами (потом вписать свой ник возле пункта задачи)

**Comment by dmoskovsov** [comment]
@bvv4ik сделано, проверь пожалуйста бизнес часть.
