### ISSUE TITLE
Полностью проставить все анотации по документации для всех сервисов (в т.ч. для параметров)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1090]
ВАЖНО: Делать небольшими партиями, по 1-2 сервиса и выливать в ветку обратно.

- [ ] 1) убрать не используемые аннатации и добавить отсутствующие (причем для всех трех генераторов документации)

- [ ] 2) Обьединить две анотации контроллера:
вместо:
````java
@Api(tags = {"SubjectMessageController"}, description = "Сообщения субьектов")
````
должно стать:
````java
@Api(tags = {"SubjectMessageController - Сообщения субьектов"})
````

- [ ] 3) в описаниях параметров использовать следующие стандарты:
- nID_Element - ИД-номер элемента...
- sID_Element - ИД-строка элемента...
- sElement - Строка-название элемента...
- nElement - Число элемента... (или номер элемента)
- bElement - Булевый флаг элемент... если true, то - ....

- [ ] 4) везде однозначно проставить обязательность полей (а не так, что в одной анотации оно обязательное а в другой - нет)

- [ ] 5) для большого верхнего блока документации:
- убрать дублирование перечисление/описание всех параметров... использовать только аннотации отдельных параметров...
- убрать закомменченные параметры
- убрать дублирование названий сервисов и контроллеров в описаниях:
- убрать из примеров - неполноценные ссылки, типа:
"HTTP Context: http://server:port/wf/service/access/getAccessKey?"
- сделать более лаконичным, понятным, убрать дубли "\n" и почистить:

-ПРИМЕР:
в описаниях, типа:
````java
    @ApiOperation(value = "Получения ключа для аутентификации", notes = "##### Доступ центральный. Получения ключа для аутентификации. #####\n\n"
            + "HTTP Context: http://server:port/wf/service/access/getAccessKey?\n\n\n"
            + "возвращает ключ для аутентификации\n\n"
            + "Пример:\n"
            + "https://test.igov.org.ua/wf/service/access/getAccessKey?sAccessLogin=activiti-master&sAccessContract=Request&sData=/wf/service/setMessage\n")
````
должно остаться только:
````java
    @ApiOperation(value = "Получения ключа для аутентификации", notes = "#####Примеры:\n"
            + "https://test.igov.org.ua/wf/service/access/getAccessKey?sAccessLogin=activiti-master&sAccessContract=Request&sData=/wf/service/setMessage\n")
````

ИЛИ:
от:
````java
    @ApiOperation(value = "Удаление сервиса", notes = "##### ActionItemController - Предметы действий (каталог сервисов. Удаление сервиса #####\n\n"
		+ "HTTP Context: http://server:port/wf/service/action/item/removeService\n\n\n"
		+ "- nID_Subject - ID авторизированого субъекта (добавляется в запрос автоматически после аутентификации пользователя)\n\n\n"
		+ "Вовращает:\n\n"
		+ "HTTP STATUS 200 - удаление успешно. HTTP STATUS 304 - не удалено.\n\n"
		+ "Пример 1:\n"
		+ "https://test.igov.org.ua/wf/service/action/item/removeService?nID=1\n\n"
		+ "Ответ 1: HTTP STATUS 304\n\n"
		+ "Пример 2: https://test.igov.org.ua/wf/service/action/item/removeService?nID=1&bRecursive=true\n"
		+ "Ответ 2: HTTP STATUS 200\n"
		+ "\n```json\n"
		+ "{\n"
		+ "    \"code\": \"success\",\n"
		+ "    \"message\": \"class org.igov.activiti.common.Service id: 1 removed\"\n"
		+ "}\n"
		+ "\n```\n" )
````
останется:
````java
    @ApiOperation(value = "Удаление сервиса", notes = "##### Примеры:\n"
		+ "1: https://test.igov.org.ua/wf/service/action/item/removeService?nID=1\n"
		+ "Ответ: HTTP STATUS 304\n"
		+ "2: https://test.igov.org.ua/wf/service/action/item/removeService?nID=1&bRecursive=true\n"
		+ "Ответ: HTTP STATUS 200\n"
		+ "\n```json\n"
		+ "{\n"
		+ "    \"code\": \"success\",\n"
		+ "    \"message\": \"class org.igov.activiti.common.Service id: 1 removed\"\n"
		+ "}\n"
		+ "\n```\n" )
````

**Comment by LamronNu** [comment]
на данный момент перепроверены все контроллеры модуля wf-base:
(lesha1980)
wf-base:
AccessCommonController
ActionFlowController
ActionTaskCommonController
ActionEscalationController

olga:
wf-base:
DebugCommonController
ActionExecuteController
ActionEscalationController
ExceptionCommonController
FinanceCommonController
ObjectFileCommonController

**Comment by LamronNu** [comment]
wf-central:
AccessCentralController
ActionEventController
ActionItemController
ActionTaskCentralController
DebugCentralController
ObjectPlaceController

**Comment by lesha1980** [comment]
Совсем забыл за эту таску, замотавшись с рядом других...

**Comment by LamronNu** [comment]
@lesha1980 поэтому мне её "перепоручили", т.к. Вы заняты были)
я и сама сейчас мало времени могу уделять ей (и айгову в целом), но она из "несрочных", поэтому делаю "малыми шагами"..
если есть сильное желание -- можете доделать (осталось где-то 5-6 контроллеров в централе). но думаю, что и сама её закончу, поэтому не переживайте)

**Comment by bvv4ik** [comment]
@lesha1980  @LamronNu
Ольга и Алексей, прошу уже "добить ее", чтоб спать спокойно и знать что у нас полный порядок)

**Comment by LamronNu** [comment]
DocumentAccessController
DocumentController
FinanceCentralController
ObjectController

всё! )
