### ISSUE TITLE
Не працює послуга "Щомісячна грошова допомога особі, яка проживає разом з інвалідом I чи II групи внаслідок психічного розладу, який за висновком лікарської комісії медичного закладу потребує постійного стороннього догляду, на догляд за ним"

### ISSUE THREAD

**Issue by Sokhatsky** [e-government-ua/i#1094]

**Comment by Sokhatsky** [comment]
Серйозність помилки: [S2]
Оточення: Windows 7 service pack 1, Mozilla Firefox версия 43.0.1
Детальний опис помилки: Помилка з'являється  при спробі зайти в послугу: "Щомісячна грошова допомога особі, яка проживає разом з інвалідом I чи II групи внаслідок психічного розладу, який за висновком лікарської комісії медичного закладу потребує постійного стороннього догляду, на догляд за ним" (https://test.igov.org.ua/service/777/general) .
Кроки відтворення.
1. Зайти на сторінку для входу в послугу https://test.igov.org.ua/service/777/general
2. На кроці 1 (вибрати область – Дніпропетровська)
3. На кроці 2 успішно пройти верифікацію через систему BankID (приват 24)
4. Фактичний результат Помилка
Очікуваний результат: Ви успішно зайшли в послугу
![2016-01-18_1234](https://cloud.githubusercontent.com/assets/16464887/12389438/7b4ad84e-bde1-11e5-93cd-1a47b4dda661.png)

**Comment by GrekD** [comment]
спасибо за сигнал. исправила
