### ISSUE TITLE
Для dashboard-js наладить работу API с удаленным тестовым сервером не прибегая к работе с локальным.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#110]
Для dashboard-js наладить работу API с удаленным тестовым сервером не прибегая к работе с локальным.
Насколько известно, чтобы это сделать  таким должен быть locan.env.js
    //activiti settings
    ACTIVITI_PROT: 'https',
    ACTIVITI_HOST: '52.17.126.64',
    ACTIVITI_PORT: 8443, //port for activiti service
Но аутентификация с этим конфигом не работает, насколько я понимаю потому что клиент не находиться в хттпс

**Comment by dmoskovsov** [comment]
Пример конфига в проекте теперь по умолчанию настроен на работу с удаленным сервером. 
Вики обновлена: https://github.com/e-government-ua/i/wiki/FrontEnd,-%D0%94%D0%B0%D1%88%D0%B1%D0%BE%D1%80%D0%B4-%D0%BF%D0%BE%D1%80%D1%82%D0%B0%D0%BB-(dashboard-js)
