### ISSUE TITLE
Реализовать сервис получения списка всех тасок, которые могут быть доступны указанному логину и которые уже заняты другими логинами, входящими во все те-же группы, в которые входит данный логин.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1102]
В оригинальном списке сервисов активити именно такого сервиса нет!

- Данные возвращать в точно таком-же формате, как и стандартный сервис активити получения списка тасок:
/wf/service/runtime/tasks
/wf/service/history/historic-task-instances
(примеры вызовов и ответных объектов можно глянуть на дашборде, в фаербаге, при выборе табов со списками)

- ВАЖНО: стараться реализовать очень оптимально, минимизировав нагрузку на сервер (т.к. запрос достаточно тяжелый будет)

- [x] 1. сервис getTasks в контроллере "ActionTaskCommonController" (контекст "/action/task")
- [x] 2. параметры:
- sLogin - строка-логин
- bIncludeAlienAssignedTasks - булевый, если задан true, то выдавать в т.ч. все чужие ассайнутые задачи (по умолчанию false), в рамках тех групп, в которые входит зададанный логин
- [x] 3.. "ассоциированные задачи"
- [x] 3.1. нужно получить список всех групп, в которые входит данный пользователь
- [x] 3.2. получить полный список всех логинов (уникальных), которые входят в эти группы
- [x] 3.3. получить полный список тасок, которые доступны текущему пользователю-кандидату (в т.ч. уже ассайнутые на него)
- [x] 3.4. дополнить список тасок, которые ассайнуты на всех полученных на предыдущих этапах логинов
- [x] 4. в коментах описать сервис и параметры, для авто-генерации документации  на наши АПИ

**Comment by ASkosyr** [comment]
если bAllAssociatedTask=false - то только свои и только не ассайнутые, к которым доступ.

**Comment by ASkosyr** [comment]
https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&nSize=1&nStart=10

```json
{"total":338,"sort":"id","order":"asc","start":10,"data":[{"tenantId":"","createTime":"2016-01-21T22:32:02.147+0200","formKey":null,"processDefinitionUrl":"/wf/service/repository/process-definitions/common_mreo_2:3:8762504","processInstanceUrl":"/wf/service/runtime/process-instances/10027501","executionId":"10027501","assignee":null,"executionUrl":"/wf/service/runtime/executions/10027501","url":"/wf/service/runtime/tasks/10027584","suspended":false,"variables":[],"parentTaskUrl":"","id":"10027584","category":null,"processInstanceId":"10027501","description":null,"priority":50,"name":"Перевірка (запит по фізичним особам)","taskDefinitionKey":"usertask1","owner":null,"processDefinitionId":"common_mreo_2:3:8762504","parentTaskId":null,"dueDate":null,"delegationState":null}],"size":1}
```

**Comment by ASkosyr** [comment]
Добавил дополнительные параметры:
sOrderBy - метод сортировки задач. Необязательный параметр. По умолчанию "id". Допустимые значения "id", "taskCreateTime"

nSize - Количество задач в результате. Необязательный параметр. По умолчанию 10.
nStart - Порядковый номер первой задачи для возвращения. Необязательный параметр. По умолчанию 0

**Comment by ASkosyr** [comment]
@RoOmel , мне нужно забрать задачу из тестирования :)
я вчера делал смежную 1110 и эту немного зацепил.
сейчас как раз тестирую

**Comment by ASkosyr** [comment]
Как проверить можно.
Запрос с параметром bIncludeAlienAssignedTasks=true также должен возвращать и задачи, у которых поле assignee не пустое.

Для примера можно сравнить результаты запросов
```
https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&nSize=15&nStart=10
https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&nSize=15&nStart=10&bIncludeAlienAssignedTasks=true
```

В результате второго запроса встречаются задачи с "assignee":"tester"

**Comment by ASkosyr** [comment]
@RoOmel, задача для тестирования готова.
эту и смежную оттестирировал со своей стороны.

**Comment by RoOmel** [comment]
ОК, спс

**Comment by RoOmel** [comment]
По запросу
https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&nSize=15&nStart=10&sOrderBy=id&bIncludeAlienAssignedTasks=true
отображаются таски  параметром "assignee": null, хотя параметрв  запросе bIncludeAlienAssignedTasks=true, что не соответствует ожидаемому результату, согласно условию задачи

**Comment by bvv4ik** [comment]
так и должно быть, т.к. это должно лишь дополнить список а не сократить его
(формулировку в пункте задачи дописал подробней, чтоб не возникало путаницы)

**Comment by RoOmel** [comment]
ок
