### ISSUE TITLE
Реализовать новую навигацию закладок и меню

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1109]
В соответствии с макапом:
https://dl.dropboxusercontent.com/u/50541317/eGov/dashboard/start.html#p=необроблені
(можно выбирать разделы: необроблені, Налаштування, Управління в Версии 2. (1-я версия не актуальна))

- [x] 0) Визуализацию компонентов привести к приблизительному виду мокапа 

- [x] 1) Разместить в указанными последовательности и названиями основные закладки 
- Переименовать:
"Тікети" > "Мій розклад"
"Оброблені" > "Історія"
- при выборе закладок они должны отражать контент так-же, как это работает уже сейчас

- [x] 2) разместить слева-вверху кнопку "Инструменты", при включении которой должен отображаться альтернативный набор закладок, а при повторном клике - все должно возвращаться в исходное состояние
- при выборе каждой из этих закладок - визуализировать это так-же как и при выборе закладок с задачами, и при клике на
- Переименовать:
"Звіти" > "Звіт"
"Сервіс" > "Розклад"
- Добавить новые закладки, но в них отображать пустое поле с надпсью о скорой готовности раздела:
Групи
Користувачі
Розгортання
- при выборе закладок они должны отражать реализованный контент так-же, как это работает уже сейчас

- [x] 3) При клике на ФИО (справа-вверху) должно отображаться меню их двух указанных пунктов (из которых работать пока должен "выход" а при клике на "Профиль" отображать сообщение о том, что скоро будет готово.

- [x] 4) Подгружать список задач теперь "партиями по 50 шт", при скролировании до 50% списка - подгружать следующие "50 записей списка", если они есть. Если загружать больше нечего, то писать в конце списка надпись "(больше задач нет)"
- в используемом сейчас сервисе можно задавать число загружаемых пунктов параметром "size" и так-же, с какой строки начинать (в доке по Activiti єто есть, а ссілка на доку у нас на Вики)

- [x] 5) в закладке "Усі" і "Історія" счетчик числа задач не отображать.

- [x] 6) в закладке "Необроблені", при выборе пункта(задачи) справо перед списком полей отображать кнопку "Взяти в роботу" (сейчас она размещается в конце списка полей)

- [x] 7) Все текущие фильтры разместить в едином блоке, который отображать и скрывать при нажатии на ссылку-кнопку "Налаштувати фільтр"
- В скрытом состоянии отображать просто текст с перечислением включенных фильтров (если фильтр стоит в умолчательном состоянии - не перечислять его в списке)
- В фильтрах не размещать текущие элементы поиска по "номеру заявки" и "по тексту"
- при клике на "Скинути выльтр" - все фильтры сбрасывать в умолчательное состояние и сворачивать блок (сама кнопка сброса фильтров реализована и сейчас)

- [x] 8) Слева вверху разместить "унифицированное поле поиска".
- если вводится только число или номер заявки (в формате Х-ХХХХХ), то искать по номеру заявки, иначе искать как по тексту.
- если-же по номеру заявки не будет найдено ничего то искать повторно по тексту
- при нахождении задачи/задач по заявке - переходить к первой из них в нужную закладку (такого реализовано сейчас небыло, но задел есть) и выбирать ее в списке (как сейчас)
- переходы в разделы "Все", "История" и "Мій розклад" не производить, а и не выбирать только в других закладках.
- после достижения последнего найденного пункта в списке найденных задач - возвращаться на первый
- если ничего не найдено ни по номеру ни по тексту - выводить диалог с сообщением "Ничего не найдено по данному номеру заявки/данному тексту (или и то и другое, в зависимости от того, по какому алгоритму пришлось пройтись)"
- если поиск обнаружил заявку в разделе, но она еще не авто-подгружена как пункт в списке, то  подгружать следующие "по 50 пунктов-задач в списке". пока не подгрузится нужный пункт с задачей.

- [x] 9) Доработать "унифицированное поле поиска"
- число найденых задач отображать справа от поля поиска число найденных (не доделано, пропадает после перехода к задаче)
- при нахождении задачи/задач по заявке и переходе к ней, после выбора ее в списке скролить до нее экран

**Comment by marbug** [comment]
"фикс1" (замержил):
https://github.com/e-government-ua/i/pull/1118

**Comment by marbug** [comment]
fix2 (merged)
https://github.com/e-government-ua/i/pull/1119

**Comment by marbug** [comment]
fix3 (merged)
https://github.com/e-government-ua/i/pull/1120

**Comment by marbug** [comment]
fix4 (merged)
https://github.com/e-government-ua/i/pull/1121

**Comment by marbug** [comment]
fix5 (merged)
https://github.com/e-government-ua/i/pull/1122

**Comment by marbug** [comment]
fix6 (merged)
https://github.com/e-government-ua/i/pull/1123

**Comment by marbug** [comment]
fix7 (merged)
https://github.com/e-government-ua/i/pull/1124

**Comment by marbug** [comment]
fix8 (merged)
https://github.com/e-government-ua/i/pull/1125

**Comment by marbug** [comment]
fix9 (merged)
https://github.com/e-government-ua/i/pull/1132

**Comment by marbug** [comment]
fix10 (merged)
https://github.com/e-government-ua/i/pull/1133

**Comment by bvv4ik** [comment]
Привет,
как оцениваешь еще по времени оставшийся объем?
Может помощь нужна?

**Comment by marbug** [comment]
Привет. Думаю, тут часов на 20-30, т.к. надо передизайнить несколько сервисов и контроллеров. Пока болею. Надеюсь на выходных таки вернуться и добить. Помощь... М... Если есть желающие, то можно, но в целом там работа на одного, чтобы не запутаться и ничего не поламать. ИМХО

**Comment by marbug** [comment]
fix11 (merged)
https://github.com/e-government-ua/i/pull/1152

**Comment by marbug** [comment]
fix12 (merged)
https://github.com/e-government-ua/i/pull/1153

**Comment by kurbpa** [comment]
```3) При клике на ФИО (справа-вверху) должно отображаться меню их двух указанных пунктов (из которых работать пока должен "выход" а при клике на "Профиль" отображать сообщение о том, что скоро будет готово.```

Сейчас 3 пункта отображается... Один из них "задачи" - лишний.

**Comment by marbug** [comment]
Спасибо, выпиляю.
З.Ы. Добавил специально, т.к. при промежуточных изменениях нельзя было попасть в таски при выходе в другой пункт.

**Comment by marbug** [comment]
fix13 (merged)
https://github.com/e-government-ua/i/pull/1155

**Comment by marbug** [comment]
fix14 (merged)
https://github.com/e-government-ua/i/pull/1156

**Comment by marbug** [comment]
fix15 (merged)
https://github.com/e-government-ua/i/pull/1157

**Comment by marbug** [comment]
fix16 (merged)
https://github.com/e-government-ua/i/pull/1158

**Comment by marbug** [comment]
fix17 (merged)
https://github.com/e-government-ua/i/pull/1159

**Comment by marbug** [comment]
Таки добавил отображение "названий" страниц для "TODO", т.к. при отсутствии заглавия складывается впечатление, что работает только выделение "табин", а сам переход не работает или глючит. Сейчас всё должно быть более понятным.

**Comment by marbug** [comment]
fix18 (merged)
https://github.com/e-government-ua/i/pull/1160

**Comment by sergeygorban** [comment]
1. Вкладка "Пользователи" - не реализовано добавление пользователей
2. Вкладка "Группы" - не реализовано добавление групп
3. Вкладка "Отчет" -  при формировании отчета за выбранный интервал времени файл открывается пустой или с непонятными символами. Очень неудобен поиск заявки для формирования отчета
4. Кнопка "взять в работу" во вкладке "Не обработанные" - размещается  внизу и вверху
 5. Фильтр. Выборка по фильтру не работает. Если установить фильтр в какой то вкладке, а затем перейти в другую, то происходит сброс фильтра в установленной вкладке, но через время данный фильтр устанавливается сам и выполняет выборку. 
6. Кнопка "Поиск": 
1. При вводе заявки в формате 0-11333163, происходит ее нахождение и подсветка, но фактическое нахождение в общем списке необходимо производить с помощью ползунка
2. При вводе в "поиск" любой цифры, к примеру "2" для поиска заявок в любом разделе, происходит какой-то поиск с отображение найденных результатов и автоматическое перенаправление в раздел "В работе"
  
3. Если в "поиск" задать название заявки без номера, то поиск не будет выполнен

7. Профиль пользователя не реализован

**Comment by sergeygorban** [comment]
Вывод после тестирования: согласно требованиям задачи и замечаниям согласно https://github.com/e-government-ua/i/issues/1193 все выполнено
