### ISSUE TITLE
Убрать с портала PHP логотип Днепрорады

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#111]
а также другие лого Днепрорады (оставить унифицированный дизайн)

**Comment by alegast** [comment]
done.

**Comment by bvv4ik** [comment]
Спасибо!
но тут я немного протупил... както https://test.e-gov.org.ua/ смотрется сейчас ну совсем уныло)

а можно всеже какуюнить унифицированную картинку, вместо прошлой, близкую по размеру и посвященную Электронному правительству и соответствующую тематике портала "Электронным услугам регионнов" (данный конкретный портал по большей части временный демонстрационный, с реально работающими услугами, причем не только Днепрорады, но и Львова, Киева и т.д.... т.е. демонстрационный прототип). А как центральный портал докрутим - и раскидается все по категориям там в каталоге - уже он станет демонстрационным и реальным одновременно. а этот для тестов оставим)

**Comment by dubilet** [comment]
отлично смотрится )
пока не переехали на единый портал, все должно выглядеть кричаще "тестовым"
:)

**Comment by alegast** [comment]
Як варіант, дефолтне bootstrap navagation мен. З login , fio/logout

**Comment by bvv4ik** [comment]
логин/логаут тут ка раз не нужен... они есть на дашборде для чиновников

**Comment by alegast** [comment]
Давайте картинку, повісимо як логотип )
