### ISSUE TITLE
В кастомный сервис получения тасок добавить опциональные параметры-фильтры, подобьекты с данными и сортировку

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1110]
На базе реализованной задачи:
https://github.com/e-government-ua/i/issues/1102

- [x] 1) Добавить параметры-фильтры:
- [x] 1.1) bFilterHasTicket - только задачи, к которым есть тикет (есть отдельный сервис, который обеспечивает выдачу всего списка)
- [x] 1.2) sFilterStatus - статус, у которого возможные значения:
- "OpenedUnassigned" - только не-ассайнуиые
- "OpenedAssigned" - только ассайнуиые
- "Opened" - только открытые (не в истории)
- "Closed" - только закрытые (история)

- [x] 2) Добавить под объекты с данными к тем таскам, которые связаны с тикетом.
(есть отдельный сервис, который обеспечивает выдачу целого  списка задач по тикетам с массой вспомогательных данных. вот эти данные и должны попасть в этот под-объект)

- [x] 3) Добавить в перечень полей, по которым можно сортировать через параметр sOrderBy - поле с датой тикета, и при его задаче сортировать по нему.

- [x] 4) ВАЖНО: при реализации обязательно вынести в отдельные методы:
- формирование списков по стандартным наборам критериев, 
- и отдельно обертку, вызывающую этот сервис и формирующую обьект ответа (чтоб иметь возможность потом в другой такой-же обертке вызывать этот конечный метод запроса несколько раз, с разными критериями, кешировать результаты для последующих наборов критериев и уже формировать иной итоговый обьект в ответ.
- это понадобится для реализации производной таски: https://github.com/e-government-ua/i/issues/1117

**Comment by bvv4ik** [comment]
я там чуток названия поправил:
- bFilterHasTicket - только задачи, к которым есть тикет (есть отдельный сервис, который обеспечивает выдачу всего списка)
- bFilterAssigned - только ассайнуиые
- bFilterUnassigned - только не-ассайнуиые
- bFilterStatusClosed - только закрытые (история)
- bFilterStatusOpened - только открытые (не в истории)

**Comment by bvv4ik** [comment]
и важным моментом дополнил:
ВАЖНО: при реализации обязательно вынести в отдельные методы:
- формирование списков по стандартным наборам критериев, 
- и отдельно обертку, вызывающую этот сервис и формирующую обьект ответа (чтоб иметь возможность потом в другой такой-же обертке вызывать этот конечный метод запроса несколько раз, с разными критериями, кешировать результаты для последующих наборов критериев и уже формировать иной итоговый обьект в ответ.
- это понадобится для реализации производной таски: https://github.com/e-government-ua/i/issues/1117

**Comment by ASkosyr** [comment]
Примеры запросов

```
https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&bFilterHasTicket=true&sFilterStatus=Opened
https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&sFilterStatus=Opened
https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&sFilterStatus=Closed
https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&sFilterStatus=OpenedAssigned
https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&sFilterStatus=OpenedUnassigned
https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&sFilterStatus=OpenedUnassigned&bIncludeAlienAssignedTasks=true
```

**Comment by ASkosyr** [comment]
По запросу 
https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&sFilterStatus=OpenedUnassigned

выводятся все таски, которые могут быть заассайнены пользователем kermit
https://test.region.igov.org.ua/wf/service/runtime/tasks?candidateUser=kermit

Запрос
https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&sFilterStatus=OpenedAssigned
выдает все задачи, которые сейчас заассайнены на пользователя kermit

Пример запроса напрямую через apache activity
https://test.region.igov.org.ua/wf/service/runtime/tasks?assignee=kermit

Запрос 
https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&sFilterStatus=Opened
выдает все задачи, которые заасайнены на пользователя или которые могут быть им заассайнены

Аналог запроса
https://test.region.igov.org.ua/wf/service/runtime/tasks?candidateOrAssigned=kermit

**Comment by ASkosyr** [comment]
С последним запросом 
https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&sFilterStatus=Closed

Аналогичный запрос
https://test.region.igov.org.ua/wf/service/history/historic-task-instances?taskInvolvedUser=kermit&finished=true
получает все таски, к которым имеет отношение пользователь

taskInvolvedUser also means any involved user in a task, so also a candidate user or another identity link that's added to the task.

**Comment by RoOmel** [comment]
Спс, вопросов нет.
Реализовано согласно ТЗ.
