### ISSUE TITLE
Доработать сервис сохранения сообщений, для поддержки прикрепляемости файлов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1112]
в контексте: /subject/message
контроллере: SubjectMessageController
Дорабабатываемый сервис: /setServiceMessage

- [x] 1) добавить в сервис опциональній параметр sID_File, в котором может приходить ключ записи Редис-а и параметр sFileName, в котором содержится название файла.

- [x] 2) если придет ключ (п.1), то загрузить массив байтов из редис-а( образец в: /download_file_from_redis ), и сохранить его в Монго, (посредством класса AccessDataServiceImpl)

- [x] 3)  получив после п.2. новый ключ файла от монги - сохранить его в виде обьекта в поле sData (при сохранении сообщения SubjectMessage), в такой конструкции:
"aFile":[{"sFileName":"file.ext", "sKey":"978G9-g97B6-g6gtg-iYlkj9j-Jh9jG"}]
где sFileName - пришеджее название файла из п.1 а sKey - полученный в п.2 ключ

- [x] 4) обязательно комментировать сервисы и параметры,  чтоб могла авто-генерироваться документация по АПИ

**Comment by alexsisus** [comment]
This issue can be tested only after implementation of the related FE issue https://github.com/e-government-ua/i/issues/1113

**Comment by hordesalik** [comment]
#1113 готов, можно тестировать

**Comment by RoOmel** [comment]
Прошу указать доку или пример запроса для тестирования, а также ожидаемый результат.

**Comment by hordesalik** [comment]
@RoOmel я тестировал тут
https://test.igov.org.ua/order/search?sID_Order=0-106700217

там есть кнопка "Додати файл", после выбора он должен загрузится и после добавления комментария, информация о файле должна появится в списке комментариев **Прикріплено файл: "..."** Имя файла почему то приходит не то, которое отправлялось, но мне кажется это проблемы #1113

**Comment by RoOmel** [comment]
По ссылке
https://test.igov.org.ua/order/search?sID_Order=0-106700217
 ототбражается "Помилка сервіса!"

**Comment by bvv4ik** [comment]
@RoOmel 
прошу создать отдельную заявку для тестирования, тут видать в этой куча мусора намешалось, пока по ней нет смысла разбираться...

@alexsisus
Еще какой-то бок при сохранении контента...

аплоадится вот этот файл (application/octet-stream):
https://www.dropbox.com/sh/xuqmhuog5djnm3k/AAAj6QUQGGY4z8vpXcBK9s6Ea?dl=0
файл с размером 16040 байт

а вот скачивается файл размером 25149 байт
вот тут он скачивается:
https://test.region.igov.org.ua/wf/service/action/task/getMessageFile_Local?nID_Message=47466

и хедер уже текст/хтмл

прошу разобраться вв чем бок... то-ли не то сохраняется, то-ли довнлоадится не корректно..
ВАЖНО: с тектовым файлом так не происходит... там все гуд

**Comment by RoOmel** [comment]
Согласовано с разработчиком тестирование в таске
github.com/e-government-ua/i/issues/1113
