### ISSUE TITLE
Реализовать возможность прикреплять файлы к коментариям на централе

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1113]
- [x] 1) в закладке Статусы централа, вместе с кнопкой добавления комента - добавить кнопку "Прикрепить файл", при нажатии на которую можно выбрать для аплоада файл, и чтоб он загрузился на сервер, посредством сервиса-сетера. "/upload_file_to_redis" (в ответ будет получен ключ-ИД-шник)

- [x] 2) После аплоада файла написать соответствующую надпись вместо кнопки "Прикрепить файл" (например: "Прикреплен файл: файл1.экст ")

- [x] 3) полученный в п.1. ИД-шник файла (ключ) запомнить, и передать дополнительным параметром sID_File а название sFileName, уже при сохранении коммента(нажатии на кнопку), чтоб транзитом дальше передать его на явовский сервис, который и сейчас используется для сохранения коммента..( его доработка для этих целей по задаче: https://github.com/e-government-ua/i/issues/1112 )

- [x] 4) При загрузке списка коментариев, если будут встречаться записи-сообщений, в которых в поле sData будут данные о прикрепленном (п.3.) файле ( образованные по образцу п.3, задачи https://github.com/e-government-ua/i/issues/1112.), дописывать в сообщение-коментария на странице(только на самой странице), в конце, в отдельной строке, фразу: "Прикреплен файл: file.ext"

**Comment by hordesalik** [comment]
я возьму задачку ?

**Comment by hordesalik** [comment]
Готово, но я что то продеплоить не могу. Вернее деплой запускаю, но кнопка не появляется

**Comment by hordesalik** [comment]
Все готово, можно проверять

**Comment by IrynaAndronik** [comment]
- После аплоада файла  кнопка "Прикрепить файл"  не изменилась на  "Прикреплен файл: имя файла;
- История диалога появилась на портале чиновника, так же есть коментарий и информация о прикрепленном фале, но когда переходишь на этот файл он не открывается.
№ заявки 0-108535595
![image](https://cloud.githubusercontent.com/assets/16196477/12981302/c720793a-d0e8-11e5-9097-cc3de747f515.png)
файл при открытии
![image](https://cloud.githubusercontent.com/assets/16196477/12981314/d2c17a00-d0e8-11e5-862a-7c66b16d7214.png)

**Comment by hordesalik** [comment]
@IrynaAndronik все испрвалено. можно проверять

**Comment by IrynaAndronik** [comment]
Файл загружается, но по-прежнему не открывается. Формат .docx, .doc, .JPG.

**Comment by IrynaAndronik** [comment]
Файл появляется на портале чиновника только после написания комментария и нажатии кнопки Залишити коментар. Так должно быть? Если да, может нужно создать инструктивный лейбл о том что нужно обязательно оставить комментарий ?

**Comment by hordesalik** [comment]
Перепроверил, файл скачивается.
![image](http://grabilla.com/0620e-61583995-e903-43ec-be14-c984261b84f8.png)

**Comment by IrynaAndronik** [comment]
Да скачивается но не открывается

**Comment by hordesalik** [comment]
действительно, пишет ошибку, только текстовые нормально открываются

**Comment by alexsisus** [comment]
Переписали немного сервис получения аттачментов. 
Теперь ситуация следущая:
Было создано две тестовых услуги
0-110600919, в качестве документа прикреплен https://www.dropbox.com/sh/xuqmhuog5djnm3k/AAAj6QUQGGY4z8vpXcBK9s6Ea?dl=0
0-110850331, в атачменте картинка
Если дергать непосредственно сервис, который выгружает аттачменты с сервера, по прямому урлу, то контент аттачмента скачивается корректно и его можно просмотреть добавив к скачанному файлу нужное расширение(.docx и .jpeg соответтственно). Но если пытаться стянуть файл через портал чиновника, то в результате имеем уже битый файл. Нужно смотреть как конвертится( конвертится ли вообще) файл на ФЭ стороне.

урл для документа 
https://test.region.igov.org.ua/wf/service/action/task/getMessageFile_Local?nID_Message=47828
урл для картинки 
https://test.region.igov.org.ua/wf/service/action/task/getMessageFile_Local?nID_Message=47891

**Comment by hordesalik** [comment]
Готово. Можно проверять

**Comment by IrynaAndronik** [comment]
Отлично, теперь скачивается и открывается.
