### ISSUE TITLE
Реализовать на дашборде отображение ссылок на файлы, прикрепленный вместе с комментарием, и обеспечить возможность их загрузке по клику на ссылку.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1114]
- [x] 1) Подобно тому как описано в п.4 задачи https://github.com/e-government-ua/i/issues/1113 
Дописывать в отдельной строке (ниже самого комментария) фразу-ссылку на файл, вида "Прикреплен файл: file1.ext", если в поле sData объекта с комментарием присутствует признак прикрепленного файла:
"aFile":[{"sFileName":"file.ext", "sKey":"978G9-g97B6-g6gtg-iYlkj9j-Jh9jG"}]
где sFileName - название файла (механизм и формат сохранения так-же описан в п.3, https://github.com/e-government-ua/i/issues/1112 )

- [x] 2) Ссылка должна быть на промежуточный сервис сервера ноды, с передачей только номер сообщения и номер-процесса (пример: "/api/downloadFileOfComment?nID_Message=2342354&nID_Process=324252")

- [x] 3) Сервис ноды (для п.2)  должен использовать сервис сервис явы, написанный по п.2 задачи  
https://github.com/e-government-ua/i/issues/1115 и возвращать массив байт чтоб загрузить файл при клике на ссылку (п.2.)

**Comment by hordesalik** [comment]
Задача готова к тестированию

**Comment by sergeygorban** [comment]
Дайте пожалуйста скайп для связи с hordesalik

**Comment by hordesalik** [comment]
salik86

**Comment by sergeygorban** [comment]
Файлы, прикрепленные в комментариях к заявке, отображаются в виде ссылок на https://test-version.region.igov.org.ua. При нажатии на ссылку документа, реализована возможность открыть или сохранить данный файл
