### ISSUE TITLE
Реализовать центральный  сервис получения контента файла сообщения заявки, и его региональный "транзитный" вариант.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1115]
- [x] 1) Центральный сервис получения контента файла:  (проект: wf-central)

- [x] 1.1) Размещение и название:
Контроллер: SubjectMessageController
Контекст: /subject/message
Назвать сервис /getMessageFile

- [x] 1.2) Параметры:
nID_Message - номер-ИД сообщения (уникальный) //обязательный 
sID_Order  - строка-ИД заявки //опциональный

- [x] 1.3) Алгоритм получения контента.:
- [x] 1.3.1) Искать запись с сообщением по nID_Message в сущностях SubjectMessage (механизм взять за образец в сервисе: /getMessage )
- [x] 1.3.2) Если найден, и поле sData содержит конструкцию типа:
"aFile":[{"sFileName":"file.ext", "sKey":"978G9-g97B6-g6gtg-iYlkj9j-Jh9jG"}]
где sFileName - пришеджее название файла из п.1 а sKey - полученный в п.2 ключ
(добавление описано в п.3. в задаче https://github.com/e-government-ua/i/issues/1112 )
то загружать из Монго по ключу sKey контент файла (посредством класса AccessDataServiceImpl )
- [x] 1.3.3) Ошибки
- если не найдена запись с сообщением, то возвращать ошибку с текстом сообщения "Record not found"
- если не найден файл в монге, то возвращать ошибку с текстом сообщения "Content not found"

- [x] 1.4) Алгоритм защиты:
- [x] 1.4.1) если по п.1.2, параметр sID_Order:
- задан, то сверять наличие привязанности записи сообщения SubjectMessage с записью HistoryEvent_Service (по полю "nID_HistoryEvent_Service" в SubjectMessage) и значению поля sID_Order в связанной записи HistoryEvent_Service
- не задан - отдавать найденный контент, если он найден
- [x] 1.4.2) При заданности параметра и:
- не совпадению sID_Order - выдавать ошибку "Alien order"
- не связанностью sID_Order - выдавать ошибку "Order not found"

- [x] 1.5) В ответе отдавать:
Массив байт контента файла.

- [x] 2) Региональный сервис получения контента файла: (проект: wf-base)

- [x] 2.1) Размещение и название:
Контроллер: ActionTaskCommonController
Контекст: /action/task
Назвать сервис /getMessageFile_Local

- [x] 2.2) Параметры:
nID_Message - номер-ИД сообщения (уникальный) //обязательный 
nID_Process - номер-ИД процесса //опциональный

- [x] 2.3) Написать по образцу сервиса: /getOrderMessages_Local, но:
- обращаться в написанный сервис по п.1.
-  и возвращать массив байт.
- передавать sID_Order, конвертив его из nID_Process (образец есть так-же в: /getOrderMessages_Local )

- [x] 3) обязательно комментировать сервисы и параметры,  чтоб могла авто-генерироваться документация по АПИ

**Comment by alexsisus** [comment]
This issue can be tested only after implementation of the related FE issue https://github.com/e-government-ua/i/issues/1114

**Comment by RoOmel** [comment]
Прошу указать ссылку на доку или привести пример запроса для тестирования, а также ожидаемый результат.

**Comment by hordesalik** [comment]
в задаче #1114 реализовал ссылки, но файл не скачивается. ошибака:
`{
"code": "BUSINESS_ERR",
"message": "Can't get: nStatus=500sURL=https://test.igov.org.ua/wf/service/subject/message/getMessageFilemParam={sID_Order=0-106925014, nID_Message=46978}osReturn={\"code\":\"BUSINESS_ERR\",\"message\":\"Alien order\"}"
}`

**Comment by RoOmel** [comment]
Всё-равно не понятно.
Прошу привести кокретные ссылки сервиса и ожидаемый результат для тестирования этой задачи.
