### ISSUE TITLE
Синхронизировать контакты субьектов при подачи заявок

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1116]
По аналогии с: https://github.com/e-government-ua/i/issues/1054

В классе: RequestProcessingInterceptor
методе: saveNewTaskInfo

использовав параметр snID_Subject (фактически стринговый вариант nID_Subject) и sMailTo

- так-же синхронизировать контакты по каждому субьекту...
ВАЖНО: т.к. контакты и субьекты хранятся на централе а этот интерцептор может отрабатываться и на регионе, то сделатьеще промежуточную обертку-сервис, для передачи данных на центральный сервис через него, именно для этих целей...

Назвать /synсContacts, разместить в контроллере с Subject

**Comment by lesha1980** [comment]
Люди, подскажите в каком направлении копать, чтобы передать данные из перехватчика на wf-base в контроллер на wf-central?
