### ISSUE TITLE
Реализовать счетчик числа задач по нескольким наборам критериев-фильтров одновременно

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1117]
На базе реализованной задачи:
https://github.com/e-government-ua/i/issues/1110

- [x] 1) создать сервис /getCountTask, который используя все те-же фильтры что и в таске-образце, будет выдавать в JSON-объекте число тасок а не их список.
- входящие параметры
sLogin - логин пользователя, для которого делать выборку количеста задач
amFilter - массив-карта (JSON-объект-строка), в которой перечислены в массиве разные наборы критериев. например:
[
{"bFilterHasTicket":true},
{"sFilterStatus":"OpenedUnassigned"},
{"sFilterStatus":"OpenedAssigned","bFilterHasTicket":true}
]

- [x] 2) Выводить в одном объекте массив ответов для каждого варианта, например:
[
{"nCount":22}
{"nCount":33},
{"nCount":11},
]

- [x] 3) Оптимизировать реализацию таким образом, чтоб при каждом запросе данных, необходимых для получения числа, и понимании того, что следом будет еще один запрос - результаты этого запроса (массивы задач) запоминались в памяти, чтоб при следующем запросе, если они так-же будут востребованы - они-б не запрашивались заново а брались из памяти (причем сохранялось/кешировалось не само число а именно массивы задач, более общие, по которым было-бы достаточно пройтись циклом и подсчитать другие/смежные цифры. учитывающие другие критерии.
Для удобства - критерием разделения отдельных хранилищ массивов задач(сами массивы можно в единой мапе-кэше хранить), можно разделять по признаку разных примитивных-статусов (типа открытые-неассайнутые, открытые-ассайнутые (открытые - это сумма двух предыдущих), закрытые (они всегда только ассайнутые)

Например:
- получается перечень "открытых-ассайнутых" задач, чтоб посчитать число - понимаем что будет еще запрос, значит массив запомнили
- получается перечень "открытых-не асайнутых" задач, чтоб посчитать число - понимаем что будет еще запрос, значит массив запомнили
- получается полный перечень "открытых-асайнутых" задач у которых есть тикеты:
- а) сам список уже "открытых-асайнутых" задач берем из кеша, 
- б) затем запрашиваем список тикетов
- в) после чего отбираем из них те, что присутствуют в закешированном массиве.
- получается полный перечень "открытых-не асайнутых" задач у которых есть тикеты:
- а) сам список уже "открытых-асайнутых" задач берем из кеша,
- б) список тикетов тоже уже берем из кеша
- в) после чего отбираем из закешированного массива те, что присутствуют в другом закешированном массиве.

- [x] 4) в коментах описать сервис и параметры, для авто-генерации документации на наши АПИ

**Comment by ASkosyr** [comment]
https://test.region.igov.org.ua/wf/service/action/task/getCountTask?sLogin=kermit&amFilter=[{%22bFilterHasTicket%22:true},{%22sFilterStatus%22:%22OpenedUnassigned%22},{%22sFilterStatus%22:%22OpenedAssigned%22,%22bFilterHasTicket%22:true}]

```
[{"nCount":5},{"nCount":688},{"nCount":0}]
```

**Comment by ASkosyr** [comment]
Добавил логику сбрасывания кеша на события

TASK_ASSIGNED,TASK_CREATED,TASK_COMPLETED

**Comment by ASkosyr** [comment]
https://test.region.igov.org.ua/wf/service/action/task/getCountTask?sLogin=kermit&amFilter=[{"bFilterHasTicket":true},{"sFilterStatus":"OpenedUnassigned"},{"sFilterStatus":"OpenedAssigned","bFilterHasTicket":true}]

**Comment by RoOmel** [comment]
Прив запросе
https://test.region.igov.org.ua/wf/service/action/task/getCountTask?sLogin=kermit&amFilter=[{"bFilterHasTicket":true},{"sFilterStatus":"OpenedUnassigned"},{"sFilterStatus":"OpenedAssigned","bFilterHasTicket":true}]
Ответ сервера
[
    {
        "nCount": 0
    },
    {
        "nCount": 829
    },
    {
        "nCount": 1
    }
]
