### ISSUE TITLE
Заменить текст письма при замечании чиновника на заявку

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1127]
такой текст:

Тема: Просимо уточнити дані по Вашій заявці на iGov

Шановний (-а) %имя%!
Державний службовець, що обробляє Вашу заявку (%ФИО служащего%), просить уточнити Вас дані.
Коментар службовця: %коммертарий%

Щоб уточнити ці дані, перейдіть, будь ласка, за %цим посиланням% та заповніть поле.

**Comment by IrynaAndronik** [comment]
В тексте письма при замечании чиновника на заявку отсутствует:
-  %имя%!  чья заявка (вместо этого -Шановний громадянин);
- %ФИО служащего%.

**Comment by nazarenkod** [comment]
Подскажите, что делать с этой таской? 
На данный момент текстовка не соответствует требуемой...доработка текста будет или что-то изменилось?
