### ISSUE TITLE
Поправить отображаемость надписи напоминания актуализации данных БанкИД в форме заявки услуги

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1128]
1. Надпись "Якщо ці або будь-які інші дані, які були передані з Вашого банку, вже не актуальні, просимо Вас звернутися до цього банку для актуалізації." выводить только при авторизации через BankID. Для ЭЦП не делать этого.

**Comment by nazarenkod** [comment]
готово

**Comment by julyprodan** [comment]
протестировала на альфе на услуге https://alpha.test.igov.org.ua/service/28/general все отработало корректно, при авторизации через банк ид надпись была, при авторизации по ЕЦП - нет
