### ISSUE TITLE
при сохранении файлов через сервисы аплоада править название и расширение

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1129]
1) для сервисов:
/upload_file_to_redis
/upload_file_as_attachment
/upload_content_as_attachment
2) заменять название файлов с кирилических на транслит
2) если расширение файла "exe", то дописывать туда "_" в конце

подсказка: в сервисе /upload_file_as_attachment уже заменяется название файла, но на название, состоящее из номера задачи... а надо-бы транслит, в остальных (этот не трогать)

**Comment by KolesnikAlex** [comment]
Берется в работу

**Comment by bvv4ik** [comment]
вынужден был временно прописать костыль:
https://github.com/e-government-ua/i/commit/e3dc7d6b19b7c3ef3053c90d220499e03c261b5e

по завершению реализации и проверке - прошу этот костыль убрать (когда точно названия файлов будут уже не в кракозяблах)

**Comment by bvv4ik** [comment]
я прошу прощения, но есть перспектива реализации у этой ишью?

**Comment by KolesnikAlex** [comment]
Да, извиняюсь за задержку, долго отсутствовал.

**Comment by bvv4ik** [comment]
спс, ожидаю тогда фидбека)

**Comment by KolesnikAlex** [comment]
Извините, я не смогу выполнить это задание. Отдайте его кому-нибудь другому.
