### ISSUE TITLE
Рендеринг: Реализовать на центральном портале формирование каталога услуг относительно геоположения на фронте на основе данных из API бэка

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#113]
на /i/portal-js
В рамках этого образца:
На http://dr1v3.github.io/index.html

Только после реализации:
https://github.com/e-government-ua/i/issues/112
и
https://github.com/e-government-ua/i/issues/114

В соответствии с логикой:
https://docs.google.com/document/d/19nDtuDfB2faxBrA5zhlSxgFaXp1f4bTnkX7akwJVKno/edit

И структурой:
https://docs.google.com/spreadsheets/d/1UNPmkvpXwgFnSnjZ7nf4Fpr_hKm0JDxpRLBUshwNzWY/edit#gid=1718514141

**Comment by Kiaba** [comment]
http://e-government-ua.github.io/i/#/index - реалізовано формування списку послуг за допомогою API.
Використовуємо https://docs.angularjs.org/api/ngMockE2E/service/$httpBackend для emulation серверної частини.
Очікуємо реалізації серверної частини.

**Comment by bvv4ik** [comment]
все полностью готово)
