### ISSUE TITLE
Доработать сервис получения данных по задаче

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1131]
Развить реализованный в задаче:
https://github.com/e-government-ua/i/issues/1011
 сервис получения данных задачи.
- [x] 0) Добавить в сервис опциональный параметр sLogin, куда если передается логин, то проверять его вхождение в одну из групп, на которые распространяется данная задача. И если не входит, то выводить эксепшин "Access deny (group1, group2...)", где в скобках перечислить групы, которые содержатся в задаче.
- [x] 1) Где-бы не находилать таска (в истории или среди активных) - находить ее там и отдавать данные в такой-же структуре обьекта.
- [x] 2) обернуть те поля, что сейчас возвращаются в объекте - в элемент oProcess (т.к. они все относятся именно к процессу)
- [x] 3) все поля таски разместить в элементе-массиве: "aField", где в каждом элементе массива поле/объекте возвращать полный набор свойств и атрибутов с оригинальными названиями.
- [x] 4) если добавлен параметр bIncludeGroups=true, то в отдельном элементе aGroups возвращать массив отождествленных групп.
- [x] 5) если добавлен параметр bIncludeStartForm=true, то в отдельном элементе aFieldStartForm возвращать массив полей стартовой формы с теми значениями, что там были изначально (если, конечно, есть возможность их получить)
- [x] 6) если добавлен параметр bIncludeAttachments=true, то в отдельном элементе aAttachment возвращать массив элементов-объектов атачей (без самого контента)
- [x] 7) Если среди полей есть поле с типом электронной очереди, то контентом этого поля (JSON-объект) - доростить объект с полем, через элемент oData
- [x] 8) Описать все коментарии к сервису и параметрам, для корректной авто-генерации документации по АПИ
- [x] 9) если добавлен параметр bIncludeMessages=true, то в отдельном элементе aMessage возвращать массив сообщений по задаче (сейчас этот массив подгружается по сервису: /getMessageFile_Local, потому код этого сервиса вынести в пэкэдж бизнес-сервиса igov.service.business.subject.message., класс MessageService (посмотреть на соседние образцы чтоб были нужные аннотации и бины подтягивались))
- [x] 10) Добавить в объект элементы:
- sStatusName - название юзертаски
- sID_Status - ИД юзертаски
- sDateTimeCreate - дата и время создания юзертаски

**Comment by GFalcon-UA** [comment]
Процесс с элементом электронной очереди, но еще не принятый в работу чиновником:
https://test.region.igov.org.ua/wf/service/action/task/getTaskData?nID_Task&nID_Process=10870349
Процесс, который завершен и находится в архиве:
https://test.region.igov.org.ua/wf/service/action/task/getTaskData?nID_Task&nID_Process=10260070

**Comment by sergeygorban** [comment]
Нужен скайп для связи с GFalcon-UA

**Comment by GFalcon-UA** [comment]
gfalcon4

**Comment by sergeygorban** [comment]
При передачи запроса по получению стартовой формы заявки  GET https://test-version.region.igov.org.ua/wf/service/action/task/getStartFormData?nID_Task=1145104, которая непосредственно связана с методом  getTaskData приходит такой ответ:

**Comment by sergeygorban** [comment]
{
:   "pib_ur":"",
:   "edrpo":"",
:   "subekt":"fiz",
:   "imya_ur":"",
:   "edoc":"8925cd0e-e39d-408e-b375-3d9ff7ae2b0d",
:   "bankIdlastName":"ГОРБАНЬ",
:   "subekt_2":"personally",
:   "email":"sergey.gorban@ukr.net",
:   "date_today":"25\/03\/2016",
:   "notice":"Замовляючи послугу Ви надаєте згоду на обробку Ваших персональних даних та підтверджуєте їх актуальність.",
:   "rNumber":null,
:   "remail":null,
:   "bankIdfirstName":"СЕРГІЙ",
:   "markers5":"{\"motion\":{\"ShowFieldsOnCondition_5\":{\"aField_ID\":[\"imya_ur\",\"edrpo\",\"pib_ur\", \"adres_ur\"],\"asID_Field\":{\"sClient\":\"subekt\"},\"sCondition\":\"[sClient] == 'ur'\"}}}",
:   "markers6":"{\"motion\":{\"ShowFieldsOnCondition_6\":{\"aField_ID\":[\"adres_fiz\"],\"asID_Field\":{\"sClient\":\"subekt\"},\"sCondition\":\"[sClient] == 'fiz'\"}}}",
:   "markers7":"{\"motion\":{\"ShowFieldsOnCondition_7\":{\"aField_ID\":[\"doverennost\"],\"asID_Field\":{\"sClient\":\"subekt_2\"},\"sCondition\":\"[sClient] == 'confidant'\"}}}",
:   "doc_zemlya":"f14c93e5-f63c-4d0e-9085-16864a6d91d3",
:   "bankIdPassport":"ВЕ908720 АРТЕМОВСКИМ РО УМВДУ В ДОНЕЦКОЙ ОБЛ. 23.07.2003",
:   "sID_Public_SubjectOrganJoin":"lev",
:   "bankIdinn":"3167300413",
:   "layout":"г.Днепропетровск",
:   "adres_fiz":"г.Днепропетровск",
:   "adres_ur":"",
:   "square":"12акров",
:   "bankId_scan_passport":"1d88be9b-1efc-4d8e-9fa7-d9bb0be9fe7f",
:   "doverennost":null,
:   "bankIdmiddleName":"СЕРГІЙОВИЧ",
:   "phone":"066 060 0286",
:   "rName":null,
:   "bankId_scan_inn":"b2822de7-d1de-4388-86a1-ff0d929b85e3",
:   "text9":"Будь ласка, заповнюйте усі поля українською мовою"
}

**Comment by sergeygorban** [comment]
Вопрос: как связано с стартовой формой значение параметра square = 12акров?
Как получить эталонный вид стартовой формы конкретной заявки?
Если заявка доступна для создания в Днепропетровске и во Львове, то при передачи в запросе метода getStartFormData параметра  bIncludeGroups = true я должен получить в ответе 
sDateTimeCreate":"2016-03-25 00:58:33.590",
:   "aGroups":
:   [
:   :   "cnap_lev"
:   ]
две группы?

**Comment by sergeygorban** [comment]
При получении информации о заявке, которая принята в работу возвращается "aGroups": null.
Запрос: https://test-version.region.igov.org.ua/wf/service/action/task/getTaskData?nID_Task=&nID_Process=&sID_Order=0-12105717&bIncludeGroups=true

**Comment by sergeygorban** [comment]
Какие значения может возвращать параметр
sStatusName - название юзертаски 
sID_Status - ИД юзертаски
и что означают эти параметры?

**Comment by GFalcon-UA** [comment]
Баг со значением NULL в массиве **aGroups** - исправил. Сейчас NULL-значения в массив не попадают (отфильтровываются). Я так понял, что это в _Activiti_ остается "след" группы, когда таска ее покидает и переходит на новый этап по бизнес-процессу.

По поводу вышеизложенных вопросов.... 

- Для получения Стартовой формы я использовал уже существующий сервис `action/task/getStartFormData` в чистом виде без изменений. Поэтому содержание элемента **aFieldStartForm** считаю корректным.

- при выполнения задания по п.10 у меня был такой комментарий:
> "sID_Status - ИД юзертаски" - это обозначение статуса (по сути юзертаска это и есть некий этап/статус отработки задачи). Например: usertaskq, usertask2 и т.д.

На остальные вопросы исчерпывающего ответа, к сожалению, дать не могу.

**Comment by sergeygorban** [comment]
Большое спасибо
