### ISSUE TITLE
Реализовать кастомные сервисы работы с группами и пользователями Активити

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1134]
- [x] 1) /getGroups - получение списка групп
sLogin - логин того, чей список групп, в которые он входит, выводить //опциональный, по умолчанию все группы

- [x] 2) /setGroup - добавить/обновить группу
sID - строка-ИД группы
sName - строка-название группы

- [x] 3) /getUsers - получение списка юзеров
sID_Group - строка-ИД группы, в которую должен входить логин //опциональный, по умолчанию все юзеры

- [x] 4) /setUser - добавить/обновить юзера
sLogin - строка-логин
sPassword- строка-логин
sName - строка-название (сохраняем в FirstName)
sDescription - строка-описание (сохраняем в LastName)
sEmail - имейл, опциональный.

- [x] 5) /removeGroup - удалить групу
- если в групу входит хотябы один логин, выводить ошибку и список входящих логинов
- если в група входит в хотябы одну таску, выводить ошибку и список этих тасок

- [x] 6) /removeUser - удалить юзера
sLogin - строка-логин

- [x] 7) добавить описания в коменты/анотации для аавто-генерации доков по АПИ

забыл добавить сервисы:

- [x] 8) /setUserGroup - добавить группу для юзера
sID_Group - строка-ИД группы, в которую должен входить логин
sLogin - строка-логин

- [x] 9) /removeUserGroup - удалить группу для юзера
sID_Group - строка-ИД группы, в которую должен входить логин
sLogin - строка-логин

**Comment by bvv4ik** [comment]
Приветствую,
как там успехи по таске?)

**Comment by bvv4ik** [comment]
как там успехи?)

**Comment by PaulLuchyn** [comment]
Принимаю в работу

**Comment by nazarenkod** [comment]
подскажите сценарий для тестов

**Comment by nazarenkod** [comment]
Спасибо, сам нашел:) сервисы работают, задачу закрываю

**Comment by bvv4ik** [comment]
забыл добавить сервисы:

/setUserGroup - добавить группу для юзера
sID_Group - строка-ИД группы, в которую должен входить логин
sLogin - строка-логин

/removeUserGroup - удалить группу для юзера
sID_Group - строка-ИД группы, в которую должен входить логин
sLogin - строка-логин

**Comment by bvv4ik** [comment]
и там еще не хочет работать:
1) /getGroups - получение списка групп
sLogin - логин того, чей список групп, в которые он входит, выводить //опциональный, по умолчанию все группы

если не задавать параметр "sLogin"
при этом должно ваыдавать список всех групп.. а не выдает... приходится кермит логин писать
