### ISSUE TITLE
Реализовать кастомный сервис получения и установкидеплоя БП активити а так-же получения списка загруженных БП и удаления

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1135]
- [ ] 1) /action/task/setBP - установить/задеплоить новый БП
Параметры:
sFileName - строка-название файла
Метод: POST
в теле передавать тело XML в multipartfile
Ответ - код 200 если все гуд, иначе эксепшин

- [ ] 2) /action/task/getBP - получить загруженный БП
Параметры:
sID - строка-ID БП
Ответ - multipartfile тела XML 

- [ ] 3) /action/task/getListBP - получить список БП с версиями (массив объектов)
Параметры:
sID_BP - строка-ИД БП //опциональный фильтр, иначе все
sFieldType - строка-типа поля //опциональный фильтр, иначе все
sID_Field - строка-ИД поля //опциональный фильтр, иначе все
ОТВЕТ:
[
{sID_BP:"subsidy_dnepr"
,sVersion:"6:5436"
,nTasks:345 //число тасок, в которых встречено
}
]

- [ ] 4) /action/task/removeListBP - удалить список БП с версиями (массив объектов)
Параметры:
sID_BP - строка-ИД БП //опциональный фильтр, иначе все
sFieldType - строка-типа поля //опциональный фильтр, иначе все
sID_Field - строка-ИД поля //опциональный фильтр, иначе все
sVersion- строка-версия БП //опциональный фильтр, иначе все

**Comment by bvv4ik** [comment]
Приветствую,
как там успехи по таске?)

**Comment by kalu44i** [comment]
Привет!) До конца недели залью, если не срочно!?

**Comment by bvv4ik** [comment]
до конца недели - ок)
спасибо!

**Comment by kalu44i** [comment]
1) https://test.igov.org.ua/wf/service//action/task/setBP
Зроблено згідно стандартів (потрібна допомога у формуванні правильного POST запиту)

2) https://test.igov.org.ua/wf/service/action/task/getBP?sID=CivilCardAccountlRequest:1:6
Вертає файл bpmn з XML

3) https://test.igov.org.ua/wf/service/action/task/getListBP
повертає повний список БП з версіями у вигляді:
{  
      "id":"CivilCardAccountlRequest:1:6",
      "category":"http://www.activiti.org/test",
      "name":"Видача картки обліку об’єкта торговельного призначення, сфери послуг та з виробництва продуктів харчування",
      "key":"CivilCardAccountlRequest",
      "description":null,
      "version":1,
      "resourceName":"/sybase/tomcat/webapps/wf-central/WEB-INF/classes/bpmn/autodeploy/dnepr-2.bpmn",
      "deploymentId":"1",
      "diagramResourceName":"/sybase/tomcat/webapps/wf-central/WEB-INF/classes/bpmn/autodeploy/dnepr-2.CivilCardAccountlRequest.png",
      "tenantId":"",
      "suspended":false
   }, ...

4) https://test.igov.org.ua/wf/service/action/task/removeListBP - видаляє список БП
https://test.igov.org.ua/wf/service/action/task/removeListBP?sID_BP=CivilCardAccountlRequest:1:6 - видаляє БП з ID - sID_BP
+
аналогічно при використанні інших фільтрів

**Comment by nazarenkod** [comment]
Реализовано согласно описанию
