### ISSUE TITLE
Реализовать новую связанную сущность SubjectAccount и ее сущность типа, по аналогии с SubjectContact, только для хранения связанных с субъектом акаунтов + доработка смежной сущности и сущности SubjectHuman

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1136]
- [ ] 1) SubjectAccount

> **Поля:**
> nID - номер-ИД (уникальный, автоитерируемый)
> sLogin - строка-аккаунта (уникальный, в контексте nID_SubjectAccountType, nID_Server и nID_Subject)
> sNote - строка нотации (описания) //опциональный
> nID_SubjectAccountType - номер-ИД типа аккаунта
> nID_Server - номер-ИД сервера
> nID_Subject - номер-ИД субьекта

- [ ] 2) SubjectAccountType
> **Поля:**
> nID - номер-ИД (уникальный, автоитерируемый)
> sID - строка-ИД (уникальный)
> sNote - строка нотации (описания) //опциональный

> **Записи в csv:**
> nID;sID;sName
> 1;iGov;iGov
> 2;PD;PD

- [ ] 3) Сервисы:
- [ ] 3.1) /getSubjectAccounts - получение акаунтов
> **Параметры:**
> nID_Subject //номер-ИД субьекта //опциональній
> sLogin //строка-аккаунта //опциональный (но должен быть либо он, либо nID_Subject)
> nID_Server - номер-ИД сервера //опциональный
> nID_SubjectAccountType - номер-ИД типа аккаунта //опциональный

- [ ] 3.2) - /setSubjectAccount - добавление/обновление акаунта
Те-же параметры, что и в п.п.3.1,
> **но с дополнительными параметрами:**
> sLogin - строка-аккаунта
> sNote - строка нотации //опциональный
> nID_SubjectAccountType - номер-ИД типа аккаунта
> nID_Server - номер-ИД сервера 
> nID_Subject - номер-ИД субъекта

- [ ] 4) Доработать сущность SubjectHuman и SubjectOrgan, чтоб дополнительным элементом объекта появился aAcount, содержащий массив объектов отождествленных аккаунтов

- [ ] 5) Доработать сущность SubjectHuman и SubjectOrgan, чтоб дополнительным элементом объекта появился aContact, содержащий массив объектов отождествленных контактов

- [ ] 6) коменты для автогенерации доки по АПИ

**Comment by kr110666kai** [comment]
Уточнение
2. Записи в csv:
nID;sID;**sName** наверное имелось ввиду **sNote**

**Comment by bvv4ik** [comment]
не, все-же это название.. Node - это как-бы описание...
его теоретически тоже можно добавить но пока не нужно

**Comment by bvv4ik** [comment]
ВАЖНАЯ ПРАВКА:
в задаче элемент nID_SubjectHuman заменен на nID_Subject

**Comment by bvv4ik** [comment]
и добавлены параметры сервиса 3.1)

**Comment by kr110666kai** [comment]
не, все-же это название.. Node - это как-бы описание...
его теоретически тоже можно добавить но пока не нужно

т.е. в SubjectAccountType
поле **sNote** заменить на **sName**?

**Comment by kr110666kai** [comment]
1. Пункт
сделан https://github.com/e-government-ua/i/blob/test/wf-central/src/main/java/org/igov/model/subject/SubjectContact.java

2. Пункт сделан 
https://github.com/e-government-ua/i/blob/test/wf-central/src/main/java/org/igov/model/subject/SubjectContactType.java

Сделал тест для проверки работы DAO https://github.com/e-government-ua/i/blob/test/wf-central/src/test/java/org/igov/model/subject/SubjectAccountTest.java

3. Пункт,
3.1. DAO приготовил.
Остальное пока нет

**Comment by bvv4ik** [comment]
отлично
только-бы все-же контрэин на nID_Subject стоит сделать
если не сложно... а то потом замучаемся

**Comment by kr110666kai** [comment]
Сделаю

**Comment by kr110666kai** [comment]
1.
только-бы все-же контрэин на nID_Subject стоит сделать

Добавил
```
 <changeSet id="issue-1136-2" author="kr110666kai">
	    <addForeignKeyConstraint constraintName="FK_AccountContact_Subject" referencedTableName="Subject" baseColumnNames="nID_Subject" baseTableName="SubjectAccount" referencedColumnNames="nID"/>
</changeSet>
```

2. 
3.1) /getSubjectAccounts - получение акаунтов  сервис 
сделал, залил, Перепроверю, добавлю доку к вечеру или завтра к обеду.

**Comment by kr110666kai** [comment]
п.3.1 сделал
https://jenkins-new.igov.org.ua/job/central_alpha/ws/wf-central/target/generated-docs/central-igov.html#_Получение_аккаунтов_субъектов

**Comment by kr110666kai** [comment]
п.3.2 сделан
https://jenkins-new.igov.org.ua/job/central_alpha/ws/wf-central/target/generated-docs/central-igov.html#_Добавление_обновление_аккаунта_субъекта

**Comment by OlgaTurenko** [comment]
Немного подправила 4 и 5 пункты (добавила еще и сущность SubjectOrgan)

**Comment by kr110666kai** [comment]
Хочу уточнить по п.4, 6  добить именно в **SubjectHuman** и **SubjectOrgan**, не в **Subject**?

**Comment by OlgaTurenko** [comment]
да. конечно просится в сабджект, но есть объективные причины по которым нужно именно в SubjectHuman и SubjectOrgan

**Comment by kr110666kai** [comment]
**aAccount** достаточно добавить по типу;
private transient List<SubjectContact> aContact;

или добиться работы
@OneToMany
private transient List<SubjectAccount> aAccount;

**Comment by OlgaTurenko** [comment]
transient - вроде говорит о том, что это не поле таблицы, а обычное поле класса. Там в SubjectOrgan добавляли такое поле (по сути костыль) при реализации другой задачки. и ручками в него помещали данные акаунта, которые получали отдельным запросом (это в сервисе /getSubjects, по сути дергаем 2-а дао, чтоб получить отдельно сабджект, отдельно акаунты) Думали что после реализации Вашей задачки как раз этот модификатор убрать (тоесть структуру табличек доработать необходимо, добавив поле с ид акаунта) и одним запросом будет тянуться сабджект уже вместе с акаунтами.

**Comment by kr110666kai** [comment]
Для информации.
п.4 в SubjectHuman aAccount удалось вставить. 
Со вставкой в SubjectOrgan пока проблема с частью тестов, хотя написанный тест DAO проходит.

**Comment by kr110666kai** [comment]
Я правильно понимаю, у нас используется две SessionFactory:
в GenericEntityDao
в BaseEntityDao

**Comment by kr110666kai** [comment]
Пока не получается добавить в сущности **SubjectHuman** и **SubjectOrgan** 
**List\<SubjectAccount\> aAcount.** Проблема в том, что **foreign key** в **SubjectAccount** связан с **Subject**, а не с **SubjectHuman/SubjectOrgan**:

```
<addForeignKeyConstraint constraintName="FK_AccountContact_Subject" referencedTableName="Subject" baseColumnNames="nID_Subject" baseTableName="SubjectAccount" referencedColumnNames="nID"/>
```

Чего я пока смог добиться.
Добавление в **SubjectHuman** и **SubjectOrgan** конструкции 
```
@LazyCollection(value = LazyCollectionOption.FALSE)
@OneToMany
@JoinColumn(name="nID_Subject", referencedColumnName="nID_Subject")
private List<SubjectAccount> aAccounts;
```

Частично работает, Например работает простое получении сущностей **SubjectHuman** и **SubjectOrgan** в тесте.

Но вылетают тесты по работе с "**Service**". Например выполнение сервиса **/action/item/getService** заканчивается неудачей, коллекции оказываются вне какой либо сессии. Я посмотрел debug hibernate, там многоуровневое подключение сущностей.


PS. Добавление **List\<SubjectAccount\> aAcount** в **Subject** проблем не имеет.
