### ISSUE TITLE
Реализовать Системтаску создания документа УкрДок-а

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1140]
- [x] 1) Класс и название системтаски CreateDocument_UkrDoc
- [x] 2) Параметры:
> sLoginAuthor - строка-логин автора
> sHead - строка заголовка
> sBody - строка тела
> nID_Pattern - номер-ИД шаблона
- [x] 3) Механизм:
- [x] 3.1) Вызываем сервис по адресу:
- боевой: https://doc.privatbank.ua/docs
- тестовый: https://doc.stage.it.loc/docs
Передавая туда POST-ом объект:
```
{"content": {
    "name": "**Строка заголовка (sHead)**",
    "text": "**Строка тела (sBody)**",
    "paragraphs": [],
    "extensions": {}
}
 ,"actors"  : {
     "paragraphs"  : {}
    ,"ratifiers"     : []
    ,"reconcilers"   : []
    ,"addressee"     : {}
    ,"readers"       : []
    ,"author" : {
         "id" : "**строка-логин автора (sLoginAuthor)**"
     }
  }
 , "details": {"template" : **номер-ИД шаблона (nID_Pattern)** }
}

```
- [x] 3.2) Для авторизации и принятия формата объекта передаем в хеадере:
Authorization : Bearer G5o67jm84O54yG67l7K8J57y7g455y67o7lhi
Content-Type  : application/json
где "G5o67jm84O54yG67l7K8J57y7g455y67o7lhi" - полученный SID 
по методу getSessionId()
в классе org.igov.service.business.document.access.handler.DocumentAccessHandler_PB
(он сейчас приватный, потому его нужно вынести в общий класс и сделать публичнім)

- [x] 3.3) В ответ получаем 
номер созданного документа, который помещаем в переменную процесса sID_Document, в формате "2345345:2016", где до двоеточия номер документа, а после год документа(текущий)

П.С.: 

- Дока по АПИ Укр-Дока:
https://itwiki.privatbank.ua/wiki/MIS_%D0%9F%D1%80%D0%B8%D0%B2%D0%B0%D1%82%D0%94%D0%BE%D0%BA:%D0%9D%D0%BE%D0%B2%D1%8B%D0%B5_%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D1%8B

- Примеры объектов вызова АПИ Укр-Дока:
https://itwiki.privatbank.ua/wiki/MIS_%D0%9F%D1%80%D0%B8%D0%B2%D0%B0%D1%82%D0%94%D0%BE%D0%BA:%D0%9D%D0%BE%D0%B2%D1%8B%D0%B5_%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D1%8B/%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B?code=160205ACD1imci4839r5&state=enter

ВАЖНО:

- Тестовый БП: https://test.igov.org.ua/service/154/general
Файл БП: _test_UKR_DOC.bpmn

- в тестовом БП на системтаске nID_Pattern установить равным 10677

**Comment by msvidran** [comment]
Тестовый БП:
https://test.igov.org.ua/service/154/general
Файл БП:
_test_UKR_DOC.bpmn

**Comment by sergeygorban** [comment]
1. Скажите пожалуйста, правильно ли я понимаю цель тестирования данной задачи: создать документ, которому будет присвоен определенный ID на портале https://test.igov.org.ua/ 
и проверить возврат этого ID, отправив POST запрос на https://doc.stage.it.loc/docs?
Шаги:
Зайти на портал https://test.igov.org.ua/
Выбрать раздел "Тестова служба"
Выбрать _test_UKR_DOC
Заполнить поля и получить ID документа
Отправить POST запрос на https://doc.stage.it.loc/docs

2. Как получить SID (пример запроса)

3. Тело POST запроса
"name": "**Строка заголовка (sHead)**", (Где ее взять?)
"text": "**Строка тела (sBody)**",      (Где его взять?)
"id" : "**строка-логин автора (sLoginAuthor)**" (Что за логин передавать?)
"details": {"template" : **номер-ИД шаблона (nID_Pattern)** }(В этот параметр передавать ID созданного документа на портале?)

4. Какой порт использовать для https://doc.stage.it.loc/docs ?

**Comment by msvidran** [comment]
Сделал >>> **в тестовом БП на системтаске nID_Pattern установить равным 10677**
**Ошибка**
Повернен пустий об'ект!

Час: "2016-02-18T07:58:09.005Z" , Функція: submitForm(UI)
Значення параметрів:
nID_Service: 154,nID_ServiceData: 883,processDefinitionId: _test_UKR_DOC:1:1,
