### ISSUE TITLE
Реализовать Системтаску получения содержимого документа УкрДок-а

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1141]
- [x] 1) Класс и название системтаски GetDocument_UkrDoc
- [x] 2) Параметры:
> sID_Document - строка-ИД документа (в формате "2345345:2016", где до двоеточия номер документа, а после год документа(текущий)
- [x] 3) Механизм:
- [x] 3.1) Вызываем сервис по адресу:
- где хост берется с generalConfig.getsUkrDocServerAddress()
- страница /docs/<ГОД УТВЕРЖДЕНИЯ>/<ИДЕНТИФИКАТОР ДОКУМЕНТА>/content
- [x] 3.2) Для авторизации и принятия формата объекта передаем в хеадере:
Authorization : promin.privatbank.ua/EXCL G5o67jm84O54yG67l7K8J57y7g455y67o7lhi
Content-Type  : application/json
где "G5o67jm84O54yG67l7K8J57y7g455y67o7lhi" - полученный SID 
по методу getSessionId()
в классе UkrDocUtil
`String sessionId = UkrDocUtil.getSessionId(generalConfig.getSID_login(), generalConfig.getSID_password(), generalConfig.sURL_AuthSID_PB() + "?lang=UA");
`
(он сейчас приватный, потому его нужно вынести в общий класс и сделать публичнім)
- [x] 3.3) В ответ получаем документ, например:
```
{ "content" : { 
     "name"       : "Сервер для СХП"
    ,"text"       : "Уважаемый Никита Анатольевич! ..."
    ,"paragraphs" : [ 
        { "id"    : "1"
         ,"name"  : "Предоставить для нужд СХП x86- ..."
         ,"text"  : "Предоставить ... "
        }
     ]
    ,"attributes" : null
    ,"extensions" : null
  }
 ,"actors"  : {
     "paragraphs"  : {
        "1" : {
           "type"      : "task"
          ,"report"    : "Отчет в ЭСК"
          ,"executors" : [ {"id" : "DN141173KAV"} ]
          ,"control"   :   {"id" : "DN171081NMV"}
          ,"date"      : "28.03.2013"
        }
     }
    ,"ratifiers"     : [ 
        { "id"       : "DN151271SDG"
	 ,"signed"   : "05.03.2013"
         ,"signType" : "NORMAL"
        } 
     ]
    ,"reconcilers"   : [ 
        { "id"       : "DN141173KAV"
         ,"signed"   : "05.03.2013"
         ,"signType" : "NORMAL"
         ,"area"     : "Подтверждает соответствие выставляемых заданий исполняемым функциям"
        }
     ]
    ,"addressee"     : {
          "id"       : "DN081162VNA"
         ,"comment"  : "Разрешаю"
     }
    ,"readers"       : []
    ,"author" : {
         "id" : "DN171081NMV"
     }
  }
 ,"details" : {
     "id"       : 6596539
    ,"year"     : 2013
    ,"template" : 8540
    ,"type"     : "Служебная записка"
    ,"number"   : "Э.17.0.0.0/4-2061"
    ,"created"  : "05.03.2013"
    ,"state"    : "Исполнен"
    ,"actors"   : {
        "DN151271SDG" : {
           "name"     : "Шелудько Д. Г." 
          ,"position" : "..."
        }
       ,"DN141173KAV" : {
           "name"     : "Клепач А. В."
          ,"position" : "..."
        }
       ,"DN081162VNA" : {
           "name"     : "Волков Н. А."
          ,"position" : "..."
        }
       ,"DN171081NMV" : {
           "name"     : "Наволочка М. В."
          ,"position" : "..."
        }
     }
    ,"buttons" : {}
  }
}
```
- [x] 3.4) Сохраняем в поля таски:
- sHead_Document_UkrDoc
содержимое:
     "name"       : "Сервер для СХП"

- sBody_Document_UkrDoc
содержимое:
    ,"text"       : "Уважаемый Никита Анатольевич! ..."

П.С.: 

- Дока по АПИ Укр-Дока:
https://itwiki.privatbank.ua/wiki/MIS_%D0%9F%D1%80%D0%B8%D0%B2%D0%B0%D1%82%D0%94%D0%BE%D0%BA:%D0%9D%D0%BE%D0%B2%D1%8B%D0%B5_%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D1%8B

- Примеры объектов вызова АПИ Укр-Дока:
https://itwiki.privatbank.ua/wiki/MIS_%D0%9F%D1%80%D0%B8%D0%B2%D0%B0%D1%82%D0%94%D0%BE%D0%BA:%D0%9D%D0%BE%D0%B2%D1%8B%D0%B5_%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D1%8B/%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B?code=160205ACD1imci4839r5&state=enter

**Comment by bvv4ik** [comment]
я там чуток подправил п.п. 3.1 и п.п. 3.2
(просто привел в соответствие с реальностью, как в прошлой системтаске реализовано)

**Comment by ASkosyr** [comment]
тикет доделал
добавил систем таску в _test_UKR_DOC.bpmn з захардкоженным значением документа.

надо вставить правильно айдишник после системтаски, которая отправляет документ.
