### ISSUE TITLE
bug с сайтом igov.org.ua

### ISSUE THREAD

**Issue by chemfind** [e-government-ua/i#1142]
Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.
![error](https://cloud.githubusercontent.com/assets/7547101/12868330/b9557fe2-cd0c-11e5-94be-b3fa55bb9a80.jpg)

**Comment by bvv4ik** [comment]
были временные трудности, но уже все гуд
