### ISSUE TITLE
Реализовать сервис редиректа на страницу-заглушку в случае падения 

### ISSUE THREAD

**Issue by chemfind** [e-government-ua/i#1143]
Реализовать сервис редиректа на страницу-заглушку в случае падения
Текст: "Не хвилюйтеся, проводяться регламентні роботи. Скоро все буде добре, навіть краще, ніж раніше :)"

**Comment by bvv4ik** [comment]
одобрямс)
сделаем...

**Comment by ReasonX7** [comment]
Перехід на state `unavailable` відбувається кожного разу, коли надходить помилка 502.

Сервіс помістив в `public-js`, то ж він доступний для обох проектів. Правда швблон поки що захардкодив в JS [коді](https://github.com/e-government-ua/i/blob/92df24193bd53b5c2b2d22faa27c54729b59523b/public-js/unavailable/unavailable.module.js#L8)

**Comment by ReasonX7** [comment]
Як бути з лого `iGov`? На `dashboard-js` немає стилів `i-nav` & `navbar-brand`. Писати окремі стилі? І як офрмлювати - так само, як і на `central-js`?

**Comment by ReasonX7** [comment]
<img width="1440" alt="screen shot 2017-04-05 at 3 08 35 am" src="https://cloud.githubusercontent.com/assets/9498075/24684866/05a19294-19b2-11e7-85a2-aeac4d380c64.png">
