### ISSUE TITLE
Реализовать сервис получения отчета о поданных заявках,

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1146]
- [x] 1) Контекст и название: /action/event/getServiceHistoryReport

- [x] 2) Параметры:
> sDateAt - дата "с" (в формате YYYY-MM-DD hh:mm:ss)
> sDateTo - дата "по" (включительно, в формате YYYY-MM-DD hh:mm:ss)

- [x] 3) Данные отдавать в виде csv-файла

- [x] 4) Поля с данными:
> sID_Order - Строка-ИД заявки
> nID_Server - Номер-ИД сервера
> nID_Service - Номер-ИД услуги
> sID_Place - Строка-ИД услуги (брать из поля sID_UA)
> nID_Subject - Номер-ИД субьекта
> nRate - число-рейтинг
> sTextFeedback - строка-текст отзыва
> sUserTaskName - строка названия текущей юзертаски (этапа)
> sHead - строка заголовка
> sBody - строка тела (описания)
> nTimeMinutes - число минут, ушедших на отработку заявки
> sPhone - строка с телефоном

- [x] 5) Базовый список формировать из сущности HistoryEvent_Service, а к ней подгружать:
- [x] 5.1) данные по отзыву (sTextFeedback) из сущности SubjectMessage, у которой nID_SubjectMessageType = 2
- [x] 5.2) телефон - подгружая на региональном сервере заявку через сервис /getStartFormData, где nID_Task брать с одноименного поля сущности HistoryEvent_Service

- [x] 6) коментировать сервис и параметры для автогенерации документации по АПИ

**Comment by ASkosyr** [comment]
Присутсвует проблема с получением стартовой формы с регионального сервера для подтягивания телефона.
Логика не работает для завершенных процессов. Разбираюсь

**Comment by ASkosyr** [comment]
Добавил метод для получения значения переменной процесса (получение телефона из стартовой формы для завершенных процессов).
Пример вызова
https://test.region.igov.org.ua/wf/service/action/task/getProcessVariableValue?nProcessID=8965001&sVariableName=phone

**Comment by ASkosyr** [comment]
Пример запроса:
https://test.igov.org.ua/wf/service/action/event/getServiceHistoryReport?sDateAt=2016-02-09 00:00:00&sDateTo=2016-02-11 00:00:00

Пример результата
```csv
sID_Order,nID_Server,nID_Service,sID_Place,nID_Subject,nRate,sTextFeedback,sUserTaskName,sHead,sBody,nTimeMinutes,sPhone
0-101277690,0,687,6800000000,44674,,,,Надання довідки про те, що посвідчення батьків та дитини з багатодітної сім'ї не видавалося,,20911,+380 97 729 9676
0-88625055,0,740,6500000000,20045,,,,,Необхідно уточнити дані, за коментарем: не вірно вказані дані членів родини. Син - не відповідні ПІБ, бат - відсутні обов'язкові дані,,+380 97 225 5363
```

**Comment by RoOmel** [comment]
Протестировал ссылки, приведенные выше - актуальный результат отличается от ожидаемого

**Comment by RoOmel** [comment]
Первая ссылка должна быть

**Comment by RoOmel** [comment]
По ссылке
https://test.igov.org.ua/wf/service/action/event/getServiceHistoryReport?sDateAt=2016-02-09 00:00:00&sDateTo=2016-02-11 00:00:00
Ответ сервера
sID_Order,nID_Server,nID_Service,sID_Place,nID_Subject,nRate,sTextFeedback,sUserTaskName,sHead,sBody,nTimeMinutes,sPhone
0-101277690,0,687,6800000000,44674,,,,Надання довідки про те, що посвідчення батьків та дитини з багатодітної сім'ї не видавалося,,20911,+380 97 729 9676
0-88625055,0,740,6500000000,20045,,,,,Необхідно уточнити дані, за коментарем: не вірно вказані дані членів родини. Син - не відповідні ПІБ, бат - відсутні обов'язкові дані,,+380 97 225 5363
0-105450019,0,25,6300000000,20049,,,,Вклеювання фотокарток при досягненні особою віку 25 або 45 років,,9828,+380 66 111 2222
0-103875017,0,659,7400000000,44876,,,,Відправити звернення до міського голови,,13618,+380937730359
0-107825026,0,740,6500000000,20049,,,,Довідка про склад сім'ї,,1,+380 97 728 2593
0-107200010,0,1450,1200000000,20049,,,,Звернення громадян до Управління житлового господарства міської ради,,26,+380 50 777 7777
0-107202158,0,151,1200000000,20049,,,прийняття рішення про надання послуги,Експлуатаційний дозвіл для провадження діяльності на потужностях (об’єктах) з переробки неїстівних продуктів тваринного походження або з виробництва, змішування та приготування кормових добавок, преміксів і кормів,,,067 672 2615
0-107827596,0,1465,4600000000,46209,4,,,(загальна) - ПЕРЕРЕЄСТРАЦІЯ ПРИ ПЕРЕОБЛАДНАННІ БЕЗ ЗМІНИ НОМ.АГРЕГАТІВ,,10,+380 97 320 9244
0-107204720,0,734,6100000000,20049,,,Перевірка даних,Тернопіль ЦНАП - Виготовлення викопіювання в масштабі 1:500, 1:2000,,,380673592574
0-107830125,0,1471,4600000000,46209,5,,,(загальна) - Зміна анкетних данних власника транспортного засобу,,7,+380 97 320 9244
0-107205151,0,1397,,47010,,,Перевірка (запит по фізичним особам),(Загальна послуга) - Надання витягу з Єдиного державного реєстру МВС України,,,380979007382
0-107831843,0,1467,4600000000,46209,5,,,(загальна) - ПЕРЕРЕЄСТРАЦІЯ ПРИ ЗАМІНІ НОМЕРНОГО ЗНАКУ. ,,6,+380 97 320 9244
0-107833060,0,1397,,47010,,,Перевірка (запит по фізичним особам),(Загальна послуга) - Надання витягу з Єдиного державного реєстру МВС України,,,380979007382
0-107225019,0,1397,,47010,,,Перевірка (запит по фізичним особам),(Загальна послуга) - Надання витягу з Єдиного державного реєстру МВС України,,,380979007382
0-107834389,0,1468,4600000000,46209,,,,(загальна) - Перереєстрація транспортного засобу на нового власника по успадкуванню,,32,+380 97 320 9244
0-107275101,0,173,6300000000,47019,5,,,Обмін паспорта громадянина України в разі зміни (переміни) прізвища, імені або по батькові,,49,+380 98 675 0213
0-107875016,0,1469,4600000000,46209,,,,(загальна) - Реєстрація транспортного засобу привезеного з-за кордону ,,8,+380 97 320 9244
0-107300317,0,25,6300000000,47019,,,,Вклеювання фотокарток при досягненні особою віку 25 або 45 років,,8,+380 98 675 0213
0-107325010,0,63,5900000000,20049,,,,Проведення обстежень зелених насаджень, оформлення і надання відповідних документів на їх видалення,,2,+380 67 223 3445
0-107878440,0,1381,1200000000,47113,,,,Дніпродзержинськ - ЦНАП - Видача ордера на видалення зелених насаджень,,98,+380 67 536 4086
0-106050017,0,667,6100000000,20049,,,,Погодження режиму роботи об’єктів сфери торгівлі та сфери обслуговування населення.,,8806,+380 50 565 5555
0-107883960,0,25,6300000000,20049,,,,Вклеювання фотокарток при досягненні особою віку 25 або 45 років,,22,+380 97 728 2593
0-107327250,0,63,5900000000,20049,,,Підготовка документів Департаментом інфраструктури після прийняття рішення (3-й крок),Проведення обстежень зелених насаджень, оформлення і надання відповідних документів на їх видалення,,-1,+380 67 444 4444
0-107885358,0,740,6500000000,46066,,,,Довідка про склад сім'ї,,11,+380 93 563 5866
0-107351342,0,173,6300000000,47019,,,Перевірка вхідних даних,Обмін паспорта громадянина України в разі зміни (переміни) прізвища, імені або по батькові,Необхідно уточнити дані, за коментарем: ,,+380 98 675 0213
0-107897795,0,1464,4600000000,46209,5,,,(загальна) - ПЕРЕРЕЄСТРАЦІЯ НА НОВОГО ВЛАСНИКА ЗА ДОГОВ. КУПІВЛІ-ПРОДАЖУ,,11,+380 97 320 9244
0-107525012,0,1463,4600000000,46209,5,,,(загальна) - ЗНЯТТЯ З ОБЛІКУ ДЛЯ РЕАЛІЗАЦІЇ.,,8,+380 97 320 9244
0-102552208,0,740,6500000000,46066,,,Візит громадянина,Довідка про склад сім'ї,,-1,+380 93 563 5866
0-107899877,0,740,6500000000,46066,,,Візит громадянина,Довідка про склад сім'ї,,-1,+380 93 563 5866
0-107909210,0,4,1800000000,45927,,,Перевірка вхідних даних,Видача копій, витягів з розпоряджень міського голови, рішень, прийнятих міською радою та виконавчим комітетом,,,+380 98 338 3770
0-104150013,0,11,5600000000,20049,,,Обробка звернення,Відправити звернення до голови РДА,,-1,+380 97 728 2593
0-107912146,0,151,1200000000,20049,,,прийняття рішення про надання послуги,Експлуатаційний дозвіл для провадження діяльності на потужностях (об’єктах) з переробки неїстівних продуктів тваринного походження або з виробництва, змішування та приготування кормових добавок, преміксів і кормів,,,067 777 7777
0-108025019,0,775,5600000000,20049,,,Перевірка документів в Управлінні праці та соціального захисту населення (1-й етап),УПЗСН - Призначення державної соціальної допомоги малозабезпеченим сім’ям,,,+380 94 444 4444
0-108075054,0,4,3200000000,20049,,,Перевірка вхідних даних,Видача копій, витягів з розпоряджень міського голови, рішень, прийнятих міською радою та виконавчим комітетом,,,+380 97 728 2593
0-108226238,0,1450,1200000000,20049,,,Обробка звернення у канцелярії міської ради,Звернення громадян до Управління житлового господарства міської ради,,,+380 50 767 6767
0-108226842,0,1450,1200000000,20049,,,Обробка звернення у канцелярії міської ради,Звернення громадян до Управління житлового господарства міської ради,,,+380 68 535 3535
0-108250411,0,23,1800000000,20049,,,Прийняття рішення: доцільність запиту,Надання довідок незайнятому населенню про відсутність земельних ділянок для ведення ОСГ,,,+380980178173
0-89650015,0,740,6500000000,44798,,,,,,63358,+380 50 960 0041

**Comment by RoOmel** [comment]
После загрузке файла "serviceHistoryReport" на ПК, содержимое отличается от текста выше кодировкой, в экселевском файле крокозябры.

**Comment by ASkosyr** [comment]
При открытии файла нужно указать кодировку utf-8

Тогда файл откроется с корректным отображением символов

http://prntscr.com/a3wkpv
