### ISSUE TITLE
Добавить в шетдулер процесс по авто-генерации электронных очередей, с запасом на ближайший месяц, для всех ткстовых услуг

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1147]
- проверять - если свободных слотов нету, то генерить на больший период ,вплоть до полугодя, чтоб в запасе было слотов, на срок "около месяца"
- сдалать так, чтоб можно было легко добавлять другие электронные очереди, по которым точно так-же будут генериться автоматом слоты (например в названии электронной очереди писать префикс "_auto_" и перебирая все очереди - только по ним авто-генерировать (напомню, пока что автогенерить только одну тестовую очередь (там из названия будет видно что она тестовая))

- Класс где добавляются новые джобы шетдулера тут:
org.igov.run.schedule.JobsInitializer

- посмотреть образец вызова генерации слотов можно в сервисе "/buildFlowSlots" (ВАЖНО: не копипастить, а в крайнем случае просто общий код вынести в общий метод и вызывать просто его из нескольких мест, в т.ч. уже из сервиса текущего)

**Comment by maxline** [comment]
Видение реализации
1.	В класс JobsInitializer.java добавляем метод
private void **addBuilderFlowSlotsJob**(Scheduler scheduler) throws SchedulerException {
        JobDetail oJobDetail_BuilderFlowSlots_Standart = new JobDetail(**"oJobDetail_BuilderFlowSlots_Standart",
                "oJobDetail_BuilderFlowSlots_Group", JobBuilderFlowSlots.class**);

        CronTrigger oCronTrigger_EveryNight_Deep = new CronTrigger("oCronTrigger_EveryNight_Deep",
                "oCronTrigger_EveryNight_Group");
        try {
            LOG.info("oCronExpression__EveryNight_Deep...");
            CronExpression oCronExpression__EveryNight_Deep = new CronExpression("0 0 2 1/1 * ?");
            LOG.info("oCronExpression__EveryNight_Deep.setCronExpression...");
            oCronTrigger_EveryNight_Deep.setCronExpression(oCronExpression__EveryNight_Deep);
        } catch (Exception oException) {
            LOG.error("FAIL: ", oException.getMessage());
            LOG.debug("FAIL: ", oException);
        }
        if(!generalConfig.bTest()){
            LOG.info("scheduleJob...");
            scheduler.scheduleJob(oJobDetail_BuilderFlowSlots_Standart, oCronTrigger_EveryNight_Deep);
        }else{
            LOG.info("scheduleJob... SKIPED(test)!");
        }


2.	В пакет org.igov.run.shedule  добавляем  класс  JobBuilderFlowSlots   (аналогично классу JobEscalation)

public class** JobBuilderFlowSlots **extends IAutowiredSpringJob {

    private final static Logger LOG = LoggerFactory.getLogger(JobBuilderFlowSlots.class);
    @Autowired
    private FlowService flowService;
    public void execute(JobExecutionContext context) throws JobExecutionException {
        LOG.info("In QuartzJob - executing JOB at {} by context.getTrigger().getName()={}",
                new Date(), context.getTrigger().getName());
        try {
          
           ** //maxline:todo исправить на вызов на buildFlowSlots
            //maxline: nID_Flow_ServiceData получаем список всех тестовых услуг
            //maxline: startDate, StopDate - написать алгоритм  проверки - если свободных слотов нету, 
            //то генерить на больший период ,вплоть до полугодя, чтоб в запасе было слотов, на срок "около месяца"**
            
           ** flowService.buildFlowSlots**( nID_Flow_ServiceData, startDate, stopDate)
            
        } catch (CommonServiceException oException) {
            LOG.error("Bad: ", oException.getMessage());
            LOG.debug("FAIL:", oException);
        }
    }

**Comment by bvv4ik** [comment]
около того, только-ж еще должно быть:
    ```
@Override
    public void afterPropertiesSet() throws Exception {
        addEscalationJob(scheduler);
        addBuilderFlowSlotsJob(scheduler);
    }
```

**Comment by bvv4ik** [comment]
//maxline: nID_Flow_ServiceData получаем список всех тестовых услуг

и тут не всех тестовых услуг а всех тестовых Электронных очередей (сущности "Flow_ServiceData")

**Comment by maxline** [comment]
ок, тогда вопросы такие
1. как получить список тестовых услуг, их можно хардкодить, или надо парсить файл Flow_ServiceData.csv ?
2. как примерно должен выглядеть алгоритм получения startDate stopDate? какие методы возвращают наличие свободных слотов?

**Comment by bvv4ik** [comment]
1.ни в коем случае ни каких парсингов файлов)
через сущность (ДАО) получить массив элементов этой сущномти
2. stopDate - это "startDate + месяц"
а вот startDate либо текущая, либо, если на сегодня и ближайшее время слоты нагенерены и все заняты, то отступать в перед до тех пор, пока либо не закончатся сгенеренные, либо не начнутся свободные... но с учетом указанного лимита полугода...

**Comment by bvv4ik** [comment]
Привет, как там успехи по таске?

**Comment by maxline** [comment]
Реализована 1-я часть задания. Для очереди 12 test_queue_cancel  проверяется наличие свободных слотов (на срок 20 рабочих дней), в случае нехватки слотов, генерируются новые слоты. 
Слоты генерируются помесячно, пока не будет выполнено условие наличия свободных 20 рабочих дней,  но максимальный срок генерации полгода.

**Comment by bvv4ik** [comment]
по поводу суффикса auto в названии очереди, сейчас в 
flow_ServiceData.csv
только одна очередь с суффиксом auto
1;Test;1;1;_test_dnepr_mvd-1_auto

а для тестирования алгоритма, нужно хотя-бы парочку таких очередей
[18:53:50] Сергей: можно исправить очередь
12;_test_queue_cancel;358;1;_test_queue_cancel
на
12;_test_queue_cancel;358;1;_test_queue_cancel_auto
или мне лучше лучше csv-шку не трогать?

**Comment by Koffeek** [comment]
Добавил суффикс для потоков №4 и 20 (обе очереди по заграну). Что именно тестировать?

**Comment by maxline** [comment]
спасибо! на тестирование передам завтра, и там опишу что тестировать.

**Comment by maxline** [comment]
Передаю на тестирование. 
Описание функционала ниже.

Считаем что:
 - в месяце всего 30 календарных дней;
 - в месяце 20 рабочих дней;
 - полгода - 180 календарных дней
 Для функции автогенерации новых слотов в очереди, такое округление допустимо.
 
 Автогенерация запускается по шедулеру ежедневно в 2 часа ночи.
 Автогенерация выполняется только для очередей, у которых в названии бизнес процесса есть суффикс auto.
Пример: 
Услуга: "176;Видача/заміна паспорта громадянина для виїзду за кордон" 
Очередь: "4; ДМС, Днепр, Поля 1; 63; 11; dnepr_dms_passport_auto"

Принцип работы. Алгоритм проверяет набирается ли свободных 20 рабочих дней на периоде 
(текущая дата, текущая дата + 180 дней). Если нет, то запускает построитель слотов на периоде
(текущая дата, тукущая дата + 30 дней), последний день в период не входит. 
Проверяет появилось ли 20 свободных рабочих дней, если да - то финиш, если нет - 
запускаем построитель слотов на периоде(текущая дата + 30 дней, текущая дата + 60 дней) 
последний день в период не входит. Если построили слотов на 180, и так и не набралось
20 свободных рабочих дней - то финиш.

**Comment by maxline** [comment]
Что потестировать.
1.	Автогенератор должен запускаться по шедулеру каждый день в 2 часа ночи.
2.	Проверить, что то срабатывает для всех очередей с признаком auto (суффикс sID_BP)
3.	Если по одной услуге, есть разные очереди (flow_serviceData), нужно проверить  что новые слоты генерируются независимо по каждой очереди, не перезатирают друг друга и т.д.
4.	Проверить автогенерацию слотов если начальная дата - разный день недели пн-пт, а так же для выходных (должен корректно отрабатывать в любой день недели и любой день месяца, любой месяц в т.ч. февраль с 28 днями).
5.	Проверить ситуацию когда свободные слоты частично уже сгенерированы (или частично заняты) в разных комбинациях (одним куском, несколькими кусками). Проверять ситауцию отдельно когда слотов нет потому что они не сгенерированы и еще, и когда нет, потому что они заняты. Проверять, когда занято много слотов (на несколько месяцев), чтобы посмотреть что построитель не будет строить новые слоты после 180 дней.
6.	Тест на корректность передаваемых данных (исключения). Например если вообще нет услуг с признаком auto, если в качестве числовых параметров Flow_ServiseData.csv и ServiceData.csv, заданы неверные параметры (строки, null-ы и т.д.)
7.	Другие тесты и проверки необходимые по мнению тестировщиков.

**Comment by RoOmel** [comment]
Добрый день.
Задача реализована уже в боевой версии или ещё нет?
Дата для тестирования от 26 марта какая-то сомнительная.
