### ISSUE TITLE
Откорректировать контент отсылаемого письма, при замечании чиновника

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1148]
Образец:
https://dl.dropboxusercontent.com/u/50541317/eGov/portal/status/start.html#p=письмо

Реализация находится в: org.igov.io.mail.NotificationPatterns.sendTaskEmployeeQuestionEmail

ВАЖНО:
Учесть, что используемый производный метод createTable_TaskProperties используется не только в этом методе, потому если даже его и править, то с учетом этого обстаятельства.
А лучше всего сделать его копию и уже ее адаптировать под задачу

**Comment by PaulLuchyn** [comment]
Принимаю в работу

**Comment by sergeygorban** [comment]
Текст отсылаемого письма соответствует образцу
