### ISSUE TITLE
При заполнении формы заявки всегда размещать внизу, перед кнопкой сабмита текст-согласие на хранение и обработку персональных данных.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1149]
Текст: "Відправляючи заявку, Ви надаєте згоду на обробку персональних даних"

**Comment by AVATOR** [comment]
добавил текст, на скрине видно где.
http://pix.toile-libre.org/upload/original/1456136028.png

если не там просьба вернуть подправлю

**Comment by AVATOR** [comment]
подправил вывод сообщения
http://pix.toile-libre.org/upload/original/1456143044.png

**Comment by sergeygorban** [comment]
Текст отображается. Все отлично
