### ISSUE TITLE
Рендеринг: Определить при клике на услугу на центральном портале

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#115]
на /i/portal-js

Только после реализации:
https://github.com/e-government-ua/i/issues/113

Рендеринг:
- На фронте при клике на услугу определить, обслуживается ли услуга порталом и в зависимости от этого активировать форму работы с услугой или выводить внешнюю ссылку.
- На фронте на основе дерева данных определить, является ли услуга геозависимой и активировать выбор региона или деактировать селект.
- На фронте определить, предоставляется ли услуга в данном регионе и в завимости от результата вывести соотв. информацию или выводить следующую строку.

В соответствии с логикой:
https://docs.google.com/document/d/19nDtuDfB2faxBrA5zhlSxgFaXp1f4bTnkX7akwJVKno/edit

И структурой:
https://docs.google.com/spreadsheets/d/1UNPmkvpXwgFnSnjZ7nf4Fpr_hKm0JDxpRLBUshwNzWY/edit#gid=1718514141

**Comment by Kiaba** [comment]
На даний момент працюють наступний список url:
1) http://i.gov.ua/index.html#/service/link - послуга першого типу (Пользователь переходит по ссылке на услугу, реализованную на сторонней платформе). Потребує адаптаію макета.
2) http://e-government-ua.github.io/i/#/service/built-in/default - послуга четвертого типу (Все этапы услуги реализованы на платформе Портала).Послуга також не є геозалежною. Потребує адаптації макету.
3) http://e-government-ua.github.io/i/#/service/built-in/region - послуга четвертого типу (Все этапы услуги реализованы на платформе Портала).Послуга також є геозалежною. Потребує адаптації макету.

**Comment by Kiaba** [comment]
Добавив перенаправлення:
- #/service/{id}/link - якщо послуга першого типу
- #/service/{id}/built-in - якщо послуга четвертого типу

**Comment by bvv4ik** [comment]
а как эти перенаправления работают?

**Comment by Kiaba** [comment]
Для того, щоб завантажити профіль послуги необхідно перейти за посиланням:
#/service/{id}

Якщо у нас послуга першого типу спрацьовує перенаправлення на #/service/{id}/link
Якщо у нас послуга четвертого типу спрацьовує перенаправлення на #/service/{id}/built-in

**Comment by bvv4ik** [comment]
а сами линки будут браться из элемента структуры дерева всех услуг?

**Comment by Kiaba** [comment]
Да.

**Comment by bvv4ik** [comment]
отлично, главное будет потом это подвязать к генерируемой структуре на веб-е...
чтоб оно целостно заработало

**Comment by Kiaba** [comment]
Добавив перенаправлення:
 - #/service/{id}/built-in/default - якщо послуга четвертого типу і незалажна від регіону.
 - #/service/{id}/built-in/region - якщо послуга четвертого типу і залежна від регіону.

**Comment by bvv4ik** [comment]
готово
