### ISSUE TITLE
Реализовать автоматическую установку календарика выбора даты на форме услуги - в режим года

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1150]
- Сейчас он устанавливается умолчательно в режим дня месяца, и только при клике переходим вначале на месяц а потом на год.
- умолчательность не означает что нельзя выбрать месяц и день, а просто начинает путь выбора с этого уровня.
- этот бутстраповский компонент поддерживает такой режим.

Для тестирования можно использовать эту услугу:
https://test.igov.org.ua/service/1397/general

Как есть сейчас при первом клике на иконку календарика:
![image](https://cloud.githubusercontent.com/assets/4208821/12983019/1b0cd9c4-d0f0-11e5-9881-832669d271f8.png)

Как должно быть при первом клике:
![image](https://cloud.githubusercontent.com/assets/4208821/12983056/38362474-d0f0-11e5-9ed9-0c28c189ce62.png)

**Comment by iRipVanWinkle** [comment]
Я  его заменил бы на более красивый :)
Я смогу заняться задачами, которые на мне, на следующей неделе.

**Comment by bvv4ik** [comment]
я опасаюсь, что другой(более красивый) вызовет еще больше пожеланий по настройкам...
потому пока постараемся обойтись малой кровью.
ок?

**Comment by bvv4ik** [comment]
получится поправить календарик?
а то у нас версия вот-вот...

**Comment by Sokhatsky** [comment]
Перевірено на версіях послуги:
https://test.igov.org.ua/service/1397/general/
https://test-version.igov.org.ua/service/1397/general/
працює
