### ISSUE TITLE
Поправить текст диалога, после сабмита формы услуги, при подаче заявки

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1151]
Образец:
https://docs.google.com/document/d/1nQKp8nFWeGg315VQtMtotzW6Ytn7XVYAqGBPSfkPGgg/edit

**Comment by sergeygorban** [comment]
1. Скажите пожалуйста, Тестирование выполнять на https://test.igov.org.ua/ ?
2. Данный текст появляется при создании любого документа на портале или нет?

**Comment by VadimGulich** [comment]
Скажите пожалуйста, Тестирование выполнять на https://test.igov.org.ua/

**Comment by sergeygorban** [comment]
При успешной подачи заявки, текст сообщения соответствует приведенному тексту в примере. Дефектов не выявлено
