### ISSUE TITLE
Проблема с кодировкой — важно!

### ISSUE THREAD

**Issue by chemfind** [e-government-ua/i#1161]
Проблема с кодировкой страниц 
![igov_org_ua_ _ _ _](https://cloud.githubusercontent.com/assets/7547101/13050210/8c62a358-d3fa-11e5-966c-f0d9474c22ba.jpg)
— важно!

**Comment by Koffeek** [comment]
@chemfind сейчас всё нормально отображается. Возможно был некоторый сбой.

**Comment by chemfind** [comment]
Опять проблема с кодировкой (Chrome, Safari, Android)
![igov_org_ua_ _ _ _](https://cloud.githubusercontent.com/assets/7547101/13168755/76fe44fe-d6e8-11e5-8f22-3f6f99d6ec46.jpg)

**Comment by ezhikus** [comment]
Подтверждаю, проблема случается время от времени. Видел вчера и сегодня. Chrome, Windows.

**Comment by bvv4ik** [comment]
воспроизвести не получается, нужно четкий алгоритм воспроизведения. иначе непонятно как устранять...

**Comment by bvv4ik** [comment]
реализован ряд доработок, которые должны помочь это решить, но т.к. проверить не получается, то выльем в бой, и уже по факту эксплуатации станет видно...

**Comment by bvv4ik** [comment]
протестировать получится видать уже только на практике на проде, т.к. на тесте повторить так ни разу и не удалось

**Comment by nazarenkod** [comment]
за неделю воспроизвести не смог...задачу закрываю
