### ISSUE TITLE
Реализовать отображение ниже футера иконок спонсоров со ссылками

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1163]
Под блоками Громадянам, Волонтерам, Держорганам размещаем еще один блок "Спонсори iGov" (эту надпись сделать таким же стилем, как "Громадянам").

И там разметить эти логотипы (со ссылками на соответствующий сайт).

- [x] 1) Каждый раз отображать рандомно
- [x] 2) высота каждого по умолчанию 50 пикселей (ширина пропорцилональнв)
- [x] 3) изначальный список хранить в виде единого JSON-обьекта-массива, где указывать путь к изображению, УРЛ и опциональній параметр высоты (а уже пормироваться все остальное должно отталкиваясь от этого единого обьекта-массива)

Пример:

- [x] 4) Разместить пока два элемента:

- http://contact-call.com/ 
 ![image](https://cloud.githubusercontent.com/assets/4208821/13086277/3815c57c-d4eb-11e5-8c4f-4314289567f9.png)

- http://www.de-novo.biz/uk/
![image](https://cloud.githubusercontent.com/assets/4208821/13086284/43434db6-d4eb-11e5-88c9-2890df892e85.png)

**Comment by sergeygorban** [comment]
Логотипы отображаются случайно, высота всех соответствует требованию
