### ISSUE TITLE
Отобразить ФИО авторизованного пользователя и ссылку "Выход" в верхнем-правом углу, для профиля ternopil.igov.org.ua

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1164]
точно так-же, как это в стандартном профиле сейчас отображается

**Comment by cheese2602** [comment]
Протестировано на https://test.ternopol.igov.org.ua . ФИО пользователя после авторизации через Bank ID отображается. Кнопка "Выход" работает.
