### ISSUE TITLE
При заходе в профиль услуги в регионе или городе - отображать в поле с OrganJoin в т.ч. те позиции, у которіх КОАТУУ пустой

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1165]

**Comment by GrekD** [comment]
https://test.igov.org.ua/service/160/general
проверять по полю:
Митниця, де здійснюватиметься митне оформлення товару:

**Comment by sergeygorban** [comment]
Какова цель тестирования данной задачи?

**Comment by sergeygorban** [comment]
Объясните пожалуйста что это такое "в поле с OrganJoin в т.ч. те позиции, у которіх КОАТУУ пустой"?

**Comment by sergeygorban** [comment]
Дайте более понятное описание задачи для тестирования

**Comment by bvv4ik** [comment]
@GrekD подтвердила что все работает
