### ISSUE TITLE
Футер накладывается на инструкцию услуги

### ISSUE THREAD

**Issue by chemfind** [e-government-ua/i#1168]
Футер накладывается на инструкцию услуги:
Например:
https://igov.org.ua/service/1/instruction
![igov_org_ua_ _ _ _](https://cloud.githubusercontent.com/assets/7547101/13144306/789891d4-d652-11e5-8ccd-74fa48445746.jpg)

https://igov.org.ua/service/654/instruction
![igov_org_ua_ _ _ _](https://cloud.githubusercontent.com/assets/7547101/13144343/be7726fc-d652-11e5-886e-263ca6e3770a.jpg)

**Comment by bvv4ik** [comment]
готово

**Comment by chemfind** [comment]
проблема осталась (Chrome, Safari, + Android)
![igov_org_ua_ _ _ _](https://cloud.githubusercontent.com/assets/7547101/13177854/6056875c-d724-11e5-97f0-862c266ea90c.jpg)
![igov_org_ua_ _ _ _](https://cloud.githubusercontent.com/assets/7547101/13177876/7aa5dafe-d724-11e5-9d9d-18903974b019.jpg)

**Comment by bvv4ik** [comment]
все исправлялось (и исправляется всегда) вначале на тестовом (альфе)

на боевой все попадает только потом, как пправило с версией

**Comment by 3ugol** [comment]
по адресам 
https://igov.org.ua/service/654/instruction
https://igov.org.ua/service/1/instruction

в  Chrome Версия 48.0 и Firefox 44.0
накладывания футера не обнаружено
