### ISSUE TITLE
Оживить переключение между табами на центральном портале

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#117]
на /i/portal-js

Только после реализации:
https://github.com/e-government-ua/i/issues/114

Оживить переключение между табами на центральном портале (пояснять что разделы пока не работают)

**Comment by Kiaba** [comment]
http://e-government-ua.github.io/i/

Переходи між сторінками працюють. Залишилось адаптувати макети.

**Comment by Kiaba** [comment]
Все працює.
