### ISSUE TITLE
Ошибка на тестовом портале.

### ISSUE THREAD

**Issue by lesha1980** [e-government-ua/i#1170]
Возникает ошибка на центральном тестовом портале. 
![error](https://cloud.githubusercontent.com/assets/12561441/13199096/49f1a5ea-d824-11e5-8a60-cbc12195e540.jpg)

**Comment by bvv4ik** [comment]
проверял, вроде все работает, ошибок не пишет

![image](https://cloud.githubusercontent.com/assets/4208821/13202192/421e0d74-d89a-11e5-9321-b8be99711f24.png)

**Comment by lesha1980** [comment]
Уже да...
