### ISSUE TITLE
Реализовать корректную систему бэкапинга хранилища MongoDB

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1171]

**Comment by Skoffer** [comment]
Вариант номер 1 (на ревью)
Раз в день полный дамп. Инкрементальный дамп раз в час.

`#!/bin/bash
set -eo pipefail
#
# MongoDB Backup Script
# Author Vyacheslav Lenskyy (pstu@list.ru)
#
#=====================================================================
# Set the following variables to your system needs
# (Detailed instructions below variables)
#=====================================================================

# Database name to specify a specific database only e.g. myawesomeapp
# Unnecessary if backup all databases
# DBNAME=""

# Username to access the mongo server e.g. dbuser
# Unnecessary if authentication is off
# DBUSERNAME=""

# Password to access the mongo server e.g. password
# Unnecessary if authentication is off
# DBPASSWORD=""

# Database for authentication to the mongo server e.g. admin
# Unnecessary if authentication is off
# DBAUTHDB=""

# Host name (or IP address) of mongo server e.g localhost
DBHOST="127.0.0.1"

# Port that mongo is listening on
DBPORT="27017"

# Backup directory location e.g /backups
BACKUPDIR="/var/backups/mongodb"
OPLOGFILE="$BACKUPDIR/lastoplog"

#======================================================================
# Choose Compression type. (gzip or bzip2)
COMP="gzip"

#=========================================================================
shellout () {
    if [ -n "$1" ]; then
        echo $1
        exit 1
    fi
    exit 0
}

#=====================================================================

PATH=/usr/local/bin:/usr/bin:/bin
DATE=`date +%Y-%m-%d_%Hh%Mm`                      # Datestamp e.g 2002-09-21
HOD=`date +%H`					  # Hour of day

LOGFILE=$BACKUPDIR/$DBHOST-`date +%H%M`.log       # Logfile Name
LOGERR=$BACKUPDIR/ERRORS_$DBHOST-`date +%H%M`.log # Logfile Name
OPT=""                                            # OPT string for use with mongodump

# Do we need to use a username/password?
if [ "$DBUSERNAME" ]; then
    OPT="$OPT --username=$DBUSERNAME --password=$DBPASSWORD"
    if [ "$REQUIREDBAUTHDB" = "yes" ]; then
        OPT="$OPT --authenticationDatabase=$DBAUTHDB"
    fi
fi

# Do we use oplog for point-in-time snapshotting?
if [ "$OPLOG" = "yes" ]; then
    OPT="$OPT --oplog"
fi

# Do we need to backup only a specific database?
if [ "$DBNAME" ]; then
  OPT="$OPT -d $DBNAME"
fi

# Create required directories
mkdir -p $BACKUPDIR/{daily,hourly} || shellout 'failed to create directories'

# IO redirection for logging.
touch $LOGFILE
exec 6>&1           # Link file descriptor #6 with stdout.
                    # Saves stdout.
exec > $LOGFILE     # stdout replaced with file $LOGFILE.

touch $LOGERR
exec 7>&2           # Link file descriptor #7 with stderr.
                    # Saves stderr.
exec 2> $LOGERR     # stderr replaced with file $LOGERR.

# Database dump function
dbdump () {
    STR="mongodump --host=$DBHOST:$DBPORT --out=$1 $OPT"
    eval $STR
    [ -e "$1" ] && return 0
    echo "ERROR: mongodump failed to create dumpfile: $1" >&2
    return 1
}

# Compression function plus latest copy
compression () {
    SUFFIX=""
    dir=$(dirname $1)
    file=$(basename $1)
    if [ -n "$COMP" ]; then
        [ "$COMP" = "gzip" ] && SUFFIX=".tgz"
        [ "$COMP" = "bzip2" ] && SUFFIX=".tar.bz2"
        echo Tar and $COMP to "$file$SUFFIX"
        cd "$dir" && tar cf - "$file" | $COMP -c > "$file$SUFFIX"
        cd - >/dev/null || return 1
    else
        echo "No compression option set, check advanced settings"
    fi

 #delete original file
 rm -rf "$1"

 return 0
}

# Hostname for LOG information
if [ "$DBHOST" = "localhost" -o "$DBHOST" = "127.0.0.1" ]; then
    HOST=`hostname`
    if [ "$SOCKET" ]; then
        OPT="$OPT --socket=$SOCKET"
    fi
else
    HOST=$DBHOST
fi


if [ "$HOD" = "01" -o ! -e $OPLOGFILE ]; then
    echo Full backup
    FILE=$BACKUPDIR/daily/$DATE
    dbdump $FILE && compression $FILE
    rm -r $BACKUPDIR/hourly/*
else 
    echo Incremental backup
    FILE=$BACKUPDIR/hourly/$HOD
    # Get last recorded oplog position
    LASTOPLOG=`cat $OPLOGFILE`
    OPT="$OPT --db=local --collection=oplog.rs --query='{ \"ts\" : { \$gt : $LASTOPLOG } }'"
    dbdump $FILE && compression $FILE
fi

#record last oplog
LASTOPLOG=$(mongo $DBHOST:$DBPORT/local --quiet --eval 'db.oplog.rs.find().sort({$natural:-1}).limit(1).next().ts')
echo $LASTOPLOG > $OPLOGFILE`
