### ISSUE TITLE
Estonian-eID et al.

### ISSUE THREAD

**Issue by landswellsong** [e-government-ua/i#1175]
Есть Эстонская карточка и желание покодить на благо родины. Нужна ли в IGov (есть ли уже?) поддержка аутентификации при помощи служб 3-х государств? Например иностранец хочет получить госуслугу и аутентифицируется своей ID-картой. 

ПС: извините, если issue не туда, куда надо, думаю рано добавляться в Slack

**Comment by bvv4ik** [comment]
к сожалению те средства аутентификации, которые есть на текущий момент - не предполагают "аутентификации при помощи служб 3-х государств"... хотя потребность такая есть...
если есть конкретные технические решения позволяющие это реализовать - готовы выслушать...

а вообще все такие предложения прошу в iForum-репозиторий
данный репозиторий только для уже готовых и утвержденных к реализации ишью

**Comment by landswellsong** [comment]
@bvv4ik спасибо за информацию.
