### ISSUE TITLE
[S1] в послузі "Перереєстрація транспортного засобу на нового власника за договором купівлі-продажу" блок в рядку "*Бажана дата візиту до МРЕВ:"

### ISSUE THREAD

**Issue by 3ugol** [e-government-ua/i#1176]
os Windows XP SP2/ Chrome Версия 48.0.2564.116

Облать Київ місто Київ
відсутня можливість заповнити обов'язковий рядок "*Бажана дата візиту до МРЕВ:"

https://test.igov.org.ua/service/1464/general/place/built-in/region/5/city/6
![1](https://cloud.githubusercontent.com/assets/17325484/13293442/5c269b92-db28-11e5-90e6-7bc640dba645.JPG)

**Comment by manwhowins** [comment]
https://github.com/e-government-ua/i/issues/1083
