### ISSUE TITLE
Реализовать поддержку системного тега даты закрытия таски, при экспорте статистики

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1177]
${sDateClose}

**Comment by dmitrijzabrudskij** [comment]
работает:)
одна просьба: можно время в 24-часовой формат перевести?

сейчас так отображается: УПСЗН Амур-Нижньодніпровського району, м. Дніпропетровськ;0-112025017;19.02.2016 06:10:06;БІЛЯВЦЕВ;25.02.2016 01:09:24;attr4

это 18:10:06 и 13:09:24 соответственно

**Comment by bvv4ik** [comment]
формат даты и времени - указывается задаваемым в пропертях параметром.. можно любой формат там указывать

**Comment by dmitrijzabrudskij** [comment]
все работает. можно закрывать. спасибо!
