### ISSUE TITLE
Написать сервис смены пароля пользователя в Activiti

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1178]
Контроллер: ActionTaskCommonController
Название: changePassword
Параметры:
sLogin - строка-логин того кто меняет пароль
Метод: POST
в теле передавать строку-обьект JSON:
{
"sLoginOwner":"user" - строка-логин учетки, в которой меняется пароль
,"sPasswordOld":"123" - строка-старый пароль
,"sPasswordNew":"1231" - строка-новый пароль
}

**Comment by lesha1980** [comment]
Протестировать сервис можно с помощью запроса get-запроса. Я на время тестирования оставил возможность взаимодействия с сервисом через GET-метод.

**Comment by sergeygorban** [comment]
Запрос 
https://test.region.igov.org.ua/wf/service/action/task/changePassword?sLoginOwner=it190968gss&sPasswordOld=1q2q3q4q5q6q&sPasswordNew=1
Ответ
{
:    "userId"
:   :"it190968gss", 
:   "userEmail" : "sergey.gorban.cc@gmail.com", 
:   "userFirstName":"??????", 
:   "userLastName":"???????"
}
Значение параметров с вопросами

**Comment by sergeygorban** [comment]
Запрос: https://test.region.igov.org.ua/wf/service/action/task/changePassword?sLoginOwner=it190968gss&sPasswordOld=1+1=2qawsedrftgyhЫФВАПР,?qwedgqazwsxedcrfvtgb()!@&sPasswordNew=1+1=2qawsedrftgyhЫФВАПР,?qwedgqazwsxedcrfvtgb()!@#$&

Ответ: { "userId":"it190968gss", "userEmail" : "sergey.gorban.cc@gmail.com", "userFirstName":"??????", "userLastName":"???????"}

Пароль изменился в учетку на https://test.region.igov.org.ua/ зайти не смог

**Comment by sergeygorban** [comment]
GET https://test.region.igov.org.ua/wf/service/action/task/changePassword?sLoginOwner=it190968gss&sPasswordOld=1q2q3q4q5q6q&sPasswordNew=1q2q3q4q5q6q

**Comment by sergeygorban** [comment]
Передать в запросе некорректный старый пароль
GET https://test.region.igov.org.ua/wf/service/action/task/changePassword?sLoginOwner=it190968gss&sPasswordOld=1&sPasswordNew=1q2q3q4q5q6q
Ответ
{"code":"BUSINESS_ERR","message":"Password 1 is wrong"}

Ошибка на мой взгляд не информативна

**Comment by sergeygorban** [comment]
Передать пустое значение старого пароля
GET https://test.region.igov.org.ua/wf/service/action/task/changePassword?sLoginOwner=it190968gss&sPasswordOld=&sPasswordNew=1q2q3q4q5q6q
Ответ
{"code":"BUSINESS_ERR","message":"Password  is wrong"}
Ошибка на мой взгляд не информативна

**Comment by sergeygorban** [comment]
Передать пустое значение нового пароля
GET https://test.region.igov.org.ua/wf/service/action/task/changePassword?sLoginOwner=it190968gss&sPasswordOld=1q2q3q4q5q6q&sPasswordNew=
Ответ
{ "userId":"it190968gss", "userEmail" : "sergey.gorban.cc@gmail.com", "userFirstName":"??????", "userLastName":"???????"}
Сервис установил новый пароль, в учетку доступа нет
Обратно установить пароль можно отправив запрос с пустым старым паролем
GET https://test.region.igov.org.ua/wf/service/action/task/changePassword?sLoginOwner=it190968gss&sPasswordOld=&sPasswordNew=1q2q3q4q5q6q

**Comment by lesha1980** [comment]
1. userFirstName и userLastName  — это похоже на траблы с кодировкой. В базе имя и фамилия есть, но кодировка не соответствует, похоже. Вполне возможно, что эти данные в базу так и записались.
2. Я не думаю, что сервис должен выполнять проверку корректности введенного пароля по регулярному выражению. Его функция менять изменять пароль. Насколько понимаю, эта проверка должна выполняться на клиентском уровне.
3. Какой род ошибок по вашему мнению более информативен?

**Comment by sergeygorban** [comment]
Дай свой скайп для связи

**Comment by antonlegkiy** [comment]
dn200690lav

воскресенье, 17 апреля 2016 г. пользователь sergeygorban написал:

**Comment by lesha1980** [comment]
Мой Скайп lesha8021

**Comment by sergeygorban** [comment]
Вывод после тестирования сервиса:
1. Нет валидации используемых символов для нового пароля
2. Нет валидации на количество символов для нового пароля
3. Если забыт старый пароль, то выполнить смену пароля невозможно
