### ISSUE TITLE
Реализовать новую структуру работы с моим журналом, поиском заявок и просмотра ее профиля

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1179]
- [x] 1) При заходе в Мой Журнал без авторизации, должен быть такой интерфейс:
https://dl.dropboxusercontent.com/u/50541317/eGov/portal/start.html#p=единый_раздел
![image](https://cloud.githubusercontent.com/assets/4208821/13337356/91e2b4b8-dc23-11e5-8d0f-8965045776e8.png)

- [x] 2) При заходе в Мой Журнал с авторизацией, должен быть такой интерфейс:
![image](https://cloud.githubusercontent.com/assets/4208821/13337230/e7c4b1fc-dc22-11e5-818a-1a563bf7a7e9.png)
при клике на "Детальніше" должно быть то что в п.3.

- [x] 3) После поиска и нахождения заявки без авторизации, должен быть такой интерфейс:
https://dl.dropboxusercontent.com/u/50541317/eGov/portal/start.html#p=звернення__неавторизований_користувач_

![image](https://cloud.githubusercontent.com/assets/4208821/13337427/fd0bbfdc-dc23-11e5-8432-f957aa62b6aa.png)

- [x] 4) После поиска и нахождения заявки с авторизацией, но при этом заявка не пренадлежит авторизованному, должен быть такой интерфейс:
https://dl.dropboxusercontent.com/u/50541317/eGov/portal/start.html#p=звернення__користувач__-_не_э_автором__

![image](https://cloud.githubusercontent.com/assets/4208821/13337437/05137bac-dc24-11e5-99d3-5af2c9d71602.png)

- [x] 5) После поиска и нахождения заявки с авторизацией, и заявка пренадлежит авторизованному, должен быть такой интерфейс:

- [x] 5.1 открытое:
https://dl.dropboxusercontent.com/u/50541317/eGov/portal/start.html#p=звернення__є_повідомлення_

![image](https://cloud.githubusercontent.com/assets/4208821/13337374/aa55e84e-dc23-11e5-95d7-40ad9187bdbb.png)

- [x] 5.2 закрытое:
https://dl.dropboxusercontent.com/u/50541317/eGov/portal/start.html#p=звернення__закрите_

![image](https://cloud.githubusercontent.com/assets/4208821/13337379/b2124e4c-dc23-11e5-86a6-290c943fc56a.png)

- [x] 5.3 с замечанием:
https://dl.dropboxusercontent.com/u/50541317/eGov/portal/start.html#p=звернення__зауваження__

![image](https://cloud.githubusercontent.com/assets/4208821/13337386/ba5e64c8-dc23-11e5-94bc-b1d095e5ce9b.png)

**Comment by IrynaAndronik** [comment]
1) При входе в Мой Журнал без авторизации под надписью "або увійдіть в систему для перегляду подій щодо усіх Ваших звернень та документів" наличие "Картка киянина", в примере этого нет. 
![bug](https://cloud.githubusercontent.com/assets/16196477/14076411/07b4bfe0-f4ea-11e5-83ce-ad366f3cdf74.JPG)

**Comment by IrynaAndronik** [comment]
4) После поиска и нахождения заявки с авторизацией, но при этом заявка не принадлежит авторизованному, появляется сообщение об ошибке вместо ожидаемого интерфейса 
![bug1](https://cloud.githubusercontent.com/assets/16196477/14076657/790425f8-f4ec-11e5-8ba7-593db8c4e74d.JPG)

**Comment by nazarenkod** [comment]
По пунктам: 
1). 
![1](https://cloud.githubusercontent.com/assets/13256486/15071613/92da70f0-1395-11e6-9312-6f0f24d7f617.jpg)
Все ок.
2) 
![2](https://cloud.githubusercontent.com/assets/13256486/15071865/6f25f0ce-1397-11e6-83c7-ed13fb5b1246.jpg)
Все ок, только не понятно что имелось в виду "при клике на "Детальніше" должно быть то что в п.3."
3) 
![3](https://cloud.githubusercontent.com/assets/13256486/15071923/ec4da9e8-1397-11e6-8fd9-909958c84369.jpg)
Есть отличие от шаблона - выделено на скриншоте.
4)
![4](https://cloud.githubusercontent.com/assets/13256486/15072017/9c223c4e-1398-11e6-84a4-0cf22abb2c18.jpg)

Все ок.

На данный момент не работает поиск на дашборде и как следствие невозможно отработать заявку. Отпишите пзж здесь, как починят
