### ISSUE TITLE
Добавить в POM-ы (в первую очередь wf-*) - наш репозиторий Nexus

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#118]

**Comment by admiral-diver** [comment]
Мы добавили Nexus в корневой pom. Я думаю задачу можно закрыть по неактуальности. Если что не так - перееоткроем.

**Comment by bvv4ik** [comment]
Так:
1) мы-ж корневой пом еще не создали окончательно и не заюзали всеми!
2) у нас-жеж  не один корневой ПОМ, т.к., например, на бэке центрального сайта будет хоть и очень похожий, но все-же свой собственный пом (по началу вообще без бизнес-процессов)
3) в ПОМ-е ядра - у нас точно так-же могут юзаться либы вспомогательных проектов(например Редис), которые находятся также только в нашем Нексус-е..

потому, указания этого нашего репозитория, среди прочих, почти во всех ПОМ-ах должна быть обязательно! (разве что, пока, кроме проекта Редис-а)
