### ISSUE TITLE
Доработать сервис выгрузки данных, для поддержки выгрузки только закрытых тасок из истории, за указанный период

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1181]
- Дорабатываемый сервис: /downloadTasksData
- Добавить опциональные параметры
sTaskEndDateAt - дата "на/с" в формате yyyy-MM-dd
sTaskEndDateTo - дата "по/к" в формате yyyy-MM-dd
- реализовать так, чтоб если заданы эти параметры-фильтры, выборка происходила по более оптимальному сценарию (т.е. вначале выбирались именно таски исходя из этого критерия, а потом уже все остальное)

**Comment by ASkosyr** [comment]
Пример запроса

```
https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?&sID_BP=dnepr_spravka_o_doxodax&sDateAt=2016-03-01&sDateTo=2016-04-01&saFields=${nID_Task};${sDateCreate};${area};;;0;${bankIdlastName}%20${bankIdfirstName}%20${bankIdmiddleName};4;${aim};${date_start};${date_stop};${place_living};${bankIdPassport};1;${phone};${email}&sID_Codepage=win1251&nASCI_Spliter=18&sDateCreateFormat=dd.mm.yyyy%20hh:MM:ss&sFileName=dohody.dat&sTaskEndDateAt=2016-03-01&sTaskEndDateTo=2016-04-01
```

**Comment by ASkosyr** [comment]
Получить все законченные задачи по конкретному процессу (Для процесса dnepr_spravka_o_doxodax)

```
https://test.region.igov.org.ua/wf/service/history/historic-task-instances?processDefinitionKey=dnepr_spravka_o_doxodax&finished=true
```

**Comment by sergeygorban** [comment]
Запрос:

**Comment by sergeygorban** [comment]
https://test.region.igov.org.ua/wf/service/action/task/
downloadTasksData?
&sID_BP=dnepr_cnap_225
&sDateAt=2016-03-01
&sDateTo=2016-04-01
&saFields=${nID_Task};
${sDateCreate};${area};;;0;
${bankIdlastName}%20
${bankIdfirstName}%20
${bankIdmiddleName};4;
${aim};${date_start};
${date_stop};${place_living};
${bankIdPassport};1;${phone};
${email}
&sID_Codepage=win1251
&nASCI_Spliter=18
&sDateCreateFormat=dd.mm.yyyy%20hh:MM:ss
&sFileName=dohody.dat
&sTaskEndDateAt=2016-03-01
&sTaskEndDateTo=2016-04-01

В ответе получаем некорректный месяц создания заявки, а также время создания заявки не соответствует с временем в ответе

**Comment by sergeygorban** [comment]
Часть ответа: 1288303516.43.2016 07:03:38

**Comment by dmitrijzabrudskij** [comment]
что-то у меня не получается(

запрос следующий:
https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=subsidiesUkraine&sID_State_BP=usertask1&sDateAt=2016-03-21&sDateTo=2016-03-23&saFields=${area};${sID_Order};${sDateCreate};${bankIdlastName};${sDateClose};${selection};&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=escalation.csv&sTaskEndDateAt=2016-03-21&sTaskEndDateTo=2016-03-23

вообще 0 результатов. хотя 2 заявки есть законченные в нем

**Comment by bvv4ik** [comment]
"хотя 2 заявки есть законченные в нем"
а какой датой закончены эти заявки? можеш итог выборки полной дать чтоб глянуть эти даты и понять - попадают-ли они в период?

**Comment by dmitrijzabrudskij** [comment]
22.03.2016
вот пример запроса, по которому заявки возвращаются: https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=subsidiesUkraine&sID_State_BP=usertask1&sDateAt=2016-03-21&sDateTo=2016-03-23&saFields=${area};${sID_Order};${sDateCreate};${bankIdlastName};${sDateClose};${selection};&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=escalation.csv

**Comment by bvv4ik** [comment]
```
УПСЗН Апостолівського району;0-135751926;21.03.2016 12:05:36;БІЛЯВЦЕВ;21.03.2016 12:05:36;
УПСЗН Амур-Нижньодніпровського району, м. Дніпропетровськ;0-135800845;21.03.2016 12:21:15;БІЛЯВЦЕВ;21.03.2016 12:21:15;
УПСЗН Апостолівського району;0-138126332;22.03.2016 14:24:00;БІЛЯВЦЕВ;22.03.2016 14:24:00;

```

да, дата "21.03.2016 12:21:15" должна была попасть в предыдущую выборку...

@ASkosyr Александр, по свободе, глянь плиз...

**Comment by ASkosyr** [comment]
подправил.
Сейчас по запросу задачи возвращаются.

Проблемка была после мержа, не вызывался код получения тасок, если были параметры sTaskEndDateAt=2016-03-21&sTaskEndDateTo=2016-03-23 в запросе

**Comment by dmitrijzabrudskij** [comment]
что-то у меня вообще выгрузка на альфе сломалась...

**Comment by dmitrijzabrudskij** [comment]
https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=subsidiesUkraine&sID_State_BP=usertask1&sDateAt=2016-03-21&sDateTo=2016-03-23&saFields=${area};${sID_Order};${sDateCreate};${bankIdlastName};${sDateClose};${selection};&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=escalation.csv

результат:
<!DOCTYPE html>
<html>
    <head>
        <title>A

**Comment by ASkosyr** [comment]
@dmitrijzabrudskij 

я подправил логику немного. теперь результат по последнему запрому возвращается.

Проблема в том, что поле selection является переменной конкретной задачи, и что-то список переменных задачи возвращается пустой.
В результате не находило значение для selection.

Я еще посмотрю как переменные задачи подтянуть, чтобы подправить запрос.

**Comment by ASkosyr** [comment]
Напрямую в активити делаю запрос.
Для 3 тасок, которые выбираются. нет переменной selection.

А поле selection давно добавлялось?

https://test.region.igov.org.ua/wf/service/history/historic-task-instances?taskId=13812953&includeTaskLocalVariables=true
https://test.region.igov.org.ua/wf/service/history/historic-task-instances?taskId=13580404&includeTaskLocalVariables=true
https://test.region.igov.org.ua/wf/service/history/historic-task-instances?taskId=13575512&includeTaskLocalVariables=true

**Comment by dmitrijzabrudskij** [comment]
это поле в бизнес-процессе с самого его создания

**Comment by bvv4ik** [comment]
@ASkosyr
Саша, на самом деле нужно фильтровать по этому значению:
endTime

а не полю вариэйблов

**Comment by ASkosyr** [comment]
@bvv4ik в последнем запросе проблема не фильтрации, а выборки заданных полей

saFields=${area};${sID_Order};${sDateCreate};${bankIdlastName};${sDateClose};${selection}

а именно поля selection, которое является полем формы юзер таски и которого нет в переменных процесса, чтобы получить значение

**Comment by bvv4ik** [comment]
ага, т.е. вы уже решали другую задачу)
а то Дима сегодня страшно распереживался, что ему приходится до сих пор статистику по субсидиям считать руками... без этих сервисов

**Comment by bvv4ik** [comment]
так сейчас уже все работает?

**Comment by ASkosyr** [comment]
еще нет
пока у меня только получилось подтянуть значение (но не могу проверить на альфе). то есть для поля selection должно выводится attr3.

Подгрузка формы для хисторк процесса - немного непрямолинейная задачка. Код кажется нашел на форумах, но сегодня уже проверить не успею его.
Постараюсь завтра сделать, чтобы значение человекочитабельное было.

**Comment by bvv4ik** [comment]
т.е. получается, что этот сервис из покон веков не умел из хистори-тасок поля выгребать?

**Comment by bvv4ik** [comment]
ну вообще-то это тогда не касается данной ишью...

скажи - сам фильтр по endTime удалось починить?

**Comment by ASkosyr** [comment]
> т.е. получается, что этот сервис из покон веков не умел из хистори-тасок поля выгребать?
если это не переменные процесса - то оне умел.

> скажи - сам фильтр по endTime удалось починить?
запрос насколько я вижу работает.
например вот такой возращает 3 таски, которые закрыты 28 числа. без параметров последних двух тоже 3 таски возвращается

https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=subsidiesUkraine&sID_State_BP=usertask1&sDateAt=2016-03-21&sDateTo=2016-03-23&saFields=%24%7Barea%7D;%24%7BsID_Order%7D;%24%7BsDateCreate%7D;%24%7BbankIdlastName%7D;%24%7BsDateClose%7D;%24%7Bselection%7D;&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=escalation.csv&sTaskEndDateAt=2016-03-27&sTaskEndDateTo=2016-03-29

**Comment by ASkosyr** [comment]
@bvv4ik еще по поводу полей что вспомнил. 
Поля стартовой формы кажется попадают а переменные процесса после завершения процесса. Проблема только с полями юзер тасок внутри процесса.

**Comment by dmitrijzabrudskij** [comment]
https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=subsidiesUkraine&sID_State_BP=usertask1&sDateAt=2016-03-21&sDateTo=2016-03-23&saFields=%24%7Barea%7D;%24%7BsID_Order%7D;%24%7BsDateCreate%7D;%24%7BbankIdlastName%7D;%24%7BsDateClose%7D;%24%7Bselection%7D;&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=escalation.csv&sTaskEndDateAt=2016-03-27&sTaskEndDateTo=2016-03-29

этот запрос данные возвращает, но нет значения поле selection (мне не нужно его в "удобоваримом формате" возвращать - достаточно id этого enum'а - именно в таком виде он и возвращался при запросе всех созданных заявок за период)

еще момент: запрос должен отрабатывать без фильтра по sDateAt=2016-03-21&sDateTo=2016-03-23. 

Мне нужны 2 работающих запроса:
1. всех созданных заявок за период
2. всех отработанных заявок за период

**Comment by ASkosyr** [comment]
> но нет значения поле selection

вот его получить у меня пока не получается. смотрю еще.

**Comment by dmitrijzabrudskij** [comment]
что самое интересное - оно было
и на боевом выгружается:)

https://region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=subsidiesUkraine&sID_State_BP=usertask1&sDateAt=2016-03-21&sDateTo=2016-03-23&saFields=%24%7Barea%7D;%24%7BsID_Order%7D;%24%7BsDateCreate%7D;%24%7BbankIdlastName%7D;%24%7BsDateClose%7D;%24%7Bselection%7D;&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=escalation.csv

**Comment by ASkosyr** [comment]
@bvv4ik @dmitrijzabrudskij 
разобрался. почему работает на боевом :)

дико извиняюсь. но изначально кажется получение тасок работало. получается 2 дня тупил :(

по поводу вот этого комментария.

> **dmitrijzabrudskij commented 7 days ago**
> что-то у меня не получается(
> 
> запрос следующий:
> https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=subsidiesUkraine&sID_State_BP=usertask1&sDateAt=2016-03-21&sDateTo=2016-03-23&saFields=${area};${sID_Order};${sDateCreate};${bankIdlastName};${sDateClose};${selection};&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=escalation.csv&sTaskEndDateAt=2016-03-21&sTaskEndDateTo=2016-03-23
> 
> вообще 0 результатов. хотя 2 заявки есть законченные в нем

запрос не возвращал данных, потому что таски закончены 28 марта, что не попадает в диапазон
sTaskEndDateAt=2016-03-21&sTaskEndDateTo=2016-03-23

если убрать эти два параметра или поставить корректные данные завершения, то задачи выбираются.
вот таким запросом например

https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=subsidiesUkraine&sID_State_BP=usertask1&sDateAt=2016-03-21&sDateTo=2016-03-23&saFields=${area};${sID_Order};${sDateCreate};${bankIdlastName};${sDateClose};${selection};&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=escalation.csv&sTaskEndDateAt=2016-03-28&sTaskEndDateTo=2016-03-29

а вот почему для этих задач пустое значение атрибута - мне не ясно на данный момент.
потому что вот для свежей задачи по субсидии атрибут не пустой. я ее создал и руками обработал.
и вот таким запросом все нормально выбирается с атрибутом

https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=subsidiesUkraine&sID_State_BP=usertask1&sDateAt=2016-03-29&sDateTo=2016-03-30&saFields=%24%7BnID_Task%7D;%24%7BnID_Task%7D;%24%7Barea%7D;%24%7BsID_Order%7D;%24%7BsDateCreate%7D;%24%7BbankIdlastName%7D;%24%7BsDateClose%7D;%24%7Bselection%7D;&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=escalation.csv&sTaskEndDateAt=2016-03-29&sTaskEndDateTo=2016-03-30

возможен ли вариант. что таски были завершены без выбора значения для selection?

**Comment by dmitrijzabrudskij** [comment]
возможен ли вариант. что таски были завершены без выбора значения для selection?

нет, так не получится сделать (разве что глюк самого активити - поле selection всегда обязательно к выбору)

еще такой вопрос: без параметров sDateAt=2016-03-21& и DateTo=2016-03-23 запрос будет работать? но с sTaskEndDateAt=2016-03-29 и sTaskEndDateTo=2016-03-30 - чтобы выбирать только закрытые таски за период?

**Comment by ASkosyr** [comment]
> еще такой вопрос: без параметров sDateAt=2016-03-21& и DateTo=2016-03-23 запрос будет работать? но с sTaskEndDateAt=2016-03-29 и sTaskEndDateTo=2016-03-30 - чтобы выбирать только закрытые таски за период?

https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=subsidiesUkraine&sID_State_BP=usertask1&saFields=%24%7BnID_Task%7D;%24%7BnID_Task%7D;%24%7Barea%7D;%24%7BsID_Order%7D;%24%7BsDateCreate%7D;%24%7BbankIdlastName%7D;%24%7BsDateClose%7D;%24%7Bselection%7D;&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=escalation.csv&sTaskEndDateAt=2016-03-29&sTaskEndDateTo=2016-03-30

да
я немного подправил логику, чтобы не подставлялись значения начала задачи в запрос (если не заданы, то они проставлялись как вчера и сегодня)

запрос выполняется корректно насколько я вижу

**Comment by dmitrijzabrudskij** [comment]
о, работает)
спасибо
но по старым заявкам что-то все равно selection не выгружает...

**Comment by ASkosyr** [comment]
по старым заявкам я тоже увидел что не выгружает.
я честно говоря не знаю как побороть и почему так произошло.

даже напрямую из апач активити если запрашивать рест запросами - там нет данных для тех юзер тасок.
