### ISSUE TITLE
Доработать сервис выгрузки данных, для поддержки высылки формируемого отчета на почту

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1182]
- Дорабатываемый сервис: /downloadTasksData
- Добавить опциональный параметр
  sMailTo - строка с электронным адресом получателя
- если задан этот параметр, высылать на этот электронный адрес письмо со сформированным файлом в качестве атача (в заглавии - "Выборка за: (начальная дата)-(конечная дата), для БП: "+"Название БП ")

**Comment by ASkosyr** [comment]
Пример запроса для получения выгрузки по задачам на указанные имейл.

```
https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?&sID_BP=dnepr_spravka_o_doxodax&sDateAt=2016-03-01&sDateTo=2016-04-01&saFields=${nID_Task};${sDateCreate};${area};;;0;${bankIdlastName}%20${bankIdfirstName}%20${bankIdmiddleName};4;${aim};${date_start};${date_stop};${place_living};${bankIdPassport};1;${phone};${email}&sID_Codepage=win1251&nASCI_Spliter=18&sDateCreateFormat=dd.mm.yyyy%20hh:MM:ss&sFileName=dohody.dat&sMailTo=askosyr@gmail.com
```

**Comment by sergeygorban** [comment]
Отправил запрос, получил ответ
1271847414.11.2016 11:03:180ГОРБАНЬ СЕРГІЙ СЕРГІЙОВИЧ4АА111111 ДНЕПРОПЕТРОВСКИМ РО УМВДУ. 12.07.20081+380 66 060 0111sergey.gorban@ukr.net

1288303516.43.2016 07:03:380ГОРБАНЬ СЕРГІЙ СЕРГІЙОВИЧ4АА111111 ДНЕПРОПЕТРОВСКИМ РО УМВДУ. 12.07.20081+380 66 060 0111sergey.gorban@ukr.net

1288315616.54.2016 07:03:560ГОРБАНЬ СЕРГІЙ СЕРГІЙОВИЧ4АА111111 ДНЕПРОПЕТРОВСКИМ РО УМВДУ. 12.07.20081+380 66 060 0111sergey.gorban@ukr.net

**Comment by sergeygorban** [comment]
1. Что это за числа 12718474, 12883035, 12883156. Заявки на https://test.region.igov.org.ua по этим номерам не находятся.
2. Месяц создания некорректный , время создания не соответствует реальному созданию заявки
3. Что означает цифра "1" после 12.07.2008, "0" после 11:03:18, "4" после ФИО?

**Comment by sergeygorban** [comment]
Запрос:

**Comment by sergeygorban** [comment]
https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?&sID_BP=dnepr_cnap_225&sDateAt=2016-03-01&sDateTo=2016-04-01&saFields=${nID_Task};${sDateCreate};${area};;;0;${bankIdlastName}%20${bankIdfirstName}%20${bankIdmiddleName};4;${aim};${date_start};${date_stop};${place_living};${bankIdPassport};1;${phone};${email}&sID_Codepage=win1251&nASCI_Spliter=18&sDateCreateFormat=dd.mm.yyyy%20hh:MM:ss&sFileName=dohody.dat&sMailTo=sergey.gorban@ukr.net

**Comment by sergeygorban** [comment]
Запрос:
https://test.region.igov.org.ua/wf/service/action/task/
downloadTasksData?
&sID_BP=dnepr_cnap_225
&sDateAt=2016-03-01
&sDateTo=2016-04-01
&saFields=${nID_Task};
${sDateCreate};
${area};;;0;
${bankIdlastName}%20
${bankIdfirstName}%20
${bankIdmiddleName};4;
${aim};${date_start};
${date_stop};
${place_living};
${bankIdPassport};1;
${phone};
${email}
&sID_Codepage=win1251
&nASCI_Spliter=18
&sDateCreateFormat=dd.mm.yyyy%20hh:MM:ss
&sFileName=dohody.dat
&sMailTo=sergey.gorban@ukr.net

**Comment by sergeygorban** [comment]
Первый запрос на альфе, на бете результат аналогичный

**Comment by nazarenkod** [comment]
сейчас запрос возвращает такую ошибку
{
  "code": "SYSTEM_ERR",
  "message": "Failed to convert value of type 'java.lang.String' to required type 'java.util.Date'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.lang.String to type @io.swagger.annotations.ApiParam @org.springframework.web.bind.annotation.RequestParam @org.springframework.format.annotation.DateTimeFormat java.util.Date for value '2016-03-01 '; nested exception is java.lang.IllegalArgumentException: Invalid format: \"2016-03-01 \" is malformed at \" \""
}

**Comment by OlgaTurenko** [comment]
1) загрузка файла-отчета:
https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=dnepr_cnap_225&sDateAt=2016-03-01&sDateTo=2016-04-01&saFields=${nID_Task};&sID_Codepage=win1251&nASCI_Spliter=18&sDateCreateFormat=dd.mm.yyyy%20hh:MM:ss&sFileName=dohody.dat  

2) отправка его на почту:
https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=dnepr_cnap_225&sDateAt=2016-03-01&sDateTo=2016-04-01&saFields=${nID_Task};&sID_Codepage=win1251&nASCI_Spliter=18&sDateCreateFormat=dd.mm.yyyy%20hh:MM:ss&sFileName=dohody.dat&sMailTo=olga.kuzminova87@gmail.com


На почту не приходит отчет. Неоходимо разобраться почему.
