### ISSUE TITLE
Доработать сущность истории и связанные с ней сервисы

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1183]
- [x] 1) в сущность HistoryEvent добавить опциональные элементы (соотв. гетеры/сетеры):
- [x] 1.1) nID_HistoryEvent_Service - Номер-ИД связки с элементом сущности HistoryEvent_Service //опциональный
- [x] 1.2) nID_Document - Номер-ИД связки с элементом сущности Document //опциональный
- [x] 2) При наличии там элемента выводить соответственно в сущности:
- oHistoryEvent_Service (связанный объект сущности HistoryEvent_Service)
- oDocument (связанный объект сущности Document)
или null, при отсутствии.
(сами nID_HistoryEvent_Service и nID_Document в сущности не отображать)
- [x] 3) Доработать сервис /getHistoryEvents, добавив параметр:
- bGrouped - булевый //опциональный, по умолчанию false, если true, то оставлять только последнюю по дате (sDate) запись, и с тех, у которых nID_HistoryEvent_Service или nID_Document - один и тот-же
- [x] 4) Во всех сервисах, обеспечивающих добавление записи HistoryEvent - добавить эти два новых опциональных параметра.
- [x] 5) Дописать коментарии в анотации, для корректной автогенерации документации по АПИ

**Comment by kr110666kai** [comment]
Могу завтра к обеду сделать. Если не будет чего-то срочного до сегодня к вечеру.

**Comment by kr110666kai** [comment]
Выполнено
https://jenkins-new.igov.org.ua/job/central_alpha/ws/wf-central/target/generated-docs/central-igov.html#_Загрузка_событий

**Comment by bvv4ik** [comment]
Посмотрел, спасибо!
Но важные два замечания:
1) я не увидел передачу этих новых параметров из вызывающих этот сервис/сетер мест... в частности - в интерцепторе( ну может не прямо в нем, но в связанном)  где проимходит добпвление новой записи EventHistory_Service  на основе новой заявки±EventHistoryи так-же при изменениях в зачвке когда просто добавляются EventHistoryи... все точно также при добавлении записей истории по документам... ведь по сути эти поля для запоминании этих связок и делались...
2) не стоило в сетерах типом ставить обьект а лучше просто ил-шник... ведь изначально у нас ид-шники есть... иначе куча накладных действий во многих местах придется делать при преобразовании ид-шника в обьекты документа и события истории сервиса

**Comment by kr110666kai** [comment]
Замечания исправил. Завтра еще перепроверю сервисы, но пока пропущенных не видно.

**Comment by kr110666kai** [comment]
Может в контроллере DocumentController в /setDocument надо аналогично /setDocumentFile добавить создание HistoryEvent?
```
actionEventService.createHistoryEvent(HistoryEventType.SET_DOCUMENT_INTERNAL,
                nID_Subject, sSubjectName_Upload, nID_Document, null);
```

**Comment by bvv4ik** [comment]
Спасибо за такую оперативность!

"Может в контроллере org.igov.service.controller.DocumentController.java в /setDocument надо аналогично /setDocumentFile добавить создание HistoryEvent?"
наверно не стоит... по двум причинам:
1) это сервис пока не используется
2) вероятней всего скоро мы все эти вызовы сохранения истории будем делать в интерцепторе... чтоб избежать лишней запутанности, нагромаждений и случайных пропусков...

Еще раз спасибо!
попрошу коллег протестить...

**Comment by sergeygorban** [comment]
Как тестировать данную задачу, скажите пожалуйста?

**Comment by kr110666kai** [comment]
Как тестировать данную задачу, скажите пожалуйста?

1. Делаем запрос с минимумом условий:
https://test.igov.org.ua/wf/service/action/event/getHistoryEvents?nID_Subject=10
В ответе 20 результатов

2. Далее добавляем условие nID_HistoryEvent_Service=2
https://test.igov.org.ua/wf/service/action/event/getHistoryEvents?nID_Subject=10&nID_HistoryEvent_Service=2
В ответе 4 результата, у всех HistoryEvent_Service с nID = 2

3. А теперь условие группировки bGrouped=true
https://test.igov.org.ua/wf/service/action/event/getHistoryEvents?nID_Subject=10&bGrouped=true
В ответе 9 результатов, (результат как в п.1 но дополнительно отфильтрован согласно https://jenkins-new.igov.org.ua/job/central_alpha/ws/wf-central/target/generated-docs/central-igov.html#_Загрузка_событий )

4. Теперь условие bGrouped=true и nID_HistoryEvent_Service=2
https://test.igov.org.ua/wf/service/action/event/getHistoryEvents?nID_Subject=10&bGrouped=true&nID_HistoryEvent_Service=2
В ответе 2 результата, (результат как в п.3 но дополнительно отфильтрован согласно https://jenkins-new.igov.org.ua/job/central_alpha/ws/wf-central/target/generated-docs/central-igov.html#_Загрузка_событий )
Обратите внимание первые три ответа в п.3. имеют одинаковый oDocument.nID = 1, поэтому в ответ попадает только один из них с "sDate": "2015-07-04 15:09:56.000",

**Comment by bvv4ik** [comment]
на самом деле уже данная реализация в основе новой навигации истории заявок:
https://github.com/e-government-ua/i/issues/1179
и там все работает, а значит и тут все гуд

**Comment by sergeygorban** [comment]
В ответе параметры принимают значение NULL
https://test.igov.org.ua/wf/service/action/event/getHistoryEvents?nID_Subject=47423

Это так и должно или в ответе есть параметры, которые не должны принимать значение null

**Comment by sergeygorban** [comment]
В ответе параметры принимают значение NULL
https://test.igov.org.ua/wf/service/action/event/getHistoryEvents?nID_Subject=47423

Это так и должно или в ответе есть параметры, которые не должны принимать значение null
