### ISSUE TITLE
Ошибка при попытке смены города, для которого недоступна электронная услуга

### ISSUE THREAD

**Issue by ashavanov** [e-government-ua/i#1184]
[s3]

Браузер в котором проводил тест: Firefox 44.0.2

Шаги:
1. Выбор любой услуги (напр. Отримання субсидії на оплату житлово-комунальних послуг) на главной странице сайта
2. На открывшейся пошаговой форме выбрать любой из регионов (напр. Винницкая область), а в нем - город, для которого данная услуга не доступна (напр. Бар)
3. Поставить курсор в конец поля города
Появляется список

ER: пользователь должен иметь возможность поменять город
AR: доступен только ранее выбранный город
1. При помощи кнопки backspace на клавиатуре начать удалить введенное значение

ER: пользователю доступен список городов к выбору
AR: список городов не доступен к выбору, появляется ошибка с текстом c is null (caused by "undefined")  - скриншот во вложении.

![c is null](https://cloud.githubusercontent.com/assets/17461550/13506638/be5fb996-e187-11e5-8e38-7b9101b35812.jpg)

При попытке закрыть окно с ошибкой оно появляется снова, единственный способ от него избавиться - закрыть или перегрузить табу браузера

**Comment by redixin** [comment]
Consider about turning off js obfuscation. This is open project for open government right?

**Comment by NikolayAngel** [comment]
Тестирование успешно. Тестировал на Дельте "Отримання субсидії на оплату житлово-комунальних послуг"(654)
Выбрал город по которому нет услуги
![image](https://cloud.githubusercontent.com/assets/11869200/26192274/b0ca4caa-3bb9-11e7-8da2-d5889cce92b6.png)
После этого нажал изменить, данные по выбору области стали доступны, без каких-либо ошибок.
