### ISSUE TITLE
Заменить ответ сервиса колбэка для СЭД УкрДок на JSON-обьект

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1186]
Сейчас по реализованной ишью: 
https://github.com/e-government-ua/i/issues/1137
в случае успеха просто возвращается 200-тый код и стринга
а нужно чтоб эта-же стринга возврвщалась но в виде JSON-обьекта
Например:
{"sReturnSuccess":"Ok"}

**Comment by ArtemTokarenko** [comment]
Принимаю  в роботу

**Comment by ArtemTokarenko** [comment]
Тестировщику.

как делал я:
1. в постмене(https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop) вписывал в верхнее поле localhost:8080/wf/service/action/task/callback/ukrdoc
2.кнопка левее от предыдущего поля в положение "post"
3. ниже вкладка в "body"
4.ещё ниже "raw"
5. правее вкадка "text" в "JSON" (не обязательно)
6.открывшееся после (предположительно) 3го шага, поле под "raw"  вставляем скопированною из  #1137 инфу ту что под "3) Образец принимаемого объекта:" (lда всю , да большая)
7.нажимаем "Send" с права от нашего самого первого поля


ожидаемый результат 
{
  "sReturnSuccess": "OK"
}
в формате JSON

**Comment by MaksKnight** [comment]
дайте пожалуйста запрос для ввода

**Comment by MaksKnight** [comment]
после проверки получил только ответ 200, подскажите пожалуйста может что то не то сделал ?
![image](https://cloud.githubusercontent.com/assets/17780607/15284071/c0e73c48-1b57-11e6-93e2-dc089fe9d430.png)

**Comment by MaksKnight** [comment]
возвращает объект но без {"sReturnSuccess":"Ok"}, подскажите что не так  @bvv4ik 
![image](https://cloud.githubusercontent.com/assets/17780607/15284670/5f560780-1b5b-11e6-9905-0a7684cae134.png)
