### ISSUE TITLE
Доработать сервис отчетов, добавив параметр-исключений номеров услуг из них

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1187]
- Сервис: /getServiceHistoryReport
- Параметр: sanID_Service_Exclude
содержит ИД-номера услуг, которые нужно исключить из отчета (разделенные через запятую)
например: 34,56,14

**Comment by bvv4ik** [comment]
По поводу тестирования прошу обращаться к @GrekD

**Comment by VadymBuz** [comment]
Принимаю в работу

**Comment by VadymBuz** [comment]
Добавлен параметр, выделен жирным, в котором передаются ID услуг в виде строки: "1,5,24,56"
и если в базе есть строка с ID этой услуги, он исключается из результата
https://test.igov.org.ua/wf/service/action/event/getServiceHistoryReport?sDateAt=2016-02-09 00:00:00&sDateTo=2016-02-11 00:00:00&**sanID_Service_Exclude**=1,5,24,56

так же была добавлена ещё одна проверка  в jUnit тест:
} else if (Collection.class.isAssignableFrom(type)) {
             randomizer = collectionRandomizer;
          }

**Comment by sergeygorban** [comment]
Дайте пожалуйста скайп для связи с VadymBuz

**Comment by VadymBuz** [comment]
vadikan_23

**Comment by sergeygorban** [comment]
2. Тест №2
Запрос:
https://test-version.igov.org.ua/wf/service/action/event/getServiceHistoryReport?sDateAt=2016-03-22 00:00:00&sDateTo=2016-03-22 23:59:59
Ответ:
sID_Order;nID_Server;nID_Service;sID_Place;nID_Subject;nRate;sTextFeedback;sUserTaskName;sHead;sBody;nTimeMinutes;sPhone

0-11400018;0;99;1200000000;27491;;;Перевірка ЦНАП;Внесення до Державного земельного кадастру відомостей (змін до них) про земельну ділянку;;;+380 66 060 0286

0-11375017;0;627;8000000000;20053;;;Формування довідки в РДА; Київ МДА - Надання довідки про перебування на обліку громадян, які потребують відповідно до законодавства поліпшення житлових умов;;-1;380671032122

3. Тест №3
Запрос:
https://test-version.igov.org.ua/wf/service/action/event/getServiceHistoryReport?sDateAt=2016-03-22 01:00:00&sDateTo=2016-03-22 00:00:00
Ответ:
Данные не получены

**Comment by sergeygorban** [comment]
ВОПРОС: Где мне найти sanID_Service_Exclude для конкретной заявки?

**Comment by GrekD** [comment]
@sergeygorban 
@VadymBuz 
работает, проверила на боевом

**Comment by nazarenkod** [comment]
Протестировано
