### ISSUE TITLE
Доработать сущность истории заявок, добавив поле под-сервиса, и сохраняя в него теперь тоже данные в интерцепторе, а так-же выводя теперь это поле в объекте, через сервис отчетов по заявкам

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1188]
- Сущность: HistoryEvent_Service
- Поле: nID_ServiceData - номер-ИД под-услуги
- Сервис: /getServiceHistoryReport
- Класс интерцептора: org.igov.service.controller.interceptor.RequestProcessingInterceptor
- Метод интерцептора: saveNewTaskInfo

**Comment by bvv4ik** [comment]
По поводу тестирования прошу обращаться к @GrekD

**Comment by PaulLuchyn** [comment]
Принимаю в работу, дедлайн сегодня уточню

**Comment by IrynaAndronik** [comment]
Как тестировать? @GrekD

**Comment by PaulLuchyn** [comment]
На вход подаются две даты, в результате работы должны получить csv - файлик, со следующими полями:sID_Order;nID_Server;nID_Service;sID_Place;nID_Subject;nRate;sTextFeedback;sUserTaskName;sHead;sBody;nTimeMinutes;sPhone;nID_ServiceData.

**Comment by GrekD** [comment]
коллеги я извиняюсь, я не очень понимаю что это за задача
не понимаю так же что такое интерцептор :)
можете более понятным языком объяснить что это, чтоб я могла ответить на Ваш вопрос?

**Comment by PaulLuchyn** [comment]
@GrekD , попробую ответить на Ваши вопросы.
Итак:
1 - интерсептор (от англ. intercept - перехватывать), это - такой клас, методы которого запускаются перед обработкой запросов (реквестов)
2 - после проделанной мною работы было добавлено новое поле в сущность истории заявок, в которое в интерсепторе сохраняются данные и это же поле теперь должно выводится через сервис отчетов по заявкам
3 - необходимо проверить сохраняются ли данные при создании новой таски (метод интерсептора saveNewTaskInfo), а также выводится ли данное поле через сервис отчетов по заявкам (сервис /getServiceHistoryReport)

**Comment by GrekD** [comment]
@PaulLuchyn 
nID_ServiceData - само поле появилось, но все строки выгрузки пустые в этом поле - я пробовала разные диапазоны дат

**Comment by PaulLuchyn** [comment]
@GrekD  , возможно в базе нету записей с этим полем? сейчас посмотрю код, может баг

**Comment by GrekD** [comment]
@PaulLuchyn 
добрый день
доработка уже на боевом, но в само поле nID_ServiceData  ничего не проливается

**Comment by PaulLuchyn** [comment]
@GrekD , в смысле: ничего не проливается?

**Comment by GrekD** [comment]
@PaulLuchyn  
nID_ServiceData должен проливаться номер строки из файла ServiceData (он всегда есть, и поле не может быть пустым)
по запросу ни в одной строчек этих номеров нет
вот скрин: желтым выделена переменная sPhone и в строчках ее значение (номер телефона) - все подтягивается
зеленым выделена переменная nID_ServiceData и **пустое место** куда должны были пролиться номера
![123](https://cloud.githubusercontent.com/assets/10836093/14847628/52812726-0c72-11e6-85c8-40a8ec1476b7.jpg)
