### ISSUE TITLE
Переделать прикрепление прилагаемого файла к задаче

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#119]
1) Сохранять контент файла из редина нев аттачмент а в карту
2) Сохранять не в листенере а на кружке
3) Скопировать этот метод сервиса download_from_db как download_from_db_new
4) Заменить начало метода сервиса download_from_db_new на импорт не из аттачмента а с карты

**Comment by Dashchenko-Inna** [comment]
Работает два варианта сохранения фала:

**Comment by Dashchenko-Inna** [comment]
1. Сохранением в execution

**Comment by Dashchenko-Inna** [comment]
2.Атачмент средствами активити
