### ISSUE TITLE
Расширить перечень спонсоров (банеров со сылками на них)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1192]
Список спонсоров и их УРЛ-ы тут:
https://docs.google.com/document/d/1pdcv75L--gyFgrWKxPCPynHGNhKQfLkayAfa4an_bwU/edit

Банеры взять тут:
https://www.dropbox.com/s/8aisak69xb2vy07/sponsor.zip?dl=0

**Comment by sergeygorban** [comment]
Количество банеров соответствует перечню. При нажатии на банеры происходит переход на оф.страницу
