### ISSUE TITLE
Устранить замечания по реализованной новой навигации

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1193]
В соответствии ссо списком и скриншотами:
https://docs.google.com/document/d/1QDIFgfXFDTnIS8-0WS5itPAdHAR4S4vmRjqM5FQDdrY/edit

устранить следующие замечания:

- [x] 1. Авторизоваться<br>
**Ожидаемый результат:** По-умолчанию открыт раздел Необроблені<br>
**Фактический результат:** Открыт раздел “Мій розклад”
- [x] 2. Выбрать раздел Профиль<br>
**Ожидаемый результат:** Переход в раздел профиля. Навигационная панель не меняется.<br>
**Фактический результат:** Навигационная панель переключается в режим инструментов.
- [x] 3. Навести курсор на  любую вкладку в навигационной панели<br>
**Ожидаемый результат:** Курсор  видоизменяется в указатель ( по аналогии с наведением на  наши ссылки, кнопки, записи в списке задач)<br>
**Фактический результат:** Курсор не видоизменяется
- [x] 4. Навести курсор на  ссылку настройки фильтров<br>
**Ожидаемый результат:** Зона клика  соответствует размерам надписи.<br>
**Фактический результат:** Зона клика очень маленькая. Трудно  попасть крусором
- [x] 5. -<br>
**Ожидаемый результат:** (см.изображение по ссылке)<br>
**Фактический результат:**  (см.изображение по ссылке)
- [x] 6. Установить фокус в поле для поиска<br>
**Ожидаемый результат:** Отображается подсказка (см.изображение по ссылке) <br>
**Фактический результат:** Подсказка не отображается
- [x] 7. Ввести в строку поиска id существующего обращения <br>
**Ожидаемый результат:** Заявка будет найдена<br>
**Фактический результат:** Найдено огромное количество других заявок -  критерий поиска непонятен
- [x] 8. Перейти в  Мій розклад<br>
**Ожидаемый результат:** календарь, в котором можем выбрать дату или все даты и просмотреть очередь заявок,<br>
**Фактический результат:** отсутствует выбор хоть какой-то даты пока не нажмешь на слово “Дата”:

**Comment by GFalcon-UA** [comment]
п.7 - поиск работал, но не всегда происходил автофокус списка задач на найденной. Чтоб убедиться в этом, приходилось крутить срол-бар списка задач вверх или вниз. От сюда, возможно, и складывалось первое впечатление, что критерии поиска не понятны.
Проблема исправлена, но с нюансом: в случае, если в результате поиска будет найдено две или более заявок, то список отфокусируется на первой попавшейся из них.

**Comment by sergeygorban** [comment]
Замечания устранены
