### ISSUE TITLE
Реализовать профиль пользователя

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1194]
В продолжение реализации:
https://github.com/e-government-ua/i/issues/1109

Реализовать профиль пользователя по мокапу:
https://dl.dropboxusercontent.com/u/50541317/eGov/dashboard/start.html#p=налаштування

- [x] 1) Отображать:
ПІБ : Іванов Іван Іванович
Логін : %employee_login%

- [x] 2) Для "Зміна пароля"
использовать сервис, реализованный по таске: https://github.com/e-government-ua/i/issues/1178

- [x] 3) Меню открывать при клике на ФИО пользователя (в верхнем-правом углу) и выборе пункта меню "Профиль", при это м НЕ переключаться в режим инструментов, а просто дополнительно отображать открытую закладку "Мій Профіль", в которой и отображать профиль (при сохранении или отмене скрывать блок и сам таб/закладку)

- [x] 4) Поля "Контактний телефон" и "Контактний e-mail" заполнять данными, полученными из сервиса /getSubjectsByAccount, на центральном портале wf-central (передавая логин в поле saLogin) и сделать поля не редактируемыми (кнопки правее скрыть)

**Comment by Beluy452** [comment]
приймю в роботу)

**Comment by bvv4ik** [comment]
[23:04:57] Alex Beluy: я добавив стрінку в роутинг (profile)
https://test.region.igov.org.ua/profile

**Comment by glebzhebrakov** [comment]
in progress

**Comment by bvv4ik** [comment]
нужно проверить, реализован-ли п.5, на каком-то из пользователей, у кого есть контакты в SubjectContacts

**Comment by bvv4ik** [comment]
@msvidran  все протестировал и все в порядке
