### ISSUE TITLE
Ошибка при открытии страницы Видео - вступление!

### ISSUE THREAD

**Issue by MaksProtsenko** [e-government-ua/i#1195]
Окружение:
Chromium Версия 48.0.2564.116 
Ubuntu 14.04

Шаги:
1. Открыть страницу https://github.com/e-government-ua/i/wiki/%D0%AF%D0%BA-%D0%BF%D0%BE%D1%87%D0%B0%D1%82%D0%B8-%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D1%83
2. Перейти по ссылке [Видео - вступление!](https://pbank.webex.com/pbank-ru/ldr.php?RCID=8cdd26659085938889cae387d69ffd65)

ER: должна выводится страница с видео.
AR: выводится ошибка "Неправильный ввод или системная ошибка. Повторите попытку или обратитесь к администратору сайта.".

![_001](https://cloud.githubusercontent.com/assets/13639968/13773671/326016c8-eaa3-11e5-9f25-4a25861e851b.png)

**Comment by bvv4ik** [comment]
оно работает, просто должен быть проставлен плагин вебекса
