### ISSUE TITLE
Реализовать проверку полей на наличие writable=false, и такие поля при сабмите игнорировать

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1196]
Тестовая услуга(которая должна начать сабмититься в результате):
https://test.igov.org.ua/service/671/general  (_test_dependence_form )
(там поле с типом маркер содержит writable=false)

В данном файле:
\i\central-js\server\api\process-form\form.controller.js

в строке, начиная с 88-й,
проверяя атрибут writable - не допускать добавления полей (в properties), в которых writible = false

учитывать, что options.formData.params[id] может возвращать null

ВАЖНО: Обязательно перепроверять все еще и на других услугах, чтоб они работали после доработки правильно, т.к. множественные попытки реализации ломали сабмит на других услугах.

**Comment by kurbpa** [comment]
@bvv4ik 
 в процессе   строка с маркером имеет следующий вид 
```    <activiti:formProperty id="markers2" name="extended_marker" type="markers" default="${markerService.loadFromFile('test_folder/testmarkers.json')}" writable="false"></activiti:formProperty>
     ```

тем не менее  маркер после обработки попадает в историю.
можно убедиться  на примере заявки 0-135756453 (доступна для kermit  в разделе истории на альфе)
