### ISSUE TITLE
Сделать корректный возврат ответа при не найденной в базе заявки

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1197]
Сейчас при вызове:
https://test.igov.org.ua/wf/service/action/event/getHistoryEvent_Service?sID_Order=0-6975013&bAuth=true

возвращает сообщение:
Transaction rolled back because it has been marked as rollback-only

а должно возвращать то, что предусмотрено в эксепшине (либо не найдена, либо неверный формат, либо неверная контрольная сумма)

**Comment by ArtemTokarenko** [comment]
Здравствуйте LyashenkoGS ,а вы уже сделали эту таску?

**Comment by LyashenkoGS** [comment]
Здравствуйте Артем. Возникла проблема. 
 написал интеграционный тест   @Transactional(noRollbackFor ={
            EntityNotFoundException.class,
            CRCInvalidException.class
    } )
    @Test
    public void testGetHistoryEvent_Service() throws Exception {
        actionEventService.getHistoryEventService("0-6975013");
    }}
 с @Transactional работает как надо
 убираю @Transactional над тестом, но добавляю над всеми методами которые используются при вызове  .getHistoryEventService("0-6975013");
- не работает
 вероятно это мой случай http://stackoverflow.com/questions/6097012/no-rollback-only-for-transaction-when-exception-occurs-in-submethod 
при дебаге вылетает ексепшен на 1 же строчке .getHistoryEventService()

**Comment by sergeygorban** [comment]
Запрос на получение истории событий пользователя:
https://test.igov.org.ua/wf/service/action/event/getHistoryEvents?nID_Subject=47423
Из этого запроса брать значение параметра nID 
https://test.igov.org.ua/wf/service/action/event/getHistoryEvent?nID=51099
Ответ:
{
:   "code":"BUSINESS_ERR",
:   "message":"Entity with id=51099 does not exist"
}

Возвращается ответ только для событий _test_UKR_DOC
https://test.igov.org.ua/wf/service/action/event/getHistoryEvent?nID=49409
{
:   "sMessage":"Ви подали заявку на послугу _test_UKR_DOC_Передача у власність земельної ділянки. \n Cтатус: Обробка після прийняття рішення",
:   "sDate":"2016-02-29 06:57:57.585",
:   "oHistoryEvent_Service":null,
:   "oDocument":null,
:   "nID":49409,
:   "nID_Subject":47423,
:   "nID_HistoryEventType":1,
:   "sEventName":"Пользователь воспользовался услугой на портале"
}

**Comment by sergeygorban** [comment]
Вывод после тестирования: 
1. Запрос типа GET https://test.igov.org.ua/wf/service/action/event/getHistoryEvent_Service?sID_Order=150751858 приводит к 500 ошибке сервера. 
2. Запрос типа GET https://test.igov.org.ua/wf/service/action/event/getHistoryEvent_Service?sID_Order= приводит к 500 ошибке сервера. 
3. Запрос типа GET https://test.igov.org.ua/wf/service/action/event/getHistoryEvent_Service?sID_Order=1-150751858
возвращает ответ
{
:   "code":"BUSINESS_ERR",
:   "message":"Record with nID_Server=1 and nID_Process=15075185 not found!"
}
4. Если формат заявки корректный, но ее не существует 
Запрос GET https://test.igov.org.ua/wf/service/action/event/getHistoryEvent_Service?sID_Order=0-150751958
возвращает ответ
{
:   "code":"BUSINESS_ERR",
:   "message":"CRC Error"
}
