### ISSUE TITLE
Реализовать системтаску/листенер интеграции с конвейером Corezoid

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1199]
- [ ] 1) Название класса-системтаски/листенера: SendObject_Corezoid
- [ ] 2) Параметры:
- sID_Conveyour - ИД-номер конвейера 
- soJSON - строка-обьекта JSON, содержащий все нужные для конвейера параметры
- [ ] 3) При неуспехе отсылки - выводить ошибку с текстом "Не удалось отправить данные в конвейер"
- [ ] 4) Документация по Corezoid: https://doc.corezoid.com/ru/api/
- [ ] 5) В проперти AS.properties (generalConfig) разместить єти параметры авторизации для корезоида:
- general.Corezoid.sLogin - строка-логин 
- general.Corezoid.sSecretKey - строка-секретный ключ
- [ ] 6) Добавить, при передаче в конвейер запроса параметр:
- nID_UserTask - ИД-номер юзертаски 
- [ ] 7) Скачать [либу](https://www.dropbox.com/s/u9m8sewe0krmcz1/ConveyorApiUtils-2.2.jar?dl=0) 
и затянуть в наш репозиторий: https://nexus.igov.org.ua

**для предоставления доступа нужно обратиться в скайп: belyavtsevw**

Прописать как зависимость Maven (и туда-же сохранить в репозиторий):
```
<dependency>
          <groupId>com.pb.crm</groupId>
          <artifactId>ConveyorApiUtils</artifactId>
          <version>2.2</version>
</dependency>
```

**Comment by nazarenkod** [comment]
подскажите как проверить?
