### ISSUE TITLE
доработать сервис getSubjectsByAccount

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1200]
- [x] 1) добавить опциональный параметр saLoginExternal и nID_SubjectAccountType
- [x] 2) при задаче п.1 искать через сущность SubjectAccount по полю sLogin из параметра saLoginExternal
- [x] 3) найдя nID_Subject - вывести все данные по субъекту, в т.ч. контакты
- [x] 4) задавать SubjectAccountType по nID_SubjectAccountType
- [x] 5) nID_Server сделать опциональным

**Comment by ArtemTokarenko** [comment]
Принято в роботу

**Comment by kr110666kai** [comment]
Я тут немного помог в решении п.4
Сделал изменения в SubjectAccount https://github.com/e-government-ua/i/commit/34fd47b19bf2f95e0a78136e93b8fc551fe9dc5d
ксательно сохранения SubjectAccountType

**Comment by ArtemTokarenko** [comment]
Покорно благодарю)

**Comment by ArtemTokarenko** [comment]
Тестировщику:
Предисловие: Сервис вытягивает данные по введённым опциональным(не обязательным) параметрам.
Как тестировать: 1)Запустить локальный сервер 2)Ввести логин пароль 3) ввести в адресною строку 
http://localhost:8080/service/subject/getSubjectsByAccount?nID_Server=0&saLoginExternal=["Barmaley"]&saLogin=["Barmaley"]&nID_SubjectAccountType=1       должно вывести 2 одинаковых текста типа {
organs: { },
externalUsers: {
Barmaley: {
sID: "",
sLabel: "Artur Kvasnii",
sLabelShort: "",
aSubjectAccountContact: [
{
subject: {
sID: "",
sLabel: "Artur Kvasnii",
sLabelShort: "",
aSubjectAccountContact: null,
nID: 24
},
subjectContactType: {
sName_EN: "Phone",
sName_UA: "РўРµР»РµС„РѕРЅ",
sName_RU: "РўРµР»РµС„РѕРЅ",
nID: 0
},
sValue: "",
sDate: null,
nID: 1
},
{
subject: {
sID: "",
sLabel: "Artur Kvasnii",
sLabelShort: "",
aSubjectAccountContact: null,
nID: 24
},
subjectContactType: {
sName_EN: "Email",
sName_UA: "Р•Р»РµРєС‚СЂРѕРЅР° Р°РґСЂРµСЃР°",
sName_RU: "Р­Р»РµРєС‚РЅРѕРЅРЅС‹Р№ Р°РґСЂРµСЃ",
nID: 1
},
sValue: "kvasniy@mail.ru",
sDate: null,
nID: 2
}
],
nID: 24
}
},
users: { }
}
Вводим 
http://localhost:8080/service/subject/getSubjectsByAccount?nID_Server=0&saLoginExternal=["Barmaley"]&nID_SubjectAccountType=1  
ожидаем один текст который выше

Вводим 
http://localhost:8080/service/subject/getSubjectsByAccount?nID_Server=0&saLoginExternal=["Barmaley"] 
ожидаем один текст который выше

Вводим 
http://localhost:8080/service/subject/getSubjectsByAccount?saLoginExternal=["Barmaley"]
ожидаем один текст который выше

**Comment by bvv4ik** [comment]
так ведь оно не вылито в ветку тест?

и ссылка:
https://test.region.igov.org.ua/wf/service/subject/getSubjectsByAccount?saLoginExternal=[%22Barmaley%22]&nID_SubjectAccountType=1
- не работает

**Comment by sergeygorban** [comment]
Когда задача будет готова для теста?

**Comment by sergeygorban** [comment]
GET https://test.igov.org.ua/wf/service/subject/getSubjectsByAccount?nID_Server=0&saLoginExternal=["Barmaley"] 
java.net.URISyntaxException: Illegal character in query at index 95: https://test.igov.org.ua/wf/service/subject/getSubjectsByAccount?nID_Server=0&saLoginExternal=["Barmaley"] 
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at java.net.URL.toURI(Unknown Source)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:252)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:74)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1105)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1094)
	at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:429)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257)
	at java.lang.Thread.run(Unknown Source)

**Comment by sergeygorban** [comment]
Опишите сервис хотя бы немного, чтобы можно было тестировать. Какие параметры обязательные, какие нет? Актуально  ли описание сервиса на ресурсе или нет?

**Comment by bvv4ik** [comment]
не акткально
