### ISSUE TITLE
Исправить ошибку экспорта через сервис downloadTasksData

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1201]
Вызвать:
https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?saFieldsCalc=&bHeader=false&sFileName=dohody.dat&sDateCreateFormat=dd.MM.yyyy HH:mm:ss&sDateAt=2016-03-16&saFields=${nID_Task};${sDateCreate};${area};${bankIdinn};;;${bankIdlastName} ${bankIdfirstName} ${bankIdmiddleName};4;${aim};${date_start1};${date_stop1};${place_living};${bankIdPassport};1;${phone};${email}&sID_State_BP=null&sID_Codepage=win1251&sID_BP=dnepr_spravka_o_doxodax&saFieldSummary=&sDateTo=2016-03-18&nASCI_Spliter=18

Предложит сохранить [файл](https://www.dropbox.com/s/4m6ju3hvaz1t7c7/dohody.dat?dl=0)  с таким контентом:
1296553416.03.2016 18:01:21dnepr_and2943209693БІЛЯВЦЕВ ВОЛОДИМИР ВОЛОДИМИРОВИЧ4ТЕСТ для подання за вимогоюdd.MM.yyyydd.MM.yyyyДніпропетровськ, вул. Поля, 1АО295227 БАБУШКИНСКИМ РО В Г ДНЕПРОПЕТРОВСКЕ ГУ ГМС УКРАИНЫ В ДНЕПРОПЕТРОВСКОЙ ОБЛ 17.08.20151380932030405vidokgulich@gmail.com
1306540717.03.2016 14:23:31dnepr_and2943209693БІЛЯВЦЕВ ВОЛОДИМИР ВОЛОДИМИРОВИЧ4ТЕСТ для подання за вимогоюdd.MM.yyyydd.MM.yyyyДніпропетровськ, вул. Поля, 1АО295227 БАБУШКИНСКИМ РО В Г ДНЕПРОПЕТРОВСКЕ ГУ ГМС УКРАИНЫ В ДНЕПРОПЕТРОВСКОЙ ОБЛ 17.08.20151380932030405vidokgulich@gmail.com

Где сейчас неправильно выгружается поле area ( ${area} ), из него должно браться то значение, которое стоит в поле name после вертикального разделителя (это код инспекции): по факту же берется сейчас id элемента

П.С.:
это поламалось букваотно недавно... раньше все работало нормалльно...

считалось так, что в атрибуте "name" хранятся данные, которые могут быть разделенные знаком ";", в таком случае мы должны выгружать при экспорте именно то что находится после второго знака ";"(разделителя/сплитера), т.е. в третьем разряде...

**Comment by dmitrijzabrudskij** [comment]
из поля формы area должен браться не id (он выглядит как dnepr_and в примере Володи), а name, причем после вертикального разделителя (это код налоговой инспекции, он имеет 4 знака, только цифры)
