### ISSUE TITLE
Доработать сервис получения истории заявки /getHistoryEvents

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1202]
добавить опциональный параметр nID_HistoryEvent_Service при задавании которого - выбирать только записи, которые содержат в поле nID_HistoryEvent_Service соответствующий(такой-же) номер

**Comment by kr110666kai** [comment]
Сделано
https://jenkins-new.igov.org.ua/job/central_alpha/ws/wf-central/target/generated-docs/central-igov.html#_Загрузка_событий

**Comment by bvv4ik** [comment]
Метеор!)
я оглянуться не успел)
Спасибо!

**Comment by bvv4ik** [comment]
а я тут как раз ишью писал, по интеграции iGov с давно использующейся в "нашей организации сервис сохранения ошибок MSG", который вот только-только развернули на ДеНово в рамках проекта iGov)

и вот подумал, тамжеж АПИ-документация доступна только из внутренней сети и пришлось-бы что-то переносить в гуглодок(копипасти) а ччто-то периодически просить и до-вросить...

может, чтоб избежать всего этого гимороя, не сложно было-бы взяться за эту таску?
https://github.com/e-government-ua/i/issues/1203
(ведь доступ к внутренней сети-ж есть)

**Comment by kr110666kai** [comment]
Да, конечно

**Comment by sergeygorban** [comment]
В рамках тестирование необходимо понимать следующее:
nID_Subject - это ID пользователей портала Igov или что то другое?  Как мне получить мой ID?
getHistoryEvents - если в метод передать только nID_Subject, я получу всю историю пользователя? Необходим полный перечень того, что подразумевается под историей пользователя
nID_HistoryEvent_Service - как получить значения этого параметра?

**Comment by bvv4ik** [comment]
реализация давно используется фронтовой реализацией новой навигации
потому отдельно уже не имеет смысло тестировать
