### ISSUE TITLE
Подключить механизм отсылки сообщеинй об ошибках и начать отсылать сообщения из интерфейса:

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1203]
- [ ] **1) Подключить сам механизм** - на wf-base:

- [x] 1.1) Подключить либу
- Оригинальное место либы в: http://nexus.ci.it.loc/#nexus-search;classname~MSGCore
(в доке есть депенденси) но т.к. репозиторий недоступен "из вне", то

скачать ее можно [тут](https://www.dropbox.com/s/sk9gafiwsxrdldx/MSGCore-2.0.1.032.jar?dl=0): 
и, разместить тут: https://nexus.igov.org.ua
**для предоставления доступа нужно обратиться в скайп: belyavtsevw**

Прописать как зависимость Maven (и туда-же сохранить в репозиторий):
```
<dependency>
          <groupId>com.pb.ksv</groupId>
          <artifactId>msgcore</artifactId>
          <version>2.0.1.032</version>
</dependency>

```

- [ ] 1.2) Написать обертку вызова с флюент-интерфейсом:
- [Дока по либе](https://itwiki.privatbank.ua/wiki/Java_%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0_%D0%BF%D0%BE_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B5_%D1%81_%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D0%BE%D0%BC_%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B9)

- [Дока по ЕСО](https://itwiki.privatbank.ua/wiki/%D0%A1%D0%B5%D1%80%D0%B2%D0%B8%D1%81_%D1%85%D1%80%D0%B0%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F_%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA)

- [ ] 1.3) Проверить заход в интерфейс:

- [Интерфейс статистики МСГ](http://msg.igov.org.ua/message-service-statistics/)

- [Админка МСГ](http://msg.igov.org.ua/message-service-administration/index):
**Нужен ваш емейл,для предоставления доступа**

- [ ] **2) Начать отсылать данные**, приходящие в сервис /action/event/setEventSystem - на wf-central:

Через обертку п.1.2 слать данные

Ключем считать:
- sType+sFunction

Остальные параметры как вспомогательные:
- sHead
- sBody
- sError
- nID_Subject
- nID_Server

В том числе отдельно под-объект:
- sDate
- smData
- asParam

В том числе отдельно композитный под-объект, состоящий из под-объектов:
- smDataMisc = sResponseMessage+sResponseCode+soResponseData

**Comment by bvv4ik** [comment]
п.1.1 уже реализован

**Comment by bvv4ik** [comment]
главное теперь п.1.2 и 2

**Comment by kr110666kai** [comment]
Как быть с этим:
https://itwiki.privatbank.ua/wiki/%D0%A1%D0%B5%D1%80%D0%B2%D0%B8%D1%81_%D1%85%D1%80%D0%B0%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F_%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA
1) Обратиться к аналитику (Синяев А.) для заведения бизнес процесса в справочник сервиса сообщений. ... весь п.1...

Я же не могу просто так попросить, да и с некоторыми полями определиться надо.

**Comment by bvv4ik** [comment]
бизнеспроцесс уже заведен

**Comment by bvv4ik** [comment]
там только осталось доступ зарегить входа в админку и мониторилку

**Comment by bvv4ik** [comment]
я могу добавить в скайп к коллегам и со мной, чтоб можно было любые просьбы напрямую озвучивать, а я поспособствую

**Comment by bvv4ik** [comment]
добавил в скайп-группу)

**Comment by bvv4ik** [comment]
может в чем-то помощь нужна?

**Comment by kr110666kai** [comment]
На текущий момент я уже отсылаю простенькое сообщение на сервис из теста. 

Есть несколько непонятных вопросов, но надо сформулировать их для себя.

**Comment by kr110666kai** [comment]
1. Вопрос
```
Ключем считать:
sType+sFunction
```
Непонятно что это за параметры и куда их применять. Я предполагаю что **sType** это Классификация типов сообщений: 

- Ошибка доступа(авторизация) 
- Ошибка валидации входящих данных 
- Информационное сообщение 
- Предупреждение 
- Внутренняя ошибка 
- Внешняя ошибка 

а **sFunction**?

2. Вопрос
```
В том числе отдельно под-объект:
sDate
smData
asParam
В том числе отдельно композитный под-объект, состоящий из под-объектов:
smDataMisc = sResponseMessage+sResponseCode+soResponseData
```
Но ведь все эти данные получаются из **smData**.
Имеет смысл хранить и **smData** и  то что из него достается?

**Comment by kr110666kai** [comment]
Хочу развернуть вопрос про **sType+sFunction**

Для отсылки сообщений в МСГ надо завести шаблон сообщения (в терминах МСК просто сообщение). После этого можно отсылать сообщение указанного вида и все они будут привязаны к заведенному шаблону.

Например заведем **один** шаблон сообщения с кодом **IGOV-ERROR**.
**sType+sFunction** это должны быть поля шаблона** IGOV-ERROR**?
В этом случае вопросов нет все ясно.

но может имеется ввиду что нужно создать много шаблонов сообщений с кодом вида **sType+sFunction**? 
В этом случае нужен список **sType+sFunction**

**Comment by kr110666kai** [comment]
Можно подключить механизм, так как я его понял, а далее уже доводить до ума.

**Comment by kr110666kai** [comment]
http://msg.igov.org.ua/message-service-statistics/index?ReqId=2PDH6AHGURH3RIQ$

**Comment by bvv4ik** [comment]
я вижу уже что-то появилось)
http://msg.igov.org.ua/message-service-statistics/index?Dep=111111111111&BusId=TEST&RM=0&TI=2

**Comment by bvv4ik** [comment]
осталось, как я понял - прикрутить уже постоянную рассыдлку с того сервиса?

**Comment by bvv4ik** [comment]
@kr110666kai  "Хочу развернуть вопрос про sType+sFunction"

по сути, sType может принимать значения:
danger - реально опасность (ошибка)
warning - просто предупреждение (не страшно но стоит знать)
success - просто информация о событии


sFunction - это:
функция, в которой это поисходит... 
этих функций может быть очень много, и их всех даже не перечислить с ходу..


соединение этих двух параметров позволяет создать ключевой ассортимент значимых событий/соообщений

все остальное(в т.ч. разные параметры и т.д. - внутри передаем)


так вот, чтоб не заводить ручками каждый раз весь этот ассортимент событий - нужно воспользоваться их сервисом, который позволяет добавлять новые события (нужно доку почитать)

и можно просто при появлении нового события просто дергать их сервис чтоб оно у них добавлялось

**Comment by bvv4ik** [comment]
@kr110666kai
"Вопрос
В том числе отдельно под-объект:
sDate
smData
asParam
В том числе отдельно композитный под-объект, состоящий из под-объектов:
smDataMisc = sResponseMessage+sResponseCode+soResponseData
Но ведь все эти данные получаются из smData.
Имеет смысл хранить и smData и то что из него достается?"

я наверно случаянно упомянул в ряду и "smData"...
дублировать конечно-же не надо, но важно чтоб вся инфа в итоге туда передалась..

**Comment by kr110666kai** [comment]
По **sType+sFunction** сейчас общаюсь с ребятами, есть ли возможность сделать автоматическое добавление.

По **smData** его разборку честно скопировал с **/action/event/setEventSystem** 
соответственно на его основании воссоздал JSON структуру smData
```
{
	"asParam": ["par1", "par2", "par3"],
	"oResponse": {
		"sMessage": "value sMessage",
		"sCode": "value sCode",
		"soData": "value soData"
	},
	"sDate": "value sDate"
}
```
Может есть где-то есть ее (**smData**) определение?

**Comment by kr110666kai** [comment]
По автоматическому добавлению  sType+sFunction мне ответили:
```
такой возможности нет
[10:06:30] mayer.info: и в первую очередь потому, что при заведении ошибки нужно указывать ее вменяемое описание
[10:06:39] mayer.info: есть возможность завести ошибки скопом из файла
```
Поэтому предлагаю завести сообщения с нужными нам **sType**, а **sFunction** помещать в атрибуты, как и **sHead, sBody, sError** и т.д.

**Comment by OlgaTurenko** [comment]
апи для автоматического добавления нового типа сообщения через сервис:

MSG_ADD. Добавление сообщений.[править]

Протокол запроса:
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<doc>
  <r cntr="UA" key="0" sid="#sid#" t="MSG_ADD"/>
    <s Type='' MsgCode='' BusId='' Descr='' TemplateMsgId='' >
      <LocalMsg  Level="" Lang="" Text="" Title="" FullText=""/>
      <Attr Type="" Value="" SubValue="" />
    </s>
  </doc>


Требования в теге <s/>: 
1) Все параметры являются обязательными. 
2) Параметр Type может принимать значения только справочные значения из поля MsgType, таблица tRefMsgType. 
3) Параметр BusId может принимать значения только справочные значения из поля BusId, таблица tRefBusProc. 
4) Параметр TemplateMsgId может принимать значения только справочные значения из поля TemplateMsgId, таблица tRefMainTemplates. 
5) Параметр MsgCode должен быть уникален в рамках таблицы tMsg. 
Общие требования: 
1) При создании сообщения нужно учесть, что с сообщением должно быть создано минимум одно LocalMsg. 
2) Тег атрибутов сообщений (Attr) являются необязательным параметром. 
3) Обязательными параметрами в локализированном сообщении(LocalMsg) являются: Level, Lang, Text. Level - согласно справочника уровней. Lang согласно 
справочника(справочник захаркожен). 
4) Обязательными параметрами в атрибутах сообщения(Attr) являются: Type, Value. Type - согласно справочника типов атрибутов.

**Comment by kr110666kai** [comment]
Думаю в Пятницу закончу вопрос, Сегодня отделение открываем.

**Comment by kr110666kai** [comment]
Вопрос застрял на получении гугловской сессии для автjризации на сервисе сообщений.
Сейчас разбираюсь как сделать через GoogleAPI

**Comment by kr110666kai** [comment]
Пока не нашел решения как получить гугловскую сесиию без ручного ввода. Разбираюсь дальше.

**Comment by kr110666kai** [comment]
1. Задача запущена в рамках бизнес-процесса TEST.
2. msg.log пока оставил в debug

**Comment by kr110666kai** [comment]
В классе https://github.com/e-government-ua/i/blob/test/wf-central/src/main/java/org/igov/service/business/msg/MsgSendImpl.java  есть подробное описание

**Comment by bvv4ik** [comment]
сори, я как-то замотался с другими задачами, и упустил из вида эту...

"1.Задача запущена в рамках бизнес-процесса TEST."
я-ж так понимаю - это он принимает только все то что на тестовом происходит?

можно ,плиз, ориентируясь на флаг bTest в generalConfig - лить в т.ч. и в прод-БП
а то у нас свалка будет...

**Comment by kr110666kai** [comment]
```
"1.Задача запущена в рамках бизнес-процесса TEST."
я-ж так понимаю - это он принимает только все то что на тестовом происходит?
```

Имеется ввиду, что нам на http://msg.igov.org.ua/message-service-administration/index завели только бизнес-процесс с кодом TEST, больше ничего не заводили. На него сейчас все и льется.

```
2. можно ,плиз, ориентируясь на флаг bTest в generalConfig - лить в т.ч. и в прод-БП
а то у нас свалка будет...
```

Нам ничего кроме TEST не заводили, я так понимаю надо попросить завести еще один БП и лить данные туда.
Бизнесс-процесс можно задать в 
https://github.com/e-government-ua/i/blob/test/wf-central/src/main/resources/msg.properties
BusId=TEST

**Comment by kr110666kai** [comment]
Еще, возникает вопрос: для наших нужд размеры полей атрибутов 60 символов малы, 
Надо попросить расширить, вопрос до какой величины?

**Comment by kr110666kai** [comment]
На Сервисе сообщений заведены три Бизнес-процесса:

**IGOV_PROD** - iGov Прод
**IGOV_TEST_BETA** - iGov Тест-бета
**IGOV_TEST** - iGov Тест-альфа


Выбор в какой Бизнес-процесс лить сообщения задается в файле свойств **wf-central/src/main/resources/msg.properties**.
свойство:
```
  BusId=TEST            # лить в БП iGov Тест-альфа
  BusId=IGOV_TEST_BETA  # лить в БП iGov Тест-бета
  BusId=IGOV_PROD       # лить в БП iGov Прод
```

Я, завел три преднастроенных файла свойств:
- **wf-central/src/main/resources/msg.properties.alfa**
- **wf-central/src/main/resources/msg.properties.beta**
- **wf-central/src/main/resources/msg.properties.prod**

Можно просто перезаписывать **msg.properties** нужным файлом

**Comment by kr110666kai** [comment]
Я вот подумал, а не логичнее ли перенести свойства для настройки работы механизма в AS.properties?  Например;
```
# MSG 
general.msg.sMsgURL=http://msg.igov.org.ua/MSG
general.msg.sBusId=TEST
general.msg.sTemplateMsgId=HMXHVKM80002M0
general.msg.sMsgLogin=kr110666kai@gmail.com

```
Соответственно, для работы добавить сервис org.igov.service.business.msg.MsgService.

**Comment by OlgaTurenko** [comment]
" а не логичнее ли перенести свойства для настройки работы механизма в AS.properties"  очень даже логично :)

**Comment by kr110666kai** [comment]
Настрока работы сервиса перенесена в **AS.properties**

Пример для TEST - Alfa
```
# MSG Alfa
general.msg.sMsgURL=http://msg.igov.org.ua/MSG
general.msg.sBusId=TEST
general.msg.sTemplateMsgId=HMXHVKM80002M0
general.msg.sMsgLogin=kr110666kai@gmail.com
```

**Comment by kr110666kai** [comment]
Перенес пакет в wf-base

**Comment by kr110666kai** [comment]
В org.igov.io.mail.Mail добавлена запись в Сервис Хранения Ошибок в случае события нудачной
отправки письма через UniSender
https://github.com/e-government-ua/i/commit/a5157ebd5e86d17e6dc51c973b7f8a5100256f68

**Comment by kr110666kai** [comment]
В  https://github.com/e-government-ua/i/blob/6d4c6cdd34e3975b134303245335e14648e8a25d/wf-base/src/main/java/org/igov/io/mail/Mail.java 
в send() заменил прямой вызов sendOld() на вызов sendAlternativeWay(sbBody.toString());
Тепер в MSG  должны пересылаться все ошибки

**Comment by kr110666kai** [comment]
Добавлена отсылка сообщения об ошибке в RequestProcessingInterceptor
