### ISSUE TITLE
Некорректное отображение времени регистрации заявки

### ISSUE THREAD

**Issue by smoktii-igov** [e-government-ua/i#1204]
При переходе по ссылке из письма, где указано номер заявки и УРЛ, где можно посмотреть ее статус - некорректно отображается время регистрации заявки
![error0т](https://cloud.githubusercontent.com/assets/17428200/13922608/b3a9a1e0-ef85-11e5-9fd8-a23d08793d92.png)

**Comment by smoktii-igov** [comment]
Может не конвертится переменная при сохранении во время по Гринвичу, а потом преобразуется при отображении?

**Comment by Julia-tera** [comment]
Дозвіл на розміщення зовнішньої реклами : 
При выборе  Области: Днепропетровская, и попытки выбрать город  выпадает ошибка: 
Помилка 
c is null (caused by "undefined")
Час: "2016-03-24T10:56:23.205Z"

http://clip2net.com/s/3w06TgO

**Comment by smoktii-igov** [comment]
Если на Альфе потыкать мышью в разные выпадающие списки, то список все-таки покажется.

**Comment by Julia-tera** [comment]
саму проблему будем устранять?

**Comment by Julia-tera** [comment]
Дозвіл на розміщення зовнішньої реклами:
В полях : 
*Копія виписки з єдиного державного реєстру юридичних осіб та фізичних осіб:
*Ескіз рекламного засобу з конструктивним рішенням:
*Фотокартка або комп'ютерний макет місця, на якому планується розташування реклами:
Розмір має бути не менш 6х9 см.

Позволяет прикреплять файлы любого формата. включая инсталляшки приложения и музыку
http://clip2net.com/s/3w5EzNI

**Comment by Julia-tera** [comment]
При подаче заявки Дозвіл на розміщення зовнішньої реклами:
во время сохранения данных получаем сообщения об ошибке 

Помилка по операції: 'Сабміт форми послуги'
Помилка відсилки єлектронної пошти! (скоріш за все не вірні дані вказані у формі чи електроний адрес)
Час: "2016-03-26T10:14:49.671Z" , Функція: submitForm
Відповідь сервера:
Повідомленя: couldn't execute activity <serviceTask id="servicetask5" ...>: Error happened when sending email (sClerkPost)Код: SYSTEM_ERRІнші дані (обь'єкт): {"code":null,"message":null}
Значення параметрів:
nID_Service: 15,nID_ServiceData: 624,processDefinitionId: dnepr_cnap_184:1:1,saField: 



Скрины ошибок:
http://clip2net.com/s/3w5EZEe,
http://clip2net.com/s/3w5EZEe

почтовый ящик введен корректно.
http://clip2net.com/s/3w5F9ns

**Comment by Julia-tera** [comment]
При подаче заявки Дозвіл на розміщення зовнішньої реклами:
во время сохранения данных получаем сообщения об ошибке:
 
Такий код ЄДРПОУ не існує - (ви не можете вписувати літери) 

Код корректный
http://clip2net.com/s/3w5HTYA

**Comment by Julia-tera** [comment]
Ошибка не устранена. 
Будут ли устранять эти баги?
http://clip2net.com/s/3wTUoMr

**Comment by Julia-tera** [comment]
Время регистрации заявки отображается корректно. 
![6](https://cloud.githubusercontent.com/assets/17043155/14720306/8b324f0e-0809-11e6-8a84-f804caea0ebc.png)
