### ISSUE TITLE
"a.includes is not a function" on the main page.

### ISSUE THREAD

**Issue by redixin** [e-government-ua/i#1205]
Currently https://igov.org.ua/ looks like this: https://i.imgur.com/zl7gJqg.png

**Comment by bvv4ik** [comment]
When happens?

**Comment by redixin** [comment]
This is weird. There is no such error in firefox. I can see this error only in iceweasel (38.4.0esr-1)

**Comment by redixin** [comment]
The problem is Array.prototype.includes not supported by some browsers (firefox<=43, standard android browser)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**Comment by redixin** [comment]
The same error in default android-4 browser: https://i.imgur.com/EAwJTT9.png
