### ISSUE TITLE
Добавить в форме заполнения услуги виртуальный параметр bReferent, в котором отражать включенность режима референтности

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1206]
- [ ] 1) Если нет его, то добавлять параметр bReferent в объект с параметрами формы до того как эти поля будут отрисованы на форме (судя по всему в фабрике), устанавливая в нем writible=false.
- [ ] 2) При включении режима референтности записывать туда значение true иначе false .и обязательно "рефрешить" механизм отработки маркеров (если он не сработает автоматом)
- [ ] 3) Изначально предусмотреть, что такой параметр может и быть в бизнеспроцессе... в таком случае п.1 просто не должен отработать.

**Comment by MaksKnight** [comment]
Все работает корректно.
