### ISSUE TITLE
Починить доступность истории любой заявки - администратору

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1207]
Почему-то перестало позволять для администратора (когда он авторизован на централе) - смотреть детальную историю по любой заявке.

Сейчас если на тестовом -альфе авторизоваться под тестовым акаунтом - должно давать права администратора

Чтоб проверить:
нужно подать любую заявку авторизовавшись не под тестовым акаунтом а ПОД СОБОЙ (можно тестовую из подкатегории тестовых) и получив ее номер (в формате Х-ХХХХХХХ) найти ее в Моем журнале (чтоб перешло в профиль истории по ней)

При заходе туда ПОД СОБОЙ должно отображаться возможность внести коментарий... нужно его внести, чтоб он добавился ниже.

потом нужно "Выйти"(в верхнем-правом углу разавторизоваться) и уже авторизоваться под тестовым акаунтом (в вики в нашем хозяйстве есть номер телефона пароль и СМС)
и в этой-же истории сейчас под ним не будет видно списка коментов... а должно! т.к. тестовый акаунт имеет роль админа.

проблема гдето видать на беке в этом сервисе, где идет проверка на isAdmin в обьекте сессии.
чтото при последних реализациях поламали (ранее работало)

постараться осторожно

**Comment by ijmac** [comment]
Что-то под собой даже комментарий добавить не могу

**Comment by ijmac** [comment]
Добавление комментов починил, только пока без авторендеринга, надо Ctrl+R

**Comment by ijmac** [comment]
По поиску в тестовом пользователе заявка не ищется,  если заходить по прямой ссылке заявки https://test.igov.org.ua/search?sID_Order=0-154243360, все ок и комментарии тоже видны

**Comment by ijmac** [comment]
Авторендеринг поправил, протестировал, работает
