### ISSUE TITLE
Исправить фильтр городов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1209]
Услуга:
"Виготовлення викопіювання в масштабі 1:500, 1:2000"
https://igov.org.ua/service/734/general

- реализована только для Днепропетровска (ну и г.Тернополь)
```
312;734;10;10;NULL;4;{"processDefinitionId":"ternopol_cnap_vikop:1:58"};;false;1;false;;BankID,EDS;0
493;734;1;1;NULL;4;{"processDefinitionId":"dnepr_GlavAPU_258:1:1"};;false;1;false;;BankID,EDS;0
```

но при выборе фильтра на главной странице Днепропетровская обл.+КривойРог - она всеравно отобразится

![image](https://cloud.githubusercontent.com/assets/4208821/13985314/b847df2a-f104-11e5-885f-1a496d9783b4.png)

П.С.: Логика работы фильтра должна быть такая:
- при выборе области туда должны попадать и все услуги областные и услуги чисто городские, города которых находятся в этой-же области
- при выборе следующего фильтра "города" - должны также оставаться все областные услуги(этой области) в выборке + услуги именно того города, который выбран.(сейчас-же, почему-то, продолжают отображаться услуги и из других городов этой области)

**Comment by ijmac** [comment]
Исправил, запушил, дождался деплоя, на тесте попробовал, работает

**Comment by sergeygorban** [comment]
Не понятно, что значит услуги областные? Это услуги доступные для всех городов области? Как понять какая услуга относится к конкретному городу? Есть список услуг для конкретных городов?

**Comment by GrekD** [comment]
Не понятно, что значит услуги областные? 
Это значит что услуга оказывается для всех городов области - раскрывается сразу на всю область, а не на конкретные города

Как понять какая услуга относится к конкретному городу?
В задаче приведен пример на котором можно проверять:
"Виготовлення викопіювання в масштабі 1:500, 1:2000"
https://igov.org.ua/service/734/general
она реализована только для Днепропетровска (ну и г.Тернополь)
но при выборе фильтра на главной странице Днепропетровская обл.+КривойРог - она всеравно отобразится, в то время как для Кривого рога отображаться не должна

**Comment by sergeygorban** [comment]
Спасибо

**Comment by sergeygorban** [comment]
Дефект исправлен

**Comment by annastolbova** [comment]
@sergeygorban , добрый день,

при фильтрации по городу не отображаются областные услуги, которые может заказать любой житель области
пример такой областной услуги 
https://igov.org.ua/service/1400/general

фильтр делаю на примере г.Никополь (днепропет-ой обл.), эта услуга после фильтрации не отображается.
