### ISSUE TITLE
Запуск послуг для Комсомольської  райради у м. Херсоні 

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/i#1211]
СПИСОК
адміністративних послуг які можуть надаватися 
Комсомольською районною у м. Херсоні радою та її виконавчими органами 
в електронному вигляді через мережу Інтернет в Херсонській області

№ з/п	Відповідальна особа,
прізвище,
ім'я, по батькові та
посада
	Вид послуги, допомоги	Повна адреса
(вулиця, номер будинку, населений пункт, район, область, поштовий індекс)	Контактний телефон для довідок з питань …
(код міжміського зв’язку, номер телефону)	Електронна адреса
1.		Стерлюс Ірина Олександрівна – головний спеціаліст-координатор відділу призначення державних допомог,
Кулакова Любов Віліївна – головний спеціаліст-інформатор відділу призначення державних допомог	 Звернення до голови районної ради	вул. Суворова, 29, м. Херсон, Херсонська область, 73000	(0552) 22-96-81
	komsomol2007@ukr.net

2.		Стерлюс Ірина Олександрівна – головний спеціаліст-координатор відділу призначення державних допомог,
Кулакова Любов Віліївна – головний спеціаліст-інформатор відділу призначення державних допомог	Запис на прийом для отримання субсидії на оплату житлово-комунальних послуг	вул. Суворова, 29, м. Херсон, Херсонська область, 73000	(0552) 22-96-81
	komsomol2007@ukr.net

3.	Стерлюс Ірина Олександрівна – головний спеціаліст-координатор відділу призначення державних допомог,
Кулакова Любов Віліївна – головний спеціаліст-інформатор відділу призначення державних допомог	Запис на прийом для призначення допомоги при народженні дитини (ст..3 Закону України «Про державну допомогу сім’ям з дітьми»)	вул. Суворова, 29, м. Херсон, Херсонська область, 73000	(0552) 22-96-81
	komsomol2007@ukr.net

4.	Стерлюс Ірина Олександрівна – головний спеціаліст-координатор відділу призначення державних допомог,
Кулакова Любов Віліївна – головний спеціаліст-інформатор відділу призначення державних допомог	Запис на прийом для призначення державної соціальної допомоги малозабезпеченим сім’ям (Закон України «Про державну соціальну допомогу малозабезпеченим сім’ям»)	вул. Суворова, 29, м. Херсон, Херсонська область, 73000	(0552) 22-96-81
	komsomol2007@ukr.net

5.	Стерлюс Ірина Олександрівна – головний спеціаліст-координатор відділу призначення державних допомог,
Кулакова Любов Віліївна – головний спеціаліст-інформатор відділу призначення державних допомог	Запис на прийом Призначення допомоги на дітей одиноким матерям (ст. 3 Закону України «Про державну допомогу сім’ям з дітьми»)	вул. Суворова, 29, м. Херсон, Херсонська область, 73000	(0552) 22-96-81
	komsomol2007@ukr.net

6.	Стерлюс Ірина Олександрівна – головний спеціаліст-координатор відділу призначення державних допомог,
Кулакова Любов Віліївна – головний спеціаліст-інформатор відділу призначення державних допомог	Запис на прийом Призначення допомоги на дітей, над якими встановлено опіку чи піклування (ст. 3 Закону України «Про державну допомогу сім’ям з дітьми»)	вул. Суворова, 29, м. Херсон, Херсонська область, 73000	(0552) 22-96-81
	komsomol2007@ukr.net

7.	Стерлюс Ірина Олександрівна – головний спеціаліст-координатор відділу призначення державних допомог,
Кулакова Любов Віліївна – головний спеціаліст-інформатор відділу призначення державних допомог	Запис на прийом Призначення державної соціальної допомоги на дітей-сиріт та дітей, позбавлених батьківського піклування та грошового забезпечення батькам-вихователям, прийомним батькам (Постанова Кабінету Міністрів від 31.01.2007 р. №81)	вул. Суворова, 29, м. Херсон, Херсонська область, 73000	(0552) 22-96-81
	komsomol2007@ukr.net

8.	Стерлюс Ірина Олександрівна – головний спеціаліст-координатор відділу призначення державних допомог,
Кулакова Любов Віліївна – головний спеціаліст-інформатор відділу призначення державних допомог	Запис на прийом Призначення допомоги при усиновленні дитини (ст. 3 Закону України «Про державну допомогу сім’ям з дітьми»)	вул. Суворова, 29, м. Херсон, Херсонська область, 73000	(0552) 22-96-81
	komsomol2007@ukr.net

9.	Стерлюс Ірина Олександрівна – головний спеціаліст-координатор відділу призначення державних допомог,
Кулакова Любов Віліївна – головний спеціаліст-інформатор відділу призначення державних допомог	Запис на прийом Призначення допомоги у зв'язку з вагітністю та пологами (ст. 3 Закону України «Про державну допомогу сім’ям з дітьми»)	вул. Суворова, 29, м. Херсон, Херсонська область, 73000	(0552) 22-96-81
	komsomol2007@ukr.net

10.	Стерлюс Ірина Олександрівна – головний спеціаліст-координатор відділу призначення державних допомог,
Кулакова Любов Віліївна – головний спеціаліст-інформатор відділу призначення державних допомог	Запис на прийом Призначення компенсаційної виплати непрацюючій працездатній особі, яка доглядає за інвалідом І групи, а також за престарілим, який досяг 80-річного віку (Постанова Кабінету Міністрів від 26.07.1996 р. №832)	вул. Суворова, 29, м. Херсон, Херсонська область, 73000	(0552) 22-96-81
	komsomol2007@ukr.net

11.		Запис на прийом Призначення одноразової винагороди жінкам, яким присвоєно почесне звання "Мати-героїня" (Постанова Кабінету Міністрів від 28.02.2011 р. №268)			
12.	Стерлюс Ірина Олександрівна – головний спеціаліст-координатор відділу призначення державних допомог,
Кулакова Любов Віліївна – головний спеціаліст-інформатор відділу призначення державних допомог	Запис на прийом Призначення державної соціальної допомоги особам, які не мають права на пенсію, та інвалідам (Закон України «Про державну соціальну допомогу особам, які не мають права на пенсію, та інвалідам»)	вул. Суворова, 29, м. Херсон, Херсонська область, 73000	(0552) 22-96-81
	komsomol2007@ukr.net

13.	Стерлюс Ірина Олександрівна – головний спеціаліст-координатор відділу призначення державних допомог,
Кулакова Любов Віліївна – головний спеціаліст-інформатор відділу призначення державних допомог	Запис на прийом Призначення тимчасової державної допомоги дітям, батьки яких ухиляються від сплати аліментів, не мають можливості утримувати дитину або місце проживання їх невідоме (Постанова Кабінету Міністрів від 22.02.2006 р. №189)	вул. Суворова, 29, м. Херсон, Херсонська область, 73000	(0552) 22-96-81
	komsomol2007@ukr.net

14.	Стерлюс Ірина Олександрівна – головний спеціаліст-координатор відділу призначення державних допомог,
Кулакова Любов Віліївна – головний спеціаліст-інформатор відділу призначення державних допомог	Запис на прийом Призначення щомісячної грошової допомоги особі, яка проживає разом з інвалідом I чи II групи внаслідок психічного розладу, який за висновком лікарської комісії медичного закладу потребує постійного стороннього догляду, на догляд за ним (Постанова Кабінету Міністрів від 28.08.2000 р. №1192)	вул. Суворова, 29, м. Херсон, Херсонська область, 73000	(0552) 22-96-81
	komsomol2007@ukr.net

 Кулик Павло

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net
Тел: +380661622002
Блог:https://www.facebook.com/kylikpavel, 
https://www.facebook.com/profile.php?id=10001084

**Comment by Koffeek** [comment]
Будь ласка перенесіть завдання у репозиторій бізнес-аналітиків (https://github.com/e-government-ua/iBP/issues), та розбийте по окремих послугах.
