### ISSUE TITLE
Запуск послуг в Дніпровській райраді у м. Херсон 

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/i#1212]
СПИСОК
адміністративних послуг які можуть надаватися 
Дніпровською районною у м. Херсоні радою та її виконавчими органами 
в електронному вигляді через мережу Інтернет в Херсонській області
 
1.		Гузь Оксана Інтигамівна, головний спеціаліст з інформаційно-аналітичного забезпечення	 Звернення до голови районної ради	вул. Перекопська,166, каб.300,
м. Херсон, Херсонська область, 73000	(0552) 35-43-45
(0552) 51-98-69	drik@ukr.net

2.		Дзьоба Оксана Петрівна, головний спеціаліст;
Шеремет Любов Андріївна, провідний спеціаліст	Запис на прийом для отримання субсидії на оплату житлово-комунальних послуг	вул. Перекопська,166, каб.104,
м. Херсон, Херсонська область, 73000	(0552) 35-44-65	drik@ukr.net

3.		Дзьоба Оксана Петрівна, головний спеціаліст;
Шеремет Любов Андріївна, провідний спеціаліст	Запис на прийом для призначення допомоги при народженні дитини (ст..3 Закону України «Про державну допомогу сім’ям з дітьми»)	вул. Перекопська,166, каб.104,
м. Херсон, Херсонська область, 73000	(0552) 35-44-65	drik@ukr.net

4.		Дзьоба Оксана Петрівна, головний спеціаліст;
Шеремет Любов Андріївна, провідний спеціаліст	Запис на прийом для призначення державної соціальної допомоги малозабезпеченим сім’ям (Закон України «Про державну соціальну допомогу малозабезпеченим сім’ям»)	вул. Перекопська,166, каб.104,
м. Херсон, Херсонська область, 73000	(0552) 35-44-65	drik@ukr.net

5.		Дзьоба Оксана Петрівна, головний спеціаліст;
Шеремет Любов Андріївна, провідний спеціаліст	Запис на прийом Призначення допомоги на дітей одиноким матерям (ст. 3 Закону України «Про державну допомогу сім’ям з дітьми»)	вул. Перекопська,166, каб.104,
м. Херсон, Херсонська область, 73000	(0552) 35-44-65	drik@ukr.net

6.		Дзьоба Оксана Петрівна, головний спеціаліст;
Шеремет Любов Андріївна, провідний спеціаліст	Запис на прийом Призначення допомоги на дітей, над якими встановлено опіку чи піклування (ст. 3 Закону України «Про державну допомогу сім’ям з дітьми»)	вул. Перекопська,166, каб.104,
м. Херсон, Херсонська область, 73000	(0552) 35-44-65	drik@ukr.net

7.		Дзьоба Оксана Петрівна, головний спеціаліст;
Шеремет Любов Андріївна, провідний спеціаліст	Запис на прийом Призначення державної соціальної допомоги на дітей-сиріт та дітей, позбавлених батьківського піклування та грошового забезпечення батькам-вихователям, прийомним батькам (Постанова Кабінету Міністрів від 31.01.2007 р. №81)	вул. Перекопська,166, каб.104,
м. Херсон, Херсонська область, 73000	(0552) 35-44-65	drik@ukr.net

8.		Дзьоба Оксана Петрівна, головний спеціаліст;
Шеремет Любов Андріївна, провідний спеціаліст	Запис на прийом Призначення допомоги при усиновленні дитини (ст. 3 Закону України «Про державну допомогу сім’ям з дітьми»)	вул. Перекопська,166, каб.104,
м. Херсон, Херсонська область, 73000	(0552) 35-44-65	drik@ukr.net

9.		Дзьоба Оксана Петрівна, головний спеціаліст;
Шеремет Любов Андріївна, провідний спеціаліст	Запис на прийом Призначення допомоги у зв'язку з вагітністю та пологами (ст. 3 Закону України «Про державну допомогу сім’ям з дітьми»)	вул. Перекопська,166, каб.104,
м. Херсон, Херсонська область, 73000	(0552) 35-44-65	drik@ukr.net

10.		Дзьоба Оксана Петрівна, головний спеціаліст;
Шеремет Любов Андріївна, провідний спеціаліст	Запис на прийом Призначення компенсаційної виплати непрацюючій працездатній особі, яка доглядає за інвалідом І групи, а також за престарілим, який досяг 80-річного віку (Постанова Кабінету Міністрів від 26.07.1996 р. №832)	вул. Перекопська,166, каб.104,
м. Херсон, Херсонська область, 73000	(0552) 35-44-65	drik@ukr.net

11.		Іванова Тетяна Павлівна, завідувач сектором персоніфікованого обліку пільгових категорій громадян	Запис на прийом Призначення одноразової винагороди жінкам, яким присвоєно почесне звання "Мати-героїня" (Постанова Кабінету Міністрів від 28.02.2011 р. №268)	вул. Перекопська,166, каб.112,
м. Херсон, Херсонська область, 73000	(0552) 35-19-88	drik@ukr.net

12.		Дзьоба Оксана Петрівна, головний спеціаліст;
Шеремет Любов Андріївна, провідний спеціаліст	Запис на прийом Призначення державної соціальної допомоги особам, які не мають права на пенсію, та інвалідам (Закон України «Про державну соціальну допомогу особам, які не мають права на пенсію, та інвалідам»)	вул. Перекопська,166, каб.104,
м. Херсон, Херсонська область, 73000	(0552) 35-44-65	drik@ukr.net

13.		Дзьоба Оксана Петрівна, головний спеціаліст;
Шеремет Любов Андріївна, провідний спеціаліст	Запис на прийом Призначення тимчасової державної допомоги дітям, батьки яких ухиляються від сплати аліментів, не мають можливості утримувати дитину або місце проживання їх невідоме (Постанова Кабінету Міністрів від 22.02.2006 р. №189)	вул. Перекопська,166, каб.104,
м. Херсон, Херсонська область, 73000	(0552) 35-44-65	drik@ukr.net

14.		Дзьоба Оксана Петрівна, головний спеціаліст;
Шеремет Любов Андріївна, провідний спеціаліст	Запис на прийом Призначення щомісячної грошової допомоги особі, яка проживає разом з інвалідом I чи II групи внаслідок психічного розладу, який за висновком лікарської комісії медичного закладу потребує постійного стороннього догляду, на догляд за ним (Постанова Кабінету Міністрів від 28.08.2000 р. №1192)	вул. Перекопська,166, каб.104,
м. Херсон, Херсонська область, 73000	(0552) 35-44-65	drik@ukr.net

15.		Іванова Тетяна Павлівна, завідувач сектором персоніфікованого обліку пільгових категорій громадян	Запис на прийом Встановлення статусу батьків та дитини з багатодітної сім’ї	вул. Перекопська,166, каб.112,
м. Херсон, Херсонська область, 73000	(0552) 35-19-88	drik@ukr.net

Кулик Павло

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net
Тел: +380661622002
Блог:https://www.facebook.com/kylikpavel, 
https://www.facebook.com/profile.php?id=10001084

**Comment by Koffeek** [comment]
Будь ласка перенесіть завдання у репозиторій бізнес-аналітиків (https://github.com/e-government-ua/iBP/issues), та розбийте по окремих послугах.
