### ISSUE TITLE
Реализовать для тестового включения мока для авторизации по БанкИД

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1213]
- сделать отображение для тестового клиента кнопки включения/выключения режима мока авторизации (отображать эту кнопку только если это тестовый сервер)
- кнопка включает/выключает куку, которая передается на сервер
- на сервере если кука включена и сервер тестовый - реализует механизм мока для авторизации (т.е. симулирует получение от БанкИД готового объекта с персональными данными)

**Comment by ijmac** [comment]
Реализовал, на альфе проверил, работает

**Comment by nazarenkod** [comment]
функционал рабочий.
Есть 2 проблемы: 
1. Время загрузки больше 1 минуты.
2. Не предаются ФИО в поля

**Comment by ijmac** [comment]
Исправил ошибки, проверил на альфе, время загрузки нормальзовалось, ФИО поля заполнены

**Comment by nazarenkod** [comment]
Спасибо. Закрываю
