### ISSUE TITLE
Реализовать на базе сервиса /access/login (/access/login-v2) создать новый, модифицированный

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1214]
- [x] 1) Назвать сервис: /access/loginSubject (и разместить в том-же контроллере)

- [x] 2) сделать метод POST
- [x] 3) Содержимое параметра sPassword перенести в тело запроса
- [x] 4) при успешной авторизации вызывать сервис(на центральном):
/wf/service/subject/getSubjectsBy
с параметрами:
saLoginExternal=[%22Barmaley%22] ,где вместо "Barmaley" должен быть  заданный логин
- [x] 5) в ответ возвращать объект, полученный с сервиса п.4
- [x] 6) заполнить аннотации комментами, по параметрам и сервису, для авто-генерации доки по АПИ

**Comment by ArtemTokarenko** [comment]
Принимаю в роботу

**Comment by bvv4ik** [comment]
Привет, как успехи с таской?

**Comment by ArtemTokarenko** [comment]
я занимался 1220 на той неделе, сейчас занимаюсь этой

**Comment by PaulLuchyn** [comment]
Принимаю в работу

**Comment by PaulLuchyn** [comment]
Комментарий для тестировщика: при вводе корректных данных должно создавать сессию для пользователя и возвращать соответствующую этому пользователю структуру объектов. При вводе некорректных данных должна возвращаться ошибка с кодом LI_0001 и сообщением Login or password invalid.

**Comment by nazarenkod** [comment]
подскажите, пожалуйста, по сценарию...
я отсылаю POST https://test.region.igov.org.ua/wf/access/loginSubject?sLogin=kermit
в теле запроса указываю sPassword... но у меня в обоих случаях возвращает статус 200.
Подскажите, где я ошибаюсь

**Comment by PaulLuchyn** [comment]
@nazarenkod , добрый день! Какие оба случая? Вы меняете какие-то параметры в них? Опишите, пожалуйста, детальнее ваши оба случая и что в них не так.

**Comment by nazarenkod** [comment]
@PaulLuchyn , добрый день!
1. В body я передаю валидный пароль kermit.
2. В body я передаю не валидный пароль kermit32.
В обоих случаях я получаю 200 и html код

**Comment by PaulLuchyn** [comment]
@nazarenkod , вот мои скрины
![image](https://cloud.githubusercontent.com/assets/17761368/15244458/f69cc948-1909-11e6-890b-b7cd935e1161.png)
![image](https://cloud.githubusercontent.com/assets/17761368/15244475/0718a026-190a-11e6-9011-1411bb07814b.png)

**Comment by nazarenkod** [comment]
@PaulLuchyn , вот мой
![2016-05-13_15-17-58](https://cloud.githubusercontent.com/assets/13256486/15247638/30723806-191e-11e6-8959-be17ab599c5c.jpg)

**Comment by nazarenkod** [comment]
@PaulLuchyn , вот мой
![2016-05-13_15-17-58](https://cloud.githubusercontent.com/assets/13256486/15247676/63fb75de-191e-11e6-9261-59ede928446f.jpg)

**Comment by PaulLuchyn** [comment]
@nazarenkod , это нормально, чтоб получить доступ к данному сервису необходимо в хедеры добавить следующее:
ключ: Authorization
значение: Basic YWN0aXZpdGktbWFzdGVyOlVqaHRKbkV2ZiE= 
Также сообщаю что созданный сервис сделан по аналогии с /access/login.

**Comment by nazarenkod** [comment]
спасибо за объяснение, все работает
