### ISSUE TITLE
Доработать сущности SubjectMessage и HistoryEvent полем sSubjectInfo+nID_Subject и обеспечить их сохраняемость из разных источников

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1215]
- [x] 1) в сущность SubjectMessage добавить поле sSubjectInfo - строка-информация о субъекте
- [x] 2) в сущность HistoryEvent добавить поле sSubjectInfo - строка-информация о субъекте
- [x] 3) в сущности HistoryEvent и SubjectMessage, при не пустом поле nID_Subject - формировать связанный подобьект-элемент oSubject, в который подтягивать поля этой сущности Subject (иначе null)
- [x] 4) Доработать сервис замечания /setTaskQuestions
- [x] 4.1) опциональным параметром sSubjectInfo, при задавании которого сохранять в новую запись SubjectMessage в т.ч. значение этого параметра в соотв. поле
- [x] 4.2) опциональным параметром nID_Subject, при задавании которого сохранять в новую запись SubjectMessage в т.ч. значение этого параметра в соотв. поле
- [x] 5) Доработать сохранение в интерцепторе (org.igov.service.controller.interceptor.RequestProcessingInterceptor) записи HistoryEvent, при изменения состояния БП (метод: saveUpdatedTaskInfo), сохраняя туда
- [x] 5.1) опционально значение параметра sSubjectInfo в соотв. поле.(если задан)
- [x] 5.2) опционально значение параметра nID_Subject в соотв. поле.(если задан)
- [x] 6) заполнить аннотации комментами, по параметрам и сервису, для авто-генерации доки по АПИ

**Comment by VadymBuz** [comment]
Принимаю в работу

**Comment by bvv4ik** [comment]
Привет,
как успехи с таской?

**Comment by LyashenkoGS** [comment]
> 
 1) в сущность SubjectMessage добавить поле sSubjectInfo - строка-информация о субъекте
> 
Что конкретно должна содержать строка, какую информацию ?

**Comment by maxline** [comment]
Сорри, мои два последних коммита на самом деле относились к таске #1218 .
Опечатался в комментариях при коммите.

**Comment by VadymBuz** [comment]
Схема теста:

1)создаем любую заявку в [https://test.igov.org.ua/](https://test.igov.org.ua/) например, _test_datepicker
запоминаем ее номер (0-192032979)

2)заходим в дашборд чиновника https://test.region.igov.org.ua/tasks (под тестер/тестер)
и отправляем запрос на внесение замечаний
https://test.region.igov.org.ua/api/tasks/setTaskQuestions с телом запроса:
`{"nID_Process" :"19203297",
"sBody" :"",
"sMail":"vadymbuziak@gmail.com",
"saField":[{"sID":"check_3",
"sName":"внутри никакой врайтбл не ставлю, зато через запятую ставлю дескрипшн",
"sType":"string","sValue":"поле3","sValueNew":"поле3","sNotify":"pole3"}],
"soParams":{"sClientFIO" : "ДМИТРО ОЛЕКСАНДРОВИЧ"},
"sSubjectInfo":"informizia"}`

P.S. для отправления запроса я использовал Postman

3)если ответ 200 ОК, то делаем запрос на https://test.igov.org.ua/wf/service/subject/message/getServiceMessages?sID_Order=0-192032979
где среди всех месседжей ищем нужный(он будет одним из последних)
`{
    "nID_HistoryEvent_Service": 62249,
    "sSubjectInfo": "informizia",
    "oSubject": {
      "sID": "3119325858",
      "nID": 20045
    },
    "nID": 62436,
    "sHead": "Зауваження по заяві 0-192032979",
    "sBody": "Необхідно уточнити дані, за коментарем: <br/><br/>",
    "sDate": "2016-04-25 17:22:44.168",
    "nID_Subject": 20045,
    "sMail": "",
    "sContacts": "",
    "sData": "",
    "oSubjectMessageType": {
      "sDescription": "Работника замечание-комментарий по услуге",
      "nID": 5,
      "sName": "ServiceCommentEmployee"
    }
  }`
поле sSubjectInfo сохранилось

4) теперь точно так же проверяем сохранилась ли запись в Журнале (HistoryEvent)
http://test.igov.org.ua/wf/service/action/event/getHistoryEvents?nID_Subject=20045
среди остальных, ищем нужный(так же будет последним, или один из последних)
`{
    "sMessage": "По заявці №0-192032979 задане прохання уточнення:\nНеобхідно уточнити дані, за коментарем: \n",
    "sDate": "2016-04-25 17:22:44.160",
    "oHistoryEvent_Service": {
      "sID": null,
      "nID_Task": 19203297,
      "nID_Subject": 20045,
      "sUserTaskName": "рассмотрение и загрузка",
      "sDate": "2016-04-25 17:22:44.170",
      "nID_Service": 751,
      "nID_Region": 1,
      "sID_UA": "1200000000",
      "nRate": null,
      "soData": "[]",
      "sToken": "eLFwVaki1OmW07BGl5oY",
      "sHead": "_test_datepicker",
      "sBody": "Необхідно уточнити дані, за коментарем: ",
      "nTimeMinutes": null,
      "sID_Order": "0-192032979",
      "nID_Server": 0,
      "nID_Proccess_Feedback": null,
      "nID_Proccess_Escalation": null,
      "sID_Rate_Indirectly": null,
      "nID_StatusType": 3,
      "nID_ServiceData": null,
      "sID_StatusType": "Opened_RemarkEmployeeQuestion",
      "sName_UA_StatusType": "Заявка вiдкрита i отримала зауваження вiд робiтника",
      "nID_Protected": null,
      "nID": 62249
    },
    "oDocument": null,
    "sSubjectInfo": "informizia",
    "oSubject": {
      "sID": "3119325858",
      "sLabel": null,
      "sLabelShort": null,
      "aSubjectAccountContact": null,
      "nID": 20045
    },
    "nID": 62435,
    "nID_Subject": 20045,
    "nID_HistoryEventType": 9,
    "sEventName": "Запрос на уточнение данных"
  }`
и опять проверяем присутствует ли поле sSubjectInfo

**Comment by nazarenkod** [comment]
протестировано
