### ISSUE TITLE
Доработать сущность SubjectHuman для поддержки признака пола

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1218]
- Добавить опциональное поле nID_Sex - номер-ИД пола
- значение резолвить через энум SubjectHumanSex:

> 0 - Female
> 1 - Male
>

**Comment by maxline** [comment]
Володя, 
в класс SubjectHuman.java добавлено следующее

    public enum SubjectHumanSex {
        FEMALE(0, "Female"),
        MALE(1, "Male");
        private String sID_Sex;
        private int nID_Sex;
        
        private SubjectHumanSex(int nID_Sex, String sID_Sex) {
            this.nID_Sex = nID_Sex;
            this.sID_Sex = sID_Sex;
        }
        public static SubjectHumanSex getBynID_Sex(int nID_Sex){
            if (nID_Sex > 1 || nID_Sex < 0) {
                throw new IllegalArgumentException(
                        String.format("nID_Sex [%d] is out of possible range!", nID_Sex));
            }
            SubjectHumanSex result = null;
            
            if (nID_Sex == 0) {
                result = FEMALE;
            } else if (nID_Sex == 1) {
                result = MALE;
            }
            return result;
        }
    }
    
    private int nID_Sex;
    
    public int getnID_Sex() {
        return nID_Sex;
    }

    public void setnID_Sex(int nID_Sex) {
        this.nID_Sex = nID_Sex;
    }

    public SubjectHumanSex geteSubjectHumanSex(int nID_Sex){
        return SubjectHumanSex.getBynID_Sex(nID_Sex);
    }

1. Похоже на то что нужно? Просьба дать замечания, если что-то не так.
2. Так же просьба чуть подробнее описать, что имелось ввиду под резолвить через энум, если эту часть нужно доработать.
Спасибо!

**Comment by bvv4ik** [comment]
nID_Sex - лишнее
т.к. там есть встроенное order

**Comment by ASkosyr** [comment]
Остался один момент.

в csv файле я гружу значения для nID_Sex как 0 или 1
но в результате запроса вот здесь возвращается стринговое представение FEMALE, MALE
https://test.igov.org.ua/wf/service/subject/getSubjectHuman?nID_Subject=1
```
"nID_Sex":"FEMALE"
```
нужно переопределять toString реализацию?
или маппинг 0 и 1 только для загрузки нужно и в данном случае такое представление нормально?

**Comment by ASkosyr** [comment]
После обсуждения с @bvv4ik  добавил логику сериализации enum чтобы присутствовало и числовое и строковое значение

```
"oID_Sex":{"nID_Sex":"0","sID_Sex":"female"}
```

**Comment by ASkosyr** [comment]
https://test.igov.org.ua/wf/service/subject/getSubjectHuman?nID_Subject=1
