### ISSUE TITLE
Заказ услуги на тесте: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by smoktii-igov** [e-government-ua/i#1219]
Сборок новых нет, вроде все стабильно, но ошибка на АЛЬФЕ при заказе заявки (после выбора уровня области - ошибка при выборе района). 
Для примера услуга https://test.igov.org.ua/service/15/general

Помилка
Cannot read property 'length' of null (caused by "undefined")
Час: "2016-03-24T22:42:39.868Z"
Потыкаешь мышкой и открывается список

![error01](https://cloud.githubusercontent.com/assets/17428200/14033533/b96d4cda-f223-11e5-8e0b-539c609b0fa4.png)

**Comment by bvv4ik** [comment]
уже-ж больше не появляется?

**Comment by smoktii-igov** [comment]
Ошибка ушла, все ОК.

**Comment by smoktii-igov** [comment]
Опять на Альфе появилась эта же ошибка
