### ISSUE TITLE
Реализовать кеширование данных при авторизации в Redis

### ISSUE THREAD

**Issue by admiral-diver** [e-government-ua/i#122]
https://github.com/e-government-ua/i/blob/test/auth/bankid-oauth-weblib/src/main/java/ua/org/bankid/oauth/impl/BankIdStorageServiceRedisImpl.java

Developer Skype: zora.boris 

Необходимо кешировать:
* Информацию об авторизации (Токен доступа, Токен обновления)
* Информация о пользователе (ФИО, Телефон, ИНН, ...)

**Comment by bvv4ik** [comment]
@MaximPedich прошу написать в комменте, как можно протестировать доработку тестерам?

**Comment by MaximPedich** [comment]
Нужно в конфигурации spring-security-oauth2 указать, что имплементацией интерфейса TokenStore будет RedisTokenStore.

Насколько я понимаю, сейчас эта конфигурация находится в файле oauth2-servlet.xml

**Comment by bvv4ik** [comment]
тестеры неумеют программировать, тут нужен какой-то более простой и очевидный способ

**Comment by VadimGulich** [comment]
Судя по коду то реализовано , задачу закрываю так как более 1.5 м. нет активности по ней
