### ISSUE TITLE
Оптимизировать структуру ответа сервиса getSubjectsByAccount

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1220]
ВАЖНО: стоит не ламать этот сервис существующий getSubjectsByAccount а скопировать его в новый:
getSubjectsBy
и уже там комбинировать... а потом на него перейдем
просто чтоб не поламать существующие механизмы

https://test.igov.org.ua/wf/service/subject/getSubjectsByAccount?saLoginExternal=[%22Barmaley%22]&nID_SubjectAccountType=1

сейчас отдает:

```
{
"organs": {},
"externalUsers": {
"Barmaley": {
"sID": "",
"sLabel": "Artur Kvasnii",
"sLabelShort": "",
"aSubjectAccountContact": [
{
"subject": {
"sID": "",
"sLabel": "Artur Kvasnii",
"sLabelShort": "",
"aSubjectAccountContact": null,
"nID": 24
},
"subjectContactType": {
"sName_EN": "Phone",
"sName_UA": "Телефон",
"sName_RU": "Телефон",
"nID": 0
},
"sValue": "",
"sDate": "2016-02-15 00:51:57.743",
"nID": 1
},
{
"subject": {
"sID": "",
"sLabel": "Artur Kvasnii",
"sLabelShort": "",
"aSubjectAccountContact": null,
"nID": 24
},
"subjectContactType": {
"sName_EN": "Email",
"sName_UA": "Електрона адреса",
"sName_RU": "Электнонный адрес",
"nID": 1
},
"sValue": "kvasniy@mail.ru",
"sDate": null,
"nID": 2
}
],
"nID": 24
}
},
"users": {}
}
```

а нужно чтоб:
- [x] 1) каждый раз не дублировалось:
```
{
"subject": {
"sID": "",
"sLabel": "Artur Kvasnii",
"sLabelShort": "",
"aSubjectAccountContact": null,
"nID": 24
},
```

в элементах:
SubjectAccountContact

- [x] 2) в то-же время чтоб тут:
"Barmaley": {
"sID": "",
"sLabel": "Artur Kvasnii",
"sLabelShort": "",

был встроен под-обьект SubhectHuman и/или SubjectOrgan со всеми полями (однократно)

- [x] 3) вместо конструкции:
"externalUsers": {
"Barmaley": {

должно быть независящая от того какие параметры задаются...

например:
```
aSubjectAccount: [
{sLogin:"Barmaley"
, nID_Server:1
;;; b n/l/

```

**Comment by ArtemTokarenko** [comment]
Взято в роботу

**Comment by LyashenkoGS** [comment]
Вот так ?
{
  "organs": {},
  "aSubjectAccount:": [{
    "Barmaley": {
      "oSubjectHuman": {
        "sID": "",
        "sLabel": "Artur Kvasnii",
        "sLabelShort": ""
      },
      "aSubjectAccountContact": [
        {
          "subjectContactType": {
            "sName_EN": "Phone",
            "sName_UA": "Телефон",
            "sName_RU": "Телефон",
            "nID": 0
          },
          "sValue": "",
          "sDate": "2016-02-15 00:51:57.743",
          "nID": 1
        },
        {
          "subjectContactType": {
            "sName_EN": "Email",
            "sName_UA": "Електрона адреса",
            "sName_RU": "Электнонный адрес",
            "nID": 1
          },
          "sValue": "kvasniy@mail.ru",
          "sDate": null,
          "nID": 2
        }
      ],
      "nID": 24
    }
  }]
}

**Comment by LyashenkoGS** [comment]
to ArtemTokarenko : как можно с Вами связаться?

**Comment by ArtemTokarenko** [comment]
только прочитал мыло skymennn@gmail.com

**Comment by bvv4ik** [comment]
UPD:
стоит не ламать этот сервис существующий а скопировать его в новый:
getSubjectsBy
и уже там комбинировать... а потом на него перейдем
просто чтоб не поламать существующие механизмы

**Comment by bvv4ik** [comment]
@LyashenkoGS
"Вот так ?
{"

почти...


нужно учесть еще п.3

```
aSubjectAccount: [
{sLogin:"Barmaley"
, nID_Server:1
;;; b n/l/

```

**Comment by bvv4ik** [comment]
привет,
а есть какой-то прогноз по срокам реализации?

**Comment by LyashenkoGS** [comment]
ветка issue1020. Если такой вариант пойдет, то завтра в течении дня сделаем.

**Comment by LyashenkoGS** [comment]
Готово.  ccfec0a0a185b531489801a53c371754f4827a18
Старый вариант не ломал 
Новый тестил по ссылке http://localhost:8080/wf-central/service/subject/getSubjectsBy?saLoginExternal=[%22Barmaley%22]&nID_SubjectAccountType=1

**Comment by sergeygorban** [comment]
Нужен контакт разработчика, дайте пожалуйста

**Comment by LyashenkoGS** [comment]
Одним из последних работал я,  skype lyashenko.grigory

**Comment by sergeygorban** [comment]
Вывод после тестирования: сервис работает согласно требованиям указанным в задачи
