### ISSUE TITLE
Перенести все дефолтные проперти/конфиги в process.json

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1221]
- [x] 1) в process.json перенести значения
из /central-js/server/config/local.env.sample.js и если чего там не будет, то из /central-js/server/config/environment/local/index.js
- [x] 2) /central-js/server/config/environment/local/*.pem - перенести в /central-js/
(и поправить соотв значения путей в пропертях)
- [x] 3) переместить /central-js/server/config/environment/index.js в /central-js/server/config/index.js и убрать дефолтные значения справа от "||"
- [ ] 4) Убрать из использования в коде и удалить файлы и папки:
- /central-js/server/config/local.env.sample.js
- /central-js/server/config/environment/test.js
- /central-js/server/config/environment/test-alpha.js
- /central-js/server/config/environment/test-beta.js
- /central-js/server/config/environment/prod.js
- /central-js/server/config/environment/local/index.js
- /central-js/server/config/environment/local
- /central-js/server/config/environment
- [x] 5) добавить булевый параметр bCompile=true //
а в \central-js\server\config\express.js заменить конструкции:
  if ('prod' === env || 'test-alpha' === env || 'test-beta' === env) {
на проверку bCompile=true
и
  if ('local' === env || 'test' === env) {
на  проверку bCompile=false
- [x] 6) обязательно на вики поправить инструкции установки 
[центрального](https://github.com/e-government-ua/i/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D1%86%D0%B5%D0%BD%D1%82%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BE%D1%80%D1%82%D0%B0%D0%BB%D0%B0-%D0%B3%D1%80%D0%B0%D0%B6%D0%B4%D0%B0%D0%BD-(central-js,-frontend)
) и [регионального](https://github.com/e-government-ua/i/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D1%80%D0%B5%D0%B3%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B4%D0%B0%D1%88%D0%B1%D0%BE%D1%80%D0%B4%D0%B0-%D1%87%D0%B8%D0%BD%D0%BE%D0%B2%D0%BD%D0%B8%D0%BA%D0%B0-(dashboard-js,-frontend)) фронтов.

**Comment by ijmac** [comment]
параметр bCompile положил в central-js/server/config/index.js
