### ISSUE TITLE
Решить проблему с необновляемостью списка энума на базе атрибута, при выборе другого SubjectOrganJoin 

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1222]
Подробное описание проблемы:
https://docs.google.com/document/d/16ffPtfrV7sIxuO9qch8m5N3o4pGOgBcHluPZOuZA3ik/edit

**Comment by ijmac** [comment]
Пофиксил, 
на альфе работает

**Comment by Koffeek** [comment]
Проверил. Работает. Спасибо.
