### ISSUE TITLE
Реализовать кеширование ключевых вызовов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1224]
- [x] 1) получение статистики по услуге (на 3 часа)
- [x] 2) getService (на 3 часа)

Использовать реализованный новый механизм кеширования
(https://github.com/e-government-ua/i/compare/optimizedCustomObjects?expand=1)

**Comment by ijmac** [comment]
Сделал келирование статистики и услуг. 
На альфе тестировал - работает.

**Comment by bvv4ik** [comment]
готово
