### ISSUE TITLE
Починить вывод поля при экспорте заявок

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1228]
запрос БЕЗ поля selection:

https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=subsidiesUkraine&sID_State_BP=usertask1&sDateAt=2016-03-21&sDateTo=2016-03-23&saFields=${area};${sID_Order};${sDateCreate};${bankIdlastName};${sDateClose};${selection};&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=escalation.csv

УПСЗН Апостолівського району;0-135751926;21.03.2016 12:05:36;БІЛЯВЦЕВ;28.03.2016 11:44:37;
УПСЗН Амур-Нижньодніпровського району, м. Дніпропетровськ;0-135800845;21.03.2016 12:21:15;БІЛЯВЦЕВ;28.03.2016 11:44:37;
УПСЗН Апостолівського району;0-138126332;22.03.2016 14:24:00;БІЛЯВЦЕВ;28.03.2016 11:44:42;

запрос С полем selection (уже тоже не работает):

https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=subsidiesUkraine&sID_State_BP=usertask1&sDateAt=2016-03-21&sDateTo=2016-03-23&saFields=${area};${sID_Order};${sDateCreate};${bankIdlastName};${sDateClose};${selection};&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=escalation.csv&sTaskEndDateAt=2016-03-28&sTaskEndDateTo=2016-03-29

УПСЗН Апостолівського району;0-135751926;21.03.2016 12:05:36;БІЛЯВЦЕВ;28.03.2016 11:44:37;
УПСЗН Амур-Нижньодніпровського району, м. Дніпропетровськ;0-135800845;21.03.2016 12:21:15;БІЛЯВЦЕВ;28.03.2016 11:44:37;
УПСЗН Апостолівського району;0-138126332;22.03.2016 14:24:00;БІЛЯВЦЕВ;28.03.2016 11:44:42;

dn200986zda - логин/пароль для проверки
при заходе в дашбоард  (альфы)
там можно найти эту заявку

**Comment by ASkosyr** [comment]
> запрос С полем selection (уже тоже не работает):

он работает только для некоторых задач

вот по такой выборке 2 задачи есть с атрибутом

https://test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=subsidiesUkraine&sID_State_BP=usertask1&saFields=%24%7Barea%7D;%24%7BsID_Order%7D;%24%7BsDateCreate%7D;%24%7BbankIdlastName%7D;%24%7BsDateClose%7D;%24%7Bselection%7D;&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=escalation.csv&sTaskEndDateAt=2016-03-28&sTaskEndDateTo=2016-03-29

**Comment by bvv4ik** [comment]
@ASkosyr
когда с димой общались, то выяснилось что на стартовой таске этого поля нет вот потому там и проскакивают эти таски

так что все норм

таску закрываем)))
