### ISSUE TITLE
Создание зарезервированной  переменной sDateCreateАpplication

### ISSUE THREAD

**Issue by smoktii-igov** [e-government-ua/i#1229]
Использование атрибута sDateCreate в принтформах БП неиформативно, так как там хранится дата-время "взятия в работу" чиновником юзертаски, т.е. он меняется со временем. Не хватает атрибута, который будет хранить дату-время подачи заявки гражданином, т.е. создания старттаски. Хотелось бы уйти от атрибута "Даты подачи заявления", который вводит сам гражданин. Этот атрибут необходим при печати на заявлении. 
И назвать атрибут, например, sDateCreateАpplication.

**Comment by smoktii-igov** [comment]
@ValeryStavitsky @kurbpa @Koffeek @GrekD @msvidran

**Comment by YmNIK13** [comment]
Еще бывают ситуации, когда надо на каждой юзер таске фиксировать дату.
Предлагается реализация либо через маркер, который сможет присваивать переменной значение системного дата/время сервера, либо через атрибут дефолт.
Такой функционал нужен, и на портале, и на дашбоде.

**Comment by bvv4ik** [comment]
ребята, все уже давно реализовано... названо просто по другому
спросите у старших коллег

**Comment by smoktii-igov** [comment]
Реализовано 
sDateTimeCreateProcess
sDateCreateProcess
sTimeCreateProcess
