### ISSUE TITLE
Реализовать интерфейс в закладке "О портале", для выгрузки отчетов о оказанных услугах (только для админа)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1230]
Использовать [сервис](https://jenkins-new.igov.org.ua/job/central_alpha/ws/wf-central/target/generated-docs/central-igov.html#_Получение_отчета_о_поданных_заявках):
/action/event/getServiceHistoryReport

- Отображать этот блок только для админа
- Позволять как отображать в виде таблицы так и сохранять как файл
- Фильтры должны быть все те-же что и в сервисе
- давать возможность сортировать по колонкам кликая на колонки (по убыванию и по возрастанию при повторных кликах)

**Comment by antonlegkiy** [comment]
интерфейс доступен в разделе "Про портал" (https://test.igov.org.ua/about) и отображается только для админа. Сортировка заявок в статистике возможна при нажатии на название колонки что находится в шапке таблицы. Чтобы получить отчет нужно выбрать период времени за который его нужно составить и нажать "Завантажити". Если какие либо заявки нужно скрыть с статистики, выбираем "Фільтр" и вводим через запятую номера nID_Service, после подгружаем список уже без этих заявок. 
Статистику можно скачать нажав на "Зберегти".

**Comment by GrekD** [comment]
выбрала период 16.05.2016-20.05.2016, в фильтре исключила услугу 1397, время не вібирала - только дату
нажала "завантажити" ждала 4 минуты - ничего не появилось
при нажатии "зберегти" тоже файл не загурзился

потом выбрала даты 16-17 с указанием времени
в фильтре исключила услугу 1397
все ок - данные получила, загрузить тоже удалось, только выгружается сsv в непонятной кодировке - но это уже не так существено

1. предлагаю укнопку "завантажити" переименовать на "отримати данні"
2. Предлагаю время поставить 00:00 по умолчанию -чтоб не надо было выбирать
3. поле sID_Order сделать чуть шире, чтоб номер заявки помещался в одну строку

**Comment by antonlegkiy** [comment]
1. кнопку переименовал
2. время по умолчанию установлено на 00:00, но поскольку в данном случае оно связно с датой, ее так же выставил по умолчанию на 01.01
3. номер заявки помещается\

если будут пожелания по внешнему виду статистики также буду рад услышать

**Comment by GrekD** [comment]
Если можно, то еще чуть шире сделать поле sPhone	(за счет поля nID_ServiceData - в нем будет пока что не более 5 цифр) - во всем  остальном все ок, замечаний нет.
спасибо!

**Comment by antonlegkiy** [comment]
сделано
а насчет кодировки, то нужно в екселе выставить будет utf-8 и все будет ок
