### ISSUE TITLE
Перенести все дефолтные проперти/конфиги в process.json (только для дашборда)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1231]
По образу и подобию: https://github.com/e-government-ua/i/issues/1221

**Comment by GFalcon-UA** [comment]
Перестал локально запускаться Dashbord, хотя переменные SERVER_KEY и SERVER_CERT прописаны правильно. 
![screenshot](https://cloud.githubusercontent.com/assets/13604023/14967421/fedf5bea-10bf-11e6-86f2-10e578bdfabe.png)

Специально что ли переносить ключи в папку D:/sybase/cert ???

**Comment by ijmac** [comment]
Поправил process.json, сделал дефолтный, можно запускать без кастомного по http

**Comment by nazarenkod** [comment]
Подскажите как проверить

**Comment by GFalcon-UA** [comment]
В дашборде должно быть `"bTest": "TRUE"`, иначе инструментальная панель не отображается

**Comment by nazarenkod** [comment]
запрос https://test.region.igov.org.ua/api/env/get-env-config
возвращает {"bTest":true}
