### ISSUE TITLE
Реализовать закладку работы с группами (раздел инструменты)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1232]
- добавлять пользователя
- удалять пользователя
- добавлять группу
- удалять группу
- добавлять пользователя в группу
- удалять пользователя из группы
- Использовать сервисы по ишью:
https://github.com/e-government-ua/i/issues/1134

**Comment by Sokhatsky** [comment]
Позволяет добавлять пользователя при не корректном заполнении поля Email:
![2016-06-27_0037](https://cloud.githubusercontent.com/assets/16464887/16365135/d9087698-3bff-11e6-8ebd-5c3b1cec9d81.png)

**Comment by Sokhatsky** [comment]
При добавлении пользователя и не заполнении всех полей кнопка "Зберегти" активна. И при нажатии кнопки "Зберегти" пользователя якобы добавляют т.е. не появляется предупреждающего сообщения о необходимости заполнить все поля

**Comment by Sokhatsky** [comment]
При добавлении пользователя и заполнении поля Логин не выдается сообщения о превышении максимальной длины поля. А если она превышена пользователь с данным логином не добавится и предупреждающего сообщения не появится

**Comment by bvv4ik** [comment]
работает
