### ISSUE TITLE
Доработать сохранение истории по закрытым заявкам

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1234]
В классе интерцепторе: org.igov.service.controller.interceptor.RequestProcessingInterceptor.java доработать метод saveClosedTaskInfo(sRequestBody); Сейчас история не сохраняется по закрытым заявкам в которых в теле запроса нет параметра taskId (так как String snID_Task = (String) omRequestBody.get("taskId");  отдает нал). Но в таких случаях есть ид таски в урле запроса (это запросы вида runtime/tasks/{taskId}). Тоесть передавать в метод вместо sRequestBody  ид таски, где ид таски брать или из sRequestBody, или, если там нет и это урл вида runtime/tasks/{taskId}, то из урла. В самом же методе делать проверку на то, что ид таски пришло не наловое.

**Comment by PaulLuchyn** [comment]
Принимаю в работу

**Comment by nazarenkod** [comment]
как можно проверить на фронте?

**Comment by kurbpa** [comment]
@bvv4ik  
Володя подскажи пожалуйста
