### ISSUE TITLE
[S5] Орфографические ошибки на странице услуги. 

### ISSUE THREAD

**Issue by inmydelorean** [e-government-ua/i#1236]
**Сторінка:** https://igov.org.ua/service/1467/instruction

**№1. Слово "Перереєстарція" у назві послуги "Перереєстарція транспортного засобу при заміні номерного знаку".**
![screenshot_1](https://cloud.githubusercontent.com/assets/8604869/14250393/f1d659a2-fa86-11e5-90b3-ba8e2cbf1b75.png)

**№2. Вкладка "Як працює". Крок 3. Слово "отримаєете" у реченні "в разі неможливості надання послуги Ви отримаєете лист з зазначенням підстави для відмови".**
![screenshot_2](https://cloud.githubusercontent.com/assets/8604869/14250394/f1f2c84e-fa86-11e5-859d-75b6ea568ef6.jpg)

**Comment by kurbpa** [comment]
Исправил. Спасибо!
