### ISSUE TITLE
Вынести все параметры из кода в проперти AS.properties

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1237]
Обязательно вначале подготовить список названий переменных, с их текущими значениями(для ревью), и только после утверждения этого списка - переносить все туда

**Comment by ostap7** [comment]
Беру в работу. Дедлайн:11-04-2016

**Comment by ArtemTokarenko** [comment]
@ostap7 ,как можно с Вами связаться?

**Comment by ostap7** [comment]
slack - ostap

**Comment by ArtemTokarenko** [comment]
@ostap7 , может скайп? вот мой skymennn1

**Comment by bvv4ik** [comment]
готово
