### ISSUE TITLE
Починить отображаемость предупреждения о незаполненности обязательного поля на форме с типом select

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1238]
При указании sID_Public_SubjectOrganJoin type="select" и required="true", в случае когда пользователь не сделал выбор, то поле не подсвечивается красным прямоугольником, как обычное обязательное поле! В интерфейсе звездочка стоит, но выбор не сделан, а нажимаю "Замовити послугу".
 Реакции нет, мышей крутишь сразу в глаза не бросается, что поле не заполнено.
 Пример https://test-version.igov.org.ua/service/1393/general

**Comment by OlgaTurenko** [comment]
![image](https://cloud.githubusercontent.com/assets/10909557/14637186/5e1d912c-0638-11e6-9e10-6fb2e166512c.png)

**Comment by OlgaTurenko** [comment]
вроде бы все подсвечивает на бете.

**Comment by oliverfrost** [comment]
Указанный баг воспроизвести не удалось. Считаю, что проблема была устранена.
