### ISSUE TITLE
При включеннии референтности автоматически проставлять в зарезервированные поля данные по реально авторизированному субьекту

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1239]
Как только включается чекбокс референтности, действовать по следующей схеме:
- если есть поле с id=sFIO_Referent -сетить в него Фамилию, Имя и Отчество того, кто реально авторизовался (то что в желтом блоке вверху)

- если есть поле с id=sINN_Referent -сетить в него ИНН того, кто реально авторизовался (то что в желтом блоке вверху)

Если чекбокс выключается то оба эти поля - НЕ ОТЧИЩАТЬ

**Comment by ostap7** [comment]
Принимаю в работу.
Дедлайн: 11.09.2016
