### ISSUE TITLE
Проверять в листенере заполненность поля Электронной Очереди и если оно не заполнено то не проходить процедуру сохранения ИД тикета

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1240]
Класс:
org.igov.service.business.action.task.core.AbstractModelTask
Метод:
public void scanExecutionOnQueueTickets(DelegateExecution oExecution,

там нужно добавить проверку sValue

**Comment by sergeygorban** [comment]
Вывод после тестирования: 
Если поле заявки с электронной очередью не заполнено, то выполнить отправку заявки не удается

**Comment by bvv4ik** [comment]
nfr tckb dsdjl ghjnbdjhtxtn pflfxt - pfxtv pflfxe pfrhsdfnm&

**Comment by Akylish88** [comment]
Добрый день Владимир. 
Еще раз детально протестил услугу. Ошибка с очередями.
Электронная очередь только на Новопсковский район. На другие города очереди нет.
На другие города не пропускает, работает только на Новопсков.
https://test.igov.org.ua/service/1392/general
Переменные visitDay, nID_Department_visitDay заложены в маркер.
"ShowFieldsOnCondition_3": {
      "aField_ID": [
        "visitDay",
        "nID_Department_visitDay"
      ],
      "asID_Field": {
        "sClient": "sID_Public_SubjectOrganJoin"
      },
      "sCondition": "[sClient] == 'lug_newpsc'"
    }
Можно обратить внимание что на бетте эта же услуга с Новопсковским районом но без очереди работает на все города коректно.

На альфе в автодеплое процесс:  cnap_417

**Comment by Akylish88** [comment]
![21](https://cloud.githubusercontent.com/assets/17428736/14734987/de7a077a-0876-11e6-8159-18c0ed69ab12.png)
![22](https://cloud.githubusercontent.com/assets/17428736/14734986/de79c706-0876-11e6-9289-21fdeb57a208.png)
![23](https://cloud.githubusercontent.com/assets/17428736/14734988/de7a1f8a-0876-11e6-918d-6f83f1cdb94b.png)
