### ISSUE TITLE
Реализовать профиль ДФС

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1246]
- [x] 1) Реализовать поддомены-зеркала:
https://test.dfs.igov.org.ua
https://dfs.igov.org.ua

- [x] 2) Реализовать вид профиля по образцу:
![igov-dfs3_small](https://cloud.githubusercontent.com/assets/4208821/14443095/d5131bb0-0045-11e6-9896-7f8940e2bf43.png)

- [x] 3) Использовать хеадер:
![igov-dfs](https://cloud.githubusercontent.com/assets/4208821/14443124/f7125226-0045-11e6-9c0d-ce12eade5e67.png)

- [x] 4) Использовать тайтл:
![igov-dfs_title](https://cloud.githubusercontent.com/assets/4208821/14443126/fa48ddd4-0045-11e6-9c2d-14810489911f.png)

- [x] 5) Скрыть поле поиска по услугам (с фильтрами)

- [x] 6) Вместо выборки по массиву населенных пунктов реализовать выборку по названию органа

- [x] 7) Меню "Контакты" сделать в виде сссылки

**Comment by antonlegkiy** [comment]
иногда возникает ситуация что колонки выстраиваются в 1 ряд, отменил изменения, ищу другой подход. https://github.com/e-government-ua/i/commit/fdd7d65bebe7ca2bbb6c7b5a3cd7154b5826aa6a
