### ISSUE TITLE
При переходе на вкладку "документы" -  "Невідома помилка: [object Object] "

### ISSUE THREAD

**Issue by Julia-tera** [e-government-ua/i#1248]
При переходе на вкладку "документы" с любой другой вкладки выдает две ошибки "Невідома помилка: [object Object] "

http://clip2net.com/s/3wVbDWV
и вторая того же текста с дополнительным с чекбоксом, в котороа предлагает "Не давать на этой странице создавать дополнительные диалоговые окна"
http://clip2net.com/s/3wVbHQT

**Comment by bvv4ik** [comment]
прошу самостоятельно не создавать в данном репозитории ишью!
т.к. он только для отфильтрованных, формализованных для разработчиков и утвержденных ТЗ
для всех предложений есть форум: iForum или iTest

либо есть у нас файл с бэклогом (гуглодок)
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit
