### ISSUE TITLE
Вернуть стандартный календарик для выбора полей с датой в умолчательное состояние на старте "выбор года"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1249]
Фактически восстановить все, как это было описано в ишью:
https://github.com/e-government-ua/i/issues/1150

В идеале привести календарик к такому виду:
![image](https://cloud.githubusercontent.com/assets/4208821/14554226/17d8c98a-02f4-11e6-9d38-298a4ee5d037.png)

**Comment by antonlegkiy** [comment]
1. 
![image](https://cloud.githubusercontent.com/assets/17439100/14574667/addf0982-0365-11e6-992f-8756a1e633d6.png)

2. 
![image](https://cloud.githubusercontent.com/assets/17439100/14574638/865f264e-0365-11e6-936f-b9ded1a95bee.png)
3. 
![image](https://cloud.githubusercontent.com/assets/17439100/14574649/927373f4-0365-11e6-8994-ee321392ba71.png)

**Comment by antonlegkiy** [comment]
1. 
![image](https://cloud.githubusercontent.com/assets/17439100/14588940/c6dff67e-04de-11e6-837c-02e74dff44dd.png)
2. 
![image](https://cloud.githubusercontent.com/assets/17439100/14588942/d53a39aa-04de-11e6-8a9a-0389195ebb6b.png)
3. 
![image](https://cloud.githubusercontent.com/assets/17439100/14588943/e18b3682-04de-11e6-8d5b-b7a6d8918555.png)

link : https://localhost:9000/service/654/general/place/built-in/region/5/city/0 (Послуга->Соціальна допомога->Отримання субсидії на оплату житлово-комунальних послуг  )

**Comment by antonlegkiy** [comment]
добавлена локализация месяцев с англ на укр язык.

**Comment by julyprodan** [comment]
добрый день! Предлагаю все-таки писать название месяца в именительном падеже, а не в родительном. тем более после выбора наименование трансформируется в порядковый номер месяца.
Отдельно хотелось бы попросить все-таки сделать календарь, начинающийся с понедельника, а не воскресения, и  подписать дни недели

**Comment by antonlegkiy** [comment]
добрый день! понял, будет сделано!

**Comment by antonlegkiy** [comment]
откорректировал, дни недели начинаются с пн, подписи на дни недели добавлены, месяца отображаются в сокращенном виде как на скрине в таске.

**Comment by sergeygorban** [comment]
Есть предложение при нажатии "Очистить" вместе с очисткой поля, возвращать календарь на выбор года

**Comment by julyprodan** [comment]
спасибо, единственное еще хотелось бы, когда выбрал месяц и видишь даты, чтобы было видно какой месяц выбрал, сейчас только слово даты
