### ISSUE TITLE
Добавить в отдаваемом через сервис /getTaskData поле aField обьекта - подэлемент-массив aEnumValue

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1250]
(то что в стандартном обьекте, отдаваемом сервисом активити, хранится в элементе enumValues)

**Comment by ASkosyr** [comment]
Пример вызова

https://test.region.igov.org.ua/wf/service/action/task/getTaskData?nID_Task&nID_Process=10260070

**Comment by nazarenkod** [comment]
поле aField передается
