### ISSUE TITLE
Починить ан-ассайн таски

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1251]
https://docs.google.com/document/d/13YwOABkZadB0EByuK5Uj8e3V1AYrEc5Tq1RN4FLhaP0/edit

**Comment by antonlegkiy** [comment]
https://test.region.igov.org.ua/tasks/all/17970845 если в таске нажать "Вiдкрiпити" - закрепленный чиновник смениться на "Вільний тікет" и тикет переместится в "Необробленi"

**Comment by nazarenkod** [comment]
Протестировано на альфе.
