### ISSUE TITLE
Разобраться с неработающей кнопкой "Змінити" (город)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1255]
Способ воспроизвести:
зашла в услугу. 
выбрала Тернополь
авторизовалась
заполнила-отправила.
решила заполнить еще заявку на Днепр.
перехожу на главную, захожу в услугу - 
вижу автозаполненый тернополь и открыта форма заявки (т.е. я уже авторизована)
нажимаю кнопку "Змінити" (город)
на секунду форма заявки пропадает, и появляется снова , а Город Тернополь остается.

ВАЖНО:
ситуация не стабильна.. то работает то не работает...

**Comment by zolotovatatyana** [comment]
https://www.youtube.com/watch?v=W5SggRW_mcI&feature=youtu.be

**Comment by nazarenkod** [comment]
Больше не появляется
