### ISSUE TITLE
"Реєстрація авто з пробігом в МРЕВ " Не корректно отрабатывает выпадающий список выбора области

### ISSUE THREAD

**Issue by Julia-tera** [e-government-ua/i#1256]
"Реєстрація авто з пробігом в МРЕВ "
Не корректно отрабатывает выпадающий список выбора области  при повторном использовании. В выпадающем списке отображается только одна запись выбранная ранее, изменить ее есть возможность только при ручном удалении текста названия выбранного варианта, после чего выпадающий список показывает полный перечень. В выпадающем списке нужно показывать все возможные варианты, для возможности выбора без ручного стирания текста.

**Comment by Julia-tera** [comment]
![70272e3e-e179-11e5-9c30-85c96d15e0e9](https://cloud.githubusercontent.com/assets/17043155/14719822/fabb25a6-0806-11e6-9676-b168d3903bd1.png)

**Comment by kurbpa** [comment]
неактуально. Услуга закрыта.
