### ISSUE TITLE
Мій журнал  - Не работает поиск. Выдает некорректное  сообщение об ошибке

### ISSUE THREAD

**Issue by Julia-tera** [e-government-ua/i#1257]
Мій журнал  - Не работает поиск. Выдает некорректное  сообщение об ошибке
![4](https://cloud.githubusercontent.com/assets/17043155/14719979/d8116d34-0807-11e6-95d0-383705f9b289.png)

**Comment by bvv4ik** [comment]
прошу самостоятельно не создавать в данном репозитории ишью!
т.к. он только для отфильтрованных, формализованных для разработчиков и утвержденных ТЗ
для всех предложений есть форум: iForum или iTest

либо есть у нас файл с бэклогом (гуглодок)
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit
