### ISSUE TITLE
Реализовать маркер валидации расширения загружаемого файла на форму услуги

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1258]
На базе реализованной таски:
https://github.com/e-government-ua/i/issues/770#issuecomment-208563866
(можно посмотреть там как проверять расширение файла)

и по примеру маркера-валидатора: "CustomFormat_1"
(можно найти поиском в проекте [тут](https://github.com/e-government-ua/i/blob/test/central-js/client/app/common/factories/markers.factory.js))

создать маркер-валидатор:
```
  {
    validate: {
      ,FileExtensions_1: { //унифицированный валидатор расщирений файлов
        aField_ID: ['file1','file2'],
        saExtension: 'jpg,pdf,png',
        sMessage: 'Недопустимий формат файлу! Повинно бути: {saExtension}Ї'
      }
    }
  }
```

вместо найденного "{saExtension}" подставлять значение соотв. параметра

**Comment by GFalcon-UA** [comment]
Для тестирования маркера в форме заявки должно быть поле с html-тегом <file-field> и присвоенным атрибутом name значением, которое указано в параметре aField_ID
Маркер должен начинаться с FileExtensions_ExtValue - где ExtValue - любое текстовое/цифровое значение
saExtension - обязательный параметр маркера - должен быть в формате строки со значениями, которые разделены запятыми (после запятых можно писать пробелы)
В шаблон сообщения валидатора sMessage допускается передавать имя любого из параметров маркера, при условии, что оно будет заключено в фигурные скобки.

**Comment by GrekD** [comment]
@GFalcon-UA работает, спасибо!
