### ISSUE TITLE
Доработать профиль Налоговой Службы

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1259]
https://sfs.igov.org.ua/

сравниваем с http://sfs.gov.ua/

**Шапка:**
- [x] 1. сделать ширину такой же, как на сайте ДФС
- [x] 2. сделать такой же фавикон
- [x] 3. справа от лого поставить поиск по сайту (там get-запрос, типа: http://sfs.gov.ua/search/?query=qwerty)
- [x] 4. сделать лого и элементы справа от него такого же размера, как на сайте sfs
- [x] 5. пункты меню справа сделать в таком же стиле, как "Публічна інформація", "Адміністративні послуги" на sfs.

**Тема:**
- [x] 6. убрать фильтр в поле поиска
- [x] 7. убрать статистику "оналйн, "дуже скоро"... под полем поиска.

**Comment by nazarenkod** [comment]
доработка не реализована

**Comment by nazarenkod** [comment]
а можно еще номного подправить верстку в хроме Версия 51.0.2704.103 m
![2016-06-23_17-13-44](https://cloud.githubusercontent.com/assets/13256486/16306368/2337da20-3966-11e6-9447-e9a24a8c225a.png)

**Comment by nazarenkod** [comment]
все еще актуально
