### ISSUE TITLE
Реализовать возможность отправки уведомлений чиновникам e-mail/SMS 

### ISSUE THREAD

**Issue by chemfind** [e-government-ua/i#1260]
Реализовать возможность отправки уведомлений чиновникам на e-mail/SMS о новых заявках.
варианты:
– после поступления заявки
– кумулятивно через час/сутки, с учетом счетчика заявок

**Comment by bvv4ik** [comment]
прошу не создавать в данном репозитории ишью!
т.к. он только для отфильтрованных, формализованных для разработчиков и утвержденных ТЗ
для всех предложений есть форум: iForum
