### ISSUE TITLE
Неактивные поля в регистрационной форме по ФЛП

### ISSUE THREAD

**Issue by NataliaGaykalova** [e-government-ua/i#1261]
Налоговая вернула с отказом регистрацию физического лица-предпринимателя (№ 0196434770) по причине "Заповніть буд-ласка заяву державною мовою. Вами не зазначено поля: 1) "країна громадянства", "будинок". При заполнении формы окна ""країна громадянства", "будинок" - неактивны, их нельзя заполнить. Кроме того, ФИО тоже указано на русском языке. Просьба устранить данную проблему.

**Comment by dmitrijzabrudskij** [comment]
а как Вы авторизовывались для подачи заявки - через эцп или bankid?

**Comment by NataliaGaykalova** [comment]
и так, и так пробовала

**Comment by dmitrijzabrudskij** [comment]
а попробуйте еще раз, пожалуйста - даже если номер дома не втянется в форму. и сбросьте сюда номер заявки - я прослежу чтобы отработали нормально. (адрес у Вас можно из заявления на упрощенную систему налогообложения взять)

**Comment by NataliaGaykalova** [comment]
заявка 0-211444504, дом, номер квартиры и страна гражданства не втянулись. В заявлении на упрощенную систему налогооблажения все данные указаны. Буду благодарна, если поможете решить)

**Comment by dmitrijzabrudskij** [comment]
спасибо, сегодня займутся Вашей заявкой

**Comment by NataliaGaykalova** [comment]
И Вам спасибо, ожидаю

**Comment by NataliaGaykalova** [comment]
пришел положительный ответ. Спасибо.
