### ISSUE TITLE
сделать SubjectOrganJoinAttributes без nID, а с составнім ключем nID_SubjectOrganJoin + sName

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1262]
т.е. чтоб liqbase и дальше апдейтил по этому составному ключу

**Comment by brunneng** [comment]
Готово. Теперь в SubjectOrganJoinAttribute.csv  не нужно придумывать уникальный nID.

**Comment by bvv4ik** [comment]
забыл дописать про предварительную очистку ещё и таблиц SubjectOrganJoin, Service

**Comment by nazarenkod** [comment]
как можно проверить?

**Comment by bvv4ik** [comment]
работает
