### ISSUE TITLE
сделать автоматическую предварительную очистку SubjectOrganJoinAttributes и ServiceData

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1263]
и последующую заливку(load) туда данных туда из *.csv (liqbase-ом)

и так-же предварительную очистку таблиц:
На централе:
SubjectOrganJoin
Service
На бэйсе:
EscalationRule
EscalationRuleFunction
FlowLink
FlowPropertyClass
FlowProperty
Flow_ServiceData
SubjectOrganDepartment
AccessService*

ВАЖНО: В тех таблицах, где есть поле nID - отчищать только записи, которые с индексом "до 10000"

**Comment by brunneng** [comment]
Реализовано в контексте задачи 1262

**Comment by bvv4ik** [comment]
забыл дописать про предварительную очистку ещё и таблиц SubjectOrganJoin, Service

**Comment by nazarenkod** [comment]
подскажите сценарий для тестирования

**Comment by brunneng** [comment]
О сценарии отвечу позже. В таске появились новые требования и надо доделать.
