### ISSUE TITLE
Обеспечить работоспособность маркеров-валидаторов, которые работали на централе - в т.ч. и на дашборде

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1265]
т.е. реализовать "прослойку", работая через которую маркер-валидатор сможет как работать на Централе (в форме заполнения услуг) так и в дашборде (на профиле задачи, перед ее сабмитом)

**Comment by antonlegkiy** [comment]
добавил тестовые маркеры для того чтобы можно было протестировать работоспособность (поскольку большинству полей на дашборде еще не присвоены маркеры). https://test.region.igov.org.ua/tasks/selfAssigned/15033497 как пример. поле "П.І.Б. співробітника" принимает только укр буквы, другие символы и цифры не пропускает, "Реєстраційний номер звернення" принимает только цифры.. также маркеры что доступны сейчас на централе работают и на дашборде.
маркеры находятся в public-js и они общие как для централа так и для дашборда

**Comment by julyprodan** [comment]
1)"П.І.Б. співробітника"  принимает только укр буквы, другие символы и цифры не пропускает - прошу разрешить точку

**Comment by bvv4ik** [comment]
@julyprodan

Юлия, Антон добавил эти маркеры только для теста!
Вы можете запихнуть в БП те маркеры которые Вам нужно... все должно рабоаать так-же как и на централе(именно в отношении маркеров-валидаторов полей)

**Comment by bvv4ik** [comment]
Вас прошу добавляя в тестовые БП свои маркеры-валидаторы убедиться что все работает корректно и что вы можете начать это использовать
