### ISSUE TITLE
Починить при отработке сервиса /setTaskQuestions добавления сообщения в сущность /Message

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1266]
раньше работало но почему то перестало...

Проверить так:
1) подать заявку тестовую (в тестовой подкатегории), обязательно указав свлю электронку и запомнить номер заявки
2) зайти в дашбоард под логином/паролем tester/tester и найти там эту заявку
3) выбрать и нажать замечание, после чего отправить
4) убедиться что в письме придет жто замечание
5) на централе найти в моем журнале эту заявку и зайти в историю - там должно быть это замечание

**Comment by PaulLuchyn** [comment]
Принимаю в работу

**Comment by bvv4ik** [comment]
работает
