### ISSUE TITLE
Починить подапивание авторизации в дашборде и проблемы отрисовки табов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1267]
какая то странная штука начала происходить с региональным фронтом(дашбордом)
очень долго логинется...

и при этом бывает так, что уже табы отрисовались и осталась отриисованной страница ввода логина и пароля...

https://test.region.igov.org.ua

**Comment by hordesalik** [comment]
Добавлено отображение загрузки после входа пользователя пока загружаются данные для отображения списка задач

**Comment by MaksKnight** [comment]
проверил, все работает
