### ISSUE TITLE
Нету проверки на налл для поля Город

### ISSUE THREAD

**Issue by Ciget** [e-government-ua/i#1268]
Добрый день,

исправьте проблему с невалидной обработкой свойства длинны на текстовом поле **Город**

Шаги для воспроизведения:
1) Открыть любую услугу где есть выбор города (https://igov.org.ua/service/724/general)
2) Выберите любой город
3) Удалите (очистите поле) название города
4) вуаля

![incorrect_check_for_null](https://cloud.githubusercontent.com/assets/2539541/15045331/a0e2f4c8-12e2-11e6-8453-956b81d41f62.png)

Заранее спасибо.

**Comment by bvv4ik** [comment]
прошу самостоятельно не создавать в данном репозитории ишью!
т.к. он только для отфильтрованных, формализованных для разработчиков и утвержденных ТЗ
для всех предложений есть форум: iForum

либо есть у нас файл с бэклогом (гуглодок)
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit
