### ISSUE TITLE
Ошибка при авторизации

### ISSUE THREAD

**Issue by NataliaGaykalova** [e-government-ua/i#1269]
Уже пару дней не могу авторизоваться с помощью ЭЦП, при подтягивании сначала ошибка :Ошибка аутентификации Не зарегистрированный запрос. Повторите еще раз. А потом следующая ошибка. Скрин в приложении.
[Документ Microsoft Word.docx](https://github.com/e-government-ua/i/files/251721/Microsoft.Word.docx)

**Comment by bvv4ik** [comment]
прошу не создавать в данном репозитории ишью!
т.к. он только для отфильтрованных, формализованных для разработчиков и утвержденных ТЗ
для всех предложений есть форум: iForum
