### ISSUE TITLE
Баг в разделе "Внесення змін до реєстраційних даних фізичної особи-підприємця"

### ISSUE THREAD

**Issue by alex-xander-dp-ua** [e-government-ua/i#1273]
Вот такая ошибка после этапа подписания через ЭЦП. 
Это заявка ушла или не ушла?

![bug](https://cloud.githubusercontent.com/assets/16093571/15302676/e0987a38-1bbc-11e6-87a9-f9582f49ee29.jpg)

**Comment by bvv4ik** [comment]
прошу самостоятельно не создавать в данном репозитории ишью!
т.к. он только для отфильтрованных, формализованных для разработчиков и утвержденных ТЗ
для всех предложений есть форум: iForum или iTest

либо есть у нас файл с бэклогом (гуглодок)
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit
