### ISSUE TITLE
Подключить новый сервис рассылки СМС:

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1274]
- [x] 1) в generalConfig дописать гетеры для трех новых параметров:

> general.SMS.sURL_Send
> general.SMS.sMerchantId
> general.SMS.sMerchantPassword
> 

(в той-же системе именования переменных и гетеров как и с ОТП)

- [ ] 2) Класс разместить в пэкэдже:
**org.igov.io.sms**
с названием:
**ManagerSMS**

Ориентируясь на пример класса:
**ManagerOTP**

**Всегда указывать следующие данные:**
  "merchant_id":"13", //брать из параметра general.SMS.sMerchantId  "merchant_password":"qwerty",//брать из параметра general.SMS.sMerchantPassword
       "from":"iGov", 
**УРЛ брать из параметра:**  general.SMS.sURL_Send
(вместо урла: https://sms-inner.siteheart.com/api/otp_create_api.cgi
будет: https://sms-inner.siteheart.com/api/send_sms_api.cgi)

**Отправка сообщения:**
метод: POST
формат: application/json

- [ ] 3) руководствоваться документацией:
https://itwiki.privatbank.ua/wiki/SMS_API

**в частности:**
**JSON Формат запроса[править]**
При использовании JSON формата необходимо указать HEADER HTTP запроса content-type = "application/json; charset = utf-8"
```
{
  "merchant_id":"13",                        <!-- Айди мерчанта(клиентского сервиса). Необходимо указывать исключительно номер, а не полное название мерчанта. Выдается менеджером после подписания служебной записки -->
  "merchant_password":"qwerty",              <!-- Пароль мерчанта(клиентского сервиса). Выдается менеджером после подписания слежебной записки -->
  "sms":[
    {
       "from":"10060",                       <!-- Номер с которого SMS будет доставлена пользователю. Необязательный. По умолчанию - 10060.  --> 
       "phone":"+380XXXXXXXXX",              <!-- Номер телефона получателя в международном формате -->
       "text":"test sms"                     <!-- Текст сообщения -->
    }
  ]
}
```
В запрсое может быть передано более одного SMS-сообщения, т.е. в массиве sms может быть любое кол-во однотипных объектов
Обязательные поля:

> phone - номер получателя в международном формате (пример: +380671234567)
> text - текст сообщения

Опцинальные поля:

- from - Номер или альфаимя с которого будет доставлено SMS (по умолчанию 10060 или PrivatBank в зависимотси от страны назначения, возможность отправки от других имен должна согласовываться)
- sms_category - идентификатор категории/группы сообщений сервиса/мерчанта инициировавшего отправку
- date_expired - в формате yyyy-mm-dd HH:MM:SS, например 2015-06-08 22:22:00
- order_id - Идентификатор категории(группы) сообщений сервиса(мерчанта) инициировавшего отправку

**JSON Формат ответа:**
```
{
  "merchant_id":"13",
  "global_status":"ok",             <!-- Статус обработки всего JSON пакета. Если значение fail, значит весь пакет забракован -->
  "error_code":"Error1",            <!-- Код ошибки. Тег существует если global_status принимает значение fail -->
  "error":"error description",      <!-- Описание ошибки. Тег существует если global_status принимает значение fail -->
  "sms":[
    {
       "package_status":"fail",     <!-- Cтатус конкретной SMS. Если значение fail, значит SMS забракована, есил ok - принята к отправке -->
       "phone":"+380969747359",     <!-- Передаётся, если нет связанной с ним ошибки -->
       "error_code":"Error1",       <!-- Код ошибки. Тег существует если package_status принимает значение fail -->
       "error":"error description"  <!-- Описание ошибки. Тег существует если package_status принимает значение fail -->
     }
   ]
}
```
Поля которые будут возвращены в ответе если были переданы в запросе:

> phone
> sms_category
> order_id
> date_expired

- [ ] 4) в классе сервистаски отсылки почты и СМС (MailTaskWithAttachmentsAndSMS) заменить отсылку на этот новый сервис

**Comment by finchatticus** [comment]
и

**Comment by kr110666kai** [comment]
п.2, 3, 4 выполнены

**Comment by bvv4ik** [comment]
реализовано
