### ISSUE TITLE
Выборочное логирование по отдельным сущностям в хибернейте - апдейтов, инсертов и ремувов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1276]
- Реализовать в хибернейте возможность, чтоб по некоторым(именно некоторым) сущностям - сохранялись-бы все апдейты/инсерты/ремувы
- в логах
- чтоб можно было-бы, в случае чего, взять за несколько часов этих логов и дополнить данными взятый бэкап суточной давности

**Comment by nazarenkod** [comment]
как можно проверить?
