### ISSUE TITLE
Доработать первичное отсылаемое сообщение при подаче заявки

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1277]
Находится в классе: \i\wf-base\src\main\java\org\igov\io\mail\NotificationPatterns.java

Сейчас это:
Ваша заявка 0-256093732 прийнята!
Ви завжди зможете переглянути її поточний статус у розділі "Статуси". Також на кожному етапі Ви будете отримувати email-повідомлення.

А нужно: 
Вітаємо Андрію, Ваша заявка 0-256093732 прийнята!
Ви завжди зможете переглянути її поточний статус у розділі "Статуси". Також на кожному етапі Ви будете отримувати email-повідомлення.

Имя брать так-же из стандартного поля (как и электронку) с id="bankIdfirstName"

**Comment by IgorMaksymov** [comment]
Принимаю в работу

**Comment by IgorMaksymov** [comment]
был измнен заголовок для письма, дополнительно было вставлено имя юзера.

**Comment by IgorMaksymov** [comment]
был измнен заголовок для письма, дополнительно было вставлено имя юзера.

**Comment by nazarenkod** [comment]
Реализовано, но есть вопрос.
сейчас имя юзера выводится большими буквами (ДМИТРО)
![2016-05-27_9-01-33](https://cloud.githubusercontent.com/assets/13256486/15599149/d100c99c-23e9-11e6-8303-3b59089cd25e.jpg)
В шаблоне, который писал @bvv4ik имя должно быть(Дмитро). 
Что то изменилось?

**Comment by IgorMaksymov** [comment]
@nazarenkod он передается таким, как берется из системы логина, я не делал манипуляций над строкой, а передавал как есть.

**Comment by IgorMaksymov** [comment]
@nazarenkod теперь строка понижается в регистре, а затем 1-й чар повышается и становится "Дмитро"

**Comment by nazarenkod** [comment]
отличная работа, спасибо

**Comment by IgorMaksymov** [comment]
@nazarenkod как выяснилось, задание требует доработки т.к. может приходить null,а проверки нету

**Comment by IgorMaksymov** [comment]
@nazarenkod переделал.
Если  bankIdFirstName == null || bankIdFirstName.equalsIgnoreCase("null") то должно прислать письмо с заголовком  "Вітаємо, Ваша заявка прийнята!"

**Comment by nazarenkod** [comment]
@IgorMaksymov как можно получить  bankIdFirstName = nul для проверки заголовка?l

**Comment by IgorMaksymov** [comment]
@nazarenkod когда он не передается вообще или когда вы неправильно его берете.
или попробуйте взять не id="bankIdfirstName", а id="bankId**F**irstName"(большая F) и тогда он не найдет параметр и передаст null
