### ISSUE TITLE
Указывать при отправке почты имя адресата, по мимо электронки

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1278]
- [x] 1) Доработать класс: \i\wf-base\src\main\java\org\igov\io\mail\Abstract_Mail.java
и \i\wf-base\src\main\java\org\igov\io\mail\Mail.java
так, чтоб можно было задавать еще и имя получателя, которое-бы при отсылке учитывалось.

например вместо "khvetkevich@gmail.com" чтоб отсылалось на 

`"Андрій Хветкевич <khvetkevich@gmail.com>"`

, где "Андрій Хветкевич" задавалось-бы через метод "_ToName"

если не задан то отправлять как и раньше

- [ ] 2) Во всех БП, где используются системтаски:
MailTaskWithAttachment
MailTaskWithAttachments
MailTaskWithoutAttachment
передавать в параметр "to" не только электронный адрес(например: "khvetkevich@gmail.com"), но и имя (например: "Андрій Хветкевич <khvetkevich@gmail.com>")

- [x] 3) Везде где используется класс \i\wf-base\src\main\java\org\igov\io\mail\Mail.java (кроме случаев п.2) - передавать обязательно еще и параметр Имени в сетере "_ToName" (Фамилию и Имя), где это возможно... а где не возможно указать в комментариях к ишью

- [x] 4) При отправке через Юнисендер так-же передавать теперь єто название в доп-поле
 значение для подстановки {{ToName}}

```
в этом методе:
public UniResponse subscribe(SubscribeRequest oSubscribeRequest) throws Exception {
этом классе:
public class UniSender {
этом пэкэдже:
package org.igov.io.mail.unisender;

```
документация на сервисы:
https://support.unisender.com/index.php?/Knowledgebase/Article/View/35/0/podstnovk-strok-v-pisme

оно будет в техзаголовках.
лимит - 78 символов
http://joxi.ru/Bv29aPlf9EGj2G  вот тест проводил
все что будет в поле с этой подстановкой - будет в техзаголовках письма

при добавлении данных контакта нужно передавать значение допполя, по которому используется эта подстановка
или же просто вместо Name  использовать ToName
при добавлении данных контактаэто при использовании сервиса /api/subscribe
при использовании данного метода вы добавляете по контакту информацию

**Comment by kurbpa** [comment]
@bvv4ik 
аналогичная поддержка должна значит быть и в системтаске MailTaskWithAttachmentsAndSMS

**Comment by IgorMaksymov** [comment]
принято в работу сабтаски 1 и 3

**Comment by kurbpa** [comment]
@bvv4ik 

какая должна быть форма записи для отправки на несколько емейлов?
`${mail},${mail2},kyrbatsky@gmail.com,kurbpa@gmail.com`

**Comment by julyprodan** [comment]
@bvv4ik Владимир, я добавила  <activiti:expression><![CDATA[${bankIdlastName} ${bankIdfirstName} <${email}>]]></activiti:expression>
в письме приходит Кому: klimkovichy@gmail.com

Это так и должно быть?

**Comment by IgorMaksymov** [comment]
Были изменены методы:
1) org.igov.io.mail.NotificationPatterns#sendTaskCreatedInfoEmail
2) org.igov.io.mail.NotificationPatterns#sendTaskEmployeeQuestionEmail
3) org.igov.model.document.access.DocumentAccessDaoImpl#setDocumentLink

методы, в которых я не вижу способа получить имя:
1) org.igov.io.mail.NotificationPatterns#sendVerifyEmail
неоткуда брать данные
2) org.igov.service.controller.actionexecute.ActionExecuteController#testMail
неоткуда брать данные / тест.
3) org.igov.service.controller.ActionTaskCommonController#downloadTasksData 
неоткуда брать данные
4) org.igov.service.controller.DebugCommonController#sendAttachmentsByMail
неоткуда брать данные / тест.
5) org.igov.service.business.escalation.handler.EscalationHandler_SendMailAlert#sendEmail
неоткуда брать данные
6) org.igov.service.controller.FinanceCommonController#setPaymentStatus_TaskActiviti
неоткуда брать данные / тест.


также я не трогал класс org.igov.service.business.action.task.systemtask.mail.MailTaskWithAttachmentsAndSMS

**Comment by IgorMaksymov** [comment]
заметка: протестировать отправку писем множеству адресатов через ","
