### ISSUE TITLE
Реализовать механизм сохранения отсылаемых почтовых сообщений

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1279]
- [x] 1) Дополнить сущность SubjectMessage полем:
sID_DataLink - Строка-ИД линка на данные
- [x] 2) Дополнить справочник SubjectMessageType записью:
nID;sName;sDescription
10;ServiceMailSent;Отправлено письмо на почту
- [x] 3) При каждой отсылке электронного письма на гражданина:
- [x] 3.1) контент этого письма сохранять в Монго
- [x] 3,2) в сущность SubjectMessage (на централе) добавлять новую строку, а в ней сохранять такие данные:
- sID_DataLink - ключ записи Монги в поле 
- sHead - "Отправлено письмо"
- sBody - Заголовок письма
- sDate - текущая дата и время
- sMail - электронка, но которую отсылаем
- nID_SubjectMessageType = 10
- nID_HistoryEvent_Service (HistoryEvent_Service найти по sID_Order, которое определить по про ИД процесса)
- nID_Subject = 0
- sContacts = ""
- sData = ""
- sBody_Indirectly = null
- sSubjectInfo = null
- [x] 4) Написать на централев контроллере SubjectMessageController сервис /getSubjectMessageData с параметром:
nID_SubjectMessage - номер-ИД записи с сообщением субьекта
который будет возвращать контент монги(просто HTML-контент) по ключу из поля sID_DataLink, соответствующей записи nID_SubjectMessage
- [x] 5) При не нахождении эксеппшин RecordNotFound, и не 200-тый код

- [x] 6) Дополнить сервис п.5 параметром: 
```

            @ApiParam(value = "Номер-ИД субьекта (хозяина заявки сообщения)", required = false) @RequestParam(value = "nID_Subject", required = false) Long nID_Subject,
            @ApiParam(value = "булевский флаг, Включить авторизацию", required = false) @RequestParam(value = "bAuth", required = false, defaultValue = "false") Boolean bAuth,

```
и кодом в начале:

```
            Long nID_HistoryEvent_Service = взять из записи сообщения.
            
            HistoryEvent_Service oHistoryEvent_Service = historyEventServiceDao.findById(nID_HistoryEvent_Service);
            nID_HistoryEvent_Service = oHistoryEvent_Service.getId();
            
            if(bAuth){
                actionEventService.checkAuth(oHistoryEvent_Service, nID_Subject, sToken);
            }


```
для возможности проверки принадлежности сообщения

**Comment by ASkosyr** [comment]
Как проверять.
В сообщения сохраняются письма о результате обработки заявок.
Например, при тестировании на услуге
https://test.igov.org.ua/service/1/general
следуюет полностью обработать заявку.

После обработки заявки можно просмотреть список всех системных сообщений, используя ID заявки.
Например, запрос https://test.igov.org.ua/wf/service/subject/message/getServiceMessages?sID_Order=0-230375011 возвращает результат
```
[{"oMail":{"subject":{"sID":"2872618515","sLabel":"","sLabelShort":"","nID":0},"subjectContactType":{"sName_EN":"Email","sName_UA":"Електрона адреса","sName_RU":"Электнонный адрес","nID":1},"sValue":"askosyr@gmail.com","sDate":"2016-06-06 22:15:31.654","nID":48771},"nID_HistoryEvent_Service":74450,"oSubject":{"sID":"2872618515","sLabel":"","sLabelShort":"","nID":0},"sID_DataLink":"229d3838-0d3c-4fa7-aafe-4665a9cd0fb3","nID":74452,"sHead":"","sBody":"Звернення на тему: Надання довідки про відсутність або наявніть судимості","sDate":"2016-06-06 22:15:31.684","nID_Subject":0,"sMail":"askosyr@gmail.com","sContacts":"","sData":"0","oSubjectMessageType":{"sDescription":"Отправлено письмо на почту","nID":10,"sName":"ServiceMailSent"}}]
```
где "nID":74452 номер сохраненного сообщения

Используя этот номер можно получить содержимое сообщения
https://test.igov.org.ua/wf/service/subject/message/getSubjectMessageData?nID_SubjectMessage=74452
