### ISSUE TITLE
Подобрать и реализовать централизованную систему логирования

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#128]
Подобрать и реализовать централизованную систему логирования, для сбора логов серверов в одном общедоступном месте(может веб), и желательно с настройками прав доступа.(для Java-BackEnd и NodeJS-FrontEnd)

т.к. лазить на разные машины, собирая логи - очень дорогая процедура...

Главные критерии: бесплатный, легкий в установке/интеграции, не экзотический (чтоб в нети доки/примеры и юзатели были в достаточном количестве)

**Comment by shvaykovski** [comment]
https://getsentry.com/

**Comment by paul-lysak** [comment]
Если разворачивать на своих серверах - есть такой стек технологий: http://logstash.net/ в конечном счете логи оказываются в ElasticSearch.

**Comment by borikd** [comment]
будет уже откатанный нами набор fluentd + elastisearch+shield plugin + kibana

**Comment by borikd** [comment]
хотя, насчет shield plugin сомневаюсь, ибо платный он:)

**Comment by bvv4ik** [comment]
Главные критерии: бесплатный, легкий в установке/интеграции, не экзотический (чтоб в нети доки/примеры и юзатели были в достаточном количестве)

**Comment by budnik** [comment]
@paul-lysak стэк называется [ELK](https://www.elastic.co/webinars/introduction-elk-stack), даёт  :100: очков другим опенсорс технологиями. Если не удасться найти подходящее клауд(SaaS) решение, то этот вариант боллее чем подходящий. Работал с ним пару лет, могу ответить на вопросы.

Ещё есть [sentry](/getsentry/sentry), это немного другое, но может даже лучше.

**Comment by denden76** [comment]
пока  fluentd + elastisearch + kibana + nginx - в качестве морды с простой веб ауентификацией... Или она не надо?

**Comment by barif** [comment]
Предлагаю Kibana + ElasticSearch, как по мне, общепринятая практика в отрасли, бесплатно и надежно.

**Comment by zora-borys** [comment]
+1

2015-04-29 21:30 GMT+03:00 Alexandr <notifications@github.com>:

**Comment by admiral-diver** [comment]
+1

**Comment by denden76** [comment]
так мы это тоже предлагаем :)

**Comment by ValerijMakarenko** [comment]
более того, это даже реализовано..

**Comment by bvv4ik** [comment]
как говорится - дьявол в деталях...
пока еще не реализовано, но надеюсь таки будет реализовано совсем скоро...
параллельно реализовывается еще один вариант, в котором основа та-же "Kibana + ElasticSearch"... но - есть ньюанс)

**Comment by ValerijMakarenko** [comment]
непонятно. зачем разворачивать две площадки, с одним и тем же назначением, да еще и софт одинаковый ) ?

**Comment by bvv4ik** [comment]
он не полностью одинаковый, и общая модель немножко другая..

ведь почти во всех машинах по 4-ре колеса и одному рулю, это-ж не означает что нам достаточно будет "копейки на все времена")

**Comment by ValerijMakarenko** [comment]
так в этом и вопрос -зачем, зачем тратить время людей и рессурсы? давайте один вариант просто уберем и всё..

**Comment by bvv4ik** [comment]
следуя такой логике:
Зачем нам мелкий, средний и крупный бизнес?
давайте устроим один большой СССР, с монопольным "единым предприятием"...

кроме 25-лет опыта в ИТ, у меня около 20-ти лет опыта в бизнесе(своем/совместном), хобби - политика, и два экономических образования...

потому если кто-то еще задает себе такие вопросы "а зачем нам избыточность, когда можно на этом сэкономить" - я отвечаю просто "надо!")
(а если все-же интересны и не понятны "детали", по "надо", с удовольствием объясню в личку или голосом в чате... а то мы тут такой флейм разведем, что забудем с чего начинали)

**Comment by denden76** [comment]
мне интересны детали, ибо 1 вариант пилим мы...могет не надо его пилить

**Comment by bvv4ik** [comment]
надо-надо) с Дмитриями лександровичами это все согласовано)

давай в скайп?
мой: belyavtsevw

**Comment by bvv4ik** [comment]
уже реализовано централизованное логирование на Kibana+Jelastic и т.д.
