### ISSUE TITLE
Проблема с авторизацией через ЭЦП

### ISSUE THREAD

**Issue by max-andr** [e-government-ua/i#1280]
Добрый день!
Хотел воспользоваться авторизацией через ЭЦП, но столкнулся с проблемой: весь компьютер завис на процессе авторизации.

Мои действия:
1. Захожу на услугу https://igov.org.ua/service/1497/general
2. Кнопка "Сертификат ЭЦП"
3. Кнопка "Обрати файл"
4. Выбираю ключ Key-6.dat
5. Ввожу пароль
6. Кнопка "Далі"
7. Весь компьютер полностью виснет более чем на 5 минут, даже курсор перестаёт двигаться. Приходится перезагружать компьютер.
Проблема проявляется и на Ubuntu, и на Windows. Был установлен CryptoPlugin для Хрома, и .deb/.exe файл.

При этом авторизация через Приват24 работает отлично, но мне нужен вхож именно через ЭЦП.

**Comment by Koffeek** [comment]
@max-andr Какой именно ЭЦП Вы пользуетесь?

**Comment by max-andr** [comment]
@Koffeek 
ЭЦП, которую я получил прямо в налоговой.

**Comment by bvv4ik** [comment]
@max-andr прошу писать в iForum https://github.com/e-government-ua/iForum/issues
данный репозиторий только уже для постановке конкретных ТЗ на разработчиков а не для разбора проблем
