### ISSUE TITLE
Реализовать маркер-валидатор FieldNotEmptyAndNonZero

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1281]
который не будет допускать наличия пустоты в поле или нуля

**Comment by GFalcon-UA** [comment]
маркер можно цеплять как к селектам, так и к обычным полям - должно работать
главное, чтоб имя маркера было в формате
FieldNotEmptyAndNonZero_XXX - где ХХХ - любое значение
а aField_ID - был в формате массива (все обрамлено в квадратные скобки, внутри разделение элементов - запятыми)

**Comment by antonlegkiy** [comment]
1 если поле не обязательное - идет проверка на введенные вручную значения, если таких районов/городов нет - выводиться ошибка и не невозможно отправить форму.
2 если поле обязательное к заполнению форма не будет отправлена пока поле не заполнено, поле считается верно заполненным если выбран район/город с предложенного списка

проверка в данном случае ведется на "sID_Public_SubjectOrganJoin"  "0".

**Comment by sergeygorban** [comment]
Антон, дайте ваш скайп для связи

**Comment by antonlegkiy** [comment]
dn200690lav
