### ISSUE TITLE
При переходе по силке "видео вступления" получаю ошибку

### ISSUE THREAD

**Issue by Sharabaddin** [e-government-ua/i#1282]
При обработке вашего запроса в службе совещаний произошла ошибка. Обратитесь в службу поддержки или к своему администратору и предоставьте следующий идентификатор отслеживания ошибки:Идентификатор отслеживания ошибки:
(9E09A04370564058B2DC47D3E685E505_1464862871930)

**Comment by stepio** [comment]
Уочняю:
1. Заходим на "wiki" проекта: [Як почати роботу](https://github.com/e-government-ua/i/wiki/%D0%AF%D0%BA-%D0%BF%D0%BE%D1%87%D0%B0%D1%82%D0%B8-%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D1%83)
2. "Кликаем" на ссылку: [Видео - вступление!](https://pbank.webex.com/pbank-ru/ldr.php?RCID=8cdd26659085938889cae387d69ffd65)
3. Открывается страница:
![Error screenshot](https://www.dropbox.com/s/k7mglxx9nhnhx8i/Screenshot%202016-06-10%2011.33.07.png?raw=1)

**Comment by bvv4ik** [comment]
прошу самостоятельно не создавать в данном репозитории ишью!
т.к. он только для отфильтрованных, формализованных для разработчиков и утвержденных ТЗ
для всех предложений есть форум: iForum

либо есть у нас файл с бэклогом (гуглодок)
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit
