### ISSUE TITLE
В истории заявки давать открывать текст отосланных гражданину писем.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1283]
В продолжение реализации https://github.com/e-government-ua/i/issues/1279

- [x] 1) В истории заявки (Мой журнал), для сообщений где nID_SubjectMessageType = 10 отрисовывать ссылку с названием "письмо", который будет открывать новое окно, в которое будет подгружаться контент письма, отосланного гражданину. (на всю страницу), и это окно можно будет только закрыть  целиком (внутри только ХТМЛ и ни каких кнопок)

- [x] 2) Контент письма подгружать с помощью явовского сервиса  /subject/message/getSubjectMessageData куда нужно передавать параметр nID_SubjectMessage (ИД сообщения из п.1)

- [ ] 3) При вызове сервиса п.2, как и для всех остальных вызовов сервисов обязательно передавать на сервер Явы еще и параметр nID_Subject и параметр bAuth=true, если это не администратор, или bAuth=false если администратор.

**Comment by antonlegkiy** [comment]
пример заявки https://test.igov.org.ua/search?sID_Order=0-230304754.

если в сообщении nID_SubjectMessageType = 10, появляется ссылка с именем "Лист", по нажатии на которую открывается окно с телом письма.

**Comment by AlenaUglenko** [comment]
vds

**Comment by nazarenkod** [comment]
п.1 и п.2 реализованы.
п.3.сейчас возвращает 
`{code: "500", message: "Unknown exception: null"}` 
![2016-06-23_17-05-02](https://cloud.githubusercontent.com/assets/13256486/16306060/1a77df6c-3965-11e6-979c-6f522b7b9b7e.png)
Ждем реализации п.3
