### ISSUE TITLE
Выводить в сервис логирования ошибок MSG и все ошибки и варнинги бэкэнда на уровне контроллера

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1284]
В классе: \i\wf-base\src\main\java\org\igov\io\Log.java
Методе: public Log send(){

выводить все 
if(oStatus==LogStatus.ERROR){
как DANGER

выводить все 
}else if(oStatus==LogStatus.WARN){
как WARNING

и максимально выводить в MSG всю информацию об эксепшине, в плоть до стектрейса

все точно так-же как и с выводом клиентских ошибок - с авто-созданием типов ошибок, где ключем будет в этот раз "тип(варнинг/еррор"(как и было) + Метод в котором произошел эксепшен(или класс)

**Comment by kr110666kai** [comment]
}else if(oStatus==LogStatus.INFO){
Отылать?

**Comment by kr110666kai** [comment]
Добавлен вывод для 
oStatus==LogStatus.ERROR
oStatus==LogStatus.WARN

**Comment by bvv4ik** [comment]
работает
