### ISSUE TITLE
При открытии тестовой версии сайта - вываливается json error

### ISSUE THREAD

**Issue by Ciget** [e-government-ua/i#1286]
Steps to reproduce:
1) Открыть в браузере [https://test-version.igov.org.ua/service/4/general](https://test-version.igov.org.ua/service/4/general)

![image](https://cloud.githubusercontent.com/assets/2539541/15908621/50a6ac9e-2dcb-11e6-8c37-0763ced31d77.png)

**Comment by bvv4ik** [comment]
прошу самостоятельно не создавать в данном репозитории ишью!
т.к. он только для отфильтрованных, формализованных для разработчиков и утвержденных ТЗ
для всех предложений есть форум: iForum

либо есть у нас файл с бэклогом (гуглодок)
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit
