### ISSUE TITLE
При заказе вытяга местного главы "Помилка по операціїД Сапбміт форми посліги" на тестовом сайте

### ISSUE THREAD

**Issue by Ciget** [e-government-ua/i#1287]
1) Пойти на тестовую версию сайта https://test-version.igov.org.ua
2) Заказать услугу "Видача копій, витягів з розпоряджень міського (селищного) голови, рішень, прийнятих міською (селищною) радою та виконавчим **комітетом"**
3) Заполнить все валидными данными (скрин есть)
4) нажать кнопку заказать

Ожидаю - прийдет смс и покажется сообщение что все гуд
Реальность - пришла смс а на экране еррор мессейдж.
![image](https://cloud.githubusercontent.com/assets/2539541/15964648/29516cbc-2f22-11e6-9f73-49bc4ef5a178.png)

**Comment by smoktii-igov** [comment]
Используйте для тестирования (подачи заявок) сайт https://test-delta.igov.org.ua 
Для обработки заявок сайт: https://test-delta.region.igov.org.ua/

Только что проверил https://test-delta.igov.org.ua. Там все подается. 
Если на https://test-delta.igov.org.ua  возникнут проблемы напишите, по какой области/городу возникла проблема

**Comment by Ciget** [comment]
Так, на цьому сайті все працює. 
Дякую.
