### ISSUE TITLE
Результат обробки послуги

### ISSUE THREAD

**Issue by NataliaGaykalova** [e-government-ua/i#1288]
Доброго дня!
Немає виписки на сайті мінюсту по зверненню №0-301593196. Хоча прийшла відповідь з iGov, що:
 "Шановний(-а) МАКСИМ ВІТАЛІЙОВИЧ
Ваше звернення №0-301593196 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено позитивне рішення про реєстрацію змін."

**Comment by agerman-ua** [comment]
@NataliaGaykalova 
Доброго дня.
Дякую за повідомлення. В наступній версії виправимо текст листа.
Тепер щодо відсутності даних у реєстрі.
Інформація від держслубовця буде тільки завтра.
З повагою, Август.

**Comment by NataliaGaykalova** [comment]
З текстом проблеми немає, проблема в тому, що немає виписки більш ніж 10 днів.

**Comment by agerman-ua** [comment]
Держслужбовець просила розбір перенести на завтра.

**Comment by NataliaGaykalova** [comment]
гаразд, чекаємо на завтра

**Comment by agerman-ua** [comment]
@NataliaGaykalova 
Доброго ранку.
Не знаю з чого почати. Якби не реальний випадок то начебто схоже на жарт.
Ми з держслужбовцем дійшли висновку що по Вашій заявці була відмова, але людина помилково обрала пункт "позитивне рішення" заімість "відмова".
Вибачте за затримку. В цій гілці Вас не очікували побачити. Пишіть наступного разу, будь ласка, у "iForum" https://github.com/e-government-ua/iForum/issues
До речі, держслужбовець дуже вибачається.
Пропоную Вам подати нове звернення та написати його номер сюди. Ми, в такому разі, спробуємо передати її саме цьому виконавцеві (вона щиро відчуває свою провину). Якщо не напишете - тоді звернення буде опрацьовано у звичайному режимі.
Ще раз вибачте за незручності. Це "Фактор людини". Передбачити абсолютно все просто неможливо.
З повагою, Август.

**Comment by bvv4ik** [comment]
прошу не создавать в данном репозитории ишью!
т.к. он только для отфильтрованных, формализованных для разработчиков и утвержденных ТЗ
для всех предложений есть форум: iForum
