### ISSUE TITLE
Создать единую точку логирования для Back-End RESTFul

### ISSUE THREAD

**Issue by admiral-diver** [e-government-ua/i#129]
Создать проект logging в корневом каталоге репозитория "i". Вынести в него кофиг логера и организовать единый логер для всего кастомного бэка. Отрефакторить логирование в текущем Back-End RESTful

**Comment by brunneng** [comment]
А обязательно для логирования выделять аж целый отдельный проект? Не достаточно ли будет подключить http://www.slf4j.org/  + кастомный файл конфигурации для каждого веб модуля?

**Comment by bvv4ik** [comment]
вообщем смотрите, эта задача сейчас по сути уже выполняется нашим коллегой... Запущен центральный сервер кибаны, куда через логслэш будут роутиться все логи и с фронтов и с бэков и с система... мало того, это все будет настроено уже через папет-сервер, который позволит централизованно синхронизировать настройки всех серверов.
в результате мы элементарно через комит в рему - сможем переконфигуривать сервера и все средства логирования...

и причем в планах длижайших дней это все уже до-реализовать...

потому пока эту задачу отдельно реализовывать не нужно, т.к. она решится как составная часть более общей задачи.

**Comment by bvv4ik** [comment]
уже реализовано централизованное логирование на Kibana+Jelastic и т.д.
