### ISSUE TITLE
Реализовать сервис принятия фидбека по услуге от сторонней организации

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1290]
- [x] 1) Сервис: /setFeedbackExternal

Контекст: /subject/message

**Параметры:**
sID_Source - 50
sAuthorFIO - 300
sMail - 150
sHead - 500 **//опциональный**
sBody - 2000
**sPlace - 200 //опциональный**
**sEmployeeFIO - 300 //опциональный**
nID_Rate
nID_Service
**sAnswer - 2000 //опциональный**

**ОТВЕТ:**
`{"sURL":"https://alpha.test.igov.org.ua/service/123/feedback?nID=345&sID_Token=3dsf45e632e6t5t43"}`
где:
"https://alpha.test.igov.org.ua" - берется из гетера хоста централа класса generalConfig
"123" - nID_Service
"3dsf45e632e6t5t43" - сгенеренный токен из 20-ти символов, и сохраненный в базу
345 - ИД добавленной записи 

**При задавании параметра nID sToken, и их совпадении с найденной строкой - обновлять запись а не добавлять новую**

**При задавании параметра sAnswer - записывать его значение  - последним элементом массива**
Пример sAnswer-параметра:
{
"sFIO":"Эльвира"
,"bSelf":false
,"sDate":"2016-17-11 09:33:23.100"
,"sText":"Рады помочь!"
}
При этом в поле "sAnswer", например массив - 
{
"sFIO":"Эльвира"
,"bSelf":false
,"sDate":"2016-17-11 09:33:23.100"
,"sText":"Рады помочь!"
}
,{
"sFIO":"Эльвира"
,"bSelf":false
,"sDate":"2016-17-12 09:33:23.100"
,"sText":"Взаимно!"
}
]

- [x] 2) Записывать это в созданную сущность SubjectMessageFeedback
с такими-же полями включая sID_Token

- [x] 3) Сервис: /getFeedbackExternal - получение списка фидбеков

Контекст: /subject/message

**Параметры:**
nID_Service - номер-ИД //опциональный (если не задан то выдает только одну запись автора, иначе все записи по сервису)
sID_Token - строка-ИД токена
nID - номер-ИД

- Обязательно проверять соотвествие sID_Token у найденной по nID записи, что подтверждает что запрашивает автор. И только тогда разрешать далее отрабатывать запрос, иначе ошибка "Not permission!"
- При этом если не передать nID_Service то отдать должно один элемент в массиве (чей ИД)
- А если передать nID_Service, то все записи по этому сервису отдавать

Ответ:
массив обьектов, но без Токенов

**Comment by sergeygorban** [comment]
Здравствуйте! Необходим скайп для связи с разработчиком.

**Comment by IgorMaksymov** [comment]
@sergeygorban  maksymov.i
