### ISSUE TITLE
При любом изменении статуса заявки - автоматически закрывать порожденный БП эскалаций

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1294]
Общая точка где мониторится проверка изменений статусов - в интерцепторе (там-же и пораждаются БП эскалации)

**Comment by GrekD** [comment]
@ASkosyr 
Саша, можешь, пожалуйста, перенести эти правки ветку мастер?
и отписаться )

**Comment by ASkosyr** [comment]
Замержил в мастер
