### ISSUE TITLE
Проблема з наданням виписок

### ISSUE THREAD

**Issue by NataliaGaykalova** [e-government-ua/i#1296]
Згідно заявок:
№ 0227566107 від 10.05.2016 КІсанов Ю.З.
№ 0227612922 від 10.05.2016 Хадаєв О.О.
№ 0227774757 від 10.05.2016 Шуба І.В.
№ 0229483167 від 11.05.2016 Голуб Я.С. 
було зареєстровано підприємців. Але на сайті Мінюсту є лише витяги по даним ФОПам. Раніше на електронну адресу присилався опис, тепер він не надсилається. Яким чином ми можемо отримати Виписки з ЄДР? На сайті Мінюсту за вказаними номерами заявок їх немає

**Comment by lem8r** [comment]
Ці номера заявок не мають ніякого відношення до сайту мінюсту.
Якщо ці заявки виконано, то зробіть платний витяг на сайті мінюсту:
https://usr.minjust.gov.ua/ua/extractedr
А взагалі, ЄДРПОУ є в публічному доступі, тому надавати комусь витяг звідти не потрібно.

**Comment by bvv4ik** [comment]
прошу не создавать в данном репозитории ишью!
т.к. он только для отфильтрованных, формализованных для разработчиков и утвержденных ТЗ
для всех предложений есть форум: iForum

**Comment by lem8r** [comment]
Может вам помочь организовать нормальный форум или саппорт?

29 черв. 2016 11:43 "bvv4ik" <notifications@github.com> пише:

**Comment by NataliaGaykalova** [comment]
было бы неплохо. Буду Вам благодарна)

**Comment by lem8r** [comment]
@NataliaGaykalova с кем можно про это поговорить?

**Comment by NataliaGaykalova** [comment]
со мной (Skype: n_gaykalova)
