### ISSUE TITLE
при вводе комментария волонтером в производной заявке-эскалации и сабмите - копировать его в виде отдельных сообщений истории заявки (основной и производной)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1297]
добавлять запись в сущность SubjectMessage

оптимально отлавливать это в интерцепторе
смотреть нужно на БП у которого id=system_escalation
когда идет операция апдейта
глядя на поле с id=comment (именно в нем коммент вносится)

Сохранять запись с типом:
9;ServiceCommentEmployeeAnswer;Работника ответ/комментарий по услуге

делать это через вызов сервиса на централе (посмотреть как это делается через замечание и сделать подобно... вроде сервис: setSubjectMessage)

**Comment by kr110666kai** [comment]
Пока застрял на воспроизведении ситуации эскалации

**Comment by GrekD** [comment]
@kr110666kai 
добрый день!
вот алгоритм воспроизведения эскалации:
1. https://alpha-old.test.igov.org.ua/service/786/general
подаем заявку, область - Киев, город - Киев (только эти населенные пункты надо выбирать - на других не сработает)
2. запускаем запрос:
https://alpha-old.test.region.igov.org.ua/wf/service/action/escalation/runEscalationRule?nID=425
3. заходим в дашборд https://alpha-old.test.region.igov.org.ua
ПІБ : volont_escalation
Логін : volont_escalation
ищем последнюю

**Comment by GrekD** [comment]
забыла еще добавить:
 - эскалация генерится только один раз, т.е. если Вам еще надо что-то проверить - надо заново подавать родительскую заявку, генерить по ней эскалацию, вобщем проходить весь круг заново
- эскалация пропадет только если произойдут какие-то изменения с родительской заявкой (ее возьмут в работу или отработают) - по другому в ней можно только переносить срок рассмотрения, но закрыть не получится

**Comment by bvv4ik** [comment]
@kr110666kai 
Александр, ну как, получится сделать прогноз по времени, которое еще может понадобиться?

**Comment by kr110666kai** [comment]
Застрял на вопросе воспроизведения самой ситуации. Эскалацию сделать получается. Беру ее в работу, добавляю комментарий, но при попытке сохранения возникает ошибка: {"code":"BUSINESS_ERR","message":"Record with
 nID_Server=5 and nID_Process=20210066 not found!"}

**Comment by kr110666kai** [comment]
На текущий момент, даже создание эскалации не работает 
Cannot read property 'nID' of undefined (caused by "")
https://drive.google.com/file/d/0B4_nhAYzTtL6Z0RkVC0xN29jdXc/view?usp=sharing

**Comment by GrekD** [comment]
@kr110666kai 
зайдите сюда:
https://alpha-old.test.region.igov.org.ua
и оставьте комментарий по любой из уже существующих заявок.
Для этого нужно в поле: Коментар за результатми контакту з адміністративним органом *
оставить хоть что-то

там же среди полей есть такое: Номер первинного звернення - вот по нему можно найти исходную
вот например я оставила комментарий в заявке №236325661, и вот как это выглядит в родительской заявке 236325013:
https://alpha-old.test.igov.org.ua/search?sID_Order=0-236325013

**Comment by kr110666kai** [comment]
Не сохраняется комментарий.  В логах ошибка, а в зверненни на месте коментария 
```
Коментар по ескалації послуги за заявою 0-236300991
null
```
Я пытаюсь отследить комментарий так:

1. захожу как volont_escalation
2. беру в работу
3. заношу в "Коментар за результатми контакту з адміністративним органом *" что-то типа 111-111.
4.  Жму опрацювати

Потом ищу комментарий в логах:

Например в Service_Controller.log:

```
2016-07-14_17:04:58.688 | INFO | interceptor.RequestProcessingInterceptor | http-nio-13100-exec-19 | [protocolize](sRequestBody={"
taskId":"23627669","properties":[{"id":"comment","value":"222-222"},{"id":"nCountDays","value":"1"}]})

..................................
пропущено
..................................

2016-07-14_17:04:58.803 | ERROR | interceptor.RequestProcessingInterceptor | http-nio-13100-exec-19 | [save] ERROR   [IC_TimeExecu
tion]{}({sID_Process=23627663}):Can't close escalation for task /0)org.igov.service.controller.interceptor.RequestProcessingInterc
eptor.getTotalTimeOfExecution(521):null

..................................
пропущено
..................................


2016-07-14_17:04:59.012 | ERROR | interceptor.RequestProcessingInterceptor | http-nio-13100-exec-19 | [save] ERROR   [IC_TaskClose
]{}({sResponseBody=, sRequestBody={"taskId":"23627669","properties":[{"id":"comment","value":"222-222"},{"id":"nCountDays","value"
:"1"}]}, sURL=https://alpha-old.test.region.igov.org.ua/wf/service/form/form-data, mRequestParam={}}):Can't save service-history r
ecord /0)org.igov.io.web.HttpRequester.getInside(254):nStatus=403sURL=https://alpha-old.test.igov.org.ua/wf/service/action/event/u
pdateHistoryEvent_ServicemParam={nID_StatusType=8, sUserTaskName=закрита, sID_Order=0-236276639, nTimeMinutes=-1}osReturn={"code":
"BUSINESS_ERR","message":"Record with nID_Server=0 and nID_Process=23627663 not found!"}
java.lang.Exception: nStatus=403sURL=https://alpha-old.test.igov.org.ua/wf/service/action/event/updateHistoryEvent_ServicemParam={
nID_StatusType=8, sUserTaskName=закрита, sID_Order=0-236276639, nTimeMinutes=-1}osReturn={"code":"BUSINESS_ERR","message":"Record
with nID_Server=0 and nID_Process=23627663 not found!"}
```

**Comment by GrekD** [comment]
в том-то и дело что коммент куда-то девается, а вместо него передает null
это и нужно починить

**Comment by kr110666kai** [comment]
Разбираю логику работы. Столкнулся вот с чем:

система обращается к https://alpha-old.test.igov.org.ua/search?sID_Order=4-236300991

и получает ошибку:
```
2016-07-16_19:21:46.409 | INFO | org.igov.io.web.HttpRequester | http-nio-13100-exec-5 | [getInside]FINISHED! (nStatus=403,sURL=https://alpha-old.test.igov.org.ua/wf/service/action/event/getHistoryEvent_Service,mParam={sID_Order=4-236300991},osReturn={"code":"BUSINESS_ERR","message":"Record with nID_Server=4 and nID_Process=23630099 not found!"})
```

а ордер находиться в  https://alpha-old.test.igov.org.ua/search?sID_Order=0-236300991
(номер сервера)

**Comment by kr110666kai** [comment]
Задача с места сдвинулась, перехват события сохранения комментария по эскалации я сделал.  Осталось сохранить данные, это проще. 
Честно говоря, много времени ушло на понимание взаимосвязи внутри Activiti.

**Comment by kr110666kai** [comment]
Локализовал ошибку, неверный несуществубщий определяется.
Подскажите  **sID_Order** должен указывать на первоначальную заявку? 
т.е. на то что человеку приходит в письме как: 
Вітаємо, ВОЛОДИМИР, Ваша заявка **5-202500092** прийнята!

**Comment by GrekD** [comment]
> Подскажите sID_Order должен указывать на первоначальную заявку? 

верно

**Comment by kr110666kai** [comment]
Сохранение комментария готово.

(проверял на alpha, на alpha-old ошибки с номером сервера)

Проверять так:
1. https://alpha.test.igov.org.ua/service/786/general
	подаем заявку, область - Киев, город - Киев (только эти населенные пункты надо выбирать - на других не сработает)
2. запускаем запрос:
	https://alpha.test.region.igov.org.ua/wf/service/action/escalation/runEscalationRule?nID=425
3. заходим в дашборд https://alpha.test.region.igov.org.ua
	ПІБ : volont_escalation
	Логін : volont_escalation
3.1. Берем єскалацию в работу
3.2. Вносим комментарий в поле: Коментар за результатми контакту з адміністративним органом *
3.3. Жмем опрацювати.

Замечание:
Я просто добавил сохранение комментария, поэтому в итоге комментарий в исходную заявку добавляется два раза:

- первый раз тот что я сделал, но уже с нужным комментарием.
- второй раз как null (как программа работала и раньше)

Пример: https://alpha.test.igov.org.ua/search?sID_Order=5-203050012


Кстати при подаче заявки на alpha есть неточность в номере сервера.

Это отображается на сайте, сразу после подачи заявки (номер сервера **0** неправильный):
Шановний(-а) ВОЛОДИМИР ВОЛОДИМИРОВИЧ!
Ваше звернення **0-203050012** успішно зареєстровано
(номер також відправлено Вам електронною поштою на Ваш e-mail kutz12@mail.ru) Результати будуть спрямовані також на email.
Звертаємо увагу, що Іноді листи потрапляють у спам або у розділ "Реклама" (для Gmail).


Это отображается в письме (номер сервера **5** правильный):
Вітаємо, ВОЛОДИМИР, Ваша заявка **5-203050012** прийнята!
Ви завжди зможете переглянути її поточний статус у розділі "Мій журнал". Також на кожному етапі Ви будете отримувати email-повідомлення.
У разі необхідності Ви можете спрямувати питання та пропозиції скориставшись формою за посиланням

**Comment by kr110666kai** [comment]
C alpha-old тоже понятно,
Заявки поданные здесь https://alpha-old.test.igov.org.ua/service/786/general
Уходят на https://alpha.test.region.igov.org.ua.

**Comment by kr110666kai** [comment]
Повторное сохранение с нулевым комментарием убрал, сохраняется только новый вариант.

**Comment by kr110666kai** [comment]
Смотрю, теперь запуск https://alpha.test.region.igov.org.ua/wf/service/action/escalation/runEscalationRule?nID=425
плодит в исходной заявке сообщения типа:
 Ваша заявка №4-203550017 змiнила свiй статус на опрацювання звернення

а в https://alpha.test.region.igov.org.ua/ уже нет эскалаций по этой заявке.
может так и должно быть?

**Comment by GrekD** [comment]
нет, не должно
получается просто не сгенерилась эскалация, будем разбираться с Владимиром

**Comment by GrekD** [comment]
вроде работают эскалации, и коммент передается корректно.
подскажите, пожалуйста, вот эта стандартная фраза или ее можно изменить?:
Відповідь/коментар робітника по заяві 5-203814721

потому что тут комментарий будет вносить не робітник

**Comment by kr110666kai** [comment]
Фраза тут прописывается https://github.com/e-government-ua/i/blob/test/wf-central/src/main/java/org/igov/service/business/subject/SubjectMessageService.java

**Comment by GrekD** [comment]
@kr110666kai 
Александр, можете, пожалуйста, перенести правки по этой таске в ветку мастер?

**Comment by kr110666kai** [comment]
правки в мастер перенес

**Comment by OlgaTurenko** [comment]
задваивается комментарий волонтера в истории "Мой журнал"пример:
https://alpha.test.igov.org.ua/search?sID_Order=5-213701349.
Александр, гляньте, пожалуйста, по свободе. Будем очень благодарны.

**Comment by OlgaTurenko** [comment]
![img_14092016_175828](https://cloud.githubusercontent.com/assets/10909557/18518491/eb3aff88-7aa8-11e6-9578-100861bb52f0.png)
![img_14092016_175837](https://cloud.githubusercontent.com/assets/10909557/18518492/eb3ba438-7aa8-11e6-9eba-45a35aeb3719.png)

**Comment by kr110666kai** [comment]
Завтра гляну

**Comment by kr110666kai** [comment]
по пути исправил сохранение истории.
https://alpha.test.igov.org.ua/search?sID_Order=5-214626463
Какой оставляем комментарий, тот что идет до 
```
Ваша заявка №5-214626463 змiнила свiй статус на опрацювання волонтером
```

**Comment by GrekD** [comment]
это задвоился один и тот же - по времени видно
оставляем тот, который идет выше чем 
Ваша заявка №5-214626463 змiнила свiй статус на опрацювання волонтером

**Comment by kr110666kai** [comment]
Странная ошибка вылезла при запуске:
https://alpha.test.region.igov.org.ua/wf/service/action/escalation/runEscalationRule?nID=425
```
{"code":"SYSTEM_ERR","message":"Transaction rolled back because it has been marked as rollback-only"}
```

**Comment by GrekD** [comment]
Такое бывает иногда.
надо каждый раз "свежую" заявку подавать и на нее запрос запускать, и обязательно Киев-Киев

**Comment by kr110666kai** [comment]
Проверить пока не удается, при выборе задания на https://alpha.test.region.igov.org.ua выскакивает ошибка (на тек.момент только №214728978 без ошибки)
В логе пишет:
```
Caused by: org.activiti.engine.impl.javax.el.PropertyNotFoundException: Cannot resolve identifier 'bankIdlastName'
```

**Comment by kr110666kai** [comment]
Проверил на:
https://alpha.test.igov.org.ua/search?sID_Order=5-214626463
16.09.2016 16:57 ......

На новых не могу, ошибка при выборе на https://alpha.test.region.igov.org.ua

**Comment by kr110666kai** [comment]
На новых тоже работает https://alpha.test.igov.org.ua/search?sID_Order=5-216825016

**Comment by GrekD** [comment]
https://alpha.test.igov.org.ua/search?sID_Order=5-217200013
задвоение

**Comment by kr110666kai** [comment]
Поправил, проверте пожалуйста
https://alpha.test.igov.org.ua/search?sID_Order=5-217200013

**Comment by GrekD** [comment]
да, все ок - подтверждаю
