### ISSUE TITLE
Починить получение слотов по очередям после закрытия окна с предупреждением

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1298]
При заказе услуги с очередями с разбивкой по департаментам в случае, когда один гражданин выбрал департамент, идет запрос на сервер по получению слотов по департаменту и после гражданин выбирает слот в департаменте. И если этот же слот в этом департаменте выбирает другой гражданин, то у второго появляется предупреждающее окно, что слот занят (это нормально). Но при закрытии этого окна с клиента на сервер идет запрос по получению слотов, но не сетится при вызове департамент... итог - тянуться слоты по всем департаментам, а не по тому, который выбрал гражданин. 

Посмотреть это можно так:
в 2-х разных браузерах попробовать начать заказывать одну и туже услугу с одинаковыми параметрами. К примеру эту: 
https://beta-old.test.igov.org.ua/service/184/general , город Днепропетровск. 
Выбираем на форме в поле: "Оберіть відповідальний підрозділ або ЦНАП району (міста), до якого належить нове місце реєстрації дитини" район, видим, что подтянулись по нему слоты (время, на когда можно записаться). Это вызвался сервис /getFlowSlots_ServiceData с параметром nID_SubjectOrganDepartment, куда передали ид пидроздилу)
Саму услугу можно не заказывать. После выбора пидроздила выбираем под одним пользователем определенное время (тем самым бронь установится), затем под другим это же время (ошибку увидим), закрываем ошибку и после пойдет сново вызов сервиса на получение слотов /getFlowSlots_ServiceData но уже не передается nID_SubjectOrganDepartment. Это нужно починить. Департамент должен передаваться!!! Иначе сейчас возвращается от сервера ошибка.

**Comment by Koffeek** [comment]
Проверка на https://alpha-old.test.igov.org.ua/service/29/general/place/built-in/region/1/city/1 показало что всё работает согласно заданию
