### ISSUE TITLE
Реализовать новый интерфейс каталога услуг

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1299]
На основании реализации сервисов: https://github.com/e-government-ua/i/issues/1289
И мокапов: https://docs.google.com/presentation/d/1eo2twV8cug8rhVIh-lYKC6em7HrRL5TJb9F3Ya4TLFA/edit#slide=id.g122c151cca_0_19
И рисунков высокого разрешения: https://www.dropbox.com/sh/um43i0g3buil0h4/AABp6ogTqbPB8ikbcQUQplAra?dl=0

реалиовать:

**ВАЖНО: делать это с другими контроллерами и вьюхами, чтоб легко можно было переключиться на старое отображение!!!**

- [x] 1) Новый вид основной страницы:
![image](https://cloud.githubusercontent.com/assets/4208821/16545702/9044d15e-413b-11e6-8d7e-f9fadc156a44.png)
В частности:
- [x] новый набор пунктов основного меню ("Послуги", "Мій журнал", "Про проект")
- [x] закладки "Послуги громодянам", "Послуги Бізнесу"
(За державними органами - пока не нужно)
- [x] при переходе на каждую вкладку передавать в параметр nID_Category сервиса  
отображать каталог на основе данных сервиса /getCatalogTreeTag, передавая туда в nID_Category, соответствующие номера 1 (бизнес) или 2 (гражданам)
- [x] отображать каталог в виде таблички из трех колонок, построчно
- [x] отображать иконки в тэге img, указывая в src то что приходит в параметре sSubPathFileImage, корневого тега (не отображать иконку, если параметр пуст, но резервировать место под иконку такого-же размера)
- [x] при клике на "Корневой тег"(первый пункт каждого блока) - подгружать отображать диалог из п.2(на основе сервиса /getCatalogTreeTagService), передавая туда nID_ServiceTag, на который кликнули а так-же nID_Category и параметр sRoot=true
- [x] при клике на "Обычный тег"(НЕ первый пункт каждого блока) - подгружать отображать диалог из п.3(на основе сервиса /getCatalogTreeTagService), передавая туда nID_ServiceTag, на который кликнули а так-же nID_Category и параметр sRoot=false
- [x] новый вид поиска (так-же как и сейчас, передавать в параметр sFind то что введено в поиске, для новых двух сервисов: /getCatalogTreeTag и  /getCatalogTreeTagService)

- [x] 2) Вид диалога "Корневого тега":
![image](https://cloud.githubusercontent.com/assets/4208821/16545938/ccefc9e6-4141-11e6-8ce3-cd6370291f87.png)
В частности:
- [x] Подгружать список тэгов и услуг на основе сервиса /getCatalogTreeTagService, передавая туда в nID_Category, соответствующие номера 1 (бизнес) или 2 (гражданам), в зависимости от выбранной вкладки, nID_ServiceTag с номером тега и bRoot=true.
- [x] При работе с "Послуги громодянам" отображать вверху "Оберіть Вашу життєву ситуацію" а  при "Послуги Бізнесу" - "Оберіть Ваш розділ".
- [x] Ниже отображать перечень "Обычных тегов" в одну колонку (в полученных с сервиса данных, элемента aServiceTag_Child), при клике на пункты которых - подгружать отображать диалог из п.3(на основе сервиса /getCatalogTreeTagService), передавая туда nID_ServiceTag, на который кликнули а так-же nID_Category и параметр sRoot=false
- [x] Еще ниже отображать перечень услуг в три колонки (в полученных с сервиса данных, элемента aService), при клике на пункты которых переходить в стандартный диалог "Профиля услуги"
- [x] Вверху отображать "хлебные крошки", с "Головна" и текущий "Корневой тег", при клике на "Головна" будет происходить переход в соотв. диалог п.1

- [x] 3) Вид диалога "Обычного тега":
![image](https://cloud.githubusercontent.com/assets/4208821/16545982/da2d53d8-4143-11e6-8b71-38c5176dc735.png)
В частности:
- [x] подгружать список услуг на основе сервиса /getCatalogTreeTagService, передавая туда в nID_Category, соответствующие номера 1 (бизнес) или 2 (гражданам), в зависимости от выбранной вкладки, nID_ServiceTag с номером тега и bRoot=false.
- [x] в основном поле отображать HTML-контент из поля sNote (объекта, полученного с сервиса)
- [x] в блоке(справа) "Связанные услуги" отображать перечень услуг в одну колонку (в полученных с сервиса данных, элемента aService), при клике на пункты которых переходить в стандартный диалог "Профиля услуги"
- [x] Вверху отображать "хлебные крошки", начиная с "Головна", далее "Корневой тег" и в конце "Обычный тег", при клике на которые ("Головна" и "Корневой тег") будет происходить переход в соответствующие диалоги п.1 или п.2.
- [x] в самом конце прикрутить стандартный компонент Hyper Comments

- [x] 4) Новый вид закладки "Про проект":
![image](https://cloud.githubusercontent.com/assets/4208821/16547600/8dbb244c-417c-11e6-9d35-e66d452a63c3.png)
В частности:
- [x] Фото брать из соцсети (желательно ссылкой), а если фото нет ставить универсальную "заглушку
- [x] Списки людей с их характеристиками и ссылками хранить в отдельном массиве JSON, у которого обязательно должно быть поле sGroup, в котором должен задаваться тип, на основе которого и будет происходить распределение в нужный список и название группы sGroupName. 

например:
var aVolonteur = [
{"sGroup":"central", "sFIO":"Білявцев Володимир", "sURL":"https://", "sCity":"м.Дніпро"}
, {"sGroup":"region-vinnitsa", "sFIO":"Швайко Олег", "sURL":"https://", "sCity":"м.Винниця"}
....
]

var aVolonteurGroup = [
{"sGroup":"central", "sGroupName":"", "sID_Place":""}
, {"region-vinnitsa", "sGroupName":"м.Винниця", "sID_Place":"00460000"}
, {"region-dnepr", "sGroupName":"м.Дніпро", "sID_Place":"008600001"}
....
]

- [x] Так-же, как и в прошлом разделе там должен находиться блок с экспортом отчета.

**Comment by antonlegkiy** [comment]
https://docs.google.com/document/d/1WHhohpcbpOYS5QRIUOfEPevFcVtssjFlxVI8bpVjxQ8/edit
