### ISSUE TITLE
Исправить фиксация статуса закрываемости заявки

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1304]
Описание кейса с проблеммой:
https://docs.google.com/document/d/1ZVKe1sAB2mhuQPq1KEudV3j7JDW1vjX83544kHWrOEM/edit

услуга:
https://alpha.test.igov.org.ua/service/344/general/place/built-in/region/0/city/0

Вся логика, которая при добавлении/апдейте/удалении заявки выполняет производные действия (например обновляет информацию в истории или порождает процесс эскалации), находится в классе: org.igov.service.controller.interceptor.RequestProcessingInterceptor

в частности при определении кейса и вызываются методы обновления истории по заявке:
saveNewTaskInfo
saveUpdatedTaskInfo
saveClosedTaskInfo

**Comment by ASkosyr** [comment]
Задачку подправил.
Ждем теперь тестирования от БА

**Comment by GrekD** [comment]
задача выполнена в полном объеме, все теперь работает корректно
