### ISSUE TITLE
Интегрировать Sender для онлайн-помощи на центральном портале

### ISSUE THREAD

**Issue by lem8r** [e-government-ua/i#1305]
- [x] Использовать виджет Sender'а на центральном портале для предоставления возможности фидбека пользователя на любой странице портала одним кликом.
- [x] При этом нужно собрать как можно больше информации о пользователе и его действиях на сайте(ФИО, телефон, почта)
- [x] Передавать nID пользователя в процесс на корзоиде.
- [x] Передавать URL в процесс на корзоиде.
- [x] Передавать метку времени обращения с точностью до мс.
- [ ] Передавать в процесс скриншот поточной страницы.
- [x] Разработать робот для обработки входящих заявок от пользователей портала с возможностью постить всю информацию на внешний сервис.
- [ ] Перенести настройки виджета в файл конфигурации. (company id, app secret)

**Comment by lem8r** [comment]
Создал ветку central-js_sender_integration для проверки концепта использования сэндера для онлайн-помощника/фидбека.

При инициализации виджета можно передавать информацию о пользователе, чтоб диалог велся не анонимно.

На данный момент создается анонимный виджет при заходе на портал. При этом в чат автоматом передается url на которой находится пользователь при начале диалога.

Если пользователь авторизировался на сайте, то виджет перезапускается с информацией о пользователе: ФИО, телефон, почта, идентификатор(инн), url.

До настройки роботов и форм для чата дело не дошло, поэтому пока что используются примитивные боты из моей компании.
При начале диалога выдается форма приветствия. После ввода сообщения выдается ответ бота. 
По завершению диалог можно посмотреть в аналитике диалогов. Там как раз отображается переданная информация о пользователе.
Выглядит примерно так:
Портал
![2016-07-09 21 51 57](https://cloud.githubusercontent.com/assets/5942291/16709664/977e9c46-461f-11e6-9fa3-3499a6cd0bf9.png)
Аналитика диалогов с информацией о пользователе:
![2016-07-09 21 52 45](https://cloud.githubusercontent.com/assets/5942291/16709670/b7cdd64c-461f-11e6-9ea2-e133a47a3998.png)

**Comment by lem8r** [comment]
Прогресс застыл. Уже больше трех недель общаюсь с тех поддержкой сендера/корзоида ....

**Comment by lem8r** [comment]
Наконец-то разобрался с техподдержкой корзоида.
Теперь вся нужная информация с диалога передается в процесс на корзоиде. Оттуда ее можно постить на любой внешний сервис.

**Comment by lem8r** [comment]
Теперь все коммиты переехали на ветку `central-sender`. Старая ветка уже слишком отстала. 
Перед запуском `grunt serve` нужно выполнить `bower install` для установки md5.

**Comment by lem8r** [comment]
Разобрался как делать скриншот сайта, теперь вопрос как передать данные в диалог. Обратился в саппорт сендера..

**Comment by lem8r** [comment]
Саппорт сендера больше месяца "решает мой вопрос"... Здесь мои полномочия все)

**Comment by OlgaTurenko** [comment]
добрый день! подскажите, пожалуйста, так вопрос на стороне Сендера и не удалось решить?

**Comment by lem8r** [comment]
Добрый день.
Мне с саппорта так и не ответили ничего.
Я ковырялся в js-исходниках сендера и по-моему там нет такого функционала, чтоб можно было со стороны браузера клиента втихаря отправлять информацию на сервер сендера.

Разве что юзер сам может прикрепить любой файл в диалог, но это не то что нужно.

**Comment by OlgaTurenko** [comment]
согласна, что не очень удобно. но все равно спасибо Вам большое за приложенные усилия!
