### ISSUE TITLE
В анкете постановки нового транспортного средства на учет поле для файлов внизу, которое говорит что может ZIP ругается что формат только JPG, PNG и PDF

### ISSUE THREAD

**Issue by YuriyBit** [e-government-ua/i#1309]
Неплохо-бы сделать 3 поля для файлов или мультигрузилку (там 3 документа обычно).
![postanovka_na_uchet](https://cloud.githubusercontent.com/assets/12912658/16902752/cb37bdd6-4c70-11e6-9f98-42f695987fe8.JPG)

**Comment by bvv4ik** [comment]
в ПДФ-е прекрасно размещаются все три страницы... "мультигрузилка тут не подходит", т.к. все это должно быть одним документом, на который в теории(в перспективе) может быть наложено ЭЦП

и просьба не создавать ишью в репозитории для разработчиков

для этого есть iForum, там бмзнесаналитики могут на это обратить внимание, а тут только спам
