### ISSUE TITLE
Подобрать key-value хранилище

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#131]
Подобрать key-value хранилище, что-то вроде riak или может даже MongoDB, для централизованного хранения документов и файлов, которым будут пользоваться все областные сервера! 

Главные критерии: бесплатная, простая в установке и обслуживании, не экзотическая(чтоб была достаточная среда юзателей в мире), быстрая.(желательно с уже встроенной системой резервирования и архивирования)

**Comment by shvaykovski** [comment]
MongoDB + GridFS?

**Comment by bvv4ik** [comment]
а есть какая-то аналитика по ним, личный опыт, может?
нужны подробности

**Comment by vbolshutkin** [comment]
По опыту, MongoDB весьма удобна в использовании и предоставляет гораздо больше, чем просто key-value storage, но GridFS оказался примерно в 3 раза медленнее обычной сетевой файловой системы (NFS, GlusterFS). Однако NFS не масштабируется, да и увеличение размера GlusterFS тоже совсем просто делается.

Riac не щупал, но мне нравится, что у него REST API

**Comment by dutchakdev** [comment]
Имхо MongoDB + GridFS отличное решение. За счет простоты масштабирования и конфигурации в целом. Только вот монга это не совсем кейвелью. Это документо ориентированная бд. Но это не важно.

**Comment by bvv4ik** [comment]
байтаррэй-же там нормально можно хранить?
и ограничения по размеру каждого файла какие?

**Comment by alegast** [comment]
Обмежень монги(дефолтних) 16мб на документ в gridfs не має. Тут актульне питання наскільки добре gridfs горизонтально масштабуеться /  можна партиціонувати. У кого є реальний досвід ? 

З монгою в цьому плані все добре а от файли хз.

**Comment by dutchakdev** [comment]
@bvv4ik вроде как можно но зачем? хранить какие-то состояния? А в целом ограничений реально нет. У меня опыт не большой так как только пишу проект на ней, но в целом нравится доступность информации по многим вопросам. ранее использовал gridfs для большого хранилища видео.

Масштабируется очень легко и наглядно можно посмотреть в статьи http://habrahabr.ru/post/217393/ на практике где-то так все и есть.

**Comment by bvv4ik** [comment]
я имел в виду - нет-ли случаянно там ограничений) мало-ли, в связи с бесплатностью не более "такого-то размера"...

За инфу статью спасибо, сейчас почитаю.

У кого будет что противопоставить/пополнить коллегу, прошу...

**Comment by dutchakdev** [comment]
Нет, нету, она полностью бесплатная, ограничений нет.

**Comment by ivankravchenko** [comment]
`mongo` може бути найбільш влучним рішенням для суспільного проекта через її найбільшу популярність та універсальність.
Щось "серйозніше", типу Cassandra і тому подібне — чудово, але підійме поріг входження для нових девелоперів.

**Comment by alekseymykhailov** [comment]
почему бы не хранить файлы на s3 ? А в базе (postgres , которая уже используется ) просто "описывать" доступ к этим файлам

**Comment by bvv4ik** [comment]
в базе и так будем описывать доступ,
но S# - это Амазон, на который совсем не хочется завязываться... В то время как Манго можно будет переместить куда угодно

**Comment by denden76** [comment]
Добро дня коллеги. для выбора хранидища надо ответить на несколько вопросов. 
1 - есть операции удаления?
2 - размер хранилища? нужно ли линейное маштабирование
3 - вторичные индексы? полнотекстовый поиск?
есть опыт работы с монгой, риаком, хадупом( HBASE, мап редус), ну всяком мелочевкой.
4 - будет ли миграция с облака амазон? ( у них есть в принципе свои хранилища и при прочих равных стоимость будет дешевле чем поднимать все на инстансах)

**Comment by bvv4ik** [comment]
1. да
2.потенциально достаточно большое (терабайты), для начала и 5-10-гигов хватит Что значит "линейное масштабирование"?
3.не нужно, т.к. доступ будет исключительно по ключу, который будет храниться в другой базе
Больше всего присматриваюсь к Манго
4.скорей всего будет! но когда - не известно... Почему не хотелось на Амазон, т.к. потом придется в сотнях серверов переписывать методы-обертки обращений... А если-б Манго, то только адрес сервака в контексте.

**Comment by vbolshutkin** [comment]
У Монго на самом деле есть только один значимый для меня недостаток - в "сотню серверов" нужно тянуть лишнюю зависимость - монго драйвер. Я бы предложил попробовать Riak или сделать фасад с похожим простым REST интерфейсом и внутри и инкапуслировать хранение в Монговском GridFs или на S3 (для начала).

Насколько я понимаю, ключи будут уникальные, поэтому проблем экземпляры фасадов при необходимости будут масштабироваться без проблем с конкурентными изменениями и.т.п. Если вы решите пойти по такому пути, то я готов взяться за этот фасад.

**Comment by denden76** [comment]
мне тоже нравиться риак, только есть одно и существенное но. Риак меньше чем пять нод в продакшине крутить нельзя, а все это в итоге может крутиться на каком-то подстольном железе - типа старого целерона...Драйвер это недостаток?

**Comment by vbolshutkin** [comment]
Как по мне - недостаток, хоть и небольшой. Во-первых, принципиальная невозможность доступа с клиентского джаваскрипта (тоже небольшая проблема, просто файлы будут проксироваться порталами). Во-вторых - слезть с монго просто так не получится - придётся менять "сотни серверов". Ну и просто - чем меньше зависимостей - тем лучше. Но принципиально, я не против монги.

**Comment by bvv4ik** [comment]
Коллеги, а что скажете по поводу Apache Cassandra?

**Comment by denixx** [comment]
28 Апр 2015 г. 18:11 пользователь "Vladimir Bolshutkin" <
notifications@github.com> написал:
>
> Как по мне - недостаток, хоть и небольшой. Во-первых, принципиальная
невозможность доступа с клиентского джаваскрипта (тоже небольшая проблема,
просто файлы будут проксироваться порталами).

Ходить в базу с клиента? Может всё же не стоит? Авторизация, там, и всё
такое на стороне сервиса спасут мир.

**Comment by bvv4ik** [comment]
вообщем Apache Cassandra ни кто не знает...

**Comment by dr1v3** [comment]
Я про такое даже не слышал.

**Comment by zora-borys** [comment]
я за MongoDB, але не проти Cassandra

2015-04-28 18:43 GMT+03:00 bvv4ik <notifications@github.com>:

**Comment by trntv** [comment]
> Коллеги, а что скажете по поводу Apache Cassandra?
А Cassandra разве файлы умеет хранить?

**Comment by ivankravchenko** [comment]
http://stackoverflow.com/questions/8842837/is-cassandra-good-for-storing-files

Ще доволі хороша штука — [Ceph](http://ceph.com). Питання може виникнути тільки в адмініструванні, потрібні спеціалісти.

**Comment by ivankravchenko** [comment]
До Ceph: окрім усього іншого, це і POSIX-сумісна файлова система, тож HTTP доступ робиться будь-яким вебсервером.
Доступ до файлів (об’єктів) як по ефективним API, так і "напряму", як до локальних файлів.
Scalability тут ніби на найвищому рівні.

**Comment by denden76** [comment]
Коллеги, смотрите монго не подходит по определению - она не  key-value. Касандра неплохой выбор, но нужно мимнимум 2 ноды + я бы глянул на http://www.aerospike.com/russian/ 
Из плюсов - хранение большоего объема в value. Из минусов, кросс-датацентр репликация везде платная.

**Comment by denden76** [comment]
И в первом и во втором варианте - полный набор клиентов + документация.

**Comment by zora-borys** [comment]
Початковий меседж був:
*Подобрать* *key-value* *хранилище*, что-то вроде riak или может даже
MongoDB, *для централизованного хранения документов и файлов.*
Для цих речей монго підходить добре.


2015-04-29 10:39 GMT+03:00 denden76 <notifications@github.com>:

**Comment by zora-borys** [comment]
а якщо документи пишуться раз а читаються безліч, то тоді взагалі hadoop

2015-04-29 10:50 GMT+03:00 Borys Zora <zora.borys@javatar.com.ua>:

**Comment by bvv4ik** [comment]
denden76 commented 9 minutes ago
"Коллеги, смотрите монго не подходит по определению - она не key-value. "

Так для того к ней и предлагалось импользовать "приблуду" - GridFS
(и пока ни кто конструктивно не смог опровергнуть наибольшее предпочтение именно к этому "наборчику")


versus197 [8:08 PM] 
кассандра скорее для больших и медленных данных
нам же надо быстрое


по поводу ответа:
versus197 [8:08 PM]
кластер редисов или кластер эластиксерч если надо поиск
последний редис в кластеры собирается норм

Уточняющий "вопрос в студию",:
не уверен, что редис справится с такими обьемами... кроме того а можно редис-у задавать для одного контента безлимитный срок жизни а для других - лимитированный?"

**Comment by PavelKorchagin** [comment]
Коллеги, предлагаю сформировать требования к хранилищу а потом подбирать его.
1. Размер файла 
2. ~ Кол-во запросов на инсерт 
3. ~ Кол-во запросов на апдейт
4. ~ Кол-во запросов на read
5.  2I Yes/No
6. devops support time 
7. etc.
Что забыл добавляйте. Таблицу сделаем сравнительную

**Comment by zora-borys** [comment]
для якогось дерважного проекту в Бразилії запросили комітерів apache
servicemix & camel & cxf
на javaOne 2013 році вони зробили доповідь по стеку техноголій і підходах.
вони вибрали базу Cassandra, на моє запитання чому не MongoDB - чувак
відповів,
що і MongoDB підійшла б, але для тестування піднімать Cassandra легше.

P.S.
до цього була система на майкрософтовських технологіях і не витримала
навантаження

2015-04-29 10:56 GMT+03:00 bvv4ik <notifications@github.com>:

**Comment by bvv4ik** [comment]
по этим критериям нам подойдет абсолютно любое хранилище.
базовые требования в самой задаче были уже описаны

**Comment by denden76** [comment]
8 - где и как будет эксплуатироваться :)

**Comment by dutchakdev** [comment]
@zora-borys странно, монго поднимается очень легко.

**Comment by stormsw** [comment]
Для американцев сму хранения и анализа судебных решений запили на хадуп.

**Comment by nakolkin** [comment]
Мои американцы тоже любят Hadoop и Hive

**Comment by levonet** [comment]
Посмотрите на [Elliptics](http://reverbrain.com/elliptics/), простое, тупое key-value хранилище, используется не только в Яндексе и Coub, с очень активным комьюнити.

Из преимуществ:

  - безграничная масштабируемость
  - распределённость (без использования master-нод)
  - высокая надёжность и отказоустойчивость (это была цель создания этого хранилища)

Из недостатков:

  - весь цикл по установке и поддержке ложиться на админов, так как никто не предоставляет Elliptics как сервис

**Comment by barif** [comment]
Если выбирать простое key-value, то я бы выбрал Redis, хорошо зарекомендовавшая себя технология. MongoDB хорошо подходит для хранения метаданных, у которых может быть очень разная структура. 

Вообще для этих целей очень хорошо подходит Hadoop, там будет возможность еще и искать по всем этим документам, но у меня большие сомнения по поводу разворачивания и поддержки этой системы.

Как вариант можно воспользоваться Cassandra, порог вхождения ниже чем у Hadoop, но позволит построить большую систему.

**Comment by alekseymykhailov** [comment]
>Вообще для этих целей очень хорошо подходит Hadoop

@barif  вы имеете ввиду просто хранить в HDFS или использовать HBASE

>но у меня большие сомнения по поводу разворачивания и поддержки этой системы.

там ничего сверхсложного нет 
проблемы могут возникать при больших нагрузках (впрочем как и везде) , но несколько ТБ для HDFS/HBASE проблемой не будет. Если там будет около сотни ТБ то уже возникают серъезные требования к сети и железу...

ну и есть еще момент : раньше у HDFS была единая точка отказа - одна нода для метаданных у которой не существовало стендбая (https://www.youtube.com/watch?v=hEqQMLSXQlY) , но сейчас эта проблема кажется уже решена.. Но всё же процесс который хранит метаданные не масштабируется горизонтально, т.е. c увелечением объема данных , нужно будет увеличивать Xmx для этого процесса (опять же - для десятка ТБ, это не проблема)

ну и еще для старта hadoop есть одна неприятная зависимость - это ZooKeeper

и думаю на чальном этапе, когда объем данных слишком мал , использовать Hadoop , ИМХО, слишком "жирно" ... :)

**Comment by barif** [comment]
@alekseymykhailov Я имел ввиду HBASE. 

Есть два момента которые следует прояснить:
1. Нужен ли нам Hadoop со старта?
2. Будет ли Hadoop-специалист в проекте.

Относительно второго пункта, я не сомневаюсь что каждый из нас по мануалу поднимет HBASE, и даже настроит. Но это технология которую нужно поддерживать и оперативно решать возникающие рабочие моменты. У нас есть кто этим будет заниматься?

**Comment by alekseymykhailov** [comment]
Если вдруг решим hbase, то у меня есть опыт. Правда с немного устаревшей версией

**Comment by stormsw** [comment]
разворачивать можно докерами. К примеру https://registry.hub.docker.com/u/sequenceiq/hadoop-docker/
Могу запустить зашарить инстанс на азуре. Только hadoop из одной ноды польку не пляшет.

**Comment by denden76** [comment]
Специалист по хадупу есть и это я. И да проблема решена с отказоустойчивостью в name нодах. Но для того чтоб крутить хадуп в продакшн моде нужно( загибаем пальцы) 2 управляющих ноды мимнимум( отказоустойчивость помним?) и три дата ноды - фактор репликации = 3. Плюс Аутентифика́ция постороена на kerberos. Это значит что ява програмисты - без проблем, то остальным придеться поприседать. Плюс днс с обратной зоной...

**Comment by alekseymykhailov** [comment]
@denden76 а ZooKeeper для HBASE?

**Comment by denden76** [comment]
Если коллег так шатает от монги в хадуп, предлагаю все таки s3 для начала. Надо будет валить - поставим Riak CS (Cloud Storage), если количество машин (> 4) не смущает. Там декларируют S3-compatible API and authentication, тоесть если не юзать новых фич от s3 то и код можно будет не переделывать. http://docs.basho.com/riakcs/latest/references/apis/storage/s3/

**Comment by bvv4ik** [comment]
это хорошо, и для нас это означает, что как только нагрузка у нас выростет, или даже просто мы подростем в масштабах - вполне вероятно Хадуп начнем ставить...

Сейчас мы в любом случае решили создавать спринг-фассад, чтоб переезд был максимально легким... Может у кого есть опыт/примеры, и кто-то готов был-бы взяться за реализацию?
Вот задача:
https://github.com/e-government-ua/i/issues/149

**Comment by denden76** [comment]
ZooKeeper для HBASE? кворум можно крутить на датанодах :) да и регионы тоже HBASE, а мастера на наймнодах. 5 машин это мимнимум!!!

**Comment by bvv4ik** [comment]
пока слишком тяжжеловесно... описал выше стратегию, которая вырисовывается..

**Comment by alekseymykhailov** [comment]
@denden76 HBASEу необходим zookeeper все его компоненты хранять конфигурацию кластера в кластере zookeeper. Так что получается немаленькая инсталяция )

кстати для монго тоже требутеся минимум 3 ноды для replica-set (для продакшн)
потом, когда нужно будет масштабировать и начинать испоьзовать sharing нужно будет еще несколько конфиг серверов и каждый shard  будет состоять и з replica-set ... (желательно)

**Comment by bvv4ik** [comment]
ну это-ж опционально, что нам и нужно..

**Comment by bvv4ik** [comment]
Реализована уже MangoDB+GridFS, и даже фассад
