### ISSUE TITLE
Реализовать интерфейс поиска в аналитическом сервере

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1310]
- [x] 1) Справа от поля поиска добавить чекбокс "Архив", который включает режим поиска в архиве аналитического сервера
- [x] 2) при включенном режиме (п.1) - искать данные с помощью сервиса /getProcesses, передавая туда параметр: "sID_" (в нем то что в строке поиска) и asID_Group(с группами в которые входит текущий пользователь, но передавая их на бэке), а из ответа(массива) беря первый элемент.
- [x] 3) ответ выводить в виде див-диалога со скролом, в виде форматированного объекта JSON
- [x] 4) в объекте если есть поле sID_Data, и если оно не пустое, то отрисовывать в нижнем-правом углу кнопку "ЗАГРУЗИТЬ".
- [x] 5) при клике "ЗАГРУЗИТЬ". - вызывать сервис getFile, передавая туда nID_Attribute_File и sLogin (логин текущего пользователя, но передавая их на бэке), а в ответ придет байтовый массив.

**Comment by OlgaTurenko** [comment]
Сервиса (урлы бля беты):
https://beta-old.test.region.igov.org.ua/wf/service/analytic/process/getProcesses?sID_=1

https://beta-old.test.region.igov.org.ua/wf/service/analytic/process/getFile?ID_Attribute_File=1
