### ISSUE TITLE
Добавить поддержку занятия сразу нескольких слотов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1311]
ВАЖНО: вместо "visitDate1" может быть любое другое название!

- [x] 1) Если в форм есть поле с id="nSlots_visitDate1" и при этом есть поле с id="visitDate1" (с type="queueData"), при этом если в nSlots_visitDate1 есть число и оно больше 1, то передавать в запрос:
1) получения расписания(на яве сервис /getFlowSlots_ServiceData) параметр nSlots с передачей туда значения nSlots_visitDate1
2) резервирования слота(на яве сервис /setFlowSlot_ServiceData) параметр nSlots с передачей туда значения nSlots_visitDate1

- [x] 2) Если значение в nSlots_visitDate1 меняется, то обязательно сбравывать содержимое поля id="visitDate1" (загруженный список)

- [x] 3) полей как "visitDate1" может несколько разных одновременно (например visitDate1, visitDate2, visitDate3, test1) и соотв. к ним поля типа nSlots_test1, все так-же должно работать... к каждому полю своя пара...

курирует задачу @kurbpa

**Comment by kurbpa** [comment]
https://alpha.test.igov.org.ua/service/756/general -  ссылка на тестовую услугу на альфе
