### ISSUE TITLE
Реализовать справочник КВЕД-ов с выбором в форме услуги

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1312]
По аналогии с выбором Currency.csv (и другими)

- [x] 1) создать сущность SubjectActionKVED
с полями:
nID - номер-ИД (уникальный-автоитерируемый)
sID - врока-ИД уникальный
sNote - втрока описания

в централе есть уже файл-справочник "SubjectActionKVED.csv"
На альфе и бете (ветки тест и тест-дельта)
структура файла
nID;sID;sNote

примеры строк
1;01.11;Вирощування зернових культур (крім рису), бобових культур і насіння олійних культур
40;05.10;Добування кам'яного вугілля 

В файле :
Есть отдельные одинарные кавычки (апострофы украинского языка)
Нет двойных кавычек
Есть круглые скобки
Есть запятые

- [x] 2) создать сервис /subject/getActionKVED в контроллере субьектов (на централе)
с параметром: sFind
отдающий массив подпадающих под критерии текста, указанного в параметре sFind. среди  кведов (искать по sID и sNote)

- [x] 3) в форме услуги реагировать на наличие поля с id=sID_SubjectActionKVED*
при обнаружении этого элемента - отрисовывать автокомплит на этом поле, где можно вводить части ИД-шек квед-ов(передавать на явe(п.2) в параметр sFind) и названия КВЕД-ов, и должен с низу выводиться список подпавших под критерий(в каждой строке списка вначале sID а потом через пробел sNote)

при выборе в этом поле нужно проставить sID выбранного объекта

все по аналогии с другими такими справочниками
Нужно сделать выбор КВЕД-ов по аналогии с выбором страны. 

Количество таких полей в одном процессе может быть значительным (уже есть 30 на старттаске).

т.е. по сути может быть одновременно:
id=sID_SubjectActionKVED1
id=sID_SubjectActionKVED_2
id=sID_SubjectActionKVED_3
...и т.д.

и каждый из них отдельно можно будет выбрать

ВАЖНО: обязательно сделать это через общий механизм, который для остальных таких справочников с авто-комплитом используется(общие блоки кода там)

**Comment by kr110666kai** [comment]
SubjectActionKVED.csv в формате CP1251 я перекину его в UTF8?

**Comment by agerman-ua** [comment]
Да. Конечно. В остальных csv - UTF8?

**Comment by kr110666kai** [comment]
п. 1 сделал

п. 2 сделал. Пояснения:
Поиск по **sFind** сделал без учета регистра, в любой части текста по принципу
 **(sID LIKE sFind) or ( sNote LIKE sFind)**
Пример
https://alpha.test.igov.org.ua/wf/service/subject/getActionKVED?sFind=рибальство


PS. в ходе работы сделал сначала такой сервис (убирать не стал, вдруг пригодиться)
https://alpha.test.igov.org.ua/wf/service/subject/getActionKVED2?sID=03&sNote=Прісноводне

**Comment by agerman-ua** [comment]
для тестов на альфе
https://alpha.test.igov.org.ua/service/1515/general
