### ISSUE TITLE
Неверность проверки формата .zip при добавлении тех. паспорта при подаче заявки "Перереєстрація транспортного засобу при переобладнанні без зміни ном.агрегатів" 

### ISSUE THREAD

**Issue by Alexandrperiel** [e-government-ua/i#1313]
1) Открыть сайт https://igov.org.ua/
2) Найти послугу "Перереєстрація транспортного засобу при переобладнанні без зміни ном.агрегатів" и нажать на неё
3) Зарегестрироваться под Bank-id
4) Заполнить валидные данные
5) В поле "Копія тех.паспорта:" добавить файл с расширением .zip
     ОР: проверка пропустит файл с данным расширением, т.к. добавлять необходимо 2 файла(лицевую и обратную сторону), так же есть надпись: "при наявності більш ніж однієї копії, файли можуть бути завантажені у вигляді ZIP-архіву"
    ФР: Ошибка: "Недопустимий формат файлу! Повинно бути: jpg,pdf,png!"
![default](https://cloud.githubusercontent.com/assets/20611878/17146777/59310cf2-5368-11e6-881e-1d3388750026.jpg)

**Comment by bvv4ik** [comment]
прошу не создавать ишью в этом репозитории!
есть репозитории: iForum и iTest, для этого
данный репоззиторий только для уже конкретных и отфильтрованных задач разработчикам
