### ISSUE TITLE
Доработать сущность истории, массив которых выдает сервис /getServiceHistoryReport, добавив туда поле sDateCreate (с датой создания заявки, которые не будет меняться при обновлении єтой строки в дальнейшем и и датой закрытия, которая установится только при закрытии заявки)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1315]
1) Новое (22.4.216) - Доработать сервис получения заявок - добавить поля с датой подачи и с датой закрытия заявки (добавив их так-же в саму сущность)

Сущность: HistoryEvent_Service

список:
HistoryEvent_Service.csv

Курирует Дарья

**Comment by lesha1980** [comment]
Добавленные поля пока пустые, поэтому при тестинге получаем csv файл с полями sDateCreate и sDateClosed пустыми в каждой записи. Пример теста https://alpha.test.igov.org.ua/wf/service/action/event/getServiceHistoryReport?sDateAt=2016-02-09%2000:00:00&sDateTo=2016-02-11%2000:00:00

Здесь видим поля sDateCreate, sDateClosed пустыми, так как значения их в таблице null.

**Comment by GrekD** [comment]
@lesha1980 добрый день!
использовала запрос на вгрузку за последние 5 дней:
https://alpha.test.igov.org.ua/wf/service/action/event/getServiceHistoryReport?sDateAt=2016-09-01%2000:00:00&sDateTo=2016-09-05%2000:00:00
sDateCreate - это поле полюбому должно быть заполнено, т.к. если есть другие поля заявки, это значит что есть сама заявка, и у нее по любому есть дата создания (sDateCreate)
sDateClosed - тоже есть заявки которые закрыты:
5-213127490;5;110;;20049;;;закрита;Видача/обмін посвідчення особи моряка;;-1;+380 97 728 2593;1775;;
по ней полюбому должна быть пролита и sDateClosed 

Получается вопрос:

> значения их в таблице null.
почему там null? Должны быть записи

**Comment by lesha1980** [comment]
Данная таска не о заполнении полей sDateCreate, sDateClosed, а лишь об их добавлении в сущность. Заявок без данных полей очень много, так как они уже создавались, поэтому резонно оставить вариант с ограничением, допускающим null в этих полях таблицы. Если поставить ограничение, не допускающее null в этих полях, мы поломаем другие сервисы, которые предполагают работу с сущностью HistoryEvent_Service. Думаю, что будет другая таска, связанная с данным заданием, которая позволит со временем заполнять данные поля и установить ограничение на null.

**Comment by GrekD** [comment]
@OlgaTurenko 
Оля, в этой выгрузке появились поля sDateCreate;sDateClosed
но они пусты.
Леша говорит, что это отдельная задача, чтоб туда что-то передавалось.
Можешь, пожалуйста, поставить эту задачу?

**Comment by OlgaTurenko** [comment]
Даш, можно проверять. Дата старта и дата закрытия будут ставится по новым заказанным или закрытых после выкладки версии процессов. (по-старым пока что этой даты в отчете не будет). Тоесть нужно заказать услугу, отработать ее полностью (убедиться, что в журнале статус проставиться Закрыта) и тогда можно пробовать делать выгрузку в отчет. По этой услуге дата начала и окончания должна быть.

**Comment by GrekD** [comment]
работает на альфе

**Comment by GrekD** [comment]
омега - работает
https://omega.test.igov.org.ua/wf/service/action/event/getServiceHistoryReport?sDateAt=2016-10-01%2000:00:00&sDateTo=2016-10-04%2000:00:00

**Comment by GrekD** [comment]
на боевом **не** работает этот допиленный сервис 
sDateCreate;sDateClose - шапка есть, но данных в этих столбцах нет

**Comment by GrekD** [comment]
сделать sDateCreate и sDateClose параметрами запроса.
так же нужна возможность назначить диапазон:
или
sDateCreateAt - sDateCreateTo
или
sDateCloseAt - sDateCloseTo

**Comment by OlgaTurenko** [comment]
#1398
