### ISSUE TITLE
Реализовать справочник КОАТУУ-ов с выбором в форме услуги

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1316]
По образу и подобию задачи:
https://github.com/e-government-ua/i/issues/1312
только сущность ObjectPlace_UA (вместо SubjectActionKVED)

- [x] 1) создать сущность ObjectPlace_UA
с полями:
nID - номер-ИД (уникальный-автоитерируемый)
sID - строка-ИД уникальный
sName_UA - строка названия на Украинском
nID_PlaceType - номер-ИД связки с типом (сущность PlaceType)

в централе есть уже файл-справочник "ObjectPlace_UA.csv"
На альфе и бете (ветки тест и тест-дельта)
структура файла
nID;sID;sName_UA;nID_PlaceType

примеры строк
1;00008000;Дніпропетровська обл.;1
2;00009000;Запорізька обл.;1

- [x] 2) создать сервис /subject/getObjectPlace_UA в контроллере субьектов (на централе)
с параметром: sFind
отдающий массив подпадающих под критерии текста, указанного в параметре sFind. среди  записей (искать по sID и sName_UA)

- [x] 3) в форме услуги реагировать на наличие поля с id=sID_ObjectPlace_UA*
при обнаружении этого элемента - отрисовывать автокомплит на этом поле, где можно вводить части ИД-шек квед-ов(передавать на явe(п.2) в параметр sFind) и названия КОАТУУ, и должен с низу выводиться список подпавших под критерий(в каждой строке списка вначале sID а потом через пробел sNote)

при выборе в этом поле нужно проставить sID выбранного объекта

все по аналогии с другими такими справочниками
Нужно сделать выбор КОАТУУ-ов по аналогии с выбором страны. 

Количество таких полей в одном процессе может быть значительным (уже есть 30 на старттаске).

т.е. по сути может быть одновременно:
id=sID_ObjectPlace_UA1
id=sID_ObjectPlace_UA_2
id=sID_ObjectPlace_UA_3
...и т.д.

и каждый из них отдельно можно будет выбрать

ВАЖНО: обязательно сделать это через общий механизм, который для остальных таких справочников с авто-комплитом используется(общие блоки кода там)

**Comment by agerman-ua** [comment]
для тестов на альфе
https://alpha.test.igov.org.ua/service/1515/general

**Comment by kr110666kai** [comment]
в централе есть уже файл-справочник "ObjectPlace_UA.csv" - не вижу справочника

**Comment by agerman-ua** [comment]
Сейчас подготовлю.

**Comment by kr110666kai** [comment]
.1 - сделал

п.2 - сделал.
Пояснения по реализации:

- Поиск по sFind сделал без учета регистра, в любой части текста по принципу
(sID LIKE sFind) or ( sName_UA LIKE sFind)
Пример: https://alpha.test.igov.org.ua/wf/service/object/place/getObjectPlace_UA?sFind=дніпр

- ObjectPlace_UA.csv - сделал временный, потом коллега заменит на настроящий

- по заданию: создать сервис /subject/getObjectPlace_UA в контроллере субьектов (на централе)
 наверное, тут неточность

 я сделал сервис:
 **/object/place/**getObjectPlace_UA в **ObjectPlaceController**,

 но если надо перекину как
 **/subject/**getObjectPlace_UA в ObjectPlaceController в **SubjectController**

**Comment by kr110666kai** [comment]
Похоже осталось заполнить: ObjectPlace_UA.csv

**Comment by GFalcon-UA** [comment]
Август, добавь пожалуйста на форму услуги поле с ИД-шником "email". Без этого поля протестировать полноценно не получается (заявка не сабмитится)

**Comment by agerman-ua** [comment]
Добавил. Заявка отправлялась "по факту" но с демонстрацией ошибки.

**Comment by kr110666kai** [comment]
т.е. сервис под новый формат переделать?

**Comment by agerman-ua** [comment]
@kr110666kai 
Пока нет. Владимир не согласовал.

**Comment by kr110666kai** [comment]
ок, я пока KOATUU.xlsx пропарсю на Perl, что бы если что справочник быстренько сделать
