### ISSUE TITLE
Устранить ошибку при порождении БП по отработке эскалаций

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1317]
Происходит в двух кейсах:
- [x] 1) когда группа пользователей формируется с использованием переменых, типа:
`<userTask id="usertask1" name="Обробка звернення бек-офіс (оператор)" activiti:candidateGroups="**dmr_${asStatusSuper}**">

при этом внутренний вызов порождения эскалации:
`https://alpha.test.region.igov.org.ua/wf/service/action/task/start-process/system_escalation?organ=Indirectly_group_Corezoid, Indirectly_dmr_front_office, Indirectly_dmr_supervisorTemp, Indirectly_dnepr_dtek_head, Indirectly_dmr_lawyer, Indirectly_dnepr_gas_${asStatus}, Indirectly_dnepr_gas_head, Indirectly_group_UkrDoc, Indirectly_dmr_${asStatusSuper`

- [x] 2) Если в БП более одной  группы и в группах нет параметров. Пример:

`<userTask id="usertask1" name="Обробка вхідної документації ЦНАП (1-й крок)" activiti:candidateGroups="cnap_lviv_chervonogradT">
`
`<userTask id="usertask3" name="Підготовка відповіді управлінням ЖКГ (2-й крок)" activiti:candidateGroups="chervonograd_mvk1">`

при этом внутренний вызов порождения эскалации:
`https://alpha.test.region.igov.org.ua/wf/service/action/task/start-process/system_escalation?organ=chervonograd_mvk1, cnap_lviv_chervonogradT`

Подробное описание проблемы и тесткейс:
https://docs.google.com/document/d/1_y6tyVCQI_RW27pv1GZ19zFdnkNmPFgFeebzIA5eiBo/edit?pref=2&pli=1

курирует Максим Свидрань

**Comment by taaraora** [comment]
Проблема воспроизводится, когда при создании процесса эскалации в параметре organ передаётся больше двух групп. 
Изначальный код ответа сервера 505 был из-за некорретно формировавшегося url. Эта проблема пофиксил коммитом https://github.com/e-government-ua/i/commit/90a0f0582f1aa158e1722db481a2e9f252aad942.
С корректным URL Activiti пытается стартовать процесс, но падает с ошибкой, невозожности вставить группу в таблицу ACT_ID_GROUP это изначально пофиксил комитом https://github.com/e-government-ua/i/commit/90bf893aa7e5c409941965f5b8d48ea9266d4b9d.
Но это не решило проблему, так как даже если мы передаём в параметре organ всего лишь две гурппы, activiti пытается создать группу с таким _ID. 
Попробовал ограничить количество органов до одного https://github.com/e-government-ua/i/commit/90bf893aa7e5c409941965f5b8d48ea9266d4b9d система отработала коррестно и создала эскалационный процесс.
Сейчас завис на следующих впоросах:

1.  Зачем и **как?** метод `runtimeService.startProcessInstanceByKey(key, variables)` кроме сторинга вириейбла organ пытается заинсертить это в БД?

2. Фикс с ограничением групп до одной работает, но по факту ограничивает функциональность. Насколько я понимаю нужно передавать все группы на которые потенциально могут взять в исполнение таску, даже если получится пофиксить пункт 1, мы будем ограничены размером строки queryparams метода GET.

**Comment by msvidran** [comment]
@taaraora Попробовал - эскалационный процесс породился. Но остались вопросы:

**Comment by taaraora** [comment]
@msvidran Попробуйте пожалуйста протестить создание эскадационного процесса.
