### ISSUE TITLE
Реализовать открытие текста отосланного письма не в отдельном окне а в виде див-диалога

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1319]
В продолжении задачи:
https://github.com/e-government-ua/i/issues/1283

использовать ErrorFactory а в ней тип info или success (из них есть только какой-то один)

**Comment by sergeygorban** [comment]
При нажатии на "Лист" во вкладке "Мой журнал" на https://alpha.test.igov.org.ua возникает ошибка

**Comment by sergeygorban** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/17043142/17869664/f8a2df04-68bc-11e6-9714-8edf02360cc0.png)
