### ISSUE TITLE
написание начальных юнит тестов бизнес-процессов

### ISSUE THREAD

**Issue by maxtmn** [e-government-ua/i#132]
добавлен пакет 
org.activiti.test
для написания юнит тестов процессов
На перво этапе тестируем что схема бп деплоится и что процесс стартует (выполнение бп, проводим до ближайшего выхода из процесса)

**Comment by maxtmn** [comment]
первый тест готов
org.activiti.test.bp.dnepr.mvk_1.Mvk_1_Test

**Comment by zora-borys** [comment]
package: org.activity ?
ми дописуємо open source?
будем висилать патчі туда, щоб вони закомітили це в продукт?

2015-04-29 10:28 GMT+03:00 maxtmn <notifications@github.com>:

**Comment by paul-lysak** [comment]
Ні, просто це такий збочений підход до іменування пакетів

2015-04-29 10:43 GMT+03:00 Zora Borys <notifications@github.com>:
