### ISSUE TITLE
При сохранении поля эскалации о данных исходной заявки сделать это в более удобном для восприятия виде

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1322]
Сейчас при порождении эскалационного процесса, в одном из его полей добавляется информация о исходной заявке... но в неудобном виде (в виде просто обьекта JSON)
А нужно сделать это обычным текстом, где каждая строка будет с новой строки.

должно получиться в итоге что-то типа:

Ответ гражданину: Уважаемый...
ИД таски: 20097560
Логин сотрудника: null
ФИО гражданина: БІЛЯВЦЕВ ВОЛОДИМИР ВОЛОДИМИРОВИЧ
Ссылка: https://alpha.test.region.igov.org.ua/wf/service/action/task/getStartFormData?nID_Task=200975014
Дней: 0
Название: призначення компенсації по догляду за інвалідом I гр., престарілим старше 80 років
Описание: null
ИД правила эскалации: 425
Услуга: Видача довідкок про отримання/неотримання усіх видів державних соціальних допомог
ИД БП (полный): kiev_soc_help_177:16:20080004
Электронный адрес: darja.grek@gmail.com
Прошедшая информация: 0
Район: УПСЗН Бабушкінського району, м. Дніпропетровськ
Название таски: опрацювання звернення
Номер таски: 200975014
ИД процесса: 20097501
Дата БП: 2016-07-06 21:05:01
Прошло дней: 0
Лимит дней: -1
Паспорт: АО295227 БАБУШКИНСКИМ РО В Г ДНЕПРОПЕТРОВСКЕ ГУ ГМС УКРАИНЫ В ДНЕПРОПЕТРОВСКОЙ ОБЛ 17.08.2015
ИНН: 2943209693
Телефон: +380 50 182 7284
ИД таски: 200975014
Прошло часов: 0
ИД БП: kiev_soc_help_177

т.е. и чтоб каждый параметр с новой строки шел((переносы строк добавить)
и чтоб вместо id-шек брались названия полей (а там где конструируется этот объект - есть от куда брать неймы), а там где это не из полей - просто ставились описанные выше названия.

просто найди участок в коде, где генерируется этот объект, который потом сетится в это поле, порождаемой эскалационной заявки...

**Comment by IgorMaksymov** [comment]
вот алгоритм воспроизведения эскалации:
1. https://alpha.test.igov.org.ua/service/786/general
подаем заявку, область - Киев, город - Киев (только эти населенные пункты надо выбирать - на других не сработает)
2. запускаем запрос:
https://alpha.test.region.igov.org.ua/wf/service/action/escalation/runEscalationRule?nID=425
3. заходим в дашборд https://alpha.test.region.igov.org.ua
ПІБ : volont_escalation
Логін : volont_escalation
ищем последнюю

**Comment by OlgaTurenko** [comment]
класс в котором тебе по задаче нужно вносить изменения: org.igov.service.business.action.task.bp.handler.BpServiceHandler
метод, м котором нужно будет вносить изменения: startEscalationProcess
mParam.put("saField", new JSONObject(mTaskParam).toString());
поле, формат которого нужно изменить

**Comment by GrekD** [comment]
ИД правила эскалации: -1
ИД эскалации правила: 425
кажется дублируется  - по названию одно и тоже, а по сущности - разные параметры

nDaysLimit: 0 - передает ИД, а надо нейм

подскажите, пожалуйста, ИД вот этого поля: Автор звернення:
