### ISSUE TITLE
При наличии в форме поля sID_Merchant отображать кнопку "Оплатить" и обеспечит вызов сервиса, при ее нажатии

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1326]
- [x] 1) Для сервиса брать данные

**из полей:**
> sID_Merchant
> sSum
> sID_Currency (если есть)
> sDescription (если есть)
и передавать такими-же параметрами на сервер ноды (в сервис-прослойку)

**+ дополнительно параметры:**
- а) sID_Order передавать значение, состоящее из:
"ИД услуги(nID_Service)"+"_--_"+ИД БП"+"_--_"+"ДАТА+ВРЕМЯ в формате YYYY-MM-DD_hh:mm:ss.nnn"
- б) nID_Server - ИД сервера (из ServiceData)
и так-же передавать параметрами на сервер ноды (в сервис-прослойку)

- [x] 2) на сервере ноды вызывать РЕГИОНАЛЬНЫЙ сервис явы(ХОСТ(sHost)определяется по nID_Server, в коде много примеров): /wf/services/finance/redirectPaymentLiqpay

с такими-же параметрами:

> sID_Merchant
> sSum
> sID_Order
> sDescription (если задан, иначе не передавать)
> sID_Currency (если задан, иначе не передавать)
> nID_Subject (должен автоматом передаваться как и в остальных вызовах сервисов явы с ноды на сервере, из сессии)

- [x] 3) в ответ получить на сервере в виде JSON-объекта:
```
{
"sURL":"https://"
,"data":"1"
,"signature":"2"
}
```
и после этого, открыть на клиенте в новом окне этот УРЛ **sURL**, **методом POST** с передачей в нем этих параметров **data** и **signature**

**ВАЖНО:**
отображать кнопку "Оплатить":
а) вместо поля sID_Merchant
б) только если поле sID_Merchant с типом string (т.е. , например, если там тип invisible, то как не отображали так и не отображаем)

**Comment by kurbpa** [comment]
https://alpha.test.igov.org.ua/service/1532/general - вылил тестовую услугу
