### ISSUE TITLE
Скрывать кнопку на дашборде чиновника "Внести зауваження"

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1330]
После отработки чиновником заявки до обновления заявки остается на заявке активная кнопка "Внести зауваження". Ее необходимо скрывать после отработки заявки чиновником. 

Описание причины почему ее необходимо скрывать: https://docs.google.com/document/d/1Yjtbr8eRJQvk3DMUypNVOyX_L-h0Qh6qcnQEx45t3E8/edit?usp=sharing

**Comment by GFalcon-UA** [comment]
Из приложенного документа:
п.1 - реализовано на дашборде скрытие кнопки "Внести зауваження" если задача отработана;
п.2 - отложено.

**Comment by agerman-ua** [comment]
п.1 на альфе протестировано - всё корректно.
