### ISSUE TITLE
Доработать сервис /downloadTasksData

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1332]
Доработать сервис /downloadTasksData. Если в параметре  saFields передали значение sLoginAssignee или *, то добавлять в отчет еще поле с исполнителем данной задачи. (элемент assignee у обьекта task)

Смотреть класс org.igov.service.controller.ActionTaskCommonController.java. Необходимо в хедер отчета добавить это поле и в строку со значениями также добавить. Достать исполнителя можно из  TaskFormData oTaskFormData = oFormService.getTaskFormData(oTask.getId()); oTaskFormData.getTask().getAssignee();  (смотреть метод fillTheCSVMap в сервисе)

**Comment by agerman-ua** [comment]
https://alpha.test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=dnepr_cnap_560_ur&bHeader=true&sDateAt=2016-04-01&sDateTo=2016-09-01&saFields=${sID_Order};${sDateCreate};${sDateClose};${sClientFIO};&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=create_1492_2016-08-09_2016-08-10.csv

**Comment by agerman-ua** [comment]
Проверено.
Тест (рабочий запрос) работает. На новой альфе.
https://alpha.test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=dnepr_cnap_560_fop&bHeader=true&sDateAt=2016-06-01&sDateTo=2016-09-01&saFields=${};${};${sID_Order};${sDateCreate};${sDateClose};${sClientFIO};${bankIdinn};${phone};${email};${sVarOblNam};${asDecisionMain};${asHaveDecisionFile};${sUniqNum};${fDecisionDoc};${fVarUstDoc};${fVarDod1};${fVarDod2};${sComment};${asDecisionFirst_01};${asDecisionFirst_03};${bankIdlastName};${bankIdfirstName};${bankIdmiddleName};${sLoginAssignee}&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=create_1495_2016-08-18_2016-08-19.csv

**Comment by HSdevelop** [comment]
${sLoginAssignee}

**Comment by OlgaTurenko** [comment]
Август, дай, пожалуйста, ссылочку на тестовом по которой ошибка при загрузке отчета. Чтоб Сергей убедился, что смог починить.

**Comment by agerman-ua** [comment]
https://alpha.test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=_test_ved&bHeader=true&sDateAt=2016-09-01&sDateTo=2016-10-01&saFields=${sID_Order};${sDateCreate};${sDateClose};${sLoginAssignee}&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=test.csv

**Comment by agerman-ua** [comment]
Протестировано на боевом. Работает.
