### ISSUE TITLE
Организовать считку параметров платежей с сфтп и передачу их в таску.

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1337]
Организовать шетдулер, который раз в сутки ночью будет считывать построчечно и парсить файл 11082016.csv (лежит в папке logs) на сфтп (файл будет содержать параметры квитанций, оплаченых гражданами).
Параметры для подключения к сфтп: 
Путь: alpha.test.igov.org.ua
Порт: 22 
Протокол: sftp 
Логин: sftpuser 
Пароль: zaqxswcde

Первая строка в файле - это названия переменных тасок. Следующие строки - значения.

Среди ид-к будет PURPOSE- в значении которого будет вшит ид заявки в виде: sID_Order=ид (закодированная), в которой в значении будет прошита ид-ка таски. Нужно вычленять из текста ид-ку таски sID_Order (начинается после '=' и до последней цифры), по sID_Order  нужно получать ид таски активити и в  переменные этой таски необходимо

 передать все параметры. Таким образом чиновники на форме смогут видеть параметры платежей по квитанциям.

**Comment by ASkosyr** [comment]
Добавил в шедулер.
В ручную можно проверить 

```
https://alpha.test.igov.org.ua/wf/service/test/action/loadPayments
```
