### ISSUE TITLE
Реализовать сервисы-обертки для вызова внешнего сервиса электронных очередей

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1338]
Документация внешнего АПИ:
http://tapi.cherg.net/

Формат объектов: JSON
Авторизация: basic-auth (в хеадере в base64 логин и пароль)
Тестовый сервер: http://tapi.cherg.net
Логин: igov
Пароль: rEYgYC8i

Пример: http://tapi.cherg.net/regions/

- [x] 1) Сервис выбора очереди региона /flow/DMS/getSlots
Параметры:
nID_Service_Private - уникальный строковой-ИД места (составной из "Региона_города_департамента")
nDays - количество дней
Ответ:
Два вложенных массива времен в даты очереди места:
[
aTime:[
{object}
,{object}
]
]
Где вместо {object} обьект с ячейкой очереди

- [x] 2) Сервис резервирования очереди региона /flow/DMS/setSlotHold
Параметры:
nID_Service_Private
sFLowSlotDateTime
sSubjectPhone
sSubjectFamily - фамилия
sSubjectName - имя
sSubjectSurname -  отчество
sSubjectPassport - паспорт
Ответ:
объект с уникальным ИД Тикета, полученного в ответ на запрос

- [x] 3) подтверждение резервации /flow/DMS/setSlot
nID_SlotHold

**Comment by taaraora** [comment]
Таска №1 выполнена но не по описанию.
nID_Service_Private - уникальный id сервиса (целое число) 
nDays - опционально, количество рабочих дней для которых нужно выбрать слоты. Дефлтное значение 7 дней, если засетили большее число то берём всё равно 7.
В ответе для каждой даты содержится массив слотов на этот день.
1) http://tapi.cherg.net/ не показывает реальные рабочие дни даже если использовать /workdays (на день независимости показывал рабочие слоты) **По этому выборка дат рабочих дней основана на скипе субботы и воскресенья, что не всегда корректно**.
Вопрос, нужно ли используя http://tapi.cherg.net/list_reserve получать список резерваций и фильтровать слоты которые выводятся в результате? На данный момент /list_reserve не поддерживает фильтры и выдаёт все резервации по всем регионам по всем организациям по всем сервисам.

**Comment by taaraora** [comment]
URI REST ресурсов были изменены:
1) /getFlowsByPlace -> /getSlots
2) /setFlowsByPlace -> /setSlotHold
3) /confirmFlow -> /setSlot

Флоу использования созданных ресурсов следующий:
1) Вызываем  /getSlots для существующего сервиса (например 428), получаем массивы слотов по датам.
2) вызываем /setSlotHold чтобы создать резервацию слота для конкретного сервиса и дата + время (требует ряд данных о субъекте который записывается на приём), в ответ получаем объект в котором есть время до которого мы должны успеть подтвердить резервацию и пропертю reserve_id, это и есть id нашей резервации слота.
3) вызываем  /setSlot для подтверждения резервации слота.

**Comment by bvv4ik** [comment]
работает)
