### ISSUE TITLE
Реализовать поддержку использования сервисы-обертки для вызова внешнего сервиса электронных очередей

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1339]
На основе ишью:
https://github.com/e-government-ua/i/issues/1338
- [x] 1) так-же как и для стандартных Электронных Очередей (ЭО), только в названии ИД полей справа должно быть префикс "_DMS" (только без департаментов и др. параметров), а ИД Сервиса (nID_Service_Private) брать из одноименного (ИД) поля
- [x] 2) в комбобоксе подгружать список дат, а при выборе даты подгружать список времени (все из п.1. прошлого ишью)
- [x] 3) при выборе слота использовать п.2. прошлого ишью, и нужные поля брать из стандартных полей (ИД), bankIdFamily, email и т.д. (можно подсмотреть в БП), и запоминать ИД резервирования
- [x] 4) при сабмите (перед ним) использовать сервис п.3. для подтверждения резервирования.(передавая запомненный ИД резервирования)
  при неудачи ошибку выводить в див-диалоге, с маркером warning
  "Невозможно зарезервировать время в электронной очереди ДМС"

курирует задачу Павел Курбацкий

Для создания тестового БП:
нужно чтоб было в БП поле nID_Service_Private, которое можно чтоб проставлялось как атрибут... в него нужно передавать ИД сервиса ДМС (для теста можно: 428 )

**ИД сервиса ДМС получить можно таким образом:**
- Вначале получить массив регионов: http://tapi.cherg.net/#path--regions
  http://tapi.cherg.net/regions/
  отдает:

```
{
"status-code": "0",
"status-detail": "0",
"data": [
{
"id": "8000000000",
"name": "М.КИЇВ",
"enabled": true
},
{
"id": "3200000000",
"name": "КИЇВСЬКА",
"enabled": false
},
{
"id": "100000000",
"name": "АР КРИМ",
"enabled": false
},
{
"id": "500000000",
"name": "ВІННИЦЬКА",
"enabled": false
},
{
"id": "700000000",
"name": "ВОЛИНСЬКА",
"enabled": false
},
{
"id": "1200000000",
"name": "ДНІПРОПЕТРОВСЬКА",
"enabled": false
},
{
"id": "1400000000",
"name": "ДОНЕЦЬКА",
"enabled": false
},
{
"id": "1800000000",
"name": "ЖИТОМИРСЬКА",
"enabled": false
},
{
"id": "2100000000",
"name": "ЗАКАРПАТСЬКА",
"enabled": false
},
{
"id": "2300000000",
"name": "ЗАПОРІЗЬКА",
"enabled": false
},
{
"id": "2600000000",
"name": "ІВАНО-ФРАНКІВСЬКА",
"enabled": false
},
{
"id": "3500000000",
"name": "КІРОВОГРАДСЬКА",
"enabled": false
},
{
"id": "4400000000",
"name": "ЛУГАНСЬКА",
"enabled": false
},
{
"id": "4600000000",
"name": "ЛЬВІВСЬКА",
"enabled": false
},
{
"id": "4800000000",
"name": "МИКОЛАЇВСЬКА",
"enabled": false
},
{
"id": "5100000000",
"name": "ОДЕСЬКА",
"enabled": false
},
{
"id": "5300000000",
"name": "ПОЛТАВСЬКА",
"enabled": false
},
{
"id": "5600000000",
"name": "РІВНЕНСЬКА",
"enabled": false
},
{
"id": "5900000000",
"name": "СУМСЬКА",
"enabled": false
},
{
"id": "6100000000",
"name": "ТЕРНОПІЛЬСЬКА",
"enabled": false
},
{
"id": "6300000000",
"name": "ХАРКІВСЬКА",
"enabled": false
},
{
"id": "6500000000",
"name": "ХЕРСОНСЬКА",
"enabled": false
},
{
"id": "6800000000",
"name": "ХМЕЛЬНИЦЬКА",
"enabled": false
},
{
"id": "7100000000",
"name": "ЧЕРКАСЬКА",
"enabled": false
},
{
"id": "7300000000",
"name": "ЧЕРНІВЕЦЬКА",
"enabled": false
},
{
"id": "7400000000",
"name": "ЧЕРНІГІВСЬКА",
"enabled": false
},
{
"id": "8500000000",
"name": "М.СЕВАСТОПОЛЬ",
"enabled": false
}
]
}
```
- Потом по ИД региона получить массив оранизаций: http://tapi.cherg.net/#path--organizations
  http://tapi.cherg.net/organizations?region_id=8000000000 **(методом POST)**
  отдает:

```
{
  "status-code": "0",
  "status-detail": "0",
  "data": [
    {
      "id": "85",
      "name": "Відділ централізованого оформлення документів №2",
      "address": ""
    },
    {
      "id": "74",
      "name": "Голосіївський районний відділ",
      "address": ""
    },
    {
      "id": "75",
      "name": "Дарницький районний відділ",
      "address": ""
    },
    {
      "id": "76",
      "name": "Деснянський районний відділ",
      "address": ""
    },
    {
      "id": "70",
      "name": "Дніпровський районний відділ",
      "address": ""
    },
    {
      "id": "77",
      "name": "Оболонський районний відділ",
      "address": ""
    },
    {
      "id": "78",
      "name": "Печерський районний відділ",
      "address": ""
    },
    {
      "id": "79",
      "name": "Подільський районний відділ",
      "address": ""
    },
    {
      "id": "80",
      "name": "Святошинський районний відділ",
      "address": ""
    },
    {
      "id": "81",
      "name": "Солом’янський районний відділ",
      "address": ""
    },
    {
      "id": "83",
      "name": "Шевченківський районний відділ 1",
      "address": ""
    },
    {
      "id": "86",
      "name": "Шевченківський районний відділ 2",
      "address": ""
    }
  ]
}
```
- Ну и потом по ИД организации ИД сервиса: http://tapi.cherg.net/#path--services
  http://tapi.cherg.net/services?org_id=85

```
{
"status-code": "0",
"status-detail": "0",
"data": [
{
"id": "428",
"name": "Паспорт громадянина України для виїзду за кордон"
}
]
}
```

**Comment by kurbpa** [comment]
тестовая услуга - https://alpha.test.igov.org.ua/service/1539/general

**Comment by GFalcon-UA** [comment]
Можно тестировать, но есть нюансы:
Из стороннего сервиса нам приходят несколько параметров тиккета: 
service_id
ticket_number
ticket_code
...
а в нашем поле queueData можно сохранить только одно числовое значение в переменную nID_FlowSlotTicket. На данный момент пока сохраняю там только ticket_code
===========================
На форме добавил проверки: чтобы поле с выбором времени для слота ДМС стало активным, необходимо выполнение четырех условий:
1. должна быть заполнено поле с фамилией пользователя
2 должно быть заполнено поле с именем пользователя
3 в поле с паспортными данными должен содержаться валидный серия-номер паспорта
4 поле с номером телефона должно быть валидным

**Comment by Koffeek** [comment]
В связи с массовой выдачей ID-карт стоит убрать условие обязательного наличия "серия и номер паспорта в своих соответствующих полях."

**Comment by GFalcon-UA** [comment]
Какие тогда данные передавать в параметре pasport ? http://tapi.cherg.net/#path--set_reserve у них ведь там requred

**Comment by GFalcon-UA** [comment]
Убрал проверку. Если поле bankIdPassport не заполненно - будет посылаться пустая строка

**Comment by OlgaTurenko** [comment]
спасибо, Алексей! прошу проверить работоспособность.

**Comment by julyprodan** [comment]
все хорошо

**Comment by GFalcon-UA** [comment]
Исправил, если приходит ошибка о занятом времени:
1. Исправил содержимое диалогового окна для api.cherg.net
2. Исправил сброс SlotPicker-а для боевого
3. Добавил запрос на повторную загруску списка слотов
