### ISSUE TITLE
Запрет назначать исполнителя по уже взятым в работу таскам

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1348]
В классе интерцепторе проверять, если метод вызываемого сервиса PUT, урл имеет маску  Pattern TAG_PATTERN_PREFIX = Pattern.compile("runtime/tasks/[0-9]+$")  и в теле запроса присутствует параметр "assignee" и значение его не пустая строка или нал (пример такого тела запроса sRequestBody={"assignee":"kermit"}) (тоесть вызывается сервис по назначению исполнителя по таске) , то делать проверку по ид таски а не назначена ли она уже на кого-то (через апи активити с помощью переменной в классе runtimeService, почитать документацию как получить по ид таски ее исполнителя). Если назначена, то выбрасывать исключение с текстом "Task has been already assigneed!".

**Comment by OlgaTurenko** [comment]
Проблема, которая после реализации должна решиться: https://docs.google.com/document/d/1R-lAYyLktSR9RErxaeWC7iRrznCmSQwd_fruodHjv50/edit?usp=sharing

**Comment by agerman-ua** [comment]
Протестировал вчера. Всё работает. Спасибо.
