### ISSUE TITLE
Починить определение группы по эскалационному процессу.

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1350]
Починить определение группы по эскалационному процессу. Описание проблемы со ссылками на процес и запуск по нему эскалации:
https://docs.google.com/document/d/13K_dioIpeOAzwEhcsQRJxA2bpqqKYPcEE7dYOc_zYPY/edit

Также
- [x] 1) Добавить поле с ид поля: sLoginAssigned; название на русском "Логин сотрудника", куда помещать исполнителя по таске.
- [x] 2) Добавить в поле Данные: поле "Количество просроченных дней" (sElapsedDay) которое = (сегодняшняя дата - дата создания заявки - 1)
- [x] 3) Удалить из поля Данные: "Кол-во просроченных дней: -1" (nDueElapsedHours)
- [x] 4) Добавить в форму поля place(Место), куда помещать место, где была услуга заказана. (вызывать сервис на централе по получению по ид процесса объекта Place (сервис /getPlaceByProcess) )
- [x] 5) из поля "данные" так же убрать:
ИД БП (полный): kiev_soc_help_177:17:20123461;  ИД таски активити: 211026815;  ИД таски: 21102740;  Номер таски: 211026815; ИД процесса: 21102681; Ссылка: https://alpha.test.region.igov.org.ua/wf/service/action/task/getStartFormData?nID_Task=211026815
 Прошедшая информация: 0;  Лимит дней: 0
- [x] 6) вынести в отдельное поле: Дата БП (sDate_BP): 2016-08-27 23:36:10
- [x] 7) email - надо из "данных" так же вывести в отдельное поле, потому что будем слать гражаднину еще письмо
- [x] 8) вывести в одельное поле из поля "данные" sTaskName (Имя таски: Перевірка ЦНАП) - если можно то передавать и ИД юзертаски и ее нейм в формате: (UserTask1 - Перевірка ЦНАП)
- [x] 9) не передаются контакты чиновников (поле sEmployeeContacts) на боевом сейчас они передаются а на альфе - нет.
- [x] 10) sElapsedDay так же вынести в отдельное поле
- [x] 11) в эскалационную заявку передавать ссылку на родительскую заявку в поле sURL_OrderHistory, пример возможной ссылки <a href="https://igov.org.ua/search?sID_Order=[nID_Protected]">[nID_Protected]</a>

**Comment by HSdevelop** [comment]
̶2̶)̶ ̶Д̶о̶б̶а̶в̶и̶т̶ь̶ ̶в̶ ̶п̶о̶л̶е̶ ̶Д̶а̶н̶н̶ы̶е̶:̶ ̶п̶о̶л̶е̶ ̶"̶К̶о̶л̶и̶ч̶е̶с̶т̶в̶о̶ ̶п̶р̶о̶с̶р̶о̶ч̶е̶н̶н̶ы̶х̶ ̶д̶н̶е̶й̶"̶ ̶(̶s̶E̶l̶a̶p̶s̶e̶d̶D̶a̶y̶)̶ ̶к̶о̶т̶о̶р̶о̶е̶ ̶=̶ ̶(̶с̶е̶г̶о̶д̶н̶я̶ш̶н̶я̶я̶ ̶д̶а̶т̶а̶ ̶-̶ ̶д̶а̶т̶а̶ ̶с̶о̶з̶д̶а̶н̶и̶я̶ ̶з̶а̶я̶в̶к̶и̶ ̶-̶ ̶1̶)̶
̶3̶)̶ ̶У̶д̶а̶л̶и̶т̶ь̶ ̶и̶з̶ ̶п̶о̶л̶я̶ ̶Д̶а̶н̶н̶ы̶е̶:̶ ̶"̶К̶о̶л̶-̶в̶о̶ ̶п̶р̶о̶с̶р̶о̶ч̶е̶н̶н̶ы̶х̶ ̶д̶н̶е̶й̶:̶ ̶-̶1̶"̶ ̶(̶n̶D̶u̶e̶E̶l̶a̶p̶s̶e̶d̶H̶o̶u̶r̶s̶)̶

**Comment by GrekD** [comment]
![image](https://cloud.githubusercontent.com/assets/10836093/18046667/9f20d0f6-6de1-11e6-9d13-4cdd166c915c.png)
Сережа, посмотрите, пожалуйста: в новом виде в дашборде строчки из поля "данные" опять идут сплошной мешаниной - добавьте плиз перенос строк

**Comment by GrekD** [comment]
из поля "данные" так же убрать:
- [ ] ИД БП (полный): kiev_soc_help_177:17:20123461
- [ ] ИД таски активити: 211026815
- [ ] ИД таски: 21102740
- [ ] Номер таски: 211026815
- [ ] ИД процесса: 21102681 
- [ ] Ссылка: https://alpha.test.region.igov.org.ua/wf/service/action/task/getStartFormData?nID_Task=211026815 
- [ ] Прошедшая информация: 0 
- [ ] Лимит дней: 0

- [ ] вынести в отдельное поле: Дата БП: 2016-08-27 23:36:10

**Comment by HSdevelop** [comment]
из поля "данные" так же убрать:

 ИД БП (полный): kiev_soc_help_177:17:20123461
 ИД таски активити: 211026815
 ИД таски: 21102740
 Номер таски: 211026815
 ИД процесса: 21102681
 Ссылка: https://alpha.test.region.igov.org.ua/wf/service/action/task/getStartFormData?nID_Task=211026815
 Прошедшая информация: 0
 Лимит дней: 0

 вынести в отдельное поле: Дата БП: 2016-08-27 23:36:10

**Comment by HSdevelop** [comment]
из поля "данные" так же убрать:

 ИД БП (полный): kiev_soc_help_177:17:20123461
 ИД таски активити: 211026815
 ИД таски: 21102740
 Номер таски: 211026815
 ИД процесса: 21102681
 Ссылка: https://alpha.test.region.igov.org.ua/wf/service/action/task/getStartFormData?nID_Task=211026815
 Прошедшая информация: 0
 Лимит дней: 0

 вынести в отдельное поле: Дата БП: 2016-08-27 23:36:10

**Выполнил**

**Comment by HSdevelop** [comment]
`
![image](https://cloud.githubusercontent.com/assets/20037226/18109985/aaad3274-6f1d-11e6-9fb3-372569278768.png)
`
Сломался перенос строк на стороне фронт энд'а.

**Comment by HSdevelop** [comment]
![image](https://cloud.githubusercontent.com/assets/20037226/18110029/f1362138-6f1d-11e6-9059-ee87168e4486.png)

**Comment by HSdevelop** [comment]
![2016-08-31_1-49-11](https://cloud.githubusercontent.com/assets/20037226/18110056/23f03668-6f1e-11e6-9f56-85af97474d18.jpg)

На стороне фронт энда проблема

**Comment by GrekD** [comment]
я извиняюсь, что добавляю задания по крохам, но конкретно это родилось после понедельничного совещания:
email - надо из "данных" так же вывести в отдельное поле, потому что будем слать гражаднину еще письмо

**Comment by GrekD** [comment]
задваивается комментарий волонтера в истории "Мой журнал"

**Comment by GrekD** [comment]
- [ ] вывести в одельное поле из поля "данные" sTaskName (Имя таски: Перевірка ЦНАП) - если можно то передавать и ИД юзертаски и ее нейм в формате: (UserTask1 - Перевірка ЦНАП)

**Comment by OlgaTurenko** [comment]
поле email и sTaskName начнем заполнять. Даш, только просьба в самом бп ескалационном его добавить.

**Comment by GrekD** [comment]
добавила, емайл уже Сережа сделал ))
sElapsedDay - вот это из поля "данные" тоже в отдельное попросила его перенести

**Comment by GrekD** [comment]
и еще напомню что не передаются контакты чиновников (поле sEmployeeContacts) на боевом сейчас они передаются а на альфе - нет.

**Comment by GrekD** [comment]
на альфе все работает
