### ISSUE TITLE
Реализовать сервис получения сводной статистики по оказанным услугам за период, с группировкой по плейсам

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1351]
- [x] Делать на основании существующего сервиса получения статистики по услуги (те-же поля получать)
- [x] название сервиса  /getServicesStatistic в том-же контроллере и контексте что и прошлый сервис
- [x] параметры:

> sDateAt // дата "С", обязательный в формате YYYY-MM-DD hh:mm:ss..nnn
> sDateTo // дата "По", обязательный в формате YYYY-MM-DD hh:mm:ss..nnn
- [x] на выходе csv-файл, с полями:

> nID_Service //номер-ИД услуги
> sService //строка-название услуги
> sID_Place_UA //строка-ИД места (берется из поля sID_UA)
> sPlace //строка-название места (берется из поля sID_UA ИД-шник, и по нему ищется в сущности Place название)
> nCountTotal //число оказанных услуг всего
> nRateMiddle //число-средняя оценка 
> nHoursMiddle //число-часов в средням отрабатывалась услуга

Курирует Дарья Грек

**Comment by GrekD** [comment]
на альфе работает

**Comment by OlgaTurenko** [comment]
Даш, а чего удалили лейбл тест? Не работает?

**Comment by GrekD** [comment]
на альфе работало, я убрала лейбл, т.к. таска уже была протестирована.
не надо убирать в таких случаях?

**Comment by GrekD** [comment]
омега - все ок
https://omega.test.igov.org.ua/wf/service/action/event/getServicesStatistic?sDate_from=2016-10-01 00:00:00&sDate_to=2016-10-04 00:00:00

**Comment by GrekD** [comment]
Проверка на боевом показала:
1. в эту выливку не проливаются услуги общеукраинские. Пример такой услуги 1387
2. По самым топовым именно по Днепропетровской области цифры в статистике чуть меньше чем на портале.
диапазон ставила с 1 апреля 2015 года по 10 октября текущего
Проверить можно на услугах:
Звернення громадян до міської ради
Видача/заміна паспорта громадянина для виїзду за кордон
Отримання субсидії на оплату житлово-комунальних послуг
Видача паспорта громадянина для виїзду за кордон для дитини
Надання довідки про притягнення до кримінальної відповідальності, відсутність (наявність) судимості або обмежень, передбачених кримінально-процесуальним законодавством України
