### ISSUE TITLE
Перейти на новый сервис отправки СМС (3-я версия)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1352]
Текущий класс, через который происходит отправка:
\i\wf-base\src\main\java\org\igov\io\sms\ManagerSMS.java
на его базе сделать клон:
\i\wf-base\src\main\java\org\igov\io\sms\ManagerSMS_New.java

и переписать его с учетом такого описания(все вызовы с прошлого класса перевести на этот, потому лучше обертку оставить точно такой-же, только имя класса другое):

**ОПИСАНИЕ:**
Отправка сообщения:
URL: {ROOT_URL}/api/v1/send
метод: POST
формат: application/json
**Запрос:**
**тело:**
```
  {
    "messageId": "unique123",
    "callbackUrl": "https://....",
    "schemaId": 1,
    "addrPhone": "+380...",
    "typeSend": "online",
    "typeCheck": "info",
    "merchantId": "10",
    "merchantType": "sms_service",
    "merchantPassword": "",
    "messageTemplate": [
        { "type": 0, "text": "обычный текст" },
        { "type": 1, "text": "текст скрытый только на интерфейсе" },
        { "type": 2, "text": "текст скрытый на интерфейсе и в БД" }
    ],
    "smsAlfaname" : "",
    "senderTTL" : 60,
    "privat24TTL" : 60
}

```
**описание параметров:**
**Параметр	Обязательный	Тип	Органичения	Описание**

> messageId	*	string	length: 1..100	Уникальный идентификатор сообщения, по которому будет отправлен callback.
> callbackUrl	*	string	length: 1..1000	URL на который будут отправлены callback при изменении статуса.
> schemaId	*	int	id существующей схемы	Идентификатор схемы отправки сообщений
> addrPhone	*	string	regexp: \+\d{4,15}	Номер телефона для отправки сообщения
> typeSend	*	string	online или offline	Тип отправки
> merchantId	*	int	id мерчанта	Идентификатор мерчанта
> merchantType		string	sms_service или otp_service	Тип мерчанта (по умолчанию: sms_service)
> merchantPassword	*	string		Пароль от мерчанта
> messageTemplate	*	array	size: not_empty	Шаблон сообщения. Состоит из набора элементов
> {'type': 0, 'text':'текст'}

**где**

> text- часть текста,
> type - тип скрытия этой части.

Итоговое сообщения для клиента собирается путём конкатенации всех text из массива messageTemplate.
Параметр type влияет только на скрытие этой части текста в интерфейсе администрирования или БД.
0 - текст нигде не скрывается (значение по умолчанию если type не передан)
1 - текст скрывается только в интерфейсе администрирования
2 - текст скрывается и в интерфейсе и в БД
otp		int		Пароль. Используется только в схеме IVR-звонка с диктовкой пароля
smsAlfaname		string		Используется только в канале SMS.
Имя отображаемое в поле "отправитель". Должно поддерживаться сервисом SMS API.
senderTTL		int	min 15 сек
max 10800 сек
по умолчанию 180 сек	Время (в секундах) в течении которого будет ожидаться ответ о доставке от Sender, перед тем как перейти к попытке отправки в следующем канале.
privat24TTL		int	min 15 сек
max 10800 сек
по умолчанию 60 сек	Время (в секундах) в течении которого будет ожидаться ответ о доставке от Приват24физ (old), перед тем как перейти к попытке отправки в следующем канале.
smsTTL		int	min 15 сек
max 180 сек
по умолчанию 30 сек	Время (в секундах) в течении которого будет ожидаться ответ о доставке SMS.
messageEndDate		string		Граничное время отправки сообщения.
Время, до которого сообщение можно отправлять. После - сообщение теряет актуальность.
Формат yyyyMMddHHmmss
retryCount		int	>0	Количество попыток отправки.
Если не передавать осуществляется 1 попытка отправки согласно указанной схемы.
Время повторной попытки 5 минут.

**Пример:**
Отправка по схеме sender|privat24|sms, количество попыток 2.
Осуществляется попытка отправить в Sender - Приват24физ (old) - SMS, ожидаем 5 минут, повторяется вторая попытка отправки в Sender - Приват24физ (old) - SMS

**Ответ**
**успешный ответ api**
```
{
    "msStatus": "ok",
    "schemaList": [ "sender", "privat24", "sms" ]
}
```
**успешный ответ callback**
```
{
    "msStatus": "delivered",
    "messageId": "ref1",
    "schemaList": [ "sender", "privat24", "sms" ],
    "msChannel": "sms",
    "messageHistory": {
        "sender": "Сообщение не доставлено",
        "privat24": "Не дождались отчета о доставке",
        "sms": "Сообщение отправлено"
    }
}
```
**ответ с ошибкой.**
```
{
    "msStatus": "warning",
    "msCode": "incorrect_password",
    "msMessage": "Указанный пароль не подходит для мерчанта 25@sms_service"
    "messageId": "ref1",      // будет передан, только если это callback
}

```
**описание параметров:**
**Параметр	Тип	Описание**

> msStatus	string	Статус обработки.
> ok - принято в работу, не финальный статус, еще будет callback
> delivered - доставлено, финальный статус
> not_delivered - не доставлено, финальный статус
> warning - ошибка валидации или проверки бизнес логики, финальный статус
> error - ошибка отправки, финальный статус, можно повторить запрос
> msCode	string	Код ошибки
> msMessage	string	Описание ошибки
> schemaList	array	Последовательность каналов отправки
> messageHistory	object	История попыток отправки в каналах из schemaList
> messageId	string	Уникальный id сообщения. Передаётся при callback.
> коды ошибок
> msCode	msStatus	Описание
> check_password	error	Ошибка при обращении к API валидации пароля от мерчанта
> corezoid_crash	error	Ошибка при обращении к API Corezoid
> fatal_error	error	Внутренняя ошибка MessageService
> no_send	error	Сообщения данного типа не отправляются по плану Б
> promin_crash	error	Ошибка при обращении к API проминя
> send_error	not_delivered	Адресат не доступен в каналах указанной схемы
> access_denied	warning	По указанной сессии нет нужной роли
> bad_request	warning	На вход пришёл запрос не в формате json или не соответствующий описанным критериям
> channel_undefined	warning	Ошибка определения канала отправки
> duplicate	warning	По указанному messageId уже был запрос
> incorrect_password	warning	Указанный пароль мерчанта не подходит к указанному id мерчанта
> schema_undefined	warning	По указанному коду схема отправки не определена
> session_close	warning	Указанная сессия не существует или не активна

**Comment by kr110666kai** [comment]
Добрый день, для решения задачи на https://alpha.test.igov.org.ua надо добавить в [AS.properties](https://github.com/e-government-ua/i/commit/1a1725e65b44a255b8789a5557eb3fe55817a68a#diff-d71015d73e66e7bb279f60692c51edd5):
```
 ### SMS_New
general.SMS_New.sURL_Send=https://sms-inner.siteheart.com/api/v1/send
general.SMS_New.sMerchantId=1070
general.SMS_New.sMerchantPassword=111
general.SMS_New.sCallbackUrl=https://alpha.test.igov.org.ua/wf/service/sms/callbackSMS
```

**Comment by bvv4ik** [comment]
@kr110666kai
Добрый,
на самом деле достаточно лишь в прошлый блок добавить:
general.SMS.sURL_SendNew=https://sms-inner.siteheart.com/api/v1/send
(остальные параметры брать с прошлого места...
и я только что добавил, можно проверять)


а вот general.SMS_New.sCallbackUrl=https://alpha.test.igov.org.ua/wf/service/sms/callbackSMS
не нужно в проперти, его нужно генерить динамически, на осовании хоста регионального сервера (в генерал конфиге: general.Self.sHost)

**Comment by kr110666kai** [comment]
https://sms-inner.siteheart.com/api/v1/send не верный адрес сервиса, завтра постараюсь уточнить

**Comment by kr110666kai** [comment]
Новый сервис отправки СМС задействован, залит на альфу.
На текущий момент на тесте отсылки СМС на телефон не будет. Только код ответа от сервиса
**{"msStatus":"ok","schemaList":["sms"]}** - это успешный
На боевом должно работать.
