### ISSUE TITLE
Добавить новый тип полей активити "table", и встроить в листенер обработки файлов поддержку тех полей, что будут в нем храниться как обьекты массива JSON

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1353]
- [x] 1) Добавить поддержку типа "table"
- [x] 2) Создать тестовый БП с таким полем и в элементе default подобный образец контента объекта-JSON: 

:

```
{
   "aField":[
      {
         "id":"sName"
         ,"name":"Название"
         ,"type":"string"
         ,"requred":"true"
         ,"writible":"true"
         ,"default":""
      }
      ,{
         "id":"nSum"
         ,"name":"Сумма;Сумма стоимости"
         ,"type":"long"
         ,"requred":"true"
         ,"writible":"true"
      }
   ]
}
```

По этому шаблону формируются клоны, с заполненными уже данными, и сохраняющиеся уже в виде общего объекта-JSON всей таблицы со всеми полями (п.3)
- [ ] 3) Учитывать обработку в листенере аплоадера и новый тип с подобным контентом.

```

{
   "aRow":[
      {
         "aField":[
            {
               "id":"sName"
               ,"name":"Название"
               ,"type":"string"
               ,"requred":"true"
               ,"writible":"true"
               ,"value":"Имя1"
            }
            ,{
               "id":"nSum"
               ,"name":"Сумма"
               ,"type":"long"
               ,"requred":"true"
               ,"writible":"true"
               ,"value":"Сумма1"
            }
         ]
      }
   ]
}

```

**ВАЖНО:**
- в форме гражданина и чиновника это поле отображаться не должно, а только таблица вместо него, на основании объекта вида.п.3 (причем в форме гражданина этот обьект может формироваться самим гражданином, путем добавления новых строк в таблицу и удаление их, через интерфейс)
- контент общего объекта JSON должен сохраняться в виде файла, как обычный атач (только сам атач не должен отображаться ни кому, а храниться там только в технических целях)
- все правила, которые применялись к полям обычным, должны применяться и к полямм этой таблицы, по всем правилам активити (маркеры валидоторов и моушина, подсветка неверных данных и т.д.)

**Comment by GrekD** [comment]
тестовый бп
https://alpha.test.igov.org.ua/service/3/general

**Comment by OlgaTurenko** [comment]
поддерка прикрепления файлов в поля таблиц

**Comment by OlgaTurenko** [comment]
уже не актуальна. создана вместо нее вот эта: https://github.com/e-government-ua/i/issues/1461
