### ISSUE TITLE
Реализовать фронтовую поддержку нового типа table

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1354]
В продолжении реализации: https://github.com/e-government-ua/i/issues/1353
- [x] 1) На центральном портале, при встрече поля с типом table:
- [x] 1.1) отрисовывать его и работать с ним так:
- вокруг блока со строками и полями рисовать слабозаметную рамку, очерчающую всю таблицу а название поля писать перед блоком (над ней)
- каждая строка(как уже заполненная так еще нет) должна включать в себя все ее поля, взятые из default (вверху лейбл, внизу поле, еще ниже сообщение о поле(например не заполнено)), 
- всегда должна быть одна строка с полями незаполненными в самом низу (для добавления новой строки), и когда поля в ней заполнятся и нажмется "Добавить"(п.п.1.2) - она переместится в верхнюю, заполненную часть таблицы, а внизу добавится опять новая строка со всеми незаполненными полями (или заполненными по дефолту)
- **Эти пункты можно в последнюю очередь:**
- работать с маркерами стандартно (только адресация к каждому из них должна быть не как раньше "[field1]", где "field1" - id поля а "[table1.field1]", где table1 - id поля с таблицей а field1 - id поля в таблице, без учета строки в таблице, т.к. все строки идентичны, и только с разными данными)
- Должна быть такая-же поддержка стандартных серекторов ии автокомплитов (ориентироваться на id-шник поля таблицы так-же, как ориентировались на обычный id-шник поля.
- [x] 1.2) реализовать кнопку добавления новой строки в таблице, при этом:
- кнопку отображать справа последней незаполненной строки таблицы
- по нажатию клонировать эталонный объект атрибута default (исходное ишью п.2), и добавлять в каждый элемент поле value(с проставленным значением), и соответствено убирать атрибут default.
- сохранять временно общий итоговый объект JSON (исходное ишью п.3) в оперативной памяти и работать с ним там аж до самого сабмита
- валидировать поля (стандартными валидаторами) по нажатию на кнопку "Добавить" (так-же, как это делалось раньше при нажатии на кнопке сабмит)
- [x] 1.3) реализовать кнопку удаления любой строки в таблице, при этом:
- кнопку отображать справа от таблицы, напротив строки, которую нужно удалять
- по нажатии удалять ее из временного общего итогового обьекта JSON (исходное ишью п.3) в оперативной памяти.
- [ ] 1.4) Заблокировать возможность редактирование любых полей добавленных выше строк таблицы, а для редактирования отображать справа кнопку "Изменить"(по нажатию на которую разблокировать редактирование), после, отредактировав дать возможность сохранить кнопкой "Сохранить" или отменить, кнопкой "Отменить". При сохранении так-же валидировать и не давать сохранять невалидные данные. После сохранения опять блокировать поля для редактирования.
- [x] 1.5) По сабмиту выполнять следующие действия:
- сохранять контент JSON-обьекта так-же как это делается и при обычных типах file (в redis), и в значение(value) єтого типа table сохранять полученный ключ. ВАЖНО: обязательно в качестве названия поля в параметре передавать название поля с добавлением строки "[table]"
- следом проводить обычный сабмит.
- [x] 2) На региональном портале(дашборде чиновника), при встрече поля с типом table :
- [x] 2.1) отрисовывать его и работать с ним так:
- вокруг блока со строками и полями рисовать слабозаметную рамку, очерчающую всю таблицу а название поля писать перед блоком (над ней)
- каждая строка должна включать в себя все ее поля, взятые из общего обьекта JSON (вверху лейбл, внизу поле, 
- [x] 2.2) загружать общий обьект JSON из файла ко ключу в поле (value)
- [ ] 2.3) не отображать этот атач в общем списке атачей (игнорировать по признаку наличия в названии слова "[table]"

ВАЖНО:
Для тестирования использовать тестовый БП:
https://alpha.test.igov.org.ua/service/3/general

Курирует процесс приемки работы Дарья Грек

[16:08:52] Павел  Курбацкий: https://dl.dropboxusercontent.com/u/50541317/eGov/dashboard/%D0%BF%D0%BE%D1%80%D1%82%D0%B0%D0%BB_-_%D0%B4%D0%B0%D1%88%D0%B1%D0%BE%D1%80%D0%B4.html -  первый вариант отображения всего этого чуда на портале (справа)

кнопки добавления / удаления строки - кликабельны
[16:09:37] Павел  Курбацкий: показал пример двух таблиц.... 6 колонок и 2 колонки
[16:10:25] Павел  Курбацкий: на текущий  момент по нашим процессам максимальный вариант необходимый - 4 колонки, но  можно закладываться но  более сложный

![image](https://cloud.githubusercontent.com/assets/4208821/18052566/c8ff1942-6e03-11e6-95f2-7eefb70de826.png)

**Comment by kurbpa** [comment]
@bvv4ik 
@GrekD 
@antonlegkiy 

Убедительная просьба дождаться макетов интерфейсов!!

**Comment by kurbpa** [comment]
Мокап - https://dl.dropboxusercontent.com/u/50541317/eGov/dashboard/%D0%BF%D0%BE%D1%80%D1%82%D0%B0%D0%BB_-_%D0%B4%D0%B0%D1%88%D0%B1%D0%BE%D1%80%D0%B4.html

**Comment by GrekD** [comment]
Баг:  если тейбл не объявлен как отдельное поле на дашборде, то в принтформу не потянутся данные  
надо или
1. сделать так чтоб тейблы можно было сделать недоступными для редактирвоания чиновником
или
2. тянуть в принтформу из аттачей данные тейблов
