### ISSUE TITLE
Добавить проливку в поле sID_Place_UA - выбранного места услуги (ее ИД)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1355]
делать это сразу при подгрузке формы

брать ИД плейса из подобьекта oServiceData
подобькта oPlace.sID

проверять на тестовой услуге:
https://alpha.test.igov.org.ua/service/785/general

Курирует Дарья Грек

**Comment by GrekD** [comment]
работает, можно переносить правку
