### ISSUE TITLE
хочу присоединится к этой команде, как это сделать?

### ISSUE THREAD

**Issue by lelelada** [e-government-ua/i#1356]

**Comment by GrekD** [comment]
@lelelada 
добрый день!
в этот репозиторий задачи, пожалуйста, не создавайте - он только для разработки
Вот ссылка
https://github.com/e-government-ua/i/wiki/%D0%AF%D0%BA-%D0%BF%D0%BE%D1%87%D0%B0%D1%82%D0%B8-%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D1%83
еще можете писать в другой ветке:
https://github.com/e-government-ua/iForum/issues
