### ISSUE TITLE
Отображать функционал по работе с группами/пользователями (создание, редактирование и тд) только для пользователей из группы superadmin.

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1357]
Отображать функционал по работе с группами/пользователями (создание, редактирование и тд) только для пользователей из группы superadmin.
.

**Comment by OlgaTurenko** [comment]
Принимает работу Павел Курбацкий.

**Comment by kurbpa** [comment]
Проверил на альфе - реализовано согласно  описанию.

**Comment by GFalcon-UA** [comment]
пришлось вынести хранение объекта User из cookie в localStorage с использованием библиотеки https://www.npmjs.com/package/node-localstorage
