### ISSUE TITLE
Доработать автогенерацию фидбеков при закрытии процеса

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1361]
1. Для фидбеков генерировать отдельные группы отличные от эскалаций. 
   Логику добавления к группе префикса перенести в класс AssignGroupListener из класса BpServiceHandler (тоесть в переменную орган при старте процесса передавать группы без префикса). Если в переменную group_prefix в слушателе передали непустое значение, то на основании групп, которые в переменной organ, должны создаваться группы (если их еще нет) с префиксом и устанавливаться в процесс.
2. Ограничивать количество генерируемых заявок в день 100 штук. 
   Создать переменную-счетчик заявок в классе BpServiceHandler  limit_processFeedback. Перед генерацией нового процесса в классе RequestProcessingInterceptor по фидбеку проверять не превысили ли счетчик (если превысили не генерируем). После генерации каждой заявки по фидбекам увеличивать его на единицу.  И в шетдулере, который еженочно запускается и генерирует эскалации (создать класс JobFeedback на основе класса JobEscalation) реализовать сброс счетчика на ноль.
3. Запускать код по автогенерации процесса фидбека при простановке отзыва об услуге из письма гражданина, если оценка (nID_Rate) = 1 или 2 или 3 (сервис /setFeedbackExternal). Сейчас фидбеки запускаются только в интерцепторе при закрытии заявки. Тоесть создать в бейсе сервис по запуску фидбека по процессу (создаем новый метод startFeedbackProcessNew на основе startFeedbackProcess и его вызываем в новом сервисе (а старый сейчас вызывается в интерцепторе: String snID_Proccess_Feedback = bpHandler
                                   .startFeedbackProcess(snID_Task, snID_Process, sProcessName);))
4. Генерировать процесс по фидбекам из интерцептора RequestProcessingInterceptor не по всем заявкам, а отвечающим условиям:  по этой услуге в этом месте (район, город, область, страна в зависимости от того, где раскрыли услугу) было подано менее 50 заявок за все время. Для этого написать сервис по подобию /getCountOrders в том же классе, который будет возвращать количество заявок по услуге в рамках места, в котором она была подана. (сервис /getCountOrders  возвращает количество в рамках человека)
5. В заявку по фидбекам по аналогии с эскалациями должен проливаться на форму Place из исходной заявки (место, где она была заказана. подробное описание в задаче по проставлению параметра в процесс эскалации).
6. Если фидбек не отрабатывается на протяжении 20 дней, то закрывать автоматом заявку
   Тоесть в шетдуллере  (класс JobEscalation)  делать выборку всех незакрытых процессов, с датой старта = (сегодня - 20 дней)   и закрывать такие процессы. (делается через runtimeService.deleteProcessInstance(processInstance.getProcessInstanceId(), "deprecated");)

7.необходимо показывать еще такие поля (в БП они внесены):

nID_Protected
clfio
Place
phone
email
nID_Proccess_Feedback
processName
region
nasPunkt
organ
sDate_BP
sBody
nID_Rate
sEmployeeContacts
sBody_Indirectly
nID_Rate_Indirectly
info

**Comment by OlgaTurenko** [comment]
Принимает задачу Грек Дарья.

**Comment by HSdevelop** [comment]
п.6 #1361 - выполнено

**Comment by ElenaShebaldenkova** [comment]
п.1 и п.2. выполнены.

**Comment by OlgaTurenko** [comment]
Елена, уже именно в ветке тест сделано или пока что локально?

**Comment by Dashchenko-Inna** [comment]
локально

**Comment by Dashchenko-Inna** [comment]
чтоб никто не начал

**Comment by Dashchenko-Inna** [comment]
п1,2,3 готовы и в ветке test

**Comment by Dashchenko-Inna** [comment]
п.4 - готово

**Comment by GrekD** [comment]
**0.** коллеги подскажите, пожалуйста, как породить фидбек на альфе?
**п.2,3,4** похоже проверить не смогу. Или подскажите как тестировать
**п.5.** сейчас в процессе фидбека отображаются только 2 поля:

- nID_Proccess_Feedback
- organ
необходимо показывать еще такие поля (в БП они внесены):

- nID_Protected
- clfio
- Place
- phone
- email
- nID_Proccess_Feedback
- processName
- region
- nasPunkt
- organ
- sDate_BP
- sBody
- nID_Rate
- sEmployeeContacts
- sBody_Indirectly
- nID_Rate_Indirectly
- info

**Comment by OlgaTurenko** [comment]
Андрей делает 7-й пункт.

**Comment by msvidran** [comment]
При переходе на заявку для отработки фидбэка выдает ошибку. Фидбэк был написан после перехода из письма, клгда была выставленна оценка.

**Comment by Dashchenko-Inna** [comment]
реализован п.7 задачи, исправлены ошибки все что нашла по старому методу - startFeedbackProcess и по новому - startFeedbackProcessNew

**Comment by Dashchenko-Inna** [comment]
Unknown property used in expression: ${bankIdlastName} ${bankIdfirstName} ${bankIdmiddleName} - исправлено

**Comment by GrekD** [comment]
**п.1** - группы генерируются, но есть проблема с группами в формировании идшника которой берется переменная из БП. Так например породились группы:
Feedback_upszn${nArea}
Feedback_rda_${sID_Public_SubjectOrganJoin}
Feedback_common_zags_${sID_Public_SubjectOrganJoin}
я не знаю, может, это исправлено (т.к. есть и нормлаьно порожденные группы), но лучше чтоб разработчик глянул 

**п.2.3.4**  проверить получится уже в боевой эксплуатации   
**п.5**  - все ок   
**п.6.**  получится только в конце ноября проверить, но думаю специально этой проверки ждать не будем  
 
**п.7.**   

- [ ]  в поле не передаются данные  - nID_Proccess_Feedback - ID бізнес-процесу (какой БП родительской закрытой заявки)
- [ ]  в поле не передаются данные  - processName  - Назва послуги (по какой услуге породился фидбек)
- [ ]  в поле не передаются данные  - region - какая область была выбрана заявителем в родительской исходной заявке
- [ ]  в поле не передаются данные  - nasPunkt - какой населенный пункт был выбран в родительской заявке
- [ ]  в поле не передаются данные  - sDate_BP - Дата подання звернення (имеется ввиду родительская заявка)
- [ ]  в поле не передаются данные - sBody - поле есть, но туда не передались значения (я поставила комментарий как заявитель)
- [ ]  в поле не передаются данные - nID_Rate - поле есть, но туда не передались значения (я поставила оценку как заявитель)
- [ ]  info - тут какая-то штука приключилась - в это поле передается текст из точно такого же ИДшника родительской заявки, а не текст который прописан по дефолту в БП system_feedback

**Comment by GrekD** [comment]
все замечания по п.7. так и остались - не передаются поля, которые я описала в прошлом комментарии.
Проверяла на заявке 235276056

**Comment by GrekD** [comment]
пока задача неактуальна
