### ISSUE TITLE
Доработать механизм маркера ValuesFieldsOnCondition (сеттинга значений), для поддержки ссылок на другие поля

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1362]
Доработать механизм работы маркера так, чтоб сетились в поля не только фиксированные значения, прописанные в маркере, а могли-бы сетиться и значения других полей, на которые ссылаются теги в маркерах.

Например, вместо:
```
ValuesFieldsOnCondition_401":{
   "sNote":["поставити + Місто, пробел остальным"]
   ,"aField_ID":["sVarPlace401Plus","sVarPlace402Plus","sVarPlace403Plus","sVarPlace404Plus"]
   ,"asID_Field_sValue":["+"," "," "," "]
   ,"asID_Field":{"sClient":"asSelectTypePlace"}
   ,"sCondition":"[sClient] == 'tf401'"
}

```
чтоб было:
```
ValuesFieldsOnCondition_401":{
   "sNote":["поставити + Місто, пробел остальным"]
   ,"aField_ID":["sVarPlace401Plus","sVarPlace402Plus","sVarPlace403Plus","sVarPlace404Plus"]
   ,"asID_Field_sValue":["[sVarPlace402Plus]"," "," ","Текст [sName] подходит"]
   ,"asID_Field":{"sClient":"asSelectTypePlace"}
   ,"sCondition":"[sClient] == 'tf401'"
}

```
Где вместо тегов:
[sVarPlace402Plus] и [sName]
подставлялись-бы значения полей формы с такими ИД-шниками.

причем если значение в одном из этих полей изменится - чтоб сразу одновилось и производное место

поддержка маркера должна сохраниться так-же и на дашборде

Курирует реализацию и проверку: Август

**Comment by agerman-ua** [comment]
Услуга для тестов - https://alpha.test.igov.org.ua/service/1515/general
