### ISSUE TITLE
Починить автозаполнение заявки гражданина  данными из прошлой заявки. 

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1363]
Починить автозаполнение заявки гражданина данными из прошлой заявки. 

Детальное описание:
https://docs.google.com/document/d/1J5yiXx6nWRq-_3Hcl45JgyCG_7C6Ehq0Oi_tSfR92gs/edit

**Comment by OlgaTurenko** [comment]
Принимает задачу Дарья Грек.

**Comment by GrekD** [comment]
на альфе работает
