### ISSUE TITLE
Починить проставление статуса заявки в истории

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1366]
При определенных условиях (описание подробное по ссылке: https://docs.google.com/document/d/1ZVKe1sAB2mhuQPq1KEudV3j7JDW1vjX83544kHWrOEM/edit) не меняется статус заявки при ее закрытии.  Статус при закрытии проставляем в интерцепторе (отрабатывает код  в интерцепторе при каждом вызове любого нашего сервиса): org.igov.service.controller.interceptor.RequestProcessingInterceptor.java метод: saveClosedTaskInfo. 
Блок: 
if (bProcessClosed) {
                    LOG.info("Saving closed task");

```
                mParam.put("nID_StatusType", HistoryEvent_Service_StatusType.CLOSED.getnID().toString());
                mParam.put("sUserTaskName", sUserTaskName);
                mParam.put("sID_Order", sID_Order);
                historyEventService
                        .updateHistoryEvent(sID_Order, mParam);//sID_Process
                LOG.info("saving closed task finished");
            }
```

**Comment by OlgaTurenko** [comment]
![image](https://cloud.githubusercontent.com/assets/10909557/18288389/ca094a66-7483-11e6-8f95-bc81c729a1de.png)

**Comment by OlgaTurenko** [comment]
слева видно В обробцi, а должно писать Закрита.

**Comment by OlgaTurenko** [comment]
![default](https://cloud.githubusercontent.com/assets/10909557/18303000/877b57ec-74e3-11e6-83ae-fafe02ab3676.png)

**Comment by OlgaTurenko** [comment]
также не меняется название шага на котором заявка находится. выделила красным это название.

**Comment by GrekD** [comment]
статус заявки меняется в течении ее движения по юзертаскам - эта часть гуд
Но, когда идет по ветке таймера - то не закрывается, а она точно в архиве - это видно через запросы, кроме того я попробовала ее удалить и у меня не получилось, что является еще одним признаком, что заявка закрыта.
https://delta.test.igov.org.ua/search?sID_Order=5-89824478

**Comment by GrekD** [comment]
осталось еще сценарий с маркером разрулить
