### ISSUE TITLE
Доработать селектор, добавив в строки автокомплита ИД-шки перед названием

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1367]
При поиске выдавать в выпадающем списке не только название но и ИД-шники, перед названиями.

Описание подробней:
https://docs.google.com/document/d/1twFr_Lhk8rwFnJVhEx5vZnJNyUhxPcBdigG1IJsrN3w/edit

UPD: (30/09/2016)

- [ ] сделать это одним полем
- [ ] в этом одном поле будет наименовнаие и код - поиск может осуществляться и по тjму и по тому
- [ ] в принтформу будет передаваться только код без наименования

**Comment by GrekD** [comment]
на тестовых работает
