### ISSUE TITLE
починить автозаполнение данными предыдущей заявки

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1370]
https://docs.google.com/document/d/1J5yiXx6nWRq-_3Hcl45JgyCG_7C6Ehq0Oi_tSfR92gs/edit?usp=sharing

**Comment by Novakanna** [comment]
автозаполняться должны все поля? валидация полей должна быть?

**Comment by Novakanna** [comment]
Автозаполнение работает для таких полей:
Сумма nSum - поле з типом string
E-Mail адреса для зворотнього зв'язку:
Найменування товару:
Код товару (УКТ ЗЕД):
поле з типом енум:
Поле з типом дата

**Comment by GrekD** [comment]
вроде сегодня окончательно починили)
