### ISSUE TITLE
Реализовать маркер-атрибут для отрисовки линии(группирующей/отсекающей) одни поля от других

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1373]
вид маркера такой:

```

{
 "attribute" : {
  "Line_1" : {
   "aElement_ID" : ["idFieldFirstBefore"], //ИД-шники полей, перед которыми рисовать линию
   "sValue" : "Общая группа" //если задано, то по центру линии писать текст
  },
  "Line_2" : {
   "aElement_ID" : ["idFieldFirstBefore2"], 
   "sValue" : "Вторая группа"
  } 
 }
}
```

и отрисовывать линию с/без назания по нему
- реализовать в public-js
- соотв. должно работать и в дашборде и централе

Выглядеть визуально эта линия должна приблизительно так:

![image](https://cloud.githubusercontent.com/assets/4208821/18640784/47fb0c52-7ea2-11e6-8d83-845cd3bb7ac9.png)

**Comment by GFalcon-UA** [comment]
тестировал на услуге
https://alpha.test.igov.org.ua/service/1515/general
в дашборд она попадает под tester-а

**Comment by GrekD** [comment]
линия отрисовывается, вид не соответствует виду на дашборде, но как я поняла - стили нет возможности пока что редактировать, поэтому предлагается выливать то что есть.

**Comment by GrekD** [comment]
спасибо, это именно та линия, которую мы хотели
