### ISSUE TITLE
Доработать возможность конвертации ХТМЛ в ПДФ формируемого на основе принтформы атача.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1382]
Сейчас, при:
а) name="File label;File title;pattern/print/minust/common_zags_1.html"
- автоматически формируется принтформа по шаблону pattern/print/minust/common_zags_1.html
  и результат атачится к таске в виде ХТМЛ-файла.
  (и далее этот атач шлется как атач в письме)

Нужно(в дополнение):
б) name="File label;File title;sPrintFormFileAsIs=pattern/print/minust/common_zags_1.html"
чтоб работало так-же как и при "а"

в) name="File label;File title;sPrintFormFileAsPDF=pattern/print/minust/common_zags_1.html"
чтоб работало так-же как и при "а", но при этом чтоб еще ХТМЛ-файл предварительно конвертился из ХТМЛ в ПДФ, при помощи сервиса(вызов на ноде):

[13:28:40] Зайченко Валерий Валерьевич: https://bankid.privatbank.ua/ResourceService/checked/uploadFilesForConvert
Аналагично с методом uploadFilesForSignature загружаете файл(ы), только хидер acceptKeyUrl тут уже не обязателен
В ответ как и ранее получаете сообщение вида 
{"state":"ok","code":"000000","desc":"https://bankid.privatbank.ua/ResourceService/checked/claim/2b696bd2-c588-43e7-acf4-9ed98bcf7fef/clientPdfClaim"}
только теперь по этому урлу вы сразу забираете готовый pdf или zip с pdf внутри
[13:29:34] Зайченко Валерий Валерьевич: Метод конвертит не только html ->pdf а и все остальное по аналогии с  uploadFilesForSignature

Курирует: Максим Свидрань
Тестовая услуга: https://alpha.test.igov.org.ua/service/732/general
BPMN файл: wf-region\src\main\resources\bpmn\autodeploy\ _test_PDF_attached.bpmn

**Comment by msvidran** [comment]
@GFalcon-UA может есть какие-то вопросы?

**Comment by msvidran** [comment]
В почту письмо пришло с двумя вложениями

http://prntscr.com/d4ixep

но ниодно не открывается
http://prntscr.com/d4ixu6

вернее Attach_22865048 можно открыть, но только через блокнот, а там чистый HTML
