### ISSUE TITLE
Реализовать поддержку маркером RequiredFieldsOnCondition работы и на поле с id="form_signed", для онлайн-регулирования обязательности наложения ЭЦП

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1384]
Подробное описание:
https://docs.google.com/document/d/1QBC0tzlWvAbwLkQ4Hn7adYcl03EGZ283wksoT8WPEXM/edit

Курирует Татьяна
Тестовая таска: https://delta.test.igov.org.ua/service/654/general

**Comment by OlgaTurenko** [comment]
тест получения уведомления
