### ISSUE TITLE
Подключить автогенерацию слотов

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1385]
В классе JobsInitializer раскомментировать //addBuilderFlowSlotsJob(scheduler); и привести в рабочее состояние автогенерацию слотов (если там есть ошибка).

Доработать автогенерацию слотов (класс JobBuilderFlowSlots) так, чтоб можно было задавать количество дней на которое генерируем. Как это сделать:

1)Добавить поле nCountAutoGenerate типа логн, может быть наловым в сущность Flow_ServiceData. Добавить в справочник  Flow_ServiceData.csv в шапку это поле. Добавить в заполнении таблицы данными из справочника это поле.

2)В шетдуллере по автогенерации устанвливать dateEnd (дату по которую генерируем слоты) равную dateStart + nCountAutoGenerate. Если nCountAutoGenerate равна налу, значит автогенерировать слоты по этой очереди не нужно.

**Comment by Koffeek** [comment]
По исходным условиям все работает корректно, но для внедрения предлагаю изменить логику работы. При наличии признака, по шетдулеру генерировать слоты на дату (день сегодняшний + nCountAutoGenerate). Нагенерить слоты на минимальный промежуток (месяц) мы сможем самостоятельно один раз, а такая генерация позволяет спокойно удалять праздничные дни или корректировать расписание "на ходу". Сейчас при удалении "праздничного дня" на следующее утро он генерируется снова.

**Comment by Koffeek** [comment]
Отсутствует возможность удаления дней или времени из списка автогенерации
