### ISSUE TITLE
Отображается сообщение об ошибке на странице "Мій журнал" после нажатия Enter в поле поиска

### ISSUE THREAD

**Issue by Novakanna** [e-government-ua/i#1386]
[S3]
Окружение: Windows 7, Google Chrome
Шаги воспроизведения
1. Открыть сайт https://alpha.test.igov.org.ua
2. Нажать кнопку “Мій журнал”
3. Ввести любое слово(например, "тест") в поле ввода и нажать Enter
4. Обратить внимание на сообщение об ошибке
Ожидаемый результат:
Выполняется поиск на странице при нажатии Enter без сообщений об ошибке

Дополнительно: вводимые данные отображаются в окне об ошибке как параметры. Т е при вводе следующего слова в поиск, предыдущее остается в параметрах.
Ошибка также присутствует на боевой версии сайта
![image00](https://cloud.githubusercontent.com/assets/22517791/19012776/928445e4-87c7-11e6-9ebb-54cc02ad38b8.png)
![image01](https://cloud.githubusercontent.com/assets/22517791/19012775/92839194-87c7-11e6-8369-3b3d474003c1.png)

**Comment by OlgaTurenko** [comment]
неверно вводиться формат заявки, потому и сообщение об этом. (пустое значение - недопустимый формат заявки)
