### ISSUE TITLE
сделать необязательными ИД-шники записей

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1387]
- [x] 1) чтоб в этих цсвшках сделали такой же принцип как в SubjectOrganJoinAttribute.csv, т.е. избавится от ИДшников, и должна быть возможность удалять строки без нанесения вреда базе
  вот эти надо сделать в первую очередь:
  ObjectCustoms.csv
  SubjectOrganJoinTax.csv
- [x] 2) во вторую очередь, чтоб можно было в этих файлах удалять строчки без ущерба целостности базы:
  Subject.csv
  SubjectAccount.csv
  SubjectContact.csv
  ВАЖНО:  в этих сущностях обязательно сохранять записи, которые в базе создаются уже через сервисы динамически... вроде начинаются с индекса 10000 но нужно перепроверить.
  Чтоб ни дай Бог с боевой базы их не прибило ничего...

Курирует: Дарья Грек

**Comment by GrekD** [comment]
@brunneng 1 пункт работает, спасибо
второй пункт будем реализовывать?

**Comment by brunneng** [comment]
Уже реализовано

**Comment by GrekD** [comment]
удалила строчку из файла Subject.csv
и локальная сборка не пошла(

**Comment by brunneng** [comment]
Напиши пожалуйста какую строчку удалила, чтоб я смог у себя воспроизвести и происследовать

**Comment by GrekD** [comment]
1;ПАО;ПАО ПриватБанк;ПриватБанк

**Comment by GrekD** [comment]
@brunneng Евгений, есть новости по этой таске?

**Comment by brunneng** [comment]
Киньте пожалуйста ошибку, которая возникает  и в каком тесте. Дело в том что на 1;ПАО;ПАО ПриватБанк;ПриватБанк завязано много других записей, их тоже надо удалять (в других csv файлах) чтобы не было нарушения ссылочной целостности в базе.

**Comment by GrekD** [comment]
@brunneng 
попробовала удалить строчку и связанные с ней строчки в других файлах - всё работает.
спасибо! ставлю лейбу для переноса доработок в мастер

**Comment by brunneng** [comment]
Отлично! :)
