### ISSUE TITLE
Реализовать авто-сеттинг глобальной проперти процесса, при выполнении определенных операций с заявкой/таской

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1388]
Сетить в глобальную переменную с id=saTaskStatus одно или несколько из значений, через запятую, или убирать их из списка значений, при:
- [x] 1) Подаче замечания:
  добавлять "WaitAnswer"
  (найти сервис в АПИ на регионе по добавлению замечания, и там доработать)
  \i\wf-base\src\main\java\org\igov\service\controller\ActionTaskCommonController.java
  void setTaskQuestions(
- [x] 2) Ответе на замечание: 
  добавлять "GotAnswer"
  и убирать "WaitAnswer"
  (найти сервис а АПИ на централе по ответу на замечание, и там доработать)
  \i\wf-central\src\main\java\org\igov\service\controller\ActionTaskCentralController.java
  void setTaskAnswer(
- [x] 3) Добавлении коммента от гражданина:  
  добавлять "GotUpdate"
  (найти сервис а АПИ на централе по сеттингу добавлению мессаджа(понимать что это от гражданина), и там доработать)
  \i\wf-central\src\main\java\org\igov\service\controller\SubjectMessageController.java
  ResponseEntity setServiceMessage(
- [x] 4) Добавлении коммента от чиновника:  
  убирать "GotUpdate"
  (найти сервис а АПИ на централе по сеттингу добавлению мессаджа(понимать что это НЕ от гражданина), и там доработать)
  \i\wf-central\src\main\java\org\igov\service\controller\SubjectMessageController.java
  ResponseEntity setServiceMessage(

Курирует: Юлія Продан

**Comment by OlgaTurenko** [comment]
Принимает задачу Юлия.

**Comment by julyprodan** [comment]
@julyprodan
