### ISSUE TITLE
Компактрое отражение статусов тасок

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1391]
В продолжение реализации:
https://github.com/e-government-ua/i/issues/1388

Смотреть при загрузке списка тасок в каждом ее пункте(обьекте массива тасок) - ее вариэйблы, ища там ту что с id=saTaskStatus
а в ней могут присутствовать значения, перечисляемые через запятую.

При нахождении там значений отрисовывать справа-вверху уголки разного цвета с тултипом:
WaitAnswer - Серый (тултип "Вопрос задан от госслужащего")
GotAnswer - Красный (тултип "Ответ дан от гражданина")
GotUpdate - Желтый (тултип "Комментарий от гражданина")

(примеры отображения внизу, и там отображать пока всегжа еденичку, а позже это будет браться цифра откуда-то)

В фаербаге можно глянуть вызов списка тасок, типа такого:
https://alpha.test.region.igov.org.ua/api/tasks?filterType=unassigned&page=3

который отдает обьект типа:

```
[
......
{id: "22303013"
,url: "https://alpha.test.region.igov.org.ua/wf/service/runtime/tasks/22303013",
,assignee:null
,category:null
,createTime:"2016-10-05T20:49:04.427+03:00"
,delegationState:null
,description:null
,dueDate:null
,executionId:"22302980"
,executionUrl:"https://alpha.test.region.igov.org.ua/wf/service/runtime/executions/22302980"
,formKey:null
,id:"22303013"
,name:"User Task"
,owner:null
,parentTaskId:null
,parentTaskUrl:null
,priority:50
,processDefinitionId:"_test_sID_UA:11:21140004"
,processDefinitionUrl:"https://alpha.test.region.igov.org.ua/wf/service/repository/process-definitions/_test_sID_UA:11:21140004"
,processInstanceId:"22302980"
,processInstanceUrl:"https://alpha.test.region.igov.org.ua/wf/service/runtime/process-instances/22302980"
,suspended:false
,taskDefinitionKey:"usertask1"
,tenantId:""
,url:"https://alpha.test.region.igov.org.ua/wf/service/runtime/tasks/22303013"
,variables:[
{name: "bankIdfirstName", type: "string", value: "MockUser", scope: "global"}
,{name: "bReferent", type: "string", value: "false", scope: "global"}
,{name: "sID_Place_UA", type: "string", value: "test", scope: "global"}
,{name: "client", type: "string", value: "attr2", scope: "global"}
,{name: "mark1", type: "string",…}
,{name: "email", type: "string", value: "v-i-d-o-k@mail.ru", scope: "global"}
,{name: "sNameUnit", type: "string", value: "sNameUnit", scope: "global"}
,{name: "info", value: null, scope: "global"}
,{name: "sID_UA", type: "string", value: "1210100000", scope: "global"}
...
]}
]

```

Так вот глобальные переменные находятся именно в массиве **variables:[**

Курирует Юлия Продан @julyprodan

**Проверять так:**
Подать одну из тестовых услуг тут(обязательно ту где нужно в форме указывать свой емэил):
https://alpha.test.igov.org.ua/subcategory/1/56
запомнить ее номер заявки
потом зайти на: https://alpha.test.region.igov.org.ua (дашбоард)
под логином/паролем: tester/tester
и найти по номеру заявки ее
взять в работу
перейти в закладку в работе и там выбрав ее оставить замечание
убедиться что после этого появится букав-флаг перед названием задачи
потом зайти в историю заявки (пришедшее письмо на почту)
и устранить замечание
потом вернуться к заявке в дашборде и убедиться что первая буква пропала и появиась другая

![img_11102016_164953](https://cloud.githubusercontent.com/assets/4208821/19273512/78fed0f6-8fd5-11e6-92d2-eed01a3e9b15.png)
![img_11102016_165753](https://cloud.githubusercontent.com/assets/4208821/19273510/78fb05d4-8fd5-11e6-918c-3ff3a31b3101.png)

и отображать нужно всегда только один вид(цвет) уголочка
даже если статусов несколько
в соответствии с приоритетами:
1) ответ на замечание
2) комментарий
3) послано замечание

**Comment by donvadicastro** [comment]
Не получается пройтись полностью по STR

> Подать одну из тестовых услуг тут(обязательно ту где нужно в форме указывать свой емэил)

Выбрал _test_mailer - тут необходимо задавать mail

...

> убедиться что после этого появится букав-флаг перед названием задачи

Вот после добавления замечания визуально на этой странице ничего не поменялось. Все ли я делаю правильно?

Спасибо.

**Comment by julyprodan** [comment]
@julyprodan

**Comment by donvadicastro** [comment]
GotAnswer - Красный (тултип "Ответ дан от гражданина")
GotUpdate - Желтый (тултип "Комментарий от гражданина")

Я так понимаю оба этих статуса могут быть одновременно на одной задаче. Правильно? Или нет? Если да - какой приоритетней? Или же обе метки должны быть на задаче разного цвета?

**Comment by donvadicastro** [comment]
PR created
https://github.com/e-government-ua/i/pull/1394

**Comment by donvadicastro** [comment]
- Добавил статусы как в мокапе
- Добавил порядок отображения согласно приоритету: красный -> желтый -> серый
- Цифры везде "1" как сказано в задаче

**Comment by zolotovatatyana** [comment]
Коллеги, а ишью все же осталось в холде или выливается? 
т.к. на боевом появились "уголочки" с оповещениями:
![image](https://cloud.githubusercontent.com/assets/17428210/20479081/7ed5b08c-afe5-11e6-9d12-544137dd40b8.png)
