### ISSUE TITLE
доработать сервис /getServiceHistoryReport на опциональность загрузки данных из заявок

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1395]
- [x] 1) добавить опциональный булевый параметр bIncludeTaskInfo (по умолчанию false)
- [x] 2) когда он НЕ РАВЕН true - не вызывать региональный сервис  /service/action/task/getProcessVariableValue и не загружать данные оттуда

**Comment by OlgaTurenko** [comment]
Убедиться, что когда параметр в запросе bIncludeTaskInfo = фолс, то телефон не тянется в отчет

**Comment by GrekD** [comment]
- [ ]  bIncludeTaskInfo = True - телефон выгружается
- [ ]  bIncludeTaskInfo = False - телефон не выгружается
- [ ]  bIncludeTaskInfo не указан - телефон не выгружается
