### ISSUE TITLE
доработать сервис /getServiceHistoryReport на поддержку по умолчанию кодировки win1251

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1396]
сейчас по умолчанию отдает в UTF8

проверить так, что при загрузке периода и открытии в виндовом экселе - кирилица не видна, а должна быть видна
- [x] 1) добавить опциональный строковой параметр sCodepage (по умолчанию "WIN1251"(ну или стандартный ИД кодировки для Win1251))
- [x] 2) когда он НЕ РАВЕН умолчательному, а например UTF8 - выводить ответные данные из сервиса в этой кодировке

**Comment by annastolbova** [comment]
@annastolbova

**Comment by OlgaTurenko** [comment]
https://alpha.test.igov.org.ua/wf/service/action/event/getServiceHistoryReport?sDateAt=2016-11-01%2000:00:00&sDateTo=2016-11-05%2000:00:00

присер вызова сервиса

**Comment by Pizza1234** [comment]
Сделан комит ea471eb05a450d89e73da960d7efcb5c0abcb5cd. Залит на альфу.
