### ISSUE TITLE
доработать сервис /getServiceHistoryReport для поддержки выборки не по дате модификации а по дате создания или закрытия таски

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1398]
Добавить опциональный параметр sID_FilterDateType, который 
- [ ] 1) по умолчанию "Edit", и тогда выборка должна работать как сейчас, с обычными sDateAt и sDateTo
- [ ] 2) если задан как "Create", то выборка должна работать по аналогии с обычными sDateAt и sDateTo только выборку делать сравнивая с полем sDateCreate а не sDate, сущности. 
- [ ] 3) если задан как "Close", то выборка должна делать сравнивая с полем sDateClose а не sDate, сущности.

**Comment by OlgaTurenko** [comment]
Принимает Дарья или Август

**Comment by skuhtin** [comment]
https://github.com/e-government-ua/i/commit/57e22b32516c7aeb5890deb48e0dcedd81e58c30

**Comment by skuhtin** [comment]
https://github.com/e-government-ua/i/commit/19dbe9c34c2832667d9f4431544db7134aaa1cb2

**Comment by skuhtin** [comment]
https://github.com/e-government-ua/i/commit/36c860078a8220c361ebf0060a408c3b365842a3

**Comment by skuhtin** [comment]
протестировано на:
https://test.igov.org.ua/wf/service/action/event/getServiceHistoryReport?sDateAt=2016-09-09%2000:00:00&sDateTo=2016-10-13%2000:00:00&sID_FilterDateType=Create
https://test.igov.org.ua/wf/service/action/event/getServiceHistoryReport?sDateAt=2016-09-09%2000:00:00&sDateTo=2016-10-13%2000:00:00&sID_FilterDateType=Close
https://test.igov.org.ua/wf/service/action/event/getServiceHistoryReport?sDateAt=2016-09-09%2000:00:00&sDateTo=2016-10-13%2000:00:00

**Comment by GrekD** [comment]
@skuhtin 
третий запрос выдает все таски но по многим из них нет  sDateCreate, мне кажется что этот показатель должен быть во всех заявках/
Кроме этого, замечаний нет.

**Comment by skuhtin** [comment]
В третьем запросе поле sDateCreate пустое по таскам, созданым до дополнения сущности этим параметром. Все новые таски должны появляться с sDateCreate и sDateClose (по закрытию). Если необходимо заполнение по всем предыдущим таскам, думаю необходимо сделать это в отдельной задаче по апдейту БД

**Comment by GrekD** [comment]
поняла, нет дополнительно не нужно. спасибо!
