### ISSUE TITLE
маркер валидатор нового типа, для проверки типа на число

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1401]
Написать валидатор, сообщающий что вносить можно только цифры, в поле переменной типа long. Сейчас если в поле типа long внести буквы, поле не помечается как неправильно заполненное, но при нажатии на "Замовити послугу" выдает ошибку "Submit form" которая непонятна гражданам 

Например:

```
     ByType_NumberOnly: { // Целочисленное, по типу
        aField_Type: ['long'],
        sMessage: 'Повинно бути числом'
      }
```

работать должен и на дашборде и на централе

**Важно: Реализовывать в проекте public-js**
# zolotovatatyana

**Comment by zolotovatatyana** [comment]
29/11 протестировано на alpha
