### ISSUE TITLE
Создать базовые сущности по СЕД - ProcessSubject и SubjectGroup

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1404]
В модуле wf-base создать базовые сущности (где nID поле - праймери ключ; поля не наловые, если не указанно обратное; если это сущность-справочник, то также создать файлы .csv и организовать загрузку данных в таблицы из файлов):
- [x] 1) Сущности дерева процессов-задач
- [x] 1.1) **ProcessSubjectStatus** (справочник, наследуемся от NamedEntity)

> nID
> sName
- [x] 1.2) **ProcessSubject**

> nID
> snID_Process_Activiti
> nID_ProcessSubjectStatus (форингкей на ключ из ProcessSubjectStatus )
> nOrder
> sLogin
> sDateEdit
> sDatePlan
- [x] 1.3) **ProcessSubjectTree**

> nID
> nID_ProcessSubject_Child
> nID_ProcessSubject_Parent
- [x] 1.4) **Создать в дао методы и в контроллере соответственные сервиса:**

> - getProcessSubjects(snID_Process_Activiti_Parent[, nDeepLevel, sFind]) (0/null=all) По родительскому процессу исполнения получаем все дочерние процессы по исполнению с заданной глубиной. 
- sFind - текст поиска (искать в ФИО, по наличию вхождения текста в ФИО)

**Логика работы:**
- получаем из ProcessSubject по snID_Process_Activiti_Parent объект.
- если nDeepLevel (глубина выборки) больше одного, то из таблички SubjectGroupTree по пэрэнту вытягиваем дочерние элементы и вкладываем их в результирующий объект. проводим логику до тех пор, пока не дойдем до нужной глубины.
- если nDeepLevel = 0/null, то значит нужно сделать выборку в полную глубину. 
  **Пометка:** параметры окруженные "[]" могут быть наловыми (они не обязательные)

> - setProcessSubject(snID_Process_Activiti_Parent, sLogin[, sDatePlan, nOrder]) //Сохранить сущность
> - setProcessSubjectLogin(snID_Process_Activiti, sLogin) //Сохранить в сущность логин
> - setProcessSubjectOrder(snID_Process_Activiti, nOrder) //Сохранить в сущность порядок
> - setProcessSubjectStatus(snID_Process_Activiti, nID_ProcessSubjectStatus) //Сохранить в сущность статус
> - setProcessSubjectDatePlan(snID_Process_Activiti, sDatePlan) //Сохранить в сущность плановую дату выполнения
- [x] 2) Сущности дерева организационной иерархии
- [x] 2.1) **SubjectGroup** (наследуемся от NamedEntity)

> nID
> sID_Group_Activiti
> sChain
> sName
- [x] 2.2) **SubjectGroupTree** (составной праймери кей)

> nID
> nID_SubjectGroup_Child
> nID_SubjectGroup_Parent
- [x] 2.3) **Создать сервис getSubjectGroups(sID_Group_Activiti[, nDeepLevel, sFind])**

- sFind - текст поиска (искать в ФИО, по наличию вхождения текста в ФИО)

**Логика работы:**
- получаем из SubjectGroup по sID_Group_Activiti объект.
- если nDeepLevel (глубина выборки) больше одного, то из таблички SubjectGroupTree по пэрэнту вытягиваем дочерние группы и вкладываем их в результирующий объект до тех пор, пока не дойдем до нужной глубины.
- если nDeepLevel = 0/null, то значит нужно сделать выборку в полную глубину. 

После того, как сформировали список со всеми дочерними SubjectGroup в нужную глубину идем по этому списку и формируем уникальный список с пользователями активити из этих групп. (отрефакторить код сервиса /getUsers контроллера ActionIdentityCommonController, вынеся всю логику в отдельный сервис, а в контроллере уже вызывать этот новый созданный сервис).

Список групп кладем в результирующую мапу под ключем aSubjectGroup, список пользователей - под ключем aSubjectUser.

пример структуры ответа:

{ 
'aSubjectGroup':[группы]
'aSubjectUser':[юзеры]
}

**Comment by skuhtin** [comment]
#1404 https://github.com/e-government-ua/i/commit/36a36e0d2bb877f3bed786764f0d30bc5fb5184e

**Comment by GrekD** [comment]
1.2. и 1.3 
SubjectGroup.csv
SubjectGroupTree.csv
наполнены

**Comment by skuhtin** [comment]
#1404 https://github.com/e-government-ua/i/commit/79ea90956682567d24ae981c61e9d29e3d4af69d

**Comment by Dashchenko-Inna** [comment]
пункт 2.3 - готов

**Comment by Dashchenko-Inna** [comment]
1.4)  - готово

**Comment by skuhtin** [comment]
сервиса по п.1.1 - 1.3 дописаны

**Comment by OlgaTurenko** [comment]
Отлично. спасибо все большое!!!
