### ISSUE TITLE
Создать базовую сущность для СЕД - DocumentStep

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1405]
- [x] 1) **Создать сущности (в т.ч. использовать Liqbase):**
- [x] 1.1) **DocumentStep** //Шаг документа

> nID //номер-ИД уникальный-автоитерируемый
> sKey_Step //внутренняя строка-ИД шага
> nOrder //номер порядка (уникальный для записи в рамках одного snID_Process_Activiti)
> snID_Process_Activiti //номер-ИД процесса
- [x] 1.2) **DocumentStepSubjectRight** //Право субъекта на шаге документа

> nID //номер-ИД уникальный-автоитеррируемый
> nID_DocumentStep //номер-ИД связки с основной сущностью
> sKey_GroupPostfix //строка-постфикс группы (уникальный для записи в рамках одного nID_DocumentStep)
> sName //строка-имя права субьекта на шаге документа (роль/функция подписания/просмотра)
> bWrite //булевый, true=на запись на процесс (подпись документа)
> sLogin //логин того кто подписал/просмотрел (иначе налл)
> sDate //дата подписания/просмотра (иначе налл)
- [x] 1.3) **DocumentStepSubjectRightField** //Право субъекта по полю(маске) на шаге документа

> nID_DocumentStepSubjectRight //номер-ИД связки с родительской
> sMask_FieldID //строка-маска ИД-поля (уникальный для записи в рамках одного nID_DocumentStepSubjectRight)
> bWrite //булевый, true=на запись на поле (редактирование поля)
- [x] 2) **Создать основные методы в DAO в классе-бине DocumentsStepsService:**
- [x] 2.1) setDocumentSteps(snID_Process_Activiti,soJSON)  //Установить в сущности данные по “Образцу объекта” (п.4)
- [x] 2.2) getDocumentStepRights(sLogin, snID_Process_Activiti) //Проверить список прав шага документа у логина. (Сервис: /action/task/getDocumentStepRights)
  **Отдавать:**
- Если нет ни каких прав: возвращать эксепшин "AccessDeny"
- Если есть какие-то права:

```
{
    "bWrite":true //DocumentStepSubjectRight.bWrite
    ,"asID_Field_Read":[ //DocumentStepSubjectRightField.bWrite=false
        "sName" //DocumentStepSubjectRightField.sMask_FieldID
        , "sFamily"
    ]
    ,"asID_Field_Write":[ //DocumentStepSubjectRightField.bWrite=true
        "sReport"
    ]
}
```

**Важно:** в массивах asID_Field_Read и asID_Field_Write выдавать уже не маски а именно id-шки полей
- [x] 2.3) getDocumentStepLogins(snID_Process_Activiti) //Получить список логинов, которые подписали/ознакомились  (Сервис: /action/task/getDocumentStepLogins)
  **Отдавать:**
```
{
        "login1": { //DocumentStepSubjectRight.sLogin 
            "sDate": "2016-05-13 10:10:01" //DocumentStepSubjectRight.sDate
            , "bWrite": true //DocumentStepSubjectRight.bWrite
            , sName: "Главный визирующий" //DocumentStepSubjectRight.sName
            , sFIO: "Иванов Иван Иванович"
            , aUser: [
                {sLogin: "ivanov", sFIO: "Иванов Иван Иванович"}
                , {sLogin: "Petrov", sFIO: "Петров Петров Петрович"}
            ]
        }
        ,"login2": {
            "sDate": "2016-05-15 12:12:34"
            , "bWrite": false
            , sName: "Главный контроллирующий"
            , sFIO: "Иванов Иван Иванович"
            , aUser: [
                {sLogin: "ivanov", sFIO: "Иванов Иван Иванович"}
                , {sLogin: "Petrov", sFIO: "Петров Петров Петрович"}
            ]
        }
        ,"login3": {
            "sDate": "2016-05-15 12:12:35"
            , "bWrite": false
            , sName: "Главный исполнитель"
            , sFIO: "Иванов Иван Иванович"
            , aUser: [
                {sLogin: "ivanov", sFIO: "Иванов Иван Иванович"}
                , {sLogin: "Petrov", sFIO: "Петров Петров Петрович"}
            ]
        }
}        
```
- [ ] 3) **Создать вспомогательные методы в DAO в классе-бине DocumentsStepsService:**
  Подсказка: если где-то требуется sKey_Step, то он берется из текущего шага.
- [ ] 3.1) setDocumentStepSubjectRight(snID_Process_Activiti, sKey_GroupPostfix, bWrite) //Установить право записи, равное bWrite, для ветки к путем sKey_Step/sKey_GroupPostfix
- [ ] 3.2) cloneDocumentStepSubject(snID_Process_Activiti, sKey_GroupPostfix, sKey_GroupPostfix_New) //Клонировать ветку права записи с путем sKey_Step/sKey_GroupPostfix в ветку с путем sKey_Step/sKey_GroupPostfix_New
- [ ] 3.3) removeDocumentStepSubject(snID_Process_Activiti, sKey_GroupPostfix) //Удалить ветку права записи с путем sKey_Step/sKey_GroupPostfix
- [x] 3.4) setDocumentStep(snID_Process_Activiti[, sKey_Step)] //проставить номер шаг в поле таски с id=sKey_Step_Document
- [ ] 3.5) setDocumentStepSubject(snID_Process_Activiti, sLogin, soData_JSON) //Отметить подписание/просмотр для данного логина.
- Проверять права через getDocumentStepRights, в т.ч. проверяя - все-ли из полей saID_Field имеют права на запись, а если нет то возвращать эксепшин AccessDeny
- Проставить sLogin и sDate (текущей со временем, в формате YYYY-MM-DD hh:mm:ss.nnn)
- Ассайнуть таску и только потом ее сабмитить (данные в стандартном формате в soData_JSON)
  **ВТОРОСТЕПЕННО(можно в последнюю очередь):**
- [ ] 3.6) setDocumentStepSubjectRightField(snID_Process_Activiti, sKey_GroupPostfix, sMask_FieldID, bWrite) //Установить право записи для поля с ключом sMask_FieldID, равное bWrite, для ветки к путем sKey_Step/sKey_GroupPostfix
- [ ] 3.7) removeDocumentStepSubjectRightField(snID_Process_Activiti, sKey_GroupPostfix, sMask_FieldID) //Установить право записи/чтения для поля с ключом sMask_FieldID, в ветке с путем sKey_Step/sKey_GroupPostfix
- [x] 4) **Образец объекта:** который должен парсится и собираться на основании сущностей п.1-3:

```
{
    "_": { //DocumentStep.sKey_Step (то что с названием "_" - действует на всех шагах)
        "deps_canclers": { //DocumentStepSubjectRight.sKey_GroupPostfix
            "bWrite":true
            ,"asID_Field_Read":[ //DocumentStepSubjectRightField
                "*" //sMask_FieldID and bWrite=false
            ]
            ,"asID_Field_Write":[
                "*" //sMask_FieldID and bWrite=true
            ]
        }
    }
    , "decisioners": {
        "dep1_boss1": {
            "bWrite":true
            ,"asID_Field_Read":[
                "*"
            ]
            ,"asID_Field_Write":[
                "*"
            ]
        }
        ,"dep1_boss2": {
            "bWrite":true
            ,"asMask_FieldID_Read":[
                "*"
                "!sSystemField"
                "!sReport*"
            ]
            ,"asMask_FieldID_Write":[
                "sResolution1"
                ,"sComments1"
            ]
        }
    }
    ,"sender": {
        "dep1_middle": {
            "bWrite":false
            ,"asMask_FieldID_Read":[
                "sResolution1"
                ,"sComments1"
            ]
            ,"asMask_FieldID_Write":[
                "sReport1"
                , "sCommentExecute*"
            ]
        }
    }
    ,"checker": {
        "dep1_jun": {
                "bWrite":false
        }
    }
}

```

**Пометка: объект можно делать через мапу или JSONObject-класс.**
- [ ] 5) Создать листенер DocumentInit_iDoc со следующими функциями:
- [x] 5.1) Если в сущности DocumentStep еще нет записи с snID_Process_Activiti = ИД текущего процесса, то:
- вытягивать из из файла по пути /pattern/document/[sID_BP].json - контент и передавать его в setDocumentSteps(snID_Process_Activiti,soJSON), где [sID_BP] - это ИД БП (без версии), который в данном БП, в котором листенер,
- а в поле id=sKey_Step_Document сетить ИД первого шага sKey_Step (не того что общий "_")
- [ ] 5.2) проставить группы на юзертаску, которые соответствуют всем правам текущего шага, причем ИД группы должно быть "[sID_BP][sKey_GroupPostfix]",
  где:
- [sID_BP] - берется из текущего процесса (ИД - БП)
- [sKey_GroupPostfix] - берется из каждой записи прав текущего шага
- [ ] 6)  НЕ АКТУАЛЬНО:
- [ ] 6.1) getDocumentSteps(snID_Process_Activiti)  //Получить из сущностей строку JSON-обьект по “Образцу объекта” (п.4)
- [ ] 6.2) Если по пути /patterns/document/[sID_BP].[sKey_Step].js найден файл, то выполнять его как js...............
#

**Comment by skuhtin** [comment]
ошибочный номер задачи в пуше, не относится к текущей, сорри
