### ISSUE TITLE
BUG: Видача/заміна паспорта громадянина для виїзду за кордон: TypeError: Cannot read property 'nID_Server' of null

### ISSUE THREAD

**Issue by stormsw** [e-government-ua/i#1406]
- Перейти на [Видача/заміна  паспорта громадянина для виїзду за кордон](
https://igov.org.ua/service/176/general
)
- Вибрати регіон із списку для якого послуга не підтримується (наприклад Житомир)

Отримаете повідомлення про помилку:
TypeError: Cannot read property 'nID_Server' of null

**Comment by Koffeek** [comment]
@ stormsw Попробовал повторить. Воспроизвести не получилось. Возможно закешировались старые данные

**Comment by stormsw** [comment]
Підтверджую.
