### ISSUE TITLE
Реализовать поддержку доп. сервиса очередей ДМС - подгрузки доступных дней

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1413]
В продолжении реализации: https://github.com/e-government-ua/i/issues/1338
- [x] 1) Реализовать поддержку доп. сервиса очередей ДМС - подгрузки доступных дней:
  http://api.cherg.net/#path--workdays
  У нас это сервис:
  /flow/DMS/getSlotFreeDays
  **Параметры:**
  nID_Service_Private - уникальный числовой-ИД сервиса
  **Ответ:**
  Массив доступных дат:

```
aDate:[
"YYYY-MM-DD"
,"YYYY-MM-DD"
]
```

Где вместо "YYYY-MM-DD" - дата в формате "YYYY-MM-DD")

**ВАЖНО:** по признаку work_day: integer
0 - выходной день, 1 - рабочий день и есть свободные слоты, 2 - рабочий день, свободных слотов нет
выбирать только те что с номером 1
- [x] 2) Используя механизм п.1. - оптимизировать работу сервиса /DMS/getSlots
  (подгружать не все даты а только те по которым есть свободные слоты)

**Comment by kr110666kai** [comment]
Реализовано:

https://alpha.test.region.igov.org.ua/wf/service/action/flow/DMS/getSlotFreeDays?nID_Service_Private=428

**Comment by bvv4ik** [comment]
Спасибо огромное!
