### ISSUE TITLE
Сделать авто-доподгрузку списка с отдывами

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1415]
https://igov.org.ua/service/1397/feedback

чтоб как у Фб: внизу отображать ссылку "Показати ще", при клике на которую открывается еще 20 комментариев

**Comment by Novakanna** [comment]
на альфе:
Показаны 6 отзывов, после нажатия кнопки отображается еще +8 отзывов, после повторного нажатия отображается +17 отзывов.

**Comment by hordesalik** [comment]
@Novakanna , дело в том, что при загрузке фидбеков они проверяются на правильность контента в них, т.е. что есть имя, есть тело и т.п. И те, которые не подходят - не отображаются. Соответственно в одном запросе приходит 20 отзывов и из них N может быть неправильными. @bvv4ik обещал сделать проверку на бекенде, чтобы всегда приходили только валидные отзывы, а на фронте оставили фолбек
