### ISSUE TITLE
маркер кастомной визуализации элементов формы/таски - кастомные стили

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1418]
**Детали реализации:**
Для указанных блоков HTML, в которых размещаются поля формы или сама формы - назначать кастомный уникальный класс. для которого назначать указанные стили.
Причем стилями-коммон - дополнять стили регионального и центрального варианта отображения фронтэнда
- [ ] 1) Задача кастомных стилей для отдельных полей

```
{
 "attribute" : {
  "StyleCustomField_1" : { //Задача кастомных стилей для отдельных полей
   "aElement_ID" : ["info"], //ИД-шники полей
   ,"sCondition" : "" //опциональный, условие, при выполнении которого применять этот стиль (если не задан, то применять безусловно)
   ,"sCSS_common" : "" //задача стилей общих
   ,"sCSS_central" : "
          color: red;
          position: absolute;
          width: 100%;
          top: 100px;
          text-align: center;
" //задача стилей для централа
   ,"sCSS_region" : "" //задача стилей для региона
  }
 }
}
```

```

.bvv {
    color: red;
    position: absolute;
    width: 100%;
    top: 100px;
    text-align: center;
}
```

![image](https://cloud.githubusercontent.com/assets/4208821/19644839/a218b28e-99fa-11e6-839c-abffc9b05aa8.png)

```
.bvv {
    color: green;
    width: 100%;
    text-align: center;
}

```

![image](https://cloud.githubusercontent.com/assets/4208821/19645248/84921dd4-99fc-11e6-9db9-35efa81976c9.png)
- [ ] 2) Задача кастомных стилей для всей формы

```
{
 "attribute" : {
  "StyleCustomForm_1" : { //Задача кастомных стилей для всей формы
   ,"sCondition" : "" //опциональный, условие, при выполнении которого применять этот стиль (если не задан, то применять безусловно)
   "sCSS_common" : "" //задача стилей общих
   ,"sCSS_central" : "
          color: red;
          position: absolute;
          width: 100%;
          top: 100px;
          text-align: center;
" //задача стилей для централа
   ,"sCSS_region" : "" //задача стилей для региона
  }
 }
}
```

```
.bvv2 {
    text-align: right;
}
```

![image](https://cloud.githubusercontent.com/assets/4208821/19645348/e78d1e3e-99fc-11e6-858b-4db0a1fec7fe.png)

**Comment by GrekD** [comment]
дивіться я у бізнес-процесс вже прописала стилі, які повинні давати червоний колір
{
  "attributes": {
    "StyleCustomField_2": {
      "sCSS_common": [
        {
          "color": "red",
          "position": "absolute",
          "width": "100%",
          "top": "100px",
          "text-align": "right"
        }
      ]
    }
  }
}
але ні одно з полів не перфарбовуються у червоний
