### ISSUE TITLE
Создать сервис отправки смс

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1420]
Написать сервис /sentSms по отправке  смс сообщения в контроллере SubjectMessageCommonController.java

Создать сервис:

в котором по маске проверять а номер получателя лайф-абонент. если да - вызывать сервис по отправке смс сообщения:
POST https://api.life.com.ua/ip2sms/
Content-Type: text/xml
<message>
<service id='single' source='iGov'/>
<to>+380675605424</to>
<body content-type="text/plain">This is a sample message</body>
</message>

При успешной отправке ответ:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><status id="6613206330116" date="Fri, 28 Oct 2016 16:38:27 +0300" ext_id="123456123456"><state>Accepted</state></status>

куда в to передавать номер получателя, в body - текст сообщения.

Внимание, для тестирования выделили ограниченое количество смс, потому тестировать с умом.

@Autowired
    GeneralConfig generalConfig;
Логин, пароль и урл хранить в конфиге. Заполнить данные в файле AS.property

**Comment by annastolbova** [comment]
@annastolbova
