### ISSUE TITLE
Заменить текущий хардкод текста автоматического сообщения при подаче заявки

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1437]
Заменить текущий хардкод текста автоматического сообщения при подаче заявки на такое, что расположено по данному пути:
 wf-base/src/main/resources/patterns/mail/auto_client_notify.html 

Выхов отсылки происходит в интерцепторе

Принимает работу Павел Курбацкий

**Comment by OlgaTurenko** [comment]
Проверить нужно, что автосообщение приходит.

**Comment by zolotovatatyana** [comment]
Приходит. Но выглядит странно 
![image](https://cloud.githubusercontent.com/assets/17428210/21005857/32243058-bd3f-11e6-8712-b15c3b29b0d0.png)

**Comment by zolotovatatyana** [comment]
![image](https://cloud.githubusercontent.com/assets/17428210/21093578/45a7d67e-c05b-11e6-82c7-9d000160cfba.png)
