### ISSUE TITLE
Дашборд: Для типа поля "file" отрисовывать ссылку на скачиваемый файл

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#144]
https://test.e-gov.org.ua/admin

Для типа поля "file" отрисовывать ссылку на скачиваемый файл (т.к. сейчас есть поле но там отражается ИД, использовавшийся для загрузки файла),
вместо того чтоб эту ссылку отрисовывать в конце всех полей.
(например: Файл: ScreenHunter_102 Apr. 23 16.59.jpg file)

Так-же передавать в сервис для скачивания "download_file_from_db" еще параметр: nFile и передавать туда порядковый номер поля типа file в рамках этого задания.

**Comment by alexeybondarenko** [comment]
не совсем понятна задача. сейчас в имени id аттача. что поставить взамен?

**Comment by bvv4ik** [comment]
сейчас вообще ни как не предусмотрена обработка полей типа file

а давай голосом в скайп?
мой: belyavtsevw

**Comment by bvv4ik** [comment]
нужно просто начать обрабатывать этот тип поля, и во всех полях где оно будет встречаться - отрисовывать такую-же ссылку на загрузку файла, как сейчас в единственном экземпляре в самом низу.. перед кнопками принятия в работу или отработки...

**Comment by alexeybondarenko** [comment]
там тип поля string. если будет возвращаться file, то сможет обработать. а пока только остается прогонять значение по массиву вложений и догадываться, что это файл. не совсем хороший вариант
