### ISSUE TITLE
Устранить дубли атачей на юзертаске.

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1441]
Устранить дубли атачей на юзертаске.
описание проблемы: 
https://docs.google.com/document/d/1z-BcWLWHUUlJwW_EAB2huno8DLgIHjXjq4exbQCNUjw/edit

https://docs.google.com/document/d/1KY1Pvncs8GyNV5V7RnhXI9-WycGVgB-pvFk37xeinV4/edit?usp=sharing

Это слушатель FileTaskInheritance.java метод addAttachmentsToCurrentTask. перед добавление к юзертаске атача делать проверку а нет ли еще такого атача на этой юзертаске.

**Comment by agerman-ua** [comment]
@agerman-ua
