### ISSUE TITLE
Пропадают заявки. Письмо приходит о успешном заказе.

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1443]
Пропадают заявки. Письмо приходит о успешном заказе.  Сделать так, чтоб если услуга не заказалась, то письмо не приходило и ошибка сохранялась на сервисе ошибок

**Comment by zolotovatatyana** [comment]
https://alpha.test.igov.org.ua/service/755/general 
на указываемый электронный адрес приходит письмо с номером заявки
