### ISSUE TITLE
Не давать уточнять Энумы

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1444]
На дашборде чиновника не давать уточнять энумы.

ДОЧИНИТЬ Сделать уточнение определенных полей чиновником. Не работают типы textArea, long, date, double  в ТЗ по редизайну https://docs.google.com/document/d/1dfbCGDLV-ErbO3A3_CGngj6yjSmHdJSbhizXr3WemgY/edit#  #СвидраньМаксим  
Описание: https://docs.google.com/document/d/1MeObXsbMe3uqck0r_SU7-tO9ROEufzfhtyUgg2KxwOw/edit?usp=sharing

**Comment by antonlegkiy** [comment]
"ДОЧИНИТЬ Сделать уточнение определенных полей чиновником. Не работают типы textArea, long, date, double в ТЗ по редизайну" - работало. 
"На дашборде чиновника не давать уточнять энумы." - в связи с тем что по ишью #751 поле enum переделывалось в string возникала данная ситуация. попаравил. тестировать можно на услуге https://alpha.test.igov.org.ua/service/3/general - там все типы полей.

**Comment by msvidran** [comment]
Протестировано на тестовом процессе https://alpha.test.igov.org.ua/service/3/general
textArea, long, date, double - уточняются, enum - для уточнения скрыт. Можно в версию.
