### ISSUE TITLE
Пока заявка не взята в работу на дашборде чиновника необходимо скрывать файлы присоединённые к заявке.

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1446]
Пока заявка не взята в работу на дашборде чиновника необходимо скрывать файлы присоединённые к заявке. Для непонятливых чиновников внизу, вместо файлов, вывести инфу типа "для отримання доступу до завантажених файлів необхідно взяти звернення в роботу"

**Comment by agerman-ua** [comment]
@agerman-ua

**Comment by agerman-ua** [comment]
Алексей. 
Пожалуйста, если можно, хоть какой-то коммент порождать для привлечения внимания в таких случаях.
А то почти случайно увидел изменения в ишью. Письмо не пришло. 
Флажок письмо не порождает для таких как я.
Тестирую.

**Comment by agerman-ua** [comment]
Функционально всё работает. 
Алексей прошу выделить сообщение, как минимум, жирным шрифтом. А то совсем невыразительно получилось.

**Comment by agerman-ua** [comment]
Отлично, финальные правки (по согласованию с Павлом).
- [ ] 1. Изменяем текст:
с 
"**Для отримання доступу до прикріпленних додатків, необхідно прийняти заявку в роботу**" 
на 
"**Щоб переглянути додатки необхідно взяти звернення в роботу**"
- [ ] 2. Центруем надпись.

**Comment by agerman-ua** [comment]
Замечаний по реализации нет. Спасибо.
