### ISSUE TITLE
Дореализовать поиск по архиве.

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1447]
В wf-region дореализовать поиск по архиву.

В сервисе /getProcesses в wf-region реализовать поиск по sID_ также в верхнем и нижнем регистре. В идеале мочь искать по началу слова (в случае, если задано более 3-х символов, иначе поиск не производить).

Тестировать на alpha-old. там есть данные
Пример вызова сервиса:

https://alpha-old.test.region.igov.org.ua/wf/service/analytic/process/getProcesses?sID_=Д-583/1

**Comment by McTrYYn** [comment]
Добавил две возможные реализации, проверить их роботу локально нету возможности

**Comment by OlgaTurenko** [comment]
Спасибо большое, Виталий! Мы протестируем и сюда о результате отпишемся.

**Comment by msvidran** [comment]
При поиске в верхнем регистре Д-583/1  заявку находит
![image](https://cloud.githubusercontent.com/assets/7354990/21190416/58436160-c22a-11e6-9642-037f3c62053d.png)

При поиске в нижнем регистре д-583/1 не находит
![image](https://cloud.githubusercontent.com/assets/7354990/21190519/bcdad4e6-c22a-11e6-89bf-3794568ac150.png)

**Comment by smoktii-igov** [comment]
А если несколько заявок удовлетворяют поиску, то как перейти на вторую, третью и т.д.?

**Comment by OlgaTurenko** [comment]
Кирилл, на это отдельная задача стоит. Алексей ею занимается на фронте. Это бековая задача. Тут делаем только поиск по новым регистрам.

**Comment by McTrYYn** [comment]
Есть вероятность того что оно не задеплоилось на нужный сервер?

**Comment by OlgaTurenko** [comment]
а Вы ж в ветку тест изменения пушили?

**Comment by McTrYYn** [comment]
протестировал, остальсь несколько правок. Вопрос, если sID_ меньше трёх символов, то ничего поиск не происходит, если больше то по полному  sID_ или по первым трём символам?

**Comment by OlgaTurenko** [comment]
продеплоили, но все равно не ищет. Если у Вас логи какие-то есть, то на альфе можно их глянуть (чтоб на 100% убедиться, что Ваша правка доехала, хотя должна была доехать, если в ветку тест пушили)

**Comment by OlgaTurenko** [comment]
если 3-и символа - даже не пытаемся искать, возвращаем, как буд-то ничего не нашли. если задачи 3-и и более - то ищем их в начале. тоесть если ид к примеру Д-112, то задавая в поиске Д-1 или Д-11 или Д-112 - то находим, задавая в поиске Д или Д- или 112 - то не находим, так как ищем только по началу слова.

**Comment by msvidran** [comment]
Поиск работает:
- если вводим д-583/1 находит заявку **Регистрационный номер	Д-583/1**
- если вводим Д-112 или д-112 находит заявку **Регистрационный номер	Д-112**
- если вводим Д-1 находит заявку **Регистрационный номер	Д-1**


### поиск заявок значительно увеличился по времени !!! 
На данный момент поиск одной заявки занимает около 1 мин и более

**Comment by McTrYYn** [comment]
Всё что можно было оптимизировать в контроллере я оптимизировал. При выводе только первого элемента удовлетворяющего запрос поиска временя поиска не уменьшаеться .

**Comment by OlgaTurenko** [comment]
спасибо!!
