### ISSUE TITLE
Починить поисковик

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1449]
На региональном дашборде чиновника починить поисковик:

https://docs.google.com/document/d/1fp-kH1LBcfNWZ93bzNocXJ9t5P8OKmtmL0E943xQE_c/edit

Также доработать:
1) Индикация порядкового номера текущей заявки (Отражаем текущую запись на которой позиционируемся как "3/4" в окошка найденных элементов)
2) Аналогичную систему поиска переносим на закладку "Необроблени"

**Comment by OlgaTurenko** [comment]
![image](https://cloud.githubusercontent.com/assets/10909557/21002358/0e74d6d2-bd2e-11e6-8270-7be1f2ce1303.png)

на беке видим, что ид-ки обеих возвращает.

**Comment by GFalcon-UA** [comment]
Чтоб перейти к следующей заявке - на поле поиска нужно нажать клавишу Enter (не удаляя предыдущего поискового запроса).
После просмотра последней найденной заявки - следующая будет открыта первая заявка в списке перебора.
Если поисковый запрос был изменен, но результат поиска окажется идентичен предыдущему, то переход к следующей заявке будет происходить далее по циклу перебора.

**Comment by smoktii-igov** [comment]
Согласовано:
1. Отражаем текущую запись на которой позиционируемся как "3/4" в окошка найденных элементов
2. Аналогичную систему поиска переносим на закладку "Необроблени"

Проверено и ОК
1. Поиск на закладке "В работе" есть и работает. 
2. Переход работает.
3. Поиск регистронезависимый

**Comment by smoktii-igov** [comment]
Неестественній порядок поиска - запись первая в списке, а находится третьей
![image](https://cloud.githubusercontent.com/assets/17428200/21501864/3af5dd7a-cc54-11e6-88d4-77116daf217f.png)

**Comment by GFalcon-UA** [comment]
Замечания поустронял. Прошу протестировать повторно

**Comment by MalaOleksandra** [comment]
Заявки из папки Необробленнi отображаются в папке Документи. [S3]

Окружение: Google Chrome, Mozilla FireFox, IE (version 11)
Шаги:
1. Неотработанные заявки отображаются в папке Документи
https://www.screencast.com/t/yRkYY9uV2y

2. Если перейти из папки Необробленнi в папку Документи и вернуться назад, то слева от tasks-list-holder будет отображаться содержимое заявки, но не в полном объеме
https://www.screencast.com/t/Hq4RuR6YkJIE

**Comment by antonlegkiy** [comment]
Данная ситуация только на альфе, отношения к поисковику она не имеет.

**Comment by GFalcon-UA** [comment]
На вкладку "Документи" сейчас сливаются все заявки из "Не оброблені" и "В роботі" у которых в `processDefinitionId` есть значение `doc` https://github.com/e-government-ua/i/issues/1468
![image](https://cloud.githubusercontent.com/assets/13604023/22462215/15a48216-e7b5-11e6-8ea6-0273f65b57a3.png)

Находять на вкладке "Не оброблені" часть полей, который должны быть доступны только исполнителю - скрывается. На вкладке "Документи" - это ограничение сняли.
Вот то, что счетчик не совсем адекватно работает - это я согласен - это да. Но этот баг относится не к этому issue

**Comment by smoktii-igov** [comment]
Принципиально механизм работает. 
Есть замечания к работе поисковика, когда список заявок больше, чем один экран просмотра.

См. https://docs.google.com/document/d/1amF9EdbiBU5hJyxEnnfrAFVLGq9ld5RHJfskCoJiTFc/edit

**Comment by smoktii-igov** [comment]
В РЕЛИЗЕ, все работает в выполненной части
