### ISSUE TITLE
Дашборд: В названии задания (в списке), вместо "ivFrank_mvk_2:3:25023" отрисовывать нормальное название услуги, как в остальных задачах.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#145]
В названии задания (в списке), вместо "ivFrank_mvk_2:3:25023" отрисовывать нормальное название услуги, как в остальных задачах.

**Comment by AndrewLvov** [comment]
В случае 
"ivFrank_mvk_2:3:25023" запрос к '/api/processes' вернул список, в котором такого элемента нет.
Это проблема на бек-енде или такая ситуация возможна и не возвращать ничего ?

**Comment by bvv4ik** [comment]
нужно просмотреть какой на самом деле в реальности вызывает сервис '/api/processes' 
и подправить запрос так, чтоб отдавался полный список, в т.ч. этот пункт. т.к. если пункт есть, значит в реальности он должен быть гдето в базе (в общем списке создававшихся сервисов).

вот тут можно глянуть возможные параметры реальных сервисов активити(в ноде у нас всего-лишь проксирующий бэк): http://www.activiti.org/userguide/#_forms

**Comment by AndrewLvov** [comment]
Исправлено @bvv4ik , закрываю.
