### ISSUE TITLE
Доработать сущность AttributeName

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1450]
1) На аналитическом сервере (модуль iGov-UA Analytic) доработать сущность AttributeName. Добавить поле к сущности и таблице nOrder. Проставить очередность согласно файла (графа Стало) https://docs.google.com/spreadsheets/d/1u7JtnQIXHfVZVQ7AN9tYxKhAAR3dI4doNi5e0zz6qMM/edit#gid=1211536646 . 
Атрибуты, которые не отображаем (зачеркнуты), имеют ид = -1.  Самый первый имеет порядок = 1

**Comment by OlgaTurenko** [comment]
https://alpha-old.test.region.igov.org.ua/wf/service/analytic/process/getProcesses?sID_=%D0%94-583/1 ссылка для тестирования

**Comment by OlgaTurenko** [comment]
я задачку протестировала. все ок

**Comment by msvidran** [comment]
![image](https://cloud.githubusercontent.com/assets/7354990/21049539/1143cb84-be1e-11e6-8f16-7a2eea1f5292.png)
а у меня вот так выводит.
