### ISSUE TITLE
Отображать элементы согласно их порядка

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1451]
При поиске в архиве на дашборде отображать атрибуты из списка согласно их порядка, который реализован в задаче #1450 . Атрибуты с порядком = -1 не отображать. Самый верхний атрибут в списке имеет порядок 1, следующий 2 и тд

**Comment by OlgaTurenko** [comment]
сссылка для проверки, что готова бековая часть: https://alpha-old.test.region.igov.org.ua/wf/service/analytic/process/getProcesses?sID_=%D0%94-583/1

**Comment by GFalcon-UA** [comment]
Юзер kermit - перегружен своими группами, поэтому тестировать под юзерами, которые чуть более скромнее (я входил под tester)

**Comment by msvidran** [comment]
атрибуты должны расположены в порядке как указано в таблице https://docs.google.com/spreadsheets/d/1u7JtnQIXHfVZVQ7AN9tYxKhAAR3dI4doNi5e0zz6qMM/edit#gid=1211536646 в разделе "СТАЛО"
а на данный момент выглядит вот так
![image](https://cloud.githubusercontent.com/assets/7354990/21099190/6a383e74-c075-11e6-895a-f824adb75486.png)

**Comment by GFalcon-UA** [comment]
Оно не было продеплоено. Сейчас прошу протестировать повторно

**Comment by msvidran** [comment]
После тестирования заказчиком выявлен ряд доработок (не блокирующих):
- в поля выделены красным подставлять значения из справочников https://docs.google.com/spreadsheets/d/1u7JtnQIXHfVZVQ7AN9tYxKhAAR3dI4doNi5e0zz6qMM/edit#gid=1211536646
- т.к. поиск заявки значительно увеличился - нужно какое-то колесико поставить при поиске и выводить сообщение, если не найдено

**Comment by OlgaTurenko** [comment]
это уже сделаем не в рамках этой задачки
