### ISSUE TITLE
Доработки в разделе "Мой журнал"

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1452]
Доработки в разделе "Мой журнал"

- [x] #приоритет1 починить кнопку ликпея в моем журнале: отображается, но не кликабельна - кнопки оплаты Ликпей в некоторых письмах неактивны (например почта укрнет режет графику) и тогда невозможно оплатить  услугу кроме как закрыть заявку и подать новую с новым почтовым ящиком 10.11.2016 #АвгустГерман

- [x] #приоритет1 починить кнопку "отменить заявку" из писем в моем журнале: отображается, но не кликабельна Когда долго не отрабатывается заявка начинаются эскалации и в случае с МРЭО обычно люди сами идут и получают услугу, а отменить не получится если кнопка 14.11.2016 #АвгустГерман

- [ ] в письмах в "моем журнале" необходимо добавить визуализацию и возможность загрузки аттачей отправленных в письме заявителю как гарантированный порталом вариант получения вложений 10.11.2016 #АвгустГерман

- [x] #приоритет2  Кнопки выставления оценки из письма в Моем журнале не кликабельны - должно перебрасывать на страничку Видгука #ЗолотоваТатьяна

**Comment by OlgaTurenko** [comment]
Тоесть после переноса моего журнала из отдельного окна в див-диалог перестали быть кликабельными кнопки. необходимо починить.

**Comment by agerman-ua** [comment]
@agerman-ua

**Comment by agerman-ua** [comment]
> в письмах в "моем журнале" необходимо добавить визуализацию и возможность загрузки аттачей отправленных в письме заявителю как гарантированный порталом вариант получения вложений  10.11.2016 #АвгустГерман
Только этот пункт не выполнен и будет реализован наверное не в ближайшее время.
Предлагаю закрыть это ишью целиком и отдельно открыть только данный пункт.
Данный функционал изначально был предусмотрен в журнале гражданина и является очень востребованным.
