### ISSUE TITLE
Починить выгрузку статистики. 

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1453]
Починить выгрузку статистики. 

Реализовать 3-й пункт из файла:
https://docs.google.com/document/d/1zcej2SZxw9l5UHTIJtU6zEFzkyEyhUIJRksxsLXfG8I/edit

3.1. разделитель какой-то странный получается - надо чтоб был точка с запятой, а при через открытии через ексель - сразу разделял данные на столбцы
3.2. дата выгружается не в заданном мною формате

**Comment by GrekD** [comment]
выбрала диапазон выгрузки 16-18.12.2016
выбрала БП - мінюст - службовий лист
выдало ошибку:

> Не удается получить доступ к сайту
> Веб-страница по адресу https://alpha.test.region.igov.org.ua/api/reports/export?sID_BP=doc_justice_171&sID_State_BP=null&sDateAt=16/12/2016&sDateTo=18/12/2016&saFields=${nID_Task};${sDateCreate};${area};${bankIdinn};;;${bankIdlastName}%20${bankIdfirstName}%20${bankIdmiddleName};4;${aim};${date_start1};${date_stop1};${place_living};${bankIdPassport};1;${phone};${email}&sID_Codepage=win1251&nASCI_Spliter=18&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=dohody.dat&bHeader=false&saFieldsCalc=&saFieldSummary=&, возможно, временно недоступна или постоянно перемещена по новому адресу.
> ERR_INVALID_RESPONSE

**Comment by OlgaTurenko** [comment]
просьба глянуть чего не работает сервис

**Comment by OlgaTurenko** [comment]
сервис работает. неверно вызывает сервис клиент. создала таску на починку: https://github.com/e-government-ua/i/issues/1469

**Comment by sergiymatyushko** [comment]
Добрий день Ольга.
С прошедшими праздниками.
Я сейчас на собеседовании. Смогу принять в работу только вечером.

С уважением,

17 янв. 2017 г. 9:33 пользователь "Olga" <notifications@github.com> написал:

**Comment by OlgaTurenko** [comment]
спасибо!

**Comment by OlgaTurenko** [comment]
удачи на собеседовании :)

**Comment by sergiymatyushko** [comment]
Ольга, можете зайти в скайп? не хотелось бы захламлять git перепиской

2017-01-17 11:16 GMT+02:00 Olga <notifications@github.com>:
