### ISSUE TITLE
Реализовать собственную опциональную предварительную конвертацию HTML в PDF при наложении ЭЦП на подаваемую заявку

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1456]
Сейчас HTML с заполненной формой сразу передается в сервис БанкИД для конвертации в ПДФ и наложение ЄЦП

- Нужно чтоб вначале мі собственнім механизмом производили конвертацию (взять из Дашборда и поместить в public-js), и потом уже готовый ПДФ отсылать на подписание.

- Нужно выполнять такую собственную конвертакию только в том случае, если в поле с id=form_signed в атрибуте name, в третьем разделе(разделенном через ";" присутствует параметр(параметры разделяются ",") -  "bPrintFormFileAsPDF=true"

Принимает работу Август

**Comment by agerman-ua** [comment]
@agerman-ua - наблюдатель

**Comment by agerman-ua** [comment]
тестовая услуга на альфе
https://alpha.test.igov.org.ua/service/1416/general
видна под tester

**Comment by GFalcon-UA** [comment]
Я не вижу, где [в тестовом BPMN](https://github.com/e-government-ua/i/blob/test/wf-region/src/main/resources/bpmn/autodeploy/_test_autosign_printform_ECP.bpmn) в поле `form_signed` взять параметр `bPrintFormFileAsPDF`

**Comment by agerman-ua** [comment]
Добавил параметр **bPrintFormFileAsPDF=true**

**Comment by agerman-ua** [comment]
Протестировано. Переводит намного лучше чем ранее использовавшийся. Очень хорошо что не потребуется срочный рефакторинг автофайлов с ЭЦП в ранее созданных процессах.
