### ISSUE TITLE
Поддержка на бэке прикрепления файлов(type=file) в новом концепте, с поддержкой таблиц

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1461]
- [x] 1) Создать класс TaskAttachVO со всеми полями, формирующими в итоге JSON-объект вида:
```
{
"sID_StorageType": "Redis" //тип хранилища
, "sKey": "jHG986-7gOO-ho&H07-Hdfgy4-554yws" //ключ контента
, "sVersion": "2016-12-16" //строка-версия
, "sDateTime": "2016-12-16 23:23:48.001" //строка-дата и время (загрузки)
, "sFileNameExt": "passport.pdf" //строка названия и расширения файла
, "sContentType": "html/text" //строка с типом контента (по стандартам)
, "nBytes": 2345235 //Чисол байтов, которые занимает контент
, "bSigned": true //наложено или не наложено ЭЦП
, "aAttribute": [ //массив атрибутов
   {
      sID:"sVar1" //строка-ИД атрибута
      , sValue:"value1" //строка значения атрибута
   }
   , {
      sID:"nCount" //строка-ИД атрибута
      , sValue:"12" //строка значения атрибута
   }
]
}
```

- [x] 2) При отработке листенера FileTaskUploadListener - реализовать параллельную поддержку альтернативного варианта
- [x] 2.1) Если в значении(value) поле с типом file или table вместо(как обычно сейчас) ИД-шки Редис-а(из чисел и символов) или Атача(числа) будет обнаружен сериализованный JSON-обьект, вида п.1, то обрабатывать его иначе, нежели раньше (должен быть отдельный участок-иф, переключающий на новый метод обработки, а не доращивать в старом)
- [x] 2.2) в кейсе п.2.1  если тип хранилища Редис ("sID_StorageType": "Redis"), то переносить контент в Монгу ("sID_StorageType": "Mongo"), обновлять sID_StorageType, sKey и сохранять обновленный сериализованный объект в то-же значение этого-же поля.
- [x] 2.3) Точно так-же анализировать поле типа file для таблиц
Таблицы хранятся тоже в сериализованых объектах JSON, в виде атачей(теперь могут храниться и в новом виде, в рамках нового концепта), ссылки на которые размещаются в полях с типом table.
Ишью, по которой реализовывались таблицы: https://github.com/e-government-ua/i/issues/1353
Пример объекта с таблицей:
```
{
   "aRow":[
      {
         "aField":[
            {
               "id":"sName"
               ,"name":"Название"
               ,"type":"string"
               ,"requred":"true"
               ,"writible":"true"
               ,"value":"Имя1"
            }
            ,{
               "id":"nSum"
               ,"name":"Сумма"
               ,"type":"long"
               ,"requred":"true"
               ,"writible":"true"
               ,"value":"Сумма1"
            }
         ]
      }
   ]
}

```
Для полей таблицы где "type":"file" применимо все то-же, что и для п.п. 2.1 и 2.2
т.е. десериализовать контент атача с таблицей, найти в нем типы file и отрабатывать их так-же, сохранив потом обратно все в контент аттача/сериализованый объект таблицы (но уже под новым 
ИД), и обязательно обновив значение поля типа table(обновленным сериализованным JSON-обьектом)

Пример парсинга обьекта с таблицей в методе:
public void setProcessSubjects(Map<String, String> mParam, String snProcess_ID){
Класса:
org.igov.service.business.process.ProcessSubjectService

- [x] 3) Для **выгрузки(довнлоада)** файлов-атачей по новому концепту реализовать отдельные сервис (по образцу существующего: /download_file_from_db , скопировав его)
Название:
/getTaskAttach
Параметры:
nID_Task //номер-ИД задачи
sID_Field //строка-ИД поля (типа file или table)
В ответ так-же отдавать поток мультипартфайла как и в образце

- по sID_Field - вытягивать сериализованный объект образца п.1, и по нему уже получать сам контент

- [x] 4) Для **загрузки(аплоада)** файлов-атачей по новому концепту реализовать отдельный сервис, с общими параметрами:
Параметры:

> nID_Task //номер-ИД задачи
> sFileNameExt //строка названия и расширения файла
> bSigned //наложено или не наложено ЭЦП (булевый) //опциональный (по умолчанию false)
> sID_StorageType //Строка-ИД типа хранилища *Redis* или "Mongo" //Опциональный (по умолчанию ("Mongo")
> saAttribute_JSON //массив атрибутов в виде сериализованного обьекта JSON вида:
> 

```
[ //массив атрибутов
   {
      sID:"sVar1" //строка-ИД атрибута
      , sValue:"value1" //строка значения атрибута
   }
   , {
      sID:"nCount" //строка-ИД атрибута
      , sValue:"12" //строка значения атрибута
   }
]
```
 //опциональный (по умолчанию пустой массив: [] )

а в ответ отдавать стандартный JSON-обьект вида п.1
при этом остальные поля проставлять так(и соответственно и сохранять контент так):
"sKey" = (полученный ключ контента)
"sVersion" = "2016-12-16" (текущая версия способа сохранения)
"sDateTime" = (такущая дата и время сохранения в формате "2016-12-16 23:23:48.001")
"nBytes" = (Число байтов, которые занимает контент)

- [x] 4.1)  Дополнить метод возможностью **загрузки байтового** контента по образцу существующего: /upload_file_as_attachment , скопировав его, с названием: /setTaskAttach (так-же метод POST)
**Дополнительным параметром:**

> так-же в параметре MultipartFile file передавать контент
т.е. если file<>null, то отрабатывать по этой схеме (как мультипартфайл), иначе идем по п.4.2

- [x] 4.2)  Дополнить метод возможностью **загрузки стрингового** контента по образцу существующего: /setTaskAttachment , скопировав часть его, кода
**Дополнительными параметроми:**

> sContentType //строка-MIME тип отправляемого файла //опциональный (по умолчанию = \"text/html\")

в таком случае считывать пришедшую строку из тела запроса (если не идем по сценарию п.4.1

**Comment by GrekD** [comment]
на альфе все корректно, сегодня ожидается мерж в Дельту, где еще аналитики будут юзать около недели новый сервис, может всплывут доработки.
