### ISSUE TITLE
Дашборд: Сделать page-нацию для списка задач или скролл

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#147]
а то с длинным списком сложно работать.

**Comment by alexeybondarenko** [comment]
Взял в работу

**Comment by alexeybondarenko** [comment]
Предлагаю добавить поиск по таскам

**Comment by bvv4ik** [comment]
alexeybondarenko : Спасибо, только все-же, наверно лучше скролл(для сразу загруженного полного списка)... т.к. у нас уже реализовано запоминание выбранной таски при переходе из таба в таб. И если после перехода мы опять будем оказываться на первой странице, то это все будет утеряно

**Comment by alexeybondarenko** [comment]
Добавил
