### ISSUE TITLE
Доработать сервис /getSubjectGroups

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1471]
Доработать сервис /getSubjectGroups. Добавить в него по аналогии с сервисом, который отдает задания по документу /getProcessSubjectTree флаг Boolean bIncludeRoot с дефолтом true. Если тру, то к ответу добавлять рутовый элемент.

Во вторую очередь реализовать /getSubjectGroupTree, который будет работать также, как /getSubjectGroups, но возвращать ответ в виде дерева.

**Comment by OlgaTurenko** [comment]
Виталий, спасибо за разработку этой задачки!!! Если позволите ее доделает другой человек, так как очень она нам на сегодня горит (стопорит доработку на фронте). А я Вам могла бы новую (такую чтоб не срочная была) подобрать. Вы позволите?

**Comment by McTrYYn** [comment]
Хорошо, /getSubjectGroups готов и запушен а за /getSubjectGroupTree ещё не брался
