### ISSUE TITLE
Реализовать расширенный функционал фильтра

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1475]
- [x] 1) Создать сервис getFields - получения полей БП, на базе сервиса /getBPs, с теми-же параметрами запроса, только отдавая в ответ массив полей, содержащихся в полученном списке БП.
Например:
```
[
   {
      "sID" :"bankIdFamily"
      , "sName" :"Прізище"
      , "sID_Type" :"string"
   }
   ,{
      "sID" :"bankIdName"
      , "sName" :"Ім'я"
      , "sID_Type" :"string"
   }
]

```

- [x] 2) Доработать сервис /getTasks - получения списка доступных пользователю задач,
добавив в него опциональный параметр: soaFilterField в который можно передавать сериализованный JSON-объект с полями и их значениями, по которым нужно фильтровать задачи (т.е. если объект задан, то отдавать только те задачи, в которых есть указанные поля с такими значениями)
Пример объекта:

```
[
   {
      "sID" :"bankIdFamily"
      , "sName" :"Прізище"
      , "sID_Type" :"string"
      , "sValue" :"Біляв*"
   }
   ,{
      "sID" :"bankIdName"
      , "sName" :"Ім'я"
      , "sID_Type" :"string"
      , "sValue" :"Волод*"
   }
]

```

где в значении если указан символ "*" - это означает маска "любой текст"

Тестировать на одном из БП МинЮст-а (по СЕД)

Куратор Дарья Грек

**Comment by ASkosyr** [comment]
Примеры вызова для 2 пункта

https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&nSize=1&soaFilterField=[{%22sID%22:%22taskDefinitionKey%22,%22sName%22:%22taskDefinitionKey%22,%22sID_Type%22:%22string%22,%22sValue%22%20:%22usertask*%22}]&nSize=1

https://test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&nSize=1&soaFilterField=[{%22sID%22:%22taskDefinitionKey%22,%22sName%22:%22taskDefinitionKey%22,%22sID_Type%22:%22string%22,%22sValue%22%20:%22usertask1%22},{%22sID%22:%22processInstanceId%22,%22sName%22:%22processInstanceId%22,%22sID_Type%22:%22string%22,%22sValue%22%20:%2223288469%22}]&nSize=1

**Comment by ASkosyr** [comment]
Вызов 1 пункта

https://test.region.igov.org.ua/wf/service/action/task/getBPs?sLogin=kermit

**Comment by antonlegkiy** [comment]
добрый день, подскажите, не выходит отфильтровать нужную заявку, запрос такой:
https://alpha.test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=kermit&soaFilterField=%5B%7B%22processInstanceId%22:%2225573287%22%7D%5D

всего заявок 4шт, только у одной processInstanceId=2225573287, но почему в ответ приходят снова 4 заявки. подскажите что я делаю не так.

**Comment by antonlegkiy** [comment]
и по второму сервису подскажите плз.
https://alpha.test.region.igov.org.ua/wf/service/action/task/getBPs?sLogin=kermit
по данному запросу возвращается 4бпшки которые доступны кермиту.
https://alpha.test.region.igov.org.ua/wf/service/action/task/getFields?sLogin=kermit
а под данному уже поля. но почему-то в ответ приходят только 3 поля, хотя на самом деле их больше и почти во всех бп они разные (но не во всех :) ).

**Comment by GrekD** [comment]
**getFields** возвращает пустой массив и **getTasks** возвращает тоже вроде пустой объект
https://alpha.test.region.igov.org.ua/wf/service/action/task/getFields?sLogin=justice_common
https://alpha.test.region.igov.org.ua/wf/service/action/task/getTasks?sLogin=justice_common

**Comment by GrekD** [comment]
если запустить с параметром bDocOnly=false, то результат есть
https://alpha.test.region.igov.org.ua/wf/service/action/task/getFields?sLogin=justice_common&bDocOnly=false
возвращает вроде как надо
но ты прав:
нам нужно чтоб фильтр работал на любой процесс - неважно документ это или обычный процесс
т.е. по идее сервис getFields должен работать без флага bDocOnly=false

**Comment by GrekD** [comment]
Саша спасибо за реализацию!
