### ISSUE TITLE
Реализовать поддержку расширенного фильтра на базе нового сервиса

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1476]
На основании сервиса получения списка полей п.1. и доработанного сервиса получения списка задач п.2 в ишью https://github.com/e-government-ua/i/issues/1475

- [x] 1) Использовать в дашборде теперь подгрузку списка задач только используя сервис /getTasks 
- [x] 2) добавить гибкий фильтр по полям, где через автокомплит ищется поле (из сервиса п.1) , по его названию (где в выпадающем списке слева идет название а справа, в скобках, его ИД-шник, а будучи выбранным правее в поле вводится его значение. Причем еще правее, если sType=String, нужно выводить комбобокс со значениями "Начиная с"(по умолчанию), "С присутствием", "Заканчивая на", "Равно", и в зависимости от выбранного пункта к значению при отправки его в сервис(п.2) добавляется "*" (справа, слева и справа, справа, соответственно)
Если тип не string то комбобокс не отображать и "*" не добавлять
- [x] 3) выбрав в автокомплите поле - добавлять ниже возможность выбрать еще одно поле  с фильтром, и выбров в нем - так-же ниже еще одно добавлять. Убирать любое из них должна быть возможность крестиком правее этого поля.
4) Выбранные фильтры запоминать в ЛокалСтораж, и при обновлении страицы восстанавливать.- [ ] 

Тестировать на одном из БП МинЮст-а (для СЕД)

Курирует: Дарья Грек

**Comment by GrekD** [comment]
Антон, посмотри, плиз фильтры - не подтягивается сейчас ничего
я знаю что просила временно для демонстрации в мин.юсте поменять сервис, верни пожалуйста, тот который был (getTasks)
так же прошу учесть еще вот это:

не выводить в список поля с типом sType=markers, file,label,queueData,invisible,table,fileHTML,textArea
