### ISSUE TITLE
Перевести централ на взаимодействие с новыми сервисами по работе с атачами

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1477]
Реализован на беке новый сервис (вызывается постом):

https://alpha.test.region.igov.org.ua/wf/service/object/file/setAttachment?nID_Process=25527501&sFileNameAndExt=test.txt

Возможные параметры сервиса:
@ApiParam(value = "номер-ИД процесса", required = true) @RequestParam(value = "nID_Process", required = true) String nID_Process,
            @ApiParam(value = "наложено или не наложено ЭЦП", required = false) @RequestParam(value = "bSigned", required = false, defaultValue = "false") Boolean bSigned,
            @ApiParam(value = "cтрока-ИД типа хранилища Redis или Mongo", required = false) @RequestParam(value = "sID_StorageType", required = false, defaultValue = "Mongo") String sID_StorageType,
            @ApiParam(value = "массив атрибутов в виде сериализованного обьекта JSON", required = false) @RequestParam(value = "aAttribute", required = false) List<Map<String, Object>> aAttribute,
            @ApiParam(value = "файл для сохранения в БД", required = false)@RequestParam(value = "oFile", required = false) MultipartFile oFile,
            @ApiParam(value = "название и расширение файла", required = true) @RequestParam(value = "sFileNameAndExt", required = true) String sFileNameAndExt,
            @ApiParam(value = "ид поля", required = true)@RequestParam(value = "sID_Field", required = true) String sID_Field,
            @ApiParam(value = "строка-MIME тип отправляемого файла (по умолчанию = \"text/html\")", required = false)@RequestParam(value = "sContentType", required = false, defaultValue = "text/html") String sContentType,
            @ApiParam(value = "контент файла в виде строки", required = false)@RequestBody String sData)

1) Заменить сервис по загрузке файлов в редис /upload_file_to_redis на /setAttachment, куда передавать в sID_StorageType значение Redis.

2) Во вторую очередь (после успешного тестирования нового сервиса для типа файл) перевести сервис setTaskAttachment  (это сервис используется для сохранения таблиц) также на этот новый сервис.

3) В третью очередь заменить вызов сервиса upload_content_as_attachment (передавая параметр sData и sContentType и в sID_StorageType значение Mongo) и upload_file_as_attachment (передавая параметр oFile  и в sID_StorageType значение Mongo) на регионе на новый сервис.
 
Сервис новый возвращает джейсонину, ее нужно передавать в значение переменной типа файл, вместо ид редиса.

https://github.com/e-government-ua/i/issues/1478

**Comment by OlgaTurenko** [comment]
задачка по которой делали бек: #1461

**Comment by GrekD** [comment]
на альфе все ок, неделю будем тестить на дельте

**Comment by GrekD** [comment]
нашли небольшой баг **на Дельте**
1. перевели все файлы в БП на новую схему (dnepr_cnap_211)
2. файлы, которые подтягиваются из банк ид (bankId_scan_passport, bankId_scan_inn) приходят на юзертаску, но именуются идшкой, а не неймом
проверять можно на услуге
https://delta.test.igov.org.ua/service/102/general
на дашборде тестить под кермитом
[скриншоты](https://docs.google.com/document/d/1J02VR74AizGtcODFey8i0KZCWON5Fjmxk80B4INFGps/edit)
исправление курирует Кулиш Андрей  @Akylish88

**Comment by GrekD** [comment]
баг на Дельте (2)
При подгрузке файла, переведенным на новую схему с наложенным ецп - подпись ЕЦП не распознается, надпись об акредитованном центре не появляется, при попытке сабмита срабатывает маркер-валидатор, который требует прикрепить файл с ЕЦП.
При этом в консоли инфо про ецп видна, т.е. бек отрабатывает

**Comment by GrekD** [comment]
баг 3 (на альфе)
https://alpha.test.igov.org.ua/service/291/general/
Если заполнить услугу - прикрепить файлы в тейбле и попробовать их все подписать ЕЦП (через form_signed_all) - не происходит сабмита или перенаправления на страницу для наложения ЕЦП

**Comment by GrekD** [comment]
Все три бага устранены на альфе
