### ISSUE TITLE
Создать слушатель юзертаски UpdateStatusTaskTreeAndCloseProcess

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1482]
Создать слушатель юзертаски UpdateStatusTaskTreeAndCloseProcess. Передаем туда ид процесса snID_Process_Activiti и статус sID_ProcessSubjectStatus. По ид процесса активити вынимаем всех детей. Если статус отличен от статусов:
2;Виконано;executed
3;Невиконано;notExecuted
4;Неактуально;unactual
6;Закрита;closed
то проставляем в статус сущности ProcessSubject не актуально (4;Неактуально;unactual), дергаем апи активити и закрываем процесс-задачу с причиной = sID статуса (unactual).

**Comment by GrekD** [comment]
при попытке закрыть процесс-родитель выскакивает ошибка
Exception while invoking TaskListener: Exception while invoking TaskListener: java.lang.ClassCastException: java.lang.Long cannot be cast to org.json.simple.JSONObject

**Comment by GrekD** [comment]
Все работает
