### ISSUE TITLE
Реализовать на клиенте (централ, регион) поддержку типа тейбл с типом значения в столцах file.

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1483]
Реализовать на клиенте (централ, регион) поддержку типа тейбл с типом значения в столцах file.
При прикреплении файла в ячейку таблицы дергается сервис по сохранению ататча, результат вызова (мапа в джейсон формате) подставляется в виде значения в велью в эту ячейку (без экранирования ее. тоесть это не строка, а именно мапа в джейсонформате).

**Comment by GrekD** [comment]
не добавляются строчки в такой тейбле почему-то
смотреть здесь:
https://alpha.test.igov.org.ua/service/291/general

**Comment by antonlegkiy** [comment]
маркер валидатор для типа "file" не настроен на таблицы, поправлю

**Comment by GrekD** [comment]
аттачи в тейбл добавляются и корректно приходят на дашборд
есть проблема только с наложением ЕЦП на такие аттачи через form_signed_all - вынесено как отдельный баш в другом ишью
