### ISSUE TITLE
Починить вкладку Мой  розклад

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1485]
Починить работу с Моим розкладом. 2-е ошибки:

Если выбираем все даты:

![image](https://cloud.githubusercontent.com/assets/10909557/21843562/22aedb44-d7f4-11e6-94fe-ee8e47669341.png)

Если выбираем конкретную дату:

![image](https://cloud.githubusercontent.com/assets/10909557/21843583/3a0ecf7e-d7f4-11e6-9871-4e09d7f29f14.png)

**Comment by julyprodan** [comment]
При Тільки не взяті в обробку такая же ошибка
