### ISSUE TITLE
Доработать поддержку диапазонов-исключений(праздников/доп-выходных) для электронных очередей и новый группирующий признак а так-же провести доп-оптимизацию

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1488]
- [x] 1) Добавить в сущность Flow_ServiceData и FlowProperty строковое поле sGroup, длиной 100 симполов (может быть наловое)

- [x] 2) Доработать механизм генерации слотов (для дальнейшей реализации исключения)
- **в классе:** org.igov.service.business.flow.FlowService
Методе:
public List<FlowSlotVO> buildFlowSlots(Long nID_Flow_ServiceData, DateTime startDate, DateTime stopDate), который используется в сервисе /buildFlowSlots
- **и классе:** org.igov.service.business.flow.FlowService
Методе:
public void checkAndBuildFlowSlots(Flow_ServiceData flow, DateTime oDateStart), который используется в шетдулере (класс JobBuilderFlowSlots), через вызов oFlowService.buildFlowSlots

**ТАК:**
- [x] 2.1 Отталкиваясь от указанного Flow_ServiceData - формировать лист сущностей FlowProperty, где будут только записи в которых bExclude=true и при этом они подпадают под одно из правил(или оба сразу):
- [x] 2.1.1. если в поле sGroup исходной сущщности Flow_ServiceData не пусто (не нал и не пустая строка), и при этом такое-же значение в соответствующем поле sGroup но уже сущности FlowProperty (которые и перебираются)
- [x] 2.1.2. если в поле nID_Flow_ServiceData сущности FlowProperty такой-же номер как и в поле nID исходной сущщности Flow_ServiceData
- [x] 2.2 На основании полученного листа 2.1  сформировать список конкретных точечных дат со временем, которые обязательно должны ограничиваться диапазоном в полях sDateTimeAt - sDateTimeTo (в рамках каждой записи FlowProperty) 
- [x] 2.3 На основании полученного листа 2.2 с датами, временем и длительностью отрезков, при дальнейшей генерации(**"Генератор"(хэндлер)**) слотов (в указанных выше двух методах) - обязательно перед генерацией каждого слота проверять его на попадание в сформированный в п.2.2 диапазон, и если он попадает то не генерировать его
**Пояснение:**
- **"Генератор"(хэндлер)** задается в поле nID_FlowPropertyClass, где в сущности FlowPropertyClass уже указан сам бин, который будет выполнять обрботку.
- На текущий момент таким умолчательным бином является "DefaultFlowSlotScheduler" (класс: org.igov.service.business.flow.handler.DefaultFlowSlotScheduler) и в нем и происходит операция генерации.
- необходимо добавить в интерфейс BaseFlowSlotScheduler также поле aDateRange_Exclude, в который передавать сформированный в п 2.2 лист (либо создать отдельный класс в котором будет храниться дата+время+длительность, либо использовать текущий)
- доработать этот класс-генератор DefaultFlowSlotScheduler (в соответствии с обновленным интерфейсом), чтоб обеспечить реализацию п 2.3 

- [x] 2.4 Так-же на основании полученного листа 2.2, после завершения генерации перебирать все слоты за заданный изначально диапазон, и если они попадают в какой-то из полученных в п.2.2 отрезков - удалять их ,ка это делается при использовании сервиса /clearFlowSlots , НО, ОБЯЗАТЕЛЬНО с сохранением тех, по которым уже созданы тикеты.

- [x] 3) Переименовать сущность Flow_ServiceData в Flow (соответственно nID_Flow_ServiceData в nID_Flow), с ОБЯЗАТЕЛЬНЫМ сохранением данных в базе (т.е. просто переименованием также таблицы и полей в таблицах)

Курирует Юлия Продан

**Comment by julyprodan** [comment]
на альфе тестирование успешное,жду переноса в дельту
