### ISSUE TITLE
Создать слушатель таски DoWorkOnCloseTaskEvent 

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1489]
1) Отрефакторить метод private void saveClosedTaskInfo(String sRequestBody, String snClosedTaskId, boolean bSaveHistory) throws Exception в классе RequestProcessingInterceptor:
 создать метод doWorkOnCloseTaskEvent (String snClosedTaskId, boolean bSaveHistory), в него вынести всю логику из старого метода, кроме отпределения snID_Task. (сетинг snID_Task оставить в старом). Из старого вызывать новый метод. Вынести этот метод в сервис org.igov.service.business.action.event.CloseTaskEvent (создать класс).

2) Создать слушатель таски DoWorkOnCloseTaskEvent в котором вызывать этот сервис, куда передавать ид текущей таски и bSaveHistory = true.

**Comment by GrekD** [comment]
https://alpha.test.igov.org.ua/service/282/general
1. пока что статусы в "моем журнале" не меняются. Пример
https://alpha.test.igov.org.ua/search?sID_Order=5-262025673
2. первая юзертаска, которая автоотрабатывается таймером не пропадает из дашборда, и отработать ее в дальнейшем нельзя

**Comment by GrekD** [comment]
тестирование по ветке "таймером на юзертаске"
Еще не до конца работает так как надо:
https://alpha.test.igov.org.ua/search?sID_Order=5-269750018
1. заявка пришла на 1 ЮТ, через 20 секунд автоотработалась и перешла уже на вторую юзертаску
2. статус не поменялся, он остался: статус 1 (ЮТ с таймером)
3. отработала вторую юзертаску
4. статус сразу поменялся как бы 2 раза:
Ваша заявка №5-269750018 змiнила свiй статус на статус 3 (ЮТ без таймера)
Ваша заявка №5-269750018 змiнила свiй статус на статус 2 (ЮТ без таймера)

тестирование по ветке "висящий таймер"
https://alpha.test.igov.org.ua/search?sID_Order=5-269750212
1. заявка сразу перешла в статус Заявка подана - закрита, при том что должен быть статус "статус 1 - перед этим был висящий таймер (ЮТ без таймера)"
2. отработала заявку на 1 ЮТ - статус поменялся на  "Заявка вiдкрита - статус 2 - перед этим был висящий таймер (ЮТ без таймера)"
3. отработала ЮТ 2 статус поменялся на "Заявка закрита - закрита"

таким образом на обоих путях в статус не попадает статус с юзертаски 1
а при висящем таймере еще и сразу высвечивается ошибочный статус о том, что заявка закрыта (сразу после подачи)

**Comment by ElenaShebaldenkova** [comment]
Даша, на енде висел листенер, который задваивал закрытие тасок - я его убрала, закрытие в моем журнале теперь отображается верно. со второй веткой(висящий таймер) непонятно что происходит - там никаких листенеров не висит - может тип таймера должен быть другой? проверь разные типы таймеров.

**Comment by OlgaTurenko** [comment]
Добрый день! А эта задачка уже реализована в полном объеме и устранены замечания?
