### ISSUE TITLE
Реализовать Spring-фассад, для возможности легкого переключения от одного key-value хранилища на другое

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#149]
по умолчанию ориентироваться на MongoDB
Монга готова!!!
10.60.74.10:27017
логин: sitesc
role: readWrite
пароль смогу скинуть в личку

1) он должен стать в первую очередь встроенной абстрактной оберткой(можно в виде отдельного проекта, типа /i/storage-static, который будет в виде зависимости jar подтягиваться в остальные проекты, через наш Nexus), через которую, посредством интерфейса будут юзаться 3 метода:
Object getData(String sID) - возвращает объект с данными
String setData(Object o) - возвращает ИД записи
boolean removeData(String sID) - возвращает true, если удалил корректно

2) желательно(но пока не критично) сразу реализовать обращение через REST,в /i/wf-base
ориентир по кошерному варианту REST:
PUT /
Owner: {serviceName}
Authentication-Token: {serviceAuthToken}
[Content-Type: {contentType}]
[File-Name: {fileName}]
201 CREATED text/plain {fileKey}

POST /{fileKey}
Owner: {serviceName}
Authentication-Token: {serviceAuthToken}
[Content-Type: {contentType}]
201 CREATED text/plain {URL}
409 CONFLICT

DELETE /{fileKey}
Authentication-Token: {serviceAuthToken}
200 OK
404 NOT_FOUND

GET /{fileKey}
200 OK
Content-Type: {contentType}
Content-Disposition: attachment
404 NOT_FOUND

**Comment by vbolshutkin** [comment]
Как и говорил предварительно, готов взяться. Как я понял, это исключительно key-value для файлов с REST интерфейсом? Предлагаю примерное API

PUT /
  Owner: {serviceName}
  Authentication-Token: {serviceAuthToken}
  [Content-Type: {contentType}]
  [File-Name: {fileName}]
201 CREATED text/plain {fileKey}

POST /{fileKey}
  Owner: {serviceName}
  Authentication-Token: {serviceAuthToken}
  [Content-Type: {contentType}]
201 CREATED text/plain {URL}
409 CONFLICT

DELETE /{fileKey}
  Authentication-Token: {serviceAuthToken}
200 OK
404 NOT_FOUND

GET /{fileKey}
200 OK
 Content-Type: {contentType}
 Content-Disposition: attachment
404 NOT_FOUND
(или, может, редирект на Amazon S3)

Что имеется ввиду:
* запись доступна авторизированным сервисам 
* авторизированные публичные ключи сервисов перечислены в конфиге
* конфиг перечитывается без перезагрузки
* можно создать файл со случайным ключем
* можно записать/обновить/удалить файл по заранее заданному ключу
* удаление/изменение доступны только сервису создателю
* чтение по ссылке доступно всем
* создатель может указать Content-Type, который потом вернётся по ссылке
* или мы пытаемся автоматически поставить  Content-Type по расширению файла (из хедера File-Name)
* по умолчанию: application/octet-stream

Вопросы:
 - время хранения +- бесконечно? Только до явного удаления? 
 - какие задачи по администрированию должны поддерживаться?

Особенности:
 - высокодоступность должна обеспечиваться путём запуска как минимум двух инстансов и балансировщика
- впрочем, балансировщик может пригодиться и для других сервисов.
 
Прошу высказать замечания

**Comment by bvv4ik** [comment]
По всем пунктам вроде все норм!

По вопросам:
"время хранения +- бесконечно? Только до явного удаления?"
да

"какие задачи по администрированию должны поддерживаться?"
1) прибить все одним махом)
2) просмотреть список (с ключами и атрибутами, если они есть)
3) добавляьб/изменять/удалять юзверей (желательно та-же работа с ролями, но не принципиально)

По особенностям:
я-ж так понимаю, это уже больше вопрос к организации самого кей-вэлуе хранилища?
или именно о фассаде с РЕСТ, спринговом фассаде(точнее приложении для него)?

**Comment by vbolshutkin** [comment]
Не совсем понял про работу с ролями. "юзверей" - имеется ввиду авторизированные сервисы e-gov? Я бы хотел свести к минимуму все административные функции фасада. Я думаю, что у нас будет еще много микросервисов, которые будут общаться друг с другом, и явно не все эндпоинты должны быть доступны кому попало. Так что в идеале я вижу еще один сервис, в котором задаются права одних сервисов на других. Пока хотелось бы обойтись конфигом.

Насчёт балансировки я имел ввиду, что как бы внедряя этот фасад мы на самом деле теряем преимущества высокодоступности самого хранилища. Например, если все порталы и сервисы используют фасад, а не хранилище напрямую, то может произойти следующее - хранилище (кластер монго или Amazon S3) доступно, но фасад упал по какой-то причине. Это обидно.

В принципе, точно так же может упасть любой из сервисов (типа portal-php / dashboard-js / любой из конкретных порталов).

Поэтому при росте требований к отказоустойчивости и высокодоступности обычно дублируют и балансируют все сервисы. Например, с помощью HAProxy.

**Comment by bvv4ik** [comment]
ок, по авторизации, как и писал - желательно но не обязательно

по поводу фасада, я все-же больше думал о том, что коль это спринг-овый фасад, то его можно юзать как напрямую из приложения, на каждой машине независимо, так и через обращения к этой машине через РЕСТ... тогда если "упадет" какая-то из машин - на ней в принципе не будет возможность оказывать услугу... К слову, все региональные машины, со временем будут в кластерах с балансировщиком в виде энжинса, потому они уже сами по себе будут достаточно хорошо усилен и в отношении отказоустойчивости...

**Comment by vbolshutkin** [comment]
Кажется, я не совсем понял задачу... Я предполагал фасад хранилища как абсолютно отдельный микросервис с REST интерфейсом, написанным на  Spring MVC... Именно в нём могло бы быть реализовано краткосрочное кеширование аттрибутов в памяти, среднесрочное кеширование файлов в редисе и долгосрочное хранение где-нибудь типа МонгоДБ. Чтобы все остальные сервисы и порталы при необходимости дёргали простые HTTP запросы, что сравнительно легко делается независимо от языка.

Вы же, кажется, имеете ввиду просто какой-то класс или JAR типа обёртки для MongoDB драйвера?

**Comment by bvv4ik** [comment]
и jar-ник, и поддержку REST, посредством него...
на сколько я знаю уже есть в Spring что-то уже почти готовое... али как?

**Comment by vbolshutkin** [comment]
Я не очень в курсе таких особенностей Spring, но если класс для доступа уже подключен к порталу и портал имеет может при определённых условиях записывать/удалять/читать файлы, то какой смысл выставлять наружу REST API для PUT/POST/DELETE? Ладно еще GET, но это скорее делается на уровне самого портала, а не в jar.

Кроме того, если мы просто используем обёртку над Mongo, то нужно еще понимать, что тогда  пароль/сертификат доступа к Монго мы отдаём порталам и теряем возможность разграничивать доступ к файлам (т.е. пункт "удаление/изменение доступны только сервису создателю"). Потому что в Монго, насколько я знаю, нету построчного контроля доступа, только по базам, а нам, вроде, может понадобиться доступ на чтение к файлам других сервисов. 

Конечно, можно создавать в монго по одной базе на сервис, а потом пусть обращаются к чужим файлам только через REST интерфейс того портала, который создал файл. Но это нивелирует "централизованность" хранилища.

Так что... 
- либо Монго не подходит по причине отсутствия поддержки Fine Grained Access Control
(- либо я ошибаюсь и есть возможность её этому научить)
- либо такую поддержку надо добавлять с помощью отдельного микросервиса
- либо вычеркиваем требование "удаление/изменение доступны только сервису создателю" и получаем "все порталы имеют доступ ко всем файлам"

**Comment by bvv4ik** [comment]
"какой смысл выставлять наружу REST API для PUT/POST/DELETE"
смысл в возможности, например по АЯКС-у с фронта сохранить туда чето

"тогда пароль/сертификат доступа к Монго мы отдаём порталам и теряем возможность разграничивать доступ к файлам"
пока хранилище централизовано - такой необходимости нет, т.к. и все "региональные серверы" по сути управляются нами... При этом когда кому-то из областей захочется перенести свой сервак на свое железо - без проблемм, ставится на их желего и еще одна монга и настройками этого регионального сервера пренаправляем его на свой-же собственный кей-вэлуе стораж.

так что .в стратегии предусмотрена и "децентрализация")

**Comment by vbolshutkin** [comment]
>>пока хранилище централизовано - такой необходимости нет, т.к. и все "региональные серверы" по сути управляются нами... При этом когда кому-то из областей захочется перенести свой сервак на свое железо - без проблемм, ставится на их желего и еще одна монга и настройками этого регионального сервера пренаправляем его на свой-же собственный кей-вэлуе стораж.

Простите, не совсем согласен. Надо изначально определиться, централизованное хранилище, или нет. 
Пример: сервис А записал файл в централизованное хранилище. Сервис B захотел его прочитать полез в хранилище, нашел там файл. Предлагаемый вами REST фасад запущен на обоих порталах, и файл доступен по адресам A/storage/{fileKey} и B/storage/{fileKey}. Кто-то завязался на адрес B/storage/{fileKey}, а потом вдруг портал B переехал на своё железо и своё собственное хранилище. Ссылка B/storage/{fileKey} перестала работать, или как минимум рассинхронизировалась

Я вижу варианты:
1. никогда не шарить хранилище и ссылки (децентрализация)
2. всегда шарить их и не позволять использовать своё хранилище (централизация)

**Comment by bvv4ik** [comment]
вместе с переездом на другое желего регионального портала и создания там локального хранилища - туда-же переедут и те данные, которые принадлежат этому региональному апликейшину... ведь сама база там собственная, и все ключи к контенту на центральном кей-валуе хранилище там есть.
Так что за это не переживайте, этот момент продуман.

Отдельные сертефикаты будут появляться лишь при конкретной необходимости "вынести из общей системы" региональный сервер с данными...

**Comment by vbolshutkin** [comment]
Еще раз: либо ключи файлов шарятся между всеми сервисами (любой сервис может получить напрямую файл, записанный другим сервисом. Это централизованное хранилище), либо нет. Если есть хоть малейший шанс, что данные сервиса будут храниться отдельно - то это означает децентрализованное хранилище. В этом случае, каждый сервис имеет напрямую доступ только к тем файлам, которые записал сам (даже если всеми данными управляет один сервер/один экземпляр монго и.т.п), а за остальными нужными файлами лезет на те сервисы, которые их создали. 

Насколько я понимаю, вы на самом деле имеете ввиду децентрализованный вариант, хотя в таске #131 написано "для централизованного хранения"... Верно? "Централизованное хранение" - это значит просто, что поначалу всё это будет храниться на одном сервере для уменьшения расходов на поддержку, но хранилище каждого сервиса будет логически изолированным от хранилищ других сервисов?

**Comment by bvv4ik** [comment]
) такс, давайте для экономии времени пообщаемся голосом... предлагаю в скайпе: belyavtsevw

**Comment by bvv4ik** [comment]
тут в том-то и "вся соль", что нужно реализовать централизованную модель, готовую к децентрализации(постепенной)...
давайте все-же голосом в скайпе обсудим: belyavtsevw
?

**Comment by vbolshutkin** [comment]
Я не против обсудить в скайпе, но для этого сложнее найти время, потому что в офисе я без гарнитуры, а дома работаю нерегулярно. Я Вас добавлю и попробуем состыковаться.

**Comment by bvv4ik** [comment]
Мой телефон: 068-854-19-54 Владимир
я смогу сбросить и перезвонить...

**Comment by bvv4ik** [comment]
Ну шо, Монга готова!!!
10.60.74.10:27017
логин: sitesc
role: readWrite
пароль смогу скинуть в личку

@vbolshutkin Берешся фасад делать?

1) он должен стать в первую очередь встроенной абстрактной оберткой(можно в виде отдельного проекта, типа /i/storage-static, который будет в виде зависимости jar подтягиваться в остальные проекты, через наш Nexus), через которую, посредством интерфейса будут юзаться 3 метода:
Object getData(String sID) - возвращает объект с данными
String setData(Object o) - возвращает ИД записи
boolean removeData(String sID) - возвращает true, если удалил корректно

2) желательно сразу реализовать обращение через REST,в /i/wf-base

**Comment by vbolshutkin** [comment]
По результатам телефонного обсуждения, это будет всё же децентрализованный вариант, но с таким заделом, чтобы поначалу не тратить время на изоляцию баз. Так, чтобы не заморачиваться с генерацией сертификатов и даже паролей под каждый сервис. Есть мысль использовать имя проекта как ключ. Или генерировать случайный ключ и класть в .properties файл.

Вобщем, стало чуть понятнее. Так что да, я возьмусь. 

Единственное что, хотелось бы от исполнителя задачи про Мои Документы узнать подробности про то, какие аттрибуты файлов нужны. Потому что ,думаю, там будет всё же не просто String setData(Object o), а какой-нибудь String setData(FileVO o) или как-то так, где FileVO внутри содержит массив байт и аттрибуты.

**Comment by bvv4ik** [comment]
все атрибуты будут "вынесены во вне", т.е. они будут храниться в реляционной базе, в "записи о документе", где так-же будет храниться key, от записи кэй-вэлю хранилища (этого монго)

думаю, все-же, корректней всего, заточиться на поддержку и массива байтов и стринги (просто по два экземпляра гетера и сетера)... т.к. тогда, когда там будет сохраняться, например объект JSON -  его, на уровне фасада, можно было-бы сохранять не как массив байтов, посредством GridFS, а как обычная запись в самой Монг-е...

**Comment by vbolshutkin** [comment]
Создал пулл-реквест https://github.com/e-government-ua/i/pull/220

Пока только спринговое API. По сути, там заточка на массив байт, как основной вариант. API простое, но есть сомнения по правильности обработки исключений. 

Пытался сделать REST, но задумался над тем, что для корректной реализации нужно сохранять  Content-Type и другие поля, которые, возможно, были присланы. Поэтому добавил еще вариант спрингового API для сохранения MultipartFile и его возвращения в виде собственного класса. Кое как сделал. Но этот API плохо продуман. И в итоге на REST сил пока не хватило.

Юнит-тесты есть, но они получились совсем не "юнит", а скорее интеграционные,потому что требуют наличие установленной Монго. Поэтому я их пока отключил, чтоб не падали на дженкинсе и вообще у всех остальных.

Вобщем, блин немного комом. Нужно будет сделать ревью.

**Comment by bvv4ik** [comment]
Там жеж так и пришлось откатить твою доработку, т.к. не хватало какой-то либы и в итоге не делался билд. Ты можешь плиз добавить нужную зависимость, перепролить и ОБЯЗАТЕЛЬНО проконтролировать что все заработало и ничего не поломалось?

**Comment by vbolshutkin** [comment]
Эмм.. а можно хоть намекнуть, что за зависимости у вас не хватает. В pom.xml прописано всё, что нужно (и ничего лишнего), никаких репозиториев, кроме центрального не используется. Локально и в vagrant проект собирается. Насколько я понял, на вашем нексусе стоит какая-то странная настройка, запрещающая автоматическое проксирование к maven-central и артифакты туда нужно запихивать вручную? Тогда я тут мало что могу сделать.

Я тут внесу улучшения, о которых говорилось выше (переименую, немного улучшу API). Но с зависимостями, не похоже на мой косяк.

**Comment by bvv4ik** [comment]
@maxtmn мержил, он-же и заключение делал... а потом, и откатил...

**Comment by bvv4ik** [comment]
готово)
