### ISSUE TITLE
Доработать сервис getSubjectGroupsTree

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1499]
В сущность Subject добавить два поля: oSubjectHuman, SubjectOrgan связь один-к-одному.

Доработать сервис getSubjectGroupsTree. Добавить в сервис и контроллер параметры по фильтрации:

sSubjectType
sSubjectType

Возможные варианты: * (дефолтно по умолчанию проставить), Organ, Human.

Если в фильтре передали * - то возвращаем все, как сейчас.
Если в фильтре передали Organ - то фильтруем и пэрэнта и чайлда по типу орган и возвращаем в ответе только органы.
Если в фильтре передали Human - то фильтруем и пэрэнта и чайлда по типу орган и возвращаем в ответе только людей.

**Comment by GrekD** [comment]
https://alpha.test.region.igov.org.ua/wf/service/subject/group/getSubjectGroupsTree?sID_Group_Activiti=MJU_Dnipro_&nDeepLevel=0&sSubjectType=*

https://alpha.test.region.igov.org.ua/wf/service/subject/group/getSubjectGroupsTree?sID_Group_Activiti=MJU_Dnipro_&nDeepLevel=0&sSubjectType=Human

https://alpha.test.region.igov.org.ua/wf/service/subject/group/getSubjectGroupsTree?sID_Group_Activiti=MJU_Dnipro_&nDeepLevel=0&sSubjectType=Organ
