### ISSUE TITLE
Доработать механизм формирования ПДФ-файла на основе принтформы, при отправке на почту

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1501]
сейчас в поле в атрибуте нейм прописывается так:
        <activiti:formProperty id="PrintForm_4" name="File label;File title;sPrintFormFileAsPDF=pattern/print/dms/zajava_znBk.html" type="file"></activiti:formProperty>

а нужно чтоб когда прописано:

        <activiti:formProperty id="PrintForm_4" name="File label;File title;sPrintFormFileAsPDF=pattern/print/dms/zajava_znBk.html,sFileName=page1" type="file"></activiti:formProperty>

то имя генерироуемого файла проставлялось-бы "page1" (расширение то-же что и было ранее)

**Comment by agerman-ua** [comment]
@GFalcon-UA 
Если получится без дополнительных затрат, прошу сделать возможным использование в качестве "page1" не только статичное значение но и значение переменной.
например "${page1}".
Если сейчас сложно - тогда просто не исключить возможность впоследствии доработать с минимальными затратами. В рамках уже другого ишью.
Спасибо.

**Comment by GFalcon-UA** [comment]
Если и делать `${page1}`, то тогда откуда должно приходить значение?

**Comment by smoktii-igov** [comment]
Речь идет о возможности подставлять не только константніе значения имени файла, но и использовать контекстные переменные бизнес-процесса. Например, использовать номер заявки, ФИО заявителя и т.д.

**Comment by smoktii-igov** [comment]
Результат тестирования именования файлов во вложениях EmailИменование файлов осуществляется корректно, согласно ТЗ (использование значений переменных в именах файлов не допускается - файлы просто не попадают во вложение)
