### ISSUE TITLE
Создать тест для сервиса  /getUsers

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1506]
1) Посмотреть как писали тест для сервиса /getFlowSlots_ServiceData в классе  org.igov.service.controller.ActionFlowController.java.
Сам тест к сервису лежит в папке Тесты в org.igov.service.controller.ActionFlowControllerScenario.java, тест shouldSuccessfullyGetFlowSlotsAndSaveTicket. Попробовать из браузера вызвать этот сервис и посмотреть что он в ответ возвращает: (пример вызова: https://alpha.test.igov.org.ua/wf/service/action/flow/getFlowSlots_ServiceData?nID_Service=176&nID_SubjectOrganDepartment=24&nDiffDays=2). 
Соответственно на этом примере можно разобраться с готовым тестом и по аналогии сделать для указанного сервиса.

2) В классе  org.igov.service.controller.ActionIdentityCommonScenario.java  написать тест shouldSuccessfullyGetUsers, который протестируем сервис /getUsers, который находится в классе: org.igov.service.controller.ActionIdentityCommonController.java.
В тесте пробовать вызвать сервис с параметром sID_Group=admin (пример вызова: https://alpha.test.igov.org.ua/wf/service/action/identity/getUsers?sID_Group=admin).

**Comment by OlgaTurenko** [comment]
https://alpha.test.igov.org.ua/wf/service/action/flow/getFlowSlots_ServiceData?nID_Service=176&nID_SubjectOrganDepartment=24&nDiffDays=2

**Comment by kirei7** [comment]
Создал ActionIdentityCommonScenario класс, в нем сделал Test метод shouldSuccessfullyGetUsers.
В методе провожу три проверки:

- GET запрос без параметра возвращает всех (3 шт) юзеров
- GET запрос с параметромs sID_Group=admin получает в ответ одного юзера
- GET запрос с параметромs sID_Group равным какой-то несуществующей группе получает в ответ ноль юзеров
