### ISSUE TITLE
Исправить выгрузку downloadTasksData - при выборе большого периода выгрузки - теряются данные

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1509]
Если мы делаем запрос **downloadTasksData** за период (например за месяц) то в выборку попадают не все записи. Это повторяемо, т.е. пропадают одни и те же при повторном идентичном запросе. Если период запроса уменьшить до одного дня - проблемы нет. С увеличением периода "потери" растут.

Пример:
Запрос по процессу закрытие ФОП https:
//igov.org.ua/service/87/statistics
Видим что за всё время работы услуги всего было принято 3288 заявок на 15:29 2017.02.07

запускаем запрос (Get метод):
https://region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=justice_0087_FOPclose&bHeader=true&sDateAt=2016-12-01&sDateTo=2017-02-08&saFields=${sID_Order};${sDateCreate};${sDateClose};${sClientFIO};${sLoginAssignee};${sID_UA}&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=create_0087_2016-12-01_2017-02-08.csv
Дважды выполненный, один и тот-же, запрос возвращает результирующий файл с одинаковым количеством записей - 1075. Не хватает 2213 заявок.
[Первый результат](https://drive.google.com/file/d/0B9UDkfHM4vkrZUthUjhpNkY5SjA/view?usp=sharing) 
[Второй результат](https://drive.google.com/file/d/0B9UDkfHM4vkrVTZwSGVGX3ZwMEU/view?usp=sharing) 

Если уменьшить интервал и, соответственно, увеличить количество запросов на весь исходный период - итоговое количество будет больше, т.е. меньше записей потеряется
Если выгружать каждые сутки, то потерь нет, **надо сделать так чтоб потерей не было и при заданных больших интервалах**.

[подробное тз](https://docs.google.com/document/d/1RTPBDKxPpx8dW7qgcF5kfLcHYd_7g9ZzaX8xR9PldBI/edit)

Принимает задачу Август Герман @agerman-ua

**Comment by agerman-ua** [comment]
На дельте уже достаточное количество заявок по одной услуге для тестирования сервиса.
Услуга https://delta.test.igov.org.ua/service/87/statistics
Тут мы видим полное количество заявок "на сейчас" - это наш ориентир. 
Услуга запущена в декабре 2016 т.е. ранее декабря 2016 данные по ней можно не искать.
для запросов логин/пароль system
Запрос за один день (2017-04-11)
https://delta.test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=justice_0087_FOPclose&bHeader=true&sDateAt=2017-04-11&sDateTo=2017-04-12&saFields=${sID_Order};${sDateCreate};${sDateClose}&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=test-stat-0087.csv
Запрос за месяц (2017-03)
https://delta.test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=justice_0087_FOPclose&bHeader=true&sDateAt=2017-03-01&sDateTo=2017-04-01&saFields=${sID_Order};${sDateCreate};${sDateClose}&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=test-stat-0087.csv
В отчете за март месяц видно что последняя найденная заявка создана 26.03.2017  15:40:13
А если сделаем отчет за один этот день (2017-03-26)
https://delta.test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=justice_0087_FOPclose&bHeader=true&sDateAt=2017-03-26&sDateTo=2017-03-27&saFields=${sID_Order};${sDateCreate};${sDateClose}&sID_Codepage=win1251&nASCI_Spliter=59&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=test-stat-0087.csv
то видим что указанный день на этой заявке не закончился.

**Comment by ElenaShebaldenkova** [comment]
Хорошо, спасибо - беру в работу

**Comment by ElenaShebaldenkova** [comment]
Запрос я начала действия услуги 
https://delta.test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=justice_0087_FOPclose&bHeader=true&sDateAt=2016-12-01&sDateTo=2017-04-28&saFields=${sID_Order};${sDateCreate};${sDateClose}&sID_Codepage=win1251&nASCI_Spliter=59&nRowsMax=5000&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=test-stat-0087.csv

Обязательно добавлять nRowsMax=.... , если ожидаемое количество должно быть больше 1000(дефолтное значение 1000)

**Comment by agerman-ua** [comment]
Протестировано успешно, с последними правками, на дельте. 
В таком виде можно в мастер. И закрывать ишью.
