### ISSUE TITLE
Реализовать сервис-обертку получения списка улиц

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1511]
- [ ] 1) Создать контроллер ObjectPlaceController в wf-base (подобно тому, что есть сейчас в wf-central)
с контекстом: /object/place/sub

**создать сервис:**
/PB/getSubPlaces_

**с параметрами:**
sID_SubPlace_PB -код узла адреса
sFind - строка поиска (ищет по вхождению текста в название улицы) //опциональный

**в ответ отдавать:**
массив под-мест(улиц)
с кодом улицы, типом и названием

- [ ] 2) кешировать запрашиваемый список стандартным механизмом через мемкеш

- [ ] 3) данные брать из внешнего сервиса:

**Адрес вызова сервиса:**
https://service-street.tech.igov.org.ua/AddressReference/address/item.do?id=UA40773&language=RUS

**Документация:**
https://docs.google.com/document/d/1SppaZgDRNU9LFbE4ngOIrg9Ebu83WkyJD4wHPP6g7fc/edit#heading=h.4ovb807m5oaa

**Авторизации нет**

- [ ] 4) **НЕ АКТУАЛЬНО** Авторизация тбыла такая-же как и при работе с СМС (Promin)
где проперти с УРЛ-ом и так-же дубли пропертей УРЛ-а авторизации, логин и пароьл Проминя (тот что для СМС) - вынести отдельно:
### SMS
general.Object.SubPlace.PB.Auth.sLogin={{ Object.SubPlace_Auth_sLogin }}
general.Object.SubPlace.PB.Auth.sPassword={{ Object.SubPlace_Auth_sPassword }}
general.Object.SubPlace.PB.Auth.sURL_GenerateSID={{ Object.SubPlace_Auth_sURL_GenerateSID }}
general.Object.SubPlace.sURL_Send={{ Object.SubPlace_sURL_Send }}

- сами Проперти добавить как в общий файл AS.propertyes в проекте
так и попросить ДевОп-а добавить все это в репозиторий iSystem (и iSystemTop)

- Приемку работ будет делать: Август

**Comment by kr110666kai** [comment]
Застрял на получении id-сессии Проминя:
ERROR   [Web_PostSelf]{}({saParam=<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<session><user auth='EXCL' login='igov' password='igov-sess'/></session>, sURL=https://auth-id.igov.org.ua/ChameleonServer/session
s/open?lang=UA}):[post]:BREAKED! java.net.PlainSocketImpl.socketConnect/20)org.igov.io.web.HttpRequester.postInside(103):Connectio
n timed out

**Comment by bvv4ik** [comment]
вопрос решился координально, через замену площадки для сервиса)
переписал чуток ишью... теперь авторизация не нужна)

прошу допилить

**Comment by kr110666kai** [comment]
вопросом занялся

**Comment by kr110666kai** [comment]
Можно проверять:
https://alpha.test.igov.org.ua/wf/service/object/place/sub/PB/getSubPlaces_/?sID_SubPlace_PB=1A4101J4VRPD00

https://alpha.test.igov.org.ua/wf/service/object/place/sub/PB/getSubPlaces_/?sID_SubPlace_PB=1A4101J4VRPD00&sFind=лен

Вопрос по 2) кешировать запрашиваемый список стандартным механизмом через мемкеш
Я сохраняю данные в бине контроллера [org.igov.service.business.object.ObjectPlaceCommonService](https://github.com/e-government-ua/i/blob/test/wf-base/src/main/java/org/igov/service/business/object/ObjectPlaceCommonService.java)
```
private HashMap<String, List<ObjectAddress>> mCacheListAddress = new HashMap<String, List<ObjectAddress>>();
```
или есть какой-то другой механизм?

**Comment by bvv4ik** [comment]
"Вопрос по 2) кешировать запрашиваемый список стандартным механизмом через мемкеш
Я сохраняю данные в бине контроллера org.igov.service.business.object.ObjectPlaceCommonService"

там есть пример кеширования в сервисах получения каталога услуг (новог, тот что с тегами)
/getCatalogTreeTag
Там:
serviceTagService.getCatalogTreeTag(
а там есть хороший пример в методе:
private ServiceTagTree getServiceTagTreeCached(boolean includeTestTags, boolean includeTestEntities) {

ключем кэша становится уникальный ИД-шник сервиса, например:
private static final String GET_SERVICE_TAG_TREE_CACHE_KEY = "ServiceTagService.getServiceTagTree";
и комбинация значений предаваемых параметров, например:
(includeTestTags, includeTestEntities)

**Comment by kr110666kai** [comment]
Сделал по аналогии

**Comment by bvv4ik** [comment]
т.е. уже кеширование реализовано? чекбокс пункта можно отмечать?

и еще будет большая просьба по этой ишью:
нам нужно как-то получить из справочника массив всех населенных пунктов и регионов, включая их названия и если есть КОАТУУ... 

я не смог разобраться - как это сделать(

**Comment by kr110666kai** [comment]
Да, кеширование есть

По КОАТУУ и список всех пунктов и регионов посмотрю

**Comment by agerman-ua** [comment]
Когда смотрел доки, и дёргал запросы, сложилось впечатление что не все области присутствуют.
И нет привязки населённых пунктов и регионов к КОАТУУ. Там, кажется, собственная уникальная нумерация.

**Comment by kr110666kai** [comment]
Поиск всех областей согласно документации дает всего 11 областей и Крым

https://service-street.tech.igov.org.ua/AddressReference/address/item.do?id=UA40773&language=UAN&all=false&exclusions=false

- Днепропетровская
- Закарпатская
- Запорожская
- Ивано-Франковская
- Киев
- Крым
- Ровненская
- Севастополь
- Сумская
- Тернопольская
- Черкасская
- Черновицкая

привязки к КОАТУУ нет

**Comment by agerman-ua** [comment]
А можно, всё-таки, выгрузить в .сsv населённые пункты этих областей? С информацией какая есть (свой код, почтовый индекс, название ...). Кроме Крыма и Севастополя.

**Comment by kr110666kai** [comment]
сделаю

**Comment by kr110666kai** [comment]
Вытащил все населенные пункты этих областей в двух языках (RUS, UAN)
https://drive.google.com/file/d/0B4_nhAYzTtL6MkRKeERJdHh5ZGM/view?usp=sharing

Сделал утилитку для этого
https://github.com/e-government-ua/i/blob/0930994e5cfc9265f2c97204c5aeb88dbd182971/wf-base/src/test/java/org/igov/service/business/object/ObjectPlaceTownUtil.java

Но, там явно не все города. Например я так и не смог пока вытащить Кривой Рог.

**Comment by OlgaTurenko** [comment]
Август, вроде ж уже сделали задачу и приняли? Если да, то поставь, плиз, лейбл соответствующий
