### ISSUE TITLE
Реализовать поддержку html в дескрипшине поля на форме централа

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1512]
Пояснение к полю добавляется в нейм поля через точку с запятой
```xml
 <activiti:formProperty id="sDocNoMarriage" name="Документ про розірвання шлюбу; або інший документ, який підтверджує припинення шлюбу (якщо Ви раніше перебували у шлюбі)" type="file"></activiti:formProperty>
```
Необходимо сделать так, чтоб туда можно было добавлять описание с использованием нтмл - для того чтоб бизнес-аналитики могли формировать подсказки в виде ссылок

со стороны БА принимает задачу Грек Дарья

**Comment by GFalcon-UA** [comment]
HTML-текст отделяется двойной точкой с запятой:
`name=" sTitleText ; sDescription ;; html = sTextInHtmlFormat ;; key2 = value2 ;; key3 = value3 "`
где:
`sTitleText` - наименование поля;
`sDescription` - описание поля (комментарий), которое будет выведено под наименование поля;
`sTextInHtmlFormat` - текст HTML-кода, который будет выведен под комментарием к полю;
`key2`, `key3`, `value2`, `value3` - прочие параметры, которые нужно передать в `property` в виде ключ-значение, разделенные двойными точками с запятыми.
При этом в `property` создается объект `options` с перечнем этих параметров:
```
property : {
      "id": ... ,
      "name": ... ,
      "type": ... ,
      "value": ... ,
      "readable": ... ,
      "writable": ... ,
      "required": ... ,
      "datePattern": ... ,
      "enumValues":... ,
      "options": {
             "html": sTextInHtmlFormat,
             "key2": value2,
             "key3": value3
          }
}
```

**Comment by GFalcon-UA** [comment]
Протестировать можно на https://alpha.test.igov.org.ua/service/1515/general
