### ISSUE TITLE
заменить метод гет на метод POST  в сервисе отправки замечания

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1517]
Переделать сервис /setTaskQuestions

Вместо параметров:
sBody
saField
soParams
передавать в теле запроса JSON-объект с этими параметрами в качестве его элементов
**Например:**
{
"sBody":"",
"saField":"",
"soParams":"",
}

ВАЖНО: Поправить на клиенте (дашборде) передачу этих данных

Курирует: Юлия Продан

**Comment by julyprodan** [comment]
при уточнении маленького количества полей (3 поля) - уточняется, но появились проблемы с кодировкой 
![image](https://cloud.githubusercontent.com/assets/17750882/23104013/333608cc-f6ce-11e6-86af-6838f920767f.png)
при уточнении 10 полей  - ошибка 
![image](https://cloud.githubusercontent.com/assets/17750882/23104047/abfb04a6-f6ce-11e6-9410-5510c3943a32.png)

**Comment by julyprodan** [comment]
Oleksii Khalikov
это ошибка Хибернейта при обращении к БД

**Comment by julyprodan** [comment]
нужна помощь специалистов по беку

**Comment by GFalcon-UA** [comment]
Наткнулись на какое-то системное ограничение, проявляется, если попітаться отправить больше 16 комментариев. Т.е. если отправлять замечания по 16-полям 0 еще все хорошо, а при одновременном віборе 17-и - уже все плохо.

**Comment by julyprodan** [comment]
задачу сменили на https://github.com/e-government-ua/i/issues/1553
