### ISSUE TITLE
Написание унифицированного теста/тов, чтоб шаблонно тестировать бизнес процессы Активити, перебирая их все, без создания под каждый отдельный бизнес-процесс своего собственного юнит-теста

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#152]
у нас создается куча бизнес-процессов в Activiti и очень остро стал вопрос написания юнит-тестов для того чтоб быть уверенным, что каждый из них работает а не поломался. Но создовать по отдельному юнит-тесту на каждый бизнес-процесс(который сейчас можно и без программиста сделать/изменить, силами бизнес-аналитика) - это будет означать потерять основное преимущество Активити.
Нужно придумать, как-бы мы могли шаблонно тестировать эти бизнес процессы, перебирая их все... В идеале одним унифицированным тестом, или несколькими, шаблонными, которые пройдутся по всем бизнес-процессам, и проверят все их шаги на "неполоманность".

Возможно это будет: смок-тесты, возможно data-driven

**Comment by vbolshutkin** [comment]
Боюсь, что такой "юнит" тест сделать практически невозможно, потому что унифицированным кодом теста не проверить все шаги и ветвления БП. А если делать так, чтобы тест читал .bpmn файл, то получится, что мы тестируем не БП, а саму Activity (надеюсь, она и без нас нормально оттестирована)

Можно сделать простой тест на дым, просто чтобы удостовериться, что БП развернуты  там, где их ожидают увидеть, что они нормально стартуют,

Еще можно попробовать сделать какой-нибудь интеграционный (можно совмещенно с нагрузочным) тест, который будет много раз запускать БП и эмулировать обезьяну за компьютером - заполнять формы абсолютно случайным образом и отправлять их

**Comment by bvv4ik** [comment]
убрал слово "юнит"

добавил "Возможно это будет: смок-тесты, возможно data-driven"

тут важна сама суть унифицированного тестирования всех бизнес-процессов

**Comment by crazyfox-ua** [comment]
как я вижу тестирование, исходя из своего опыта на других проектах:
1) Юнит-тесты: девелоперы покрывают ими свой код, мы туда не лезем.
2) Смок-тесты: очень простые и короткие тесты на базовую функциональность, просто чтобы убедиться, что ничего эпического не поломали очередным коммитом
3) Функциональные UI тесты: проверяем определённую функциональность в каждом модуле
4) Интеграционные тесты: проверяем интеграцию с соседними модулями/проектами
5) Бенчмаркинг: проверяем насколько больше/меньше тормозит приложуха после изменений в коде
6) Нагрузочные тесты: проверяем, какую нагрузку может обслужить приложуха и железо

Всё это довольно просто автоматизируется, но для эффективного тестирования бизнеса/функциональности очень желателен опытный мануальщик, который пропишет Что и Как мы тестируем

**Comment by bvv4ik** [comment]
похоже - нам нужно что-т овроде п.2.
но нужно понять, как-бы нам их "натравить" на все наши бизнес-процессы...
по идее, проходясь по списку имеющихся в инстансе бизне-процессов, просто по типам полей заполнять значения(вызвав предварительно базовый сервис), и потом сэмулировать сабмит...

дальше можно наворотить - попытаться то-же самое проделывать над каждым следующим юзер-таском процесса... както так

**Comment by alexnikitchuk** [comment]
на сколько я понимаю, для этих целей нужно наваять тестовый фреймворк, кот. решит эту проблему.

**Comment by crazyfox-ua** [comment]
За тест-фреймворк я возьмусь, это без проблем, как-раз мой профиль )) Просто хочется немного понять предметную область, чтоб по-максимуму избежать основных проблем

**Comment by bvv4ik** [comment]
а есть возможность голосом поговорить в скайп?
belyavtsevw

П.С. так быстрее смог-бы по предметной области ликбез провести

**Comment by crazyfox-ua** [comment]
Только после майских - на работе не получится, а после сразу уезжаю из города на выходные

**Comment by bvv4ik** [comment]
ок, ну если будет время/желание "по пути" пообщаться голосом: 068-854-19-54 (смогу сбросить и перезвонить)

**Comment by maxtmn** [comment]
+5

30 апреля 2015 г., 11:11 пользователь Vladimir Bolshutkin <
notifications@github.com> написал:

**Comment by bvv4ik** [comment]
чо тут "плюсовать", если человек "боится")

"потому что унифицированным кодом теста не проверить все шаги и ветвления БП"
- шото не улавливаю логики или конкретных аргументов...

Если у нас есть конкретные типы полей, контент которых всеравно не влияет на работу бизнес-процесса, то как раз "ботом" их заполнять - это самая простая задача... 

единственную сложность вижу в том, как энумить шаги БП и сами БП... тут я прост оне работал с активити,чтоб знать какими методами это можно было-бы сделать... Но сами поля и типы, которые нужно заполнять в БП описаны... и мы, по сути, когда ручками тестируем и так "абрукадабру" в поля вбиваем...

**Comment by vbolshutkin** [comment]
>>"потому что унифицированным кодом теста не проверить все шаги и ветвления БП"
шото не улавливаю логики или конкретных аргументов...
Если у нас есть конкретные типы полей, контент которых всеравно не влияет на работу бизнес-процесса, то как раз "ботом" их заполнять - это самая простая задача...

Вы правы, при условии, что контент полей не влияет на тип бизнес процесса. Но есть масса примеров, когда он очень даже влияет. Самый простой и наболевший пример - требование предъяаить справку из военкомата при перерегистрации (факторы - пол, возраст, медицинское образование). Эту логику унифицированный тест не проверит. Плюс одним запуском БП не обойти все шаги при наличии ветвлений. 

Поэтому я и предложил сделать много запусков и заполнять поля "ботом". Это может быть хороший тест на дым, совмещенный с нагрузочным тестированием.

**Comment by bvv4ik** [comment]
так вот у нас таких "особых БП" будет 0.001%
а основа - совершенно тупые болванки...(сейчас у нас вообще 100% процессов такие)
и писать для каждой из них программистам юнит-тест код - это, к-бы это так помягче выразиться? ну я уже сказал - "расточительство" и совершенно бессмысленный копипаст...
Мы-ж не кодеры тут собрались а люди творческие, инженеры, можно сказать... 
Да, не тривиально, но реально, ИМХО... нужно только собрать людей, которые глубже умеют с Активити и БП работать...

"(факторы - пол, возраст, медицинское образование)"
- это обычные энумы и намбер типы... этокак раз очень даже легко...

а для ну уж совсем специфических типов полей(значений полей), спокойно можем отдельный блок логики написать...

кроме того - у нас все персональные данные подгружаются через банк ИД, и если мы будем использовать тестовый сервис, тот там тоже проблем не будет...

**Comment by vbolshutkin** [comment]
Вы говорите примерно о том же, что и я, но я просто уточнил, что это будет только лишь тест на дым (что ничего не поломалось, что 500 ошибки не полетели и.т.п.). Заполнить случайные поля для возраста и пола - конечно, легко. Мой комментарий имел целью уточнить, что унифицированный тест не сможет протестировать логику. То есть он не сможет заметить, что БП пошел по неверной ветке при определённых входных данных.

Для БП без ветвлений (в реальной жизни это примерно 0.0001% БП) достаточно одного прогона теста со случайными данными. Для совсем сложных и специфичных (их тоже очень мало, вы правы) даже милион рандомных запусков не обойдут все ветки БП. Я не призываю отказаться от теста, я просто предлагаю делать не один проход, а много. А если много - то это уже и нагрузочный тест сразу

**Comment by bvv4ik** [comment]
Да, значит мы действительно приблизительно одинаково понимаем это.

у нас-жеж задача не написать "классический юнит-тест"(т.к. BPM явно вынуждает нас "выйти за рамки классики"), а обеспечить механизм прохождения типа-ботом(вместо человека) по имеющимся доступным этапами каждого из простого бизнес процессов, заполняя поля контентом нужного типа и убедиться в том, что на этих простых операциях все нормально и ничего не поломалось после нашей правки.

Ведь правки программистов как правило будут приводить именно к последствиям неожиданных эксепшинов, а не изменения поведения бизнес-процесса в совершенно непредсказуемом направлении.
Можно конечно писать юнит-тесты и на каждый класс, который используется в этапах бизнес-процесса, но я прошу обратить внимание на экономику:
полностью покрывать тестами абсолютно все методы и классы в проекте - куда дороже, чем иметь один унифицированный симулятор примитивных действий с бизнес-процессами.
При том, что результат надежности имеем практически тот-же!
(совсем редкие и слощные вещи конечно можно юнит-тестами прогонять, но не в данном случае)

Мало того, тут как раз, учитывая то. что сами бизнес-процессы будут писать не программисты а бизнес-аналитики даже вредно было-бы дублировать поведение использования бизнес-процесса в хардкоде, т.к. после любых правок в бизнес-процесса аналитиком, без изменения юнит-теста программистом - тупо может не захотеть деплоиться проект, если там автоматом запускаются юнит-тесты при сборке.

Понимаете о чем я? 

Да, возможно условный термин "тест на дым" для этого больше подходит.
Тут ключевое слово тест, и суть самого процесса, который он должен представлять собой!

Если-бы тут были специалисты по Активити, и хотябы один рабочий юнит-тест для бизнес процесса, то, думаю, мы могди-бы покапавшись и покомбинировав найти оптимальное решение данной задачи! А надубасить кода мы всегда успеем!

**Comment by Dashchenko-Inna** [comment]
Уважаемый Владимир, специалисты по активити есть и как Вы выразились есть тест по активити в рабочем состоянии, который именно проверяет бизнес процесс. Но если бы Вы сам хоть немного разбирались и почитали про активити и посмотрели как пишутся юнит-тесты самими разработчиками , создателями , то не писали бы тут чушь.

**Comment by Dashchenko-Inna** [comment]
vbolshutkin , +5

**Comment by vbolshutkin** [comment]
Ок. Мне это интересно, и я попробую с этим покопаться.

**Comment by bvv4ik** [comment]
Отлично! Если не возражаешь, ассигну тебя тогда на эту таску.
Прошу, по результату формированию общего видения схемы реализации - откоментить...

**Comment by maxtmn** [comment]
привет
вот я и дождался когда все успокоятся и дело дойдет до дела
в двух словах, за последние два года перебрали множество вариантов
написания тестов для процессов активити, разные схемы и подходы.
пункт 1 - написать тест, для которого не нужен будет программист - не
получится, потому что, ... и этих "потому что" оооочень много
пункт 2 - тестировать нужно бизнес-процесс а не активити
пункт 3 - чем большее покрытие тестами бизнес-процесса, тем менее гибким
становится сам процесс, 100% покрыли бп - и внести какие либо правки в
процесс становится очень трудно.  Поэтому, здесь, в самый раз тесты на
"дым".

в этом проекте для тестирования бизнес-процессов нам нужно два типа тестов:
малые тесты - тесты функционального кода,  тесты используемых (самописных
тасков) классов. Самые обычные юнит тесты
средние тесты - тестирование самого процесса, здесь нужно протестировать
логические блоки. Акцент на ветвления, параллельные ветки, подпроцессы.

Почему все решили что нельзя взять и перебором получить доступ ко всем
бизнес-процессам? Да легко - доступ к активити-диплоймент, пять минут и
будет такой тест.
Почему все решили что нельзя запускать один и тот же тест по всем-всем
процессам? Проще простого!
Эти возможности предоставляет сам активити.  Вот только толку нам от этого,
никакого.

Не надо тратить свое время, на то, что в данный момент нам не нужно.
Научно-исследовательская деятельность это интересно, но требует времени и
человеко-часов, и человеко-мозгов.



4 мая 2015 г., 4:23 пользователь bvv4ik <notifications@github.com> написал:

**Comment by bvv4ik** [comment]
Постараюсь теперь кратко и структурировано/системно выделить основные пункты реализации "унифицированной системы тестирования БП", которая должна запускаться при каждом деплое приложения из Дженкинс(в порядке приоритета реализации):
1) Запуск авто-деплоймента всех бизнес-процессов, для фильтрации грубых ошибок.
2) Запуск механизма тестирования на "дым", с перебором "из вне"(скорей всего по REST) всех бизнес-процессов, и прохождение ботом по каждому из полей с его заполнением в соответствии с его типом, а затем сабмитом(в перспективе по каждой юзер-таске), для убежденности, что базовые примитивные механизмы отработки юзер-таски не повреждены. (можно попытаться JMeter или аналогами, но принципиально важно реализовать именно унифицированный механизм прохождения по всем бизнес-процессам... пусть даже только до первой юзер-таски, для каждого, на первом этапе)
3) Запуск юнит-тестов, которыми должен быть покрыт каждый из классов, для кубиков бизнес процессов (а не каждый бизнес процесс), чтоб предотвратить поломки на уровне классов.

П.С.: повторять логику каждого бизнес-процесса в персональных юнит-тестах - не будем! У нас бизнес-процессов будут десятки тысяч, потому это будет "дорога в ад"! Вопрос не в том чтоб "написать тест, для которого не нужен будет программист", вопрос в том, чтоб "не писать столько-же отдельных тестов, сколько у нас отдельных бизнес-процессов"!

**Comment by vbolshutkin** [comment]
>>Отлично! Если не возражаешь, ассигну тебя тогда на эту таску.
1) Запуск авто-деплоймента всех бизнес-процессов
2) Запуск механизма тестирования на "дым"
3) Запуск юнит-тестов

Можно, но хочу подчеркунть, что собираюсь взяться только за пункт 2. Список всех БП собираюсь взять с wf-central, для генерации случайных данных попробую Faker.  Как проработаю поглубже - отпишусь. 

При этом считаю, что пункт 3 (юнит-тесты кубиков) даже более важен, так что тестовый фреймворк (предложенный @crazyfox-ua) будет очень кстати. Можно создать отдельные таски, чтобы не путаться.

**Comment by maxtmn** [comment]
1) Запуск авто-деплоймента всех бизнес-процессов

Делается автоматически средствами активити, ничего для этого делать не надо
04.05.2015 16:03 пользователь "Vladimir Bolshutkin" <
notifications@github.com> написал:

**Comment by bvv4ik** [comment]
Отлично, я п.2. во глову угла и ставил, просто п.1., как мне показалось - вообще элементарно реализовывался-бы, при этом давая хороший результат, потому я его первым и написал...

ок, с нетерпением ждем первых результатов..

а по поводу п.3. - согласен что важно, но он, как по мне, более трудоемкий, и по сути не закончится никогда, т.к. новые типы "кубиков" будут появляться всегда, покуда будет развиваться этот проект... При этом "фреймворк (предложенный @crazyfox-ua) будет очень кстати." - также согласен, и может он не откажет тогда заняться хотябы началом реализации этого 3-го пункта, уже в рамках отдельной задачи...

еще остается найти желающего по 1-му пункту, может Инна согласится

**Comment by maxtmn** [comment]
Список всех БП собираюсь взять с wf-central

Список всех Бп, опять таки, есть в активити, в движке, там его брать и
нужно.
Читаем юзергайд о deployment.

Володя Болшуткин, давай дальше в личке.
 04.05.2015 16:07 пользователь "Maxym Tereshchenko" <mastodont1984@gmail.com>
написал:

**Comment by bvv4ik** [comment]
maxtmn
1) Запуск авто-деплоймента всех бизнес-процессов
Делается автоматически средствами активити, ничего для этого делать не надо

это в том случае, когда деплоится новый процесс..
но если процесс уже задеплоен, а мы чего-то там поменяли "из окружения"(не в самом БП), что могло-бы повлиять на это процесс(хоть ранее он деплоился и успешно), то вот повторный ре-деплой автоматический при деплое всего проекта нам-бы и помог...

**Comment by maxtmn** [comment]
Чаво?!
04.05.2015 16:11 пользователь "bvv4ik" <notifications@github.com> написал:

**Comment by bvv4ik** [comment]
vbolshutkin "Список всех БП собираюсь взять с wf-central"
нужно пока ориентироваться на демо-процессы в wf-dneprorada

в wf-central - пока особо процессов не будет, т.к. он будет хранить только общеукраинские БП

**Comment by maxtmn** [comment]
Список Бп......
Володя, не уводите людей в лес.
04.05.2015 16:13 пользователь "bvv4ik" <notifications@github.com> написал:

**Comment by maxtmn** [comment]
Предлагаю тему закрыть, дальше я с Балшуткиным и Инной все сделаем.
Всем спасибо за внимание
04.05.2015 16:15 пользователь "Maxym Tereshchenko" <mastodont1984@gmail.com>
написал:

**Comment by bvv4ik** [comment]
Ни кто, ни кого, ни куда - не уводит! Лишь направляю "на путь истинный")
Попрошу, по делекатней, с оценками... а то так агульно, без конкретики, кто угодно может...

Максим, тогда прошу создать отдельные 3 задачи по этим 3-м пунктам, с назначением по каждой из них конкретного исполнителя, с обязательной ссылкой в теле задачи на данную issue, чтоб всем новым людям было понятно "с чего все начиналось".
Ну и как, наиболее опытного - проконтролировать процесс... плиз

тогда можно будет эту issue звкрывать

**Comment by vbolshutkin** [comment]
Первые наработки унифицированного теста: https://github.com/e-government-ua/i/pull/186

Вкратце - сделал JMeter скрипт, который запускает и проходит все БП активити. По умолчанию натравлен на wf-dniprorada, но может быть легко переправлен на любой другой портал прямо при вызове из командной строки. В общем-то, по сути он почти даже не ограничен нашими инстансам активити, можно попробовать на других.

Особенности:
- натравливается на уже запущенный инстанс по HTTP, так что так просто не получится подсунуть моки.
- соответственно, отправка емэйлов - тоже реальная. Поэтому я не генерирую адреса, чтоб не забанили, а подставляю свой (через параметр командной строки). В итоге мне на почту сыпется куча писем.
- типы полей определяются по type и id. То есть работать будет только с теми БП, где емейл юзера имеет mail или email. 

Недоработки:
- забыл добавить поддержку type=user
- недостаточно удобное логирование
- нет информации о покрытии веток БП
- недостаточное тестирование краевых случаев (пустых полей, отрицательных значений и.т.п)
- мне кажется необходимым тестирование таймаутов, но пока к этому ничего не готово (и БП, и тест)

И надо заметить, что с JMeter, мне кажется, будет достаточно сложно поддерживать информацию о покрытии и проверенных краевых случаях, потому что любая передача данных там через глобальные переменные...

Уже найденные баги в БП:
- в большинстве стандартных БП можно задать невалидный email. Запрос уйдёт в работу, но упадёт на 3м шаге (MailTask). И избавиться от такого висячего процесса достаточно сложно. Во-первых, на стороне формы должна быть валидация, во-вторых надо что-то сделать, чтобы процесс хотя бы не зависал. Пусть лучше завершится с ошибкой. А еще лучше уйдёт пользователю на уточнение.
- В БП "Калуська РДА - Видача витягу з технічної документації про нормативну грошову" получил ошибку "Unknown property used in expression: ${bankIdLastName} ${bankIdFirstName} ${bankIdSecondName}". Тоже - убрать нельзя, процесс висит и постоянно показывает всплывающее сообщение. Похожая ошибка в БП "Миколаєвська ОДА - Взяття на облік громадян, які потребують поліпшення житлових умов” и еще нескольких
- При достаточно небольшой нагрузке получил ошибку "Deadlock detected. The current transaction was rolled back.". Похоже даже на баг активити. Может, можно решить тюнингом настроек, но как-то странно, что это не просто замедление, а именно деадлок.

**Comment by bvv4ik** [comment]
как по мне - отличный результат, а особенно прикольно то, что, похоже, мы таки действительно почти сразу наткнулись на ограниченность Активити по очень частому использованию... то-ли нужно действительно "тюнить" активити, то-ли искуственно сдерживать поток запросов к нему...
(я поинтересуюсь у коллег - кто его юзал, были-ли подобные траблы у них замечены)

пока, у меня возникло пару вопросов:
1) правильно я понимаю, что по мере появления новых бизнес-процессов этот тестер автоматом будет проходиться и по ним?
2) как можно простым способом запустить это тест? (т.е. не только через деплой, где он будет "прикручен автоматом", а именно "из вне, дополнительно... например вызовом какого-то срвиса)"

**Comment by vbolshutkin** [comment]
Тут как раз пока ситуация в том, что он пока не прикручен автоматом, и мне пока не совсем понятно, как его прикрутить. Придётся серьёзно допиливать (сейчас если есть ошибки БП, то тест зависает), как-то настраивать, чтобы нормально сигнализировать, если какой-то процесс поломался. Но допилим, конечно. Может откажусь от JMeter даже.

Этот скрипт сейчас абсолютно внешний (я его положил в wf-base). Запускается из командной строки или из JMeter GUI. Самый простой способ попробовать:

vagrant up
jmeter -n -t wf-base/src/main/resources/jmeter/Activiti.jmx -Jemail={ваш_емейл}

можно без вагранта, натравить на тестовый сервер, например

jmeter -n -t wf-base/src/main/resources/jmeter/Activiti.jmx -Jemail={email} -Jserver={server} -Jport={port} -Jprotocol=https -Jcontext=wf-dniprorada -Jlogin={login} -Jpassword={password}

Логин и пароль тут должны быть от пользователя активити, который состоит во всех группах (типа kermit).  Если там, другая Basic аутентификация, то можно задать base64({basicLogin}:{basicPassword}) в параметре -JbasicAuth

Скрипт проходит по всем развернутым БП (пока 1 раз, потому что письма приходят на почту по-настоящему, и так их по 25 за один прогон), но у него сейчас нет критерия успешности и проверки покрытия. Возможно, в будущем будет больше чем один прогон. Запускать такой тест при каждой сборке - не стоит.

**Comment by bvv4ik** [comment]
То что сейчас сделано уже круто!
понятно, нужно потихоньку дошлифовывать, но начало хорошее положено...

и, наверно придется из явы запускать в рантайме, по вызову из REST


создал производную задачу:
https://github.com/e-government-ua/i/issues/187

**Comment by vbolshutkin** [comment]
А можете рассмотреть и принять мой пулл-реквест https://github.com/e-government-ua/i/pull/186? Или выдать права на запись.

Кстати, что делать с недочётами в БП, на которые я наткнулся (с невалидным email и с отсутствующими полями с префиксом bankId) и которые по сути заваливают тест? Вы создадите соответствующие таски или мне создать по своему усмотрению?

**Comment by vbolshutkin** [comment]
Максим смерджил пулл-реквест. Таски, давайте, я сам создам. При необходимости - уточните.

**Comment by bvv4ik** [comment]
"Кстати, что делать с недочётами в БП, на которые я наткнулся"
видел там Максим, похоже, что-то уже в связи с этим начал править... только-ж он молчит как партизан)
Максим, создай пожалуйста эти такски, по исправлению этих боков, или поручи кому-то создать, а сам в них отпишись если принял на себя.. иначе бардак получается и очень сложно контроллировать кто чего взял/невзял...

vbolshutkin - прошу согласовать с Максимом, чтоб таки эти задачи появились по исправлению БП, и было понятно кто ими занялся + на какой они стадии...

еще просьба, по 1-му и 3-му пунктам этой issue, просил создать задачи(Максима). а то опять не понятно - будет их делать кто-то или не будет... Так очень сложно контроллировать процесс, если все делается "на тихаря". Пожалуйста, постарайтесь уважительно относится к чужому времени, ведь тоже вынужден совмещать это все с кучей другой основной работы...

**Comment by vbolshutkin** [comment]
Максим уже поручил мне их создать :) Вот: #188, #189, #190

**Comment by bvv4ik** [comment]
Спасибо,
тогда, наверно, как только будут созданы задачи по п.1 и п.3 - можно будет закрывать эту issue
