### ISSUE TITLE
5. На базе принтформы по умолчанию создавать PDF

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1524]
## 5
- [ ] При сабмите формы (только документа) - на базе умолчательной авто-принтформы создавать PDF ( #1456 )  и сохранять его через сервис /**setDocumentImage** #1523 

Общая идея **Подписание документов ЕЦП**
 состоит в том, чтоб на электронные документы чиновники могли накладывать ЕЦП (на дашборде)
При этом даем возможность сначала рассмотреть и отправить документ дальше по этапам, а ЕЦП наложить потом - т.н. "отложенное ЕЦП"
Такие "отложенные ЕЦП" будут размещаться в отдельной вкладке в виде ПДФ файлов, сформированных на основании кастомной принтформы
Основное преимущество этой вкладки в том что документы без ЕЦП можно будет подписать все сразу - выбрав всю группу документов через чекбоксы, и единожды нажав кнопку "підписати ЕЦП"

**Comment by GFalcon-UA** [comment]
можно тестировать после того, как решат проблему с юзером justice_common на беке

**Comment by GrekD** [comment]
Сервис работает
пример вызова
https://alpha.test.region.igov.org.ua/wf/service/object/file/getDocumentImage?nID_Process=30620008&sKey_Step=step_1&sLogin=justice_common

еще продолжаем разбираться с беком - если в процессе уже есть принтформа (не умолчательная) то пдф не формируется

**Comment by GFalcon-UA** [comment]
Даша, так это ж надо и на фронте еще один запрос допиливать, чтоб НЕ дефолтную форму отправлять на setDocumentImage
С не дефолтной формой конечно же оно не работает сейчас.

**Comment by GrekD** [comment]
Задача реализована - генерится дефолтная принтформа в ПДФ - не зависимо от того есть ли другие кастомные принтформы в процессе или нет.
Но в процессе реализации возникла подзадача:

> если задана принтформа, у которой название файла начинается с "_doc_", то берем эту принтформу за основу (саамую первую что найдем)

эта новая подзадача не реализована.
Пример запроса:
https://alpha.test.region.igov.org.ua/wf/service/object/file/getDocumentImage?nID_Process=31202560&sKey_Step=step_1&sLogin=justice_common

**Comment by GFalcon-UA** [comment]
Маленькое уточнение:
Имя файла должно начинаться с  `_doc_имя-файла`  (нижнее подчеркивание-doc-нижнее подчеркивание)
или просто `doc`
p.s. обратите внимание, что если doc просто обрамить двумя знаками подчеркивание, то включается форматирование курсивом

**Comment by GFalcon-UA** [comment]
Оно должно было работать в варианте `_doc_имя-файла`
Сейчас добавил вариант `doc_имя-файла`
Прошу перетестировать

**Comment by GrekD** [comment]
пример кастомной принтформы
```xml
 <activiti:formProperty id="PrintForm_1" name="File label;File title;sPrintFormFileAsPDF=pattern/print/minust/_doc_justice_171_rkk1.html"  type="file"></activiti:formProperty>
```
