### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by DimasSup** [e-government-ua/i#153]
Нахожусь на странице https://52.17.126.64/auth/login
Нажимаю войти через bankId
браузер пытается перейти 
https://bankid.privatbank.ua/DataAccessService/login?sidBi=****
и ничего не происходит, страница не грузится. иногда браузер подвисает.
Иногда останавливается на https://52.17.126.64/auth/authclient?authclient=bankid
Safari 7.0.5, Mac OS, 10.9.4

**Comment by bvv4ik** [comment]
заходите на test.e-gov.org.ua
