### ISSUE TITLE
12. В документах отображать напротив подписантов так же еще данные о подписи ЕЦП

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1531]
## 12

- [ ] На фронте отображать напротив подписанта: #1436 

- обязательность наложения ЭЦП (bNeedECP)
- дата наложенности ЭЦП (sDateECP)

Общая идея **Подписание документов ЕЦП**
 состоит в том, чтоб на электронные документы чиновники могли накладывать ЕЦП (на дашборде)
При этом даем возможность сначала рассмотреть и отправить документ дальше по этапам, а ЕЦП наложить потом - т.н. "отложенное ЕЦП"
Такие "отложенные ЕЦП" будут размещаться в отдельной вкладке в виде ПДФ файлов, сформированных на основании кастомной принтформы
Основное преимущество этой вкладки в том что документы без ЕЦП можно будет подписать все сразу - выбрав всю группу документов через чекбоксы, и единожды нажав кнопку "підписати ЕЦП"

**Comment by GFalcon-UA** [comment]
Если `bNeedECP=false` то дата подписи проставляется из `sDate`
Если `bNeedECP=true` - дата из `sDateECP`

**Comment by OlgaTurenko** [comment]
Спасибо! Проверяем.
