### ISSUE TITLE
13. Реализовать метод проверки наложености ЭЦП /isDocumentAllSigned

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1532]
## 13

- [x] **Реализовать метод проверки наложености ЭЦП по строкам-подписантам(/**isDocumentStepSubmitedAll**), где отмечен флаг обязательности ЭЦП(bNeedECP=true) #1530 , и фактически ЭЦП нету (sDateECP=null)** #1522 

Что должен делать сервис!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Принимает на вход ид процесса, степ и логин. По ид процесса и названию степа вытягиваем всех участников данного степа и проверять sDate. Если все даты есть, значит все участники степа отработали его и возвращать сервис должен в таком случае true (в мапе как сейчас). Иначе false.
--------------------------------------------------------------------

Общая идея **Подписание документов ЕЦП**
 состоит в том, чтоб на электронные документы чиновники могли накладывать ЕЦП (на дашборде)
При этом даем возможность сначала рассмотреть и отправить документ дальше по этапам, а ЕЦП наложить потом - т.н. "отложенное ЕЦП"
Такие "отложенные ЕЦП" будут размещаться в отдельной вкладке в виде ПДФ файлов, сформированных на основании кастомной принтформы
Основное преимущество этой вкладки в том что документы без ЕЦП можно будет подписать все сразу - выбрав всю группу документов через чекбоксы, и единожды нажав кнопку "підписати ЕЦП"

**Comment by GrekD** [comment]
Сервис **isDocumentStepSubmitedAll** работает корректно.
Пример скрипта для вызова сервиса в БП:
```
var nID_Process = execution.getProcessInstanceId();
var sLogin = execution.getVariable('sName_SubjectRole')
var sKey_Step = execution.getVariable('sKey_Step_Document')
var obj3= documentStepService.isDocumentStepSubmitedAll(nID_Process, sLogin, sKey_Step)
execution.setVariable('bSubmitedAll', obj3.bSubmitedAll.toString())
```

**Comment by OlgaTurenko** [comment]
Даш, тоесть все ок и ставим лейбл вершин?

**Comment by GrekD** [comment]
Оля, пока мы просто проверяем подписи (сабмиты), а это ишью вроде на сервис, который будет проверять наличие именно подписи ЕЦП, поэтому не ставила версион.
Получилось что мы реализовали промежуточный сервис, а ишью для проверки именно подпсии ЕЦП

**Comment by OlgaTurenko** [comment]
думаю отдельной таской сделаем допил этого сервиса ще и на наличие ЭЦП. но он пока для нас не критичен. таску закрыла, чтоб не путаться по ней
