### ISSUE TITLE
Починить пропажу атачей со второй юзертаски на дельте 

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1534]
Починить пропажу атачей со второй юзертаски на дельте. Перенести правку ручками и на альфу.

**Comment by smoktii-igov** [comment]
Подтверждаю, что файлы на второй юзертаске появляются, но, к сожалению, не именами, как это было ранее, а своими Идишниками
![image](https://cloud.githubusercontent.com/assets/17428200/23047095/4a83f81e-f4b6-11e6-9e5d-a787c252b2e0.png)

**Comment by smoktii-igov** [comment]
Протестировано на БЕТЕ - все ОК

**Comment by smoktii-igov** [comment]
На РЕЛИЗЕ все работает
