### ISSUE TITLE
Написать сервис getDeparByGroup_Activiti

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1542]
Сервис написать в контроллере и сервис-обертку, замапленную, как компонента с именем, которая вернет по юзеру его департамент
Название сервиса: getDeparByGroup_Activiti
Параметр на входе: sID_Group_Activiti

**Comment by Deivur** [comment]
Ссылка для тестирования:
https://alpha.test.region.igov.org.ua/wf/service/subject/group/getDeparByGroup_Activiti?sID_Group_Activiti=MJU_Dnipro_Top6_Dep1_Exec5

**Comment by GrekD** [comment]
спасибо! Сервис работает корректно
