### ISSUE TITLE
Прикрыть Jenkins и поменять пароли.

### ISSUE THREAD

**Issue by corebug** [e-government-ua/i#1544]
https://hsc.gov.ua/asynchPeople/

**Comment by YmNIK13** [comment]
Это немного не к нам :) 
[Головний сервісний центр МВС України](https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%D0%93%D0%BE%D0%BB%D0%BE%D0%B2%D0%BD%D0%B8%D0%B9+%D1%81%D0%B5%D1%80%D0%B2%D1%96%D1%81%D0%BD%D0%B8%D0%B9+%D1%86%D0%B5%D0%BD%D1%82%D1%80+%D0%9C%D0%92%D0%A1+%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B8)
