### ISSUE TITLE
Реализовать стандартный элемент формы для подгрузки по ОКПО полей организации

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1546]
УРЛ запроса:
https://opendatabot.com/api/v1/company/КОД?apiKey=ВашКод

за АПИ-ключем обратиться к Белявцеву иил Кузьминоваой Ольге

ИД-полей должны начинаться с:
sID_SubjectOrgan_OKPO_
sFullName_SubjectOrgan_
sShortName_SubjectOrgan_
sLocation_SubjectOrgan_
sCEOName_SubjectOrgan_
sActivitiesKVED_SubjectOrgan_
sDateActual_SubjectOrgan_

Постфикс как группа должен обьединять записи одного ОКПО

```

{
"full_name": "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ \"ПАПКА24\"",
"short_name": "ТОВ \"ПАПКА24\"",
"code": "40411743",
"location": "49000, Дніпропетровська обл., місто Дніпро, Жовтневий район, ВУЛИЦЯ РОГАЛЬОВА, будинок 28, кімната 229",
"ceo_name": "ДУБІЛЕТ ДМИТРО ОЛЕКСАНДРОВИЧ",
"activities": "62.01 Комп'ютерне програмування",
"database_date": "19-02-17"
}
```

**Comment by bvv4ik** [comment]
Более подробное описание стандартного элемента:
https://docs.google.com/document/d/1dTJnbkkEJZ9H_9_fK_z2KgPMFvSG2CArEHP58C1JuNs/edit

**Comment by agerman-ua** [comment]
2 набора полей с постфиксами 01 и 02 добавлены в тестовый процесс 
https://alpha.test.igov.org.ua/service/303/general
