### ISSUE TITLE
Создать тест для сервиса /setGroup

### ISSUE THREAD

**Issue by YmNIK13** [e-government-ua/i#1547]
1. Посмотреть как писали тест для сервиса /getFlowSlots_ServiceData в классе org.igov.service.controller.ActionFlowController.java.
Сам тест к сервису лежит в папке Тесты в org.igov.service.controller.ActionFlowControllerScenario.java, тест shouldSuccessfullyGetFlowSlotsAndSaveTicket. Попробовать из браузера вызвать этот сервис и посмотреть что он в ответ возвращает: (пример вызова: https://alpha.test.igov.org.ua/wf/service/action/flow/getFlowSlots_ServiceData?nID_Service=176&nID_SubjectOrganDepartment=24&nDiffDays=2).
Соответственно на этом примере можно разобраться с готовым тестом и по аналогии сделать для указанного сервиса.

2. В классе org.igov.service.controller.ActionIdentityCommonScenario.java написать тест shouldSuccessfullyGetUsers, который протестируем сервис /setGroup, который находится в классе: org.igov.service.controller.ActionIdentityCommonController.java.
2.1 В тесте пробовать вызвать сервис с параметром setGroup?sID=testers&sName=testers (пример вызова: https://alpha.test.region.igov.org.ua/wf/service/action/identity/setGroup?sID=testers&sName=testers) 
2.2 В тесте найти созданную группу через сервис этого же контроллера без параметров /getGroups (пример вызова: https://alpha.test.region.igov.org.ua/wf/service/action/identity/getGroups )

**Comment by Pakirava-Datsuma** [comment]
может, надо написать shouldSuccessfully**SetGroup** ? shouldSuccessfully**GetUsers** там уже есть

**Comment by OlgaTurenko** [comment]
совершенно верно!

**Comment by Pakirava-Datsuma** [comment]
дополнительный функционал (удаление созданной тестом группы) лежит в [другой ветке](https://github.com/e-government-ua/i/tree/i-1547_test_merging), т.к. там надо дополнительно разбираться. Возможно, правильнее под него субтаску сделать — не держать же эту открытой.

**Comment by OlgaTurenko** [comment]
да. в тексте этой задачи не вижу задачи на удаление. потому закрываю. Валера, создашь, пожалуйста, таску на удаление?
