### ISSUE TITLE
Создать сущность Замечание

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1553]
Создать сущность SubjectMessageQuestionField с полями:
"sID":"phone",
"sName":"Ваш контактний телефон",
"sType":"string",
"sValue":"+380 12 111 2233",
"sValueNew":"+380 12 111 2233",
"sNotify":"Здесь строка из двухсот знаков. Здесь строка из двухсот знаков. Здесь строка из двухсот знаков. Здесь строка из двухсот знаков. Здесь строка из двухсот знаков. Здесь строка из двухсот знаков. И конец."

(это джейсонина, ид - название поля, значение - пример данных, которые там могут записываться)

Сюда будем сохранять поля, которые требуют уточнения.

При вызове сервиса замечания чиновника /action/event/updateHistoryEvent_Service больше не сохраняем значения в поля (таблица HistoryEventService поле soData, таблица SubjectMessage поле sData) в том случае, если это замечание!!!!!!!!. А сохраняем эти данные в новую сущность, которая связана с сущностью SubjectMessage один ко многому (тоесть добавить в сущность SubjectMessage  новое поле типа лист, который содержит объекты типа SubjectMessageQuestionField ). 

При уточнении данных гражданином (сервис /subject/message/getServiceMessages) апдейтить значение в сущности SubjectMessageQuestionField.

Протестировать после доработки задачи по фронту.

**Comment by NikolayAngel** [comment]
В данный момент задача не реализована, поля и комментарии к ним не передаются с дашборда чиновника в журнал клиента:
Отчет о тестировании:
https://docs.google.com/document/d/1GzV_IyAO5jPt5xkBjyLZH6u1YHLJ3-Q2yMhpiFKgU_k/edit

**Comment by ElenaShebaldenkova** [comment]
Николай, а при чем тут моя задача? Суть моей задачи описана в ишью. Для того чтоб ее протестировать необходимо:
 https://alpha.test.igov.org.ua/service/709/general
заходим в дашборд (кермит)
берем в работу
переходим в отправку зауважень
отмечаем 17 полей и вставляем комментарий по одному символу (либо пять полей с коментарием по 300 символов) 
отправляем замечание
идея в том, что емли сериализованный ДЖСОН с массивом замечаний больше 1500 знаков - БД отказывается принимать его одной строкой
и после сабмита замечаний - вываливалась ошибка
После сабмита замечаний - замечания должны прийти на почту
После того, как будут добавлены правки на фронте - замечания должны  будут отображаться на централе в Моем журнале и на дашборде в истории переписки.

## **Моя задача реализована полностью** - данные сохраняются в новую сущность, пишутся в базу и возвращаются сервисом https://alpha.test.igov.org.ua/wf/service/subject/message/getServiceMessages?sID_Order=5-330135717. 

"Протестировать после доработки задачи по фронту." - Николай, а это реализовано на фронте?

**Comment by OlgaTurenko** [comment]
Да, похоже на фронте еще не сделали задачу.

**Comment by NikolayAngel** [comment]
Не заполняются данные по типу date 
![image](https://cloud.githubusercontent.com/assets/11869200/25743454/28c13858-319d-11e7-8fcb-c6a7081da836.png)

**Comment by ElenaShebaldenkova** [comment]
Не заполняются данные по типу date, кнопка выбора даты не реагирует на стороне клиента. - Николай, Вы читали условие задачи к которой пишете комментарий? Каким образом не реагирующая кнопка выбора даты относится к созданию сущности-комментария?

**Comment by NikolayAngel** [comment]
При отправке ответа на замечания выдает ошибку ![image](https://cloud.githubusercontent.com/assets/11869200/25744070/888adff2-31a0-11e7-810f-78f2268e5e5e.png)

**Comment by NikolayAngel** [comment]
Последнее замечание переносим во фронт в задачу https://github.com/e-government-ua/i/issues/1554

**Comment by NikolayAngel** [comment]
есть тип textArea, в клиенте он позволяет вносить 4000 символов, но при внесении замечаний на дашборде выдает ошибку
![image](https://cloud.githubusercontent.com/assets/11869200/26065418/901c0a08-399c-11e7-9fc6-527e54ed566f.png)
