### ISSUE TITLE
При отображении данных по замечаниях брать теперь данные из сущности SubjectMessageQuestionField 

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1554]
При отображении данных по замечаниях брать теперь данные из сущности SubjectMessageQuestionField.

О том, что были замечания, теперь определять не по наличию контента в поле soData, а по статусу заявки (в сущности хисториэвентСервис)

(после реализации задачки по беку #1553)

**Comment by NikolayAngel** [comment]
Тестирование успешно. Все данные отправляются, отображаются, заполняются как в клиенте так и в дашборде с количеством символов более 200. При использовании более 300 символов выдает ошибку.
Подробный отчет:
https://docs.google.com/document/d/1-yWsiQ-NUvdOp_zY8cXVuKB0BWroqXZ7nyTBWsfutgQ/edit

**Comment by NikolayAngel** [comment]
Так же при отправке ответа на замечания выдает ошибку (возможно связано с невозможностью выбора даты)
![image](https://cloud.githubusercontent.com/assets/11869200/25744293/bdb0edd8-31a1-11e7-92e5-e49ed844fd87.png)

**Comment by GFalcon-UA** [comment]
Там БД на все колонки ограничение на длину текста поставили 255 знаков. Если вам достаточно будет такой длинны, я просто буду рубать длину строки. Если нет - давайте договариваться, какую длину задать для полей `sValue`,` sValueNew` и `sNotify`

**Comment by NikolayAngel** [comment]
1. Не выбирается дата на клиенте( скрин в замечании выше)

**Comment by agerman-ua** [comment]
> Не выбирается дата на клиенте( скрин в коментарии выше) 2. Длину строки оставляем везде 225, но вместо "рубания" строк выводим на клиенте и дашборде такое замечание : "Превышено допустимое количество в 225 символов для комментария"

225 - опечатка, правильно 255.

**Comment by GFalcon-UA** [comment]
Ув. Николай
1. Реализации поле даты я даже не касался, поэтому есть подозрение, что в этом бр оно и не работало нормально. Прошу сделать отдельный тестовый бп, на котором можно было бы протестировать отработку замечаний на всех возможных типах полей стартовой формы. У меня появились сомнения, что они все работают.
2. Если так сделать - это сделает страницу еще более "заторможенной". Предлагаю стандартный способ средствами браузера просто не давать ввести 256-й символ. Я верю, что люди, которые пользуются порталом, разумные и догадаются, что достигнут лимит и еще я очень сомневаюсь, что кто-то где-то будет подсчитывать, а какое же количество символов текста он уже набрал?

**Comment by NikolayAngel** [comment]
" Предлагаю стандартный способ средствами браузера просто не давать ввести 256-й символ" - такой вариант вполне подходит.

Дополнительная ошибки:
 тип fileHTML: тест отображается в дашборде, но становится недоступен при попытке внести замечание.
Тип file - нет возможности внести по нему замечание
Тип table - на дашборде присутствует только не активная кнопка "добавить рядок", вместо содержимого таблицы.
Тестовый процесс _test_coment.bpmn
Если удобней можем текущие вопросы обсуждать в скайпе (Пастух Николай), не всегда вовремя могу увидеть ваш ответ.

**Comment by NikolayAngel** [comment]
Тест

**Comment by GFalcon-UA** [comment]
Николай. Чтоб внести изменение в поле Дата - кликать надо на кнопку, а не текстом в поле. Вы же в услуге тоже дату, когда заполняли заявку - дату выбирали через кнопку
![image](https://cloud.githubusercontent.com/assets/13604023/26142904/466104fe-3aeb-11e7-8cea-17920ef34683.png)

**Comment by NikolayAngel** [comment]
Алексей, спасибо за помощь, действительно нужно на кнопку нажимать, а я вторую неделю в поле комент все жмакал и думал почему не получается:)
Но сейчас есть другая проблема комент или новую дату которую выбираю на клиенте не попадает в историю на дашборде
![image](https://cloud.githubusercontent.com/assets/11869200/26143799/1f3b13e8-3aef-11e7-923c-f8a81b11d43d.png)
![image](https://cloud.githubusercontent.com/assets/11869200/26143808/25a3bdf2-3aef-11e7-8d07-66a64a5223ff.png)

**Comment by antonlegkiy** [comment]
> а я вторую неделю в поле комент все жмакал и думал почему не получается:)

не получалось не потому что вы нажимали не на то, а потому что не работало поле типа "дата", оно было пофикшено позавчера.

**Comment by NikolayAngel** [comment]
Я понял, то ирония была на комент Алексея : "Чтоб внести изменение в поле Дата - кликать надо на кнопку, а не текстом в поле." Надеюсь Алексей все верно понял, смайлик я поставил.

**Comment by GFalcon-UA** [comment]
`Но сейчас есть другая проблема комент или новую дату которую выбираю на клиенте не попадает в историю на дашборде`
Сегодня как раз в это время делали правки на бек-энде по отправке ответов на замечание. Сегодня c 10 утра до 16:30 могла наблюдаться такая проблема на Альфе, но она уже исправлена

**Comment by NikolayAngel** [comment]
Тестирование успешно, тип дата передается в дашборд чиновника, остальная информация так же корректно передается. Спасибо.
