### ISSUE TITLE
Устранить ошибку при повторной попытке зайти в форму услуги при просроченной авторизации

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1556]
Если авторизоваться при заходе в какую-то форму услуги (выбрав город/область) и через какое-то время (пол часа или более, сколько живет сессия) - попробовать еще раз зайти в нее или другую - вылетит ошибка:
http://prntscr.com/eem7kw

приходится нажать выход и повторно авторизоваться...

**Comment by AleksejDomash** [comment]
вот фикс на альфе от 05.02.2017 https://github.com/e-government-ua/i/commit/5159af56c8e88c60e968ce7e3a1f8cbd5c3fbe54

**Comment by agerman-ua** [comment]
Процесс тестирования в файле
https://docs.google.com/document/d/14AmBPlpueN8DnYMxn0i2h5cU_ieVWJU8xLHBSSnQZ3k/edit?usp=sharing
Можно считать исходную проблему устранённой в принципе.
Стоит продолжить наблюдение уже на боевом.
