### ISSUE TITLE
Избавиться от типа поля invisible путем замены его на нужный тип + readable=false

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1558]
1)  Протестировать на централе и регионе, что поля с readable=false (тип стринг, лонг, дейт, файл, тейбл и тд) не отображаются

2) Протестировать на централе, что в поля с readable=false  и writable=true можно записывать значение.

2) Если по пунктам 1 и 2 ответ положительный, то поменять поля с типом invisible на соответственный тип + сделать его readable=false.

**Comment by NikolayAngel** [comment]
При локальной сборке в Эклипсе с параметром "readable" и 'readeble' выдает ошибку, что параметр не известен. Такая же ошибка и при сборке на Jenkins
Tests in error: 
.ActivitiProcessesTest): unknown type 'readable' privateMail
unknown type 'readeble' privateMail

**Comment by OlgaTurenko** [comment]
![default](https://cloud.githubusercontent.com/assets/10909557/23646505/c684141e-0319-11e7-85e5-bdcb2ea6e636.png)

**Comment by NikolayAngel** [comment]
Изменение параметра с readable=true на readable=false не принесло изменений alpha.test.igov.org.ua, поля по прежнему видны

**Comment by NikolayAngel** [comment]
![1](https://cloud.githubusercontent.com/assets/11869200/23648348/02720644-0323-11e7-8b1c-2aab402c5e4c.jpg)
![2](https://cloud.githubusercontent.com/assets/11869200/23648351/03fd4154-0323-11e7-9f3d-11707bdd2c5c.jpg)

**Comment by NikolayAngel** [comment]
1. Поля с readable=false (тип стринг, лонг, дейт, файл, тейбл и тд) на цетральном и региональном портале не отображаются.
2. Поля с readable=false и writabele=true Нельзя записывать значение (см.скрины)
![4](https://cloud.githubusercontent.com/assets/11869200/23656594/011e97ba-0343-11e7-9b37-449fafeaa2c6.jpg)
![3](https://cloud.githubusercontent.com/assets/11869200/23656610/0ee826a4-0343-11e7-8367-2a83bce04278.jpg)
3. Итог: поле можно сделать невидимым с помощью типа readeble=false, но при этом не будет возможности вносить в него данные при readeble=false и writabele=true

**Comment by NikolayAngel** [comment]
4. Данные можно вносить по умолчанию (default) в эклипсе, они будут не видны для пользователя (readable=false), но могут использоваться в самом БП.
![5](https://cloud.githubusercontent.com/assets/11869200/23670364/24bddf50-0370-11e7-9fe9-e2ca03661300.jpg)
![6](https://cloud.githubusercontent.com/assets/11869200/23670368/28615a92-0370-11e7-953a-5f13dbb5436c.jpg)

**Comment by NikolayAngel** [comment]
Замену всех процессов произвел Изменения сделал на https://alpha.test.igov.org.ua/1, по ссылке https://docs.google.com/spreadsheets/d/1_BeZBkfwkV-_he7UHQWUWDJqikIm2ObGH7-ktAI1FrI/edit#gid=0
