### ISSUE TITLE
Подмена ссылки на IDcard при авторизации и в журнале

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/i#1560]
на портале сейчас при нажатии IDcard сейчас идет переадресация на ссылку https://bankid.org.ua/
необходимо сделать переадресацию на следующую ссылку https://bankid.org.ua/DataAccessService/login?sidBi=787df445-dc82-4ce2-8ed8-95f8598b6788
во всех местах, где есть кнопка IDcard

![idcard](https://cloud.githubusercontent.com/assets/17762394/23650245/23253daa-032a-11e7-87fb-fd09c601034e.jpg)

**Comment by GFalcon-UA** [comment]
Сделал, хотя для пользователя - это +1 клик, а в результате он все равно пойдет пользоваться сервисом https://bankid.privatbank.ua/DataAccessService/mobileDigitalSignature , который и так до этого открывался при клике на эту кнопку
