### ISSUE TITLE
Доработать валидацию полей с типом long и double 

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1565]
Проблема с внесением значений в поля с типом long и double - валидаторы срабатывают не совсем корректно:
а) в тип лонг невозможно внести значение 0
б) в тип double невозможно внести значение от 0 до 0.99
Необходимо это пофиксить
![1](https://drive.google.com/uc?export=download&id=0B6mOkUg9oq1zT0M4SnZZR2t6WjA)  
задачу принимает Кулиш Андрей @Akylish88

**Comment by Akylish88** [comment]
![11](https://cloud.githubusercontent.com/assets/17428736/24661125/32f45a72-195a-11e7-89e3-1b45bd9b9cee.jpg)
![12](https://cloud.githubusercontent.com/assets/17428736/24661124/326bbda2-195a-11e7-82a8-6cd546d7349e.jpg)

**Comment by Akylish88** [comment]
Выявлена новая неполадка.
Нельзя в double внести целое число. На дашборде такая же ошибка.

Также при этом можно внести не числовые символы, например буквы знаки "*", "/", "-" и другие.

**Comment by GrekD** [comment]
@Akylish88 можно проверять

**Comment by msvidran** [comment]
Не передает второй ноль
![image](https://cloud.githubusercontent.com/assets/7354990/24752440/800f8ef8-1ad6-11e7-8a24-48ccb7b09bf5.png)

**Comment by Akylish88** [comment]
Тот же бажок, что описал Максим и на старте, вводиш 5.00, на дашбоард приходит 5.0

В остальном все хорошо. Больше ошибок не выявлено.

**Comment by GFalcon-UA** [comment]
Коллеги, `double` - это число с плавающей точкой. В нем нельзя определить, сколько нолей отображать после запятой (один, два, три или восемь).
Выход для такой ситуации - использовать поле с типом `string`, но навесить на него этот валидатор `DoubleNumber`

**Comment by Akylish88** [comment]
Ок, спасибо, тогда в версию.

**Comment by Akylish88** [comment]
Новая проблема с Double

Записал видео с ошибкой.
https://www.youtube.com/watch?v=xwWK4DzoeFI&feature=youtu.be

Услуга где выявлено:
https://delta.test.igov.org.ua/service/98/general

Процесс: DGK_0098_VidDokZemleust

П.С. Алексей скажите вам подходит формат сообщения про ошибки в виде видео?
Сделал первое, знаю есть некоторые недочеты. Но по вашим пожеланиям готов улучшить этот способ.

**Comment by GFalcon-UA** [comment]
Поправил ошибку на Альфе и Дельте

C видео - тоже можно, но желательно, чтоб там была видна адресная строка браузера. И чтоб ссылка на видео была в самом конце сообщения "на закуску".

**Comment by Akylish88** [comment]
Супер! Ошибки нет!

Большое спасибо за оперативность!
