### ISSUE TITLE
Обеспечить поддержку на фронте нового типа поля fileHTML

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1567]
- [x] Создать новый тип поля fileHTML (поддерживающий Html, со встроенным Html-редактором) - [ ] позволяющий пользователю форматировать текст непосредственно в поле
 **[Пример](https://drive.google.com/open?id=0B1uoWNhWT8YYZVgycHpVc3ZVQ0U)**
- [x] Введенный текст и форматы должны без изменений передаваться в принтформу
- [ ] Размер поля сделать как в типе textArea(с возможностью растянуть на фронте)

**Логика работы:**
- работать с контентом точно так-же как и для типа file, только без кнопки аплоада файла а именно сохранять тот контент, который введен в ХТМЛ-редакторе
- при этом, хоть контент и будет сохраняться как атач - на дашборде не отображать его как атач, а сам контент просто в обычном поле в ХТМЛ-редакторе
- как и для типа file, в значении(value) должен быть JSON-обьект, который так-же как и с тем типом - ни где не будет виден, но все остальное с ним будет происходить точно такое-же)

Задачу курирует и принимает Свидрань Максим @msvidran

**Comment by OlgaTurenko** [comment]
по беку решена задача. добавлен новый тип данных fileHTML
