### ISSUE TITLE
Приоритетные задачи по 1С vs iDoc

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1578]
- [x] Выносим форматирование дат (вынести в отдельный спринговый сервис **getDateFormatted_ByField**(sID_Field,sFormat)
- [x] просчет количества дней отпуска (вынести в отдельный спринговый сервис: **getDateDiff_ByField**(sID_Field_DateAt,sID_Field_DateTo)
- [x] определение логина аккаунта по логину акаунта iGov (вынести в отдельный Спринговый Сервис: **getLoginAccount_ByField**(sID_Field_LoginSelf, sID_SubjectAccountType))

**Comment by OlgaTurenko** [comment]
получить текущую дату в заданом формате:
получить разницу дат в днях:dateUtil.getDateDiff_ByField(snID_Process, sID_Field_DateAt, sID_Field_DateTo)
получить дату из поля в заданном формате: dateUtil.getDateFormatted_ByField(snID_Process, sID_Field, sFormat);
получить аккаунт организации по аккаунту айгова: subjectServiceю.getLoginSubjectAccountByLoginIgovAccount(sID_Login_Activiti, sID_SubjectAccountType)
