### ISSUE TITLE
Реализовать предоставление прав на степ при возврате на этот степ

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1580]
Реализовать предоставление прав на степ при возврате на этот степ. Тоесть если логин группы уже есть на степе и при этом уже проставлена дата сабмита, то мы эту жату ставить наловой, дату подписания ЭЦП ставим наловой, меняем права на те, которые в эталонной группе. (именно меняем в существующем сабджекте, не создаем новый). Тоесть у нас по-прежмену каждая персональная группа будет единожды фигурировать на степе.

**Comment by zolotovatatyana** [comment]
Проверено на работе _doc_oe_premium.  Процесс перепрыгивает на нужную таску, права выдаются в полной мере, поля writable как задумано. Проблем при тестировании не выявлено.

**Comment by zolotovatatyana** [comment]
2. Для возврата на ЮТ в новыми полями - объявляем в JSON новый степ, новую группу, и прописываем их в дополнительной скрипттаске. При попытке назначить новые права существующему степу - таска приходит в нужную группу но поля не доступны к редактированию.

подробнее в доке: https://docs.google.com/document/d/1OZ1oAGA-c6P4e4gBZkzGByR7tkJHO8akHqTb5tTXNAE/edit

**Comment by zolotovatatyana** [comment]
при возврате на прошлую ЮТ достаточно дать новые права на тот же степ. работает корректно.
