### ISSUE TITLE
Редизайн интерфейса заявки

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#1589]
Доработать дизайн заявки на портале igov.org.ua в соответствии с макетом
![default](https://cloud.githubusercontent.com/assets/11442397/24188064/8315d782-0ee8-11e7-99c4-37079cbb79b0.png)

1. Убрать серый фон заявки

2. Фразу о  перенаправлении на страницу ЭЦП  показываем только если в БП есть соответствующая переменная.
`<activiti:formProperty id="form_signed" name="Заява з ЕЦП;;bPrintFormFileAsPDF=true" type="file" required="true"></activiti:formProperty> `
Если эта переменная не обязательная, то  вместо  обычной кнопки заказа услуги отображаем 2 кнопки ( как показано на макете). Никогда не отображать чекбокс "накласти ЕЦП" (отображается при наличии на стартовой форме переменной `id="form_signed"`).

3. Отображать стандартный текст "Якщо ці або будь-які інші дані, які були передані з Вашого банку, вже не актуальні, просимо Вас звернутися до цього банку для актуалізації." только в том случае, если авторизация  пользователя была через BankID

4.Для отображения лейблов  сделать  пару стандартизированных пресетов стилей (в макете показаны "warning" и "information"). 

5. Звездочки, которые показывают обязательность поля к заполнению, отображать справа от названия поля. Сейчас отображается слева.

**Comment by antonlegkiy** [comment]
чтобы ваш лейбл был стилизирован нужным цветом (варианты - warning (желтый), success (зеленый), danger (красный), info (голубой)) нужно 3м параметром прописать его класс. 
пример: name=" ; ;labelType=warning"

если забудете прописать в нейм класс, то будет дефолтный - info.

**Comment by GrekD** [comment]
на боевом
