### ISSUE TITLE
Починить проверку а закрыт ли процесс

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1597]
Суть проблемы в том, что когда в процессе таймер не на юзертаске, то проверка, а есть ли еще активные таски, отдает ответ, что нет.
Детальное описание и процесс на котором сможем после фикса проверить:
https://docs.google.com/document/d/1Nf1_KzVrhQTgUb9g6_96WsP6LoEz3PtEH3YnCEEa_TE/edit
в коде это место проверки тут:
public class CloseTaskEvent
кусок кода где проверяем:
List<Task> aTask = taskService.createTaskQuery().processInstanceId(snID_Process).list();
                LOG.info("11111sUserTaskName before : " + snID_Process);// new log не меняется статус
                boolean bProcessClosed = (aTask == null || aTask.isEmpty());:

Нужно переписать логику проверки. смотреть не активные таски (taskService), а по ид бп-ка искать схему бп (репозиторийСервис) и проверять эта ли ид таски последняя. если да - процесс закрыт, если нет - процесс не закрыт

**Comment by Akylish88** [comment]
Был вопрос по паролю.
Логин:Akylish88
Пароль: 123456

**Comment by Akylish88** [comment]
Починено.
Спасибо.
Статус после таймера отображает правильный.
