### ISSUE TITLE
Доработать селект для айдока

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1598]
добавить в атрибуты нейма селекта еще один параметр
**sName_SubjectRole**
В параметре указывать ИД поля, в которое необходимо засетить значение логина 
будет выглядеть так:
```xml
<activiti:formProperty id="sApprover" name="Утверждающий; ;sID_SubjectRole=Executor,sID_Group_Activiti=sID_Group_Activiti,nDeepLevel=nDeepLevel,sName_SubjectRole=sPoleSet" type="select"></activiti:formProperty>
<activiti:formProperty id="sPoleSet" name="Логін" type="string"></activiti:formProperty>
```

**Comment by antonlegkiy** [comment]
параметр sName_SubjectRole не добавлял, подстроил селект SubjectRole под стандарты остальных селектов с постфиксами.
если несколько селектов на странице, выделить их можно при помощи постфиксов:
sName_First - sLogin_First
sName_Second - sLogin_Second
или
sName_ЛюбоеОбщееНазваниеДляГруппы_First - sLogin_ЛюбоеОбщееНазваниеДляГруппы_First
sName_ЛюбоеОбщееНазваниеДляГруппы_Second - sLogin_ЛюбоеОбщееНазваниеДляГруппы_Second

**Comment by GrekD** [comment]
работает, должен быть общий постфикс для полей. пример
```xml
<activiti:formProperty id="sName_DelegateUT3" name="кому делегировать; ;sID_SubjectRole=Executor,sID_Group_Activiti=sID_Group_Activiti,nDeepLevel=nDeepLevel" type="select"></activiti:formProperty>
<activiti:formProperty id="sLogin_DelegateUT3" name="Логін" type="invisible"></activiti:formProperty>
```
