### ISSUE TITLE
Добавить отслеживание Google Analytics на главный портал

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#160]
Вставить на главный портал:
< script >
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62587678-1', 'auto');
  ga('send', 'pageview');

< /script >

**Comment by levonet** [comment]
Я правильно понимаю, что главный портал лежит здесь `/portal-js/client`?

**Comment by bvv4ik** [comment]
не,
central-js

**Comment by levonet** [comment]
Со сборкой разобрался, беру в работу
