### ISSUE TITLE
Доработать сервис downloadTasksData

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1610]
- [x] добавить опциональный  параметр **asField_Filter**, который должен возвращать формулу для конкретного БП из поля **sFormulaFilter_Export** (SubjectRightBP).
- [x] И отфильтровывать результат выгрузки по этой формуле.

Название класса где реализован этот механизм **ToolJS.java**
```java
package org.igov.util;
public class ToolJS {
public static String getCalculatedFormulaValue(String sFormulaOriginal, Map<String, Object> mParam) {//String
```

Например в параметре **asID_FieldFilter_Export** для БП **subsidiesUkraine_ECP** указано **sID_Public_SubjectOrganJoin=s2,s3**
Это означает, что в БП **subsidiesUkraine_ECP** есть поле sID_Public_SubjectOrganJoin , и в выгрузку подтянуть только заявки где в поле **sID_Public_SubjectOrganJoin** значение **s2**(бабушкинский район) или **s3**(анд район)

Пример вызова сервиса
https://alpha.test.region.igov.org.ua/wf/service/action/task/downloadTasksData?&sID_BP=subsidiesUkraine_ECP&bHeader=true&sID_State_BP=usertask1&saFields=${nID_Task};${sDateCreate};${sID_Public_SubjectOrganJoin};${bankIdlastName}${bankIdfirstName}${bankIdmiddleName};${ECP}&sDateAt=2017-03-01&sDateTo=2017-04-20&asField_Filter=[sFormulaFilter_Export]&sLogin=testing

**Comment by alexfargo** [comment]
Тестирование проводил на БП justice_0353_PervDopom, на одной тестовой заявке.

Вызывал командой:
https://alpha.test.region.igov.org.ua/wf/service/action/task/downloadTasksData?sID_BP=justice_0353_PervDopom&bHeader=true&sID_State_BP=usertask1&saFields=${nID_Task};${sDateCreate};${asDecide}&sDateAt=2017-01-01&sDateTo=2017-05-05&asField_Filter=[asDecide==sAccept]

asDecide имеет три варианта: sAccept, sAnswer, sReject

Результат в Postman'е:
nID_Task;sDateCreate;asDecide
33065224;2017-05-04 15:15:27;sAnswer

Пробовал брать sAccept в одинарные и двойные кавычки, в условие ставил все три варианта, ничего не изменилось.

**Comment by yegorkovylin** [comment]
&asField_Filter=[asDecide==sAccept]

так задавать не правильно
задавать нужно как в примере, а само условие вносить в цсв

**Comment by alexfargo** [comment]
Протестировал на той же услуге с корректным запросом через SubjectRightBP.
Все работает. В Postman'е выдает то, что нужно. Работают как одинарные условия, так и двойные и больше.
Однако при попытке предоставить доступ на выгрузку данных двум разным группам пользователей (две строки в SubjectRightBP на разные asID_Group_Export), на разных условиях - в Postman'е выдает ошибку 500.
Также при выгрузке данных через кнопку "Звіт" на Регионе условие не работает, выгружаются все заявки.
