### ISSUE TITLE
Починить отображение типа fileHTML в файле подписанным ЭЦП

### ISSUE THREAD

**Issue by msvidran** [e-government-ua/i#1613]
Суть проблемы: при подписании ЭЦП стартовой формы в виде принтформы поля типа fileHTML проливаются в подписанный файл PDF в виде джейсона 
Описание проблемы https://docs.google.com/document/d/1Fqz2MqxVkv2t-7bwiiQI6tEPYN-2DsdoxN2KtjcH-p0/edit?usp=sharing

UPD:
Еще при использовании поля fileHTML в письме - поле в виде джейсона
![image](https://cloud.githubusercontent.com/assets/7354990/24747095/fac0bd38-1ac3-11e7-85a4-f2066589433e.png)

тестовый процесс https://alpha.test.igov.org.ua/service/1389/general
**с наложением ЭЦП**

UPD 2: обратить внимание на тип **table** - в подписанное заявление не приходят значения айдишников, в принтформе на дашборде заполняется все корректно
https://www.evernote.com/l/AceM1CMQRkZKIL3XddtKXA_Jk6kJI_GI0P8B/image.png

**Comment by GFalcon-UA** [comment]
На фронте централа исправил формирование ПДФ с полями типа `table` и `fileHTML`
Также, теперь поддерживаются все шаблонные теги, которые на данный момент доступны на дашборде:
```
[sDateCreateProcess]
[sTimeCreateProcess]
[sDateTimeCreateProcess]
[sDateCreate]
[sCurrentDateTime]
[sUserInfo]
```

Только тег `[sID_Order]` для центрально портала работать не будет

**Comment by OlgaTurenko** [comment]
спасибо большое! если все ок теперь, то просьба лейбл тест поставить

**Comment by msvidran** [comment]
Проверил. 
Конвертирует файл с наложенным ЭЦП - отлично. Тип fileHTML проливается в файл ПДФ нормально + таблица тоже.

осталось поправить тип fileHTML в письме - тогда сможем поставить лейбу "тест" и считать тикет закрытым

**Comment by msvidran** [comment]
контент типа fileHTML в письмо проливается.
