### ISSUE TITLE
Сохранять в глобальные переменные процесса sLogin_LastSubmited

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1617]
сохранять в глобальные переменные процесса логин последнего кто работал с таской - **sLogin_LastSubmited**

**Comment by OlgaTurenko** [comment]
Егор, это делать нужно там, где ты дату подписи и логин сохраняешь при сабмите.

**Comment by GrekD** [comment]
https://github.com/e-government-ua/i/issues/1617
не работает до конца так как надо:
130 подаем, в sLogin_LastSubmited записан автор justice_common
выбираю Васину - переходим на шаг 2 в sLogin_LastSubmited записан автор justice_common (верно)
под Васиной выбираю Симоненко - по идее когда я зайду под Симоненко, то в sLogin_LastSubmited  должна увидеть логин Васиной, а там все так же логин автора
т.е. нужно дохордить до третьего шага, при этом в селекте выбирать разных людей, чтоб понять что меняется логин sLogin_LastSubmited

**Comment by yegorkovylin** [comment]
работает

**Comment by GrekD** [comment]
работет ))
