### ISSUE TITLE
Починить отображение принтформ сформированые как ПДФ на следующей таске.

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1618]
принтформы сформированые как ПДФ не приходят на следующую таску. Поля дословно скопированы с тестового бп (где все работает) но в айДоке файлы не формируются. https://docs.google.com/document/d/139fL8xsU4ffGsxIDecYBzRoG5EU_9pghVDydXFpl1O4/edit

**Comment by zolotovatatyana** [comment]
работает на альфе
