### ISSUE TITLE
В дашборде, при наведении курсора мышки на табы(закладки) - менять значек курсора на "руку с указательным пальцем"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#162]

**Comment by dr1v3** [comment]
Взял

**Comment by dr1v3** [comment]
Посмотрел, он и так меняется как бы

**Comment by bvv4ik** [comment]
неа, на дашборде таким и остается...

**Comment by maxymshg** [comment]
посмотрите pull request если норм, то можете проливать. Я не большой спец css, так что любые замечания приветсвую.
