### ISSUE TITLE
Доработать метод cloneDocumentStepFromTable

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1620]
- [x] добавить еще один параметр **sID_FieldTable**, в котором будет указан идшник поля таблицы с которого надо взять логин для клонирования
- [x] если параметр не задан, то дефолтом брать **sLogin_isExecute**

**Comment by msvidran** [comment]
При возврате документа с замечанием и внесения замечания автором у согласующего нет возможность подписать заново. 
https://docs.google.com/document/d/1fQwZ5llUwaUOvqu0lHrhcUKpBqVb1CS8YTpQ3UD37fc/edit?usp=sharing
