### ISSUE TITLE
исправить ошибку в сервсисе isDocumentStepSubmitedAll

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1621]
не срабатывает скрипт проверки подписей в одном типе шаблонов
вот сам скрипт
```
var nID_Process = execution.getProcessInstanceId();
var obj3= documentStepService.isDocumentStepSubmitedAll(nID_Process, 'test', 'step_2')
execution.setVariable('bSubmitedAll', obj3.bSubmitedAll.toString())
```
при этом в другом БП он работает

отличие в БП в котором не работает в том, что я проверяю **все ли ознакомились** а не **все ли подписали**
т.е. сами права у этих юзеров были только на просмотр и при нажатии на кнопку "ознайомлений" вылазит ошибка

> {code: "SYSTEM_ERR", message: "Transaction rolled back because it has been marked as rollback-only"}
> code:"SYSTEM_ERR"
> message:"Transaction rolled back because it has been marked as rollback-only"

после закрытия ошибки таска как бы обработанная, не доступна для подписи, но и у других ознакамливающихся уже не появляется
проверять на БП
_doc_justice_31.bpmn
под логином/паролем **justice_common**

**Comment by OlgaTurenko** [comment]
![image](https://cloud.githubusercontent.com/assets/10909557/24838661/f463578c-1d54-11e7-8058-6a343f79dd85.png)

**Comment by GrekD** [comment]
ошибка была в БП - на юзертаске, которую проверяют на наличие всех подписей не должен стоять листенер SetTask
