### ISSUE TITLE
Сервис "Делегировать" подписанта документа

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1623]
https://docs.google.com/document/d/1JhGRq_OcmSQGJWdhdzvbD3CUIx6lpZxWkRhOW9-8AxU/edit

Сервис /delegateDocumentStepSubject (и РЕСТ и СПРИНГ)

**Comment by msvidran** [comment]
Ничего не происходит при нажатии кнопки "Делегувати". Селект возле кнопки выбирается. Малюткину в дашборд ничего не попало.
![image](https://cloud.githubusercontent.com/assets/7354990/24963925/9898939e-1fa8-11e7-8a91-3f97db726e70.png)

**Comment by msvidran** [comment]
UPD:
в шаблоне для Мироновского хлебопродукта в селект кнопки "Делегувати" подтягиваются люди другого предприятия
![image](https://cloud.githubusercontent.com/assets/7354990/24967201/fc502204-1fb1-11e7-872f-a14b49dcd5b4.png)

**Comment by msvidran** [comment]
@yegorkovylin 
у @kr220290pjj повторяется проблема с подтягиванием в сервис делегирования людей из другой компании
UPD: сейчас проверила, при делегировании в процессах МинЮста тянет дерево БиТиСолюшин и на альфе и на дельте

![image](https://cloud.githubusercontent.com/assets/7354990/26572060/1e6668a0-4521-11e7-94b6-19764b4b9d97.png)
