### ISSUE TITLE
Реализовать кнопку "делегировать" для текущего подписанта документа

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1624]
На основании реализации сервиса: /delegateDocumentStepSubject
delegateDocumentStepSubject(String snID_Process_Activiti, String sKey_Step, String sKey_Group, String sKey_Group_Delegate)

На базе ишью: https://github.com/e-government-ua/i/issues/1623
Где основная идеология: https://docs.google.com/document/d/1JhGRq_OcmSQGJWdhdzvbD3CUIx6lpZxWkRhOW9-8AxU/edit

- [x] 1) Начинать отображать в раду кнопок действий с документом кнопку "Делегировать"
- [x] 2) При клике на эту кнопку отображать автокомплит всего дерева сотрудников (отображать ФИО и справа в скобках логин)
- [ ] 3) При выборе какого-то из сотрудников - вызывать сервис /delegateDocumentStepSubject с параметрами, где:
- последний параметр sKey_Group_Delegate - логин(персональная группа) выбранного сотрудника
- а в предпоследний sKey_Group брать значение из переменной sID_Group_Activiti (а если ее нет то дефолтом чтоб это было "mu")
- [ ] 4) Поле успешной отработки - перезагружать интерфейс с документом (только с открытым документом а не всего браузера)

Приемка работы: Дарья Грек

**Comment by OlgaTurenko** [comment]
Максим, вроде ж уже это сделали? Поставь лейбл вершин и закрой задачу пожалуйста
