### ISSUE TITLE
При отмене слота отражать изменение статуса в журнале

### ISSUE THREAD

**Issue by julyprodan** [e-government-ua/i#1628]
1. Заказать https://alpha.test.igov.org.ua/service/176/general (кроме Новокодацкого, областного и Шевченковского)
2. Через журнал кнопкой отменить слот 
![image](https://cloud.githubusercontent.com/assets/17750882/25088446/1a585ac0-237f-11e7-8156-6fa8f6c29250.png)
3. Ваша заявка відмінена. Ви можете подати нову на Порталі державних послуг iGov.org.ua.
З повагою, команда порталу  iGov.org.ua Появится такая надпись, но в журнале смена статуса не произойдет. 
![image](https://cloud.githubusercontent.com/assets/17750882/25088482/573dc420-237f-11e7-8958-1a9a25484b6d.png)

Добавить при отмене статус в журнал "Ви самостійно скасували заявку" и менять статус В обробці на закрыта. 
 Проверяет: Юлия Продан

**Comment by NikolayAngel** [comment]
Тестирование на Дельте прошло успешно. Отчет о тестировании:
https://docs.google.com/document/d/1WjM_IKdSXmJ3Gulz5-3c_9XhdNkYA0GZsLcjoDXHICg/edit
