### ISSUE TITLE
Проверить все  существующие БП на наличие письма гражданину после старта процесса

### ISSUE THREAD

**Issue by julyprodan** [e-government-ua/i#1629]
Для изменения схемы - по умолчанию письмо есть, для отключения вносить исключение в C:\e-gov\NetBeansProjects\i\wf-base\src\main\java\org\igov\service\controller\interceptor\RequestProcessingInterceptor.java
Проверить все текущие БП на наличие письма после старта, все БП, в которых письма нет, внести в таблицу. 
**Задача состоит**  в том, чтобы пройтись по корню автодеплоя (правильно в eclipse в диаграмме активити) и проверить наличие письма *для гражданина* (servicetask)  сразу после старта (startevent). Все БП, в которых нет письма *гражданину* , нужно занести в гугл-таблицу, потом дать ссылку. Заносить ОБЯЗАТЕЛЬНО не нейм, а ID process.
Проверяет: Юлия Продан

**Comment by NikolayAngel** [comment]
Создал таблицу с ид БП в которых нет сервистаски https://docs.google.com/spreadsheets/d/1_BeZBkfwkV-_he7UHQWUWDJqikIm2ObGH7-ktAI1FrI/edit#gid=1838727331

**Comment by NikolayAngel** [comment]
Список БП с ид находится по адресу \wf-base\src\main\resources\sendMail.properties . Тестироование работоспособности провели на Омеге и боевом
