### ISSUE TITLE
Поменять схему в работе автописьма

### ISSUE THREAD

**Issue by julyprodan** [e-government-ua/i#1635]
На текущий момент автописьмо приходит по всем БП после стартаски. Отключаем вручную в файле C:\e-gov\NetBeansProjects\i\wf-base\src\main\java\org\igov\service\controller\interceptor\RequestProcessingInterceptor.java строка 72

Изменить схему таким образом, чтобы по умолчанию автописьмо не приходило, но можно было включать для отдельных БП. 
Проверяет: Юлия Продан

**Comment by OlgaTurenko** [comment]
Тоесть хранить список (лист) бп-к, по которым необходимо делать рассылку. если заказалась услуга из списка - письмо отправляем. иначе не шлем. Заполнить список данными из таблицы. Таблицу предоставит Продан Юлия.

**Comment by ElenaShebaldenkova** [comment]
Сделала доработку: вынесла список бп, по которым надо отправлять автописьмо в отдельный файл sendMail.properties( \wf-base\src\main\resources\sendMail.properties) - редактирование
процессов теперь делать здесь, при добавлении - через запятую, а перенос на новую строку -  запятая пробел и косая черта.

**Comment by NikolayAngel** [comment]
Внес изменения в инструкцию
