### ISSUE TITLE
При загрузке документов выявить места, где тратиться много времени

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#1640]
При загрузке списка документов на вкладке Документы (если их много) грузятся долго. Добавить логирование чтоб понять узкие места (потом убрать) выяснить на какие операции тратиться больше всего  время.

**Comment by Deivur** [comment]
Разбил сервис getTasks контролера ActionTaskCommonController на 8 логических участков. В итоге вот этот кусок кода отрабатывается на два порядка дольше чем остальные 7.
`List<Map<String, Object>> data = new LinkedList<>();
                if ("ticketCreateDate".equalsIgnoreCase(sOrderBy)) {
                    oActionTaskService.populateResultSortedByTicketDate(bFilterHasTicket, tasks, mapOfTickets, data);
                } else {
                    oActionTaskService.populateResultSortedByTasksOrder(bFilterHasTicket, tasks, mapOfTickets, data);
                }`

**Comment by Deivur** [comment]
Проанализировав файл логов, нашел код который выполняется дольше всего. Строка, которая дольше всего отрабатывает находится в сервисе ActionTaskService.java в методе 
void populateResultSortedByTasksOrder(boolean bFilterHasTicket,
            List<?> tasks, Map<String, FlowSlotTicket> mapOfTickets,
            List<Map<String, Object>> data)
который вызывает:
Map<String, Object> populateTaskInfo(TaskInfo task, FlowSlotTicket flowSlotTicket)
в цикле, и отрабатывает за разное время от 0,1 с до 0,8 с. Строка из метода 
HistoricProcessInstance processInstance = oHistoryService.createHistoricProcessInstanceQuery().
                processInstanceId(task.getProcessInstanceId()).
                includeProcessVariables().singleResult();
Выполняется от 0,1с до 0,5с для одной таски. processInstance  используется для получения sPlace, который потом кладется в результирующую мапу.
Попробовал закомментировать код, где получаем sPlace. В результате документы загрузились за 0,6 секунды.

**Comment by OlgaTurenko** [comment]
Прошу доработать сервис так:
Если sFilterStatus= Documents, то не делать этот механизм по populateResultSortedBу

**Comment by Deivur** [comment]
Выполнив доработку документы вообще перестали отображаться, сам контролер возвращает пустой массив: {"total":117,"data":[],"size":15,"start":0,"sort":"id","order":"asc"}

Решели сделать проверку, непосредственно перед вызовом кода, который тормозит в методе populateTaskInfo. Изначально это сделать нельзя было, так как не передавалось значение sFilterStatus. Добавил это поле аргументом в populateResultSortedByTasksOrder, и перегрузил метод  populateTaskInfo, чтобы в нем реализовать проверку sFilterStatus= Documents.

Как результат время загрузки документов уменьшилось с  6 - 11 секунд до 0,4 - 0,6

![default](https://cloud.githubusercontent.com/assets/8025638/25429656/5fdc868e-2a82-11e7-8de0-19e09e3996c8.PNG)

**Comment by OlgaTurenko** [comment]
спасибо!
