### ISSUE TITLE
Разобраться с ошибкой сервиса startProcess

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1645]
сервис бьет ошибку
https://alpha.test.region.igov.org.ua:443/wf/service/action/task/startProcess?nID_Service=1&nID_ServiceData=1&nID_Subject=1&sID_BP=chervonograd_cnap_301&sID_UA=1&sLogin=MJU_common

{"code":"SYSTEM_ERR","message":null}

**Comment by ElenaShebaldenkova** [comment]
Даш, убери ее пожалуйста - она самопочинилась)
