### ISSUE TITLE
На главном портале подгружаемые по БанкИД поля(при заполнении формы) - отрисовывать в виде лэйблов а не инпут-ов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#165]
так-же как это сейчас на PHP-портале: test.e-gov.org.ua (репозиторий /i/portal-php)

**Comment by Kiaba** [comment]
Залишилось розібратися зі складними полями типу "Паспортні дані" і т.д.

**Comment by bvv4ik** [comment]
для этого уже другая задача:
https://github.com/e-government-ua/i/issues/224
