### ISSUE TITLE
Очищать sCancelInfo при выборе слота следующим гражданином

### ISSUE THREAD

**Issue by julyprodan** [e-government-ua/i#1656]
1. Заказывается слот;
2. Отменяется этот слот;
3. Он же заказывается заново 
и сразу приходит информация, что он отменен по времени отмены первого слота 
за сутки до посещения в заявке менятеся  статус на  Закрыто

Проверяет Юля Продан

**Comment by NikolayAngel** [comment]
Тестирование на Дельте прошло успешно. Отчет о тестировании:
https://docs.google.com/document/d/1WjM_IKdSXmJ3Gulz5-3c_9XhdNkYA0GZsLcjoDXHICg/edit
