### ISSUE TITLE
сформировать статистику использования BankID на портале

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#1657]
из логов фронта централа, через эластиксерч - сформировать статистику за 2017 помесячно за 4 месяца (январь-апрель), по числу используемых разных авторизаций
файл central-js_out.log
искать такие вхождения в логах:
/bankid/callback
/bankid-nbu/callback
/eds-/callback

**Comment by Dimiys** [comment]
В связи с отсутствием логов старше периода 07.04.2017, сделал парсинг по каждому дню по каджому из вхождений в период 07.04.2017-02.05.2017
('bankID', 0)
('NBU', 57 51 28 24 54 79 57 14 72 13 3 2 81 68 95 86 37 39 51 61 122 57 39 24 33 33)
('eds-', 0)

**Comment by Dimiys** [comment]
Изменил поиск по вхождениям и написал для него скрипт на python.
вот какие результаты получились в период 04.07- по сегодня
('bankID', 57123)('NBU', 1477)('eds', 5362)
в проц. соотношении('bankID', 89.3)('NBU', 2.3)('eds', 8.3)
