### ISSUE TITLE
Реализовать авто-тесты для дашборда, с добавлением в Дженкинс строки запуска теста

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#169]

**Comment by dmoskovsov** [comment]
Сделано. Деплой dashbordjs при неработающих тестах больше невозможен.

**Comment by bvv4ik** [comment]
я-б сказал даже больше: работа дашборда - больше невозможна))
П.С.: он поламался после этого последнего коммита

**Comment by bvv4ik** [comment]
после вот этого:
githubBOT [2:05 AM] 
[i:test] 1 new commit by Daniil:
009d974: Testing CI - fix [31mFatal error: listen EADDRINUSE[39m]. - Daniil

сам сайт: https://test.e-gov.org.ua/admin
