### ISSUE TITLE
Реализовать авто-тесты для главного портала, с добавлением в Дженкинс строки запуска теста

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#170]

**Comment by bvv4ik** [comment]
уже-ж вроде было реализовано, но поломало сборку проекта и пришлось откатить.
прошу пофиксить и продеплоить заново

**Comment by dmoskovsov** [comment]
Для того чтобы прогнать тесты в проекте дашборд откройте client/Gruntfile.js, наидите строку

  grunt.registerTask('build', [
    'clean:dist',
    'concurrent:dist',
    'injector',
    'wiredep',
    'useminPrepare',
    'autoprefixer',
    'ngtemplates',
    'concat',
    'ngAnnotate',
    'copy:dist',
    'cdnify',
    'cssmin',
    'uglify',
    'rev',
    'usemin'
  ]);

Замените на 

  grunt.registerTask('build', [
    'clean:dist',
    'concurrent:dist',
    'injector',
    'wiredep',
    'useminPrepare',
    'autoprefixer',
    'ngtemplates',
    'concat',
    'ngAnnotate',
    'copy:dist',
    'test',
    'cdnify',
    'cssmin',
    'uglify',
    'rev',
    'usemin'
  ]);

Деплоймент на тестовый сервер перестанет работать даже несмотря на то что дженкинс удачно соберает билд.

**Comment by bvv4ik** [comment]
ну, теоретически можно скопировать этот "client/Gruntfile.js" в "client/Gruntfile_local.js", чтоб локально именно его запускать а не менять его контент каждый раз, НО:
1) нам всеравно важно запускать тесты именно при деплое, потому хвсеже нужно понять - почему эти тесты не запускаются корректно при деплое..
2) синхронно изменять два файла будет явным усложнением процедуры...
3) сложно будет людей научить использовать для локального запуска один файл а для общего другой..

может можно как-то запустить тесты отдельно, типа grunt test?, в скрипте дженкинса?
я готов поучаствовать, чтоб проанализировать ошибки, которые возникают на джобе дженкинса, чтоб таки тесты там появились по умолчанию...
