### ISSUE TITLE
Добавить отслеживание Google Analytics на дашбоард

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#171]
Вставить на дашбоард(пробелы в тэгах скрипт убрать):
< script >
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62587678-3', 'auto');
  ga('send', 'pageview');

< /script >

**Comment by levonet** [comment]
Взял в работу
