### ISSUE TITLE
На главном сайте, все логирование (NodeJS, pm) обязательно привести в строгое соответствие со стандартом! 

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#177]
1) Всегда, в начале выводимой строки выдавать таймштамп в формате "YYYY-MM-DD_HH:mm:ss.nnn "
2) Не выводить контент файлов (тем более байты)
3) стараться придерживаться такого формата вывода каждой строки вывода:
(таймштамп)\[(название функции)\]\((Переменные со значениями, через запятую)\):(текст сообщения)

**Comment by AleksejDomash** [comment]
Привет, @ValerijMakarenko . В файлах process.json надо добавить "log_date_format" : "YYYY-MM-DD_HH:mm:ss.SSS", см. пример в https://github.com/e-government-ua/i/commit/501f342

**Comment by bvv4ik** [comment]
" В файлах process.json надо добавить "log_date_format" : "YYYY-MM-DD_HH:mm:ss.SSS""

Готово!
