### ISSUE TITLE
На бэке Java, все логирование (log4j и systemout) обязательно привести в строгое соответствие со стандартом! 

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#178]
1) Всегда, в начале выводимой строки выдавать таймштамп в формате "YYYY-MM-DD_HH:mm:ss.nnn "
2) Не выводить контент файлов (тем более байты)
3) стараться придерживаться такого формата вывода каждой строки вывода:
(таймштамп)\[(название функции)\]\((Переменные со значениями, через запятую)\):(текст сообщения)

**Comment by glebzhebrakov** [comment]
Могу взять для старта, предлагаю также заменить весь systemout на log4j

**Comment by bvv4ik** [comment]
Отлично, 
и предложение поддерживаю!
Спасибо, ассигну тогда...

есть какой-то прогноз по времени реализации?

**Comment by glebzhebrakov** [comment]
Я думаю до вторника справлюсь, я проект засетапил, все стартует, но еще не разобрался, так что беру с запасом.

**Comment by bvv4ik** [comment]
Понял, еще раз спасибо, ожидаю...
если че - я всегда на связи... можно в личку слак-а: bvv4ik или в скайп belyavtsevw

**Comment by glebzhebrakov** [comment]
Под "Переменные со значениями, через запятую" имеются в виду переменные. которые были переданы в метод, откуда пишется лог ? 
Например: void example(a,b,c) { log.info("message");  } , то выводить a,b,c ?

**Comment by glebzhebrakov** [comment]
В данный момент сообщения их логгера приведены к виду : 
2015-05-10_20:19:43.787[org.springframework.web.servlet.FrameworkServlet.initServletBean]:FrameworkServlet 'dispatcher': initialization completed in 1991 ms

**Comment by glebzhebrakov** [comment]
пулл реквест : https://github.com/e-government-ua/i/pull/205
