### ISSUE TITLE
На всех серверах установить одинаковое время и дату + временную зону

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#179]
чтоб велось корректное логирование

**Comment by ValerijMakarenko** [comment]
готово

**Comment by alekseymykhailov** [comment]
на все сервера установлен NTPd папетом 
так что дата должна быть коректна

```
# ntpq -np
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*91.236.251.12   105.240.56.33    2 u   89 1024  377   61.682   -4.083   2.821
+91.236.251.5    36.224.68.195    2 u   99 1024  377   62.655    0.173   2.047
+195.214.215.17  91.236.251.12    3 u   69 1024  377   48.922    0.909   1.153
-217.175.0.36    78.154.171.62    3 u  422 1024  377   83.790   -4.477   2.807
```


а таймзону нужно устанавливать через cloud-init на этапе запуска инстанса
и я добавлю изменение таймзоны через паппет (https://github.com/e-government-ua/i/issues/260) для уже запущеных серверов или для тех где не устанавливается TZ на этапе деплоя (чтобы в следующий раз не менять руками)
