### ISSUE TITLE
Создать REST-сервис обертку для запуска авто-тестов бизнес-процессов через jMeter

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#187]
в /i/wf-base

Фактически нужно будет в рантайме выполнить:
jmeter -n -t wf-base/src/main/resources/jmeter/Activiti.jmx -Jemail={email} -Jserver={server} -Jport={port} -Jprotocol=https -Jcontext=wf-dniprorada -Jlogin={login} -Jpassword={password}

которое было реализовано по задаче:
https://github.com/e-government-ua/i/issues/152#issuecomment-99994478

установить лимит времени выполнения в 2 мин. потом прибивать тред.
по итогу отдавать ответ в виде объекта JSON (желательно отобразить там число найденных и протестированных БП)

**Comment by vbolshutkin** [comment]
Тут есть одна проблема - в том, что так придётся иметь JMeter на машине с развернутым порталом и скрипт таскать. Можно попробовать использовать облачный BlazeMeter, там есть бесплатный тариф и он вроде совместим с JMeter.

Либо отойти от JMeter вообще и запилить обычный Java-код, который легко будет выставить как сервис (там и емейлы можно будет "замОчить"). Об этом мы еще подумаем.

И вообще, я скорее попробовал бы его вставить по вызову mvn integration-test с каким-нибудь ключем типа -DjmeterTest=true. Плагины jmeter-maven-plugin и chronos-maven-plugin имеются.

**Comment by vbolshutkin** [comment]
Или в Jenkins вкрутить, это и сейчас несложно. Впрочем, после интеграции с мавеном, это стало бы еще проше

**Comment by bvv4ik** [comment]
"Тут есть одна проблема - в том, что так придётся иметь JMeter на машине с развернутым порталом и скрипт таскать."
так это вообще не проблемма, т.к. мы и так на всех машинах для "Рад" наследуемся от ядра, "wf-base", в котором в т.ч. и активити эксплорер... и на эти-же машины копируется по экземпляру портала для чиновников... теперь еще будет копироваться и jMetter, так что все норм... он должен быть свой на каждой производной машине, т.к. на каждой этой производной машине свой набор БП будет..

вот сейчас докручивают https://dniprorada.e-gov.org.ua + https://dniprorada.e-gov.org.ua/admin
которые разворачиваются с репозитория: "_Dnipropetrovsk_MVK"
так что там можно и потренироваться (РЕСТ должен быть в ядре /i/wf-base)

**Comment by bvv4ik** [comment]
в Дженкинс - само-собой вкрутим

**Comment by vbolshutkin** [comment]
>теперь еще будет копироваться и jMeter
Ну я имел ввиду, что придётся еще и само приложение Apache JMeter таскать. Оно, впрочем, не очень большое и почти не требует зависимостей.

**Comment by bvv4ik** [comment]
за это не переживай... тут лучше таскать, т.к. со временем часть региональных серверов всеравно переедут на чужое железо, и единая централизованная система тестирования уже не подошла-бы...

а кроме того, приходилось-бы гдето вести и постоянно актуализировать полный перечень серверов, на которых находятся БП.. и к тому-же, если у них будут разны авторизационные данные, то еще и этим себе голову морочить..  а так, все данные по авторизации при деплое автоматом смогли-бы проливаться куда нужно, в рамках региональной машины,
