### ISSUE TITLE
Бизнес-процессы не могут быть завершены, если запущены с невалидным email

### ISSUE THREAD

**Issue by vbolshutkin** [e-government-ua/i#188]
Баг затрагивает большинство текущих БП стандартного образца (заявка-обработка-отправка_письма).

Шаги воспроизведения:
1. откройте БП Дніпропетровскька МДА - Легалізація об’єднань громадян шляхом повідомлення
2. Запустите процесс, указав невалидный email (например "asd"). Обратите внимание, что процесс стартовал 
3. Откройте очередь задач для отдела Sales, выберите задачу "Входящие", примите её и закройте с указанием отдела.
4. Откройте очередь задач для выбранного отдела, выберите задачу "Обработка", примите её и попытайтесь закрыть.
5. Обратите внимание на ошибку "Could not add asd as recipient", что задача "Обработка" не закрыта и что процесс висит без видимой возможности его удалить.

Ожидаемое поведение:
1. При возникновении ошибки, связанной с неправильным заполнением формы следует предусмотреть в БП создание задачи на пользователя для на повторное заполнение формы
2. Ошибки сервис-тасков не должны блокировать завершение пользовательских тасков.
3. Поле email должно валидироваться на форме. Процесс с таким значением email не должен начинаться вообще
4. При возникновении такой ошибки при наличии валидации формы следует предусмотреть в БП отправку сообщения системному администратору / безопаснику, потому что это может свидетельствовать о поломках валидации / попытках взлома.

**Comment by bvv4ik** [comment]
уже реализован специальный тип поля "markers", в котором можно хранить в спец-формате описание того - какие поля и как нужно валидировать.

т.е. достаточно указывать там названия полей с электронками для проверки, и валидность электронки может проверяться на фронте, посредством вызова сервиса на бэке.

**Comment by bvv4ik** [comment]
@vbolshutkin возьмешься за написание сервиса на бэке?

**Comment by bvv4ik** [comment]
написаны валидаторы,
не актуально

**Comment by bvv4ik** [comment]
написаны валидаторы
не актуально
