### ISSUE TITLE
Разобраться с DeadLock в Activiti

### ISSUE THREAD

**Issue by vbolshutkin** [e-government-ua/i#189]
Однажды в процессе тестирования (2 потока) была получена следующая ошибка

{"code":"SYSTEM_ERR","message":"\n### Error updating database.  Cause: org.h2.jdbc.JdbcSQLException: Deadlock detected. The current transaction was rolled back. Details: \"\nSession #757 (user: SA) on thread http-nio-8080-exec-9 is waiting to lock PUBLIC.ACT_HI_ACTINST while locking PUBLIC.ACT_HI_DETAIL (exclusive), PUBLIC.ACT_RU_VARIABLE (exclusive), PUBLIC.ACT_HI_VARINST (exclusive).\nSession #758 (user: SA) on thread http-nio-8080-exec-10 is waiting to lock PUBLIC.ACT_HI_DETAIL while locking PUBLIC.ACT_RU_EXECUTION (exclusive), PUBLIC.ACT_HI_PROCINST (exclusive), PUBLIC.ACT_HI_ACTINST (exclusive).\"; SQL statement:\ninsert into ACT_HI_DETAIL (ID_, TYPE_, PROC_INST_ID_, ACT_INST_ID_, EXECUTION_ID_, TASK_ID_, TIME_, NAME_, TEXT_)\n    values (\n      ?,\n      'FormProperty',\n      ?,\n      ?,\n      ?,\n      ?,\n      ?,\n      ?,\n      ?\n    ) [40001-176]\n### The error may involve org.activiti.engine.impl.persistence.entity.HistoricDetailEntity.insertHistoricFormProperty-Inline\n### The error occurred while setting parameters\n### SQL: insert into ACT_HI_DETAIL (ID_, TYPE_, PROC_INST_ID_, ACT_INST_ID_, EXECUTION_ID_, TASK_ID_, TIME_, NAME_, TEXT_)     values (       ?,       'FormProperty',       ?,       ?,       ?,       ?,       ?,       ?,       ?     )\n### Cause: org.h2.jdbc.JdbcSQLException: Deadlock detected. The current transaction was rolled back. Details: \"\nSession #757 (user: SA) on thread http-nio-8080-exec-9 is waiting to lock PUBLIC.ACT_HI_ACTINST while locking PUBLIC.ACT_HI_DETAIL (exclusive), PUBLIC.ACT_RU_VARIABLE (exclusive), PUBLIC.ACT_HI_VARINST (exclusive).\nSession #758 (user: SA) on thread http-nio-8080-exec-10 is waiting to lock PUBLIC.ACT_HI_DETAIL while locking PUBLIC.ACT_RU_EXECUTION (exclusive), PUBLIC.ACT_HI_PROCINST (exclusive), PUBLIC.ACT_HI_ACTINST (exclusive).\"; SQL statement:\ninsert into ACT_HI_DETAIL (ID_, TYPE_, PROC_INST_ID_, ACT_INST_ID_, EXECUTION_ID_, TASK_ID_, TIME_, NAME_, TEXT_)\n    values (\n      ?,\n      'FormProperty',\n      ?,\n      ?,\n      ?,\n      ?,\n      ?,\n      ?,\n      ?\n    ) [40001-176]"}

Следует разобраться, почему так могло произойти, не является ли это багом Активити.

**Comment by maxtmn** [comment]
Это связано с базой данных. в h2 по умолчанию лочатся таблицы.
на postgres по умолчанию лочки не ставятся, и, соответственно такой ошибки не будет.

на h2 можно попробовать отключить лочки:
  final DataSource ds = new SimpleDriverDataSource(new 
org.h2.Driver(), "jdbc:h2:mem:test_db;MVCC=TRUE", "sa", "");
 ds.getConnection().createStatement().execute("SET 
DEFAULT_LOCK_TIMEOUT 60000");

но, наверное, всеравно нет смысла пускать "нагрузочные" тесты на тестовой среде.
