### ISSUE TITLE
Некоторые БП невозможно завершить без заполнения полей, которые указаны как необязательные

### ISSUE THREAD

**Issue by vbolshutkin** [e-government-ua/i#190]
Этот баг затрагивает несколько БП, в основном из "Миколаєвська ОДА".

Шаги воспроизведения:
1. открыть БП "Миколаєвська ОДА - Взяття на облік громадян, які потребують поліпшення житлових умов"
2. Начать его, не заполняя необязательных полей.
3. Открывать задачи процесса и пытаться их завершать
4. Обратите внимание, что задача "Підготовка витягу з рішення виконавчого комітету Ммр щодо взяття на квартирний облік" не может быть закрыта с ошибкой 

"Unknown property used in expression: Шановний(-а), ${bankIdfirstName} ${bankIdmiddleName}.

Ваше звернення оброблено.
Ви можете отримати витяг"

Кроме того, есть БП, в котором проблема глубже: Калуська РДА - Видача витягу з технічної документації про нормативну грошову оцінку земельної ділянки. Там поля имя/фамилия отмечены как обязательные, но даже их заполнение не спасает от ошибки

**Comment by kurbpa** [comment]
На понимание - для воспроизведения БП  надо открывать  с портала? или  речь идет о старте процесса из активити эксплорера?3

**Comment by vbolshutkin** [comment]
Я обнаружил это при старте из активити эксплорера. Точнее даже, обнаружил автотестом через REST, перепроверил в активити эксплорере. 

Судя по всему, из портала может и не воспроизводится, т.к. поля ${bankIdfirstName} будут подсовываться вне зависимости от того, указано ли в процессе required для поля. Но "Калуська РДА - Видача витягу з технічної документації про нормативну грошову оцінку земельної ділянки" может и с портала воспроизвестись, похоже. Но это всё я не проверял

**Comment by kurbpa** [comment]
хм... более тщательно перепроверю все обязательны поля
С портала такой ошибки не должно быть вообще

**Comment by bvv4ik** [comment]
вообще это еще актуально?

**Comment by bvv4ik** [comment]
не актуально
