### ISSUE TITLE
На центральном портале динамически формировать список документов на основании массива обьектов-документов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#192]
1) Массив объектов документов, который описан в задаче:
https://github.com/e-government-ua/i/issues/191
нужно пока захардкодить (на основании уже имеющегося списка в макете), и далее формировать список при входе на закладку только на основании и этого массива.
(позже он будет подтягиваться из созданного сервиса)

2) При формировании списка вначале пробовать в трай-кэтче вызывать сервис getDocuments, с подставдлением туда глобальной переменной nID_Subject
(ну а уже если будет ошибка - отрисовывать захардкоденный объект, если вернется нормальный массив объектов - отрисовывать его)

3) если глобальная переменная nID_Subject не инициализирована, то вначале в трайкэтче вызывать метод syncSubject(для ее инициализации), из задачи https://github.com/e-government-ua/i/issues/193 (договориться с исполнителем, если он уже реализовал вызов, чтоб вызов не дублировался)
Если будет ошибка - записать значение глобальной nID_Subject = 1

4) nID_Document сохранять в скрытом инпуте каждого див-а строки документа, с таким-же названием. (нужно для задачи https://github.com/e-government-ua/i/issues/196 )

П.П.С: Все реализовывается в соответствии с концептом:
https://docs.google.com/document/d/1I8Avs4k-WH14X5rgOh1C4bvPboUmTPC_LNvlabUabcs/edit

**Comment by glebzhebrakov** [comment]
Могу взять этот таск, единственное что, возможно, буду долго делать пока во всем разберусь.

**Comment by bvv4ik** [comment]
уже хорошо,
а "долго" - приблизительно какой временной ориентир?

**Comment by glebzhebrakov** [comment]
я бы взял 4-5 дней потому что пока не особо представляю в каком месте менять и еще нужно посмотреть структуры данных.

**Comment by bvv4ik** [comment]
ок, договорились, спасибо! Ассигну!
если что - любые вопросы ко мне, или Инне Дащенко (она сервис по отдаче списка документов делает). Всегда поможем!

**Comment by Kiaba** [comment]
Попрошу согласовать с john_silver эту задачу в связи с тем что он так же хотел работать со списком документов.

**Comment by glebzhebrakov** [comment]
Всем спасибо, свяжусь с john_silver как только разберусь примерно что куда добавлять.

**Comment by glebzhebrakov** [comment]
центральный портал это wf-central, правильно ?

**Comment by Kiaba** [comment]
Ты будешь над back-end`om работать или front-end`om ?
back-end: ./wf-center/
front-end: ./central-js/

**Comment by bvv4ik** [comment]
над front-end: ./central-js/

**Comment by glebzhebrakov** [comment]
На данный момент готово вот такое:  https://github.com/e-government-ua/i/compare/test...glebzhebrakov:issue-192?expand=1  ,
мне не совсем понятно где брать поля : 
1) Дата завантаження копії
2) Ким завантажена копія  
 поэтому я их добавил в моковые данные в таком вот виде : 
//undescribed in task fields, but exists in the mock layout
sDDate : "27 травня 2001",
sDOwner : "Ощадбанк"

**Comment by bvv4ik** [comment]
"поэтому я их добавил в моковые данные"
абсолютно верно,
только вместо:

"sDDate : "27 травня 2001",
sDOwner : "Ощадбанк""

Но, лучше
sDate_Upload : "2015-03-23 11:12:35.000",
sID_Subject_Upload : "OshadBank"

**Comment by bvv4ik** [comment]
кстати, ожидать подтверждения ревьювера для своего пулреквеста не нужно!
достаточно проверить у себя локально и проливать в общую тестовую среду...
Главное - убедиться(дождавшись деплоя 3 мин), что все задеплоилось без ошибок и ничего не поламалось(позаходить на сайт, поклацать)

**Comment by glebzhebrakov** [comment]
да да, я помню :)

**Comment by bvv4ik** [comment]
Глеб, Вы запушили комит в другой репозиторий(
а нам он очень нужен в общем, т.к. без него не можем собрать все до кучи и оживить...

**Comment by glebzhebrakov** [comment]
Готово, я хотел еще вынести те моковые данные, которые я добавил в отдельный сервис, еще изучаю проект в плане где это добавляется.

**Comment by bvv4ik** [comment]
Нам просто сегодня нужно уже "соеденить воедино" реализации всех задач. и без этой задачи не можем сложить все( 
т.е. если там уже мелочи не принципиальные - нужно заливать! будем "походу на месте" допиливать...

**Comment by bvv4ik** [comment]
Немножко иконка справа "наехала" на другую) но в целом - готово!
