### ISSUE TITLE
Для главного портала, реализовать макет диалога, п.п.1.3.2. по подтверждению получения доступа к документу (на который открыл доступ гражданин, и передал ссылку)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#195]
Взять за основу скрин(сам диалог с другим наполнением, но вид подобный):
https://docs.google.com/presentation/d/16gAPjjfybbiYkEUjYAwVjqSs59qkM1RdTecWop1VjqQ/edit#slide=id.gad3e53e9b_0_136

В соответствии с концептом:
https://docs.google.com/document/d/1I8Avs4k-WH14X5rgOh1C4bvPboUmTPC_LNvlabUabcs/edit
по п.п. 3.2. реализовать диалог, при переходе по ссылке на главный портал(ссылку передал гражданин, который открыл данному лицу доступ), в котором человек сможет нажать кнопку ("Отправить СМС для подтверждения доступа к документу") и ниже ввести пришедший в СМС код, чтоб потом нажав кнопку "Открыть документ" - открыть документ, ссылку на который ему прислал гражданин.

Диалог должен стать див-ом, расположенным над основным видом сайта, и вписываться по стилю.

Поля должны быть такие, что описаны в данном сценарии:
1) вызов сервиса getDocumentLink(nID_Access,sSecret) - ответ:
Объект:
{
"nID":423423 //ИД доступа
,"nID_Document":34234 //ИД документа
,"sDateCreate":"2015-04-22 23:56:44.002" // дата-время предоставления доступа
,"nMS":34355 //На сколько милисекунд предоставляется доступ
,"sFIO":"Вася Пупкин" //Кому предоставляется доступ
,"sTarget":"" //С какой целью предоставляется доступ
,"sTelephone":"" //На какой телефон отправлять СМС
,"sMail":"" //Электнока того, кому доступ
,"sSecret":"" //Сикрет (копия)
}
(200-тый код, если все ок иначе {"sError":"текст ошибки"}, который нужно вывести в диалог)
По объекту заполняются поля:
- Номер телефона (не редактируется)
- ФИО  (не редактируется)
- Цель (не редактируется)
- Кнопка "Отправить СМС для подтверждения доступа к документу"

2) При нажатии кнопки "Отправить СМС для подтверждения доступа к документу"
- вызов сервиса getDocumentAccess(nID_Access,sSecret) - ответ 200-тый код, если все ок иначе {"sError":"текст ошибки"}, который нужно вывести в диалог.
- отображаем(ниже) "поле для ввода номера, который придет в СМС"

3) После ввода кода в поле отображаем:
- кнопка "Открыть документ"

4) После нажатия кнопки
- вызов сервиса setDocumentAccess(nID_Access,sSecret,sAnswer)
если ответ 200-тый код(все ок), то из полученного объекта {"sURL":"https://....."} - переходим по УРЛ-у,
иначе {"sError":"текст ошибки"}, который нужно вывести в диалог.

![image](https://cloud.githubusercontent.com/assets/4208821/7858745/63dc8614-0543-11e5-9023-56f90254893d.png)

**Comment by bvv4ik** [comment]
@vilinskyy делает дизайн
@dr1v3 делает макет по дизайну (или и то и другое)

**Comment by dr1v3** [comment]
https://github.com/e-government-ua/i/blob/test/portal-php/public_html/mockup/access.html

**Comment by bvv4ik** [comment]
Вот коммит с реализованным макетом:
https://github.com/e-government-ua/i/commit/dd205b2

его нужно только оживить теперь!
