### ISSUE TITLE
На главном портале, при отрисовки формы для заполнения ее гражданином, отображать пояснительный текст(детальное описание) для каждого поля (который хранится там-же, где и название поля)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#208]
Описание "выводить мелким серым шрифтом под соответствующим полем"

Описание дописывается через знак ";" в самом названии поля, а на клиенте подпись к полю должно браться до этого знака, а описание - после.
Например,
было:
"Номер документа"
стало:
"Номер документа;Этот номер документа Вы должны узнать в секретариате."

если знака ";" не будет, или справа от него пусто, то детальное описание не выводим!

**Comment by kurbpa** [comment]
Пояснительные тексты можно делать, если реализовать ( как я просил  уже давно ) тип данных - label.

**Comment by bvv4ik** [comment]
Нашли решение!!!

Будем дописывать через знак ";" это описание в самом названии поля, а на клиенте подпись к полю будет браться до этого знака, а детальное описание - после.
Например,
было:
"Номер документа"
стало:
"Номер документа;Этот номер документа Вы должны узнать в секретариате."

**Comment by bvv4ik** [comment]
решено
