### ISSUE TITLE
Activiti - customn-ый rest controller (Точка запуска процессов для порталов)

### ISSUE THREAD

**Issue by PavelKorchagin** [e-government-ua/i#21]
org.activiti.rest.controller.ActivitiRestApiController

Методы
1. Вернуть список всех процессов latestVersion
2. Вернуть список полей формы для запуска процесса 
3. Стартовать процесс с полями с соответствующими полями

**Comment by bvv4ik** [comment]
уже конфликтный мапинг с редиректом на /WEB-INF/jsp/*...*.jsp - устранен!
остается поправить в NodeJS обращение на это ткастомный контроллер

**Comment by bvv4ik** [comment]
причем стоит както избавиться от явно лишнего звена в NodeJS, когда лишняя прослойка в виде путей /api/ - требует постоянно править в нем, без какого-либо профита от этого... тут через JSONP стоит запросы делать прямо на сервак-бэк (конечно через предобработчик на js фронта, но без доп справочника путей к сервисам)

**Comment by bvv4ik** [comment]
сейчас ходим на:
https://52.17.126.64:8080/wf-dniprorada/service/repository/process-definitions
а нужно чтоб стал доступен кастомный, например:
https://52.17.126.64:8080/wf-dniprorada/rest/process-definitions

там как-то нужно перемапить и в конфигах + диспетчере чето "наколдовать")

**Comment by bvv4ik** [comment]
Кто первый сделает - сразу медаль героя!)

**Comment by admiral-diver** [comment]
Я как-то спрашивал, могу ли я внести изменения в кастомный контроллер. Было сказано, что да. Посмотрите ветку future-issue-20. Я туда еще не сливал BankID но там переделан контроллер. Если такая реализация process-definition подойдет, то я солью ее в test.

http://localhost:8080/wf-dniprorada/service/rest/process-definitions

**Comment by admiral-diver** [comment]
Ссылка на доументацию в ветке test: https://github.com/e-government-ua/i/blob/test/docs/specification.md
