### ISSUE TITLE
Подцепить сертификаты чтоб браузеры не выдавали ошибку!

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#212]
1) на главный портал https://e-gov.org.ua
2) на тестовый портал https://test.e-gov.org.ua
3) на тестовый портал https://test.e-gov.org.ua/admin
4) на тестовый портал https://dniprorada.e-gov.org.ua
5) на тестовый портал https://demo.e-gov.org.ua
6) на тестовый портал https://demo.e-gov.org.ua/admin

**Comment by budnik** [comment]
У вас есть wildcard сертификат? Они стоят от $59 на два года, но тут можно попросить бесплатно:
https://www.globalsign.com/en/ssl/ssl-open-source/

**Comment by ValerijMakarenko** [comment]
1) на главный портал https://e-gov.org.ua - готово
2) на тестовый портал https://test.e-gov.org.ua - готово
3) на тестовый портал https://test.e-gov.org.ua/admin - готово
4) на тестовый портал https://dniprorada.e-gov.org.ua - готово
5) на тестовый портал https://demo.e-gov.org.ua - готово
6) на тестовый портал https://demo.e-gov.org.ua/admin - в процессе

**Comment by ValerijMakarenko** [comment]
готово
