### ISSUE TITLE
На главном портале, сделать автокомплит в списке населенных пунктов, чтобы легче было осуществлять поиск

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#215]
При этом на бэке NodeJS кешировать всю структуру регионов-городов на сутки.
А с клиента NodeJS подгружать только ограниченный список городов, соответствующий уже выбранному городу и минимум двум введенным символам в поле автокомплита.

**Comment by uazure** [comment]
@bvv4ik Главный портал - это central-js? Что значит автокомплит в списке? Где этот список? По какому урлу можно это увидеть?

**Comment by bvv4ik** [comment]
"Главный портал - это central-js"
да

"Что значит автокомплит в списке?"
это как комбо-бокс, с выпадающим списком, только современный вариант как в поисковике гугл. т.е. начинаеш вводить в поле буквы, и внизу сразу начинает отображаться 10-15 строк, которые подпадают под данную комбинацию букв... как увидел в списке нужный пункт - можно клацнуть на нет и он выберется. Введи в гугле autocomplete, и в первой-же строчке будет ссылка на пример (правда, скорей всего на jQuery, но уверен что и для AngularJS такое есть, тем более, слышал там jQuery Light вроде как поддерживается..)

"Где этот список?"
этот список сейчас уже на центральном портале подтягивается после выбора услуги. 
в конечном итоге на бэке NodeJS(/back) вызывается сервис бэка явы getPlaces,
который и подтягивает всю структуру.

Нужно лишь начать кэшировать на НодеЖС эту структуру а фронту НодеЖС, для этого компонента авто-комплита, выдавать только ограниченный список Топ10, подпадающий под критерии уже выбранного Региона и нескольких букв, введенных в поле автокомплита.

А на фронте НодеЖС заменить комбобокс населенного пункта на этот компонент авто-комплита.
По идее - не сложно, но учитывая новизну проекта, может быть не так легко поначалу...
По этому все вопросы сразу , без стеснения, можно ко мне... или в скайп


" По какому урлу можно это увидеть?"
с бэка Явы вся структура городов и регионов тянется с:
https://e-gov.org.ua/wf-central/service/services/getPlaces
но сам он уже дергается с бэка НодеЖС, просто поищи в проекте central-js слово "getPlaces"
и найдеш этот вызов... тебе нужно только начать его использовать через через "обертку", которая позволит отдавать на фронт НодеЖС, через внутренний сервис "из него только сам список населенных пунктов, на основании тех двух критериев, что я написал выше(регион и буквы, входящие в название)"

**Comment by uazure** [comment]
с двумя символами ввода в автокомплите - возникает ощущение что что-то поломалось, когда вводишь первую букву города и ничего не происходит. Поэтому поставил таки 1 символ.

**Comment by bvv4ik** [comment]
Один символ тоже будет норм! Я сгораю от нетерпения попробовать)

**Comment by bvv4ik** [comment]
Готово!
