### ISSUE TITLE
На главном портале: если услуги для заданной услуги и региона нет - вместо текста “Ознайомитись, як можна скористатися цією послугою, можна в Інструкції” выводим:

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#218]
выводим:
Ви можете допомогти пришвидчити процес переведння послуги в електронний вигляд:

1) Поділіться посиланням на цю сторінку в соціальних мережах із закликом підтримати ініціативу по переводу послуги в електронний вигляд.
Чим більше буде таких закликів, тим скоріше це буде реалізовано!
[иконки Фб и Вк, как тут(https://www.google.com/url?q=https%3A%2F%2Fblago.privatbank.ua%2Fdubilet&sa=D&sntz=1&usg=AFQjCNE1S_0QDsfw3tB1g3k63MUyEEvS1w) внизу
изображение (будет позже)
заголовок: Закликаю владу перевести цю послугу в електронну форму!
Текст: %Населенный пункт% – %Название услуги%

вот сервис фб https://developers.facebook.com/docs/sharing/reference/feed-dialog/v2.3
вот твиттер: https://dev.twitter.com/web/tweet-button
(альтернативный сервис: http://share.pluso.ru/)

2) Залиште свій email. Ми Вас поінформуємо, як тільки ця послуга буде доступна в електронному вигляді.
[Ваш email...] [Зберегти]

**Comment by glebzhebrakov** [comment]
Куда сохранять по событию сабмита эмейла? или какой сервис дергать ?

**Comment by bvv4ik** [comment]
сервис этот:
    @RequestMapping(value = "/setMessage", method = RequestMethod.POST)
    public
    @ResponseBody
    HttpStatus setMessage(@RequestParam(value = "sHead") String sHead,
                          @RequestParam(value = "sBody") String sBody,
                          @RequestParam(value = "nID_Subject", required = false) Integer nID_Subject,
                          @RequestParam(value = "sMail", required = false) String sMail,
                          @RequestParam(value = "sContacts", required = false) String sContacts,
                          @RequestParam(value = "sData", required = false) String sData) {

**Comment by bvv4ik** [comment]
Но в первую очередь нужно реализовать именно п.1.
и общее до-оформление absant.html, в котором все это и будет до-реализовано...

**Comment by bvv4ik** [comment]
Готово, спасибо!
