### ISSUE TITLE
Создать на wf-central сервис сохранения сообщений от граждан

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#226]
setMessage (String sHead(обязательно), String sBody(обязательно), Long nID_Subject, String sMail, String sContacts, String sData) - возврат 200-тый код если все ок
getMessages () - возврат массива oMessage
getMessage (Long nID) - возврат oMessage

oMessage:
{nID:1
"sHead":""
, "sBody":""
, "sDate":"2015-11-22 23:24:53.093" //всегда возвращать в этом формате
, "nID_Subject":34
, "sMail":""
, "sContacts":""
, "sData":""
}

Таблица
SubjectMessages
nID - ид-шник уникальный, автоинкрементируемый (сам создается)
sHead - до 200 символов текста
sBody - текстовое поле
sDate - поле с датой и временем (автоматом должна ставиться текущая)
nID_Subject - число-ИД субьекта //опционально, по умолчанию 0
sMail - до 100 символов //опционально
sContacts - до 200 символов //опционально
sData - до 200 символов текста //опционально

П.С.: Нужно найти в коде "getServicesTree" (такой сервис написан), и сделать по образу и подобию (там сервисы + DAO + Hibernate)

Вот полноценный объект (по getMessage):
{nID:1
"sHead":""
, "sBody":""
, "sDate":"2015-11-22 23:24:53.093" //всегда возвращать в этом формате
, "nID_Subject":34
, "sMail":""
, "sContacts":""
, "sData":""
}

А вот массив (по getMessages):
[{nID:1
"sHead":""
, "sBody":""
, "sDate":"2015-11-22 23:24:53.093" //всегда возвращать в этом формате
, "nID_Subject":34
, "sMail":""
, "sContacts":""
, "sData":""
}
,{nID:2
"sHead":""
, "sBody":""
, "sDate":"2015-11-23 23:24:53.093" //всегда возвращать в этом формате
, "nID_Subject":34
, "sMail":""
, "sContacts":""
, "sData":""
}]

**Comment by bvv4ik** [comment]
Задачу взял @asafronienkov

**Comment by brunneng** [comment]
Похоже не тестилось на постгресе. Сейчас вижу очевидный косяк что таблица названа "Subjectmessage"
А сущность:
@javax.persistence.Entity
public class SubjectMessage implements Serializable {
Поскольку аннотация Table не указана то хибернейт будет предполагать что таблица называется "SubjectMessage". В постгресе важен регистр символов.

**Comment by bvv4ik** [comment]
угу, поправлю... еще руки не дошли до полноценного тестирования...
думал, вначале, все-же написать фронтовую часть под это дело, что позволило-бы нормально протестить...

**Comment by asafronienkov** [comment]
Спасибо, поправил!
