### ISSUE TITLE
Добавление в виртуальную среду разработки - central-js и dashboard-js

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#228]
в продолжение темы:
https://github.com/e-government-ua/i/issues/130#issuecomment-102664915

Прошу кроме 
1) central-js
также добавить и:
2) dashboard-js
(там практически одно и то-же)

1) Сборка  cd central-js:
 cd central-js
 npm install
 cd client
 bower install
 npm install
 npm install grunt-contrib-imagemin
 grunt debug

2) Сборка dashboard-js:
 cd dashboard-js
 npm install
 bower install
 npm install grunt-contrib-imagemin
 grunt build
 cd dist
 npm install

**Comment by bvv4ik** [comment]
Прошу кроме 
1) central-js
также добавить и:
2) dashboard-js
(там практически одно и то-же)

1) Сборка cd central-js:
cd central-js
npm install
cd client
bower install
npm install
npm install grunt-contrib-imagemin
grunt debug

2) Сборка dashboard-js:
cd dashboard-js
npm install
bower install
npm install grunt-contrib-imagemin
grunt build
cd dist
npm install

**Comment by alegast** [comment]
central-js піднімається   

з особливостей: 
 1 коли на windows  тестував  зіткнувся з проблемою описаною в https://github.com/e-government-ua/i/wiki/FrontEnd,-%D0%BF%D0%BE%D1%80%D1%82%D0%B0%D0%BB-%D0%B4%D0%BB%D1%8F-%D0%B3%D1%80%D0%B0%D0%B6%D0%B4%D0%B0%D0%BD-%28central-js%29    
можна побороти  git config --global core.autocrlf input    цю опцію краще в мануал по налаштуванню git відразу додати, до самого vagrant  ця проблема посуті не відноситься

2 npm install grunt-contrib-imagemin  криво встановлюється, але портал піднімається нормально, якщо хтось знає як побороти буду вдячний. 

3 правильно вимикати вагрант через vagrant halt , при наступному vagrant up  запустяться скрипти автооновлення порталу і бекенду і перезавантажаться налаштування мережі, vagrant suspend посуті робить паузу і є ньюанс з nodejs який вірішуеться - port forwading  8443 поза NAT але не зовсім коректно виходить з паузи. 

у кого уже розгорнута віртуальна машина можна обновитися через vagrant reload --provision,  ну або vagrant destroy, vagrant up   
 (на linux / mac спитає пароль для редагування локального hosts файлу - додаеться e-gov-ua.dev => 192.168.10.10). 

Далі буду з dashboard-js  розбиратись

**Comment by trntv** [comment]
А почему не вынести npm install и bower install в provision скрипт?

**Comment by bvv4ik** [comment]
2. а какие признаки "кривизны устанавливаемости"?

В целом - супер!)

dashboard-js - по дольше собирается(раз в 20)... нужно быть к этому готовым, психологически)

**Comment by alegast** [comment]
> А почему не вынести npm install и bower install в provision скрипт? 
provision запускається при ініціалізації або при змінах в конфігурації системи вручну,  а npm install и bower install в up_central_js.sh  при кожнуму старті системи, оновлюють залежності в package.json bower.json (якщо будуть).  наскільки я розумію більш феншуйний шлях для npm встановлювати залежності без рутових прав. 
Я більше з linux / vagrant знайомий, nodejs не зовсім моя спеціалізація всім порадам буду радий )  

> а какие признаки "кривизны устанавливаемости"?  
були варнінги на меншу ніж потрібно версію grunt хоча вона остання з можливих в їх ubuntu  PPA / NPM , були помилки directory access denied  хоча встановлюється з рутовими правами.

**Comment by alegast** [comment]
done

в grunt buld (тільки в windows) задача 
concurent:dist   
викликає  error   cannot find module log-symbols   з --force  працює 

dashboard-js білдиться дійсно довго, може в майбутньому хтось оптимізує задачі ініціалізації щоб лишнього не чистило а лише обновляло існуючі компоненти

**Comment by bvv4ik** [comment]
Прекрасно!
А можно плиз дополнить нашу текущую доку по Вагранту дополнениями по этой части?
Вот ссылка на статью нашей вики:
https://github.com/e-government-ua/i/wiki/Project,-%D0%B2%D0%B8%D1%80%D1%82%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D1%81%D1%80%D0%B5%D0%B4%D0%B0

Спасибо, это действительно очень ценная работа! Нам нужно до минимума снизить "порог вхождения в проект", и это еще один важный кирпичик в выстраивании этой системы!

**Comment by alegast** [comment]
апдейтнув доку. 

завжди радий допомогти. тепер треба намагатись тримати вагрант в актуальному стані, при доволі частих змінах в проекті

**Comment by bvv4ik** [comment]
готово (только адаптация под винду - таки нужна)
