### ISSUE TITLE
На главном портале, при авторизации граждан с определенными ИНН включать "дополнительные админ-возможности"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#237]
1) При включении добавлять параметр sID_Subject_Admin в куки, c хранением там ИНН админа!
2) Включенность считать, если есть и заполненный "параметр sID_Subject_Admi" и значение ИНН в обьекте с параметрами авторизованного гражданина совпадает с ним.
3) Сделать эту проверку через общедоступную функцию bAdmin(возвращающую true/false), 
4) Перерисовывать контент, если находимся в этот момент на закладке каталога услуг или отдельной услуге.

"дополнительные админ-возможности" = функция bAdmin() возвращает true.

Админ режим включать для ИНН:
-d.dubilet
-bvv4ik
-kiaba
-kurbpa
-anton.sych
(узнать у них их ИНН)

**Comment by VadimGulich** [comment]
Доп. админ возможности включаются
