### ISSUE TITLE
На главном портале, при вкюченных "дополнительных админ-возможностях", отрабатывать дополнительные кнопки управления основным деревом каталога - для услуг

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#239]
После реализации задачи: https://github.com/e-government-ua/i/issues/238
(оживив кнопки)

1) Кнопка "изменить услуги" (и диалог изменения названия)
2) Кнопка "добавить услугу" в подкатегории (и диалог добавления)
3) Кнопка "удалить услугу" в подкатегории (с диалогом подтверждения, который не даст удалить если есть подключенные города/области, отобразив число подключений)

Сервис "setServicesTree" и "removeService"

**Comment by valdemar8080** [comment]
1) Диалоги должны быть в модальных окна или нет ? (с модальными возни больше)
2) "setServicesTree" и "removeService" - Этих сервисов еще нет. Их написание будет в отдельной задаче ?

**Comment by valdemar8080** [comment]
Как вариант, на главной странице, где приведен большой перечень услуг и там тесно, можно сделать диалог с помощью модальных окон. А в профиле услуги, где места полно, можно диалог в jumbotron поместить.

**Comment by tseshevsky** [comment]
Сделал и замержил в тест

**Comment by nazarenkod** [comment]
Протестировано.Кнопки "изменить услуги","добавить услугу","удалить услугу" активные и рабочие

**Comment by nazarenkod** [comment]
Протестировано
