### ISSUE TITLE
На главном портале, при вкюченных "дополнительных админ-возможностях", отрабатывать дополнительные кнопки управления основным деревом каталога - для подкатегорий

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#240]
После реализации задачи: https://github.com/e-government-ua/i/issues/238
(оживив кнопки)

4) Кнопка "изменить подкатегорию" (и диалог изменения названия)
5) Кнопка "добавить подкатегорию" (и диалог добавления)
6) Кнопка "удалить подкатегорию" (с диалогом подтверждения, который не даст удалить если есть подключенные услуги, отобразив число подключений)

Сервис "setServicesTree" и "removeSubcategory"

**Comment by tseshevsky** [comment]
Сделал и замержил в тест

**Comment by tseshevsky** [comment]
Реализованы разные уровни подтверждения удаления для подкатегории с 0, 1-10 и больше 10 сервисами внутри.

**Comment by nazarenkod** [comment]
Работает для подкатегории
