### ISSUE TITLE
На главном портале, при вкюченных "дополнительных админ-возможностях", отрабатывать дополнительные кнопки управления основным деревом каталога - для категорий

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#241]
Ввиду низкой вероятности какого-либо редактирования категорий, было ПРИНЯТО РЕШЕНИЕ: ПОКА ФУНКЦИОНАЛ СКРЫТЬ

После реализации задачи: https://github.com/e-government-ua/i/issues/238
(оживив кнопки)

7) Кнопка "изменить категорию" (и диалог изменения названия)
8) Кнопка "добавить категорию" (и диалог добавления)
9) Кнопка "удалить категорию" (с диалогом подтверждения, который не даст удалить если есть подключенные подкатегории, отобразив число подключений)

Сервис "setServicesTree" и "removeCategory"

**Comment by tseshevsky** [comment]
Скрыл кнопки добавления, редактирования и удаления категории. Логика и модальные окна для всего этого реализованы. Точно работает редактирование. Добавление точно не работает - API выдает ошибку. Удаление не проверял.

**Comment by nazarenkod** [comment]
@tseshevsky подскажите как можно проверить, если кнопки скрыты?

**Comment by tseshevsky** [comment]
Не нужно проверять работу, проверьте только, что кнопки скрыты.
