### ISSUE TITLE
На главном портале, при вкюченных "дополнительных админ-возможностях", отрисовывать дополнительно кнопки управления - услугой в разных областях и населенных пунктах + описанием и сопровождением услуги (войдя в услугу и переключаясь между таб-ами)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#242]
После реализации задачи:
#237
(или сэмулировав включение этого режима в общедоступной функции bAdmin, как в той задаче)

Добавить рядом с каждой из закладок услуги(описанием и сопровождением), кроме обсуждения(где hypercomments) и первой закладки:
1) Кнопка "изменить содержание"
(также заготовки скрытых кнопок "Сохранить" и "Отмена", для задания: https://github.com/e-government-ua/i/issues/244)

Дорисовывать элементы (ниже строки с комбобоксом и автокомплитом):
2) Кнопка "изменить" (после выбора области или в т.ч. области, где услуга есть)
3) Кнопка "добавить" (после выбора области или в т.ч. области, где услуги нет)
4) Кнопка "удалить" (после выбора области или в т.ч. области, где услуга есть)

**Comment by OlgaTurenko** [comment]
@valdemar8080 добрый вечер! Скажите, пожалуйста, как у нас пробвигаются дела по данной задачке? :)

**Comment by tseshevsky** [comment]
Это не тот таск. Это я закончил 243, а не 242. Но перепутал и ветку назвал №242. Этот таск давно сделан.
