### ISSUE TITLE
На главном портале, при вкюченных "дополнительных админ-возможностях", отрабатывать дополнительные кнопки управления - услугой в разных областях и населенных пунктах (войдя в услугу)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#243]
После реализации задачи: https://github.com/e-government-ua/i/issues/242
(оживив кнопки)

1) Кнопка "изменить" (диалог изменения URL-а, тип-а услуги и oData обьекта с параметрами)
2) Кнопка "добавить" (диалог добавления URL-а и тип-а услуги и oData обьекта с параметрами)
3) Кнопка "удалить" (диалог подтверждения удаления)

Сервис "setServicesTree" и "removeServiceData"

**Comment by tseshevsky** [comment]
В целом сделал. Есть проблема с добавлением первого места в новосозданную услугу. Но на существующих услугах добавление и удаление места работает нормально.

**Comment by OlgaTurenko** [comment]
отлично. спасибо!!!

**Comment by bvv4ik** [comment]
добавление первой услуги все-же важно сделать рабочим..

**Comment by tseshevsky** [comment]
Вроде получилось. Вмержил в тест. Можно тестировать в полном объеме.

**Comment by Koffeek** [comment]
Возможно стоит добавить полное описание кейса, чтобы верно всё ввести, но пока по итогам теста могу написать следующее:

1. Добавить новую услугу получилось, правда в файле Service.csv найти её не могу. 
2. Добавить город в существующую получилось, но т.к. процесс в serviceData.csv не прописан, то не подтягивает ничего при входе. 
3. При попытке добавить первый город в новую услугу выбивает ошибку. 
4. При выборе одного типа аутентификации, вместо двух отрабатывает корректно. 
5. Кнопка "редагувати послугу в цьому місті" работает
6. Кнопка "видалити послугу в цьому місті" работает.

ИМХО если задача только по фронту, то всё работает корректно. Спасибо.

**Comment by bvv4ik** [comment]
1. в Service.csv его и не будет, т.к. пишется вс в базу уже с интерфейса напрямую
2. @tseshevsky прошу глянуть
3. Какую ошибку? @tseshevsky прошу глянуть

задача связывает фронт и бэковые сервисы... но нужно разобраться с п.2 и п.3

**Comment by Koffeek** [comment]
@bvv4ik 
1. Номер новой услуги на портале (в ссылке после заведения 42437) отличается от того, который я задавал при заведении (1600). Если я не могу это проверить и он не пишется в Service.csv, то как мне корректно подвязать процесс в serviceData.csv к данной услуге.
2. Возможно потому, что я не понимаю в каком поле и каким образом я должен определить процесс, который подвязывается под конкретный город.
3. Ошибка "city or region is not defined", но это возможно потому, что я не понимаю в каком поле и каким образом я должен это определять.

**Comment by bvv4ik** [comment]
"1. Номер новой услуги на портале (в ссылке после заведения 42437) отличается от того, который я задавал при заведении (1600). Если я не могу это проверить и он не пишется в Service.csv, то как мне корректно подвязать процесс в serviceData.csv к данной услуге."

этот интерфейс обеспечивает полностью и создание услуг и записей ServiceData
т.е. предполагается, что с помощью него, получится полностью отказаться от правок файлов Іукмшсуюсім ? ІукмшсуВфефюсім

**Comment by tseshevsky** [comment]
Пофиксил баги связанные с возможностью добавления услуги в стране, области, городе. 
Теперь возможно добавить услугу в рамках страны.
Теперь не должно быть возможно добавить услугу в рамках страны, если есть услуга в любом городе или области. И не должно быть возможно добавить услугу в рамках области, если есть услуга в любом городе ЭТОЙ области. То есть в одной области может быть одна на всю область, а в другом - отдельно в каждом городе.

**Comment by VadimGulich** [comment]
исправлено , закрываем
