### ISSUE TITLE
На главном портале, при включенных "дополнительных админ-возможностях", отрабатывать дополнительные кнопки управления - описанием и сопровождением услуги (войдя в услугу, переключаясь между таб-ами)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#244]
После реализации задачи: https://github.com/e-government-ua/i/issues/242
(оживив кнопки)

1) Кнопка "изменить содержание" и после ее нажатие переход в режим редактирования содержимого в HTML-редакторе, и возможностью сохранить изменения кнопкой "Сохранить" или отменить, кнопкой "Отмена"

Сервис "setService"

@Kiaba
Бібліотека для вирішення задачі: http://textangular.com/

**Comment by Kiaba** [comment]
Бібліотека для вирішення задачі: http://textangular.com/

**Comment by tseshevsky** [comment]
Сделал.
