### ISSUE TITLE
Реализовать подписывание цифровой подписью загружаемый документ в "Мои документы"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#250]
Реализовать на базе уже готового и реализованного на портале решения:
https://github.com/e-government-ua/i/issues/843

1) Только в интерфейсе(там где можно сейчас аплоадить файлы  в Мои Документы) - добавить чекбокс "наложить ЭЦП", при включении которого и будет проходить механизм наложения ЭЦП на файл, и уже итоговый файл аплоадить в мои документы.

2) так-же слать в сервис не ХТМЛ а тот файл, что гражданин аплоадит..

**Comment by muromec** [comment]
Please take a look at opensource implementation of DSTU-4145 and respective block cipher and hash functions in javascript.

You can find sources on the following page: https://github.com/dstucrypt/

**Comment by yurikoles** [comment]
[dstucrypt/jkurwa](https://github.com/dstucrypt/jkurwa)
>jkurwa
Oh, you...

**Comment by bvv4ik** [comment]
Задача актуализирована

**Comment by OlgaTurenko** [comment]
@Kiaba  Подскажите, пожалуйста, на каком мы этапе по задачке?

**Comment by bvv4ik** [comment]
пока не реализуем... думаем как заюзать Папка24
