### ISSUE TITLE
НЕОТЛОЖНО поправить авторизацию по БанкИД для тестового портала https://test.e-gov.org.ua

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#257]
подошла очередь к изменению по этапу №2   :)

Мы вынуждены сделать небольшие правки протокола по получению токена, а именно client_secret обвернули
в SH1{client_id +client_secret+code}, где "+  конкатенация строк". Таким образом хотим избежать передачи секьюрности в открытом виде.

Тоже самое касается и refresh_token

На текущий момент в теч. 2-ух недель будет работать как по старому, так и по новому (полигон, боевой).
Рекомендуем провести доработки сог. присланного АПИ, см. стр 5.

Прошу прощения за такие неудобства.
[9:26:33] Сергей Жук: ссылка на док

https://github.com/e-government-ua/portal-php/wiki/%D0%90%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8-%D0%BF%D0%BE-bankid
[9:27:33] Сергей Жук: и еще ссылка на док

https://github.com/e-government-ua/i/wiki/Project,-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%BF%D0%BE-BankID

**Comment by loveitgroup** [comment]
сделал
