### ISSUE TITLE
Заполнять поля с данными клиента из данных авторизации

### ISSUE THREAD

**Issue by AleksejDomash** [e-government-ua/i#26]
Также эти поля должны быть недоступны для редактирования, исправить парсинг xml с информацией о пользователе

**Comment by AleksejDomash** [comment]
сейчас возвращаются сервисом авторизации и заполняются на форме только данные по fio

**Comment by bvv4ik** [comment]
займемся этим уже в рамках дашборда, когда реализуем функционал его основного предназначения... тогда уже и для граждан функционал смогли-бы перетянуть с PHP... а пока PHP-сты этим занимаются

**Comment by bvv4ik** [comment]
уже реализовано в PHP и на центральном портале в NodeJS
не актуально
