### ISSUE TITLE
На java-бэке главного портала добавить сервисы загрузки/выгрузки дерева каталога услуг целиком

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#261]
По аналогии с setService и setServicesTree
Добавить сервисы:
"setServicesTreeAll" - загрузка в систему всего дерева и мест (из обьекта JSON, перезаписав все)
"getServicesTreeAll" - выгрузки из системы всего дерева и мест (в файл JSON)

И, основанные на них два производных сервиса(которые сделаны по подобию upload_file_to_db и download_file_from_db). Т.е. отдающие верный контент тайп и загружающие стандартный поток в виде мультипартфайла:
"uploadServicesTree" - загрузка в систему всего дерева и мест (из файла igov.ua.catalog_2015-05-06_20-02-23.json, в теле POST, перезаписав все)
"downloadServicesTree" - выгрузки из системы всего дерева и мест (в файл igov.ua.catalog_2015-05-06_20-02-23.json)

Один и тот-же целостный объект JSON, должен быть полностью совместим для загрузки и выгрузки его этими обоими сервисами.

**Comment by brunneng** [comment]
Ок. займусь на выходных.

**Comment by brunneng** [comment]
Можно ли через setServicesTreeAll изменять связки регионов и городов, и насколько это будет удобно?

**Comment by brunneng** [comment]
В том смысле что города и регионы будут повторяться в дереве несколько раз , потому что много сервисов будут на них ссылаться.

**Comment by bvv4ik** [comment]
"Можно ли через setServicesTreeAll изменять связки регионов и городов, и насколько это будет удобно?"

по идее, тут все должно быть в транзакции - вначале все прибиваем "под чистую", потом заливаем полную целостную структуру...

т.е. той сложной логики "апдейта" тут не нужно... это чисто резервное копирование и полное восстановление.

**Comment by brunneng** [comment]
Общая идея понятна. Не понятно как например залить города и регионы если на них еще нет ни одной ссылки из сервисов

**Comment by brunneng** [comment]
И будут ли передаваться id-шники сущностей? чтобы ссылаться по ним. или все будет без айдишников и мы их сами сгереним.

**Comment by bvv4ik** [comment]
И будут ли передаваться id-шники сущностей? чтобы ссылаться по ним. или все будет без айдишников и мы их сами сгереним.

предполагается, что загружать мы будем полный слепок выгруженной базы... соотв. все ИД-шники там уже будут

" как например залить города и регионы если на них еще нет ни одной ссылки из сервисов"
ну так вначале загружать блок из городов и регионов, а следом структуры каталога, со ссылками на них

**Comment by brunneng** [comment]
значит города и регионы будут загружаться отдельно от setServicesTreeAll,  а в getServicesTreeAll только ссылки на них?

**Comment by bvv4ik** [comment]
я именно видел это как общее дерево всего... и городов с регионами вместе....
т..е. три дерева в одном, 
{"aServicesTree":"[.....]","aServices":"[.....]","aPlaces":"[.....]",}

**Comment by brunneng** [comment]
это не может быть деревом всего т.к. могут существовать регионы и города на которых нет ссылок из сервисов, тут явно видно 2 дерева.

**Comment by brunneng** [comment]
интересно еще, как предполагается эти методы использовать на практике?

**Comment by bvv4ik** [comment]
" т.к. могут существовать регионы и города на которых нет ссылок из сервисов"
ну и будут эти города и регионы "не использованные" в этом отдельном третьем дереве... с труктура сервисов к ним привязывается а не наоборот.

вот тут первые три структуры и есть эти структуры:
https://docs.google.com/document/d/1hTkHdG2VK2Ftn8ScSx-ViHDopJ4yFNa7GVhuhCzP8Tg/edit

там элемент избыточности только по:
 aService: [
   					 {
   						 nID: 1,
   						 nOrder: 1,
   						 sName: ”Отримати довідку про несудимість”,
      					 }
   				 ]


все остальное уникально...



в крайнем случае можно просто экспортить все таблицы в виде JSON-дерева..
причем так, чтоб хеадер с названием полей всегда был отдельным подобьектом, а каждое поле(его название) не дублировалось в отдельной строке массива...

Например:
{
"Category":{
"aHead":["nID","sID","sName","nOrder"]
"aBody":[
["1","Citizen","Громадянам";"1"]
["1","Business","Бізнесу","1"]
]},
"SubCategory":{
"aHead":["nID;sName;sID;nID_Category;nOrder"]
"aBody":[
["1","Родина","Family","1","2"]
["2","Транспорт","Transport","1","6"]
]}
... и т.д.
}

**Comment by brunneng** [comment]
можем договорится что будет еще метод типа setPlacesAll который будет вызываться перед setServiceTreeAll и инициализировать чисто регионы и города, а из setServiceTreeAll будут пересоздаваться уже сервиса с ссылками на города (и только ссыылки без возможности модификации данных по регионам и городам) . хотя и тут есть некоторые проблемы.  Например то что при пересоздании регионов и городов уже есть в базе ссылающиеся на них сервисы. И так просто удалить не получится, надо еще удалять и сервисы. Поэтому мне такой подход не очень нравится. Можно сделать иначе, вместо setServiceTreeAll  и setPlacesAll сделать 1 метод setData, в котором будет передаваться 2 дерева:
1) регионы и услуги
2) сервисы ссылающиеся на регионы и услуги.
тогда можно будет все просделать в 1 транзакции. И выглядит это более менее не противоречиво. 
Но можно и так как вы в конце прошлого сообщения предложили.

Поэтому я и хочу выяснить как это предполагается использовать, т.е. место этого функционала в общей схеме всего приложения. Может тогда смогу какой то другой, лучший вариант предложить.

**Comment by bvv4ik** [comment]
"сделать 1 метод setData"
у нас в будущем может понадобиться точно так-же "бэкапить "профили пользователей", со всеми документами(без контента) и правами на них, потому абстрактное "setData"  точно не подойдет...

я потому и предложил "setServiceTreeAll", но если хочется еще большей "понятности в названии", можем назвать его "setServicesAndPlacesTree"...

но вообще, наверно стоит все это бэкапить в денормализованном виде, как я предложил "альтернативным вариантом", в прошлом комменте... тогда мы просто сливаем контент таблиц.

Причем, даже сможем это сделать "партиями", если структура очень большая(точнее записей в ней), то отталкиваться от "корневой структуры", и вычитывая заданный лимит элементов(отталкиваясь от так-же заданного номера) - отдавать вместе и все "подвязанные" к нему. Но, это теоретически, и в далеком будущем... Сейчас все на много проще - просто слить данные всех структур, нужных для формирования полного каталога услуг - в виде единого объекта...

Повторюсь, наверное, для унифицированности и простоты - практичнее было-бы сливать именно потаблично(все таблицы в одном обьекте)
