### ISSUE TITLE
Навести порядок в джобах Jenkins и PHP портале (уже на новом месте)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#262]
Навести порядок в джобах Jenkins и PHP портале (уже на новом месте)
1) чтоб один джоб был portal-alpha - для test.e-gov.org.ua тестовой сервер БанкИД(ветка test)
2) второй джоб был portal-beta - для demo.e-gov.org.ua боевой сервер БанкИД (ветка master)
3) в каждом из джобов чтоб были отдельные опции деплоя Портала, Дашбоарда и Бэка
4) встроить копирование конфигов PHP отдельно при отработке джоба, как это сейчас в dashboard-js сделано
5) скопировать ветку test, в ветку master

**Comment by ValerijMakarenko** [comment]
done
