### ISSUE TITLE
Создать полный клон системы центрального портала, в качестве полигона poligon.e-gov.org.ua

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#263]
https://poligon.e-gov.org.ua
https://poligon.e-gov.org.ua/wf-central

1) машину для этого взять из под "dniprorada1.e-gov.org.ua" (и сделать клон всего с e-gov.org.ua)
2) клонировать джоб:"_central_release" в "_central_alpha"
3) в этом клоне все настроить на этот центральный портал. 
4) добавить описание по этой машине в нашем гугло-экселе
5) и на poligon.e-gov.org и на poligon.e-gov.org конфиги по central-js так-же перенести в /sybase/.configs/*, и в джобах поправить их копирование при деплое
6) ВАЖНО: при отработке джоба "_central_release", перед запуском сборки проекта, копировать содержимое "wf-central\src\main\resources\data\prod\*" в "wf-central\src\main\resources\data" (т.е. на уровень выше), с перезаписью содержимого.

- База для него должна быть тоже тестовая
- Редис тоже тестовый 
- Монго пока общая (как будет готова тестовая - переведем его на эту отдельную тестовую)

**Comment by ValerijMakarenko** [comment]
done
