### ISSUE TITLE
На главном портале - привести профиль услуги в соответствие с макетом, с обязательным отображением название услуги + небольшие правки отображения каталога!

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#269]
1) Отображать название "услуги" (запоминать при заходе в профиль услуги из каталога oService.sName)
2) Отображать название "типа оператора услуги" (запоминать при заходе в профиль услуги из каталога oService.sSubjectOperatorName)
3) В каталоге услуг, надпись “Бізнес” сделать больше интервал над надписью, меньше - под ней (чтобы было видно, что она относится к нижнему блоку ссылок).

Получить для примера все "дерево каталога услуг", с нужными полями можно так:
https://poligon.e-gov.org.ua/wf-central/service/services/getServicesTree
(но в этом особо нет необходимости, т.к. дерево и так подгружается в каталоге)

Макет-образец (вид в шапки профиля услуги, с "названием услуги" и "типом оператора"), можно глянуть тут:
https://docs.google.com/presentation/d/16gAPjjfybbiYkEUjYAwVjqSs59qkM1RdTecWop1VjqQ/edit#slide=id.gad3e53e9b_0_49

Проверить можно на услуге:
"(1) Видача відомостей з документації, що включена до місцевого фонду документації із землеустрою."

**Comment by AndrewLvov** [comment]
sSubjectOperatorName выдаёт значения вида: "Субьект 5". Нужно что-то другое, смотрю.

**Comment by AndrewLvov** [comment]
А, нашёл: service.sName

**Comment by bvv4ik** [comment]
Готово
