### ISSUE TITLE
Вынести общую часть бэка со всех Рад (из репозиториев /*/wf ) в /i/wf-base, и переделать их POM + реализовать POM самого унифицированного /i/wf-base

### ISSUE THREAD

**Issue by PavelKorchagin** [e-government-ua/i#28]
Для каждого госоргана будет свой репозиторий с процессами, нужно отделить сам activiti-explorer в отдельный проект, вынести в настройки лого, etc.

**Comment by AleksejDomash** [comment]
расскажи, пжлст, конкретнее, что ты имеешь в виду про движок. Сейчас в одном проекте rest-api, engine, explorer. Это должно быть три разных модуля, которые могут стратовать независимо ?

**Comment by PavelKorchagin** [comment]
думаю, незачем их отдельно пока выделять, нужно сделать просто пустую (или с dummy процессом) общую исполняемую библиотеку с rest-api и explorer-ом, а уже в репозиториях госорганах будут  просто свои процессы и настройки

**Comment by bvv4ik** [comment]
я тоже не совсем понял... 
имеется в виду "один общий эксплорер", с разными подкладываемыми либами (включающими разные наборы бизнес-процессов и логики)?

может скайпе это обсудим?

**Comment by PavelKorchagin** [comment]
да, всё верно. задача не дублировать код по всем гос.органам (процессы у которых могут отличаться)

**Comment by bvv4ik** [comment]
так сам активити-эксплорер - это-ж просто модуль(на сколько я знаю), который работает с теми пропертями/конфиками/моделями/коннекшинамиБД, которые ему подложат... 
Как мы будем "один на всех Эксплорер" переключать на разный контекст, работая с разными гос-органами? (ведь это чтоб он заработал с другим контекстом - его каждый раз передеплоивать придется под разные контексты)

Куда проще просто в каждом репозитории госоргана оставить по одному(своему) экземпляру Эксплорера.. т.е. это как-бы внутренний инструмент работы с бизнес-моделью и процессами..
А наша фронтовая часть - внешний инструмент работы...

П.С.: Полагаю, со временем выростет на фронте и более удобный вариант дашбордов, выводящих инфу по процессам(подобно эксплореру), с возможностью ими так-же управлять...(разве что модель менять будем как и раньше - в эксплорере)

**Comment by PavelKorchagin** [comment]
идея была, чтобы сделать общий

**Comment by bvv4ik** [comment]
кроме того, мы когда-то тоже думали (в работе) так сделать(один эксплорер на кучу разных проектов), но отказались из-за того, что разные проекты могут со временем даже начать отличаться по версиям, и получится так, что в какой-то момент "едыный эксплорэр" просто с одними проектами будет работать, а с другими уже не сможет(из-за не совместимости по версиям)...

**Comment by bvv4ik** [comment]
эксплорер стоит сохранить свой в каждом проекте... он нам ни чем не мешает...

конечно, стоит как-то унифицировать "его стыковку" с контекстом(та да-же теми лого), чтоб можно было хоть как-то шаблонизировать и автоматизировать его добавление в новые проекты... но так чтоб он был единым окном для всех проектов - не понимаю как это будет работать... ведь одновременно и параллельно есть необходимость работы сразу с разными проектами...

если я чето не так понимаю - давайте в скайпе.. даже если текстом - всеравно быстрее будет

**Comment by bvv4ik** [comment]
ну т.е. чтоб через мэйвен его подтягивать с зависимостями - как минимум понадобится запуливать его разные версии куданить в нексус-репозиторий, например... 
1) тогда следить за этими разными версиями придется (какие еще юзают - какие уже нет)
2) тогда к нашему хозяйству придется репозиторий мэйвеновский добавлять (например Nexus)
3) следить за стандартами расположения контекста для эксплорера

кроме того - может понадобиться какойнить "финт ушами", может даже и временный, для какогото из проектов... т.е. чтоб там чуток модифицированный эксплорер был..

"стоит-ли овчинка выделки2?
я-бы, на данном этапе, пока с этим на замарачивался... 
просто что мы выигрываем в результате?
отсутствие нескольких веток/пэкэджей в каждом проекте?

**Comment by AleksejDomash** [comment]
я бы сделал систему плагинов, было бы легче расширять explorer и его поддерживать. То есть сам explorer остается проектом как он есть, но мы в него встраиваем в определенных местах возможность к расширению.

**Comment by AleksejDomash** [comment]
в активити уже и так положено начало плагинам, например MainMenuBarFactory. Нам надо решить какие части мы хотим расширять

**Comment by PavelKorchagin** [comment]
По перспективам интерфейса (как в eclipse) Паша Курбацкий сделал отдельную задачу

**Comment by bvv4ik** [comment]
Уточню,
нужно покопировать Днепрораду в отдельно созданные репозитории для 4-х других областей...
типа ..eGov/Nikolaev/wf

**Comment by bvv4ik** [comment]
готово
