### ISSUE TITLE
Дашборд. Отображение задач в списке необработанных только для пользователей соответствующих групп.

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#283]
Необходимо:
1. После авторизации  пользователя на дашборде определять  перечень групп, членом которых он является.
2. Отображать в "Необролених"  только те задачи, которые  соответствуют этим группам.

ВАЖНОЕ ДОПОЛНЕНИЕ:
в доке: http://www.activiti.org/userguide/#_groups
есть метод: identity/groups
где нужно указать параметр: member
равным текущему юзеру, авторизованному в дашборде
в ответ вернется его массив групп!

этот массив нужно подставить в файле:
\i\dashboard-js\server\api\tasks\tasks.controller.js
после строки:
  } else if (req.query.filterType === 'unassigned') {
в виде:
    query.candidateGroups = (загруженный список групп юзера через разделитли);
//(об этом написано в той-же документации, http://www.activiti.org/userguide
// метод GET runtime/tasks)

**Comment by AndrewLvov** [comment]
А где-то есть описание всего серверного API ?

**Comment by bvv4ik** [comment]
вот полный мануал по АПИ Активити:
http://www.activiti.org/userguide/#_forms

**Comment by bvv4ik** [comment]
и там есть параметр с перечнем групп, который можно добавить чтоб список выдаваемых задам был ограничен теми группами, в которые входит данный сотрудник.

нужно просто там-же найти сервис, который отдаст перечень групп авторизованного юзера, в которые он входит (там просто их запомнить и подставить позже в качестве параметра, при выборке списка задач, по соотв. закладке)

**Comment by kurbpa** [comment]
Коллеги, сориентируйте по срокам. 
Задача становится всё более критичной для презентаций в гос.органах.

**Comment by bvv4ik** [comment]
ВАЖНОЕ ДОПОЛНЕНИЕ:
в доке: http://www.activiti.org/userguide/#_groups
есть метод: identity/groups
где нужно указать параметр: member
равным текущему юзеру, авторизованному в дашборде
в ответ вернется его массив групп!

этот массив нужно подставить в файле:
\i\dashboard-js\server\api\tasks\tasks.controller.js
после строки:
  } else if (req.query.filterType === 'unassigned') {
в виде:
    query.candidateGroups = (загруженный список групп юзера через разделитли);
//(об этом написано в той-же документации, http://www.activiti.org/userguide
// метод GET runtime/tasks)

**Comment by bvv4ik** [comment]
Готово!

**Comment by kurbpa** [comment]
2. Отображать в "Необролених" только те задачи, которые соответствуют этим группам. - не работает.

**Comment by bvv4ik** [comment]
таки теперь работает)
