### ISSUE TITLE
Реализовать в ядре поддержку прикрепления файлов чиновниками, при обработке заявок граждан (т.е. в UserTask), подобно томму, как это реализовано для прикрепления аттачментов файлов при заполнении форм гражданами.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#284]
Предполагаемые действия:

-Убрать копирование(клонирование, если оно есть) полей типа file при первом сабмите формы в юзер таску (если оно есть)
- убрать ненужные поля в БП, типа file (по сути из юзертасков, а в стартформ наоборот - оставить) 

Далее варианты:
"план А":
Обеспечить такую-же отработку полей этого типа(file) в юзертаске(если они там есть по БП), как это сейчас реализованно при первом сабмите(т.е. вычитывать контент редиса и атачить)
(т.е. отрабатывать только каждый раз предыдущую юзертаску, при создании новой, в отдельно созданном листенере, на базе существующего)

Как "план Б" делаем так(наиболее вероятен, с учетом выяснившехся сложностей по "Плану А"):
1) Создаем сервис, на базе upload_file_to_redis, с названием upload_file_as_attachment
2) Передаем в него дополнительно параметр ИД-таски
3) Только сохранеем в нем уже массив байтов не в редис а сразу как аттачмент к указанной таске

**Comment by taaraora** [comment]
Итого:
1) На данный момент существует fileTaskUploadListener который можно "повесить" на любую user task и как итог его работы создадутся  экземпляры Attachment которые в скопе таски позволят скачать скан-копии документов, которые были загружены на начальной форме startEvent.
2) Необходимо, иметь возможность для user task для чиновников тоже получать Attachment всех файлов которые чиновник зааплоадит на таске.

Проблема будет решатся лисенером (подобным fileTaskUploadListener).
Обратить внимание на:
1) сколько лисенеров можно вешать на user-task и каким образом.
2) исключить повторное создание Attachment в случае если на разных тасках будет запускаться лисенер создающий одни и теже Attachment (например текущий fileTaskUploadListener).
3) Когда именно происходит событие "create" у user-task.

**Comment by bvv4ik** [comment]
Как "план Б" делаем так:
1) Создаем сервис, на базе upload_file_to_redis, с названием upload_file_as_attachment
2) Передаем в него дополнительно параметр ИД-таски
3) Только сохранеем в нем уже массив байтов не в редис а сразу как аттачмент к указанной таске

**Comment by taaraora** [comment]
Коллеги, к сожалению выполнение задачи блокируют инфраструктурные вопросы. С воскресенья бьюсь с поднятием инфраструктуры на своей машине: WIndows 8.1 + vagrant.
На данный момент выполняются без ошибок файлы:
scripts/prepare_machine.sh
scripts/update_wf_full.sh 
scripts/update_wf_fast.sh
scripts/up_central_js.sh

Проблемный только файл:
scripts/up_dashboard_js.sh. 

Если сегодня не решу проблемы, то завтра приму радикальные меры и установлю себе linux.
Так как я не могу точно прогнозировать решение проблем с поднятием тестовых сервисов, то предположительно завершение тикета может растянуться до конца этой недели(07.06.2015).

**Comment by dr1v3** [comment]
Зачем же так жестоко? Как вариант, можно склонировать репозиторий в виртуальной машине на виртуальную же ФС (без проброса в ФС хост-машины) и настроить доступ к файлам через самбу или фтп-сервер. Дашборд только придётся каждый раз пересобирать вручную.

**Comment by bvv4ik** [comment]
уже и производная задачка создана:
https://github.com/e-government-ua/i/issues/310

**Comment by bvv4ik** [comment]
и еще одна: https://github.com/e-government-ua/i/issues/311

по дальнейшей отсылки указанного атачмента по электронке(в кубике БП)...

**Comment by bvv4ik** [comment]
потренироваться можно на БП: kiev_mreo-1.bpmn (который специально создавался с учетом этой технологии)

**Comment by taaraora** [comment]
Имплементировано по плану Б.
