### ISSUE TITLE
Для главного портала, реализовать диалог по макету. по подтверждению получения доступа к документу (на который открыл доступ гражданин, и передал ссылку)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#285]
Оживить диалог:
https://poligon.igov.org.ua/documents/view

СЦЕНАРИЙ:

1) при заходе на портал по такой "ссылке":
"https://e-gov.org.ua/index#nID_Access=4345&sSecret=JHg3987JHg3987JHg3987
должен вызываться диалог, типа:
https://poligon.igov.org.ua/documents/view#nID_Access=4345&sSecret=JHg3987JHg3987JHg3

2) Дальше автоматический вызов сервиса getDocumentLink(nID_Access,sSecret) - ответ:
Объект:
{
"nID":423423 //ИД доступа
,"nID_Document":34234 //ИД документа
,"sDateCreate":"2015-04-22 23:56:44.002" // дата-время предоставления доступа
,"nMS":34355 //На сколько милисекунд предоставляется доступ
,"sFIO":"Вася Пупкин" //Кому предоставляется доступ
,"sTarget":"" //С какой целью предоставляется доступ
,"sTelephone":"" //На какой телефон отправлять СМС
,"sMail":"" //Электнока того, кому доступ
,"sSecret":"" //Сикрет (копия)
}
(200-тый код, если все ок иначе {"sError":"текст ошибки"}, который нужно вывести в диалог)
По объекту заполняются поля:
-Номер телефона (не редактируется)
-ФИО (не редактируется)
-Цель (не редактируется)
-Кнопка "Отправить СМС для подтверждения доступа к документу"

3) При нажатии кнопки "Отправить СМС для подтверждения доступа к документу"
вызов сервиса getDocumentAccess(nID_Access,sSecret) - ответ 200-тый код, если все ок иначе {"sError":"текст ошибки"}, который нужно вывести в диалог.
отображаем(ниже) "поле для ввода номера, который придет в СМС"
(ВАЖНО: временно работает бэкдур, и действует пароль "1234", т.к. СМС-ки пока не отправляются)

4) После ввода кода в поле отображаем:
кнопка "Открыть документ"

5) После нажатия кнопки
вызов сервиса setDocumentAccess(nID_Access,sSecret,sAnswer) если ответ 200-тый код(все ок), то из полученного объекта {"sURL":"https://....."} - переходим по УРЛ-у, иначе {"sError":"текст ошибки"}, который нужно вывести в диалог.

ВРЕМЕННО, ЕСЛИ ВСЕГДА получаем не 200-тый код(мало-ли что), то подставляем мок-овый объект:
{"name":"sURL","value":"https://igov.org...."}
и тогда перезодим по этому УРЛ-у в поле значение "value"

Актуальная документация по перечисленным выше методам тут:
https://github.com/e-government-ua/i/blob/test/docs/specification.md
(11. Предоставление и проверка доступа к документам)

П.С.: 
макет:
https://github.com/e-government-ua/i/blob/test/portal-php/public_html/mockup/access.html
макет делался по задаче:
https://github.com/e-government-ua/i/issues/195
коммит с реализованным макетом:
https://github.com/e-government-ua/i/commit/dd205b2

П.П.С:
на самом деле, сам УРЛ "ссылки", типа:
"https://e-gov.org.ua/index#nID_Access=4345&sSecret=JHg3987JHg3987JHg3987
можно подкорректировать (если сложно/плохо будет организовать редирект)
т.к. УРЛ генерится по сервису, из задачи:
https://github.com/e-government-ua/i/issues/197
а шаблон уже залит на: "https://poligon.igov.org.ua/documents/view"

**Comment by dr1v3** [comment]
Макет можно взять тут и вытянуть нужное
https://github.com/e-government-ua/i/blob/test/portal-php/public_html/mockup/access.html

**Comment by AndrewLvov** [comment]
Как воспроизвести эту страницу ?

**Comment by dr1v3** [comment]
Закинул только что макет, нужно написать соответствующий контроллер
https://poligon.igov.org.ua/documents/view

**Comment by AndrewLvov** [comment]
Попробую сделать логику

**Comment by vdubyna** [comment]
Взял задачу

**Comment by bvv4ik** [comment]
уже реализовано в другой таске...
