### ISSUE TITLE
Заменить названия серверов (при отображении в ssh-консоли) или проконтролировать замену

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#288]
на всех машинах нужно будет менять /etc/hosts

52.17.55.95 AWS-E-Government-Portal1 > AWS-iGov-centr-prod
52.17.120.14 AWS-E-Government-APP4 > AWS-iGov-centr-test
52.17.234.213 AWS-E-Government-APP5 > AWS-iGov-region-dniprorada
52.16.218.217 AWS-E-Government-DB1) > AWS-iGov-db-prod
52.17.225.109 AWS-E-Government-Redis1 > AWS-iGov-kvs-redis
54.76.209.57  > AWS-iGov-kvs-mongo
52.17.85.174 AWS-E-Government-LOGS > AWS-iGov-log
54.76.222.21 AWS-E-Government-APP3 > AWS-iGov-tech
54.76.130.15 AWS-E-Government-APP2 > AWS-iGov-region-demo-test
52.17.188.249 AWS-E-Government-APP1 > AWS-iGov-region-demo-prod

если какие-то машины пропустил - прошу отписаться в комменте

**Comment by ValerijMakarenko** [comment]
done
