### ISSUE TITLE
На главном портале, по кнопке "Все услуги" открывать страницу с перечнем услуг этой подкатегории (в три колонки)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#292]
URL, при этом должен меняться на что-то типа этого:
https://poligon.e-gov.org.ua/subcategory/10
(т.к. чтоб даже по прямой ссылке можно было отобразить то-же самое)

количество строк балансировать равномерно между всеми тремя колонками

эта задача - продолжение предыдущей: https://github.com/e-government-ua/i/issues/287

**Comment by vdubyna** [comment]
Я додав новий роут 
Не зміг знайти хороше API для того щоб зразу витягти список саме підкатегорії
але загалом масив сервісів невеликий тому тягну йогоувесь і фільтрую вже в браузері
згодом - це можна замінити на щось більш адекватне

**Comment by bvv4ik** [comment]
Спасибо огромное! Теперь совсем красота будет)

Отличный выход из положения. я осознавал, что отдельного сервиса нет, и придется пока тянуть все, потому все норм.

Единственное - хотел попросить - достаточно просто протестить у себя локально изменение, и сразу выливать в тест, минуя пулреквест.
т.к. уже куча проблемм с ним было.. и вот сейчас опять - конфликт при мерже, и ни кто кроме автора не сможет его разрулить.
Потому прошу смержить и вытолкнуть в тес...

Единственное - это стоит потом дождаться авто-деплоя на общий тестовый и убедиться что точно ничего не сломалось:
https://poligon.igov.org.ua

**Comment by bvv4ik** [comment]
Владимир, еще раз спасибо, то что нужно!!!
Готово!
