### ISSUE TITLE
Сделать вирусные баннеры для соц сетей

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/i#303]
Вот есть пример одного баннера он конечно не вирусный, но пока для начала
https://egovernmentukraine.wordpress.com/banners/

В каждом баннере должен быть только один призыв к действию
Пример 1: вступите в нашу группу на фейсбук
Пример 2: Хотите помочь? Заполните анкету на нашем сайте "Готовий допомогти"
Пример 3: Хочешь помочь? Сделай репост этого сообщения.
Пример 4: Придумайте свой вариант

Какой баннер лучше всего работает мы сможем увидеть по количеству присоединившихся к нам в команду(также косвенно можем оценить эффективность по количеству лайков и репостов).

Нужно пробовать разные варианты, эффективные оставлять, слабые выбраковывать.

Язык баннера. Давайте наверно остановимся на украинском, если есть желание можем еще сделать на русском.

Где можно брать идеи для баннеров:

Можно посмотреть как реализовано за рубежом, и выбрать те посты (публикации, призывы к действию) которые набрали больше всего комментариев, лайков, репостов.

1. https://plus.google.com/u/0/110962536448556586141/about (можно взять инфогрфику сделать похожую)
2. http://egov.md/ro
3. https://servicii.gov.md/
4. https://www.flickr.com/photos/e-government_center_moldova/sets/72157638577350014/
5. https://guvernonline.wordpress.com/
6. https://www.facebook.com/eGovernment.Center.Moldova (Страница на ФБ)
7. http://www.opengovpartnership.org/get-involved/london-summit-2013
8. Ваш вариант

Если вы делаете баннеры в фотошопе, желательно потом каждый слой сохранить отдельно, не у всех куплена лицензия на фотошоп, потому люди используют GIMP, PainNET, InkScape, любые онлайн сервисы, ваш вариант. Смысл, чтоб другой человек мог открыть и отредактировать, написать новый текст, и тп, поэтому желательно делать в той программе которая доступна всем.

Мои идеи для беннаров:

===============1================
Хочеш замінити наш уряд на електронний?
Долучайся до нашої групи:
===============2================
Ми заміняємо наш уряд на електронний! (електронним)
Допоможи нам: (тут лінк на групу ФБ)
===============3================
Ми заміняємо наш уряд на електронний!
Потім коли замінем весь уряд, почнем заміняти депутатів
Долучайся: (тут лінк на групу ФБ)
===============4================
Хочеш всі послуги отримувати в інтернеті?
В інтернеті у вас не зможуть брать взятки! (хабарі)
Долучайся: (тут лінк на групу ФБ)
===============5================
Хочеш знати куди твій голова/мер витратив бюджет?
заміни голову на електронну систему:
===============6================

**Comment by bvv4ik** [comment]
Просьба перенести эту issue в бэклог и закрыть ее:
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit

**Comment by rostag** [comment]
@VadymVolos - пропоную варіант концептуального наповнення такого банера: 
https://github.com/e-government-ua/i/issues/597#issuecomment-132564340

**Comment by VadymVolos** [comment]
@rostag дякую цікава ідея! 
Так я не зрозумів закривати цю таску чи будемо щось робити?

Наприклад для золучення нових людей нам треба подумати про пости в соцмережах

**Comment by VadymVolos** [comment]
Якщо ви пропонуете 
>rostag commented 4 hours ago
>Пропоную також на основі даної схеми з заголовком зробити шаблони Cover Photo / 
>User Photo для Facebook / Twitter / LinkedIn / GooglePlus та інших соцмереж.

>Тоді учасники проекту зможуть використати їх на своїх сторінках і тим замим сприяти залученню >нових людей у проект.

>Думаю, це допоможе нам у виконанні таску #303

Тоді можна як варіант, генерувати зображення якесь кольорове
На зображенні по центру писати яка послуга запущена
Трошки меншими літерами в яких містах чи городах запущена
Також писати дату
І загальну кількість послуг які вже запушені на порталі,

Буде міні зображення для соц мереж з свіжими новинами,

Думаю люди будуть лайкати

**Comment by VadymVolos** [comment]
Ось зробив одну фотку https://www.facebook.com/groups/458833010941504/permalink/500368116787993/

**Comment by bvv4ik** [comment]
прикольно)

**Comment by VadymVolos** [comment]
Зробив альбом в групі і додав ще декілька фото 
https://www.facebook.com/media/set/?set=oa.502158666608938&type=1

![Facebook Cover 2](https://scontent-fra3-1.xx.fbcdn.net/hphotos-xfp1/t31.0-8/11894500_983503545034414_4465670189112760638_o.jpg)

![Facebook Cover 3](https://scontent-fra3-1.xx.fbcdn.net/hphotos-xpa1/t31.0-8/11885022_983503521701083_4919010978417200131_o.jpg)

![Image for Post 4](https://scontent-fra3-1.xx.fbcdn.net/hphotos-xfl1/v/t1.0-9/11954649_983503531701082_9015850300958319671_n.jpg?oh=474786d11eadab1fd478795fed314b3b&oe=563C39F5)

**Comment by VadymVolos** [comment]
Шановні Друзі!
У зв'язку з тим що вже створили репозиторій для Бізнес Процесів
https://github.com/e-government-ua/iBP
@bvv4ik 
Можливо зробимо репозиторій для маркетингу і реклами, щоб це завдання туди перенести?

Тому що воно завжди актуальне, і дуже не вірно його закривати.
І інші питання по маркетингу, рекламі, там же ставити і вирішувати.

Ті хто пише тексти, робить презентації, відеоуроки, їх теж в відділ Маркетингу.

**Comment by bvv4ik** [comment]
дело в том, что репозиторий, в основном для хранения данных а уже таски - производное от этого процесса...
Для БП тут все понятно - создаем там базу описаний БП и ведем по их разработке таски...

для Маркетинга такой базы ,вроде как и нет(и быть не может)... а продукт маркетинга (видео-ролики для обучения пользованию, например, должны попасть(их ссылки) уже в общую вики по проекту (как, кстати, и общие доки по созданию и доработкам компонентов для БП)

Потому, создавать репозиторий только ради того чтоб туда, как в отдельную группу "таски складывать" - не вариант...

ИМХО, по Маркетингу потенциально не так много задач отдельных может быть, чтоб создавать "отдельную республику")
Тут и слак-а и соцсетей вполне достаточно (тем более что там более соответствующая этим таскам аудитория)

**Comment by rostag** [comment]
А може, тримати маркетинг-топіки в Trello? Заодно й обкатаємо ще один корисний інструмент.

**Comment by VadymVolos** [comment]
Забув за цю Таску, тільки побачив
З приводу Trello, не знаю що це і навіщо.
Якщо вмієте їм користуватись, додавайте. Тільки навіщо?

**Comment by VadymVolos** [comment]
Додав фотку з песиком на ФБ сторінку
знизу фотки написав "Дуже потрібні волонтери Фронтенд-щики (Node JS + AngularJS)."

https://www.facebook.com/igov.org.ua/photos/a.1630857540536456.1073741830.1589199384702272/1630857543869789/?type=3&permPage=1
