### ISSUE TITLE
Создание логотипа iGov для сайта электронного правительства

### ISSUE THREAD

**Issue by NikolayAngel** [e-government-ua/i#307]
Для ребрендинга название сайта egovernmentukraine (https://egovernmentukraine.wordpress.com/) на iGov необходимо разработать логотип.
Возможные ассоциации для изображения: человек, электронное правительство, государство, символика Украины, на фоне названия iGov
Логотипы iGov для примера: https://www.google.com.ua/search?q=igov&espv=2&biw=1536&bih=758&source=lnms&tbm=isch&sa=X&ei=tjNwVcPINcv9ywOdtoOwDQ&ved=0CAYQ_AUoAQ

**Comment by SergBoundary** [comment]
Вітаю. Чи ще актуальне питання логотипу?
