### ISSUE TITLE
На бэке главного портала (wf-central) - подвязать вызовы всех сервисов по документам к сохранению истории (Мой журнал)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#309]
Встроить сохранение истории, при использовании сервисов:
9. Работа с документами
11. DocumentAccess
(описание сервисов: https://github.com/e-government-ua/i/blob/test/docs/specification.md )

т.е. в яве(скорей всего в контроллерах вышеперечисленных сервисов) - подобавлять прямой вызов метода "setHistoryEvent" (не через REST, конечно, а напрямую)

Так-же ориентироваться на эту концепцию (2. Мой журнал):
https://docs.google.com/document/d/1HNA57PO7aC7SJHyWb-CS8OU-w5K1toQtwViyla1VbB0/edit
и реализованную задачу:
https://github.com/e-government-ua/i/issues/290

**Comment by bogdanlupashko** [comment]
Беру в реализацию

**Comment by LamronNu** [comment]
сделано журналирование следующих событий:
**1)загрузка документа в раздел Мои документы**
для проверки достаточно зайти в раздел Журнал и увидеть там запись.
Примечание: запись отображается некорректно. в Responce видно, что событие содержит два поля: sMessage и sEventName. второе берется "по дефолту" (из перечисления HistoryEventType).
думаю, лучше отображать sMessage , в котором содержится подробная информация -- если нужно, создам отдельную задачу.
скриншот: 
![image](https://cloud.githubusercontent.com/assets/8156670/8461835/0e0eee9c-2038-11e5-9e52-bf6a68d64ad0.png)


**2) предоставление доступа к документу. 
3) пользование доступом.**
Эти два пункта пока нет возможности проверить, т.к. функционал доступа временно не работает (задача https://github.com/e-government-ua/i/issues/460). Но журналирование на эти два действия прописано -- когда будет исправлен механизм, то протестируется и эти два пункта

*ориентировочные ссылки* (если "визуальная часть" еще не будет до конца реализована, но задача https://github.com/e-government-ua/i/issues/460 будет решена):
--дать доступ:
/wf-central/service/setDocumentLink?nID_Document=499&nMS=604800000&sFIO=test&sTarget=&sTelephone=+380102030405
--перейти по ссылке доступа (nID_Access и sSecret взять из предыдущего ответа)
/wf-central/service/getDocumentLink?sSecret=???&nID_Access=???

сейчас разбираюсь с событиями
**4) Пользователь воспользовался услугой на портале**
пункт немного не понятен -- на какой метод какого контроллера реагировать? *service/services/getService*? или *service/rest/start-process/{key}*?

**5) Изменение статуса заявки**
также уточнение  -- реагировать нужно на *service/services/setService* -- и проверять, поменялся ли статус?

список событий взят из <a href="https://docs.google.com/document/d/1HNA57PO7aC7SJHyWb-CS8OU-w5K1toQtwViyla1VbB0/edit">файла</a> 
также учитывались типы событий в перечислении **HistoryEventType**

есть ли еще События, которые нужно "залогировать" на данном этапе?

**Comment by bvv4ik** [comment]
Спасибо, на текущий момент п.1-3 достаточно!

только, важно учесть еще и метод "getDocumentAccessByHandler ", который делался по таске: https://github.com/e-government-ua/i/issues/450

а основа для п.4 и 5 сейчас реализуется в задаче: https://github.com/e-government-ua/i/issues/331
там будет реализован общий класс, в который потом останется только добавить вызовы сохранения истории.

**Comment by LamronNu** [comment]
для теста.
п.1 -- при заходе в раздел Журнал сразу есть событие, что документ загружен
п.2 -- предоставить доступ к документу -- получить ссылку -- перейти в Журнал и увидеть событие
ИЛИ: предоставить доступ через "прямую" ссылку согласно доке:
https://test.igov.org.ua/wf-central/service/setDocumentLink?nID_Document=2&sFIO=test&sTarget=secret&sTelephone=+380102030405&nMS=604800000&sMail=test@ya.com

3) метод getDocumentAccessByHandler  (пользование доступом по коду,:задача #450) -- можно проверить,  например, так

https://test.igov.org.ua/wf-central/service/services/getDocumentAccessByHandler?sCode_DocumentAccess=2&nID_DocumentOperator_SubjectOrgan=2&sPass=123&nID_DocumentType=1

все события, которые сгенерировались, можно просмотреть запросом:
https://test.igov.org.ua//wf-central/service/services/getHistoryEvents?nID_Subject=2

тут берется ид документа=2. при желании можно подобрать другой документ.

переход по ссылке доступа (которая сгенерировалась при нажатии соответствующей кнопки в разделе Мои документы) сейчас не работает (почему?? недоработано еще или "поламано"?).

 остальные пункты (по логированию бп) -- будет другая задача

**Comment by rooksnest** [comment]
Протестировано журналирование и предоставление доступа к документу.
Получение доступа по ссылке не работает!

**Comment by LamronNu** [comment]
>Получение доступа по ссылке не работает!

это другая задача, в рамках этой, к сожалению,  не решается.. хоть там событие и прописано.. т.е. по этому пункту ничего не предпринимаем (в этой таске).
>Та же в "Мой журнал" в ФФ вместо времени и даты событи возвращается "NaN undefined 0NaN NaN:NaN". В хроме такого не наблюдается.

что конкретно не так, если можно -- то скриншоты, пожалуйста. ФФ -- это сокращение чего?)) в общем, напишите тут.. задача тестирования как раз в выявлении вот таких вот "глюков" и исправлении их..)

спасибо!

**Comment by rooksnest** [comment]
ФФ - Firefox))

**Comment by LamronNu** [comment]
ээээ... круто)))) т.е. это только в фаерфоксе?) а другие браузеры как? 
действительно, в хроме такого точно не наблюдалось.. а что в коде страницы? и в шттп-запросах? не знаю, как в ФФ, но в хроме, чтобы увидеть запрос-ответ, то ПКМ -- просмотр кода элемента -- сверху вкладка Network -- справа (после отправки запроса) вкладка Response.
пкм -- правая кнопка мышки)
я у  в коде еще тоже гляну, что может быть "не так".. может, это фронт, а не бек, но в любом случае нужно разобраться.

**Comment by rooksnest** [comment]
Да, только в файрфоксе. Правда в IE не представляется возможности проверить, там полный ад)
А по ответам в запросах... ответ есть только в https://test-version.igov.org.ua/js/app/journal.js
![3](https://cloud.githubusercontent.com/assets/13005113/8894913/6d6d367c-33d0-11e5-8685-ee3af87306d3.png)
вот полный Response
define('state/journal/controller', ['angularAMD'], function (angularAMD) {
	angularAMD.controller('JournalController', ['$scope', '$state', 'config', 'BankIDService', function
 ($scope, $state, config, BankIDService) {
		$scope.config = config;

        BankIDService.isLoggedIn().then(function() {
            if ($state.is('journal')) {
                return $state.go('journal.content');
            }
        }).catch(function() {
            if ($state.is('journal')) {
                return $state.go('journal.bankid');
            }
        });
    }]);
});

define('state/journal/bankid/controller', ['angularAMD'], function (angularAMD) {
	angularAMD.controller('JournalBankIdController', ['$rootScope', '$scope', '$location', '$state', '$window'
, 'BankIDService', function ($rootScope, $scope, $location, $state, $window, BankIDService) {

        $scope.loginWithBankId = function () {
            var stateForRedirect = $state.href('journal.bankid', {});
            var redirectURI = $location.protocol() +
                '://' + $location.host() + ':'
                + $location.port()
                + stateForRedirect;
            $window.location.href = './auth/bankID?link=' + redirectURI;
        }
		
        if ($state.is('journal.bankid')) {
            if($state.params.error){
                $scope.error = JSON.parse($state.params.error).error;
            } else {
                BankIDService.isLoggedIn().then(function () {
                    return $state.go('journal.content', {code: $state.params.code});
                });
            };
        }
    }]);
});
define('state/journal/content/controller', ['angularAMD'], function (angularAMD) {
	angularAMD.controller('JournalContentController', [
        '$rootScope', '$scope', '$state', 'journal',
        function ($rootScope, $scope, $state, journal) {
            $scope.journal = journal;
            angular.forEach($scope.journal, function(item, index) {
                $scope.journal[index]['sDate'] = new Date(item.sDate);
            });
        }
    ]);
});

define('journal', ['angularAMD', 'config', 'service'], function (angularAMD) {
    var app = angular.module('journal', []);

    app.config(['$stateProvider', function ($stateProvider) {
        $stateProvider
            .state('journal', {
                url: '/journal',
                views: {
                    '': angularAMD.route({
                        templateProvider: ['$templateCache', function($templateCache) {
							return $templateCache.get('html/journal/index.html');
						}],
						controller: 'JournalController',
                        controllerUrl: 'state/journal/controller'
                    })
                }
            })
            .state('journal.bankid', {
                url: '/bankid?code&error',
                parent: 'journal',
                views: {
                    'bankid': angularAMD.route({
                        templateProvider: ['$templateCache', function($templateCache) {
							return $templateCache.get('html/journal/bankid/index.html');
						}],
						controller: 'JournalBankIdController',
                        controllerUrl: 'state/journal/bankid/controller'
                    })
                }
            })
            .state('journal.content', {
                url: '/content?code',
                parent: 'journal',
                resolve: {
                    BankIDLogin: function($q, $state, $location, $stateParams, BankIDService) {
                        return BankIDService.isLoggedIn().then(function () {
                            return {loggedIn: true};
                        }).catch(function() {
                            return $q.reject(null);
                        });
                    },
                    BankIDAccount: ['BankIDService', 'BankIDLogin', function(BankIDService, BankIDLogin
) {
                        return BankIDService.account();
                    }],
                    customer: ['BankIDAccount', function (BankIDAccount) {
                        return BankIDAccount.customer;
                    }],
                    journal: ['$q', '$state', 'ServiceService', 'customer', function($q, $state, ServiceService
, customer) {
                        return ServiceService.getJournalEvents();
                    }]
                },
                views: {
                    'content': angularAMD.route({
                        templateProvider: ['$templateCache', function($templateCache) {
							return $templateCache.get('html/journal/content.html');
						}],
						controller: 'JournalContentController',
                        controllerUrl: 'state/journal/content/controller'
                    })
                }
            })
    }]);
    return app;
});

**Comment by LamronNu** [comment]
так, код совсем не по теме) т.е. нужно смотреть не код, а то, что получил этот код...
вот скрин с хрома:
![image](https://cloud.githubusercontent.com/assets/8156670/8895249/44517a7c-33db-11e5-82f2-58f4a81b87bf.png)

видно, что дата есть, причем в формате гггг-мм-дд, чч:мм:сс,млс

по виду журнала -- вот сейчас у меня: 
![image](https://cloud.githubusercontent.com/assets/8156670/8895234/be677e48-33da-11e5-902e-fdd59fd8736a.png)

т.е. то, что "отображается пользователю", возможно, зависит от настроек у самого этого пользователя... или в браузере, или в ОС (локальные установки, например)..

**Comment by bvv4ik** [comment]
@rooksnest, 
LamronNu - права! это клиентская(фронтовая) локализация(формат даты/времени)...
и к данной задаче отношения не имеет
