### ISSUE TITLE
Activiti - new form panel design

### ISSUE THREAD

**Issue by PavelKorchagin** [e-government-ua/i#31]
Расположение элементов на панели, которая отражает формы юзертасков - не юзабильно. Проработать кастомный дизайн панели и последовательности расположения элементов.

**Comment by kurbpa** [comment]
в первом приближении проработано. https://docs.google.com/a/privatbank.ua/document/d/1xueqPW0XqXBr_SPnBtBkwhI2CPxMKihzX9zDIsqBMc4/edit#heading=h.o8t4xxgsthyn

**Comment by bvv4ik** [comment]
реализована альтернатива - дашбоард.
уже не актуально
