### ISSUE TITLE
В ядре(wf-base) переделать класс "MailTaskWithAttachments" так, чтоб он отсылал в письме атачменты(как прикрепленные файлы), которые перечислены в определенном поле.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#311]
пэкэдж класса:
org.wf.dp.dniprorada.engine.task
(не перепутать с классом "MailTaskWithAttachment"!!!)

Изменение логики:
Смотреть в поле с названием "saAttachmentsForSend"
в нем будут перечислены(через запятую) ИД-номера аттачментов, которые нужно отсылать
Например: "4543,4544,4545"

и руководствуясь образцом кода в:
org.activiti.rest.controller.getAttachmentFromDb

взять только те атачменты, ИД-номера которых перечислены в указанном выше поле...

Возможно, для этого придется как-то передавать еще туда ИД таски или ИД процесса

если надо, то откорректировать логику в классе "MailTaskWithAttachments", метода "execute(DelegateExecution execution) throws Exception {", т.к. такое впечатление, что там неверно расширение файла передается...

П.С.: потренироваться можно на БП: kiev_mreo-1.bpmn
(который специально создавался с учетом этой технологии)
А в главном каталоге название услуги:
"Реєстрація авто з пробігом в МРЕВ"
находится в Киеве
Ссылка вот:
https://poligon.igov.org.ua/service/159/general

**Comment by taaraora** [comment]
Имплементировано в соответствии с описанием.
