### ISSUE TITLE
На главном портале починить ссылку на услуге с типом "Ссылка" (сейчас там всегда https://localhost)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#312]
починить УРЛ перехода на другой сервис

Міліція
"Отримати довідку про несудимість"
Дніпропетровська
Кривий ріг
"Крок 2. Перейдіть за посиланням: Отримати довідку про несудимість"

так вот ссылка "Отримати довідку про несудимість":
http://localhost/

в то время как в данных там нормальная ссылка (в обьекте-массиве aServiceData)

**Comment by bvv4ik** [comment]
Спасибо за принятие задачи!
можно, плиз, какой-то ориентир по сроку?

**Comment by hordesalik** [comment]
с учетом выходных - 8.06 крайний срок.

**Comment by bvv4ik** [comment]
Готово!
