### ISSUE TITLE
На бэке (в ядре wf-base) реализовать сервис довнлоадинга файла csv, в котором будет храниться статистика по отработанным бизнес-процессам, в рамках какой-то услуги

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#313]
Данные(тайминги) собирать стандартными средствами Activiti (из базы)

Назвать сервис: download_bp_timing
На вход передавать:
1) sID_BP_Name ИД бизнеспроцеса
2) sDateAt дату начала выборки
3) sDateTo дату конца выборки

Должны быть поля:
-Исполнитель (на кого ассигнуто)
-дата и время старта юзертаски (этапа)
-время в милисекундах, сколько прошло до момента отработки юзертаски (этапа)
-время в часах, сколько прошло до момента отработки юзертаски (этапа)
-название этапа (юзертаски)

Предлагать сохранять с названием файла:
[название БП]_ГГГГ-ММ-ДД_чч-мм-сс.csv

саму часть по отдачи сервисом файла - можно посмотреть на примере сервиса:
/file/download_file_from_db

**Comment by taaraora** [comment]
Позвольте уточнить:
"-дата и время старта юзертаски (этапа)" подразумевается время ассайна таски на пользователя?
Если количество тасок будет тысячи и больше то вместо использования стандартных средств наверное лучше использовать обычный SQL?

**Comment by bvv4ik** [comment]
""-дата и время старта юзертаски (этапа)" подразумевается время ассайна таски на пользователя?"
нет, именно дата создания таски или скорее процесса..

"Если количество тасок будет тысячи и больше то вместо использования стандартных средств наверное лучше использовать обычный SQL?"
ка правило, если стандартными средствами активити(например РЕСТ), тот там можно задавать параметр size, например size=1000, и тогда он лимитирует ответный список 1000 позициями...
можно, конечно, и  из базы попытаться напрямую выборку делать... но мне кажется, что стоит попробовать вначале именно встроенными средствами, хотя если будет выборка из базы - тоже будет норм..

**Comment by ASkosyr** [comment]
забрал на себя
планирую поставить 26 июня

**Comment by ASkosyr** [comment]
Задачу закончил. Код в ветке test

Добавил описание нового метода на страницу с описанием API
https://github.com/e-government-ua/i/blob/test/docs/specification.md#16-Получение-статистики-по-задачам-в-рамках-бизнес-процесса

Пример вызова метода
https://test.igov.org.ua/wf-region/service/rest/file/download_bp_timing?sID_BP_Name=lviv_mvk-1:35:512570&sDateAt=2015-06-28&sDateTo=2015-07-01

**Comment by VadimGulich** [comment]
Работает корректно , спасибо за описание 
Можно на боевой
