### ISSUE TITLE
В ядре (wf-base), создать сущности для работы с "электронной очередью", при обслуживании граждан по услуге + REST-сервисы, по образцу реализованной сущности Document

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#315]
ВАЖНО: Использовать исключительно Hibernate+Liquibase+DAO+REST+JSON, как это реализовано уже для сущности Document (и автосоздание структуры с заливкой данных):
\i\wf-central\src\main\resources\liquibase\init.xml - авто-инициализация структуры через liquibase
\i\wf-central\src\main\resources\data\Document.csv - авто-заполнение структуры через liquibase
\i\wf-central\src\main\java\org\wf\dp\dniprorada\model\Document.java - сущность Hibernate
\i\wf-central\src\main\java\org\wf\dp\dniprorada\dao\DocumentDao.java - сущность DAO (ядро)
\i\wf-central\src\main\java\org\wf\dp\dniprorada\dao\DocumentDaoImpl.java - сущность DAO
\i\wf-central\src\main\java\org\activiti\rest\controller\ActivitiRestDocumentController.java - REST (/getDocument")

САМА ЗАДАЧА:

1) Создать сущности(таблицу с полями):

1.1) SubjectOrganType (тип субъекта-орган/организация), с полями:
nID (лонг) - номер-ИД (уникальный) //обязательное (автоитеррируемый)
sName (<200 символов) - строка название //обязательное

1.2) ServiceOperator_SubjectOrgan (Оператор сервиса - субъект-орган/организация), с полями:
nID (лонг) - номер-ИД (уникальный) //обязательное (автоитеррируемый)
nID_SubjectOrgan (лонг) - номер-ИД субьекта //обязательное
sName (<300 символов) - строка названия //обязательное

1.3) SubjectOrganDepartment, с полями:
nID (лонг) - номер-ИД (уникальный) //обязательное (автоитеррируемый)
nID_SubjectOrgan (лонг) - номер-ИД субьекта //обязательное
sName (<300 символов) - строка названия департамента //обязательное
sGroup_Activiti(<100 символов) - строка ИД группы Активити //обязательное

1.4) Flow_ServiceData (Данные сервиса - поток), с полями:
nID (лонг) - номер-ИД (уникальный) //обязательное (автоитеррируемый)
nID_ServiceData (лонг) - номер-ИД записи с данными сервиса //обязательное
nID_SubjectOrganDepartment (лонг) - номер-ИД департамента //обязательное
sName (<300 символов) - строка названия //обязательное
sID_BP (<50 символов) - ИД-строка определения бизнес процесса //обязательное

1.5) FlowProperty (Свойства потока), с полями:
nID (лонг) - номер-ИД (уникальный) //обязательное (автоитеррируемый)
nID_Flow_ServiceData (лонг) - номер-ИД потока данных сервиса //обязательное
nID_FlowPropertyClass (лонг) - ИД-строка класса-обработчика //обязательное
sData (<200 символов) - строка с данными для обработчика //обязательное

1.6) FlowPropertyClass (Класс-свойство потока), с полями:
nID (лонг) - номер-ИД (уникальный) //обязательное (автоитеррируемый)
sName (<100 символов) - строка названия //обязательное
sPath (<100 символов) - строка пакет.класс с обработчиком //обязательное

1.7) FlowSlot (слот потока), с полями:
nID (лонг) - номер-ИД (уникальный) //обязательное (автоитеррируемый)
nID_Flow_ServiceData (лонг) - номер-ИД потока данных сервиса //обязательное
sDate (дата со временем) - дата и время //обязательное
sData (<30 символов) - строка данных //необязательное
sDuration (длительность) - строка длительности (например "PT15M") //обязательное
В соответствии с логикой: https://en.wikipedia.org/?title=ISO_8601#Durations
sName (<200 символов) - строка, описания для человека (напр: "2015-06-06 с 8-00 до 8-30") //обязательное
(добавить ключ по комбинации полей:  nID_ServiceDataFlow+sDate)

1.8) SubjectTicket (тикет субьекта), с полями:
nID (лонг) - номер-ИД (уникальный) //обязательное (автоитеррируемый)
nID_FlowSlot (лонг) - номер-ИД слота потока //обязательное
nID_Subject (лонг) - номер-ИД субьекта //обязательное
nID_Task_Activiti (лонг) - номер-ИД задачи Активити //не обязательное
sDateEdit (дата со временем) - дата и время редактирования //обязательное

2) ОТМЕНЕНО!!!! Создать в контроллере ActivitiRestFlowController.java новые REST-методы (подобно ActivitiRestDocumentController):
получения и установки каждой из сущностей выше (гет-еры и сет-еры)
Подобно этим(только как пример названий работы и форматов объекта на выходе и входе):
2.1. /getHistoryEvents (nID_Subject) - ответ массив объектов oHistoryEvent
2.2. /getHistoryEvent (nID) - ответ объект oHistoryEvent
2.3. /setHistoryEvent (все поля сущности, кроме nID) - ответ {"nID":54235} (c ИД-шником созданного объекта oHistoryEvent)
и соблюсти в п.3. образец объекта(обязательно сохранить кейс и точные названия полей):
oHistoryEvent:{
"nID": 445
,"nID_Subject": 2
,"nID_HistoryEventType":3
,"sEventName":"" - консолидированное название события
,"sMessage":""
,"sDate":"2015-11-25 23:23:59.325"
}

(если тут будет что-то не понятно - ЛУЧШЕ уточнить предварительно и согласовать все названия!!!)

4) Наполнить \i\wf-central\src\main\resources\data\*.csv по паре примеров, для каждой сущности (и обязательно подвязать все в liquibase\init.xml

Идеология задачи:
https://docs.google.com/document/d/1Jd3LODo2Nl4EsXdvqrK8yZ5j_Hf24vuCgQhJb06TETI/edit

**Comment by brunneng** [comment]
Можете пожалуйста возле каждой таблицы дать русское название сущности (или несколько, если есть альтернативные). Мне кажется названия для некоторых таблиц подобраны не очень удачно.

**Comment by bvv4ik** [comment]
сделал

**Comment by brunneng** [comment]
Решили, что рест сервиса для новых сущностей будут создаваться в других задачах. Так что эту можно закрывать.

**Comment by brunneng** [comment]
Для тестирования нужно поднять приложение и убедится, что новые таблицы создались, и в каждой из них присутствует как минимум 1 запись тестовых данных.
