### ISSUE TITLE
Перенос классов из модулей wf-central и wf-region в wf-base.

### ISSUE THREAD

**Issue by taaraora** [e-government-ua/i#316]
В модуле wf-central ряд классов полностью или почти полностью дублируют классы из wf-base.
И в wf-region в каталоге test.
Например:
\wf-central\src\main\java\org\activiti\rest\controller\adapter\AttachmentEntityAdapter.java
\wf-central\src\main\java\org\activiti\rest\controller\entity\AttachmentEntity.java
\wf-central\src\main\java\org\activiti\rest\controller\entity\AttachmentEntityI.java
\wf-central\src\main\java\org\activiti\rest\controller\*
Необходимо проанализировать классы по трём модулям: wf-base, wf-central, wf-region и перенести все такие классы-дубликаты в wf-base (а если они различны - лучше уточнить).
При этом сконфигурировать pom.xml чтобы war для модулей wf-central и wf-region продолжили корректно собираться.

**Comment by bvv4ik** [comment]
.

**Comment by OlgaTurenko** [comment]
Сделала все, кроме ActivitiRestApiController.java

В этом классе есть на wf-base и wf-central разные версии сервисов:
/download_file_from_db
/upload_file_as_attachment (различие в sFilename)
/file/upload_file_to_redis
Я так понимаю актуальная версия на wf-base?

**Comment by bvv4ik** [comment]
"Я так понимаю актуальная версия на wf-base?"
да

**Comment by bvv4ik** [comment]
но если есть отдельные сервисы в этом контроллере, которые по другому называются, то их обязательно нужно перетащить "поштучно в бэйс", а одинаковые по названию но разные по содержанию, в плоть до скайпа с демонстрацией экрана и обсуждения голосом....

**Comment by bvv4ik** [comment]
давнооооо... это было
закрываем таску

**Comment by VadimGulich** [comment]
закрываем ))
