### ISSUE TITLE
В wf-central реализовать отсылку OTP-пароля (через sms) в классе org.wf.dp.dniprorada.dao.DocumentAccessDaoImpl, для подтверждения доступа к документу

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#317]
в классе:
org.wf.dp.dniprorada.dao.DocumentAccessDaoImpl
в методе:
public String getDocumentAccess(Long nID_Access, String sSecret) throws Exception {
начиная со 164-й строки, отсылать значение переменной "sAnswer", с помощью сервиса:

полная дока: https://itwiki.privatbank.ua/wiki/OTP_API
(доступна только сотрудникам Приватбанка, но в ней нет необходимости, т.к. все основное описано ниже)

URL для отправки пароля:
https://sms-inner.siteheart.com/api/otp_create_api.cgi

При использовании JSON формата необходимо указать HEADER HTTP запроса content-type = "application/json; charset = utf-8"
{
  "merchant_id":"13",             
  "merchant_password":"qwerty",   
  "otp_create":[
    {
       "from":"10060",             
       "phone":"+380XXXXXXXXX",   
       "category":"qwerty",       
       "sms_template":[           
         {"text":"Parol: "},  
         {"password":"2"},        
         {"text":"-"},
         {"password":"2"},
         {"text":"-"},
         {"password":"2"},
         {"text":"-"},
         {"password":"2"}
       ]
    }
  ]
}
В запрсое может быть передано более одного SMS-сообщения, т.е. в массиве otp_create может быть любое кол-во объектов
Данный пример может сгенерировать SMS со следующим текстом:
 Parol: 12-45-12-56
Обязательные поля:
phone - номер получателя в международном формате (пример: +380671234567)
Опцинальные поля:
from - Номер или альфаимя с которого будет доставлено SMS (по умолчанию 10060 или PrivatBank в зависимотси от страны назначения, возможность отправки от других имен должна согласовываться).
category - Идентификатор категории(группы) сообщений сервиса(мерчанта) инициировавшего отправку. Необязательный параметр. Категория используется как дополнительный идентификатор, не используйте если не понимаете зачем вам это.
pass_exp - Время жизни пароля в минутах. По умолчанию - 30 минут. Максимально возможное значение - 720 минут (12 часов).
sms_template - В случае отсутствия данного поля, текст СМС будет по-умолчанию "One-Time Password: ********", длинна пароля - 8 символов.

JSON Формат ответа при отправке пароля:
{
  "merchant_id":"13",
  "global_status":"ok",             
  "error_code":"Error1",            
  "error":"error description",      
  "otp_create":[
    {
       "package_status":"fail",     
       "phone":"+380969747359",     
       "error_code":"Error1",       
       "error":"error description"  
     }
   ]
}

**Comment by yevheniilazarev** [comment]
Для проверки этой доработки нужно обратиться к сервису по URL: https://test.e-gov.org.ua/wf-central/service/getDocumentAccess?nID_Access=N&sSecret=XYZ
Взять/добавить параметры можно из/в файла DocumentAccess.csv
Ожидаемый результат, если все ок

**Comment by udelis** [comment]
Протестировано. Status 200 OK
