### ISSUE TITLE
На главном портале, в подразделе "Мои документы" добавить кнопку "Добавить документ", для аплоада нового файла в качестве документа

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#321]
Реализация, как продолжение задачи: https://github.com/e-government-ua/i/issues/587

- [x] 1) Добавить основную кнопку "Загрузить документ"

- [x] 2) Перед кнопкой п.1 - добавить поле input с лэйблом: "Название документа"

- [x] 3) Перед полем п.2 добавить поле-элемент combobox с лэйблом: "Тип документа"
(подгружать туда список с сервиса getDocumentTypes, который уже используется в под-закладке "Поиск документов")

- [x] 4) Добавить новую колонку в таблицу списка документов, с эвтором "ЭЦП", и отображать там значение "под-элемента" - "fullName" из объекта, поля "oSignData" сущности Document,
Пример объекта oSignData:
{"state":"ok","customer":{"phone":"+380567161131","inn":"3578965412","email":"bankid@org.ua","fullName":"Тестувальник ПриватБанкID","addresses":[{"type":"factual","fullAddress":"49000, м. Дніпропетровськ, вул. Карла Маркса, 62"}],"signatureData":{"name":"АЦСК Держінформ'юсту","serialNumber":"2D24A7C930E2B7B404000000410D0000C2200000","timestamp":"05.08.2015 16:56:50","code":true,"desc":"ПІДПИС ВІРНИЙ","dateFrom":"04.08.2015 10:06:10","dateTo":"04.08.2017 10:06:10","sn":"UA-25287988-2015"},"organizations":[{"type":"edsOwner","name":"ПриватБанк","unit":"Регіональне відділення","mfo":"84369785","position":"керівник","ownerDesc":"Юридична особа","address":{"type":"factual","state":"Дніпропетровська","city":"Дніпропетровськ"}},{"type":"edsIsuer","name":"Держінформ'юст","unit":"Акредитований центр сертифікації ключів","address":{"type":"factual","city":"Київ"}}]}}

(при этом oSignData может и вовсе ничего не содержать.... например "{}")
(подгрузка данных в объект oSignData делалась через таску: https://github.com/e-government-ua/i/issues/588)

- [x] 5) по нажатию кнопки п.1 - сохранять документ в обычном хранилище (key-value), с учетом данных по п.2 и 3.

- При этом аплоадить через java-вский сервис "setDocumentFile"
- В параметрах указывать:
'sID_Subject_Upload': (sID_Subject самого того кто аплоадит (чей nID_Subject)), 
'sSubjectName_Upload': 'Я',
'sName': (п.2, из поля "Название документа"),
'nID_DocumentType':  (п.3, ИД-номер из поля "Тип документа"),
'sFileExtension' - расширение файла

ВАЖНО:
1. Частично это уже реализовано на портале (временно скрыто)!
(искать фразу: "Добавить документ" в файле /i/central-js/client/app/documents/content.html)

2. Полностью реализован другой, но подобный механизм аплоада!
Только при этом - в найденном образце аплоад происходит автоматом из сканов БанкИД, а нужно сделать именно по нажатию на кнопку, с вызовом диалога выбора файла с компьютера (кнопка уже даже есть).
- Искать в /i/central-js/client/app/* фразы:
"uploadFile" (пример вызова аплоада)
"uiUploader" (пример UI аплоада)
"file/directive" (пример директивы, вместо которой нужно написать другую)
"file-field" (пример использования директивы)
- Так-же искать в /i/central-js/server/* фразы:
"service/rest/file/upload_file_to_redis"

**Comment by bvv4ik** [comment]
временно приостановили, до появления возможности прикрепления цифровой подписи

**Comment by VadimGulich** [comment]
Задача реализована, файл загружается корректно , задачу закрываю 

- - - - - - - - - - - - - - - - 
Вопрос на будущее : 
Ограничения по загружаемым файлам будут дорабатываться ?
