### ISSUE TITLE
В дашборде, с права от каждого поля отображать иконку. при клике на которую содержимое поля должно копироваться в буфер обмена

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#334]
Подробнее (п.1):
https://docs.google.com/document/d/17UdmbdtqHvdlAKAUWWMk_gpu_CqFE8gfeaLVOPwCIcg/edit

![image](https://cloud.githubusercontent.com/assets/4208821/8087242/6d6d9f38-0fa2-11e5-9b03-31dd1e09488c.png)

**Comment by dmoskovsov** [comment]
Cделано.
