### ISSUE TITLE
На главном портале, в форме заполнения услуги гражданином, добавить авто-подгрузку сканов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#336]
если ИД поля начинается с "bankId_scan_" и при этом тип поля file, то:
1) скрывать такое поле (вместо отрисовки кнопки аплоада файла)
2) автоматически аплоадить в него скан из БанкИД, из того элемента, который по названию совпадает с продолжением названия поля, после слов "bankId_scan_"
3) делать это точно так-же как делается авто-аплоад сканов в Мои Документы, только метод использовать тот-же что и при обычном аплоаде гражданином файла, с сохранением в поле пришедшего ИД.

Например:
поле называется: "bankId_scan_passport"
значит скан нужно брать из поля "passport", обїекта, пришедшего по БанкИД

**Comment by AleksejDomash** [comment]
а что делать, если поле такое есть, а в банк айди такого поля нет ? оставлять обычным файлом ?

**Comment by bvv4ik** [comment]
да, просто оставлять стандартным полем подгрузки файла

**Comment by smit-pb** [comment]
А можно пример услуги и какой конкретно скан - должен подгружаться ? (паспорт? инн? ИЛИ ЧТО-ТО ДРУГОЕ)

**Comment by VadimGulich** [comment]
_test_mailer_ext   я так понял тут оно реализовано

**Comment by smit-pb** [comment]
![image](https://cloud.githubusercontent.com/assets/12965717/10011287/8cc0624e-6100-11e5-9dab-9bfe136ee9df.png)
Реализовано
