### ISSUE TITLE
Важно: в продакшене вы используете client_secret для bankid ТАКОЙ ЖЕ как записан в файле в репозитарии

### ISSUE THREAD

**Issue by aesteral** [e-government-ua/i#345]
Здравствуйте!

На данный момент e-gov.org.ua подвержен серьезной проблеме безопасности. Связана она с тем, что в продакшне используется такая же пара client_id / client_secret, что и в этом файле:

https://github.com/e-government-ua/i/blob/master/central-js/server/config.js

Что это значит?

Злоумышленник может обманом заставить жертву перейти по ссылке: 

https://bankid.privatbank.ua/DataAccessService/das/authorize?response_type=code&client_id=dniprorada&redirect_uri=https://evil.com 

(обратите внимание на redirect_uri) 

при переходе на которую жертве будет предложено пройти аутенфикацию на "портале государственных услуг". При этом параметр 'code' будет передан _стороннему сайту evil.com_.

Владелец сайта evil.com зная как client_id так и client_secret обладает всем необходимым, чтобы сформировать корректный запрос к https://bankid/DataAccessService/oauth/token?grant_type=authorization_code и получить _корректный_ access_token! С данным токеном злоумышленник имеет полный доступ к личной информации жертвы.

Что **необходимо сделать прямо сейчас**?

Выпустить новый client_id, client_secret

**Не хранить их на Github**

Отозвать все раннее выданные access_token

**сделать параметр redirect_uri фиксированным и не допускать его изменения**

**Comment by NikolayAngel** [comment]
Написал разработчикам, посмотрят

**Comment by Vanuan** [comment]
Риск не в том, что evil.com получит доступ к личной информации жертвы,
а в том, что evil.com будет посылать запросы от имени e-gov.org.ua.
Если client_secret не будет предоставлять особых привелегий владельцу ресурса (или будет выдаваться всем желающим реализовать в своем приложении авторизацию BankID), то единственный риск - введение пользователя в заблуждение: в поле "Сайт-одержувач" будет неверное значение "Портал державних послуг iGov.org.ua".

**Comment by aesteral** [comment]
Да, но, собственно, именно поэтому client_secret и имеет в названии _secret. Жертва не будет авторизовываться где попало, а на портале услуг - будет.

Таким образом, вы открывайте свой сайт чудесному миру фишинга, который будет неотличим от вашего настоящего сайта.

Как я вообще могу узнать, настоящий ли https://e-gov.org.ua/ или фишинговый, если уже сейчас адрес e-gov не совпадает с логотипом iGov и текстом на bankid?

**Comment by VadymVolos** [comment]
e-gov это старый домен, чтоб не путаться понаходите все недочеты и исправьте на домен https://igov.org.ua

**Comment by aesteral** [comment]
Видите, поскольку у вас открыт client_secret и не зафиксирован даже домен redirect_uri, я могу открыть сайт i-gov.org.ua и собирать персональные данные пользователей так, что даже самый продвинутый пользователь никогда не заметит подмены.

**Comment by bvv4ik** [comment]
@aesteral Спасибо за замечание,
уже все поправили, теперь секрет напрочь отсутствует в коде, и он другой!
