### ISSUE TITLE
Важно: в продакшне возможно скачивать чужие документы без авторизации

### ISSUE THREAD

**Issue by aesteral** [e-government-ua/i#348]
Здравствуйте!

Существует серьезная уязвимость раздела "Документи", которая позволяет третьим лицам скачивать копии документов (копии паспорта) без прохождения авторизации,

Как это происходит?

1. Вы проходите bankid-авторизацию в разделе "Документи"

2. Для вас отображается список ваших документов, для каждого из них формируется ссылка вида https://e-gov.org.ua/api/service/documents/download/{ID}

Где ID - четырехзначное число **со сквозной нумерацией**

При этом, злоумышленник может легко подобрать все такие числа и скачать с e-gov.org.ua все ранее загруженные туда документы - копии паспортов.

Обращаю внимание на то, что для такого доступа **не нужно** предоставлять через раздел документов "доступ третьей стороне".

Хорошие новости - доступ третьей стороне открыт всегда!

**Comment by aesteral** [comment]
Рекомендую подробнее изучить вопрос и способы решения тут:

https://www.owasp.org/index.php/Top_10_2010-A4-Insecure_Direct_Object_References

**Comment by aesteral** [comment]
Также обращаю ваше внимание на то, что подобные "баги" являются нарушением статьи 188-39 Кодекса Украины об административных правонарушениях: http://zakon2.rada.gov.ua/laws/show/80731-10/paran2619#n2619

> Недодержання встановленого законодавством про захист персональних даних порядку захисту персональних даних, що призвело до незаконного доступу до них або порушення прав суб’єкта персональних даних, -

> тягне за собою накладення штрафу на громадян від ста до п’ятисот неоподатковуваних мінімумів доходів громадян і на посадових осіб, громадян - суб’єктів підприємницької діяльності - від трьохсот до однієї тисячі неоподатковуваних мінімумів доходів громадян.

**Comment by hordesalik** [comment]
Да, такое я тоже находил. Нужно бы исправить и поставить подобные вопросы "hi priority"

**Comment by aesteral** [comment]
Вы это "находили" и выпустили в продакшн? О_О

**Comment by hordesalik** [comment]
собственно я ничего в продакшн не выпускаю. нашел вчера или позавчера и сейчас подтверждаю ваши слова )

**Comment by aesteral** [comment]
Простите, меня ваш тег "collaborator" ввел в сомнение.

**Comment by aesteral** [comment]
А, простите, не поправили, теперь можно скачать чужой паспорт, если ты авторизован под любым логином.

То есть, вы проходите авторизацию под своим именем, а потом скачиваете что угодно.

**Comment by ruzhovt** [comment]
Авторизация на сайте абсолютно неважна, вот скрипт для скачки сотни паспортов
curl -O "https://igov.org.ua/api/service/documents/download/[1-1000]"

**Comment by aesteral** [comment]
ruzhovt, без авторизации оно то работает, то нет. Кажется, зависит от домена e-gov или igov.

С авторизацией работает всегда.

**Comment by bvv4ik** [comment]
а Вы попробуйте скачат ьреально контент файла, плиз

**Comment by aesteral** [comment]
Прямо сейчас:

После авторизации:

- скачиваю свой документ: 0 байт

- другие документы: 0 байт

Ранее скачивалась копия документа.

**Comment by bvv4ik** [comment]
ну вот - никакого нарушения закона)

**Comment by aesteral** [comment]
Вы внесли изменения или оно сломалось?

Я определенно потерял возможность скачивать документ, который скачивался ранее.

**Comment by bvv4ik** [comment]
Вы можете сейчас стукнуть меня в скайп, плиз?*
belyavtsevw

**Comment by ruzhovt** [comment]
подвтерждаю. уже не качает. час назад скачало более сотни паспортов.

**Comment by aesteral** [comment]
Я вам писал сегодня. Логин как тут.
