### ISSUE TITLE
Раздел "документи" предлагает загрузку файлов с некорректными расширениями

### ISSUE THREAD

**Issue by aesteral** [e-government-ua/i#349]
При загрузке документов через https://e-gov.org.ua/api/service/documents/download/{ID} никаким образом не контролируется content-type, например при скачивании моего паспорта в файле в формате .jpg его было предложено скачать как passport.zip.

Необходимо, чтобы при скачиваний файлов им было подставлено корректное расширение файла.

**Comment by bvv4ik** [comment]
Для теста:
зайти под собой в мои документы и убедиться что загруженный и скачанный файл с соответствующим расширением

**Comment by VadimGulich** [comment]
Корректное расширение  получаем
Можно на боевой 
Тест проводил на : https://test.igov.org.ua/
