### ISSUE TITLE
Activiti - custom types for form elements

### ISSUE THREAD

**Issue by PavelKorchagin** [e-government-ua/i#35]
Реализовать поддержку кастомных типов в процессах активити согл. списка

https://docs.google.com/a/privatbank.ua/document/d/1LES8GhAvwqRKkwX2QUsRGksoI45vGbdiRCHJUzxjMXw/edit

**Comment by PavelKorchagin** [comment]
Паша, не хватает описания как поля отображаются в портале для граждан. (Show, hide, etc.)

**Comment by kurbpa** [comment]
Описание добавлено.

**Comment by taaraora** [comment]
Взял в работу.

**Comment by bvv4ik** [comment]
Спасибо, только я в документе дописал важный коммент:

bid_file
bid_string
email
Вместо этого нужно научиться маркировать как-то поля, например словами "BankID, checkEmail, checkEmailExist", чтоб эти маркеры были доступны после загрузки формы

ну а тип label всеже нужен

**Comment by taaraora** [comment]
Тип label, я уже сделал, правда ещё не разобрался как закомитить следуя всем процедурам по документу https://github.com/e-government-ua/i/blob/master/CONTRIBUTING.md
на основании чего будет добавляться маркер? Правильно ли я понимаю, что этот маркер должен выглядеть примерно как тэг milestone ишшы на github? 
![image](https://cloud.githubusercontent.com/assets/2936828/7686825/525ee4f8-fda1-11e4-85bf-6707119331aa.png)

**Comment by bvv4ik** [comment]
"Тип label, я уже сделал правда ещё не разобрался как закомитить следуя всем процедурам по документу https://github.com/e-government-ua/i/blob/master/CONTRIBUTING.md"

Отлично, не надо по тому доку, просто пройдись по нашей прошурке: https://github.com/e-government-ua/i/wiki/%D0%9A%D0%B0%D0%BA-%D0%BD%D0%B0%D1%87%D0%B0%D1%82%D1%8C-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%83

выливать нужно в ветку тест!
только обязательно убедитесь что после этого ничего не поламалось, и в течении 3-х минут собравшиеся билды не выдали в слак ошибку (deploy)
https://e-government-ua.slack.com/messages/deploy/details/

Или пройдясь по сайтам:
https://e-gov.org.ua - главный портал для граждан
https://test.e-gov.org.ua - портал для граждан (как завершится полностью главный портал - этот будет убран)
https://test.e-gov.org.ua/admin-activiti - админка (родная Активити) - для чиновника (логин: dn310780bvv пароль: 123)
https://test.e-gov.org.ua/admin - админка (свой дашбоард) - для чиновника

В данном случае важней выбрать услугу на https://test.e-gov.org.ua и полностью заполнить форму.
Для BankID можно использовать:
логин: +380102030405
пароль: value
SMS: 123456



"на основании чего будет добавляться маркер? "
это должно где-то добавляться в самом бизнеспроцессе(схеме), только желательо не отдельным параметром а в каком-то стандартном поле... может есть там какое-то поле формата...


"Правильно ли я понимаю, что этот маркер должен выглядеть примерно как тэг milestone ишшы на github? "
Не совсем, этот маркер/маркеры с полем нужны для того,чтоб на клиенте проводить специфическую валидацию или особую обработку поля.
При том, нужно понимать, что у нас самописный фронт, и тут нам это нужно именно для того чтоб его реализовать гибким(активити-эксплорер вообще не используем для граждан и чиновников)

**Comment by taaraora** [comment]
Я думал, что будет использоваться родной Activiti Explorer. Основной проблемой создания label - кастомного типа для формы, было - написать рендерер на основе ui элементов vaadin, который отображал бы текст в окне Activity Explorer.
Правильно ли я понимаю требования к кастомному типу label:
1) Должен отображаться в родном Activity Explorer.
2) Должен быть различим при REST запросах с помощью "маркера" (как я прочёл при получении информации о таске через REST, получаемый JSON содержит информацию о форме расположенной на таске и конкретно описание каждого поля формы: его тип значение и т. д.)

Требования к "маркерам":
1) Поля форм (даже если это поля одного типа например label, string и т. д.) должны быть различимы по определённому маркеру, который принимает следующие значения:  "BankID, checkEmail, checkEmailExist..." маркер должен передаваться как часть REST-ответа.

**Comment by bvv4ik** [comment]
"Я думал, что будет использоваться родной Activiti Explorer. Основной проблемой создания label - кастомного типа для формы, было - написать рендерер на основе ui элементов vaadin, который отображал бы текст в окне Activity Explorer."

label будет использоваться ActivitiExplorer, и это, наверно или последний или один из самых последних "кастомных типов", которые нам придется реализовывать...
Но акцент мы теперь делаем исключительно на самописный фронт, и именно потому нужно реализовать механизм маркеров, которые позволят при одном и том-же типе поля вести себя на фронте несколько по разному(в частности по валидации данных или подтязивания их, например по БанкИД)

"Правильно ли я понимаю требования к кастомному типу label:
1) Должен отображаться в родном Activity Explorer.
2) Должен быть различим при REST запросах с помощью "маркера" (как я прочёл при получении информации о таске через REST, получаемый JSON содержит информацию о форме расположенной на таске и конкретно описание каждого поля формы: его тип значение и т. д.)"

1) да
2) сам тип(например label), как и раньше будет различим по самому элементу "type". Только нужно еще найти место, смежное с полем, чтоб там можно было изначально в БизнесПроцессе перечислять "слова-маркеры", которые будут давать важную дополнительную информацию на самописный фронтэнд, который в зависимости от нее будет несколько по разному работать с данными этого поля... при том не на столько различно, чтоб при этом стало невозможным, без этой логики(на самописном фронте) работать с этим полем в АктивитиЭксплорере... ну, не будет валидации, ну не критично... Ведь Активити эксплорер будет использоваться, по сути, только уже самими разработчиками. а для обычных людей фронт самописный.


"Требования к "маркерам":
1) Поля форм (даже если это поля одного типа например label, string и т. д.) должны быть различимы по определённому маркеру, который принимает следующие значения: "BankID, checkEmail, checkEmailExist..." маркер должен передаваться как часть REST-ответа."

Да, и этих маркеров в одном поле может быть несколько, перечисляться они могут через запятую.

2) Должна быть простая возможность добавлять/править эти маркеры в редакторе БизнесПроцесса (чтоб бизнес-аналитики могли их прописывать в БП без "танцев с бубном")

еще, желательно(но не обязательно) реализовать участок в бэке Активити(как пример), который-бы просто вычитывал этот список маркеров для каждого поля, и логировал его(так мы в будущем смогли-бы прикрутить туда юнит-тесты и другие тесты)

**Comment by taaraora** [comment]
По поводу маркеров. На данный момент поэкспериментировав с process definition xml, сразу пришлось отсечь варианты добавления маркеров в поля expressions, в проперти value для не enum типов филдов формы. Не получится легко получать маркеры по REST из таблцы в которой хранится информация о process definitions.
Так же требование:
> (чтоб бизнес-аналитики могли их прописывать в БП без "танцев с бубном").

ограничивает нас тем набором полей которое на данный момент поддерживает Activiti Designer при редактировании формы/таски.
На данный момент вижу два основных пути решения задачи:
1. Готовое решение. Каждая форма, полям которой нужно добавлять маркеры, имеет отношение с user task 1:1. Мы можем воспользоваться user task. В user task есть поле Documentation которое предназначено для добавления описания к таске. По xsd схеме, любой элемент  BPMN 2.0 может содержать вложенный блок Documentation, он является опциональным, и может быть использован для добавления комментария к элементу. Мы можем использовать его для добавления туда своих маркеров, например в виде некой строки: "text:marker1, testlabel:marker22, duedate:marker1, decision:marker112". Я проверил в таком же виде элемент Documentation выдаст строку при REST ответе (я запрашивал таску по id):
> {"id":"126",
"url":"http://localhost:8080/service/runtime/tasks/126",
"owner":null,
"assignee":"kermit",
"delegationState":null,
"name":"╨Ю╨▒╤А╨░╨▒╨╛╤В╨║╨░",
"description":"text:marker1, testlabel:marker22, duedate:marker1, decision:marker112",
...

2. Исходный код Activiti Designer и Activiti BPM открыт (я проверил), а занчит, мы можем расширить схему нужными элементами/свойствами, дописать классы которые парсят xml. Дописать eclipse плагин , чтобы он начал поддерживать наши кастомные поля. Это более архитекутрно правильный подход, но он потребует больше усилий чем первый. В любом случае я готов за него взяться, если первый вариант не устроит и альтернатив не найдём.

**Comment by bvv4ik** [comment]
Все ясно!
п.1. полностью нам подходит ,с учетом имеющихся ограничений!
Если учесть, что потенциально со временем мы смогли-бы реализовать и свой вариант дизайнера БП, то это-бы в будущем и позволило полностью "убрать танцы с бубном для бизнес-аналитиков", при простановки маркеров!

Прошу тогда:
1) убедиться, что при текущей работе на порталах, при заполнении форм - это поле "description" всегда передается порталу, и если не передается - указать на то, что нужно изменить в запросе, чтоб выдавалось (в виде отдельного задания на комманду центрального портала "Portal-Dashboard_NodeJS-Java"
2) убедиться, пообщавшись с Павлом Курбацким (kurbpa), что:
1) поле дескрипшин не используется сейчас
2) не будет использоваться для других нужд
3) есть штатная возможность его заполнения бизнес-аналитиками в дизайнере БП

**Comment by taaraora** [comment]
Проверил:
1) https://test.e-gov.org.ua/admin все 4 таски были получены как REST ответ и содержат: \"description\":null, 
2) https://poligon.e-gov.org.ua и https://test.e-gov.org.ua используют другой API.

**Comment by taaraora** [comment]
По итогам разговора, решили сделать отдельный тип, похожий на Label, который будет содержать key:value значения с маркерами для полей формы. Решение было принято, для того, чтобы получать информацию о маркерах при получении формы, а не списка тасок.
