### ISSUE TITLE
Вы нарушаете положения Закона Украины 2297-17 "Про захист персональних даних"

### ISSUE THREAD

**Issue by aesteral** [e-government-ua/i#350]
Ресурс e-gov.org.ua серьезно нарушает положения Закона Украины 2297-17 "Про захист персональних даних", а именно:

Согласно закона,

> обробка персональних даних - будь-яка дія або сукупність дій, таких як збирання, реєстрація, накопичення, зберігання, адаптування, зміна, поновлення, використання і поширення (розповсюдження, реалізація, передача), знеособлення, знищення персональних даних, у тому числі з використанням інформаційних (автоматизованих) систем;

> одержувач - фізична чи юридична особа, якій надаються персональні дані, у тому числі третя особа;

> персональні дані - відомості чи сукупність відомостей про фізичну особу, яка ідентифікована або може бути конкретно ідентифікована;

> розпорядник персональних даних - фізична чи юридична особа, якій володільцем персональних даних або законом надано право обробляти ці дані від імені володільця;

Таким образом, сайт e-gov.org.ua занимается сбором и обработкой персональных данных, следовательно, согласно статьи 8 Закона вы обязаны предоставить:

> джерела збирання, місцезнаходження персональних даних, мету їх обробки, місцезнаходження або місце проживання (перебування) володільця чи розпорядника персональних даних або дати відповідне доручення щодо отримання цієї інформації уповноваженим ним особам, крім випадків, встановлених законом;

> інформацію про умови надання доступу до персональних даних, зокрема інформацію про третіх осіб, яким передаються персональні дані;

> про механізм автоматичної обробки персональних даних;

вы обязаны получить: **згоду суб’єкта персональних даних на обробку його персональних даних;**, 

А также: обеспечить прием запросов на прекращение обработки персональных данных, на их изменение и уничтожение.

Обеспечить защиту персональных данных согласно статье 24 Закона.

Обращаю ваше внимание, что в случае несоблюдения данного закона вы можете **понести ответственность** за правонарушения предусмотренные как Кодексом об административных правонарушениях (статья 188-39), так и Уголовным кодексом (статья 182).

**Comment by Vanuan** [comment]
А когда вы в Dropbox заливаете скан паспорта, вы тоже галочку требуете?

**Comment by aesteral** [comment]
Вы работает в украинской юрисдикции и соблюдаете украинское законодательство. Мне это кажется очевидным.

Например, в Британии я езжу по левой стороне, а в Украине - нет.

**Comment by aesteral** [comment]
И, кстати, обращаю ваше внимание на то, что с Дропбоксом у меня есть соглашение об использовании, в котором указано, какие данные они собирают и как обрабатывают. С которым я соглашаюсь, поставив галочку:

https://www.dropbox.com/terms#terms

https://www.dropbox.com/terms#privacy

И в нем, кстати, указаны реквизиты для связи в случае возникновения вопросов, связанных с персональными данными: privacy@dropbox.com

**Comment by Vanuan** [comment]
Лично я ничего не нарушаю. Я являюсь таким же пользователем, как и вы.

**Comment by Vanuan** [comment]
Прошу прощения за переход на личности

**Comment by aesteral** [comment]
Простите, пожалуйста, поскольку на igov даже нет информации о его распорядителе, то я даже не могу узнать, кто за него несет ответственность :(

А у вас аватарка есть, вы очень солидно выглядите.

**Comment by snaki4** [comment]
Помоєму це дуже просто рішити (як роблять у всому світі) галочкою "accept Terms & ... " при реєстрації.

**Comment by aesteral** [comment]
Дело не в галочке.

Необходимо написать эти самые Terms в соответствии с Законом и включить в них предусмотренную законом информацию, а именно:

> джерела збирання, місцезнаходження персональних даних, мету їх обробки, місцезнаходження або місце проживання (перебування) володільця чи розпорядника персональних даних або дати відповідне доручення щодо отримання цієї інформації уповноваженим ним особам, крім випадків, встановлених законом;

> інформацію про умови надання доступу до персональних даних, зокрема інформацію про третіх осіб, яким передаються персональні дані;

> про механізм автоматичної обробки персональних даних;

И, главное, информацию о юридическом или физическом лице, осуществляющем сбор и обработку информации и информацию о порядке **подачи запросов на прекращение обработки персональных данных, на их изменение и уничтожение** и их **выполнение**

Кроме того, галочка не решит проблему нарушения статьи 24 и КоАП, описывающих требований к защите персональных данных (см #348).

**Comment by dutchakdev** [comment]
Нет распорядителя, распорядители - волонтеры. Если у вас есть предложения, вы можете помочь создать нам пользовательское соглашения и организовать поддержку в данном направлении. Где хранится разного рода информация - это данные открытые их никто не скрывал, кстати.

**Comment by Vanuan** [comment]
Кстати, про ответственность. В Украине ее несет тот, кто обнаружил уязвимость :(
http://ain.ua/2015/04/03/573414

**Comment by Vanuan** [comment]
А регистрация и сессии пока не реализованы.

**Comment by aesteral** [comment]
Значит вам следует определить одного из волонтеров как ответственное лицо и указать его.

> Если у вас есть предложения, вы можете помочь создать нам пользовательское соглашения и организовать поддержку в данном направлении. 

Э, нет, я хочу узнать, наконец, **кому мне написать, чтобы мой паспорт удалили наконец**. Кроме прокуратуры.

> Где хранится разного рода информация - это данные открытые их никто не скрывал, кстати.

Окей, давайте:

> знати про джерела збирання, **місцезнаходження своїх персональних даних**, мету їх обробки, **місцезнаходження або місце проживання (перебування) володільця чи розпорядника персональних даних** або дати відповідне доручення щодо отримання цієї інформації уповноваженим ним особам, крім випадків, встановлених законом;

Где я могу прочитать эту открытую информацию?

> пред’являти вмотивовану вимогу володільцю персональних даних із запереченням проти обробки своїх персональних даних;

Куда мне предъявить, наконец, эту вимогу? Волонтерам? Дубилету? В суд? По мобильнику господина Белявцева, который я нашел тут в комментах? В УМВС по Одесской области?

**Comment by Vanuan** [comment]
Я думаю, надо писать на info@bankid.org.ua

**Comment by aesteral** [comment]
Как они связаны с egov / i-gov?

**Comment by dutchakdev** [comment]
Что давайте? Гляньте логи работы над проектами, там все есть где и как хранится, я вам спорт чтоле? :) У нас нет и не может быть ответственного так как это будет централизацией а это плохо. Если нужно удалить данную информацию мы можем это обсудить со всеми и сделать.

**Comment by Vanuan** [comment]
Скан паспорта вы сами загружали на портал?

**Comment by bvv4ik** [comment]
Полагаю, вчера инцедент был исчерпан,
по поводу "пользовательского соглашения" - согласен, разумно. Постараемся найти свободное время и для таких "формальностей"(как только с первой волной замечаний справимся)... хотя по формальностям у нас, конечно-же больший "специалист"- государство... Понаделало их столько и такого качества, что жизни нет... от и приходится гражданам "взваливать на свои плечи этот труд"... А если так придираться скурпулезно ко всему, то все захлохнет и не начавшись( 

П.С.: в других нормальных цивилизованных странах, огромное количество инфы, которую мы тут "законами защищаем" - принципиально открыта свободно всем подряд! Хотя, закон, конечно-же, наш нацинальный, соблюдать нужно! С этим ни кто не спорит...
