### ISSUE TITLE
Раздел "документи": невозможно предоставить доступ третьим лицам не указав необязательный параметр e-mail

### ISSUE THREAD

**Issue by aesteral** [e-government-ua/i#351]
При попытке использовать функцию "Надати доступ до електронного документу третій особі", заполнив только поля "ім’я та прізвище" и "номер її мобільного телефону", оставив необязательно поле "e-mail" пустым, получаю ошибку BUSINESS_ERR: required String parameter 'sMail' is not present.

**Comment by bvv4ik** [comment]
предоставление доступа, к сожалению, еще не до-реализовано... и в т.ч. уведомления об обязательности полей.

сообщение об этом обязательно добавим!
