### ISSUE TITLE
Реализовать кеш для "горячих" методов rest сервисов.

### ISSUE THREAD

**Issue by brunneng** [e-government-ua/i#353]
Была обнаружена проблема с быстродействием метода getServicesTree. Дело в том что хибернету приходится за раз вытаскивать много данных. Поскольку данные меняются редко, это можно пофиксить добавлением кеша на уровне метода рест сервиса. В данной задаче необходимо реализовать такой кеш для метода getServicesTree а так же возможность легкого добавления кеширования для других методов.

**Comment by brunneng** [comment]
Сделал, что можно добавлять кеширование на спринговые бины с помощью аннотации @EnableCaching. Единственная загвоздка, что оно не работает для рест контроллеров.. Каким то образом при запросе на контроллер обходится проскя бина контоллера которая добавляет кеш (сама прокся создается, проверял в дебаге)..  Если кому то охота поковыряться с этим - милости прошу. И вторая причина почему нельзя это сделать для рест конроллера - это потому что возвращаемый результат ResponseEntity - спринговая сущность которая 1) не сериализуемая, 2) не имеет конструктора без аргументов, поэтому в Ehcache её положить не получится.. 
Поэтому пришлось добавить специальный CachedInvocationBean и через него делать вызов.

**Comment by bvv4ik** [comment]
Готово! Спасибо!
