### ISSUE TITLE
Доступна информация о загруженных файлах без авторизации

### ISSUE THREAD

**Issue by denisdnu** [e-government-ua/i#356]
По адресу https://igov.org.ua/api/service/documents/?nID_Subject={ID} доступна информация о загруженных файлах пользователя без авторизации, где ID - целочисленный идентификатор, изменяя который в большую или меньшую сторону мы можем получить информацию о загруженных файлах других пользователей, что архитектурно неверно. Данная информация должна возвращаться только при наличии авторизованной сессии и только по тем ID, к которым имеет доступ пользователь, в противном случае должна возвращаться ошибка или пустой ответ.

**Comment by bvv4ik** [comment]
сам контент не доступен, потому от самого списка - толку "ноль"...

но, это тоже будет ограничено, как только разделаемся с первой волной замечаний)

Спасибо!
