### ISSUE TITLE
Выдача доступа третьему лицу для любого электронного документа

### ISSUE THREAD

**Issue by denisdnu** [e-government-ua/i#357]
Потенциально возможна выдача доступа третьему лицу для любого электронного документа без авторизации.
При оформлении доступа к электронному документу для третьего лица формируется GET запрос вида https://igov.org.ua/api/service/documents/{ID}/share?nID_Document={nID_Document}&nID_Subject={nID_Subject}&nMS={nMS}&sFIO={sFIO}&sMail={sMail}&sTarget=&sTelephone={sTelephone}
Запрос возвращает ответ вида {"name":"sURL","value":"https://igov.org.ua/index#nID_Access=1&sSecret={sSecret}"}
При изменении таких целочисленных параметров, как ID, nID_Document, nID_Subject, всё равно происходит генерация ссылки доступа даже без наличия авторизованной сессии, что архитектурно неверно. Ссылка должна генерироваться только при наличии авторизованной сессии и только к тем документам, к которым имеет доступ пользователь, в противном случае должна возвращаться ошибка или пустой ответ.

**Comment by bvv4ik** [comment]
за это не переживайте) 
реально пока ни кому ни какой доступ не выдается... конечно-же защита на сервере будет от этого... но ее включат уже когда завершат разработку, чтоб удобно было тестировать.

А за внимательность и обращение - спасибо!
Только, порошу. если действительно в будущем таки что-то реальное обнаружите на портале из небезопасного - лучше напрямую обращайтесь в скайп: belyavtsevw
или bvv4ik@gmail.com
т.к. это Вы честный человек. и Вам важно сообщить об этом всему миру, как можно скорее... а есть другие, которые увидев Ваш пост начнут "без зазрения совести" пользоваться им в своих корыстных целях!

Спасибо!

**Comment by denisdnu** [comment]
Просто хочу обратить внимание на систематичность таких ошибок, и то, что их нужно устранять не локально, а на уровне  архитектуры.

**Comment by bvv4ik** [comment]
как раз на уровне архитектуры они и устраняются) тут можете быть спокойны!

проверка. на самом деле, на стороне бэка и их связки осуществляется... просто многое было не прикрученно именно для удобства тестирования при разработке... и как это бывает, иногда, таковым и осталось при сливании в продакшин...
