### ISSUE TITLE
На главном портале реализовать сессию на NodeJS, для сохранения авторизации и безопасности

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#359]
-всегда генерить сессию исключительно по результатам авторизации в БанкИД, и получения ИНН-а
-всегда ,при генерации сессии использовать syncSubject, с передачей туда полученного ИНН-а, получением nID_Subject в ответ и сохранением его в созданную сессию
-всегда передавать во всех методах на бэк явы - параметр nID_Subject

Дополнительно:
Сделать так, чтобы сессия держалась, и если зашел через BankID в одном месте, то в другом оно уже не просит зайти. (например в Моих Документах и Журнале или Услуге)
При этом кэшировать загруженные данные с БанкИД в памяти (на клиенте)

**Comment by bvv4ik** [comment]
для теста нужно убедиться, что все вызовы ява-сервисов содержат nID_Subject, который не получится подменить на клиенте Ноды.

посмотреть это можно в логах сервера poligon.igov.org.ua

**Comment by VadimGulich** [comment]
Какое время жизни сессии должно быть ? 

При авторизации через  БанкИД  при заказа заявки в Услуге , для повторной заявки услуги запрашивает тоже авторизацию через БанкИД .

**Comment by bvv4ik** [comment]
это реализовано так:
если хоть где-то авторизовался, то в мои документы и журнал будет пускать (должно пускать)
при заходе в услугу - будет требовать авторизацию всегда

**Comment by VadimGulich** [comment]
Задача реализована и работает корректно 
Уточните , пож-ста , время жизни сессии и должна ли она автоматически продлеваться при работе с меню "Мои документы" , "Меню" ?
