### ISSUE TITLE
На главном портале сделать страничку с полем sID_BusinessKey процеса и nID_ServiceData, чтобы можно было смотреть статус заявки

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#36]
по этим ИД можно будет понять на каком региональном сервере оно находжится и там проверить ее статус (через стандартные сервисы Активити)

**Comment by AleksejDomash** [comment]
По этому номер можно слать запрос на получение статуса процеса.  Я сделал вызов pop-up окна, когда заявка успешно подана, в нем написан номер заявки (businessKey). Ссылка на рест http://www.activiti.org/userguide/#_rest_api,  раздел 15.5.5. List of process instances

**Comment by bvv4ik** [comment]
логично сделать еще один СервисТаск, который выполняется сразу после поступления заявки, и который будет "заявителю" слать сразу письмо со ссылкой(на эту страницу), в которой будет заложен и этот ИД, таким образом он сможет из пришедшего ему письма всегда быстро посмотреть текущий статус его заявки.

**Comment by AleksejDomash** [comment]
Я думаю это должна быть отдельная задача

**Comment by bvv4ik** [comment]
согласен

**Comment by PavelKorchagin** [comment]
Сейчас Паша Курбацкий делает док. По дизайну админки. Через рест. Стандартный я бы внешнему миру не давал доступ. Сделал канал #wf-design и всех пригласил туда.

**Comment by bvv4ik** [comment]
не актуально, т.к. решили все в журнале протоколировать, на главном портале
