### ISSUE TITLE
На бэке Явы, при использовании метода getDocumentFile ОБЯЗАТЕЛЬНО отдавать корректное расширение файла, беря его из хеадера, а не прописывая захардкоденное расширение ".zip"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#360]

**Comment by bvv4ik** [comment]
для теста:
зайти на полигон под собой в Мои документы,
и убедиться, что скачивается файл с нормальным расширением а не ".zip.zip"

**Comment by VadimGulich** [comment]
Тестирование проведено на : https://poligon.igov.org.ua
- Проверена возможность скачивания/просмотра скачанного документа :  файл скачивается с нормальным расширением 
- Проверена возможность скачивания чужих документов : нет возможности получения чужих документов.

Можно выставлять на боевой!
