### ISSUE TITLE
Вынести логин/пароль по basic-authorization в проперти из *context*.xml

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#365]

**Comment by bvv4ik** [comment]
для теста:
1) убедиться, что при прямом обращении к сервисам явы на центральном и региональном сервере - без авторизации не пускает! (например: на центральном https://poligon.igov.org.ua/wf-central/service/services/getServicesTree а на региональном https://test.igov.org.ua/wf-region/service/repository/process-definations)
2) что если заменить на центральном и региональном серверах:
/sybase/.configs/wf/AS.properties
параметры:
general.auth.login=activiti-master
general.auth.password=UjhtJnEvf!
и передеплоить (https://jenkins.igov.org.ua/view/new/job/central_alpha/ и https://jenkins.igov.org.ua/view/new/job/regional-alpha/)
то будет требовать и на региональном и на центральном серверах именно эти новые авторизационные данные

**Comment by admiral-diver** [comment]
Выполнено
