### ISSUE TITLE
Создать еще одну бетта-тестовую среду тестирования

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#368]
1) Разместить все на машине "dniprorada.igov.org.ua" !!!

2) скопировать джобы со старых: "central_alpha" и "regional-alpha"
в новые, с названиями: "central_beta" и "regional-beta"
и настроить на ветку "test-version" (сама ветка создана)
с обязательным настроем авто-деплоя при пуше туда

3) Полный набор приложений cо своими поддоменами:
test-version.igov.org.ua - central-js
test-version.igov.org.ua/admin - wf-central
test-version.region.igov.org.ua - portal-php (ПОКА МОЖНО НЕ СТАВИТЬ!!!)
test-version.region.igov.org.ua/admin - dashboard-js
test-version.region.igov.org.ua/admin-activiti - wf-region
(скопировать с приложений, на которые ссылаются джобы "central_alpha" и "regional-alpha", включая содержимое папок /sybase/.configs/)

4) отдельные схемы на тестовой базе:
jdbc:postgresql://pg.igov.org.ua:5432/test-version-central
(скопировать с jdbc:postgresql://pg.igov.org.ua:5432/central_p)
jdbc:postgresql://pg.igov.org.ua:5432/test-version-region
(скопировать с jdbc.url=jdbc:postgresql://pg.igov.org.ua:5432/govr_p)

5) проставить все сертификаты на приложения
и открыть все нужные порты, как на остальных полигонах

**Comment by creativie** [comment]
по №3 прошу уточнить IP-адреса/имена к которым нужно биндить новые поддомены

**Comment by bvv4ik** [comment]
"Я так понимаю что все поддомены будут смотреть на dniprorada.igov.org.ua, верно?"
да

**Comment by creativie** [comment]
DNS done.

**Comment by bvv4ik** [comment]
а что осталось?

**Comment by bvv4ik** [comment]
для тестеров:
должна быть полноценная среда тестирования, но пока без PHP-портала (он пока не нужен)
и мертификаты вроде должны быть в понедельник...

**Comment by staiki** [comment]
Здравстуйте. На https://test-version.igov.org.ua/ ничего не открывается. Крутит колесо и всё. Ещё не работает?

**Comment by bvv4ik** [comment]
Здравствуйте,
да, там до сих пор проблема с развертыванием приложения
занимаемся...

**Comment by bvv4ik** [comment]
Для теста:
просто зайти на сервера и убедиться что на них также все работает

**Comment by VadimGulich** [comment]
Все работает корректно

**Comment by staiki** [comment]
На тестовой под новым браузером Edge от майкрософта требует сертификат.

**Comment by bvv4ik** [comment]
сертификаты еще доставляют... это процесс еще должен занять пару дней...
