### ISSUE TITLE
На главном портале, в на странице “Все услуги” исправить форматирование и стили

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#369]
Страница “Все услуги”
https://igov.org.ua/subcategory/1/3
- [x] 1) выводить услуги не таблицей, а так же ИМЕННО колонками, как на стартовой! (а не таблицей)
- [x] 2) название раздела сделать таким же шрифтом, как на стартовой странице название подкатегории
- [x] 3) левый край - по одной линии с логотипом

**Comment by bvv4ik** [comment]
Для теста:
просто пройти по ссылке в задаче и визуально убедиться

**Comment by OlgaKotova** [comment]
1) вот эти 2 пункта прошли тест 
-название раздела сделать таким же шрифтом, как на стартовой странице название подкатегории
-левый край - по одной линии с логотипом

1) на счет первого пункта:
при выборе подпункта “Міліція та ДАІ”, например, выводится этот подраздел с именем “Міліція та ДАІ”, но в нем отображены все услуги раздела “Громадянам”, а так же вывод услуг осуществляется таблицей, как я поняла.
Вот мувик http://screencast.com/t/e2viI5f2Fd9

**Comment by poremchuk** [comment]
Мій недолік. Друзі, поставте у вибірці властивість субкатегорії. На разі немає фізичної можливості виправити.

Дивитись можна сюди - central-js\client\app\service\subcategory\subcategory.html

**Comment by OlgaKotova** [comment]
@poremchuk 
еще в дополнение к предыдущему комменту:
ситуация, описаная в п.2 повторяется и для раздела "Бізнесу". 
так же, для этого раздела нашла баг - когда открываешь любой из подразделов, например "Бізнесу: Будівництво, нерухомість, земля", страница открывается не сверху(т.е. немного проскролена вниз) см. http://screencast.com/t/Y4h4eHtDQur 

что с ним делать? завести новую issue или тут оставить для фикса?

**Comment by bvv4ik** [comment]
"что с ним делать? завести новую issue или тут оставить для фикса?"
нового не надо, просто ждем правок по этой таске...

**Comment by OlgaKotova** [comment]
@bvv4ik 
спасибо, только что закрыла эту issue, все-таки ее завели в трекер )

Подскажите пжл, кто-то займется исправлением по этому комментарию?
2) на счет первого пункта:
при выборе подпункта “Міліція та ДАІ”, например, выводится этот подраздел с именем “Міліція та ДАІ”, но в нем отображены все услуги раздела “Громадянам”, а так же вывод услуг осуществляется таблицей, как я поняла.
Вот мувик http://screencast.com/t/e2viI5f2Fd9

@poremchuk писал, что в даный момент не может пофиксить, но написал, что необходимо сделать:
Друзі, поставте у вибірці властивість субкатегорії. На разі немає фізичної можливості виправити.
Дивитись можна сюди - central-js\client\app\service\subcategory\subcategory.html

**Comment by bvv4ik** [comment]
@poremchuk надеюсь, на этих выходных таки получится дочинить

**Comment by poremchuk** [comment]
Повернув по субкатегоріям як і було. Розібратись як розкидати по колонках items так як звучить у завданні я не зміг.

**Comment by rostag** [comment]
За годину-дві завершую свій поточний таск, а тоді спробую взятися за цей.

**Comment by poremchuk** [comment]
Дякую.

**Comment by rostag** [comment]
@OlgaKotova - наскільки я бачу, вимоги завдання було виконано. Конкретно про це:

а) При выборе подпункта “Міліція та ДАІ”, например, выводится этот подраздел с именем “Міліція та ДАІ”, но в нем отображены все услуги раздела “Громадянам”, 

— зараз відображаються тільки послуги "Міліція та ДАІ", тобто правильно.

б) а так же вывод услуг осуществляется таблицей, как я поняла.

— мабуть, тут мається на увазі те, що елементи виводяться у порядку "зліва направо та згори донизу", а хотілося б "згори донизу та зліва направо"

Ілюстрація зміни:

![image](https://cloud.githubusercontent.com/assets/451410/8891080/38339e0a-3322-11e5-91e0-b4ba6b8d8baa.png)

 — так, @bvv4ik ?

**Comment by OlgaKotova** [comment]
@rostag @bvv4ik Перечень услуг в категории соответствует названию категории - исправлено. Осталось решить последний вопрос с выводом услуг, как их все-таки выводить? Если как на верхнем скрине, который оставил Ростислав, то можно закрывать.

**Comment by rostag** [comment]
Ольго, нагорі я показав перелік послуг саме так, як він є зараз, а нижня
картинка - це те, що, як я припускати, ми хотіли б зробити.

2015-07-27 9:29 GMT+03:00 Olga <notifications@github.com>:

> @rostag <https://github.com/rostag> @bvv4ik <https://github.com/bvv4ik>
> Перечень услуг в категории соответствует названию категории - исправлено.
> Осталось решить последний вопрос с выводом услуг, как их все-таки выводить?
> Если как на верхнем скрине, который оставил Ростислав, то можно закрывать.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/i/issues/369#issuecomment-125102142>.
>



-- 

Рост
http://fpug.org.ua
http://flash-ripper.com
facebook.com/rastislavr
+38 050 406 03 96
rostislav.siryk@gmail.com

**Comment by bvv4ik** [comment]
так, @bvv4ik ?

@rostag - да, совершенно верно...
к сожалению разработчик так и не смог справиться с задачей.
остается надежда, что кто-то таки наберется сил и поборет таску

**Comment by OlgaKotova** [comment]
@bvv4ik может тогда закрыть эту таску и открыть новую, которая решает задачу отображения списка услуг?

**Comment by bvv4ik** [comment]
не стоит, пусть остается эта

**Comment by VadimGulich** [comment]
баги исправили ?

**Comment by uazure** [comment]
Сделал три колонки на страничке подкатегорий, добавил сортировку по имени после сортировки по статусу услуги (готова, не готова)

**Comment by OlgaKotova** [comment]
Вывод услуг исправлен.
Коллеги, скажите, пжл(может я что-то пропустила), на главной странице на https://test.igov.org.ua, перед названием которых отображается "_", как на скрине https://test.igov.org.ua . Все так и должно быть или это нужно исправить?

**Comment by bvv4ik** [comment]
так и должно быть)
так помечаются тестовые или скрытые услуги - их на боевом будет не видно

**Comment by OlgaKotova** [comment]
Хорошо, тогда закрываем, наконец-то ))
