### ISSUE TITLE
Activity - Авторизация REST API через токены BankID

### ISSUE THREAD

**Issue by admiral-diver** [e-government-ua/i#37]
Реализовать согласно бизнес процессу предоставленному в приложении

Сценарий: https://www.gliffy.com/go/publish/7853145

![rest api auth](https://cloud.githubusercontent.com/assets/7460582/7035163/b7e8c8b2-dd8e-11e4-96dd-0466cae88c46.png)

**Comment by bvv4ik** [comment]
@zora-borys я так понимаю - таска готова,
только прошу написать в комменте - как ее можно протестировать?

**Comment by VadimGulich** [comment]
я так понимаю задача давно уже реализована и функционал работает , закрываю
