### ISSUE TITLE
На главном портале, при заполнении формы, помечать красной звездочкой все поля, обязательные к заполнению

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#370]

**Comment by bvv4ik** [comment]
Для теста:
зайти в услугу "Надання довідки про відсутність або наявніть судимості"
там "Днепропетровская" и "Днепропетровск"

там некоторые поля обязательные а некоторые нет

**Comment by RoOmel** [comment]
Символ астериска (*) присутствует перед названиями всех полей, обязательные к заполнению.
Задачу закрываю.
