### ISSUE TITLE
На главном портале, при заполнении формы, после нажатия кнопки "Заказать" - блокировать эту кнопу и показывать анимацию, говорящую о том, что процесс запущен и нужно подождать

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#372]
после нажатия на кнопки отправки формы ( “Подтвердить” или “Замовити послугу” ) несмколько секунд нет  визаульно никакой реакции - создается ощущение, что кнопка неработает. Необходимо блокировать кнопку и показывать прогессор какойто.

**Comment by bvv4ik** [comment]
Для теста: просто зайти в форму на главном портале, например в услугу справки о несудимости, и заполнив форму попытаться отправить...кнопка исчезнет и появится надпись "зачекайте..."

**Comment by annasahi** [comment]
Протестировано
