### ISSUE TITLE
На дашборде, при отработке формы, после нажатия кнопки действия(чиновником) - блокировать эту кнопу и показывать анимацию, говорящую о том, что процесс запущен и нужно подождать.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#373]
на дашборде у чиновника касательно кнопок “Оправцювати” / “Взяти в роботу”

**Comment by bvv4ik** [comment]
тест https://github.com/e-government-ua/i/issues/372

**Comment by katebutenko** [comment]
Для тесту:

"Необроблені": при натисканні на "Взяти в роботу" з'являється напис "Зачекайте" http://screencast.com/t/krxyIiBSgy
Якщо після цього натиснути на "Продовжити роботу з необробленими" напис змінюється на "Задачу направлено в роботу"
http://screencast.com/t/NKEfB04eWYO

"В роботі": при натисканні на "Опрацювати"  з'являється напис "Зачекайте" 
http://screencast.com/t/5K31nHwn0IUZ

Після натискання на "Ок" кнопка "Опрацювати" стає неактивною та з'являється напис "Задачу опрацьовано":
http://screencast.com/t/FXIr0H5lZ2rD

**Comment by smit-pb** [comment]
Задача  реализована согласно ТЗ и доп описанию.
