### ISSUE TITLE
На главном портале, после заполнении формы реализовать отображение кастомного сообщения об успешной отправке заявки.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#374]
Если в форме присутствует поле с id "response"
Но отображать в качестве текста после успешной отправки сообщения именно это содержимое (вместо того, что там сейчас отображается, типа: Спасибо, Ваша заявка№___ принята....)

Если такого поля нет, или оно пустое (после трим-а), то отображать текущее сообщение.

при этом обязательно предварительно заменять все найденные в этом тексте участки, типа ${family}, на значения из соответствующих полей формы.
Например, в данном случае из элемента с ИД "family"

П.С.: При этом хеадер:
Ваше звернення №____ успішно зареєстровано
- оставляем всегда! (подменяем только тело)

**Comment by asafronienkov** [comment]
Test $scope.data.formData.setResponce();

**Comment by kurbpa** [comment]
Применил на примере прицесса - https://poligon.igov.org.ua/service/159/general
для Киева

**Comment by asafronienkov** [comment]
В форме должен присутствовать attr name "response"

**Comment by bvv4ik** [comment]
теперь можно проверять

**Comment by smit-pb** [comment]
А валидация полей будет потом делаться ?
и нормальный ( не кривой) календарь с нормальной локализацией - тоже будет потом доделываться ?

**Comment by smit-pb** [comment]
Или - отдельной задачей на улучшение это все оформить ?

**Comment by bvv4ik** [comment]
smit-pb commented just now
А валидация полей будет потом делаться ?
и нормальный ( не кривой) календарь с нормальной локализацией - тоже будет потом доделываться ?

валидация сейчас в работе...

по календарю - даже задача пока еще не делалась, т.к. до этого нужно будет еще кое-какие решения принять... но все это помнится

**Comment by smit-pb** [comment]
ок.

**Comment by bvv4ik** [comment]
smit-pb commented just now
Или - отдельной задачей на улучшение это все оформить ?

задачи на улучшение должны создавать координаторы разработки...
а Вы можете создать таску в milestones - "test", с лэйблом "remark"
и тогда это облегчит учет таких "пунктиков", при этом не будет мешать разработчикам, и путать их...

а потом такие ремарки смогут быть обьеденены в таски уже.. в зависимости от их мест правок, чтоб оптимизировать работу

**Comment by bvv4ik** [comment]
проверять на
https://test.igov.org.ua

**Comment by smit-pb** [comment]
уже.
