### ISSUE TITLE
На главном портале реализовать валидацию поля, которое промаркировано как Телефон

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#375]
если в поле типа "markers" содержится объект, в элементах которого фигурирует ссылка на какие-то поля, как требующие валидации "по формату телефона" - проводить их валидацию после ввода содержимого этого поля, и отображать справа текст об ошибке формата, если ошибка будет.

Пример объекта:
{
    "validate":{
        "PhoneUA":{
                "aField_ID":["privatePhone","workPhone"]
        }
        , "Mail":{
                "aField_ID":["privateMail"]
        }
    }
}

где "privatePhone" и "workPhone" - это ИД-шники тех полей, которые нужно валидировать

Формат валидации "+380xxxxxxxxx"
где "x" - цифра от 0 до 9

ПОДСКАЗКА:
Для валидации телефона, стоит использовать плагин:
internation phone number
Пример использования:
http://jackocnr.com/intl-tel-input.html

Для валидации электронки, использовать патерн:
http://www.w3.org/TR/html-markup/input.email.html

**Comment by glebzhebrakov** [comment]
Нужно еще на фронте добавить красную рамку/надпись если валидация поля не прошла. 
Смотреть servicebuiltinbankidc.controller.js
Проверка прошла валидация номера или нет выполняется методом intlTelInput("isValidNumber").
Вот еще пример http://jackocnr.com/lib/intl-tel-input/examples/gen/is-valid-number.html

**Comment by bvv4ik** [comment]
проверить можно на услуге по МРЕО для Киева

**Comment by nazarenkod** [comment]
Задача реализована.Поле подсвечивается красным цветом при вводе буквенных/знаковых значений и не пропускает их. НО в поле можно вбить больше 9ти значений.Считаю это багом исходя из задачи-"Формат валидации "+380xxxxxxxxx""
![9](https://cloud.githubusercontent.com/assets/13256486/8844615/cdb92292-311f-11e5-9282-68c66229553a.jpg)

**Comment by bvv4ik** [comment]
оно не даст сабмитить форму с невалидным номером

**Comment by rostag** [comment]
@bvv4ik - тепер у цій формі працює і валідація мейлу:

![image](https://cloud.githubusercontent.com/assets/451410/8890819/3886a57e-3317-11e5-8be7-af7f1915efe6.png)

Додано як частина #543

**Comment by nazarenkod** [comment]
Валидация мейла работает, но но как и писал выше пропускает с невалидным номером телефона.
![invalidphone](https://cloud.githubusercontent.com/assets/13256486/8893289/3d6f6838-3393-11e5-92bc-2eddb5dc29c7.jpg)
![submit](https://cloud.githubusercontent.com/assets/13256486/8893290/4171b698-3393-11e5-9236-fa7def66c62b.jpg)

**Comment by rostag** [comment]
@bvv4ik - можу сьогодні доробити валідацію номеру. Згода?

**Comment by bvv4ik** [comment]
@rostag Спасибо! Отлично реализовано!

"можу сьогодні доробити валідацію номеру телефону."
был-бы признателен...

"Треба винести плагін у директиву, щоб усе гладко працювало."
согласен, но при этом крайне важно все завязывать на элементе "markers"

**Comment by rostag** [comment]
Знаю, що обіцяв ще три дні тому доробити - виникла заминка з "винести плагін у директиву" - тобто інтеграцією jQuery плагіну intlTelInput до форми AngularJS. Зміг це побороти, витратив час, але тепер маємо послідовне рішення. Отже, сьогодні таки буде готово.

**Comment by rostag** [comment]
Доробив валідацію, тепер текст помилки таки відображається справа від поля вводу телефону.

**Comment by rostag** [comment]
Дивно. Локально - працює, а на https://test.igov.org.ua/service/159 - ні. Розбираюсь...

**Comment by rostag** [comment]
Запрацювало! Прошу перевірити валідацію телофону: https://test.igov.org.ua/service/159/general

**Comment by nazarenkod** [comment]
Если ввести валидный номер для другой страны ,а потом перейти на Украину, то пропускает с инвалидным номером+пропускает недопустимые знаки в поле email.
Если нужно, то напишу человеческий баг-репорт...
![mailvalidation](https://cloud.githubusercontent.com/assets/13256486/9010863/45293130-37b2-11e5-8699-71ed67710a96.jpg)
![incorrectvalid](https://cloud.githubusercontent.com/assets/13256486/9010867/4b658f76-37b2-11e5-8e84-7a3d99d60f94.jpg)

**Comment by rostag** [comment]
@nazarenkod - дякую, буду зараз перевіряти.

Також помітив ще помилку після відправки форми: "SYSTEM_ERR For input string: "050 333 3333" 

![image](https://cloud.githubusercontent.com/assets/451410/9011245/a673a838-37b4-11e5-82ef-b3bba130b6d9.png)

У вас є така помилка?

**Comment by nazarenkod** [comment]
Была, когда только начал проверять форму....потом пропала и больше не появлялась...

**Comment by rostag** [comment]
@nazarenkod - гм, і в мене зникла. Може, вже хтось виправив )

**Comment by nazarenkod** [comment]
Я тоже так думал:)

**Comment by bvv4ik** [comment]
т.е. таки работает норм?

**Comment by nazarenkod** [comment]
Ошибку, я так понял, починили. Валидация поля "Телефон" работает.Осталась только проблема с валидацией поля "email"

**Comment by rostag** [comment]
@nazarenkod - а яка проблема з валідацією email? Я щойно перевірив тут:
https://test.igov.org.ua/service/159/general/city/built-in/region/1/city/1/

Валідація працює:
![image](https://cloud.githubusercontent.com/assets/451410/9062604/22abdad2-3acc-11e5-9b7d-99a9002f923e.png)

**Comment by nazarenkod** [comment]
@rostag Пропускает недопустимые знаки
![nocorrectinput](https://cloud.githubusercontent.com/assets/13256486/9064069/77b92a46-3ad3-11e5-967c-c883498ef62e.jpg)

**Comment by rostag** [comment]
@nazarenkod - дякую, буде виправлено!

**Comment by rostag** [comment]
@nazarenkod @bvv4ik - насправді, до "собаки" (так звана "локальна частина" мейл-адреси) ці символи є формально валідними ( ``` # - _ ~ ! $ & ' ( ) * + , ; = : ``` ), прошу: https://en.wikipedia.org/wiki/Email_address#Local_part

Отже, нам треба вирішити: чи будемо пропускати їх ми, чи ні. Для мене не проблема додати ще одну перевірку, але спочатку треба нам прийняти це рішення.

**Comment by bvv4ik** [comment]
@rostag прав!
будем придерживаться общих стандартов!

**Comment by nazarenkod** [comment]
@bvv4ik хорошо.Значит таску закрываю.
