### ISSUE TITLE
На бэке(в активити) задать формат даты/времени, при использовании поля типа date (формат: YYYY-MM-DD)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#376]
Сейчас все даты выбранные из датапикера передаются в не очень красивом формате
( Tue May 12 00:00:00 EEST 2015: 111)

**Comment by maxtmn** [comment]
можно пример, откуда и куда в таком формате передается дата?
по умолчанию сейчас формат даты для полей "date" установлен: dd/MM/yyyy

**Comment by bvv4ik** [comment]
например, при формировании текста письма

**Comment by bvv4ik** [comment]
сейчас подход такой, что просто добавляем лэйбл "test", и пишем краткий коммент для тестера - как можно проверить

**Comment by RoOmel** [comment]
В сервер возвращает "date" "2015-01-01", "2015-07-06", "2015-07-20", что соответствует формату таски YYYY-MM-DD.

**Comment by bvv4ik** [comment]
"Вопрос только по корректности возвращаемой "date", описанной в #522"
так это не относится к данной задаче
