### ISSUE TITLE
На главном портале, доработать форму предоставления доступа к документу

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#377]
Текст над формой: Ви можете надати доступ до документу, згенерувавши код до нього. За цим кодом можна буде знайти Ваш документ (вкладка Пошук документу за кодом). Також Ви можете додатково захистити документ SMS-паролем.

Новая последовательность полей:
-На який термін ви надаєте доступ? [select: 1 день, 1 тиждень, 1 рік]
-Чи бажаєте Ви захистити документ SMS-паролем? Ви можете ввести номер мобільного телефону людини, якій Ви надаєте доступ, і тоді для входу їй потрібно буде ввести SMS-пароль [radio: Ні Так]
(если клиент выбрал Так) Номер мобільного телефону людини, якій Ви надаєте доступ: [инпут с + в начале]
кнопка [Отримати код](пока отображается ссылка, но будет код и к этой задаче это не относится)

после сабмита появляется окошко, где можно скопировать код (пока эт оссылка, но это нормально ,пока)
(само копирование в буфер обмена при клике перенесено в таску https://github.com/e-government-ua/i/issues/385)

**Comment by bvv4ik** [comment]
dmoskovtsov [9:02 PM] 
Эта сделана кроме копирования в буфер 
https://github.com/e-government-ua/i/issues/377
Тому кто будет ее заканчивать нужно передать что проблема в подключении ng-clip с angularamd. Когда его подключат должно заработать из коробки. 

Документ предоставляем на 7 дней при случае выбора неделя. Если я как клиент в пятницу предоставляю другу доступ на неделю, я ожидаю что в четверг он сможет им воспользоваться.

**Comment by RoOmel** [comment]
Функционал не реализован, СМС и сообщение на почту для доступа не отправляется, на форме страницы надпись "Розділ у процесі розробки!".

**Comment by bvv4ik** [comment]
в рамках данного диалога - отсылка СМС в принципе не предполагается
(это только будет делаться в: https://github.com/e-government-ua/i/issues/482 ,
основа для которой сделана тут: https://github.com/e-government-ua/i/issues/317)

а ссылка не приходит из-за ошибки, которая устраняется другой таской:
https://github.com/e-government-ua/i/issues/460#issuecomment-117709739

ИТОГО:
В данной таске нужно только убедиться, что все поля соответствуют ТЗ
(они переделывались, т.к. там были совершенно другие)

**Comment by RoOmel** [comment]
Ну так это другой совсем разговор

**Comment by RoOmel** [comment]
Нет возможности проверить функционал по требованиям ,т.к. после авторизации отображаются пустые вкладки, т.е. нет документов.
Такое впечатление, что авторизация не работает, т.к. ранее после авторизации во вкладке "Мої документи" был паспорт.

**Comment by bvv4ik** [comment]
альфа сегодня с утра была поломана(
уже починили!

**Comment by RoOmel** [comment]
Итого ,согласно https://github.com/e-government-ua/i/issues/482:
1. пункты 1 - 3 не реализованы
2. пункты 4 - 5 нет возможности проверить

**Comment by bvv4ik** [comment]
@RoOmel
"Итого ,согласно #482:
1. пункты 1 - 3 не реализованы
2. пункты 4 - 5 нет возможности проверить"

это таска 377, а не 482
и я выше в коменте описал - что конкретно нужно в ней проверить ("просто наличие полей")
и даже сейчас уже ссылка отображается...

**Comment by RoOmel** [comment]
При нажатии пиктограммы "Надати доступ третій особі":
1. Отображается надпись крупным жирным шрифтом "Надати доступ до електронного документу" с выравниванием посередине.
2. Ниже отображается надпись обычным шрифтом"Ви можете надати доступ до документу, згенерувавши код до нього. За цим кодом можна буде знайти Ваш документ (вкладка Пошук документу за кодом). Також Ви можете додатково захистити документ SMS-паролем." с выравниванием посередине.
3. Ниже отображается блок ввода данных:
3.1 mandatory field с выравниванием по левому краю "Введіть ім’я та прізвище людини, якій Ви надаєте доступ *" - пустое по умолчанию;
3.2 Выпадающий список  с выравниванием по левому краю "Введіть термін дії доступу:"  - без выбора варианта по умолчанию;
3.3 Надпись  с выравниванием по левому краю "Чи бажаєте Ви захистити документ SMS-паролем? Ви можете ввести номер мобільного телефону людини, якій Ви надаєте доступ, і тоді для входу їй потрібно буде ввести SMS-пароль";
3.4 Радиокнопка с вариантами "Ні" - по умолчанию, "Так";
3.5 Надпись с выравниванием по левому краю "Введіть електронну пошту (за бажанням)
3.6 Надпись с выравниванием по левому краю мелким шрифтом (на вказаний адрес буде надіслано посилання на документ)"
3.7 При выборе радиокнопки "Так" отображается:
 - надпись с выравниванием по левому краю "Введіть номер її мобільного телефону";
 - надпись с выравниванием по левому краю мелким шрифтом "(через нього вона веріфікується через SMS) ";
 - Поле ввода номера мобильного телефона с предзаполнением "+380"
3.8 Поле ввода адреса электронной почты

**Comment by bvv4ik** [comment]
на сколько это соответствует условиям таски?
если соответствует - прошу и сделать заключение что все гуд, и закрыть таску
если не соответствует условиям - указать что не соответствует

**Comment by RoOmel** [comment]
1. Отсутствует кнопка "Отримати код";
2. При нажатии на "Надати доступ" отображается окно с ссылкой в поле ввода
![bug_igov_08](https://cloud.githubusercontent.com/assets/12996514/8499227/09eebd58-2199-11e5-81f5-6d3d4dda20f2.jpg)

**Comment by bvv4ik** [comment]
1. поправлено
2. это нормально, пока что... ранее вообще ничего не отображалось, было исправлено другой таской. а как завершат весь каскад задач и код появится

**Comment by RoOmel** [comment]
1. Кнопка "Отримати код" отображается;
2. В разработке

**Comment by bvv4ik** [comment]
п.2. не является пунктом данной задачи,
если больше замечаний нет, я закрываю
