### ISSUE TITLE
Разобраться куда исчезают в активити задачи после их отработки, т.к. ни в архиве(в ActivitiExplorer), ни в закладке "Оброблені"(на дашборде) - там ничего нет... то-ли они после отработки удаляются, то-ли еще что-то не так...

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#378]
Задачи должны оставаться со статусом отработанных, чтоб их можно было потом всегда найти и в Активити-Эксплорере и в Дашборде, в закладке "Оброблені"

Дока по Активити:
http://www.activiti.org/userguide/#_forms

**Comment by bvv4ik** [comment]
вроде сам Активити не отдает данные...

**Comment by ASkosyr** [comment]
Ориентировочный срок поставки - 6 июля

**Comment by ASkosyr** [comment]
после завершения таски становятся доступны через хистори сервайс
например так можно получить таску по айдишнику завершенную
https://test.region.igov.org.ua/wf-region/service/history/historic-task-instances/622727

или вот так все таски завершенные пользователя
https://test.region.igov.org.ua/wf-region/service/history/historic-task-instances?taskAssignee=kermit

в dashboard-js необходимо переделать вызов на хисторик сервайс для тасок, которые уже завершены

**Comment by ASkosyr** [comment]
подправил частино пока
таски начали показывать на закладке завершенных.

оставшися моменты 
- количество всегда постоянное
- дата таски в списке некорректно отображатеся (в хисторик таске нет поля createTime)
- информация по таске не подгружается так как запрос об информации по таске идет к таск сервису

**Comment by ASkosyr** [comment]
количество обработанных тасок отображается теперь нормальное
при завершении таски количество завершенных тасок в списке увеличивается

**Comment by ASkosyr** [comment]
Пример объекта historic task, который возвращается как результат получения выполненных задач.
Урл для запроса
https://test.region.igov.org.ua/wf-region/service/history/historic-task-instances/622727

Результат:
{"id":"622727","processDefinitionId":"dnepr_mvd_1:55:620057","processDefinitionUrl":"https://test.region.igov.org.ua/wf-region/service/repository/process-definitions/dnepr_mvd_1:55:620057","processInstanceId":"622662","processInstanceUrl":"https://test.region.igov.org.ua/wf-region/service/history/historic-process-instances/622662","executionId":"622662","name":"ÐÐ°Ð´Ð°Ð½Ð½Ñ Ð¿Ð¾ÑÐ»ÑƒÐ³Ð¸","description":null,"deleteReason":"completed","owner":null,"assignee":"kermit","startTime":"2015-06-23T10:19:23.342+03:00","endTime":"2015-07-01T23:37:14.417+03:00","durationInMillis":739071075,"workTimeInMillis":null,"claimTime":null,"taskDefinitionKey":"usertask1","formKey":null,"priority":50,"dueDate":null,"parentTaskId":null,"url":"https://test.region.igov.org.ua/wf-region/service/history/historic-task-instances/622727","variables":[],"tenantId":"","category":null}

**Comment by ASkosyr** [comment]
Исправление фронтенда для правильного отображения информации о завершенных задачах не в контексте этой таски.

Это будет делаться в отдельной задаче.

**Comment by VadimGulich** [comment]
Заявки отображаются- протестировано , ждем задачку по исправлению фронта)
