### ISSUE TITLE
Создать сервисы получения свободных слотов и установки на них тикетов субъектов, для "электронной очереди"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#380]
По задаче https://github.com/e-government-ua/i/issues/315 были реализованы сущности по "Электронной очереди", в т.ч. 1.7) FlowSlot (слот потока) и 1.8) SubjectTicket (тикет субьекта).

1) Создать сервис getFlowSlots_ServiceData,
в который будут передаваться параметры:
nID_ServiceData (номер-ИД) //обязательно
bAll (булевый true/false) //опциональный, по умолчанию false (если false то из возвращаемого объекта исключаются элементы, содержащие "bHasFree":false "bFree":false)
и который вернет по сущности:
nDays (номер) //опционально (по умолчанию = 60), определяет число дней, начиная с текущей даты, за какой период делать выборку

1.7) FlowSlot (слот потока), с полями:
nID (лонг) - номер-ИД (уникальный) //обязательное (автоитеррируемый)
nID_Flow_ServiceData (лонг) - номер-ИД потока данных сервиса //обязательное
sDate (дата со временем) - дата и время //обязательное
sData (<30 символов) - строка данных (например "2*hour") //обязательное
sName (<200 символов) - строка, описания для человека (напр: "2015-06-06 с 8-00 до 8-30") //обязательное

ОТВЕТ(пример):
{
   "aDay";[
      {
      "sDate":"2015-06-17"
      , "bHasFree":true
      , "aSlot":[
         {
            "nID" : 3456
            , "sTime" : "15:30"
            , "nMinutes" : 15
            , "bFree" : false
         }
         , {
            "nID" : 3457
            , "sTime" : "15:45"
            , "nMinutes" : 15
            , "bFree" : true
         }
      }
   ]
}

ОСОБЕННОСТИ:
1.1) При определении bFree - проверять наличие в сущности SubjectTicket записей, связанных с данным ИД слот-а, и ставить true, если записи нет (если запись есть, но в ней nID_Task_Activiti = null и одновременно дата в sDate меньше чем текущая более чем на 15 минут, то считать, что записи нет) 
1.2) При определении bHasFree - проверять наличие в под-массиве "aDay" наличия хоть одной записи с "bFree" : true
1.3) Сортировать элементы массивов по "sDate" и "sTime", по возрастанию
1.4) Выдавать массив "aDay" длинной не более 60-ти элементов

2) Создать сервис setFlowSlot_ServiceData,
в который будут передаваться параметры:
nID_FlowSlot (номер-ИД) //обязательный
nID_Subject (номер-ИД) //обязательный
nID_Task_Activiti (номер-ИД) //опциональный
и который добавит запись с данным субъектом! в сущность:

1.8) SubjectTicket (тикет субьекта), с полями:
nID (лонг) - номер-ИД (уникальный) //обязательное (автоитеррируемый)
nID_FlowSlot (лонг) - номер-ИД слота потока //обязательное
nID_Subject (лонг) - номер-ИД субьекта //обязательное
nID_Task_Activiti (лонг) - номер-ИД задачи Активити //обязательное
sDateEdit (дата со временем) - дата и время создания / реактирования тикета //обязательное

ОТВЕТ(пример):
{
"nID_Ticket":453425 //ID-шник созданного тикета
}

ОСОБЕННОСТИ:
2.1) В поле "sDateEdit" - ставить текущую дату
2.2) Перед добавлением записи, проверять наличие в сущности SubjectTicket записей, связанных с данным ИД слот-а, и не давать запись, если она есть (если запись есть, но в ней nID_Task_Activiti = null и одновременно дата в sDate меньше чем текущая более чем на 15 минут, то считать, что записи нет) 
2.3) если параметр nID_Task_Activiti задан, то проставлять его в записи, если нет, то ставить null
2.4) если запись уже есть (по проверке п.п.2.2), то апдейтить ее.

**Comment by bvv4ik** [comment]
для теста:
запросы в сооотв. с описанием срвисов

**Comment by brunneng** [comment]
Для теста:
Проверять надо на свежеустановленной базе.
В запросах ниже замените localhost на тестируемый сервер.
1) GET  http://localhost:8080/wf-central/service/flow/getFlowSlots_ServiceData?nID_ServiceData=1
должно, что-то вернуть. Слот с nID = 1 свободный. 
2) POST http://localhost:8080/wf-central/service/flow/setFlowSlot_ServiceData
form parameters:
nID_FlowSlot = 1
nID_Subject = 2
nID_Task_Activiti = 1
должно вернуть 
{
"nID_Ticket" : ID-шник созданного тикета
}

3) GET  http://localhost:8080/wf-central/service/flow/getFlowSlots_ServiceData?nID_ServiceData=1
должно, что-то вернуть. Слот с nID = 2  не свободный. 

4) Повторите запрос из 2 - должно вернуть тот же nID_Ticket.

**Comment by VadimGulich** [comment]
Проверили через Postman Rest Client
