### ISSUE TITLE
На главном портале, в фильтре поиска на стартовой, делаем в поле поиска возможность открыть расширенный фильтр, в виде popup-а

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#381]
Так же, как в Gmail, как тут: https://www.dropbox.com/s/yrunvours8qo92k/Screenshot%202015-06-06%2018.38.11.png?dl=0

Добавить там такие элементы:
1) [ckeckbox] Показати тільки послуги, що доступні через Інтернет
2) [select: спісок тіпов госорганов] (выбор возможен только одного)
3) [combobox] по статусу (поле nStatus в обьекте услуги, может быть 0,1 или 2):
-Всі послуги
-Доступні онлайн
-Послуги, що запустяться незабаром

**Comment by bvv4ik** [comment]
добавлен п.3.

**Comment by VadymVolos** [comment]
Может в фильтр нужно еще добавить Область/Город?
и еще один пункт "Держ орган"

**Comment by bvv4ik** [comment]
"И еще один пункт "Держ орган" "
это и есть:
2) select: спісок тіпов госорганов

"Может в фильтр нужно еще добавить Область/Город?"
слишком сложно для реализации, тяжело для системы, и практической пользы - очень мало...
(+ масса неоднозначностей)

кроме того, мы тогда не сможем получить фидбэк, который сейчас мы получаем если человек заходит в услугу и видит что ее в этом регионе нет, но есть кнопки по соцсетям и отправке электронки...

**Comment by glebzhebrakov** [comment]
может уберем checkbox , раз у нас есть "-Доступні онлайн" в 3 пункте ?
или оставить для наглядности ?

**Comment by bvv4ik** [comment]
@glebzhebrakov
да, ссогласен, оно уже будет не к чему

**Comment by glebzhebrakov** [comment]
я все таки решил оставить, но при выборе чекбокса делаю 3 пункт disabled. так нагляднее, как мне кажется

**Comment by bvv4ik** [comment]
как-то избыточно получится, ИМХО
информационный шум будет...
