### ISSUE TITLE
На главнои портале реализовать авто-подтягивание списка доступных слот-ов и установки на них тикетов субъектов, для "электронной очереди

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#382]
Сами явовские сервисы реализуются по задаче: https://github.com/e-government-ua/i/issues/380

1) для поля с тип-ом "queueData" - отрисовывать два комбо-бокса,
- в первом отображать список дат в формате "YYYY-MM-DD"
- во втором времени, в формате "hh:dd"
- пока не выбран первый комбо-бокс - второй заблокирован.
- контент второго комбо-бокса отображать исключительно в контексте выбранной позиции по первому (и при каждом повторном выборе первого - переформировать второй).
- весь контент отображать на основании полученного объекта, который должен получаться на по вызову метода "getFlowSlots_ServiceData" (реализовать прослойку на бэке ноды)
Передавать туда параметр:
nID_ServiceData (номер-ИД ) - ИД из выбранного элемента массива aServiceData, выбранного сервис-а)

Пример объекта:
{
"aDay";[
{
"sDate":"2015-06-17"
, "bHasFree":true
, "aSlot":[
{
"nID" : 3456
, "sTime" : "15:30"
, "nMinutes" : 15
, "bFree" : true
}
, {
"nID" : 3457
, "sTime" : "15:45"
, "nMinutes" : 15
, "bFree" : true
}
}
, {
"sDate":"2015-06-18"
, "bHasFree":true
, "aSlot":[
{
"nID" : 3458
, "sTime" : "14:15"
, "nMinutes" : 15
, "bFree" : true
}
, {
"nID" : 3459
, "sTime" : "14:30"
, "nMinutes" : 15
, "bFree" : true
}
, {
"nID" : 3460
, "sTime" : "15:15"
, "nMinutes" : 15
, "bFree" : true
}

}

]
}

ВАЖНО: Пока задача по реализации этого метода не готова (https://github.com/e-government-ua/i/issues/380), подставлять мок-овый объект (уже на бэке ноды), из примера выше, эмулируя при этом вызов метода.

2) После выбора второго комбо-бокса(со временем), вызывать метод "setFlowSlot_ServiceData" (реализовать прослойку на бэке ноды)
Передавать туда параметры:
nID_ServiceData (номер-ИД ) - ИД из выбранного элемента массива aServiceData, выбранного сервис-а)
nID_Subject (номер-ИД ) - ИД текущего (аквторизированного) субьекта

По результату вызова - сохранять в поле тип-а "queueData" значение, по 
пример-у обьекта:
"{'nID_SubjectTicket':3452534, 'sDate': '2015-11-23 15:30:00.00'}"

ВАЖНО: Пока задача по реализации этого метода не готова (https://github.com/e-government-ua/i/issues/380), подставлять мок-овый объект (уже на бэке ноды), из примера выше, эмулируя при этом вызов метода.

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/8496701/f973fbdc-217f-11e5-9c3c-4a4e2f0125ea.png)
{"aDay":[]}   Пропали даты , ранее отображались

**Comment by bvv4ik** [comment]
как и писал - с утра были проблемы с базой данных альфы, постепенно восстанавливали данные.. и восстановили...
уже все норм:
![image](https://cloud.githubusercontent.com/assets/4208821/8497707/00ba5cbc-2188-11e5-91e9-6d10ac707f8d.png)

**Comment by VadimGulich** [comment]
угу , уже работает
