### ISSUE TITLE
Создать в активити новый тип "queueData", на базе "string"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#383]

**Comment by bvv4ik** [comment]
для теста: зайти в активити-эксплорер и в редактореБП увидеть возможность добавить новый тип поля

**Comment by kurbpa** [comment]
Применил новый тип на примере прицесса - https://poligon.igov.org.ua/service/159/general
для Киева

**Comment by rooksnest** [comment]
что такое редакторБП?

**Comment by bvv4ik** [comment]
это в Активити-Эксплорере такаая функция
https://test.region.igov.org.ua/admin-activiti
kermit/kermit

**Comment by kurbpa** [comment]
@bvv4ik 
В активити-эксплорере новый тип не появился - https://docs.google.com/document/d/15QvBy8e0_2xRvyHi04MQ9Ip2TlvlEjfh2PSftMY2BNM/edit?usp=sharing

PS (скрин копи-пастом кстати добавить не удается как ни пытался)

**Comment by bvv4ik** [comment]
так погоди,:
1) это альфреско, а не активити-эксплорер
2) там даже типа file нет, хотя он-то уж точно есть, ты-ж сам знаеш

**Comment by bvv4ik** [comment]
"PS (скрин копи-пастом кстати добавить не удается как ни пытался)"
вот это странность.. я пользуюсь принтскрином и отлично работает

**Comment by rooksnest** [comment]
1) это альфреско, а не активити-эксплорер
при редактировании процесса, открывается альфеско активити и там нового типа нет.
так как должно быть в действительности?

понимаю, что со временем у всех в обрез, но есть просьба, по возможности, детальней описывать задачу, т.к. впервые войдя в ту же активи эксплорер, приходится продолжительное время ковыряться, чтоб разобраться где что.

**Comment by bvv4ik** [comment]
тут нужно чтоб Павел один раз показал, что да как... а то действительно - в первое время на разбирания много времени уходит...
Павел, поможешь?

**Comment by rooksnest** [comment]
протестировано
