### ISSUE TITLE
Починить работу проперти "general.bTest" на бэке, берущейся из проперти-файла AS.properties

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#384]

**Comment by bvv4ik** [comment]
для теста, нужно смотреть в логах полигона централа(poligon.igov.org.ua), строку типа:
2015-06-21_12:25:15.996 | INFO | org.wf.dp.dniprorada.util.GeneralConfig- [bTest]:sbTest=true

предварительно загрузив каталог услуг на https://poligon.igov.org.ua

**Comment by VadimGulich** [comment]
Кто может предоставить доступ к логам полигона или может настроить kibanu для удобного доступа к логам ?

**Comment by bvv4ik** [comment]
есть кибана, но завтра  Антону все изложу, доступ появится.(предварительно с ним разговаривал уже)
