### ISSUE TITLE
На главном портале при предоставлении доступа к документу добавить функцию "авто-копирования в буфер обмена" при клике на поле

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#385]
Мои документы
-Форма предоставление доступа
--окошко после сабмита:
--- ссылку выводить в инпуте, при клике инпут показывать текст “Скопійовано у буфер” (и копировать ссылку в буфер обмена)

П.С.: перенесено из https://github.com/e-government-ua/i/issues/327

**Comment by bvv4ik** [comment]
dmoskovtsov [9:02 PM] 
Эта сделана кроме копирования в буфер 
https://github.com/e-government-ua/i/issues/377
Тому кто будет ее заканчивать нужно передать что проблема в подключении ng-clip с angularamd. Когда его подключат должно заработать из коробки.

**Comment by RoOmel** [comment]
Непонятен сценарий.

**Comment by bvv4ik** [comment]
просто открыть доступ к документу и в появившемся окне с кодом клацнуть мышкой на кнопочку правее поля с кодом. код должен скопироваться в буфер обмена.

**Comment by RoOmel** [comment]
Код в буфер обмена не копируется

**Comment by bvv4ik** [comment]
у меня копируется... пробовал несколько раз.. прошу или видео-демо записать или в скайпе в расшареном экране показать

**Comment by RoOmel** [comment]
Мувик про баг
https://drive.google.com/a/privatbank.ua/file/d/0By-38eMuwpQrODQzbEJkSnl6aDA/view?usp=sharing
Здесь https://docs.google.com/spreadsheets/d/1Orx4JaKP-lSSVfY9569LZsAG9KgAuM-wKHWsA71D_Ow/edit?pli=1#gid=2121840503
Баг 9-тая запись

**Comment by bvv4ik** [comment]
доступ на док запросил, т.к. не дает открыть

**Comment by RoOmel** [comment]
https://drive.google.com/file/d/0B11yU74u6FZBQmZ5amNRNjgwa1U/view?usp=sharing

**Comment by RoOmel** [comment]
Конечно, я же доступ раснарил на домен ПБ

**Comment by bvv4ik** [comment]
![image](https://cloud.githubusercontent.com/assets/4208821/9086227/b3b73dae-3b8b-11e5-84bc-c1ab59f7b137.png)

1) клик
2) Ctrl+V: 21170

все работает...
или прошу уточнить - в каком именно обозревателе не работает (у меня хром)

**Comment by RoOmel** [comment]
Я же выше указал - "Мувик про баг в FF39.0" - Firefox ver. 39.0

**Comment by VadimGulich** [comment]
https://drive.google.com/file/d/0Bw7BSYSLbe2MOWlSQ0NUTEcwZUE/view?usp=sharing 
В ФФ уже работает , уже даже фильм есть про это = ))
