### ISSUE TITLE
На бэке централа добавить добавить в сущность ServiceData поле asAuth, и перечислить там допустимые методы авторизации, например "BankID,EDS"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#386]
обязательно добавить в умолчательные инициализационные списки значения по этой сущности в виде:
BankID,EDS

**Comment by bvv4ik** [comment]
Ну как там, получается?

**Comment by dgroup** [comment]
Приступаю :)

**Comment by bvv4ik** [comment]
Для теста:
в услуге: Надання довідки про відсутність або наявніть судимості
в Днепропетровске, должен быть доступен только один метод авторизации - через БанкИД

т.к. в ServiceData с ИД 33 - в поле asAuth проставлен только маркер "BankID"

**Comment by VadimGulich** [comment]
"asAuth":"BankID" - отображается вход только через BankID
"asAuth":"" - отображается вход через BankID,EDS
"asAuth":"BankID,EDS " - отображается вход через BankID,EDS
"asAuth":"EDS " - отображается вход через EDS

Протестировано на https://poligon.igov.org.ua , можно на боевой :)

**Comment by dgroup** [comment]
:clap:
