### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by yurikoles** [e-government-ua/i#389]
Хотел бы сделать iOS app. Соотвественно нужен API и mock-up`ы.
Пока сделаю рекламу в Slack cocoa-developers.

**Comment by sosnovsky** [comment]
Я бы поучаствовал.

**Comment by sviatoslav** [comment]
+1

**Comment by alokard** [comment]
+1. Описание API, вроде, уже есть - https://github.com/e-government-ua/i/blob/master/docs/specification.md

Mock-up'ы как wireframes, думаю не проблема самим набросать, a вот для дизайна стоит найти кого-то.

**Comment by VadymVolos** [comment]
Для дизайна можете написать подробное ТЗ, какие блоки, какие кнопки, под какие экраны, вообщем подробно все написать и оставить задачу в ветке Makeup
https://github.com/e-government-ua/i/milestones/Makeup

**Comment by painie** [comment]
ИМХО с юзерских сценариев стоит начать. Какие сценарии будут полезны? Каких реально достичь с существующим API?
Дублировать нынешниие бизнес-сценарии может быть накладно, проще моб версию сайта улучшать

**Comment by VadymVolos** [comment]
Мобильная версия сайта да, но нужны приложение в аппстор, гуглсторе, виндовссторе.

Зачем?

Similar to Windows' Live Tile support, we'll add support for iOS Web Apps. This includes:
- Icon support for the home screen for iPad and iPhone (both retina only)
- Hiding the Safari user interface
- Changed appearance of the staus bar

Вообщем 
автологин нужен с мобильного
скрыть интерфейс браузера и развернуть сайт на весь экран
также возможно геолакация
пуш уведомления

Нужно думать, какие функции делать, но наличие приложения во всех сторах нужно.

**Comment by bvv4ik** [comment]
давайте это разместим гдето в общем гуглодоковском файле "бэклога", т.к. задача не первостепенная, хоть и полезная.. на перспективу...
