### ISSUE TITLE
Amazon eu-west??

### ISSUE THREAD

**Issue by yurikoles** [e-government-ua/i#391]
Есть же eu-central!

**Comment by creativie** [comment]
Есть еще много разных, не понятен вопрос

**Comment by yurikoles** [comment]
Ну логично же, что eu-central поближе к нам будет.

**Comment by creativie** [comment]
По расстояния - да, по сети особой разницы нет.
http://www.cloudping.info/

**Comment by bvv4ik** [comment]
а что скажете на счет ДеНово?
-качество
-цены
-возможности

**Comment by bvv4ik** [comment]
тема "зависла", я так понял...
