### ISSUE TITLE
На дашборде реализовать настраиваемый шаблон, в форме для печати

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#394]
- [ ] 1) Сейчас, при использовании кнопки "Роздрукувати":
тело "захардкодено", а нужно, чтоб оно бралось из поля с id="sBody"
(если поле отсутствует или = null, то оставлять текущее отображение)
- [ ] 2) В теле, все встреченные теги (например "[family]", где "family" - id существующего в форме поля), заменять на значения соответствующих полей, а если это будет конструкция, типа [label=family] на их лэйблы, соответственно.
- [ ] 3) В теле, все встреченные теги "[id]", заменять на id-задачи (если какие-то "стандартные" еще пропущены, то и для них придумать маркеры)
- [ ] 4) для полей с типом enum подставлять не само значение элемента(типа "attr1"), а его название в масиве энумов(типа: "Вариант первый"). В коде на стандартной форме уже реализованы функции, которые это умеют делать.

**Comment by AleksejDomash** [comment]
не понял этот пункт полностью  2) В теле и футере, все встреченные теги типа "[family]", заменять на значения соответствующих полей (т.е. id=family, в данном случае), а [label=family] на их лэйблы, соответственно.

есть реальный пример ?

**Comment by AleksejDomash** [comment]
посмотрел процес dnepr_subsidies.bpmn, по идее, для него необходимо делать специфическую форму, но там нет нигде таких полей  id="footer", id="sBody"

**Comment by bvv4ik** [comment]
можно не ждать пока кто-то добавит эти поля, можно прост озамокать их...
так,как будто они там были и данные от туда считались...

например значение поля sBody:
<center>Заявка № [id]</center>
<label>Фамилия  заявителя:</label> [family]
<label>Решение:</label> [result]

далее обычной заменой перебираем все поля формы и если встретим их в таком "шаблоне" - заменяем на значения.

т.е. получилось-бы:
<center>Заявка № 23345</center>
<label>Фамилия  заявителя:</label> Белявцев
<label>Решение:</label> Принято



с "footer" то-же самое...

**Comment by bvv4ik** [comment]
Павел, добавь плиз поля:
id="sBody" (типа invisible)
и
id="footer" (типа invisible)
в этот БП

**Comment by bvv4ik** [comment]
упростил задачу... убрал футер. Пусть весь шаблон будет целиком задаваться через поле с id=sBody (или оставаться тот, который сейчас захардкоден)

**Comment by AleksejDomash** [comment]
добавил возможность брать шаблон для печати из sBody. Таким образом, в процесе должно быть поле sBody типа invisible, в котором содержится html с шаблонами типа [id поля формы]. Например: <div>Фамилия: [idFieldLastName]</div>. Так подходит ?

Возможно стоит также использовать шаблоны для label, как указано выше в коментариях, тогда можно передлать:
1.  [label=id field]
2. [value=id field]

**Comment by bvv4ik** [comment]
1.текст "[label=idFieldLastName]" - должен замениться на лэйбл поля idFieldLastName
2.текст  "[idFieldLastName]" - должен замениться на значение поля idFieldLastName

где "idFieldLastName" - id-шник реального поля в БП

**Comment by bvv4ik** [comment]
на всяк случай добавлен п.4.

**Comment by bvv4ik** [comment]
для теста:
БП: dnepr_subsidies
в дашборд зайти под: dn200986zda dn200986zda
а там ИД процесса №1275342
если уже такого нет, то другой БП по субсидиям... и "Роздрукувати". Появится диалог, в котором будут в т.ч. подставлены данные по таске

**Comment by smit-pb** [comment]
При нажатии на "Роздрукувати" - вообще ничего не происходит.
Тестирование на https://test.region.igov.org.ua:6948/ - Под ФаирФокс и под Хромом.

Возможно что-то "не долили" не сервер ?

**Comment by bvv4ik** [comment]
происходит, только диалог выводится в самом верху, проскролировать нужно (эта проблема решается другой задачей)

**Comment by smit-pb** [comment]
Да - спасибо, нашел.

А вот проблемка которая в нутри открытого окна - 


Есть проблема с №1275342 -
"<![CDATA[

(найменування структурного підрозділу "
Это отображается в самом начале открытой формы из которой должна пойти печать.
А это в конце -
" одержуваних послуг).
]]> "

**Comment by smit-pb** [comment]
Для других - аналогичных заявок ( на пример №762751) - данная ошибка не воспроизводиться.

Расценивать это - как проблема с конкретной заявкой ? или как ?

**Comment by bvv4ik** [comment]
это текст который сейчас правит БА
это не сама форма...

**Comment by smit-pb** [comment]
Вопрос в том - расценивать это как ошибка ? 
или нужно будет еще раз протестировать Чуть позже сегодня ? 
Или фактически можно закрывать задачу ?

**Comment by bvv4ik** [comment]
это не ошибка формы а еще недописанный контент..
так что все норм
