### ISSUE TITLE
На главном портале сделать скролл для списко городов и регионов (DropBox з регіонами розташувати у декілька колонок)

### ISSUE THREAD

**Issue by poremchuk** [e-government-ua/i#395]
Доброго вечора, друзі.

Наразі дропбокс з регіонами випадає до низу на декілька корпусів сторінки. Це більше баг ніж фітча :) Думаю, варто зробити меню у декілька колонок або інт. мапу.
![22 06](https://cloud.githubusercontent.com/assets/3364472/8285868/df95216a-190e-11e5-9173-4f99095c79ca.png)

**Comment by hordesalik** [comment]
я б краще додав скрол якщо у дропбоксі більше 5-10 елементів

**Comment by poremchuk** [comment]
Думаю, не варто змушувати користувач робити додаткові дії у т.д. клацати, скролити і т.д.

**Comment by bvv4ik** [comment]
Спасибо за замечание, обязательно поправим

**Comment by poremchuk** [comment]
bvv4ik, можу я мапою зробити якщо Ви не проти?

**Comment by bvv4ik** [comment]
@poremchuk
там просто места нет для карты( а если придется размещать в другом месте и того сложнее будет... я-б всеже пока просто "топ 10 сделал"... потому, если у Вас есть возможность и желание это сделать(топ 10) - были-бы очень Вам благодарны!

**Comment by poremchuk** [comment]
На мою думку, ви пропонуєте половинчасте рішення.
Я подумаю як можна зробити краще і без мапи.

2015-06-23 11:41 GMT+03:00 bvv4ik <notifications@github.com>:

> @poremchuk <https://github.com/poremchuk>
> там просто места нет для карты( а если придется размещать в другом месте и
> того сложнее будет... я-б всеже пока просто "топ 10 сделал"... потому, если
> у Вас есть возможность и желание это сделать(топ 10) - были-бы очень Вам
> благодарны!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/i/issues/395#issuecomment-114408158>.
>



-- 
З повагою, Поремчук Євгеній Володимирович
Мій сайто-блог - www.indev.org.ua
Web-інженерія - www.aisogroup.com <http://www.AisoGroup.com>
Початитись зі-мною:  ICQ  - 321 324 376

**Comment by bvv4ik** [comment]
можно со скролом, например...

**Comment by hordesalik** [comment]
скрол - вполне себе штатная ситуация. это быстрее, чем что то лепить ) а при желании потом можно и карту или другое решение сделать

**Comment by poremchuk** [comment]
Теж варіант.

2015-06-23 11:48 GMT+03:00 hordesalik <notifications@github.com>:

> скрол - вполне себе штатная ситуация. это быстрее, чем что то лепить ) а
> при желании потом можно и карту или другое решение сделать
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/i/issues/395#issuecomment-114409303>.
>



-- 
З повагою, Поремчук Євгеній Володимирович
Мій сайто-блог - www.indev.org.ua
Web-інженерія - www.aisogroup.com <http://www.AisoGroup.com>
Початитись зі-мною:  ICQ  - 321 324 376

**Comment by bvv4ik** [comment]
взял в работу @poremchuk

**Comment by bvv4ik** [comment]
я так понимаю - скроллы добавлены)

**Comment by poremchuk** [comment]
Я не додавав, так як не зміг запустити проект на локалі аби добратись до
дизайну.

On 5 July 2015 at 23:33, bvv4ik <notifications@github.com> wrote:

> я так понимаю - скроллы добавлены)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/i/issues/395#issuecomment-118666263>.
>



-- 
З повагою, Поремчук Євгеній Володимирович
Електропошта: e.poremchuk@gmail.com
Skype: aisogroup

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/8541029/9a37ffb2-2493-11e5-8848-96b19faccad1.png)


Скроллы добавлены , но нужно убрать нижний скролл

**Comment by bvv4ik** [comment]
нужно исправить, конечно, в рамках этой задачи... не стоит плодить их...

**Comment by RoOmel** [comment]
1. При выборе "Область" в выпадающем списке отображается "Київ" и "Київська" - это баг или так надо?;
2. При выборе "Київ" в выпадающем списке "Область" - отображается "Київ" - в чём задумка?;

**Comment by poremchuk** [comment]
Київ та Севастополь - міста зі-спеціальним статусом.
Конституція України, ч. 3 ст. 133



2015-07-08 11:35 GMT+03:00 RoOmel <notifications@github.com>:

>
>    1. При выборе "Область" в выпадающем списке отображается "Київ" и
>    "Київська" - это баг или так надо?;
>    2. При выборе "Київ" в выпадающем списке "Область" - отображается
>    "Київ" - в чём задумка?;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/i/issues/395#issuecomment-119495201>.
>



-- 
З повагою, Поремчук Євгеній Володимирович
Електропошта: e.poremchuk@gmail.com
Skype: aisogroup

**Comment by poremchuk** [comment]
Іншими словами - це територіальні одиниці вищого рівня.

2015-07-08 11:40 GMT+03:00 Євгеній Поремчук <e.poremchuk@gmail.com>:

> Київ та Севастополь - міста зі-спеціальним статусом.
> Конституція України, ч. 3 ст. 133
>
>
>
> 2015-07-08 11:35 GMT+03:00 RoOmel <notifications@github.com>:
>
>>
>>    1. При выборе "Область" в выпадающем списке отображается "Київ" и
>>    "Київська" - это баг или так надо?;
>>    2. При выборе "Київ" в выпадающем списке "Область" - отображается
>>    "Київ" - в чём задумка?;
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/e-government-ua/i/issues/395#issuecomment-119495201>.
>>
>
>
>
> --
> З повагою, Поремчук Євгеній Володимирович
> Електропошта: e.poremchuk@gmail.com
> Skype: aisogroup
>
>
>


-- 
З повагою, Поремчук Євгеній Володимирович
Електропошта: e.poremchuk@gmail.com
Skype: aisogroup

**Comment by RoOmel** [comment]
а при чём это здесь?

**Comment by poremchuk** [comment]
Що "это" ?

**Comment by RoOmel** [comment]
это - 3 вопроса выше по тексту...
 я не против того, что "Київ та Севастополь - міста зі-спеціальним статусом.
Конституція України, ч. 3 ст. 133", но как это связано с приложением?

**Comment by bvv4ik** [comment]
1. так надо
2. так надо
3. так надо
)

**Comment by RoOmel** [comment]
Нижний скролл убран.
Если 3 вопроса выше по тексту - так задумано - можно закрывать задачу.

**Comment by bvv4ik** [comment]
тогда прошу закрывать
