### ISSUE TITLE
Bank-id авторизація не відпрацьовує при увімкненому плагіні AdBlock Plus

### ISSUE THREAD

**Issue by poremchuk** [e-government-ua/i#396]
Друзі, наткнувся на вкрай не приємну штуку - у останньому Chrome не можу залогінитись через BankId при увімкненому плагіні AdBlock Plus. Причому авторизація на любих соц.мережах через OAuth2 працює у мене на проектах та на інших сайтах бездоганно. 

AdBlock Plus популярний плагін, а це означає що будуть проблеми у користувачів.

Процес:

1. Натискаємо на IGov з любого місця "увійти через BankID". 
2. Вибираємо ПриватБАнк
3. Телефон, пароль, СМС.
4. Редірект назад на Igov
5. Прохання залогінитись :)

**Comment by bvv4ik** [comment]
сообщите пожалуйста версию плагина и ФФ
покопаемся конечно, но, думаю, что тут дело в настройках плагина еще может быть... работа с БанкИД все-же может значительно отличаться от работы Вашего проекта, потому тут сложно сравнить

**Comment by poremchuk** [comment]
Діло у тому, що на УСІХ інших проектах в мережі на яких я авторизуюсь через
OAuth2 і подібні інтрументи - проблем немає. Проблема виникає тільки з
банкАЙДІ.

2015-06-23 14:45 GMT+03:00 bvv4ik <notifications@github.com>:

> сообщите пожалуйста версию плагина и ФФ
> покопаемся конечно, но, думаю, что тут дело в настройках плагина еще может
> быть... работа с БанкИД все-же может значительно отличаться от работы
> Вашего проекта, потому тут сложно сравнить
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/i/issues/396#issuecomment-114462733>.
>



-- 
З повагою, Поремчук Євгеній Володимирович
Мій сайто-блог - www.indev.org.ua
Web-інженерія - www.aisogroup.com <http://www.AisoGroup.com>
Початитись зі-мною:  ICQ  - 321 324 376

**Comment by poremchuk** [comment]
Adblock Plus 1.9
Chrome Версія 43.0.2357.130 m

**Comment by dirzhov** [comment]
У меня нет в хроме Adblock. После ввода телефона, пароля, СМС идет редирект на igov и бесконечно куртится прогрессбар.
Win7+Chrome 43.0.2357.124 m
Win7+Firefox 33.1.1

Из упавших риквестов:
https://poligon.igov.org.ua/api/service?nID=1
https://poligon.igov.org.ua/api/bankid/account?access_token=dbb7585b-7454-4a04-b94d-b5fc302e612c

Респонсы в урлах:
<h1>An error occurred.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>If you are the system administrator of this resource then you should check
the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>
<p><em>Faithfully yours, nginx.</em></p>

**Comment by bvv4ik** [comment]
@dirzhov это-ж полигон, на него постоянно что-то комитят, перегружают и т.д. потому случаются временные перебои в его работе... сейчас проверил - вроде все работает нормально

**Comment by dirzhov** [comment]
да, сейчас работает

**Comment by poremchuk** [comment]
Особисто я юзав продакт.

2015-06-24 13:30 GMT+03:00 bvv4ik <notifications@github.com>:

> @dirzhov <https://github.com/dirzhov> это-ж полигон, на него постоянно
> что-то комитят, перегружают и т.д. потому случаются временные перебои в его
> работе... сейчас проверил - вроде все работает нормально
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/i/issues/396#issuecomment-114818532>.
>



-- 
З повагою, Поремчук Євгеній Володимирович
Мій сайто-блог - www.indev.org.ua
Web-інженерія - www.aisogroup.com <http://www.AisoGroup.com>
Початитись зі-мною:  ICQ  - 321 324 376
