### ISSUE TITLE
Архів з паспортом не відкривається

### ISSUE THREAD

**Issue by poremchuk** [e-government-ua/i#397]
Друзі, перевірив можливість завантаження скан-копій паспорта з сайту Igov. Відкрити, на жаль
, не можливо.
![22 06](https://cloud.githubusercontent.com/assets/3364472/8286115/6fa3d430-1910-11e5-8d7f-16f4ea38e0b9.png)

**Comment by LamronNu** [comment]
Наскільки я зрозуміла -- цей функціонал ще у розробці (наповнення документами). Якщо подивитись на розмір файлу -- то там 0 байт, на що @bvv4ik мені відповів "это временно".

**Comment by bvv4ik** [comment]
@LamronNu права, это было неожиданно-вынужденное временное ограничение, и буквально "на днях" - оно будет снято) потому прошу - простить...

**Comment by bvv4ik** [comment]
это временное ограничение, завтро должно быть снято
