### ISSUE TITLE
В обратном адресе письма к гражданину писать адрес noreply@igov.org.ua вместо admin@igov.org.ua

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#398]
Сейчас  емейл уведомления гражданину отпраляются с адреса admin@igov.org.ua а
нужно с noreply@igov.org.ua

**Comment by uazure** [comment]
Может, noreply@igov.org.ua , как это принято для отправки уведомлений, не требущих ответа?

**Comment by bvv4ik** [comment]
мне больше нравится  noreply@igov.org.ua
но сейчас обсудим еще...

**Comment by VadymVolos** [comment]
noreply@igov.org.ua это хорошо, но когда юзер может отвечать на сообщения это лучше. Если нельзя отвечать Гугл, Майлюру, Яндекс заносят такие адреса в спам.

Поэтому желательно если юзер пишет на info@igov.org.ua нужно обязательно с этого адреса ему отвечать.

**Comment by kurbpa** [comment]
ему не нужно отвечать на эти сообщения. Это информационные  автоматические  оповещения.

**Comment by VadymVolos** [comment]
У меня есть статистика что от 10 до 20% все же отвечают.

**Comment by VadymVolos** [comment]
Оптимально желательно или подключить сервис рассылок, или попросить чтоб наши ребята сделали отслеживание открываемости писем. Когда процент откриваемости на каком-то из почтовых сервисов упал, это говорит о том что они занесли или адрес или весь домен с поддоменами в черный список. После этого идет процесс переписки с почтовым сервисом с просьбой убрать домен из под санкций, данная переписка может затягиваться на пару месяцев иногда и больше.

**Comment by bvv4ik** [comment]
готово
для теста: нужно заполнить заявку по услуге, например справка о несудимости

**Comment by NikitaLyah** [comment]
письмо все так же приходит от admin@igov.org.ua 
![screenshot_9](https://cloud.githubusercontent.com/assets/12964328/8324402/eede71ee-1a58-11e5-9f73-cd587ddec108.jpg)

**Comment by antonsych** [comment]
https://github.com/e-government-ua/i/issues/397
