### ISSUE TITLE
В теле письма гражданину необходимо отправлять другую иконку (сейчас отправляется иконка Днепропетровского гор.совета))

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#399]
вот пример иконки:

![image](https://cloud.githubusercontent.com/assets/4208821/8311147/de8bcd68-19dc-11e5-804d-a39a9e2683a9.png)

**Comment by bvv4ik** [comment]
нужна сама иконка

**Comment by VadymVolos** [comment]
Вот пару фоток герба http://abali.ru/?tag=%D0%B3%D0%B5%D1%80%D0%B1-%D1%83%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D1%8B

**Comment by bvv4ik** [comment]
попробуйте сейчас

**Comment by dgroup** [comment]
Коллеги есть детальный тест кейс? Может ли кто то описать как мне получить имейл с некорректной картинкой?

**Comment by ASkosyr** [comment]
вот здесь иконка не та
http://prntscr.com/7o42kt

**Comment by dgroup** [comment]
@ASkosyr, а Вы можете посмотреть имя картинки в имейле? :) Суть проблемы ясна, но я не знаю как воспроизвести кейс :)

**Comment by dgroup** [comment]
Заказал справку на свой имел через http://test.igov.org.ua - http://prntscr.com/7o4g5d, вообще иконки нет :).

**Comment by ASkosyr** [comment]
я так понимаю что по разному в разных браузерах отображается
у меня одно и то же письмо отображается с иконкой (http://prntscr.com/7o8ow4) и без (http://prntscr.com/7o8oio) если открываю в обычном Gmail но ноуте или в Google inbox.

по поводу айди картинки - вот
http://prntscr.com/7o8pq8

**Comment by bvv4ik** [comment]
в разных браузерах - видать ссылка не везде отрабатывает... с этим позже разберемся...
а по поводу иконки - нужно прост опоменять на бэке ссылку на новую, где будет другая уже иконка.. просто поискать в коде упоминание этой ссылки и заменить

**Comment by dgroup** [comment]
@ASkosyr, спасибо Вам за скрин с URL на картинку
@bvv4ik , так и хотел, поэтому попросил @ASkosyr предоставить имя/ссылку.

**Comment by bvv4ik** [comment]
Для теста:
просто заполнить форму гражданина и получить письмо

**Comment by smit-pb** [comment]
На данный момент в самом письме не отображается эконка (т.е. виден значек как будто не загрузилась картинка) а в мини инфо о письме - отображается герб днепр рады.
![gerb_01](https://cloud.githubusercontent.com/assets/12965717/8693166/becc15fc-2add-11e5-8e74-d7a489fa2b1f.png)
Тестирование проводилось на https://test.igov.org.ua/

Наверное задача требует доработки ?

**Comment by bvv4ik** [comment]
это у Вас, скорей всего, закешировалась старая картинка..
или отображается картинка профиля аккаунта iGov, которую тоже поправили.

а не отображаться может из-за прокси.
попробуйте отчистить кэши и/или переотослать заявку

**Comment by smit-pb** [comment]
Да - после чистки кеша - отображается значек IGOV
