### ISSUE TITLE
На главном портале, сделать кликабельными каунтеры услуг (готово, скоро, в работе) что бы при клике включался автоматом фильтр по ним.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#403]
![image](https://cloud.githubusercontent.com/assets/4208821/8310743/a581d73a-19da-11e5-8a64-66a6ab66eaf2.png)

Задачу по фильтрам реализовывал @glebzhebrakov , потому к нему стоит обратиться еред началом реализации, чтоб упростить задачу.

**Comment by glebzhebrakov** [comment]
нашел немного времени сегодня, готово, скоро запушу. по горячим следам так сказать

**Comment by glebzhebrakov** [comment]
готово
