### ISSUE TITLE
На дашборде вместо энкоденного в Base64 параметра авторизации "ACTIVITI_AUTH_BASIC" , добавить два раздельных параметра с логином и паролем, а энкодить его "на  лету"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#404]

**Comment by bvv4ik** [comment]
Для теста:
убедиться, что в проекте dashboard-js больше нет "ACTIVITI_AUTH_BASIC"

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/8693236/609e936e-2ade-11e5-9176-5e6272a7a59c.png)


Я так понял еще не убрали

**Comment by LamronNu** [comment]
не ту ветку смотрите. master -- это продакшн-сервер, туда все изменения позже попадают.
нужно смотреть ветку test

**Comment by VadimGulich** [comment]
Да , спасибо , уже увидел

**Comment by VadimGulich** [comment]
"ACTIVITI_REST": "",
 "ACTIVITI_USER": "",
Можно в релиз
