### ISSUE TITLE
На главном портале, в футере(внизу) справа, добавить еще одну ссылку

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#405]
Приєднатись <br>на GitHub
https://github.com/e-government-ua/i/wiki/%D0%AF%D0%BA-%D0%BF%D0%BE%D1%87%D0%B0%D1%82%D0%B8-%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D1%83
(самая правая)

**Comment by VadymVolos** [comment]
Дополнительное задание, по этой ссылке https://github.com/e-government-ua/i/wiki/%D0%AF%D0%BA-%D0%BF%D0%BE%D1%87%D0%B0%D1%82%D0%B8-%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D1%83
видео в хроме не воспроизводится, если есть файл с видео дайте видео, я залью на ютуб и вставлю ссылку в инструкцию "Як почати роботу"

**Comment by bvv4ik** [comment]
@VadymVolos
у меня воспроизвелось.. видать не скачан плагин ВебЭкс-а

**Comment by alexnikitchuk** [comment]
лінк є, відео відтворюється
