### ISSUE TITLE
Відсутність скролінгу у випадаючому спискові

### ISSUE THREAD

**Issue by polosatui** [e-government-ua/i#406]
Серйозність помилки:  S4 
Оточення: Windows 7 (x64) Firefox 38.0.5
Детальний опис помилки:
При виборі будь якої послуги, в "Крок 1. Оберіть свій регіон"  дропдаун розвертається повністю без можливості скролінгу.
Додаткова інформація для розробника: можливо варто зробити, наприклад, як на OLX при виборі міста.
Кроки відтворення:
1.Вибрати будь яку послугу 
2. Натиснути на дропдаун "Область" та "Місто"
3.Спостерігати результат
Очікуваний результат: Дропдаун "Область" та "Місто" мають можливість скролінгу. 
![2015-06-23_18-26-26](https://cloud.githubusercontent.com/assets/12971440/8311694/94c8eeaa-19e0-11e5-92c4-52cd4a670438.png)

**Comment by polosatui** [comment]
https://github.com/e-government-ua/i/issues/406

**Comment by bvv4ik** [comment]
дубль
https://github.com/e-government-ua/i/issues/395
