### ISSUE TITLE
Вмпадаючий список виходить за межі футера

### ISSUE THREAD

**Issue by polosatui** [e-government-ua/i#407]
Серйозність помилки: S3
Оточення: Windows 7 (x64) Firefox 38.0.5
Детальний опис помилки:
При виборі будь якої послуги, в "Крок 1. Оберіть свій регіон" дропдаун розвертається повністю та виходить за межі футера.
Додаткова інформація для розробника:
Кроки відтворення:
1.Вибрати будь яку послугу
2. Натиснути на дропдаун "Область" та "Місто"
3.Спостерігати результат
Очікуваний результат: Дропдаун "Область" та "Місто" не виходять за межі футера
![2015-06-23_18-26-26](https://cloud.githubusercontent.com/assets/12971440/8311953/87e8fbce-19e2-11e5-9420-e94936f8fb04.png)

**Comment by bvv4ik** [comment]
ДУБЛЬ https://github.com/e-government-ua/i/issues/395
