### ISSUE TITLE
Відсутність ряду населених пунктів Полтавської області у дропдауні "Місто"

### ISSUE THREAD

**Issue by polosatui** [e-government-ua/i#408]
Серйозність помилки: S3
Оточення: Windows 7 (x64) Firefox 38.0.5
Детальний опис помилки:
При виборі будь якої послуги, в "Крок 1. Оберіть свій регіон" в Полтавській області відсутній ряд міст:
1.смт Велика Багачка;
2. смт Диканька;
3. смт Козельщина;
4. смт Котельва;
5. смт Машівка;
6. смт Нові Санжари;
7. смт Оржиця;
8. смт Решетилівка;
9. смт Семенівка;
10. смт Чорнухи;
11. смт Чутове;
12. смт Шишаки.
Додаткова інформація для розробника: це населені пункти хоч і не є містами але вони районні центри.
Кроки відтворення:
1.Вибрати будь яку послугу
2. Натиснути на дропдаун "Область" потім "Місто"
3.Спостерігати результат
Очікуваний результат: Дропдаун "Місто" містить всі територіальні одиниці (25 шт)

**Comment by bvv4ik** [comment]
просто пока не заливали все населенные пункты... чтоб сейчас сэкономить ресурсы, и не создавать задач для более детального поиска(а он понадобится)
все это обязательно будет)
