### ISSUE TITLE
BankID: 502 Bad Gateway

### ISSUE THREAD

**Issue by Vanuan** [e-government-ua/i#409]
https://bankid.privatbank.ua/DataAccessService/das/authorize?response_type=code&client_id=9b0e5c63-9fcb-4b11-84ff-31fc2cea8801&redirect_uri=https://igov.org.ua:443/service/4/general/city/built-in/region/1/city/1/

**Comment by bvv4ik** [comment]
это было временная неработоспособность сервера БанкИД
но все уже наладилось
