### ISSUE TITLE
Изменить отображение  задач в списке

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#41]
Вместо  названия текущего этапа обработки заявки необходимо отображать:
Название услуги
Название текущего этапа
Дата подачи обращения

Источник - https://docs.google.com/a/privatbank.ua/document/d/1xueqPW0XqXBr_SPnBtBkwhI2CPxMKihzX9zDIsqBMc4/edit#

**Comment by bvv4ik** [comment]
уже реализовано дашборде
не актуально
