### ISSUE TITLE
[S4] - На дашборде не добавлена иконка-кнопка "скопировать в буфер обмена" на поле типа "textArea"

### ISSUE THREAD

**Issue by annasahi** [e-government-ua/i#413]
Окружение: 
Тестовый сервер: https://poligon.igov.org.ua/
Браузер: Google Chrome 40.0.2214.115 m, Firefox 36.0.4

Описание ошибки: 
Перейти на дашборд #527605 -  https://test.igov.org.ua/admin (логин demomvd и пароль demomvd).
Напротив полей типа "string" расположена иконка-кнопка "скопировать в буфер обмена", а напротив полей типа "textArea" такой иконки-кнопки нет.
![screenshot_6](https://cloud.githubusercontent.com/assets/10552086/8325435/53db23fe-1a62-11e5-8dcd-ba9e32abc268.png)

Ошибка относится к задаче  #379

**Comment by dmoskovsov** [comment]
@annasahi обновил фикс, пожалуйста проверьте.

**Comment by annasahi** [comment]
Протестировано
