### ISSUE TITLE
Доработка визуализации  при работе с обязательными полями на дашборде

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#414]
1. Необходимо отмечать  звуздечкой обязательные к заполнению поля.
2. Если  пользователь пытается отправить заявку, без заполнения обязательного поля, это поле и его название необходимо подсвечивать красным. Также необходимо дополнительно отображать  во всплывающем окне понятный текст сообщения с просьбой заполнить все обязательные поля.

Сейчас отображается ошибка, которая пользователей пугает - https://files.slack.com/files-pri/T040NRX6X-F06P03C4F/pasted_image_at_2015_06_24_11_12_am.png

**Comment by bvv4ik** [comment]
картинка не открывается

**Comment by kurbpa** [comment]
https://www.dropbox.com/s/z0hcyhpsc2220h6/error.JPG?dl=0 - вылил на дропбокс

**Comment by katebutenko** [comment]
для тестинга: 

Теперь явно видно required поле: http://screencast.com/t/eKAvkpLAIyKy
Поле комментария становится required если заявка отклоняется: http://screencast.com/t/arFW5E2X8
Если какие-то поля не заполнены, выводится понятная ошибка с перечислением незаполненных полей:
http://screencast.com/t/eKAvkpLAIyKy

(сейчас выводится первые 50 символов названия поля, можно будет сделать как-то аккуратнее в будущем)

**Comment by VadimGulich** [comment]
все ок )
