### ISSUE TITLE
[S3] - Для входа через BankID "ПриватБанк", при вводе логина из "подсказки автосохранения", в поле ввода "Логин" подгружается только 10 символов

### ISSUE THREAD

**Issue by annasahi** [e-government-ua/i#416]
Тестовый сервер: https://poligon.igov.org.ua/ 
Браузер: Google Chrome 43.0.2357.130 m

Шаги воспроизведения ошибки:
1. Выбрать услугу "Надання довідки про відсутність або наявніть судимості"
2. Выбрать свой регион (Днепропетровская область, город Днепропетровск)
3. Войти в систему через BankID - выбрать ПриватБанк
4. Кликнуть на поле ввода "Логин", после чего появится подсказка автосохранения (при условии, что вы уже посещали сайт)
5. Выбрать появившийся номер телефона, он должен отобразиться в самом поле ввода

Фактический результат:
В поле ввода подгружается номер телефона без последних трёх (3) цифр, из-за того, что автоматически не убираются пробелы (всего пробелов три и недостающих цифр тоже три)
![screenshot_7](https://cloud.githubusercontent.com/assets/10552086/8328232/90cdc61c-1a77-11e5-866d-01d741588a9c.png)

![screenshot_8](https://cloud.githubusercontent.com/assets/10552086/8328235/9915697e-1a77-11e5-9b0f-59edc1ee073e.png)

Ожидаемый результат:
Телефонный номер (логин) должен отображаться в подсказке с пробелами, а подгружаться без пробелов, как это происходит на странице авторизации Приват24
![screenshot_9](https://cloud.githubusercontent.com/assets/10552086/8328284/1cfaf6f0-1a78-11e5-9863-18420fa9cbf2.png)

![screenshot_10](https://cloud.githubusercontent.com/assets/10552086/8328286/232642d2-1a78-11e5-9ea3-47134ea92771.png)

**Comment by bvv4ik** [comment]
БанкИД не касается проекта iGov
им занимается Сергей Жук

**Comment by bvv4ik** [comment]
и по результату закрыть таску
