### ISSUE TITLE
Функционал [S4] - Отсутствует сообщение об ошибке "Необхідно заповнити." при незаполненном поля ввода контактного телефона на форме “Надання довідки про відсутність або наявніть судимості”

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#417]
Короткое описание: Функционал [S4] - Отсутствует сообщение об ошибке "Необхідно заповнити." при незаполненном поля ввода контактного телефона на форме “Надання довідки про відсутність або наявніть судимості”
Дата нахождения: 24.06.2015
Автор: RoOmel
Серьёзность: S4
Окружение (ОС, браузер): Windows 7x64, Mozilla Firefox 38.0
Детальное описание:
 Сообщение об ошибке указывает на необходимость ввода данных.
Доп. информация:
 Исходная задача https://github.com/e-government-ua/i/issues/370
Предусловия:
1. Пользователь авторизован и находится на форме "Крок 3." веб-страницы  "Надання довідки про відсутність або наявніть судимості";
2. Поле ввода "Контактний телефон:" очищено
Шаги воспроизведения: 
1. Нажать кнопку "Замовити послугу" в нижней части формы “Надання довідки про відсутність або наявніть судимості”;
Фактический результат:
![bug_igov_02](https://cloud.githubusercontent.com/assets/12996514/8328081/5f861074-1a76-11e5-8367-7832d55c3c39.jpg)
Ожидаемый результат:
Отображение сообщения об ошибке “Необхідно заповнити.”;

**Comment by bvv4ik** [comment]
1) задача не обязывала "сообщение об ошибке" там, где красная звездочка
2) контент в поле есть, потому там и нет красной рамочки
3) валидация поля с телефоном еще не реализована, а только в процессе и данной задачи не касается
