### ISSUE TITLE
Интерфейс [S4] - Отсутствует красная рамка обязательного поля ввода контактного телефона на форме “Надання довідки про відсутність або наявніть судимості”

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#418]
Короткое описание: Интерфейс [S4] - Отсутствует красная рамка обязательного поля ввода контактного телефона на форме “Надання довідки про відсутність або наявніть судимості”
Дата нахождения: 24.06.2015
Автор: RoOmel
Серьёзность: S4
Окружение (ОС, браузер): Windows 7x64, Mozilla Firefox 38.0
Детальное описание: Визуальное выделение полей обязательных для заполнения фокусирует внимание пользователя.
Доп. информация:
Исходная задача https://github.com/e-government-ua/i/issues/370
Предусловия:
1. Пользователь авторизован и находится на форме "Крок 3." веб-страницы  "Надання довідки про відсутність або наявніть судимості";
2. Поле ввода "Контактний телефон:" очищено;
Шаги воспроизведения: 
1. Нажать кнопку "Замовити послугу" в нижней части формы “Надання довідки про відсутність або наявніть судимості”;
Фактический результат:
![bug_igov_01](https://cloud.githubusercontent.com/assets/12996514/8328079/5a8cef02-1a76-11e5-956a-1ed0313b6b42.jpg)
Ожидаемый результат:
Поле ввода “*  Контактний телефон:” обведено красной рамкой;

**Comment by bvv4ik** [comment]
1) задача не обязывала делать красную рамочку там, где красная звездочка
2) контент в поле есть, потому там и нет красной рамочки
3) валидация поля с телефоном еще не реализована, а только в процессе и данной задачи не касается
