### ISSUE TITLE
dniprorada.igov.org.ua:  angular.module is not a function

### ISSUE THREAD

**Issue by Vanuan** [e-government-ua/i#419]
Grunt/Bower теперь не добавляет `angular` в папку `build/js`.

**Comment by bvv4ik** [comment]
не совсем понял...
что именно и где не работает?

**Comment by Vanuan** [comment]
1. Открыть https://dniprorada.igov.org.ua/
2. Открыть консоль
3. Увидеть ошибки 
```
Uncaught SyntaxError: Unexpected token <
Uncaught TypeError: angular.module is not a function"
```
4. Спиннер крутится бесконечно.

**Comment by bvv4ik** [comment]
это просто поломанный апликэйшин)
сисадмины дочинят(в процессе еще) и все там тоже будет норм...
