### ISSUE TITLE
[S3] - Теряется сессия

### ISSUE THREAD

**Issue by NikitaLyah** [e-government-ua/i#420]
При переходе на другие вкладки теряется сессия после чего нужно заново авторизироваться через BankID
Окружение (ОС, браузер): Не важно
*Шаги воспроизведения:* 
1.Зайти в раздел “Документы” - “Мои документы”
2.Авторизироваться через банкИД
3.Перейти на вкладку “Пошук документу за кодом”
4.Обратно перейти на вкладку “Мои документы”
*Фактический результат:*
Сессия оборвалась, для того чтоб посмотреть свои документу нужно опять авторизироваться через банкИД 
*Ожидаемый результат:* 
Сессия не обрывается

**Comment by bvv4ik** [comment]
какая задача тестировалась?
этот не баг, а просто функционал еще не реализован.
только в планах на реализацию...
