### ISSUE TITLE
Функционал [S3] -  Закрытие сессии и переход на страницу авторизации BankID при нажатии на клавиатуре "Backspace" на форме “Надання довідки про відсутність або наявніть судимості”

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#422]
Короткое описание: Функционал [S3] -  Закрытие сессии и переход на страницу авторизации BankID при нажатии на клавиатуре "Backspace" на форме “Надання довідки про відсутність або наявніть судимості”
Дата нахождения: 24.06.2015
Автор: RoOmel
Серьёзность: S3
Окружение (ОС, браузер): Windows 7x64, Mozilla Firefox 38.0
Детальное описание: 
Доп. информация:
Исходная задача #370
Предусловия:
1. Пользователь авторизован и находится на форме "Крок 3." веб-страницы "Надання довідки про відсутність або наявніть судимості";
2. Фокус ввода установлен вне поля ввода;
Шаги воспроизведения: 
1. Нажать на клавиатуре "Backspace";
Фактический результат:
![bug_igov_03](https://cloud.githubusercontent.com/assets/12996514/8329196/19fb5a1e-1a80-11e5-8277-00ef9b9bc286.jpg)
Ожидаемый результат:
Нажатие на клавиатуре "Backspace" выполняет свою прямую функцию только при заполнении полей ввода.

**Comment by bvv4ik** [comment]
БанкИД - это не проект iGov
им занимается Сергей Жук
прошу с ним связаться, если есть реальная ошибка, а эту таску закрыть, по результату
