### ISSUE TITLE
На главном портале, в профиле услуги, сделать возможность редактировать область на шаге выбора региона (не требуя завершения выбора города), но на шаге 2 - блокировать возможность редактировать место вообще(как и сейчас)

### ISSUE THREAD

**Issue by NikitaLyah** [e-government-ua/i#423]
Если пользователь ошибется и выберет не ту область то возможности изменить область - нет

*Шаги воспроизведения*
1. Зайти на "Надання довідки про відсутність або наявніть судимості"
2. Выбрать область "Днепропетровская"
3. Попытаться изменить область на другую

*Фактический результат:*
Комбобокс закрыт для выбора, перевыбрать область - невозможно

*Ожидаемый резальтат:*
Комбобокс открыт, возможность изменить область - есть

![screenshot_12](https://cloud.githubusercontent.com/assets/12964328/8329742/9c888070-1a84-11e5-8e43-1969893e8567.jpg)

**Comment by bvv4ik** [comment]
какая задача тестировалась?
это не баг а просто не реализованный функционал.
прошу отнести в группу фронтэнда, и убрать маркер баг
приоритет реализации - низкий

**Comment by NikitaLyah** [comment]
@bvv4ik проводилось иследовательское тестирование

**Comment by bvv4ik** [comment]
фронтэнд у нас:  Portal-Dashboard_NodeJS-Java
спасибо

**Comment by bvv4ik** [comment]
Решили: таки возможность редактирования нужно оставить до перехода на Шаг 2
прошу убрать Question

**Comment by VadimGulich** [comment]
Можно на боевой , протестировано
