### ISSUE TITLE
Интерфейс [S4] - Ошибка языка интерфейса в надписи поля ввода предыдущего ФИО (рус.) на форме “Надання довідки про відсутність або наявніть судимості”

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#424]
Короткое описание: Интерфейс [S4] - Ошибка языка интерфейса в надписи поля ввода предыдущего ФИО (рус.) на форме “Надання довідки про відсутність або наявніть судимості”
Дата нахождения: 24.06.2015
Автор: RoOmel
Серьёзность: S4
Окружение (ОС, браузер): Windows 7x64, Mozilla Firefox 38.0
Детальное описание: Язык интефейса для названий всех полей ввода должен быть одинаковым чтобы соблюдать консистентность.
Доп. информация:
Исходная задача #370
Предусловия:
1. Пользователь авторизован и находится на форме "Крок 3." веб-страницы "Надання довідки про відсутність або наявніть судимості";
Шаги воспроизведения: 
1. Найти название поля ввода “Попереднє ПІБ (рос.):”;
Фактический результат:
![bug_igov_04](https://cloud.githubusercontent.com/assets/12996514/8329762/b5482fe8-1a84-11e5-82fc-ea38dc0428ac.jpg)
Ожидаемый результат:
Отображение название поля ввода “Попереднє ПІБ (рос.):”;

**Comment by bvv4ik** [comment]
@kurbpa  Павел ,поправь плиз в БП

**Comment by kurbpa** [comment]
Не могу сказать что это ошибка. Это фича.
При заполнении формы, где данные нужно указать например на англ языке  требование об этом формулируется также на англ языке.

**Comment by bvv4ik** [comment]
@kurbpa
коллега сетует на "кляту россійську", в лєйбле)

**Comment by kurbpa** [comment]
я прекрасно понял. Ну не баг это.

**Comment by bvv4ik** [comment]
а, ну да, логично.. типа, третий пункт:
previous FN (eng.)

**Comment by RoOmel** [comment]
Если интерфейс будет на 3-х языках (рус/укр/англ) как тогда вы реализуете ввод данных?
Я не сетую на рус. яз., просто на одном языке это выглядит правильнее, ведь тут главное чтобы  ФИО было введено на рус. яз.

**Comment by bvv4ik** [comment]
"Если интерфейс будет на 3-х языках (рус/укр/англ) как тогда вы реализуете ввод данных?"
а как на ввод данных в поля влияет язык лэйблов?

"на одном языке это выглядит правильнее"
не соглашусь... вообще слово, "правильнее" - "не правильно"
(т.к. для этого должны существовать правила, а в данном случае это субъективно)

**Comment by Maximaximum** [comment]
Підтримую @RoOmel . Очікується введення прізвища користувача російською мовою, а не знання користувачем російської мови. Пропоную замінити "Предьідущее ФИО (рус.):" на "Попереднє ПІБ (рос.):"

**Comment by bvv4ik** [comment]
не будем устраивать тоталитаризм)
вообще в планах сделать локализацию портала на как минимум трех языках:
Украинском, Русском и Английском. (с легким переключением на тот язык, который человеку/гражданину комфортен)
А как только вступим в Евросоюз, то и остальные 20 языков добавим)

**Comment by Maximaximum** [comment]
Погоджуюся, не влаштовуймо тоталітаризм. Відштовхуймося від законодавства.
Наразі єдиною державною мовою України є українська. Єдиною мовою порталу є українська. Не українсько-англійсько-російська суміш, а українська мова.
Громадянин не зобов'язаний володіти ще якоюсь мовою, крім української, щоб отримувати послуги від держави.
Якщо будуть інші локалізації - чудово. Для когось це буде зручно. Але ж це будуть локалізації "англійська", "російська", "румунська", а не "англійсько-румунська", "російсько-китайська" і "румунсько-французька", правда ж?

**Comment by RoOmel** [comment]
Согласен, должна соблюдаться консистентность интерфейса.
Слово "правильнее" заменяю словом корректнее.

**Comment by bvv4ik** [comment]
тему закрываем

**Comment by Maximaximum** [comment]
А, ну так. "Не будем устраивать тоталитаризм" :)

**Comment by bvv4ik** [comment]
Для справки:
https://ru.wikipedia.org/wiki/%D0%A2%D0%BE%D1%82%D0%B0%D0%BB%D0%B8%D1%82%D0%B0%D1%80%D0%B8%D0%B7%D0%BC

просто тут работа... много работы... очень много работы...
я, конечно, поговорить о политике и жизни люблю, но не за счет работы и не на работе... с удовольствием-бы лично пообщался с интересным человеком, гденить в пабе, за кружечкой пива...
Вот, может, получится во Львов в июле поехать, так тогда мог-бы на обратном пути через Киев)

**Comment by Maximaximum** [comment]
Так, надзвичайно важко виправити один рядок, замість того щоб розводити термінологічно-філософську демагогію.
