### ISSUE TITLE
[S5] - Выпадающий список при выборе региона/города отображается ниже футера страницы.

### ISSUE THREAD

**Issue by NikitaLyah** [e-government-ua/i#425]
Окружение (ОС, браузер):  [не зависит от браузера]

*Фактический результат:*
![screenshot_13](https://cloud.githubusercontent.com/assets/12964328/8329959/9cd29938-1a86-11e5-976a-3d9fd2e42387.jpg)

*Ожидаемый результат:*
 Выпадающий список имеет скрол

**Comment by bvv4ik** [comment]
это не реализованный функционал, 
задача по которому уже есть в issue
