### ISSUE TITLE
[S4] - Нет валидации полей в форме отправки заяки

### ISSUE THREAD

**Issue by NikitaLyah** [e-government-ua/i#426]
*Детальное описание:*
Пример заявки : “Надання довідки про відсутність або наявніть судимості”
1.Создание заявки:
![screenshot_14](https://cloud.githubusercontent.com/assets/12964328/8330047/330d111c-1a87-11e5-8344-74a0695feb6e.jpg)
2. Заявка отправлена:
![screenshot_15](https://cloud.githubusercontent.com/assets/12964328/8330075/72dd967c-1a87-11e5-9f88-3375028a8155.jpg)

*Ожидаемый результат:*  
Валидация полей:
-поле дата рождения - ввод цифры и символ “ . ”
-место рождения -  ввод букв и символов “  - , / .”
-гражданство  - ввод буквы
-предыдущее ФИО - ввод букв и симвл “ - ”
-телефон - ввод цифр + проверка на формат телефона (380ххххххххх)
-почта - ввод латин. букв и символов “@ . _”  + проверка на формат  почты (@доменное имя)

**Comment by bvv4ik** [comment]
это не реализованный функционал а не баг!
задачи по валидации телефона и электронки уже созданы, в процессе реализации
цифровые поля тоже валидируются

остальное будет реализовываться по мере обьективной необходимости и приоритета
