### ISSUE TITLE
На главном портале, в профиле услуги, формат ФИО в Шаг 2 оставляем, а в завершающем диалоге оставляем только Имя и Отчество

### ISSUE THREAD

**Issue by NikitaLyah** [e-government-ua/i#427]
*Детальное описание:*
После отправки любой заявки ФИО пользователя отображается не корректно
![screenshot_16](https://cloud.githubusercontent.com/assets/12964328/8330192/417f1a8c-1a88-11e5-8951-0fa378a9a391.jpg)

*Ожидаемый результат:*
Последовательность Фамилия Имя Отчество

**Comment by bvv4ik** [comment]
это не баг а такая реализация,
прошу убрать маркер баг и добавить в группу по фронтэнду с пометкой "question"
будет обсуждено на селекторе и принято решение

**Comment by NikitaLyah** [comment]
@bvv4ik  я не знаю как у вас это реализовано, выглядит это как баг, по этому подобные задачи я буду заводить как баги

**Comment by bvv4ik** [comment]
@NikitaLyah
С чего Вы взяли, что должна быть именно та последовательность ФИО, о которой Вы говорите?

**Comment by bvv4ik** [comment]
фронтэнд у нас: Portal-Dashboard_NodeJS-Java
спасибо

**Comment by kurbpa** [comment]
Позвольте вставить 5 копеек с точки  зрения проэктировщика интерфейсов:
1. Крок 2: Ви увійшли як %Фамилия Имя Отчество% - всё же корректнее. Тем более что в  последующий БП применятеся именно такая очередность также.

2. На спасибо странице, при обращении к гражданину Достаточно просто Имени и Отчества (Фамилия избыточна).

**Comment by bvv4ik** [comment]
я-ж не против, но изначально так, кажется, даже в макете изначальном было... да и ни кого не смущало, предполагалось что так уважительней, т.к. не с Фамилии  начинаем...
сегодня обсудим.

**Comment by bvv4ik** [comment]
решили: формат ФИО в Шаг 2 оставляем
в завершающем диалоге оставляем только Имя и Отчество

прошу поправить задачуи убрать Question

**Comment by bvv4ik** [comment]
Для теста:
просто отработать услугу и посмотреть итоговый диалог

**Comment by NikitaLyah** [comment]
В чем проблема сделать очередность Фамилия Имя Отчество ? Ведь даже вы в своих комментариях используете аббревиатуру ФИО а не ИОФ @bvv4ik 
![screenshot_6](https://cloud.githubusercontent.com/assets/12964328/8539442/78c78cc6-2484-11e5-8a76-314c96179668.jpg)

**Comment by bvv4ik** [comment]
вопрос решенный, и не только мной... прошу проверять только в рамках поставленной задачи. если у Вас будет много желания, времени и сил подискутировать на эту или другую тему - прошу писать ее в списке в отдельном гуглофайле, и какнибудь когда их накопится достаточно много - смогу пересматривать их сам или передавать другим коллегам.. а потом, может по некоторым из них получится и обсудить голосом.
Но, прошу, не продолжать этот разговор в виде переписки через комменты... ну честно, очень мало времени и много работы.. и у Вас, как я вижу - тоже..
Спасибо!
