### ISSUE TITLE
При входе в “Мій журнал”, если возникает ошибка - отображать диалог с ней

### ISSUE THREAD

**Issue by NikitaLyah** [e-government-ua/i#428]
*Детальное описание:* 
После подтверждения входа на BankID происходит редирект на страницу с выбором варианта входа
ответ сервера:  {"error":"invalid_grant","error_description":"Invalid authorization code: ZcV7WS22315"}

*Ожидаемый результат:* 
Вход в меню “Мій журнал” ,  в случае ошибки вывод сообщения о ошибке.

**Comment by bvv4ik** [comment]
это еще не реализованный функционал,
прошу поместить в группу по фронту и убрать маркер баг
будет реализовано, но приоритет у такой доработки очень низкий

**Comment by bvv4ik** [comment]
фронтэнд у нас: Portal-Dashboard_NodeJS-Java
спасибо

**Comment by bvv4ik** [comment]
Решили: отображать диалог с ошибкой

**Comment by bvv4ik** [comment]
создана комплексная задача:
https://github.com/e-government-ua/i/issues/459
эту закрываем
