### ISSUE TITLE
[S2] - Перебирая nID_Subject в запросе  https://igov.org.ua/api/service/documents?nID_Subject=4260  можно получить ИНН и ФИО клиента

### ISSUE THREAD

**Issue by NikitaLyah** [e-government-ua/i#429]
*Детальное описание:* 
Пример полученных данных:
{"nID":2,"sName":"text/plain"},"sFile":"dd.txt","oDate_Upload":1420063200000,"sID_Subject_Upload":"2","sSubjectName_Upload":"ПриватБанк","oSubject_Upload":{"nID":1,"sID":"ПАО","sLabel":"ПАО ПриватБанк","sLabelShort":"ПриватБанк"},"oSubject":{"nID":2,"sID":"2872618515","sLabel":"Белявцев Владимир Владимирович","sLabelShort":"Белявцев В. В."}}]

*Ожидаемый результат:* 
Нет возможности получения данных о 3-их лицах

**Comment by bvv4ik** [comment]
@OlgaTurenko 
Ольга, точно защита стоит по "nID_Subject=4260" для метода getDocuments?

**Comment by OlgaTurenko** [comment]
я так поняла, что жалоба на то. что вместе с ид-ко подтягивается ФИО и ИНН а не должно по мнению Никиты.
И про защиту по этому методу. защиту как делали - брали из параметров запроса ид-ку сабджекта и сверяли в ответном. В этом методе мы берем эту ид-ку и делаем селект по ид-ке. Тоесть там не никак не те не могут быть

**Comment by bvv4ik** [comment]
@NikitaLyah 
Никита, прошу дать такой-же УРЛ на полигоне. т.к. на полигоне уже все пофиксино, вроде как

@OlgaTurenko
не, тут речь именно о получении списка не своих документов

**Comment by bvv4ik** [comment]
@NikitaLyah 
на все эти запросы:
https://igov.org.ua/api/service/documents?nID_Subject=4260
https://igov.org.ua/api/service/documents?nID_Subject=4261
https://igov.org.ua/api/service/documents?nID_Subject=4262
будет всегда один ответ)

и это данные исключительно того пользователя который авторизовался

**Comment by bvv4ik** [comment]
прошу перепроверить. там все норм, вроде как

**Comment by hordesalik** [comment]
может тогда и не стоит сабжект ид передавать раз всегда отдаются "мои документы"

**Comment by VadimGulich** [comment]
На боевом уже исправлено https://igov.org.ua/

**Comment by bvv4ik** [comment]
так и на тестовом тоже)

**Comment by bvv4ik** [comment]
@hordesalik
"может тогда и не стоит сабжект ид передавать"
да, он со временем уберется за ненадобностью (обычного пользователя это вообще не должно беспокоить)
