### ISSUE TITLE
[S4] - Дублируется результат поиска области

### ISSUE THREAD

**Issue by NikitaLyah** [e-government-ua/i#430]
*Шаги воспроизведения:*
1.Перейти в “Послуги” - “Надання довідки про відсутність або наявніть судимості” ;
2.В поле поиска области ввести “Ки”.

*Фактический результат:*
![screenshot_17](https://cloud.githubusercontent.com/assets/12964328/8330411/de37300c-1a89-11e5-8f20-94b17c6ddf10.jpg)

*Ожидаемый результат:* 
Результат поиска один, не дублируется.

**Comment by bvv4ik** [comment]
ага, дубль, поправим

**Comment by bvv4ik** [comment]
прошу занести в группу фронтєнда

**Comment by bvv4ik** [comment]
фронтэнд у нас: Portal-Dashboard_NodeJS-Java
спасибо

**Comment by bvv4ik** [comment]
один пункт переименован в Киев

**Comment by NikitaLyah** [comment]
@bvv4ik  Почему нельзя убрать дубль? Получается область "Киев" и город надо тоже выбрать "Киев"
![screenshot_4](https://cloud.githubusercontent.com/assets/12964328/8425342/899889b4-1f0d-11e5-8753-216540dbe0da.jpg)

**Comment by bvv4ik** [comment]
Так устроено наше административное деление, что Севастополь и Киев являются отдельными административными единицами!  Получается, что Киев - это область и Киевская область - это область)
Кстати, на сколько я знаю - готовится сейчас законопроект, который наконец устранит эту коллизию... потому, не имеет смысла перестраивать глобально систему взаимосвязей Регион-Город, ради этого случая (а по другому и не получится)
