### ISSUE TITLE
[S1] Функціонал сайту недоступний при відключенні JavaScript

### ISSUE THREAD

**Issue by polosatui** [e-government-ua/i#431]
Серйозність помилки: [S1]
Оточення: Windows 7 (x64) Google Chrome 43.0.2357.130 m
Детальний опис помилки:
При відключенні JavaScript не прогружається контент та не працюють лінки розділів на хедері.
Додаткова інформація для розробника:
Кроки відтворення:
1.Відключити JavaScript
2. Зайти на https://poligon.igov.org.ua/
3.Спостерігати результат
Очікуваний результат: При відключенні JavaScript ключовий функціонал доступний
![2015-06-24_16-10-00](https://cloud.githubusercontent.com/assets/12971440/8330922/83c51932-1a8d-11e5-8557-77ce8ab236df.png)

**Comment by bvv4ik** [comment]
без яваскрипта тут делать нечего)

**Comment by polosatui** [comment]
а что делать тем у кого его нет? 
на старіх телефонах, например?

**Comment by bvv4ik** [comment]
иди в магазин - покупать новый телефон)

ради 1-2-х динозавров мы не будем занимать отдельно штат разработчиков, чтоб делать полную копию портала без яваскрипта(что, по сути, вообще невозможно для данного уровня сложноси, ИМХО)

я понимаю еще поддержку для людей с ограниченными физическими возможностями - это святое... но... потакать таким вещам - совсем некомильфо

**Comment by polosatui** [comment]
ок, нонял)
