### ISSUE TITLE
Функционал [S3] - Отсутствует валидация полей обязательных для ввода на форме “Надання довідки про відсутність або наявніть судимості”

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#432]
Функционал [S3] - Отсутствует валидация полей обязательных для ввода на форме “Надання довідки про відсутність або наявніть судимості”
Дата нахождения: 24.06.2015
Автор: RoOmel
Серьёзность: S3
Окружение (ОС, браузер): Windows 7x64, Mozilla Firefox 38.0
Детальное описание:
 Отсутствует валидация полей обязательных для ввода
"* Дата народження:";
"* Місце народження:";
"* Громадянство:";
"* Мета отримання довідки:";
"* Контактний телефон:" - валидация на ввод цифр выполняется, но не на их количество;
"* Ваш e-mail:"
Доп. информация:
Исходная задача #370
Предусловия:
1. Пользователь авторизован и находится на форме "Крок 3." веб-страницы "Надання довідки про відсутність або наявніть судимості";
2. Фокус ввода установлен вне поля ввода;
Шаги воспроизведения: 
1. Заполнить любыми символами все поля в любом количестве;
2. Заполнить поле "* Контактний телефон:" цифрами в любом количестве;
3. Нажать кнопку "Замовити послугу";
Фактический результат:
![bug_igov_05_01](https://cloud.githubusercontent.com/assets/12996514/8330635/5bbfcbf0-1a8b-11e5-90ed-699d84086e74.jpg)
![bug_igov_05_02](https://cloud.githubusercontent.com/assets/12996514/8330636/5bd8ac42-1a8b-11e5-810e-23163fafa592.jpg)
![bug_igov_05_03](https://cloud.githubusercontent.com/assets/12996514/8330637/5be2b3fe-1a8b-11e5-9a48-570fdd10b242.jpg)
![bug_igov_05_04](https://cloud.githubusercontent.com/assets/12996514/8330638/5be32636-1a8b-11e5-8724-7902e1dc4634.jpg)
Ожидаемый результат:
Осуществляется валидация полей ввода

**Comment by bvv4ik** [comment]
issue дублирующаяся
уже отпиисывался:
сейчас ртолько реализуются задачи по валидации телефона и емэйла
номерные поля валидируются..
остальное - пока реализовывать не будем,

**Comment by RoOmel** [comment]
issue не дублируется с моими задачами, т.к. про валидацию вводимых данных я ранее задач не заводил.
Были две задачи по атрибутам mandatory field.

**Comment by bvv4ik** [comment]
я про эту:
https://github.com/e-government-ua/i/issues/426
