### ISSUE TITLE
На бэке(wf-base), при отправке формы гражданином, если поле типа file отмечено как requred=false, то допускать его незаполненность и пропускать в листенере (FileTaskUploadListener)

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#433]
Необходимо  реализовать возможность  отправки заявки  если часть файлов в заявке обязательны к загрузке( и загружен), а часть - необязательны и не загружен.

Сейчас возникает ошибка.

**Comment by bvv4ik** [comment]
Выбрать услугу:
"Надання витягу з технічної документації про нормативну грошову оцінку земельної ділянки"
Луцк
Там заполнить все поля и выбрать первые 4-ре файла (последний, 5-й не выбирать)
Сабмитить и все должно отработаться и выдаться номер заявки.

**Comment by kurbpa** [comment]
"ВАЖНО: Для БА, в БП нужно в поле типа file указывать default=" " (именно с пробелом)"

для всех полей этого типа или только для необязательных ?

**Comment by bvv4ik** [comment]
только для необязательных!
