### ISSUE TITLE
Доработка  формы печати заявления на дашборде

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#434]
- [ ] 1) Если форма  содержит очень большое количество полей, то  форма после нажатия на кнопку "Роздрукувати"  становится доступна только после  скролинга страницы ( см. скрин).
Дефект  воспроизводится на заявке id=652920
(логин/пароль на  полигонный дашборд: test_tern_oda1)

- расположить ее по центру, задать вменяемую высоту, и, наверно в этом див-е сделать скрол...

После нажатия на  кнопку печати  на этом всплывающем окне, осуществляется переход на новую вкладку браузера и стартуем механизм печати. Было бы логично если б при этом всплывающее окно  закрывалось.
![error- task 652920](https://cloud.githubusercontent.com/assets/11442397/8334459/b4053164-1aa0-11e5-848e-949b6f846800.JPG)

- [ ] 2) "зона кликабельности" кнопки Х - смещена

- нужно поправить.

**Comment by VadimGulich** [comment]
Проверялось на : https://test.igov.org.ua:6948/login  
Задача не реализована

**Comment by RoOmel** [comment]
Окно предварительного просмотра не закрывается при нажатии на пиктограмму "Х".
Кнопка "Роздрукувати" видна только после скроллинга страницы.
Интуитивно не понятно где страница предварительного просмотра.

**Comment by bvv4ik** [comment]
"RoOmel commented an hour ago"
Окно предварительного просмотра не закрывается при нажатии на пиктограмму "Х

**Comment by RoOmel** [comment]
kurbpa
Павел, по свободе просмотрите, плиз
https://github.com/e-government-ua/i/issues/485

**Comment by kurbpa** [comment]
@RoOmel 
@bvv4ik 
#485  изучил.

п.2 и п.3 дублируют по сути описанную мною текущую задачу и должны быть устранены в ходе фикса текущей задачи.

Относительно возможности "закрыть":
Окно закрывается, но зона клика очень маленькая и смещена  вправо-вверх относительно пиктограмы Х

**Comment by bvv4ik** [comment]
@kurbpa 
@RoOmel
ну то что я и говорил, по крестику - он работает, хоть и смещен, но это не одно и то-же
(дописал пунктом в ЭТОЙ задаче - ПОПРАВИМ)
а по остальным - дубль

**Comment by VadimGulich** [comment]
Проверялось на :https://test.igov.org.ua/admin
Задача не реализована

**Comment by bvv4ik** [comment]
да. действительно с ней задержка... убрал маркеры

**Comment by bvv4ik** [comment]
Для теста:
просто зайти на дашборд под акаунтом (указанном в этой таске) и во "В работе" выбрать задачу 652920 или другую с большим количеством полей

**Comment by OlgaKotova** [comment]
1) всплывающее окно закрывается после перехода на страницу печати - фикс.
2) для всех трех форм, доступных в меню "В роботі" баг повторяется - всплывающее окно видно только после скролинга страницы вверх. 
3) после нажатия на кнопку "Роздрукувати" и скрола страницы, при открытии док-та для печати боковая панель задач не скрывается или размер окна при открытии задачи на печать не форматируется под всплыв.окно. Чтобы скрыть боковую панель нужно проскролить само всплывающее окно. На мувике видно детали http://screencast.com/t/G5YUldxD .

Тестила на MAC OS X 10.10.4 в Safari 8.0.7.

**Comment by OlgaKotova** [comment]
@AleksejDomash @bvv4ik 
Теперь заявка вообще на дает возможности открыть всплыв. окно для печати. После нажатия на кнопку "Распечатать" открываеться окно ошибки с текстом "Не всі поля заповнені!".
На скрине http://screencast.com/t/rjFnYWff отметила нужное поле.

**Comment by bvv4ik** [comment]
@OlgaKotova так и не должно давать, пока не все ОБЯЗАТЕЛЬНЫЕ поля заполнены...

**Comment by bvv4ik** [comment]
@AleksejDomash п.2-3, похоже действительно недоработка (на видео очень хорошо видно)

**Comment by OlgaKotova** [comment]
@bvv4ik дело в том, что в первый раз, когда я тестила, форма давала доступ к печати

**Comment by bvv4ik** [comment]
@OlgaKotova тогда, скорее, это в прошлый раз была недоработка) т.к. не должно было давать, если поля есть незаполненные...

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/8900553/ba09e376-3449-11e5-952d-08eb627b937f.png)


Ошибка при нажатии на кнопку "Роздрукувати "  по любо из заявок

**Comment by serdyuk-alex** [comment]
Починил

**Comment by OlgaKotova** [comment]
@serdyuk-alex ну как бы все-равно скролить вверх нужно http://screencast.com/t/D7NzPNMCZgb
@bvv4ik проверьте, пжл, по мувику, если все устраивает, закрываем.

**Comment by serdyuk-alex** [comment]
Какова ситуация на других браузерах?

**Comment by OlgaKotova** [comment]
@serdyuk-alex в firefox и chrome на MAC OS ситуация такая же, на Windows у меня нет возможности проверить

**Comment by serdyuk-alex** [comment]
Проверил на тестовом сервере, почему-то моего комита там нету, там старые стили валяются.
@bvv4ik, у нас что-то с деплоем не то?
https://jenkins.igov.org.ua/view/new/job/central_alpha/2468/ - вот сборка собралась успешно вчера, правда сегодня последние несколько не собираются

**Comment by bvv4ik** [comment]
чтоб продеплоить на фронт дашборда - нужно ручками джоб дженкинса запускать, и указівать там галочку UI

**Comment by serdyuk-alex** [comment]
Посмотрел на тест-сервере, мои стили подхватились, просьба проверить

**Comment by OlgaKotova** [comment]
проверила, все исправлено 
закрываю
