### ISSUE TITLE
На главном портале, сортировать Области и Города в комбобоксе формы услуги - по алфавиту

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#435]

**Comment by bvv4ik** [comment]
Для теста:
просто убедиться, что сортировка городов и регионов правильная в профиле услуги

**Comment by VadimGulich** [comment]
Города - реализовано по алфавиту 
Регион  - не реализовано
нужно доработать

**Comment by VadimGulich** [comment]
По  городам и регионам реализован алфавитный порядок , задачу закрываю , но нужно будет подправить баг https://github.com/e-government-ua/i/issues/488

**Comment by uazure** [comment]
Как на счет сортировать вначале по доступности города, а затем по алфавиту?
