### ISSUE TITLE
Функціонал [S3] При масштабуванні вікна браузера на половину меню хедера видає лише категорію "Послуги" (не працюючу)

### ISSUE THREAD

**Issue by polosatui** [e-government-ua/i#436]
Серйозність помилки: S3
Оточення: Windows 7 (x64) GC 43.0.2357.130 m
Детальний опис помилки:
При масштабуванні вікна браузера на половину, меню хедера видає лише категорію "Послуги" (не працюючу) (1) + всі посилання з футера злізають (2)

![2015-06-24_22-29-02](https://cloud.githubusercontent.com/assets/12971440/8339698/0eef24a6-1ac2-11e5-86bf-1ee3427566e8.png)
![2015-06-24_22-29-51](https://cloud.githubusercontent.com/assets/12971440/8339725/3e604a9e-1ac2-11e5-81a6-d406d9c28ef6.png)

**Comment by bvv4ik** [comment]
Еще не адаптировали полноценно под мобильные,
прошу:
-убрать лэйбл баг,
-добавить лэйбл "question"
-поместить в группу фронтэнда
и? рассмотрим вопрос о приоритете этой доработки... затем подправим формулировку

**Comment by bvv4ik** [comment]
Просьба перенести эту issue в бэклог и закрыть ее:
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit
