### ISSUE TITLE
[S5] Неповний переклад інформаційної довідки в Bank ID 

### ISSUE THREAD

**Issue by polosatui** [e-government-ua/i#437]
Серйозність помилки: [S5]
Оточення: Windows 7 (x64) GC 43.0.2357.130 m
Детальний опис помилки:
При переході на Англ. або Рос мову інформаційна довідка перекладається не повністю
![2015-06-24_22-45-57](https://cloud.githubusercontent.com/assets/12971440/8339903/90d83bc8-1ac3-11e5-8c83-d039da9c29b4.png)

**Comment by bvv4ik** [comment]
это к порталу не относится, прошу задачи по БанкИД не ставить в ГитХаб-е по порталу... 
Ответственный за БанкИД - Сергей Жук

можно переносить в отдельную группу или ассигнуть сразу на него

**Comment by polosatui** [comment]
а можно его ник, а то найти не могу

**Comment by SergeyZhukDP** [comment]
Коллеги, это не баг, эту часть просто еще физически не делали. Сейчас не до этого, но спасибо.
