### ISSUE TITLE
Проблема работы с сессиями на портале

### ISSUE THREAD

**Issue by annasahi** [e-government-ua/i#438]
На странице "Документы" и "Мой журнал" при каждом обновлении страницы или переходе с одного раздела в другой необходимо проходить повторную авторизацию.
(Авторизация была через ПриватБанк)

**Comment by LamronNu** [comment]
https://github.com/e-government-ua/i/issues/420

**Comment by bvv4ik** [comment]
этот функционал не был реализован!
только сегодня ночью была вылита доработка, которая позволяет авторизовавшись в Моих документах потом переходить без авторизации в Журнал...

но эта доработка еще в процессе, там багу нужно пофиксить при работе с подзакладками.

потому - таску закрываю, как разработчик завершит - она будет передана на тестирование
