### ISSUE TITLE
[S3] - Нет возможности повторного выбора "Области"

### ISSUE THREAD

**Issue by annasahi** [e-government-ua/i#439]
Шаги воспроизведения:
1. Выбор услуги "Надання довідки про відсутність або наявніть судимості"
2. В Шаге №1 "Оберіть свій регіон" в поле "Область" выбрать "Дніпропетровська" 

Фактический результат:
Нет возможности повторно выбрать область, http://screencast.com/t/QJKogD55 -- видео воспроизведения

**Comment by LamronNu** [comment]
дубль: https://github.com/e-government-ua/i/issues/423
