### ISSUE TITLE
На главном портале исправить орфографические ошибки

### ISSUE THREAD

**Issue by annasahi** [e-government-ua/i#440]
- [x] Ошибка в тексте (https://igov.org.ua/journal/bankid) "Щоб почати користуватись сервісом “Мій журнал”, увійдіть через BankID або через електронно-ціфровий підпис". Ошибка - "ціфровий".
- [x] Ошибка в тексте (раздел "Послуги") "РеєстраційнИ дані". Ошибка - остання літера в слові "РеєстраційнІ".
- [x] Раздел "Освіта". В подразделах идёт перечень услуг с использованием словосочетания "надання ліцензіЯ", правильно употреблять "надання ліцензіЇ".
- [x] Ошибка в слове "Днепропетровск" на странице "Про портал", в таблице "Велика подяка ІТ-волонтерам..." (https://poligon.igov.org.ua/about). (Заходим на страницу, жмем <F3> 
в окне поиска набираем Днепропетровск и,как минимум, три ошибки)

**Comment by bvv4ik** [comment]
только по поводу п.4. - не понял.
в чем ошибка?

**Comment by annasahi** [comment]
Пункты 2 и 4 уже исправлены.

**Comment by bvv4ik** [comment]
а зачем опять переоткрыта таска?

**Comment by annasahi** [comment]
Нечаянно нажала на закрытие, потом открыла заново, т.к. П. 1 и 3 не исправленны.

**Comment by bvv4ik** [comment]
как не выполнены? можно скрин плиз?
в первом коменте как раз они-то и были выполненны,  и небыл понятен только п.4.

**Comment by LamronNu** [comment]
п. 4: 
![image](https://cloud.githubusercontent.com/assets/8156670/8452558/8f49514e-1ff4-11e5-8aca-e1c1d16ff141.png)

**Comment by bvv4ik** [comment]
"набираем Днепропетровск"
я это и набирал... + 3-е название все-же корректное.
два остальных - поправлены!

**Comment by annasahi** [comment]
Если ещё актуально

**Comment by annasahi** [comment]
Если ещё актуально
![screenshot_1](https://cloud.githubusercontent.com/assets/10552086/8453007/ddf3d0ae-1ff8-11e5-9f98-fbf8ce79a9a8.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/10552086/8453010/e75a1afe-1ff8-11e5-8163-15ea3cac6af8.png)

**Comment by bvv4ik** [comment]
Я, честно. не понимаю - где Вы это видите...?
на каком сервере смотрите? на https://test.igov.org.ua ?

![image](https://cloud.githubusercontent.com/assets/4208821/8454150/da5163e8-2003-11e5-993c-d72617a4432c.png)

![image](https://cloud.githubusercontent.com/assets/4208821/8454265/ccdfd9d2-2004-11e5-9740-ba1ade3e1e88.png)

**Comment by VadimGulich** [comment]
Все исправлено
