### ISSUE TITLE
Функционал [S3] - Не работает ссылка "Натисніть тут" при верификации используя сервис Приват24

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#441]
Короткое описание: Функционал [S3] - Не работает ссылка "Натисніть тут" при верификации используя сервис Приват24
Дата нахождения: 25.06.2015
Автор: RoOmel
Серьёзность: S3
Окружение (ОС, браузер): Windows 7x64, Mozilla Firefox 38.0
Детальное описание: 
Доп. информация:
Исходная задача #370
Предусловия:
1. Пользователь находится на странице верификации используя сервис Приват24
Шаги воспроизведения: 
1. Нажать на ссылку "Натисніть тут";
Фактический результат:
![bug_igov_06](https://cloud.githubusercontent.com/assets/12996514/8356813/39e61388-1b60-11e5-9af9-932e8f6cf2b3.jpg)
Ожидаемый результат:
Осуществляется отправка повторного СМС

**Comment by bvv4ik** [comment]
просьба не создавать таски по Банк ИД.
т.к. он не является частью портала!
Прошу обращаться напрямую к Сергею Жуку

**Comment by RoOmel** [comment]
Я его не знаю, можно ссылку на его контакт?

**Comment by bvv4ik** [comment]
конечно:
Скайп: szhuk75
Электронка: sergej.zhuk@privatbank.ua
