### ISSUE TITLE
На главном портале, в профиле услуги, при выборе области (например Львовской) - не отображаются все нужные диалоги об отсутствии услуги (в т.ч. кнопки соцсетей), а должно отображаться.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#442]
Например:
https://igov.org.ua/service/17/general

![2015-06-25 19 40 37](https://cloud.githubusercontent.com/assets/4208821/8360006/a3b6e780-1b72-11e5-94c0-f08272aa8d78.png)

**Comment by bvv4ik** [comment]
готово

**Comment by polosatui** [comment]
фсьо працює, тільки треба виправити літеру у слові пришвидЧити на пришвидШити

**Comment by bvv4ik** [comment]
пофиксил)
