### ISSUE TITLE
На главном портале, в профиле услуги, при выборе области, если хоть одна область находится с услугой - не дает возможности выбрать город, а сразу переходит к шагу 2, а должно давать возможность выбрать и другие города

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#443]
Например:
https://igov.org.ua/service/17/general

т.е. наличие областной услуги не должно блокировать возможность размещать там и городские

**Comment by bvv4ik** [comment]
эта задача решится автоматически, при решении корневой:
https://github.com/e-government-ua/i/issues/550

**Comment by smit-pb** [comment]
Работает.
