### ISSUE TITLE
На главном портале, в расширенном фильтре добавить еще фильтр, комбо-боксы "область" и "город", которые появляются при выборе соседнего фильтра в состояние "Доступны онлайн"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#444]
Комбобоксы(автокомплиты) взяь те-же, что и в профиле услуги.

Выбирать только те услуги где есть подуслуги с заданной областью или городом

**Comment by poremchuk** [comment]
Формуються різні випадаючі списки: одні через <select>-><value> інші через <ul><li>. Потрібно привести до одного вигляду усі списки на порталі.

**Comment by bvv4ik** [comment]
в данной таске вообще нужно использовать "typeahead", для таких списков городов/регионов... точно так-же, как это реализовано в профиле услуги.

пока что, приводить все к одному виду не стоит, окончательно не решили - какой из вариантов наиболее практичным будет... ну и этой таски оно точно не касается..

**Comment by poremchuk** [comment]
Чому не торкається? У фільтрі все на селектах, а моделі що повертають міста та регіони працюють зі-списками.

**Comment by bvv4ik** [comment]
там пусть и остаются селекты, а тут нужны списки. одно другому не мешает.

**Comment by serdyuk-alex** [comment]
Для теста необходимо зайти на централ борду и поиспользовать поиск как обычный так и extended версию

**Comment by RoOmel** [comment]
Поиск работает корректно в обычном и расширенном режимах
