### ISSUE TITLE
[S4] Відсутній контент в закладці "Мій журнл" після переходу на неї із закладки "Про портал"

### ISSUE THREAD

**Issue by polosatui** [e-government-ua/i#445]
Серйозність помилки: [S4]
Оточення: Windows 7 (x64) Google Chrome 43.0.2357.130 m
Детальний опис помилки:
Відсутній контент в закладці "Мій журнл" після переходу на неї із закладки "Про портал".

**Comment by bvv4ik** [comment]
а можно скрин, плиз?

**Comment by polosatui** [comment]
уже норм, то видимо ночной комит виноват был)

**Comment by polosatui** [comment]
а хотя нет, после многоразовых повторений таки не работает
![2015-06-26_9-04-01](https://cloud.githubusercontent.com/assets/12971440/8371589/72c948fa-1be2-11e5-9500-eecb6f9575de.png)

**Comment by bvv4ik** [comment]
от-бы хоть закономерность установить...

**Comment by polosatui** [comment]
Послуги-Документи - Мій журнал - Про портал - Мій журнал

**Comment by VadymVolos** [comment]
Я сейчас открыл посмотреть, тоже контента нет, пустая страница.
Но после обновления, появился кружочек мол страница грузится, и загрузилась.

Первый раз кружочка загрузки не появлялось, наверно запрос не был отправлен.

**Comment by VadymVolos** [comment]
Нашел закономерность, когда нажимаете кнопку "Мій журнал" открывается страница.
При открытой странице еще раз нажмите не кнопку "Мій журнал" и контент со страницы пропадет.

**Comment by VadymVolos** [comment]
И аналогично страница "Документи" когда она открыта если повторно нажать на кнопку "Документи" контент со страницы пропадет.

**Comment by VadimGulich** [comment]
Нужно доработать!

Ошибка №1 : После входа через ID Bank на время открывается форма с авторизацией, после   чего загружается меню "Мой журнал"
Шаги: 
1) Войти в меню "Мой журнал" 
2) Авторизоваться через  ID Bank
Фактический результат: Кратковременно открывается форма с авторизацией в меню "Мой журнал"
Ожидаемый результат: Отображается анимация загрузки пока не загрузится меню

 Ошибка №1 : Постоянно висит анимация загрузки
Шаги: 
1) Войти в меню "Мой журнал" 
2) Авторизоваться через  ID Bank
3) Обновить страницу
Фактический результат: Постоянно висит анимация загрузки
Ожидаемый результат: Меню загружается

Если возможности доработать нет в рамках этой задачи , прошу оставить коммент и будет отдельно заведен баг.
