### ISSUE TITLE
Bug: Раздел послуги, для бiзнесу, медицина.

### ISSUE THREAD

**Issue by Alienhub** [e-government-ua/i#446]
Раздел: Бизнсу-Медицина, отсутсвует иконка (Всi послуги) под разделом Медицина, а должна быть, во всех других разделах она присутсвует.
S3, Windows 7, 64-bit, Mozilla 38.0.5, Chrome Version 43.0.2357.130m

Steps to reproduce:
1. Launch web-site "poligon.igov.org.ua".
2. Click item "Poslugy".
3. Find item "Bisnesy".
4. Find item "Medicine".

Expected result:
Item "Vsi poslugy" should be under the section of Medicine.

Actual result:
No required item "Vsi poslugy". 

![bug](https://cloud.githubusercontent.com/assets/13061861/8374496/865e75fe-1bfe-11e5-8906-7948a1e65972.png)

**Comment by VadymVolos** [comment]
Я не уверен, но когда в списке будет 6 услуг кнопка должна появится. Пока там 4 услуги.
Если я ошибаюсь поправьте меня.

**Comment by bvv4ik** [comment]
@VadymVolos совершенно прав!
тут все норм)
