### ISSUE TITLE
В ще не реалізованих послугах, лічильник спрацьовує при натисканні лінку соцмереж

### ISSUE THREAD

**Issue by polosatui** [e-government-ua/i#448]
В ще не реалізованих послугах, лічильник спрацьовує при натисканні лінку соцмереж навіть якщо не поділитися посиланням, а просто подивитися на вікно що відкрилось та закрити його.

**Comment by bvv4ik** [comment]
не понял из описания(

**Comment by polosatui** [comment]
нажимаем иконку - открывается окно соцсети + срабатывает счетчик сразу же, то есть мы не нажимаем "поделиться ссылкой" а счетчик уже сработал

**Comment by VadymVolos** [comment]
https://igov.org.ua/service/22/general
Это кнопки сервиса Pluso в том сервисе по другому нет возможности..
решается только установкой других кнопок от соц сетей.

**Comment by VadymVolos** [comment]
Кстати это сервис share.pluso.ru ру разработчиков, не нужно чтоб они знали нашу статистику.

**Comment by VadymVolos** [comment]
Вот один из вариантов самописных кнопок http://share42.com/
Только если будете использовать эти кнопки хорошо проверьте их код, чтоб статистика никуда не уходила, весь код подробно просмотрите.

**Comment by poremchuk** [comment]
По моєму, по приорітетності це навіть не 10-та задача, при усій повазі...

**Comment by polosatui** [comment]
так в неї і пріорітету немає, просто питання

**Comment by bvv4ik** [comment]
это особенность компоненты... ее, кстати ,выбрал Дмитрий Александрович, и мы одно время пытались сменить на что-то другое, но достойной альтернативы не нашли...
