### ISSUE TITLE
На главном портале "оживить" кнопку "Авторизация по ЭЦП"(типа БанкИД)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#449]
Для вызова ЭЦП на боевом:
https://bankid.org.ua/DataAccessService/das/authorize?response_type=code&client_id=5d06b5ae-35ed-49aa-9249-36a1681be6a9&eds=true&redirect_uri=https://igov.org.ua:443/documents/user/bankid

для вызова ЭЦП на полигоне:
https://bankid.privatbank.ua/DataAccessService/das/authorize?response_type=code&client_id=5d06b5ae-35ed-49aa-9249-36a1681be6a9&eds=true&redirect_uri=https://poligon.igov.org.ua:443/documents/user/bankid

ВАЖНО: в проекте уже есть готовые переменные в конфиге, где хранится хост БанкИД:
		, sProtocol_AccessService_BankID: 'https' //Test
		, sHost_AccessService_BankID: 'bankid.privatbank.ua' //Test
, потому хардкодить хост НЕ НАДО, плиз)

**Comment by bvv4ik** [comment]
Для теста:
убедиться что ожила кнопка авторизации по ЕЦП в: Моих документах, Моем журнале, и при получении услуги

**Comment by smit-pb** [comment]
На тестовом необходимо подключать переменные ? или как ? 
Сейчас на тестовом происходит переадресация на линк - https://bankid.org.ua/ и все.

**Comment by smit-pb** [comment]
А при получении услуги - вообще нет ссылки или кнопки на ЕЦП

**Comment by bvv4ik** [comment]
там где это другой тип услуги, или услуга не предполагает авторизации по ЕЦП - ее и не будет...
смотрите только те места, где она есть.

**Comment by smit-pb** [comment]
![image](https://cloud.githubusercontent.com/assets/12965717/8563592/50310c8a-254a-11e5-96c3-13468f5704e4.png)
При нажатии на " електронно-цифровий підпис" происходит редирект на "https://bankid.org.ua/".

По этому еще раз вопрос - на тестовом еще УРЛЫ - не изменены ? или как ?

**Comment by bvv4ik** [comment]
а на какие урл-ы они должны быть изменены?)

**Comment by smit-pb** [comment]
для вызова ЭЦП на полигоне:
https://bankid.privatbank.ua/DataAccessService/das/authorize?response_type=code&client_id=5d06b5ae-35ed-49aa-9249-36a1681be6a9&eds=true&redirect_uri=https://poligon.igov.org.ua:443/documents/user/bankid

Собственно из тела задачи.

**Comment by smit-pb** [comment]
По состоянию на Сегодня (16,07) На тестовом ссылки ЭЦП - так и не заменены. 
т.е. Задача требует доработки ?

**Comment by bvv4ik** [comment]
то просто в БанкИД менялись условия работы, потому и перестаало работать.
только сегодня утром завершилось совещание, на котором решили работу БанкИД в этой части "вернуть на родину". т.е. совсем скоро все заработает обратно. (на нашей стороне доработок не требуется... просто ждем,  яотпишусь когда)

**Comment by bvv4ik** [comment]
уже все починили

**Comment by smit-pb** [comment]
Да - ЭЦП кнопка и урлы , ожили.
Касательно услуг - ЭЦП работает корректно , но только на тех услугах где эта кнопка присутствует.
