### ISSUE TITLE
На dashboard-js организовать отдельный вход-авторизацию для чиновников, ведущую к интерфейсу типа ActivitiExplorer

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#45]
В интерфейсе организовать отображение поступивших заявок от граждан, с возможностью выбирать их и отрабатывать

**Comment by AleksejDomash** [comment]
пример авторизации можно найти здесь https://github.com/DaftMonk/fullstack-demo

**Comment by maxymshg** [comment]
Пример приложения написаного с использованием angular.js + activiti REST
http://alfrescoblog.com/2014/06/07/angular-js-activiti-webapp-part-i/
http://alfrescoblog.com/2014/06/17/angular-js-activiti-webapp-part-ii/
