### ISSUE TITLE
На бэке главного портала(wf-central) реализовать сервис получения объекта документа, по уникальному коду открытого доступа к нему + вспомогательный сервис получения списка операторов документов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#450]
1) Название:
getDocumentAccessByHandler 
(подобно /getDocumentAccess и создать в том-же контроллере)

2) Параметры:
sCode_DocumentAccess - строковой код доступа к документу
nID_DocumentOperator_SubjectOrgan - номер-ИД субьекта-органа оператора документа
nID_DocumentType(опционально) - номер-ИД типа документа
sPass (опционально) - строка - пароль

3) Добавить сущность:
DocumentOperator_SubjectOrgan (по образу и подобию ServiceOperator_SubjectOrgan.csv)
В ней поля:
nID - уникальный номер-ИД (автоитеррируемый)
sName - строковое имя
nID_SubjectOrgan - номер-ИД субьекта-органа
sHandlerClass - строка названия класса-обработчика с путем

3.1) создать по нему вспомогательный сервис getDocumentOperators,
возвращающий массив объектов JSON этой сущности
Например:
[
{
"nID":1
,"sName":"iGov"
,"nID_SubjectOrgan":2
,"sHandlerClass":"DocumentAccessHandler_IGov"
}
]

3.2) добавить в инициализирующую таблицу DocumentOperator_SubjectOrgan.csv один элемент 
nID=1
sName="iGov"
nID_SubjectOrgan=2
sHandlerClass="DocumentAccessHandler_IGov"

4) Создать класс-обработчик: 
DocumentAccessHandler_IGov
Вызывать его  тогда, когда в сервисе, в параметре nID_DocumentOperator_SubjectOrgan=1
(т.е. соответствует записи в п.3, где этот класс указан в поле sHandlerClass)

5) в сущности: DocumentAccess
добавить поле:
sCode - строка с кодом (до 50-ти символов)
sCodeType - строка с кодом (до 20-ти символов)

6)  в классе-обработчике DocumentAccessHandler_IGov
(для всех обработчиков DocumentAccessHandler_* - создать унифицированный интерфейс)
-принимать значение sCode_DocumentAccess
-искать по нему в сущности: DocumentAccess - запись по полю sCode

6.1) если найден и sCodeType=null - отдавать обьект-JSON документа (сущность Document)
6.2) если найден и sCodeType=SMS - сверять еще пришедший параметр sPass с полем sAnswer (сущности DocumentAccess), и если совпадают,отдавать обьект-JSON документа (сущность Document) или выводить ошибку:
{"sError":"Document Access wrong password"}
6.3) если не найден - выводить ошибку:
{"sError":"Document Access not found"}

7) Все ошибки логировать и описание сервисов добавить в доку: https://github.com/e-government-ua/i/blob/test/docs/specification.md

**Comment by dgroup** [comment]
## Тесткейсы для /getDocumentOperators 

#### [№1] Получить всех операторов документов, которые поддерживает система
1. Отправить реквест https://poligon.igov.org.ua/wf-central/service/services/getDocumentOperators

*ER* = масив из одной сущности, с параметрами
```json'
[
  {
    "nID_SubjectOrgan": 2,
    "sHandlerClass": "org.wf.dp.dniprorada.model.document.DocumentAccessHandler_IGov",
    "nID": 1,
    "sName": "iGov"
  }
]    
````

#### [№2] Добавить нового оператора документов, которые поддерживает система
1. Добавить в новую сущность еще одну запись с таким же форматом полей как в data/DocumentOperator_SubjectOrgan.csv 2. Отправить реквест https://poligon.igov.org.ua/wf-central/service/services/getDocumentOperators

*ER* = масив из двух сущностей, с параметрами
```json'
[
  {
    "nID_SubjectOrgan": 2,
    "sHandlerClass": "org.wf.dp.dniprorada.model.document.DocumentAccessHandler_IGov",
    "nID": 1,
    "sName": "iGov"
  },
  {
    "nID_SubjectOrgan": new_nID_SubjectOrgan,
    "sHandlerClass": "new_sHandlerClass",
    "nID": new_nID,
    "sName": "new_sName"
  }
]    
````

#### [№3] Удалить оператора документов
1. Удалить запись добавленную в Т.С#2
2. Отправить реквест https://poligon.igov.org.ua/wf-central/service/services/getDocumentOperators

*ER* = T.C#1.ER

**Comment by dgroup** [comment]
## Тесткейсы для "/getDocumentAccessByHandler "

#### [№1] Получить документ по строковому коду и коду органа
Отправить запрос на https://poligon.igov.org.ua/wf-central/service/services/getDocumentAccessByHandler?sCode_DocumentAccess=2&nID_DocumentOperator_SubjectOrgan=2 , где _sCode_DocumentAccess_ строковый код  доступа (хранится в сущности DocumentAccess), _nID_DocumentOperator_SubjectOrgan_ это номер органа, который имеет право запрашивать документ

*ER* = получен документ в формате json:
````json
{
    "sDate_Upload": "2015-01-01",
    "sContentType": "text/plain",
    "contentType": "text/plain",
    "nID": 2,
    "sName": "Справка",
    "oDocumentType": {
        "nID": 1,
        "sName": "Справка"
    },
    "sID_Content": "1",
    "oDocumentContentType": {
        "nID": 2,
        "sName": "text/plain"
    },
    "sFile": "dd.txt",
    "oDate_Upload": 1420063200000,
    "sID_Subject_Upload": "2",
    "sSubjectName_Upload": "ПриватБанк",
    "oSubject_Upload": {
        "nID": 1,
        "sID": "ПАО",
        "sLabel": "ПАО ПриватБанк",
        "sLabelShort": "ПриватБанк"
    },
    "oSubject": {
        "nID": 2,
        "sID": "2872618515",
        "sLabel": "Белявцев Владимир Владимирович",
        "sLabelShort": "Белявцев В. В."
    }
}
````

#### [№2] Попытка получить документ по строковому коду и некорректному коду органа

Отправить запрос на https://poligon.igov.org.ua/wf-central/service/services/getDocumentAccessByHandler?sCode_DocumentAccess=2&nID_DocumentOperator_SubjectOrgan=100500

*ER* = сообщение о том что орган не найдет:
````json
{
    "code": "SYSTEM_ERR",
    "message": "Organ not found"
}
````

#### [№3] Попытка получить документ по некорректному строковому коду
Отправить запрос на https://poligon.igov.org.ua/wf-central/service/services/getDocumentAccessByHandler?sCode_DocumentAccess=100500&nID_DocumentOperator_SubjectOrgan=2,

*ER* = сообщение об ошибке:
````json
{
    "code": "SYSTEM_ERR",
    "message": "Document Access not found"
}
````

#### [№4] Получить документ по строковому коду, ID органа и паролю

Отправить запрос на https://poligon.igov.org.ua/wf-central/service/services/getDocumentAccessByHandler?sCode_DocumentAccess=2&nID_DocumentOperator_SubjectOrgan=2&sPass=123

*На данный момент данная проверка работает только для документов у который sCodeType_DocumentAccess = SMS*

*ER* = T.C#1.ER
Если указать заведомо неправильный пароль, то
*ER* = сообщение об ошибке:
```json
{
    "code": "SYSTEM_ERR",
    "message": "Document Access wrong password"
}
```

#### [№5] Получить документ по строковому коду, типу документа, ID органа и пароля
Поведение такое как у **T.C#4**, но добавляется проверка по типу документа (nID_DocumentType).

*ER*(Тип документа корректный) = *T.C#1.ER*
*ER*(Тип документа не правильный) = *T.C#3.ER*

**Comment by NikitaLyah** [comment]
Протестировал все тест-кейсы кроме "[№2] Добавить нового оператора документов, которые поддерживает система" каким образом нужно добавить новую сущность еще одну запись с таким же форматом полей как в data/DocumentOperator_SubjectOrgan.csv ?

**Comment by bvv4ik** [comment]
просто так оператора нельзя добавить, т.к. под это еще придется писать класс хэндлер(обработчик)...
