### ISSUE TITLE
На базе basic-авторизаци, при доступе ко всем сервисам бэка, вместа сверки всегда со статическим логином и паролем - сверять пользователя  с пользователем в Activiti

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#451]
Сейчас для авторизации всегда в хеадере передается параметр, типа:
'Authorization', "Basic YWN0aXZpdGktbWFzdGVyOlVqaHRKbkV2ZiE="
Где:
"Basic YWN0aXZpdGktbWFzdGVyOlVqaHRKbkV2ZiE="
- зашифрованный в Base64 логин и пароль 
Например: getBase64(“activiti-master:UjhtJnEvf!”);

так вот вместо
логина: activiti-master
пароля: UjhtJnEvf!
должна быть расширена сверка со всеми логинами и паролями которые есть в Активити.

и любой из зарегистрированных пользователей должен быть допущен к сервисам.

П.С.: ограничение по методам в последующем должна быть реализована в фильтре, через сверку групп, в которые входит пользователь.

**Comment by admiral-diver** [comment]
Реализовано без сверки групп

**Comment by bvv4ik** [comment]
а докрутил туда логирование, но чето инфу по юзверю зарегеному не захотело выдавать...
но я еще седня попроверяю

**Comment by bvv4ik** [comment]
Для теста, можно на центральном в логах глянуть:
generalUsername!!!3test: tech_mvd
и там видно какое значение выдает гетер в этом тестовом запросе

**Comment by admiral-diver** [comment]
OMG! Поясни) Удовлетворен/Не удовлетворен. И что хочешь улучшить)

**Comment by bvv4ik** [comment]
) Удовлетворен конечно! Это для тестеров инфа...
Следующим этапом - сравнивать присутствие юзера в определенной группе, после чего только и авторизовывать его... сейчас не группы пока не смотрит...

но, это не срочно)
