### ISSUE TITLE
Нужно унифицировать "Крок 2" в услугах

### ISSUE THREAD

**Issue by polosatui** [e-government-ua/i#452]
![2015-06-26_23-23-05](https://cloud.githubusercontent.com/assets/12971440/8386650/c58cd76e-1c5a-11e5-956b-2164ba7d89a8.png)
![2015-06-26_23-23-42](https://cloud.githubusercontent.com/assets/12971440/8386651/c59036c0-1c5a-11e5-8814-eeae41c50181.png)
![2015-06-26_23-24-15](https://cloud.githubusercontent.com/assets/12971440/8386652/c591bcd4-1c5a-11e5-82af-f211f0cf11c3.png)

**Comment by bvv4ik** [comment]
так это так специально и реализовано))) крок 2 и должен быть разным
где-то нужен один перечень авторизации, где-то другой, а где-то авторизация вообще не нужна а нужна прямая ссылка на ресурс

**Comment by polosatui** [comment]
Ок, понял. Только тогда в услугах где требуется переход необходимо указивать на какой ресурс будет осуществлен переход.

**Comment by hordesalik** [comment]
оно указывается если с бекенда приходит описание услуги. т.е. нужно просто инфу заполнить и все будет отображаться

**Comment by polosatui** [comment]
А это у кого в компетенции?

**Comment by bvv4ik** [comment]
Павел Курбацкий
