### ISSUE TITLE
Написать в яве метод(в wf-base) проверки последних измененных файлов по пути

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#453]
который будет запускаться через main (ручками с коммандной строки), в параметрах принимающий строку-путь (sFullPathScan), которую нужно просканировать, и отдающий булевый ответ (true/false) - есть-ли изменения в каком-то из содержащихся папках/файлах, в сравнении с последним сканированием.

дату последнего сканирования запоминать посредством сохранения списка измененных файлов (дополнения списка существовавшего) в техническом файле (сравнивать в датой/временем модификации этого файла)

хранить этот технический файл на два уровня вверх, относительно указанного пути, в файле с названием в виде двух промежуточных папок, разделенных точкой, и окончанием в виде ".modify.lst"

Например:
входящий параметр-путь:
"/sybase/jenkins/data/jobs/regional-alpha/workspace/central-js"
значит файл-список изменений должен быть по пути:
"/sybase/jenkins/data/jobs/regional-alpha/workspace.central-js.modify.lst"

содержание файла подобно такому(с полной датой и временем модификации, относительным путем к файлу/папке и разделенные через знак ";"):
2015-06-25_12:12:59.003;/server/config.js
2015-06-25_12:12:44.011;/server/components/activiti/index.js

**Comment by ASkosyr** [comment]
Забираю на себя
Ориентировочная дата окончания - к вечеру 28 Июня - 29 июня

**Comment by bvv4ik** [comment]
Для теста:

Выполнить:
$JAVA_HOME/jre/bin/java -classpath "/sybase/jenkins/data/jobs/central_alpha/lib/*" org.egov.filescanner.ModificationsScanner $1
где в качестве параметра "$1" указать путь к содержимому
а вместо:
"/sybase/jenkins/data/jobs/central_alpha/lib/*" 
путь к библиотекам проекта (wf-base)

запустив раз, потом 2 - напишет что изменения не найдены
потом изменить файл в указанной папке и запустить третий раз - напишет что уже найдены
