### ISSUE TITLE
Создать сервисы "электронной очереди": авто-генерации слотов, в соответствии с расписанием потока и отчистки слотов за указанный период

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#454]
1) Генерация слотов
1.1) Создать сервис генерации buildFlowSlots
в параметрами:
nID_Flow_ServiceData - номер-ИД потока по данным сервиса (по которому генерируется слоты)
sDateStart (опциональный) - дата "начиная с такого-то момента времени", в формате "2015-06-28 12:12:56.001"
sDateStop (опциональный) - дата "заканчивая к такому-то моменту времени", в формате "2015-07-28 12:12:56.001"

1.2) Создать класс-обработчик: "org.wf.dp.dniprorada.base.service.flow.propertyHandler.DefaultFlowSlotScheduler"
Вызывать его тогда, когда в сервисе, по параметру nID_Flow_ServiceData - выходим на ссылку в этого класса и пути (по текущим данным мы выйдем со значением nID_Flow_ServiceData=1)
Определяем это по такой логике:
1.2.1.) этот ИД ищет записи в сущности:
(1.5) FlowProperty (Свойства потока), с полями:
nID (лонг) - номер-ИД (уникальный) //обязательное (автоитеррируемый)
nID_Flow_ServiceData (лонг) - номер-ИД потока данных сервиса //обязательное
nID_FlowPropertyClass (лонг) - ИД-строка класса-обработчика //обязательное
sData (<200 символов) - строка с данными для обработчика //обязательное
где nID_Flow_ServiceData совпадет!
На текущий момент в этой таблице есть такая запись (где nID_FlowPropertyClass=1):
nID;nID_FlowPropertyClass;sData;nID_Flow_ServiceData
1;1;Test Property Data;1
1.2.2.) в этой записи есть поле "nID_FlowPropertyClass", у котором значение=1, соответственно ищем в сущности:
(1.6) FlowPropertyClass (Класс-свойство потока), с полями:
nID (лонг) - номер-ИД (уникальный) //обязательное (автоитеррируемый)
sName (<100 символов) - строка названия //обязательное
sPath (<100 символов) - строка пакет.класс с обработчиком //обязательное
записи с этим ИД, и т.к. в таблице такая запись есть:
nID;sName;sPath
1;Shedule_MREO;org.wf
то получаем по ней:
sName=Shedule_MREO;org.wf и sPath=org.wf
(т.е. выходим на класс "org.wf.Shedule_MREO")

1.3) В классе обработчике принимать параметр sData,
который получается из найденной в п.п.1.1.2. записи сущности FlowProperty
(sData (<200 символов) - строка с данными для обработчика)
В этом значении описана периодичность расписания, по логике:
https://en.wikipedia.org/?title=ISO_8601#Durations
И также принимать значения полученных параметров sDateStart и sDateStop
Логика их "дефолтности" должна быть в этом классе, через проверку их на null:
- если sDateStart=null - берется текущая дата
- если sDateStop=null - берется sDateAt + 2 месяца

1.4) В классе обработчике выполнить метод make
который за указанный период(sDateAt-sDateTo), с учетом расписания(sData) и в рамках указанного "Flow_ServiceData" - проходится по записям сущности:
(1.7) FlowSlot (слот потока), с полями:
nID (лонг) - номер-ИД (уникальный) //обязательное (автоитеррируемый)
nID_Flow_ServiceData (лонг) - номер-ИД потока данных сервиса //обязательное
sDate (дата со временем) - дата и время //обязательное
sData (<30 символов) - строка данных //необязательное
sDuration (длительность) - строка длительности (например "PT15M") //обязательное
В соответствии с логикой: https://en.wikipedia.org/?title=ISO_8601#Durations
sName (<200 символов) - строка, описания для человека (напр: "2015-06-06 с 8-00 до 8-30") //обязательное
А исходя из существующих записей:
- Все не обнаруженные записи - должны быть сгенерированы!
- Все обнаруженные и совпавшие могут быть обновлены только в рамках поля "sDuration"  (если оно отличается)

1.5) В ответ сервис должен вернуть массив созданных записей, в виде JSON-обьекта

2) Очистка от слотов 
2.1) Создать сервис очистки clearFlowSlots
в параметрами:
nID_Flow_ServiceData - номер-ИД потока по данным сервиса (по которому отчищаются слоты)
sDateStart (обязательный) - дата "начиная с такого-то момента времени", в формате "2015-06-28 12:12:56.001"
sDateStop (обязательный) - дата "заканчивая к такому-то моменту времени", в формате "2015-07-28 12:12:56.001"
bWithTickets (опциональный, умолчательно false) - булевый, разрешающий удалять в т.ч. занятые тикетами слоты

2.2) выполнить очистку записей в сущности FlowSlot, за указанный период(sDateStart-sDateStop) и в рамках указанного "Flow_ServiceData":
ВАЖНО: 
- если bWithTickets=false, то "пропускать" занятые тикетами слоты (сущность: SubjectTicket), но обязательно выводить их массив в ответе
- если bWithTickets=true, то "освобождать"(от тикетов) и удалять занятые тикетами слоты (в самих тикетах обновлять поле SubjectTicket.sDateEdit равным текущей дате.

2.3) В ответ сервис должен вернуть массив "удаленных" и "с тикетами" записей слотов, в виде JSON-обьекта

3) Обязательно описать указанные методы в документации: https://github.com/e-government-ua/i/blob/test/docs/specification.md

П.С.: предыдущие задачи по реализации этих сущностей и сервисов к ним:
https://github.com/e-government-ua/i/issues/315
https://github.com/e-government-ua/i/issues/380

**Comment by brunneng** [comment]
Для описания того когда генерировать слоты тут:
"sData (<200 символов) - строка с данными для обработчика //обязательное"
Решили использовать формат cron expression:
http://www.quartz-scheduler.org/documentation/quartz-1.x/tutorials/crontrigger

**Comment by brunneng** [comment]
Было решено добавить в SubjectTicket поля sDateStart,sDateFinish типа DATETIME - которые соответствуют интервалу слота. Чтобы если тикет будет отвязан от слота в операции clearFlowSlots - то чтобы сохранилась информация на какое время был тикет.

**Comment by bvv4ik** [comment]
Для теста:
можно в нашей доке по АПИ глянуть описание и сгенерить слотов на пару недель

**Comment by RoOmel** [comment]
1) Создать сервис генерации buildFlowSlots - соответствует ТЗ.
Сгенерил на 3 недели
Вот фрагмент:
{
        "nID": 20576,
        "sTime": "08:00",
        "nMinutes": 15,
        "bFree": true
    },
2) Очистка от слотов clearFlowSlots  - соответствует ТЗ.
Одну неделю освободил )
Вот фрагмент:
{
    "aDeletedSlot": [
        {
            "nID": 20416,
            "sTime": "08:00",
            "nMinutes": 15,
            "bFree": true
        },
