### ISSUE TITLE
Создать в активити новый тип "invisible", на базе "string"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#455]
он прописывается в контекстном файле и под него создается класс
(в качестве примера можно взять "queueData")

так-же добавить этот тип для полей с id "responce" и "footer" в БП:
dnepr_mvd-1
dnepr_mvk-1
harkov_mvd-1
hmelnitskij_mvk-1
kiev_mreo-1
nikopol_mvd-1
nikopol_mvk-1
voznesensk_mvk-1

и убрать с этих полей readable="false"

П.С.: на клиенте(и центральном портале и дашборде) - поля с этим типом отображаться не будут

**Comment by bvv4ik** [comment]
Для теста:
Можно открыть любой из БП, например dnepr_mvd-1, в проекте
и убедиться что там есть такой тип type="invisible"
при этом проект работает и "не падает", значит точно тип поддерживается

так-же можно убедиться по работе задачи:
https://github.com/e-government-ua/i/issues/467

**Comment by VadimGulich** [comment]
Работает корректно!
Можно на боевой 
Проверено при тестировании задачи : так-же можно убедиться по работе задачи:
#467
