### ISSUE TITLE
На дашборде - скрывать поля с типом "invisible" и отображать поле с типом "label"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#456]

**Comment by bvv4ik** [comment]
Для теста:
зайти на https://test.region.igov.org.ua/admin
логин/пароль: kermit/kermit
и найти там заявку по МРЕО, где есть и тип lable и invisible

**Comment by VadimGulich** [comment]
Нет заявок по МРЕО в https://test.region.igov.org.ua/admin

При попытке добавить по Киеву , полчаем ошибку:
{"code":"SYSTEM_ERR","message":"form property 'response' is not writable"}

**Comment by bvv4ik** [comment]
попробуйте сейчас

**Comment by VadimGulich** [comment]
Ошибка при создании заявки в МРЕО Киев 
code: "SYSTEM_ERR"
message: "String index out of range: -1"

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/8483240/16bdfcac-20f8-11e5-897b-f7f223636325.png)
https://test.region.igov.org.ua:6948/tasks 
kermit/kermit   
Войти в меню "В роботі"
Пример заявки : #745458 (2015-6-26 9:46) kiev_mreo_1:89:742597

**Comment by bvv4ik** [comment]
это старая запись, в которой неверные данные были... в той что создавалась последней - все должно быть нормально

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/8493041/b159c8ae-215c-11e5-9198-ae35f512b816.png)

**Comment by VadimGulich** [comment]
Эту закрываю , баг относится к этой задаче : https://github.com/e-government-ua/i/issues/458
