### ISSUE TITLE
На бэке(wf-base) доработать listener (слушатель) "FileTaskUploadListener" (для Activiti), который будет также искать поля с типом "queueData", и выбирая из них данные вызывать метод setFlowSlot_ServiceData

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#457]
- В классе FileTaskUploadListener уже подобным образом мониторятся типы "file" и там происходит загрузка контента из редис-а а потом аттачмент к задаче.
- В данном случае нужно просто вызывать метод "setFlowSlot_ServiceData", но напрямую из явы (передавая соответствующие параметры напрямую ,посмотрев образец в контроллере)
- В найденном поле типа "queueData" будет объект, подобно этому:
"{'nID_SubjectTicket':3452534, 'sDate': '2015-11-23 15:30:00.00'}"

1) По "nID_SubjectTicket" находить запись(тикет) в сущности "SubjectTicket" (по полю nID).
В ней доставать значения: nID_ServiceData и nID_Subject

2) В метод "setFlowSlot_ServiceData" передавать эти параметры:
nID_ServiceData (номер-ИД )
nID_Subject (номер-ИД )
а также, задавать параметр:
nID_Task_Activiti (номер-ИД)
в который передавать номер-ИД текущей таски (по которой отрабатывает листенер)

3) Обязательно логировать (с уровнем info) факт нахождения поля "queueData" и вызова метода "setFlowSlot_ServiceData". Обязательно логировать ошибки!

П.С.: задача по аналогичному вызову метода, но как REST и с клиента, реализовывалась:
https://github.com/e-government-ua/i/issues/382

**Comment by bvv4ik** [comment]
Для теста:
в региональном логе, сразу после оформления заявки по МРЕО(Киев)
найти "SCAN:queueData"
и ниже sValue=
в котором должен быть полученный обьект и без ошибок

**Comment by VadimGulich** [comment]
{"code":"SYSTEM_ERR","message":"form property 'response' is not writable"}  после оформления

**Comment by bvv4ik** [comment]
это где пишет? после какого оформления, на каком портале?

**Comment by bvv4ik** [comment]
попробуйте сейчас

**Comment by VadimGulich** [comment]
Ошибка при создании заявки в МРЕО Киев 
code: "SYSTEM_ERR"
message: "String index out of range: -1"

Проверял на : https://test.igov.org.ua/service/159/

**Comment by VadimGulich** [comment]
Исправлено
