### ISSUE TITLE
На дашборде, в полях типа "queueData" брать из значения параметр с датой и отображать его на форме, вместо всего содержимого поля

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#458]
Значение данного поля выглядит примерно так(объект JSON):
{'nID_SubjectTicket':3452534, 'sDate': '2015-11-23 15:30:00.00'}"

из него нужно брать значение параметра "sDate"(2015-11-23 15:30:00.00)
и отрисовывать в тэге lable (жирным шрифтом) данного поля
При этом в title писать "Тикет № 3452534" (номер брать из элемента nID_SubjectTicket)

**Comment by bvv4ik** [comment]
Для теста:
после проверки: https://github.com/e-government-ua/i/issues/457
зайти в дашбоард и найти задачу, где должно отрисоваться поле

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/8483350/f6fd6140-20f8-11e5-842d-31fad54c4614.png)

**Comment by bvv4ik** [comment]
это старая запись, в которой неверные данные были... в той что создавалась последней - все должно быть нормально

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/8493441/a53c537e-2162-11e5-8684-eefd32d58e2f.png)

После нажатия распечатать

**Comment by bvv4ik** [comment]
это не было ни как регламентировано для печатной формы, потому к данной таске это не относится. Главное - важная инфа отдается(ИД-шник тикета и дата)... решение по отображению в версии для печати еще не принято и для этого будет отдельная задача.

**Comment by VadimGulich** [comment]
Ясно , тогда задача протестирована , можно на боевой
