### ISSUE TITLE
На главном портале выводить div-диалог с ошибкой (и информацией, которую по ошибке можно выдать), при работе в наиболее важных частях портала (иначе часто просто крутится "крутилка", хотя ошибка реально произошла... или выводится диалог об успехе, который не соответствует действительности)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#459]
1) При возврате после BankID-авторизации в профиль услуги (иначе просто крутится крутилка, хотя ошибка реально произошла)
2) После отправки заполненной формы услуги гражданином (вместо диалога об успешной отправке)
3) При возврате после BankID-авторизации в "Мои документы" (иначе часто просто крутится крутилка, хотя ошибка реально произошла)
4) При возврате после BankID-авторизации в "Мой журнал" (иначе часто просто крутится крутилка, хотя ошибка реально произошла)

ВАЖНО: Вызов диалога реализовать через "функцию-прослойку", в которую передавать:
1) полученные данные об ошибке (чтоб в будущем можно было формировать нормальный текст для гражданина)
2) название функции, в которой произошла ошибка (или ее идентификатор, например "ServiceProfile_AuthBankID_Return")
Так-же предусмотреть возможность в этой "прослойке" задавать хеадер и тело сообщения диалога.

ПРИМЕР:
можно зайти в услугу "Отримання довідки про доходи (пенсійний фонд)" (на главном портале тестовом)
там Днепропетровская, Днепропетровск
заполнить форму, прикрепить файл,
и далее нажать нижнюю кнопку (зажется "Заказать услугу")
и после этого он через несколько секунд выведет диалог, что вроде как заявление зарегестрировано, но только без номера! (вообщем явно с ошибкой)
а все потому, что сам запрос:
https://test.igov.org.ua/api/process-form
вернул ошибку:
{"code":"SYSTEM_ERR","message":"Cannot find task with id 1305434"}
причем сам статус Status Code:200 OK
т.е. ошибка произошла гдето при обращении с бэка Ноды на бэк Явы... и дальше просто на фронт транзитом передало обьект с ошибкой...
потому придется и такое отслеживать и не 200-тые коды

**Comment by mendeleev** [comment]
Беру в роботу

**Comment by bvv4ik** [comment]
если будут какието сложности в реализации или тестах - прошу сразу сообщать. будем помагать

**Comment by mendeleev** [comment]
Поки що єдина складність в тому, що помилки при описаних в задачі випадках, не виникають.

**Comment by mendeleev** [comment]
Хочу прикрутити більш-менш людський діалог, бо алєртами то якось не дуже гарно, але поки не виходить. Модуль, який використовується в розділі "документи", при ініціалізації робить програму циклічною.

**Comment by bvv4ik** [comment]
поддерживаю идею про "человеческий диалог", но я-б, на первом этапе в принцибе-б поотыскивал и по трайкэтчил все те места, где могут быть ошибки и выводил-бы их хотябы даже и алертами.. т.к. сейчас ошибок вообще не пишится, что просто ужастно... т.к. и функционал не работает и нет ни какого сообщения об ошибке...

потом уже элементарно в коде отыскиваются все эти алерты и заменяютя на нормальный диалог (это можно было-бы даже отдельной таской сделать)

**Comment by mendeleev** [comment]
Створив компоненту для виведення повідомлень. Для того, щоб нею скористатись, потрібно підключити фабрику **ErrorsFactory** і методом **push** передати туди повідомлення у вигляді об’єкту з полями **type** та **text**. Поле type може приймати 4 значення: **danger, warning, success, info** і воно потрібно для того, щоб задати зовнішній вигляд повідомлення, яке буде виводитись.

Приклад:
```javascript
angular.module('app').service('ActivitiService', function($http, ErrorsFactory) {
...
  ErrorsFactory.push({
    type: "danger",
    text: "сталась помилка при обробці даних"
  });
...
```

Ось як виглядають всі 4 типи повідомлень:
![errortypes](https://cloud.githubusercontent.com/assets/4169132/8860470/aed566f2-318c-11e5-94a8-9959657204db.png)

Поки що виведення помилки додав лише в двох місцях. При замовленні послуги, та при перевірці чи залогінений користувач.
![error](https://cloud.githubusercontent.com/assets/4169132/8860116/5ddcaad2-318a-11e5-9759-0d6e169f1b12.png)

Як відтворити:
- замовляємо якусь послугу, наприклад "Реєстрація авто з пробігом в МРЕВ"
- логінимось через BankID
- заповнюємо всі поля
- в полі з email навмисно пишемо якусь абрукадабру, щоб зробити його не валідним
- клікаємо на "замовити"

**P.S.** Не дуже вкурсі як проходить процес заливання і збирання на тестовому сервері, тому не можу поки сказати коли воно там з’явиться.

**Comment by bvv4ik** [comment]
@mendeleev  Супер!!!
Значительный прогресс!
теперь осталось планомерно попокрывать все опасные места проверками с выводом таких мессаджей... (я позже дам уже готовый механизм, который позволит очень гибко, на основании встречающихся участков сообщений проходиться по дереву и заменять их на нормальные человеческие месаджи)
но пока нам нужно покрыть как можно большую часть опасных участков

**Comment by bvv4ik** [comment]
@mendeleev  вот, похоже выявился один забытый момент:
https://github.com/e-government-ua/i/issues/611

я, кстати, разок тоже с подобным столкнулся...
думаю, все-же стоит выводить ошибки в модальном див-окне, чтоб человек сам осознанно только закрыв диалог - переходил дальше...

**Comment by bvv4ik** [comment]
@mendeleev
есть еще силы/время докрутить таску?

т.к. уже несколько раз сталкивался, что при 500-м коде в ответе из явовского бэка - на фронте тек ошибок и не отображало...

и, нужно, либо автоматом убирать отображенный мессадж с ошибкой, после любого следующего клика(перехода кауда-то), либо таки выводить это в модальном окне.. т.к. сейчас получается, что отображенная ошибка ни куде не девается, даже если я ушел уже в другие менюшки...

я вижу, что основа таски, конечно, реализована, но эти два момент не позволяют ее закрыть окончательно...

**Comment by katebutenko** [comment]
для того, чтоб это воспроизвести - напишите, пожалуйста, любой путь для воспроизведения любой backend ошибки на портале.

**Comment by rostag** [comment]
@bvv4ik — я так розумію, цю таску треба ще завершити? Готовий взятися.

**Comment by bvv4ik** [comment]
@mendeleev уже прикручен унифицированный всплывающий диалог отображения ошибки,
есть возможность желание - поприкручивать его на все "опасные участки" ?

**Comment by bvv4ik** [comment]
реализовано окончательно
