### ISSUE TITLE
На главном портале(бэке), в Моих документах, при открытии доступа на документ - починить получение ссылки на доступ к документу (по кнопке "Получить код")

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#460]
После заполнения всех полей и нажатии на кнопку "Надати доступ"
отображается диалог с лєйблом, типа:
"Посилання, за яким користувач може отримати доступ (через SMS-пароль)"

и в поле пусто(раньше работало)

Фактически происходит запрос:
https://poligon.igov.org.ua/api/service/documents/464/share?nID_Document=464&nMS=604800000&sFIO=%D0%A4%D0%98%D0%9E&sTarget=&sTelephone=+

в ответ на который должен приходить объект из которого и берется эта ссылка(это все настроено)
Но в какой-то момент перестал приходить объект (вероятно связано с доработкой нами безопасности)

Нужно найти ошибку и починить.

**Comment by LamronNu** [comment]
есть подозрение, что это не фронт-ошибка, а бэк. потому что с фронта запрос идет на получение доступа к документу, т.е. на адрес _wf-central/service/setDocumentLink_ (если я правильно понимаю логику)

К сожалению, решить пока не получилось. Возможно, у кого-то получится разобраться.
Ниже информация, которая была получена мною сегодня.

тестировано на запросе <a href="http://localhost:8081/wf-central/service/setDocumentLink?nID_Document=2&nMS=604800000&sFIO=test&sTarget=&sTelephone=+380102030405">http://localhost:8081/wf-central/service/setDocumentLink?nID_Document=2&nMS=604800000&sFIO=test&sTarget=&sTelephone=+380102030405</a>

вылетает при попытке сохранить запись, т.е. в методе *writeRow* класса *org.wf.dp.dniprorada.dao.DocumentAccessDaoImpl*
сейчас там код примерно такого вида
```sql
INSERT INTO DocumentAccess (columns) 
VALUES (values)
```
*ексепшион*: ```unexpected token: VALUES near line 1, column 104```
который говорит о том, что хибернейт не поддерживает такую форму запросов (https://forum.hibernate.org/viewtopic.php?f=1&t=960034)

__вариант 1__ : переписать на 
```sql
INSERT INTO org.wf.dp.dniprorada.model.DocumentAccess (columns) 
select values 
from org.wf.dp.dniprorada.model.DocumentAccess da where da.nID_Document=nID_Document
```
*ексепшион:*
```No data type for node: org.hibernate.hql.internal.ast.tree.IdentNode 
 +-[IDENT] IdentNode: 'test' {originalText=test}```
 
 __вариант 2__: вернуть сохранение обьекта средствами Хибернейта
```java
 s.save(o); OR s.saveOrUpdate(o);
 ```
 *ексепшион:* 
 ```org.h2.jdbc.JdbcSQLException: Значение NULL не разрешено для поля "NID"
NULL not allowed for column "NID"; SQL statement:
insert into DocumentAccess (nID, nID_Document, nMS, sAnswer, sCode, sCodeType, sDateAnswerExpire, sDateCreate, sFIO, sMail, sSecret, sTarget, sTelephone) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23502-176]```
последняя ошибка "странная", потому что ид-шка должна генерироваться хибернейтом (есть соответсвующие аннотации у сущности DocumentAccess ), но почему-то она не подставляется..

*вопрос* такой: работал ли этот метод вообще? если да -- то какие именно изменения были произведены в "глобальной" логике, что могло привести к таким ошибкам?
сам класс DocumentAccessDaoImpl "изучен" чуть ли не до момента создания, видно, что сначала был использован метод  s.save(o), потом переписан на инсерт-валуез, но непонятно, работало ли оно до/после изменений.

**Comment by bvv4ik** [comment]
@LamronNu Спасибо за подробное исследование проблемы,
уже асайнул таску на разработчика, который "пилил" этот функционал...

**Comment by yevheniilazarev** [comment]
Нужно обращаться к setDocumentLink вот так
https://test.igov.org.ua/wf-central/service/setDocumentLink?nID_Document=2&sFIO=test&sTarget=secret&sTelephone=+380102030405&nMS=604800000&sMail=test@ya.com
т.е. все эти параметры должны быть обязательными. Можно пробовать.

**Comment by LamronNu** [comment]
проверено. работает (хотя локально все равно ругается, ексепшион из "варианта 2"...)

а с фронта ссылка генерируется, но не переходит, если ее вставить в строку браузера.

**Comment by bvv4ik** [comment]
"с фронта ссылка генерируется"
т.е. уже поправлено на бэке или фронте?

**Comment by LamronNu** [comment]
с бека работает, т.е ссылка генерируется и отображается (плюс генерируется событие в журнал, которое создается только в случае "успеха"). 
но если "перейти по ссылке", то выкидывает 404

**Comment by bvv4ik** [comment]
для теста:
зайти в Мои документы, там в списке на однос клацнуть на иконку открытия доступа, заполнить поля и нажать последнюю кнопку... теперь уже должна появиться ссылка в диалоге, а не пустое место.

**Comment by NikitaLyah** [comment]
Ссылка появилась, но кнопка копирования в буфер обмена не работает, если выделять ссылку и копировать с помощью клавиш Ctrl + C то ссылка не копируется
@bvv4ik

**Comment by bvv4ik** [comment]
починка "копирования в буфер обмена" - в другой созданной задаче... тут этого не требовалось

**Comment by NikitaLyah** [comment]
а что насчет "если выделять ссылку и копировать с помощью клавиш Ctrl + C то ссылка не копируется" ?

**Comment by bvv4ik** [comment]
скажу по секрету: эту ссылку даже негде применить)
потому решится вопрос с применением ссылки и с копированием в буфер обмена - одновременно...
важно было чтоб нанные доходили до клиента.. на сколько я понимаю - они теперь начали доходить
