### ISSUE TITLE
Не работает линк info@bankid.org.ua

### ISSUE THREAD

**Issue by Alienhub** [e-government-ua/i#461]
При клике мышью, не работет ссылка: info@bankid.org.ua
Окружение: Windows 64-bit, Chrome Version 43.0.2357.130 m

![bug link](https://cloud.githubusercontent.com/assets/13061861/8393658/70591528-1d22-11e5-8f18-779c0946a9f2.png)

**Comment by bvv4ik** [comment]
ребята, уже сколько писал - БанкИД это не iGov
прошу не создавать таски по нему тут! ведь превращается все в свалку

**Comment by Alienhub** [comment]
Сорри, все понял.
