### ISSUE TITLE
[S4] Ошибка при загрузке мой журнал

### ISSUE THREAD

**Issue by VadimGulich** [e-government-ua/i#463]
Ошибка №1 : После входа через ID Bank на время открывается форма с авторизацией, после чего загружается меню "Мой журнал"
Шаги: 
1) Войти в меню "Мой журнал" 
2) Авторизоваться через ID Bank
Фактический результат: Кратковременно открывается форма с авторизацией в меню "Мой журнал"
Ожидаемый результат: Отображается анимация загрузки пока не загрузится меню

Ошибка №2 : Постоянно висит анимация загрузки
Шаги: 
1) Войти в меню "Мой журнал" 
2) Авторизоваться через ID Bank
3) Обновить страницу
Фактический результат: Постоянно висит анимация загрузки
Ожидаемый результат: Меню загружается

**Comment by bvv4ik** [comment]
сейчас после авторизации все нормально заходит, и даже после рефреша страницы

**Comment by VadimGulich** [comment]
Сейчас работает корректно. Исправлено
