### ISSUE TITLE
Ошибка в слове "Реєстраційні дані" в меню "Послуги"

### ISSUE THREAD

**Issue by OksanaVD** [e-government-ua/i#465]
1. Открыть меню "Послуги".
2. В разделах  "Громадянам" и "Бізнесу"  найти подраздел "Реєстраційни дані".

![data](https://cloud.githubusercontent.com/assets/12966279/8397488/7532f1b4-1dd5-11e5-8efd-d847ae30ac72.jpg)
![data1](https://cloud.githubusercontent.com/assets/12966279/8397489/75339042-1dd5-11e5-9add-78803f9574ef.jpg)

Фактический результат: Ошибка в слове  "Реєстраційни дані"
Ожидаемый результат: Слово "Реєстраційні дані" без ошибки

**Comment by VadimGulich** [comment]
Исправлено
