### ISSUE TITLE
в POM-ах разделить билды на версии "alpha", "beta" и "release", чтоб все собранные компоненты попадали в Нексус с соответствующими различающимися маркерами версий

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#466]
Реализовать через профили

**Comment by bvv4ik** [comment]
для теста:
https://jenkins.igov.org.ua/view/new/job/central_alpha/
https://jenkins.igov.org.ua/view/new/job/regional-alpha/
в консоле(логах) смотреть на появившийся префикс в собирающихся артефактах, типа "a"
например: 1.0.0a

**Comment by VadimGulich** [comment]
Добавлен префикс , проверено в консоли сборки  Console Output
