### ISSUE TITLE
На главном портале, на форме услуги, сделать скрытым поле с типом invisible

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#467]
сдедствие задачи: https://github.com/e-government-ua/i/issues/455

**Comment by bvv4ik** [comment]
Для теста, зайти на услугу: https://poligon.igov.org.ua/service/159/general
где есть поля с содержимым, которое не должно отобразиться на форме

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/8429303/0244dcde-1f2f-11e5-913e-e0c6d3bd51dc.png)

**Comment by bvv4ik** [comment]
Поправлено!

**Comment by VadimGulich** [comment]
Исправлено
