### ISSUE TITLE
[S3] Немає можливості вибрати пункт Меню при зміні розмірів вікна браузера

### ISSUE THREAD

**Issue by liliavovchak** [e-government-ua/i#470]
Mac OS X 10.10
Chrome latest version, Safari 8.0.6

0. Зменшити вікно браузера, допоки замість табів з"явиться кнопка Меню
1. Натиснути на кнопку Меню 

Expected result:
випадаючий список з можливістю вибрати одну з 4-х доступних опцій (Послуги, Документи, Мій журнал, Про портал)

Actual result:
випадаючий список не з"являється, посеред екрану показується поточна вибрана опція. Див. аттачмент

![screen shot 2015-06-29 at 10 00 07 pm](https://cloud.githubusercontent.com/assets/13079334/8416045/94e295ce-1eab-11e5-862c-12ad03a6df9c.png)

**Comment by bvv4ik** [comment]
Просьба перенести эту issue в бэклог и закрыть ее:
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit
