### ISSUE TITLE
Привести в порядок именования доменов системы порталов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#471]
Альфа-тест
test.igov.org.ua
test.region.igov.org.ua
test.region.igov.org.ua/admin
test.region.igov.org.ua/admin-activiti
Бета-тест:
test-version.igov.org.ua
test-version.region.igov.org.ua
test-version.region.igov.org.ua/admin
test-version.region.igov.org.ua/admin-activiti
Релиз:
igov.org.ua
region.igov.org.ua
region.igov.org.ua/admin
region.igov.org.ua/admin-activiti

И откорректировать документацию на вики (во Нашем хозяйстве):
https://github.com/e-government-ua/i/wiki/%D0%9D%D0%B0%D1%88%D0%B5-%D1%85%D0%BE%D0%B7%D1%8F%D0%B9%D1%81%D1%82%D0%B2%D0%BE

**Comment by bvv4ik** [comment]
Для теста:
Можно зайти на вики и по серверам

**Comment by VadimGulich** [comment]
На вики порядок , на сервера заходит )
