### ISSUE TITLE
В разделе послуги, посвидчення особи, громадянство, мисце проживання, ошибка.

### ISSUE THREAD

**Issue by Alienhub** [e-government-ua/i#473]
Видача паспорта громадянина України для виїзду за кордон замість утраченого або викраденого.
Должно быть втраченого, а не утрачено.

![grammar mistake](https://cloud.githubusercontent.com/assets/13061861/8429087/02d4b432-1f2d-11e5-95b3-ba935f0813b8.png)

**Comment by bvv4ik** [comment]
Павел, глянь плиз

**Comment by bvv4ik** [comment]
Павел, закрывать таску можно?

**Comment by bvv4ik** [comment]
?

**Comment by bvv4ik** [comment]
эти данные хранятся в Service.csv, там нужно и править

**Comment by LamronNu** [comment]
Сполучення слів "замість утраченого", з точки зору правопису, правильне (відбувається чергування літер на початку слова відповідно до законів милозвучності української мови). Слово "замість" закінчується на приголосний ("ть"), тому наступне слово має починатися на голосний ("у").
Ось посилання на <a href="http://pravopys.kiev.ua/pravopys.aspx?SectionID=167">правопис</a> і <a href="http://zakon4.rada.gov.ua/laws/show/z1089-12">нормативно-правовий акт</a>  з цим сполученням слів (розділ 6).

також виправлено деякі інші помилки, які були помічені. Деталі -- у <a href="https://github.com/e-government-ua/i/commit/fb3db3e77919d65bb2251f528adb720dd1e77c61">комміті</a> (червоним і зеленим, що на що було змінено).

Тому для тесту можна повводити в поле "пошук послуги" відповідні слова та переконатись, що вони виправлені.

Якщо ж будуть знайдені подібні помилки/неточності в назвах послуг-- прошу їх дописати в цю таску. Якщо все ок -- то потестити та закрити питання)

**Comment by nazarenkod** [comment]
Все слова исправлены.
Одна маленькая ошибка колет глаз.Прошу исправить двойной пробел "(без додання  спирту)"
![2](https://cloud.githubusercontent.com/assets/13256486/8821865/8b455db0-3069-11e5-84be-96b71699710d.jpg)

**Comment by LamronNu** [comment]
)) о, да, из-за двойного пробела делать отдельный коммит и пересобирать проект... )

ок, я поправлю это у себя, но залью вместе с какой-то другой задачей, чтобы зря не "дергать" сервер..

если это принципиально -- ждите, когда отпишусь об коммите. если нет -- можно задачу закрывать.
спасибо!

**Comment by nazarenkod** [comment]
Не принципиально, просто мозолил глаз:)
