### ISSUE TITLE
Поднять фтп на трей серверах:и зашарить через них папки с логами (на чтение)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#474]
нужно поднять фтп на
трех серверах:
test.igov.org.ua - центральный альфа
test.region.igov.org.ua - региональный альфа
dniprorada.igov.org.ua - центральный и региональный бета

и зашарить через них вот эти папки:
/sybase/tomcat_wf-central/logs/
/sybase/tomcat_wf-region/logs/
(ТОЛЬКО на чтение !!!)

**Comment by bvv4ik** [comment]
sftp sftpuser@test.region.igov.org.ua
sftp sftpuser@test.igov.org.ua
sftp sftpuser@dniprorada.igov.org.ua
пароль: zaqxswcde

**Comment by VadimGulich** [comment]
Проверка будет через клиент FileZilla

**Comment by VadimGulich** [comment]
Доступ есть к логам и только на редактирование

**Comment by bvv4ik** [comment]
"и только на редактирование"
т.е. "только на чтение"?))

**Comment by VadimGulich** [comment]
да-да , только чтение ))
