### ISSUE TITLE
На бэке (wf-base) создать метод генерации HTML-кода кнопки "Проплаты по LiqPay" (для обращения к API LiqPay, через добавление в сервис-таске активити этого участка в тело письма)

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#475]
Написать метод, принимающий параметры. описывающие уникальные характеристики платежа, и отдающий HTML-код, который формирует собой кнопку, при нажатии на которую будет произведен редирект на LiqPay, для осуществления оплаты за услугу.

- [ ] 1) Метод назвать getPayButtonHTML_LiqPay, и принимать параметры:
sID_Merchant - ИД-строковой мерчанта (магазина), String
sSum - строка сумма платежа, String
sID_Currency - ИД-строковой валюты, String
sDescription - строка-описание, String
sID_Order - ИД-строковой заказа, String
sURL_CallbackStatusNew - УРЛ, на который будет обращение, после изменения статуса платежа, String
sURL_CallbackPaySuccess - УРЛ, на который будет обращение, после успешного платежа, String
bTest - если true, то "тестовый платеж", Boolean //опциональный
nID_Subject- ИД-числовой субъекта, Long

а в переменную: sPublicKey записать значение sID_Merchant
- [ ] 2) По полученным параметрам вызывать метод getMerchant(sID_Merchant), и получить там:
sPrivateKey (если еще отсутствует - временно "замокать")
sURL_CallbackStatusNew (только если такой параметр еще не задан ранее, и не null)
sURL_CallbackPaySuccess (только если такой параметр еще не задан ранее, и не null)
(метод реализуется по задаче https://github.com/e-government-ua/i/issues/511)

Так-же добавить к УРЛ-у "sURL_CallbackStatusNew" - параметры:
nID_Subject=nID_Subject пришедший
nID_Access=значение, полученное по олученного по методу setAccessData, с передачей туда значения nID_Subject

- [ ] 3) На основании параметров в п.1. и п.2.
создать JSON-объект с такими полями и передачей в них значений:
public_key = sPublicKey
amount = sSum
currency = sID_Currency
description = sDescription
order_id = sID_Order
server_url = sURL_CallbackStatusNew
result_url = sURL_CallbackPaySuccess
language = "ru"
sandbox = bTest

А строковое представление объекта записываем в переменную sJSON

- [ ] 4) На основании п.3. параметров и переменных в п.2. и п.3., сохраняем в новые переменные:
sData - результат функции base64_encode( ${sJSON} )
sSignature - результат функции base64_encode( sha1( ${sPrivateKey} . ${sData} . ${sPrivateKey} ) )

- [ ] 5) на основании переменных п.4. - возвращаем из метода ответ HTML-код, на основе шаблона:
```
<form method="POST" action="https://www.liqpay.com/api/checkout" 
   accept-charset="utf-8">
     <input type="hidden" name="data" value="${sData}"/>
     <input type="hidden" name="signature" value="${sSignature}"/>
     <input type="image" 
     src="//static.liqpay.com/buttons/p1ru.radius.png"/>
</form>
```

- [ ] 6) передаваемые в метод параметры и ответ обязательно описать в стандартной java-doc .к методу.

П.С.:Для справки, описание API LiqPay (Liq&Buy 3.0 public):
https://www.liqpay.com/ru/doc

**Comment by OlgaTurenko** [comment]
Для тестирования был написан сервисок:
https://test.igov.org.ua/wf-central/service/services/getPayButtonHTML_LiqPay?sID_Merchant=i10172968078&sSum=55,00&oID_Currency=UAH&oLanguage=RUSSIAN&sDescription=test&sID_Order=12345&sURL_CallbackStatusNew=&sURL_CallbackPaySuccess=&nID_Subject=1&bTest=true

**Comment by RoOmel** [comment]
Вместо параметра String sID_Currency - ИД-строковой валюты в сервисе присутствует параметр oID_Currency со значением UAH.
Подставлял в переменную: sPublicKey значение sID_Merchan - на результате это никак не отразилось.
Сервис работает согласно ТЗ.
![liqpay](https://cloud.githubusercontent.com/assets/12996514/8733254/a8b073ce-2c0b-11e5-91b3-db1dcf281246.jpg)
