### ISSUE TITLE
Визуализация ошибок на дашборде при отправке заявки  без обязательных к заполнению полей

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#477]
1.  Если  пользователь пытается отправить форму, где есть незаполненные обязательные поля, необходимо в понятной форме писать об этом  в сообщении об ошибке.(Пример как отображается сейчас - https://www.dropbox.com/s/z0hcyhpsc2220h6/error.JPG?dl=0). Возможный текст для таких ошибок : "Обов'язкові поля незаповнені"

2. Обязательное незаполненное поле ( после попытки отправить ) нужно подсвечивать красным.

**Comment by rostag** [comment]
Обидва пункти мають місце, та в даному випадку маємо скріншот з помилкою, яку генерує Activiti. Ось, core developer з Activiti каже у відповідь на схожу проблему: 

"What are the outgoing flows from "excusivegateway1" [я підставив тут назву нашого модулю]. Make sure that there is at least one that has a condition that evaluates to true OR have one as last flow in your XML without a condition."

http://forums.activiti.org/comment/16188#comment-16188

Цікаво розбіратися, що викликало цю помилку з "excusivegateway1", і чи відтворюється вона зараз, і як саме її можна відтворити.

**Comment by kurbpa** [comment]
@bvv4ik 
Всё ещё актуально

**Comment by katebutenko** [comment]
@kurbpa это не то же самое, что https://github.com/e-government-ua/i/issues/414 ? фикшу сейчас

**Comment by katebutenko** [comment]
подтверждено, что это дубликат #414 . Закрываю :)
