### ISSUE TITLE
Акутализация названий прикрепленных файлов  в дашборде

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#478]
Описание к файлу "вынести за пределы ссылки". Сейчас что при клике на название файла, что при ссылке на описание аттачмента - начинается довнлоад атачмента-файла. А должно только по клику на название файла.

ДЕТАЛЬНЕЙ:
Комментарий к прикрепляемому файлу (указанный после разделителя " ; ") добавляется на форме заявки в дашборде к названию файла, что далет в итоге затруднительным анализ приложений.

Например : 
скан паспорта в заявк  отображается как аттач с комментарием – Копія довідки з міста праці, додається тільки у випадку пільгової квартирної черги. 

Необходимо комментарий отображать как  комментарий к описанию файла (как это реализовано на форме подачи заявки  на портале igov)

**Comment by bvv4ik** [comment]
вот этого не совсем понял... нужно обсудить голосом

**Comment by annasahi** [comment]
Протестировано
