### ISSUE TITLE
Реализовать "контроллируемое" наследование атачментов из одних юзертасков в другие

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#479]
- [x] 1) В классе "FileTaskUpload", после вычитки ИД-шников Редис-а со стартовой формы (полей типа file) и прикрепления аттачментов - добавлять такие-же поля на этой юзертаске(с такими-же id), с сохранением в него ИД Атачмента, прикрепленных файлов, и присвоением типа invisible.

- [x] 2) Создать класс "FileTaskInheritance", на основе "FileTaskUpload", в котором смотреть поля предыдущей юзертаски(а не стартовой вормы как в образце), в которых если есть поле с id "aFieldInheritedAttachmentID", то брать его содержимое(в виде номеров, перечисленных через запятую,например "32434,32424,4354") и сплитить по "," в лист, и вытянув каждый атачмент из предыдущих юзертасок(по этим ИД) - прикрепить их к текущей юзертаске

П.С.: Если получится предложить альтернативный вариант гибкого и выборочного наследования атачментов из разных юзертасок - это  только будет приветствоваться!

**Comment by ASkosyr** [comment]
Ориентировочный срок поставки - конец недели, начало следующей (понедельник, вторник).
12-14 июля

**Comment by ASkosyr** [comment]
FileTaskInheritance реализован в виде листенера.

Пример подключения 
<activiti:taskListener event="create" delegateExpression="${fileTaskInheritance}">
   <activiti:field name="aFieldInheritedAttachmentID">
    <activiti:expression>${inheritedAttachments}</activiti:expression>
   </activiti:field>
</activiti:taskListener>

inheritedAttachments - название поля типа файл на стартовой форме.

Такой процесс реализован на тестовом сервер для услуги "Надання довідки про відсутність (наявність) судимості або обмежень, передбачених кримінально-процесуальним законодавством України" для г. Запорожье Запорожская область

В дашбоарде такие таски появляются с названием "Надання довідки про відсутність або наявність судимості (наслідувані атачменти)"
http://prntscr.com/7t6db3

**Comment by bvv4ik** [comment]
Павел, прошу попробовать реализацию наследования атачментов "в бою")

**Comment by kurbpa** [comment]
Протестировано. Работает.
