### ISSUE TITLE
Добавить на ГитХаб Вики полное перечисление с адресами имеющегося хозяйства (в разделе "Техническое хозяйство"):

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#48]
Добавить на ГитХаб Вики полное перечисление с адресами имеющегося хозяйства (в разделе "Техническое хозяйство"):
https://github.com/e-government-ua/dniprorada/wiki/%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5-%D1%85%D0%BE%D0%B7%D1%8F%D0%B9%D1%81%D1%82%D0%B2%D0%BE

(в т.ч.упорядочить)
1) все на амазоне (урл на админку)
2) все на томкэте (версии)
3) сейчас крутится 7 инстансов(на сколько я помню)
- тестовый фронт-ПэХаПэ
- тестовый фронт будущего дашборда JS 
- тестовый бэк активити
- боевой фронт-ПэХаПэ
- боевой фронт будущего дашборда JS 
- боевой бэк активити
- дженкинс (edited)
(их адреса, взять с описания джобов  http://dniprorada.egov.dp.ua:9000/)
4) адреса для ssh
(Макаренко Валерий сможет уточнить детали, его скайп: dn230384mvl)
5) остальные Важные характеристики

**Comment by ValerijMakarenko** [comment]
done

**Comment by ValerijMakarenko** [comment]
https://github.com/e-government-ua/i/wiki/%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5-%D1%85
