### ISSUE TITLE
S3 - З мобільного, не реагує на натиски кнопок що в шапці сайту

### ISSUE THREAD

**Issue by NikitaLyah** [e-government-ua/i#480]
Окружение  Iphone 5s ios 8.3 safari.

**Comment by bvv4ik** [comment]
Просьба перенести эту issue в бэклог и закрыть ее:
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit

**Comment by bvv4ik** [comment]
Еще актуально?
