### ISSUE TITLE
Верстка: при просмотре всех услуг в каждом подразделе реализовать переход в начало страницы

### ISSUE THREAD

**Issue by AlisaProskura** [e-government-ua/i#481]
Окружение:  Windows, Chrome 43.0.2357.130, FireFox 38.0.5
Ссылка: https://test.igov.org.ua/
Шаги воспроизведения:
1. Перейти на страницу  https://test.igov.org.ua/
2. Выбрать подраздел услуг, который содержит количество услуг превышающее количество, полностью отображаемое на странице.  
(Например, подразделы "Громадянам: Посвідчення особи, Громадянство, Місце проживання", "Бізнесу: Будівництво, нерухомість, земля", "Бізнесу: Довкілля" )
3.  Перейти по кнопке "Всі послуги" для просмотра полного списка услуг в подразделе. 

Ожидаемый результат: Осуществляется переход в начало страницы. Отображается название подраздела и список услуг с самого начала.  

Фактический результат: Осуществляется переход на середину страницы. Непонятно, какой это подраздел, список услуг отображается не с самого начала. Пользователю необходимо самому переходить в начало страницы.    

При этом в некоторых подразделах с большим количеством услуг страница просмотра всех услуг отображается с самого начала (например Громадянам: Міліція та ДАІ, Будівництво, нерухомість, земля )

**Comment by bvv4ik** [comment]
Алиса, скажите пожалуйста, ну какой это баг?
1) Отображение полного перечня услуг было реализовано именно в таком виде сознательно, и было акцептировано Дмитрием Александровичем (он еще сделал некоторые предложения по правкам, но они все не касались того, о чем говорите Вы)
2) Скролл просто остается на том месте где и был до клика, а не уходит на середину страницы.

по сему, если у Вас есть подобные предложения по улучшению юзабилити - подалуйста. можете или создавать их в таске, без каких-либо пометок "bug"(можно создать отдельный лэйбл "Предложение"), либо(что на много лучше) - создайте отдельный список в гуглодоке, с предложениями, и вышлите мне или Дмитрию Александровичу на почту ссылку на него...

т.к. маркер "bug" используется для того, чтоб действительно указать на "баг"(отклонение поведения от того, которое четко было описано и зафиксировано где-то в ТЗ)... А тут Вы пишете "ожидаемое поведение" - опираясь исключительно на свое субьективное "ожидание".
А по маркеру "баг", приоритет ставится наиболее высокий(вплоть до выливки напрямую на боевой)... Что совершенно не соответствует характеру того, о чем issue

А когда в каждом предложении Вы будете ставить его, то он просто нивелируется и дискредетируется, и на него просто перестаешь реагировать вообще...

Кроме того - список issue превращается в сущую свалку, когда разработчики не знают за что хвататься и что на самом деле приоритетно...

П.С.: и, пожалуйста, не проставляйте milestone ничего кроме test, кроме случаев, когда мы консолидированно пришли к решению куда-то это перенести и оформить как таску а не заклучение тестирования... И уж точно не в milestone - *PHP, т.к. в нем сейчас разработка не ведется!

Спасибо

**Comment by AlisaProskura** [comment]
Хорошо. Спасибо.

**Comment by bvv4ik** [comment]
создана производная: https://github.com/e-government-ua/i/issues/589
