### ISSUE TITLE
На главном портале, в "Документы", "Пошук документу за кодом" - добавить поля и подвязать вызов реализованного сервиса получения документа по ID (к которому открыт доступ)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#482]
- [x] 1) Добавить элементы:
- [x] 1.1) Оберить тип документу": [комбобокс]
- [x] 1.2) Оберить оператора: [комбобокс]
- [x] 1.3) Введіть код доступу до документу [input]
- [x] 1.4)  [Знайти(кнопка)]
- [x] 2) по документации: https://github.com/e-government-ua/i/blob/test/docs/specification.md#9_workWithDocuments
- [x] 2.1) наполнять список: "Оберить оператора":
метод getDocumentOperators
- [x] 2.2) наполнять список: "Оберить тип документу":
метод getDocumentTypes
- [x] 2.3) оживить кнопку: "Оберить тип документу":
метод getDocumentAccessByHandler
Куда передавать:
sCode_DocumentAccess - код доступа документа (строка из "Введіть код доступу до документу")
nID_DocumentOperator_SubjectOrgan - код органа(оператора) (номер-ИД из "Оберить оператора")
nID_DocumentType - типа документа  (номер-ИД из "Оберить тип документу")
- [x] 3) Если в ответ на нажатие кнопки(вызов сервиса) будет получен ответ:
"Document Access wrong password"
- отрисовать дополнително:
"Введіть отриманий Вами SMS код: [input]"
 [Підтвердити(кнопка)]
При нажатии кнопки, повторить предідущий вызов сервиса, передав туда дополнительно введенній код из поля в параметре: 
sPass - пароль для доступа к документу
(иначе переходим к п.4)
- [x] 4) В результате полученный объект документа отрисовать в виде строки таблицы, как это реализовано в "Моих документах", за исключением отрисовки иконки "предоставления доступа"
- [x] 5) Иконку "Загрузки документа" подвязать к такому-же вызову сервиса, как и в Моих документах, но дополнительно передавать туда все те-же параметры, которые передавались в предыдущих пунктах:
sCode_DocumentAccess
nID_DocumentOperator_SubjectOrgan
nID_DocumentType
sPass (передавать только если был выполнен п.3.)
(запоминать эти параметры в cookie, и перезаписывать при поисках других документов)

**Comment by bvv4ik** [comment]
Для теста
код 2
тип: справка
оператор: iGov
СМС-пароль: 123
должно выдать документ, который можно будет загрузить

**Comment by RoOmel** [comment]
Окружение Chrome 43.0, Firefox 39.0, IE 11.0
 1.1) Оберить тип документу": [комбобокс] - простой выпадающий список, т.е. без поля ввода;
1.2) Оберить оператора: [комбобокс] - простой выпадающий список, т.е. без поля ввода;
1.3) Введіть код доступу до документу [input] - поле позволяет вводить символы
1.4) [Знайти(кнопка)] - кликабельна
SMS не приходит
Поле с надписью "Document Access need password - sent SMS" нередактируемо
SMS куда вводить?

**Comment by AVATOR** [comment]
вот что должно получится https://github.com/e-government-ua/i/issues/533#issuecomment-121935213 когда вводишь тестовые данные

**Comment by RoOmel** [comment]
Отображается только текст "Document Access need password - sent SMS" в нижнем поле
Всё, конец фильма)

**Comment by RoOmel** [comment]
Тетовые данные:
оператор: iGov
тип: справка
код 2

**Comment by AVATOR** [comment]
сейчас должно работать. sms код новый: 444

**Comment by RoOmel** [comment]
Поле "Введіть отриманий Вами SMS код*" стало доступно для ввода.
Пароль отправляется.
Документ доступен для загрузки.
Загруженный док-нт с текстом "No content!!!"

**Comment by RoOmel** [comment]
Данный модуль выполняется согласно ТЗ.
