### ISSUE TITLE
При создании справки "Взяття на облік громадян, які потребують поліпшення житлових умов" происходит  редирект на страницу 

### ISSUE THREAD

**Issue by AlisaProskura** [e-government-ua/i#483]
Окружение: Windows, Chrome 43.0.2357.130, FireFox 38.0.5
Ссылка: https://test.igov.org.ua/
              https://test.igov.org.ua/service/17/general

Шаги воспроизведения:
1. Перейти по ссылке на страницу справки "Взяття на облік громадян, які потребують поліпшення житлових умов" (данная справка есть в списке "22 — послуги доступно онлайн" ) https://test.igov.org.ua/service/17/general
2. На шаге 1 выбрать область и город

Ожидаемый результат: Отображается шаг 2 (в строке содержится одна или все две ссылки на авторизацию). 
Ниже отображается кнопка "Перейти"

Фактический результат: Отображается шаг 2  - пустая строка (зачем она? или не отображаются ссылки на авторизацию, или если они не нужны, то убрать шаг 2). 
Ниже отображается кнопка "Перейти"
![image](https://cloud.githubusercontent.com/assets/12996328/8456884/e5a384ac-2016-11e5-8e8f-7c1133022220.png)

3. Нажать на кнопку  "Перейти"

Ожидаемый результат: Открывается форма для заполнения информации для справки

Фактический результат: Происходит редирект на перечень всех услуг на странице https://dniprorada.igov.org.ua/

**Comment by bvv4ik** [comment]
этот тип услуги называется "Ссылка" (а не встроенная услуга, как другие)
и ее функция - перенаправить гражданина туда, где он сможет получить эту услугу...

**Comment by bvv4ik** [comment]
там обычно еще перед кнопкой пишется пояснение, но по данной услуги оно просто еще не заполнено

**Comment by AlisaProskura** [comment]
Получается, сейчас пользователь заходит в справку "Взяття на облік громадян, які потребують поліпшення житлових умов" https://test.igov.org.ua/service/17/general, но вместо перехода в форму заполнения он попадает на страницу всех услуг https://dniprorada.igov.org.ua/
Сама форма не готова?

**Comment by bvv4ik** [comment]
в данном случае это тестовая строка услуги)
на боевом он отсутствует...

**Comment by polosatui** [comment]
У меня вопрос, а переход с  https://test.igov.org.ua/service/17/general,на https://dniprorada.igov.org.ua/  в обязательном порядке происходит в новой вкладке? Просто с точки зрения пользователя - визуально все идентично, но новая вкладка+иной адрес, создается впичетление подставной страници какой то

**Comment by bvv4ik** [comment]
было специально так задумано - в новой странице

**Comment by polosatui** [comment]
Я понял, спасибо.
