### ISSUE TITLE
Функционал [S4] - Форма печати заявления на дашборде требует доработки

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#485]
1. Окно предварительного просмотра не закрывается при нажатии на пиктограмму "Х".
2. Кнопка "Роздрукувати" видна только после скроллинга страницы.
3. Интуитивно не понятно где страницу предварительного просмотра нужно видеть.

Исходная задача https://github.com/e-government-ua/i/issues/434

**Comment by bvv4ik** [comment]
1. закрывается (сам проверял)
2. она и должна отображаться в конце всех полей (так была задумана реализация)
3. эту кнопку чиновники должны знать "как Отче наш", т.к. сразу по завершению работы с заявкой они должны будут ее распечатать... 

в который раз прошу - не ставьте вы постоянно на все подряд этот маркер "баг"! Это ни какой не баг! Если есть предложения по юзабилити - предлагайте, но не в такой ворме... просто загажевается массив issue, в нем перестают совершенно ориентироваться разработчики..
почитайте пожалуйста инструкцию для тестировщиков, и поправьте то что полагается:
https://github.com/e-government-ua/i/wiki/Тестування-проекту

**Comment by RoOmel** [comment]
Маркер "Баг" стоит правильно, т.к.:
1. Не закрывается при нажатии на пиктограмму "Х" в браузерах: IE v.11, Firefox v.38, Chrome v.43 - это явно не фича и не патч.
3. Интуитивно не понятно, где страницу предварительного просмотра нужно видеть - это не про кнопку, а про страницу предварительного просмотра.
Она должна отображаться юзеру сразу, а не пользователь должен думать и искать её - это тоже не предложение по юзабилити.

**Comment by RoOmel** [comment]
kurbpa прокомментировал тоже самое неделю назад, кроме пиктограммы "Х"

**Comment by bvv4ik** [comment]
Уважаемый @RoOmel мне жалко своего и твоего времени на подобную бессмысленную переписку. И у меня и у тебя, уверен, других дел по горло!
Потому, прошу - больше никогда не писать предложения по улучшению и свои субьективные ощущения о том, что "интуитивно не понятно"
и тем более не мешать все в одну кучу!

задача отклонена, если мне Павел покажет как это не работает крестик, и что это не в рамках уже существующей решающейся задачи - он сам таску и поставит, или я поставлю.
