### ISSUE TITLE
S3 - Неінтерактивний dropdown "Область" після вибору значення

### ISSUE THREAD

**Issue by art-tykh** [e-government-ua/i#486]
**Оточення**:  Mac OS X 10.9.5, Chrome Version 43.0.2357.124, Firefox  38.0.5

**STR**:
1. Відкрити https://test.igov.org.ua/service/1/general
2. В dropdown "Область" вибрати будь-яке значення.
3. Спробувати вибрати іншу область.

AR: Випадково вибравши не свою область користувач не має можливості змінити свій вибір.
ER: Користувач повинен мати можливість змінити свій вибір. 

![screen shot 2015-07-01 at 17 53 57](https://cloud.githubusercontent.com/assets/1598859/8457515/8083cf9c-201a-11e5-8ca7-7a733a55b360.png)

**Comment by bvv4ik** [comment]
это дубль,
в работе уже стоит задача по реализации данного функционала

**Comment by art-tykh** [comment]
Duplicate for https://github.com/e-government-ua/i/issues/423
