### ISSUE TITLE
На бэке(wf-base) реализовать сущность джоина-субьекта-органа (с заливкой справочника МВД) и сервисы работы с ним

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#487]
ВАЖНО:
реализовывать все в том-же стиле, что и реализовано все в методах getDocuments, setDocumentFile и т.д. чтоб так-же с Hibernate, DAO, Liquibase и инициализационными таблицами *.csv

- [ ] 1) Сущность SubjectOrganJoin
nID - ИД-номер автоитеррируемый (уникальный, обязательный) (long)
nID_SubjectOrgan - ИД-номер (long)
sNameRu - строка <200 символов
sNameUa - ИД-строка <200 символов
sID_Privat - ИД-строка ключ-частный <60 символов //опциональный
sID_Public - строка ключ-публичный <60 символов
sGeoLongitude - строка долготы //опциональный
sGeoLatitude - строка широты //опциональный
nID_Region - ИД-номер //опциональный
nID_City - ИД-номер //опциональный
sID_UA - ИД-строка кода классификатора КОАТУУ //опциональный

- [ ] 2) Образец объекта:
{
"nID":356
, "sNameRu":"ВІННИЦЬКИЙ МВ УМВСУ У ВІННИЦЬКІЙ ОБЛ."
, "sNameUa":"ВИННИЦКИЙ ГОВД"
, "sID_Privat":"120666"
, "sID_Public":"130501"
, "sGeoLongitude":"49.2330830"
, "sGeoLatitude":"28.4477540"
, "nID_Region":12 //опциональный
, "nID_City":33 //опциональный
, "sID_UA":Э32343Э //опциональный
}

- [ ] 3) сервисы:
- [ ] 3.1) getSubjectOrganJoins - получает массив объектов п.2,
(либо всех либо в рамках заданных в запросе nID_Region, nID_City или sID_UA)
параметры:
nID_SubjectOrgan - ИД-номер (в урл-е)
nID_Region - ИД-номер (в урл-е) //опциональный (фильтр)
nID_City - ИД-номер (в урл-е) //опциональный (фильтр)
sID_UA - ИД-строка (в урл-е) //опциональный (фильтр)
- [ ] 3.2) setSubjectOrganJoins - добавляет/обновляет массив объектов п.2,
(сопоставляя по по ИД, и связывая новые с nID_Region, nID_City или sID_UA, по совпадению их названий)
параметры:
nID_SubjectOrgan - ИД-номер
В ТЕЛЕ - массив объектов(п.2) sID_Public
(если в объектах массива элементы nID_Region и nID_City не указваны, но в новых записях проставлять их как null, а в обновляемых - просто оставлять прежними)

- [ ] 3.3) removeSubjectOrganJoins - удаляет массив объектов п.2, (находя их по ИД)
параметры:
nID_SubjectOrgan - ИД-номер (в урл-е)
asID_Public - массив ИД-номеров  (в урл-е) (например [3423,52354,62356,63434])

- [ ] 4) для п.п. 3.2 реализовать специальный класс распознавания 
nID_Region и nID_City, по их коду классификатора КОАТУУ (sID_UA)
отрабатывать его тогда, когда в элементах передаваемого массива объектов они не указаны
и если будет найдено соответствие, то подставлять их ИД-шник

- [ ] 5) Добавить документацию на Вики (в АПИ)

- [ ] 6) залить справочник
(за справочником. который нужно залить нужно обратиться в скайп belyavtsevw)

**Comment by bvv4ik** [comment]
для теста:

Get: 
Method: GET
https://test.igov.org.ua/wf-central/service/services/getSubjectOrganJoins?nID_SubjectOrgan=1&sID_UA=1

Set
Method: POST
https://test.igov.org.ua/wf-central/service/services/setSubjectOrganJoins
[{"subjectOrganId":1,"sNameUa":"Українська мова","sNameRu":"Русский язык","sID_Privat":"12345","sID_Public":"130501","sGeoLongitude":"15.232312","sGeoLatitude":"23.234231"}]

Remove
Method: POST
https://test.igov.org.ua/wf-central/service/services/removeSubjectOrganJoins?nID_SubjectOrgan=1&asID_Public=130505,130506,130507,130508

**Comment by VadimGulich** [comment]
Работает удаление/добавление/получение

Хотелось бы уточнить момент, чего нет ответа после выполнение запроса на удаление/добавление массива?

И в описании , наверное нужно указать , что при создании/обновлении нужно использовать чуть больше параметров , чем указано в описании "Пример: https://test.igov.org.ua/wf-central/service/services/setSubjectOrganJoin?nID_SubjectOrgan=1&sNameRu=Днепр.РОВД " ) 

В целом задача реализована и протестирована.

**Comment by bvv4ik** [comment]
это лишь пример (ссылка)... а в описании сами поля, которые могут быть указаны - описаны

**Comment by bvv4ik** [comment]
"чего нет ответа после выполнение запроса на удаление/добавление массива?"
ответа и не должно быть... так задумано
ответ только в гетере

**Comment by VadimGulich** [comment]
Понял , спасибо за ответы
