### ISSUE TITLE
[S5] Съехал выпадающий список по городам 

### ISSUE THREAD

**Issue by VadimGulich** [e-government-ua/i#488]
![image](https://cloud.githubusercontent.com/assets/12964120/8471001/fee717dc-209b-11e5-8a1d-719d32bd064e.png)

Ожидаемы результат:  выпадающий список отображается по всей ширине формы "місто"

**Comment by bvv4ik** [comment]
та он не сьехал, а он всегда был такой...
уже и не знаю - писать что-ли отдельную инструкцию, чоб различали "баг" от "не реализованного функционала".
Основное отличие - "реализация отличается от написанного в ТЗ" (тут нет того описания в ТЗ которое-бы это регламентировало)
Вспомогательное отличие - неполучается реализовать задуманный функционал!

**Comment by VadimGulich** [comment]
Из таких мелочей складывается общее впечатление о нашем ресурсе ))
Хорошо , замечания приняты , реализацию задачи тестируем в рамках поставленной задачи.

**Comment by bvv4ik** [comment]
в таких случая больше не используем лэйбл "баг"!
используем только что созданный мной лэйбл "remark"

Критерии бага:
Основное отличие - "реализация отличается от написанного в ТЗ"
Вспомогательное отличие - неполучается реализовать задуманный функционал!

все остальное - remark

П.С: в мире, кроме "черного и белого" - существует еще бесконечность оттенков, например серого. так вот и будем пользоваться всей палитрой! Это нужно для более эффективной работы в рамках всего проекта!

**Comment by bvv4ik** [comment]
Просьба перенести эту issue в бэклог и закрыть ее:
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit
