### ISSUE TITLE
Отображается ошибка 404 в браузере IE при нажатии на "BankID" на форме "Документи"

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#489]
Отображается ошибка 404 в браузере IE при нажатии на "BankID" на форме "Документи"

**Comment by bvv4ik** [comment]
только что сам перепроверил - все нормально.
в Моих Документах вообще не должно быть Крок 1
можно скриншот плиз?

**Comment by RoOmel** [comment]
![bug_igov_07](https://cloud.githubusercontent.com/assets/12996514/8496802/b36be644-2180-11e5-83f5-df0521e5290c.jpg)

**Comment by RoOmel** [comment]
в IE ещё интереснее:
1. при нажатии на  "Мої документи"
![bug_igov_07](https://cloud.githubusercontent.com/assets/12996514/8496939/b888a184-2181-11e5-8d49-595c69122835.jpg)
2. При нажатии на "BankID"
![bug_igov_07_01](https://cloud.githubusercontent.com/assets/12996514/8496954/e293820a-2181-11e5-921e-d0c7dfc3a75e.jpg)

**Comment by RoOmel** [comment]
Итого ,согласно https://github.com/e-government-ua/i/issues/482:
1. пункты 1 - 3 не реализованы
2. пункты 4 - 5 нет возможности проверить

**Comment by bvv4ik** [comment]
ну фразу Крок 1, наверно таки нужно будет убрать... ибо Крок-а два не будет , скорей всего , никогда. но все такие мелочи нужно писать в отдельном гуглодоке, списком... иначе это загромождает реальные таски.

но не понял по поводу "циклической ссылки".
у меня мои документы открываются, авторизация проходит успешно, список документов появляется^
![image](https://cloud.githubusercontent.com/assets/4208821/8497800/d4bf7682-2188-11e5-8719-4aacd9aca9c9.png)

и по поводу "чем все-же интереснее в IE", не понял...

**Comment by RoOmel** [comment]
Циклическая авторизация, а не циклическая ссылка.
Документы отображаются - согласен.
Но при переходе от вкладок "Нотаріусам" и "Пошук документу за кодом" к вкладке "Мої документи" отображается снова "Крок 1. Увійдіть в систему через BankID", т.е. сессия работы прерывается по какой-то причине и нужно каждый раз проходить авторизацию, чтобы увидеть свои документы.

Я же написал, что в IE (в отличии от Chrome и Firefox) при нажатии на "BankID" отображается страница ошибки 404 - скриншот приаттачен выше.

**Comment by bvv4ik** [comment]
авторизация не циклическая а "не вечная".. она живет какое-т овремя, а потом  умерает... это нормально

по остальному(кросброузерности, в частрости IE)
прошу:
-изменить соотв. название issue
-ее описание
-поместить в milestones test
-пометить bug
