### ISSUE TITLE
сделать нормальный календарь.

### ISSUE THREAD

**Issue by smit-pb** [e-government-ua/i#490]
https://github.com/e-government-ua/i/issues/374
календарь - Необходимо локализировать, и чтобы модальное окно было на весь календарь, без всяких доп полос прокрутки.

**Comment by bvv4ik** [comment]
1) "а Вы можете создать таску в milestones - "test", с лэйблом "remark""
тут только лэйбл

2) кроме того, я писал "валидация сейчас в работе..."
потому не надо было дублировать ее

3) так-же, не надо в одну issue, даже если она "remark" - "пихать все задачи", в каждой issue своя, должна быть... а по хорошему, такие списки мелких предложений нужно в одном гуглофайле вести.

4) Пожалуйста, не пишите тасок - "как должно быть" ,или "как необходимо". Пишите то, что "Вам показалось неудобным и недоработанным". т.к. иначе, у разработчиков складывается впечатление, что это прямое руководство к действию... И, я думаю, Вы догадываетесь, что будет дальше, если каждый будет писать то что ему кажется правильным, а другие будут все это реализовывать - получится как когда в мультфильме "Простоквашино" писали письмо "родителям Дяди Федора"(когда лохматость потом повысилась)

П.С.: ребята, такое количество "хотелок", которые "затмевают" реальные задачи, на которые должны обращать внимание разработчики - парализует реальный процесс разработки и реальной работы над базовыми элементами проекта! issue для реально полноценно сформулированных, описанных и утвержденных задач! Или для реальных багов, которые блокируют какой-то функционал или подрывают безопасность. Все остальные - "хотелки, пожелалки и замечалки",в идеале, в отдельном гуглодоке-списке

**Comment by smit-pb** [comment]
Создавалось в Testing - почему был глюк - ХЗ. 
Спасибо - поправил , перенес.
Счета данную задачу - не хотелкой - а необходимостью. Но возможно с низким приоритетом.

Когда в поля для отправки данных в гос органы , можно впихнуть все что угодно - это абсолютно не есть хорошо. 
Касательно отображения календаря - это тоже не хорошо когда локализация отличается от текущей, да еще и появляются различные полосы прокрутки.
![image](https://cloud.githubusercontent.com/assets/12965717/8497249/57dff5a0-2184-11e5-9fdf-50d8adef9236.png)

**Comment by bvv4ik** [comment]
"Когда в поля для отправки данных в гос органы , можно впихнуть все что угодно - это абсолютно не есть хорошо. 
Касательно отображения календаря - это тоже не хорошо когда локализация отличается от текущей, да еще и появляются различные полосы прокрутки."
У нас только РАЗРАБАТЫВАЮЩИЙСЯ  проект, а не РЕАЛИЗОВАННЫЙ! В нем еще тьма тьмущая чего нужно сделать, и для того чтоб это можно было воплотить в реальность, с теми ресурсами .которые есть у нас в наличии - нужно очень-очень быть аккуратным с приоритетами и задачами! И вот как раз приоретизированием всего перечня задач и занимаются те люди(в т.ч.я) .которые курируют весь проект в целом! Ваша-же задача, в первую очередь, - находить ошибки/отклонения в реализации по ПЕРЕДАННЫМ ВАМ ДЛЯ ПРОВЕРКИ задачам! Ну, или, если нашли действительно важную дыру в безопасности. Или действительно перестал работать функционал и ни как не получается выполнить действие! Все!
А уже если у вас после выполнения этих главных задач останется время на что-то другое(например нахождение орфографических ошибок или "некрасивостей в дизайне", то Вам спасибо скажем, конечно-же, но ТОЛЬКО если вы не будете накидывать такие "замечания" в общий список issue! т.к. он для другого предназначен! Повторяю в десятый(минимум) раз, все такие задачи пишите в общем гуглофайле (бэклоге), к которому периодически мы сможем обращаться, "одинокими зимними вечерами"... Иначе это все превращается в бардак и совершенно бессовестный перевод драгоценного сейчас времени (и вашего и нашего)!
Работа должна приносить пользу, согласны-ж с этим? Вот я и описываю те критерии, при соблюдении которых это будет реальная польза!
Спасибо!

**Comment by bvv4ik** [comment]
Просьба перенести эту issue в бэклог и закрыть ее:
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit

**Comment by smit-pb** [comment]
Не исправлено. Перенесено в фаил https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit
Ждет своего времени ;)
