### ISSUE TITLE
Добавить еще один профиль Спринга в весь проект вмест отекущих "prod" и "test,default", должно быть "prod", "test" и "local,default" и в новом "test" ссылаться на каталог catalina и на тестовых серверах установить его(test), вместо prod

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#492]

**Comment by bvv4ik** [comment]
Для теста, можно убедиться что новый профиль добавлен:
https://github.com/e-government-ua/i/blob/test/wf-base/src/main/resources/context.xml

**Comment by VadimGulich** [comment]
<beans profile="prod">
 <beans profile="test">
<beans profile="local,default">
Проверено
