### ISSUE TITLE
Реализовать на бэке wf-base - сущности и сервисы по сохранению и получению статуса заявок "объект события по услуге"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#493]
- [x] 1) Сущность HistoryEvent_Service (объект события по услуге)
nID - ИД-номер автоитерируемый (уникальный, обязательный) (long)
sID - ИД-строка
nID_Task - ИД-номер задачи (long)
nID_Subject - ИД-номер (long) //опциональный
sStatus - строка-статус
sID_Status - строка-статус //опциональный

- [x] 2) Образец объекта:
{
"nID":356
, "sID":"Kukds9823r"
, "nID_Task":3534453
, "nID_Subject":234
, "sStatus":"Одобрено"
, "sID_Status":"accepted"
}

- [x] 3) сервисы:
- [x] 3.1) getHistoryEvent_Service - получает объект п.2,
параметры:
sID - ИД-строка (в урл-е)
Если не найдена запись возвращать объект ошибки со значением "Record not found"
- [x] 3.2) addHistoryEvent_Service - добавляет объект п.2,
параметры:
nID_Task - ИД-номер задачи (long)
nID_Subject - ИД-номер (long) //опциональный
sStatus - строка-статус (long)
sID_Status - строка-статус (long) //опциональный
для авто-генерации значения поля sID:
- использовать алгоритм Луна  (10 символов)
- закладывать nID в основу - как логин
- закладывать случайно-сгенерированный код в основу - как логин
- [x] 3.3) updateHistoryEvent_Service - добавляет/обновляет объект п.2,
параметры:
nID - ИД-номер
sStatus - строка-статус
sID_Status - строка-статус (long) //опциональный
Если не найдена запись возвращать объект ошибки со значением "Record not found"

- [x] 4) Добавить документацию на Вики (в АПИ)

П.С.: пока делаем sID - опциональным, и реализуем такой механизм "защиты от ошибки":
1) в add-методе, после добавления записи, берем nID(например: "1232132"), пропускаем его через алгоритм Луна(получая, например "1"(взято "на абум")), и добавляя полученное число контрольной суммы справа, выдавая в ответе, например: {"nID":1232132, "nID_Protected":12321321}
2) в get и update-методах берем заданное число в параметре "nID_Protected", например "12321321" (именно, не sID, а nID_Protected!)
"отсекаем" от него правое число (контрольную сумму), например "1232132" и пропускаем через алгоритм Луна, сверяя потом полученную контрольную сумму, например "1".
- если совпадает - ищем запись по nID (исходное nID_Protected, с отсеченной правой цифрой) и отдаем объект, как обычно(либо еще и апдейт, если это update)
- если НЕ совпадает - выдаете ошибку "CRC Error"
- если совпадает но не находит запись - пишем стандартную ошибку "Record not found"

П.П.С.: Алгоритм генерации sID (ПОКА НЕ РЕАЛИЗУЕМ ВООБЩЕ!!!)
Вот калькулятор по Луне: http://planetcalc.ru/2464/ (сам алгоритм наверняка уже дето в готовой либе есть)
а) допустим у нас есть в nID число "12345678"
по алгоритму получаем:
Последний разряд контрольной суммы: 4
Следующая проверочная цифра: 2
б) так-же берем nID_Subject (как логин), например 16
по алгоритму получаем:
Последний разряд контрольной суммы: 8
Следующая проверочная цифра: 6
в) "собираем воедино все цифры":
12345678 & 4 & 2 & 16 & 8 & 6
т.е.: 12345678421686
г) превращаем это десятиричное число в 27+27+10=64-ричное, символьное из латинских больших(27) и маленьких(27) букв и цифр(10)
получим что-то вроде G8hi3, т.е. 5 символов (взято "на абум", т.к. "под рукой" небыло калькулятора перевода в 64-ричную систему)
д) остается еще 5 свободных (до 10-ти обозначенных в задании), для случаянно-сгенерированного пароля
например, 7Klg2
е) в итоге получаем уникальный sID="G8hi37Klg2", которы никогда не повторится, если nID и nID_Subject будут другими нежели в нашем случае (даже если когдато сгенерится такой-же пароль)

П.П.С.: "Статус заявок" в https://docs.google.com/document/d/16fnxyvEyzuBcVFEd3s6e_AJqAELvSAl4GydB4AH3R9M/edit#

**Comment by LamronNu** [comment]
**temporary** task done without algorithm Luna and with GET-methods for add/update records.

for test:
1) add new HistoryEvent_Service
https://test.igov.org.ua/wf-central/service/services/addHistoryEvent_Service?nID_Task=1&sStatus=new&nID_Subject=2

response: sID of new record

2) check result (get-method):
https://test.igov.org.ua/wf-central/service/services/getHistoryEvent_Service?sID=xxx
where xxx -- nID from previous response
response:
```json
{
"nID":20081,
"sID":"20081",
"nID_Task":1,
"nID_Subject":2,
"sStatus":"new",
"sID_Status":null,
"id":20081   // ???
}
```
3) update-method:
https://test.igov.org.ua/wf-central/service/services/getHistoryEvent_Service?nID=xxx&sStatus=edit

response: nothing (void method)    // ??

**Comment by bvv4ik** [comment]
ВАЖНО!
Пока не приступили к реализации последнего шага по алгоритму Луна, прошу прочитать корректировку приоритета(не будем пока генерировать sID, это слишком сложно).

Пока делаем sID - опциональным, и реализуем такой механизм "защиты от ошибки":
1) в add-методе, после добавления записи, берем nID(например: "1232132"), пропускаем его через алгоритм Луна(получая, например "1"(взято "на абум")), и добавляя полученное число контрольной суммы справа, выдавая в ответе, например: {"nID":1232132, "nID_Protected":12321321}
2) в get и update-методах берем заданное число в параметре "nID_Protected", например "12321321" (именно, не sID, а nID_Protected!)
"отсекаем" от него правое число (контрольную сумму), например "1232132" и пропускаем через алгоритм Луна, сверяя потом полученную контрольную сумму, например "1".
- если совпадает - ищем запись по nID (исходное nID_Protected, с отсеченной правой цифрой) и отдаем объект, как обычно(либо еще и апдейт, если это update)
- если НЕ совпадает - выдаете ошибку "CRC Error"
- если совпадает но не находит запись - пишем стандартную ошибку "Record not found"

**Comment by bvv4ik** [comment]
и на английском лучше коменты не писать, а то ведь не все тестировщики и разработчики так легко его читают)

**Comment by LamronNu** [comment]
тесты -- согласно <a href="https://github.com/e-government-ua/i/blob/test/docs/specification.md#17_workWithHistoryEvent_Services">доке</a>

или ориентироваться на примеры: 
_1) добавление нового события_
http://test.igov.org.ua/wf-central/service/services/addHistoryEvent_Service?nID_Task=2&sStatus=new&nID_Subject=2
_2) редактирование_
2.1)
http://test.igov.org.ua/wf-central/service/services/updateHistoryEvent_Service?nID_Protected=12&sStatus=finish
должна быть ошибка *CRC error*
2.2)
http://test.igov.org.ua/wf-central/service/services/updateHistoryEvent_Service?nID_Protected=33&sStatus=finish
должна быть ошибка *Record not found*
2.3)
http://test.igov.org.ua/wf-central/service/services/updateHistoryEvent_Service?nID_Protected=11&sStatus=finish
должно быть все ок

_3) получение обьекта_
3.1)
http://test.igov.org.ua/wf-central/service/services/getHistoryEvent_Service?nID_Protected=20
должна быть ошибка *CRC error*
2.2)
http://test.igov.org.ua/wf-central/service/services/getHistoryEvent_Service?nID_Protected=55
должна быть ошибка *Record not found*
2.3)
http://test.igov.org.ua/wf-central/service/services/getHistoryEvent_Service?nID_Protected=22
должно быть все ок

**Comment by RoOmel** [comment]
Описание алгоритма Луна
https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC_%D0%9B%D1%83%D0%BD%D0%B0
Онлайн-калькулятор контрольной суммы по Алгоритму Луна
http://planetcalc.ru/2464/
(тестировал работу калькулятора на числах от 3-хзначных до 10-тизначных - ошибок в работе не нашёл пока)
Исходный код этого калькулятора можно взять по ссылке ниже
http://planetcalc.ru/personal/source/?id=2461

**Comment by LamronNu** [comment]
что именно имеется ввиду? какую цифру Вы ожидаете там увидеть?

согласно тому же калькулятору, который Вы указали, сейчас там берется "первое" значение, т.е. "Последний разряд контрольной суммы" (в <a href="https://github.com/e-government-ua/i/blob/test/docs/specification.md#17_workWithHistoryEvent_Services">документации</a> об этом тоже сказано, чтобы не было недоразумений:
*контрольная цифра -- это последний разряд суммы цифр числа nID по алгоритму Луна*)

Возможно, по Вашему мнению, там должна быть "следующая проверочная цифра" -- но такого в постановке задачи не было (переделать, при необходимости, дело пяти минут).

Алгоритм у меня немного другой, не через строки.

Числа проверялись по этому калькулятору, вот примеры (сгенерированные рандомно):
>test 0:   nID=303,   checkSum=6
>test 1:   nID=813,   checkSum=3 
>test 2:   nID=965,   checkSum=7
>test 3:   nID=98,   checkSum=7
>test 4:   nID=929,   checkSum=2
...

или "огромные числа" (лонг):
>test 0:   nID=746767933516710843,   checkSum=5
>test 1:   nID=171979859076009516,   checkSum=8
>test 2:   nID=260749693203987726,   checkSum=6
>test 3:   nID=709104497307275372,   checkSum=3
>test 4:   nID=332777621797381220,   checkSum=4
...

Если все же есть такие числа, при задании которых генерируется не то числа -- просьба их сообщить (конкретно, какое число, какая цифра получается и какая должна быть).

Но такого, по идее, быть не должно... Разве что при размере чисел от 19 знаков, но такой случай мы не рассматриваем, т.к. как это больше типа данных Long)

**Comment by RoOmel** [comment]
В ссылке на баг "Функционал [S3] - Последняя цифра nID_Protected при генерации не соответсвует логике алгоритма Луна #538" по тексту выше я подробно описал суть проблемы.

**Comment by RoOmel** [comment]
Тестировал согласно доки, указанной в таске.

**Comment by RoOmel** [comment]
Коммент перенёс по просьбе разработчика.
"По запросу
http://test.igov.org.ua/wf-central/service/services/updateHistoryEvent_Service?nID_Protected=33&sStatus=finish
Актуальный результат:
could not resolve property: nID of: org.wf.dp.dniprorada.model.HistoryEvent_Service
Ожидаемый результат:
Record not found"

**Comment by LamronNu** [comment]
спасибо за перенос)
по результату *could not resolve property: nID of: org.wf.dp.dniprorada.model.HistoryEvent_Service* сейчас посмотрю, что не так

**Comment by LamronNu** [comment]
поправлено.

**Comment by RoOmel** [comment]
LamronNu commented "тесты -- согласно доке"
Протестировано:
 - по описанию алгоритма Луна https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC_%D0%9B%D1%83%D0%BD%D0%B0
 - с помощью онлайн-калькулятора контрольной суммы по Алгоритму Луна http://planetcalc.ru/2464/

1. Добавление нового события
http://test.igov.org.ua/wf-central/service/services/addHistoryEvent_Service?nID_Task=2&sStatus=new&nID_Subject=2
Результат:
"nID_Protected": 203038,
"nID": 20303
Соотвествует ТЗ

2. Редактирование
2.1 http://test.igov.org.ua/wf-central/service/services/updateHistoryEvent_Service?nID_Protected=203037&sStatus=finish
	Результат:
	STATUS 403 Forbidden
	CRC Error
Соотвествует ТЗ

2.2 http://test.igov.org.ua/wf-central/service/services/updateHistoryEvent_Service?nID_Protected=203049&sStatus=finish
	STATUS 403 Forbidden
	Record not found
Соотвествует ТЗ

2.3 http://test.igov.org.ua/wf-central/service/services/updateHistoryEvent_Service?nID_Protected=203038&sStatus=finish
	Результат:
	STATUS 200 OK
Соотвествует ТЗ

3. Получение обьекта
3.1 http://test.igov.org.ua/wf-central/service/services/getHistoryEvent_Service?nID_Protected=203037
	Результат:
	STATUS 403 Forbidden
	CRC Error
Соотвествует ТЗ

3.2 http://test.igov.org.ua/wf-central/service/services/getHistoryEvent_Service?nID_Protected=203049
	Результат:
	STATUS 403 Forbidden
	Record not found
Соотвествует ТЗ

3.3 http://test.igov.org.ua/wf-central/service/services/getHistoryEvent_Service?nID_Protected=203038
	Результат:
	STATUS 200 OK
Соотвествует ТЗ
