### ISSUE TITLE
На бэке централа создать сервис добавления/обновления и удаления элемента в сущность "типов документов"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#494]
Сущность: DocumentType
Название полей в объекте JSON должны точно соответствовать полям в базе
1) Сервисы
- [x] 1.1) setDocumentType - возвращать объект ошибки, если не найден nID (при обновлении). И добавлять запись новую при при отсутствии заданного параметра nID
- [x] 1.2) removeDocumentType - возвращать объект ошибки, если не найден nID
2) nID не передавать, т.к. он автогенерируемый

- [x] 3) Добавить описание в доку

**Comment by LamronNu** [comment]
для теста
1) создать новый тип:
https://test.igov.org.ua/wf-central/service/services/setDocumentType?nID=100&sName=test
ответ: ```{"nID":20314,"sName":"test"}```
изменить (взять ид из предыдущего ответа):
https://test.igov.org.ua/wf-central/service/services/setDocumentType?nID=20314&sName=test2
ответ: ```{"nID":20314,"sName":"test2"}```

2) удалить запись. 
несуществующую: 
https://test.igov.org.ua/wf-central/service/services/removeDocumentType?nID=20312
ответ: ```403.Record not found```
существующую (созданную в п.2):
https://test.igov.org.ua/wf-central/service/services/removeDocumentContentType?nID=20314
ответ: ```200 ok``` (и при выборке всех типов ее уже не будет. запрос для выборки: https://test.igov.org.ua/wf-central/service/services/getDocumentTypes)

уже прописанные типы желательно не трогать, тестируем на "своих", созданных в п.1

документация -- в процессе

**Comment by VadimGulich** [comment]
Все работает согласно описанию
