### ISSUE TITLE
На бэке централа создать сервис получения списка типов контента документа, добавление и удаление элемента

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#495]
Сущность: DocumentContentType
Название полей в обьекде JSON должны точно соответствовать полям в базе
   1) Сервисы
- [x] 1.1) getDocumentContentTypes - возвращать массив объектов соотв.сущности в JSON
- [x] 1.2) setDocumentContentType - возвращать объект ошибки, если не найден nID (при обновлении). И добавлять запись новую при при отсутствии заданного параметра nID
- [x] 1.3) removeDocumentContentType - возвращать объект ошибки, если не найден nID
- [x] 2) Добавить описание в доку

**Comment by LamronNu** [comment]
для теста
1) перечень всех типов контента документа:
https://test.igov.org.ua/wf-central/service/services/getDocumentContentTypes

2) создать новый тип:
https://test.igov.org.ua/wf-central/service/services/setDocumentContentType?nID=10&sName=test
ответ: ```{"nID":20311,"sName":"test"}```
изменить (взять ид из предыдущего ответа):
https://test.igov.org.ua/wf-central/service/services/setDocumentContentType?nID=20311&sName=test2
ответ: ```{"nID":20311,"sName":"test2"}```

3) удалить запись. 
несуществующую: 
https://test.igov.org.ua/wf-central/service/services/removeDocumentContentType?nID=20312
ответ: ```403.Record not found```
существующую (созданную в п.2):
https://test.igov.org.ua/wf-central/service/services/removeDocumentContentType?nID=20311
ответ: ```200 ok``` (и при выборке всех типов ее уже не будет)

уже прописанные типы желательно не трогать, тестируем на "своих", созданных в п.2

документация -- в процессе

**Comment by VadimGulich** [comment]
Протестировано , все работает согласно описанию
