### ISSUE TITLE
Написать один юнит тест для всех дао.

### ISSUE THREAD

**Issue by brunneng** [e-government-ua/i#496]
Написать один юнит тест который будет вытаскивать все бины наследники от AbstractEntityDao и рефлективно вызывать открытые методы поиска (начиющиеся на get, find и тп) передавая в качестве параметров произвольные сгенерированные значения.  Будет проверятся только что метод не падает, а не то, находит ли он что-то или нет. Таким образом можно будет перехватывать тривиальные ошибки в построении критериев и запросов.

**Comment by dgroup** [comment]
+1

**Comment by dgroup** [comment]
Также надо обратить внимание что не все дао интерфейсы/реализации наследуются от AbstractEntityDao и BaseEntityDao.

Возможно для начала надо составить список существующих решений, и их отношений, и следовательно, возможно придется переработать текущую идею по тестированию.

**Comment by Invizible** [comment]
ок, займусь этим, может даже схемку потом размещу где-то

**Comment by dgroup** [comment]
:+1:

**Comment by bvv4ik** [comment]
@Invizible ну как, есть шансы на реализацию этого унитеста?
т.к. без него не сможем рефакторить по ДАО... стремно совсем будет

**Comment by Invizible** [comment]
вот как раз хотел спросить про этот таск. Я из описания не совсем понимаю что мы хотим протестировать. Я имею ввиду: какая польза рандомных вызовов? Что мы этим протестируем, проверку входных параметров? Просто я не сильно вижу смысла ровно в таком тесте. Я поддерживаю написание теста для самого этого AbstractEntityDao с помощью dbunit - это реально покажет работает он или нет. Даже если написать тест по описанию, то мы ничего перед рефакторингом не проверим, т.к. наследников всего несколько от этого класса. В идеале конечно же нужно написать тест на этот абстрактный класс и для каждого ДАО отдельно их специфические методы (отличные от базовых методов). И по-хорошему это нужно сделать перед рефакторингом, но сколько это займет времени?

**Comment by Invizible** [comment]
Возможно оптимальным вариантом будет:
1) написать тест для AbstractEntityDao
2) порефакторить все ДАО
3) запушить это все в отдельную ветку
4) и дальше расшарить эту работу на остальных: чтобы каждый взял ДАО, написал для него нормальный юнит тест с использованием dbunit и потом запустил этот тест 2 раза: 1 раз для оригинального ДАО и второй - для ДАО после рефакторинга. Если все работает как и работало - перенести эту 1 ДАО с тестом в ветку test

**Comment by brunneng** [comment]
Не очень понимаю зачем так сложно. Тест проверяет только то что строится корректный запрос. Например в сущнсоти поле "id" а в критерии использовали "nID", или не правильно сделали join и тп. И все, результаты запроса он не тестирует. Поэтому мне видится такая последовательность:
1) написать тест для всех дао наследующихся от AbstractEntityDao (или реализующих EntityDao)
2) убедится что ошибок нет, если есть - исправить.
3) порефакторить дао как мы договорились в другой таске - в результате число тестируемых дао резко возрастет.
4) убедится что ошибок нет, если есть - исправить.
Все!
Это не отменяет полноценных тестов для дао, а идет как дополнение к ним, позволяющее на первых порах пока полноценного теста нет выявить тривиальные ошибки в запросе.

**Comment by Invizible** [comment]
ок, я вас понял, но к дополнению к этому я все таки напишу тест для AbstractEntityDao на dbunit, чтобы быть увереным что после рефакторинга оно вобще работает

**Comment by bvv4ik** [comment]
"но к дополнению к этому я все таки напишу тест для AbstractEntityDao на dbunit, чтобы быть увереным что после рефакторинга оно вобще работает"
100% одобрямс!

**Comment by bvv4ik** [comment]
есть какие-то ориентиры по срокам?

**Comment by Invizible** [comment]
Тест для абстрактой дао на dbunit готов. По поводу этого теста, в течении следующей недели постараюсь сделать. Т.е. ориентировочно конец сл недели: четверг - пятница, если позволит время, то постараюсь раньше.

**Comment by bvv4ik** [comment]
гуд, спасибо!

**Comment by Invizible** [comment]
Знаете, начал писать тест, так что думаю, если не встречу подводных камней, то тест будет к началу недели :)

**Comment by Invizible** [comment]
Мои апдейты: черновая версия теста готова. Что умеет:
находит все даохи наследники от EntityDao и запускает методы начинающиееся с "get", "search", "find" с рандомными параметрами. Если вызов метода бросил хибер исключение - тест обрывается и выводится стек трейс.
Доведу на выходных до ума и можно будет заливать

**Comment by bvv4ik** [comment]
класс! очень ждем...

**Comment by Invizible** [comment]
Есть ли смысл заливать этот тест отдельно, или может залить уже этот тест с остальными изменениями по рефакторингу? Просто этот тест тестирует потомков от EntityDao, а их пока 4. Или можно сделать тестирование всех классов с суффиксом DAO в имени бина, но зачем на это, если после рефакторинга все будут потомками EntityDao

**Comment by Invizible** [comment]
Залил этот тест в отдельную ветку: https://github.com/e-government-ua/i/commit/58c05df2a2dddeca1d9a160db65f9534e049681f

**Comment by brunneng** [comment]
Привет.
"Есть ли смысл заливать этот тест отдельно, или может залить уже этот тест с остальными изменениями по рефакторингу? " да, есть смысл, чтобы после рефакторинга этот тест упал если при рефакторинге допустили багу.

Насчет самого теста есть такие замечания:
1) По возможности не создавать отдельный контекст testContext.xml без крайней необходимости. Чтобы тестовый спринговый контекст был как можно более приближен к реальному.
2) Для рандомных генераторов, добавить возможно задания seed по умолчанию - для того чтобы тест был стабилен, т.е. чтобы если тест проходил один раз, то он гарантированно бы проходил во второй раз (потому что seed один и тот же , и генераторы вернут те же значения параметров). 
3) В качестве параметров в метод поиска может передаваться некий POJO класс фильтр. Добавить генератор для POJO - который будет пытаться создавать его через конструктор без параметров и засечивать параметры через сеттеры (или если конструктора без параметров нет, то через конструктор с наибольшим, кол-вом параметров). Причем если внутри POJO есть другие классы POJO то создавать их так же рекурсивно.
4) Добавить возможность исключать отдельные классы dao и методы в dao из теста (на тот случай если для метода поиска есть некие ограничения на параметры, типа параметр больше 0 и т.п.)

**Comment by brunneng** [comment]
5) При логировании ошибки выводить строку с параметрами которые передали в метод.

**Comment by Invizible** [comment]
2 и 4 я сделал. по поводу 5: в логах при вызове метода логируются сгенерированые параметры и по логу это все можно посмотреть. Действительно ли вы хотите это продублировать в самом конце лога?

**Comment by brunneng** [comment]
Скажем так, если тест прошел успешно то какие там были случайные параметры - разработчика будет мало интересовать. А вот если упал - тогда уже интересно чтобы воспроизвести и подебажить. Поэтому если не сложно - сделайте пожалуйста чтобы они в эксепшене были, чтобы не приходилось где-то еще искать в логах.

**Comment by Invizible** [comment]
@brunneng ok, добавил отображение параметров в сообщение об фэйли методов. Все остальное тоже сделал, кроме 1го. Не хотелось бы тянуть весь контекст со всеми контроллерами и сервисами, чтобы запусть юнит тест, к-рый никак не связан с остальными бинами, ведь ДАО на то и дао, что в базу только ходят

**Comment by Invizible** [comment]
В общем вот что есть: https://github.com/e-government-ua/i/commit/db0934b5fd9ea36dab3640efa1423003576f172e

**Comment by brunneng** [comment]
Ок, если еще коммитил в ветку test - коммить. только
-               <hibernate.version>4.3.10.Final-fixed</hibernate.version>
+		<hibernate.version>4.3.10.Final</hibernate.version>
верни fixed версию.. Это мы пропатчили багу хибернетовскую связанную с работой с PostgreSQL. 
https://hibernate.atlassian.net/browse/HHH-9805
Они пофиксят в версии 4.3.11 , которая еще не вышла

**Comment by Invizible** [comment]
У меня просто были какие-то проблемы с этой версией, ну я попробую вернуть

**Comment by Invizible** [comment]
Версию хибера вернул, залил в ветку test

**Comment by brunneng** [comment]
Отлично. Такое интенсивное использование guava - впечатляет.. :)

**Comment by Invizible** [comment]
куда ж без нее

**Comment by brunneng** [comment]
таску можно закрывать?

**Comment by Invizible** [comment]
ну продолжать я уже буду таску #497 может быть и будут какие-то изменения касательно этого кода, но уже как часть той таски (вдруг что-то захочется изменить, добавить, подкрутить)

**Comment by brunneng** [comment]
ок. тогда закрываем
