### ISSUE TITLE
Vagrant помилка: "/sbin/mount.vboxsf: mounting failed with error : Protocol error"

### ISSUE THREAD

**Issue by 40rn05lyv** [e-government-ua/i#498]
Зробив все відповідно до https://github.com/e-government-ua/i/wiki/Project,-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0 ("виртуальная среда"), вкінці помилка:

==> default: /sbin/mount.vboxsf: mounting failed with the error
==> default: : Protocol error

Повний лог:

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty32'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty32' is up to date...
==> default: Setting the name of the VM: i_default_1436127190554_53236
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 8443 => 8443. Now on port 2200.
==> default: Fixed port collision for 9000 => 9000. Now on port 2201.
==> default: Fixed port collision for 22 => 2222. Now on port 2202.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 8443 => 2200 (adapter 1)
    default: 9000 => 2201 (adapter 1)
    default: 22 => 2202 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2202
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Checking for host entries
==> default: Configuring and enabling network interfaces...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: /sbin/mount.vboxsf: mounting failed with the error
==> default: : Protocol error
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by bvv4ik** [comment]
@versus глянь плиз, таки действительно бок в вагранте?

**Comment by alegast** [comment]
Опиши будь ласка  версії ПО на якому запускаеш: vitrualbox, OS, vagrant.  (більшість проблем були саме кросплатформенні) 
Було б інформативніше  якщо б запустити з дебаг отпцією (http://docs.vagrantup.com/v2/other/debugging.html)  і пикріпити сюди

**Comment by bvv4ik** [comment]
я так понял - проблема решена?

**Comment by elcreator** [comment]
Проблема остается. Window 7 x64, vagrant свежий, virtualbox 4.3.28.
В логах, кроме этой ошибки, пишет о разных версиях виртуалбокс тулзов на гостевой машине и хосте. На гостевой 4.3.10. Не думаю, что это должно мешать, но все же.
Альтернативную конфигурацию (в папке vagrant) я после нескольких фиксов, которые выложил как пулреквест, поднял (только wf-base). Фиксы понадобились в основном из-за того, что дебиан на вагранте монтирует виндовую папку с правами 0777 на все файлы, из-за чего внутри машины  эти файлы воспринимаются не как плейнтекстовые конфиги, а как исполняемые скрипты для генерации конфига.

**Comment by elcreator** [comment]
Для чистоты эксперимента поставил совпадающую версию виртуалбокса отсюда http://download.virtualbox.org/virtualbox/4.3.10/ . в гите никаких изменений. Вот логи:
http://pastebin.com/raw.php?i=g1knCAi5

**Comment by bvv4ik** [comment]
конечно, тогда нужно пофиксить както

**Comment by elcreator** [comment]
Может, кто-то с уже настроенным окружением возьмется пофиксить ansible скрипт из альтернативной конфигурации, чтобы он поднимал все возможные окружения, будучи запущенным прямо из гостевой машины и управляя ею же через локальный коннект.
Идея в том, чтобы полностью отвязаться от хостовой ОС и связанных с ней багами (права на файлы, переносы строк, глюки монтирования файловых систем etc). Если скрипт успешно поднимется на конкретном дистрибутиве - он будет поднимется на этом дистрибутиве у всех. Конечно, можно было бы и просто кому-то образ настроенной виртуалки раздавать, но инсталлятор безопаснее, т.к. просмотреть его текст на наличие руткитов реально, в отличие от целого образа.

**Comment by AndriyBrez** [comment]
Проблема ще й досі не вирішена, можливо хтось поділиться хоча б тимчасовим рішенням?

**Comment by versus** [comment]
vagrant plugin install vagrant-vbguest (on windows host ) fixed the issue for me, thanks

**Comment by versus** [comment]
открываем  консоль, переходим в папку проекта и вводим следующие комманды

vagrant destroy
vagrant plugin install vagrant-vbguest
vagrant up

**Comment by ostap7** [comment]
Так же хочу заметить, что есть проблема и под Ubuntu'ой при сборке vagrant'ом.
Не правильна версия(такой нет на сервере) - Tomcat'a, не правильные разрешения для папок.
Что говорить, когда под Windows конфигурация для VirtualBox'a даже не прописана(TODO:).

Я с этим уж повозился недельку(время от времени) так что берусь это пофиксить.

**Comment by ostap7** [comment]
Беру эту таску в работу- ставлю лейб Active(это же для этого здесь этот лейб?) )

**Comment by bvv4ik** [comment]
проблема, я так понимаю - уже не актуальна?
