### ISSUE TITLE
Оптимизировать всю структуру контекстов стринга, и полностью уюрат ьго дублирование и повторное фигурирование пропертей во всех проектах бэка явы

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#499]

**Comment by bvv4ik** [comment]
Для теста:
убедиться, что все корневые контексты без копипаста находятся в едином месте, с пропертями:
https://github.com/e-government-ua/i/tree/test/wf-base/src/main/resources
а в остальных проектах только наследники и уже без пропертей:
https://github.com/e-government-ua/i/tree/test/wf-central/src/main/resources
https://github.com/e-government-ua/i/tree/test/wf-region/src/main/resources

**Comment by AlisaProskura** [comment]
Подскажите:  
1)  "все корневые контексты" - это имеются ввиду все, что находятся по ссылкам в комменте выше  или есть "все" какие-то еще?
2) для тестирования  достаточно, чтобы  расположение и наличие файлов по указанным  ссылкам  визуально  соответствовало тому, что написано в комменте "Для теста"? или необходимо смотреть что-то еще?

**Comment by AlisaProskura** [comment]
Еще смущают пароли есть в свойствах.
Например тут:
https://github.com/e-government-ua/i/blob/master/wf-base/src/main/resources/storage-mongodb.properties
mongodb.login=sitesc
mongodb.password=ZZX6YDC1ZDUPp3nOY
mongodb.host=redis.igov.org.ua

Тут:
https://github.com/e-government-ua/i/blob/master/wf-base/src/main/resources/AS.properties

Оно, может, не используется или ещё что... но это странно, когда вот так пароли в открытом доступе в гите.

**Comment by bvv4ik** [comment]
1. да, те что по первой ссылке
2.да, для теста, т.к. он потом и в продакшин попадет

по "открытым паролям" - все норм, это пароли тестовых серверов, они могут быть открыты для всех... т.к. без открытых тестов вообще мало что можно тестировать и разрабатывать

**Comment by AlisaProskura** [comment]
Хорошо. Спасибо.
