### ISSUE TITLE
Унифицировать работу с liquibase, для пролной взаимной совместимости работы на тестовых и боевой средой, чтоб сделать данные на боевом - живыми!

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#500]

**Comment by bvv4ik** [comment]
Для теста:
убедиться в расположении новых структур ликвибейса:
https://github.com/e-government-ua/i/tree/test/wf-base/src/main/resources/liquibase
https://github.com/e-government-ua/i/tree/test/wf-central/src/main/resources/liquibase
и авто-загружаемых данных:
https://github.com/e-government-ua/i/tree/test/wf-base/src/main/resources/data
https://github.com/e-government-ua/i/tree/test/wf-central/src/main/resources/data
и то чно при этом альфа и бета тестовые + пробакшин - работают

**Comment by VadimGulich** [comment]
Работает
