### ISSUE TITLE
Создать на бэке wf-base методы сохранения сгенерированного одноразового ключа и его считывания

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#501]
методы (внутренние, а не сервисы):
- [x] setAccessData(String sData) - сохраняет данные, и получает ключ ответ
- [x] getAccessData(String sKey) - загружает данные по ключу
- [x] removeAccessData(String sKey) - удаляет данные по ключу

-Для этого использовать существующий у нас модуль storage-static (key-value хранилище)
-примеры его использования можно найти в сервисе getDocumentFile и setDocumentFile
-Сохранять лучше в простом виде а не через GridFS

**Comment by admiral-diver** [comment]
Добрый день. Ольга, сделайте пожалуйста интерфес в проекте wf-base без реализации и напишите его название в этом чате. Необходимо для параллельной реализации связанной задачи.

**Comment by OlgaTurenko** [comment]
Добрый день! org.wf.dp.dniprorada.base.dao.AccessDataDao

Там уже с реализацией (только еще докрутить метод getAccessData нужно немного, чтоб правильно байты в строку сконвертились)

**Comment by bvv4ik** [comment]
Для теста:
Подтвержденность корректной реализации будет выполненность производной задачи:
https://github.com/e-government-ua/i/issues/502
(и ее протестированность)

или, если Ольга придумает другой метод проверки)

**Comment by VadimGulich** [comment]
Производная задаче реализована , согласно этому задачу закрываю
