### ISSUE TITLE
В существующей системе basic-авторизации (через фильтр, спринг и сверкой логина/пароля с Активити) - доработать альтернативный механизм по одноразовому коду

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#502]
смотреть в запросе параметр sAccessKey и nID_Subject и:
- [x] 1) если они есть, то проверять авторизацию по альтернативному алгоритму.
(в процессе будут использованы методы, написанные по задаче: 
https://github.com/e-government-ua/i/issues/501)
- [x] 1.1) через метод getAccessData - загрузить данные по ключу (sAccessKey)
- [x] 1.2) содержимое должно равняться значению nID_Subject
- [x] 1.3) если getAccessData ничего не вернул  то выводить ошибку "Error custom authorization - key is absant" 
- [x] 1.4) если getAccessData вернул значение, не совпадающее с nID_Subject", то выводить ошибку "Error custom authorization - key data is wrong" 
- [x] 1.5) если п.1.2 прошел успешно, то отрабатывать removeAccessData по ключу sAccessKey
и отрабатывать авторизацию успешно
- [x] 2) если их нет, то проверять авторизацию как обычно

П.С.: если методы по задаче 501 еще не будут готовы, то временно замокать вход по праметрам:
sAccessKey=1 и nID_Subject=1

**Comment by tasman26104** [comment]
пункт 1.3 "если getAccessData ничего не вернул то выводить ошибку "Error custom authorization - key is absant"" никогда не сработает, из-за того, что DAO всегда возвращает непустой результат. В таком случае будет ошибка "Error custom authorization - key data is wrong"

**Comment by tasman26104** [comment]
Также реализована возможность использования тестовых данных для входа: для этого в файле AS.properties нужно указать свойства general.auth.custom.accessKey и general.auth.custom.subjectId (по умолчанию равны 123 и 122 соотвественно)

**Comment by bvv4ik** [comment]
так на полигоне берется конфиг с сервера, разработчики не могут его править... а тестировщики могут тестировать только на этом общем полигоне.

Потому, единственный вариант - это по создавать несколько одноразовых ключей. и в комментариях, для тестировщика предоставить эти ссылки.

(в идеале, просто создать сервис, который сможет генерить эти ключи, и который будет доступен только на тестовом... т.е. том, в котором в GeteralConfig.bTest = true... в коде есть примеры использования этого параметра(этот клас обязательно должен автовайриться, ятоб подтянулис проперти))

**Comment by tasman26104** [comment]
Для тестирования задачи нужно отправить запрос на контекстный путь Rest-АПИ, например: 
https://test.region.igov.org.ua/wf-region/service/repository/process-definitions?sAccessKey=fa886405-790c-4ea2-bd29-5b45866cb5a5&nID_Subject=MTIzNDU2

Можно использовать следующие данные (все ключи одноразовые!): 
nID_Subject:
MTIzNDU2

sAccessKey:
ef28c5d3-e11c-4bfc-b107-1ad383a99b54
933cfbae-8afb-4545-b8a7-c642777588f5
e313f5dd-2a8d-4df4-b274-167a441f0ee6
e26fb80a-2920-44ff-bdff-7b5df1ddb9bf
a202d92a-bfd3-43b8-b8fe-f2c1af1d6b96
4877b258-183f-41f9-915e-3c8896470e46
68c040ea-c76c-4f9a-9e7f-6bb7dac53916
d2d87db1-fab2-4c19-8ec2-6b51c855200d
f1304d79-a201-48c7-aa41-2e000fcd7385
f1304d79-a201-48c7-aa41-2e000fcd7385
9c3e22e5-4158-4b15-8705-e2f87287e65f
a4bd4bee-6f19-49fc-b333-b9e85ac9ace5
a365e52a-3277-4020-88d5-59a9c229ca6b
6bd0d452-e887-4b73-8841-f0791f1a4989
476fa27f-2fb8-4760-a1a5-17ce51e7b66e
b7185b91-17e6-471b-8667-d68c56208792
ceee24b2-24b1-47e4-ae99-7de043c93338
74e20338-3629-4d0a-bd32-1f42178133ee
7e5cdcf7-1413-4a1d-9c9b-12d4efa31a2f
c6f81707-ab25-4296-af99-25d8b5a89e5e

**Comment by VadimGulich** [comment]
Согласно описанию для тестированию задача проверена , все работает корректно
