### ISSUE TITLE
Доработать классы MailTaskWithAttachment и MailTaskWithAttachments, чтоб найденные в теле тэги [sAccessKey] и [nID_Subject] - заменялись данными

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#503]
1) [nID_Subject] заменять на значение поля nID_Subject
2) [sAccessKey] заменять на значение, полученное поолученного по методу setAccessData, с передачей туда значения nID_Subject
3) [sURL_ServiceMessage] заменять на значение "https://test.igov.org.ua/wf-central/service/messages/setMessage"

Вынести логику этой замены в отдельный класс, отдельный метод, чтоб не дублировать код в обоих классах

П.С.: Метод реализовывается по задаче: https://github.com/e-government-ua/i/issues/501

**Comment by bvv4ik** [comment]
плиз, прошу сориентировать по планируемой дате реализации

**Comment by bvv4ik** [comment]
Для теста:
отработать услугу(БП), который создает Павел Курбацкий
если он подтвердит, что письмо пришло корректное, с корректной и отсылаемой формой, то все ок

**Comment by VadimGulich** [comment]
MailTaskWithAttachment и MailTaskWithAttachments  уже тестировались в рамках других задач, считаем протестированным
