### ISSUE TITLE
На главном портале, при авто-заполнении формы, если встречается поле с id=nID_Subject, то заполнять его текущим значением этой переменной (полученной при авторизации)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#504]
Такое поле, для примера, добавлено в БП "dnepr_mvd-1.bpmn"
(Справка о несудимости, Днепропетровск)

Для теста: заполнив эту форму на главном портале, открыв дашборд, найдя эту заявку - посмотреть в фаербаге какое значение этого поля пришло.

**Comment by bvv4ik** [comment]
Для теста:
в фаербаге убедиться что поле nID_Subject таки заполненное отсылается после сабмита

**Comment by AleksejDomash** [comment]
Поправлю: 
Это нельзя протестировать через фаербаг. Так как значение для поля nID_Sibject устанавливается на nodejs, а не на клиенте. Возможнный способ: включить логирование запросов в nodejs и поверить в логе запрос, которій идет на java бєк

**Comment by bvv4ik** [comment]
так оно устанавливается уже на сабмите или при загрузке формы?

**Comment by AleksejDomash** [comment]
браузер отправляет пост запрос на nodejs, nodejs добавляет nID_Subject и дальше отправляет на java-back

**Comment by RoOmel** [comment]
Если нужен паблик кей, добавьте, плиз, чтобы можно было зайти по sftp на NodeJS
---- BEGIN SSH2 PUBLIC KEY ----
Comment: "rsa-key-20150814"
AAAAB3NzaC1yc2EAAAABJQAAAQEAh+sJQSKfVaKDknCJDdPSnFZxQyGSq2B8kXuZ
GNgyBeMbJr0fQTlLedlKSf4NEfhNjQyqGG6VTGVjq0AO8CdSwftVltWShHSIXq2v
aiartN4DZy6JE9nU9d106LjdoK7FVbDnQVKaHXX+zbdkUDcYXai0eR5DwDvcmnj/
ruqVrvlafhjnQkmJ19u0fGB+/GaWOS0mYHDJyia+xg+ghmInLUQ9MMI9EbPd3R++
yuw0nh3/yr60onf4sCa93C3MhtNfM0OHgsa5J+TMgtLZgpzqSRwWj5VMvoBW4ZI2
iOQLsl1IXJtLVy1dzxz2Mj0yA+Abj3vBWKPFtCkyoc5xYyyDTQ==
---- END SSH2 PUBLIC KEY ----

**Comment by RoOmel** [comment]
Логи на FTP (по Tomcat и NodeJS) - на какой сервер нужно заходить?
Тест-альфа-централ: test.igov.org.ua 
Тест-альфа-регион: test.region.igov.org.ua 
Тест-бета централ и регион: dniprorada.igov.org.ua

**Comment by bvv4ik** [comment]
Тест-альфа-регион: test.region.igov.org.ua

**Comment by VadimGulich** [comment]
Древняя задача , закрываем )
