### ISSUE TITLE
На главном портале создаем новый пункт в меню "Статус заявок" и оживляем его

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#505]
- [x] 0) Добавить в главное меню новый пункт "Заявки" (название нового модуля "order")
- [x] 1) Текст под заголовком:
"На цій сторінці Ви можете переглянути статус по своїй заявці за її номером."
- [x] 2) Элементы(ниже):
Номер заявки: [Поле ввода]
[Переглянути] (кнопка)
- [x] 3) После нажатия на “Переглянути” под полем показываем:
- [x] 3.1) Тип заявки: %тип% (Тип захардкодить "Услуга")
- [x] 3.2) таблица с двумя колонками "Час" и "Статус", и одной строчкой, где в ячейках разместить полученные с сервиса данные.
- [x] 4) искать через сервис getHistoryEvent_Service,
куда передается параметром "sID" - значение из "поля ввода"
Сервис реализован по задаче: https://github.com/e-government-ua/i/issues/493

**Comment by AVATOR** [comment]
для тестирования вводите данные:
код: 11 и должен показатся табличка с статусом "новая заявка"
код: 22 и должен показатся табличка с статусом "заявка в обработке"
код: 21 и должен показатся сообщение "Неверный номер!"
дата в таблице покачто выводится текщяя (как будет реализованно на backend то будет исправленно).

**Comment by OlgaKotova** [comment]
@bvv4ik @AVATOR Все отработало, НО, скажите, это нормально, что тексты "новая заявка" и "заявка в обработке" выводятся на рус. языке?

**Comment by AVATOR** [comment]
мне в json приходит из backend-а этот текс и я его и вывожу.
@bvv4ik если нужно переводить сообщения то я могу подправить задачу?

**Comment by bvv4ik** [comment]
переводить сообщение не надо...
текст действительно в базе... и это тестовый текст. когда будут заливать реальные заявки  - текст будет нормальный

**Comment by OlgaKotova** [comment]
@AVATOR @bvv4ik закрываю

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/9001620/67d9219a-3762-11e5-81d7-e20143a18789.png)


Все работает , дата не так критично , но желательно будет исправить )
