### ISSUE TITLE
На главном портале заменить хардкод test.region.igov.org.ua на тот сервер, который прописан в подуслуге (aServiceData)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#506]
найти этот участок можно простым поиском в проекте фразы "test.region.igov.org.ua"

**Comment by bvv4ik** [comment]
Для теста:
можно будет убедиться. после проливки этого кода на бету, что на бэте и на альфе разное число свободных слотов.. при. например, оформлении услуги по МРЕО (Киев)

**Comment by OlgaKotova** [comment]
@bvv4ik Кол-во слотов и некоторые их имена отличаются. Проверьте на скринах, если все верно, закрывайте. 
Альфа http://screencast.com/t/TWmwxDLSZTl и бета http://screencast.com/t/uDP5amTrizEa (нужные поля я выделила стрелками)
