### ISSUE TITLE
Дропдаун области становится неактивен при выборе

### ISSUE THREAD

**Issue by asyasmi** [e-government-ua/i#509]
При выборе области из выпадающего списка сменить ее становится невозможно. 
https://igov.org.ua/service/1/general/city

Два walkaournd: 
1. Обновить страницу. 
2. Выбрать Город и нажать на сброс. 

Абсолютно неюзабельно для пользователя.

**Comment by bvv4ik** [comment]
дубль
таска уже давно создана и на полигоне решена

**Comment by bvv4ik** [comment]
https://github.com/e-government-ua/i/issues/423
