### ISSUE TITLE
Написать автоматизированные тесты по одной основным функциям бэка

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#51]
на junit
1) получение списка процессов последней верссии
2) получение данных процесса с ИД

**Comment by admiral-diver** [comment]
Там есть уже тесты на фасад, написанные на spring-test (без тестирования интеграции с БД). Они обеспечивают сугубо целосность Custom REST API. Нужно что-то большее? Если да, прошу расписать.

**Comment by bvv4ik** [comment]
т.е. они уже включают, как минимум, оба этих метода?

**Comment by admiral-diver** [comment]
На текущий момент вместе с доработкой Custom API были написаны три теста:
1. На запуск процесса
2. Получение информации по задаче
3. Получение списка процессов

Суть тесто заключается в том, что они эмулируют обращение по HTTP (GET/POST) на REST контроллер. При этом они лишь гарантируют тот факт, что при изменении API - они упадут. Т.е. максимум от чего они спасут, так это от:
1. Добавление/удаление/переименование нового параметра в JSON ответе/запросе
2. Изменение контекста обращения
3. Изменение типа запроса POST/GET
4. Изменение статус кодов (200, 400, ...)

При изменении любого условия из перечисленных пунктов - тесты упадут. Если этого достаточно, то задачу можем закрыть.

**Comment by bvv4ik** [comment]
Супер!
Спасибо!
Закрываю!
