### ISSUE TITLE
В разделе Мои документы можно получить документ другого пользователя

### ISSUE THREAD

**Issue by artem-erofeev** [e-government-ua/i#510]
Только что загрузил для просмотра паспортные данные. Получил свои и чужие.

**Comment by artem-erofeev** [comment]
.tif файл с 4 страницами

**Comment by bvv4ik** [comment]
если такое и есть, то это может быть только из-за путанницы только на этапе сохранения данных в базу БанкИД... тут нужно поправить данные в базе.
1) сообщите пожалуйста Ваш:телефон и желательно ИНН
2) можете плиз выслать этот файл на почту bvv4ik@gmail.com

**Comment by artem-erofeev** [comment]
отправил вам на почту телефон и инн

8 июля 2015 г., 11:19 пользователь bvv4ik <notifications@github.com>
написал:

**Comment by artem-erofeev** [comment]
По хорошему следует проверить все документы. Можно программно прогнать всю базу tif-ов и посчитать в них кол-во страниц. Если больше двух, то там что-то подозрительное.

**Comment by SergeyZhukDP** [comment]
Привет. Артем дело в том, что по вашим указанным ИНН и мобильному тянет данные из банка женского пола. Это правильно ? Да, в сканах есть и вы и не вы. Вопрос, это ваш мобильный и ИНН ?

**Comment by bvv4ik** [comment]
та у меня две страницы, и там все норм..
проблемма не на стороне iGov, а на стороне "первоисточника", если вообще эта проблема касается хоть сколь-либо значительного числа людей... возможно, просто "недосмотр" сотрудника, которые заносил сканы в базу...

**Comment by SergeyZhukDP** [comment]
нет, проблема серьезная, Артем откуда увас этот мобильный и ИНН ?!

**Comment by bvv4ik** [comment]
я-б задал вопрос, тогда, по другому:
"куда спрятали труп"?)

**Comment by artem-erofeev** [comment]
Не переживайте, это данные девушки. Я свой паспорт загрузил для просмотра и
ей стало интересно. Загрузили ее - а там..)

**Comment by artem-erofeev** [comment]
На мой взгляд, если это недосмотр сотрудника, который вносил данные в базу, то следует провести проверку всей базы. Сервис растет, количество пользователей тоже. Если есть вероятность возникновения таких артефактов, их нужно устранить на данном этапе, пока это не вылилось в юридическую проблему.

**Comment by SergeyZhukDP** [comment]
Ясно, ну вашу проблему то вылечим, ну а как пример вопрос конечно подымим в нужносм русле. Спасибо !

**Comment by bvv4ik** [comment]
дальше, предлягаю уже через "прямые контакты"
