### ISSUE TITLE
На бэке централа доработать сущность Merchant и добавить один метод сервиса

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#511]
- [ ] 1) Добавить поля
sPrivateKey - строковое, приватный ключ, длиной <100 символов (not null)
nID_SubjectOrgan - числовое-ИД субъекта-организации //опциональное
sURL_CallbackStatusNew - УРЛ, на который будет обращение, после изменения статуса платежа, String, <500 символов //опциональное
sURL_CallbackPaySuccess - УРЛ, на который будет обращение, после успешного платежа, String, <500 символов //опциональное

- [ ] 2) Добавить метод сервиса getMerchant(sID), по которому находить(по полю id) и отдавать объект -JSON с полями по мерчанту.
Образец отдаваемого объекта:
{
"sID":"i68670213143" //строковой ИД мерчанта (паблик-кей) (текущее - id)
,"nID_SubjectOrgan":3432 //числовое-ИД (НОВОЕ)
,"sPrivateKey":"8Hde98909de3" //строковой ключ (НОВОЕ)
,"sID_SubjectOrgan_Owner":"" //Строковой-ИД субїекта-организации(ОКПО) (текущее - idOwner)
,"sOwnerName":"Приватбанк" //Строковое название субьекта-организации (текущее - ownerName)
,"sURL_CallbackStatusNew":"" //строковое, УРЛ (НОВОЕ)
,"sURL_CallbackPaySuccess":"" //строковое, УРЛ (НОВОЕ)
}

- [ ] 3) Добавить в метод сервиса setMerchant соответствующие новые поля из п 1.

- [ ] 4) Поправить нашу документацию АПИ

ОПЦИОНАЛЬНО: Прикрутить к сущности liqubase и поправить сущность в соответствии с устоявшимся стандартом

П.С.: Необходимо для реализации задачи: https://github.com/e-government-ua/i/issues/475

**Comment by bvv4ik** [comment]
для тестирования есть описания в нашей вики по АПИ

**Comment by bvv4ik** [comment]
консолидированная таска сделана:
https://github.com/e-government-ua/i/issues/519

**Comment by RoOmel** [comment]
Всё реализовано согласно ТЗ.
Протестировано, отчёт в консолидированной таске https://github.com/e-government-ua/i/issues/519
