### ISSUE TITLE
Создать сущность Country и сервисы к ней

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#515]
Примеры источников данных:
http://www.profiwins.com.ua/uk/letters-and-orders/gks/4405-426.html
https://uk.wikipedia.org/wiki/ISO_3166-1

1) Сущность Country
nID - ИД-номер Код внутренний (уникальный-ключ, автоитерируемый, long)
nID_UA - ИД-номер Код, в Украинском классификкаторе (уникальный-ключ, long)
sID_Two - ИД-строка Код-двухсимвольный, международный (уникальный-ключ, String 2 символа)
sID_Three - ИД-строка Код-трехсимвольный, международный (уникальный-ключ, String 3 символа)
sNameShort_UA - Назва країни, коротка, Украинская (уникальный, String < 100 символов)
sNameShort_EN - Назва країни, коротка, англійською мовою (уникальный, String < 100 символов)
sReference_LocalISO - Ссылка на локальный ISO-стандарт, с названием  (a-teg с href) (String < 100 символов)
Пример объкта сущности:
{
nID,3
, "nID_UA":123
, "sID_Two":"AU"
, "sID_Three":"AUS"
, "sNameShort":"Австралія"
, "sNameShort_EN":"Australy"
, "sReference_LocalISO":"<a href=\"https://uk.wikipedia.org/wiki/ISO_3166-2:AU\">ISO_3166-2:AU</a>"
}

2) сервисы:
2.1) getCountryes - отдает массив объектов сущности, подпадающих под критерии
параметры:
nID_UA //опциональный
sID_Two //опциональный
sID_Three //опциональный
sNameShort_UA //опциональный
sNameShort_EN //опциональный
2.2) setCountry - апдейтит элемент(если задан один из уникальных-ключей) или вставляет (если не задан nID), и отдает экземпляр нового объекта
параметры:
nID //опциональный, если другой уникальный-ключ задан и по нему найдена запись
nID_UA //опциональный, если другой уникальный-ключ задан и по нему найдена запись
sID_Two //опциональный, если другой уникальный-ключ задан и по нему найдена запись
sID_Three //опциональный, если другой уникальный-ключ nID задан и по нему найдена запись
sNameShort_UA //опциональный, если nID задан и по нему найдена запись
sNameShort_EN //опциональный, если nID задан и по нему найдена запись
sReference_LocalISO //опциональный
2.3) removeCountry - удаляет элемент(по ОБЯЗАТЕЛЬНО заданому одому из уникальных-ключей)
параметры:
nID //опциональный, если другой уникальный-ключ задан и по нему найдена запись
nID_UA //опциональный, если другой уникальный-ключ задан и по нему найдена запись
sID_Two //опциональный, если другой уникальный-ключ задан и по нему найдена запись
sID_Three //опциональный, если другой уникальный-ключ задан и по нему найдена запись

3) Наполнить данными csv

4) Добавить документацию

**Comment by bvv4ik** [comment]
.

**Comment by LamronNu** [comment]
для теста: 
созданные сервисы
 1) getCountries() -- возвращает весь список стран (залит справочник согласно двум ссылкам выше)
ссылка: https://test.igov.org.ua/wf-central/service/services/getCountries
 2) getCountry() -- возвращает объект Страны по первому из 4х ключей (nID, nID_UA, sID_Two, sID_Three). Если нет ни одного параметра -- ошибка 403.
ссылка: по аналогии с п.1, только поменять имя метода и добавить параметры.
3) setCountry() -- согласно тз, апдейтит элемент (если задан один из уникальных ключей) или вставляет (если не задан nID), и отдает экземпляр нового объекта
4) removeCountry() -- удаляет обьект по одному из четырех ключей (nID, nID_UA, sID_Two, sID_Three) или кидает ошибку 403 "запись не найдена".

написан юнит-тест, который тестирует разные кейсы. кроме тривиальных, учтены еще такие:
в п.2 -- если задано два ключа от разных записей -- вернется та, ключ который "первее" в таком порядке: nID, nID_UA, sID_Two, sID_Three.
в п.3 -- если задано все параметры (без nID) и их еще не было в базе -- то создается новая запись, если кинуть другой запрос, в котором все параметры другие, кроме "первого" (nID_UA) -- то запись *обновится", иначе (все "другое", кроме одного из следующих после nID_UA ключей) -- кинет ошибку 403.

и там, и там -- поведение согласно тз.

если будут обнаружены другие кейсы, которые "не вписываются" в описание задачи -- прошу в студию) но вроде учтены все варианты.

документация -- в процессе. поэтому выше написано вкратце + описание задачи (кроме первого пункта getCountries, который без параметров и возвращает всё)

**Comment by LamronNu** [comment]
документация: https://github.com/e-government-ua/i/blob/test/docs/specification.md#21

**Comment by RoOmel** [comment]
созданные сервисы:
1) getCountries - протестировано, реализовано согласно ТЗ;
2) getCountry - протестировано, реализовано согласно ТЗ;
3) setCountry - STATUS 405 Method Not Allowed
4) removeCountry проверю после п.3

**Comment by bvv4ik** [comment]
"3) setCountry - STATUS 405 Method Not Allowed"
так метод, видать другой должен быть... постмэном можно любой метод подставить

**Comment by RoOmel** [comment]
Неудачная шутка.
Из условия ТЗ:
3) setCountry - апдейтит элемент (если задан один из уникальных ключей) или вставляет (если не задан nID), и отдает экземпляр нового объекта
в п.3 -- если задано все параметры (без nID) и их еще не было в базе -- то создается новая запись, если кинуть другой запрос, в котором все параметры другие, кроме "первого" (nID_UA) -- то запись *обновится", иначе (все "другое", кроме одного из следующих после nID_UA ключей) -- кинет ошибку 403.
![postman_01](https://cloud.githubusercontent.com/assets/12996514/8844032/0a547a32-3119-11e5-8393-200dc0c30070.jpg)
Ещё будут комменты?

**Comment by LamronNu** [comment]
setCountry -- тоже GET-метод, не POST

**Comment by RoOmel** [comment]
Тоже самое

**Comment by RoOmel** [comment]
LamronNu - прикрепи сюда скрин, плиз, своего запроса.
Может какие-то права нужно для добавления новой записи?

**Comment by LamronNu** [comment]
![image](https://cloud.githubusercontent.com/assets/8156670/8850286/8b6f7f6e-314f-11e5-9f93-762b5d10c844.png)
вот сам запрос:
https://test.igov.org.ua/wf-central/service/services/setCountry?nID_UA=123&sID_Two=AU&sID_Three=AUS&sNameShort_UA=%D0%90%D0%B2%D1%81%D1%82%D1%80%D0%B0%D0%BB%D1%96%D1%8F&sNameShort_EN=Australy&sReference_LocalISO=ISO_3166-2:AU

прав вроде не нужно никаких.. главное, не "попасться" на уже существующие ключи.. 
при тесте у меня использовались ключи вроде таких: "-" или "--", чтоб после создания страны про нее забыть:)

кстати, о странах) при объединении двух ссылок была упущена одна страна, Сарк (код 680, англ. Sark) -- из-за недостатка информации о ней: не найдены двух и/или трехзначный код, точно уже не помню; в Википедии (списке, вторая ссылка) ее нету, есть англоязычная страничка (по стране), но там неполная инфа для этого справочника..

поскольку это малоизвестная страна и её использование в нашем проекте маловероятно, то она была упущена в справочнике.. но если есть желание -- можете покопаться:) "для теста")

или берите тестовые значения, как уже описано выше..

**Comment by RoOmel** [comment]
Из условия ТЗ:
3) setCountry - "... или вставляет (если НЕ ЗАДАН nID), и отдает экземпляр нового объекта"
В моём запросе параметр nID отсутствует.
Так его надо указывать или нет?
, т.к. тут получается баг спека

**Comment by LamronNu** [comment]
попробую объяснить: 
 - если нИД задан -- то это апдейт. ищется запись по нИД, если нету -- ошибка "не найдено" .
 - если нИД не задан, то может быть или апдейт (если задан и найден ключ, например, сИД_юа, т.е. по этому ключу), или инсерт (если заданы все ключи и они уникальны, т.е. таких еще нету в справочнике).

т.е. сам метод сначала ищет по одному из ключей обьект, если находит -- обновляет, если не находит -- вставляет.

по идее, можно для сетКантри кидать запрос, где только два параметра. один -- ключ (из  nID, nID_UA, sID_Two, sID_Three), второй -- поле, которое требуется изменить.

честно говоря, не вижу ситуаций, когда такое потребуется... справочник вроде "статический".. разве что при изменении названий/составов каких-то государств..

**Comment by RoOmel** [comment]
Согласен, может и не потребуется, но в таске для тестирования пункт такой есть - вот и "копаю" чтобы проверить.

**Comment by RoOmel** [comment]
3. setCountry
Тест прошёл
{
    "nID_UA": 999,
    "sID_Two": "XX",
    "sID_Three": "XXX",
    "sNameShort_UA": "КинДзаДза",
    "sNameShort_EN": "KinDzaDza",
    "sReference_LocalISO": "ISO_3166-2:XX",
    "nID": 21008
}

4) removeCountry
Тест прошёл - созданная запись удалена
