### ISSUE TITLE
справочник областей и городов

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/i#516]
для реализации общеукраинских услуг на портале (на первом этапе такими услугами будут услуги, предоставляемые через укрпочту) необходима реализация нового элемента, подгружающего на форму на портале список областей областей и список городов

**Comment by bvv4ik** [comment]
зачем?
у нас уже есть выбор области/города, когда гражданин заходит в услугу.
и делается это по справочнику!
вопрос только в том, чтоб эту информацию передавать в поле БП

**Comment by bvv4ik** [comment]
тук-тук!

**Comment by dmitrijzabrudskij** [comment]
это нужно для услуг укрпочты - они не будут привязаны к какому-то
конкретному городу. плюс Паша про свой бп говорил  - ему тоже нужна такая
доработка (добавил в копию)

2015-07-21 3:31 GMT+03:00 bvv4ik <notifications@github.com>:

> тук-тук!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/i/issues/516#issuecomment-123108654>.
>



-- 
С уважением, Забрудский Д.А.
Ведущий специалист по web-разработке
dmitrij.zabrudskij@privatbank.ua
skype: dn200986zda
+380979362996

**Comment by bvv4ik** [comment]
та не нужно это, т.к. у нас на обрастях и городах завязана вся структура... и выбор их должен происходить до захода в форму услуги а не после. На форме, максимум, это может быть прикручивание отделений, например Укрпочты, которые опять-же будут подтягиваться(фильтроваться) по выбранному месту... 
Этот подход уже реализован для МВД, по справке о несудимости и уже находится в стадии начала тестирования...

если есть каталог отделений Укрпочты, то нужно его предоставить ,вместе с ИД-шниками классификатора общеукраинского (КОАТУУ) возле каждого отделения... так-же будет возможность у самой Укрпочты через наши АПИ обновлять этот список(как и у МВД)

если тут есть общее понимание - прошу переименовать таску в "Занести в базу указанный каталог отделений для Укрпочты"(с обязательными колами КОАТУУ)

**Comment by bvv4ik** [comment]
не актуально
