### ISSUE TITLE
На бэке wf-base создать сервис сохранения в файле указанных полей тасок активити за определенный период (с реализакией примера для Налоговой, по БП субсидии)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#517]
Пример реализации подобной задачи(только для истории) тут:
https://github.com/e-government-ua/i/issues/313
т.е. можно взять за основу(скопировать) сервис "download_bp_timing", только выбирать данные не из истории а из текущих юзертасок(еще не отработанных). И загружая каждую из них(обьект с полями) - перебирать эти поля(по их id) и при нахождении нужных - выбирать их значения для подстановке в соответствующие колонки.

- [x] 1. Создать сервис
Каждая строка в результирующем файле - отдельная задача
- [x] 1.1) Название сервиса: "downloadTasksData", куда передавать параметры:
- sID_BP - id бизнеспроцесса
- sID_State_BP - id состояния бизнеспроцесса (usertask)
- sDateAt - дата начала выборки тасок //опционально, умолчательно начало "сегодня" (формат: YYYY-MM-DD)
- sDateTo - дата конца выборки тасок //опционально, умолчательно начало "завтра" (формат: YYYY-MM-DD)
- nASCI_Spliter - номер-код символа-разделителя //опциональный, умолчательно ";"
- saFields - id-полей, переданные через "символ-разделитель"
(например: saFields=${nID_Task};${bankIdPassport};${bankIdlastName} ${bankIdfirstName} ${bankIdmiddleName};1;${sDateCreate})
- sID_Codepage - ИД-строка кодовой страницы //опциональный, умолчательно "win1251"
- sDateCreateFormat - формат даты создания //опциональный, умолчательный: "yyyy-mm-dd HH:mm:ss"
- sFileName - название файла //опциональный, умолчательный: "data_BP-ZZZZ_YYYY-MM-DD_hh-mm-ss.txt" (где "ZZZZ" - id-бизнеспроцесса, например: "dnepr_spravka_o_doxodax")
- [x] 1.2) Зарезервированные id полей (значения которых берутся на основании общих для Activiti данных о процессе/таске):
- nID_Task - "id таски"
- sDateCreate - "дата создания таски" (в формате sDateCreateFormat)
- [x] 1.3) Особенности обработки полей:
Если тип поля enum, то брать не его ИД пункта в энуме а именно значение
Если тип поля enum, и в значении присутствует знак ";", то брать только то ту часть текста, которая находится справа от этого знака
- [ ] 1.4) задокументировать сервис на Вики (можно сделать в последнюю очередь)

- [x] 2) Проверить на конкретной задаче БП Налоговой (субсидии), по БП "dnepr_spravka_o_doxodax":
- [x] 2.1) Задать "умолчания":
- Кодировка (sID_Codepage): win1251 (CL8MSWIN1251)
- Разделитель полей saFields (nASCI_Spliter):18
- Формат даты (sDateCreateFormat): "dd.mm.yyyy hh24:mi:ss"
- [x] 2.2) Задать поля:
- 1. номер заявки у нас в админке ("id таски", зарезервированное поле: "nID_Task")
- 2. дата/время поступления заявки нам ("дата создания таски", зарезервированное поле: "sDateCreate")
- 3. код инспекции, куда отправлять заявление (area)
- 4. ИНН гражданина (пустое "")
- 5. серия и номер паспорта (пустое "")
- 6. идентификатор запроса (всегда 0 - только паспорт)
- 7. ФИО гражданина (bankIdlastName bankIdfirstName bankIdmiddleName)
- 8. Цель получения справки (по умолчанию 4)
- 9. Для кого/чего выдается справка (поле aim)
- 10. Период с (date_start)
- 11. Период по (date_stop)
- 12. Место жительства (place_living)
- 13. Паспортные данные (bankIdPassport)
- 14. Статус запроса (всегда 1)
- 15. Телефон (phone) 
- 16. Почта (email)
(https://docs.google.com/document/d/1C5uy7enJN95RfHbow8bBEfK5FcbIab305_eT9OLLUKo/edit)
- [x] 2.3) Сопоставить результат в этим примером строк-записей в файле (должно получиться так в выдаваемом файле):
2809702.02.2015 09:54:154031234567890А?1234561?ВАНОВ ?ВАН ?ВАНОВИЧ4ПРЕД'ЯВЛЕННЯ ЗА М?СЦЕМ ВИМОГИ01.01.201431.12.2014М.ДН?ПРОПЕТРОВСЬК, ВУЛ.ДЗЕРЖИНСЬКОГО, БУД.1-АЖОВТНЕВИМ РВУМВС1099-09-09-099example@mail.ru

**Comment by JTaky** [comment]
Код в ветке test.
Документация сервиса: https://github.com/e-government-ua/i/blob/test/docs/specification.md#22

Пример вызова сервиса: https://test.region.igov.org.ua/wf-region/service/rest/file/downloadTasksData?sID_BP=kiev_mreo_1&sDateAt=2015-06-28&sDateTo=2015-08-01&nASCI_Spliter=59&sID_Codepage=UTF8&saFields=bankIdlastName;bankIdfirstName;bankIdmiddleName;bankIdPassport

Для загрузки всех полей можно использовать: https://test.region.igov.org.ua/wf-region/service/rest/file/downloadTasksData?sID_BP=kiev_mreo_1&sDateAt=2015-06-28&sDateTo=2015-08-01&nASCI_Spliter=59&sID_Codepage=UTF8&saFields=*

*Открытый вопрос*: как необходимо обрабатывать параметр sID_State_BP? В данный момент он фильтрует по DelegationState, возможные значения: PENDING и RESOLVED.

**Comment by bvv4ik** [comment]
Тут не реализован главный пункт №2, ради чего это все затевалось (налоговая, справка о доходах, для субсидии)!

При его реализации сразу-бы обнаружилось-бы "упущение" (просто не получилось-бы реализовать):

Вместо "saFields=bankIdlastName;bankIdfirstName;bankIdmiddleName;bankIdPassport"
должно быть что-то типа(как и написано в таске):
"saFields=${nID_Task};${bankIdPassport};${bankIdlastName} ${bankIdfirstName} ${bankIdmiddleName};1;${sDateCreate})"
Дело в том, что тут два значения из полей сливаются в одну колонку(${bankIdlastName} ${bankIdfirstName}, и это очень важный момент гибкости настройки, без которого п.2. не реализовать в т.ч. должны поддерживаться "фиксированные/кастомные значения")

т.е. для п.2. запрос должен быть:
https://test.region.igov.org.ua/wf-region/service/rest/file/downloadTasksData
?sID_BP=kiev_mreo_1
&sID_BP=dnepr_spravka_o_doxodax
&sID_State_BP=usertask1
&sDateAt=2015-06-28
&sDateTo=2015-08-01
&saFields=${nID_Task};${sDateCreate};${area};;;0;${bankIdlastName} ${bankIdfirstName} ${bankIdmiddleName};4;${aim};${date_start};${date_stop};${place_living};${bankIdPassport};1;${phone};${email}
&sID_Codepage=win1251
&nASCI_Spliter=18
&sDateCreateFormat=dd.mm.yyyy hh24:mi:ss
&sFileName=dohody.dat

Но оно НЕ ВЗЛЕТИТ так при текущей реализации!
в т.ч. не понятно - сработает-ли такое значение в параметре "sDateCreateFormat"(и остальных)

Прошу "допилить", чтоб такой запрос, который я выше уже собрал - смог отработать!


По вопросу:
"Открытый вопрос: как необходимо обрабатывать параметр sID_State_BP? В данный момент он фильтрует по DelegationState, возможные значения: PENDING и RESOLVED."

- а разве не получится выбрать юзертаски БП, по их ИД? например "usertask1" (как в приведенном выше примере справки о доходах)

и, думаю в любом случае, скорей всего "PENDING", т.к. "RESOLVED" похоже на завершенный этап

**Comment by ASkosyr** [comment]
срок поставки с изменениями - сегодня-завтра.

**Comment by RoOmel** [comment]
Работает согласно ТЗ
Фрагмент ответа сервера:
"141004216.32.2015 10:07:17АНД (пров. Універсальний, 12)0БІЛЯВЦЕВ ВОЛОДИМИР ВОЛОДИМИРОВИЧ4мета16/07/201517/07/2015мокешрмшгкеуАЕ432204 БАБУШКИНСКИМ РО ДГУ УМВД 26.09.19961380102030405mendeleev.ua@gmail.com"
