### ISSUE TITLE
на главном портале в форме подвязать к типу "select", и id=sID_Public_SubjectOrganJoin сответствующую сущность SubjectOrganJoin

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#518]
Цель - отрисовать в форме автокомплит, для поля типа "select", с id=sID_Public_SubjectOrganJoin
при этом наполнение этого автокомплита - получить по сервису getSubjectOrganJoin, задав в него параметр sID_UA, полученный еще на стадии выбора обрасти и города.
При выборе пользователем значения из автокомплита - в поле сетить sID_Public

- Загружать список через гетер: getSubjectOrganJoin
(на вики есть дока по АПИ: https://github.com/e-government-ua/i/blob/test/docs/specification.md)

- sID_UA передавать из выбранного региона или города, а если там его нету - не передавать, т.к. он опциональный.
ВАЖНО: пока там нет значений, замокать значение "2", уже после получения значения.
(пометить TODO, чтоб позже можно было удалить)

- Использовать готовый компонент автокомплита(typeahead), который используется для выбора Регионов и Городов (только подвязать его уже к этому сервису getSubjectOrganJoin , пробросим через бэк ноды, как обычно)

- Пример такого поля есть в БП "dnepr_mvd-1.bpmn" (Справка о несудимости, Днепропетровск))  
(задача, по которой оно сделано: https://github.com/e-government-ua/i/issues/534)
на нем и проверять

**Comment by hordesalik** [comment]
поле добавлено в форме города, региона, страны. получение списка проброшено через ноду

**Comment by bvv4ik** [comment]
Для теста:
выбрать отделение(в этом новом поле)
и в фаербаге убедиться, что при сабмите отсылается в поле проставленный ИД-шник

**Comment by LucySuslova** [comment]
Добавьте, пожалуйста, снова поле Отделение, т.к. сейчас его в заявке о получении справки о несудимости (Днепр) нет. 
http://prntscr.com/84gtls

**Comment by bvv4ik** [comment]
создали отдельный БП, для Запорожья.. там это поле уже должно быть

**Comment by LucySuslova** [comment]
поля Отделение нет. по запорожью (справка о несудимости) на месте поля Отделение отображается 
Увага: Довідка буде оформлена протягом 10-20 робочих днів
http://screenshot.ru/upload/image/NIFx

**Comment by bvv4ik** [comment]
прошу проверить повторно - уже все должно отображаться

**Comment by LucySuslova** [comment]
1. на https://test.igov.org.ua/ выбираю "Надання довідки про відсутність (наявність) судимості або обмежень, передбачених кримінально-процесуальним законодавством України."
2.Область Запорожская
3. авторизируюсь через банкИД
4. отображается 
Увага:Довідка буде оформлена протягом 10-20 робочих днів
*Прізвище:ДУБІЛЕТ
![default](https://cloud.githubusercontent.com/assets/11993951/9358224/8da7ce0e-4693-11e5-9224-a6d044f9d8c7.png)

если реализовано, то в какой заявке, области, городе?

**Comment by bvv4ik** [comment]
Услуга и Область выбрана верна.. там ниже есть поле... проскролировать нужно

**Comment by LucySuslova** [comment]
testing completed
