### ISSUE TITLE
Интегрировать проплату через Liqpay

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#519]
ДЕКОМПОЗИРОВАНО:

На бэке централа доработать сущность Merchant и добавить один метод сервиса
https://github.com/e-government-ua/i/issues/511

На бэке (wf-base) создать метод генерации HTML-кода кнопки "Проплаты по LiqPay"
https://github.com/e-government-ua/i/issues/475

Доработать класс(системтаски) "MailTaskWithAttachment" и "MailTaskWithAttachments", и найдя там тэг "[paymentButton_LiqPay]"
https://github.com/e-government-ua/i/issues/513

На бэке централа реализовать сервис для callback-а от liqpay
https://github.com/e-government-ua/i/issues/512

На бэке wf-base реализовать проверку изменения статуса платежа, и правку поля в юзертаске БП
https://github.com/e-government-ua/i/issues/476

**Comment by bvv4ik** [comment]
Павел, пожалуйста:, нужно 

1) предоставить данные тестовой учетки по ликвипею(аккаунту), чтоб можно было добавить запись и проверить весь процесс платежа по нему:
Нужно:
-Публичный ключ,
-Приватный ключ
-Название мерчанта

2) в один из БП добавить глобальные переменные:
sID_Payment - ИД транзакции платежа (записать туда: пробел)
nID_Subject - ИД-номер субъекта (записать туда: 0)
sID_Merchant - ИД-строковой мерчанта (магазина), (записать туда: Публичный ключ мерчанта)
String sSum - строка сумма платежа, (записать туда: сумму платежа)
String sID_Currency - ИД-строковой валюты, (записать туда: ИД валюты, например UAH)
String sDescription - строка-описание, String (записать туда: краткое описание платежа)

3) в этот-же БП добавить на нужную юзертаску:
поле со ссылкой на глобальное поле sID_Payment
(т.к. в нее потом попадет ИД транзакции платежа)

4) в этот-же БП, в письмо встроить тэг "[paymentButton_LiqPay]", где нужно разместить кнопку для проплаты

5) Написать тут в коменте - ИД БП, его название и название услуги на главном портале, с кородом (желательно со ссылкой)

**Comment by bvv4ik** [comment]
@kurbpa 
Павел, пожалуйста:, нужно 

1) предоставить данные тестовой учетки по ликвипею(аккаунту), чтоб можно было добавить запись и проверить весь процесс платежа по нему:
Нужно:
-Публичный ключ,
-Приватный ключ
-Название мерчанта

2) в один из БП добавить глобальные переменные:
sID_Payment - ИД транзакции платежа (записать туда: пробел)
nID_Subject - ИД-номер субъекта (записать туда: 0)
sID_Merchant - ИД-строковой мерчанта (магазина), (записать туда: Публичный ключ мерчанта)
String sSum - строка сумма платежа, (записать туда: сумму платежа)
String sID_Currency - ИД-строковой валюты, (записать туда: ИД валюты, например UAH)
String sDescription - строка-описание, String (записать туда: краткое описание платежа)

3) в этот-же БП добавить на нужную юзертаску:
поле со ссылкой на глобальное поле sID_Payment
(т.к. в нее потом попадет ИД транзакции платежа)

4) в этот-же БП, в письмо встроить тэг "[paymentButton_LiqPay]", где нужно разместить кнопку для проплаты

5) Написать тут в коменте - ИД БП, его название и название услуги на главном портале, с кородом (желательно со ссылкой)

**Comment by kurbpa** [comment]
Публичный ключ: i10172968078
Приватный ключ: BStHb3EMmVSYefW2ejwJYz0CY6rDVMj1ZugJdZ2K
Название мерчанта: igov test

https://test.igov.org.ua/service/159/general - услуга на портале для Киева

**Comment by RoOmel** [comment]
1. На бэке централа доработать сущность Merchant и добавить один метод сервиса
#511 - реализованы и протестированы п. 1) и 2) 
Ответ сервера по п 2)
{
    "nID": 2,
    "sID": "i10172968078",
    "sName": "igov test",
    "sPrivateKey": "BStHb3EMmVSYefW2ejwJYz0CY6rDVMj1ZugJdZ2K",
    "sURL_CallbackStatusNew": "test_sURL_CallbackStatusNew",
    "sURL_CallbackPaySuccess": "test_sURL_CallbackPaySuccess",
    "nID_SubjectOrgan": 1
}
Нет описания п.3) , для проверки реализации нужна инфа

2. На бэке (wf-base) создать метод генерации HTML-кода кнопки "Проплаты по LiqPay"
#475 - реализована и протестирована

3. Доработать класс(системтаски) "MailTaskWithAttachment" и "MailTaskWithAttachments", и найдя там тэг "[paymentButton_LiqPay]"
#513 рекурсивная ссылка на https://github.com/e-government-ua/i/issues/519

4. На бэке централа реализовать сервис для callback-а от liqpay
#512 п.1), 2), 3) как я понял не реализованы

5. На бэке wf-base реализовать проверку изменения статуса платежа, и правку поля в юзертаске БП
#476 рекурсивная ссылка на https://github.com/e-government-ua/i/issues/519

**Comment by bvv4ik** [comment]
все реализовано.. сейчас как раз идет тестирование..
отпишемся тут по результату

**Comment by bvv4ik** [comment]
все работает
для теста:
создать процесс услуги по МРЕО (Киев)
и в дашборде взять и отработать таску, до получения ИД транзакции платежа (придет письмо на мыло с кнопкой платежа, который нужно провести (одну копейку, тестовый))

**Comment by RoOmel** [comment]
На бэке централа доработать сущность Merchant и добавить один метод сервиса
#511 - реализована и протестирована п. 3) 
Ответ сервера:
{
    "nID": 2,
    "sID": "i10172968078",
    "sName": "igov test",
    "sPrivateKey": "BStHb3EMmVSYefW2ejwJYz0CY6rDVMj1ZugJdZ2",
    "sURL_CallbackStatusNew": "test_sURL_CallbackStatusNew",
    "sURL_CallbackPaySuccess": "test_sURL_CallbackPaySuccess",
    "nID_SubjectOrgan": 1
}

**Comment by RoOmel** [comment]
Тестирование:
1. Создал заявку услуги по МРЕО (Киев)
Пришло уведомление на "мыло" о создании заявки.
2. В дашборде нет возможности отработать таску, до получения ИД транзакции платежа.
2.1 Ошибка "Помилка. SYSTEM_ERR null" после ввода времени, даты и нажатия "Опрацювати" - для юзера ничего не означает.
2.2. Надо сделать предзаполнение поля "В разі надання послуги, вкажіть час/дату, коли авто може пройти огляд" для наглядности и корректности ввода;
2.3. Должна быть возможность удалить прикреплённый файл

**Comment by bvv4ik** [comment]
такс, давайте "мухи - отдельно, котлеты - отделдьно"...
то шо так было-бы лучше - ни кто не спорит... диалоги разные будем делать и даже некоторые таски уже стоят по этому поводу.. но это все не в рамках задачи "Ликвипея"

**Comment by RoOmel** [comment]
2. В дашборде нет возможности отработать таску, до получения ИД транзакции платежа.
  Ошибка "Помилка. SYSTEM_ERR null" после ввода времени, даты и нажатия "Опрацювати"
https://github.com/e-government-ua/i/issues/598
   Улучшения по процессу отработки таски оформил https://github.com/e-government-ua/i/issues/599

**Comment by bvv4ik** [comment]
#599, а точнее ее дубль: https://github.com/e-government-ua/i/issues/598
уже поправлены...

**Comment by RoOmel** [comment]
#599 - это фича, #598 - баг, поэтому никаких дублей тут нет, тем более не я выше указал "мухи - отдельно, котлеты - отдельно".

**Comment by bvv4ik** [comment]
ну причем тут отработанные?
данная таска про ликвипей, как новый механизм.
с отработанными - отдельная тема...

какие есть замечания по текущей таске (исключая то что я упомянул выше)?

**Comment by RoOmel** [comment]
2) в дашборде взять и отработать таску, до получения ИД транзакции платежа (придет письмо на мыло с кнопкой платежа, который нужно провести (одну копейку, тестовый))
На "мыло" не приходит письмо с кнопкой платежа.

**Comment by bvv4ik** [comment]
вообще ни каое письмо не приходит? или приходит но без кнопки?

можно (даже желательно) проверять на специальном отдельном тестовом БП
_test_liqPay

**Comment by RoOmel** [comment]
1-ое сообщение "Ваше звернення успішно зареєстровано.
Результат обробки звернення будуть спрямовані на цей е-мейл "
2-ое "Для отримання послуги Вам необхідно сплатити державний збір і надати квитанцію про сплату перед тех.оглядом Вашого авто.
Рахунок для сплати знаходиться в додатку до цього листа."
В аттачменте письма ничего нет

**Comment by RoOmel** [comment]
Сервис https://github.com/e-government-ua/i/blob/test/docs/specification.md#20 я тестировал, он работает корректно.

**Comment by bvv4ik** [comment]
"В аттачменте письма ничего нет"
в атачменте и не должно быть...  просто развернуть письмо полностью.. кнопка точно приходит

**Comment by RoOmel** [comment]
Да хоть полность, хоть не полностью, если кнопки нет - значит нет.
Покажи скриншот как должно быть.
Попробую ещё раз создать заявку - посмотрим.

**Comment by VadimGulich** [comment]
На тестовом БП _test_liqPay  кнопка есть , только текст  не совсем корректный  вход в Банк ИД я проводил под своим акк.:
"Оплата прошла успешно!
ID - 64547228"
![image](https://cloud.githubusercontent.com/assets/12964120/8977642/ac3a00e4-36a3-11e5-86b2-a7b0e881d367.png)
------------------------------------------------------------------------------
В данном случае "для теста:
1) создать процесс услуги по МРЕО (Киев)
2) в дашборде взять и отработать таску, до получения ИД транзакции платежа (придет письмо на мыло с кнопкой платежа, который нужно провести (одну копейку, тестовый))"

письмо приходит в виде:
![image](https://cloud.githubusercontent.com/assets/12964120/8977782/c10a01c6-36a4-11e5-8488-9c3a5b4f39e0.png)

**Comment by bvv4ik** [comment]
просто изменили БП... для теста выделили отдельный БП
