### ISSUE TITLE
Создать новый тип поля "select" в activiti, на основе "string"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#520]
создать класс и прописать в контексте

**Comment by bvv4ik** [comment]
Для теста:
в активити-эксплорере можно увидеть это новый тип

**Comment by LucySuslova** [comment]
Подскажите, пожалуйста, в каких заявках должно быть это поле

**Comment by bvv4ik** [comment]
скорее не в заявках а в бизнеспроцессах.
например в: dnepr_mvd-1
с ИД: sID_Public_SubjectOrganJoin
глянуть можно в Активити-Эксплорере

**Comment by LucySuslova** [comment]
testing completed successfully
