### ISSUE TITLE
Кнопки "Всі послуги" не раскрывают полные списки услуг при нажатии в каждой из подкатегорий на главной странице

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#521]
Окружение:
Mozilla Firefox 39.0, Google Chrome 43.0, IE 11.0

**Comment by bvv4ik** [comment]
это все следствие обновления портала, и уже занесена в список "находок":
https://docs.google.com/document/d/10xJsczHxVjAQRy4vchQ5bqjH7_WzMMOsxwFA_HTg6zo/edit

прошу, если что-то из "еще работающего 2 дня назад и уже не работающего сегодня" обнаружится - дописывать в конец списка...
