### ISSUE TITLE
Ответ сервера "2015-06-21:09-20-40" в Получение статистики по задачам в рамках бизнес процесса

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#522]
Получение статистики по задачам в рамках бизнес процесса
https://test.region.igov.org.ua/wf-region/service/rest/file/download_bp_timing?sID_BP_Name=lviv_mvk-1&sDateAt=2015-06-28&sDateTo=2015-07-01
Ответ сервера "2015-06-21:09-20-40"
Это противоречит условиям исходной задачи https://github.com/e-government-ua/i/issues/376

**Comment by bvv4ik** [comment]
"то противоречит условиям исходной задачи #376"
та задача к этой не относится
