### ISSUE TITLE
Добавить в сущность SubjectMessage поле nID_SubjectMessageType а SubjectMessageType реализовать в виде энума

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#528]
поля sName этума:
0 ServiceNeed "Просьба добавить услугу" (умолчательное)
1 ServiceFeedback "Отзыв о услуге"

при этом поле "nID_SubjectMessageType ", если оно не задается в сетере должно ставиться=0

nID_SubjectMessageType = индекс элемента энума

**Comment by brunneng** [comment]
Созданная таблица:
CREATE TABLE "SubjectMessageType"
(
  "nID" integer NOT NULL,
  "sName" character varying(100) NOT NULL,
  "sDescription" character varying(500) NOT NULL,
  CONSTRAINT pk_subjectmessagetype PRIMARY KEY ("nID"),
  CONSTRAINT "SubjectMessageType_sName_key" UNIQUE ("sName")
)

**Comment by bvv4ik** [comment]
все-же решил не создавать энум?

**Comment by brunneng** [comment]
хм. я думал имелась в виду таблица словарь :)

**Comment by bvv4ik** [comment]
ну это ничего - так тоже норм) переделывать не стоит... таблица-ж .csv есть? и в ликвибейсе прописано все?

**Comment by brunneng** [comment]
ага. все есть

**Comment by bvv4ik** [comment]
от только-бы доку еще подправить)

**Comment by bvv4ik** [comment]
а как протестить можно?

**Comment by brunneng** [comment]
Для теста проверить что соответствует спецификации:
https://github.com/e-government-ua/i/blob/test/docs/specification.md
12. Работа с сообщениями

Например можно через метод setMessage выставить другой тип сообщения через параметр nID_SubjectMessageType,  и с помощью метода getMessage проверить что он изменился.

**Comment by VadimGulich** [comment]
Работает согласно описанию 
Можно в релиз
