### ISSUE TITLE
На бэке централа (wf-central), доработать сервис getDocumentFile, чтоб доступ мог получить не только хозяин документа, но и тот, кому так-же он был открыт

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#533]
Кроме проверки на соответствие nID_Subject
Реализовать альтернативную проверку через логику сервиса:
getDocumentAccessByHandler (взять от туда образец кода)
и переданные опциональные параметры:
sCode_DocumentAccess
nID_DocumentOperator_SubjectOrgan
nID_DocumentType
sPass

- Если вызов не вернул эксепшина, то так-же отрабатывать метод.

- Проверять альтернативно, только если как минимум 3 первых параметра были переданы.

**Comment by bvv4ik** [comment]
Для теста:
зайти на: https://test.igov.org.ua/documents/search
там код: 2
тип Справка
поиск
пароль: 123
подтвердить
и в табличке - загрузить документ 
сейчас напишет ошибку, но как только будет завершена полностью задача:
https://github.com/e-government-ua/i/issues/482
то перестанет писать ошибку а именно даст загрузить документ.

**Comment by rooksnest** [comment]
При попытке загрузить файл, ошибка не отображается, но и загрузка не производится, лишь открывается пустая страница.
Бага или это от того, что еще не полностью реализована задача #482

**Comment by bvv4ik** [comment]
нужно дождаться пока выполнится полностью таска #482

**Comment by bvv4ik** [comment]
482 выполнилась

**Comment by nazarenkod** [comment]
Документ загружается
![downloadfile](https://cloud.githubusercontent.com/assets/13256486/8722143/24b99f3c-2bca-11e5-9dac-7734570018d3.jpg)

**Comment by RoOmel** [comment]
Отображается только текст "Document Access need password - sent SMS" в нижнем поле
Всё, конец фильма)

**Comment by nazarenkod** [comment]
А сейчас не работает
![wrongpass](https://cloud.githubusercontent.com/assets/13256486/8727783/40635b2c-2bea-11e5-9fca-23da14796cc7.png)

**Comment by AVATOR** [comment]
сейчас должно работать.
sms код новый: 444

**Comment by nazarenkod** [comment]
Не работает
![wrongpass1](https://cloud.githubusercontent.com/assets/13256486/8730997/1922a65e-2bfd-11e5-90a2-101db4b4192a.jpg)

**Comment by AVATOR** [comment]
сорри тупонул
4444

**Comment by nazarenkod** [comment]
Грузит
![correct](https://cloud.githubusercontent.com/assets/13256486/8731163/45c2ec40-2bfe-11e5-8427-70e9c3f7aa8b.png)

**Comment by VadimGulich** [comment]
Протестировано , можно в релиз
