### ISSUE TITLE
Создать новый тип "select" в Activiti, на базе String

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#534]
Добавить пример такого поля есть в БП "dnepr_mvd-1.bpmn" (Справка о несудимости, Днепропетровск))  

сделать id=sID_Public_SubjectOrganJoin

**Comment by bvv4ik** [comment]
Для теста:
Убедиться что такое поле появляется в данном БП, на центральном портале.
Его лейбл: "Отделение"

**Comment by udelis** [comment]
протестировано
http://img.prntscr.com/img?url=http://i.imgur.com/vkfH5L6.png
