### ISSUE TITLE
На главном портале - устранить все баги, возникшие после рефакторинга

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#535]
https://docs.google.com/document/d/10xJsczHxVjAQRy4vchQ5bqjH7_WzMMOsxwFA_HTg6zo/edit

**Comment by VadimGulich** [comment]
Ошибка:
![image](https://cloud.githubusercontent.com/assets/12964120/8722404/ff70598e-2bcc-11e5-99b8-3a5c028678b2.png)

Ожидаемый результат:
![image](https://cloud.githubusercontent.com/assets/12964120/8722405/08a29aee-2bcd-11e5-9809-a4e25f4e3cf8.png)

**Comment by VadimGulich** [comment]
Неактивная кнопка после подачи заявки(пример "Надання довідки про відсутність (наявність) судимості або обмежень, передбачених кримінально-процесуальним законодавством України." Днепропетровск) 
![image](https://cloud.githubusercontent.com/assets/12964120/8722442/75d621bc-2bcd-11e5-8ce0-960398981977.png)

Не открываются некоторые услуги:
Пример: Перегляд інтерактивної карти ділянок надр, на які надані спецдозволи на користування надрами
УРЛ: https://test.igov.org.ua/service/629/general
Скрин:
![image](https://cloud.githubusercontent.com/assets/12964120/8722507/050d3cd0-2bce-11e5-8593-952d53246b7f.png)

**Comment by VadimGulich** [comment]
4) Вход по ЕЦП:    GET https://test.igov.org.ua/auth/isAuthenticated  401 Unauthorized

**Comment by bvv4ik** [comment]
1. уже заметили, занимаются...
2. было и до рефакторинга (пока не будем тратить время на это, до выкладки версии)
3. точно работало, видимо какой-то последний комит поламал... глянем
4. проблема от части на стороне БанкИД, должно заработать сегодня, т.к. достигли договоренность на вчерашнем селекторе.

**Comment by VadimGulich** [comment]
Когда будут внесены правки отпишите ,пож-ста

**Comment by Kamilius** [comment]
1 і 3я - готово

**Comment by VadimGulich** [comment]
3 пункт исправлен , но появился еще один баг
Ошибка: 
![image](https://cloud.githubusercontent.com/assets/12964120/8753392/21c24126-2cc4-11e5-9f08-a84b3fb58e6d.png)

Ожидаемый результат:
![image](https://cloud.githubusercontent.com/assets/12964120/8753377/fdd28122-2cc3-11e5-929b-8e4d6cf64fd2.png)

**Comment by bvv4ik** [comment]
да, похоже и это глюк

**Comment by bvv4ik** [comment]
кстати, п.4. в БанкИД уже тоже починили

**Comment by VadimGulich** [comment]
Щас проверю , а глюк тот будете исправлять ?

**Comment by VadimGulich** [comment]
подтверждаю , пункт 4 исправлен

**Comment by bvv4ik** [comment]
глюк, конечно, нужно исправить перед деплоем..
Надежда на @Kamilius

**Comment by Kamilius** [comment]
@VadimGulich @bvv4ik готово :)

**Comment by bvv4ik** [comment]
так шо - закрываем таску?

**Comment by VadimGulich** [comment]
Да , закрываем , все ок
