### ISSUE TITLE
Некорректная работа фильтров поиска

### ISSUE THREAD

**Issue by Polsha** [e-government-ua/i#536]
1. Открыть главную страницу (https://igov.org.ua/)
2. В поле поиска ввести "!!!!!"  (чтобы поиск не дал результатов)
3. Нажимаем на выпадающий список в поле поиска
![issue_1](https://cloud.githubusercontent.com/assets/13255104/8639624/71403f08-28e8-11e5-903e-cef5c16f32fb.png)

4. Очищаем поле поиска

Фактический результат:
Поле статуса услуг не обновляется
![issue_2](https://cloud.githubusercontent.com/assets/13255104/8639631/cf0266de-28e8-11e5-80f1-09baedb131c2.png)

Ожидаемый результат - Поле статуса услуг обновилось.
Browsers: IE 9.0/ FF-39/Chrome-43

**Comment by bvv4ik** [comment]
ребята, прошу, не засоряйте такими тасками пул!
1) это все не баг а не реализованный функционал, или ремарка
2) всю такую мелочевку пишите в одном общем гуглофайле.
3) всем совершенно невозможно работать с реальными тасками, когда они полность "тонут" во всех подобных "ремарках", которые исправлять будут далеко не в первую очередь...
