### ISSUE TITLE
Не реагирует на клик лого сайта в хедере

### ISSUE THREAD

**Issue by Polsha** [e-government-ua/i#537]
1.Открыть главную страницу сайта (https://igov.org.ua/)
2.Нажимаем на выпадающий список в поле поиска
3.Клик на лого сайта в хедере
![issue_3](https://cloud.githubusercontent.com/assets/13255104/8639802/dea686e8-28ec-11e5-894a-185d51fa3f6b.png)

Фактический результат: ничего не происходит
Ожидаемый результат: обновление страницы сайта

Browsers: IE 9.0/ FF-39/Chrome-43

**Comment by bvv4ik** [comment]
ребята, прошу, не засоряйте такими тасками пул!
1) это все не баг а не реализованный функционал
2) всю такую мелочевку пишите в одном общем гуглофайле.
3) всем совершенно невозможно работать с реальными тасками, когда они полность "тонут" во  всех подобных "ремарках", которые исправлять будут далеко не в первую очередь...
