### ISSUE TITLE
Функционал [S3] - Последняя цифра nID_Protected при генерации не соответсвует логике алгоритма Луна

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#538]
Окружение (ОС, браузер): Windows 7x64, Mozilla Firefox 39.0, Chrome 43.0

Предусловия:
1. Открыта веб-страница Онлайн-калькулятора контрольной суммы по Алгоритму Луна http://planetcalc.ru/2464/;
2. Открыто приложение "Notepad";
3. Открыт Rest-клиент с методом GET и  со страницей запроса
по запросу http://test.igov.org.ua/wf-central/service/services/addHistoryEvent_Service?nID_Task=2&sStatus=new&nID_Subject=2
("Activiti REST API":kermit/kermit)

Тестовые данные:
nID_Task - ИД-номер задачи (long)
nID_Subject - ИД-номер (long) //опциональный
nID_Protected - проверочное число-ид
sStatus - строка-статус (long)

Шаги воспроизведения:
1. Добавить новое событие (согласно доке https://github.com/e-government-ua/i/blob/test/docs/specification.md#17_workWithHistoryEvent_Services)
по запросу http://test.igov.org.ua/wf-central/service/services/addHistoryEvent_Service?nID_Task=2&sStatus=new&nID_Subject=2;
2. Сохранить параметры ответа сервера "nID_Protected", "nID" со значениями в "Notepad";
3. Скопировать в буфер значение "nID" из "Notepad", вставить из буфера в поле "Последовательность цифр:" Онлайн-калькулятора контрольной суммы по Алгоритму Луна и нажать кнопку "Рассчитать";
4. Подставить значение поля "Следующая проверочная цифра:" Онлайн-калькулятора контрольной суммы по Алгоритму Луна после значения "nID" из "Notepad"

Актуальный результат:
значения "nID" из "Notepad" и "nID_Protected" отличаются;
Ожидаемый результат: 
значения "nID" из "Notepad" и "nID_Protected" совпадают;

Описание алгоритма Луна https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC_%D0%9B%D1%83%D0%BD%D0%B0
Онлайн-калькулятор контрольной суммы по Алгоритму Луна
http://planetcalc.ru/2464/
Исходный код этого калькулятора
http://planetcalc.ru/personal/source/?id=2461

Исходная таска https://github.com/e-government-ua/i/issues/493

**Comment by bvv4ik** [comment]
@RoOmel разработчик по исходной задаче ни "слухом ни духом" не узнает о том, что Вы написали...
прошу - либо в исходной таске написать в комментарии кратко о "претензии по результату тестирования", со ссылкой на эту, вновь созданную задачу, либо целиком перенести все это в комментарий к той задаче... проанализировать и ответить Вам может только тот кто реализовывал таску, а он(она) вообще не в курсе того что вы написали...

**Comment by RoOmel** [comment]
Так в исходной таске последним комментом есть запись про найденный баг.
Ок, напишу коммент дополнительно.

**Comment by LamronNu** [comment]
@RoOmel , теперь я точно вижу, что Вы ожидаете увидеть не ту цифру.

Вы пишете, что должно быть:
>Подставить значение поля "Следующая проверочная цифра:" Онлайн-калькулятора контрольной суммы по Алгоритму Луна после значения "nID" из "Notepad"

тогда как в моем <a href="https://github.com/e-government-ua/i/issues/493#issuecomment-120922747">комментарии</a> и в самой <a href="https://github.com/e-government-ua/i/blob/test/docs/specification.md#17_workWithHistoryEvent_Services">доке</a> написано, что берется **"последний разряд контрольной суммы"**...

**Comment by LamronNu** [comment]
протестируйте, пожалуйста,  метод согласно этому условию.
если и в этом случае найдутся ошибки -- буду разбираться.
спасибо!

**Comment by RoOmel** [comment]
Не вопрос, т.к. перед заведением бага, несколько раз прошёл шаги.
Итак:
1. сервер возвращает следующие параметров со значениями:
"nID_Protected": 202765
"nID": 20276
Как видно из результата "nID" отличается от "nID_Protected" на цифру 5;
2. Подставляю в калькулятор значения параметра "nID" 20276, чтобы проверить корректности генерации "nID_Protected";
3. При вводе в поле "Последовательность цифр:" 20276 и нажатии "Рассчитать" - получаем ответ калькулятора в поле "Следующая проверочная цифра:" 2;
4. Подставляем полученную цифру 2 справа от значения "nID" - получаем 202762, то соответствует корректному значению и не соответствует значению "nID_Protected", полученному от сервера
Если полученное число 202762 теперь подставить в калькулятор и снова нажать "Рассчитать" - в поле "Последний разряд контрольной суммы:" будет цифра 0, что говорит о кратности контрольной суммы проверочного числа.
Все дейсвия калькулятора можно проделать вручную, но результат будет тот же, поэтому не вижу смысла это расписывать.

Ваш алгоритм даёт примерно 20% правильных значений, при этом системы я не заметил.
Попробуйте в качестве версии заменить свой алгоритм на уже существующий и работающий без ошибок с сайта, кот. я указал, а дальше решайте сами что делать.

**Comment by LamronNu** [comment]
мой алгоритм выдает "последний разряд контрольной суммы", тогда как Вы продолжаете ожидать там "следующую проверочную цифру"

**Comment by RoOmel** [comment]
Вот строка из доки "сначала проверяется корректность числа nID_Protected -- последняя цифра должна быть "контрольной" (по алгоритму Луна) для всего числа без нее."

**Comment by RoOmel** [comment]
Если это "Последний разряд контрольной суммы:" - тогда алгоритм правильный, но в постановке задачи напутано

**Comment by LamronNu** [comment]
>Вот строка из доки "сначала проверяется корректность числа nID_Protected -- последняя цифра должна быть "контрольной" (по алгоритму Луна) для всего числа без нее."

есть такое. а ниже, через пару абзацев, есть объяснение, что это за "контрольная цифра".

не хотелось дублировать объяснение дважды, чтобы не "засорять эфир" доки (сначала кратко, а позже -- развернуто). если не нравится описание в документации -- Вы всегда можете его поправить, это же общедоступный ресурс..

постановку тз (в котором просто написано, что это должна быть "контрольная сумма") можно трактовать по-разному. первый вариант алгоритма у меня вообще возвращал сумму цифр контрольной суммы. потом, после уточнения у @bvv4ik,  переделано было на "последний разряд".. при желании, можно сделать и "следующую проверочную цифру" -- но зачем? задача состоит в том, чтобы:
а) генерировать как-то "проверочную цифру"
б) по этой цифре проверять корректность введенного нИД.

свою функцию этот метод выполняет.

**Comment by bvv4ik** [comment]
Согласен полностью с @LamronNu
реализовано точно в соответствии с заданием!

**Comment by RoOmel** [comment]
"если не нравится описание в документации" - нравится/не нравится...
...задача описана в двух местах и описана поразному - вот я и задаю вопросы, чтобы понять как я должен тестировать и какой результат ожидать.

"реализовано точно в соответствии с заданием" - в этом как раз и заключается моя задача, проверить соответстиве актуального результата ожидаемому исходя из постановки задачи.

**Comment by RoOmel** [comment]
По запросу
http://test.igov.org.ua/wf-central/service/services/updateHistoryEvent_Service?nID_Protected=33&sStatus=finish
Актуалный результат:
could not resolve property: nID of: org.wf.dp.dniprorada.model.HistoryEvent_Service
Ожидаемый результат:
Record not found

**Comment by LamronNu** [comment]
спасибо за замечание!

поправлена документация -- возвращается не словосочетание "Record not found", а  код состояния HTTP 403 с пояснением ошибки "Record not found".

т.е. это нужно смотреть через Network Browser (в хроме это Просмотр кода элемента -- вкладка Network)

и пожалуйста, если Вы тестируете задачу #493, то пишите замечания туда -- так будет видно весь процесс тестирования-отладки задачи... тем более, что текущий коммент совсем не относится к заголовку issue. по-хорошему, эту таску можно было уже закрыть (т.к. все вопросы разобраны) -- и продолжить "разбор полетов" по таске 493 уже там...

спасибо!

**Comment by RoOmel** [comment]
Ок, перенесу туда свой коммент, чтобы была хронология событий.
