### ISSUE TITLE
На бэке централа(wf-central), при использовании метода "предоставления доступа к документу", заменить возврат УРЛ-а, на ИД-номер

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#539]

**Comment by bvv4ik** [comment]
Для теста:
нужно зайти в Документы, там, в строке с документом кликнуть на иконку "цепочку", и заполнив поля открыть доступ. в итоговом диалоге должен отобразиться в поле номер а не УРЛ

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/8659332/c2bb7cf6-29b2-11e5-9a4a-69598720dde0.png)

не реализовано , отображается УРЛ + кнопка копировать не работает (над кнопкой "ОК")

**Comment by bvv4ik** [comment]
тестируем на ТЕСТОВОМ, а не боевом

**Comment by VadimGulich** [comment]
Первое тестирование проводил на https://test-version.igov.org.ua))

Тестирование на тестовом:
![image](https://cloud.githubusercontent.com/assets/12964120/8668824/c427224c-2a17-11e5-85bb-0580be6a8b95.png)

Не открывается форма для заполнения полей

**Comment by VadimGulich** [comment]
Реализовано/протестировано  ошибки по получению доступа по коду и отображения меню будут описаны в других  задачах https://github.com/e-government-ua/i/issues/544

**Comment by VadimGulich** [comment]
https://github.com/e-government-ua/i/issues/552
