### ISSUE TITLE
[S5] - Орфографическая ошибка

### ISSUE THREAD

**Issue by annasahi** [e-government-ua/i#541]
Форма "Знайшли помилку або баг на Порталі?" (ссылка на главной станице "Помилка або баг на Порталі?")
"Опішить проблему, будь ласка" - ошибка в слове "Опішить", а надо "Опишіть" http://prntscr.com/7qnn2n

**Comment by bvv4ik** [comment]
Дмитрий Александрович,
вроде это в гугловской форме очепятка?
если дадите права на нее - я поправлю, или Вы...

**Comment by bvv4ik** [comment]
.

**Comment by bvv4ik** [comment]
Просьба перенести эту issue в бэклог и закрыть ее:
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit

**Comment by annasahi** [comment]
Issue перенесена в бэклог.
