### ISSUE TITLE
На главном портале, при заполнении гражданином формы услуги - автоматически подтягивать из БанкИД дополнительные поля

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#542]
- [x] адрес прописки - оставить редактируемым (id=bankId*)
- [x] гражданство (id=bankIdsID_Country)
- [x] телефон - оставить редактируемым (id=bankId*)
- [x] email - оставить редактируемым (id=bankId*)

ВАЖНО:
- Все такие поля на форме, в таких случаях, так-же как и сейчас, должны начинаться с фразы "bankId", а продолжаться ИД полем БанкИД, как и при текущем автоматическом подтягивании ФИО, Паспорта и т.д.
- Документация по БанкИД:
https://github.com/e-government-ua/i/wiki/%D0%9A%D0%BE%D1%80%D0%B8%D1%81%D0%BD%D1%96-%D0%BF%D0%BE%D1%81%D0%B8%D0%BB%D0%B0%D0%BD%D0%BD%D1%8F-%D1%82%D0%B0-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D1%96%D1%8F#%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F-%D0%BF%D0%BE-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-bankid

**Comment by bvv4ik** [comment]
для теста нужно создать тестовый БП со всеми этими полями
id
bankIdsID_Country
bankIdemail
bankIdphone
bankIdAddressFactual

@dmitrijzabrudskij  Дима создай плиз БП "_test_fields_bankid"

**Comment by dmitrijzabrudskij** [comment]
https://test.igov.org.ua/service/720/general

**Comment by dmitrijzabrudskij** [comment]
https://test.igov.org.ua/service/720/general

**Comment by VadimGulich** [comment]
Поля не появились пока:
![image](https://cloud.githubusercontent.com/assets/12964120/9331898/844d62de-45ca-11e5-8495-9e444c21a5b9.png)

**Comment by VadimGulich** [comment]
Ошибка : Всплывающее окно блокирует работу https://test.region.igov.org.ua:6948/tasks
(сообщение в окне с "кривым переводом")

Шаги:
1) Войти в https://test.region.igov.org.ua:6948/tasks 
2) Выбрать пункт - В работе
3) Открыть заявку по субсид.  , пример: (2015-8-3 15:5) Отримання субсидії на оплату житлово-комунальних послуг | Взяти в роботу   (#2075403)
4) Из выпадающего списка выбрать печать декларации
5) Нажать печать (после зап обяз.полей)
6) Закрыть окно печати
7) Перейти в меню - Необработанные

Появилось всплывающее сообщение которое блокирует работу : 
![image](https://cloud.githubusercontent.com/assets/12964120/9460473/0622de80-4b0f-11e5-85ff-166b51a6c17c.png)

**Comment by bvv4ik** [comment]
@dmitrijzabrudskij Дима, ктото прибил БП или переименовал его?

**Comment by dmitrijzabrudskij** [comment]
я не трогал его. процесс как был, так и остался. https://test.igov.org.ua/service/720/general

**Comment by bvv4ik** [comment]
@dmitrijzabrudskij 
Дима, реально какой-то бок... БП не задеплоен...
ты можеш переименовать файл с БП и в каталоге поправить?
а то стремно, не проверив это на боевой выкладывать...

**Comment by dmitrijzabrudskij** [comment]
таки да - моя ошибка. поправил. пробуйте

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/9495119/8c53f22e-4c12-11e5-981b-f6919e4cf31b.png)


Поля телефона и почты не редактируются 
Ожидаемый результат: Согласно описанию задачи поля редактируемые

**Comment by dmitrijzabrudskij** [comment]
подтверждаю. в самом процессе поля заведены как редактируемые

**Comment by bvv4ik** [comment]
редактируемость полей задается для дашборда а не центрального портала...
на центральном портале все автоматические поля - не радактируемые (другого концепта пока не принимали)

**Comment by dmitrijzabrudskij** [comment]
нужно значит предусмотреть какой-то атрибут чтобы некоторые поля из банкид могли быть редактируемыми. задваться должен проектировщиком бизнес-процесса

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/9513214/887f9652-4c95-11e5-8842-1d8cd1bd98ad.png)
Не отображается почта


а так ,тогда норм:
![image](https://cloud.githubusercontent.com/assets/12964120/9513251/41701cf4-4c96-11e5-80c5-11cc3f1ef4c6.png)

**Comment by bvv4ik** [comment]
По редактируемости полей создана отдельная таска:
https://github.com/e-government-ua/i/issues/706

**Comment by bvv4ik** [comment]
Не отображается почта
тут, скорей всего, не задан кастомный шаблон конечного диалога после сабмита, где будет указан корректный ИД поля с электронкой... Дима, можеш, по свободе, добавить в этот тестовый БП (кажись поле response)
