### ISSUE TITLE
На главном портале реализовать валидацию поля, которое промаркеровано как Электронный адрес + подкрашивать красной рамочкой такие поля (в т.ч. по номеру телефона) и справа отображать текст ошибки, если поле таки не валидно.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#543]
ВАЖНО: сделать точь-в точь как в задаче: https://github.com/e-government-ua/i/issues/375

только уже не для номера телефона
(по сути механизм уже там готовый будет использоваться, останется дописать кусок валидации формата телефона)

в файле:
\i\central-js\client\app\service\built-in\controllers\servicebuiltinbankid.controller.js

встроить:

function checkEmail(email) {
    var re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
    return re.test(email);
}

посмотрев как через обьект "markers" проверяется - какие поля нужно валидировать

ВАЖНО: Добавить отрисовку "красной рамочки" вокруг полей и справа пояснения ошибки, если поле не валидно (для некоторых полей такое уже реализовано и даже не дает сабмитмть... но только для обязательных полей пока и для номерных полей.. а нужно и для номера телефона и для почты)

**Comment by bvv4ik** [comment]
Уже реализована таска: https://github.com/e-government-ua/i/issues/375
(там только нужно будет напротив полей отображать подсвечивание того, что поля заполнены не валидно, если так будет)

так что нужно просто расширить проверку этого-же механизма, до электронки

**Comment by rostag** [comment]
Роблю валідацію + візуальні ефекти до неї.

**Comment by rostag** [comment]
@bvv4ik - я завершив писати код валідатора, та перед тим, як відправляти код, хочу уточнити: де саме буде поле типу "markers"? Чи вірно я розумію, що він буде однією із властивостей форми, до якої належить даний input, що проходить валідацію?

**Comment by bvv4ik** [comment]
@rostag отлично!
"де саме буде поле типу "markers"?"
сейчас пока не стоит об этом думать... но на будущее - оно будет браться именно кк значение одного из полей формы(скрытое-техническое). т.е. Бизнесаналитики будут в БП добавлять такое поле, делать ему тип markers, и описывать там какие типы валидаций и на какие поля формы нужны. а уже на фронте(позже и на бэке) - будут находиться унифицированные механизмы валидации(в т.ч. как этот), которые по каждому типу для перечисленных по нему полям будет производить специфическуб для него процедуру сверки... там дальше и WIM-код машины и т.д.

**Comment by rostag** [comment]
@bvv4ik в процесі тестування виявив, що дана регулярка "пропускає" й неправильні адреси, наприклад: aaa@aaa/aaa. Можна замість неї використати, наприклад, таку:

/^[-a-z0-9~!$%^&*_=+}{\'?]+(\.[-a-z0-9~!$%^&*_=+}{\'?]+)*@([a-z0-9_][-a-z0-9_]*(\.[-a-z0-9_]+)*\.(aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,5})?$/i

**Comment by rostag** [comment]
Зробив. Код валідації по маркеру виніс у окремий файл, таким чином, щоб його можна було використовувати з різних інших модулів, не дублюючи код валідації з регуляркою etc.: 
ValidationService.validateEmailByMarker( form.email, $scope.markers );

Ось як це працює:

![image](https://cloud.githubusercontent.com/assets/451410/8890819/3886a57e-3317-11e5-8be7-af7f1915efe6.png)

Можна перевірити тут: https://test.igov.org.ua/service/159

**Comment by bvv4ik** [comment]
При попытке сабмита такой формы - не дает это сделать, и пишет ошибку:
Error: a is undefined
this.validateEmailByMarker@https://test.igov.org.ua/app/4c857df8.app.js:1:21895
c.submit@https://test.igov.org.ua/app/4c857df8.app.js:2:630
pe.prototype.functionCall/<@https://test.igov.org.ua/app/4e0b3c0f.vendor.js:7:12801

**Comment by bvv4ik** [comment]
Для проверки удобно использовать:
https://test.igov.org.ua/service/670/general
Днепропетровск

даже при коректном вводе емейла и попытке сабмита выдает:
TypeError: Cannot read property '$name' of undefined
    at validateEmailByMarker (https://test.igov.org.ua/app/4c857df8.app.js:1:21940)
    at n.c.submit (https://test.igov.org.ua/app/4c857df8.app.js:2:632)
    at pe.functionCall (https://test.igov.org.ua/app/4e0b3c0f.vendor.js:7:12803)
    at ef.(anonymous function).compile.c.on.e (https://test.igov.org.ua/app/4e0b3c0f.vendor.js:7:19327)
    at n.$get.n.$eval (https://test.igov.org.ua/app/4e0b3c0f.vendor.js:6:3409)
    at n.$get.n.$apply (https://test.igov.org.ua/app/4e0b3c0f.vendor.js:6:3635)
    at HTMLButtonElement.<anonymous> (https://test.igov.org.ua/app/4e0b3c0f.vendor.js:7:19379)
    at HTMLButtonElement.ea.event.dispatch (https://test.igov.org.ua/app/4e0b3c0f.vendor.js:2:18972)
    at HTMLButtonElement.ea.event.add.q.handle (https://test.igov.org.ua/app/4e0b3c0f.vendor.js:2:15652)

**Comment by bvv4ik** [comment]
починил,
добавив проверку:
    if ( !markers || !emailCtrl ) {
      return;
    }

**Comment by rostag** [comment]
@bvv4ik - спасибо! Теперь нужно понять, в каких случаях emailCtrl оказывается undefined...

**Comment by rostag** [comment]
@bvv4ik - я зрозумів, чому там був undefined: тому що на формі поле для пошти має ім'я 'mail', а не 'email', і, звісно ж, не знаходиться. А це, у свою чергу викликано тим, що цей запит:

/api/process-form?url=https:%2F%2Ftest.region.igov.org.ua%2Fwf-region%2Fservice%2Fform%2Fform-data%3FprocessDefinitionId%3D_test_mailer:11:1747609

Повертає рез-т, де поле позначено як 'mail', і це, я думаю, не має так бути:

{"formKey":null,"deploymentId":"1747501","processDefinitionId":"_test_mailer:11:1747609","processDefinitionUrl":"https://test.region.igov.org.ua/wf-region/service/repository/process-definitions/_test_mailer:11:1747609","taskId":null,"taskUrl":null,"formProperties":[{"id":"mail","name":"mail","type":"string","value":null,"readable":true,"writable":true,"required":false,"datePattern":null,"enumValues":[]},{"id":"bankIdlastName","name":"Прізвище","type":"string","value":null,"readable":true,"writable":true,"required":true,"datePattern":null,"enumValues":[]},{"id":"bankIdfirstName","name":"Ім'я","type":"string","value":null,"readable":true,"writable":true,"required":true,"datePattern":null,"enumValues":[]},{"id":"bankIdmiddleName","name":"По-Батькові","type":"string","value":null,"readable":true,"writable":true,"required":true,"datePattern":null,"enumValues":[]}]}

Звісно, ми можемо зробити так, щоб скпирт обробляв і поле з іменем 'mail', але це не відповідає стандартному йменуванню мейл-поля.

**Comment by bvv4ik** [comment]
дело в том, что со временем элемент "markers" будет так-же браться из поля приходящей таски. И его будут формировать те-же самые Бизнесаналитики, которые будут и бизнеспроцесс писать... и там они уже и будут следить за тем, чтоб соответствовали ИД.

т.е. не будет у нас гарантированно одинаковых стандартных ИД. а будут у нас маркеры, которые будут идти "в комплекте" с полями своего БП. и таких валидаций у нас может быть еще миллион...(WIM-код автомобиля, например, серийный номер чего-то и т.д.)

потому важна унифицированость самой базовой структуры markers

**Comment by rostag** [comment]
@bvv4ik ясно: markers — це елемент, який задає типову поведінку іншим елементам, переліченим у масивах типу:
```json
{"validate":{ 
"PhoneUA": { "aField_ID":["privatePhone","workPhone"]}, 
"Mail": { "aField_ID":["privateMail"]
}}}

Дякую )

**Comment by bzhest** [comment]
Есть проблема с валидацией поля "Ваш контактный телефон", забиваю свой номер в формате 0632297637 - на этапе заполнения ошибки нет, ничего не подсвечивает, нажимаю "Замовити послугу" и уже после Сабмита сверху ошибку получаю - помилкаSYSTEM_ERR For input string: "063 229 7637"
+
Можно ли в рамках этой задачи добавить проверку на поле "Дата видачі довідки-рахунка:". Там можно будущую дату ставить, хотя по логике так не должно быть

**Comment by rostag** [comment]
@bzhest - зрозумів, зроблю.

**Comment by bvv4ik** [comment]
@rostag
прошу глянуть смежную таску(в ней, в т.ч. и вопросы по реализации этой):
https://github.com/e-government-ua/i/issues/634

@bzhest
"Можно ли в рамках этой задачи добавить проверку на поле "Дата видачі довідки-рахунка:""
не, это все отдельные задачи будут и не прямо сейчас а позже..

**Comment by rostag** [comment]
@bvv4ik - добре, роблю #634

**Comment by bzhest** [comment]
@rostag

**Comment by bzhest** [comment]
@rostag
"не, это все отдельные задачи будут и не прямо сейчас а позже.."
Для понимания, заводить ли мне сейчас отдельный кейс под проверку этого поля?

**Comment by bvv4ik** [comment]
@bzhest
Нет! прошу ни какие задачи не создавать! Все пожелания/предложения - в общий файл бэклога...
Валидаторы мы реализуем по мере их острой необходимости со стороны заказчиков/госорганов...

**Comment by smit-pb** [comment]
реализовано согласно постановке задачи.
