### ISSUE TITLE
На главном портале в документах, починить диалог открытия доступа к документу.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#544]
еще несколько дней назад работало.

Работает на бэте:
![image](https://cloud.githubusercontent.com/assets/4208821/8676316/6a718ab4-2a51-11e5-9024-b217a14ce6cc.png)

не работает на альфе:
![image](https://cloud.githubusercontent.com/assets/4208821/8676327/830d0bd4-2a51-11e5-9d65-e140b5205693.png)

**Comment by bvv4ik** [comment]
Для теста:
просто убедиться что диалог начал открываться

**Comment by poremchuk** [comment]
Сьогодні ввечері займаюсь цією проблемою!

**Comment by nazarenkod** [comment]
работает на альфе
![test egov docs](https://cloud.githubusercontent.com/assets/13256486/8719371/eeaf4f56-2bb3-11e5-896a-637eef226d35.jpg)

**Comment by bvv4ik** [comment]
@poremchuk уже таску решили,
прошу тогда сконцентрироваться на таске по валидации

**Comment by nazarenkod** [comment]
Есть требования по валидации?

**Comment by VadimGulich** [comment]
Подскажите , пож-ста, валидация будет реализована в рамках этой задачи или есть отдельная задача ?

**Comment by bvv4ik** [comment]
валидация, если мне память не изменяет, только по телефону реализована... остальное - не сейчас

**Comment by VadimGulich** [comment]
Ясно , тогда эту задачу закрываем

**Comment by bvv4ik** [comment]
заодно сделали и валидацию на оба поля и полностью починили как открытие доступа так и открытие дока по доступу

стоит окончательно проверить в разных комбинациях, чтоб можно было передать Дмитрию Александровичу для окончательной приемки

**Comment by VadimGulich** [comment]
ОТР не приходит на указанный номер 

1) Оберить тип документу    - выбрать
2) Оберить оператора     - выбрать
3) Введіть код доступу до документу       - ввести
4) Нажать "Знайти"
5) Открылось поле ввода пароля с SMS 
Ответ:
{"code":"SYSTEM_ERR","message":"Document Access password need - sent SMS"}
Ошибка:  Не приходит ОТР

---------------------------------------------------------
Исправте пож-ста  ошибку в слове
![image](https://cloud.githubusercontent.com/assets/12964120/8754210/8836b0da-2cca-11e5-9ea6-319295cb8ad6.png)

**Comment by bvv4ik** [comment]
не тестовом отсылка выключена специально)
там всегда пароль 4444

по очепятке - поправим, но это-бы кудато складировать в общий гуглофайл...

**Comment by VadimGulich** [comment]
понял , тогда все ок ) 
Очепятку перенесу в гугл док ))

**Comment by VadimGulich** [comment]
https://docs.google.com/spreadsheets/d/1Orx4JaKP-lSSVfY9569LZsAG9KgAuM-wKHWsA71D_Ow/edit#gid=1732799412

**Comment by bvv4ik** [comment]
А вот за перенос это в файл и ссылку - СПАСИБО!
(если удастся еще попереносить в это тфайл и остальные такие-же issue "с орфографическими ошибками", то совсем было-б все "в шоколаде")
