### ISSUE TITLE
Починить поддержку кирилицы, при загрузке файлов

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#546]
Аплоадинг происходит через сервис:
/file/upload_file_to_redis

ошибка кодировки где-то в:
AbstractModelTask.multipartFileToByteArray(file)

В самом методе:
	public static ByteArrayOutputStream multipartFileToByteArray(MultipartFile file)
уже пытался подбирать кодировку - не получилось...

в логах хорошо видно, что при всех попытках:
                String sFilename = new String(file.getOriginalFilename().getBytes(),"Cp1251");//UTF-8
                System.out.println("sFilename=" + sFilename);
                
                String sFilename1 = new String(file.getOriginalFilename().getBytes(Charset.forName("UTF-8")));//UTF-8
                System.out.println("sFilename1=" + sFilename1);
                String sFilename2 = new String(file.getOriginalFilename().getBytes(),"UTF-8");//UTF-8
                System.out.println("sFilename2=" + sFilename2);
                String sFilename3 = new String(file.getOriginalFilename().getBytes(Charset.forName("Cp1251")));//UTF-8
                System.out.println("sFilename3=" + sFilename3);
                String sFilename4 = new String(file.getOriginalFilename().getBytes());//UTF-8
                System.out.println("sFilename4=" + sFilename4);

- кодировка кривая.. то-ли она двойная происходит...

Логи на FTP можно смотреть тут:
Тест-альфа-регион: test.region.igov.org.ua 
протокол: sftp 
логин: sftpuser 
пароль: zaqxswcde

Проверять можно, при заполнении обычной услуги на главном портале (выбрать услугу "_test_mailer" в поиске, и город Днепропетровск)...

достаточно просто прикрепить файл и даже не сабмитить форму услуги, и тут-же глянуть в логи...

Можно и на региональном портале(дашборде), то так сложнее... выглядит там оно так:
![kirilica](https://cloud.githubusercontent.com/assets/11442397/8704156/f74fda02-2b29-11e5-947b-d2b4be31442b.JPG)

**Comment by bvv4ik** [comment]
Реализовано через приведение кирилицы в латиницу (т.к. в ряде случаем могут быть использованы украинские символы в названии, которые могут плохо восприниматься некоторыми оболочками файловой системы)

Для теста:
проверять нужно только через добавление новых файлов (старые так и останутся в кривой кодировке)

**Comment by NikitaLyah** [comment]
*Реализовано через приведение кирилицы в латиницу* - НЕ реализовано см. скриншот
![screenshot_1](https://cloud.githubusercontent.com/assets/12964328/8982956/a85f78ca-36ce-11e5-8ce4-e1b7f2c8861c.jpg) файлы названы на кирилице

**Comment by bvv4ik** [comment]
да, проблема... возвращено на доработку

**Comment by brunneng** [comment]
проблема с кодировкой вот в чем
имя файла передается в http хедере Content-Disposition
значения в хедере передаются только в кодировке US-ASCII
соответственно все неподдерживаемые символы превращяются в месиво
и восстановить их нельзя
http://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http
вот большой тред на эту тему
общая рекомендация - включать имя файла дополнительным параметром запроса

**Comment by uazure** [comment]
Ребят, напишите пожалуйста шаги для воспроизведения проблемы. Я правильно понял что это речь идет о подпроекте dashboard-js? Как там залогиниться? Вообще где живет информация о том, как тестировать? Обновите пожалуйста README с этой важной для каждого нового разработчика информацией.

**Comment by uazure** [comment]
Предлагается такой вариант фикса (в коммите перед этим сообщением). Браузер передает дополнительное поле под названием `originalFilename`, контентом которого является оригинальное имя файла. Я не знаю как тестировать, что получает джава бекенд, но код нод-бекенда видимо просто проксирует запрос как есть, добавляя лишь хедеры авторизации. Посему надеюсь что этого фикса достаточно.

**Comment by brunneng** [comment]
Был не прав насчет необходимости передачи имени файла в параметре / урле  запроса.
Фикс был возможен чисто на стороне джавы.

**Comment by bvv4ik** [comment]
Все работает, ура!
Я сам столько промучался с этим эпизодом, что не передать словами...
