### ISSUE TITLE
Рефакторинг полей типа date в модели

### ISSUE THREAD

**Issue by brunneng** [e-government-ua/i#547]
Во всех сущностях где надо хранить дату (со временем) вместо Timestamp использовать joda DateTime, а в базе хранить таймзону даты.

**Comment by brunneng** [comment]
Для теста, пожалуйста проверьте на интерфейсе что сценарии работы с SubjectMessage и Document работают как и раньше. Чисто теоретически могло поломаться.

**Comment by bvv4ik** [comment]
т.е.
1) зайти в профиль услуги, которая еще не реализована и отослать там email. в правой колонке, убедившись в фаербаге что ошибки в ответ нет
2) зайти и поработать в разделе Мои документы

**Comment by nazarenkod** [comment]
Фаербаг ошибок не показал.Так-же,при работе в разделе "Мои документы" все работает как и работало, фаербаг чистый.Закрываю.
