### ISSUE TITLE
Збереження сесії авторизації через BankId 

### ISSUE THREAD

**Issue by poremchuk** [e-government-ua/i#549]
Колеги, над дизайном проекту працювати вкрай важко, так як при любому перевантаженні(f5) елементів, що потребують авторизації приходиться перелогінитись в БанкАйДі.

Прошу реалізувати підтримку сесій.

**Comment by bvv4ik** [comment]
там не все так просто, т.к. сессия БанкИД живет всего 3 минуты (такое ограничение у самого БангкИД). Но в будущем, некоторый варианты кеширования все-же будут реализованы..
Правда, это будет более комплексная задача, нежели эта.
Потому, прошу закрыть таску (просто тяжело ориентироваться в тасках при наличии большого числа тасок формата "не забыть")
