### ISSUE TITLE
Использование АПИ ГитХаб-а чтоб отсылать email-сообщение(или даже viber/sms) сразу одной или нескольким командам ГитХаб-а

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#55]
может есть спецы?

**Comment by budnik** [comment]
Вы можете упомянуть разработчика чтобы ему пришла нотификация(как в твитере):
 /cc @bvv4ik
Или для этих целей каждый разработчик моежт сам подписываться этой штукой:
![selection_13 3013 3013 30](https://cloud.githubusercontent.com/assets/1160699/7157016/4087abee-e374-11e4-92d6-5678dccd3e2e.png)
В крайнем случаее можно расширить функционал бота из #57

**Comment by bvv4ik** [comment]
В том-то и дело, что каждый раз не будешь, чтоб кого-то проинформировать - прикреплять его к какой-то задаче... тут важно иметь возможность: "одним кликом написать просьбу всей Команде/дам ГитХаб-а", даже если нет задач ни каких... 

"В крайнем случае можно расширить функционал бота из #57"
Это конечно было-бы вообще здорово! т.к. тогда можно было-бы и каждого в приват проинформировать в Слак-е(кроме электронки)... нам важно создать общий инструмент более надежного и простого информирования коллег(их системной организации и синхронизации взаимного информирования о связанных событиях), причем не только в рамках каких-то задач, а в принципе по разным событиям... даже созданным вручную.
И желательно с возможностью учета присутствия коллег в определенных командах...
например оповестить все кооманды, кроме топ-менеджеров.. и т.д.
Или, завершилась задача, которая открывает возможность начать реализацию следующих трех задач, о чем автомат смог-бы проинформировать в их порталы команд, или даже персонально...

Ваш вариант со скриптом - отличная идея, которая позволит нам максимально гибко этим манипулировать. Надеюсь и дальше на Вашу поддержку в этом направлении!

**Comment by budnik** [comment]
[Хубот](hubot.github.com) достаточно гибкий для любого сценария использовани, можно прикрутить хоть СМС хоть Имейл. Но моё личное мнение состоит в том что для эфективной работы нужно ограничить количество каналов взамодействия. Лично мне даже чатик больше вреда чем пользы приносит, а вы говорите СМС. Более того разработчик должен сам решать как он хочет получать нотификации и когда. Не смотря на то что разработка ведётся на базе enterprise+waterfall стека, модель взаимодействия разработчиков будет отличатся от того что есть в ПриватБанке или другой крупной компании.

**Comment by budnik** [comment]
Используйте issue + team mentions:
https://github.com/blog/1121-introducing-team-mentions
не обязательно issue должны быть тасками

**Comment by bvv4ik** [comment]
Спасибо за ссылку - почитаю, поизучаю..

а по поводу "спама на коллег из комманды" - не беспокойтесь... и уж точно СМС-ки не будем слать)

этим инструментом конечно будем пользоваться очень осторожно, но пока егокак такогово нет, и невозможно, например, собрать оперативно в одно время, в одном месте, хотябы значительную часть комманды или нескольких команд..

Вообщем - Хубот, ИМХО, то что нам нужно...я обязательно еще покопаюсь в нем, чтоб лучше понять... как реализуете issue - сможем и на практике "пощупать"

**Comment by bvv4ik** [comment]
не смог найти возможность в Mileston-е отсылать коммент сразу всем участникам этой группы...
тем более с выбором сразу нескольких milestones

не возражаете если я эту задачу на Вас ассигну?

**Comment by budnik** [comment]
tl;dr;  milestone  -- не группа.

майлстоун это просто папочка с  кучкой issue, гитхабовский флоу предпологает что разработчики входят в команды и команы можно упомянуть в issue, тогда всем членам прийдет извещение почтой или ещё как в зависимости от настроек.

**Comment by bvv4ik** [comment]
я понимаю что не группа, но дефакто является неким обьединителем issue, чего нам как раз и нужно!

"команы можно упомянуть в issue, тогда всем членам прийдет извещение почтой или ещё как в зависимости от настроек."
нам важно лишь один раз, при создании задачи ассигнуть на группу (как это с milrstone получается), чтоб потом абсолютно все комменты и изменения попадали в нужную нам группу слак-а...


но ведь эта задача не проэто.
тнужно "легким движением руки", отослать 3-м группам, например одно и то-же сообщение...  которое уже и им на электронку придет и в слак(именно в эти три группы)

можете просто создать пример, а то я чето не вьеду)

**Comment by budnik** [comment]
Я понял ваш "кейс". У меня нет готового решения. Как вариант:
1. Создать группы разработчиков в github аналогичные комнатам\командам в slack
2. Вручную или ботом добавлять\удалять туда нужных разработчиков.

После этого можно в любом коменте гитхаба упомянуть такую команду, или неслколько команд и все получат нотификации!

**Comment by bvv4ik** [comment]
1. у нас как раз-то такие группы (комманды) уже созданы... они полностью соответствуют Milestone-с
2.вот только ботом вычитывать-бы их участников, чтоб рассылать в слак и на электронку нужный мессадж

**Comment by lem8r** [comment]
Можно на corezoid навернуть робота, который бы при получении веб-хука парсил сообщение и кидал его в зависимости от milestone в разные чаты
