### ISSUE TITLE
На главном портале кардинально переделать (в т.ч.рефакторить) механизм выбора Области и Города в профиле услуги

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#550]
Нужно кардинально переписать этот участок!

- [x] 1) Помимо самого рефакторинга, т.е. "сокрашения отдельных веток(в т.ч. html и js):
/i/dashboard-js/app/service/city,
/i/dashboard-js/app/service/region,
/i/dashboard-js/app/service/country,
(это вообще не должны быть отдельные ветки!)
Все это должно быть в единой унифицированной сущности, например: /service/place

Там сейчас происходит серьезная коллизия, когда одна услуга содержит региональные и городские подуслуги одновременно! (в aServiceData)
Получается, что:
- [x] 2) если первой в массиве попадается подуслуга в регионе, а вторая пусть даже и в городе, то второй не дает выбрать этот город, а перескакивает на следующий шаг сразу после выбора региона...
(была создана отдельная задача: https://github.com/e-government-ua/i/issues/443)

- [x] 3) если-же первой стоит подуслуга  в городе, а вторая в регионе, то второй требует таки ввести и город (хотя его там и не надо выбирать, т.к. она в регионе)
(была создана отдельная задача: https://github.com/e-government-ua/i/issues/540)

**Comment by uazure** [comment]
Давайте тут обсудим, как должно быть правильно.
Под правильно имеется в виду такой код, дальнейшая модификация которого не должна вызывать проблем. Код должен быть легко читаем и понятно назначение различных модулей.
Не должно быть более одного места с одинаковым кодом или разметкой. Если такие места есть - они должны быть выделены в отдельную сущность.

Я не полностью понимаю как работает то что есть, но у меня есть видение того, как это должно было бы быть.
Выбор региона осуществляется через ангуляровский сервис. Задача сервиса - предоставлять контроллерам информацию о том, какой регион или город выбрал пользователь, и позволять контроллерам обновлять эту информацию в сервисе. Сервис делает броадкаст сообщения при изменении своего состояния, что позволяет подписчикам (контроллерам/директивам) запросить у сервиса актуальные данные.
Сервис может инициализироваться из данных урл, если в нем указаны регион\город. Сервис может запоминать в localStorage (или sessionStorage - как договоримся) выбранный город.

Пользователями сервиса должны являться директивы, которые позволяют выбирать регион\город и любые контроллеры, которым нужно знать регион\город.

**Comment by rostag** [comment]
@uazure - згоден з запропонованим сервісом angularjs. Я також не повністю розумію, як саме це працює зараз. Тому @bvv4ik, буде дуже корисно мати *перелік тест-кейсів*, як формальних, так і простих покрокових для юзера. Можете з цим допомогти? Таким чином, будемо перевіряти функціонал до і після рефакторингу.

**Comment by bvv4ik** [comment]
Да, коллеги, может таки поборим эту тему наконец!

По сути должны быть такие тесткейсы:
1) Услуга где есть только города - позволяет выбрать область, потом дает выбрать город и переходит на шаг 2
2) Услуга где есть только области - позволяет выбрать область,  и переходит на шаг 2
3) Услуга где есть города, идущие вначале и области - позволяет выбрать область, потом, если по данной области есть еще и города дает выбрать город и переходит на шаг 2, если города по области нет - сразу переходит на шаг 2
4) Услуга где есть области, идущие вначале и города - позволяет выбрать область, потом, если по данной области есть еще и города дает выбрать город и переходит на шаг 2, если города по области нет - сразу переходит на шаг 2
5) Услуга где нет ни областей ни городов (уровень страны) - сразу переходит на шаг 2

если все эти кейсы отрабатываются корректно - все гуд

ВАЖНО:
В проекте есть файл ServiceData.csv - именно на базе его данных при заходе в услугу определяется - в каких городах/регионах она есть...

там в колонках nID_City и nID_Region как раз и определяется привязка к региону или городу... или стране (если оба налл)

а в колонке nID_Service - ИД услуги

т.е. по нему можно подобрать реальные услуги под описанные выше тест-кейсы...

**Comment by VadymVolos** [comment]
О! Какая классная тема!
Вы уже решили как правильно? У меня есть идеи.

Можно сделать как в интернет магазинах, там есть фильтр, можно фильтровать по брендам, можно по товарам, можно по цвету. Вообщем у нас можно сделать аналогично. Можно отсортировать по ОДА например

> [Харьковская ОДА](http://kharkivoda.gov.ua/pro-oblast/43126) (всего заказано услуг 0, в процессе выполнения 0, уже работающих 0)
>> [Города:](http://kharkivoda.demowww.com/pro-oblast/administratyvno-terytorialnyy-ustriy/mista)
>>> город Харьков (всего заказано 0, в процессе выполнения 0, уже работающих 0)
>>> город Ізюм (всего заказано 0, в процессе выполнения 0, уже работающих 0)
>>> город 3
>>> город 4

>> [Районы:](http://kharkivoda.demowww.com/pro-oblast/administratyvno-terytorialnyy-ustriy/rayony)
>>> Балаклійський район (всего заказано 0, в процессе выполнения 0, уже работающих 0)
>>> Харківський район (всего заказано 0, в процессе выполнения 0, уже работающих 0)
>>> район 3
>>> район 4

И далее с другими ОДА аналогично.

**Comment by rostag** [comment]
@bvv4ik - дякую за тест-кейси, це дуже спроситить нам життя.
@VadymVolos - гарні ідеї, я думаю, їх буде легше втілити одразу після того, як зробимо цей важливий рефакторинг. Зможу взятися за це після свого поточного таску по валідаторах, якщо раніше не візьметься хтось інший :wink:

**Comment by VadymVolos** [comment]
Ок :) @bvv4ik помоги пожалуйста, перенеси мои идеи куда считаешь будет правильным.

**Comment by bvv4ik** [comment]
@VadymVolos все идеи в бэклог... ссылка на файлец тут фигурировал в комментах ко многим таскам
@rostag Спасибо за такую активность! Правда, валидаторы сейчас важнее...

**Comment by rostag** [comment]
@bvv4ik - так, валідатори зараз -- це мій пріоритет номер один, сьогодні завершую їх.

**Comment by rostag** [comment]
Беруся за цей таск.

**Comment by rostag** [comment]
Важливо: використати поновлений бек з #608

**Comment by bvv4ik** [comment]
не совсем #608
а там другая таска по Places
но ждать ее полного завершения не стоит... оптимизировать можно/нужно уже и без этого

**Comment by VadymVolos** [comment]
А сюда фидбек можно писать по поводу фильтра по областям?
посмотрел фильтр, с точки зрения юзабилити
было бы хорошо чем меньше кликов тем лучше
напрягает чтоб посмотреть нужно разорачивать, нужно как то упростить
И также было бы класно если б возле каждой области было две цифры написано (кількість доступних/кількість які скоро будуть), наприклад:

Волинська (5/2)
Вінницька (8/4)

На данный момент нужно развернуть список областей, потом страница перезагружается и под фильтром отбражается сколько одступно и сколько будет скоро

Но можно сократить, и сразу в том списке виводить эти цифри

**Comment by bvv4ik** [comment]
очень прошу все предложения в бэклог, или когда создадим отдельный репозиторий - туда...
тут ведется только разработка и исправление ошибок

**Comment by VadymVolos** [comment]
Ок. Я думал, выводить цифры возле названия областей это же разработка?
Волинська (5/2)
Вінницька (8/4)

PS1. Я пока не понимаю где грань между разработкой и предложениями по разработке.
PS2. Давайте создадим репозиторий, так как файл беклога в гугл докс напоминает свалку
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit#

**Comment by rostag** [comment]
Учора змерджив результат першого етапу рефакторингу (злиття трьох гілок коду: service/country, service/region, service/city у одну - service/place), здається нічого великого не зламалось,  https://github.com/e-government-ua/i/pull/848

У реалізації максимально врахував архітерктурні моменти, викладені у коменті @uazure ( https://github.com/e-government-ua/i/issues/550#issuecomment-128641486 )

Приступаю до другого етапу - власне перехід на нову бек-сутність Place, яка описана у #573 

@bvv4ik — вірно щодо другого етапу?

**Comment by OlgaTurenko** [comment]
@rostag  Добрый день! Подскажите, пожалуйста, а что у нас этой задачкой? Получилось сделать 2 и 3 этапы? :)

**Comment by rostag** [comment]
Еще делаю )

**Comment by bvv4ik** [comment]
та не,  не скромничай - эту-т отаску тв давно сделал)

а вот ее продолжение теперь тут:
https://github.com/e-government-ua/i/issues/924

эту можно закрывать
