### ISSUE TITLE
Наполнить новую колонку sID_UA, сущностей Region и City - данными

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#551]
данные хранятся в соответствующих *.csv

Города:
https://docs.google.com/spreadsheets/d/1GNA50FsRN0od3PIRc_Kd108DIQId9zLq3UZE3lKhovs/edit#gid=0

Регионы:
nID;sName;sID_UA
1;Дніпропетровська;"1200000000"
2;Львівська;"4600000000"
3;Івано-Франківська;"2600000000"
5;Київ;"8000000000"
6;Херсонська;"6500000000"
7;Рівненська;"5600000000"
8;Волинська;"700000000"
9;Тернопільська;"6100000000"
10;Автономна Республіка Крим;"100000000"
11;Вінницька;"500000000"
12;Донецька;"1400000000"
13;Житомирська;"1800000000"
14;Закарпатська;"2100000000"
15;Запорізька;"2321281200"
16;Київська;"3200000000"
17;Кіровоградська;"3500000000"
18;Луганська;"4400000000"
19;м. Севастополь, міськрада;"8500000000"
20;Миколаївська;"4800000000"
21;Одеська;"5100000000"
22;Полтавська;"5300000000"
23;Сумська;"5900000000"
24;Харківська;"6300000000"
25;Хмельницька;"6800000000"
26;Черкаська;"7100000000"
27;Чернівецька;"7300000000"
28;Чернігівська;"7400000000"

**Comment by LamronNu** [comment]
для теста:
https://test.igov.org.ua/wf-central/service/services/getPlaces
убедиться, что в списке мест поле sID_UA заполнено и корректно.

**Comment by nazarenkod** [comment]
Поле sID_UA заполнено и корректно

**Comment by bvv4ik** [comment]
тогда таску можно закрывать?

**Comment by nazarenkod** [comment]
Смело

**Comment by bvv4ik** [comment]
ну так, а тогда - чего ждем?)
по текущей схеме тестировщики, по успешному завершению тестов - закрывают задачу
