### ISSUE TITLE
S3 Ошибка открытия доступа к файлам 

### ISSUE THREAD

**Issue by VadimGulich** [e-government-ua/i#552]
Ошибка: Не отображается код для предоставления доступа к файлу
Сервер: https://test.igov.org.ua
Меню:  Документы - Предоставление доступа к документам

Описание:
1) Открыть форму предоставления доступа
2) Заполнить  поля:
  - Имя Фамилия
  - Выбрать любой период
  - Ввести номер телефона (или выбрать "нет")
  - Поле ввода почты НЕ заполнять
3) Нажать "Отримати код"
Скрин:
![image](https://cloud.githubusercontent.com/assets/12964120/8734515/2eb2407c-2c13-11e5-8370-4a0a3b5c4d7e.png)

Ожидаемый результат: Отображается код (так как почта не обязат. поле)

**Comment by bvv4ik** [comment]
уже все работает, можно перепроверять

**Comment by VadimGulich** [comment]
исправлено
