### ISSUE TITLE
На главном портале устранить замечания в запускаемом подразделе "Поиск документов"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#553]
https://docs.google.com/document/d/14pOMoXUw1nGMV-Or39b7-ZXzbsAywwyPepxqr-CTiBA/edit

**Comment by bvv4ik** [comment]
Оставшиеся два пункта дополнены и перенесены в отдельные таски:
https://github.com/e-government-ua/i/issues/321 (Добавить документ)
https://github.com/e-government-ua/i/issues/586 (отображение вкладки Мои документы)

Остальное можно проверять!

**Comment by smit-pb** [comment]
Все что в задаче описано - исправлено.
