### ISSUE TITLE
S 5 Ошибка в слове 

### ISSUE THREAD

**Issue by VadimGulich** [e-government-ua/i#554]
Сервер:https://test.igov.org.ua/
Меню: Поиск - Выбрать установу

Скрин:
![image](https://cloud.githubusercontent.com/assets/12964120/8741877/e33f0698-2c67-11e5-882d-e5060116fc38.png)
Ожидаемый результат: Міністерство

**Comment by bvv4ik** [comment]
Павел, как будет время поправь плиз

@VadimGulich очень прошу в осередной раз - не засоряйте такими мелкими тасками пул задач issue в гитхабе! Создайте наконец один гуглофайл, и там записывайте все такие мелочи... т.к. очень трудно ориентироваться в реальных задачах гитхаба, когда они "тонут" в таких... Гитхаб для действительно неотложных или тех задач, которую человеку можно ассайнуть для реализации на день или больше... все остальное - пишите пожалуйста в отдельном общем файле

**Comment by VadimGulich** [comment]
Файл есть https://docs.google.com/spreadsheets/d/1Orx4JaKP-lSSVfY9569LZsAG9KgAuM-wKHWsA71D_Ow/edit#gid=1732799412

ок, задачи от S1 до S3 заводим  в гитхаб , S4-S5 в этот файл.

**Comment by bvv4ik** [comment]
спасибо, так Вы перенесете эту таску туда и закроете ее тут?

**Comment by VadimGulich** [comment]
Да, так и сделал))
