### ISSUE TITLE
В личном кабинете сделать возможность спрятать все персональные данные за звездочки

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/i#555]
В личном кабинете сделать возможность спрятать все персональные данные за звездочки
(для какой группы относиться эта задача не знаю, перенесите пожалуйста в нужную).

Стоит задача делать видеоинструкции для каждой из услуг. Чтоб люди могли делать видео, нужно чтоб они могли скрыть свои персональные данные в личном кабинете портала. Личном кабинете и для чиновников и в личном кабинете обычного пользователя.

-========
Ірина Кельнер:
Добрий день. Хто вміє робити навчальні відео по роботі з порталом? Треба відеоінструкцію як для користувачів послуги, так і для органів які надають послугу. Бажано по кожній послузі.
https://www.facebook.com/groups/458833010941504/permalink/486928944798577/
-========

**Comment by bvv4ik** [comment]
в соответствующую команду добавил...
а кто ставил задачу делать видео-инструкции?

**Comment by VadymVolos** [comment]
Ирина задачу поставила, точнее попросила помочь ее решить
на ГитХабе данной задачи по видео нет, там масса видео нужно.

Нужно найти желающих и будем обучать их как записывать видео.
Также нужно программу для Винды бесплатную подобрать для записи экрана.

**Comment by VadymVolos** [comment]
Я не знаю как будет лучше по поводу звездочек, давайте тут обсудим.
Возможно вместо звездочек, тестовые аккаунты для каждой услуги создать?

Чтоб человек мог зайти, посмотреть как внутри все работает (демо аккаунт)
отправить демо заявку, получить демо ответ.

Что думаете?

**Comment by bvv4ik** [comment]
не, аккаунты - не вариант... роли цеплять нужно на существующую сущность Subject, по которой идентифицируется человек, например сейчас через ИНН (и др. идентификаторы)

**Comment by bvv4ik** [comment]
сегодня было расширенное совещание, и приняли решение, что нет необходимости специально реализовывать такой функционал, т.к. скрытие подобных данных легко осуществляется массой инструментов.
может быть, как нибудь потом...

!!! Зато удалось утвердить возврат комментариев! (но уже не на этой деплоящейся версии)

**Comment by VadymVolos** [comment]
Комментарии это хорошо:) Только нужно их правильно организовать. 
@bvv4ik а где у нас обсуждение по поводу комментариев? Я хочу поучаствовать.

**Comment by VadymVolos** [comment]
" т.к. скрытие подобных данных легко осуществляется массой инструментов."
Дайте пожалуйста эти инструменты которых масса, и расскажите как ими пользоваться.
