### ISSUE TITLE
На бэке централа добавить в сущность DocumentType булевое поле bHidden, и реализовать работу с ним

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#556]
в т.ч.:
- модифицировать сервис getDocumentTypes:
в котором если будет true в таком поле, то при - пропускать такие типы при формировании и отдаче массива
- доработать сервис-сеттер
- в табличке с данными (csv) - во всех типах проставить значение false

П.С.: Нечно подобное реализовано в сервисе getServices

**Comment by LamronNu** [comment]
для теста:
добавить новый тип с параметром bHidden=true, и убедиться, что получить его по нИд можно, но увидеть в списке всех типов -- нет.

документация поправлена тоже: https://github.com/e-government-ua/i/blob/test/docs/specification.md#9_workWithDocuments, раздел "типы документов"

**Comment by NikitaLyah** [comment]
Просьба написать детально и пошагово как проверить данную задачу, т.к не все владеют данными терминами и не так хорошо знают проект @bvv4ik  @LamronNu

**Comment by LamronNu** [comment]
1) в документации найти раздел "типы документов", прочитать и разобраться с методами
2) под "добавить" имеется ввиду метод setDocumentType, "получить" -- getDocumentType, "список всех типов" -- getDocumentTypes
3) для авторизации сервисов потребуется логин-пароль, посмотреть его можно тут: https://github.com/e-government-ua/i/wiki/%D0%9D%D0%B0%D1%88%D0%B5-%D1%85%D0%BE%D0%B7%D1%8F%D0%B9%D1%81%D1%82%D0%B2%D0%BE

**Comment by VadimGulich** [comment]
Работает согласно  описанию
