### ISSUE TITLE
Добавьте LICENSE файл

### ISSUE THREAD

**Issue by dmakhno** [e-government-ua/i#557]
Не смог найти под какой лицензией ведется разработка.
Но зайдя с главного сайта (igov.org.ua) на `Знайшли помилку або баг на Порталі?`
Попал на форму подписанную:
"Эта форма созданна внутри ПриватБанка"
![image](https://cloud.githubusercontent.com/assets/1913863/8747428/aa72d0b8-2c9b-11e5-9ccd-3c758b33e707.png)

Это настораживает в отсутствии явно лицензии, кем будет использован труд или персональные данные.

**Comment by bvv4ik** [comment]
Дмитрий Александрович, что скажете?

**Comment by bvv4ik** [comment]
Просьба перенести эту issue в бэклог и закрыть ее:
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit
