### ISSUE TITLE
Графическое полное описание всей схемы проекта в инструменте https://www.gliffy.com

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#56]
- [ ] 1) место и роль каждой подпапки репозитория "i" (wf-base, central-js, wf-central, wf-region, dashboard-js, portal-php(хоть и отживает свое, но это тоже стоит обозначить), storage*(key-value-хранилища Редис и Монго), auth*(пока в разработке но на вики есть планируемая схема)...)
- [ ] 2) размещение существующих серверов (пока они на Амазоне, в вики есть и их список и схема деплоев)
- [ ] 3) размещения там-же уже существующих схем по Авторизации (БанкИД(в т.ч.ЭЦП),BasicAuth(в т.ч.sID_Access)) (покопаться нужно на вики)
- [ ] 4) приблизительные наметки будущего места существующей части проекта в контексте всего igov.org.ua (это вынесение копий региональных серверов на собственное железо, например министерств или др.госорганов). Другие репозитории на уровне репозитория "i"
- [ ] 5) полная схема "конвейера процесса разработки" в проекте... от поступления задачи, до локальной разработки, локального тестирования, общего тестирования и передачи для теста тестерам(которые принимают и закрывают таску)
- [ ] 6) полная схема тестирования (согласовать с Сычем Антоном)

**Comment by alesgood** [comment]
Взяла задачу в работу.

**Comment by alesgood** [comment]
Роль и описание корневых папок репозитория
http://www.gliffy.com/go/publish/7808301

![folder_repository](https://cloud.githubusercontent.com/assets/11561028/7169325/0ea2ef22-e3cd-11e4-991d-42daaf0549a0.png)

**Comment by bvv4ik** [comment]
это хорошо, теперь важно увязать эту новую схему с остальными...
кстати, нужно сразу учесть, что wf-dniprorada, чуть позже будет вынесена "за скобки, в другой репозиторий", как и остальные рады.... и вот они все будут собираться на основе единого ядра wf-base

и стоит както показать что оба портала - это по сути одно и то-же, только на разнвх языках написаны... и в конечном итоге они вольются в dashboard-js
както так

**Comment by bvv4ik** [comment]
дописал еще последний пункт:
- полная схема "конвейера процесса разработки" в проекте... от клиента-бизнесаналитика-системного аналитика-групп разработчиков-тестировщиков и приемщиков...

**Comment by bvv4ik** [comment]
@HelenAnalis Елена, как там успехи, движется дело?)
