### ISSUE TITLE
На дашборде реализовать раздел "Звіт"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#560]
При нажатии кнопки "Сформувати файл" - предлагать сохранять файл, используя готовій сервис:
https://test.region.igov.org.ua/wf-region/service/rest/file/download_bp_timing?sID_BP_Name=lviv_mvk-1&sDateAt=2015-06-28&sDateTo=2015-07-01
Который написан по задаче: https://github.com/e-government-ua/i/issues/313, и АПИ которого описано на нашей Вики.
(фактически нужно будет просто туда подставлять параметры из полей интерфейса)

![image](https://cloud.githubusercontent.com/assets/4208821/8758441/efd277ac-2cec-11e5-9a86-ef46b8009072.png)

Условия:
- Вкладку отображать пользователям с ролью руководителя  - mngr
- Задавать период отчета и услугу (БП, например: "Название БП (lviv_mvk-1)").
- В список  услуг должны попасть те процессы, к которым у этого пользователя есть доступ
(в каждом БП и его этапе прописана группа, к которой он относится)
- Доступ определяется по принадлежностям к тем или иным группам в активити, и есть в стандартном описании: http://www.activiti.org/userguide/#_groups
15.15.2. Get a list of groups
GET identity/groups).

**Comment by bvv4ik** [comment]
Реализовано пока без комбобокса, а через поле input
Этот функционал будет реализован отдельной задачей по реализации: https://github.com/e-government-ua/i/issues/570

**Comment by smit-pb** [comment]
1) Раздел называется не "Звіт" а "Звіти"
2) На мокапе присутствует выпадающий список "Послуга" - фактически в функционале этого нет.
3) При экспорте - сохраняется в файле с расширением "Имя.dat"
4) Если сохранить статистику - то загружается Эксель фаил и в место нормального названия колонок - колонки проименованы на Английском языке - и названия колонок вписаны одной стракой в первую ячейку. (Assignee,"Start Time","Duration in millis","Duration in hours","Name of Task"
)

Все выше перечисленное - так и должно работать ? (т.к. описание всем 4 пунктам я так и не нашел).

**Comment by bvv4ik** [comment]
1. все норм, там уже сейчас именно звиты)
2. выше в комменте написано по этому поводу. будет реализовано отдельной таской.
3. так и должно быть
4. сам контент возвращает другой сервис, который был написан на много раньше.. и пока там все норм.
