### ISSUE TITLE
На дашборде реализовать возможность сортировки заявок

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#561]
Реализовать возможность сортировать заявки по дате и времени поступления в любом из разделов (в роботі / необроблені / оброблені)
За датою:
- Від найдавніших
- Від найновіших

![image](https://cloud.githubusercontent.com/assets/4208821/8758653/0cfd97ec-2cef-11e5-95bc-bfa38d7ddcee.png)

**Comment by dn190187kaj** [comment]
Сортировка заявок:
в роботі - работает;
необроблені - работает;
оброблені - НЕ РАБОТАЕТ.

Шаги:
1. Захожу в админку.
2. Выбираю заявки - Оброблені.
3. Выбираю фильтр Від найдавніших (сделал скриншот - test 1).
4. Выбираю фильтр Від найновіших (сделал скриншот - test 2)
Полученный результат:
Заявки не сортируются. Вверху всегда заявка #1000331.

Так же:
а) время в заявках в "оброблені" отображается как NAN-NAN-NAN-NAN-NAN-NAN;
б) работая с заявками в меню "оброблені" было выделение меню "НЕоброблені"
Отобразил это в скриншоте test 3. 
![test 1](https://cloud.githubusercontent.com/assets/13554482/9039019/2d4aa818-3a01-11e5-9f0c-1304e373d355.jpg)
![test 2](https://cloud.githubusercontent.com/assets/13554482/9039020/2d4abeca-3a01-11e5-80f2-199518739c7b.jpg)
![test 3](https://cloud.githubusercontent.com/assets/13554482/9039021/2d626a34-3a01-11e5-8f71-dbf8c895add0.jpg)

**Comment by coolvision** [comment]
похоже что на test.igov.org.ua для "обработанных" и "необработанных" заявок просто не задано время создания, поэтому и сортировка не работает.
т.е. это неправильные данные в базе, а не баг.
для тестирования стоит сначала создать несколько новых заявок, с временем.

**Comment by coolvision** [comment]
а вот подсветку меню надо подправить

**Comment by dn190187kaj** [comment]
попробовал сам заявку создать #2087555, обработал ее, но время в ней в обработанных, все равно NAN. Подсказать можете как создать несколько новых "обработанных" заявок, с временем.

**Comment by bvv4ik** [comment]
раздел "отработанные", и правда - пока изрядно не доделан

**Comment by dn190187kaj** [comment]
Пока снимать "тест" ?

**Comment by bvv4ik** [comment]
не, если в остальных разделах все норм, то все норм...
раздел с отработанными - будем делать отдельно и основательно

**Comment by dn190187kaj** [comment]
в остальных норм. Закрываю.
