### ISSUE TITLE
На дашборде, в разделе "Оброблені", убрать кнопку "Опрацювати"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#562]
Раздел предполагает возможность просмотра заявок, которые уже были обработаны  пользователем. Следовательно:
- никаких активных полей для ввода, выпадающих списков или кнопок “Оправцювати” здесь быть не должно. 
- Кнопку печати нужно оставить активной. (безусловно)
 
![image](https://cloud.githubusercontent.com/assets/4208821/8758675/4b1016d6-2cef-11e5-8956-f1ad48c0b172.png)

**Comment by Polsha** [comment]
Можно уточнить Вы пишете, что никаких активных полей для ввода, выпадающих списков или кнопок “Оправцювати” здесь быть не должно. Но у Вас на макете поле "Рiшення про надання послуги" с выпадающим списком.

**Comment by kurbpa** [comment]
@Polsha 
Это скрин того как есть "Сейчас"(проявление дефекта), а не того как "должно быть".

**Comment by Polsha** [comment]
1. логинимся как админ https://test.region.igov.org.ua:6948/
2. Заходим в раздел Обробленi
3. Выбираем заяву #1002659

ожидаемый результат - никаких активных полей для ввода, выпадающих списков быть не должно 
фактический результат -  поле с выпадающим списком "Рішення про надання послуги" - активное
![3](https://cloud.githubusercontent.com/assets/13255104/8793682/1a9ac406-2f83-11e5-800c-3f1588a41f68.jpg)

**Comment by Polsha** [comment]
и еще есть типы заявок с дополнительными активными полями  

1.логинимся как админ https://test.region.igov.org.ua:6948/

2.Заходим в раздел Обробленi
3.Выбираем заявку #1042736

![4](https://cloud.githubusercontent.com/assets/13255104/8793737/c2eef3ca-2f83-11e5-8043-c9cb6454fd57.jpg)

3.Выбираем заявку #1097655
![6](https://cloud.githubusercontent.com/assets/13255104/8793773/ff24727a-2f83-11e5-97d6-1a6c3beec13b.jpg)

3.Выбираем заявку #1030171
![5](https://cloud.githubusercontent.com/assets/13255104/8793804/5a9ecec0-2f84-11e5-8c0a-5a5d89e97e84.jpg)

**Comment by smit-pb** [comment]
Подтверждаю. На пример для таски №760527 - 32 поля доступно для редактирования.

**Comment by bvv4ik** [comment]
поправлено

**Comment by VadimGulich** [comment]
Ошибка исправлена!

**Comment by Polsha** [comment]
![5](https://cloud.githubusercontent.com/assets/13255104/8793882/6aa114da-2f85-11e5-99d3-b2aae81a7a00.jpg)
так а что по поводу  этого?

**Comment by bvv4ik** [comment]
"так а что по поводу этого?"
раздел "Оброблено" - еще не завершен полностью... этим занимаются. к данной задаче это не относится
