### ISSUE TITLE
На дашборде, после нажатия на “Взять в роботу” - отображать 2 кнопки а не одну.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#563]
Сейчас, после нажатия на “Взять в роботу” отображается информационное окно с единственной кнопкой “ОК”.
А нужно - отображать 2 кнопки:
●	для перехода к взятой только что в работу заявке 
●	для возврата к списку необработанных

 
![image](https://cloud.githubusercontent.com/assets/4208821/8758700/c8a26e82-2cef-11e5-9d19-afdffcbf60c2.png)

**Comment by Kamilius** [comment]
@bvv4ik готово

**Comment by bvv4ik** [comment]
Отлично)
для теста:
в дашборде взять в работу любую таску

**Comment by Polsha** [comment]
таска выполнена, только кнопки поменяны местами.

**Comment by Kamilius** [comment]
@Polsha поправив

**Comment by Polsha** [comment]
и еще это уже мелочь, но на всякий случай 
![default](https://cloud.githubusercontent.com/assets/13255104/8771890/19734b48-2ecf-11e5-92e4-2a949b832547.jpg)

**Comment by Kamilius** [comment]
@Polsha Поправив, після наступного деплою має бути доступним

**Comment by Polsha** [comment]
"у" на "в" не поменялось
![issue_4](https://cloud.githubusercontent.com/assets/13255104/8793572/93b64fa6-2f81-11e5-860e-b02ff3b60830.jpg)

**Comment by bvv4ik** [comment]
похоже что тут на макете ошибка а не в реализации...

**Comment by Polsha** [comment]
функция отображать 2 кнопки а не одну - реализована, Если надписи на кнопках Вас устраивают, я закрываю issue

**Comment by kurbpa** [comment]
@bvv4ik 
@Polsha 
Есть проблема.
После нажатия на "Почати опрацювання задачі", пользователь будет перенаправлен на текущую задачу в разделе "В роботі" (задача будет уже выбрана в левой части с перечнем задач). Но правая часть с содержимым при этом не обновляется. На ней  всё также присутствует кнопка "Взять в работу" и всё так же неактивны все поля необходимые для заполнению чиновнику.

**Comment by bvv4ik** [comment]
@Kamilius подтверждаю, глюк таки действительно есть, просьба поправить

**Comment by VadimGulich** [comment]
Баг исправили и ждет исправления?

**Comment by VadimGulich** [comment]
исправлено ранее
