### ISSUE TITLE
На дащборде переделать страницу авторизации (дизайн)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#564]
- [x] Форму для ввода логина и пароля расположить сразу на главной странице (сейчас надо нажимать малозаметную ссылку Увійти), иначе приходится КАЖДОМУ новому участнику нашей команды объяснять, как авторизоваться.
- [x] Поля для ввода логина/пароля сделать короче.
- [x] Самому порталу дашборда необходимо дать название "портал обробки звернень громодян" (вместо: “Електронний портал”, которое ни о чем не говорит)
 
![image](https://cloud.githubusercontent.com/assets/4208821/8758731/4c658560-2cf0-11e5-90e6-a8ec106bfab1.png)

**Comment by Kamilius** [comment]
Цей візьму на себе :)

**Comment by Kamilius** [comment]
Готово https://github.com/e-government-ua/i/pull/580/commits

**Comment by Polsha** [comment]
Кнопака "Увiйти" имеет разный цвет в разных браузерах Chrome 43 #DDDDDD, FF 39 #FOFOFO,  IE 9 #FOFOFO

**Comment by Polsha** [comment]
на макете и в реале кнопка "Увiйти" отличается по цвету, на данный момент мы это не тестим?

**Comment by Kamilius** [comment]
Я гадаю, що не варто, оскільки на скільки я знаю - в нас немає "Design guideline"a

**Comment by Polsha** [comment]
проверено в Chrome 43, FF 39, IE 9
