### ISSUE TITLE
На дашборде подкрашивать в списке задач каждую из них цветом

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#565]
если название юзертаски заканчивается на:
"_red" - подкрашивать строку - красным цветом (класс: "bg_red")
"_yellow" - подкрашивать строку - желтым цветом (класс: "bg_yellow")
"_green" - подкрашивать строку - зеленым цветом (класс: "bg_green")
"usertask1" - подкрашивать строку - салатовым цветом (класс: "bg_first")

Необходимо для  лучшей визуализации  етапов и критичности  обработки заявки. 

![image](https://cloud.githubusercontent.com/assets/4208821/8758771/c5bfe716-2cf0-11e5-828e-3a8e1826de55.png)

**Comment by kurbpa** [comment]
"если название юзертаски заканчивается на:"
смущает то что название таски я всегда осмысленным делаю для последующего отображения в дашборде.
доп. цифры  могут очень смущать.

**Comment by bvv4ik** [comment]
их видно не будет)

**Comment by bvv4ik** [comment]
Пример цветов:
![image](https://cloud.githubusercontent.com/assets/4208821/8768149/47a007be-2e7e-11e5-8530-3a145e49e95b.png)

**Comment by Polsha** [comment]
Не понятно в каких случаях передается класс bg_

**Comment by bvv4ik** [comment]
ни в каких)

**Comment by Polsha** [comment]
то есть эта таска не реализована и мне проверять ее никак?

**Comment by bvv4ik** [comment]
"если название юзертаски заканчивается на:"
можно просто глянуть на ИД таски и сопоставить с условиями этой задачи...

вообщем - все работает)
