### ISSUE TITLE
Использование API GitHub-а и Slak-а чтоб комментарии по Issue, в соответствующих Milestones GitHub-а, попадали в соответствующие каналы комманд

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#57]
Нужен настоящий профи!

**Comment by budnik** [comment]
Думаю для таких задач хорошо подойдет гитхабовский [hubot](github/hubot). Сейчас попробую набросать скрипт по вашим требованиям. Потом можем его задеплоить на heroku.

**Comment by bvv4ik** [comment]
Супер, спасибо.
Был-бы Вам благодарен, если-б Вы решили этот очень важный для нас вопрос!
очень буду ждать развития...

**Comment by bvv4ik** [comment]
а Вам не сложно и подключиться на канал комманды в слак-е:
https://e-government-ua.slack.com/messages/_org_git-btrack-rules/

П.С.: чтоб наши коллеги знали "героев нашего времени" поближе)

**Comment by budnik** [comment]
[Cделал](https://github.com/budnik/hubot-github-repo-event-notifier/commit/393e3e152fba55bd9aa9b62a4e7de433fce2c7bf), вчером после работы планирую написать инстркуцию как это задеплоить и использовать. Я не могу понять как мне подключиться к команде на слаке. И мне нужна будет помощь администратора слака чтобы включить бота.

**Comment by bvv4ik** [comment]
Класс!
Скажите плиз Ваш логин в Слак-е - я пришлю Вам инвайт для него и конкретно канала этой команды: https://e-government-ua.slack.com/messages/_org_git-btrack-rules/

Как только Вам нужно будет чтото поадминить в Слаке - обращайтесь ко мне лично (в слаке @bvv4ik или скайп: belyavtsevw), или к Великотскому Вячеславу (слак: @admiral-driver)(просто сошлитесь на эту задачу - он поможет!)

**Comment by budnik** [comment]
Насколько я понимаю логин в слаке уникальный только внутри команды, т.е. в каждой команде может быть свой пользователь `bvv4ik` или `budnik`  Думаю вы можете добавить меня по моему email:
dmitriy.budnik@gmail.com

**Comment by bvv4ik** [comment]
нет, на весь Слак у Вам может быть только один логин заведенный, который привязан к этому Вашему электронному адресу...

только что глянул - Слак сказал что Ваш электронный адрес уже зареген у нас в i.gov домене Слак-а...

мне нужно было знать именно ваш логин, например мой #bvv4ik (у меня он просто полностью совпадает и с логином Гит-а)

только что смог Вас добавить в портал комманды, по логину #budnik
отпишитесь там плиз, чтоб Мы понимали, что Вы с нами)

**Comment by budnik** [comment]
Вы меня нашли потому что мне вот только-что пришло приглашение в команду, и я выбрал логин. В другой команде у меня другой логин. а имейл для входа один и тот-же.

**Comment by bvv4ik** [comment]
"Вы меня нашли потому что мне вот только-что пришло приглашение в команду,"
Наоборот, это Вам пришло уведомление, т.к. я Вас нашел и прислал инвайт)

на сколько я знаю - логин таки в Слак-е один..
или может сообщите оба Ваших логина в Слак-е, чтоб я мог убедиться в обратном?

**Comment by budnik** [comment]
Вы меня нашли по фамилии, там же написано в поле поиска "name or email" логина budnik у меня небыло до того как я его не создал после приглашения. У меня был логин d1b в домене d1b:
![selection_14 2514 2514 25](https://cloud.githubusercontent.com/assets/1160699/7157766/75205cdc-e37b-11e4-81ca-797ab9438eb9.png)
попробуйте поискать мой юзернейм `d1b` не уверен что найдется что-то

**Comment by budnik** [comment]
Похоже готово.

**Comment by bvv4ik** [comment]
На https://e-government-ua.slack.com/messages/_org_git-btrack-rules/details/ проверили, все работает! Отлично
Спасибо...
тогда и на остальные коналы добавить и - полный порядок)

**Comment by bvv4ik** [comment]
а чето по остальным каналам уведомления на слак не приходят

**Comment by budnik** [comment]
@bvv4ik Занимаюсь переносом с heroku на IBM bluestack, т.к. первый прекратил предоставление полностью бесплатного плана.

**Comment by budnik** [comment]
проверка-проверка 1-2-3!

**Comment by budnik** [comment]
test, 1-2-3

**Comment by budnik** [comment]
testing IBM cloud for github bot

**Comment by LamronNu** [comment]
сегодня туда загружено небольшое приложение.. есть бесплатный план, только там поменялась методология настройки -- нужно дополнительно прописывать Procfile + "включать" dynos...

или Ваше приложение более "громоздкое"? например, там два процесса предусмотрено, тогда как для бесплатного плана допускается только один процесс..

если есть сложности с настройкой этого Procfile -- могу помочь.. если, конечно, проблема еще не решена)

**Comment by budnik** [comment]
На хероку новые тарифы и в бесплатном плане приложение должно простаивать несколько часов в сутки. Бот работает круглосуточно и постоянно. Перенес на bluestack потому.
