### ISSUE TITLE
На бэке (wf-base) реализовать сервис, возвращающий массив БП, к которому у заданного логина есть доступ.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#570]
1) Название сервиса getLoginBPs
2) Параметры:
sLogin - строковое значение - логин пользователя в Activiti
3) Ответ, массив-обьектов(JSON) бизнеспроцессов, к которым у логина есть доступ:
Например:
[
{
"sID":"mvd_dnepr_1"
"sName":"Справка о несудимости"
},
{
"sID":"mreo_kiev_1"
"sName":"Регистрация авто в МРЕО"
}
]
4) Добавить описание на вики в АПИ

ВАЖНО: Принадлежность к процессу проверять через наличие у пользователя вхождения в ту группу, которая в данном БП определена как та, что позволяет запускать процесс, через механизм:
Получить из описания процесса через репозиториСервис можно группу, которая может стартануть процесс:
https://test.region.igov.org.ua/wf-region/service/repository/process-definitions/zhitomir_mvk_2:87:1445137/identitylinks/
.

П.С.: Это нужно для реализации одного из пунктов задачи: https://github.com/e-government-ua/i/issues/560

**Comment by ASkosyr** [comment]
Метод реализован
пример запроса
https://test.region.igov.org.ua/wf-region/service/rest/getLoginBPs?sLogin=kermit

Описание добавил на WIKI страницу 
https://github.com/e-government-ua/i/blob/master/docs/specification.md#17_getBPForUsers

**Comment by nazarenkod** [comment]
Реализовано
![default](https://cloud.githubusercontent.com/assets/13256486/8825738/01bf54ee-308a-11e5-8c64-65b50a67de28.jpg)
