### ISSUE TITLE
На централе (wf-central) реализовать набор сущностей с корнем Place, для организации всех регионов, районов, и населенных пунктов в единую унифицированную структуру, и сервисы работы с ними

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#573]
|Phase       | Status    | Responsible |
|------------  |------------|------------       |
|Dev. build | ![Complete 100%](http://progressed.io/bar/100 "Complete") | @dgroup |
|Dev. QA    | ![Complete 100%](http://progressed.io/bar/100 "Complete")   | @dgroup |
|BA (API)    | ![Complete 100%](http://progressed.io/bar/50 "Complete")   | @dgroup |
|QA            | ![Complete 100%](http://progressed.io/bar/88 "Complete")     | @RoOmel |

- [x] 1) Сущности:
- [x] 1.1) Сущность Place - "место"
Поля:
- nID - ИД-номер (автоитерируемый-уникальный)
- nID_PlaceType - ИД-номер типа
- sID_UA - ИД-строка (уникальный) общеукраинский код классификатора (КОАТИИ)
- sName - строка-название (например: "Днепропетровск", "Днепропетровская")
- sNameOriginal - строка-название оригинальное (например: "ЛУЧИСТІВСЬКА/С.ЛУЧИСТЕ")
- [x] 1.2) Сущность PlaceType - "тип места"
Поля:
- nID - ИД-номер (автоитерируемый-уникальный)
- nOrder - порядковый номер
- sName - строка-название (например: "Область", "Город", "Село")
- bArea - булевый, "Площадь" (true = область/район/регион и т.д.)
- bRoot - булевый, "Корень" (true = административная еденица страны)
- [x] 1.3) Сущность PlaceTree - "дерево мест"
Поля:
- nID_Place - ИД-номер места
- nID_Place_Root - ИД-номер места-корня
- nID_Place_Area - ИД-номер места-площади
- nID_Place_Parent - ИД-номер места-родителя

- [x] 2) Сервисы мест:
- [x] 2.1) getPlacesTree
Параметры:
- nID //опциональный, если задан то с указанного узла дерева
- sID_UA //опциональный, если задан то с указанного узла дерева
- nID_PlaceType //опциональный, если задан то только заданные типы узлов дерева
- bArea //опциональный, если задан - выбрать только те что с соответственным bArea
- bRoot //опциональный, если задан - выбрать только те что с соответственным bRoot
- nDeep //опциональный, если задан - выбрать только это число вложений по дереву
- [x] 2.2) getPlace
Параметры:
- nID //опциональный, если задан - sID_UA
- sID_UA //опциональный, если задан - nID
- bTree //опциональный, если задан - выводить рекурсивно  все дерево до корня
- [x] 2.3) setPlace - инсертер и апдейтер одновременно
Параметры:
- nID //опциональный, если задан - sID_UA
- sID_UA //опциональный, если задан - nID
- остальные параметры сущности
- [x] 2.4) removePlace
Параметры:
- nID //опциональный, если задан - sID_UA
- sID_UA //опциональный, если задан - nID

- [x] 3) Сервисы типов мест:
- [x] 3.1) getPlaceTypes
Параметры:
- bArea //опциональный, если задан - выбрать только те что с соответственным bArea
- bRoot //опциональный, если задан - выбрать только те что с соответственным bRoot
- [x] 3.2) getPlaceType
Параметры:
- nID
- [x] 3.3) setPlaceType - инсертер и апдейтер одновременно
Параметры:
- nID
- остальные параметры сущности
- [x] 3.4) removePlaceType
Параметры:
- nID

- [ ] 4) Занести данные из класификатора в csv-шки
http://www.ukrstat.gov.ua/klasf/klasif/koatuu.rar

- [ ] 5) Добавить в доку

Уже в конце всего, после успешных тестов:
- [ ] 6) Добавить в сущность ServiceData поле nID_Place, и по проставлять соответствующие ИД-шники-синонимы текущих мест, и выдавать только ближайших +1 уровень (nDeep=2)

**Comment by dgroup** [comment]
# [Draft] Place hierarchy API
### Story 1: "/getPlacesTree"
**T.C:№1.1**: _получить иерархию объектов вниз начиная с указанного узла (параметр `nID`)._
https://test.igov.org.ua/wf-central/service/getPlacesTree?nID=459
ER:
```json
{
    "nLevelArea": null,
    "nLevel": 0,
    "o": {
        "nID": 459,
        "sName": "Недригайлівський район/смт Недригайлів",
        "nID_PlaceType": 2,
        "sID_UA": "5923500000",
        "sNameOriginal": ""
    },
    "a": [
        {
            "nLevelArea": null,
            "nLevel": 1,
            "o": {
                "nID": 460,
                "sName": "Недригайлів",
                "nID_PlaceType": 4,
                "sID_UA": "5923555100",
                "sNameOriginal": ""
            },
            "a": []
        }
    ]
}
```
**Примечание**: по умолчанию возвращаются иерархия с ограниченным уровнем вложенности детей (поле `nDeep`, по умолчанию равно 1).

**T.C:№1.2**: _получить иерархию объектов вниз начиная с указанного узла (параметр `nID`) и количества уровней вниз (параметр `nDeep`)._
https://test.igov.org.ua/wf-central/service/getPlacesTree?nID=459&nDeep=4
ER:
```json
{
    "nLevelArea": null,
    "nLevel": 0,
    "o": {
        "nID": 459,
        "sName": "Недригайлівський район/смт Недригайлів",
        "nID_PlaceType": 2,
        "sID_UA": "5923500000",
        "sNameOriginal": ""
    },
    "a": [
        {
            "nLevelArea": null,
            "nLevel": 1,
            "o": {
                "nID": 460,
                "sName": "Недригайлів",
                "nID_PlaceType": 4,
                "sID_UA": "5923555100",
                "sNameOriginal": ""
            },
            "a": [
                {
                    "nLevelArea": null,
                    "nLevel": 2,
                    "o": {
                        "nID": 458,
                        "sName": "Вільшана",
                        "nID_PlaceType": 5,
                        "sID_UA": "5923584401",
                        "sNameOriginal": ""
                    },
                    "a": []
                },
                {
                    "nLevelArea": null,
                    "nLevel": 2,
                    "o": {
                        "nID": 461,
                        "sName": "Вакулки",
                        "nID_PlaceType": 5,
                        "sID_UA": "5923555101",
                        "sNameOriginal": ""
                    },
                    "a": []
                },
                {
                    "nLevelArea": null,
                    "nLevel": 2,
                    "o": {
                        "nID": 462,
                        "sName": "Віхове",
                        "nID_PlaceType": 5,
                        "sID_UA": "5923555102",
                        "sNameOriginal": ""
                    },
                    "a": []
                }
            ]
        }
    ]
}
```
**T.C:№1.3**: _получить иерархию объектов вниз начиная с указанного узла (параметр `sUA_ID`)._
https://test.igov.org.ua/wf-central/service/getPlacesTree?sID_UA=5923500000
ER = T.C:№1.1

**T.C:№1.4**: _получить иерархию объектов вниз начиная с указанного узла (параметр `sUA_ID`) и количества уровней вниз (параметр `nDeep`)._
https://test.igov.org.ua/wf-central/service/getPlacesTree?sID_UA=5923500000&nDeep=3
ER = T.C:№1.2

**Comment by dgroup** [comment]
# [Draft] Place hierarchy API
### Story 2: "/getPlace"
**T.C:№2.1**: _получить иерархию объектов вверх начиная с указанного узла (параметр `nID`)._
https://test.igov.org.ua/wf-central/service/getPlace?nID=462
ER: возвращает 1 объект Place по параметру (`nID`)
```json
{
    "nLevelArea": null,
    "nLevel": 0,
    "o": {
        "nID": 462,
        "sName": "Віхове",
        "nID_PlaceType": 5,
        "sID_UA": "5923555102",
        "sNameOriginal": ""
    },
    "a": []
}
```
**Примечание**: по умолчанию возвращаются иерархия с ограниченным уровнем (только 1 уровень)
- [ ] Dev. тестирование @dgroup
- [ ] QA тестирование

**T.C:№2.2**: _получить иерархию объектов вверх начиная с указанного узла (параметр `nID`). Для активации выборки по полной иерархии необходимо указать параметр `bTree`._
https://test.igov.org.ua/wf-central/service/getPlace?nID=462&bTree=true
ER: возвращает иерархию объектов снизу вверх (напр. от деревни к району/области)
```json
{
    "nLevelArea": null,
    "nLevel": 2,
    "o": {
        "nID": 459,
        "sName": "Недригайлівський район/смт Недригайлів",
        "nID_PlaceType": 2,
        "sID_UA": "5923500000",
        "sNameOriginal": ""
    },
    "a": [
        {
            "nLevelArea": null,
            "nLevel": 1,
            "o": {
                "nID": 460,
                "sName": "Недригайлів",
                "nID_PlaceType": 4,
                "sID_UA": "5923555100",
                "sNameOriginal": ""
            },
            "a": [
                {
                    "nLevelArea": null,
                    "nLevel": 0,
                    "o": {
                        "nID": 462,
                        "sName": "Віхове",
                        "nID_PlaceType": 5,
                        "sID_UA": "5923555102",
                        "sNameOriginal": ""
                    },
                    "a": []
                }
            ]
        }
    ]
}
```
- [ ] Dev. тестирование @dgroup
- [ ] QA тестирование

**T.C:№2.3**: _получить иерархию объектов вверх начиная с указанного узла (параметр `sUA_ID`)._
https://test.igov.org.ua/wf-central/service/getPlace?sUA_ID=5923555102
ER = T.C:№2.1
- [ ] Dev. тестирование 
- [ ] QA тестирование

**T.C:№2.4**: _получить иерархию объектов вверх начиная с указанного узла (параметр `sUA_ID`). Для активации выборки по полной иерархии необходимо указать параметр `bTree`._
https://test.igov.org.ua/wf-central/service/getPlace?sUA_ID=5923555102&bTree=true
ER = T.C:№2.2
- [ ] Dev. тестирование 
- [ ] QA тестирование

**Comment by dgroup** [comment]
# Place hierarchy API
### Story 3: "/setPlace"  ![Complete 50%](http://progressed.io/bar/50 "Complete")
**T.C:№3.1**: _Вставить новый объект Place._
[POST] https://test.igov.org.ua/wf-central/service/setPlace?sName=child_of_462&nID_PlaceType=5&sID_UA=90005000462&sNameOriginal=5000_462_child
ER: GET запрос по адресу должен вернуть 
```json
```
...
setPlace - инсертер и апдейтер одновременно Параметры:
nID //опциональный, если задан - sID_UA
sID_UA //опциональный, если задан - nID

**Comment by bvv4ik** [comment]
"Вопросы/предложения к @bvv4ik

1) T.C:№1.5, по идее у нас должен возвращаться список, т.к. иерархия как таковая ломается фильтрацией по типу.
 Да
 Нет
2) Что возвращать если записей нет? Кидать что то в стиле NotFoundException?"


1) Именно в п.1.5 - стоит, только придется тогда в каждом элементе еще и ИД парента размещать (т.к. когда это именно структура а не массив, то вышестоящий по структуре элемент и позволяет понять"ИД парента")
но только для п.1.5. т.к. если там уже будет больше чем один тип, то всеравно структура нужна... и, кстати если скипаться элементы будут , то ИД парента так-же понадобятся... ну то уже такое(пока на остальные кейсы не заморачиаемся)

2) эксепшин, если реально исходный ИД не найден... а вот если найден, но по п.1. (Т.С.1.5), и при этом соответствующих типу чилдов нет - просто пустой массив...

**Comment by dgroup** [comment]
# Place hierarchy API
### Story 4: "/removePlace"  ![Complete 100%](http://progressed.io/bar/50 "Complete")
**T.C:№4.1**: _удалить объект Place._
[POST] 
ER: 
1.  HTTP code = 200 OK
2.  GET запрос по адресу https://test.igov.org.ua/wf-central/service/getPlaceEntity?nID=22830 должен вернуть cообщение об ошибке:
```json
```
- [ ] Dev. тестирование
- [ ] QA тестирование

**Comment by dgroup** [comment]
# Place hierarchy API
### Story 5: "/getPlaceTypes"  ![Complete 100%](http://progressed.io/bar/100 "Complete")
**T.C:№5.1**: _Получить тип места (область)._
https://test.igov.org.ua/wf-central/service/getPlaceTypes?bArea=true&bRoot=true
ER: 
```json
[
    {
        "bArea": true,
        "bRoot": true,
        "nID": 1,
        "sName": "Область",
        "nOrder": null
    }
]
```
- [x] Dev. тестирование @dgroup
- [ ] QA тестирование

**T.C:№5.2**: _Получить тип места (район)._
https://test.igov.org.ua/wf-central/service/getPlaceTypes?bArea=true&bRoot=false
ER: 
```json
[
    {
        "bArea": true,
        "bRoot": false,
        "nID": 2,
        "sName": "Район",
        "nOrder": null
    }
]
```
- [x] Dev. тестирование @dgroup
- [ ] QA тестирование

**T.C:№5.3**: _Получить тип места (ПГТ, город, село)._
https://test.igov.org.ua/wf-central/service/getPlaceTypes?bArea=true&bRoot=false
ER: 
```json
[
    {
        "bArea": false,
        "bRoot": false,
        "nID": 3,
        "sName": "Город",
        "nOrder": null
    },
    {
        "bArea": false,
        "bRoot": false,
        "nID": 4,
        "sName": "ПГТ",
        "nOrder": null
    },
    {
        "bArea": false,
        "bRoot": false,
        "nID": 5,
        "sName": "Село",
        "nOrder": null
    }
]
```
- [x] Dev. тестирование @dgroup
- [ ] QA тестирование

**T.C:№5.4**: _Получить ошибку не указав один(оба) обязательный(ых) параметр(а)._
https://test.igov.org.ua/wf-central/service/getPlaceTypes
ER: 
```json
{
    "code": "BUSINESS_ERR",
    "message": "Required Boolean parameter 'bArea' is not present"
}
```
or
```json
{
    "code": "BUSINESS_ERR",
    "message": "Required Boolean parameter 'bRoot' is not present"
}
```
- [x] Dev. тестирование @dgroup
- [ ] QA тестирование

**Comment by dgroup** [comment]
# Place hierarchy API
### Story 6: "/getPlaceType"  ![Complete 100%](http://progressed.io/bar/100 "Complete")
**T.C:№6.1**: _Получить тип места (как сущность) по первичному ключу (параметр `nID`)._
https://test.igov.org.ua/wf-central/service/getPlaceType?nID=1
ER: 
```json
[
    {
        "bArea": true,
        "bRoot": true,
        "nID": 1,
        "sName": "Область",
        "nOrder": null
    }
]
```
- [x] Dev. тестирование @dgroup
- [ ] QA тестирование

**T.C:№6.2**: _Получить ошибку что сущность не найдена по некорректному первичному ключу (параметр `nID`)._
https://test.igov.org.ua/wf-central/service/getPlaceType?nID=1
ER: 
```json
{
    "code": "SYSTEM_ERR",
    "message": "Entity with id=100500 does not exist"
}
```
- [x] Dev. тестирование @dgroup
- [ ] QA тестирование

**Comment by dgroup** [comment]
# Place hierarchy API
### Story 7: "/setPlaceType"  ![Complete 100%](http://progressed.io/bar/50 "Complete")
**T.C:№7.1**: _Cоздать новый тип места._
[POST] https://test.igov.org.ua/wf-central/service/getPlaceType?nID=1
ER: 
1. HTTP code = 200 OK
2. GET запрос по адресу https://test.igov.org.ua/wf-central/service/getPlaceType?nID=22830 должен вернуть вашу сущность:
```json
[
    {
        "bArea": true,
        "bRoot": true,
        "nID": 1,
        "sName": "Область",
        "nOrder": null
    }
]
```
- [ ] Dev. тестирование @dgroup
- [ ] QA тестирование

**Comment by dgroup** [comment]
# Place hierarchy API
### Story 8: "/removePlaceType"  ![Complete 100%](http://progressed.io/bar/100 "Complete")
**T.C:№8.1**: _Удалить тип места по первичному ключу (`nID`)._
[POST] https://test.igov.org.ua/wf-central/service/removePlaceType?nID=23417
ER: 
1. HTTP code = 200 OK
2. GET запрос по адресу https://test.igov.org.ua/wf-central/service/getPlaceTypes?bArea=false&bRoot=false должен вернуть масив без вашей сущности:
```json
[
    {
        "bArea": false,
        "bRoot": false,
        "nID": 3,
        "sName": "Город",
        "nOrder": null
    },
    {
        "bArea": false,
        "bRoot": false,
        "nID": 4,
        "sName": "ПГТ",
        "nOrder": null
    },
    {
        "bArea": false,
        "bRoot": false,
        "nID": 5,
        "sName": "Село",
        "nOrder": null
    }
]
```
- [x] Dev. тестирование @dgroup
- [ ] QA тестирование

**Comment by RoOmel** [comment]
1. request
https://test.igov.org.ua/wf-central/service/getPlacesTree?nID=459&nDeep=1
response
200 ОК
{
    "nLevelArea": null,
    "nLevel": 0,
    "o": {
        "sID_UA": "5923500000",
        "nID": 459,
        "sName": "Недригайлівський район/смт Недригайлів",
        "nID_PlaceType": 2,
        "sNameOriginal": ""
    },
    "a": [
        {
            "nLevelArea": null,
            "nLevel": 1,
            "o": {
                "sID_UA": "5923555100",
                "nID": 460,
                "sName": "Недригайлів",
                "nID_PlaceType": 4,
                "sNameOriginal": ""
            },
            "a": []
        }
    ]
}
Ответ на запрос без параметра nDeep такой же, т.е. значение "1" параметра задано по умолчанию.
2. request
https://test.igov.org.ua/wf-central/service/getPlacesTree?nID=459&nDeep=2
response
200 ОК
{
    "nLevelArea": null,
    "nLevel": 0,
    "o": {
        "sID_UA": "5923500000",
        "nID": 459,
        "sName": "Недригайлівський район/смт Недригайлів",
        "nID_PlaceType": 2,
        "sNameOriginal": ""
    },
    "a": [
        {
            "nLevelArea": null,
            "nLevel": 1,
            "o": {
                "sID_UA": "5923555100",
                "nID": 460,
                "sName": "Недригайлів",
                "nID_PlaceType": 4,
                "sNameOriginal": ""
            },
            "a": [
                {
                    "nLevelArea": null,
                    "nLevel": 2,
                    "o": {
                        "sID_UA": "5923584401",
                        "nID": 458,
                        "sName": "Вільшана",
                        "nID_PlaceType": 5,
                        "sNameOriginal": ""
                    },
                    "a": []
                },
                {
                    "nLevelArea": null,
                    "nLevel": 2,
                    "o": {
                        "sID_UA": "5923555101",
                        "nID": 461,
                        "sName": "Вакулки",
                        "nID_PlaceType": 5,
                        "sNameOriginal": ""
                    },
                    "a": []
                },
                {
                    "nLevelArea": null,
                    "nLevel": 2,
                    "o": {
                        "sID_UA": "5923555102",
                        "nID": 462,
                        "sName": "Віхове",
                        "nID_PlaceType": 5,
                        "sNameOriginal": ""
                    },
                    "a": []
                }
            ]
        }
    ]
}
На самом деле параметр nDeep со значением "2" в данном запросе определяет уровень  вложений по дереву и отображает все дочерние узлы 1-го и 2-го уровней. При этом параметр nDeep со значением "3" или "4" возвращает тот же результат для данного родительского узла.

**Comment by RoOmel** [comment]
T.C:№1.4
request
https://test.igov.org.ua/wf-central/service/getPlacesTree?sID_UA=5923500000&nDeep=2
response
200 ОК

**Comment by RoOmel** [comment]
T.C:№1.7 Выборка всех узлов с "Площадь" (true = область/район/регион и т.д.)
request
https://test.igov.org.ua/wf-central/service/getPlacesTree?nID=459&bRoot=false&nDeep=2
response
200 ОК

**Comment by RoOmel** [comment]
T.C:№2.1, T.C:№2.2, T.C:№2.3, T.C:№2.4 соответствуют ТЗ

**Comment by RoOmel** [comment]
T.C:№3.1, T.C:№3.2 соответствуют ТЗ
T.C:№3.3
При запросе методом POST
![bug_igov_15_01](https://cloud.githubusercontent.com/assets/12996514/9683115/b01bc92a-5315-11e5-9017-82004077f7cd.jpg)
возвращает 200 ОК.
Но проверка обновлённых данных
https://test.igov.org.ua/wf-central/service/getPlaceEntity?nID=22830
возвращает
{
    "code": "SYSTEM_ERR",
    "message": "Entity with id=22830 does not exist"
}
при этом повторный запрос T.C:№3.2
https://test.igov.org.ua/wf-central/service/getPlaceEntity?sID_UA=90005000462
возвращает
{
    "sID_UA": "90005000462",
    "nID": 24202,
    "sName": "child_of_462",
    "nID_PlaceType": 5,
    "sNameOriginal": "5000_462_child"
}

**Comment by RoOmel** [comment]
T.C:№4.1 соответствуют ТЗ

**Comment by RoOmel** [comment]
T.C:№5.1, T.C:№5.2, T.C:№5.3, T.C:№5.4,

**Comment by RoOmel** [comment]
T.C:№6.1 соответствуют ТЗ

**Comment by RoOmel** [comment]
T.C:№7.1  соответствуют ТЗ

**Comment by RoOmel** [comment]
8.1 соответствуют ТЗ
В тесткейсе шаги надо поменять местами, т.к. первичный ключ мы не знаем и его надо брать из ответа
https://test.igov.org.ua/wf-central/service/getPlaceTypes?bArea=false&bRoot=false
а потом подставлять в запрос для удаления

**Comment by RoOmel** [comment]
Итого:
1.5 - вопрос

**Comment by dgroup** [comment]
@RoOmel , спасибо. Планирую устранением проблем заняться на следующей неделе...

**Comment by dgroup** [comment]
Смогу приступить к устранению на следующей неделе (сейчас в командировке, нет свободного времени)

**Comment by RoOmel** [comment]
Ок, буду ждать фикса.
Ку

**Comment by dgroup** [comment]
@RoOmel , добрый вечер. 

Просмотрел Т.С№3.3 и мне кажется в вашем примере система должна генерировать ошибку. Пользователи не могут указывать первичный ключ для новой сущности - ибо это задача хибернейта (фреймворк для работы с слоем базы данных).

Вы согласны с данным утверждением? Могу ли я приступить к реализации данного подхода?

**Comment by dgroup** [comment]
@RoOmel , что касается 1.5:
> Самый верхний узел имеет "nID_PlaceType": 2, т.е. по сути таски его не должно быть?
Cамый верхний узел это сущность, с которой мы начинаем поиск. Думаю это надо уточнить у Владимира, @bvv4ik .

**Comment by dgroup** [comment]
@RoOmel , обсудил пункт 1.5 с Владимиром. Ваше замечание абсолютно справедливо, верхний узел уберем (добавил его в последних комитах, в изначальной реализации его не было).

**Comment by RoOmel** [comment]
@dgroup при проверке ТС №3.3 ошибку не возвращает (видно на скриншоте), но запрос согласно ТЗ не обновляет данные, что подтверждает запрос https://test.igov.org.ua/wf-central/service/getPlaceEntity?nID=22830, а также подтверждает запрос T.C:№3.2
https://test.igov.org.ua/wf-central/service/getPlaceEntity?sID_UA=90005000462, кот. возвращает старые данные

**Comment by RoOmel** [comment]
что на счёт:
6.2 - вопрос;
8.1 - исправить шаги ТС
?

**Comment by dgroup** [comment]
@RoOmel пока не дошел, пока у меня 3.3 и 1.5 в очереди.

**Comment by dgroup** [comment]
@RoOmel , протестировал Т.С№3.3.
[POST] https://test.igov.org.ua/wf/service/setPlace?sName=Warshava_test_1&nID_PlaceType=5&sNameOriginal=test1&sID_UA=1234567890&nID=100500
Получил сообщение об ошибке, т.к. нельзя указывать первичный ключ при создании:
```json
{
    "code": "SYSTEM_ERR",
    "message": "Entity with id=100500 does not exist"
}
```
С моей точки зрения - данный Т.С. работает корректно. Просьба проверить еще раз.

P.S.: Стоит убрать первичный ключ - объект создается без проблем и доступен по sID_UA через `getPlaceEntity`.

**Comment by RoOmel** [comment]
Если я правильно понял механизм и логику работы запросов, то:
1) Тетс-кейс 3.1 вставляет новый объект Place, при этом параметр nID генерируется.
Например, в ответе параметр nID вернулся со значением например 24202.
2) Тетс-кейс 3.3 повтор предыдущего запроса с добавлением параметра nID и значением  например 22830, тем самым обновляем новый объект.
Оба запроса возвращают 200 ОК.
При этом проверка новго объекта запросом https://test.igov.org.ua/wf-central/service/getPlaceEntity?nID=22830 возвращает ошибку, проверка https://test.igov.org.ua/wf-central/service/getPlaceEntity?nID=24202
Это значит, что Тетс-кейс 3.3 не обновляет nID.

Сейчас тТетс-кейсы 3.1 - 3.3 нет возможности проверить со значением 90005000462 параметра sID_UA.

**Comment by dgroup** [comment]
@RoOmel , текущий статус по тесткейсам:
- 1.5 - исправлено;
- 6.2 - ссылка обновлена в описании Т.С, правок кода не требуется;
- 8.1 - не вижу смысла менять шаги. Если Вы считаете что нужно менять - пожалуйста, меняйте, тестируйте как хотите. Все тесткейсы выше - это дев. кейсы которые были использованы мной для дев. тестирования.

**Comment by RoOmel** [comment]
С выводом по Тетс-кейс 3.3 Вы согласны или нет

**Comment by dgroup** [comment]
> "Это значит, что Тетс-кейс 3.3 не обновляет nID." ?

Cовершенно верно, айди не должен обновлятся.

**Comment by RoOmel** [comment]
А в чём тогда суть ТС 3.3, какой должен быть ожидаемый результат?

**Comment by dgroup** [comment]
> А в чём тогда суть ТС 3.2 - 3.3, какой должен быть ожидаемый результат для каждого из них?

Задача одна и та же: обновить параметры сущность Place. 

Разница в алгоритме поиска сущности для обновления:
1.  Поиск по первичному ключу (РК)
2.  Поиск по UA ID параметру

Нужно было убедится что поиск и обновление работает.

**Comment by RoOmel** [comment]
Ок, тогда закрываю задачу.

**Comment by bvv4ik** [comment]
рано закрывать таску... еще есть не выполненные пункты

**Comment by dgroup** [comment]
Для тестирования нужно использовать те же тесткейсы что и были использованы для /getService.

**Comment by dgroup** [comment]
# Place hierarchy API + Service API.
### Story 9: "/getService"  ![Complete 100%](http://progressed.io/bar/100 "Complete")
**T.C:№9.1**: _Получить сервис по первично ключу (`nID`)._
**[GET]** https://test.igov.org.ua/wf-central/service/services/getService?nID=1
**ER**: В каждой сущности aServiceData должно добавится два поля
- oPlace
- oPlaceRoot

где,
**oPlace** это место (регион, город, деревня. и тд), по сути это универсальная замена City, Region (их со временем удалим).
**oPlaceRoot** это область, в которой расположен oPlace.
```json
{
    "sSubjectOperatorName": "Міністерство Внутрішніх Справ",
    "subjectOperatorName": "Міністерство Внутрішніх Справ",
    "nID": 1,
    "sName": "Надання довідки про відсутність (наявність) судимості або обмежень, передбачених кримінально-процесуальним законодавством України.",
    "nOrder": 1,
    "aServiceData": [
        {
            "oPlace": {
                "sID_UA": "1211000000",
                "nID": 2,
                "sName": "Кривий Ріг",
                "nID_PlaceType": 3,
                "sNameOriginal": ""
            },
            "oPlaceRoot": {
                "sID_UA": "1200000000",
                "nID": 50001,
                "sName": "Дніпропетровська",
                "nID_PlaceType": 1,
                "sNameOriginal": ""
            },
            "bTest": true,
            "sNote": "Перейдя на этот сайт Вы сможете получить услугу",
            "asAuth": "BankID,EDS",
            "test": true,
            "note": "Перейдя на этот сайт Вы сможете получить услугу",
            "nID": 1,
            "nID_City": {
                "sID_UA": "1211000000",
                "nID": 2,
                "sName": "Кривий Ріг",
                "nID_Region": {
                    "sID_UA": "1200000000",
                    "nID": 1,
                    "sName": "Дніпропетровська"
                }
            },
            "nID_ServiceType": {
                "nID": 1,
                "sName": "Внешняя",
                "sNote": "Пользователь переходит по ссылке на услугу, реализованную на сторонней платформе"
            },
            "oSubject_Operator": {
                "oSubject": {
                    "sID": "ПАО",
                    "sLabel": "ПАО ПриватБанк",
                    "sLabelShort": "ПриватБанк",
                    "nID": 1
                },
                "sOKPO": "093205",
                "sFormPrivacy": "ПАО",
                "sNameFull": "Банк ПриватБанк",
                "nID": 1,
                "sName": "ПриватБанк"
            },
            "oData": "{}",
            "sURL": "https://dniprorada.igov.org.ua",
            "bHidden": false
        },
    ...
    ],
    "sInfo": "",
    "sFAQ": "",
    "sLaw": "",
    "nSub": 0,
    "nID_Status": 1,
    "nStatus": 0
}```
- [x] Dev. тестирование @dgroup
- [ ] QA тестирование

**Comment by dgroup** [comment]
@RoOmel, добрый день.
Есть ли новости по поводу тестирования?

**Comment by RoOmel** [comment]
Добрый день.
Сегодня постараюсь закрыть задачу.

**Comment by RoOmel** [comment]
T.C:№9.1 пройден.
Story 9: "/getService"  согласно ТЗ

**Comment by RoOmel** [comment]
4) Занести данные из класификатора в csv-шки
http://www.ukrstat.gov.ua/klasf/klasif/koatuu.rar - "битая" ссылка
