### ISSUE TITLE
На дашборде подвязать использоване сервиса экспорта тасок по БП ("downloadTasksData"), в разделе "Звіт"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#574]
На дашборде, если у пользователь состоит в группе "mngr":
(это можно отрисовать сразу в отдельном разделе, как в таске: https://github.com/e-government-ua/i/issues/560)

1) отрисовать поле input для даты (умолчательно ставить прошлый день)
2) отрисовать кнопку "Экспортировать", при нажатии на которую вызывать сервис "downloadTasksData" (параметры слать те-же что в таске 517, только дату из п.1)
3) параметры для сервиса передавать с клиента а не сервера
(позже будет комбобокс с выбором вариантов)

Сервис "downloadTasksData" реализовывался по таске:
https://github.com/e-government-ua/i/issues/517

П.С.: даже если сервис окончательно не оттестирован - привязаться "даже без особых тестов" (главное чтоб вызывался сервис, а он уже точно будет предлагать сохранять файл)

**Comment by rooksnest** [comment]
Предоставьте, пож, логи/пароль для роли "mngr" и для роли, которая не предусматривает взможность экспорта.
Если для "mngr"  это kermit/kermit, то на дашборде не наблюдается раздел "Звiт".
Такой раздел присутствует в активи-эксплорер, но там на данный момент функционал не работает, нет реакции на "Генерувати звіти".
Нужно более детальное пояснение, что, где, как.

**Comment by bvv4ik** [comment]
kermit/kermit
Вот видно раздел звит:

![image](https://cloud.githubusercontent.com/assets/4208821/8920825/d067466c-34d6-11e5-8187-698a8f4b60f2.png)

![image](https://cloud.githubusercontent.com/assets/4208821/8920829/da936daa-34d6-11e5-8c79-173606f86272.png)

**Comment by VadimGulich** [comment]
Неверно задан по умолчанию БП ,в таком формате выгрузка не происходит , правильный формат указан на скрине:
![image](https://cloud.githubusercontent.com/assets/12964120/8924527/56af7cb4-3507-11e5-887f-a9540d9f3866.png)

Вопрос: 
1) Формат такой и будет при экспорте или будут правки в рамках другой задачи?
![image](https://cloud.githubusercontent.com/assets/12964120/8924565/aa0a1c70-3507-11e5-9418-964c0929e6e6.png)

**Comment by rooksnest** [comment]
При экспорте отчета за один день, загружается пустой файл (размер: 0 байт).

**Comment by bvv4ik** [comment]
"Если причина в том, что за это день нет данных, то возможно стоит в дальнейшем предусмотреть информирование об этом, без загрузки самого файла"
нет смысла делать сервис, который будет говорить что вызов другого сервиса вернет пустой список...

"При экспорте отчета за один день (27.07.15), загружается пустой файл (размер: 0 байт). "
дата конца должна быть минимум на один день больше начальной


"Вопрос: 
1) Формат такой и будет при экспорте или будут правки в рамках другой задачи?"

это всего-лишь дефолт...
на самом деле задавать там можно что угодно, а скоро, в рамках отдельной задачи там вообще можно будет выбирать это из выпадающего списка доступных данному сотруднику БП

**Comment by VadimGulich** [comment]
Спасибо за ответы, тогда критических ошибок нет , задача реализована корректно
