### ISSUE TITLE
Актуализировать описание на нашей вики, по полной установке явовского бэкэнда на томкэте(проекты wf-*)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#579]
Размещение:
https://github.com/e-government-ua/i/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%B0-Tomcat-(backend)

Важные части описания:
1) сразу запускать под спринговым профилем local (чтоб подтягивались дефолтные проперти проекта, и не приходилочь их подкладывать в томкэт)
2) Установка обоих проектов wf-central и wf-region (wf-base НЕ НУЖНО, т.к. это ядро, которое только наследуется а не "поднимается" в качестве отдельного сервера)
3) настройки таких-же контекстов как и на общем тестовом (/wf-central и /wf-region) и поднятии их на тех портах, которые дефолтом предлагаются в настройках фронтовых проектов(глянуть на вики). т.е. чтоб локально развернутые фронты так-же легко настраивались на локальный бэк явы.
4) возможность "отвязки" в базе от общего регионального при вызове услуг (хранится в ServiceData.csv, который при модивикации ОБЯЗАТЕЛНО нужно поставить в игнор для локального ГИТ-а)
5) Лаконично, но при этом понятно (желательно с картинками, но не принципиально)

По стилю придерживаться примеров:
https://github.com/e-government-ua/i/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D1%80%D0%B5%D0%B3%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B4%D0%B0%D1%88%D0%B1%D0%BE%D1%80%D0%B4%D0%B0-%D1%87%D0%B8%D0%BD%D0%BE%D0%B2%D0%BD%D0%B8%D0%BA%D0%B0-(dashboard-js,-frontend)
и
https://github.com/e-government-ua/i/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D1%86%D0%B5%D0%BD%D1%82%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BE%D1%80%D1%82%D0%B0%D0%BB%D0%B0-%D0%B3%D1%80%D0%B0%D0%B6%D0%B4%D0%B0%D0%BD-(central-js,-frontend)

**Comment by bvv4ik** [comment]
ну как, уже можно сформировать какие-то приблизительные прогнозы по срокам решения таски?

**Comment by 40rn05lyv** [comment]
Фактично вікі оновлена, але потрібно пофіксити #622 і перевірити чи після фіксу працюватиме інтеграція локального wf-central з локальним wf-region.

**Comment by bvv4ik** [comment]
локальные настройки авторизации БанкИД на фронте - обязательно поборим, но думаю это стоит реализовывать в отдельной таске... по этой таске важно чтоб реально по доке на нашей вики любой мог поставить себе наши явовские проекты (бэка)

если это сейчас так - данную таску можно закрывть
