### ISSUE TITLE
Раздел II. Создать подгруппы задач, на основе старой задачи для ActivitiExplorer-а

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#58]
ВМЕСТО:
https://github.com/e-government-ua/i/issues/41
по образцу:
https://docs.google.com/document/d/1xueqPW0XqXBr_SPnBtBkwhI2CPxMKihzX9zDIsqBMc4/edit#heading=h.o8t4xxgsthyn
пункт 2. Изменить разделы работы с  задачам

НУЖНО:
Создать подобные "табы" подгрупп задач, со счетчиками числа задач и возможностью выбрать любую из подгрупп (в результате должен отобразиться список задач с соотв.критериями)
П.С.: Сами задачи должны начать отображаться по задаче: https://github.com/e-government-ua/i/issues/60

**Comment by AleksejDomash** [comment]
Изменить порядок расположения разделов:
В роботі- раздел открыт по-умолчанию  после авторизации.  В этот раздел должны попадать все незавершенные процессы, где исполнителем  является  пользователь.
Необроблені
Оброблені

**Comment by bvv4ik** [comment]
осталось каунтеры сделать на таб-ах
