### ISSUE TITLE
[dashboard-js] Велика кількість помилок у консолі браузера

### ISSUE THREAD

**Issue by Kamilius** [e-government-ua/i#582]
На сторінці https://test.region.igov.org.ua:6948/tasks дашборду у консолі виникає величезна кількість помилок, пов"язана, на мою думку, з відсутністю перевірки якоїсь колекції або об"єкту типу `string` на наявність. Наче видимих багів це не викликає, та я можу помилятись, оскільки не знаю, що було імплементовано протягом останніх кількох днів у відношенні дашборду.

![screen shot 2015-07-20 at 10 06 25 am](https://cloud.githubusercontent.com/assets/3115794/8771917/09df68ae-2ec7-11e5-8283-21a46790b32c.png)

Більш детально наразі сказати нічого не можу, бо з роботи доступна лише версія тест сервера, а на ній код - мініфіковано

**Comment by bvv4ik** [comment]
поправлено

**Comment by Kamilius** [comment]
Перевірено
