### ISSUE TITLE
[dashboard-js] На закладці "Оброблені" дати виглядають, як NaN-NaN-NaN NaN:NaN

### ISSUE THREAD

**Issue by Kamilius** [e-government-ua/i#583]
https://test.region.igov.org.ua:6948/tasks, вкладка "Оброблені". Усі дати відображені як "NaN-NaN-NaN NaN:NaN". Потрібно відображати вірну дату, або ж не відображати її взагалі

![screen shot 2015-07-20 at 11 21 12 am](https://cloud.githubusercontent.com/assets/3115794/8773077/9f708baa-2ed1-11e5-89c5-b7e6ca780fb9.png)

**Comment by bvv4ik** [comment]
уже писали об этом несколько раз... это будет реализовываться комплексно в отдельном ТЗ
