### ISSUE TITLE
На главном портале, в форме заполнения услуги: обрабатывать новое поле "Страны"(id=sCountry_UA) в виде автокомплита с опциональным проставлением по нему смежного поля (id=sID_Country) с ИД-страны и/или опционального обратного проставления по ИД-страны (id=bankIdsID_Country) "Предустановленного автокомплита" (id=sCountry_UA)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#584]
ВАЖНО:
вместо поля id=sCountry_UA может быть поле id=resident (тогда ориентироваться на него)

- [x] 1) Если при загрузки формы есть поле с id=sCountry_UA, то отрисовывать на его месте компонент авто-комплита(typeahead, подобно тому как в таске: https://github.com/e-government-ua/i/issues/518), и позволять выбирать страны по поиску вхождений вводимого текста в название из элемента "sNameShort_UA" получаемых объектов-стран(сущностей "Country") массива по вызову сервиса /getCountries (на бэке явы). После произведенного выбора страны в текущем поле с id=sCountry_UA, оставлять там значение элемента "sNameShort_UA".

- [x] 2) Если наступил кейс п.1, а в нем еще НЕ осуществлен выбор автокомплита (т.е. не выбрана страна), и при этом есть еще на форме поле с id=bankIdsID_Country (и оно не пустое), то автоматически предустанавливать в автокомплите п.1, значение из элемента "sNameShort_UA", получаемого объекта-страны(сущности "Country"), через вызов сервиса /getCountry, передавая туда параметр "sID_Three", который изначально берется как раз из поля с id=bankIdsID_Country. (возможно, удастся обойтись и одним использованием в п.1. сервисом /getCountries)

- [x] 3) Если наступил кейс п.1, а в нем ОСУЩЕСТВЛЕН выбор автокомплита (т.е. выбрана страна), и при этом есть еще на форме поле с id=sID_Country, то автоматически предустанавливать в это поле с id=sID_Country - значение из элемента "sID_Three", получаемого объекта-страны(сущности "Country"), после выполненного в п.1. вызова сервиса /getCountries.

ПОЯСНЕНИЯ:
1) Для проверки можно взять справку о несудимости для Днепропетровска. Там уже есть поле с id=sCountry_UA, что позволит прикрепить автокомплит.(для п.1.)
2) а поля для остальных двух пунктов можно замокать
2.1.) т.е. в п.2., если нету id=bankIdsID_Country - сэмулировать его наличие со значением, как будто поле есть, чтоб сработал механизм авто простановки
2.2.) а в п.3., если id=sID_Country нету, то добавить его на стадии загрузки всех полей на форму (только в фронтовом объекте с полями, чтоб можно было его отрисовать на форме и засетить)

**Comment by maxymshg** [comment]
Взял в работу

**Comment by bvv4ik** [comment]
осталось реализовать п.2 и п.3

**Comment by hordesalik** [comment]
п. 2 готов. после теста нужно удалить часть кода, которая была добавлена для эмуляции отсутствующего поля bankIdsID_Country. Где удалять - написано в комментарии к коммиту выше

**Comment by bvv4ik** [comment]
@hordesalik
тамжеж эмуляция написана так, что если в реале поле есть - все будет работать нормально с этим реальным полем? без эмуляции?

**Comment by hordesalik** [comment]
хм. будет 2 поля bankIdsID_Country. оно всегда добавляется

**Comment by bvv4ik** [comment]
нельзя два поля, нужно проверять его уже фактическое наличие... если будет два поля с одинаковыми ИД - это может привести к сбою, если это попадет на боевой...

**Comment by bvv4ik** [comment]
и, какой прогноз по п.3?

**Comment by hordesalik** [comment]
Ок. проверку добавлю сегодня/завтра
п.3 постараюсь сделать до понедельника

**Comment by bvv4ik** [comment]
пожно приоритеты поменять пестами)
т.е. приоритетней п.3, а проверка "второстепенна")

**Comment by hordesalik** [comment]
дело во времени, которое это занимает. п.2. исправить - минут 15, а с п.3. повозится нужно

**Comment by hordesalik** [comment]
п.2 доработан

**Comment by bvv4ik** [comment]
ок, тогда бум ждать п.3.

**Comment by hordesalik** [comment]
п.3 готов
т.к. тестирование п.2 и п.3 одновременно невозможно, в условиях отсутствия реальных данных и нужных полей, для тестирования п.2 нужно закомментировать следующую строку:
client/app/common/components/form/factories/formData.js:30
в ней эмулируется предустановление данных в поле "resident"

после теста всего таска нужно удалить блок кода с
client/app/service/built-in/controllers/servicebuiltinbankid.controller.js:16
по
client/app/service/built-in/controllers/servicebuiltinbankid.controller.js:45
и строку 
client/app/common/components/form/factories/formData.js:30

**Comment by RoOmel** [comment]
Насколько я парвильно понял новое поле формы (например "Надання довідки про відсутність (наявність) судимості або обмежень, передбачених кримінально-процесуальним законодавством України.") называется "*Громадянство:", а не "Страны" , т.к. автокомплит реализован именно там.
Замечания:
1. Не учитываются двойственные названия таких стран как, например: Голландія - Нідерланди, Англія - Велика Британія, их совсем немного, но все они фоициально признанные и дествующие.
2. Нет предустановленного значения - убеждён, что большинству пользователей будет удобнее, чтобы поле было заполнено по умолчанию "Україна"

**Comment by bvv4ik** [comment]
основной функционал давно работает
проверка по справке о несудимости

**Comment by RoOmel** [comment]
Я так понял тестирование по этой задаче не актуально.
