### ISSUE TITLE
На главном портале отвязать срок жизни сессии от срока жизни токена БанкИД (3 минуты), при использовании под-закладки Мои документы и закладки Журнал, а так-же осуществлять авто-аплоад инициализационных документов только одни раз за жизнь сессии.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#585]

**Comment by bvv4ik** [comment]
Для теста:
авторизоваться в подзакладке "Мои документы", переключиться на другую подзакладку, а потом переключиться обратно через 10-20 минут. Не должно потребовать заново авторизоваться там.

**Comment by NikitaLyah** [comment]
Не реализовано, при повторном переходе на вкладку "Мои документы" приходится авторизироваться занаво  @AleksejDomash

**Comment by bvv4ik** [comment]
@AleksejDomash шо, таки да? может быть ошибка?

**Comment by NikitaLyah** [comment]
уже работает, закрываю
