### ISSUE TITLE
На главном портале, в разделе Документы поправит отображение выбранной заклади.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#586]
После авторизации в под-вкладке “Мои документы” - становится не активный таб (становится не понятно, на какой вкладке находится пользователь)
т.е. он вроде серым цветом светится(фон), но это только до клика в сторону... а потом получается так, как будто ни один таб не выбран... хотя список документов светится..
При этом - пропадает рамка вокруг... (до авторизации она есть)

Вероятней всего связано с тем, что до авторизайии и после - это разные пути в УРЛ-е, и соответственно разные вьюзи.

**Comment by coolvision** [comment]
еще сюда же подсветка вкладки "документы" для разных под-вкладок

**Comment by bvv4ik** [comment]
красота... действительно, таки удалось починить эту беду

но, кажется, когда еще не было никакой авторизации (куки пустые), то при заходе в Мои документы - пусто... если, при этом авторизоваться где-то в услуге, и вернуться в Мои документы - все будет гуд...

**Comment by bzhest** [comment]
Протестировано, ошибка исправлена

**Comment by bvv4ik** [comment]
при авторизации через Банк, когда уже авторизация произошла, а список документов еще не отобразился(здето 4 секунды) - просто белое поле и нет ни какого прогресса(крутилки, например), показывающего, что процесс идет... до этого, вроде, крутилка в этот промежуток таки крутилась...

**Comment by bvv4ik** [comment]
чтоб проверить - нужно отчистить куки

**Comment by bzhest** [comment]
почистил куки, смотрю на боевом, крутилка крутится при загрузке Моих документов после авторизации через BankId, белого поля не наблюдаю, что в Мозилле, что в Хроме

**Comment by OlgaKotova** [comment]
@bzhest @bvv4ik мы же вроде бы на test.igov.org.ua проверяем?
"крутилка"  отсутствует на тестовом,  просто белый экран, а через секунды 2 открываются документы(там он один - документ).
Касательно таба, все подсвечивается - и раздел "Док-ты", и его подразделы.
Проверяла на MAC OS X 10.10.4 в Safari 8.0.7

**Comment by coolvision** [comment]
ок, подправлю, добавлю крутилку

**Comment by OlgaKotova** [comment]
@coolvision что-то добавлялось?

**Comment by coolvision** [comment]
@OlgaKotova  да, добавилась крутилка пока загружаются документы на test.igov.org.ua

**Comment by bvv4ik** [comment]
прекрасно!

**Comment by VadimGulich** [comment]
исправлено , закрываю
