### ISSUE TITLE
На бэке централа добавить в сущности Document поле "oSignData" и доработать сервисы для работы с ним

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#587]
1) Добавить в сущность Document - стринговое обязательное поле oSignData.
Если ЕЩЕ НЕ реализована задача: https://github.com/e-government-ua/i/issues/588, то:
2) При использовании сервиса setDocumentFile - сохранять в это поле значение "{}"
3) При использовании сервиса setDocument - сохранять в это поле значение "{}"

**Comment by LamronNu** [comment]
в указанных сервисах добавлен параметр oSignData, пока необязательный, по умолчанию "{}".

для теста: согласно документации "достать" документ, например, так:
www.test.igov.org.ua/wf-central/service/services/getDocument?nID=1&nID_Subject=1
или www.test.igov.org.ua/wf-central/service/services/getDocuments?nID_Subject=1

и убедиться, что появилось новое текстовое поле согласно ТЗ.
методы setDocumentFile  и  setDocument  являются пост-методами, поэтому проверить создание документа "простой строкой" не получится.. скорей всего, этот шаг будет проверен в связанной задаче

**Comment by VadimGulich** [comment]
протестировано , можно на релиз
