### ISSUE TITLE
На бэке централа доработать сервисы сохранения документа, для добавления туда дополнительных атрибутов по ЭЦП.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#588]
Реализовать только по завершению задачи: https://github.com/e-government-ua/i/issues/587

1) При аплоаде нового документа через сервисы setDocumentFile или setDocument - автоматически отправлять его на "сервис БанкИД", который позволит проверить ЭЦП (в т.ч. наложена-ли она вообще), и вернуть ответ с ее атрибутами, которые нужно будет прикрепить к полю сущности Document.

ВАЖНО: описание этого сервиса БанкИД" находится в нашем вики, АПИ ро Банк ИД, стр.22
"Проверка подписанного объекта на подлинность и получение информации о хозяине ЭЦП"

2) Сохранить все атрибуды в виде JSON-обьекта, в поле "oSignData" а если пустота, то сохранять "{}"

**Comment by ASkosyr** [comment]
Срок поставки - понедельник 10 августа

**Comment by bvv4ik** [comment]
есть  в коде строки:
(класс: org.activiti.rest.controller.ActivitiRestDocumentController)

        String soSignData = null;
        //TODO: по другому пункту issue587 - проставлять soSignData

вот в этом месте и нужно будет отсылая для проверки контент файла - возвращать и проставлять сюда объект JSON (его строковое представление)

**Comment by ASkosyr** [comment]
Пример информации о ЭЦП документа

```
{"state":"ok","customer":{"phone":"+380567161131","inn":"3578965412","email":"bankid@org.ua","fullName":"Тестувальник ПриватБанкID","addresses":[{"type":"factual","fullAddress":"49000, м. Дніпропетровськ, вул. Карла Маркса, 62"}],"signatureData":{"name":"АЦСК Держінформ'юсту","serialNumber":"2D24A7C930E2B7B404000000410D0000C2200000","timestamp":"05.08.2015 16:56:50","code":true,"desc":"ПІДПИС ВІРНИЙ","dateFrom":"04.08.2015 10:06:10","dateTo":"04.08.2017 10:06:10","sn":"UA-25287988-2015"},"organizations":[{"type":"edsOwner","name":"ПриватБанк","unit":"Регіональне відділення","mfo":"84369785","position":"керівник","ownerDesc":"Юридична особа","address":{"type":"factual","state":"Дніпропетровська","city":"Дніпропетровськ"}},{"type":"edsIsuer","name":"Держінформ'юст","unit":"Акредитований центр сертифікації ключів","address":{"type":"factual","city":"Київ"}}]}}
```

**Comment by bvv4ik** [comment]
в принципе, уже это точно работает, т.к. иначе-бы не подтягивались данные по ЭЦП на сканах с БанкИД...

пожно проверить на боевом: зайти под своим акаунтом в Мои документы и загрузится скан где будет и колонка с ЭЦП а там ссылка с инфой по всем полям

**Comment by RoOmel** [comment]
Проверить на боевом - это не сложно, попробую. я разобраться хочу как это должно работать и работает так как ожидается

**Comment by RoOmel** [comment]
В своём акаунте в разделе "Мои документы" при клике по ссылке отображается информация ЭЦП по всем полям
