### ISSUE TITLE
На главном портале, после клика на кнопку "Все услуги" - после перехода на другую страницу с полным перечнем услуг этой подкатегории - скролировать экран в самый верх.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#589]
Создана вместо:
https://github.com/e-government-ua/i/issues/481

**Comment by VadymVolos** [comment]
Напишу простым языком для тех кто будет делать, ибо долго искал что же там не так.

Вообщем:
1. Міліція та ДАІ > нажать кнопку "Всі послуги"
2. Посвідчення особи, Громадянство, Місце проживання > нажать кнопку "Всі послуги"

Как вы видите в варианте 1 - страница открывается с самого начала.
А в варианте 2 - страница открывается с центра.

Варианты решения не знаю, скорее всего нужно к кнопке привязать якорь, и сказать чтоб она открывалась с самого верху.

**Comment by OlgaKotova** [comment]
так же проблема актуальна  для раздела "Бізнесу" - когда открываешь любой из подразделов, например "Бізнесу: Будівництво, нерухомість, земля", страница открывается не сверху(т.е. немного проскролена вниз). 
На мувике видно http://screencast.com/t/Y4h4eHtDQur

**Comment by rostag** [comment]
Варіант вирішення:
Використовувати $anchorScroll. Він дозволяє прокручувати до якоря, заданого через $location.hash. (у новішій версії ангуляру його можна використовувати навіть без $location.hash(), це має одну перевагу: рядок адеси у браузері не змінюється).

https://code.angularjs.org/1.3.15/docs/api/ng/service/$anchorScroll

Вношу в код відповідні зміни.

**Comment by rostag** [comment]
Готово. Прошу переглянути зміни. Зараз ідемо найпростішим варіантом - після перемикання на підкатегорію сторінка прокручується до самої гори. Можна прокручувати, наприкад до заголовку підкатегорії.

**Comment by OlgaKotova** [comment]
@rostag я вижу, что проблема не исправлена на test.igov.org.ua.
Тестила на MAC OS X 10.10.4 в Safari 8.0.7.

**Comment by rostag** [comment]
@OlgaKotova Дякую. Можливо, варто протестувати це пізніше, бо в даний момент я ще не бачу свого виправлення на test.igov.org.ua, коли намагаюсь знайти його у коді.

**Comment by rostag** [comment]
@bvv4ik — будь ласка, змерджіть #593, щб можна було тестувати #589.

**Comment by bvv4ik** [comment]
(дублирую из другой таски)
@rostag можете делать и через пулреквесты, но мержить придется самостоятельно... и обязательно после мержа(дождавшись завершения авто-деплоя) - перепроверять потом уже на общем тестовом, что ничего не поламалось. если поламается и не удастся оперативно починить - откатить мерж...

**Comment by rostag** [comment]
@bvv4ik — дякую, зрозумів, змерджив, зараз перевірю.

**Comment by rostag** [comment]
@OlgaKotova — прошу перевірити зараз.

**Comment by OlgaKotova** [comment]
@bvv4ik все отработало корректно, закрываю.
