### ISSUE TITLE
Раздел III. Сделать форму "работы с заявкой для представления simpleUser", на основе старой задачи для ActivitiExplorer-а

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#59]
ВМЕСТО:
https://github.com/e-government-ua/i/issues/40
по образцу:
https://docs.google.com/document/d/1xueqPW0XqXBr_SPnBtBkwhI2CPxMKihzX9zDIsqBMc4/edit#heading=h.4qfzrf47g6tz
сделать форму из пункта "Изменить форму работы с  заявкой для представления simpleUser" 
NEW MESSAGES
domash [10:17 PM]

НУЖНО:
Сделать форму "работы с заявкой" (в виде отдельной страницы app/form)
При выборе конкретной задачи в списке (сам список делается по задаче: https://github.com/e-government-ua/i/issues/60)

**Comment by kurbpa** [comment]
Обновлено:
* Скрыть раздел “Люди” (исполнителя  можно выбирать/назначать через добавление в процесс переменной типа user)
* Итоговый вид формы работы с заявкой до взятия в работу (отредактировано 15,04):
