### ISSUE TITLE
[S5] - Орфографическая ошибка

### ISSUE THREAD

**Issue by annasahi** [e-government-ua/i#590]
"Ви можете допомогти пришвидшити процес переведння послуги в електронний вигляд"  -- Ошибка в слове "переведення"
http://screencast.com/t/glxNehCZWhO

**Comment by rostag** [comment]
Зустрічається багато разів у разних файлах. Виправляю.

**Comment by rostag** [comment]
Зроблено.

**Comment by NikitaLyah** [comment]
Не реализовано @rostag 
![screenshot_2](https://cloud.githubusercontent.com/assets/12964328/8824334/51637dde-307d-11e5-985a-e09e81775fce.jpg)

**Comment by rostag** [comment]
@NikitaLyah - дякую. Це виправлення ще недоступне на test.igov.org.ua. Я повідомлю тут, коли буде.

**Comment by rostag** [comment]
@bvv4ik — будь ласка, змерджіть #594, щоб можна було тестувати #590.

**Comment by bvv4ik** [comment]
@rostag можете делать и через пулреквесты, но мержить придется самостоятельно... и обязательно после мержа(дождавшись завершения авто-деплоя) - перепроверять потом уже на общем тестовом, что ничего не поламалось. если поламается и не удастся оперативно починить - откатить мерж...

**Comment by bvv4ik** [comment]
Просьба перенести эту issue в бэклог, если еще не сделана и закрыть ее:
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit

**Comment by rostag** [comment]
@NikitaLyah — готово, прошу перевіряти на test.igov.org.ua
