### ISSUE TITLE
UI: Odometer для візуалізації числових показників

### ISSUE THREAD

**Issue by rostag** [e-government-ua/i#595]
Щоб показувати важливі цифри, для наглядності можна використати odometer: 
http://github.hubspot.com/odometer/docs/welcome/

**Comment by bvv4ik** [comment]
возможно, когда где-то это используем, но пока не вижу места применения этому компоненту...

П.С.: просьба предложения по какой-либо компоненте публиковать в Слак-е, в соответствующем канале... т.к. в issue пишутся только задачи для реализации(пытаюсь уже давно отучить туда и задачи по орфографическим ошибкам ставить, а писать их в общем гуглодоке, но пока малорегультативно)... очень тяжело работать с issue, когда основные задачи "тонут" в океане мелких ошибок и других сообщений...

**Comment by bvv4ik** [comment]
Просьба перенести эту issue в бэклог и закрыть ее:
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit

**Comment by rostag** [comment]
@bvv4ik - ясно, дякую. У беклог переніс. Про правильне використання issues зрозумів — тут тримати тільки основні задачі.

**Comment by bvv4ik** [comment]
ага, спасибо большое!
