### ISSUE TITLE
Отсутствует расшифровка ссылки * [S5]

### ISSUE THREAD

**Issue by DmitroYatsuk** [e-government-ua/i#596]
Windows XP, Chrome 43.0.2357.134 m;
на странице: Надання доступу третій особі - поле: Введіть ім’я та прізвище людини, якій Ви надаєте доступ: *. Нет расшифровки символа *.
Для перехода:  Документы - Мої документи - Вхід IDBank - Надання доступу третій особі

**Comment by bvv4ik** [comment]
Просьба перенести эту issue в бэклог и закрыть ее:
https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit

**Comment by DmitroYatsuk** [comment]
Перенесена в бэклог
