### ISSUE TITLE
Нарисовать графическую схему связи всех сущностей и их полей в инструменте https://www.gliffy.com

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#597]
Образец в виде изображения:
http://www.gliffy.com/go/publish/image/3855234/L.png
Этот-же образец, но в интерактивном формате giffly:
http://www.gliffy.com/go/publish/3855234

**Comment by VadimGulich** [comment]
Подскажите , пож-ста , где можно посмотреть/проверить , что задача реализована?

**Comment by HelenAnalis** [comment]
Добрый день. Задача реализована в виде схемы http://www.gliffy.com/go/publish/image/8642935/L.png

**Comment by VadimGulich** [comment]
Спасибо

**Comment by rostag** [comment]
@HelenAnalis — дякую вам, результат супер! Але не вистачає заголовка — щоб з першого погляду було ясно, про що ця схема. Зробите? Можу допомогти. Маю фотошоп )

**Comment by rostag** [comment]
Пропоную такий варіант:
![igov-scheme](https://cloud.githubusercontent.com/assets/451410/9355678/e705611a-4683-11e5-8414-ec504f039b0e.png)

**Comment by rostag** [comment]
Пропоную також на основі даної схеми з заголовком зробити шаблони Cover Photo / 
 User Photo для Facebook / Twitter / LinkedIn / GooglePlus та інших соцмереж.

Тоді учасники проекту зможуть використати їх на своїх сторінках і тим замим сприяти залученню нових людей у проект.

Думаю, це допоможе нам у виконанні таску #303

**Comment by bvv4ik** [comment]
Согласен с @rostag !

**Comment by HelenAnalis** [comment]
Уважаемый @rostag, спасибо за идею. Действительно, дельное предложение. Обязательно добавлю заголовок, но так как схема динамичная и предполагается возможность ее актуализации, думаю, стоит это реализовать в gliffy, а не в фотошопе.

**Comment by rostag** [comment]
@HelenAnalis — цілком згоден, краще інтегрувати заголовок у gliffy. Я можу підготувати зображення та еспортувати його з фотошопу — для подальшого використання у gliffy.

**Comment by HelenAnalis** [comment]
Добрый день. Спасибо за предожение. Я уже реализовала, посмотрите, пожалуйста. Мне кажется, получилось неплохо )))

**Comment by rostag** [comment]
@HelenAnalis — дякую, але не бачу посилання )

**Comment by bvv4ik** [comment]
я так понимаю - все сделано
