### ISSUE TITLE
Функционал [S3] - Ошибка "Помилка. SYSTEM_ERR null" после ввода времени, даты и нажатия "Опрацювати"

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#598]
В дашборде нет возможности отработать таску.
![bug_igov_09](https://cloud.githubusercontent.com/assets/12996514/8843790/eaee9f5e-3115-11e5-94b7-6f3d39561a15.jpg)

**Comment by bvv4ik** [comment]
это глобальная проблема... она решается сейчас...

**Comment by bvv4ik** [comment]
вроде должно было уже починиться

**Comment by RoOmel** [comment]
нет, ошибка та же самая
как правильно вводить время и дату?
на той же странице слева один пример ввода, а справа - другой

**Comment by bvv4ik** [comment]
может просто кривой БП, была попытка создать новый процесс?

**Comment by bvv4ik** [comment]
это точно какой-то старый поломанный процесс... нужно "с нуля" создать и на нем проверять
не должно быть ошибок
