### ISSUE TITLE
Отработка таски в дашборде

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#599]
1.1 Ошибка "Помилка. SYSTEM_ERR null" после ввода времени, даты и нажатия "Опрацювати" - для юзера ничего не означает.
![bug_igov_09](https://cloud.githubusercontent.com/assets/12996514/8843819/510bb664-3116-11e5-93a2-1524503c123a.jpg)
1.2. Надо сделать предзаполнение поля "В разі надання послуги, вкажіть час/дату, коли авто може пройти огляд" для наглядности и корректности ввода;
1.3. Должна быть возможность удалить прикреплённый файл

**Comment by bvv4ik** [comment]
1) зачем здесь дубль? https://github.com/e-government-ua/i/issues/598
2) уважаемый @RoOmel давайте все то что "должно быть" и "надо сделать" - будут решать коллегиально все те, у кого эта функция. Вы можете только предложить, и предлагать нужно не в issue, а другими способами (например в Слак-е или в каком-т ообщем файле гуглодока)
т.к., повторяюсь, все такие issue - очень сильно мешают работать с реальными важными задачами.

прошу все это перенести в соответствующий файл (ссылка есть у Антона Сыча) и закрыть issue

**Comment by bvv4ik** [comment]
зависла
