### ISSUE TITLE
Реализовать сервис на wf-base, для подгрузки контента определенных файлов-шаблонов на сервере.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#600]
- [x] 1) Сервис назвать getPatternFile
Параметры:
sPathFile - строковое название папки и файла (например: print/file.html)
sContentType - строковой тип контента
Возвращать контент указанного файла.
(у этого cthdbcf должна быть и простая возможность вызова как обычного метода из явы)
- [x] 2) Папки смотреть начиная с корня классов (т.е. "\i\wf-region\src\main\resources\patterns",
и убедиться, что в продеплоеном виде берется именно этот каталог в качестве исходного
- [x] 3) создать в проекте соответствующую папку "patterns" по пути "\i\wf-region\src\main\resources\patterns"
- [x] 4) Не допускать, чтоб в параметре "sPathFile" встречались "..", которые позволят сослаться на папку, уровнем выше.
- [x] 5) задавая в хеадере респонса тот контенттайп, что указан в "sContentType" - отдавать контент файла.
- [x] 6) описать в доке с АПИ

**Comment by bvv4ik** [comment]
уже реализовано(как дополнение) - параллельное решение для прямого действия в юзертасках.

т.е. достаточно указать в переменной "sBody" содержимое "[pattern/print/subsidy.html]" и оно будет заменено на содержимое файла "pattern/print/subsidy.html"

Пока реализована поддержка такого перечня файлов:
pattern/print/subsidy.html
pattern/print/1.html
pattern/print/2.html
pattern/print/3.html
pattern/print/4.html
pattern/print/5.html

**Comment by bvv4ik** [comment]
только в юзертасках листенер обязательно должен быть fileTaskInheritance

**Comment by LamronNu** [comment]
документация: https://github.com/e-government-ua/i/blob/test/docs/specification.md#30_workWithPatternFiles

для теста:
сейчас на сервере доступны такие файлы-шаблоны:
тестовые "пустышки":
* report/report1.html
* report1.html

"реальные" шаблоны:
* print/subsidy_zayava.html
* print//subsidy_declaration.html

для тестирования можно попробовать просмотреть их с разным контент-тайпом (в доке есть пример). 
для корректного запроса слеши в sPathFile в урл-е нужно дублировать.

**Comment by nazarenkod** [comment]
Работает согласно описанию.
