### ISSUE TITLE
Несанкционированный доступ к админке [S2]

### ISSUE THREAD

**Issue by DmitroYatsuk** [e-government-ua/i#601]
Windows XP, Chrome 43.0.2357.134 m;
На главной странице, раздел Міліція та ДАІ: Надання довідки про відсутність (наявність) судимості або обмежень, передбачених кримінально-процесуальним законодавством України.
Переход в админский режим
Для перехода: Послуги - Міліція та ДАЇ - Надання довідки про відсутність або наявність судимості(вибір міста) - Вхід IDBank - Формування/відправка заявки - Замовити послугу - Возвращение на https://test.igov.org.ua/
http://screencast.com/t/CL7LDlfXYXBU

**Comment by bvv4ik** [comment]
) это тестовый)
на тестовом при авторизации под тестовым аккаунтом так и должно быть
