### ISSUE TITLE
На дашборде добавить еще одно меню "Сервис", и разместить там раздел определения шаблонов, генерации и просмотра сгенерированых слотов.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#604]
Разместить в разделе:

- [x] 1) Комбобокс выбора одного из доступных БП, как это реализовано по:
https://github.com/e-government-ua/i/issues/609
(при выборе автоматом заполнять таблицы ниже п.2 и п.3)

- [x] 2) Блок шаблонов: "Список рабочего времени недели"
- [x] 2.1. Список из колонок:
Номер;Дни недели;Временной промежуток
- кнопка "удалить" и "изменить" напротив каждой кнопки (удаление - вызывает сервис удаления записи и перезагружает список в таблице)
- Кнопка "Добавить"
- при том "Добавить" и "изменить" - открывают диалог п.п.2.2., а "изменить" - переносит туда данные
- Получается список по сервису /flow/removeSheduleFlowIncludes
- [x] 2.2. Диалог(div): "Выберите рабочие дни недели"
- Инпут - "Название"
- Инпут - "Время с"
- Инпут - "Время по"
- Чекбокс - Пн
- Чекбокс - Вт
- Чекбокс - Ср
- Чекбокс - Чт
- Чекбокс - Пт
- Чекбокс - Сб
- Чекбокс - Вс
- Инпут Число "Длительность слота" (например 15)
- Комбобокс тип-а длительности слота (Minute-Минут,Hour-Часов)
- Инпут "Выражение-формула расписания" (Например: {"0 0/15 14-15 ? * MON,TUE,THU,FRI":"PT15M"})
- Кнопка - "Добавить" (или "сохранить", если было редактирование п.2.1.)
- Добавляется и изменяется пункт по сервису /flow/setSheduleFlowInclude
- Удаляется пункт по сервису /flow/setSheduleFlowInclude

- [x] 3) Блок шаблонов: "Список исключений рабочего времени дат"
- [x] 3.1. Список из колонок:
Номер;Дата;Временной промежуток
- кнопка "удалить" и "изменить" напротив каждой кнопки  (удаление - вызывает сервис удаления записи и перезагружает список в таблице)
- Кнопка "Добавить"
- при том "Добавить" и "изменить" - открывают диалог п.п.3.2., а "изменить" - переносит туда данные
- Получается список по сервису /flow/getSheduleFlowExcludes
- [x] 3.2. Диалог(div): "День и временной промежуток исключения"
- Инпут - "Название"
- Инпут - "Время с"
- Инпут - "Время по"
- Инпут - "Дата"
- Кнопка - "Добавить" (или "сохранить", если было редактирование п.3.1.)
- Добавляется и изменяется пункт по сервису /flow/setSheduleFlowExclude
- Удаляется пункт по сервису /flow/removeSheduleFlowExclude

- [x] 4) Блок "Генерация слотов расписания"
- Инпут - "Дата-время с"
- Инпут - "Дата-время по"
- Кнопка - "Сгенерировать" - вызывает по критерию п.1 (фактически и списку п.2) - "сервис генерации" (/flow/buildFlowSlots) и следом вызывает "по каждой строке" п.3 - "сервис удалений"  (/flow/clearFlowSlots).
- Кнопка - "Удалить сгенерированное" - вызывает по по параметрам текущегго пункта - "сервис удалений" (/flow/clearFlowSlots)

- [x] 5) Блок "Посмотреть текущий график и занятые слоты"
- Выберите дату (календарик). Инпут - "Дата"
- После выбора даты показывается простая таблица:
- Таблица:
------
| Промежуток | Статус |
------
| 08:00 - 08:15 | Свободно |
------
| 08:15 - 09:30 | ФИО 1 |
------
| |  ФИО 2 |
------
| |  ФИО 3 |
------
...
------
| 09:30-10:30 | Свободно |
------
| 11:30-11:45 | ФИО 1 |
------
- Получается список по сервису /flow/getFlowSlots_ServiceData

Сервисы(АПИ) генерации/удаления слотов(и др.), описанном на вики:
https://github.com/e-government-ua/i/blob/test/docs/specification.md#18_workWithFlowSlot

Остальные сервисы реализуются по таске:
https://github.com/e-government-ua/i/issues/605

Основной концепт:
https://docs.google.com/document/d/1Jd3LODo2Nl4EsXdvqrK8yZ5j_Hf24vuCgQhJb06TETI/edit

**Comment by tseshevsky** [comment]
Замержил в тест. Сделано все, кроме генерации слотов расписания. Генерация работает наполовину - buildFlowSlots работает, clearFlowSlots - нет.

**Comment by bvv4ik** [comment]
тестить нужно только то что в таске (реально реализовано на много больше(с запасом), но то на перспективу)...

генерировать нужно только на основании уже существующих записей инклудов (добавленные в интерфейсе работать не будут пока что)

**Comment by bvv4ik** [comment]
Заходить сюда: https://test.region.igov.org.ua:6948/services

**Comment by bvv4ik** [comment]
@tseshevsky а под каким логином/паролем заходить, чтоб нужный БП в списке увидеть?

**Comment by tseshevsky** [comment]
Стандартными: kermit/kermit. Выбирать "Киев - регистрация авто с пробегом в МРЕВ" или "Днепропетровск - регистрация авто с пробегом в МРЕВ" в выборе Бизнес-процесса.

**Comment by RoOmel** [comment]
Задачи реализованы согласно ТЗ.
Ошибки интерфейса:
1) Кнопку с надписью "Добавити" надо переименовать с азаровского языка на укр-кий "Додати"
Улучшения:
1) 2.1, 3.1 Кнопки с пиктограммами "удалить", "изменить" желательно снабдить поп-ап сообщениями, кот. всплывают при получении фокуса

**Comment by tseshevsky** [comment]
Исправил и улучшил.

**Comment by RoOmel** [comment]
Странно, что-то я не увидел изменения текста и поп-ап сообщений вкладок "Робочоий час тижня", "Винятки робочого часу".
 ![bug_igov_14_01](https://cloud.githubusercontent.com/assets/12996514/9651717/e87c35a6-521c-11e5-9bc6-d785b5584cb8.jpg)

**Comment by tseshevsky** [comment]
Да, я напортачил с ветками. Прямо в тест залил.

**Comment by tseshevsky** [comment]
Переделал - теперь в ветке сделал и вмержил в тест.

**Comment by RoOmel** [comment]
На каком сайте обновление смотреть?
На https://test.region.igov.org.ua:6948/services
всё по старому, не вижу изменений

**Comment by tseshevsky** [comment]
Перебилдил. Появились изменения.

**Comment by RoOmel** [comment]
Подтверждаю, задача реализована согласно ТЗ
