### ISSUE TITLE
На бэке централа создать сервисы добавления, изменения и удаления шаблонов расписаний включений и исключений (слотов потоков) а так-же доработать сервис получения слотов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#605]
- [x] 1) Добавить в сущность "FlowProperty":
- булевое поле "bExclude"
- стринговое поле "sName"
- стринговое поле "sRegionTime"
- стринговое поле "saRegionWeekDay"
- стринговое поле "sDateTimeAt"
- стринговое поле "sDateTimeTo"

- [x] 2) Сервис /flow/getSheduleFlowIncludes - получения расписаний включений
Параметры:
nID_Flow_ServiceData - ИД-номер потока
Ответ:
Массив объектов сущности:
FlowProperty, где bExclude=false

- [x] 3) Сервис /flow/setSheduleFlowInclude - добавления/изменения расписания включений
Параметры:
nID - ИД-номер //опциональный ,если задан - редактирование
nID_Flow_ServiceData - ИД-номер потока 
sName - Строка-название ("Вечерний прием")
sRegionTime - Строка период времени ("14:16-16-30")
saRegionWeekDay - Массив дней недели ("su,mo,tu")
sDateTimeAt - Строка-дата начала(на) в формате YYYY-MM-DD hh:mm:ss ("2015-07-31 19:00:00")
sDateTimeTo - Строка-дата конца(к) в формате YYYY-MM-DD hh:mm:ss ("2015-07-31 23:00:00")

- [x] 4) Сервис /flow/removeSheduleFlowInclude - удаления расписания включений
Параметры:
nID_Flow_ServiceData - ИД-номер потока 
nID - ИД-номер
Ответ:
Массив объектов сущности:
FlowProperty, где bExclude=true

- [x] 5) Сервис /flow/getSheduleFlowExcludes - получения расписаний исключений
Параметры:
nID_FlowSlot - ИД-номер потока слотов

- [x] 6) Сервис /flow/setSheduleFlowExclude - добавления/изменения расписания исключений
Параметры:
nID - ИД-номер //опциональный ,если задан - редактирование
nID_Flow_ServiceData - ИД-номер потока 
sName - Строка-название ("Вечерний прием")
sRegionTime - Строка период времени ("14:16-16-30")
saRegionWeekDay - Массив дней недели ("su,mo,tu")
sDateTimeAt - Строка-дата начала(на) в формате YYYY-MM-DD hh:mm:ss ("2015-07-31 19:00:00")
sDateTimeTo - Строка-дата конца(к) в формате YYYY-MM-DD hh:mm:ss ("2015-07-31 23:00:00")

- [x] 7) Сервис /flow/removeSheduleFlowExclude - удаления расписания исключений
Параметры:
nID_Flow_ServiceData - ИД-номер потока 
nID - ИД-номер

- [x] 8) Доработать сервис /flow/getFlowSlots_ServiceData, чтоб можно было задать параметр sDate, в который передавать дату (в формате: YYYY-MM-DD), за которую нужно ролучить слоты

**Comment by ASkosyr** [comment]
Планируемая дата поставки - к понедельнику 3 августа

**Comment by ASkosyr** [comment]
Добавил описание сервисов
https://github.com/e-government-ua/i/blob/test/docs/specification.md#24_getBPForUsers

**Comment by ASkosyr** [comment]
Примеры вызовов сервисов для тестирования описаны в документации по линке выше :)

**Comment by nazarenkod** [comment]
Все работает согласно описанию.
