### ISSUE TITLE
Помилка у слові Заявка(Завявка)

### ISSUE THREAD

**Issue by dmitriy-timofeev** [e-government-ua/i#606]
У вкладці Статуси, при вводі номера недійсної заявки та натисканні Переглянути, в підсказці є помилка у слові Заявка(Завявка). 
Скрін тут http://screencast.com/t/2QOwjeyfSrH

**Comment by rostag** [comment]
@bvv4ik - я правильно зрозумів, що такі issues (типу виправлення опечаток) треба одразу до беклогу заносити?

**Comment by dmitriy-timofeev** [comment]
Так.


2015-07-29 14:26 GMT+04:00 Rostyslav Siryk <notifications@github.com>:

**Comment by rostag** [comment]
Схоже, це вже виправлено - https://test.igov.org.ua/order/search

**Comment by bvv4ik** [comment]
ну, тогда закрываем, чтоли?

**Comment by smit-pb** [comment]
Заменено на "Невірний номер!".

Можно считать как исправлено.
