### ISSUE TITLE
На бэке централа доработать сущность HistoryEvent_Service и организовать вызов ее сервисов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#607]
- [ ] 1. На бэке централа добавить для сущности HistoryEvent_Service поле sDate типа "дата-время" (так-же как и для сущности Document)

- [ ] 2. Через уже реализованный механизм фильтра(при вызове любого сервиса), на регионале реализовать сервиса центрального портала:
- [x] 2.1. addHistoryEvent_Service при каждом добавлении таски Активити (которое используются на центральном портале, а вызывает региональный)
- [ ] 2.2. updateHistoryEvent_Service при каждом изменении таски Активити (ассайн и сабмит, которые используются на региональном дашборде)

- [ ] 3. В поля проставлять следующие данные:
- [ ] 3.1  В поле со статусом проставлять название юзертаски (task.getName()) (при изменении или "Заявка подана", при создании)
- [ ] 3.2 В поле sData проставлять текущую дату создания/правки записи
- [ ] 3.3 В sID при создании записи проставлять первичный ИД, который получается при создании процесса (который именно возвращается активити), и далее его не менять)

- [ ] 4. Убедиться что события по п.2 сохраняются также и в Мой Журнал (как это происходит и с остальными событиями по загрузке документа и предоставлению к нему доступа)

**Comment by RoOmel** [comment]
Согласно доки https://github.com/e-government-ua/i/blob/test/docs/specification.md#17_workWithHistoryEvent_Services
запрос http://test.igov.org.ua/wf-central/service/services/addHistoryEvent_Service?nID_Task=2&sStatus=new&nID_Subject=2
"ругается" на отсутствие параметров

**Comment by bvv4ik** [comment]
@OlgaTurenko Ольга, прошу помочь в тестировании

**Comment by bvv4ik** [comment]
уже все давно подвязано на фронт и можно посмотреть в Мой Журнал историю всех событий...

**Comment by RoOmel** [comment]
Согласно ТЗ:
 4. События сохраняются в Мой Журнал:
4.1 Дата создания записи
4.2 Название
