### ISSUE TITLE
На бэке централа доработать сервис getServicesTree дополнительными фильтрами

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#608]
- [x] 1) Добавить в сервис getServicesTree так, чтоб если название услуги начинается с символа "_", то выводить такой элемент каталога только если флаг bTest в классе GeneralConfig равняется true (иначе не включать его в выдаваемый каталог)

- [x] 2) Добавить в сервис getServicesTree опциональный параметр "asID_Place_UA" , где через запятую, приходит массив строк-ИД мест.
Например:
getServicesTree?asID_Place_UA=3200000000,8000000000
где:
sID_UA = "3200000000" (КИЇВСЬКА ОБЛАСТЬ/М.КИЇВ)
sID_UA = "8000000000" (М.КИЇВ)
(коды взяты из всеукраинского классификатора мест: http://www.ukrstat.gov.ua/klasf/klasif/koatuu.rar)

Если параметр asID_Place_UA задан, то накладывать фильтр на выдаваемый каталог услуг. т.е. выводить только те услуги, в которых в подуслугах (в ServiceData) есть те, которые находятся в указанных регионах или городах. (связанные сущности Region и City)

ВАЖНО: При этом, пока что:
3200000000 - приравнивать к региону "Киевский"
8000000000 - приравнивать к городу"Киев"
Остальные коды пока вообще игнорировать!!!
(т.е. выдавать полный каталог, если ни одного из вышеперечисленных кодов не указано)

**Comment by 40rn05lyv** [comment]
Одне питання - який параметр мається на увазі під "название услуги"? sSubjectOperatorName? (див. https://test.igov.org.ua/wf-central/service/services/getServicesTree)

**Comment by bvv4ik** [comment]
"aService":[{"sSubjectOperatorName":"Міністерство Внутрішніх Справ","subjectOperatorName":"Міністерство Внутрішніх Справ","nID":1,"sName":"Надання довідки про відсутність (наявність) судимості або обмежень, передбачених кримінально-процесуальним законодавством України."


вот тут - это "sName":"Надання довід....

**Comment by 40rn05lyv** [comment]
Туплю..

**Comment by 40rn05lyv** [comment]
Залишилось інтегр тести написати

**Comment by bvv4ik** [comment]
Класс!
А вот тесты на эту фифу, пока не стоит писать... т.к. через некоторое время доделается таска по сущности Place, и данная реализация немного поправится, в связи с этим... вот тогда и можно будет тесты написать

**Comment by 40rn05lyv** [comment]
Імплементовано. Тест на №2 (фільтр по "asID_Place_UA") все-таки невеликий додав.
Доку (https://github.com/e-government-ua/i/blob/test/docs/specification.md#15_workWithServices) оновлювати?

**Comment by bvv4ik** [comment]
гуд,
да, доку обязательно ... сори, сам забыл в таску дописать....

**Comment by RoOmel** [comment]
Согласно доки протестировано:
1. Запросы с фильтром sFind - согласно ТЗ;
2. Запросы с фильтром asID_Place_UA - согласно ТЗ;
3. Запросы с фильтром general.bTest - при значении false или true возвращает сервисы, у которых параметр "sName": начинается с "_";
Если 3-тий пункт не приоритетный - закрываю таску

**Comment by bvv4ik** [comment]
3-й пункт важный, странно...

@RoOmel а как эмулировалось "фильтром general.bTest - при значении false или true"?

**Comment by bvv4ik** [comment]
кстати, уже и для Киева заюзали эту доработку)))
https://test.kiev.igov.org.ua

**Comment by RoOmel** [comment]
Согласно доки "Если general.bTest = false, сервисы, имя которых начинается с "_", не вовращаются."апросом нельзя, зачем тогда 
В качестве параметра запроса подставлял general.bTest и его значения false или true.
Если протестировать это нельзя запросом - зачем тогда указывать в описании?

**Comment by bvv4ik** [comment]
это можно протестировать подстановкой этого параметра на сервере... по ssh доступ могу дать на тестовый... нужен только пабликкей

**Comment by RoOmel** [comment]
ок, я готов

**Comment by bvv4ik** [comment]
ок) тогда паблик кей можно прямо сюда скинуть)

**Comment by RoOmel** [comment]
---- BEGIN SSH2 PUBLIC KEY ----
Comment: "rsa-key-20150814"
AAAAB3NzaC1yc2EAAAABJQAAAQEAh+sJQSKfVaKDknCJDdPSnFZxQyGSq2B8kXuZ
GNgyBeMbJr0fQTlLedlKSf4NEfhNjQyqGG6VTGVjq0AO8CdSwftVltWShHSIXq2v
aiartN4DZy6JE9nU9d106LjdoK7FVbDnQVKaHXX+zbdkUDcYXai0eR5DwDvcmnj/
ruqVrvlafhjnQkmJ19u0fGB+/GaWOS0mYHDJyia+xg+ghmInLUQ9MMI9EbPd3R++
yuw0nh3/yr60onf4sCa93C3MhtNfM0OHgsa5J+TMgtLZgpzqSRwWj5VMvoBW4ZI2
iOQLsl1IXJtLVy1dzxz2Mj0yA+Abj3vBWKPFtCkyoc5xYyyDTQ==
---- END SSH2 PUBLIC KEY ----

**Comment by bvv4ik** [comment]
ключ добавил, но чето он какойто не стандартный
обычно он похож на:
ssh-dss AAAAB3NzaC1kc3MAAACBAOiu94Myqkb7A5wJaqSHS6JTmpcIqIr68t0Zi8wFyHGMqxF5wPyTi0t2AO45f//GVTHX7GH78kmZvCyhIPacCdK3R9JfmviSE5B6lfScetnRbr+OSD/dgo9bOlBLbIbQB3jEyX65m8epowa0iIQwgfOX4oULRCRyIa8iDFv8TUhjAAAAFQCSoOq4MihRHgAvbSeyqipzpUDEOQAAAIEAl9rtozKJ6BX2+MuLJyWl05EkptceUS/ChikbG0iDTIUIdZwgifV0kibDloxRqxR1PE5B256zKCKQNzRMH2Th5CCjRGbd3l+07kHtAw9R96GxYoKrxF+JfRK0iEyHMrXdIPqj0kTa9U5GPfBqNHgEt4gHZfiP3tvUyYADnowI78sAAACBAKaR1DD0ksCDL3axVWhl9nLiXVPKeyB3FUHALoCkBvoY6iI15/X5GZhuNmOzwzkBsDuhvd0efvgDOKOiT2nn7cmdtQbUlu1ZM4UeipDRDpyaFm9giAp7c9Fgc621zlVWZ42l8/VjZWZ01yM8mhuCBvy0BgBFl34r1iygRviTni3l borik@Borovik-PC

ну то ладно, может и заработает...

теперь нужно заходить на sybase@test.igov.org.ua по ssh
там в папке: /sybase/tomcat_wf-central/conf 
есть файл: AS.properties
где есть параметр: general.bTest = true
который можно переключить временно в false. а потом ОБЯЗАТЕЛЬНО вернуть обратно

переключив, нужно вначале запустить файл:
/sybase/tomcat_wf-central/bin/shutdown.sh
и сразу: /sybase/tomcat_wf-central/bin/startup.sh
(это для перезагрузки сервера, чтоб параметр вступил в силу)

т.е. вначале включить false и перегрузить и потом обратно и перегрузить

**Comment by RoOmel** [comment]
при установке соединения сообщение консоли
"Host key did not appear in manually configured list"

**Comment by bvv4ik** [comment]
попробуй в Putty

**Comment by RoOmel** [comment]
Как раз в Putty и пробовал

**Comment by bvv4ik** [comment]
по факту проверено уже на боевом (там эта доработка)
п.1 работает
можно таску закрывать

**Comment by bvv4ik** [comment]
но, работу по ssh все-же стоит наладить...
для начала все-же дать актуальній публичній ключ такого формата что я написал віше...
коллеги-сисадмині, наверняка смогут помоч в єтом
