### ISSUE TITLE
На дашборде, в разделе "Звіт" в блоке "Статистика" - заменить поле input (БП:) - на комбобокс, с автоматической подгрузкой туда списка доступных лишь данному авторизированому сотруднику ИД бизнеспроцессов, и на бєке ноды обязательно передавать при вызове сервиса "Статистики"  - логин авторизованного пользователя

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#609]
- [ ] 1) Подгружать список доступных БП для данного авторизированного пользователя с сервиса "getLoginBPs", описание которого есть в вики: https://github.com/e-government-ua/i/blob/test/docs/specification.md#23_getBPForUsers (написан по таске: https://github.com/e-government-ua/i/issues/570)

- [ ] 2) В комбобоксе отображать нормальные названия БП, а их ИД-шки использовать как id пунктов комбобокса

- [ ] 3) при вызове сервиса "Статистики"(для которого будет выбираться данный ИД процесса)  - всегда передавать на бэке ноды логин авторизованного пользователя.

П.С.: Данная задача является продолжением(завершением) исходной задачи:
https://github.com/e-government-ua/i/issues/574

![image](https://cloud.githubusercontent.com/assets/4208821/8958994/e4ad8bc8-3610-11e5-88b2-ee2f4dda1a90.png)

**Comment by VadimGulich** [comment]
протестировано, можно на боевой
