### ISSUE TITLE
На дашборде реализовать возможность выбора одного из нескольких доступных шаблонов формы печати для таски, вместо одного.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#610]
- [x] 1. Возле кнопки "Роздрукувати" (справа) разместить комбобокс, в котором перечислять все доступные шаблоны для печати.
- [x] 2. Список шаблонов формировать так:
- [x] 2.1. Смотреть все поля в форме, с id=sPatternPrint_*
- [x] 2.2. Брать название шаблона из атрибута "name" каждого из полей п.п.2.1.
- [x] 2.3. Сортировать пункты комбобокса в порядке id п.п.1.1.
(т.е. sPatternPrint_1, sPatternPrint_2, sPatternPrint_3)
- [x] 3. Поправить работу кнопки "Роздрукувати" так, чтоб использовалось значение (value) выбранного поля (вместо текущего варианта реализации, когда берется значение поля sBody)

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/9244107/bc2d2d3e-41a0-11e5-81d1-806aa98b140d.png)

Задача реализована в не полном объеме 
1) Нет шаблонов для печати
2) "Криво" отображается комбобокс

**Comment by bvv4ik** [comment]
1. тут просто в данной таске их и не должно быть.. нужно искать ту, где они есть... кажись субсидии
2. с его визуализацией пока не замарачиваемся... когда будем редизайнить всю форму тогда и поправим в т.ч. и это.. пока - главное чтоб работало

**Comment by VadimGulich** [comment]
В https://test-version.region.igov.org.ua/tasks   не попадают заявки 
Пример заявки:  25150209

**Comment by bvv4ik** [comment]
так для "https://test-version.region.igov.org.ua/tasks " нужно их подавать с "https://test-version.igov.org.ua" (это бета-тестовый)

**Comment by VadimGulich** [comment]
Поле появилось и возле кнопки "Взять в работу"
![image](https://cloud.githubusercontent.com/assets/12964120/9271486/e9bdc3ca-4282-11e5-9941-b398f63e2257.png)


Возле "распечатать все ок:"
![image](https://cloud.githubusercontent.com/assets/12964120/9271484/e5264e90-4282-11e5-9914-deebe210200f.png)

**Comment by bvv4ik** [comment]
через 2 мин завершится деплой и можно будет проверять

**Comment by VadimGulich** [comment]
Ошибка : Всплывающее окно блокирует работу https://test.region.igov.org.ua:6948/tasks
(сообщение в окне с "кривым переводом")

Шаги:
1) Войти в https://test.region.igov.org.ua:6948/tasks 
2) Выбрать пункт - В работе
3) Открыть заявку по субсид.  , пример: (2015-8-3 15:5) Отримання субсидії на оплату житлово-комунальних послуг | Взяти в роботу   (#2075403)
4) Из выпадающего списка выбрать печать декларации
5) Нажать печать (после зап обяз.полей)
6) Закрыть окно печати
7) Перейти в меню - Необработанные

Появилось всплывающее сообщение которое блокирует работу : 
![image](https://cloud.githubusercontent.com/assets/12964120/9460473/0622de80-4b0f-11e5-85ff-166b51a6c17c.png)

**Comment by smit-pb** [comment]
Ошибка больше не воспроизводиться.

**Comment by smit-pb** [comment]
Совместно смогли воспроизвести.
Использовали Пользователя "кермит".
Заявка - №20751615
Рядом с кнопкой "Распечатать" выбираем из списка - любой из 2-х "Паттернов"
Нажать печать (после зап обяз.полей)
Закрыть окно печати
Перейти в меню - Необработанные

Появилось всплывающее сообщение которое блокирует работу : 
"Не выбран шаблон для печати".

Актуально для Chrome и FireFox последних версий.

**Comment by smit-pb** [comment]
Данную проблему - исправлять будут ? или необходима отдельно оформленная задача ?

**Comment by bvv4ik** [comment]
эта проблема известна давненько... она отдельно идет, данной таски она не касается

**Comment by smit-pb** [comment]
Тогда - таки можно закрывать задачку.
