### ISSUE TITLE
При создании заявки на услугу и допущением ошибок в анкете отображается уведомление с ошибкой, которое не пропадает, пока не подашь заявку на новую услугу

### ISSUE THREAD

**Issue by bzhest** [e-government-ua/i#611]
Вопрос к дополнению задачи - https://github.com/e-government-ua/i/issues/459. [S4].
Windows XP, Chrome 44.0.2403.107 m, FireFox 39.0
Для перехода: Послуги- "Видача копії рішення міської ради, витягу з протоколу сесії міської ради, витягу з протоколу засідання постійної комісії міської ради" - Выбор Днепропетровская Область, Днепропетровск - Вхід IDBank

При заполнении обязательных полей с некорректными данными и нажатии [замовити послугу] отображается сверху уведомление с ошибкой:  ПОМИЛКАSYSTEM_ERR For input string: "Тринадцать". 
1) Это уведомление будет отображаться, даже если переходить на другие страницы сайта и не пропадет пока на поле с ошибкой [X] не нажать, либо F5, либо войти в IDBank - тогда сообщение об ошибке пропадет
2)Отображается уведомление об ошибке в 1 заполненном поле (в этом случае значение "№"), хотя в других полях так же забиты были некорректные данные.
Скрин заполнения формы - 
![default](https://cloud.githubusercontent.com/assets/12616696/8980102/eb735360-36b6-11e5-8f64-3509e52013ec.JPG)
Скрин с Текстом ошибки
![default](https://cloud.githubusercontent.com/assets/12616696/8980108/f42088de-36b6-11e5-9775-54edcf3583fd.JPG)

**Comment by bvv4ik** [comment]
это просто не дореализованная часть по таске:
https://github.com/e-government-ua/i/issues/459

прошу этут таску закрыть, а замечание написать в указанной таске
