### ISSUE TITLE
Привести в порядок документацию по нашим АПИ на Вики

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#617]
- [ ] 1) Все образцы обьектов запросов должны быть обрамлены соответствующим образом (там есть достойные примеры)
- [ ] 2) каждый пункт и подпункт сделать в одном стиле.. сейчас все в разнобой

План приведения документации в лучший вид:
1) Убрать в примере ответа //[].
2) Убрать фигурные скобки с названий параметров запроса.
3) Контектст отдельно, параметры запроса отдельно.
4) Там гдн Get запросы по возможности подобавлять примеры.
5) В первую группу отнести логин, логаут и назвать "Аутентификация пользователя".
6) Сервиса активити в отдельную группу объединить "Activiti".
7) Вконце описание мерчантов совсем плохи, обратить внимание
8) Сделать красивую структуру json запросов и ответов (хороший пример http://server:port/wf-central/service/services/setService )
9) Добавить пример запроса в HTTP Context: http://server:port/wf-central/service/services/setService - (взять из getService) 

Структура:

Название раздела (жирным, самый крупный шрифт, все остальное будет мельче)
Описание что сервис делает (выделать на общем фоне, возможно размером шрифта)
Тип запроса (GET, POST, PUT, DELETE) жирным
Контекст жирным
Параметры хедера (если есть)
Параметры запроса в виде списка (навание - расшифровка)
Пример запроса (слово "Пример:" жирным и после с новой строки сам пример, если GET запрос, то в виде ссылки)
Пример ответа (слово "Ответ:" жирным и после с новой строки сам ответ.)
Разделитель сервисов в группе (серая горизонтальная полоса)

ВАЖНО:
- правки нужно производить в ветке test а не в ветке master
- Переименовать раздел:
18. Работа со слотами потока
в
18. Работа с "Электронным Расписанием" (с потоками, слотами и тикетами)
и поместить в нем, в т.ч.:
24. Получение расписаний включений 
25. Добавление/изменение расписания включений 
26. Удаление расписания включений 
27. Получение расписаний исключений 
28. Добавление/изменение расписания исключения 
29. Удаление расписания исключений

**Comment by rodionbykov** [comment]
Предложение по организации. 
- Общее описание системы, зачем она создается
- Термины (закрепить названия, чтобы одна вещь всегда называлась одним словом), сущности (e.g. пользователи, заявки на документы, документы) и актеры (кто взаимодейтсвует посредством системы)
- Общая диаграмма системы
- Сценарии использования (актер-действие-результат)
- Описание бек-енда
- Описание клиента 
 = сервер
 = клиент
- Описание протоколов (енд-поинты, структура HTTP запросов/ответов)
- Описание системы аутентификации

(Как новичку в технологии, мне было трудно разобраться во всем по нынешним документам, по мере роста проекта приходящие разработчики не должны тратить много времени на изучение).

**Comment by bvv4ik** [comment]
по поводу того , что "порог входа в проект должен быть максимально легким" - однозначно согласен, к этому изначально стремились изначально, но т.к. проект, особенно на начальных стадиях, очень сильно менялся - небыло смысла особого все в деталях прописывать...
Сейчас уже занимаются рисованием связей всех сущностей(общая графическая схема всех взаимосвязей)... и так-же схемой компонентов системы в целом(отдельно)... + тут в АПИ наведем еще больше порядка...

а вот по поводу "зачем она создается", или "термины", "сценарии", "протоколы" - это все очень сильно будет загромождать общую доку... мы постараемся или полностью обойтись без этого(просто все стараться делать лаконично и при этом емко, в смысловой нагрузке)... или, какнибудь, в отдельном "вспомогательном файле" это реализовать... ведь протоколы и термины тут все стандартные, а название сущностей и их роль на схеме будет понятна...

может, еще несколько видео-роликов сделаем, но пользованию порталом(это будет лучше всяких слов)... если-б еще кто нашелся, кто готов был-бы этим заняться..))

**Comment by OlgaTurenko** [comment]
Есть один парень, он вроде как делает пробную версию видео. Ждем :)

**Comment by bvv4ik** [comment]
просьба учесть важное дополнение (которое только что добавил в таску):
- правки нужно производить в ветке test а не в ветке master
- Переименовать раздел:
18. Работа со слотами потока
в
18. Работа с "Электронным Расписанием" (с потоками, слотами и тикетами)
и поместить в нем, в т.ч.:
24. Получение расписаний включений 
25. Добавление/изменение расписания включений 
26. Удаление расписания включений 
27. Получение расписаний исключений 
28. Добавление/изменение расписания исключения 
29. Удаление расписания исключений

**Comment by bvv4ik** [comment]
@Zhinsheng
есть перспектива по этой таске или шансы не высоки?)

**Comment by Zhinsheng** [comment]
Добрый день
Мы с Ольгой обсуждали в скайпе, что я, как не программист, смогу выполнить
только маленький кусочек задачи - тот, который сделала. Остальное я просто
не сумею (моя специализация - написание текстовых инструкций)

**Comment by OlgaTurenko** [comment]
я хотела эту задачу дать Елене. Но если есть желающие - я с удовольствием посодействую!

**Comment by Zhinsheng** [comment]
Тогда как лучше поступить?


> я хотела эту задачу дать Елене. Но если есть желающие - я с
удовольствием посодействую!

**Comment by bvv4ik** [comment]
задача не актуально, т.к. реализовали механизм авто-генерации доков по АПИ (на вики первые ссылки)
