### ISSUE TITLE
В разделе статистики некорректно отображается список доступных процессов

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#618]
![image](https://cloud.githubusercontent.com/assets/11442397/9009458/fbabaaf4-37a9-11e5-9eac-1c6d91392b93.png)
![scr_1](https://cloud.githubusercontent.com/assets/11442397/9010076/9a3f6630-37ad-11e5-8503-e71af4b6ad04.JPG)
![scr_2](https://cloud.githubusercontent.com/assets/11442397/9010075/9a3c3d3e-37ad-11e5-8908-aa5c8d73de16.JPG)

в перечне процессов на продакшне не отображается доступный мне (пример наглядно на скринах )

**Comment by ASkosyr** [comment]
Сегодня вечером посмотрю

**Comment by ASkosyr** [comment]
Разобрался как парсить процесс и получать группы, которые могут запускать userTask
```
BpmnModel bpmnModel = repositoryService.getBpmnModel(processDef.getId());				

for (FlowElement flowElement: bpmnModel.getMainProcess().getFlowElements()){
	if (flowElement instanceof UserTask) {
	UserTask userTask = (UserTask)flowElement;
	List<String> candidateGroups = userTask.getCandidateGroups());
	}				
}
```

Пример получения модели через рест сервис


https://test.region.igov.org.ua/wf-region/service/repository/process-definitions/kiev_mreo_1:360:2037630/model

**Comment by ASkosyr** [comment]
задачу сделал

**Comment by VadimGulich** [comment]
БП отображаются , можно на боевой
