### ISSUE TITLE
mvn tomcat7:run не деплоїть wf-region

### ISSUE THREAD

**Issue by 40rn05lyv** [e-government-ua/i#621]
Степи:
1. Відкрити консоль.
2. Перейти у папку _wf-region_.
3. Виконати команду _mvn tomcat7:run_

Очікуваний результат:
http://localhost:8081/wf-region/service/rest/process-definitions поверне список процесів.
Див.: https://test.region.igov.org.ua/wf-region/service/rest/process-definitions

Реальний результат:
404 error.

Пояснення:
Команда _tomcat7:run_ по-дефолту деплоїть поточний проект. Відповідно, значення _warSourceDirectory_ задається як _wf-region\src\main\webapp_. Враховуючи, що цієї папки не існує, то нічого не деплоїться. 

Як вирішення потрібно перенести папку _wf-base/src/main/webapp_ і набір контролерів (наприклад, _ActivitiRestApiController_) до проекту _wf-region_. _wf-base_ повинен містити лише спільні базові класи. Наскільки я розумію, усі пакети, які починаються з _org.activiti_ повинні бути у _wf-region_.

**Comment by bvv4ik** [comment]
в том-то и дело, что wf-base в себе должен содержать все классі (ну, разве что кроме уж совсем персональніх для какого-то отдельного региона)... для того бєйс и создан... а уже регион содержать должен только бизнеспроцессы и проперти свои(ну и те "свои" классы, которыя нужны только для какого-то одного региона... но пока таких даже и нет)

wf-region сейчас деплоится везде на тестовіх и боевом, правда ручками... нужно подумать, как-бы поправить ПОМ, чтоб он таки мог деплоиться автоматом... кстати, на гласфиш он автоматом таки деплоится.. нужно только для томкэта что-то придумать

**Comment by 40rn05lyv** [comment]
Зрозумів лише після того як глянув на цю картинку https://cloud.githubusercontent.com/assets/11561028/7169325/0ea2ef22-e3cd-11e4-991d-42daaf0549a0.png (її варто оновити і поставити кудись у вікі).
Значить після реального запуску, у нас у репозиторії буде поряд з wf-region окремі проекти для кожної місцевої ради типу wf-dniprorada, wf-kyivrada і т.д., які міститимуть мінімум файлів.

Ще питання - для чого тоді нам мати 2 входи на адмінку: через https://test.igov.org.ua/wf-central/ і https://test.region.igov.org.ua/wf-region/ . Таке враження, що це побічний ефект wf-base і такого бути не повинно. Думаю потрібно зробити додатковий проект wf-region-base, щоб структура була наступна:

wf-base
wf-central extends wf-base
wf-region-base extends wf-base
wf-region extends wf-region-base
wf-kyivrada extends wf-region-base

У такому разі можна буде перенести папку webapp з wf-base у wf-region-base, плюс можливо ще якісь класи і таким чином wf-central міститиме лише те, що необхідно.

**Comment by bvv4ik** [comment]
"Значить після реального запуску, у нас у репозиторії буде поряд з wf-region окремі проекти для кожної місцевої ради типу wf-dniprorada, wf-kyivrada і т.д., які міститимуть мінімум файлів."
Да, совершенно верно!

"для чого тоді нам мати 2 входи на адмінку: через https://test.igov.org.ua/wf-central/ і https://test.region.igov.org.ua/wf-region/ ."
есть общенациональные Бизнес-Процессы (они должны лежать в wf-central), а есть региональные(wf-region)

"Таке враження, що це побічний ефект wf-base і такого бути не повинно. "
)) не, тут все норм, тут-то как раз все продумано...
так что ничего переносить не придется)

**Comment by bvv4ik** [comment]
удалось разобраться?

**Comment by 40rn05lyv** [comment]
Потрібно виконувати команду tomcat7:run-war - тоді попередньо виконується фаза package і  деплоїться коректний варник. Оновив доку.

Можна закривати.

**Comment by bvv4ik** [comment]
отлично, спасибо!
