### ISSUE TITLE
invalid_token при автентифікації через BankID на локальному серваку

### ISSUE THREAD

**Issue by 40rn05lyv** [e-government-ua/i#622]
Кроки:
1. Виконати з папки wf-central команду mvn tomcat7:run
2. Скопіювати _central-js/server/config/local.env.sample.js_ до _central-js/server/config/local.env.js_ .
3. Замінити 
    _ACTIVITI_PROTOCOL: 'https',_
    _ACTIVITI_HOSTNAME: 'test.igov.org.ua',_
на
    _ACTIVITI_PROTOCOL: 'http',_
    _ACTIVITI_HOSTNAME: 'localhost:8080',_
4. Виконати команду _central-js/_/_1_build_run.bat_
5. Зайти на сайт http://localhost:9000/ , вибрати послугу, вибрати місто, спробувати автентифікувати через BankID через ПриватБанк (логін: +380102030405, пароль: value, код: 123456).

Очікуваний результат:
Користувача перекидає на сторінку для заповнення його даних.

Реальний результат:
Помилка:
![image](https://cloud.githubusercontent.com/assets/1200215/9023171/4e0515de-3899-11e5-84d4-32eb0d6401f3.png)

**Comment by bvv4ik** [comment]
локально точно работало... какой-то момент упущен, видать, в доке...
нужно спросить у кого-то из ребят фронтэндщиков...
(я постараюсь поспрашивать, но, прошу, если есть возможность уточнить напрямую)

**Comment by bvv4ik** [comment]
тут больше похоже не на проблему аутентификации а именно попытке заюзать услугу с локального сервака... но нужно проверить, конечно, и убедиться..

**Comment by 40rn05lyv** [comment]
На робочому компі запрацювало... Мабуть попробую ще вдома на чистому проекті.

**Comment by bvv4ik** [comment]
все выяснил, будет работать локально, но только с https... и соотв. со сгенеренными сертификатами

**Comment by VadimGulich** [comment]
Ошибки больше (пока) не наблюдается , на данный момент протестировано и исправлено
