### ISSUE TITLE
Проблеми у роботі Головного Порталу на мобільних пристроях

### ISSUE THREAD

**Issue by rostag** [e-government-ua/i#623]
Дві помилки на смартфоні (чув скарги від користувачів, бачив сам):

1. Не працює мобільна версія головного меню — неможливо використати "Документи", "Статуси", "Мій журнал", та "Про портал" через меню (див. ілюстрацію, обвів червоним)
2. Footer сайту працює як "розпорка" і заважає сайту коректно, тобто на повну ширину, відобразитися на екрані (див. помаранчеву стрілку):

![image](https://cloud.githubusercontent.com/assets/451410/9023950/59c3c90c-38bb-11e5-8402-d982a501dd79.png)

CSS-фреймворк Bootstrap, на якому зроблено фронт-енд, пропонує рішения таких проблем, оскільки є mobile-first продуктом.

Спробую виправити ці дві помилки.

**Comment by rostag** [comment]
Меню не працює, тому що файл bootstrap.js не додається до index.html, а має додаватися, адже  він прописаний тут: i/central-js/bower.js як: "bootstrap": "~3.3.5"

**Comment by rostag** [comment]
Насправді, замість Bootstrap-методів треба використати методи Angular UI JS - http://stackoverflow.com/questions/23834507/angular-ui-bootstrap-navbar-collapse-and-javascript
Пробую

**Comment by rostag** [comment]
Виправив

**Comment by bvv4ik** [comment]
т.е. можно отдавать на тестирование тестерам?
если так - прошу ставить лэйбл "test", чтоб тестеры могли убедиться в работоспособности

**Comment by rostag** [comment]
@bvv4ik - так, можна давати на тестування. Про лейбл "test" зрозумів, буду ставити за необхідності.

**Comment by nazarenkod** [comment]
Проблема исправлена, страницы отображаются корректно.
Проверено на Android 4,4,2
