### ISSUE TITLE
Реализовывать Сервис сохранения прикрепляемого файла во временное хранилище Redis

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#63]
Реализовывать Сервис №1
Согласно схеме: http://www.gliffy.com/go/publish/image/3750471/L.png

**Comment by dutchakdev** [comment]
а где обсуждалось именно redis хранилище?

**Comment by PavelKorchagin** [comment]
добрый день, есть какие-то другие предложения, готовы обсудить?
redis взяли по скорости и из-за функции автоудаления по таймеру.

**Comment by egoruch** [comment]
Не до конца понятно что делать.
1.правильно ли я понял, что все что делает сервис 1 -это сохранение самого файла, его имени в редис. также при аплоаде сервис должен вернуть ID файла?
2.Где этот редис к которому должны подключиться?куда настраивать конекшн?
3.Когда файл будет удаляться из редиса?

**Comment by bvv4ik** [comment]
1. сохраняет только сам контент, причем скорее в виде листа обьектов (т.к. файлов может быть несколько) (сам лист названий и полученного ИД с записи редис-а сохраняется в поле формы.
2.к редису через REST-сервис, который пишется другим разработчиком на общем бэк-е (группа бэк-РЕСТ
3.файл сам о туда удалится через время, об этом не паримся

**Comment by zhmurkov** [comment]
задачу по бэку могу взять я

**Comment by bvv4ik** [comment]
Отлично, ассигнул!
Спасибо!

Прошу отписаться об этом в соотв.канале комманды в Слак

**Comment by bvv4ik** [comment]
тест

**Comment by budnik** [comment]
ping

**Comment by budnik** [comment]
ping

**Comment by zhmurkov** [comment]
Слил на ревью старшему

**Comment by admiral-diver** [comment]
Слил изменения в ГИТ

**Comment by alegast** [comment]
Можете в кількох словах описати Request Api Url (for file upload), Request type, params 

Зараз Post request  вертає 404 (параметри авторизації передаю)
Client error response [url] https://52.17.126.64:8080/wf-dniprorada/service/file/upload_file_to_redis [status code] 404 [reason phrase] Not Found
пробував ще так
Client error response [url] https://52.17.126.64:8080/wf-dniprorada/service/file/upload-file-to-redis [status code] 404 [reason phrase] Not Found

**Comment by bvv4ik** [comment]
чтоб приняло авторизацию, нужно в хеадере запроса передавать:
"Authorization", "Basic YWN0aXZpdGktbWFzdGVyOlVqaHRKbkV2ZiE="

**Comment by bvv4ik** [comment]
@RequestMapping(value = "/file/upload_file_to_redis", method = RequestMethod.POST)
    @Transactional
    public
    @ResponseBody
    String putAttachmentsToRedis(@RequestParam("file") MultipartFile file) throws IOException {
    	
    	return redisService.putAttachments(file.getBytes());
    }

**Comment by alegast** [comment]
авторизація для submit forms  на фронтенді 'login' => 'activiti-master',   'password' => 'UjhtJnEvf!'. 

давайте від пхп абстрагуемось. там хоч і 200 вертає та contentBody не той що очікуємо . 

curl -v -i --insecure -X POST 'https://52.17.126.64:8080/wf-dniprorada/file/upload_file_to_redis' -H "Content-Type: text/xml" -H "Authorization: Basic YWN0aXZpdGktbWFzdGVyOlVqaHRKbkV2ZiE=" --data-binary "@/home/san4o/Pictures/1348810.jpeg"
або так 
curl -v -i --insecure -X POST 'https://52.17.126.64:8080/wf-dniprorada/file/upload_file_to_redis' -H "Authorization: Basic YWN0aXZpdGktbWFzdGVyOlVqaHRKbkV2ZiE=" --form "file=@/home/san4o/Pictures/1348810.jpeg"

чого не вистачає ?

**Comment by admiral-diver** [comment]
Подее контекст должен быть: 'https://52.17.126.64:8080/wf-dniprorada/service/file/upload_file_to_redis

Пропущено /service

**Comment by admiral-diver** [comment]
POST https://52.17.126.64:8080/wf-dniprorada/service/rest/file/upload_file_to_redis

{"code":"SYSTEM_ERR","message":"The current request is not a multipart request"}

**Comment by L1Ntu** [comment]
curl -v -i --insecure -X POST 'https://52.17.126.64:8080/wf-dniprorada/service/rest/file/upload_file_to_redis' -H "Authorization: Basic YWN0aXZpdGktbWFzdGVyOlVqaHRKbkV2ZiE=" --form "file=@/root/test.png"

Content-Length: 0

**Comment by Dashchenko-Inna** [comment]
добрый день, Игорь, бросьте пожалуйста свой скайп

**Comment by bvv4ik** [comment]
и не вижу в конструкции:
curl -v -i --insecure -X POST 'https://52.17.126.64:8080/wf-dniprorada/service/rest/file/upload_file_to_redis' -H "Authorization: Basic YWN0aXZpdGktbWFzdGVyOlVqaHRKbkV2ZiE=" --form "file=@/root/test.png"


- параметра с названием файла
