### ISSUE TITLE
При повторному виборі міста не показується Крок 2.

### ISSUE THREAD

**Issue by 40rn05lyv** [e-government-ua/i#632]
Кроки:
1. Зайти на https://test.igov.org.ua/service/679/general/city
2. Вибрати Область: Волинська, Місто: Луцьк. (появиться Крок 2).
3. Натиснути "Змінити".
4. Вибрати Область: Волинська, Місто: Луцьк.

Очікуваний результат:
З’явиться Крок 2.

Справжній результат.
Крок 2 не з’являється.

![igov org ua - google chrome](https://cloud.githubusercontent.com/assets/1200215/9057541/843a0afe-3aa3-11e5-90a2-a552b74a7ab5.jpg)

**Comment by bvv4ik** [comment]
@Kiaba прошу глянуть, это, похоже, следствие:
https://github.com/e-government-ua/i/issues/550

**Comment by Kiaba** [comment]
Fixed
