### ISSUE TITLE
[S3] - На главной странице test.igov.org.ua после успешной регистрации через раздел "Док-ты", при переходе на гл. страницу и выборе активной услуги, необходимо регистрироваться повторно.

### ISSUE THREAD

**Issue by OlgaKotova** [e-government-ua/i#633]
Шаги:
1. Перейти на test.igov.org.ua, выбрать раздел "Документы" и зарегистрироваться через BankID.
2. Перейти на главную страницу и выбрать услугу "Надання довідки про відсутність (наявність) судимості або обмежень, передбачених кримінально-процесуальним законодавством України."(как пример).
3. Выбрать область и город(у меня Днепропетровская, Днепропетровск).

Фактический результат: Шаг 2 просит повторной регистрации через BankID.
Ожидаемый: по идее, если регистрация ранее была успешной, то этого пункта не должно быть. Или я ошибаюсь?

Окружение: MAC OS X 10.10.4, Safari 8.0.7

**Comment by bvv4ik** [comment]
так и должно быть, для услуг - регистрация должна быть постоянной.

**Comment by OlgaKotova** [comment]
Понятно, закрываю.
