### ISSUE TITLE
На главном портале починить работу нового валидатора validateAutoVIN (и проверить универсальность работы остальных, основанную на объекте markers)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#634]
- [ ] 1) Убедиться что вообще оно работает и починить, если не работает...

- [ ] 2) сделать такой-же вывод ошибки при валидации справа поля, как и при валидации электронки или телефона:
(<div ng-message="...  сам текст "Невалидное значение в поле с ‘VIN-код авто’")

- [ ] 3) ВАЖНО: убедиться что задействован механизм маркеров:
    $scope.markers = {
        validate:{
            PhoneUA:{
                aField_ID:['privatePhone','workPhone', 'phone', 'tel']
            }, Mail:{
                aField_ID:['privateMail','email']
            }, AutoVIN:{
                aField_ID:['vin_code', 'vin_code1', 'vin']
            }
        }
    };

т.е.сейчас проверка при сабмите такая:
        ValidationService.validateEmailByMarker( form.email, $scope.markers );
        ValidationService.validateTelephoneByMarker( form.phone, $scope.markers );
        ValidationService.validateAutoVIN( form.vin, $scope.markers );

проверяющая только элементы:
form.email
form.phone
form.vin

но ни где не увидел механизма, который-бы по объекту "markers",
- для телефонов привязывал этот механизм валидации - к ИД-шкам: ['privatePhone','workPhone', 'phone', 'tel']
- для электронок к ИД-шкам ['privateMail','email']
- и для vin к ['vin_code', 'vin_code1', 'vin']

- [ ] 4) Убедиться, что сабмит проходит успешно без ошибок, и наоборот, если поле не валидно - чтоб при сабпите подкрашивало поле и писало ошибку рядом с ним

**Comment by rostag** [comment]
перевіряю...

**Comment by bvv4ik** [comment]
отлично!)
а что радостного есть по п.3?))

**Comment by rostag** [comment]
П.3 зараз буде працювати так, як написано у таскові, але є одне запитання:

- Чи обов'язково співставляти поле вводу з маркерами примусової валідаціїї саме за id-атрибутом HTML-елементу? Це може потенційно конфліктувати з якимось іншим механізмом у браузері, що працює з цими ID-шками, тому я пропоную маркувати не так:

```
<input id="'vin_code' />
```
а так:
```
<input data-igov-validation-marker="'vin_code' />
```

Це буде добре читатися і точн оне викличе ніяких конфліктів.

ОК?

**Comment by rostag** [comment]
Доробив валідацію AutoVIN та валідацію за маркерами в цілому (п.3) - прошу перевірити )

**Comment by nazarenkod** [comment]
@rostag @bvv4ik VIN-номер работает.
Пропускает 8ми значный номер телефона, и не решен вопрос с полем "email ", заданный в таске  #375

**Comment by nazarenkod** [comment]
![invalidinpur](https://cloud.githubusercontent.com/assets/13256486/9137731/691a9e28-3d28-11e5-87a2-423fdfcac4c0.jpg)

**Comment by rostag** [comment]
@nazarenkod - зробив, прошу перевіряти. До речі, а який саме набір використовуєш для тестування, можеш ним поділитися, щоб я додав його до формальних тестів? Очікую у такому форматі:
```
VALID
0504060391
380504060391
+380504060391

INVALID:
380504060
```

**Comment by bvv4ik** [comment]
@rostag у тебя так ловко и хорошо получается с валидаторами, что очень хотел-бы попросить тебя за еще одну точно такую-же таску взяться (развитие основной идеи с маркерами + немного больше творчества):
https://github.com/e-government-ua/i/issues/654

**Comment by rostag** [comment]
@bvv4ik - ок

**Comment by nazarenkod** [comment]
Работает согласно описанию.
