### ISSUE TITLE
На дашборде привести в порядок раздел "Отработанные"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#635]
В списке:
- [x] 1) формат строки нужен такой:
"номер задачи (дата создания-дата завершения(если уже завершено)) имя процесса имя задачи"
т.е.:
- выдавать корректные названия БП (не ИД а именно названия)
- выдавать дату начала и завершения БП
- убрать остальной мусор (типа NaN-NaN-NaN NaN:NaN)
- [x] 2) в отработанных полях - так-же продолжать отображать поля формы, как и у не отработанных (сейчас пишет ошибку справа)

**Comment by maxymshg** [comment]
Можно получить пример, что конкретно ожидается по итогам выполнения задачи?
Сейчас отображение выглядит следующим образом:
# номер задачи (дата создания) имя процесса имя задачи
#1000331 (NaN-NaN-NaN NaN:NaN) kuznetsovsk_mvk-1 | Прийняття рішення: доцільність запиту

Что значит "БП"?

**Comment by bvv4ik** [comment]
БП = Бизнес-Процесс

"Можно получить пример, что конкретно ожидается по итогам выполнения задачи?
Сейчас отображение выглядит следующим образом:
номер задачи (дата создания) имя процесса имя задачи"

да, конечно, вот так должно быть:
"номер задачи (дата создания-дата завершения(если уже завершено)) имя процесса имя задачи"

просто сейчас вместо даты вообще пишется "(NaN-NaN-NaN NaN:NaN"

**Comment by maxymshg** [comment]
Я тут заметил, что в данных по разному подаются с бэкенда даты:
1) createTime
2) startTime

Можно выровнять бэкенд на что то одно, а то мой коммит я так понимаю сломал соседние табы :(

**Comment by bvv4ik** [comment]
"по разному подаются с бэкенда даты"
не совсем понял...
для других табов источник данных совершенно другие сервисы... там и поля другие потому..

**Comment by bvv4ik** [comment]
поламал...

тут нужно через ng-if в зависимости от выбранного таба брать данные поля для формирования строк списка

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/9298986/b0be66e4-44bf-11e5-80d9-68f61a5b9c80.png)

Ошибка в отображении отработанных полей ,не корректно отображаются названия полей
Ожидаемый результат: отображение полей названия поля в укр. а не параметрами

**Comment by bvv4ik** [comment]
это не ошибка а именно те данные, которые доступны из Истории, стандартными средствами Активити... тут главное просто сохранить наиболее важные данные...

**Comment by VadimGulich** [comment]
Понял, тогда все ок
