### ISSUE TITLE
На главном портале починить получние контрольной суммы по алгоритму Луна

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#636]
Найти строчки:
        //TODO: Fix Alhoritm Luna
        //Number 2187501 must give тCRC=3
        //Check: http://planetcalc.ru/2464/

и поправить алгоритм.

ссылка на онлайн-калькулятор:
http://planetcalc.ru/2464/

Пример:
для числа "2187501" - калькулятор выдает контрольную сумму 3

так-же и на: https://test.igov.org.ua/order/search
если задать 21875013 - напишет как и должно быть - запись не найдена
(вместо сообщения что номер не валиден. т.к. тут тоже алгоритм работает.

а вот если в консоли обозревателя запустить:
        var n = parseInt(2187501);
        var nFactor = 1;
        var nCRC = 0;
        var nAddend;
        while (n !== 0){
            nAddend = Math.round(nFactor * (n % 10));
            nFactor = (nFactor === 2) ? 1 : 2;
            nAddend = nAddend > 9 ? nAddend - 9 : nAddend;
            nCRC += nAddend;
            n /= 10;
        }
        alert(nCRC%10);

- вернет 7 (что неверно)

П.С.: другие описания алгоритма:
https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC_%D0%9B%D1%83%D0%BD%D0%B0

https://gist.github.com/dimiork/75d8b1288171fba45d71

**Comment by bvv4ik** [comment]
Для теста:
можно создать заявку(записам ее номер), зайти на закладку статусы и ввести ее там для поиска - должно найти

**Comment by OlgaKotova** [comment]
@bvv4ik Заявка по номеру нашлась.
Закрываю.
