### ISSUE TITLE
ПО "Єдине вікно подання електронної звітності" сделать онлайн, смогем?

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/i#637]
Ребята поступил такой фидбек:
 -------------------------------------------------------
Владимир Гошуренко: Если электронное правительство сможет придать человеческое лицо бесплатному ПО "Єдине вікно подання електронної звітності" (разработка ДФСУ), то оно заслужит вечное уважение и благодарность всей бухгалтерской и предпринимательской общественности страны. А также их потомков.
https://www.facebook.com/volodymyr.hoshurenko
https://www.facebook.com/jaanika.merilo/posts/10207304146420649
http://prokey.org.ua/kak-besplatno-otpravlyat-otchetnost-v-elektronnom-vide
 -------------------------------------------------------
Кто что думает по этому вопросу? Если данная программа нужна, возможно мы можем у себя на портале сделать  ее онлайн аналог? (edited)

**Comment by zadarma** [comment]
там они, конечно, очень сильно заморочились... Боюсь, что тема там огромная, и придется еще разгребать все го...но, которое себе сложили в голове проектировщики этого "продукта".
А вообще - неплохо было бы помочь, если бы дали возможность его изменять для улучшения.

**Comment by shvaykovski** [comment]
там они, конечно, очень сильно заморочились... Боюсь, что тема там огромная, и придется еще разгребать все го...но, которое себе сложили в голове проектировщики этого "продукта".
А вообще - неплохо было бы помочь, если бы дали возможность его изменять для улучшения.

**Comment by VadymVolos** [comment]
Вот я нашел ссылку, там 7 альтернатив http://prokey.org.ua/kak-besplatno-otpravlyat-otchetnost-v-elektronnom-vide

Если все альтернативы не устраивают. Можем обдумать и если нужно сделать свой вариант. 

Не вижу для чего нам нужно чтоб они дали возможность его изменить. Можем сделать свой вариант, и даже брать процент за использование данного сервиса. Деньги могут капать в бюджет наших разработчиков, нашего сервиса, вообщем куда деть деньги это не проблема думаю все вместе быстро придумаем.

**Comment by uazure** [comment]
В чем собственно заключается подача электронной отчетности?
Формирование хмл документа в определенном формате (который как я понимаю довольно часто модифицируется), подписание его электронной подписью, отправка на почтовый шлюз налоговой, обработка пришедших ответов от шлюза налоговой (тоже писем).
Чисто технически - никаких особых проблем. Но концептуально у меня есть возражения.
Во-первых, это очень большой объем работы, а затем поддержки системы в актуальном состоянии. Кто будет ответственно заниматься поддержанием системы в актуальном состоянии в течении лет - не ясно. Пока этот вопрос не решен - не вижу смысла начинать реализовывать функционал.
Во-вторых, в целом задача уже решена, уже есть рабочие бесплатные и платные решения этой задачи. Среди перечисленных 7 альтернатив еще не указан taxer.ua который тоже прекрасно работает и базовый функционал предоставляет бесплатно. Может мы как портал сможем ограничиться ссылками на известные бесплатные решения? За размещение ссылок, точнее за приоритетный их порядок тоже можно брать денежку в качестве рекламы

**Comment by VadymVolos** [comment]
Можем и ссылками. Согласен работы много. Поэтому данная задача с лейблом "question"
чтоб мы обменялись мыслями и пришли к чему-то простому.

**Comment by LamronNu** [comment]
с одной стороны, эта "услуга" должна быть представлена на портале, т.к. задача нашего проекта как раз в этом и состоит: создать "единый интерфейс доступа к госуслугам" (плюс будет дополнительный "поток пользователей", я думаю).
с другой стороны, "делать её с нуля" нет смысла, поскольку уже есть альтернативные решения (первое) и достаточно других "нереализованных" услуг (второе).

вариант со ссылками, как по мне, самый оптимальный. пусть пользователь сам решает, что ему удобней и т.п.
а если в будущем станет вопрос об реализации услуги со стороны портала -- тогда и будем его решать.

**Comment by bvv4ik** [comment]
согласен с @LamronNu
 - пока реально только ссылки сделать... а как забабахкаем все остальные основные услуги - возьмемся и за такие)

**Comment by bvv4ik** [comment]
прошу таску в юэклог (перенести в общий гуглодок и тут закрыть), а то тяжело работать с таким количеством неактуальных на данный момент тасок,...

**Comment by VadymVolos** [comment]
Я не шарю как переносить таски, перенесите пожалуйста. И если не сложно в двух словах как переносить, чтоб я знал на будущее :) Спасибо!

**Comment by VadymVolos** [comment]
@bvv4ik "юэклог" это куда? 
Ссылку дайте пожалуйста на общий гуглдок, я перенесу.

**Comment by rostag** [comment]
@VadymVolos "юеклог" - це, мабуть, "беклог" - https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit

**Comment by VadymVolos** [comment]
@rostag Дуже дякую!
