### ISSUE TITLE
Отсутствует название самой услуги в форме для заказа услуги - Запит на отримання публічної інформації (облдержадміністрація). 

### ISSUE THREAD

**Issue by bzhest** [e-government-ua/i#638]
Windows XP, Chrome 44.0.2403.107 m, FireFox 39.0
Для перехода: "Послуги" - "Взаємодія з державними органами" - "Запит на отримання публічної інформації (облдержадміністрація)"

В окне заказа услуги отсутствует само название услуги + съехало влево форма с выбором области.

![default](https://cloud.githubusercontent.com/assets/12616696/9107094/634bdca6-3c2d-11e5-8270-1c5c846140e7.JPG)

В других окнах название имеется + форма центрирована, например: "Реєстрація авто з пробігом в МРЕВ"

![default](https://cloud.githubusercontent.com/assets/12616696/9107081/51b7c7de-3c2d-11e5-8f70-39d2da8d5279.JPG)

**Comment by uazure** [comment]
fixed
