### ISSUE TITLE
test.igov.org.ua loading fault

### ISSUE THREAD

**Issue by vikor** [e-government-ua/i#639]
Precondition: 
- Chrome Version 22.0.1207.1
- url: https://test.igov.org.ua/

Загрузка страницы завершилось сообщением: "Aw, Snap! Something went wrong while displaying this webpage. ..."
Перезагрузка страницы приводит к такому же результату.
Другие версии Хрома не проверял.

Firefox 39.0 работает нормально.

![clipboard01](https://cloud.githubusercontent.com/assets/2273766/9107637/8725cb4c-3c31-11e5-8da0-7884d8108196.jpg)

**Comment by bvv4ik** [comment]
это шото локальное с компом... работает на хроме нормально
