### ISSUE TITLE
Реализовывать Сервис загрузки прикрепленного к заявке файла из постоянной базы

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#64]
Реализовывать Сервис №3
Согласно схеме: http://www.gliffy.com/go/publish/image/3750471/L.png

**Comment by maxtmn** [comment]
это лишний шаг. 
при реализации задачи Сервис №2 - файл (файлы) будут прикреплены к бизнес-процессу как  attachment. В активити, такие файлы хранятся в отдельной таблице. зачем еще куда-то сохранять их же?

**Comment by bvv4ik** [comment]
они там-же в аттачменте и будут, в базе.
а загружаться от туда уже будут из админки/дашборда, а не активити-эксплорера
потому шаг не лишний
