### ISSUE TITLE
На портале сделать фильтр по Области

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/i#640]
Привет ребята, стоит задача отслеживать/просматривать количество запущенных услуг и услуг которые в процессе запуска по областям и городам.

В данном случае нужен фильтр По Харькову и Харьковской области. 
Для удобного просмотра возможно есть смысл выводить инфу в виде таблички (это не принципиально, но думаю так будет более удобно для просмотра и восприятия).
Спасибо!

Для какой ветки относится задача не знаю, перенесите пожалуйста в нужную.

**Comment by bvv4ik** [comment]
уже задача давно стоит
