### ISSUE TITLE
На главном портале убрать дубликацию темплейтов.

### ISSUE THREAD

**Issue by uazure** [e-government-ua/i#642]
Нереальная лапша из html темплейтов и контроллеров и роутов которые это все включают\выключают.
Вероятное решение - создание директив для выполнения элементарных операций (выбор области, выбор города, отображение кнопок с вариантами идентификации и т.п.) и интеграция директив с существующими контроллерами и темплейтами.
Задача на вскидку большая, может потребовать дней для вкуривания существующей системы и переделывания по-нормальному. Храбрецу который за это возьмется и доведет до победного конца - респект от всей команды и их потомков.

**Comment by bvv4ik** [comment]
я третий месяц уговариваю @Kiaba наконец привести в божеский вид этот блок с city+region+country... он изначально этот копипаст реализовал, он вроде потом согласился с тем, что так быть не должно, но у него-же все ни как не найдется время чтоб это сделать... вечно какие-то 100500 причин...

если кто возьмется за это - так-же буду благодарен...
(у самого руки опускаются, когда смотрю на этот бардак.. и переделал-бы сам, если-б оставалось время после текущих первоочередных задач, да если-б опыта по NodeJS и AngularJs біло хоть сколько-то)

Вот это таска, первый пункт:
https://github.com/e-government-ua/i/issues/550

эту таску прошу закрыть (дубль)
