### ISSUE TITLE
Добавить готовую услугу "Замовлення Витягу з Державного земельного кадастру" 

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/i#643]
Привет ребята!
На портал нужно добавить уже готовую услугу, точнее линк на эту услугу.

Назвать ее нужно "Замовлення Витягу з Державного земельного кадастру" 
вот ссылка http://map.land.gov.ua/kadastrova-karta по этому адресу она предоставляется.

 ----

*Комментарии Ирины по поводу данной услуги, возможно они пригодятся:*

ira
а хто знає, чому ми ще не виставили послугу "Замовлення Витягу з Державного земельного кадастру" , вже працює тут http://map.land.gov.ua/kadastrova-karta

vadym
"Замовлення Витягу з Державного земельного кадастру" на порталі треба тільки лінк на цю карту додати, чи потрібна інтеграція з порталом? Якщо тільки лінк, можемо додати.

ira 
тільки лінк, поки що там не потрібно верифікації. Думаю, це вони даремно :simple_smile:, я вже двічі замовила витяг на чужі земельні ділянки, чекаю коли прийде відмова.  Дмитро казав, що нова версія буде з нашою ідентифікацією. А поки маємо те, що маємо. (edited)

ira
і ще - послуга платна, а мені прийшло підтвердження що оплата успішна, але гроші не заплатила :simple_smile: Є там такий баг. Буду у держкомземі, покажу їм. (edited)

vadym
Сюди лінк додати https://igov.org.ua/service/48/general (Надання відомостей з Державного земельного кадастру у формі довідки, що містить узагальнену інформацію про землі (території))
чи це не та послуга? (edited)

ira
Думаю, що ні.
Вона на карті так і називається - Замовлення Витягу з Державного земельного кадастру. Може краще щоб не заплутатись, зробити нову? (edited)

vadym
Можемо і нову.

**Comment by kurbpa** [comment]
Шикарно!!!
Спасибо!

Хотя название указано неправильно.
Правильная формулировка - Надання відомостей з Державного земельного кадастру у формі Витягу з Державного земельного кадастру про земельну ділянку

**Comment by VadymVolos** [comment]
Пожалуйста :)
По поводу названия, я у Иры спрашивал...
Лично я не в кусе как правильно,
возможно в описание добавьте два названия чтоб через поиск можно было найти.

**Comment by bvv4ik** [comment]
уже добавили на боевой... таску можно закрывать

**Comment by VadimGulich** [comment]
угу , добавлено , закрываю
