### ISSUE TITLE
Q: На главном портале нужна возможность выбора города\региона до навигации по услугам

### ISSUE THREAD

**Issue by uazure** [e-government-ua/i#645]
Каждый раз как клацаю главный портал, хочется чтобы мой город\регион запоминались с прошлого раза, а список услуг фильтровался бы исходя из выбранного региона.
Как я вижу работу портала.

Первый заход: список услуг, строка поиска, плюс к этому возможность указать свой регион и выбрать город. Если выбран регион\город, то отображаются только те сервисы, которые применимы в моем городе\регионе. Если выбран регион\город, то его можно в один клик сбросить.

Повторный заход: сайт сам подставляет мой регион и фильтрует услуги. В один клик я могу сбросить регион\город.

Что думаете о таком флоу?

**Comment by bvv4ik** [comment]
задача по расширенному фильтру по регионам давно в работе... я не против, что-б кто-то еще взял на себя ее реализацию, чтоб она быстрей воплотилась в жизнь...

по поводу запоминария региона - идея хорошая,  но все это нужно в бэклог сразу относить, т.к. не хватает ресурса(тем более, сейчас люди по отпускам разьехались) чтоб даже более важные таски реализовывать...

П.С.: а вообще, просьба - все предложения в отдельном общем списке вести или бэклоге, т.к. в issue должно быть только то .что уже  готово для разработчиков... а при таком количестве "всякой всячины" разработчики теряются, не зная что можно брать в работу, и в итоге все вынуждены обращаться ко мне, а меня не хватает на всех(  или, чаще всего - видя такой хаос - делают "от ворот поворот"

**Comment by bvv4ik** [comment]
так в бэклок только кусок этой задачи, а фильтр по регионам это-ж уже созданая задача давно: 
https://github.com/e-government-ua/i/issues/444

(название и контент данной задачи переписать, и вообще стараться не писать в одной issue несколько задач. т.к. потом тяжело отделять)
