### ISSUE TITLE
Функционал [S3] - В письме отсутствует кнопка для оплаты регистрации авто.

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#647]
Содержание письма:
![bug_igov_10](https://cloud.githubusercontent.com/assets/12996514/9131111/6d3667f8-3cf1-11e5-9909-b3aed60113f1.jpg)

Исходная задача
https://github.com/e-government-ua/i/issues/519

**Comment by bvv4ik** [comment]
из данного БП сознательно ее пока убрали... на тестовом БП кнопка исправно отсылается
таску можно закрывать
