### ISSUE TITLE
Обеспечить поддержку в интерфейсе возможности прикрепления гражданином файла в заполняемой заявке

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#65]
Связаться с исполнителем по задаче (для согласования полей):
https://github.com/e-government-ua/i/issues/63
и обеспечить поддержку в интерфейсе возможности прикрепления гражданином файла в заполняемой заявке (аплоада), воспользовавшись сервисом №1, согласно схеме:
http://www.gliffy.com/go/publish/image/3750471/L.png

П.С.: передавать в заявке два дополнительных поля: Название файла и ID записи в Redis

**Comment by L1Ntu** [comment]
могу взять в работу

**Comment by bvv4ik** [comment]
Отлично, спасибо.
А Вам не сложно будет еще отписаться в канале комманді(в слак-е), об єтом:
https://e-government-ua.slack.com/messages/_portal-front_php/

?

**Comment by bvv4ik** [comment]
на тестовом: http://52.17.126.64:5588/
БП:CivilCopyDocRequest - Звернення громадян стосовно надання копій документів
Поле textArea:
Id - textArea
Type - textArea
Name - Додаткова iнформацiя

**Comment by bvv4ik** [comment]
Поле для key redis (которое должно быть заполнено на фронте полученном после аплоада ИД-шником аплоаденного файла в Редис):
Id - attachedId
Type - string
Name - Додаткові документи

**Comment by bvv4ik** [comment]
сервис аплоада файла в Редис, чтоб получить его ИД
/file/upload_file_to_redis

полученный ID Редис-а, куда будет фактически зааплоаден файл - нужно будет сохранить в поле attachedId, заполняемой гражданином формы

**Comment by alegast** [comment]
ще потрібні данні для авторизації на той же redis на бекенді. 
content type (file extension) на бекенді самі визначать ?

**Comment by bvv4ik** [comment]
не понял,
это сервис-обертка нашего бека.. в котором уже происходит связь с редис-ом, сохранение туда контента, и возвращение полученного ИД

**Comment by alegast** [comment]
Скоріш за все я не зрозумів ) 
в задачі https://github.com/e-government-ua/i/issues/63  не описано яким чином з форми на фронтенді файл має опинитись в Redis і звідки потім взяти ІД . Це якесь окреме апі ? 
 В данний момент фронтенд працює з бекендом https://52.17.126.64:8080/wf-dniprorada/service/  через json.  Серилізувати контент файла в string і передавати на апі не схоже що це малось на увазі. 
Подрібні уточнення від бекенду.

**Comment by bvv4ik** [comment]
"в задачі #63 не описано яким чином з форми на фронтенді файл має опинитись в Redis"
- все верно! Именно эта функция и должна быть реализована в текущей задаче (65).
т.е. эта задача аплоадит в теле запроса данные, посредством сервиса из задачи 63.
в ответ , от этого сервиса получает ИД Редис-а (под которым будет числится сохраненный контент)
(то как там этот сервис взаимодействует с редисом - не важно, ибо черный ящик)
Полученный на фронте ИД просто сохраняем в поле формы..
(уже потом, после сабмита формы - по этому ИД данные опять вытянутся из Редис-а, и сохранятся в базу, но это тоже не важно, т.к. черный ящик)


все что нужно в данной задаче, это добавить кнопку аплоада, по которой будет происходить выбор файла, который нужно прикрепить, после чего контент этого файла должен переправиться через сервис "/file/upload_file_to_redis" - куда нужно, а себе в форме мы оставим просто ИД-шник этого сохранения...

и только когда все остальные поля будут заполнены - сабмитим форму...

**Comment by bvv4ik** [comment]
контент файла для отправки в теле гапроса не надо сериализовать... это обычная практика аплоадить контент на сервлет в теле запроса...

если возникнут вопросы по взаимодействию с сервисом по аплоаду - стоит уточнить у коллеги, который его реализовывал... (там в его задаче есть его логин, или можно найти его в скайпе по логину: dn080692zaa)

если нужно - могу организовать общий чат.. или можно перезвонить мне 093 463 84 56

**Comment by loveitgroup** [comment]
готово
