### ISSUE TITLE
На дашборде, в отчетах, экспорте (фактически вызывается сервис /file/downloadTasksData) поправить дефолтные параметры

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#653]
3) в поле 4 вставлять инн гражданина (параметр bankIdinn). если этот параметр пустой (бывает, что граждане отказываются от инн), то писать в него NULL
4) в поле 6 убрать значение 0 (пусть будет пропуск)

**Comment by VadimGulich** [comment]
Подскажите , пож-ста,это при скачивании или в скачанном файле можно проверить ?

**Comment by bvv4ik** [comment]
в скачаном

**Comment by VadimGulich** [comment]
При скачивании по ниже указанном запросе : 
https://test-version.region.igov.org.ua/api/reports/export?sID_BP=dnepr_spravka_o_doxodax&sID_State_BP=usertask1&sDateAt=2015-06-01&sDateTo=2015-08-01&saFields=${nID_Task};${sDateCreate};${area};${bankIdinn};;;${bankIdlastName}%20${bankIdfirstName}%20${bankIdmiddleName};4;${aim};${date_start1};${date_stop1};${place_living};${bankIdPassport};1;${phone};${email}&sID_Codepage=win1251&nASCI_Spliter=18&sDateCreateFormat=dd.MM.yyyy%20HH:mm:ss&sFileName=dohody.dat

В скачанном файле не отображается ИНН или NULL : 
![image](https://cloud.githubusercontent.com/assets/12964120/9268347/b1bd3a9e-4266-11e5-8996-7225bf27876f.png)

**Comment by bvv4ik** [comment]
дело в том, что до доработки этого поля и небыло... т.е. проверить можно только на вновь созданных заявках, за даты, начиная со вчерашней

**Comment by VadimGulich** [comment]
Проверено , протестировано , можно в боевой
