### ISSUE TITLE
На центральном портале, добавить в markers новые валидаторы, и обеспечить их работоспособность.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#654]
ВАЖНО: Разные маркеры могут "назначаться" на одни и те-же поля.

- [x] 1) Все украинские буквы, без цифр, возможен минус и пробел
"TextUA":{ 
      "aField_ID":["fio"]
}
Текст ошибки: "Текст може містити тількі українські літери або мінус че пробіл"

- [x] 2) Все русские буквы, без цифр, возможен минус и пробел
"TextRU":{
      "aField_ID":["fio_RU"]
}
Текст ошибки: "Текст може містити тількі російські літери або мінус че пробіл"

- [x] 3) Валидная дата заданного формата (чтоб формат можно было задавать)
"DateFormat":{
      "aField_ID":["fio"]
      , "sFormat": "YYYY-MM-DD" //
}
Текст ошибки: "Дата може бути тільки формату" (и дальше дописывать формат из sFormat)

- [x] 4) С/до даты в поле с/после текущей, больше/меньше дней/месяцев/лет
"DateElapsed":{
      "aField_ID":["dateOrder"]
      , "bFuture": false //если true то дата должна быть в будущем
      , "bLess": true //если true то "дельта" между датами должна быть "менее чем" (указана нижними параметрами)
      , "nDays": 3
      , "nMounths": 0
      , "nYears": 1
}
Текст ошибки: "С/До дати с/після сьогоднішньої, повинно бути більше/меньше ніж х-днів, х-місяців, х-років.

Примечания:
х-___ - подставлять только если не равно 0
С/До - в зависсимости от bFuture
більше/меньше - в зависсимости от bLess

- [ ] 5) Дописать валидаторы п.1-4 в файл: https://docs.google.com/document/d/1LO95UPIQ3FOvxJXaKWb5uAUuYOIFVjn1KUMAudrLW3M/edit?pli=1

**Comment by rostag** [comment]
1), 2), 3 - Зробив, перевіряю.
4) - Роблю.

**Comment by rostag** [comment]
Будь ласка, дайте тест-кейси для п.4.

Давайте уточнимо варіанти повідомлення:
```
Загальний: "[Від|до] дати у полі [від|до] поточної [пройшло|залишилося] [більше|менше] [днів|місяців|років]."
```
Конкретні:
```
Від дати у полі до поточної пройшло більше 2 днів.
Від дати у полі до поточної пройшло менше 2 днів.
Від дати у полі до поточної залишилося більше 2 днів.
Від дати у полі до поточної залишилося менше 2 днів.
До дати у полі від поточної пройшло більше 2 днів.
До дати у полі від поточної пройшло менше 2 днів.
До дати у полі від поточної залишилося більше 2 днів.
До дати у полі від поточної залишилося менше 2 днів.
```

Це ще не всі, так?

**Comment by rostag** [comment]
4) - майже готовий, перевіряю.

**Comment by bvv4ik** [comment]
@rostag - да, сообщения что надо!
(только со временем еще и научимся в зависимости от числа корректное окончание ставить, а пока окончанеи лучше точкой прерывать)

**Comment by rostag** [comment]
@bvv4ik - я вже реалізував такі закінчення, у валідатор влаштовано таку функцію pluralize: 
```
  /**
   * Перетворює числа nUnits та ключ key на слова такі як: 
   * - 1 день, 2 дні, 5 днів, 
   * - 1 місяць, 3 місяці, 10 місяців
   * - 1 рік, 4 роки, 5 років
   */
  self.pluralize = function(nUnits, key) {
    var types = {
      'days': {
        single: 'день',
        about: 'дні',
        multiple: 'днів'
      },
      'months': {
        single: 'місяць',
        about: 'місяці',
        multiple: 'місяців'
      },
      'years': {
        single: 'рік',
        about: 'роки',
        multiple: 'років'
      }
    };
    var form = nUnits === 0 ? '' : Math.abs(nUnits) === 1 ? types[key].single : Math.abs(nUnits) < 5 ? types[key].about : types[key].multiple;
    form = form === '' ? '' : nUnits + ' ' + form;
    return form;
  };
```
Також, я зробив для цих валідаторів unit-тести, а ще інтегрував бібіліоеку для роботи з часом - angular-moment (це призвело до додаткових витрат часу, бо модуль тестування та бібліотека не захотіли запрацювати одразу :sweat_smile: )

**Comment by bvv4ik** [comment]
Круто!)

только я чето не нашел новых маркеров в коде, в объекте:

    $scope.markers = {
        validate:{
            PhoneUA:{
                aField_ID:['privatePhone','workPhone', 'phone', 'tel']
            }, Mail:{
                aField_ID:['privateMail','email']
            }, AutoVIN:{
                aField_ID:['vin_code', 'vin_code1', 'vin']
            }
        }
    };

там все старое(

**Comment by bvv4ik** [comment]
напомню - этот обьект - краеугольный камень всей системы валидации... т.к. будет его дефолтная модель(общая для всех) а будут модели, которые будут домерживаться в нее с загружаемых БП... это принципиально важно, чтоб на ней все сходилось, и через нее регламентировалось - на какие поля что "вешается" и с какими критериями...

**Comment by rostag** [comment]
@bvv4ik - дякую, намагаюся притримуватися цього підходу - усі маркери у одному місці. У об'єкті  $scope.markers будуть усі маркери до одного.

**Comment by bvv4ik** [comment]
"Виникло питання: чи будемо ми зберігати markers як єдиний на усю систему (central-js/client) value-object? Чи у кожного $scope буде свій, такий власний об'єкт?"

как я и писал, чуть позже в базовую можель будут домерживаться маркеры отдельных БП...

т.е. "базовый" + "мерж локального из БП" = "итоговый"... но это позже..
сейчас все "выращиваем" в едином обьекте...


и важный вопрос:
"только я чето не нашел новых маркеров в коде, в объекте:"

дело в том, что нам срочно нужно заюзать уже некоторые из этих маркеров в БП по справке о несудимости для всей страны (оговорены сроки с МВД)... я, было, попытался заюзать - и не нашел их... может они куда переместились или они не вылиты еще? 
очень нужно .процесс стал...

**Comment by rostag** [comment]
я прямо зараз відправляю усе це на test сервер... просто вирішив більше потестувати і забекапити, пам'ятаючи той раз, коли трохи поламав сервер.

**Comment by rostag** [comment]
Багато змін - багато ризиків. Jenkins почав збирати, зараз буду перевіряти, чи працює на test-сервері.

**Comment by rostag** [comment]
@bvv4ik - ось тестова сторінка, де можна швидко перевіряти усі наявні валідатори:
https://test.igov.org.ua/test

**Comment by rostag** [comment]
Перевіряти можна тут (валідатор Auto VIN, мейлу та телефону):  
 - http://test.igov.org.ua/service/159/general/city/built-in/region/1/city/1/

І тут (усі валідатори): 
 - https://test.igov.org.ua/test

**Comment by bvv4ik** [comment]
@rostag огромное спасибо!
все супер, реализация прекрасная!
я еще потестю, конечно, по проведя общий обзор - впечатление отличное!

**Comment by nazarenkod** [comment]
@rostag 
Оператор life:) добавил новый код сети :073.
Прошу учесть.

**Comment by rostag** [comment]
@nazarenkod - дякую! Я щойно перевірив - такі номери пропускає як правильні:
0731234567
380731234567
+380731234567
а у вас?

**Comment by nazarenkod** [comment]
@rostag а у меня не пропускало вообще...принимало как неправильные.
Нужно разбираться....

**Comment by nazarenkod** [comment]
@bvv4ik @rostag 
Все работает согласно описанию, но все еще не добавлен код оператора 073.Ждем или закрывать?

**Comment by bvv4ik** [comment]
+380731234567
должно пропускать

**Comment by nazarenkod** [comment]
![vlidphone1](https://cloud.githubusercontent.com/assets/13256486/9486785/616b8c72-4bd4-11e5-8675-f5c349b62922.png)

**Comment by bvv4ik** [comment]
@nazarenkod действительно ,проверил сам - именно этот номер не хочет пропускать...
похоже ограничение компонента..
можно что-то сделать из не сложного, чтоб починить? или уже черт с ним, пока, с этим кодом... позже поправим?

**Comment by nazarenkod** [comment]
@bvv4ik Я так понимаю таску нужно закрывать?

**Comment by rostag** [comment]
@bvv4ik @nazarenkod - я подивлюся, чому саме цей номер не хоче пропускати.

**Comment by VadimGulich** [comment]
rostag - Вы еще не смотрели в чем причина ?

**Comment by nazarenkod** [comment]
@bvv4ik что делать с этой таской?

**Comment by rostag** [comment]
@nazarenkod — я перевірю і виправлю це

**Comment by VadimGulich** [comment]
Еще не смотрели и не правили ?

**Comment by nazarenkod** [comment]
@bvv4ik Заметил странное поведение валидатора номера.
Если стереть полностью поле "телефон" и внести в него валидное значение , то при сабмите бьёт ощибку.Фикс будет в рамках этой таски или писать репорт?

**Comment by nazarenkod** [comment]
Простите, забыл скрин ошибки
![bug](https://cloud.githubusercontent.com/assets/13256486/10117914/f239f9a0-6470-11e5-9c31-2dc466cb4f1d.jpg)

**Comment by VadimGulich** [comment]
Закрываем задачу , а ошибку с номером на 380731234567 перенесем в бэклог , мож ктот исправит
