### ISSUE TITLE
Сохранять события запуск, изменение статуса и закрытие в журнал событий

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#655]
При запуске процесса, изменении его статуса и закрытии процесса сохранять событие в журнал событий (сущность HistoryEvent)  через метод 
setHistoryEvent(Long nID_Subject, Long nID_HistoryEventType, String sEventName_Custom, String sMessage)

где:
nID_Subject - брать из запроса
nID_HistoryEventType - брать из энума (старт процесса - GET_SERVICE; изменение статуса заявки - ACTIVITY_STATUS_NEW, и закрытие процесса - создать новый тип)
sEventName_Custom = sMessage
Для формирования sMessage:
GET_SERVICE - необходимо название услуги брать из бизнесс-процеса, статус брать из параметра метода сохранения истории сервиса 
ACTIVITY_STATUS_NEW - номер заявки защищенный брать из параметра метода сохранения истории сервиса или получать через сервис AlgorithmLuna.getProtectedNumber(nID_Task), 
                      статус брать из параметра метода сохранения истории сервиса

**Comment by RoOmel** [comment]
Добавление записи в журнал
Запрос POST
https://test.igov.org.ua/wf-central/service/services/setHistoryEvent
Параметры:
nID_Subject = 3
nID_HistoryEventType
sEventName
sMessage = "Громадянам"
Ответ сервера: Статус 200 ОК
"21852"

Проверка журнала
Запрос GET
https://test.igov.org.ua/wf-central/service/services/getHistoryEvents?nID_Subject=3
Ответ сервера
 {
        "sMessage": "\"Громадянам\"",
        "sDate": "2015-08-18 13:20:30.018",
        "nID": 21851,
        "nID_Subject": 3,
        "nID_HistoryEventType": 0,
        "sEventName": ""
    }
Задача реализована согласно ТЗ
