### ISSUE TITLE
Отображать в списке заявок ( на дашборде чиновника) название услуг. 

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#657]
![image](https://cloud.githubusercontent.com/assets/11442397/9172888/26f87c46-3f7f-11e5-9905-82028f7d17ec.png)

Сейчас отображается id б-процесса активити.
Необходимо отображать полное название услуги.

**Comment by rooksnest** [comment]
проверено на альфе https://test.region.igov.org.ua:6948/
