### ISSUE TITLE
Реализовать на бэке (wf-base) подсистему Электронной Эскалации

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#658]
Все реализовывать по существующим стандартам проекта: Liqibase, Hibernate и т.д.!

- [x] 1) Создать сущность EscalationRule с параметрами:
nID - ИД-номер (уникальный-автоитерируемый)
sID_BP - ИД-строка бизнеспроцесса
  sID_UserTask - ИД-строка юзертаски бизнеспроцесса
sCondition - строка, до 200 символов 
soData - строка-обьект, с данніми (JSON-обьект), до 500 символов
sPatternFile - строка файла-шаблона
nID_EscalationRuleFunction - ИД-номер функции ,при эскалации

- [x] 2) Создать сущность EscalationRuleFunction с параметрами:
nID - ИД-номер (уникальный-автоитерируемый)
sName - строка-название (Например "Отсылка уведомления на электронную почту")
sBeanHandler - строка бина-обработчика

 3) Создать обработчик EscalationHandler_SendMailAlert
("Отсылка уведомления на электронную почту")
(ВАЖНО: при реализации желательно сразу учесть п.6.)

- [x] 3.1) В котором принимать параметры:
nID_Task_Activiti
sCondition
soData
sPatternFile

- [x] 3.2) Помещать параметры из "soData" в мапу мап(распарсить как JSON-объект), ожидая строку вида:
{"sParam1":"a@a.a","nParam2":456,"bParam3":true,"asMailRecipient":["b@b.b","c@c.c"]}
при том, если первые символы переменных первого уровня маленькие(при этом следующий символ большой):
s - кастить в String
n - кастить в Long
b - кастить в Boolean
as - кастить в массив/лист String
an - кастить в массив/лист Long
в остальных случаях кастить в стринг

- [x] 3.3) Добавлять в мапу п.п.3.2 параметры из полученной задачи, по ее ИД (параметр nID_Task_Activiti), с соблюдением тех-же правил определения типа (кастинг) а п.3.2. 

- [x] 3.4) По выражению в "sCondition" ,с учетом параметров, полученных в п.п. 3.3. - произвести проверку, при которой если получится True - выполнять дальнейшие действия в п.п.3.5.

- [x] 3.5) Выполнить отсылку на электронную почту:
- [x] 3.5.1) по адресам, распарсеного подпараметра "asMailRecipient" (из soData)
- [x] 3.5.2) По шаблону тела, взятому с параметра "sPatternFile" (в коде искать метод getPatternFile(String sPathFile))
- [x] 3.5.3) С заголовком, распарсеного подпараметра "sHead" (из soData)
- [x] 3.5.4) Заменой всех найденых вхождений в шаблоне тела, типа [sParam0], где "sParam0" - название параметра (положенного в мапу по п.п. 3.2 и п.п. 3.3):

- [x] 4) Добавить шетдулер на 2 часа ночи, который будет:
- [x] 4.1) перечислять все записи сущности "EscalationRule"
- [x] 4.2) выбирать по ним таски указанного БП (sID_BP), с учетом фильтрации юзертаски (sID_UserTask), при том если в sID_UserTask стоит "*", то проходиться по всем юзертаскам
- [x] 4.3) проходясь по ним отрабатывать бин-хэндлер, указанный в параметре sBeanHandler, сущности EscalationRuleFunction (связь через nID_EscalationRuleFunction)

- [x] 5) добавить в соответствующие инициализационные файлы (data/*.csv) сущностей п.1. и п.2. (liquibase)
- [x] 5.1) п.1 - пару БП
- [x] 5.2) п.2 - один элемент, со ссылкой на бин-эндлер (класс-обработчик), описанный в п.3.

- [x] 6) Вынести п.п.3.1 - 3.4 в отдельный класс и метод, как общий унифицированный

- [x] 7) Добавить в отдельном контроллере EscalationController сервисы (get-еры, set-еры и remove-ры) для сущностей п.1
- [x]  и п.2

**Comment by bvv4ik** [comment]
Ольга, я там один параметр добавил в сущность п.1: "sID_UserTask"
я не успел опомниться, кк Вы реализовали уже два первых пункта)
прошу, и это поле учесть (оно понадобится позже)

**Comment by LamronNu** [comment]
ок, добавлю) все еще в процессе)
часть закоммичена, т.к. проверялся контроллер и правильность создания таблиц в бд)

**Comment by RoOmel** [comment]
Какокй сценарий для теста и где в доке можно прочитать про реализацию этих запросов

**Comment by LamronNu** [comment]
@RoOmel , как только доберусь -- обновлю доку для сущностей EscalationRule  и EscalationRuleFunction, плюс допишу, как проверить всю таску "в целом". Там много нюансов, которые следует проверить, возможно, буду "по частям" описывать..
Постараюсь отписаться в течении этой (т.е. уже следующей) недели.

**Comment by LamronNu** [comment]
что нужно протестировать, основные пункты:
1) "базовые" сервисы нахождения/добавления/обновления/удаления сущностей EscalationRuleFunction и EscalationRule.
2) правильность выполнения условия сКондишион в EscalationRule и кастинг переменных в соДата 
3) отправка писем по расписанию

1) по **EscalationRuleFunction**
"исходный" урл: test.region.igov.org.ua/wf-region/service/escalation
все методы GET

1.1) добавление/обновление, **/setEscalationRuleFunction**
параметры: 
nID - ИД-номер, опционально
sName - обяз.
sBeanHandler - строка бина-обработчика, опционально

ответ: созданная/обновленная запись.

- если нИД не задан, то это создание записи
- если нИД задан, но его нету -- кажется, будет ошибка "403. Record not found"
- если нИД задан, и он есть -- запись обновляется

1.2) удаление, **/removeEscalationRuleFunction**
по нИД, если записи нету -- "403. Record not found"

1.3) нахождение всех, **/getEscalationRuleFunctions**
возвращает список всех записей функций ескалации

1.4) возврат одной записи, **/getEscalationRuleFunction**
по нИД, если записи нету -- "403. Record not found"
если есть -- вернется нужная запись

пока это все, по EscalationRulе и остальным пунктам буду дописывать по мере возможности.
если где-то есть неточности -- пишите, буду исправлять)
спасибо!

**Comment by RoOmel** [comment]
Прошу привести пример хотя бы одного REST-запроса, т.к. любой запрос по данной таске возвращается с одним ответом "HTTP Status 404".
К тому же в таске заданы параметры для setEscalationRuleFunction:
nID - ИД-номер (уникальный-автоитерируемый)
sID_BP - ИД-строка бизнеспроцесса
sID_UserTask - ИД-строка юзертаски бизнеспроцесса
sCondition - строка, до 200 символов 
soData - строка-обьект, с данніми (JSON-обьект), до 500 символов
sPatternFile - строка файла-шаблона
nID_EscalationRuleFunction - ИД-номер функции ,при эскалации.
а в примере реализации их намного меньше.

Колллеги, давайте будем экономить время друг друга.
Идеальным вариантом было бы конечно - добавить описание в доку https://github.com/e-government-ua/i/blob/test/docs/specification.md#0_contents

**Comment by LamronNu** [comment]
в таске две реализованные сущности, мною в комменте описана только одна из них. 
то, что Вы привели параметры -- это EscalationRule (правило эскалации).
я же описала EscalationRuleFunction (функция эскалации), скрин:

![image](https://cloud.githubusercontent.com/assets/8156670/9680709/7726a860-5301-11e5-8df2-2ddb26627e42.png)

полный урл вот:
 www.test.region.igov.org.ua/wf-region/service/escalation/getEscalationRuleFunctions
другие запросы -- по аналогии (меняется последнее слово и добавляются параметры).

дока будет, но позже, т.к. сейчас не хватает времени, поэтому решила писать сюда хотя бы "по частям"..

**Comment by LamronNu** [comment]
**дока** вот: https://github.com/e-government-ua/i/blob/test/docs/specification.md#34
по ней тестируются основные сервисы (добавление/обновление/удаление) по двум сущностям: правило эскалации (EscalationRule) и функция эскалации (EscalationRuleFunction) -- там 8 сервисов.

дальше.
**по самому процессу эскалации.**

правило эскалации -- это запись с указанием бп и задачи, по которым следует отправлять уведомления в случае "зависания", т.е. необработки задач чиновниками.

для теста создан сервис, по которому можно протестировать весь процесс. https://test.region.igov.org.ua/wf-region/service/escalation/runEscalationRule

т.е.  схема теста выглядит так:
1) создаем новое правило, например, так:
https://test.region.igov.org.ua/wf-region/service/escalation/setEscalationRule?sID_BP=dnepr_dms_passport&sID_UserTask=*&sCondition=nDaysLimit%3E0&soData={nDaysLimit:3,asRecipientMail:[%27your@email%27]}&sPatternFile=escalation/escalation_template.html&nID_EscalationRuleFunction=1
 
где указываем:
- свой рабочий емейл (чтобы увидеть это письмо)
- условие эскалации.
в уже наполненной базе частым условием есть условие "nElapsedDays > nDaysLimit", где nElapsedDays  -- это количество пройденных дней (считается в коде), nDaysLimit -- задается в соДата.
в моем примере указано nDaysLimit > 0, что равносильно "для всех задач", поскольку число 3 (из соДата) всегда больше 0... 

- файл-шаблон. можно не менять (поскольку тестируется не шаблон)
- функция эскалации. тоже не меняем (сейчас создан только один бин-обработчик с ид=1, который рассылает письма-уведомления)
- также можно "поэксперементировать" с ид процесса (sID_BP) и ид задачи (sID_UserTask)

2) запоминаем nID
3) запускаем правило на выполнение: https://test.region.igov.org.ua/wf-region/service/escalation/runEscalationRule?nID=[yourID]

если все верно -- получаете "письма счастья" на свой емейл.

4) для теста "расписания в 2 ночи" -- оставляем правило и ждем 2х ночи :)

5) не забываем удалить это правило после всего цикла тестирования

ссылка для создания правила и теста -- рабочая, только что проверялась (выверены все знаки кавычек и слешей, в результате по указанному процессу получено 28 писем).

**Comment by RoOmel** [comment]
Согласно сценария:
1. Создание правила:
Request:
https://test.region.igov.org.ua/wf-region/service/escalation/setEscalationRule?sID_BP=zaporoshye_mvk-1a&sID_UserTask=*&sCondition=nElapsedDays==nDaysLimit&soData={nDaysLimit:3,asRecipientMail:[roman.omeljanenko@privatbank.ua]}&sPatternFile=escalation/escalation_template.html&nID_EscalationRuleFunction=1

Response:
{
    "sID_BP": "zaporoshye_mvk-1a",
    "sID_UserTask": "*",
    "sCondition": "nElapsedDays==nDaysLimit",
    "soData": "{nDaysLimit:3,asRecipientMail:[roman.omeljanenko@privatbank.ua]}",
    "sPatternFile": "escalation/escalation_template.html",
    "nID": 26231,
    "nID_EscalationRuleFunction": {
        "sBeanHandler": "EscalationHandler_SendMailAlert",
        "nID": 1,
        "sName": "Отсылка уведомления на электронную почту"
    }
}
2. Запуск правила:
Request:
https://test.region.igov.org.ua/wf-region/service/escalation/runEscalationRule?nID=26231

Response: 200 ОК
Письма нет

3. Проверка наличия правила:
Request:
https://test.region.igov.org.ua/wf-region/service/escalation/getEscalationRule?nID=26231
Response:
{
    "sID_BP": "zaporoshye_mvk-1a",
    "sID_UserTask": "*",
    "sCondition": "nElapsedDays==nDaysLimit",
    "soData": "{nDaysLimit:3,asRecipientMail:[roman.omeljanenko@privatbank.ua]}",
    "sPatternFile": "escalation/escalation_template.html",
    "nID": 26231,
    "nID_EscalationRuleFunction": {
        "sBeanHandler": "EscalationHandler_SendMailAlert",
        "nID": 1,
        "sName": "Отсылка уведомления на электронную почту"
    }
}

Поиск нового правила поиском email в ответе запроса
https://test.region.igov.org.ua/wf-region/service/escalation/getEscalationRules

4. Удаление правила:
Request:
https://test.region.igov.org.ua/wf-region/service/escalation/removeEscalationRule?nID=26231
Response: 200 ОК

5. Повтор пункта 3
403 Forbidden
{
    "code": "BUSINESS_ERR",
    "message": "Record not found. No such EscalationRule with nID=26231"
}

Реализовано всё согласно ТЗ, кроме отправки письма на email.

**Comment by LamronNu** [comment]
@RoOmel 
Вы указали в параметре сКондишион (условие):
>"sCondition": "nElapsedDays==nDaysLimit"

письмо отравляется только в том случае, если условие истинно, т.е. возвращает true
в Вашем случае нельзя точно определить, какой тут результат был, т.к. неизвестно, сколько дней насчитало в nElapsedDays (эта величина -- сколько дней задача "висит" на обработке).

попробуйте указать nElapsedDays > nDaysLimit (т.е. "прошло больше 3х дней" -- хотя тоже не факт, что такие задачи будут в указанном бп)

или, чтоб наверняка: nDaysLimit > 0

**Comment by RoOmel** [comment]
Семён Семёныч   ...   я всё сделал по инструкции для теста.
Поменял значения параметра "sCondition": "nDaysLimit > 0"
Жду "письмо счастья"

**Comment by RoOmel** [comment]
Если функция рассылки писем реализована и работает - не вижу причин далее продолжать, т.к. кроме этого я всё протестировал.

**Comment by LamronNu** [comment]
так пришло письмо или нет? после того, когда Вы поменяли на условие "nDaysLimit > 0"?
оно должно прийти при запуске /runEscalationRule

**Comment by RoOmel** [comment]
Нет, пробовал несколько раз.
Так а какая разница, может в синтаксисе запроса опечатка.
Если это уже реализовано и людям письма приходят - значит эта проверка не актуальна.

**Comment by LamronNu** [comment]
1) заверните емейл в одинарные кавычки: 'емейл'
2) попробуйте на другом бп. Тот, который Вы выбрали, кажется, либо без задач, либо все задачи обработаны. например, возьмите dnepr_dms_passport, по нему я точно только что получила 28 писем.

**Comment by RoOmel** [comment]
Пришло сразу 28 писем, хотя запрос на запуск сек 20 висел, а потом сервер выругался.

**Comment by RoOmel** [comment]
Прошу доку уточнить по написанию email в запросе.

**Comment by LamronNu** [comment]
ок, уточню.
спасибо!
