### ISSUE TITLE
На бэке (wf-base) в методе replacePatterns заменить захардкоденное перечисление путей к паттернам (String[] asPatterns =) - на автоматическую вічитку реального списка таких файлов по пути /pattern/*

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#659]
- рекурсивно просто перечислить все вложенный в путь файлы (в т.ч. в подкаталогах)
- обращая внимание, что ниже есть пример, который позволяет смотреть на соответствующий путь: oFile = new File("../webapps/wf-region/WEB-INF/classes/"+sName);
- в итоге, в переменной стринговом масссиве asPatterns - должен оказаться список, подобный тому, что сейчас там есть (с относительными путями)
- вычитку списка вынести вверх метода, чтоб он происходил только единажды при вызове метода
- полученный список логировать

**Comment by nazarenkod** [comment]
Как можно проверить данную задачу?

**Comment by bvv4ik** [comment]
не актуально
