### ISSUE TITLE
На главном портале, в профиль Киева добавить стандартное меню, как это отражено на скриншоте.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#660]
чтоб на тестовом открыть профиль Киева, нужно зайти по адресу: https://test.kiev.igov.org.ua
(учесть вид на маленьком экране смартфона)

![image](https://cloud.githubusercontent.com/assets/4208821/9177002/5d4cdb9e-3f97-11e5-9b15-5941c3af3c64.png)

**Comment by VadymVolos** [comment]
На будущее если будете на портале делать поддомен для Киева, имя его правильно сделайте:
kyiv.igov.org.ua

**Comment by hordesalik** [comment]
Меню добавил, но не могу понять почему оно не работает

**Comment by rooksnest** [comment]
Некорректное отображение на мобильных устройствах:
**iPad (Safari, iOS 8.1)**
![img_0100](https://cloud.githubusercontent.com/assets/13005113/9267789/25c09d36-425e-11e5-81b3-9a7bea870f02.PNG)
![img_0101](https://cloud.githubusercontent.com/assets/13005113/9267794/30b15ea6-425e-11e5-999c-7d3779e3a738.PNG)
**iPhone 4S (Safari, iOS 8.4)**
![img_0367](https://cloud.githubusercontent.com/assets/13005113/9267804/53643090-425e-11e5-9685-f7682e323969.PNG)
![img_0366](https://cloud.githubusercontent.com/assets/13005113/9267806/6054567c-425e-11e5-9647-3f49138b1512.PNG)
**ASUS Transformer Pad TF300T (Android 4.4.1, Chrome 43.0.2357.92)**
![screenshot_2015-08-14-08-42-35](https://cloud.githubusercontent.com/assets/13005113/9268398/41105136-4267-11e5-901f-a1630a7577e5.jpg)
![screenshot_2015-08-14-08-42-51](https://cloud.githubusercontent.com/assets/13005113/9268401/456574dc-4267-11e5-916e-1690ec9b3ba5.jpg)

**Comment by VadimGulich** [comment]
Нужно исправить ошибки под мобильными устройствами

**Comment by bvv4ik** [comment]
под мобильное устройство пока не затачиваемся
закрываем эту старую таску

**Comment by VadimGulich** [comment]
понял , тогда закрываю
