### ISSUE TITLE
На главном портале реализовать "умную форму" (в зависимости от вводимых данных в одни поля - отображать/скрывать другие поля)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#661]
- [ ] 1) дополнить унифицированный объект "markers" - блоком "motion"(по мимо validate), в котором описывать поведение (поискать в коде слово "markers", и дополнить тот обьект + дописать логику поведения):

  var markers = {
    validate: {
      PhoneUA: {
        aField_ID: ['privatePhone', 'workPhone', 'phone', 'tel']
      },
      ....(валидаторов уже много, перечислять их все не буду)...
      Mail: {
        aField_ID: ['privateMail', 'email']
      }
    },
    motion: {
      ShowFieldsOnNotEmpty_1: { //Показывает поля при не пустом указанном поле (иначе скрывает)
        aField_ID: ['sPhone_User1', 'sMail_User1'] //'text3', 'phone'
        , sField_ID_s: 'sFIO_User1' //fioUA
      },
      ShowFieldsOnTrue_1: { //Показывает поля при определенном значении указанного поля (иначе скрывает)
        aField_ID: ['sFIO_User1','sAddress_User1']
        , sField_ID_n: 'nID_Type_User1' //опционально
        , sField_ID_n1: 'nID_SubType_User1' //опционально
        , sField_ID_s2: 'sID_Type_User1' //опционально
        , sCondition: "[n]==1 || [n]==[n1] || [s2]=='none' || ([n] >10 && [n] < 20)"
      }
    }

  };

- [ ] 2) Добавить новый элемент "ShowFieldsOnNotEmpty_*", с такой логикой работы:
- [ ] 2.1) Если поле на форме, с ИД, которое указано в параметре "sField_ID_s" - является не пустым (т.е. не равно null и не пустая строка(в т.ч. через trim), то отображать все поля (с лэйблами), ИД-шники которых указаны в параметре-массиве aField_ID.
- [ ] 2.2) Если п.2.1. не выполняется - скрываем эти поля
- [ ] 2.3) Такая логика поведения должна быть на всех элементах, которые начинаются с "ShowFieldsOnNotEmpty_", т.е. "ShowFieldsOnNotEmpty_1", "ShowFieldsOnNotEmpty_2"... При том в каждом элементе могут быть свой набор полей, и соответственно проверка тоже своя.

ВАЖНО: Скрывать/отображать поля на форме нужно целым блоком (лейбл к полю и сам контент поля)

- [ ] 3) Добавить новый элемент "ShowFieldsOnTrue_*", с такой логикой работы:
- [ ] 3.1) Условие в поле "sCondition" является true, то отображать все поля (с лэйблами), ИД-шники которых указаны в параметре-массиве aField_ID.
- [ ] 3.2) Если п.2.1. не выполняется - скрываем эти поля
- [ ] 3.3) Такая логика поведения должна быть на всех элементах, которые начинаются с "ShowFieldsOnTrue_", т.е. "ShowFieldsOnTrue_1", "ShowFieldsOnTrue_2"... При том в каждом элементе могут быть свой набор полей, и соответственно проверка тоже своя.
- [ ] 3.4) В выражении "sCondition"
- [ ] 3.4.1) заменяются "ссылки на переменные" в квадратных кавычках на фактические значения тех полей, ИД-шники которых в этих элементах содержатся.
- [ ] 3.4.2) значения подставляются в кавычках стринговые (если идентификатор начинается с символа 's'), а без кавычек номерные (если идентификатор начинается с символа 'n').
- [ ] 3.4.3) после замены ссылок на переменные на сами значение - происходит eval(или аналог), и значение присваивается переменной bShowFieldsOnTrue_* (по названию элемента, но с добавлением b в начеле(Boolean), т.е. для примера п.1. это будет bShowFieldsOnTrue_1).
- [ ] 3.4.3)  Результат выполнения (true/false) используется в п.п. 3.1

Например, выражение:
sCondition: "[n] == 1 || [s2] == 'none' || ([n] >10 && [n] < 20)"

Указан под-элемент: sField_ID_n: 'nID_Type_User1'
по этому "[n]" заменится значение из поля с id=nID_Type_User1 (например там число 123)

Указан под-элемент: sField_ID_s2: 'sID_Type_User1' (например там строка 'none')
поэтому "[s2]" заменится значение из поля с id=sID_Type_User1

В итоге выражение преобразуется в:
"123 == 1 || 'none' == 'none' || (123 >10 && 123 < 20)"
И выполняется в виде:
eval("var bShowFieldsOnTrue_1 = (123 == 1 || 'none' == 'none' || (123 >10 && 123 < 20))");

- [ ] 4) Механизм должен отрабатывать "онлайн", а не только при загрузке формы. Т.е., если гражданин ввел какие-то данные в поле, от которого зависит отображение других - этот механизм должен будет сработать и отобразить/скрыть соответствующие поля.

ДЛЯ ЧЕГО ЭТО НУЖНО:
Реальный процесс - получение материальной помощи.

Заявка может подаваться получателем мат.помощи или его представителем (значение ввыбирается на форме).
В  зависимости от того кто подает - отличающийся набор полей и прикрепляемых обязательных документов.

https://test.igov.org.ua/service/671/general - тестовый процесс.

На дашборде он попадает  в обработку  для  аккаунта "tester"

**Comment by bvv4ik** [comment]
прошу обратить внимание на важный пункт в таске:
ВАЖНО: Скрывать/отображать поля на форме нужно целым блоком (лейбл к полю и сам контент поля)

**Comment by serdyuk-alex** [comment]
Закомитил движок, для проверки нужно в бп добавить 
```javascript
markers {
    motion: {
      ShowFieldsOnNotEmpty_1: {
        aField_ID: ['email']
        , sField_ID_s: 'client'
      },
      ShowFieldsOnCondition_1: {
        aField_ID: ['info1','file1']
        , asID_Field: { sClient: 'client' }
        , sCondition: "[sClient] == 'attr1'"
      },
      ShowFieldsOnCondition_2: {
        aField_ID: ['info2','file2']
        , asID_Field: { sClient: 'client'}
        , sCondition: "[sClient] == 'attr2'"
      }
    }
}
````
Будет отображать поля поля представителя/получателя в зависимости от выбранной опции. Будет отображать email только если опция не пустая.

**Comment by bvv4ik** [comment]
Проверить можно на услуге:
https://test.igov.org.ua/service/671/general

(_test_dependence_form)

достаточно выбирать разные варианты энума и будут отображаться разные производные поля

**Comment by smit-pb** [comment]
Что-то явно пошло не так ;)
![image](https://cloud.githubusercontent.com/assets/12965717/9897741/9a89ba2a-5c54-11e5-8f36-224576f6c49e.png)
Я не нашел отличия -
![image](https://cloud.githubusercontent.com/assets/12965717/9897745/a57c55b4-5c54-11e5-8718-b21ad3b6e07f.png)

**Comment by smit-pb** [comment]
Реализована.
