### ISSUE TITLE
Написать на вики страницу со стандартами проекта

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#662]
На этой странице со стандартами:
https://github.com/e-government-ua/i/wiki/%D0%9D%D0%B0%D1%88%D0%B8-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D1%8B

- [x] 1) Стандарты создания контроллера с сервисами в нем
- [x] 2) использование liquibase (где они лежат базовые чанджсеты, которые трогать нельзя)
- [x] 2.1) правила добавления "чанджсетов" для liquibase (где они лежат для регионального/бэйса и центрального)
- [x] 2.2) использование файлов "лоадеров данных" (/data/*) для liquibase (где они лежат для регионального/бэйса и центрального, и как учитіваются подпапки beta и test)
- [x] 3) использование hibernate и базовых сущностей
- [x] 4) использование queryloader-а (для хранения SQL-запросов)
- [ ] 5) где хранятся БП, и как учитываются подпапки beta и test
- [ ] 6) где хранятся контексты и проперти и как они наследуются проектами (в т.ч. приписка *_local)
- [x] 7) при использовании маркированных переменных ,что означают в начале их названий маленькие буквы:
n,s,b,m,a,o, с примерами... (и возможные их комбинации: so,sa,as,ab,an,ao,ma,am,,, и т.д.,)
- [ ] 8) что за папка с шаблонами: /pattern/* (шаблоны для форм печати, шаблоны для писем и т.д.), и как, например, можно использовать в БП шаблоны из "pattern.print/*"
- [x] 9) Методы авторизации (basic-authorization)
- со стандартным системным логином паролем
- с логином/паролем из активити
- с одноразовым ключем (сгенерированным)
- [ ] 10) Информация и инструкция к используемым модулям
- [ ] 10.1) Электронная очередь
- [ ] 10.2) Электронные платежи (Liqpay), в т.ч. с отсылкой "кнопки оплаты" письмом
- [ ] 10.3) Электронная эскалация (в процессе реализации)
- [ ] 10.4) Мультиформы печати
- [ ] 10.5) Отправки писем с прикреплениями (атачментами) и без, в т.ч. с фидбэком
- [ ] 10.6) Наследование прикреплений (атачментов) из юзертаски в юзертаску

**Comment by LamronNu** [comment]
сделан небольшой "каркас" для задачи: https://github.com/e-government-ua/i/wiki/Project-Standarts
изменения/дополнения приветствуются)
смогу взять первый пункт, второй (по ликвибейз) и 7й (маркированные переменные). 
писать буду по мере возможности) пока другие задачи важнее.

**Comment by LamronNu** [comment]
дописан 1 и 2й пункты, также отмечено, что уже прописаны 3й, 4й и 7й.

Здесь отмечено, что написан 9й (про авторизацию) -- но этот пункт там пустой... это ошибочно отмечено или информация в другом месте?
