### ISSUE TITLE
На бэке главного портала использовать подобный(но более автоматизированный) механизм шаблонизации "Инструкций", "ЧАВО" и "законодательства"(sInfo;sFAQ;sLaw) к услугам(через отдельные файлы), как и для мульти-форм  печати

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#663]
т.е. путь к файлу "встраивать"(в квадратных скобках) прямо в поля: sInfo, sFAQ или sLaw

При этом для полей:
sInfo - использовать корневой путь /patterns/services/Info/*
sFAQ - использовать корневой путь /patterns/services/FAQ/*
sLaw - использовать корневой путь /patterns/services/Law/*

Например:
- "[*]" - такая конструкция в поле sInfo, должна брать файл: /patterns/Info/345.html, где 345 - ид-услуги, и заменяться на его содержимое.
- "[/custom.html]" - такая конструкция в поле sFAQ, должна брать файл: /patterns/FAQ/custom.html, и также заменяться на его содержимое.

П.С.: Для поиска примера вытягивания файла-шаблона, в коде искать метод getPatternFile(String sPathFile)

**Comment by dmitrijzabrudskij** [comment]
https://test.igov.org.ua/service/752/questions

не работает на альфе

вот строчка в файле service:
752;Призначення соціальної допомоги при народженні дитини;752;2;[752];[/752.html];[/patterns/services/Law/752.html];Обласна державна адміністрація 

я пробовал добавлять ссылки на описания разными способами - ни один не сработал.

подскажите в чем моя ошибка?

**Comment by bvv4ik** [comment]
в таске-ж написано, что должно быть:
[*]

**Comment by dmitrijzabrudskij** [comment]
https://test.igov.org.ua/service/752/instruction

все равно не получается. паттерны в центральном

**Comment by kurbpa** [comment]
@bvv4ik 
@VadimGulich 

прописал как - 628;Надання одноразової матеріальної допомоги громадянам;21;2;[*];;;Обласна державна адміністрація

https://test.igov.org.ua/service/628/instruction - не работает

**Comment by bvv4ik** [comment]
поправлено:
https://test.igov.org.ua/service/752/instruction

**Comment by smit-pb** [comment]
![image](https://cloud.githubusercontent.com/assets/12965717/10094532/88c05990-6369-11e5-92a8-84346fbbfb9b.png)

А это нормальное отображение ? - или всеже поломано что-то ?

**Comment by smit-pb** [comment]
![image](https://cloud.githubusercontent.com/assets/12965717/10094551/b06c0ab6-6369-11e5-8a43-a38ed5bfa40c.png)

И это тоже не хорошо.

**Comment by smit-pb** [comment]
Владимир - Отображение информации - которое показано на скринах, это нормально ? 
или будет правиться ? 
Если будет правиться - то в рамках этой задачи ? или новой задачи ?

**Comment by dmitrijzabrudskij** [comment]
задача протестирована и уже выставлена в бой. работает без нареканий. закрываю таску. всем спасибо)
