### ISSUE TITLE
date/time визита

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/i#664]
сохранять из поля visitDate с типом queueData дату и время, выбранные гражданином на старте процесса, в переменную date_of_visit

сейчас при создании услуге. в листенере(на яве) сохраняется целиком объект в поле "visitDate" (там и поправить.

П.С.: доработка нужна для красивого отображения даты визита в имейле гражданину (сейчас туда тянется все содержимое поля visitDate)

**Comment by dmitrijzabrudskij** [comment]
https://test.igov.org.ua/service/176/general/

не работает эта переменная  активити не понимает что это такое

**Comment by bvv4ik** [comment]
плиз, проверь еще раз, должно быть уже все гуд

**Comment by dmitrijzabrudskij** [comment]
все ок. можно в бой. 

пс: хотя хотелось бы секунды и милли секунды вырезать из этой переменной:)
