### ISSUE TITLE
добавить дату рождения гражданина в параметры по умолчанию

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/i#665]
добавить параметр bankIdbirthDay в стандартные данные, получаемые из банкид (наряду с именем, фамилией и прочим)

**Comment by bvv4ik** [comment]
нужно указать БП, в котором это поле уже будет, чтоб можно было его протестить

**Comment by bvv4ik** [comment]
реализовано, все будет работать с полем bankIdbirthDay

**Comment by dmitrijzabrudskij** [comment]
dnepr_subsidies
залито на альфу

**Comment by VadimGulich** [comment]
Проверено , дата добавлена
