### ISSUE TITLE
Реализовать  автозамену разделителей "запятая ->точка " в значениии переменной sSum

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#666]
при взятии значения поля юзертаски, для Liqpay:

Если в  переменную sSum  была передана запятая в качестве разделителя, автоматически заменять её на точку.

**Comment by RoOmel** [comment]
Реализовано согласно ТЗ.
Запрос с параметром sSum = 55,66
![liqpay](https://cloud.githubusercontent.com/assets/12996514/9329835/9e7fac46-45bd-11e5-8204-20707d0ed059.jpg)
