### ISSUE TITLE
Реализовать на дашборде возможность поиска заявок по ID.

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#667]
- [x] 1. Над перечнем заявок ( левее   сортировки ) добавить поле ввода для поиска заяки по id
- [x] 2. Поиск производить по тем процессам, к которым  есть доступ  у текущего  пользователя. (т.е. фактически тому списку который загружен в закладке)
- [x] 3. Поиск производить по
сервису getTasksByOrder
https://github.com/e-government-ua/i/issues/686
(по первому из найденный иди, которые в возвращаемом массиве) и
- при нахождении разместить курсор на выбранной строке(не курсор мыши а селектор строки)
- при получении ошибки с содержимым "CRC-error" - выдавать диалог с сообщением "Неверный ИД"
- при получении ошибки с содержимым "Record not found" - выдавать диалог с сообщением "ИД не найден"
- [x] 4. В списке заявок обернуть в скобки id-таски (и отнести в конец строки)

**Comment by bvv4ik** [comment]
нужна какая-то графическая зарисовка

**Comment by kurbpa** [comment]
![image](https://cloud.githubusercontent.com/assets/11442397/9232389/0d4e3386-4136-11e5-8f85-3229e00701dd.png)

Например вот так.

**Comment by bvv4ik** [comment]
готов сам бэковый сервис поиска:
https://github.com/e-government-ua/i/issues/686

**Comment by serdyuk-alex** [comment]
1. Логинимся на central и находим поиском услугу test та которая с mail, заказываем её, запоминаем номер который в сообщении будет после заказа: 
Ваше звернення №265***** успішно зареєстровано
2. Логинимся на дашбоард чиновника под tester/tester, находим засабмиченую юзером услугу на вкладке незаасайненых здесь уже можно выполнять поиск по номеру "звернення" который получили в п.1, можно заасайнить и она перейдет на табу "В роботі" там тоже можно проверить тоже самое.

Если таска найдена но ее нету на текущей табе будет сообщение: 
'У даному розділі ID не знайдено, спробуйте виконати пошук у суміжних'

**Comment by OlgaKotova** [comment]
@serdyuk-alex  значит по пунктам:
1. Услугу заказала, № получила(26851824)
2. Во вкладке "Необработанные "вела полученный в п.1 номер таски, справа в окне увидела кнопку "Взять в работу"(как-то так), но ни номера таски ни ее описания не было(просто пустая страница). Нажала "Взять в работу", после этого задача появилась во вкладке "В работе", но с другим номером - № 2685201, попыталась найти ее же по старому номеру во вкладке "Необработанные", увидела сбщ "У даному розділі ID не знайдено, спробуйте виконати пошук у суміжних". 

Вот как-то так отработала задача.

**Comment by bvv4ik** [comment]
""У даному розділі ID не знайдено, спробуйте виконати пошук у суміжних"."
ну так это и означает, что нужно перейти в ту закладку, куда "переехала таска",...  и там искать
именно так это реализовано - ищет только по выбранной закладке

**Comment by OlgaKotova** [comment]
@bvv4ik я понимаю, но, как я написала выше "Нажала "Взять в работу", после этого задача появилась во вкладке "В работе", но с другим номером - № 2685201", если так и должно быть, закрываем

**Comment by bvv4ik** [comment]
так и должно быть) т.к. это "внутренний номер"...

**Comment by VadimGulich** [comment]
все ок)
