### ISSUE TITLE
Узнать, какими методами Activiti (и в каких классах), можно авторизовать по логину/паролю пользователя (проверить его идентичность)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#67]
Подобно тому, как это реализовано в Activiti Explorer.
Чтоб можно было реализовать свой собственный интерфейс (фронт) авторизации, вместо Activiti Explorer, посредством вызова с него REST-сервиса.

**Comment by AleksejDomash** [comment]
нужен новый сервис в модуле wf-dniprorada. использовать IdentityService.checkPassord

**Comment by bvv4ik** [comment]
как раз этим вопросом занялся zora.borys
в задаче https://github.com/e-government-ua/i/issues/67
можешь связаться с ним?

**Comment by bvv4ik** [comment]
все узнал:

на жаве я юзера получал так:
User user = ProcessEngines.getDefaultProcessEngine()
    .getIdentityService().createUserQuery().userId(key).list().get(o);

потом ,доставал, то, что надо:
getEmail()
getFirstName()
getId()
getLastName()
>>>>>>>getPassword()

**Comment by maxtmn** [comment]
ProcessEngines.getDefaultProcessEngine()
				.getIdentityService().checkPassword(userId, password)
можно использовать и этот
