### ISSUE TITLE
На главном портале доработать раздел "Документы"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#671]
1. Вводя емейл (мол, на него будет отправлено письмо) -должно приходить письмо на него вида:
https://docs.google.com/document/d/1n2FIhsBrZMq6b8vqyvBoGdSfJiNLNVQZDTQucw7d2C0/edit?pli=1
2. В поле ввода телефона сразу подставлять +380

**Comment by dn190187kaj** [comment]
Работает.
Проверил:
1. Письмо приходит.
2. По умолчанию в поле ввода телефона отображается +380

**Comment by bvv4ik** [comment]
2. а удалось проверить предоставление доступа без ввода телефона и с вводом телефона? а потом проверить этот доступ? это важно. т.к. это могло повредиться.,.

**Comment by dn190187kaj** [comment]
Только что проверил. 
Если номер телефона вводить - тогда все норм - требует ввода пароля из смс.
А вот если выбрать что нужно вводить телефон, но поле телефона не заполнить - тогда пароль не требует. (скриншоты 1 и 2)
![1](https://cloud.githubusercontent.com/assets/13554482/9257139/9346623a-41fc-11e5-91cd-9271854ac576.jpg)
![2](https://cloud.githubusercontent.com/assets/13554482/9257140/934c5d0c-41fc-11e5-81ee-ce6a4b9f9fd8.jpg)

Предлагаю сделать поле телефон - обязательным для заполнения, как и поле ФИО.
Тогда нельзя будет отправить разрешение на доступ без заполенния поля телефон.

(p.s. и смс на телефон не приходят, это я так понимаю еще не настроено?)

**Comment by bvv4ik** [comment]
не всегда нужна такая защита что будет требовать смс, потому поле обязательным не должно быть..

по поводу СМС - просто для тестовых отсылка на СМС отключена... а вклюсается только на боевом... на тестовом действует пароль 4444

**Comment by bvv4ik** [comment]
т.е. я так понимаю - все норм...

**Comment by bvv4ik** [comment]
?

**Comment by dn190187kaj** [comment]
нет, не норм.
Если клиент выбирает что хочет защитить док-т смс-паролем "ТАК", но поле телефон не заполняет - тогда пускает без запроса смс пароля.
А по идеи - не должно. Выделил на скриншотах что имею ввиду.
![1](https://cloud.githubusercontent.com/assets/13554482/9276551/57a15602-42ad-11e5-88cc-b4dd3a2c9dee.jpg)
![2](https://cloud.githubusercontent.com/assets/13554482/9276550/57a04e7e-42ad-11e5-8df7-41ff23c2cef2.jpg)

**Comment by dn190187kaj** [comment]
К примеру клиент хотел защитить доступ через смс, но забыл указать телефон -  система должна требовать смс-пароль (даже если телефон не указан).

**Comment by bvv4ik** [comment]
это нормальное поведение, и не считается ошибкой...
кроме тог, это ни какого отношения не имеет к реализации данной таски.
если кроме этого замечаний нет - можно закрывать таску

**Comment by bvv4ik** [comment]
кроме того - не надо убирать лэйбл тест, т.к. тогда таска теряется... нужно просто добавлять еще один лэйбл - в процессе тестирования и, опционально, question или remark
