### ISSUE TITLE
В дашборде чиновника добавить новую вкладку "Тикеты"

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/i#672]
- [ ] 1) реализовать новую отдельную вкладку в дашборде чиновника "Тикеты"
- [ ] 2) отображать в ней список заявок-тикетов "Дата-время №Заявки №Тикета"
(Дату и время, на которое назначена заявка, можно взять из переменной sDate)
- [ ] 3) добавить фильтр выбора дня для просмотра назначенных на него заявок (по умолчанию текущая дата)
- [ ] 4) При клике на заявку отображать ее по стандарту в правой половине экрана (по ИД заявки сейчас и так есть реализованный механизм получения ее объекта, вот его и использовать)

Данные брать из сервиса: getFlowSlotTickets,
реализующегося по таске: https://github.com/e-government-ua/i/issues/688

ДО его реализации брать мок-обьект, на основании того примера что указан в задаче по сервису (выше)

**Comment by VadymVolos** [comment]
Чуть от себя добавлю, услуги не чиновники выполняют а обычные служащие.Если в отделе больше одного человека, нужно предусмотреть чтоб возле заявки была отметка кто из сотрудников взялся выполнять задачу.

**Comment by bvv4ik** [comment]
тикеты так-же как и заявки отображаются тем сотрудникам, кому они предназначаются...

тайминги по результатам работы - это совершенно другая тема и тут у нас уже и есть наработки(статистика) и реализуются новые(электронные эскалации)

**Comment by VadimGulich** [comment]
Проверено , можно в релиз
