### ISSUE TITLE
На главном портале На форме поиска документа изменить текст:

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#673]
Введіть отриманий Вами SMS код -> Введіть отриманий Вами SMS-код на телефон +38067*****62.

П.С.: телефон брать из ответа сервиса, который имеет вид:
"Document Access password need - sent SMS ("+sPhone+")"

**Comment by smit-pb** [comment]
А Можно мокап - ? т.к. сообщение "Введіть отриманий Вами SMS-код на телефон +38067*****62" - нигде не появляется.
