### ISSUE TITLE
На главном портале в форме с элементом электронной очереди (для МРЭО), при отображении списка доступных дат - отображать только даты, начиная с послезавтра

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#674]
Это делается за счет задачи дополнительного параметра-фильтра(дата-послезавтра) по дате в изначальном сервисе (описание на Вики в АПИ)
/getFlowSlots_ServiceData
в параметр sDateStart передать дату "послезавтра"

ДЕТАЛЬНЕЙ:
Необходимо давайть возможность гражданину выбирать день посещения МРЭО не ранее чем через 1 рабочий день в графике этого МРЭО.

Т.е.  если гражданин подает заявку в среду, то нужно, чтобы он могу указать желаемый день визита не  ранее чем  в пятницу.

**Comment by bvv4ik** [comment]
реализовано на стороне сервера

**Comment by bvv4ik** [comment]
вадно проверить только что отображает с послезавтра самого начала дня

**Comment by smit-pb** [comment]
Задача выполнена - при отображении списка доступных дат - отображать только даты, начиная с послезавтра .
