### ISSUE TITLE
Добавить на портал готовые услуги (реєстрація шлюбу, і тп)

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/i#675]
Поступил фидбек от Андрій Дейнека, о том что на сайте минюста уже есть услуги, а у нас на портале они еще не активны:

=
На сайті неактивні послуги: реєстрація шлюбу, розірвання шлюбу, реєстрація народження\смерті, зміна імені. Хоча мінюст уже запустило портал у пілотному режимі з цими послугами. 
http://dracs.minjust.gov.ua/
https://igov.org.ua/subcategory/1/20

=
Ссылка на  текст фидбека: https://www.facebook.com/groups/458833010941504/permalink/497567530401385/?comment_id=497569063734565&offset=0&total_comments=1&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by bvv4ik** [comment]
@dmitrijzabrudskij Дима, сможешь добавить?

**Comment by dmitrijzabrudskij** [comment]
опишите для каких областей доступно и можно ли прямую ссылку на саму услугу, а не на стартовую их портала?

**Comment by 40rn05lyv** [comment]
Посилань на послугу немає - потрібно реєструватись і заходити у свій кабінет.
Послуги працюють по м.Київ, Київська область, Одеська область, Дніпропетровська область.

**Comment by rostag** [comment]
Прямі посилання на послуги все ж є, але працюють з помилками. Так, послуга "Заява про державну реєстрацію шлюбу" знаходиться тут:
http://dracs.minjust.gov.ua/Reserv/StageOne/0

Якщо користувач не залогінився на сайт, то його перекидають на сторінку логіну з запам'ятованим редиректом на сторінку послуги:
http://dracs.minjust.gov.ua/Home/Index?ReturnUrl=%2fReserv%2fStageOne%2f0

До цього моменту все добре, а ось після логіну виникає помилка ASP.NET "Server Error in '/' Application. - The resource cannot be found." і см потрапляємо на стартову:
http://dracs.minjust.gov.ua/Home/Main_menu/Index

@VadymVolos - чи можна якнайшвидше повідомити розробникам про те, що сайт має таку важливу помилку?

**Comment by rostag** [comment]
Я б написав їм сам, але на сайті http://dracs.minjust.gov.ua/ немає жодного зворотнього звязку - думаю, про цю помилку їм також варто повідомити ;-)

**Comment by VadymVolos** [comment]
Сверху кнопка "Допомога"
но там есть только телефон:

У випадку виникнення проблем під час роботи з сайтом просимо зателефонувати:
черговому інженеру за телефоном: (+38 044) 206-71-10
Версія веб-порталу: 2.8.1.0

**Comment by VadymVolos** [comment]
Я так понимаю ссылки на услуги человек сможет увидеть только когда авторизируется там на портале. Если не авторизован будет перекидывать на главную...

**Comment by VadymVolos** [comment]
У них там интересные документ по ссылке "Первинна реєстрація - Я ознайомленний з порядком роботи з веб-порталом" (http://dracs.minjust.gov.ua/Home/GetRoolDocument/%D0%9F%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA%20%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B8%20%D0%B7%20%D0%B2%D0%B5%D0%B1-%D0%BF%D0%BE%D1%80%D1%82%D0%B0%D0%BB%D0%BE%D0%BC.pdf)

Возможно этот текст нам пригодится для описание этой услуги.

**Comment by VadymVolos** [comment]
Вот интересная инфа, я б ее добавил у нас на потртале на вкладку "Новини про послугу"
[В Україні вперше одружилися молодята, які подали документи онлайн](http://galinfo.com.ua/news/v_ukraini_vpershe_odruzhylysya_molodyata_yaki_podaly_dokumenty_onlayn_200213.html)

**Comment by 40rn05lyv** [comment]
Бачу, що додали низку послуг на головну - https://igov.org.ua/service/703/general/city . Однак додали неточно. Додали лише м. Одеса, м. Київ і м. Дніпропетровськ. Тоді як ці послуги діють і в інших районах Одеської області (Котовськ, Ізмаїл, Кілій, Южне, Рені, Ширяєве, Балта і т.д.) і Київської області (Ірпінь, Бровари і т.д.).

**Comment by bvv4ik** [comment]
тут продублирую, на всяк случай:
такие таски как эта(про новые услуги и БП) теперь можно создавать в отдельном репозитории:
https://github.com/e-government-ua/iBP/issues
а тут не стоит(тут больше по разработке таски)...

**Comment by bvv4ik** [comment]
я так понимаю - не актуально
