### ISSUE TITLE
На бэке (wf-base) реализовать эскалацию(отправку электронки), если по каким-то причинам калбэк ликпея(платежа) отработал с ошибкой

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#678]
слать письмо на bvv4ik@gmail.com и dmitrij.zabrudskij@privatbank.ua
дать возможномть повторить платеж (кнопку), с заполнением ИД транзакции и результата

**Comment by bvv4ik** [comment]
проверить можно:
-найдя в коде  bvv4ik@gmail.com через запятую добавить туда свою электронку.
-создав задачу(например тестовую) для ликпея, добиться отсылки письма с кнопкой человеку, -потом в активити-эксплорере "прибить" эту таску,
-отправить платеж по кнопке ликпея... 
должна произойти ошибка и отсылка электронки...

**Comment by nazarenkod** [comment]
@bvv4ik Добрый день.Не могли бы Вы добавить мою почту nazarenkod1990@gmail.com для тестирования этой задачи

**Comment by OlgaTurenko** [comment]
@nazarenkod Как у нас продвигается тестирование по задачке?
