### ISSUE TITLE
На главном портале реализовать в профиле услуги подвкладку "Статистика"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#681]
1) Отображаем ее для каждой “зеленой” услуги (можно посмотреть на главной при каком статусе она "маркируется" зеленой)
2) В ней выводим таблицу такого формата:
Область | Кількість наданих послуг %Название услуги%
Область-1 | N1
Область-2 | N2
3) Загружать через сервис getStatisticServiceCounts?nID_Service=1&nID_Region=2 данные и заполнять ими таблицу п.2 (сервис реализуется по таске: https://github.com/e-government-ua/i/issues/684)

П.С.: Если сервис еще не готов, то можно замокать возвращающий объект с одним/двумя фэйковыми записями в массиве.. При этом реализовав сам основной механизм запроса по сервису, но пока временно не задействовав его.(как сервис запустится - сможем переключиться)

**Comment by VadymVolos** [comment]
Я делал в ГуглТаблицах подобную таблицу https://goo.gl/PgXrZQ
Посмотрите возможно возьмете идеи от туда.
Смысл данной таблицы отслеживать эффективность по областям.
Также потом была просьба не только по областям но и каждому городу в области.
Чтоб можно было развернуть Нужную область и посмотреть уже по городам.

**Comment by serdyuk-alex** [comment]
Для проверки заходим на любой сервис и смотрим в табу "Статистика"
В скоупе комита были затронуты базовые механизмы по переходам вьюх в ui-route для сервисов. Нужно провести регрессионное тестирование заказа нескольких сервисов.

**Comment by RoOmel** [comment]
Если задача состояла в реализации вкладки и полей - согласно ТЗ.
Если должен осуществляться подсчёт обращений - не реализовано.
1. Посмотрел статистику в "Видача копій, витягів з розпоряджень міського голови, рішень, прийнятих міською радою та виконавчим комітетом";
2. Создал заявку и получил сообщение "Ваша заявка 30152483 прийнята!" на "мыло";
3. Повторил пункт 1 - счётчик не увеличился.

**Comment by bvv4ik** [comment]
нужно перепроверить т.к. были пролиты фиксы

**Comment by RoOmel** [comment]
Проверил снова.
Взял другую услугу - результат прежний - подсчёт работает некорректно, либо не работает вообще.

**Comment by VadimGulich** [comment]
Появилась ошибка при просмотре статистики:
![image](https://cloud.githubusercontent.com/assets/12964120/9994856/dc5632f8-6087-11e5-91be-bcb693e3c42e.png)

**Comment by bvv4ik** [comment]
Вроде теперь ошибок не пишет...
а сами цифры рейтинка там появятся только после того как фидбэки пойдут... потому, именно интерфейсная часть тут вроде реализована..

https://test.igov.org.ua/service/729/statistics

![image](https://cloud.githubusercontent.com/assets/4208821/9995178/68251b5e-6089-11e5-9f54-e7e77cbcb549.png)

**Comment by VadimGulich** [comment]
да , исправлено , ошибки больше нет , интерфейс реализовано
