### ISSUE TITLE
На бэке централа реализовать сервис getStatisticServiceCounts и дополнить сущность истории статусов полями nID_Service и nID_Region

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#684]
1) добавить в сущность HistoryEvent_Service поля (опциональные):
nID_Service - ИД-номер сервиса
nID_Region - ИД-номер региона
sID_UA - ИД-номер места (по классификатору КОАТУУ)
2) добавить поля п.1. в гетеры и сетеры сервисов этой сущности
3) Реализовать сервис getStatisticServiceCounts 
в который должен передаваться параметр:
nID_Service 
а в ответ возвращаться структура вида:
[
{
"sName":"Днепропетровская"
"nCount":7
}
,{
"sName":"Львовская"
"nCount":5
}
]
Которая должна формироваться на основании выборки из таблицы сущности HistoryEvent_Service 

4) При вызове сервиса создания новой записи в сущности HistoryEvent_Service
передавать туда 
параметры 
nID_Service - ИД-номер сервиса
nID_Region - ИД-номер региона
sID_UA - ИД-номер места (по классификатору КОАТУУ)
(вызов происходит в т.ч. из класса RequestProcessingInterceptor, где важно взять эти параметры из Request-а, если они там есть)

5) Актуализировать документацию по этим АПи на нашей Вики

**Comment by bvv4ik** [comment]
@uazure вроде-ж ты фронтом занимаешься? а это чисто ява-бэковая таска...
для нее фронтовая часть тут: https://github.com/e-government-ua/i/issues/681

**Comment by ASkosyr** [comment]
Пример вызова сервиса

https://test.igov.org.ua/wf-central/service/services/getStatisticServiceCounts?nID_Service=1

**Comment by ASkosyr** [comment]
Обновил документацию
https://github.com/e-government-ua/i/blob/test/docs/specification.md#33_getStatisticServiceCounts

**Comment by RoOmel** [comment]
При тестировании был создан запрос

**Comment by bvv4ik** [comment]
можно уже просто зайти в ценьтральный портал, услугу (например по МРЕО) и там в подзакладке "Статистика" подтянутся данные
это и будет доказательство работоспособности

**Comment by RoOmel** [comment]
Сообщение выше "можно уже просто зайти в ценьтральный портал, услугу (например по МРЕО) и там в подзакладке "Статистика" подтянутся данные
это и будет доказательство работоспособности" - это для кого вообще?

**Comment by bvv4ik** [comment]
дальнейшее тестирование этой задачи очень даже актуально,
и для того чтоб тестирование было реально полезным и продуктивным - я и описал способ проверки

тем более сто выяснилось, что п.4. не реализован!
т.е. не сохраняется при создании заявки данные по сервису, областям и КОАТУУ

**Comment by bvv4ik** [comment]
пошел деплой фикса на альфу
прошу через 3 минуты проверить, начало-ли учитывать эти новые услуги в статистике (подзакладке)

**Comment by nazarenkod** [comment]
@bvv4ik 
Я так понимаю мы говорим о этой статистике(отмечено зеленым)?
Не совсем понятно какие данные должны подтянутся?
![stat](https://cloud.githubusercontent.com/assets/13256486/9791397/89cc2648-57e3-11e5-97cb-469899f82e62.jpg)

**Comment by VadimGulich** [comment]
{"code":"SYSTEM_ERR","message":"java.lang.Double cannot be cast to java.lang.String"}

![image](https://cloud.githubusercontent.com/assets/12964120/10039190/3c065a42-61d8-11e5-807a-f9843deba182.png)

**Comment by bvv4ik** [comment]
перетерли случаянно фикс

только что пролито повторно, деплоится..

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/10073635/fff69408-62d2-11e5-838a-5523cdd4d95e.png)
на  тестовом не исправлено

**Comment by nazarenkod** [comment]
состояние на 25.09 13:40- так и не исправлено
![default](https://cloud.githubusercontent.com/assets/13256486/10098532/bc35c0f0-638a-11e5-839e-74aef23320a3.jpg)

**Comment by VadimGulich** [comment]
Задача уже на боевой и работает корректно
