### ISSUE TITLE
На главном портале добавить 3 новых валидатора + доработать 1 (в т.ч. использовать его отнаследованную копию) и немного совершенствовать общую систему валидации

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/i#685]
ВАЖНО: фактическое название элементов может быть любым, начинающимся, например, с "NumberBeetween". Типа: NumberBeetween_1, NumberBeetween_Floor_Subs, NumberBeetween_MaxBlocks и т.д. и все эти элементы должны работать паралельно, дополняя друг-друга (в элементах motion уже такой подход реализован)
А так-же должно так-же работать наследование маркеров (тоже, так-же как и в motion, и скорей всего уже работает унифицировано на весь markers, но стоит уточнить)

ЗАДАЧА: Добавить следующие валидаторы в элемент validate, объекта markers:

- [x] 1)
      NumberBeetween: { //Целочисленное между
        aField_ID: ['floors'],
        nMin: 1,
        nMax: 3
      }
Логика: разрешены только цифры, максимум 3
Сообщение: Проверьте правильность заполнения - число этажей состоит максимум из 3 цифр

- [x] 2)
      NumberFractionalBeetween: { //Дробное число между
        aField_ID: ['total_place', 'warming_place'],
        nMin: 0,
        nMax: 99999999
      }
Логика: разрешены только цифры, максимум 8
Сообщение: Проверьте правильность заполнения поля - площадь помещения может состоять максимум из 8 цифр

- [x] 3)
      Numbers_Accounts: { //разрешены цифры и дефисы, буквы любые запрещены
        aField_ID: ['house_number', 'gas_number', 'coolwater_number', 'hotwater_number', 'waterback_number', 'warming_number', 'electricity_number', 'garbage_number']
      }
Логика: разрешены цифры и дефисы, буквы любые запрещены
Сообщение: Проверьте правильность вводимого номера (буквы не разрешены к заполнению)

- [x] 4)
- [x] 4.1) Доработать "DateElapsed", добавив туда опциональный параметр:
        sFormat: 'YYYY-MM-DD' //формат даты
Если он задан то распознавать дату именно по жтому формату.
Параметры сделать опциональными (если не заданы считать нулем):
        nDays: 0,
        nMonths: 0,
        nYears: 0

- [x] 4.2) Наследоваться от "DateElapsed" (поведение именно такое-же, но просто с другими параметрами):
      DateElapsed_1: {
        aField_ID: ['date_of_birth'],
        sFormat: 'YYYY-MM-DD' //формат даты
        bFuture: false,
      }
Логика: не разрешено выбирать дату больше текущей
Сообщение: Выберите корректную дату - дата не может быть больше текущей

- [x] 5) Сделать опциональный параметр для всех элементов маркера валидации, где можно указывать то сообщение, которое должно выводиться в случае не валидности содержимого поля, по критериям текущего валидатора:
sMessage: "Значение не валидно!"

- [x] 6) Для всех валидаторов сделать умолчательный пропуск проверки (приравнивать это к валидности), если содержимого поля нет (т.е. там пусто)

ДЛЯ СПРАВКИ(старое описание, не принимать в рассчет!!!) : 
6) ИД: BuildFloorsMax3 - количество этажей в здании
Логика: разрешены только цифры, максимум 3
Сообщение: Проверьте правильность заполнения - число этажей состоит максимум из 3 цифр
Поля: floors

7) ИД: BuildAreaMetersMax8 - площадь помещения (квартиры, дома, склада и т.д.)
Логика: разрешены только цифры, максимум 8
Сообщение: Проверьте правильность заполнения поля - площадь помещения может состоять максимум из 8 цифр
Поля: total_place, warming_place

8) ИД: CustomerServiceAccounts - лицевые счета по коммуналке
Логика: разрешены цифры и дефисы, буквы любые запрещены
Сообщение: Проверьте правильность вводимого номера (буквы не разрешены к заполнению)
Поля: house_number, gas_number, coolwater_number, hotwater_number, waterback_number, warming_number, electricity_number, garbage_number

9) ИД: DateOfBirth - дата рождения гражданина
Логика: не разрешено выбирать дату больше текущей
Сообщение: Выберите корректную дату - дата не может быть больше текущей
Поля: date_of_birth

**Comment by rostag** [comment]
@bvv4ik, @dmitrijzabrudskij — можу взятися за це, якщо треба, по системі з #654 .

**Comment by dmitrijzabrudskij** [comment]
буде чудово! беріться

**Comment by bvv4ik** [comment]
@rostag я просто хотел немного оптимизировать эту задачу, чтоб, например, не пложить BuildAreaMetersMax8, BuildAreaMetersMax9, BuildAreaMetersMax10 и т.д.

а сделать один унифицированный...
вообщем я немного переделаю таску, и тогда отпишусь...

а пока, прошу акцент на таске с Places... а эту во вторую очередь, а то там из-за этого у нас куча накладных расходов, при любой доработке...

**Comment by bvv4ik** [comment]
Оптимизировал)

**Comment by rostag** [comment]
Якнайшвидше закінчую з рефакторингом places і беруся за це.

**Comment by rostag** [comment]
Почав працювати над цією задачею.

**Comment by rostag** [comment]
@bvv4ik - у визначенні валідаторів 1) та 2) є проблеми. Описую:
1) NumberBeetween: 
Проблема: значення параметра nMax має бути не 3, а 999 — аналогічно тому, як це задано у валідаторі 2): ```nMax: 99999999```

2) NumberFractionalBeetween: Проблема: не врахований знак дробу, тобто кома або крапка, яка відділяє цілу частину від дробної ("Логика: разрешены только цифры, максимум 8"). Насправді, маємо дозволити вводити цифри і знак коми. Вірно?

**Comment by bvv4ik** [comment]
1) в том-то и дело, что это может быть любое число... иногда лимит может быть 1-3, иногда 1-9999, а иногда 88888-99999

2) да, верно, конечно-же точки можно..

**Comment by rostag** [comment]
Зроблено, прошу перевіряти, інфа тут: https://github.com/e-government-ua/i/issues/867

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/10422704/c5220b12-70c6-11e5-92df-556b51f3f577.png)

Кому не пропускает в поле : Number Fractional Between:

**Comment by nazarenkod** [comment]
Так же добавлю:
поле "Number Fractional Between:" после точки пропускает неограниченное кол-во символов
и давайте в рамках этой задачи добавим код оператора 073

**Comment by rostag** [comment]
@VadimGulich - кому не пропускає, бо ми домовилися використовувати крапку, як таку що відповідає західному стандарту. Можливо, варто дозволити обидва символи?

@nazarenkod - так, можна увести багато знаків _після коми_, тому що насправді ми обмежуємо не кількість знаків, а максимальну величину числа. А вона залежить від кількості знаків _до коми_.  

Про код оператора 073 - згоден, треба і це виправити.
