### ISSUE TITLE
На бэке wf-base реализовать сервис getTasksByOrder

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#686]
- [ ] 1) создать сервис getTasksByOrder
- [ ] 2) Принимать параметры:
nID_Protected - ИД-строковой, содержащий в последней цифре контрольную сумму по алгоритму Луна
- [ ] 3) Отдавать массив вида:
[
123435
]
содержащий ИД активной юзертаски/тасок, в рамках процесса (помнить, что nID_Protected, без последней цифры(контрольной суммы) - это ИД таски-стартовой формы, по которой нужно найти ИД процесса и по нему уже активные юзертаски, с их ИД), 

ВАЖНО: по сути готовые участки кода есть в классе/методе: 

- org.wf.dp.dniprorada.dao.getHistoryEvent_ServiceByID_Protected(Long nID_Protected)
(проверка защищенного ИД, НО вот его наличие нужно искать не как в данном примере а уже не в центральной а региональной базе(т.к. это ИД стартовой формы)

- а тут можно найти участок(или выйти на него) получения активной юзертаски через ИД стартовой формы (id-процесса > все содержащиеся активные id-юзер-таски):
org.activiti.rest.interceptor.RequestProcessingInterceptor (метод saveHistory)

- [ ] 4) Если 
- при проверке nID_Protected - контрольная сумма не совпадет - выдавать ошибку "CRC-error"
- при поиске, на основании nID_Protected - запись не будет найдена - выдавать ошибку "Record not found"
- [ ] 5) Дополнить документацию АПИ на Вики

**Comment by ASkosyr** [comment]
Дата поставки - 26 августа

**Comment by brunneng** [comment]
Пример урла:
http://localhost:8080/wf-region/service/rest/tasks/getTasksByOrder?nID_Protected=12342

**Comment by brunneng** [comment]
Примечание: текст ошибки в случае неверного CRC был сохранен таким же как был раньше - "CRC Error"

**Comment by RoOmel** [comment]
1.5  Документация АПИ на Вики не дополнена
https://github.com/e-government-ua/i/blob/test/docs/specification.md#0_contents
1.4 При запросе с заведемо неверным параметром nID_Protected
http://test.igov.org.ua/wf-region/service/rest/tasks/getTasksByOrder?nID_Protected=1234562
ошибка не ототбражается.
1.1 - 1.3 При запросе с корректным параметром nID_Protected
http://test.igov.org.ua/wf-region/service/rest/tasks/getTasksByOrder?nID_Protected=1234561
в ответе отображается следующее
![wf-base gettasksbyorder 686](https://cloud.githubusercontent.com/assets/12996514/9430360/d4872814-49fa-11e5-992f-67158e5d2aa9.jpg)
массив вида: [ 123435 ] содержащий ИД активной юзертаски/тасок я в ответе не увидел

**Comment by brunneng** [comment]
Ошибки должны быть пофикшены и документация rest api дополнена. Проверьте пожалуйста.

**Comment by RoOmel** [comment]
1. Докум-ция дополнена.
2. Тестирование.
2.1 Добавил объект события по услуге:
Запрос:
http://test.igov.org.ua/wf-central/service/services/addHistoryEvent_Service?nID_Task=2&sStatus=new&nID_Subject=123451&sID_Status=&nID_Proccess=2&sProcessInstanceName=
Ответ:
{
    "nID_Task": 2,
    "nID_Subject": 123451,
    "sStatus": "",
    "sID_Status": "",
    "sDate": "2015-08-25 08:44:13.573",
    "nID_Protected": 22,
    "nID": 22148
}

2.2 Возвращаем спискок ID пользовательских тасок по номеру заявки
Запрос:
https://test.region.igov.org.ua/wf-region/service/rest/tasks/getTasksByOrder?nID_Protected=22
Ответ:
{
    "code": "BUSINESS_ERR",
    "message": "CRC Error"
}

Согласно описанию должен быть ответ сервера 200 ОК.
Возможно некорректно работает сервис пункта 2.1

**Comment by bvv4ik** [comment]
я не понял методику проверки и как она связана с таской...

**Comment by bvv4ik** [comment]
нужно просто оформить заявку, запомнить ее номер и в дашборде найти

**Comment by brunneng** [comment]
На запрос
https://test.region.igov.org.ua/wf-region/service/rest/tasks/getTasksByOrder?nID_Protected=22
ошибка:
{"code":"BUSINESS_ERR","message":"Record not found"}

**Comment by RoOmel** [comment]
1. По сценарию от bvv4ik "нужно просто оформить заявку, запомнить ее номер и в дашборде найти":
1.1 Создана заявка в части FrontEnd "Ваше звернення №28100011 успішно зареєстровано. Результати будуть спрямовані на Ваш roman.omeljanenko@privatbank.ua"
1.2 В дашборде по номеру 28100011 с помощью строки поиска эта заявка найдена в "Необроблені".

Если для тестирования этой задачи не нужны запросы REST-клиента - зачем тогда ставить маркер BackEnd-REST-Activity и давать описание запросов в доке https://github.com/e-government-ua/i/blob/test/docs/specification.md#32_getTasksByOrder

2. При подстановке номера 28100011 в запрос
https://test.region.igov.org.ua/wf-region/service/rest/tasks/getTasksByOrder?nID_Protected=28100011
получен ответ сервера
 [
    "2810055"
]
Ожидаемый результат мне неизвестен

**Comment by bvv4ik** [comment]
просто эти две задачи шли в паре... пока небыла готова фронтовая часть - эту нужно было тестировать как-то иначе...
а коль фронтовая есть - тестить, стало быть, проще стало)
