### ISSUE TITLE
На бэке (wf-base) реализовать сервис получения активных тикетов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#688]
- [x] 1) Создать сервис getFlowSlotTickets (в том-же контроллере где идет работа со слотами)

- [x] 2) Принимать параметры 
sLogin - строка логина пользователя
bEmployeeUnassigned - булевый, true - не ассигнутые госслужащим //опциональный, умолчательно false
sDate - строка с датой //опциональный

- [x] 3) Выдавать массив вида (сущность FlowSlotTicket):
[
{
"nID":1
,"nID_FlowSlot":2
,"nID_Subject":2
,"nID_Task_Activiti":NULL
,"sDateStart":"2015-07-20T15:00:00"
,"sDateFinish":"2015-07-20T15:15:00"
,"sDateEdit":"2015-07-20T15:00:00"
,"sUserTaskName":"Заявка подана"
,"sNameBP":"Регистрация б/у авто в МРЕО"
,"sTaskDate":"2015-07-20T15:00:00"
}
]

- [x] 4) Выборку производить по следующей логике:
- [x] 4.1) Выбирать все таски активити, которые отождествлены с логином sLogin
- [x] 4.2) Если bEmployeeUnassigned=true, то с учетом флага unassigned=true
- [x] 4.3) Далее выбирать только те из них, чьи ИД шники есть в поле "nID_Task_Activiti", сущности "FlowSlotTicket", и джоинить эти записи.
- [x] 4.4) Дополнить объединенную сущность полями (из объекта таски)
- "sUserTaskName" - Название юзертаски //например: "Заявка подана"
- "sNameBP" - Название БП //например: "Регистрация б/у авто в МРЕО"
- "sTaskDate" - Дата подачи заявки //например: "2015-07-20T15:00:00"
- [x] 4.5) Сортировать список в порядке возрастания "sDateStart" объедененной сущности (в т.ч. с данными "FlowSlotTicket")
- [x] 4.6) Если задан параметр sDate, то выбирать записи/таски только в рамках этой даты

- [x] 5) Актуализировать доку по АПИ на нашей Вики

**Comment by ASkosyr** [comment]
Описание метода добавил

https://github.com/e-government-ua/i/blob/test/docs/specification.md#31_getFlowSlotTickets

**Comment by ASkosyr** [comment]
Задача реализована
Документация добавлена

https://github.com/e-government-ua/i/blob/test/docs/specification.md#31_getFlowSlotTickets

**Comment by VadimGulich** [comment]
Проверено на смежной задаче + согласно описанию
