### ISSUE TITLE
Додати на портал готові послуги в регіонах (електронна реєстрація до дитсадка)

### ISSUE THREAD

**Issue by 40rn05lyv** [e-government-ua/i#689]
Знайшов у неті різні сайти щодо реєстрації дітей у дитсадки (послуга https://igov.org.ua/service/700/general).
* https://reg.isuo.org/preschools - ніби загальноукраїнський, але кількість підключених ДНЗ варіюється (наприклад, по Києву лише 1 ДНЗ, тому що сам Київ має свій власний портал, те саме у Львівській області);
* http://kingad-reg.ftl.kherson.ua/ - Херсон
* http://www.vmr.gov.ua/TransparentCity/dnz/Lists/Content/Default.aspx - Вінниця
* http://www.dnz.kiev.ua/ - Київ
* http://dr.lvivedu.com/uk/site/reestratsiya-ditini.html - Дрогобич
* http://dnz.te.ua/ - Тернопіль
* http://zakosvita.com.ua/uk/site/elektronna-reestratsiya-v.html - Закарпатська область
* http://sadik.kh.ua/ - Харківська область (ледве розібрався що до чого)

Коротше, сайти паршиві, кожна міська рада робила свій велосипед. https://reg.isuo.org/preschools наче мав би їх всіх об’єднувати, але хз як це все працює. Та й сам сайт не в домені *.gov.ua

**Comment by bvv4ik** [comment]
@dmitrijzabrudskij Дима, глянь плиз... если что - добавь тогда плиз их в каталог

**Comment by bvv4ik** [comment]
@dmitrijzabrudskij Дима, глянь плиз... если что - добавь тогда плиз их в каталог

**Comment by kurbpa** [comment]
@40rn05lyv  Сайты настолько  "мягко говоря не очень", что рука не поднимается их к нам добавлять пока

**Comment by bvv4ik** [comment]
кстати, такие таски как эта(про новые услуги и БП) теперь можно создавать в отдельном репозитории:
https://github.com/e-government-ua/iBP/issues

**Comment by bvv4ik** [comment]
а тут не стоит...
