### ISSUE TITLE
реализовать REST-сервис на бэке, который валидирует юзера по логину и паролю и создает сессию

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#69]
1) нужно реализовать REST-сервис на нашем бэке с активити, который позволит валидировать юзера по логину и паролю
на жаве юзера получить так:
User user = ProcessEngines.getDefaultProcessEngine()
    .getIdentityService().createUserQuery().userId(key).list().get(o);

потом ,доставал, то, что надо:
getEmail()
getFirstName()
getId()
getLastName()
getPassword()

по результату проверки - создавать сессию на сервере и отдавать в ответе, в хедере, ее ИД-шник

**Comment by bvv4ik** [comment]
ProcessEngines.getDefaultProcessEngine()
.getIdentityService().checkPassword(userId, password)
можно использовать и этот

**Comment by admiral-diver** [comment]
Задачу закрываю: https://github.com/e-government-ua/i/blob/test/docs/specification.md
