### ISSUE TITLE
На бэке централа (wf-central) добавить новый тип обработчика Квитанций 

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#690]
- [x] 1. в сущность "DocumentOperator_SubjectOrgan" (файл: DocumentOperator_SubjectOrgan.csv) добавить новую запись с новым обработчиком (handler-ом)

nID;sName;nID_SubjectOrgan;sHandlerClass
1;iGov;2;org.wf.dp.dniprorada.model.document.DocumentAccessHandler_IGov
2;PB;2;org.wf.dp.dniprorada.model.document.DocumentAccessHandler_PB

- [x] 2. Скопировать образец класса-хєндлера "DocumentAccessHandler_IGov" в "DocumentAccessHandler_PB"
и реализовать в нем, получение(проверку) наличия квитанции по следующим АПИ и схеме:

- [x] 2.1) Генерировать  через сервис ГЕНЕРАЦИИ СИД-а (доступный из внешнего мира кому угодно, (техлогин "igov" c паролем "igov-sess")):
https://auth-id.igov.org.ua/ChameleonServer/sessions/open

- [x] 2.2) Сгенерированный СИД использовать для при вызове сервиса ПОЛУЧЕНИЯ ГОТОВЫХ КВИТАНЦИЙ (доступный из внешнего мира кому угодно):
https://auth-id.igov.org.ua/PDRAPI/kvitanc-for-igov?keyID=P24AP24A385840118116309&callbackUrl=http://localhost:8084/PDRAPI/upload&lang=rus
где:
- вместо "P24AP24A385840118116309" - передавать ИД документа (как и в хендлере-образце "DocumentAccessHandler_IGov")
- вместо "http://localhost:8084/PDRAPI/upload&lang=rus"  передавать адрес своего ответногосервиса(ниже в проперти)

В хеадер передавать:
Header Authorization: Basic c2lkOjE1MDgwN2NzZTEzNDF3NDRjYjVy
где:
- вместо "c2lkOjE1MDgwN2NzZTEzNDF3NDRjYjVy" - передавать заэнкоденный(Base64) стринг:
"sid:сгенерированный на этапе п.2.1 СИД"
Например "sid:h83oi3483r9h80deh20", заэнкоденный получится что-то типа "DF3NDRjYjVyc2lkOjE1MDgwN2NzZTEzN"

- [x] 3. Вынести в проперти AS.propertyes (параметры):
sURL_DocumentKvitancii=https://auth-id.igov.org.ua/PDRAPI/kvitanc-for-igov
sURL_GenerationSID=https://auth-id.igov.org.ua/ChameleonServer/sessions/open
sURL_DocumentKvitanciiCallback=http://localhost:8084/PDRAPI/upload&lang=rus
(сообщить @bvv4ik, когда готово, чтоб можно было перенести проперти на общий тестовый сервер, и работало не только локально)

- [x] 4. При вызове нового обработчика - отрабатывать его только если тип услуги (передаваемый ИД-шник сущности DocumentType) = 0;Квитанція про сплату
Иначе выдавать ошибку "DocumentType not supported!"

**Comment by taaraora** [comment]
Due date: 22-23.08.15.

**Comment by bvv4ik** [comment]
По идее последний пункт остался?

**Comment by bvv4ik** [comment]
тестировать зайдя в поиск Документов на портале и вібрав банк, тип и № квитанции - запросить (пример номера в таске есть)

**Comment by RoOmel** [comment]
@bvv4ik "(пример номера в таске есть)"
Не увидел ни одного примера.

**Comment by bvv4ik** [comment]
"вместо "P24AP24A385840118116309" - передавать ИД документа"

вот "P24AP24A385840118116309" - это и есть номер

**Comment by bvv4ik** [comment]
вот живой номер квитанции:
P24AP24A350826699832653

**Comment by VadimGulich** [comment]
Согласно описанию не работает : 
![image](https://cloud.githubusercontent.com/assets/12964120/10073737/cc688a96-62d3-11e5-9e7d-89bfad98f417.png)
и по новому реф. тож не работает

**Comment by nazarenkod** [comment]
состояние на 25.09 13:40- так и не исправлено
![default](https://cloud.githubusercontent.com/assets/13256486/10098520/ad2c697e-638a-11e5-860b-43989ef15e5e.jpg)

**Comment by bvv4ik** [comment]
по тестовым дубликатам, добавил пару платежей '913229749', '910331572'
можно попробовать на них... 

но на боевом можно в П24 заказать справку о доходах и ее реф вбить, выбрать "справку для визовых центров"... вроде там работает

**Comment by VadimGulich** [comment]
Квитанция загружается
