### ISSUE TITLE
am i authorized? индикатор авторизации

### ISSUE THREAD

**Issue by irungentootoo** [e-government-ua/i#691]
после авторизации через банк ид "главная" не поменяла своего вида, нужна какаято иконка "меня" мол авторизирован. как например в "приват банке , с кнопочкой ВЫХОД" 
- так же касаеться безопасности.

**Comment by bvv4ik** [comment]
личный кабинет пока не реализован(в планах есть)... когда реализуют, тогда будет признак этого
