### ISSUE TITLE
S3 - Сертифікат електронно-цифрового підпису - отображает логотип BankID.

### ISSUE THREAD

**Issue by smit-pb** [e-government-ua/i#693]
На главном портале, выбираем любую услугу которая предусматривает авторизацию через BankID и через Сертификат электронно-цифровой подписи.
Нажимаем на кнопку "Сертификат электронно-цифровой подписи" - загружается страница "https://bankid.privatbank.ua" и отображается форма электронно-цифровой подписи - но отображается Логотип BankID.

![image](https://cloud.githubusercontent.com/assets/12965717/9377318/5afc9fc4-4720-11e5-9dfb-fa2ca8c10e22.png)

![image](https://cloud.githubusercontent.com/assets/12965717/9377325/6c1b62e0-4720-11e5-81da-86b97e05b724.png)

**Comment by bvv4ik** [comment]
iGov - это iGov (у него свое видение логотипов)
BankID - это BankID (у него свое)

**Comment by smit-pb** [comment]
А кто спорит ? Просто логотип отображается на странице  - ЭЦП . Что пользователей вводит в "непонимание" - почему тут логотип BankID если человек решил выбрать ЭЦП ?
Или хотите сказать BankID и ЭЦП это одна организация ? и они используют одно лого ?

**Comment by bvv4ik** [comment]
"Или хотите сказать BankID и ЭЦП это одна организация ?"
именно)
