### ISSUE TITLE
Не відпрацьовує посилання "Змінити"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#695]
Баг знайшов на продакті. Не відпрацьовує посилання "Змінити"
І судячи з логу - на click action не має реакції взагалі. Значить, проблема можливо на фронті :)

І документи не підвантажуються))

![image](https://cloud.githubusercontent.com/assets/4208821/9424788/f7e3caaa-4901-11e5-8b89-30933be44966.png)

![image](https://cloud.githubusercontent.com/assets/4208821/9424790/0621f880-4902-11e5-9bbc-9ceed372a496.png)

**Comment by VadimGulich** [comment]
1) https://test.igov.org.ua на тестовом не исправлено

2) Второй скрин с пункта  "Документы" , там кнопки "Змінити "  нет , и загружается корректно

**Comment by bvv4ik** [comment]
не совсем понял, прошу перепроверить... 
я вроде сам проверял, как будто-бы норм все

**Comment by VadimGulich** [comment]
1) По ошибке с "Змінити" мувик: https://drive.google.com/file/d/0Bw7BSYSLbe2MZzVIVTBWQ1djLVk/view?usp=sharing

2) По загрузке документов исправлено

**Comment by bvv4ik** [comment]
1. спасибо за мувик) понял теперь о чем речь...
на самом деле оно и не должно редактироваться... по хорошему єто уже нужно скріть...
но то такое, для бэклога. именно ту ошибку, ради которой была эта таска - исправили, вроде как.

П.С.: а ты что, каждый раз ждеш реальной СМС-ки, для авторизации на тестовом?
это-ж долго...
есть-же бэкдуровая учетка (на вики в доке)
+380102030405
value
123456

**Comment by VadimGulich** [comment]
>>есть-же бэкдуровая учетка (на вики в доке)

да , я знаю , пользуюсь для тестирования задач и попытки  написания автотестов))

просто такие баги воспроизвожу на своих боевых данных) 

Задачу закрываю
