### ISSUE TITLE
На главном портале, при выборе в профиле услуги города, в которой услуги нет - не отображает блок для фидбэка

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#696]
почему-то при выборе другого города ничего не показывается
[19.08.2015 15:23:11] Dmytro Dubilet: а важно ж емейлы собирать...

![image](https://cloud.githubusercontent.com/assets/4208821/9424816/03d6a1b0-4903-11e5-9015-11bfe54655ae.png)

**Comment by VadimGulich** [comment]
Исправлено, протестировано на тестовом
