### ISSUE TITLE
На главном портале, в форме услуги, при выборе времени в Электронной Очереди - выволить сообщение о ганятости, если возвращается ошибка об этом.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#697]
прикрутить диалог(хоть даже alert обычный):
когда выбираеш время электронной очереди, и возникает ошибка - этого не видно, и визуально как будто-бы ничего не произошло...
а уже после сабмита вываливает ошибку, причем другую (типа обьект поломанный)

Можно просто выводить алерт с текстом "Ці дата та час вже зайняті. оберіть інші, будь ласка"
(желательно после этого произваодить перезагрузку списка с комбобоксе, но пока хотя-бы просто чтоб он оставался не выбранным)

П.С.:
с бека явы возвращается текст ошибка, с текстом, и по ним можно выводить разные сообщения:
"FlowSlotTicket with nID_FlowSlot=123 is bBusyStatic by getnID_Task_Activiti()=4556"
-"Ці дата та час вже зайняті. оберіть інші, будь ласка"

"FlowSlotTicket with nID_FlowSlot=123 is bBusyTemp by getnID_Task_Activiti()=4556"
-"Ці дата та час вже зарезервовані. оберіть інші, будь ласка"

При другой ошибке:
-"Неможливо вибрати час. Спробуйте обрати інші або пізніше, будь ласка"

**Comment by bvv4ik** [comment]
тестить можно на: https://test.igov.org.ua/service/176/general
- зайти в одном обозревателе в услугу
- потом в другом, в эту-же услугу
- потом в первом выбрать время
- и после этого во втором - это-же время (должно вывалить ошибку)

**Comment by VadimGulich** [comment]
Основа задачи реализована, работает корректно : 

Есть пару замечаний:
1) текст ошибки не соответствует описанию в задаче
2) В ответе отображается  stack trace, по идее его б нужно скрывать
![image](https://cloud.githubusercontent.com/assets/12964120/9461031/b192e37e-4b13-11e5-9d45-7e6d75ef4612.png)

**Comment by bvv4ik** [comment]
как компромисное решение было одобрено
все гуд

**Comment by VadimGulich** [comment]
тогда закрываем ))
