### ISSUE TITLE
На бэке (wf-base) реализовать отсылку уведомления на почту, при создании новой услуги, и в теле отправлять ИД заявки, с добавленной последней цифрой контрольной суммы по алгоритму Луна

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#698]
- Реализовать это прямо в классе в классе org.activiti.rest.interceptor.RequestProcessingInterceptor
в методе:
saveHistory(HttpServletRequest request, HttpServletResponse response, boolean saveHistory) throws IOException {
по событию boolean setTask

- Отсылать почту по образу и подобию того, как это реализовано в методе:
setDocumentLink(Long nID_Document, String sFIO, String sTarget, String sTelephone, Long nMS, String sMail) throws Exception{
Класса: DocumentAccessDaoImpl
Пэкэджа: org.wf.dp.dniprorada.dao

- Заголовок:
Вы подали заявку №23543253 на услугу, через портал igov.org.ua

- Текст письма:
Вы подали заявку №23543253 на услугу, через портал igov.org.ua
(Вы всегда сможете посмотреть ее текущий статус на портале в разделе "Статусы")

При поступлении Вашей заявки в систему госоргана - Вам будет дополнительно направлено персональное письмо - уведомление.

- Электронный адрес взять из получаемого объекта в реквесте (в логах можно глянуть пример объекта)
Вот пример залогированного пришедшего тела запроса, из которого можно взять электронку({"id":"email","value":"al.dubilet@gmail.com"}):
(пока затачиваемся на такой id)

2015-08-23_21:48:33.424 | INFO | org.activiti.rest.interceptor.RequestProcessingInterceptor- sRequestBody: {"processDefinitionId":"kiev_dms_1:49:2732672","businessKey":"key","properties":[{
"id":"bankIdlastName","value":"ДУБІЛЕТ"},{"id":"bankIdfirstName","value":"ДМИТРО"},{"id":"bankIdmiddleName","value":"ОЛЕКСАНДРОВИЧ"},{"id":"Dateofbirth","value":"1"},{"id":"Areabirth","valu
e":"2"},{"id":"bankIdPassport","value":"АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002"},{"id":"bankId_scan_passport","value":null},{"id":"Nationality","value
":"3"},{"id":"kids","value":"no"},{"id":"text1","value":"Будь ласка, вкажіть дані Вашої дитини, якщо її вік перевищую 14 років"},{"id":"ChildName1","value":"456"},{"id":"kidsCitizenship","v
alue":"7"},{"id":"oldAddress","value":"8"},{"id":"newAddressLabel","value":"Заповніть деталі вашої нової адреси"},{"id":"RegistrationAddress","value":"9"},{"id":"newStreet","value":"10"},{"
id":"newHouse","value":"11"},{"id":"newCorp","value":"12"},{"id":"newApartment","value":"13"},{"id":"militaryDoc","value":null},{"id":"bringDoc","value":"other"},{"id":"bringDocOther","valu
e":"14"},{"id":"phone","value":"+380 67 503 8800"},{"id":"email","value":"al.dubilet@gmail.com"},{"id":"visitDay","value":"26/08/2015"},{"id":"visitTime","value":"15"},{"id":"warning","valu
e":"Подаючи звернення, Ви підтверджуєте достовірність усіх зазначених у зверненні даних і надаєте свою згоду на обробку Ваших персональних даних"},{"id":"sBody_1","value":null},{"id":"sBody
_2","value":null},{"id":"sBody_3","value":null},{"id":"sBody_4","value":null},{"id":"sBody_5","value":null},{"id":"sBody_6","value":null},{"id":"sBody_7","value":null}],"nID_Subject":20045}
2015-08-23_21:48:33.424 | INFO | org.activiti.rest.interceptor.RequestProcessingInterceptor- call service HistoryEvent_Service!!!!!!!!!!!
2015-08-23_21:48:33.460 | INFO | org.activiti.rest.interceptor.RequestProcessingInterceptor- https://test.igov.org.ua/wf-central/service/services/addHistoryEvent_Service: {sProcessInstanceN
ame=Київська ДМС - Реєстрація місця проживання/перебування особи!, nID_Proccess=2732706, nID_Subject=20045, sID_Status=Заявка подана}

**Comment by brunneng** [comment]
Просьба кроме непосредственной проверки отправки email-а проверить весь жизненный цикл заявки - создание/изменение/закрытие

**Comment by bvv4ik** [comment]
и как это отражается в Мой журнал + в закладке Статус

**Comment by VadimGulich** [comment]
https://github.com/e-government-ua/i/issues/398  меил должен быть как в ранее реализованой задаче 
![image](https://cloud.githubusercontent.com/assets/12964120/9736163/58b20718-5648-11e5-83c2-14bd208a0027.png)

**Comment by bvv4ik** [comment]
уже поправлено

**Comment by VadimGulich** [comment]
Не загружается меню Мои документы
{"code":"SYSTEM_ERR","message":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"initialUpload\""}

постоянно крутится прелоадер

**Comment by VadimGulich** [comment]
исправлено
