### ISSUE TITLE
Доработать систему вспомогательной технической авторизации.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#699]
Доработать класс:
\i\wf-base\src\main\java\org\activity\rest\security\AccessKeyAuthFilter.java
и связанные с ним классы:
\i\wf-base\src\main\java\org\activity\rest\security\*.java

Чтоб по мимо пары параметров(для авторизации кроме фиксированного логина/пароля энкоденного в хеадере):
        sAccessKey (ключ, по которому подтягивается сверяемый контент)
        nID_Subject (сам контент, с которым происходит сверка)

Поддерживалась комбинация:
        sAccessKey (ключ, по которому подтягивается сверяемый контент)
        sAccessContract=Request (параметр, говорящий, что сверяемым контентом является сама строка запроса)

При которой вместо сверки совпадения контента nID_Subject с контентом, полученным по ключу(sAccessKey), в качестве контента будет выступать строка самого текущего запроса. 
НО при этом, из строки реквеста важно будет вырезать сам параметр "&sAccessKey=(тот код, что пришел)"

Например:
"/wf-region/service/setPaymentStatus_TaskActiviti?sID_Order=TaskActiviti_105123&sID_PaymentSystem=Liqpay&sData=&sAccessContract=Request"

(хотя по логике там еще должен был быть параметр &sAccessKey=5d1184c7-2d84-4931-a8f5-1032b50ed699)

ВАЖНО:
- Если по ключу sAccessKey вытягивается контент, но он не совпадет со "сверяемым" выдавать эксепшин с сообщением:
"Contract data by sAccessKey is not equal !!! (sAccessContract=Request, sAccessKey=5d1184c7-2d84-4931-a8f5-1032b50ed699)"
(а в логах выводить один и другой контент, для сравнения, чтоб можно было дебажить)
- Если по ключу sAccessKey вообще не найден контента, выдавать эксепшин с сообщением:
"Content not found by sAccessKey !!! (sAccessContract=Request, sAccessKey=5d1184c7-2d84-4931-a8f5-1032b50ed699)"

П.С.: Это логическое продолжение развития предыдущей таски: https://github.com/e-government-ua/i/issues/502

**Comment by VadimGulich** [comment]
Как можно протестировать данную задачу?

**Comment by bvv4ik** [comment]
сейчас готовятся правки для тестового БП, при использовании которого и можно будет протестировать... я сообщу какой и когда

**Comment by bvv4ik** [comment]
можно в тестовом БП по ликпею провести оплату и убедиться что в юзертаску пришел ИД транзакции

**Comment by VadimGulich** [comment]
Задача будет протестирована в рамках этой задачи  https://github.com/e-government-ua/i/issues/722 (после восстановления работы БП по ликпею) 

эту закрываю , чтоб не дублировать  проверки )
