### ISSUE TITLE
покопировать папку /i/wf-dniprorada из репы i/ в отдельно созданные репы

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#70]
3) покопировать папку /i/wf-dniprorada из репы i/ в отдельно созданные репы,
/_Dnipropetrovsk_MVK/wf
/_Kaluga_RDA/wf
/_Mykolaiv_OGA/wf
/_Smila_RDA/wf
/_Kiev_MVK/wf
/_Kherson_OGA/wf
/_IvanoFrankivsk_MVK/wf

**Comment by ValerijMakarenko** [comment]
done
