### ISSUE TITLE
На главном портале при предоставлении доступа к документу код для копирования не ототбражается

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/i#702]
В Firefox ver. 40.0 код для копирования не ототбражается
![bug_igov_11](https://cloud.githubusercontent.com/assets/12996514/9486547/51426918-4bd1-11e5-84be-0548f6131cb8.jpg)

**Comment by bvv4ik** [comment]
Поправлено

**Comment by VadimGulich** [comment]
Исправлено при регрессе
