### ISSUE TITLE
На главном портале починить заход в форму услуги, когда она находится только в регионе

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#703]
https://test.igov.org.ua/service/161/general/region
зайдя в услугу в Херсонской области, уже сразу после авторизации возвращает обратно на выбор способа авторизации (вмест оформы услуги)...

П.С.: проблемма именно в том, что услуга находится в области

**Comment by bvv4ik** [comment]
Проверить можно:
найдя услугу "Запит на отримання публічної інформації (облдержадміністрація)"
или прямо на: https://test.igov.org.ua/service/161/general
Вібрать область и авторизоваться...

**Comment by VadimGulich** [comment]
Сама ошибка описана в задаче исправлено , но появился ряд новых ошибок:
1) Не подсвечивается зелен. цветом активная область
2) Пропала кнопка изменить в правом углу 
смотреть мувик:
https://drive.google.com/file/d/0Bw7BSYSLbe2MNHlCbFJXeXVGOE0/view?usp=sharing

**Comment by VadimGulich** [comment]
Эти баги есть в отчете по регрессу , закрываю эту задачку
