### ISSUE TITLE
Создать на бэке (wf-base) класс системтаски Активити, которая будет освобождать тикеты от электронной очереди

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#705]
- Назвать класс ReleaseTicketsOfQueue
- За образец системтаски можно взять MailTaskWithAttachments
- Обработчик полей, в которых хранятся JSON-объекты ссылок на Электронную очередь находятся в методе scanExecutionOnQueueTickets
- Тип поля, в котором содержится объект - queueData (клвсс QueueDataFormType), пример перебора таких полей в методе getListField_QueueDataFormType
- Пример получения Тикета и обнуление его привязки:
FlowSlotTicket oFlowSlotTicket = oFlowSlotTicketDao.findById(nID_FlowSlotTicket).orNull();
                            oFlowSlotTicket.setnID_Task_Activiti(nID_Task_Activiti);
                            oFlowSlotTicketDao.saveOrUpdate(oFlowSlotTicket);

**Comment by ASkosyr** [comment]
Пример бизнес процесса, использующего данную таску

wf-region\src\main\resources\bpmn\autodeploy\_test_queue_cancel.bpmn

**Comment by RoOmel** [comment]
Ну и как проверить эту задачу?
Может ссылку на доку или пример какой-нибудь кто-нибудь напишет?

**Comment by bvv4ik** [comment]
пройти до конца _test_queue_cancel

подать заявку (включая постановку в очередь)
и потом взятьв работу
а в конце отменить при отработке
и слот должен освобоиться

**Comment by VadimGulich** [comment]
пройти до конца _test_queue_cancel    - нет такого БП  =( 

![image](https://cloud.githubusercontent.com/assets/12964120/9761166/b401d952-5703-11e5-8a94-e3c61df3fecd.png)

**Comment by bvv4ik** [comment]
уже есть

**Comment by VadimGulich** [comment]
Нужно создать тикеты для проверки задачи
![image](https://cloud.githubusercontent.com/assets/12964120/9986414/f5667c78-6044-11e5-921e-5515c7af9692.png)

**Comment by nazarenkod** [comment]
состояние на 25.09 15:50
Ошибка при сабмите
![systentask](https://cloud.githubusercontent.com/assets/13256486/10100822/f5b10eb8-639c-11e5-9641-7a177917dd68.jpg)
скорее всего связано с правками в БП таски 720

**Comment by nazarenkod** [comment]
Работает согласно описанию.Слот освобождается
