### ISSUE TITLE
На главном портале создать новый элемент обьекта markers - attribute и его подэлемент bReadable

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#706]
- [ ] 1) дополнить унифицированный объект "markers" - блоком "attribute"(по мимо validate и motion), в котором описывать вспомогательніе атрибуті полей (поискать в коде слово "markers", и дополнить тот объект + дописать логику поведения):

  var markers = {
    validate: {
      PhoneUA: {
        aField_ID: ['privatePhone', 'workPhone', 'phone', 'tel']
      },
      ....(валидаторов уже много, перечислять их все не буду)...
      Mail: {
        aField_ID: ['privateMail', 'email']
      }
    },
    attribute: {
      bWritableByClient_1: { //Показывает поля при не пустом указанном поле (иначе скрывает)
        aField_ID: ['sPhone_User1', 'sMail_User1'] //'text3', 'phone'
        , sValue: 'true'
      }

  };

- [ ] 2) Добавить новый элемент "bWritableByClient_*", с такой логикой работы:

- [ ] 2.1) Для всех полей с ИД, которые указаны в массиве aField_ID:
- [ ] 2.1.1)  если sValue = 'true' - нужно все элементы делать обязательно редактируемыми (т.е. даже если это поле, автоматически импортирующееся из БанкИД, и отображающее данные в виде нередактируемого лэйбла - оно должно в таком случае отображаться в виде редактируемого инпут-а
- [ ] 2.1.2)  если sValue = 'false' - нужно все элементы делать обязательно НЕ редактируемыми  (полностью обратно п.п. 2.1.1)

- [ ] 2.2) Такая логика поведения должна быть на всех элементах, которые начинаются с "ShowFieldsOnNotEmpty_", т.е. "bWritableByClient_1", "bWritableByClient_2"... При том в каждом элементе могут быть свой набор полей, и соответственно проверка тоже своя.

П.С.: эта задача, подобна предыдущей. и ее логическое развитие: https://github.com/e-government-ua/i/issues/661

**Comment by serdyuk-alex** [comment]
Для проверки работы функциональности в конфигурациооном объекте был добавлен атрибут bankIdlastName, bValue = true. Т.е. он был сделан по умолчанию редактируемым на всех сервисах которые его используют, это и требуется проверить.

**Comment by VadimGulich** [comment]
Проверено
