### ISSUE TITLE
На всех бэках избавиться от ручного открвтия/закрытия сессии при работе с DAO

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#707]
Пример, класс DocumentAccessDaoImpl

типа:
Session oSession = getSession();

и:
	if(oSession.isConnected()){
				oSession.close();
			}

перевести все на утвержденный стандарт проекта:
https://github.com/e-government-ua/i/wiki/%D0%9D%D0%B0%D1%88%D0%B8-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D1%8B#3-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-hibernate-entity-and-dao-%D0%B8-%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D1%8B%D1%85-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D0%B5%D0%B9up

**Comment by Invizible** [comment]
Возможно некоторые дао заэксклужены из теста: https://github.com/e-government-ua/i/blob/master/wf-central/src/test/resources/test.properties
Можно по одному удалять и пробовать прогонять тест https://github.com/e-government-ua/i/blob/master/wf-central/src/test/java/org/wf/dp/dniprorada/dao/EntityDaoQueriesTest.java, но есть такие методы к-рые требуют валидных параметров, а не рандомных, поэтому все тупо убрать нельзя.

**Comment by Invizible** [comment]
Я могу взяться за эту таску, так как это логичное продолжение таски #497. Я таких мест видел не много

**Comment by Invizible** [comment]
К счастью такой класс был 1 :)

**Comment by bvv4ik** [comment]
так можно считать эту таску сделанной?

**Comment by Invizible** [comment]
да

**Comment by bvv4ik** [comment]
ляпота)
закрываю...

думаю, может, коль "такая пьянка" - отискать оставшиеся Сущности, которые работают у нас вне этого сложившегося стандарта и - составить их список для планомерного их перевода под него?
