### ISSUE TITLE
На главном портале для Киева убрать пункты меню

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#709]
8. В версию возможно В Работе… Убрать разделы "Документи", "Мій журнал", "Про портал"

https://docs.google.com/document/d/1fUJlMptp0npeXNShMwZedfcqnhfz6mhyDcw7qoxtZqU/edit#

**Comment by bvv4ik** [comment]
тестим на https://test.kiev.igov.org.ua

**Comment by smit-pb** [comment]
Реализовано на тестовом.
