### ISSUE TITLE
Перенести в Вики доку "Локальная установка ActivitiDesigner, для редактирования бизнес-процессов"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#71]
Перенести доку в Вики:
https://docs.google.com/a/privatbank.ua/document/d/1UpFGmrZ5PbcnJJVXFQJohkkf3dJq9h3lffD8IR4gQXg/edit#heading=h.641nf3o8hz7u

Название страницы такое:
Локальная установка ActivitiDesigner, для редактирования бизнес-процессов

**Comment by dr1v3** [comment]
[Готово](https://github.com/e-government-ua/i/wiki/%D0%9B%D0%BE%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-ActivitiDesigner,-%D0%B4%D0%BB%D1%8F-%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B1%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%BE%D0%B2)
