### ISSUE TITLE
На главном портале для Киева убрать футер

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#710]
4. В версию возможно На всех страницах перехода убрать область:

https://docs.google.com/document/d/1fUJlMptp0npeXNShMwZedfcqnhfz6mhyDcw7qoxtZqU/edit#

**Comment by bvv4ik** [comment]
тестим на https://test.kiev.igov.org.ua

**Comment by smit-pb** [comment]
На test.kiev.igov.org.ua - футтер отсутствует. Задача выполнена.
