### ISSUE TITLE
На главном портале для Киева сделать чувствительным боевой домен

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#711]
7. Сделать ссылки на реализованные услуги версии продуктива. 
для домена: https://es.kievcity.gov.ua

https://docs.google.com/document/d/1fUJlMptp0npeXNShMwZedfcqnhfz6mhyDcw7qoxtZqU/edit#

**Comment by smit-pb** [comment]
Подскажите пожалуйста - а как это протестировать ? Сайт - https://es.kievcity.gov.ua/ - не работает.

**Comment by bvv4ik** [comment]
нужно дождаться отмашки с КМДА, и тогда тестировать..

**Comment by smit-pb** [comment]
Все еще ждем отмашки :(

**Comment by smit-pb** [comment]
![image](https://cloud.githubusercontent.com/assets/12965717/9711965/0737452c-5550-11e5-8b9c-4bfc5ffc3395.png)

Это после входа через БанИД. 

на каком урле - возможно протестировать данную задачу и связанные с ней ?

**Comment by bvv4ik** [comment]
https://es.kievcity.gov.ua/

**Comment by bvv4ik** [comment]
но т.к. доработка еще не вылита на боевой а домен ссылается на боевой, то пока не продеплоимся - проверить не получится

**Comment by smit-pb** [comment]
Следовательно все задачки связанные с этой - будем тестировать уже после деплоя ?

**Comment by bvv4ik** [comment]
эта единственная задача, которую нужно тестировать на боевом...
и это не страшно, если не заработает на боевом, т.к. официально не объявляли о запуске и у нас будет время поправить, если что (но должно работать)

**Comment by OlgaKhomenko** [comment]
создан домен https://es.kievcity.gov.ua

**Comment by bvv4ik** [comment]
домен-то создан, но ссылается он на боевую версию, в которой еще эта версия не продеплоена

**Comment by bvv4ik** [comment]
так что тестить будем уже в продакшине

**Comment by smit-pb** [comment]
Проблема Актуальна !

**Comment by smit-pb** [comment]
Согласно постановки задачи - можно закрывать.
