### ISSUE TITLE
На главном портале для Киева сделать раздельній хедер и название + сделать название кликабельным

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#712]
1. При клике на название портала сделать переход на главную страницу портала

2. Внести правки в название портала Київська міська державна адміністрація (последние три слова с маленькой буквы)

https://docs.google.com/document/d/1fUJlMptp0npeXNShMwZedfcqnhfz6mhyDcw7qoxtZqU/edit#

**Comment by smit-pb** [comment]
Владимир  -подскажите, по какой ссылке можно протестировать эту задачу ? и задачи 710 и 709.

**Comment by smit-pb** [comment]
https://es.kievcity.gov.ua/ - пока не работоспособна. 
Или же эти 3-и задачи находятся в зависимости от https://github.com/e-government-ua/i/issues/711 ?

**Comment by bvv4ik** [comment]
https://test.kiev.igov.org.ua

**Comment by smit-pb** [comment]
Задачка требует доработки. 
- Київська міська державна адміністрація (последние три слова с маленькой буквы) 
НЕ реализовано!
![image](https://cloud.githubusercontent.com/assets/12965717/9753568/3cfc984c-56c7-11e5-82e1-94add243f7f1.png)

**Comment by kurbpa** [comment]
@bvv4ik 
Не готово.
https://drive.google.com/folderview?id=0BydenhvN5xzeflN3aGxaOW5nTDR1UWhYVVRCSGFFOWplakoyUEVHUktmM3RmTnhmQkZONHc&usp=sharingм - необходимая шапка

**Comment by smit-pb** [comment]
Актуальная проблема.

**Comment by smit-pb** [comment]
Реализовано в задаче #753
