### ISSUE TITLE
На главном портале, в профиле услуги, сделать для услуг с типом "ссылка" - возможность скрывать кнопку "Перейти по ссылке"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#713]
Если ссылка равна пустой строке (поле sURL), то скрывать кнопку

**Comment by smit-pb** [comment]
А есть пример таких услуг ?

**Comment by bvv4ik** [comment]
"Реєстрація авто з пробігом в МРЕВ"
(основной, без подчеркивания)

**Comment by smit-pb** [comment]
протестировано.
