### ISSUE TITLE
На бэке wf-base, при отсылке почты искать тєги enum{[*]}, где вместо "*" ид поля с типом enum, взяв значение которого нужно его подставить вместо данного тєга

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#714]
Раздел 2. п.4.Возможность отсылать в электронки не ИД энума а его название!
https://docs.google.com/document/d/1fUJlMptp0npeXNShMwZedfcqnhfz6mhyDcw7qoxtZqU/edit#

**Comment by bvv4ik** [comment]
Для тестирования6 
в БП есть поля с типом enum
у них есть id ,как и у любіх других полей
нужно взять єтот id, (какого-то БП), и на базе него прописать где-то в письме тэг enum{[*]}

например поле с id="typeOfDocument"
тогда в письме нужно вставить:  "enum{[typeOfDocument]}"
тогда туда позставится значение выбранного в форме пункта энума

**Comment by dmitrijzabrudskij** [comment]
dnepr_spravka_o_doxodax
доступна по днепропетровской области

не показывается значение енума пока

**Comment by bvv4ik** [comment]
@dmitrijzabrudskij

у тебя не там тєг заведен:
    <serviceTask id="mailtask1" name="відправка відповіді" activiti:type="mail">

не используй вообще єтот системтаск

используй на выбор:
MailTaskWithAttachments
MailTaskWithoutAttachment

**Comment by bvv4ik** [comment]
вроде правка делалась
нужно проверить повторно

**Comment by bvv4ik** [comment]
только-ж на бэте

**Comment by dmitrijzabrudskij** [comment]
на альфе не работает. имейл уже пытается отправиться. 
вот такую ошибку выдает: https://www.dropbox.com/s/2jyle35j4p07q83/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-09-08%2022.01.25.png?dl=0

**Comment by VadimGulich** [comment]
https://test-version.igov.org.ua/api/process-form 504 Gateway Time-out

**Comment by bvv4ik** [comment]
а на альфе? (бета уже устарела)

**Comment by VadimGulich** [comment]
{"code":"SYSTEM_ERR","message":"No task found for taskId '4752921'"} 
на тестовом ошибка при обработке

**Comment by bvv4ik** [comment]
это где пишет?
если на региональном то прост там поломанная задача и нужно другую выбрать

**Comment by VadimGulich** [comment]
Создал новую заявку , та же ошибка:  https://test.region.igov.org.ua/tasks 

![image](https://cloud.githubusercontent.com/assets/12964120/10094328/2ad24dcc-6367-11e5-85ec-ca65f7918340.png)
