### ISSUE TITLE
На главном портале, сделать опциональные параметрі региона и города в УРЛ-е, при указании которых автоматически будут предустанавливаться город и/или регион

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#715]
В дополнение к URL-у:
https://test.igov.org.ua/service/159/general

Это может быть Хэш- параметр, например:
https://test.igov.org.ua/service/159/general#nID_Region=5&nID_City=6
https://test.igov.org.ua/service/159/general#nID_Region=5
https://test.igov.org.ua/service/159/general#nID_Region=16
https://test.igov.org.ua/service/159/general#sID_UA_Region=8000000000&sID_UA_City=8000000000
https://test.igov.org.ua/service/159/general#sID_UA_Region=8000000000
https://test.igov.org.ua/service/159/general#sID_UA_Region=3200000000
https://test.igov.org.ua/service/159/general#sRegion=Київ&sCity=Київ
https://test.igov.org.ua/service/159/general#sRegion=Київ
https://test.igov.org.ua/service/159/general#sRegion=Київська

или обычный параметр, например:
https://test.igov.org.ua/service/159/general?nID_Region=5&nID_City=6
https://test.igov.org.ua/service/159/general?nID_Region=5
https://test.igov.org.ua/service/159/general?nID_Region=16
https://test.igov.org.ua/service/159/general?sID_UA_Region=8000000000&sID_UA_City=8000000000
https://test.igov.org.ua/service/159/general?sID_UA_Region=8000000000
https://test.igov.org.ua/service/159/general?sID_UA_Region=3200000000
https://test.igov.org.ua/service/159/general?sRegion=Київ&sCity=Київ
https://test.igov.org.ua/service/159/general?sRegion=Київ
https://test.igov.org.ua/service/159/general?sRegion=Київська

Идеальный вариант (унифицированный) через:
 "sID_UA_Region" (КОАТОУУ для Области)
и "sID_UA_City" (КОАТОУУ для города)

но в принципе подойдет пока и через:
"sRegion (название области, для автоматического ввода в автокомплит)
и "sCity" (название города, для автоматического ввода в автокомплит)

Но по итогу - область или область и город вместе - должны стать автоматом выбранные, а диалог перейти на Шаг 2 (отображение кнопки авторизации)

**Comment by VadymVolos** [comment]
Ребята, желательно в ссылках была только латиница. Иначе когда человек делится ссылкой будет большой хвост непонятных символов. Как вы знаете при лайке в твиттере длина сообщения играет значение. Плюс когда ссылки выглядят красиво это очень хорошо. Поэтому будет хорошо если учтете мои пожелания. Если у вас есть идеи лучше, пишите!

**Comment by VadymVolos** [comment]
Когда выглядит вот так ссылка, теряется весь смысл:
https://test.igov.org.ua/service/159/general?sRegion=%D0%9A%D0%B8%D1%97%D0%B2%D1%81%D1%8C%D0%BA%D0%B0

**Comment by LucySuslova** [comment]
пару уточнений нужно
1. VadymVolos commented 5 days ago >>>желательно в ссылках чтоб была только латиница.
На данный момент в ссылках допускается кириллица? Например,
https://test.igov.org.ua/service/159/general?sRegion=%D0%94%D0%BD%D1%96%D0%BF%D1%80%D0%BE%D0%BF%D0%B5%D1%82%D1%80%D0%BE%D0%B2%D1%81%D1%8C%D0%BA%D0%B0 = https://test.igov.org.ua/service/159/general?sRegion=Дніпропетровська?

2. если ссылка типа https://test.igov.org.ua/service/1/general#sID_UA_City=1210100000 (днепр), то попадаем на шаг выбора области, а потом город автоматом проставляется (после выбора области)? не должна (не может ли?) область тоже автоматом определяться и подставляться по городу?

**Comment by bvv4ik** [comment]
ребята, уже все работает

просто можно было проклацать те урл-ы что были в таске

**Comment by bvv4ik** [comment]
а лучше, по вот этой ссылке пройти:
https://test.igov.org.ua/service/159/general?sID_UA_Region=8000000000&sID_UA_City=8000000000


и убедиться что все МРЕО в списке заходят с предустановленными областями и городами

**Comment by LucySuslova** [comment]
testing completed
