### ISSUE TITLE
Реализовать на бэке (wf-base) новый тэг для подстановки ИД заявки, в теле писем, отсылаемых из БП

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#716]
реализовать в классе Abstract_MailTaskCustom

назвать тэг: [nID_Protected]
который будет в нужном месте письма, и который заменится на "ид  заявки" (защищенный по алгоритму Луна ИД процесса)

**Comment by bvv4ik** [comment]
проверить можно на тестовой услуге _test_print_form

**Comment by bvv4ik** [comment]
Днепропетрвоск

**Comment by olyv** [comment]
Можете  предоставить какие-нибудь  указания как тестировать? Например,  сценарий или где именно можно найти тэг?

**Comment by bvv4ik** [comment]
как я и писал в комменте выше "проверить можно на тестовой услуге _test_print_form"
т.е. на главном портале находим эту услугу и оформляем ее
и потом в дашборде находим ее-же и проводим ее до закрытия... на электронку должно прийти письмо с текстом, в которой будет этот номер.. (только не самое первое унифицированное письмо а именно персонализированное)

**Comment by HollyHelga** [comment]
Оставила заявку - получила письмо с ИД (32775015) и нашла заявку по ИД на сайте

**Comment by nazarenkod** [comment]
Работает согласно описанию.
![nid_protected](https://cloud.githubusercontent.com/assets/13256486/9654439/7b92b566-5233-11e5-8476-3b7c83cd007e.jpg)

**Comment by dmitrijzabrudskij** [comment]
не работает
Шановний ДМИТРО

[nID_Protected]

вместо этого параметра должен быть номер заявки

**Comment by nazarenkod** [comment]
Прошу прощения. Ошибся.

**Comment by nazarenkod** [comment]
![nid_protected](https://cloud.githubusercontent.com/assets/13256486/9711467/9f9e18b2-554c-11e5-8faf-baed29bdbbdd.jpg)
На сегодняшний день задача не реализована.

**Comment by nazarenkod** [comment]
На сегодняшний день задача не реализована.
![nid_protected](https://cloud.githubusercontent.com/assets/13256486/9711583/4ac8ab30-554d-11e5-9530-d862b694d14c.jpg)

**Comment by bvv4ik** [comment]
@dmitrijzabrudskij
Дима, это пишет при попытке отправить почту(т.е. ошибка в БП)

2015-09-08_18:40:55.958 | ERROR | org.activiti.rest.controller.ActivitiExceptionController- REST System Exception: Unknown property used in expression: #{MailTaskWithoutAttachments}
org.activiti.engine.ActivitiException: Unknown property used in expression: #{MailTaskWithoutAttachments}

**Comment by dmitrijzabrudskij** [comment]
обновил процесс на альфе. попробуйте еще раз

**Comment by bvv4ik** [comment]
если проверка на альфе будет успешна - пролью на бету

@nazarenkod 

на альфе заработало?

**Comment by VadimGulich** [comment]
{code: "SYSTEM_ERR", message: "Unknown property used in expression: #{MailTaskWithoutAttachments}"}

Ошибка при обработке заявки

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/9742628/1a6c520c-566a-11e5-974f-b23086e4ece0.png)

**Comment by dmitrijzabrudskij** [comment]
не работало из-за мейлтаски с MailTaskWithoutAttachments
поставил MailTaskWithAttachments и полетело - единственное, нужно крепить файл для отправки имейла.

но ид заявки как не было, так и нет

**Comment by bvv4ik** [comment]
уже можно пробовать, должно теперь замениться

**Comment by nazarenkod** [comment]
Ошибка обработки усуги
![5](https://cloud.githubusercontent.com/assets/13256486/9747018/d6982da2-5683-11e5-8c27-69efdbaf6f7e.jpg)

проверяю на https://test.igov.org.ua/

**Comment by LamronNu** [comment]
сейчас там ведутся правки. напишу, когда можно будет тестить

**Comment by nazarenkod** [comment]
Стоит ждать, или до утра подождет?

**Comment by LamronNu** [comment]
вот сейчас можно проверить.
в полученном письме должен быть номер заявки и кнопка отмены (таска #720)
если номер заявки увидите -- значит, текущую таску можно закрывать.

по кнопке (пока не работает само действие после нажатия) -- все замечания в 720-ю таску.. но говорю сразу -- сейчас она не работает, поэтому можно только проверить ее наличие

**Comment by nazarenkod** [comment]
@LamronNu 
та же ошибка...
https://test.igov.org.ua

**Comment by LamronNu** [comment]
давайте тогда уже лучше утром попробуете)
там просто сейчас активно заливаются изменения.. не только мои.

**Comment by nazarenkod** [comment]
@LamronNu еще какое-то время спать не буду...если заработает отпишусь.спасибо:)

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/9754815/445ff972-56d5-11e5-8fe9-4ea81763b278.png)

Обработал успешно заявку но письмо пришло , что обращение отменено

**Comment by LamronNu** [comment]
там поменяли элемент, т.е. содержание письма...
важно в данном случае было, чтобы подставилось [nID_Protected] (ну, и кнопка [cancelTask], только она из другой таски)

**Comment by dmitrijzabrudskij** [comment]
ура! заработало
подставляется и ид заявки и кнопка отмены заявки

вопрос такой - комментарий к отмене куда будет проливаться? для него нужно предусмотреть на форме в дашборде чиновника какое-то поле?

**Comment by nazarenkod** [comment]
@LamronNu 
и снова эта ошибка "500 Internal Server Error [object Object]"

**Comment by LamronNu** [comment]
@nazarenkod 
Вы ту же задачу пробуете? или новую создали?
пробуйте лучше на новой, т.е. заново заведите заявку

**Comment by nazarenkod** [comment]
@LamronNu 
каждый тест=новая заявка.Только что проверил еще раз.
Сервер:
test.igov.org.ua
![5](https://cloud.githubusercontent.com/assets/13256486/9757329/91e56b56-56e8-11e5-9f56-2c9f025165a9.jpg)

**Comment by dmitrijzabrudskij** [comment]
все работает. не сбивайте)
еще раз:
процесс _test_print_form
при обработке выберите из выпадающего списка ВТОРОЕ состояние, прикрепите любой файл и нажмите Опрацюваты

**Comment by nazarenkod** [comment]
Простите, не знал что обязательно нужно приаттачить файл.
Да, все работает, спасибо:)
Таску закрываю
