### ISSUE TITLE
На главном портале реализовать авторизованность пользователя и возможность "Выхода" (по сути - "прибивания" куки)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#717]
Мокап (как должно выглядеть):
![image](https://cloud.githubusercontent.com/assets/4208821/9625175/82180d32-515c-11e5-8bc7-0d5471d84d03.png)

**Comment by uazure** [comment]
@glebzhebrakov есть прогресс?

**Comment by glebzhebrakov** [comment]
@uazure приступаю

**Comment by VadimGulich** [comment]
Ошибка при условии если сессия заканчивается до нажатия кнопки выход  
![image](https://cloud.githubusercontent.com/assets/12964120/10094137/c81e0722-6364-11e5-8e1a-8ab8d2214d5d.png)

**Comment by VadimGulich** [comment]
Уже на боевом, работает корректно , по окончанию сессии выглядит так 

![image](https://cloud.githubusercontent.com/assets/12964120/10159018/6bf20dee-669e-11e5-934b-56c49f832526.png)

В Беклог
Как доработка улучшения:
После окончания сессии не отображать кнопку выхода и ФИО

**Comment by lem8r** [comment]
Чтобы в шапке портала автоматом убирался логин пользователя и кнопка "выйти", нужно запилить менеджер сессии, который бы следил не истекла ли сессия. И тогда к этому менеджеру можно подвязывать другие части портала.

**Comment by lem8r** [comment]
Можно тестить.
Войти на

**Comment by antonlegkiy** [comment]
@lem8r к сожалению пришлось откатить изменения, т.к возникли трудности после данного коммита в работе альфы. При перезагрузке страницы, при переходе на страницу с вводом конкретного адреса в адресной строке, при открытии страницы в новой вкладке - шел редирект на домашнюю страницу.

**Comment by lem8r** [comment]
@antonlegkiy да, действительно баг. Если не авторизироваться, то при открытии любого адреса в новой вкладке делался редирект на /
Там нужно было убрать одну лишнюю строчку, чтоб этого не было.

Редирект должен был делаться только при logout. Это упрощенный вариант избежать всплывающих алертов с ошибкой, когда юзер вышел или истекла сессия, а можно кликнуть на ссылку для которой нужна авторизация.
В идеале нужно отслеживать событие выхода юзера и прятать запрещенный контент. Для этого я в userService добавил broadcast оповещение, но чтоб им пользоваться нужно было лезть в контроллеры журнала, документов и т.д., что я самовольно делать не хотел.

**Comment by lem8r** [comment]
Зашел в журнал, идентифицировался.
Показался список заявок.
Жму "Вийти". Вышел. Гуй абсолютно не поменялся, даже верхняя полоска с логином осталась.
Теперь кликаю на любую ссылку, которую я уже видеть не должен.
Вылазит ошибка
![2016-07-16 16-40-20](https://cloud.githubusercontent.com/assets/5942291/16895155/ec958820-4b74-11e6-88d9-1343536c3712.png)
Вот это я хотел пофиксить в UserService.
Та же история, если просто оставить страницу на пару часов пока куки не истекут.
Этот баг реально достает, если пользоваться услугами iGov как обычный юзер. Хотя он тут в беклоге.
