### ISSUE TITLE
На главном портале поправить блок расширенного фильтра

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#718]
- [x] 1) Фильтры по регионам отображать сразу, а не только после нажатия на активные услуги. Иначе это совершенно не интуитивно.
- [x] 2) Элементы по регионам поставить вверх фильтра, над выбором органа.
- [x] 3) Слова “Регіон” и “Місто” равнять по левому краю так же, как надписи в других выпадающих списках.
- [x] 4) При выборе области обновлять количество доступных онлайн услуг для этой области. При выборе города – обновлять для этого города.

**Comment by bvv4ik** [comment]
сделані п.1-3
остался только 4-й

**Comment by katebutenko** [comment]
насколько я вижу, п.4 уже заимплеменчен http://screencast.com/t/XoHrs05tmqHs

**Comment by bvv4ik** [comment]
вроде да

**Comment by nazarenkod** [comment]
все фильтры рабочие.Слова “Регіон” и “Місто” выравнены по левому
