### ISSUE TITLE
Реализовать на бэке wf-base сервис отмены заявки/тикета гражданином

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#719]
Сервис, который будет получать ИД таски, и по нему отменять тикет (освобождать слот электронной очереди) и ставить отметку в поле таски об отмененной по инициативе гражданина - заявки

1) Название сервиса:
cancelTask

2) Поля:
nID_Protected - номер-ИД заявки (стандартное, с контрольной суммой)
sInfo  - строка с текстом-основанием отмены заявки

3) Освобождать тикет и сохранять данные в доп-поле
3.1) Искать активную задачу Activiti по nID_Protected (с проверенной "отсеченной" последней цифрой контрольной суммы), где без последней цифры это фактически ИД процесса.

3.2) при нахождении искать в ней поля queueData в которых хранятся JSON-объект привязки к очереди.
* Тип поля, в котором содержится объект - queueData (клвсс QueueDataFormType), пример перебора таких полей в методе getListField_QueueDataFormType

3.3) из обьекта выбирать ИД Тикета
* Обработчик полей(для примера), в которых хранятся JSON-объекты ссылок на Электронную очередь находятся в методе scanExecutionOnQueueTickets

3.4) по ИД Тикета - освобождать тикет
* Пример получения Тикета и обнуление его привязки: FlowSlotTicket oFlowSlotTicket = oFlowSlotTicketDao.findById(nID_FlowSlotTicket).orNull(); oFlowSlotTicket.setnID_Task_Activiti(nID_Task_Activiti); oFlowSlotTicketDao.saveOrUpdate(oFlowSlotTicket);

3.5) в поле с ИД sCancelInfo - записать дату и время отмены заявки и следом за ней текст "Причина отмены заявки: " (+ текст из полученного параметра sInfo)

3.6) Выводить текст ошибки:
- Если CRC не верно - "Неверный id заявки"
- Если таска не найдена - "Заявка не найдена"
- Если уже отменена - "Заявка уже отменена"

**Comment by bvv4ik** [comment]
проверкой работы станет проверка производной таски:
https://github.com/e-government-ua/i/issues/720

**Comment by brunneng** [comment]
Для тестирования:
Пример запроса
GET запрос:  http://localhost:8080/wf-region/service/rest/tasks/cancelTask?nID_Protected=123451&sInfo=absd
Где 12345 - id инстанса процесса активити. 1 - валидная контрольная сумма.
При этому чтобы данный запрос отработал без ошибок в базе активити должен существовать процесс 12345 с таской юзера.

Отмена заявки - означает обнуление nID_Task_Activiti (ссылка на таску актвити)  у соответствующей сущности FlowSlotTicket (тикет). Сообщение об успешной "отвязке" таски от тикета будет написано в лог.

Возможные ошибки
{"code":"BUSINESS_ERR","message":"Неверный id заявки"} 
{"code":"BUSINESS_ERR","message":"Заявка не найдена"}
{"code":"BUSINESS_ERR","message":"Заявка уже отменена"}
ЗАМЕЧАНИЕ: к каждому тексту ошибки временно добавлен перевод в скобочках на английский язык (предположительно могут быть проблемы с кодировкой русских символов, поэтому так сделано чтобы можно было хоть что-то понять)

**Comment by bvv4ik** [comment]
вообщем, проверкой будет - проверка таски https://github.com/e-government-ua/i/issues/720

**Comment by bvv4ik** [comment]
@brunneng сори, забыл в таске написать - в доку-ж на вики нашу обязательно этот сервис нужно добавить

**Comment by VadimGulich** [comment]
Ошибка при отмене "реальной " заявки из дашборда 
{"code":"BUSINESS_ERR","message":"Заявка не найдена (Order not found)"}

**Comment by VadimGulich** [comment]
Ошибка при отмене заявки указана выше воспроизводится и https://github.com/e-government-ua/i/issues/720  
Эту задачу закрываю , дабы не дублировать описание ошибок и их исправление
