### ISSUE TITLE
Реализовать на бэке новый тэг. при формировани письма в активити, для подстановки HTML-формі отмені заявки

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#720]
Для обеспечения таски:
https://github.com/e-government-ua/i/issues/719

Реализовать в классе Abstract_MailTaskCustom

1) Тєг назвать: [cancelTask]
2) Подставлять HTML формы (постом) на сервис https://github.com/e-government-ua/i/issues/719
с о свободным полем обьяснения (один из параметров сервиса) и предустановленным параметром nID_Provtected (этот ид получается в том-же классе для другого тэга, что делалось по таске https://github.com/e-government-ua/i/issues/716)
3) Написать сопровождающий текст:
Вы можете отменить свою заявку,указав причину в этом поле:
Кнопка "Отменить заявку"!

ВАЖНО: Обязательно встроить в запрос sAccessKey=.... sAccessContract=Response
а контент для получения "sAccessKey" должен быть в виде полного УРЛ-а, который будет в атрибуте "action", создаваемой формы отправки (сабмита)

- Приблизительный пример есть в классе, по формированию кнопки LiqPay (но в нашем случае это именно должен быть HTML- элемента form, который можно сабмитить прямо в почте)
- И по старому варианту добавления параметров *sAccessKey* и еще одного(упразненного)
пример в том-же классе: Abstract_MailTaskCustom

**Comment by dmitrijzabrudskij** [comment]
dnepr_spravka_o_doxodax
доступна по днепропетровской области

кнопка отмены заявки не появилась пока

**Comment by LamronNu** [comment]
странно, должна быть... "основа" уже есть..
точно тег [cancelTask] называется?

и подскажите, пожалуйста, как мне это увидеть можно?
т.е. как найти этот бп и как "получить" письмо, в котором будет эта кнопка?

**Comment by dmitrijzabrudskij** [comment]
процесс по днепропетровской обрасти отримання довідки про доходи

**Comment by smit-pb** [comment]
процесс по днепропетровской обрасти отримання довідки про доходи

Кнопка отмены - так еще и не появилась.

**Comment by LamronNu** [comment]
процесс _test_print_form
при обработке выберите из выпадающего списка ВТОРОЕ состояние, прикрепите любой файл и нажмите Опрацювати

**Comment by nazarenkod** [comment]
кнопка активна
![activebtn](https://cloud.githubusercontent.com/assets/13256486/9773179/8492c46a-5749-11e5-81c7-41f03a9e9604.png)
возвращает это:
![message](https://cloud.githubusercontent.com/assets/13256486/9773185/971fddd4-5749-11e5-8891-7b7c3fe4c0a7.png)

**Comment by smit-pb** [comment]
Тестирование проводилось на Альфа.
![image](https://cloud.githubusercontent.com/assets/12965717/9780762/a028a540-5795-11e5-96d6-5ae5326447df.png)
Где и какое состояние выбирать ?
Более того - жму - Опрацюваты и получаю 500 ошибку.

**Comment by nazarenkod** [comment]
Вы уверены что работаете с правильной услугой.Только что проверил.
Зеленым выделено поле выбора состояния
![state](https://cloud.githubusercontent.com/assets/13256486/9780907/194c7ba8-5797-11e5-83b7-c70a31ffd486.jpg)
и успешно отработана
![secsform](https://cloud.githubusercontent.com/assets/13256486/9780916/2cc13570-5797-11e5-8c5f-f3d750150771.jpg)

**Comment by LamronNu** [comment]
@smit-pb 
>На процессе - отримання довідки про доходи (Днепр)

на том процессе кнопки нету, сейчас она есть только в **_test_print_form**

**Comment by smit-pb** [comment]
Зашел на тестовый нашел услугу _test_print_form - Для Днепропетровска.
Вот - 
![image](https://cloud.githubusercontent.com/assets/12965717/9789607/ce429730-57d9-11e5-8b4e-5b8068e9098a.png)

**Comment by nazarenkod** [comment]
@smit-pb только что услуга отработала нормально...правда результат пока тот же
![message](https://cloud.githubusercontent.com/assets/13256486/9790003/0abcecc2-57dc-11e5-8ee5-95337f4336e4.png)

**Comment by smit-pb** [comment]
По состоянию на 8:40.
Не совсем понятная реакция почтовика (mail.ru)
![image](https://cloud.githubusercontent.com/assets/12965717/9807791/fafaccde-5860-11e5-87d3-7cc8ffbce257.png)

А потом выкидывает на страницу ->
![image](https://cloud.githubusercontent.com/assets/12965717/9807799/0a377346-5861-11e5-8e4a-0b2f08a8a00c.png)
И какой интересно логин пароль должен внести пользователь ? 

Ради теста я использовал кермита и вот результат->
![image](https://cloud.githubusercontent.com/assets/12965717/9807809/263b81e0-5861-11e5-998e-4ab4759503cd.png)

**Comment by nazarenkod** [comment]
Значит задача реализована не до конца.

**Comment by LamronNu** [comment]
по порядку)
1) да, при нажатии на кнопку, Вас "перенаправляет" на сервис портала, для входа в который нужно использовать тестовые данные (указаны в вики в "нашем хозяйстве"). Насколько я поняла, пока это временное решение, т.к. стояла задача "сделать основу для процесса отмены", т.е. кнопку+сервис. Остальное будет позже. 
2) за сервис отмены (это была таска #719) отвечает @brunneng, скорей всего, он просто еще "не дошел" до "разбора полётов". Думаю, что как только разберется -- сюда отпишется.

**Comment by brunneng** [comment]
разбираюсь

**Comment by brunneng** [comment]
Оказывается надо было добавлять кнопку Cancel к процессу _test_queue_cancel и тестировать на нем же. Этот процесс пока не светится в услугах , надо его туда добавить, а также добавить кнопку..

**Comment by smit-pb** [comment]
т.е. ждем реализации ?

**Comment by LamronNu** [comment]
ага)

**Comment by bvv4ik** [comment]
_test_queue_cancel

добавлен

**Comment by smit-pb** [comment]
Простите - а куда добавлен ?
Наверное Альфа еще не пересобиралась ?

![image](https://cloud.githubusercontent.com/assets/12965717/9869211/4eaaca92-5b8a-11e5-8cac-8bf19ef0e763.png)

**Comment by smit-pb** [comment]
Услуга есть "_test_queue_cancel"
![image](https://cloud.githubusercontent.com/assets/12965717/9990460/37f489f2-606a-11e5-9031-e902eece4939.png)

А можно очередь добавить ?

**Comment by bvv4ik** [comment]
https://github.com/e-government-ua/i/blob/test/docs/specification.md#18_workWithFlowSlot


выполнить метод: http://test.igov.org.ua/wf/service/flow/setFlowSlot_ServiceData
в PostMan-е (который легко скачать как плагин в гуглохроме)

nID_Flow_ServiceData=12
(или, вместо этого параметра, можно указать sID_BP=_test_queue_cancel)
период можно указать с текущего и +1 месяц

если что, Павел Курбацкий так-же знает как генерить слоты..

П.С.: саму запись по данному ServiceData (подуслуге) я создал...

**Comment by nazarenkod** [comment]
с горем пополам нагенерил слотов. Отослал заявку
![cancel_task](https://cloud.githubusercontent.com/assets/13256486/10097174/f75a4f3a-637f-11e5-8a07-b2c5acd6ba35.jpg)
В письме нет кнопки отмены
![cancel_button_apsent](https://cloud.githubusercontent.com/assets/13256486/10097187/07896c92-6380-11e5-8fa0-bb4ab15ebdd0.jpg)

**Comment by LamronNu** [comment]
это не то письмо.
Такое письмо приходит "автоматически" после создания заявки.
Вам нужно зайти в дашборд чиновника, найти заявку -- и "провести" её, т.е. обработать (чтобы пришло письмо-"ответ"). Содержания того письма не знаю (не видела еще обновленный процесс), но точно не то, что указано на скриншоте

**Comment by nazarenkod** [comment]
хм...я заявку обработал, но никакого письма в ответ не пришло...
сейчас проверю повторно.Просто я когда начинал проверять эту задачу, еще в услуге _test_print_form, кнопка была доступна именно в этом писме

**Comment by nazarenkod** [comment]
да, прошу прощения, приходит два письма. во втором есть возможность отмены, но вместо кнопки просто заготовка "[cancelTask]"
![cancel_task](https://cloud.githubusercontent.com/assets/13256486/10098083/f73ea6fc-6386-11e5-9977-cbcd39493585.jpg)

**Comment by smit-pb** [comment]
Сейчас вообще - помилкаSYSTEM_ERR 
 Object { code="SYSTEM_ERR",  message=null}

**Comment by bvv4ik** [comment]
2015-09-25_13:53:22.267 | INFO | org.wf.dp.dniprorada.engine.task.Abstract_MailTaskCustom- TAG_CANCEL_TASK:Found
2015-09-25_13:53:22.268 | INFO | org.wf.dp.dniprorada.base.dao.AccessDataDaoImpl- [setAccessData]:sContent=/wf/service/rest/tasks/cancelTask?nID_Protected=52252311
2015-09-25_13:53:22.270 | INFO | org.wf.dp.dniprorada.base.dao.AccessDataDaoImpl- [setAccessData]:sKey=d34fc318-24e7-413b-a367-8085b21ce348
2015-09-25_13:53:22.274 | INFO | org.wf.dp.dniprorada.base.dao.AccessDataDaoImpl- [getAccessData]:sKey=d34fc318-24e7-413b-a367-8085b21ce348,aContent.length()=56
2015-09-25_13:53:22.274 | INFO | org.wf.dp.dniprorada.base.dao.AccessDataDaoImpl- [getAccessData]:sKey=d34fc318-24e7-413b-a367-8085b21ce348,sData.length()=56
2015-09-25_13:53:22.274 | INFO | org.wf.dp.dniprorada.base.dao.AccessDataDaoImpl- [getAccessData]:sKey=d34fc318-24e7-413b-a367-8085b21ce348,sData=/wf/service/rest/tasks/cancelTask?nID_Protected=52252311
2015-09-25_13:53:22.274 | INFO | org.wf.dp.dniprorada.base.dao.AccessDataDaoImpl- [setAccessData]:sData(check)=/wf/service/rest/tasks/cancelTask?nID_Protected=52252311
2015-09-25_13:53:22.274 | INFO | org.wf.dp.dniprorada.engine.task.CancelTaskUtil- total URL for action =https://test.region.igov.org.ua/wf/service/rest/tasks/cancelTask?nID_Protected=52252311&sAccessKey=d34fc318-24e7-413b-a367-8085b21ce3
2015-09-25_13:53:22.274 | INFO | org.wf.dp.dniprorada.engine.task.Abstract_MailTaskCustom- >>>>cancel button = <form method="POST" action="https://test.region.igov.org.ua/wf/service/rest/tasks/cancelTask?nID_Protected=52252311&sAccessKey
<input type="text" name="sInfo"/><br/>
<input type="submit" name="submit" value="Скасувати заявку!"/></form>
2015-09-25_13:53:22.275 | INFO | org.wf.dp.dniprorada.engine.task.MailTaskWithAttachments- sAttachmentsForSend=null
2015-09-25_13:53:22.276 | ERROR | org.activiti.rest.controller.ActivitiExceptionController- REST System Exception: null
java.lang.NullPointerException
        at org.wf.dp.dniprorada.engine.task.MailTaskWithAttachments.execute(MailTaskWithAttachments.java:56)

т.е. проблема в описании БП:

    <serviceTask id="servicetask2" name="біометричний терміновий" activiti:delegateExpression="#{MailTaskWithAttachments}">

указано что должны отсылаться атачменты, переменная-ссылка на которые не указана в системтаске БП (_test_queue_cancel):

**Comment by dmitrijzabrudskij** [comment]
Володя, системтаска без аттачментов не работала (#{MailTaskWithoutAttachments}) - поэтому заменил на таску с аттачментами.

могу для теста поменять назад - посмотришь какая ошибка будет

**Comment by dmitrijzabrudskij** [comment]
https://www.dropbox.com/s/pfi65l4305tseuj/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-09-25%2016.01.59.png?dl=0

заработало. при переходе по кнопке из имейла требует авторизацию

**Comment by smit-pb** [comment]
Так и что с этим делать ? - фикс в рамках данной задачи ? или как ?

**Comment by bvv4ik** [comment]
по поводу "требует авторизации" - по началу починили, но после последующей доработки опять поламали..
сейчас чиним, и по результату отпишутся

**Comment by smit-pb** [comment]
Доброго дня.
В какой форме - это можно проверять ?

**Comment by smit-pb** [comment]
Таска Актуальна ?

**Comment by LamronNu** [comment]
@smit-pb , здравствуйте
Таска вроде актуальна, мне казалось, что давно закрыта уже...
Подскажите, пожалуйста, на каком бп Вы тестируете?
Вы выше писали про ошибку 
>Сейчас вообще - помилкаSYSTEM_ERR 
Object { code="SYSTEM_ERR", message=null}

а то я помню, сначала в одном бп размещали кнопку, потом в другом...
будем разбираться

**Comment by smit-pb** [comment]
Так я и спрашиваю на каком БП - его проверить то можно ?

А то последний месседж был - 
по поводу "требует авторизации" - по началу починили, но после последующей доработки опять поламали..
сейчас чиним, и по результату отпишутся

И потом ТИШИНА !!! 
Хочу ее дотестировать и закрыть - но не понятно на каком БП - ее дотестировать.

**Comment by LamronNu** [comment]
спокойствие, только спокойствие))
все мы занимаемся проектом по мере возможности и актуальности задач..
иногда что-то "упускается из виду" -- спасибо Вам за то, что не даете "забыть совсем" про задачу)

насчет этой кнопки -- сегодня уточню

**Comment by LamronNu** [comment]
услуга: _test_queue_cancel, https://test.igov.org.ua/service/756/general
в письме приходит кнопка

**Comment by smit-pb** [comment]
Доброго Дня.
Добавьте для этого БП - штук 5 дат - ПОЖАЛУЙСТА.

**Comment by OlgaTurenko** [comment]
https://test.igov.org.ua/service/159/general
там 2 разных МРЭО (  те же 2 департамента)

Прошу для тестирования использовать все же эту услугу.

**Comment by OlgaTurenko** [comment]
все в ней уже есть.

**Comment by LamronNu** [comment]
да, я нагенерила слотов на ноябрь-месяц тогда. может, даты сразу не подгрузились, нужно подождать немного.
и Ольга права, там два департамента (делалось для другой таски). просто выберите даты и там, и там

**Comment by smit-pb** [comment]
У меня пришло 3-и письма, и ни в одном из них - не было кнопки отменить. 
Была кнопка "Оплатить" и гипер ссылки на IGov.
Я использовал Мэил.ру.

Создал заявку - зашел в "хозяйство" перевел ее в работу. Потом отправил уточнение - а потом перевел в статус отработанная. 
И нету письма отмены заявки на услугу.

**Comment by LamronNu** [comment]
@OlgaTurenko , а в указаной Вами услуге (https://test.igov.org.ua/service/159/general) точно есть кнопка в письме? имею ввиду тег  [cancelTask] ? 
может, Вы перепутали с другой задачей, где нужно два департамента указывать?
в указанном мною бп кнопка есть:
>услуга: _test_queue_cancel, https://test.igov.org.ua/service/756/general

только что проверила, нагенерила расписание для Департамента 1. приходит письмо:
![image](https://cloud.githubusercontent.com/assets/8156670/11128533/fa6a3504-8982-11e5-8266-917ff48726da.png)

**Comment by OlgaTurenko** [comment]
Да. Перепутала. Не в ту задачу скопировала ссылку. Прошу прощения.

**Comment by smit-pb** [comment]
Вообщем, да кнопка появляется ( но нужно хотябы пару пикселей отступ сделать от поля ввода.)
И после нажатия - появляется окно .
![image](https://cloud.githubusercontent.com/assets/12965717/11141690/5618e978-89f0-11e5-948b-95c26e9e4eb8.png)
 
Что по сути тоже коряво смотрится.
И финально - нажав на кнопку отправить получаем страничку 
![image](https://cloud.githubusercontent.com/assets/12965717/11141702/7af724c6-89f0-11e5-8f62-c774d3ca516e.png)

Ее бы наверное не показывать пользователю.

Текущую задачу закрываю. 
А вот описанные косяки - желательно бы перенести в новую задачу на доработку.

**Comment by kraina** [comment]
GET-ссылка в POST-запросе.
У вас POST-запрос в форме "Скасувати заявку", а ссылка имеет вид GET-ссылки.
Т.е. <form method="post" ... и дальше идет ссылка для метода GET: action="https://region.igov.org.ua/wf/service/action/task/cancelTask?nID_Order=403943140&sAccessContract=RequestAndLoginUnlimited&sAccessKey=2b3310aa-3b7a-4287-bd93-157908c8c8c1"  
Вы передаете данные из письма клиента через адресную строку. Это GET-запрос. Может, стоит поменять method="POST" на method="GET" в форме: <form method="GET" action="https://region.igov.org.ua/wf/service/action/task/cancelTask?nID_Order=403943140&sAccessContract=RequestAndLoginUnlimited&sAccessKey=2b3310aa-3b7a-4287-bd93-157908c8c8c1" 

Вот простейший пример разницы между GET и POST запросами: 
Пример GET-запроса:
File: get.php 

< html>
< head>
< title>Пример передачи значений переменных методом Get< /title>
< /head>
< body>

< form method="get" >< input name="name" value="Vera" > < input name="surname" value="Taran" >< input type="submit" > < /form>
< br>

<?php
if(!empty($_GET["name"])&&!empty($_GET["surname"])){

        echo " Имя - ".$_GET["name"].",<br>фамилия - ".$_GET["surname"];
    }
?>
< /body>
< /html>

Данные из формы передаются в адресную строку: 
GET URL: http://get.php?name=Vera&surname=Taran

Пример POST-запроса:
File post.php

< html>
< head>
< title>Пример передачи значений переменных методом POST< /title>
< /head>
< body>

< form method="post" >< input name="name" value="Vera" > < input name="surname" value="Taran" >< input type="submit" > < /form>
< br>

<?php
if(!empty($_POST["name"])&&!empty($_POST["surname"])){

        echo " Имя - ".$_POST["name"].",<br>фамилия - ".$_POST["surname"];
    }
?>
< /body>
< /html>

POST URL: http://post.php
Данных из формы нет в адресной строке.

Ссылка в письме передает информацию в адресную строку, очевидно нужно использовать GET-запрос: https://region.igov.org.ua/wf/service/action/task/cancelTask?nID_Order=403943140&sAccessContract=RequestAndLoginUnlimited&sAccessKey=2b3310aa-3b7a-4287-bd93-157908c8c8c1

Я, конечно, не могу видеть весь ваш код, а только то, что есть в письме, но вдруг это поможет...
Я просто customer. Пыталась удалить себя из очереди на получение загран. паспорта, но кнопка "Скасувати заявку" не работает, если бы работала, то вместо меня мог бы пойти и получить паспорт другой хороший человек. А так я застолбила очередь и не пришла, отказаться тоже не смогла. 
Вот изобразила bug report с картинками: http://dnipro.ucoz.net/igov/BugReport_20160720_International_Passport_Task_Can.html

Просто customer Вера Таран 
[BugReportIgov.zip](https://github.com/e-government-ua/i/files/390567/BugReportIgov.zip)
![png_email_international_passport_task_cancel](https://cloud.githubusercontent.com/assets/6605200/17249272/e7c2f354-55a7-11e6-919b-d286888c6ed7.png)
