### ISSUE TITLE
Поправить на бэке тексты, выводимые в "Мой журнал"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#721]
Задача из списка:
https://docs.google.com/document/d/1Nqw1nSzuQiSOu9LiyCFDo1cV_EFhR3voa2Vg-aKPJ-0/edit?pli=1

Содержание:
Мой журнал
Все тексты были описаны в этом документе. Давайте их использовать, пожалуйста (и уж точно не на русском).

**Comment by OlgaTurenko** [comment]
На сервере тексты актуализированы. Теперь необходимо, чтоб клиент отображал содержимое поля sMessage, а не sEventName.

**Comment by VadimGulich** [comment]
На беке реализовано:
Пример:[{"sMessage":"Приватбанк завантажує Паспорт Паспорт у Ваш розділ Мої документи","sDate":"2015-07-05 15
:11:22.608","nID":20047,"nID_Subject":20045,"nID_HistoryEventType":2,"sEventName":"В Мои документы пользователя загружен новый документ – через наш портал"}
нужна задачка для фронта 
- - - - - - - - - - - - - - - - - - - 
Не критично но  нужно подправить текстовки =) : 
1) Приватбанк -->   должно быть ПриватБанк

**Comment by OlgaTurenko** [comment]
Это старый комментарий, видать в справочнике из которого тянули назание, была на тестовом ошибка.. Из свеженького: {"sMessage":"Організація ПриватБанк скористалась доступом, який Ви надали, та переглянула документ Квитанція про сплату %Назва документу%","sDate":"2015-09-08 00:18:46.487","nID":24600,"nID_Subject":20045,"nID_HistoryEventType":7,"sEventName":"Кто-то воспользовался доступом к документу, который ему предоставил пользователь"}

**Comment by VadimGulich** [comment]
Понял , спасибо Ольга =)
