### ISSUE TITLE
На бэке заменить старый вариант "одноразовой" авторизации на новый (пока вроде в двух-трех местах)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#722]
Сама обновленная авторизация реализована по таске:
https://github.com/e-government-ua/i/issues/699

Нужно 
1) В дополнение к передаваемому параметру nID_Subject
передавать еще sAccessContract=Request
2) Пир генерации sAccessKey - в качестве контента брать теперь относительный урл самого запроса
(т.е. только то что в параметрах GET, без хоста)

Сейчас старая авторизация есть
- при формировании кнопки для LiqPay
- тамже, но при запросе Мерчанта
- и при фидбєке (отсілке єлектронки с активити)
Может еще где-то...

Проще искать в коде по слову "sAccessKey"

**Comment by OlgaTurenko** [comment]
Для тестирования при формировании кнопки для LiqPay и тамже, но при запросе Мерчанта, брать услугу _test_liqpay (по завершению на портале https://test.region.igov.org.ua:6948/tasks 

Для тестирования при фидбєке брать услугу _test_mailer

**Comment by nazarenkod** [comment]
после оценки вернуло значения:
![mark](https://cloud.githubusercontent.com/assets/13256486/9663353/b6430d94-526c-11e5-989e-1070b4497697.jpg)
Я так понимаю это ожидаемое поведение?

**Comment by nazarenkod** [comment]
_test_liqpay пока не отрабатывается...видимо производятся какие-то правки

**Comment by nazarenkod** [comment]
Состояние на сегодня :
В услуге _test_mailer отображается ошибка при переходе на страницу заполнения формы
![1](https://cloud.githubusercontent.com/assets/13256486/9711859/7e50f46a-554f-11e5-8721-a32b91f00069.jpg)

В услуге _test_liqpay почти та же ситуация
![2](https://cloud.githubusercontent.com/assets/13256486/9711927/d3443f90-554f-11e5-9bc3-72b579f547e0.jpg)
Прошу отписаться когда почините.

**Comment by bvv4ik** [comment]
починили

**Comment by VadimGulich** [comment]
Зависает браузер при отработке услуги _test_liqpay  
![image](https://cloud.githubusercontent.com/assets/12964120/9743483/588db8c8-566f-11e5-9015-87191f2a5513.png)

**Comment by VadimGulich** [comment]
Услуга не работает _test_mailer
![image](https://cloud.githubusercontent.com/assets/12964120/9743753/937cc464-5670-11e5-9463-1bec8906a685.png)

**Comment by VadimGulich** [comment]
так и не исправлено

**Comment by nazarenkod** [comment]
услуга _test_liqpay отработала.
В письме пришла вот такая интересная кнопка.
![default](https://cloud.githubusercontent.com/assets/13256486/9774235/cd91d254-574f-11e5-850b-ca3a2b16dc47.jpg)
по ней переход на liqpay
![liqpay](https://cloud.githubusercontent.com/assets/13256486/9774241/dc25807c-574f-11e5-99e1-78b090587c4a.jpg)
ВОпрос: 
Будет какое то поле с ид-плптежа?

**Comment by nazarenkod** [comment]
Услуга _test_mailer на данный поломана.
![tesp_miler](https://cloud.githubusercontent.com/assets/13256486/9774329/676b02ba-5750-11e5-8bf4-44b513fcfcd8.jpg)

**Comment by VadimGulich** [comment]
@nazarenkod  <<ВОпрос: 
Будет какое то поле с ид-плптежа?

Нужно провести платеж , тчо б появился ИД платежа

**Comment by nazarenkod** [comment]
@VadimGulich 
есть тестовые данные для проведения платежа, или использовать свою карту?

**Comment by VadimGulich** [comment]
@nazarenkod  Свою =)

**Comment by nazarenkod** [comment]
Оплата пошла успешно
![default](https://cloud.githubusercontent.com/assets/13256486/9791932/3d8ce8fa-57e6-11e5-956d-1c64d51eee44.png)
в поле ид-платежа подтянулось вот такое значение
![1](https://cloud.githubusercontent.com/assets/13256486/9791962/71cc4106-57e6-11e5-88c6-803aa8ac785a.jpg)
исходя из условия "в поле id платежа должно быть не пусто и не нал" работает корректно.

**Comment by VadimGulich** [comment]
@nazarenkod  То не ИД платежа  а , № заявки без контрольной суммы  и плюс еще и  null в поле

Вот такой должен быть ИД платежа:
![image](https://cloud.githubusercontent.com/assets/12964120/9807892/35f32be6-5862-11e5-9018-00a11703ff33.png)

**Comment by VadimGulich** [comment]
Задача нуждается в фиксе

**Comment by nazarenkod** [comment]
Вот теперь все ясно и прозрачно:)Ждем фикса

**Comment by bvv4ik** [comment]
коллеги, к данной задаче эти замечания не имеют ни какого отношения

**Comment by nazarenkod** [comment]
@bvv4ik Добрый день. Для проверки руководствовался вот этим сценарием @OlgaTurenko 
("Для тестирования при формировании кнопки для LiqPay и там же, но при запросе Мерчанта, брать услугу _test_liqpay. После оплаты гражданином услуги на региональном портале в таске в поле id платежа должно быть не пусто и не нал")

Подскажите тогда, какая проверка будет подтверждать правильную реализацию задачи?

**Comment by VadimGulich** [comment]
@nazarenkod  Закрывай, доработка по ид платежа будет в рамках , я так понял , другой задачи
