### ISSUE TITLE
На главном портале реализовать наследование и переопределение отдельных подветок для глобального обьекта markers

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#724]
обеспечить возможность наследования частей глобального объекта markers с "базовой версии" и частичное опциональное переопределение при обнаружении такого-же объекта в поле markers формы

- Если поля с типом markers нету или есть но там пусто (по trim), то ничего не делать с ним
- Если поле есть и не пустое - десериализовать его в реальный JSON-объект и домержить в глобальный объект markers
- Проходиться по всем полям с типом markers и последовательно домерживать объект каждого в глобальный
- все поля структур которые в этих полях формы совпадают с элементами глобального объекта - должны заменять эти элементы глобального объекта (но только именно элементы а не так, что раз встретилась ветка validate то целиком глобальную ветку validate нужно заменить... т.е. заменять только конечные элементы веточек)

**Comment by VadimGulich** [comment]
реализовано
