### ISSUE TITLE
На главном портале, в Мои документы, добавить модальный диалог с расширенной информации по ЭЦП

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#725]
Просмотр ЭПЦ в Документы

Сделать "содержимое поля с ЭЦП в таблице с Мои документы" - кликабельным, при клике на него в новом окошке отображать названия и значения всех параметров ЭЦП.

Отображать в виде таблицы Лейбл(Понятное название поле) | Значение

- Пример объекта oSign:
{"state":"ok","customer":{"inn":"1436057000","fullName":"Сервіс зберігання сканкопій","signatureData":{"name":"АЦСК ПАТ КБ «ПРИВАТБАНК»","serialNumber":"0D84EDA1BB9381E80400000079DD02004A710800","timestamp":"01.09.2015 08:44:12","code":true,"desc":"П
ІДПИС ВІРНИЙ","dateFrom":"13.08.2015 11:24:31","dateTo":"12.08.2016 23:59:59","sn":"UA-14360570-1"},"organizations":[{"type":"edsIsuer","name":"ПУБЛІЧНЕ АКЦІОНЕРНЕ ТОВАРИСТВО КОМЕРЦІЙНИЙ БАНК «ПРИВАТБАНК»","unit":"АЦСК","address":{"type":"factual","state":"Дніпропетровсь
ка","city":"Дніпропетровськ"}},{"type":"edsOwner","name":"ПАТ КБ «ПРИВАТБАНК»","mfo":"14360570","position":"Технологічний сертифікат","ownerDesc":"Співробітник банку","address":{"type":"factual","state":"Дніпропетровська","city":"Дніпропетровськ"}}]}}

- Краткое описание:
"inn":"1436057000" - ИНН, т.к. это юр. лицо то туда вписывают ОКПО
"fullName":"Сервіс зберігання сканкопій" - это ФИО хозяина ЭЦП, типа Дубилет Дмитрий Александрович

Это информация об АЦСК
"signatureData":{"name":"АЦСК ПАТ КБ «ПРИВАТБАНК»","serialNumber":"0D84EDA1BB9381E80400000079DD02004A710800","timestamp":"01.09.2015 08:44:12","code":true,"desc":"П
ІДПИС ВІРНИЙ","dateFrom":"13.08.2015 11:24:31","dateTo":"12.08.2016 23:59:59","sn":"UA-14360570-1"}

timestamp":"01.09.2015 08:44:12" - время подписания скана
"code":true,"desc":"ПІДПИС ВІРНИЙ" - это флаг действительности ЭЦП на момент подписания, т.е. в момент подписания не была отозвана 

"dateFrom":"13.08.2015 11:24:31","dateTo":"12.08.2016 23:59:59" - срок действия ЭЦП

информация о самом хозяине ЭЦП
"type":"edsOwner","name":"ПАТ КБ «ПРИВАТБАНК»","mfo":"14360570","position":"Технологічний сертифікат","ownerDesc":"Співробітник банку","address":{"type":"factual","state":"Дніпропетровська","city":"Дніпропетровськ"}}]

- Подробное описание полей тут: http://zakon2.rada.gov.ua/laws/show/z1398-12
Брать п.п.: 3.1, 3.5, 3.8

Это задача из списка:
https://docs.google.com/document/d/1Nqw1nSzuQiSOu9LiyCFDo1cV_EFhR3voa2Vg-aKPJ-0/edit?pli=1

**Comment by nazarenkod** [comment]
Реализовано.
![default](https://cloud.githubusercontent.com/assets/13256486/9713016/595507fc-5557-11e5-9165-81cb809c3a3e.jpg)
