### ISSUE TITLE
На главном портале поправить формат и источник даты в закладках  некоторые колонки

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#726]
- [x] 1) В закладке "Мой журнал" отображать формат даты такой:
Формат даты: 01.09.2015 15:45

- [x] 2) В закладке Статусы отображать в найденной по ИД заявке - дату из обьекта а не текущую (как сейчас)

- [x] 3) В закладке Документы, Поиск Документов
- [x] 3.1) скрыть колонкы с датой и "Кем загружено
- [x] 3.2) В колонке "Завантажити" убрать заголовок, и вместо иконки закрузки отрисовать ссылку "Завантажити"

**Comment by nazarenkod** [comment]
1) В закладке "Мой журнал" отображать формат даты такой:
Формат даты: 01.09.2015 15:45
Формат даты отображается согласно описанию.
![1dataformat](https://cloud.githubusercontent.com/assets/13256486/9712363/c9df2eee-5552-11e5-9df6-6b3c890f1620.jpg)

 2) В закладке Статусы отображать в найденной по ИД заявке - дату из обьекта а не текущую (как сейчас).
Неправильный формат времени.
![2wrongdataformat](https://cloud.githubusercontent.com/assets/13256486/9712446/51b351a6-5553-11e5-9dbd-f682e8dd56c6.jpg)

 3) В закладке Документы, Поиск Документов
 3.1) скрыть колонки с датой и "Кем загружено"


Если речь идет о колонках,которые отмечены красным, то не реализовано.
Если речь о вкладке "Пошук документу за кодом"(отмечен зеленым), то дайте данные для поиска.
![3qw](https://cloud.githubusercontent.com/assets/13256486/9712762/9772cc9c-5555-11e5-9391-a9d24ad829c5.png)

**Comment by bvv4ik** [comment]
речь о поиске
чтоб искать нужно просто расшарить любой док и полученній номер ввести в поиске + источник - Приватбанк и тот тип дока что шарился... если мс СМС то код 4444

**Comment by nazarenkod** [comment]
1) В закладке "Мой журнал" отображать формат даты такой:
Формат даты: 01.09.2015 15:45 - реализовано.

 2) В закладке Статусы отображать в найденной по ИД заявке - дату из обьекта а не текущую (как сейчас) - ошибка формата даты(14:57:54.234)

 3) В закладке Документы, Поиск Документов

 3.1) скрыть колонкы с датой и "Кем загружено"-Реализовано,колонки отсутствуют.
 3.2) В колонке "Завантажити" убрать заголовок, и вместо иконки закрузки отрисовать ссылку "Завантажити"-Реализовано.
![serchdoc](https://cloud.githubusercontent.com/assets/13256486/9761311/a053d328-5704-11e5-9c61-ec8938fb9595.jpg)

Вопрос:
При поиске документа по источнику "ПриватБанк" документ не находит.Хотя в колонке "Ким завантажена копія" указано что ПриватБанк.
Работает только через выбор оператора "iGov"
Подскажите, это ожидаемое поведение?

**Comment by bvv4ik** [comment]
да, поведение ожидаемое, т.к. фактически контент уже в иГов-е...

так-же п.2. не существнное отклонение(по формату времени) не приносящее вреда...

**Comment by nazarenkod** [comment]
@bvv4ik Спасибо за пояснения.Значит задачу закрываю.
