### ISSUE TITLE
На главном портале реализовать фильтр и на странице "Все услуги"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#727]
Фильтры на странице подкатегории
например: https://igov.org.ua/subcategory/1/3

Проблема: воспользовавшись каким-то фильтром, а затем перейдя на страницу подкатегории, эти фильтры пропадают.
Нужно разместить наверху таких страниц такой же фильтр, как на стартовой. И при переходе со стартовой на страницу подкатегории, если на стартовой был выбран какой-то фильтр, задавать его сразу и на странице подкатегории.

**Comment by uazure** [comment]
@bvv4ik фильтр должен быть полным (с выбором региона, организации и т.п., или достаточно текстового поля?

**Comment by bvv4ik** [comment]
полностью идентичный фильтр тому что на главной странице

**Comment by uazure** [comment]
Сделал. Надо чтоб кто-то с незамыленым взглядом поюзал.

**Comment by VadimGulich** [comment]
Проверено , фильтр работает корректно

**Comment by uazure** [comment]
С опозданием пишу как тестировать.
1) зайти на главную страницу портала. В фильтре выбора услуг (вверху) ввести\выбрать значения. Запомнить отфильтрованный список услуг.
2) перейти в подкатегорию услуг либо нажав на "Всі послуги" внизу подкатегории либо нажав на заголовок подкатегории. Подкатегория - это например "Міліція та ДАІ", "Взаємодія з державними органами".
3) удостовериться что выбранные ранее фильтры отображаются корректно и список услуг отображается с их учетом + с учетом выбранной подкатегории.

**Comment by rostag** [comment]
Перевірив, у мене вийшло так (скажіть, чи це очікуваний рез-т):

![image](https://cloud.githubusercontent.com/assets/451410/9809337/e750349e-586f-11e5-9d3c-b88785f301c8.png)

**Comment by uazure** [comment]
@rostag в моєму розумінні - все правильно

**Comment by bvv4ik** [comment]
да, вроде все как надо
