### ISSUE TITLE
Навести порядок с контроллерами и сервисами в них

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#728]
Сейчас сервисы, совершенно не относящиеся к онтроллерам там находятся

1) В гуглоэкселе написать список контроллеров и вложенными в них сервисами (кратко только названия)
2) В отдельной колонке прописать новые названия контроллеров под отдельные сервисы и согласовать их с @OlgaTurenko или @bvv4ik
3) Внести правки на бэке и не соммитя так-же на фронте (централа и регионала), после чего закомитить
4) После этого тщательно проверить все на фронтах
5) Исправить документацию по АПИ на Вики

**Comment by tivv** [comment]
@OlgaTurenko: Не против, если  заберу таску себе?

**Comment by bvv4ik** [comment]
Ольга действительно сейчас сильно перегружена другими важными задачами, которые не получится отложить... так что с чистой совестью, думаю, можете помагать в этой таске)

**Comment by bvv4ik** [comment]
важно не забыть про то что мы говорили - чтоб клиент не поламался...

**Comment by bvv4ik** [comment]
Виталий, есть ориентиры по времени, требуемому на реализацию?

**Comment by tivv** [comment]
Если без обкладывания всего тестами - смогу на ближайших выходных. Плюс для тестирования "всего" у меня пока слишком мало знаний о проекте

**Comment by tivv** [comment]
Вот файл с текущим списком сервисов на обоих типах серверов: https://docs.google.com/spreadsheets/d/1rmsiOsUhEkWxvDWMImAu1REUR7HqwbZBcju0wcGNdrM/edit?usp=sharing

**Comment by tivv** [comment]
BTW: Как насчет унести документацию во что-то типа http://scottfrederick.github.io/springdoclet/sample/springdocs/index.html ?
Это позволит хранить все рядом с кодом, при этом имея хорошую более самоподдерживаемую документацию для тестеров / UI devов / ....

**Comment by tivv** [comment]
Еще вариант подобного подхода: https://github.com/kliniki-online/spring-web-doclet

**Comment by tivv** [comment]
Нашел неплохой обзор разных вариантов: https://mestachs.wordpress.com/tag/spring-mvc/

**Comment by tivv** [comment]
Обновил страничку в Google Docs - добавил предлагаемые места по рефакторингу контроллеров. Можно ревьювить. Все еще сомневаюсь по пакетам - я разложил по функциям (activiti/db/...), может стоило просто разнести по base/central или и то и другое (central/db,base/activiti,...)

**Comment by LamronNu** [comment]
хорошая работа) все разложено "по полочкам" -- наглядно видно, что где есть...
насчет переименования контроллеров без добавления перед названием ActivitiRest -- полностью "за" ) а то громоздко как-то получалось... хотя я думала, что в этом есть какая-то задумка..
>Все еще сомневаюсь по пакетам - я разложил по функциям (activiti/db/...), может стоило просто разнести по base/central или и то и другое (central/db,base/activiti,...)

Вы хотите эти контроллеры еще разложить по доп.пакетам, верно? "увидела" такие подпакеты: activiti (задачи, бп, эл.очереди, расписание), redis, db (большинство контроллеров, связанных с сущностями в бд: доки, сабжекты, ескалации, события, места, страны...), util (паттерны, доступ).. Вроде норм, но тут как скажут другие участники, может, и не стоит делать "деление" внутри пакета контроллер.. 

а насчет примечания:
>Part of Activiti (do we need it open to public?)

тут не подскажу, т.к. еще не ориентируюсь, как идет взаимодействие активити-элементов и этих сервисов

**Comment by tivv** [comment]
@OlgaTurenko, @bvv4ik: ваше мнение?

**Comment by OlgaTurenko** [comment]
@tivv спасибо Вам за список всех сервисов. Сегодня постараюсь все просмотреть в течении дня и ночи и до завтра отписаться.

**Comment by OlgaTurenko** [comment]
Предложила альтернативные названия. Просьба критиковать :)

**Comment by tivv** [comment]
У меня два комментария:
1) Не уверен, что имеет смысл делать пакеты на один контроллер (например org.egov.web.controller.escalation)
2) Я бы ProcessDefinition всё-таки вынес отдельно. Это работа с метаданными, в отличии от Process, где идет работа с данными.

**Comment by OlgaTurenko** [comment]
По поводу 2-го пункта - согласна.
По поводу первого тоже. Если в перспективе появятся новые виды эскалации, то мы всегда сможем организовать новый пакет и туда переселить классы по эскалации.

**Comment by OlgaTurenko** [comment]
Нужно теперь определиться с новыми названиями методов и урлами на которые замапим сервиса.

**Comment by dgroup** [comment]
Мне очень понравилось предложение с использованием SpringDoclet (https://mestachs.wordpress.com/tag/spring-mvc/ ).
Может имеет смысл сделать демо? :)

**Comment by OlgaTurenko** [comment]
В файлике скрыла столбцы с Вашими и моими предложениями, оставила согласованный вариант. Добавила столбцы по предложениям по наименованию методов и URL сервисов.

**Comment by OlgaTurenko** [comment]
По формированию ури было бы хорошо определиться со схемой его формирования, чтоб в доке описали правило, согласно которому формировали ури. У нас в ури уже есть \serviсe. К нему добавлять (к примеру) \название последнего пакета  + \название класса без слова Controller + \название метода.

**Comment by tivv** [comment]
По урлам вопрос, пытаемся ли мы делать REST с использованием всего набора методов или оставляем POST и действие в урле

**Comment by tivv** [comment]
По документации - я бы брал что-то с конца списка типа swagger или IO docs. Оно более живое плюс позволяет QA запускать запросы сразу из документации
