### ISSUE TITLE
Написать на бэке (wf-base) конвертор, для формирования формулы расписания Quartz для электронного расписания

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#730]
- [x] 1) по полям:
sRegionTime; - диапазон времени
saRegionWeekDay; - дни недели
nLen - число в минутах длительности интервала

- [x] 2) Сущности: FlowProperty.csv

- [x] 3) Написать метод getQuartzFormulaByParameters создания формулы Quartz, на основании этих параметров (п.1.), в виде стринга

Возвращать стрингу JSON-обьект такого формата:
{"0 15,30,45/15 15 ? * MON,TUE,THU,FRI":"PT15M"}
где,
"PT15M" - так-же длительности интервала
а "0 15,30,45/15 15 ? * MON,TUE,THU,FRI" - стандартная кварцевая формула

- [x] 4) Написать обратный п.3. метод getQuartzParamenersByFormula возвращения по формуле Quartz - исходных этих параметров (п.1.) в виде мапы 

Пример конвертора(правда фронтэндового):
http://www.cronmaker.com/) и обратно

- [ ] 4)  прикрутить на: /setSheduleFlowInclude
там авто-генерировать формулу по параметрам входящим и полученную строку-обьект JSON в  параметр "sData" подставлять

**Comment by ASkosyr** [comment]
Added util class /wf-base/src/main/java/org/egov/util/QuartzUtil.java with two specified methods

**Comment by ASkosyr** [comment]
добававил вызов утилиты в методе setSheduleFlowInclude

**Comment by nazarenkod** [comment]
Как проверить доработку?

**Comment by bvv4ik** [comment]
@ASkosyr  скажи плиз, как проверить?

**Comment by RoOmel** [comment]
За запрос
https://test.region.igov.org.ua/wf/service/flow/setSheduleFlowInclude?nID_Flow_ServiceData=1&sName=Test&sRegionTime=10:30-11:30&sDateTimeAt=2010-08-01 10:10:30&sDateTimeTo=2010-08-01 18:10:00&saRegionWeekDay=mo,tu

Получен ответ сервера
{
    "sData": null,
    "bExclude": false,
    "sName": "Test",
    "sRegionTime": "10:30-11:30",
    "saRegionWeekDay": "mo,tu",
    "sDateTimeAt": "2010-08-01 10:10:30",
    "sDateTimeTo": "2010-08-01 18:10:00",
    "nLen": null,
    "sLenType": null,
    "nID": 60141,
    "nID_FlowPropertyClass": {
        "sPath": "org.wf.dp.dniprorada.base.service.flow.propertyHandler.DefaultFlowSlotScheduler",
        "sBeanName": "defaultFlowSlotScheduler",
        "nID": 1,
        "sName": "DefaultFlowSlotScheduler"
    }
}
что несколько отличается от ответа в доке https://github.com/e-government-ua/i/blob/test/docs/specification.md#25_setSheduleFlowInclude
Отличие в выходных параметрах
    "nLen": null,
    "sLenType": null
Задача реализована согласно ТЗ

**Comment by RoOmel** [comment]
ASkosyr, если можно сообщите мне ваш логин скайп, чтобы вопросы по задачам решать опративнее.
