### ISSUE TITLE
Починить работу с услугой в рамках всей страны

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#731]
Заходя:
https://test.igov.org.ua/service/368/general
и авторизуясь через БанкИД
- возвращает в исходное состояние(перед авторизацией), вместо открытия формы с услугой...

**Comment by serdyuk-alex** [comment]
Зашел на услугу, залогинился через bankId нормально, правда форма не рисуется ибо приходит 
```javascript
{"code":"SYSTEM_ERR","message":"Unknown property used in expression: ${bankIdlastName} ${bankIdfirstName} ${bankIdmiddleName}"}
```
На реквест: 
https://test.igov.org.ua/api/process-form?url=https:%2F%2Ftest.region.igov.org.ua%2Fwf-region%2Fservice%2Fform%2Fform-data%3FprocessDefinitionId%3Dgni_69:57:3637712

**Comment by OlgaTurenko** [comment]
Проверила. Форма загружается по услуге. Все ок.

**Comment by VadimGulich** [comment]
работает
