### ISSUE TITLE
На главном портале добавить полный каталог банков-источников документов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#732]
на основании списка БанкИД

**Comment by olyv** [comment]
Здравствуйте, 
насколько я понимаю, список банков должен быть здесь https://test.igov.org.ua/documents/search, верно? А где можно найти список БанкИД?

**Comment by LamronNu** [comment]
>А где можно найти список БанкИД?

когда пробуете "зайти с помощью БанкИД" : 
![image](https://cloud.githubusercontent.com/assets/8156670/9703732/0e68bd8c-5495-11e5-8b02-6465325e7005.png)

**Comment by olyv** [comment]
Спасибо огромное за ответ.
Кроме перечисленных банков я также вижу в выпадающем списке некий igov, иак и должно быть? В респонсе по https://test.igov.org.ua/api/documents/search/getDocumentOperators это выглядит как 

{  
      "nID_SubjectOrgan":2,
      "sHandlerClass":"org.wf.dp.dniprorada.model.document.DocumentAccessHandler_IGov",
      "nID":1,
      "sName":"iGov"
   }

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/9711218/996c39c6-554a-11e5-9957-5b6b6ba3349a.png)

**Comment by VadimGulich** [comment]
>>Кроме перечисленных банков я также вижу в выпадающем списке некий igov, иак и должно быть? 

Да, так и должно быть  , так как документы можно загружать на IGov предоставлять доступ.

**Comment by olyv** [comment]
Хорощо. Тогда закрою issue после исправления опечатки.

**Comment by VadimGulich** [comment]
Я думаю это перенесем в беклог , а задачу закроем
