### ISSUE TITLE
На главном портале скачанные документы всегда пустые

### ISSUE THREAD

**Issue by olyv** [e-government-ua/i#733]
Шаги для воспроизведения:
1. Создайте на своем компьютере текстовый (.txt) файл
2. В разделе "Документи" загрузите только что созданный файл
3. Скачайте только что загруженный документ
Ожидаемы результат: документ скачан, содержимое документа корректное
Действительный результат: документ пуст, размер документа 0 bytes

пример "битого" документа: https://test.igov.org.ua/api/documents/download/24427

ОС Ubuntu, браузер Google Chrome

**Comment by taaraora** [comment]
fixed under commit https://github.com/e-government-ua/i/commit/420fee94d6d93af87c8d2a653ac61116fdc829a1

**Comment by bvv4ik** [comment]
да, пофиксино, проверяйте

**Comment by smit-pb** [comment]
В принципе задача выполнена согласна описания проблемы. Можно закрыть.
Но - если фаил загружен PNG или JPG - то обратно выгружается без формата , пофиксить бы ;)

**Comment by taaraora** [comment]
Имеется ввиду без расширения? Только что загрузил на  https://test.igov.org.ua файл и с ним всё хорошо  - https://test.igov.org.ua/api/documents/download/26934

**Comment by smit-pb** [comment]
Да имеется ввиду - что фаил который обратно скачиваем с сервера , то фаил качается без расширения, хотя конечно потом можно открыть с помощью тогоже вьювера эту картинку.
Но сам факт - загрузил png а обратно загрузился фаил без расширения.

**Comment by taaraora** [comment]
не получается воспроизвести, как можно с вами связаться?

**Comment by smit-pb** [comment]
Сейчас - постараюсь воспроизвести и - положить актуальный линк на фаил.

**Comment by smit-pb** [comment]
https://test.igov.org.ua/documents/user/content#share27145

**Comment by smit-pb** [comment]
Фаил загрузился как 27145
Хотя он фактически с расширением jpg

**Comment by olyv** [comment]
Тлько что проверил на google chrome (OS Ubuntu), у меня все Ок. @smit-pb можете дать ссылку на скачиваемый файл?

**Comment by smit-pb** [comment]
ІПН	15 September 2015 00:00	Я		 
Входим под Дубилетом Д. И переходим по ссылке 
https://test.igov.org.ua/documents/user/content#share27145

**Comment by olyv** [comment]
Если мы говорим о https://test.igov.org.ua/api/documents/download/27145, то у меня скачивается jpeg файл. Да, расширение не указано. Но файл не битый, имеет свойства JPEG image и открывается. Полагаю, дефект можно закрыть.
