### ISSUE TITLE
На дашборде реализовать "Интерфейс для работы с правилами эскалаций"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#734]
ориентир:
https://test.region.igov.org.ua/escalations
логин/пароль: kermit/kermit

Только на основании своего перечня полей и сущностей, которые нужно туда "вывести":

- [x] 1) основная закладка со списком правил и возможностью их добавить, редактировать, удалять и клонировать (как в образце по расписаниям электронной очереди)
EscalationRule - правила
nID;sID_BP;sID_UserTask;sCondition;soData;sPatternFile;nID_EscalationRuleFunction
1;dnepr_dms_passport;"*";"nElapsedDays == 100";"{nDays:10, asRecipientMail:['bvv4ik@gmail.com', 'askosyr@gmail.com']}";"escalation/escalation_template.html";1
где:
sID_BP - ИД БизнесПроцесса (для удобства стоит отображать его название)
sID_UserTask;sCondition - формула условия
soData - JSON-обьект с параметрами (для удобства его лучше отображать в виде комбобокса, при віборе пунктов которого давать их править + редактировать)
sPatternFile - название файла с шаблоном основного сообщения
nID_EscalationRuleFunction - ИД функции(по сути комбобокс со списком из нижних сущностей, с названиями из sName)

- [x] 2) вспомогательная закладка со списком функций, с теми-же возможностями что и в п.1.
EscalationRuleFunction - функции (действия при выполнения правил)
nID;sName;sBeanHandler
1;Отправка уведомления на электронную почту;EscalationHandler_SendMailAlert
где:
sName - название
sBeanHandler - название Бина-обработчика

**Comment by bvv4ik** [comment]
[0:44:13] Kateryna Butenko: http://screencast.com/t/2dTwF7hSxQnY
[0:44:13] Kateryna Butenko: будет доступно по https://test.region.igov.org.ua/escalations
[0:44:13] Kateryna Butenko: пока еще ничего не сохраняется не удаляется и т.д.
[0:44:13] Kateryna Butenko: это чисто UI с моделькой

**Comment by OlgaTurenko** [comment]
Просьба протестировать добавление, редактирование и удаление очередей из интерфейса.

**Comment by nazarenkod** [comment]
Работает только добавление у удаление

**Comment by bvv4ik** [comment]
@katebutenko  Катерина, реализовано таки не полностью?

**Comment by nazarenkod** [comment]
и вот так 10 минут, ничего не происходит
![clip2net_160111112251](https://cloud.githubusercontent.com/assets/13256486/12230021/d58b135a-b855-11e5-8c30-e3dad1eda26f.jpg)

**Comment by katebutenko** [comment]
@bvv4ik да, по-моему на тот момент было добавление и удаление. Насчет редактирования не помню :) кнопка для копирования была, но без функционала.

@nazarenkod  наверное, что-то уже поменялось в сервисах, достающих список правил с сервера. Надо смотреть.

**Comment by bvv4ik** [comment]
@katebutenko 
Привет, таску "допиливать" планируешь, или лучше не рассчитывать?

**Comment by GFalcon-UA** [comment]
На странице редактирования правил эскалаций, из сервера затягивается ряд правил, которые привязаны к бизнес-процессам с уже несуществующими ID
![screen](https://cloud.githubusercontent.com/assets/13604023/15313047/46b41eea-1c11-11e6-9081-f97b8bf9b486.png)
Вот список этих "мусорных" айдишников:
[undefined IDs.txt](https://github.com/e-government-ua/i/files/267524/undefined.IDs.txt)

Как поступать с такими правилами эскалаций?

**Comment by GrekD** [comment]
**тестирование:**
создала правило эскалации ИД 153248 (письмо на почту)
параметры: nDaysLimit:-1
подала заявку по процессу lviv_mvk_701
запустила вручную срабатывание этого правила эскалации
https://test.region.igov.org.ua/wf/service/action/escalation/runEscalationRule?nID=153248
письмо не пришло (спам и корзину проверяла)
так что сама эскалация пока что не срабатывает
условия пробовала разные nElapsedDays==nDaysLimit и nElapsedDays>nDaysLimit
ни по одному из них письмо не пришло

создала правило эскалации  ИД 153249 (порождение бп)
параметры: nDaysLimit:-1
запустила вручную срабатывание этого правила эскалации
https://test.region.igov.org.ua/wf/service/action/escalation/runEscalationRule?nID=153249
процесс не породился (проверяла в универсальном дашборде эскалаций volont_escalation)

**по внесению данных:**
когда создаю правило в первый раз не дает внести изменения в поле "ID функції ескалації"": только сохраняю, потом нажимаю "редагувати" и только тогда могу редактирвоать это поле

технически, заполнить все поля получилось - но это было трудно и не понятно, ни один чиновник в жизни не догадается как правильно это заполнять. В связи с этим впросы и предложения:

**вопрос:**
после добавления правила в дашборде оно как-то проливается (синхронизируется) с нашим конфигурационным файлом EscalationRule.csv?

**предложения:**

- [ ] поле Задачі бізнес-процеса: совсем не очевидно что это usertask. Вернутся к вопросам стандартизации юзертасок (маркеры состояний и предлагать в выпадающем поле именно эти фиксированные состояния) Поле переименовать "Для якого етапу звернення налаштовується ескалація?"

- [ ] Формула умови: для чиновников убрать это вобще - оставить возможность вносить сюда что-то только аналитикам в конфигурационных файлах.
По умолчанию во всех правилах что создаются из дашборда ставить: nElapsedDays>nDaysLimit

- [ ] "Параметри" и "ID функції ескалації" переформатировать в следующие поля:
- "через скільки днів повинна спрацювати єскалація" - маленькое поле и возможность внести только число
- "що треба зробити у випадку порушення термінів?" - віпадающий список из двух позиций "відправити повідомлення на емайл" та "створити задачу для волонтерів"
- в случае выбора "відправити повідомлення на емайл" - показать поле для внесения емайл

- [ ] параметр  "ИД бізнес-процессу" не показывать всем, показывать только тем у кого есть админские права

**Comment by GFalcon-UA** [comment]
Дарья, оно еще не готово для тестирования
Судя по описанию, не срабатывает, потому что параметр условия - это JS-объект обернутый в строку, вы же задали просто строку. Но до этого я еще дойду...
п.2 и п.3. - как раз сейчас занимаюсь над этим и надеюсь, что сегодня вечером или завтра уже сможете попробовать
По поводу п.4 - у меня вопрос: из сервера загружается массив бизнес-процессов, у которых одинаковые имена и различить их возможно только по их ID. Как пользователь будет их различать? вот, например:
novopscov_silrada_453
dnepr_mvk_474
dnepr_mvk_345

**Comment by GrekD** [comment]
4. согласна с Вами, но чиновник скорее не поймет эти ИДшники БП все равно. Но давайте оставлять

**Comment by GFalcon-UA** [comment]
по поводу вопроса
> после добавления правила в дашборде оно как-то проливается (синхронизируется) с нашим конфигурационным файлом EscalationRule.csv?
После добавления правила через дашборд, оно его сохраняет в базе данных на сервере в таблице `EscalationRule`. А насколько эта таблица БД синхронизируется с файлом EscalationRule.csv - этого, к сожалению, не знаю

**Comment by GFalcon-UA** [comment]
Уважаемые, чтобы

> поле Задачі бізнес-процеса: совсем не очевидно что это usertask. Вернутся к вопросам стандартизации юзертасок (маркеры состояний и предлагать в выпадающем поле именно эти фиксированные состояния) Поле переименовать "Для якого етапу звернення налаштовується ескалація?"

для этого необходимо внести дополнение в файл https://github.com/e-government-ua/i/blob/test/wf-base/src/main/java/org/igov/service/controller/ActionTaskCommonController.java и дополнить сервис `GET /action/task/getLoginBPs` так, чтобы к каждому объекту бизнес-процесса был привязан массив его юзер-тасок:
```
[
  {
    "sID": "dnepr_spravka_o_doxodax",
    "sName": "Дніпропетровськ - Отримання довідки про доходи фіз. осіб",
    "aUserTasks": 
      [
        {
          "sStatusName": название юзертаски,
          "sID_Status": ИД юзертаски
        },
        {
          "sStatusName": название юзертаски,
          "sID_Status": ИД юзертаски
        }
      ]
  },
  {
    "sID": "khmelnitskij_mvk_2",
    "sName": "Хмельницький - Надання інформації, що підтверджує відсутність (наявність) земельної ділянки",
    "aUserTasks": 
      [
        {
          "sStatusName": название юзертаски,
          "sID_Status": ИД юзертаски
        },
        {
          "sStatusName": название юзертаски,
          "sID_Status": ИД юзертаски
        }
      ]
  }
]
```
Делаем?

**Comment by GrekD** [comment]
@bvv4ik посмотрите, пожалуйста, предложение Алексея
