### ISSUE TITLE
Поменять сортировку по дате в Моем журнале.

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#736]
Поменять сортировку по дате в Моем журнале. В самом начале самые "свежие" события, в самом конце самые "старенькие". 

(https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit пункт 30)

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/9870433/75f8a1a0-5b94-11e5-8daa-46eb1f6ca4fb.png)

Дата перестала отображаться

**Comment by nazarenkod** [comment]
@VadimGulich только что проверил
Chrome 45.0.2454.85 m
![default](https://cloud.githubusercontent.com/assets/13256486/9870490/03fe3ed8-5b95-11e5-89ea-7d140f76963b.jpg)

**Comment by VadimGulich** [comment]
тогда закрыва
