### ISSUE TITLE
Починить ошибку при работе с БП по Мрео для Днепропетровска

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#737]
поламалась услуга:
"Реєстрація авто з пробігом в МРЕВ"
для Днепропетровска

после авторизации в консоли пишет:
TypeError: _.trim is not a function

![image](https://cloud.githubusercontent.com/assets/4208821/9737418/3ca5a0be-564f-11e5-85cf-9a109527abb8.png)

**Comment by serdyuk-alex** [comment]
Использовался lodash.trim но мы используем старую версию библиотеки в которой нету функций по работе со String

**Comment by VadimGulich** [comment]
Зависает браузер при отработке услуги 
![image](https://cloud.githubusercontent.com/assets/12964120/9760224/f11cd47a-56fb-11e5-89a9-535da367c7c2.png)

**Comment by VadimGulich** [comment]
Уже работает корректно :
![image](https://cloud.githubusercontent.com/assets/12964120/9785668/bd53f6f2-57bc-11e5-9c01-19883fda6dae.png)
