### ISSUE TITLE
Глосарий

### ISSUE THREAD

**Issue by HollyHelga** [e-government-ua/i#738]
Столкнулась с проблемой, что я, как и многие вновь прибывшие не сосем понимают стиль, в котором "прошареные" выражают свои мысли. Создаю табличу с соответсвующими словами. Пишите коментарии, пожелания, новые термины, вопросы и пр.
Те кому нужны мануалы по основам тестировния пишите в личку в Слаке.

https://docs.google.com/spreadsheets/d/1xuJvTDznip-UcdH1kev8lUdbmH8XNjkNctbucHaSQ6Q/edit?usp=sharing

**Comment by bvv4ik** [comment]
Прошу создать тут в конце раздел Глоссарий, и там составлять этот список:
https://github.com/e-government-ua/i/wiki/%D0%9D%D0%B0%D1%88%D0%B8-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D1%8B

**Comment by HollyHelga** [comment]
Былобы неплохо,что б соответсвующий аздел здлал ктото кто в этом разбирается...

**Comment by LamronNu** [comment]
мне кажется, что это больше к разделу про тестирование относится: https://github.com/e-government-ua/i/wiki/%D0%A2%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%83
, и добавить где-то в конце..

так как "Наши стандарты" больше нужны (и понятна терминология) разработчикам.

из того, какие еще бы термины добавить.. тут больше тестировщики, конечно, напишут, но навскидку:
 - из слов:

дашборд, полигон, продакш, боевой, фронт, услуга, системтаска, таска, ишуе, активити...

- из процессов:

  -- протестировать определенную услугу (т.е. сначала зайти на портал, найти услугу, оформить заявку, потом зайти на дашборд чиновника, провести услугу и т.п.)

 -- протестировать сервис (прочитать описание апи в документации и проверить работоспособность сервиса и соответствие его поведения ТЗ)

**Comment by olyv** [comment]
Добрый день, а что подразумевается под "Активити"?
