### ISSUE TITLE
Создать структуру, удобную для перевода текста

### ISSUE THREAD

**Issue by katebutenko** [e-government-ua/i#741]
Сейчас все тексты просто напрямую забиты в html, json и js. Стандартное решение для таких случаев - сделать xml/json dictionary, из которого можно будет брать запись на нужном языке. Тогда будет легко перевести сайт на русский или английский или любой другой язык. 

Построить такой dictionary можно, к примеру, используя систему краудсорс переводов. Я работала с системой Transifex и попробовала нескольско других. Transifex ощутимо платный, но очень удобный.

**Comment by rostag** [comment]
Підтримую. На фронт-енді можна починати з https://docs.angularjs.org/guide/i18n

**Comment by bvv4ik** [comment]
конечно поддерживаю, и это конечно-же было у нас в планах... но очень не скоро...
прошу переместить таску в бэклог: https://docs.google.com/document/d/1sUEGBOBp3HFw_n6RKMghpgMYsbSpvepQToWFKunqRZQ/edit

а отсюда удалить

**Comment by rostag** [comment]
@bvv4ik @katebutenko - переніс, зачиняю цей тікет.
