### ISSUE TITLE
Добавить указание кодировки UTF-8  в теле емейлов

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/i#742]
Добавить указание кодировки для сервис-таски  по отправке емйлов с атачментами (#{MailTaskWithAttachments})

в теле письма указание кодировки отсутствует и мозилла тандербирд уже письмо не читает.
Так же не раскодирует это письмо и стандартный клиент Андроида.

**Comment by rostag** [comment]
Важлива проблема, вже пишуть про неї: https://www.facebook.com/groups/eServicesUA/permalink/1052413501445089/

**Comment by smit-pb** [comment]
В принципе - реализовано. По крайней мере , отображается письмо нормально.

![image](https://cloud.githubusercontent.com/assets/12965717/10128983/d524026e-65c1-11e5-91e3-0be511d96e6f.png)

**Comment by Koffeek** [comment]
{"code":"SYSTEM_ERR","message":"Field definition uses unexisting field 'charset' on class org.wf.dp.dniprorada
.engine.task.MailTaskWithAttachments"} при попытке встроить поле кодировки. 
@smit-pb тестировать надо на почте i.ua тогда будет четко видно. Гугл подправляет кодировки.

**Comment by smit-pb** [comment]
протестировано на гугл почте и на мэил.ру
браузеры Хром и Фаир.

**Comment by smit-pb** [comment]
может еще какие-то условия нужно сделать чтобы воспроизвести ошибку ? (кроме i.ua ? )

**Comment by Koffeek** [comment]
Ошибка на данный момент в том, что почта просто не уходит при подстановке кодировки. А по i.ua, мы всегда кодировочные проблемы на этих ящиках отсматриваем.

**Comment by smit-pb** [comment]
Вообщем ко мне приходит на Мэил ру и на Гугл в UTF-8.
Можно закрывать ?

**Comment by NizhnikAlex** [comment]
На i.ua проблема решена

**Comment by smit-pb** [comment]
Класс ! Спасибо Алекс.
