### ISSUE TITLE
На дашборде в разделе "Звіни" блоке "Експорт" добавить такой-же комбобокс с доступными БП, как и в блоке с "Статистика" и для каждого БП брать свой набор параметров, беря их из патернов /pattern/export

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#744]
1) сейчас набор параметров захардкоден жестко:

    exportLink: function (exportParams) {
      var data = {
        'sID_BP': 'dnepr_spravka_o_doxodax',
        'sID_State_BP': 'usertask1',
        'sDateAt': exportParams.from,
        'sDateTo': exportParams.to,
        'saFields': '${nID_Task};${sDateCreate};${area};${bankIdinn};;;${bankIdlastName} ${bankIdfirstName} ${bankIdmiddleName};4;${aim};${date_start1};${date_stop1};${place_living};${bankIdPassport};1;${phone};${email}',
        'sID_Codepage': 'win1251',
        'nASCI_Spliter': '18',
        'sDateCreateFormat': 'dd.MM.yyyy HH:mm:ss',
        'sFileName': 'dohody.dat'
      };

, а нужно чтоб он брался из файла по пути 
/pattern/export/*
где название файла = id бизнеспроцесса

за исключением параметров:
        'sID_BP': 'dnepr_spravka_o_doxodax',
        'sDateAt': exportParams.from,
        'sDateTo': exportParams.to,

2) 
контент паттерна должен быть в виде обычных пропертей:

sID_BP = dnepr_spravka_o_doxodax
sID_State_BP = usertask1
saFields = ${nID_Task};${sDateCreate};${area};${bankIdinn};;;${bankIdlastName} ${bankIdfirstName} ${bankIdmiddleName};4;${aim};${date_start1};${date_stop1};${place_living};${bankIdPassport};1;${phone};${email}
sID_Codepage = win1251
nASCI_Spliter = 18
sDateCreateFormat = dd.MM.yyyy HH:mm:ss
sFileName = dohody.dat

3) Подгружать этот контент файлов с пропертями  можно через сервис:
https://test.region.igov.org.ua/wf-region/service/rest/getPatternFile?sPathFile=print/export/dnepr_spravka_o_doxodax.properties

https://github.com/e-government-ua/i/blob/test/docs/specification.md#30-Работа-с-файлами-шаблонами

т.е. просто "пробросить" этот сервис через ноду и в онлайне, после выбора пункта с БП - подтягивать проперти, которые и должны стать в основу, при использовании экспорта...

![image](https://cloud.githubusercontent.com/assets/4208821/9810631/c620830e-587a-11e5-817d-25a85fbdc886.png)

**Comment by bvv4ik** [comment]
тестить можно на БП:
dnepr_spravka_o_doxodax
Дніпропетровськ - Отримання довідки про доходи фіз. осіб

**Comment by katebutenko** [comment]
Для тесту:
на сторінці "Звіти":
поки підгружаються доступні бізнес-процеси, відображається напис "Зачекайте..."
http://screencast.com/t/P3zNORyw

(чіт для тестів: якщо натиснути "Експортувати" до закінчення завантаження, буде збережено репорт з довідками про доходи у Дніпропетровську)

"Експортувати" та "Зберегти" зберігають файли зі звітом та статистикою відповідно. Приклади файлів:
Звіт: http://screencast.com/t/oVeCJ1Zuxth кодування windows-1251
Статистика: http://screencast.com/t/oVeCJ1Zuxth кодування UTF-8

пробуйте відкривати різними редакторами, бо у даних, що повертаються, поки що є трабли з кодуванням.

**Comment by VadimGulich** [comment]
Выпадающий список вылазит за пределы браузера
![Uploading image.png…]()

**Comment by katebutenko** [comment]
у меня тоже, оно так и было ) надо либо скроллбар добавить, либо просто названия более короткие сделать. Или не комбобокс, а большую форму, в которой будет легче искать.

Проверь, пожалуйста, основной функционал, чтоб насчет самих репортов все точно было ок :)

**Comment by VadimGulich** [comment]
В ФФ не скачиваются файлы
При выборе экспорт - экспортировать любую услугу  ошибка 403  
https://drive.google.com/file/d/0Bw7BSYSLbe2MV3BxQ3dBR1ZCODQ/view?usp=sharing

**Comment by katebutenko** [comment]
Добавила обработку ошибок.
Работает только "Дніпропетровськ - отримання довідки про доходи фізичних осіб". Почти все остальное возвращает пустые файлы, так и должно быть.

**Comment by VadimGulich** [comment]
Исправлено !

Осталось:
1) не работает выгрузка файлов в ИЕ и ФФ

**Comment by katebutenko** [comment]
Поменяла процесс загрузки. Нужно проверить, что скачанный файл можно открыть и прочесть, желательно той же тулзой, которая будет использоваться конечными пользователями. Там может быть проблема с кодировками.

**Comment by VadimGulich** [comment]
Да , ошибка в кодировке есть , при скачивание статистики : 
![image](https://cloud.githubusercontent.com/assets/12964120/9870010/086bc19c-5b91-11e5-9d6c-3c3d4600e03a.png)

Остальные ошибки исправлены

**Comment by katebutenko** [comment]
Меня тоже смущает, но @bvv4ik говорит, так и должно быть. Попробуй открыть в windows-1251 кодировке

**Comment by VadimGulich** [comment]
Если  @bvv4ik говорит , что так норм , то тогда закрываем
Ошибки исправлены , суть задачи реализована )
