### ISSUE TITLE
На бэке (wf-base) доработать сервис /file/download_bp_timing, выводя в нем все поля БП

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#745]
- [x] 1) добавить опциональный параметр bDetail, с умолчательным параметром true
- [x] 2) при bDetail=true, к существующим 6-ти полям выдаваемой информации по каждой задаче:
"nID_Process", "sLoginAssignee", "sDateTimeStart", "nDurationMS", "nDurationHour", "sName"
 - выводить все поля тасок с содержимым
т.е. получится, например:
"nID_Process", "sLoginAssignee", "sDateTimeStart", "nDurationMS", "nDurationHour", "sName", "bankIdFamily", "bankIdName", "tel"

даже если набор полей в разных тасках отличается - это не страшно - просто в некоторых ячейках будут не заполнены данные (пустота)

- [x] 3) фактически подтягивать для каждой позиции таску(только из истории), и перечислять все ее поля, а id-шники делать хеадерами колонок
- [x] 4) дополнить документацию

**Comment by bvv4ik** [comment]
![image](https://cloud.githubusercontent.com/assets/4208821/9910918/2f6346cc-5ca8-11e5-8c16-584a0e474fac.png)
[19:15:18] Забрудский Дмитрий Андреевич: https://test.region.igov.org.ua:6948/tasks\
[19:15:23] Забрудский Дмитрий Андреевич: dn200986zda
[19:15:26] Забрудский Дмитрий Андреевич: логин-пароль
[19:15:31] Забрудский Дмитрий Андреевич: в обороблені

![image](https://cloud.githubusercontent.com/assets/4208821/9910934/4bc0b0ca-5ca8-11e5-9fcc-6eab6f59c72c.png)

это то, что есть

nID_Process,"sLoginAssignee","sDateTimeStart","nDurationMS","nDurationHour","sName","comment","decision","selection"


а кроме этого там еще есть bankIdfirstName, dateofbirth, date_from , garbage_number  и так далее

**Comment by RoOmel** [comment]
Запрос
https://test.region.igov.org.ua/wf/service/rest/file/download_bp_timing?sID_BP_Name=lviv_mvk-1&sDateAt=2015-06-28&sDateTo=2015-09-01&nRowsMax=1000&nRowStart=0&bDetail=true
 возвращает
"nID_Process","sLoginAssignee","sDateTimeStart","nDurationMS","nDurationHour","sName"
но интересно посмотреть на ответы сервера при других значениях параметра sID_BP_Name,
т.к. в доке
https://github.com/e-government-ua/i/blob/test/docs/specification.md#0_contents
написано, что "Метод возвращает .csv файл со информацией о завершенных задачах в указанном бизнес процессе за период.".
Файл .csv возвращается, но кроме названия параметров больше ничего.

**Comment by bvv4ik** [comment]
просто поискать в проекте любой другой БП, подпапке bpmn, которая в wf-region, в ресурсах

**Comment by RoOmel** [comment]
Где искать подпапке bpmn?

**Comment by VadimGulich** [comment]
https://github.com/e-government-ua/i/tree/test/wf-region/src/main/resources/bpmn

**Comment by RoOmel** [comment]
Вадим, благодарю за ссылку.
По запросу
https://test.region.igov.org.ua/wf/service/rest/file/download_bp_timing?sID_BP_Name=dndz_cnap_186&sDateAt=2015-10-01&sDateTo=2015-10-08&nRowsMax=1000&nRowStart=0&bDetail=true
получил ответ сервера
"nID_Process","sLoginAssignee","sDateTimeStart","nDurationMS","nDurationHour","sName","PrintForm_1","PrintForm_2","adres_1","adres_2","adres_3","bankIdPassport","bankId_scan_passport","bankIdfirstName","bankIdinn","bankIdlastName","bankIdmiddleName","category","clFio","comment_1","comment_2","date_1","date_2","date_today","decision_1","decision_2","dogovor","duration_fair","email","head","imya_ur","markers1","phone","phone_1","protokol","reestr_numb","subekt","type_fair","zgoda"
"5865135","GrekD","2015-10-06:14-03-21","152048","0","перевірка документів","","","test","Т-3","","АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002","5865194","ДМИТРО","3119325858","ДУБІЛЕТ","ОЛЕКСАНДРОВИЧ","test","ДУБІЛЕТ ДМИТРО ОЛЕКСАНДРОВИЧ","","","Wed Oct 07 00:00:00 EEST 2015","Wed Oct 14 00:00:00 EEST 2015","Wed Sep 30 00:00:00 EEST 2015","accept","reject","5865326","less","darja.grek@gmail.com","5865320","","","050 182 7284","","5865323","","","test","Замовляючи послугу Ви надаєте згоду на обробку Ваших персональних даних та підтверджуєте їх актуальність"
"5865198","GrekD","2015-10-06:14-05-32","144613","0","перевірка документів","","","test","Т-3","","АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002","5865258","ДМИТРО","3119325858","ДУБІЛЕТ","ОЛЕКСАНДРОВИЧ","test","ДУБІЛЕТ ДМИТРО ОЛЕКСАНДРОВИЧ","","","Tue Sep 29 00:00:00 EEST 2015","Thu Oct 08 00:00:00 EEST 2015","Wed Sep 30 00:00:00 EEST 2015","reject","","","less","darja.grek@gmail.com","","","","050 182 7284","","","","","test","Замовляючи послугу Ви надаєте згоду на обробку Ваших персональних даних та підтверджуєте їх актуальність"
"5865135","GrekD","2015-10-06:14-05-54","161203","0","повідомлення громадянина про прийняте рішення","","","test","Т-3","","АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002","5865194","ДМИТРО","3119325858","ДУБІЛЕТ","ОЛЕКСАНДРОВИЧ","test","ДУБІЛЕТ ДМИТРО ОЛЕКСАНДРОВИЧ","","","Wed Oct 07 00:00:00 EEST 2015","Wed Oct 14 00:00:00 EEST 2015","Wed Sep 30 00:00:00 EEST 2015","accept","reject","5865326","less","darja.grek@gmail.com","5865320","","","050 182 7284","","5865323","","","test","Замовляючи послугу Ви надаєте згоду на обробку Ваших персональних даних та підтверджуєте їх актуальність"
"5880074","GrekD","2015-10-06:15-40-27","130512","0","перевірка документів","5880150","5880153","Т-3","Т-3","","АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002","5880145","ДМИТРО","3119325858","ДУБІЛЕТ","ОЛЕКСАНДРОВИЧ","","ДУБІЛЕТ ДМИТРО ОЛЕКСАНДРОВИЧ","","","Thu Oct 01 00:00:00 EEST 2015","Wed Oct 07 00:00:00 EEST 2015","Wed Sep 30 00:00:00 EEST 2015","accept","accept","","less","darja.grek@gmail.com","","","{""motion"":{""ShowFieldsOnCondition_1"":{""aField_ID"":[""imya_ur"",""adres_3"",""phone_1""],""asID_Field"":{""sClient"":""subekt""},""sCondition"":""[sClient] == 'ur'""}}}","050 182 7284","","","","fiz","test","Замовляючи послугу Ви надаєте згоду на обробку Ваших персональних даних та підтверджуєте їх актуальність"
"5880074","GrekD","2015-10-06:15-42-38","21104","0","повідомлення громадянина про прийняте рішення","5880150","5880153","Т-3","Т-3","","АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002","5880145","ДМИТРО","3119325858","ДУБІЛЕТ","ОЛЕКСАНДРОВИЧ","","ДУБІЛЕТ ДМИТРО ОЛЕКСАНДРОВИЧ","","","Thu Oct 01 00:00:00 EEST 2015","Wed Oct 07 00:00:00 EEST 2015","Wed Sep 30 00:00:00 EEST 2015","accept","accept","","less","darja.grek@gmail.com","","","{""motion"":{""ShowFieldsOnCondition_1"":{""aField_ID"":[""imya_ur"",""adres_3"",""phone_1""],""asID_Field"":{""sClient"":""subekt""},""sCondition"":""[sClient] == 'ur'""}}}","050 182 7284","","","","fiz","test","Замовляючи послугу Ви надаєте згоду на обробку Ваших персональних даних та підтверджуєте їх актуальність"
