### ISSUE TITLE
В дашборде устранить ошибочное появление диалога "Не обран шаблон для друку"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#746]
Это происходит, когда в комбобоксе выбран шаблон для печати а потом "Роздрукувати", закрыть диалог и перейти на другую таску

![image](https://cloud.githubusercontent.com/assets/4208821/9814985/66301308-589b-11e5-9b60-308dfe0b13bb.png)

**Comment by smit-pb** [comment]
Исправлена - ошибка не воспроизводиться. Проверял под Хромом на тестовом.
