### ISSUE TITLE
На главном портале реализовать возможность по УРЛ-у автоматом заходить в закладку Статусы с предустановленным номером заявки и запуском поиска

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#747]
1) название передаваемого параметра в УРЛ-е:  &nID=1433243

2) так-же реализовать опциональный вспомозательеый параметр &sToken=jG787H9hk00j0k, который нужно передавать транзитом в сервис запроса статуса (прямо до самого бэка явы)
так-же

Пример:
https://test.igov.org.ua/order/search?nID=1433243&sToken=jG787H9hk00j0k
https://test.igov.org.ua/order/search?nID=1433243

![image](https://cloud.githubusercontent.com/assets/4208821/9815371/2d54ba40-589e-11e5-949a-b8628be42406.png)

**Comment by nazarenkod** [comment]
как можно проверить?

**Comment by bvv4ik** [comment]
https://test.igov.org.ua/order/search?nID=22
должно найти заявку

**Comment by nazarenkod** [comment]
Работает.Закрываю
