### ISSUE TITLE
протестировать возможность повторного нажатия кнопки "замовити послугу"

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/i#748]
протестировать возможность повторного нажатия кнопки замовити послугу после первого.

алгоритм:
1. заходим на портал
2. выбираем субсидии в днепропетровске
3. заполняем
4. после замовити послугу пробуем отправить максимальное количество раз

процесс: Отримання субсидії на оплату житлово-комунальних послуг

пробовать можете везде: на альфе, бете и проде

только если прод будете терзать, маякните мне чтобы я позакрывал заявки

**Comment by VadimGulich** [comment]
Добрый день , проверил по разных браузерах , отправляется только один запрос после нажатия "Замовити"  , дублирования письа нет 

Дублирование возможно если после отправки заявки переотправлять тот же запрос

![image](https://cloud.githubusercontent.com/assets/12964120/9830522/f4d775ac-593a-11e5-90b5-ba7ee5b855e5.png)
