### ISSUE TITLE
На бэке (централа) в сервисе /getStatisticServiceCounts сливать статистику отдельных услуг по МРЕО для Киеав - в одну

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#750]
Всю статистику по:
https://igov.org.ua/service/726/statistics
https://igov.org.ua/service/727/statistics
https://igov.org.ua/service/728/statistics
https://igov.org.ua/service/729/statistics
https://igov.org.ua/service/730/statistics
https://igov.org.ua/service/731/statistics
https://igov.org.ua/service/732/statistics
https://igov.org.ua/service/733/statistics

сливать в:
https://igov.org.ua/service/159/statistics

т.е. рекурсивно внутри сервиса при nID_Service=159
выгребать данные по верхнему списку, и дополнять ими существующую мапу.

**Comment by bvv4ik** [comment]
Для теста:
https://test.igov.org.ua/service/159/statistics

**Comment by VadimGulich** [comment]
Не реализовано : 
https://drive.google.com/file/d/0Bw7BSYSLbe2MVURpakpTOXk2NU0/view?usp=sharing

**Comment by VadimGulich** [comment]
Задача не реализована 
![image](https://cloud.githubusercontent.com/assets/12964120/10330228/1e01af3c-6cd3-11e5-9e6b-001d6c324abd.png)

Ожидаемы результат: Суммирование статистики по Киеву

**Comment by LamronNu** [comment]
https://test.igov.org.ua/service/159/statistics
поправлено

**Comment by VadimGulich** [comment]
исправлено , спасибо
