### ISSUE TITLE
На дашборде починить кросброузерность при копировании в буфер обмена полей заявок

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#751]
Как минимум в FF каких-то версиях не работает.. и IE

**Comment by katebutenko** [comment]
FF 40, IE 11 и Сhrome - работает. 
Если можно, уточните, пожалуйста, в каких конкретно версиях каких браузеров не копируются филды. Все филды или определенные?

**Comment by bvv4ik** [comment]
@kurbpa Павел, прошу уточнить

**Comment by kurbpa** [comment]
@bvv4ik 
@katebutenko 
фф - 40.0.3 - дефект воспроизводится на всех полях  без исключения.

**Comment by katebutenko** [comment]
известное решение этой проблемы - сделать филды readonly вместо disabled+zeroclipboard. Но у такого решения есть опять же известный недостаток: http://stackoverflow.com/questions/8876928/allow-copy-paste-in-a-disabled-input-text-box-in-firefox-browsers

так что было бы неплохо попробоват с readonly и посмотреть, что получится.

**Comment by sergeygorban** [comment]
1. У чиновника есть возможность изменять поля заявки.

**Comment by GFalcon-UA** [comment]
Я понял. Поменять то они его могут, а потом перейти на другую заявку уже не получится.
Хорошо. Сейчас попытаюсь отлавливать такие поля на этапе рисования формы и конвертировать их в обычные текстовые с атрибутом Read-Only

**Comment by GFalcon-UA** [comment]
Прошу протестировать. Все disabled поля с выпадающим списком конвертируются в обычные текстовые поля с атрибутом read-only
Таким образом, в полях данные отображаются те, что заявником  были выбраны из списка, у чиновника нет доступа к их изменению и должно работать выделение текста и копирование его в буфер обмена.

**Comment by GFalcon-UA** [comment]
исправлена ошибка с принт-формами

**Comment by nazarenkod** [comment]
Работает на ФФ и Хроме. Проблема еще актуальна для ИЕ 11

**Comment by nazarenkod** [comment]
Чинить будете под ИЕ 11, или закрывать таску?

**Comment by GFalcon-UA** [comment]
В чем выражается проблема с ИЕ 11?
Я сейчас захожу, проверяю... Все поля, которые не активны - с них выделение текста и Ctrl-C работает, в буфер копирует.
Перехожу в ассайнутые таски - поля, которые должны быть доступными для редактирования - они, вроде, доступны, а которые не должны быть доступны - ыделение текста и Ctrl-C работает.
Может я что-то упустил?

**Comment by GFalcon-UA** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/13604023/15046406/2ccd05be-12e8-11e6-8bf8-769b3a33b966.png)

**Comment by nazarenkod** [comment]
Ctrl-C работает, но я имею в виду кнопку, в конце поля, для копирования в буфер.

**Comment by GFalcon-UA** [comment]
Я понял. Оставьте пока. Я посмотрю, что с ней можно сделать

**Comment by bvv4ik** [comment]
не актуальна после редизайна
