### ISSUE TITLE
Починить в дашборде комбобокс сортировки заявок

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#752]
т.к. сейчас сортирует только в одну сторону

**Comment by katebutenko** [comment]
Для тесту:

При зміні напрямку сортування задач (Від найновіших - від найдавніших) задачі у списку повинні сортуватися відповідно.

Для необроблених задач та задач в роботі сортування відбувається за createDate - датою створення. 
Для оброблених задач сортування за startDate - датою коли задачу було відправлено на розгляд (чи коли було почато розглядання?), бо для оброблених задач поля createDate немає взагалі.

**Comment by VadimGulich** [comment]
Работает , проверял на https://test.region.igov.org.ua:6948/tasks
