### ISSUE TITLE
На главном портале заменить одну из картинок (с названием КМДА) на другую

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#753]
https://test.kiev.igov.org.ua

т.е. должно быть с маленькой буквы
масштаб и размеры вырезать точно по тому что есть сейчас

![image](https://cloud.githubusercontent.com/assets/4208821/9821530/86aa53aa-58c3-11e5-9ac6-6aeffd0ce682.png)
![image](https://cloud.githubusercontent.com/assets/4208821/9821535/8b8794b4-58c3-11e5-94ec-05ff808226f6.png)

**Comment by smit-pb** [comment]
Реализовано
