### ISSUE TITLE
Починить шетдулер запуска эскалаций на бэке

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#754]
сейчас валит ошибку

org.wf.dp.dniprorada.util.run.Escalation

метод execute

в нем:

escalationService.runEscalationAll();

должен запускаться по тому расписанию что сейчас запрограммировано на этот джоб

**Comment by bvv4ik** [comment]
В логах можно глянуть, что шетдулер запускается
в 2 часа ночи

**Comment by olyv** [comment]
Можете подсказать где посмотреть логи?

**Comment by LamronNu** [comment]
https://github.com/e-government-ua/i/wiki/%D0%9D%D0%B0%D1%88%D0%B5-%D1%85%D0%BE%D0%B7%D1%8F%D0%B9%D1%81%D1%82%D0%B2%D0%BE, пункт *Логи на FTP (по Tomcat и NodeJS)*

смотреть можно через утилиту Far. при открытии её нажать alt+F4 --> NetBox, потом (для создания нового подключения) нажать Shift+F4--> прописать нужные реквизиты (сервер-логин-пароль) -->ok.
откроется окно со списком файлов-логов.
по идее, логи за текущий день будут без приставки с датой. откройте файл (лучше предварительно его выкачать с сервера, т.е. скопировать к себе на диск) -- и ищите нужную информацию...

**Comment by OlgaKotova** [comment]
@bvv4ik проверила логи по test.igov.org.ua, ошибки org.wf.dp.dniprorada.util.run.Escalation нет.
этого достаточно или где-то еще проверять нужно?

**Comment by Unlym** [comment]
2015-10-05_02:00:00.021 | INFO | org.wf.dp.dniprorada.util.run.Escalation- [execute]:In QuartzJob - executing JOB at Mon Oct 05 02:00:00 EEST 2015 by context.getTrigger().getName()=oCronTrigger_EveryNight_Deep


проверил логи и нашол что run.Escalation запускаеться на регионе и на централе в два часа ночи!!!
