### ISSUE TITLE
Разделить логирование на несколько отдельных файлов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#757]
1)
Самые важные:
- Controller.log - все что происходит в контроллерах
- Interceptor.log - все связано с перехватом запросов
- Shetduler.log - все связано с расписанием и запуском по нему

Второстепенные(можно уже после реализации остальных пунктов):
- Escalation.log - все связано с эскалацией
- BP_Listener.log - все связано с листенерами при отработке Бизнес-Процессов
- Notify_Mail.log - все связано уведомлением посредством почты
- Payment.log - все связано с платежами (в т.ч. мерчантами)
- Document.log - все связано с документами
- Service.log - все обработкой каталогов и позиций сервисов/услуг

2) xml-файл вынести в проект, а не так как сейчас, когда он в конфиге томкета... соответственно пути - относительные (чтоб на разных серверах одинаково работало)

3) дефолтный уровень логирования INFO

**Comment by OlgaTurenko** [comment]
готово

**Comment by nazarenkod** [comment]
Как проверить?

**Comment by bvv4ik** [comment]
реализовано
