### ISSUE TITLE
Опечатки: "квітанції" замість "квитанції"

### ISSUE THREAD

**Issue by svoloshyn** [e-government-ua/i#760]
https://github.com/e-government-ua/i/search?utf8=%E2%9C%93&q=%D0%BA%D0%B2%D1%96%D1%82%D0%B0%D0%BD%D1%86%D1%96%D1%97
45 code results.

Правильно "квитанції", а не "квітанції".

**Comment by uazure** [comment]
Fixed in test branch

**Comment by smit-pb** [comment]
И где это можно проверить ?
https://github.com/e-government-ua/i/search?utf8=%E2%9C%93&q=%D0%BA%D0%B2%D1%96%D1%82%D0%B0%D0%BD%D1%86%D1%96%D1%97

Тут поиск так и выдает не корректное написание.

**Comment by smit-pb** [comment]
Исправлено. Заменено на "квитанції"
