### ISSUE TITLE
реализовать возможность распечатывать документы поданные гражданином (включая принтформу) из папки «оброблені» - сейчас это возможно только из папки «в роботі»

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/i#765]

**Comment by bvv4ik** [comment]
для теста: зайти в дашбоард и там во вкладке "В работе" должна быть кнопка Роздрукувати

**Comment by nazarenkod** [comment]
Кнопка " Роздрукувати" отсутствует...Есть только ссылка на скачивание документа
![button](https://cloud.githubusercontent.com/assets/13256486/9990060/9829b738-6066-11e5-8712-108f91911135.jpg)

**Comment by bvv4ik** [comment]
кнопку-то отобразили, но проблема оказалась глубже, т.к. набор полей в истории (Оброблено) отличается существенно, потому могут не вписываться в прописанные поля шаблона...

вообщем тут придется корректировать ТЗ

**Comment by bvv4ik** [comment]
полостью откатили,
задача должна біть переписана, т.к. в Необроблених не должно біть кнопки
а в истории не всегда и не все поля есть и они не так віглядят
