### ISSUE TITLE
На главном портале поставить ограничения на загружаемые файлы: Графические

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#770]
1) Расширения:
    bmp .gif .jpg .jpeg .png  .tif
    Текстовые(тексто содержащие)
    . doc .docx .odt  .rtf .pdf
    и формат ".txt" - скорей всего - не желательно допускать для загрузки.
    Таблицы :
    .xls, .xlsx, .xlsm
    .ods .sxc
    WKS
    CSV
2) размер файла - максимум 10 мб

**Comment by bvv4ik** [comment]
ну как, после анализа таски - есть реальная возможность сделать это простым способом? или чето сложное варганить нужно?

**Comment by iRipVanWinkle** [comment]
У меня опыта работы с Node.js нету, поэтому затягивается. Я разобрался как работает загрузка файлов, но еще не разобрался как сделать ограничение. Если таск срочный то пусть кто-то другой сделает, если нет то я сделаю :)

**Comment by iRipVanWinkle** [comment]
Хотел разобраться как на стороне Node.js ограничения поставить, но оказалось что я в нем не на столько силен. 
Могу сделать на стороне Angular.js

**Comment by bvv4ik** [comment]
можно на стороне Ангуляр)

**Comment by GFalcon-UA** [comment]
Лимиты заданы в файле https://github.com/e-government-ua/i/blob/test/central-js/client/app/common/components/form/directives/file.js через переменные `nMaxFileSizeLimit` и `aAvailableFileExtensions`

Сначала проверяется размер файла и в случае его превышение выводится сообщение об ошибке 
> Розмір завантажуємого файлу ХХХ МБайт перевищує допустимий.Для завантаження дозволяються файли розміром не більше NNN МБайт.

После успешного прохождения проверки размера файла, проверяется его тип и в случае ошибки выводится сообщение:
> Не допустимий тип файлу. Для завантаження допускаються файли лише наступних типів: .....

При тестировании, прошу проверить корректность работы в браузерах как с поддержкой HTML-5, так и без него.

**Comment by sergeygorban** [comment]
При одновременной загрузке нескольких файлов при создании заявки сервис зависает и постоянно отображает загрузку файла
![screenshot_1](https://cloud.githubusercontent.com/assets/17043142/14440045/da10f060-0036-11e6-9152-09e04f0b831c.jpg)

**Comment by smoktii-igov** [comment]
Предлагаю расширить допустимые расширения файлов еще архивами .zip, .rar, .7z

**Comment by GFalcon-UA** [comment]
Подкорректировал сообщения об ошибках и расширения архивов.
Вроде поправил баг. Прошу протестировать еще раз.
Если при пакетной загрузке встретится файл, который не удовлетворяет условиям - он загружаться не будет.

Но встречный вопрос: может имеет смысл ограничить общий объем пакетной загрузки? А то ведь так можно залить сотни мелких файлов одновременно.

**Comment by GFalcon-UA** [comment]
Понял суть бага.
Я попробую блокировать кнопки, пока не завершится уже начатый процесс загрузки файла

**Comment by GFalcon-UA** [comment]
Сделал. От момента запуска загрузки файла и до завершения этого процесса, все загрузочные кнопки, которые есть на форме, - блокируются. Пока процесс загрузки файла не завершится, у пользователя теперь нет возможности запустить загрузку еще одного файла по другой кнопке. После завершения загрузки файла - кнопки разблокируются.
Тестировать можно на этой
https://test.igov.org.ua/service/1381/general/place/built-in/region/1/city/28

**Comment by sergeygorban** [comment]
Доработка реализована согласно требованиям, загрузка .zip, .rar, .7z реализована. При загрузке файлов, кнопки следующей загрузки блокируются и становятся доступными после предыдущей загрузки
