### ISSUE TITLE
На дашборде увеличить время сессии (до 1800 секунд)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#771]

**Comment by nazarenkod** [comment]
Не реализовано.После 15 минут сессия уже была закрыта

**Comment by VadimGulich** [comment]
сессия не обрывается

**Comment by nazarenkod** [comment]
сессия закрылась после 15 минут

**Comment by bvv4ik** [comment]
поправлено, можно пробовать повторно

**Comment by nazarenkod** [comment]
@bvv4ik после 20 минут сообщение "сессия будет закрыта через 30 сек."

**Comment by nazarenkod** [comment]
на данный момент по истечению 30 минут сессия все еще открыта

**Comment by bvv4ik** [comment]
ну т.е. срок жизни сессии таки продлился?
срок жизни сессии продливается на такой-же срок, при появлении активности

**Comment by nazarenkod** [comment]
сессия живет больше 30 минут без какой либо активности

**Comment by bvv4ik** [comment]
а можно уточнить - сколько именно она живет?
т.к. там не принципиально, если будет отклонение даже в два раза..
принципиально лишь чтоб она жила дольше чем 2 минуты (как сейчас)

**Comment by nazarenkod** [comment]
час живет точно...может даже полтора...сейчас засёк, позже смогу сказать точнее

**Comment by nazarenkod** [comment]
@bvv4ik полтора часа прожила сессия, за тем появилось сообщение "через 1200 сек сессия закроется"

**Comment by VadimGulich** [comment]
сессия живет дольше двох минут , закрываю
