### ISSUE TITLE
На бэке (wf-base) реализовать новый тип поля Активити "HTML"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#772]
для поддержки HTML текстов

**Comment by bvv4ik** [comment]
@kurbpa Павел, нужно или добавить новый тестовый БП или взять существующий и добавить туда такое поле (ддля проверки)... потом дописать сюда в комменте - что за название

**Comment by kurbpa** [comment]
@bvv4ik 
создан тестовый процесс - _test_type_HTML
ссылка на услугу на альфе - https://test.igov.org.ua/service/757/general

в дашборде на альфе для обработки заявок по этому процессу можно использовать учетку  tester/tester

**Comment by smit-pb** [comment]
![image](https://cloud.githubusercontent.com/assets/12965717/9990524/c52cd95a-606a-11e5-9b49-65987ed4a03f.png)

Это считать как корректную реализацию задачи ? или как Фэил ?

**Comment by bvv4ik** [comment]
произведен полный откат,
т.к. данный функционал реализован в рамках существующего типа label
