### ISSUE TITLE
На главном портале и на дашборде реализовать поддержку нового типа поля Активити "HTML"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#773]
по нему выводить блок HTML (а там уже могут быть и ссылки и разное форматирование... вплоть до таблиц)

**Comment by uazure** [comment]
По описанию не вполне ясно, с какого бока подступиться к задаче. Есть примеры других типов полей Активити и их поддержки в портале\дашборде?

**Comment by bvv4ik** [comment]
@uazure

абсолютно все поля активити (типы) прописаны на фронте (и централа и дашборда)
под каждый тип свое поведение..
например тип Label - очень похож на HTML, т.е. выводит значение в нередактируемом виде
тип String - обычній инпут (за исключением кейсов нередактируемости)
тип markers вообще скрывается
тип date - отрисовывает календарик
тип enum - рисует комбобокс 
и т.д.

**Comment by bvv4ik** [comment]
произведен полный откат,
т.к. данный функционал реализован в рамках существующего типа label
