### ISSUE TITLE
На главном портале добавить кеширование поисковых запросов к каталогу сервисов

### ISSUE THREAD

**Issue by uazure** [e-government-ua/i#774]
ТТЛ кеширования - 5 минут.

**Comment by uazure** [comment]
Нужно тестирование корректной работы кеширования при условии проведения манипуляций (удаление, изменение) с каталогом сервисов.

**Comment by nazarenkod** [comment]
Как можно проверить задачу?

**Comment by VadimGulich** [comment]
https://github.com/e-government-ua/i/issues/810

**Comment by bvv4ik** [comment]
на главном портале, после авторизации под тестовым логином появятся кнопки редактирования, добавления и удаления категорий, подкатегорий и услуг... 
функционал работает пока только частично, потому тестировать его можно будет только по завершению каждой из этих тасок:
https://github.com/e-government-ua/i/issues/239
https://github.com/e-government-ua/i/issues/240
https://github.com/e-government-ua/i/issues/241

**Comment by bvv4ik** [comment]
Сценарий такой:

Отредактировать какую то услугу
Сразу после этого открыл портал и попробовать найти её. Удостоверится что изменения подхватились.

**Comment by nazarenkod** [comment]
@bvv4ik Протестировал все, кроме задачи #241(т.к. кнопки для категории скрыты)
откроете кнопки для теста, или можно закрывать?

**Comment by nazarenkod** [comment]
Протестировано
