### ISSUE TITLE
На главном дашборде скрывать для Киева два элемента расширенного фильтра "Область и Город"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#776]
https://test.kiev.igov.org.ua

а потом сделать видимым, для остальных т.к. сейчас это было временно скрыто

**Comment by nazarenkod** [comment]
На киевском портале элементы скрыты
![default](https://cloud.githubusercontent.com/assets/13256486/9982074/1b946666-5fd8-11e5-8b86-85713aa89bc3.jpg)

"а потом сделать видимым, для остальных т.к. сейчас это было временно скрыто"
Я так понимаю  имеется в виду видимость этих элементов на главном портале?

**Comment by VadimGulich** [comment]
На главном портале отображать 
для Киева скрыть 

Реализовано /протестировано
