### ISSUE TITLE
На бэке (wf-central) доработать сервис setMessage и сущность HistoryEvent_Service, для поддержки віставленной оценки

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#777]
- [x] 1) добавить новый опциональный параметр sID_Rate (строка) в сервисе setMessage 
принимающий "ИД рейтинга"
- [x] 2) добавить новый опциональный параметр nID_Protected (номер) в сервисе setMessage 
принимающий "ИД заявки"
- [x] 3) Добавить новое опциональное поле nRate (число) в сущности HistoryEvent_Service 
хранящее число-рейтинга
- [x] 4) При вызове сервиса setMessage  и заданных обоих параметрах п.1. и п.2 - обновлять запись в  сущности HistoryEvent_Service, в т.ч. поле п.3. (находить запись по ИД п.2)
(при этом приходящее значение из параметра sID_Rate должно содержать число от 1 до 5)
- [x] 5) Доработать класс Abstract_MailTaskCustom чтоб по тегу [sURL_ServiceMessage] добавлялся еще и параметр [nID_Protected], в УРЛ сервиса
- [x] 6) Доработать сервис getStatisticServiceCounts, чтоб выводилось еще и среднее число оценки по nRate (с дробными - 1 знак после запятой) - в параметре nRate
- [x] 7) Дополнить доку по АПИ на Вики

**Comment by bvv4ik** [comment]
как там успехи с последним пунктом?)

**Comment by bvv4ik** [comment]
включил выдачу рейтинга (может конечно там и ошибка, но есть шанс)))
закомитил...

прошу обновить доку

**Comment by bvv4ik** [comment]
Для теста: результатом будет https://github.com/e-government-ua/i/issues/778

**Comment by LamronNu** [comment]
)
дока уже обновлена: https://github.com/e-government-ua/i/blob/314ec75ad65f6c64c8fd81c37e9fd03102e6fbbe/docs/specification.md#12_workWithMessages, пункт setMessage

**Comment by nazarenkod** [comment]
Не работает.
ответ: 405 Method Not Allowed

**Comment by LamronNu** [comment]
>ответ: 405 Method Not Allowed

насколько я помню, этот метод (setMessage) пост, а не гет.. т.е. нужно отправлять пост-запросы

**Comment by nazarenkod** [comment]
пос запрос отвечает тем же самым

**Comment by VadimGulich** [comment]
Работает согласно описанию !
