### ISSUE TITLE
На главном портале ври выводе статистики так-же отображать еще и параметр nRate, с надписью "Средняя оценка"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#778]

**Comment by nazarenkod** [comment]
Проверкой будет наличие колонки "Средняя оценка" или значения в нем?

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/10241113/3fc3d260-68ed-11e5-93cf-643ace928a94.png)

Нет надписи средняя оценка

**Comment by VadimGulich** [comment]
Задача не реализована, нуждается в реализации 
на данный момент нет , функционала для тестирования

**Comment by LamronNu** [comment]
@VadimGulich 
проверкой задачи является наличие числа в колонке "Средняя оценка". Какого именно числа -- неважно. Сейчас везде ноль, т.к. по заявкам/услугам "оценивание" еще не запущено (это новое поле, его проставление реализовано на беке в задаче #777, на фронте же еще не сделано, только в планах).
Вот скрин, сделанный только что:
![image](https://cloud.githubusercontent.com/assets/8156670/10344343/55d70c92-6d2b-11e5-9fe6-7b0b43d908f5.png)

**Comment by VadimGulich** [comment]
Так понятно , просто проводилось тестирование согласно описанию задачи ))
и ожидалось поле с надписью :  "Средняя оценка"

**Comment by LamronNu** [comment]
Аа... что-то не обратила внимания) да, там сделан рейтинг, т.е. это как бы "средняя оценка", но в процентах.
