### ISSUE TITLE
На бэке (wf-base) доработать сервис отдачи свободных слотов электронного расписания

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#779]
Выводить доступные слоты не на ближашие два месяца (как сейчас - 60 дней) а именно 60 ближайших дней, с которых есть хоть по одному свободному слоту

т.е. дефолтом должен быть проставлен параметр nFreeDays=60
а другой дефолт по числу дней должен быть увеличен до полугода

Описание АПИ:
https://github.com/e-government-ua/i/blob/test/docs/specification.md#18-Работа-со-слотами-потока

**Comment by nazarenkod** [comment]
Как можно проверить?

**Comment by bvv4ik** [comment]
зайти в услугу с очередью, например по ДМС и убедиться что там 60 дней доступно, не смотря на то что не с текущей даты... 

при этом сгенерив их до конца года
как генерить описал тут:
https://github.com/e-government-ua/i/issues/720

**Comment by nazarenkod** [comment]
Не ясно, помогите разобраться.
Выбрал услугу с очередью _test_queue_cancel.
В ней сгенерены слоты
Использую доку https://github.com/e-government-ua/i/blob/test/docs/specification.md#18_workWithFlowSlot

1.Запрос гет на получение сгенереных слотов
https://test.igov.org.ua/wf/service/flow/getFlowSlots_ServiceData?nID_ServiceData=12
https://test.igov.org.ua/wf/service/flow/getFlowSlots_ServiceData?sID_BP=_test_queue_cancel
возвращает 
{
aDay: [0]
}
Вопрос:разве он не должен возвращать все сгенерированные дни? 
Пример запроса из доки 
https://test.region.igov.org.ua/wf/service/flow/getSheduleFlowIncludes?sID_BP=_test_queue_cancel
возвращает "500 Internal Server Error".

2.пост метод генерит слоты на заданный интервал, но это нигде не отображается, не в услугу, не через метод гет в первом пункте.
пример запроса http://test.igov.org.ua/wf/service/flow/buildFlowSlots?nID_Flow_ServiceData=12&sDateStart=2015-09-25 00:00:00.000&sDateStop=2015-11-28 00:00:00.000

подскажите где я ошибаюсь

**Comment by VadimGulich** [comment]
есть, все ок - протестировано
