### ISSUE TITLE
На бэке (wf-base) реализовать сервис унифицированного поиска заявки 

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#780]
- [x] 1) По точной аналогии с сервисом:
https://github.com/e-government-ua/i/blob/test/docs/specification.md#32_getTasksByOrder
только искать не по точному номеру, а по фразе (стринговый параметр sFind),

- [x] 2) присутствие которой хоть в одном из полей таски - будет означать, что нужно возвратить ее ИД в массиве. т.е. в массив должны попасть все ИД которые подпадут под этот критерий.

- [x] 3) Назвать сервис: getTasksByText

Пример: https://test.region.igov.org.ua/wf-region/service/rest/tasks/getTasksByText?sFind=Белявцев

P.S.
После обсуждения задачи были добавлены два опциональных параметра:
- sLogin 
- bAssigned 

Назначение параметров описано в документации метода https://github.com/e-government-ua/i/blob/test/docs/specification.md#36_getTasksByText

**Comment by ASkosyr** [comment]
Дата поставки - понедельник 21 сентября

**Comment by ASkosyr** [comment]
Пример вызова сервиса

https://test.region.igov.org.ua/wf/service/rest/tasks/getTasksByText?sFind=%D0%94%D0%A3%D0%91%D0%86%D0%9B%D0%95%D0%A2

**Comment by ASkosyr** [comment]
Документация по методу
https://github.com/e-government-ua/i/blob/test/docs/specification.md#36_getTasksByText

**Comment by VadimGulich** [comment]
протестировано , метод работает согласно описанию
