### ISSUE TITLE
Реализовать сервис аплоада контента на сервер, с прикреплением его в виде атачмента к таске

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#781]
По аналогии с сервисом: /file/upload_file_as_attachment
https://github.com/e-government-ua/i/blob/test/docs/specification.md#14-Аплоадupload-и-прикрепление-файла-в-виде-атачмента-к-таске-activiti

только вместо параметра file - должен быть стринговый параметр sData (в пост-е/теле)
и вспомогательный параметр sContentType КонтентТайпа (по дефолту это должен быть HTML)

Работа и ответ сервиса должны быть точно такими-же как и в примере выше.

**Comment by bvv4ik** [comment]
Для теста: вот дока https://github.com/e-government-ua/i/blob/test/docs/specification.md#34_upload_content_as_attach

**Comment by smit-pb** [comment]
Работает.
