### ISSUE TITLE
На дашборде, при открытии таски искать в ней поля с названиями sBody* и по каждому найденому подтягивать паттерн по пути в названии поля, сохраняя все в памяти и точно так-же формируя список принтформ в комбобоксе и используя выбранные шаблоны для вывода на печать

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#782]
через сервис /rest/getPatternFile
где в параметр sPathFile как раз и передавать параметр из атрибута name, поля таски
(сам метод уже испорлльзуется на дашборде)

**Comment by nazarenkod** [comment]
Как можно проверить данную задачу?

**Comment by hordesalik** [comment]
1. Создать таску на субсидию в центральном сайте для граждан
2. Зайти в дашбоард и взять ее в обработку
3. Нажать "распечатать". в консоли проследить, что при первой выбранного типа на сервер отправляется запрос на получение шаблона. При последующих распечатках этого же типа запрос уходить не должен

**Comment by nazarenkod** [comment]
Если речь идет о этом запросе(подчеркнуто зеленым), то повторно вызов метода не происходит.
![getpattern](https://cloud.githubusercontent.com/assets/13256486/9982017/4f8c6d9e-5fd6-11e5-9f53-358cd04b2c62.png)

**Comment by hordesalik** [comment]
Повторно и не должен. Результат запроса кешируется... для каждого варианта из дропдауна должна проходить одна загрузка шаблона попапа

**Comment by nazarenkod** [comment]
значит закрываю:)
