### ISSUE TITLE
На дашборде реализовать унифицированное поле поиска заявки

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#783]
Практически идентичная задача удже реализовывалась (поиск в дашборде по ИД заявки, а эта почти то-же самое... т.е.80% просто скопировать, и сервис заменить)

- [ ] 1) Добавить на уровне поля поиска по ИД заявки - унифицированное поле поиска
При вводе текста в котором (и нажатии энтер) - нужно вызывать сервис, написанный по задаче: https://github.com/e-government-ua/i/issues/780

- [ ] 2) После получения массива ИД тасок:
2.1) выбрать в списке первую из них(именно выбрать курсором чтоб справа отобразились поля заявки)

- [ ] 2.2) Подсвечивать справа от поле ввода текста: Порядковый номер найденного / число найденных тасок (мелким шрифтом)
Например: "2/5" (как в обозревателе Хром)

- [ ] 2.3) После последующих нажатий энтер не производить повторный запрос на сервер а просто пользоваться ответом полученным при первом запросе (если текст запроса не менялся)

- [ ] 2.4) Если найденных заявок больше одной, то после повторного нажания энтер - переходить (выбирать строку) со следующей из них, а после последней переключаться напервую и т.д.

П.С.: если сервис не будет еще готов, то взять сервис-образец по поиску через ИД и прост озамокать там ИД, чтоб хоть что-то возвращало через более-менее полный механизм...
а потом, как сервис завершат - просто подменим название и уберем мок запроса (сориентируем его на неальное поле поиска(текстовое))

**Comment by bvv4ik** [comment]
для теста: найдя выбирает только одно задание, пока-что

**Comment by VadimGulich** [comment]
протестировано
