### ISSUE TITLE
На дашборде реализовать фильтр-групп статусов (комбобокс)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#784]
- [x] 1) в списке должны быть варианты (сам справочник хранить в виде захардкоденного отдельного обїекта-переменной в коде):
"Все" - id=all
"Старт" - id=usertask1
"Обработка" - id=usertask2
(дефолтом должно быть всегда "Все")

- [x] 2) При выборе "Все" - отображаются просто все задачи вкладки

- [x] 3) При выборе другого пункта, кроме "Все" - отображаются только те задачи, где ИД юзертаски заканчивается на id этого пункта комбобокса

- [x] 4) Запоминать выбранность комбобокса для каждой вкладки

**Comment by uazure** [comment]
Сделал

**Comment by uazure** [comment]
Что тестировать: На вкладках "В роботі", "Необроблені" появился комбо бокс для выбора фильтов тасок. По умолчанию показываются все таски, но если для вкладки "В работе" выбрать какой-то фильтр, то он запомнится для вкладки "В работе". Тоже самое с необработанными. Также нужно проверить, корректно ли работает отображение элементов во вкладке тикеты и оброблени

**Comment by smit-pb** [comment]
![image](https://cloud.githubusercontent.com/assets/12965717/10359342/59a70410-6da0-11e5-8889-15829c780067.png)
Верстку бы - поправить ;) - а то прям глаза режет корявость.

В остальном - работает. 
(Пожалуйста заинтересованные разработчики, поправьте верстку или создайте таску на доводку верстки ;) )
