### ISSUE TITLE
На дашборде реализовать фильтр по БП и опциональный по Этапам

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#785]
- [ ] 1) Фильтр по БП реализовать аналогии с:
https://github.com/e-government-ua/i/issues/784
только в комбобоксе отображать список доступных сотруднику БП (такой компонент уже реализован в некоторых местах дашборда, в частности, в разделе "Отчеты")

соответственно - отображать при выбранном БП только задачи, у которых такой-же ИД БП

Ну а если выбран пункт "Все" то отображать все

- [ ] 2) Фильтр по этапам-же ак-же по аналогии с https://github.com/e-government-ua/i/issues/784
только в комбобоксе отображать список тех юзертасок, которые есть в указанном выбранном БП (отображать их название)

ВАЖНО: если фильтр БП (п.1.) не выбран (выбрано "Все") то этот вспомогательный фильтр не отображать, а вместо него отображать фильтр "групп-этапов" по задаче: https://github.com/e-government-ua/i/issues/784 (и наоборот!
- при этом сбрасывая его так-же на "Все", если БП фильтр выбирается "Все"
- при этом, когда в фильтре по БП выбирается какой-то БП, то переформировывать этот список Юзертасок (т.к. в каждом БП они разные)

При этом так-же, если выбран пункт "Все" то отображать все

**Comment by uazure** [comment]
Сделал

**Comment by OlgaKotova** [comment]
Проверка дала следующие результаты:
1. Фильтр реализован для 2-х вкладок - "В работе" и "Не обработанные", для "Тикетов" и "Обработанных", соответственно, фильтра нет.

2. Работа фильтра по статусу не реализована, т.е., при выборе фильтра БП, затем - установка фильтра по статусу, таски не фильтруются.
![2015-10-26_1522](https://cloud.githubusercontent.com/assets/5013971/10730170/0df595b2-7bf7-11e5-97af-c9f42ea178de.png)

3. Я так поняла, что при установке фильтров БП и по статусу, то фильтр по группе статусов не должен отображаться, если да, то этого не происходит. На скрине видно, что он присутствует не зависимо от того, какие фильтры выставлены.

**Comment by uazure** [comment]
> Работа фильтра по статусу не реализована, т.е., при выборе фильтра БП, затем - установка фильтра по статусу, таски не фильтруются.
Не фильтруются, потому что пока нет тасков с разными статусами. Т.е. у всех таксок одинаковый статус, поэтому что вариант "Все", что вариант "надання адміністративної послуги" как на скриншоте - идентичны по результату. @bvv4ik можно как-нибудь сделать тасок с разными статусами?

2. Из описания задачи в этом тикете ты поняла правильно. В процессе работы над задачей мы с @bvv4ik обсудили эту фичу и пришли к решению отказаться от такого подхода, потому что возможны всякие неочевидные эффекты при таком подходе. Поэтому каждый фильтр работает независимо и делает то, что и должен делать.
Плюс я добавил кнопку для сброса всех фильтров.

@OlgaKotova спасибо тебе за внимательное тестирование. Жаль что с нашей стороны мы ничего для тестирования не подготовили :( Постараюсь перед тем как ставить флаг "тест" убедиться в том, что есть достаточно всего для тестирования. Извини за невнимательность.
