### ISSUE TITLE
На дашборде, авто-аплоадить принтформу в виде атача

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#786]
- [ ] 1) выполнять это действие при нажатии сабмита на форме
- [ ] 2) выполнять для всех полей, которые имеют одновременно:
- тип "file"
- id, начинающееся с "PrintForm_"
- [ ] 3) в название такого поля через ";" третим элементом - должен быть путь к паттерну (который обычно выбираетя в комбобоксе, для "Роздрукувати", а в данном случае будет определен жестко, например: "pattern/print/Kherson_uorpg_kv.html")
ВАЖНО: если его там нет, то как и для принтформы - формировать стандартную принтформу
- [ ] 4) В качестве контента, апроадегощегося, должен быть сформированный HTML принтформі, с заполненніми поля (точно так-же как он формируется для ""Роздрукувати", только не показівать его в диалоге а сразу аплоадить в качестве контента)
- [ ] 5) Аплоадить контент с помощью сервиса, написанного по таске: https://github.com/e-government-ua/i/issues/781

**Comment by taaraora** [comment]
#781 done. API was documented - https://github.com/e-government-ua/i/blob/test/docs/specification.md#34_upload_content_as_attach

**Comment by hordesalik** [comment]
@taaraora не понятно как отправлять аттач. в документации описаны только параметры, но нет названия поля, куда файл отправлять
прикрепление текстового файла в виде атачмента к таске Activiti

nTaskId - ИД-номер таски
sContentType - MIME тип отправляемого файла (опциоанльно) (значение по умолчанию = "text/html")
sDescription - описание
sFileName - имя отправляемого файла

**Comment by taaraora** [comment]
@hordesalik Файл находится в теле POST запроса.

**Comment by hordesalik** [comment]
В какой задаче можно увидеть поле с "PrintForm_" ?

**Comment by hordesalik** [comment]
@taaraora можно сделать, чтобы это был не файл, а контент в параметре пост-запроса? т.к. изначально это не файл, а просто строка...

**Comment by taaraora** [comment]
@hordesalik какой предполагается максимальный размер файла? URI lengths имеет серьёзные ограничения в длинне, файлы даже plain text обычно через тело POST передают.

**Comment by hordesalik** [comment]
@taaraora в боди поста можно передать как и в гет разные параметры, т.е. url-encoded массив. ладно. я попробую все боди передать только html

**Comment by hordesalik** [comment]
@taaraora всегда возвращает ошибку
{"code":"SYSTEM_ERR","message":"Cannot find task with id 5310162"}

она приходит при любой ошибке? или только если нет этой таски? по тому же ИД загружается форма таски

**Comment by taaraora** [comment]
@hordesalik Текст ошибки зависит от ошибки, тоесть такая таска точно есть? Проверяете в Activiti Explorer?

**Comment by taaraora** [comment]
Дабавьте меня в скайп, и можно будет завтра созвониться и посмотреть. Мой скайп совпадает с логином github.

**Comment by bvv4ik** [comment]
для теста нужно создать тестовый БП под данную таску (например "_test_autosend_printform")

там должно быть поле типа "file" с id начинающееся с фразы "PrintForm_" - в юзертаске (не на стартовой форме), и в ее названии должно быть что-то типа "File label;File description;pattern/print/Kherson_uorpg_kv.html"

и за юзертаской должна быть системтаска с отсылкой этого файла на почту гражданину...

**Comment by hordesalik** [comment]
После теста в коде удалить кусок со строки:
client/components/task/task.service.js:218

**Comment by bvv4ik** [comment]
проверять на тестовой услуге _test_autosend_printform

**Comment by NizhnikAlex** [comment]
Просмотрел тестовую услугу. Замечания:
1. 
![1](https://cloud.githubusercontent.com/assets/13959354/10186669/79bba152-675b-11e5-9b29-b713f05acec9.PNG)
Кнопка file label "Завантажити файл". При нажатии открывает окно выбора файла для загрузки. Но файла формы в этом выборе нет. Лишний функционал? Может ее скрыть с дашборда чиновника?
2. Второе письмо заявителю из этого же БП. В нем нет прикрепления принтформы, но она прикрепляется и замещает в письме собой файл, ккоторый прикрепляет чиновник.

**Comment by NizhnikAlex** [comment]
Тест 2:
![1](https://cloud.githubusercontent.com/assets/13959354/10249580/c6cbbfac-692e-11e5-9f0c-a75ee16f0d8c.PNG)
Туда где надо крепить опис я добавил файл visualelementsmanifest.xml
Там где File label , открыл окно и попробовал добавить файл chrome.exe. Добавилось

В письме пришло: файл chrome.exe и файл user form.html (печатная форма).
Файл описи visualelementsmanifest.xml, который я прикреплял, и который должен был быть в письме - не пришел.

**Comment by smit-pb** [comment]
А фикс будет ? - или так и надо , чтобы только дефолтная форма приходила ?

**Comment by Koffeek** [comment]
@smit-pb а попробуйте сохранить на комп, а не открывать из почты

**Comment by bvv4ik** [comment]
Убрано отображение кнопки Загрузить файл, в отношении авто-отсылаемой принтформы
деплоится...

**Comment by NizhnikAlex** [comment]
Не убралось
![filelabel](https://cloud.githubusercontent.com/assets/13959354/10685762/7ceb3ba4-7966-11e5-9993-cac4dd602f95.PNG)

**Comment by bvv4ik** [comment]
а сейчас?

**Comment by VadimGulich** [comment]
исправлено
