### ISSUE TITLE
На главном портале, в диалоге отчета гражданину об успешной отправке его заполненной формы (после сабмита) - поправить текст и добавить электронку

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#787]
после подачи заявки гражданином выходит окно "Шановний Username...", а необходимо чтобы было "Шановний(-а) Username...".

Там же “Результати будуть спрямовані на Ваш… “ добавить слово е-мейл.

**Comment by nazarenkod** [comment]
Работает согласно описанию.
![itworks](https://cloud.githubusercontent.com/assets/13256486/9981903/227cb06e-5fd3-11e5-815a-786d772713b5.jpg)
