### ISSUE TITLE
На бэке (wf-base) доработать обработку тэга [paymentButton_LiqPay] так, чтоб он поддерживал множественные кнопки оплаты LiqPay в рамках одного письма

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#789]
- [x] 1) в классе Abstract_MailTaskCustom по мимо поиска тєга "[paymentButton_LiqPay]" искать так-же и все по маске "[paymentButton_LiqPay_*]", и каждый отрабатывать индивидуально
- [x] 2) Найдя, например "[paymentButton_LiqPay_2]" нужно будет и все остальные параметры по него:
"sID_Merchant_2"
"sSum_2"
"sID_Currency_2"
"sDescription_2"
(т.е. приписывать к их названиям такой-же индекс справа)
и только если какой-то из них не найден - брать по стандартному его названию:
"sID_Merchant"
"sSum"
"sID_Currency"
"sDescription"
- [x] 3) ХТМЛ-кнопки подставлять вместо каждого тэга - свой

**Comment by OlgaTurenko** [comment]
Для тестирования можно использовать услугу: https://test.igov.org.ua/service/674/general

**Comment by smit-pb** [comment]
![image](https://cloud.githubusercontent.com/assets/12965717/9991887/bdabad6c-6076-11e5-8832-24544577eb2e.png)
Можно считать что реализовано ? 
Каждая кнопка ведет на уникальный линк.
![image](https://cloud.githubusercontent.com/assets/12965717/9991903/e4a19f1c-6076-11e5-827c-808533d75ad2.png)

**Comment by VadimGulich** [comment]
да , закрываем
