### ISSUE TITLE
На главном портале добавить в объект markers новый валидатор по КВЕД

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#790]
(в под-объект validate)
id = KVED //вид экономической деятельности по КВЕД.
Логика: две цифры точка две цифры (первые две цифры не могут быть 04, 34, 40, 44, 48, 54, 57, 67, 76, 83, 89)
Сообщение: Такого КВЕД не існує - (ви не можете вписувати літери)
Поля: kved

**Comment by bvv4ik** [comment]
@GrekD Дарья - прошу назвать для тестера - БП, где можн опроверить результат

**Comment by GrekD** [comment]
ссылки на процессы на альфе, в которых есть такое поле:
https://test.igov.org.ua/service/745/general
https://test.igov.org.ua/service/5/general
поле *Вид діяльності згідно з КВЕД:

**Comment by smit-pb** [comment]
Тестировал на - https://test.igov.org.ua/service/745/general
Я использовал 04.34 - и КВЕД прошел вот номер - №48400016

И на - https://test.igov.org.ua/service/5/general
тоже, не реагирует на не правильные кода и буквы - заявка №48400744
![image](https://cloud.githubusercontent.com/assets/12965717/10011583/5baffd7c-6105-11e5-8861-1c4fd0373179.png)

**Comment by smit-pb** [comment]
Все еще актуально!!!
Номер заявки -> №53552134
КВЕД -> TEST.45

**Comment by bvv4ik** [comment]
еще пока не известно кто, но перетер код этой доработки!
Пришлось востанавливать из истории

сейчас продеплоится и можно будет проверять!

**Comment by bvv4ik** [comment]
как выяснилось - оно просто небыло перенесено после рефакторинга в новую сущность
сейчас вроде норм:
![image](https://cloud.githubusercontent.com/assets/4208821/10264128/436c6542-6a0c-11e5-82ca-415baedacfe7.png)

**Comment by GrekD** [comment]
не дает даже цифры вносить. Что бы не вносила - выдает эту ошибку
я пробовала начать со всеми цифрами от 0 до 9, с точкой и без - ошибку на любой символ выдает
![2015-10-03_205843](https://cloud.githubusercontent.com/assets/10836093/10264354/fc44ea6c-6a11-11e5-89fb-0b5bfe3f6303.png)

**Comment by nazarenkod** [comment]
@GrekD  Пропускает символы "!"№;%..." так же хотелось бы видеть при вводе букв/символов-"и не можете вписувати літери/символи",а при вводе невалидного КВЕД "Такого КВЕД не існує"

**Comment by smit-pb** [comment]
Квед - в принципе валидируется нормально. Но поле ввода идентификационного кода - не корректно валидируется.
![image](https://cloud.githubusercontent.com/assets/12965717/10571046/b439bade-7643-11e5-88cf-bd90e75a25c6.png)

![image](https://cloud.githubusercontent.com/assets/12965717/10571056/c65ae7f6-7643-11e5-9e55-2b2ac7dd693b.png)


Задачку по КВЕД - можно закрывать, Но Менеджерам необходимо создать задачку на доработку - валидация поля ввода ИНН.
