### ISSUE TITLE
На бэке (wf-base), в сущности Flow_ServiceData доработать учет департамента, как часть составного ключа

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#791]
1) Скопировать сущность SubjectOrganDepartment из wf-central в wf-base (с классами и csv)
ВАЖНО: в wf-base нужно:
1.1) информацию об этой новой сущности(ее создании в базе) прописывать в 
/changes/base_2015.xml
(при этом, чтоб не было конфликта в wf-central(т.к. там эта сущность уже и так создана) - нужно changeSet по созданию сущности проставить failOnError="false")
1.2) подгрузку данных делать в:
/load-data-local.xml
/data/SubjectOrganDepartment.csv
(т.к. в централе своя таблица с данными)
1.3) загрузить такие данные в  в /data/SubjectOrganDepartment.csv:
nID;sName;sGroup_Activiti;nID_SubjectOrgan
1;Test Department (_test_dnepr_mvd-1_auto);Test Group Activity;2
2;МРЕО,Киев,Петропавлівська Борщагівка, вул.Кільцева 4 (dnepr_mreo_1);demomreo;2
3;МРЕО,Киев,вул. Туполєва, 19 (kiev_mreo1_1);demomreo;2
4;МРЕО,Киев,вул. Велика кільцева дорога. 22-А (kiev_mreo2_1);demomreo;2
5;МРЕО,Киев,вул. Братиславська, 52 (kiev_mreо3_1);demomreo;2
6;МРЕО,Киев,вул. Столичне шосе, 104 (kiev_mreo4_1);demomreo;2
7;МРЕО,Киев,вул. Павла Усенка, 8 (kiev_mreo5_1);demomreo;2
8;МРЕО,Киев,вул. Новокостянтинівська, 8 (kiev_mreo6_1);demomreo;2
9;МРЕО,Киев,пров. Балтійський, 20 (kiev_mreo7_1);demomreo;2
10;МРЕО,Днепр (dnepr_mreo_1);demomreo;2
11;АВИР, Днепр, Поля 1 (dnepr_dms_passport);demoavir;2

2) Во всех сервисах работы с сущностью Flow_ServiceData и FlowProperty - добавить вспомогательный(опциональный) параметр nID_SubjectOrganDepartment, передавай который в паре с существующим sID_BP - будет выбираться не первая встретившаяся строка из сущности FlowProperty а именно та, в которой поле nID_SubjectOrganDepartment соответствует этому значению.
Такие сервисы, например:
/getFlowSlots_ServiceData
/setFlowSlot_ServiceData
/buildFlowSlots
/clearFlowSlots
/getSheduleFlowIncludes
/getSheduleFlowExcludes
/setSheduleFlowInclude
/setSheduleFlowExclude
/removeSheduleFlowInclude
/removeSheduleFlowExclude
(может еще что-то пропустил)

3) Добавить ключ в сущности на уникальность в сущности "Flow_ServiceData" пары
"nID_SubjectOrganDepartment" и "sID_BP"

4) Обновить АПИ на нашей Вики

**Comment by brunneng** [comment]
Методы в которых был добавлен параметр nID_SubjectOrganDepartment:
все внутри /flow/
buildFlowSlots
clearFlowSlots
getSheduleFlowIncludes
getSheduleFlowExcludes
setSheduleFlowInclude
setSheduleFlowExclude
removeSheduleFlowInclude

Для теста можете брать любой метод и проверять что параметр учитывается. Внимание: сейчас, если задан параметр sID_BP то также должен быть задан параметр nID_SubjectOrganDepartment - иначе упадет.

**Comment by VadimGulich** [comment]
Проверялось в рамках другой задачи
