### ISSUE TITLE
На дашборде при вытягивани для формы печати пути к патерну, из значения поля - брать название для каждого элемента комбобокса

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#792]
т.е. если сейчас в этом поле name:
name="[pattern/print/subsidies.html]"
value="<html.......и т.д."
- соответственно в комбобоксе отображается пункт с названием "[pattern/print/subsidies.html]"

а теперь нужно, чтоб когда в значении поля (value) будет текст длиной больше 0-ля символов (после трима), и при этом меньше 100 символов, то брать его в качестве названия.

Примеры:

name="[pattern/print/subsidies.html]"
value="Первая печатная форма"
- в комбобоксе должно отобразиться пункт "Первая печатная форма"

name="[pattern/print/subsidies.html]"
value=""
- в комбобоксе должно отобразиться пункт "[pattern/print/subsidies.html]"

name="[pattern/print/subsidies.html]"
value="<html.......и т.д.(более 100 символов)"
- в комбобоксе должно отобразиться пункт "[pattern/print/subsidies.html]"

**Comment by bvv4ik** [comment]
для теста: просто заполнить услугу (вроде субсидии) и убедиться что в дашборде формы печати открываются нормально (т.к. старый вариант отключен)

**Comment by nazarenkod** [comment]
Не соответствует описанию.значение value"sBody_1" больше нуля и меньше 100.Значение value не подтягивается в название, да и поля name не вижу.
![combobox](https://cloud.githubusercontent.com/assets/13256486/9990167/e2d54b02-6067-11e5-868f-4bf42eea7e08.jpg)

**Comment by hordesalik** [comment]
речь шла не о атрибуте "value", а о свойстве объекта из которого строится этот дропдаун

**Comment by nazarenkod** [comment]
т.е.сейчас имя тянет отсюда(помечено зеленым) и это ожидаемое поведение?
![combobox](https://cloud.githubusercontent.com/assets/13256486/9990527/c7bf4aea-606a-11e5-8a75-9f22c706c892.jpg)

**Comment by hordesalik** [comment]
Вот туда должно выводится свойство "value" объекта описывающего поле формы. Соответственно если оно проходит по правилам из задачи. Если не проходит - то выводим "по старому" - свойство "name"

**Comment by nazarenkod** [comment]
@hordesalik Вы меня простите, в виду отсутствия опыта, я теперь совсем запутался.Опишите , будьте добры, как нужно проверять данную задачу.

**Comment by hordesalik** [comment]
@bvv4ik скажешь где протестировать?

**Comment by nazarenkod** [comment]
я так понимаю уже давно работает.Закрываю
