### ISSUE TITLE
Заменить контекст wf-region и wf-central на wf + откорректировать региональные пути к проектам и убрать портал ПХП

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#793]
- [ ] 1) заменить во всем проекте (и фронте и бэке)

- [ ] 2) Оставить только:
https://test.region.igov.org.ua - дашборд чиновника
https://test.region.igov.org.ua/wf - админка активити

- [ ] 3) Поправить Вики

**Comment by bvv4ik** [comment]
просто пройтись по всем серверам ,в т.ч. новым

**Comment by VadimGulich** [comment]
сервера работают корректно
