### ISSUE TITLE
На бэке (wf-base) заменить в интерфейсе Activiti-Explorer изображения Днипрорады на универсальное iGov-овское

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#794]
1) Основная страница авторизации (Логотип и название Днепрорады)
![image](https://cloud.githubusercontent.com/assets/4208821/9964876/71e796da-5e3b-11e5-9252-98f50c873c1e.png)

2) Основной интерфейс активити-эксплорера (изображение-фраза "dnipro.egov.ua")
![image](https://cloud.githubusercontent.com/assets/4208821/9964893/833a27ae-5e3b-11e5-830f-c5e34c784b62.png)

За основу взять для автоизации (только подчеркнуть, что это "системний портал адміністратора"):
![image](https://cloud.githubusercontent.com/assets/4208821/9964939/dea4b7a8-5e3b-11e5-9a8c-d499db206132.png)

Фактически изображения лежат в виде графических файлов в проекте.
Их нужно только заменить!

**Comment by Unlym** [comment]
для теста зайти на страницу системного администратора (https://test.igov.org.ua/wf/) и убедиться, что нигде нету упоминаний про днипрораду

**Comment by kakhutasergey** [comment]
Упоминаний об Днепрораде на странице нет.

22 сентября 2015 г., 13:31 пользователь Unlym <notifications@github.com>
написал:

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/10095727/8290412e-6374-11e5-9219-c49712d792b1.png)

**Comment by VadimGulich** [comment]
реализовано/протестировано
