### ISSUE TITLE
На дашборде реализовать поддержку систепного тэга [sUserInfo] в принтформе, вместо которого будет подставляться ФИО того сотрудника, который авторизован в дашборде.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#795]
проверять можно на тестовой услуге test_print_form

ИД заявки: 55700014

**Comment by bvv4ik** [comment]
Доброе время суток,
ну как, есть надежда - на реализацию таски в эти выходные?

**Comment by dmaidaniuk** [comment]
Добрый день. Конечно! :) Таску сделаю до 04.10.2015.

**Comment by dmaidaniuk** [comment]
Хорошо, что есть где тестить:
https://github.com/e-government-ua/i/issues/797#issuecomment-145256168

**Comment by dmaidaniuk** [comment]
Задание практически готово. Запушал изменения. Но есть вопрос: в описание сказано, что нужно заполнить ФИО, а `Auth` возвращает только фамилию и имя. Этого достаточно или нужно расширить `Auth`?

**Comment by OlgaTurenko** [comment]
Этого достаточно :)

**Comment by dmaidaniuk** [comment]
Задание готово для тестирования.
Как тестировать:

> https://test.region.igov.org.ua
> Заходить под:
> dn200986zda/dn200986zda
> 
> Закладка: "В роботі"
> 
> Заявка:
> №55700014 _test_print_form | Взяти в роботу
> 
> нужно заполнить "примітки" и выбрать "Стан"
> Потом нажать "Роздрукувати"
> 
> появится принтформа, где в самом низу, слева, будет поле [sDateCreate], а справа [sUserInfo]

Проверить, что вместо тега `[sUserInfo]` подставляется фамилия и имя авторизированного в дашборде чиновника.

**Comment by OlgaKotova** [comment]
1)  фамилия и имя авторизированного в дашборде чиновника не подставляется
![2015-10-05_1403](https://cloud.githubusercontent.com/assets/5013971/10278974/5aa70690-6b6a-11e5-845f-ae1cf17e0822.png)

**Comment by dmaidaniuk** [comment]
Возможно я поспешил сказать, что измения уже на https://test.region.igov.org.ua
@bvv4ik : какой принцип деплоя последних изменений на этот тестовы

**Comment by OlgaKotova** [comment]
@bvv4ik @dmaidaniuk ФИО подставляется, закрываю

**Comment by bvv4ik** [comment]
@dmaidaniuk Спасибо за отличную работу!
"какой принцип деплоя последних изменений на этот тестовый сервер?"
именно для деплоя изменений на дашбоард тестового альфы:
его нужно запускать ручками тут: https://jenkins.igov.org.ua/job/regional-alpha/
клацнув "Build with Parameters"
и выбрав чекбокс "bIncludeUI_Dashboard", а остальные выключив

**Comment by dmaidaniuk** [comment]
@bvv4ik спасибо! Теперь буду знать за деплой.
