### ISSUE TITLE
На главном портале реализовать два новых валидатора - по ОКПО и МФО

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#796]
11) EDRPOU //код ЄДРПОУ.
Логика: жестко восемь цифр, тип стринг(чтобы можно было ставить default=” ”)
Сообщение: Такий код ЄДРПОУ не існує - (ви не можете вписувати літери)
Поля: edrpou

12) MFO //код банка.
Логика: жестко шесть цифр.тип стринг.(чтобы можно было ставить default=” ”)
Сообщение: Такого коду банку не існує - (ви не можете вписувати літери)
Поля: mfo

**Comment by bvv4ik** [comment]
@GrekD Дарья - прошу назвать для тестера - БП, где можн опроверить результат
или попросить того, для кого эти валидаторы

**Comment by GrekD** [comment]
МФО:
https://test.igov.org.ua/service/73/general

@Koffeek Рома, подскажи БП в котором есть поле с ОКПО, а то у меня такого процесса нет

**Comment by VadimGulich** [comment]
Призначення соціальної допомоги при народженні дитини

**Comment by VadimGulich** [comment]
Валидаторы не работают 
Проверка на : https://test.igov.org.ua/
пропускает как ОКПО так и МФО больше/меньше 8 и 6 цифр
сообщение при вводе букв не соответствует описанию:
![image](https://cloud.githubusercontent.com/assets/12964120/10129244/9891eac0-65c4-11e5-87ad-09500adcd741.png)

**Comment by bvv4ik** [comment]
еще пока не известно кто, но перетер код этой доработки!
Пришлось востанавливать из истории

сейчас продеплоится и можно будет проверять!

**Comment by bvv4ik** [comment]
как выяснилось - оно просто небыло перенесено после рефакторинга в новую сущность
сейчас вроде норм:
![image](https://cloud.githubusercontent.com/assets/4208821/10264128/436c6542-6a0c-11e5-82ca-415baedacfe7.png)

**Comment by VadimGulich** [comment]
да , теперь работает корректно )
