### ISSUE TITLE
На дашборде реализовать поддержку систепного тэга [sDateCreate] в принтформе, вместо которого будет подставляться Дата создания заявки (в формате YYYY-MM-DD hh:mm)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#797]
Он должен поддерживаться в выводимой Принтформе!

проверять можно на тестовой услуге test_print_form

ИД заявки: 55700014

**Comment by bvv4ik** [comment]
тестовая заявка создана...

https://test.region.igov.org.ua
Заходить под:
dn200986zda/dn200986zda

Закладка: "В роботі"

Заявка:
 №55700014 _test_print_form | Взяти в роботу

нужно заполнить "примиткы" и выбрать "Стан"
Потом нажать "Роздрукувати"

появится принтформа, где в самом низу, слева, будет поле [sDateCreate], а справа [sUserInfo]

и вот [sDateCreate], и должно заменяться...

**Comment by dmaidaniuk** [comment]
Можно переиспользовать новую функцию `PrintTemplateProcessor.populateSystemTag(printTemplate, tag, replaceWith)`. Достаточно имплементировать функцию `replaceWith` для возвращения серверного времени (дабы не было желания у пользователя играться с клиентским временем).

**Comment by uazure** [comment]
@dmaidaniuk - спасибо за наводку. Дата и так берется из серверного времени, записанного в объекте заявки, которых хранится на сервере.

**Comment by uazure** [comment]
Сделано в рамках #846, вмержено в тест

**Comment by OlgaKotova** [comment]
проверила, дата отображается верно
