### ISSUE TITLE
На главном портале, при авто-аплоаде скана (по полю типа "file", с id, начинающегося с "bankId"), передавать в т.ч. и расширение, т.к. иначе в дашборде чиновника  (и, судя по всему, при отсілке єлектронке в атаче) - єтот файл без расширения и его нельзя откріть

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#798]
Там, вроде, есть отдельный параметр для передачи расширения файла на бэк явы

**Comment by bvv4ik** [comment]
для теста: заполнить форму тестовой услуги _test_mailer_ext и в дашборде убедиться что скан нормально сохраняется и открывается с расширением

**Comment by VadimGulich** [comment]
работает корректно
