### ISSUE TITLE
На бэке (wf-base), в классе Abstract_MailTaskCustom добавить новый "унифицированный" тэг "[pattern/*]",вместо которого должно подставляться содержимое соотв. патерна

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#799]
т.е. если будет:
"[pattern/mail/feedback.html]"
то должен будет подставиться соответствующий контент из патерна

полный путь: **wf-reion/src/main/resources/pattern/mail**

для этого существует метод:
 getPatternFile(String sPathFile)
в классе:
Util

примеры использования в коде есть

**Comment by bvv4ik** [comment]
добрый день, есть какие-то ориентиры по срокам реализации таски?

**Comment by dmaidaniuk** [comment]
Добрый день. Срок до 27.09.2015.

**Comment by bvv4ik** [comment]
гуд, очень ждем)

**Comment by dmaidaniuk** [comment]
Сделано и запушано в ветку `test`.

**Comment by bvv4ik** [comment]
Супер, спасибо!

я тогда ставлю на этой таске лэйбл Test и пишу кратко комментарий для тестировщика как тестировать (обычно у нас такой алгоритм работы)

**Comment by dmaidaniuk** [comment]
Ясно. Подскажите на будущее, метку `test` ставить и кратко описать что тестрировать входить в обязаности реализатора?

**Comment by OlgaTurenko** [comment]
да :)

**Comment by dmaidaniuk** [comment]
Спасибо. Теперь буду знать. :)

**Comment by OlgaKotova** [comment]
В итоге никто ничего для тестеров не написал ( 
как тестировать задачку?
@bvv4ik @dmaidaniuk

**Comment by OlgaTurenko** [comment]
https://test.igov.org.ua/service/673/general 

В эту услугу уже добавили принт-формы.

**Comment by nazarenkod** [comment]
Протестировано.Соответствующий контент из паттерна подставляется
![as](https://cloud.githubusercontent.com/assets/13256486/10219733/0cc649cc-684a-11e5-95a9-a2c73f779872.jpg)

**Comment by kurbpa** [comment]
>https://test.igov.org.ua/service/673/general
>В эту услугу уже добавили патерны.

@bvv4ik 
@nazarenkod 
@OlgaTurenko 
не понимаю.... указанный процесс не содержит паттернов  в емейле.
также я нигде в процессе вообще не нашёл паттерн mail/feedback указанный в теле задачи.

**Comment by kurbpa** [comment]
Создал шаблон.
Прописал его в  емейле одного из процессов.
Всё собралось. Запустилось. Отработало корректно.
