### ISSUE TITLE
На центральном портале - реализовать "обертку", которая позволит из разных источников типа БанкИД - приводить все поля к единому виду (пока что только обычные поля, без сканов, а сканы транзитом отдавать) и подключить новую авторизацию через "Карту Киянина"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#800]
1) в обертке - взять пока за основу названия полей именно те-же что сейчас у нас в БанкИД. (чтоб для формы это всегда было одинаково) Пусть даже в других авторизациях и не будет некоторых полей, тогда там будет пустота.

2) через прослойку реализовать использование нового метода авторизации "Картка Киянина" по их документации: https://docs.google.com/document/d/1vzNeD8Kk36wysflRuChwiSsDIkj37vNyTQcQobD-aug/edit

Там стандартный Auth2.0, потому будет почти полный копипаст работы нашего существующиго БанкИД

(в будкщем будет и Киевстар-овская авторизация: MobileID, но не сейчас)

3) для КК сделать простую иконку, и добавить ее в ряд авторизаций:

3.1) профиле услуги:
![2015-10-18 20 45 36](https://github-cloud.s3.amazonaws.com/assets/4208821/10565491/ea9293d6-75d9-11e5-9105-be9b2f8a12e0.png)

3.2) Мои Документы
![2015-10-18 20 46 21](https://github-cloud.s3.amazonaws.com/assets/4208821/10565496/09cee22c-75da-11e5-8a70-df0b997170dd.png)

3.3) Мой журнал
![2015-10-18 20 47 26](https://github-cloud.s3.amazonaws.com/assets/4208821/10565500/2c8d819c-75da-11e5-8d02-6dfef9938098.png)

**Comment by bvv4ik** [comment]
![image](https://cloud.githubusercontent.com/assets/4208821/10776167/b35087e4-7d17-11e5-8cd6-96d872885bb9.png)

**Comment by bvv4ik** [comment]
Проверять тут: https://test.igov.org.ua/service/2/general
Выбрать Днепропетровск

**Comment by bvv4ik** [comment]
там выбрать авторизацию через КК (самая правая)
Логін: e-services-test
Пароль: e-services-2808

**Comment by bvv4ik** [comment]
возвращает: 
![image](https://cloud.githubusercontent.com/assets/4208821/10776230/36857624-7d18-11e5-9676-09148aba192d.png)

**Comment by bvv4ik** [comment]
https://test.igov.org.ua/service/720/general
тестировать на этом БП
убедиться что подтягивается ИНН

**Comment by bvv4ik** [comment]
Логін: e-services-test
Пароль: e-services-2808

**Comment by MaksKnight** [comment]
Подскажите пожалуйста как протестировать ?

**Comment by MaksKnight** [comment]
Есть баг. После нажатия на кнопку "Картка Киянина"
![image](https://cloud.githubusercontent.com/assets/17780607/14901394/bcfe6ad8-0d9d-11e6-94f4-7b262cab9e76.png)

**Comment by MaksKnight** [comment]
проверял в chrome и mozilla, последние версии.

**Comment by nazarenkod** [comment]
Все еще актуально
![2016-05-05_17-21-40](https://cloud.githubusercontent.com/assets/13256486/15046171/20036dc4-12e7-11e6-8c61-3245f0a10653.jpg)
![2016-05-05_17-28-54](https://cloud.githubusercontent.com/assets/13256486/15046179/23fa5668-12e7-11e6-9e5c-7ecd4ef9151a.jpg)
