### ISSUE TITLE
Скопировать среду тестового (альфа и бета) на ДеНово + сделать образ на перспективу

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#801]
- [ ] 1) так-же как мы поступили с tech-new.igov.org.ua
сделать и с test.igov.org.ua+test.region.igov.org.ua (тестовый альфа)
только, ВАЖНО:
- [ ] 1.1) реализовать это все в рамках единой машины: как dniprorada.igov.org.ua (там оба томкэта и обе Ноды на одной машине)
- [ ] 1.2) Назвать домен под сервак(для доступа по ssh): test-new.igov.org.ua и поддомены приложений, соответственно с "test-new.* должны начинаться (в ориентире на текущую альфу (там обновились контексты и набор приложений)
- [ ] 1.3) обязательно джоб именно альфовский брать и именно тот что на Деново (jenkins-new)
- [ ] 1.4) структуру /sybase/ сделать точно такую-же как и в dniprorada.igov.org.ua
- [ ] 1.5) так-же на Заббикс подключить
- [ ] 1.6) ПХП не нужен!
- [ ] 1.7) учесть сразу F5 (BIG-IPб защиту от Бакотек)
- [ ] 1.8) процов и памяти сделать как и на test-version

- [ ] 2)  так-же и бету сразу сделать: test-version-new.igov.org.ua, с учетом п.1.* проще всего скопировать образ  предыдущего п.1 )
- [ ] 2.1) Обязательно скопировать и авто-бэкапинг баз (/sybase/.backup*) 

- [ ] 3) создать на всяк случай готовый образ, для легкого разворачивания других тестовых сред)

П.С.: В закладке "DeNovo" вся схема: https://docs.google.com/spreadsheets/d/1spP-Tx2AwVx9rjNG052lUzXdYPSPOxLgIIRJNpnpkfo/edit#gid=1329182039

**Comment by bvv4ik** [comment]
какой ориентир по сроку?

**Comment by bvv4ik** [comment]
Готовые сервера:
https://test-new.igov.org.ua
https://test-new.region.igov.org.ua
https://test-version-new.igov.org.ua
https://test-version-new.region.igov.org.ua

**Comment by VadimGulich** [comment]
Сервера рабочие , все ок
