### ISSUE TITLE
На бэке (wf-base), при генерации sAccessKey для центрального сервера - обращаться к созданному сервису центрального портала, вместо внутреннего метода Java

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#804]
- использовать стандартный метод ХТТП-запроса проекта (там подставляется текущая бэйсик-авторизация)

- в созданный сервис передавать тот стандартый параметр что передавался в метод
+ передавать системный логин доступа в виде параметра sLogin
+ передавать контракт в виде параметра sAccessContract

- Назвать создаваемый сервис getAccessKey

- Возвращать сервис должен, как и в случае с методом - сгенерированный ключ.

Пример:  https://test.igov.org.ua/wf/service/services/getAccessKey?sLogin=activiti-master&sAccessContract=Request&sData=/wf/service/setMessage

**Comment by OlgaKotova** [comment]
@bvv4ik напишите, пжл, что это за параметры и где их взять - sAccessContract и sData ??

**Comment by OlgaTurenko** [comment]
sAccessContract=Request, sData=/wf/service/setMessage... тоесть относительный путь к сервису, который планируется вызываться с этим одноразовым кодом.

Но тестировать лучше в услугах. Эта доработка коснулать отправки почты, платежей ликпея и обновления статуса заявок.

**Comment by OlgaKotova** [comment]
@OlgaTurenko я все-равно не совсем понимаю как тестировать эту задачку и где? что значит в услугах? 
из описания таски я так поняла что нужно отправить запрос, я отправила с теми параметрами, что вы написали(собственно идентичен запросу из примера в описании) и получаю ошибку - {"code":"BUSINESS_ERR","message":"Required String parameter 'sAccessLogin' is not present"}
или что передавать в этих параметрах(sAccessContract и sData)?

**Comment by RoOmel** [comment]
Задача реализована согласно ТЗ.
На запрос
https://test.igov.org.ua/wf/service/services/getAccessKey?sLogin=&sAccessContract=Request&sData=/wf/service/setMessage&sAccessLogin=activiti-master
ответ сервера
1c2531c4-c57d-4d7b-8b68-d72378d8b70a
