### ISSUE TITLE
На бэке (wf-base), в классе авторизации, при обычной basic-authorization (а не по ключу sAccessKey) , при заданном параметре sAccessLogin - обязательно сверять его с тем логином что пришел в хеадере, и если он не совпадает - выводить эксепшин.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#805]
Выводить в эксепшине:
"[createToken](sAccessLogin='master'):!equals:'slave'"
(вместо 'master' и 'slave' выводить реальные полученные логины)

так-же добавить новый тип контракта (sAccessContract)=RequestAndLogin
при котором создавать токен на базе этого логина (переданного в параметре sAccessLogin)

**Comment by OlgaKotova** [comment]
@bvv4ik что означает "обязательно сверять его с тем логином что пришел в хеадере"? какой запрс давать?

**Comment by RoOmel** [comment]
При запросе
https://test.igov.org.ua/wf/service/services/getAccessKey?sAccessContract=RequestAndLogin&sData=/wf/service/setMessage&sAccessLogin=
т.е. когда параметр 'sAccessLogin' принимает любое значение эксепшн:  "createToken:!equals:'slave'" не выводится
