### ISSUE TITLE
На бэке (wf-base), создать сущность-справочник сверки логинов с доступным ему сервисом и обслуживающие метод и сервисы

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#806]
- [ ] 1) Сущность назвать AccessServiceLoginRight
- [ ] 2) Поля:
- [ ] 2.1) sLogin - строка-логин
(например: "master")
- [ ] 2.2) sService - строка-сервис
(например: "/mesages/getMessage")
- [ ] 2.3) sHandlerBean - строка-названия бина //опциональный
(например: "checkAccessLoginToTask")
- [ ] 3) Сервисы: (контекст: "access")
- [ ] 3.1) getAccessServiceLoginRight(sLogin)
- возвращает массив sService
- [ ] 3.2) setAccessServiceLoginRight(sLogin, sService, sHandlerBean)
- устанавливает пару sLogin+sService и опционально sHandlerBean
- [ ] 3.3) hasAccessServiceLoginRight(sLogin, sService, sData)
- возвращает значение от метода hasAccessServiceLoginRight(sLogin, sService) или hasAccessServiceLoginRight(sLogin, sService) (т.к. sData - опциональный)
- [ ] 4) Описать в документации на Вики (АПИ)

ПОЯСНЕНИЕ:
- Если sHandlerBean - задан, то по рефлексии вызывать метод, с передачей в него все пришедших параметров из sData (из соответствующих методов), а если sData не задано, то передавать туда null
- Для sHandlerBean создать интерфейс:
boolean hasAccessServiceLoginRight(String sData)

**Comment by brunneng** [comment]
Добавлена документация rest API: 40. Получеение и установка прав доступа к rest сервисам

**Comment by nazarenkod** [comment]
Протестировано согласно документации  rest API: 40.Работает согласно описанию
