### ISSUE TITLE
На бэке централа (wf-central) доработать сущность HistoryEvent_Service для поддержки дополнения заявки со стороны гражданина

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#807]
1) добавить в сущность опциональное стринговые поля:
1.1) soData - строка-объект с данными
1.2) sToken - строка-токена
1.3) sHead - строка заглавия сообщения
1.4) sBody - строка тела сообщения

2) доработать соответственные сервисы - гет-еры и сет-еры
(т.е. добавить сохранение и отдачу этих полей))

3) Дописать документацию по АПИ на Вики

**Comment by LamronNu** [comment]
дока: https://github.com/e-government-ua/i/blob/8aeae9e4ee3219f1edafee673c45c2fc0ac23674/docs/specification.md#17_workWithHistoryEvent_Services

для теста убедиться, что указанные в таске параметры добавляются через addHistoryEvent_Service и возвращаются в методе getHistoryEvent_Service

**Comment by nazarenkod** [comment]
Указанные в таске поля добавляются через addHistoryEvent_Service, но не возвращаются методом getHistoryEvent_Service. Я так понимаю, что бы метод getHistoryEvent_Service вернул добавленные значения, мне нужно сделать обновление методом updateHistoryEvent_Service?
Но этот метод возвращает "500 Internal Server Error".
поправте если ошибаюсь.

**Comment by LamronNu** [comment]
getHistoryEvent_Service  поправлен.
updateHistoryEvent_Service -- в доке была ошибка. первый параметр не nID_Protected, a nID_Process. дока тоже поправлена.

**Comment by nazarenkod** [comment]
Работает согласно описанию
