### ISSUE TITLE
На бэке (wf-base), создать сервис ЗАПРОСА полей, требующих уточнения и отсылкой уведомления гражданина

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#808]
- [x] 1) Метод setTaskQuestions

- [x] 2) параметры:
- [x] 2.1) saField - строка-массива полей (например: "[{'id':'sFamily','type':'string','value':'Белявский'},{'id':'nAge','type':'long'}]")
- [x] 2.2) nID_Protected - номер-ИД заявки (защищенный)
- [x] 2.3) sHead - строка заголовка письма //опциональный (если не задан, то "Необходимо уточнить данные")
- [x] 2.4) sBody - строка тела письма //опциональный (если не задан, то пустота)
- [x] 2.5) sMail - строка электронного адреса гражданина

- [x] 3) при вызове сервиса:
- [x] 3.1) Находить в сущности HistoryEvent_Service нужную запись (по сервису)
- [x] 3.2) апдейтить запись полем значением из:
- [x] 3.2.1) soData - строка-объект с данными (из "saField")
- [x] 3.2.2) sToken - строка-объект с данными (сгенерированый sToken)
- [x] 3.2.3) sHead - строка заголовка сообщения (из "sHead")
- [x] 3.2.4) sBody - строка тела сообщения (из "sBody")
- [x] 3.3) отсылать письмо
- [x] 3.3.1) на sMail
- [x] 3.3.2) с заголовком sHead
- [x] 3.3.3) и телом sBody
- [x] 3.3.4) + перечисление полей из saField в формате таблицы:
Поле / Тип / Текущее значение
- [x] 3.3.5) И гиперссылкой в конце типа: https://igov.org.ua/order?nID_Protected=12233&sToken=LHLIUH
где:
- хост должен быть текущий центральный
- nID_Protected - получный параметр
- sToken - сгенерированный случайно 20-ти символьный код
- [x] 3.4) в найденную таску (по nID_Protected) сетить в глобальную переменную
- [x] 3.4.1) saFieldQuestion - содержимое saField
- [x] 3.4.2) sQuestion - содержимое sBody

- [x] 4) Обязательно сохранять информацию о действии в Мой Журнал
Текст: По заявке №____ задана просьба уточнения: %sBody%
 + перечисление полей из saField в формате таблицы:

Поле / Тип / Текущее значение

- [ ] 5) Описать это все в доке на Вики (АПИ)

**Comment by bvv4ik** [comment]
я так понимаю - можно в тест?)

**Comment by LamronNu** [comment]
да, наверное..) вроде все проверено..
тест-кейсы и доку постараюсь написать сегодня-завтра

**Comment by LamronNu** [comment]
дока: https://github.com/e-government-ua/i/blob/test/docs/specification.md#38_setTaskQuestions
для теста нужно, чтобы:
- находилось событие по заявке и обновлялись в нем соответствующие поля (saField, sHead, sBody и sToken)
- отсылалось письмо с нужными данными

Заявку можно брать или из доки, или сгенерировать свою, как написано тут: https://github.com/e-government-ua/i/issues/809#issuecomment-143808587 (тогда можно будет протестировать текущую задачу "в комплексе" с задачей 809).

**Comment by OlgaKotova** [comment]
Уточните, пжл, каков должен быть результат этой таски? Если ее связывать с #809 (comment) , то получается, что должно приходить письмо на почту такого типа
<img width="767" alt="screen shot 2015-09-30 at 5 50 34 pm" src="https://cloud.githubusercontent.com/assets/5013971/10196511/e7e74ba0-679b-11e5-9f3a-d4f28e3e56ce.png">
Я правильно поняла?

**Comment by LamronNu** [comment]
даже если ее не связывать с 809-й таской, то письмо приходит такого вида:) просто в 809 нужно потом проверить, чтобы работал "ответ" на этот запрос... но можно и без этой "связи" тестировать)

в Вашем случае письмо есть -- это хорошо) в принципе, данная задача почти протестирована.

но если проверять все пункты, то:
1) проверьте еще, пожалуйста, чтобы была нужная запись в HistoryEvent_Service (дока вот: https://github.com/e-government-ua/i/blob/test/docs/specification.md#17_workWithHistoryEvent_Services, пункт getHistoryEvent_Service)
при получении обьекта смотрите на дату (sDate) -- если она равна той, когда пришло письмо, то смело сверяйте поля saField, sHead, sBody и sToken с теми, которые Вы кидали в запросе.
если дата другая -- то лучше создайте новый запрос (можно на ту же заявку) -- и потом проверяйте.

2) проверьте "Мой журнал". дока: https://github.com/e-government-ua/i/blob/test/docs/specification.md#13_workWithHistoryEvents, пункт getHistoryEvents 
nID_Subject посмотрите при выполнении предыдущего пункта.
добавлю еще, что nID_Subject -- это ид пользователя, поэтому для тестового банкИд может быть очень много записей... поищите в ответе "свою" запись, по дате скорее всего.
и там уже сверьте, верно ли всё записано (в описании этой задачи это пункт 4).

**Comment by OlgaKotova** [comment]
@LamronNu а почему в Вики прописано, что параметр nID_Protected нужно вычислять по алгоритму Луна? Может я чего-то не поняла, но сначала вычислила, сделала запрос и получила ответ CRC Error, потом прописала полный nID_Protected = № заявки и все получилось )
В общем, по пунктам:
1) не совсем поняла, что сверять, поэтому отправляю текст сообщения - {"nID_Task":5495001,"nID_Subject":20045,"sStatus":"Заявка подана","sID_Status":"Заявка виконана","sDate":"2015-09-29 17:59:54.971","nID_Service":784,"nID_Region":1,"sID_UA":"1200000000","nRate":0,"soData":"[{'id':'bankIdinn','type':'string','value':'1111111111'}]","sHead":"Необхідно уточнити дані","sBody":"","nID_Protected":54950014,"nID":37241} 
 - дата совпала.

2) Свою задачку я нашла. Если смотреть по дате и времени отправки письма на почту(2015-09-29 15:05), в журнале есть несколько записей, но дословно они не повторяют запись из пункта 4 описания таски, поэтому кидаю описание записей для проверки. Посмотрите, пжл, если все окей, то будем закрывать.

"sMessage":"Ваша заявка №54950014 змiнила свiй статус на setTaskQuestions","sDate":"2015-09-29 15:05:58.996","nID":37248,"nID_Subject":20045,"nID_HistoryEventType":6,"sEventName":"Изменение статуса заявки"},{"sMessage":"Ваша заявка №54950014 змiнила свiй статус на setTaskQuestions","sDate":"2015-09-29 15:03:07.061","nID":37247,"nID_Subject":20045,"nID_HistoryEventType":6,"sEventName":"Изменение статуса заявки"},{"sMessage":"Ваша заявка №54950014 змiнила свiй статус на setTaskQuestions","sDate":"2015-09-29

**Comment by LamronNu** [comment]
>параметр nID_Protected нужно вычислять по алгоритму Луна

nID_Protected -- это *уже* защищенный номер, ничего дополнительно считать не нужно, 
т.е. номер заявки уже защищен по этому алгоритму. а  то, что Вы прочитали -- там просто написано, что это такое и как считается.

>что сверять

Вы когда запрос кидали, то передавали значения saField, sHead, sBody (по крайней мере первый параметр точно передавался). 
 - saField "превращается" в табличку в письме (п.3,3,4 таски), 
 - sHead, если пустое, то в "Необходимо уточнить данные" (на укр.), также это будет тема письма;
 - sBody может быть пустым (или то, что передано в запросе)
 - и sToken -- тот 20-символьный код в конце ссылки Вашего письма ( https://igov.org.ua/order?nID_Protected=12233&sToken=[sToken]).

также сразу забыла уточнить, что в HistoryEvent_Service saField называется soData.

по идее, все верно, Но при желании, можете поэкспериментировать с sHead, sBody (т.е. попробовать передать свои)

> дословно они не повторяют запись из пункта 4 

а вот это что-то не то.. Должно быть два события: одно то, что есть (изменение статуса, nID_HistoryEventType=6), второе -- уже по задаче (запрос на уточнение, nID_HistoryEventType=9 вроде).
в общем, этот пункт сейчас гляну, что не так.

**Comment by RoOmel** [comment]
@LamronNu
Вцелом задача реализована согласно ТЗ, но saField не "превращается" в табличку в письме (п.3,3,4 таски).
Прошу привести пример ссылки с параметрами и ожидаемый результат

**Comment by LamronNu** [comment]
как раз с табличкой в письме проблем вроде нету..
по запросу, который в доке: https://test.region.igov.org.ua/wf/service/rest/setTaskQuestions?nID_Protected=52302969&saField=[{'id':'bankIdfirstName','type':'string','value':'3119325858'}]&sMail=test@email (подставте Ваш емейл), получается такое письмо:
![image](https://cloud.githubusercontent.com/assets/8156670/10390250/1b01351a-6e80-11e5-839c-4e4f3c047794.png)

просто эта табличка без явных границ.

Сейчас проблема с Моим журналом..( туда эта же табличка записываться не хочет...
проверить Журнал, если после предыдущего запроса, можно по ссылке https://test.igov.org.ua/wf/service/services/getHistoryEvents?nID_Subject=20045

искать по времени запроса (обычно последние записи в начале).
сейчас видно, что появляется запись "Ваша заявка №52302969 змiнила свiй статус на setTaskQuestions" (слово setTaskQuestions я подправлю на "человеческое"), а второй записи, которая озвучена в задаче, нету... в логах сыпятся ошибки..

я помню об этой задаче, вчера залила один фикс, но вижу, что он не помог. Сейчас много другой работы, поэтому так долго решаю этот баг))

Поэтому, если у Вас в письме нету таблички -- то напишите свой запрос и покажите свой скрин, буду разбираться и с этим.

А по Моему журналу я отпишусь, когда можно проверить его.
спасибо!

**Comment by RoOmel** [comment]
Согласен, содержание письма после отправки запроса
https://test.region.igov.org.ua/wf/service/rest/setTaskQuestions?nID_Protected=61551221&saField=[{'id':'bankIdfirstName','type':'string','value':'3119325858'}]&sMail=roman.omeljanenko@privatbank.ua&sHead="sHead"&sBody="sBody"
 аналогичное.
Странно, дргуое - при переходе по ссылке
https://test.igov.org.ua/order?nID_Protected=61551221&sToken=oKmiN9b6I26k80f05329
 в письме отображается пустая страница.
Зато при запросе
https://test.igov.org.ua/wf/service/services/getHistoryEvents?nID_Subject=20045
сервер показал в самой верхней мою заявку 61551221
{
        "sMessage": "Ваша заявка №61551221 змiнила свiй статус на setTaskQuestions",
        "sDate": "2015-10-09 16:23:25.709",
        "nID": 39636,
        "nID_Subject": 20045,
        "nID_HistoryEventType": 6,
        "sEventName": "Изменение статуса заявки"
    },

**Comment by LamronNu** [comment]
>при переходе по ссылке ... в письме отображается пустая страница.

в письме? у меня на новую страницу кидает, т.е. на страницу портала... и да, там пусто.
насколько я поняла, обработка таких урл-ов будет делаться в рамках другой задачи и пока не реализована.

>сервер показал в самой верхней мою заявку 61551221

угу... а еще должна быть вторая запись с текстом "По заявке №____ задана просьба уточнения: %sBody%  + перечисление полей из saField в формате таблицы "

поэтому... я напишу сюда, когда она появится)

**Comment by LamronNu** [comment]
ура! ) нашла, где была ошибка))
можно проверять,  в Мой журнал уже пишется.

**Comment by RoOmel** [comment]
Отлично!
Согласен, теперь ответ сервера изменился
{
        "sMessage": "По заявці №61551221 задане прохання уточнення:\n\"sBody\nПоле \t/ Тип \t/ Поточне значення\nbankIdfirstName \t string \t 3119325858 \n",
        "sDate": "2015-10-12 08:36:51.506",
        "nID": 39956,
        "nID_Subject": 20045,
        "nID_HistoryEventType": 9,
        "sEventName": "Запрос на уточнение данных"
    },
    {
        "sMessage": "Ваша заявка №61551221 змiнила свiй статус на Запит на уточнення даних",
        "sDate": "2015-10-12 08:36:51.491",
        "nID": 39955,
        "nID_Subject": 20045,
        "nID_HistoryEventType": 6,
        "sEventName": "Изменение статуса заявки"
    }
Задача реализована согласно ТЗ
