### ISSUE TITLE
На бэке (wf-region), создать сервис ОТВЕТА по полям, требующих уточнения

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#809]
- [x] 1) Метод setTaskAnswer

- [x] 2) параметры:
- [x] 2.1) saField - строка-массива полей (например: "[{'id':'sFamily','type':'string','value':'Белявцев'},{'id':'nAge','type':'long','value':35}]")
- [x] 2.2) nID_Protected - номер-ИД заявки (защищенный)
- [x] 2.3) sBody - строка тела сообщения //опциональный (если не задан, то пустота)
- [x] 2.4) sToken - строка-токена

- [x] 3) при вызове сервиса:
- [x] 3.1) Находить в сущности HistoryEvent_Service нужную запись (по сервису)
- [x] 3.2) сверять токен, и
- [x] 3.2.1) если он в сущности он указан но не совпадает с переданным, позвращать эксепшин "Token wrong"
- [x] 3.2.2) если он в сущности он не указан (null), позвращать эксепшин "Token absant"
- [x] 3.3) Находить на региональном портале таску и сетить в глобальную переменную
- [x] 3.4) в найденную таску (по nID_Protected) 
- [x] 3.4.1) сетить в глобальную переменную sAnswer - содержимое sBody
- [x] 3.4.2) сетить в каждое из полей из saField - эти новые значения
- [x] 3.5) в сущности HistoryEvent_Service обновлять
- [x] 3.5.1) поле soData значением из saField
- [x] 3.5.2) поле sToken значением null

- [x] 4) Обязательно сохранять информацию о действии в Мой Журнал
Текст: На заявку №____ дан ответ гражданином: %sBody%
 + перечисление полей из saField в формате таблицы:

Поле / Тип / Текущее значение

- [x] 5) Описать это все в доке на Вики (АПИ)

П.С.: в п.3 важно соблюсти именно эту последовательность действий

**Comment by bvv4ik** [comment]
можно в тест?
Ольга свою часть, вроде завершила...

**Comment by ASkosyr** [comment]
проверил - еще в тест рано
после setTaskQuestions не сохраняет токен в HistoryEvent

соответственно у меня летит ошибка Token is absent

**Comment by ASkosyr** [comment]
Добавил документацию
https://github.com/e-government-ua/i/blob/test/docs/specification.md#39_setTaskAnswer

**Comment by ASkosyr** [comment]
Заметки по тестированию.
Большинство полей в бизнес процессах имеют атрибут writable="false".
Для тестирования метода я поменял атрибут для поле ІПН в процессе  _test_autosend_printform ( Дніпропетровськ - експлуатаційний дозвіл з переробки неїстівних продуктів тваринного походження | прийняття рішення про надання послуги).

Для тестирования создаем заявку для _test_autosend_printform.
Заходим в админку и находим айди нового процесса.

Вызываем метод setTaskQuestions для этого процесса
https://test.region.igov.org.ua/wf/service/rest/setTaskQuestions?nID_Protected=54352839&saField=[{%27id%27:%27bankIdinn%27,%27type%27:%27string%27,%27value%27:%271111111111%27}]&sMail=aaa@aaa.com
На указанную почту прийдет письмо в котором будет урл с токеном.

Этот токен нужно подставить в следующий запрос setTaskAnswer

https://test.region.igov.org.ua/wf/service/rest/setTaskAnswer?nID_Protected=54352839&saField=[{%27id%27:%27bankIdinn%27,%27type%27:%27string%27,%270000000000%27:%271234567890%27}]&sToken=[Токен из письма]

**Comment by OlgaKotova** [comment]
не сохраняет токен http://screencast.com/t/eKpD6GEYvU

**Comment by nazarenkod** [comment]
состояние на 01.10.- не сохраняет токен 
![tokenis](https://cloud.githubusercontent.com/assets/13256486/10219999/80a12086-684c-11e5-903d-30394ce75b87.jpg)

**Comment by ASkosyr** [comment]
@nazarenkod, можно примеры запросов setTaskQuestions, setTaskAnswer?

**Comment by nazarenkod** [comment]
setTaskQuestions:
https://test.region.igov.org.ua/wf/service/rest/setTaskQuestions?nID_Protected=56526092&saField=[{%27id%27:%27bankIdinn%27,%27type%27:%27string%27,%27value%27:%271111111111%27}]&sMail=nazarenkod1990@gmail.com
где 
nID_Protected=56526092-номер созданой заявки

setTaskAnswer:
https://test.region.igov.org.ua/wf/service/rest/setTaskAnswer?nID_Protected=54352839&saField=[{%27id%27:%27bankIdinn%27,%27type%27:%27string%27,%270000000000%27:%271234567890%27}]&sToken=7B2Td6xxMaF7x0Y531St

&sToken=7B2Td6xxMaF7x0Y531St- токен из письма

к стати теперь пишет другую ошибку
{
code: "BUSINESS_ERR"
message: "Token is wrong"
}

**Comment by ASkosyr** [comment]
интересно :)
токен в базе сохранился как
"sToken":"XzMMdsaXb30kFGtHE1tb"

**Comment by ASkosyr** [comment]
А, так ты же указываешь разные nID_Protected в двух запросах
Токен сетится для другой таски

**Comment by nazarenkod** [comment]
увидел, сор

**Comment by nazarenkod** [comment]
{
code: "BUSINESS_ERR"
message: "Token is wrong"
}
все равно эта ошибка...

**Comment by ASkosyr** [comment]
Я указал неправильный коммент до этого.
там должно в запросе setTaskAnswer идти поле value

вот для каких запросов у меня работает.
Попробуй подставить только свой имейл

https://test.region.igov.org.ua/wf/service/rest/setTaskQuestions?nID_Protected=56526092&saField=%5B%7B%27id%27:%27bankIdinn%27,%27type%27:%27string%27,%27value%27:%271111111111%27%7D%5D&sMail=askosyr@gmail.com

https://test.region.igov.org.ua/wf/service/rest/setTaskAnswer?nID_Protected=56526092&saField=%5B%7B%27id%27:%27bankIdinn%27,%27type%27:%27string%27,%27value%27:%271234567890%27%7D%5D&sToken=1vWfd97o2T35Biw2oZy9

**Comment by nazarenkod** [comment]
Запрос прошел
200 OK "Response does not contain any data."

**Comment by ASkosyr** [comment]
И посмотри пожалуйста теперь в админке
Значение поля должно поменяться для таски

**Comment by nazarenkod** [comment]
ДА, значение поля ІПН поменялось на 123456789
спасибо, отличная работа:) 
я так понимаю можно закрывать?

**Comment by ASkosyr** [comment]
да :)

**Comment by BorisEfimenko** [comment]
Я прошу прощения, но тут баг в постановке задачи.
"3.4.2) сетить в каждое из полей из saField - эти новые значения".
Мы даем возможность менять вообще все writable поля всех форм процесса, а не те, которые спрашивали. Тут нужно было запросить список saField из вопроса.

А вообще в любой момент отправить ответ, позволяет "переуточнить" пользователю запрошенную когда-либо информацию, что является очень опасной возможностью. Здесь нужно или вводить параметр taskId, и после завершения этой задачи не выполнять сохранение в полях этой информации или еще что-нибудь придумать.

**Comment by OlgaTurenko** [comment]
Согласна. Можно давать менять поля, только по незакрытым таскам и опираясь на список полей, отмеченных чиновником. Обговорю с Владимиром и тогда поставим такую доработку уже отдельной задачей.
