### ISSUE TITLE
Сверстать остальные страницы/табы i.gov.ua

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#81]
Кроме igovua-documents.psd и igovua-documents-expand.psd

**Comment by valdemar8080** [comment]
Кроме  igovua-documents.psd и igovua-documents-expand.psd.. Эта страница у меня верстается.

**Comment by StVolodymyr** [comment]
Відпишіться тут які макети вже взяти в роботу

**Comment by bvv4ik** [comment]
igovua-documents.psd и igovua-documents-expand.psd верстаются по:
https://github.com/e-government-ua/i/issues/87

**Comment by dr1v3** [comment]
Все оставшиеся тоже взяты в работу.
https://github.com/e-government-ua/i/issues/92

**Comment by bvv4ik** [comment]
все давно готово)
