### ISSUE TITLE
На бэке wf-base сбрасывать кэш каталога услуг, при использовании сетеров

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#810]
При использовании методов:
/setServicesTree
/setService

**Comment by NikitaLyah** [comment]
как протестировать данную задачу?

**Comment by brunneng** [comment]
Кто-то разрабатывает интерфейс через которые можно редактировать категории, услуги.. Владимир в курсе. 
Сценарий такой: 
- Отредактировать какую то услугу
- Сразу после этого открыл портал и попробовать найти её. Удостоверится что изменения подхватились.

**Comment by bvv4ik** [comment]
@brunneng прав,
на главном портале, после авторизации под тестовым логином появятся кнопки редактирования, добавления и удаления категорий, подкатегорий и услуг... 
функционал работает пока только частично, потому тестировать его можно будет только по завершению каждой из этих тасок:
https://github.com/e-government-ua/i/issues/239
https://github.com/e-government-ua/i/issues/240
https://github.com/e-government-ua/i/issues/241

**Comment by nazarenkod** [comment]
@bvv4ik Протестировал все, кроме задачи #241(т.к. кнопки для категории скрыты)
откроете кнопки для теста, или можно закрывать?

**Comment by nazarenkod** [comment]
Протестировано
