### ISSUE TITLE
Создать новый репозиторий для форума и вывести ссылку в футер

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#812]

**Comment by bvv4ik** [comment]
https://github.com/e-government-ua/iForum/issues

**Comment by bvv4ik** [comment]
Ссылка добавлена

**Comment by VadimGulich** [comment]
Нужно подправить отображении ссылки 
![image](https://cloud.githubusercontent.com/assets/12964120/9986237/d636b16c-6042-11e5-87e0-d91af34370f8.png)

**Comment by smit-pb** [comment]
![image](https://cloud.githubusercontent.com/assets/12965717/10094334/45bd8f8e-6367-11e5-9922-4b65bd1253c7.png)

Реализовано.
