### ISSUE TITLE
Переименовать команды в Гитхабе(Team+Milestomes), Слак-е, и Экселе а так-жеобновить скрипты авто-проливки комментов в слак-е

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#813]
Новые команды:
DevBackEnd
DevFrontEnd
DevBackEndActiviti
DevAuth
DevOps
BusinessAnalitic
MockupDesign
Organisation
Test

Эксель: https://docs.google.com/spreadsheets/d/1MCH4QYkeSPkuiCwmvhxR_jWdL9SoRNneocBrdRSSxcw/edit#gid=0

**Comment by bvv4ik** [comment]
Переименовано несколько иначе, но зато убраны многие milestones и заменены ссылки на другие репозитории.
Осталось поправить скрипты авто-проливки комментов

**Comment by bvv4ik** [comment]
@budnik 
"Осталось поправить скрипты авто-проливки комментов"

сможешь поправить?

**Comment by budnik** [comment]
Да, тот сервис(бот) сейчас остановлен. Я все поправлю.

**Comment by bvv4ik** [comment]
спасибо, только глянь именно на текущие названия Milestones и каналов слак-а... т.к. в этой таске названия не актуальные уже

**Comment by budnik** [comment]
вроде сделал, и заодно остввил нотификации только на новый issue но не на новые коменты
