### ISSUE TITLE
Поиск документа выполняется если не выбран оператор

### ISSUE THREAD

**Issue by olyv** [e-government-ua/i#814]
Шаги для воспроизведения:
1. Перейдите по ссылке https://test.igov.org.ua/documents/search
2. Выберите любой тип документа (например, 27974)
3. Кликните кнопку "Знайти"
Ожидаемый результат: поле operatorId провалидировано как незаполненное, запрос на поиск документа не отправлен
Действительный результат: запрос https://test.igov.org.ua/api/documents/search/searchDocument отправлен, получен респонс "SYSTEM_ERR" и сообщение Entity with nID_SubjectOrgan='0' not found отображено в ГУИ

ОС Ubuntu, браузер Chrome

**Comment by bvv4ik** [comment]
я очень прошу не заполнять такими "тасками-пожелалками" issue
тем более не ставить маркер Баг
а писать такое в бэклог...

по сути-ж отвечает ошибкой при ошибочном запросе... все остальное украшалки на которые сейчас не можем тратить время... как и на перебор таких тасок...
