### ISSUE TITLE
На главном портале функция "Надати доступ до електронного документу" выводит несколько одинаковых форм

### ISSUE THREAD

**Issue by olyv** [e-government-ua/i#815]
Шаги для воспроизведения:

1. перейдите по ссылке https://test.igov.org.ua/documents/user/content
2. для любого документа кликните ссылку "Надати доступ третій особі"

Результат: выводится несколько одинаковых форм для ввода имени и фамилии, и эл.почты адресата. Так и должно быть или это неправильно работает фронт-энд?

ОС Ubuntu, браузер Chrome

**Comment by bvv4ik** [comment]
известный давно визуальный недосмотр... все такое в бэклог, пожалуйста
