### ISSUE TITLE
На дашборде реализовать "умные принт-формы". по образу и подобию "умных форм заполняемых услуг гражданина"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#816]
Исходный документ:
https://docs.google.com/document/d/1z6CuGnIQZkaQQISklRs3mlOt6rYnAZU4gYIW0DY556M/edit

- Все маркеры точно так-же загружать из полей с типом markers, подгруженной таски.
Только в дашборде а не форме центрального портала

- вместо скрытия/отображения полей(как на главном портале в форме), нужно просто находить в HTML-е принтформы элементы с заданными id
 соответственно во всех таких случаях подєлементі маркеров будут именоваться примерно так:
aElement_ID
sID_Element
sID_Element_sValue1
вместо:
aField_ID
sID_Field
sID_Field_sValue1
Причем наравне с ними так-же продолжится обращение и к значениям полей тасок (там где это нужно)

- подмену(обработку) HTML нужно делать уже в самом конце механизма формирования и заполнения принтформы (перед тем, как форма должна отобразиться в диалоге или передаться куда-то, например в виде атача(такое тоже уже есть))

- [x] 1) 
п.1-2, 4 - в зависимости от значения - скрывать/отображать поля/участки
(подобное уже реализовано на центральном для полей)

Пример:
motion: {
      ShowElementsOnTrue_1: { //Показывает элемент при определенном значении указанного поля (иначе скрывает)
        aElement_ID: ['sFIO_User1','sAddress_User1'] //id-шники элементов html

       , asID_Field: {
          'n':'nID_Type_User1' //опционально //id-шник полей таски
          'n1':'nID_SubType_User1' //опционально //id-шник полей таски
          's2':'sID_Type_User1' //опционально //id-шник полей таски
        }
        , sCondition: "[n]==1 || [n]==[n1] || [s2]=='none' || ([n] >10 && [n] < 20)"
      }
    }

т.е. вместо скрытия/отображения полей(как на главном портале в форме), нужно просто находить в HTML-е принтформы элементы с заданными id, и точно так-же их скрівать/отображать 

- [x] 2) 
п.3.Сплитить текст по первые "2 символа", "последующие до пробела", "все после первого пробела"

Пример:
{
    "motion": {
        "SplitTextHalf_1": {
            "sID_Field": "Passport",
            "sSpliter": " ",
            "sID_Element_sValue1": "PassportID",
            "sID_Element_sValue2": "PassportWhere"
        }
    }
}

т.е. будет взято значение из поля таски с id=Passport (sID_Field), разделено по символу " " (sSpliter) на две половины (можно через indexOf), и две половинки будут положены:
в элемент HTML с id=PassportID (sID_Element_sValue1)
в элемент HTML с id=PassportWhere (sID_Element_sValue2)

- [ ] 3)
п.5. заменять последние 2 символа на другие два символа

Пример:
{
    "motion": {
        "ReplaceTextLastSymbols_1": {
            "sID_Field": "nachalnikFamily",
            "nSymbols": 2,
            "sValueNew": "ко",
            "sID_Element_sValue": "sNachalnikFamily"
        }
    }
}

т.е. будет взято значение из поля таски с id=nachalnikFamily (sID_Field), в нем будут убраны последние 2 символа (nSymbols), вместо них будут подставлены "ко" (sValueNew) и полный итог значения   будут положены:
в элемент HTML с id=sNachalnikFamily (sID_Element_sValue)

Тестовый БП создан совсеми необходимыми элементами. 
Для простоты  к этому процессу прикрепил  все принтформы из оригинального процесса по ДМС.

Ссылка на процесс на альфе - https://test.igov.org.ua/service/769/general
для обработки можно использовать учётки kermit/kermit или tester/tester

**Comment by serdyuk-alex** [comment]
Смотрю на принтформу и не могу понять как можно с ней что-нибудь сделать ибо принтформы, насколько я вижу пишутся вольным стилем с макросами вместо которых подставляются уже значения. 

Пример:i\wf-region\src\main\resources\pattern\print\zajava_r(kiev).html

И сама принтформа формируется regexp.replaceAll по [\w+], т.е. на выходе получаем статический html который никак от ангуляра не зависит уже :) 

Т.е. originalForm который валяется где-то тут:
```html
	 <tr>
		<td class="underline">[bankIdlastName] [bankIdfirstName] [bankIdmiddleName],</td>
	 </tr>
```

Дальше подставляются значения через regexp replace и уже сама принтформа будет выглядеть вот так:

```html
	 <tr>
		<td class="underline">ДУБІЛЕТ ДМИТРО ОЛЕКСАНДРОВИЧ,</td>
	 </tr>
```

Я верно понимаю что это пример для моей таски рабочий? 
Насколько я понял должны быть элемены с атрибутом id которые я и собираюсь отслеживать и скрывать/отображать. Мне для теста самому нужно добавить айдишки? 

В принципе это можно сделать посредством [парсинга html](http://api.jquery.com/jquery.parsehtml/) формы которая приезжает и подвешивать туда ng-if или просто вырезать элемент если eval выдал нам false.

Пункты 2, 3 делаются просто ибо это можно включить в текущий препроцессинг файла принтформы (там где макросы подставляются).

**Comment by bvv4ik** [comment]
"Мне для теста самому нужно добавить айдишки?"
да, именно так....
конечно-же шаблоны подправят для того, чтоб соответствующие элементы, над которыми будет обработка маркера лежали в отдельной веточке HTML, у которой будет свой id

**Comment by bvv4ik** [comment]
"В принципе это можно сделать посредством парсинга html формы которая приезжает и подвешивать туда ng-if или просто вырезать элемент если eval выдал нам false."

я думал, что просто либо до либо после того, как HTML-шаблон будет обработан(т.е. в соответствующие "[name]" будут подставлены значения по существующей схеме) - твой механизм маркеров возьмет этот HTML как DOM-обьект, и просто находя в этом дереве нужные элементы по их id - отработает те сценарии, которые в маркерах будут определены...

**Comment by serdyuk-alex** [comment]
Вот это я преобразую в такое же как на central
```json
, sField_ID_n: 'nID_Type_User1' //опционально //id-шник полей таски
, sField_ID_n1: 'nID_SubType_User1' //опционально //id-шник полей таски
, sField_ID_s2: 'sID_Type_User1' //опционально //id-шник полей таски
```
т.е..
```json
        , asID_Field: {
          'sLN':'bankIdlastName'
        }
```
Чтобы код переиспользовать.

Почему вот это
```json
"sID_Element_sValue1": "PassportID",
"sID_Element_sValue2": "PassportWhere"
```
не сделать бы массивом?

**Comment by bvv4ik** [comment]
"Вот это я преобразую в такое же как на central"
согласен!

**Comment by bvv4ik** [comment]
"не сделать бы массивом?"
тут просто всегда будет только два элемента...

**Comment by serdyuk-alex** [comment]
П.1-2 готовы, можно тестировать

**Comment by kurbpa** [comment]
добавил в тестовый процесс маркеры на юзертаску.
**отображение/скрытие  полей с ФИО**
скрывает отображает  переменные с ФИО в зависимостиот выбранного значения в енаме condition

{"motion":{ShowElementsOnTrue_1:{aElement_ID:['bankIdlastName','bankIdfirstName','bankIdmiddleName'],asID_Field: {'n':'condition'},sCondition: "[n]=='yes'"}}}

**разделение значения по  знаку разделителя** ( в данном случае это пробел)
{"motion": {"SplitTextHalf_1": {"sID_Field": "bankIdPassport","sSpliter": " ","sID_Element_sValue1": "div1","sID_Element_sValue2": "div2"}}}
согласно маркеру 2 итоговых куска значения должны записаться в дивы div1 и div2,  которые добавлены в конец  принтформы  dodat12

**Comment by serdyuk-alex** [comment]
Пофиксил, закомитил

На форме печати получил следующее в логах:
```json
markers attribute show/hide name contain bad formatted json
SyntaxError, JSON.parse: expected property name or '}' at line 1 column 12 of the JSON data
field.value: {"motion":{ShowElementsOnTrue_1:{aElement_ID:['bankIdlastName','bankIdfirstName','bankIdmiddleName'],asID_Field: {'n':'condition'},sCondition:"[n]=='yes'"}}}
```
Т.е. теперь просто json нужно поправить на БП

**Comment by kurbpa** [comment]
@serdyuk-alex 
1й и 2й маркеры работают корректно.
Ждем реализацию 3го:)

**Comment by antonlegkiy** [comment]
заявка для теста https://test.region.igov.org.ua/tasks/selfAssigned/18490101, при выборе "Орган, що оформлює реєстрацію" с именительного падежа меняется на дательный падеж (Деснянський на Деснянського), при открытии принтформы.

**Comment by nazarenkod** [comment]
работает, спасибо
