### ISSUE TITLE
На главном портале, в форме подачи заявки на услугу, реализовать авто-добавление блока с информацией о возможности актуализации своих данных по БанкИД, если они выводятся в форму (хотябы одно поле)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#817]
Текст должен быть таким:
"Якщо ці або будь-які інші дані, які були передані з Вашого банку, вже не актуальні, просимо Вас звернутися до цього банку для актуалізації."

цвет темно-оранжевый

**Comment by VadimGulich** [comment]
Дайте пример услуги пож-ста

**Comment by edamov** [comment]
Дополниетельно еще нужно протестировать два кейса:
- если после логина через банкИД - все поля формы пустые (в этом случае сообщение не должно отображаться)
- если логин не через банкИД, а, например, через ЕЦП (сообщение тоже не должно отображаться)

**Comment by Sokhatsky** [comment]
Відсутній блок з інформацією о можливості актуалізації своїх даних через банк ІД при замовлені послуги:
 Видача/заміна паспорта громадянина для виїзду за кордон https://test.igov.org.ua/service/176/general
та послуги Видача паспорта громадянина для виїзду за кордон для дитини https://test.igov.org.ua/service/177/general
![pic1_ 817](https://cloud.githubusercontent.com/assets/16464887/12217874/04e26f1c-b717-11e5-8943-f13b1e332f66.png)
![pic2_ 817](https://cloud.githubusercontent.com/assets/16464887/12217878/1c43fa5e-b717-11e5-9a90-955ba1c075b0.png)

**Comment by Sokhatsky** [comment]
Також відсутній блок з інформацією о можливості актуалізації своїх даних через банк ІД при замовлені послуги:
Переоформлення, видача копії або дубліката ліцензії на надання освітніх послуг у сфері загальної середньої, дошкільної, позашкільної освіти https://test.igov.org.ua/service/73/general 
![pic3_ 817](https://cloud.githubusercontent.com/assets/16464887/12218245/b08284f0-b722-11e5-8996-d2f85a089549.png)

**Comment by Sokhatsky** [comment]
Також відсутній блок з інформацією о можливості актуалізації своїх даних через банк ІД при замовлені послуги:
Видача довідки про встановлення режиму роботи об’єкта https://test.igov.org.ua/service/1380/general
![pic4_ 817](https://cloud.githubusercontent.com/assets/16464887/12218300/b8a695b2-b723-11e5-8871-f2071c005af3.png)

**Comment by edamov** [comment]
@Sokhatsky Виправив помилки

**Comment by Sokhatsky** [comment]
Баг виправлений
