### ISSUE TITLE
Провести юзабилити анализ предложенного макета i.gov.ua

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#82]

**Comment by vilinskyy** [comment]
1) Добавить на **Главную** перед списком услуги поиском маленький блок с поясняющий текстом о работе сайта. Без воды объяснить, что тут можно сделать и какой профит получить. Привести пример. 
2) На странице своих документов (полагаю это вкладка **"Мои Документы”**) очень правильно сделан акцент на равносильность оригиналу. Можно текст чуть-чуть сократить, но больше выделить. Правда я думаю, это уже для будущих версий. 
3) На этой же странице нужно сделать кнопки более информативными. Я имею ввиду кнопки в **колонке Дії**. Во-первых добавить к иконке “Скопировать” расширение в котором скачается. Простой подписи .pdf будет достаточно. Это помогает избежать ощущения неизвестности перед нажатием. Так же думаю воздержаться от использования иконок и поменять их на надписи. Например “**Скачать .pdf**”. Можно подкрепить это иконками, но настаиваю на необходимости подписи кнопки. (Вот кстати про такие кнопки писал бельгийский дизайнер - у него очень ценные советы http://thomasbyttebier.be/blog/the-best-icon-is-a-text-label )
4) Название документа нужно сделать кликабельным и доступным для Live Preview. Не знаю насколько это с технической стороны необходимо и возможно, но было бы проще нажать на название документа, для его открытия в новой вкладке. Если это будет формат pdf, то он легко открывается внутри браузера, а на устаревших браузерах\компьютерах скачивается. Что подходит и аудитории и целям сайта.
5) С **журналом** все отлично
6) Кнопки разделов сайта сделать более понятными и добавить положения кнопки, что бы понять находимся мы в разделе или нет. А если находимся, то в каком. 
То есть если мы в "моих документах” то нужно их выделить в меню.

**Вопросы:** 
1) Документы можно будет удалять? Тогда это 3 действие.
2) Я видел мини-реализацию мобильного приложения. Но не очень понял зачем это на данном этапе. В любом случае - готов помочь и там - mobile - моя основная специализация.
3) Не видел систему входа\выхода из профиля со своими документами. Да и сам профиль наверное должен быть с датой рождения, полным именем, кодом паспорта и тд. Или я не так понял?

**Comment by bvv4ik** [comment]
готово, а развитие перенесено сюда:
https://docs.google.com/document/d/1YkH6-jBoNtHHcmA_zTiv95hpudXqQ2xNlwEOVAYqSnM/edit
