### ISSUE TITLE
На главном портале в форме подачи заявки гражданином - реализовать поддержку HTML для поля с типом label

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#821]

**Comment by nazarenkod** [comment]
Как можно проверить?

**Comment by smit-pb** [comment]
Как таки нам понять - реализовано или нет ?

**Comment by GrekD** [comment]
Если это подойдет для проверки:
Вот пример процесса на альфе, где я в лейбле вставляла ссылку используя теги html
https://test.igov.org.ua/service/73/general
фраза Детальні реквізити для оплати знаходяться за посиланням

**Comment by VadimGulich** [comment]
Спасибо , это подошло ))
Задача протестирована
