### ISSUE TITLE
Настроить Томкат в Neatbeans

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#823]
https://github.com/e-government-ua/i/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%B0-Tomcat-%28backend%29

На страничке  "Установка и настройка сервера Tomcat (backend)" добавить описание в пункт 3 "Настроить Томкат в Neatbeans".

**Comment by dmaidaniuk** [comment]
Сделано

**Comment by OlgaTurenko** [comment]
Большое спасибо!
