### ISSUE TITLE
На главном портале при работе с БанкИД включить шифрование

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#824]
сгенерировать приватный и публичный ключи(положив их на сервер через @bv4ik), и заюзать их в схеме с "oAuth 2.0", которая используется при авторизации по БанкИД

П.С.: можно связаться с Сергеем Жук-ом или глянуть доку по БанкИД
https://drive.google.com/file/d/0B25HjS4OnHuPTHhIY29PaldpbWc/view

**Comment by VadymVolos** [comment]
Весь интернет обыскал, нужны контакты Сергея Жука по другой таске, нигде нет...

**Comment by MaksKnight** [comment]
Подскажите пожалуйста как протестировать ?

**Comment by MaksKnight** [comment]
Все работает корректно.
