### ISSUE TITLE
На дашборде реализовать поддержку календарика на полях с типом "date" (так-же как и на центральном портале)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#825]
Реализовать возможность чтоб чиновник могу выбирать данные из календаря. Сейчас даже если мы ставим тип date в юзертаске, то не появляется там кнопочка календарика. А они хотят выбирать из календаря, а не прописывать руками.

**Быть крайне осторожным, т.к.:**
- компонент календарика используется не в одном месте (он еще и в экспорте статистики используется и в фильтре по "Мий росклад")
- в полях этого типа должен быть именно определенный формат даты

Тестировать можно так(причем протестировать лучше весь сценарий еще до доработки а потом после чтоб сравнить):
1) создать тестовую заявку связанную с датой (из тестовой подкатегории на центральном портале, можно по названию понять), т.е. чтоб одно из заполняемых полей было типа даты.
2) зайти на дашбоард под логином tester/tester и найда там эту заявку в необробленных - взять ее в работу
3) зайти в закладку "В роботи" и найти ее там убедившись что там дата нормально в поле отображается
4) если есть возможность выбрать другую дату в этом поле или в другом поле с типом даты - выбрать и отработать заявку
5) потом посмотреть опять в необробленных эту заявку ,взять ее и так-же убедиться что с датой все гуд
6) потом сделать доработку и повторить начиная с п.1

На вот этой услуге https://test.igov.org.ua/service/1450/general (Звернення громадян до Управління житлового господарства міської ради) на дашборде чиновника нет привязанного календарика к полю "Вкажіть дату реєстрації (у форматі ДД/ММ/РРРР)"

На центарле в услуге https://test.igov.org.ua/service/654/general (Отримання субсидії на оплату житлово-комунальних послуг) при выборе "Разом з Вами прописані інші особи?:" в полях их дат рождения нет календарика.

**Comment by AndrewLvov** [comment]
Вова, где можно посмотреть страницу с таким полем? А то я давно не заходил на проект )

**Comment by bvv4ik** [comment]
@AndrewLvov вот тут:
https://test.igov.org.ua/service/751/general
выбрать Днепропетровск

но нужно понимать, что это центральный портал (central-js, а реализовать нужно в региональном - dashboard-js)

**Comment by AndrewLvov** [comment]
@bvv4ik а где там datepicker ?

**Comment by bvv4ik** [comment]
?

**Comment by AVATOR** [comment]
добавил датапикеты на эти страницы:
https://test.region.igov.org.ua/tasks
https://test.region.igov.org.ua/reports

**Comment by RoOmel** [comment]
по ссылке
https://test.region.igov.org.ua/tasks
найдено несколько багов:
1) баг с выбором периода
т.е. кнопка должна блокироваться при выборе некорректного периода
 - начальная дата позже конечной
 - период превышает установленное количество дней
 - просто некорректная дата например 0015-12-17
2) при вводе некорректной даты вручную сервис "падает" или приложение целиком
в моём случае это S1, приложение не реагирует

**Comment by bvv4ik** [comment]
1. пермод вообще не надо выбирать

задача касается только поля форм с типом date
вроде по эскалации там должны быть заявки

**Comment by bvv4ik** [comment]
2. что именно проверяется?

**Comment by RoOmel** [comment]
по ссылке
https://test.region.igov.org.ua/reports
найдены баги:
1) баг с выбором периода
т.е. кнопка должна блокироваться при выборе некорректного периода
начальная дата позже конечной;
период превышает установленное количество дней;
просто некорректная дата например 0015-12-17;

**Comment by RoOmel** [comment]
проверяется работа календаря

**Comment by RoOmel** [comment]
AVATOR ручной ввод даты в подобных полях - это ЗЛО

**Comment by bvv4ik** [comment]
ПОВТОРЯЮ:

1. период вообще не надо выбирать!!!
задача касается только поля форм с типом date
вроде по эскалации там должны быть заявки


"AVATOR ручной ввод даты в подобных полях - это ЗЛО"
@RoOmel  я прошу не смешивать свое субьективное мнение и то что важно проверить по таске

**Comment by bvv4ik** [comment]
просьба проверить именно "задача касается только поля форм с типом date"

**Comment by RoOmel** [comment]
Прошу пояснить суть тестирования задачи "На дашборде реализовать поддержку календарика на полях с типом "date"" отдельно по каждой из ссылок:
https://test.region.igov.org.ua/tasks
https://test.region.igov.org.ua/reports
Что нужно проверить и какой при этом должен быть ожидаемый результат?

**Comment by bvv4ik** [comment]
тип ПОЛЕЙ должен быть date (type=date)

Поля - заявок (тасок)

выьрать таску , и отобразится куча полей, ссреди них то ,что с этим типом...
"вроде по эскалации там должны быть заявки"

**Comment by RoOmel** [comment]
По ссылке https://test.region.igov.org.ua/tasks
поля в заявках "Дата народження дитини", "Дата оформлення документів у форматі - ДД.ММ.PPPP *", "Укажіть дату реєстрації звернення" - обычные для ввода символов, т.е. не date

**Comment by GFalcon-UA** [comment]
На вот этой услуге https://test.igov.org.ua/service/1450/general (Звернення громадян до Управління житлового господарства міської ради) на дашборде чиновника нет привязанного календарика к полю "Вкажіть дату реєстрації (у форматі ДД/ММ/РРРР)"

На центарле в услуге https://test.igov.org.ua/service/654/general (Отримання субсидії на оплату житлово-комунальних послуг) при выборе "Разом з Вами прописані інші особи?:" в полях их дат рождения нет календарика.

**Comment by GrekD** [comment]
коллеги, по этой задаче есть какое-то продвижение?

**Comment by ijmac** [comment]
Выбор дат на дашборде поправил, поля "type"="date", readonly = false позволяют выбирать дату при помощи датапикера.

**Comment by kurbpa** [comment]
@ijmac 

`readonly = false `

правильно ли я понимаю, что подразумевается 
`writable="true"`

**Comment by ijmac** [comment]
Да, правильно

**Comment by msvidran** [comment]
Протестировал на услуге https://test.igov.org.ua/service/1454/general 
Календарь на дашборде чиновника отображается
![date_01](https://cloud.githubusercontent.com/assets/7354990/16757089/69d537ec-4812-11e6-89fa-925f40b727e9.png)
На следующую юзертаску дата передается в формате:
![date_02](https://cloud.githubusercontent.com/assets/7354990/16757095/74a75d9e-4812-11e6-8267-65d342bde690.png)

**Comment by julyprodan** [comment]
@ijmac Добрый день. Вы не могли бы перенести на Дельту функционал?
