### ISSUE TITLE
На дашборде сделать поддержку полей типа "file" - requared=false (т.е. чтоб не загружая на форме чиновника файл - не писало ошибку на бєке, при лаботе листенера)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#826]
Если из юзертаски переход на сервистаску, которая является письмом с аттачментом - тогда не получается отработать заявку и всплывает такое окно из которого непонятно что не так, "500 ошибка..."

При этом это поле с файлом может быть requared=false

**Comment by OlgaKotova** [comment]
@bvv4ik напишите, пжл, как тестировать эту задачу? где почитать в документации?

**Comment by smit-pb** [comment]
Проверил на альфе, на 5 разных тасках. Ошибка не выскакивает , т.е. не загружая фаил - все проходит норм.
