### ISSUE TITLE
На дашборд скопировать полностью механизм работы с обьектом markers (т.е. валидация, воушин и атрибуті)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#827]
ВАЖНО: Обязательно реализовать это в виде одного унифицированного общего модуля, который можно было-бы юзать и для дашбоарда и для централа и давать загружать сторонним пользователям в виде либы (минимизированной), чтоб они могли свой фронт реализовывать используя все наши фичи.

**Comment by kurbpa** [comment]
@bvv4ik 
когда можно ожидать наконец ?
