### ISSUE TITLE
На главном портале реализовать в обїекте markers, подобьекте motion - поддержку нового сценария "присваивания признака обязательности полей"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#828]
назвать его: "RequredOnCondition"
реализовать по образу и подобию: "ShowFieldsOnCondition_"
(т.е. возможные названия вариаций: RequredOnCondition_1, RequredOnCondition_Tax, RequredOnCondition_temp1)

Реализовать  возможность  динамически  присваивать/убирать признак обязательности к заполнению полей
Примеры сценария:
если выполняется условие 1 - обязательным для заполнения  должно быть поля1
если выполняется условие 2 - обязательным для заполнения  должно быть поля2
если выполняется условие 3 - поля 1 и 2  необязательны
если выполняется условие 4 - поле 1 необязательное для заполнения при печати в дашборде, поле 2 - обязательное для заполнения при печати.

на текущий момент учитsвается только атрибут requred в полях формы, а этот метод должен, если requred=false позволять считать его как true

Пример:
{
    "motion": {
        "RequredFieldsOnCondition_1": {
            "aField_ID": ["info1", "file1"],
            "asID_Field": {
                "sClient": "client"
            },
            "sCondition": "[sClient] == 'attr1'"
        }
    }
}

**Comment by serdyuk-alex** [comment]
В markers поле нужно добавить следующий json:
```json
{"motion":{"RequiredFieldsOnCondition_1":{"aField_ID":["info1","file1"],"asID_Field":{"sClient":"client"},"sCondition":"[sClient] == 'attr1'"}}}
```
Тогда будут поля required для одного из option селекта на:
https://test.igov.org.ua/service/671/general

**Comment by nazarenkod** [comment]
а подскажите услугу, на которой можно проверить

**Comment by VadimGulich** [comment]
https://test.igov.org.ua/service/671/general    услуга

**Comment by nazarenkod** [comment]
Протестировано
