### ISSUE TITLE
На главном портале реализовать в объекте markers, подобъекте motion - поддержку нового сценария "присваивания дефолтного значения полям"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#829]
назвать его: "ValuesFieldsOnCondition"
реализовать по образу и подобию: "ShowFieldsOnCondition_"
(т.е. возможные названия вариаций: ValuesFieldsOnCondition_1, ValuesFieldsOnCondition_Tax, ValuesFieldsOnCondition_temp1)

Реализовать возможность задавать значения переменных
пример сценария:
если выполняется условие 1 - присвоить переменной1 (string / long / double / boolean / label) определенное значение. 
если выполняется условие 2 - присвоить переменной2 (string / long / double / boolean / label) значение переменной3
если выполняется условие 3 - для переменной типа enum  указать  id выбранного элемента в этом enum

т.е. если условие выполняется - проставлять в указанные поля указанные значения

Пример:
{
    "motion": {
        "ValuesFieldsOnCondition_1": {
            "aField_ID": ["info1", "file1"],
            "sValue": "пусто",
            "asID_Field_sValue": [
                        "oneValue",
                        "secondValue"
             ]
            "asID_Field": {
                "sClient": "client"
            },
            "sCondition": "[sClient] == 'attr1'"
        }
    }
}

или

{
    "motion": {
        "ValuesFieldsOnCondition_1": {
            "aField_ID": ["info1", "file1"],
            "sValue": "пусто",
            "asID_Field_sValue": [
                        {"info1": "oneValue"},
                        {"file1": "secondValue"}
             ]
            "asID_Field": {
                "sClient": "client"
            },
            "sCondition": "[sClient] == 'attr1'"
        }
    }
}

**Comment by kurbpa** [comment]
@bvv4ik 
большая просьба предусмотреть возможность при выполнении условия задавать  не одно значение для нескольких переменных, а каждой указанной переменной задавать  свое значение.
т.е.

**Comment by serdyuk-alex** [comment]
Реализован сценарий с sValue и с value для каждого атрибута отдельно. Если sValue отсутствует - мы берем значение с asID_Field_sValue.
Проверял на https://test.igov.org.ua/service/671/general
Поле проставляется только если предыдущий кондишн (который вернул true) отличается от текущего (который тоже вернул true). Если предыдущий отсутствует (первая загрузка формы) - то значение проставляем.

JSON который добавлял в motion блок:
```json
   "ValuesFieldsOnCondition_1":{
      "aField_ID":["info1", "email"],
      "asID_Field_sValue":[
         "oneValue", "secondValue"
      ],
      "asID_Field":{
         "sClient":"client"
      },
      "sCondition":"[sClient] == 'attr1'"
   },
   "ValuesFieldsOnCondition_2":{
      "aField_ID":["info2", "email"],
      "asID_Field_sValue":[
         "oneValue2", "secondValue2"
      ],
      "asID_Field":{
         "sClient":"client"
      },
      "sCondition":"[sClient] == 'attr2'"
   }
```

**Comment by RoOmel** [comment]
Прошу уточнить сценарий для тестирования.

**Comment by kurbpa** [comment]
@RoOmel 
боюсь, что иного теста кроме как создавать маркер с соответствующей логикой и проверять его работу, придумать не получится.

Я подготовил такой маркер для процесса https://test.igov.org.ua/service/159/general (для Днепропетровска)

В зависимости  от значения в списке МРЭО должны заполняться последние  три поля на форме.

**Comment by RoOmel** [comment]
Павел, благодарю, на примере стало ясно.
Такой маркер каждый пользователь теперь может в своём аккаунте создавать?
