### ISSUE TITLE
протестировать услугу предоставления соцпомощи на боевом

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/i#833]
протестировать услугу "Призначення соціальної допомоги при народженні дитини" на боевом на предмет зависания заявки при ее подаче. После теста отпишите, пожалуйста, фио от кого вы их подавали - чтобы я мог закрыть эти заявки

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/10100934/ef31b384-639d-11e5-88d2-6c98ffb6136f.png)
 
в ФФ зависает

**Comment by VadimGulich** [comment]
Пример заполнения данных 
![image](https://cloud.githubusercontent.com/assets/12964120/10100971/33ca6306-639e-11e5-8807-ef8b4a9c7593.png)

**Comment by VadimGulich** [comment]
[15:53:12] Вадим Гулич: нашел причину
[15:53:37] Вадим Гулич: если в поле какрты указать через пробелы :
4731 1855 0658 1518
[15:53:54] Забрудский Дмитрий Андреевич: ну понятно
[15:53:59] Забрудский Дмитрий Андреевич: там лонг

**Comment by dmitrijzabrudskij** [comment]
а у тебя на других процессах паспортные данные загружаются? (у меня, к примеру, и данные и скан тянутся)

**Comment by nazarenkod** [comment]
Заявка успешно создалась вот с такими данніми
![default](https://cloud.githubusercontent.com/assets/13256486/10117089/b3e79530-6453-11e5-9eb5-965680b6579a.jpg)
Назаренко Дмитрий Олегович

**Comment by nazarenkod** [comment]
так же проверил сценарий почтового перевода.Работает, не зависает.
Заполнял с такими данными
![1](https://cloud.githubusercontent.com/assets/13256486/10117116/e91bd918-6454-11e5-9027-bfaf8397c539.jpg)
вот результат удачного сабмита
![3](https://cloud.githubusercontent.com/assets/13256486/10117120/0ef9ca82-6455-11e5-9536-3f3304d0cc24.jpg)
Создал 3 заявки(с пустыми данными после выбора способа получения помощи,со способом оплаты через банк и почту) все отработало.
Заявки поданы от Назаренко Дмитрий Олегович
