### ISSUE TITLE
На центральном портале в закладке Статусы реализовать при нахождении заявки отображение запрашиваемых полей (если они запрашиваются) и поля для свободного ввода комментария/фидбэка к своей заявке

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#834]
ВАЖНО: начинать отображать требуемые поля только в том случае, если в УРЛ-е указан параметр sToken
Пример:
https://test.igov.org.ua/order/search?nID=1433243&sToken=jG787H9hk00j0k
как это должно быть реализовано по таске: https://github.com/e-government-ua/i/issues/747
И потом этот параметр sToken нужно будет так-же передавать при сабмите, в метод setTaskAnswer

- [ ] 1) в подгружаемом объекте будут добавлены вспомогательные поля, в т.ч.
soData - строка-объект с данными
sToken - строка-токена
sHead - строка заглавия сообщения
sBody - строка тела сообщения
реализованные по таске: https://github.com/e-government-ua/i/issues/807

- [ ] 2) для отсылке введенных/уточненных данных
использовать метод по таске: https://github.com/e-government-ua/i/issues/809

- [ ] 3) в заглавии разместить текст из поля sHead и sBody 

- [ ] 4) Поля перечислять так-же как и в форме заполнения услуг

- [ ] 5) отсылать по кнопке "Отправить"
и после успешной отправки - писать диалог с текстом "Ответ отправлены успешно"
после чего скрывать все отображенные поля кроме статуса заявки, который нужно будет обновить.

- [ ] 6) (в последнюю очередь) использоватьтакие-же валидаторы и элементы управления (в т.ч. markers), как и в обычной форме

Если "в картинках", но нужно встроить в этом разделе:
![image](https://cloud.githubusercontent.com/assets/4208821/10103213/65c40de6-63ab-11e5-8469-e96c283c9e8d.png)

Вставить поля как в форме услуги:

![image](https://cloud.githubusercontent.com/assets/4208821/10103258/90d6f55c-63ab-11e5-91e0-3c02aaf19248.png)

![image](https://cloud.githubusercontent.com/assets/4208821/10103266/973cfe8c-63ab-11e5-8932-284cfbd99794.png)

+ Хедер с комментом от чиновника
+ текст коммента чиновника

И в конце кнопку "Отправить" (вместо "Заповнити послугу"):
т.е. это будет диалог, который позволит дополнять заявки граждан

по сути - это как-бы его урезанная версия,  где чиновник просит уточнить какие-то поля

**Comment by hordesalik** [comment]
не понятно как это должно работать. добавь на скрины кнопки/ссылки что нажимать, чтобы форма появилась... второе - нужно разрешать редактировать форму только пользователю, который ее заказал... вероятно нужна авторизация перед редактированием...

**Comment by bvv4ik** [comment]
дописал в начале таски так, чтоб было более понятна вся схема:
ВАЖНО: начинать отображать требуемые поля только в том случае, если в УРЛ-е указан параметр sToken
Пример:
https://test.igov.org.ua/order/search?nID=1433243&sToken=jG787H9hk00j0k
как это должно быть реализовано по таске: #747
И потом этот параметр sToken нужно будет так-же передавать при сабмите, в метод setTaskAnswer

**Comment by hordesalik** [comment]
nID в строке запроса никак не влияет на заполнение поля "Номер заявки". Это ок или оно должно быть заполнено и должна быть показана заявка запрошенная? Или ее отображение так же в рамках этой задачи нужно реализовать?

**Comment by OlgaTurenko** [comment]
Просьба протестировать данную задачку.

**Comment by nazarenkod** [comment]
Не очень понятно как её тестировать. Опишите, будьте добры

**Comment by bvv4ik** [comment]
завтра будем с @dmitrijzabrudskij тестировать весь цикл, и тогда отпишемся

**Comment by bvv4ik** [comment]
до-рихтовали, вроде
тестировать просто:
1) создать заявку
2) в дашборде ее найти и взять в рабботу
3) там в "Необроблени" - выбрать и нажать кнопку "замечанения", и чекбоксом отметить поля+комменты внести - где нужно уточнить, и отправить
4) придет на почту уведомление со ссыылкой, по которой перейти
5) попав на портал внести в поля данные и отправить
6) убедиться в дашборде что значения в полях поменялись (где просились уточнения)

для тестирования прошу взаимодействовать с  @dmitrijzabrudskij

**Comment by bvv4ik** [comment]
@dmitrijzabrudskij
Дима, если таки работает - прошу закрыть таску

**Comment by nazarenkod** [comment]
@bvv4ik 
после нажатия на кнопку "Відправити зауваження" ничего не происходит...POST запрос возвращает 403

**Comment by GrekD** [comment]
уточнить можно только редактируемые поля, нередактируемые (а это все поля которые пришли от гражданина) - уточнить нельзя. Это надо исправить, потому что уточнения у чиновников происходят именно по заполненным гражданином полям.

возможность уточнить данные была только для полей, которые должен редактирвоать чиновник - по одному из них уточнения внесла, направила "відправити зауваження". Всплывающее окно о том, что они отправлены появилось.

заявка: 0-99277752

письмо которое пришло на почту:
Поле / Тип / Поточне значення comment textArea попробуем проверить это поле
https://test.igov.org.ua/order/search?sID_Order=0-99277752&sToken=Rggdkxjt6xjPUeArNcRm
мне как гражданину ничего не понятно что оно означает, мне кажется надо передавать не идшник поля, а его название, и вобще, мне кажется текст этого сообщения надо полностью переделать - описать что конкретно человеку надо сделать:
а)не хватает таких-то данных (тут передаем название поля), мы хотим уточнить (тут коммент чиновника)
а) перейдите по ссылке (ссылка)
б) там внесите то-то
....

2. перешла по ссылке, указанной в письме
статус заявки высвечивается - "Отримання субсидії на оплату житлово-комунальних послуг", т.е. это название услуги, а надо высвечивать (я так понимаю) этап. В данном случае он бы назывался "взяти в роботу" - что вобщем-то тоже не очень корректно. Более правильно было бы высвечивать статус "уточнение данных"
нигде не высвечивается что я должна тут сделать

3. когда внесла комментарий и нажала "залишити коментар" он нигде не появился. Я (как гражданин) не уверена что это куда-то вобще ушло. Потом нажала кнопку "переглянути" - комментарий появился, но он не привязан ни к полю ни к вопросу - удобно было бы передавать на какое поле вносился комменатрий и на какой вопрос.
Затем когда оставляла следующие комментарии они автоматически появлялись в поле.

4. в дашборд чиновника никакие ответы гражданина не вернулись

**Comment by bvv4ik** [comment]
все работает
