### ISSUE TITLE
На дашборде реализовать возможность включения режима "Замечания/просьбы гражданину" ,чтоб отметив определенные поля - выслалось уведомление со ссылкой, где гражданин сможет внести в эти поля коррективы

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#835]
1) В закладке "В роботі", разместить на форме обработки заявки чекбокс "Внести замечания", при включении которого появляются:
1.1) Выключенные чекбоксы возле каждого поля заявки (только там, где атрибут writible=true)
1.2) При включении любого чекбокса - рядом текстареа для ввода коментария/замечания
1.3) ниже всех полей - общее поле текста для общего комментария
1.4) Ниже кнопка "Отправить замечание" (при этом дизейблить или скрывать, в этот период кнопку "Опрацювати", пока общий чекбокс включен)
2) При отправке замечания использовать сервис, написанный по таске:
https://github.com/e-government-ua/i/issues/808
Отправляя туда только те поля и те данные. которые были отмечены на форме.
3) при вызове сервиса п.2. обязательно передавать туда в т.ч.:
3.1) sHead - "Просьба уточнить данные"
3.2) sBody - тот текст, что в п.п.1.3
3.3) sMail - электронный адрес из поля формы (обычно споле с id=email)
3.4) saField - строка-обьект JSON со всеми полями и типами, которіе біли отмечены чекбоксами
3.5) nID_Protected - номер-ИД заявки (он высвечивается в каждой строке с заданием)
4) После успешной отправки (п.п.1.4.) - писать диалог с текстом "Замечания отправлены успешно" и сразу выключать чекбокс п.1. (с отчисткой всех остальных полей и их скрытием, в т.ч. остальных чекбоксов)

Реализовывать это в этом интерфейсе:
![image](https://cloud.githubusercontent.com/assets/4208821/10105314/b50d86a6-63b6-11e5-8dc5-17bf4f3c15e2.png)

**Comment by nazarenkod** [comment]
На данный момент не реализовано.Прошу написать когда будет что тестировать

**Comment by hordesalik** [comment]
![05a1d-10f9fcdf-e934-45ee-8e45-10110563141d 1](https://cloud.githubusercontent.com/assets/1492938/10815398/63a7b9b0-7e34-11e5-90f9-4b99d1b62a85.png)
Вот кнопка. Что не реализовано?

**Comment by smit-pb** [comment]
При попытке отправить Зауваження - 
POST https://test.region.igov.org.ua/api/tasks/setTaskQuestions 403 (Forbidden)

№73150107

**Comment by hordesalik** [comment]
только что проверил, приходит 200 OK 
"Внести зауваження" должно работать только на вкладке "В работе", но она отображается на всех вкладках, что нужно поправить, так что попробуйте на вкладке "В работе"

**Comment by hordesalik** [comment]
Добавил фикс - кнопка "Внести зауваження" отображается на вкладке "В работе"

**Comment by smit-pb** [comment]
![image](https://cloud.githubusercontent.com/assets/12965717/10839488/3184feee-7edd-11e5-94c7-b398024d92ff.png)

Нужна доработка. Появилась масса чекбоксов, заявка в мрэо на постановку авто, №73400018

**Comment by smit-pb** [comment]
Ну и - написав комменты - жму отправить Зауваження : 
{"code":"SYSTEM_ERR","message":"Could not find a task with id 'setTaskQuestions'."}
Получаю вот такой ответ в консоль. 
При этом визуально на странице не отображается никаких изменений и никаких Уведомлений об ошибке.

![image](https://cloud.githubusercontent.com/assets/12965717/10839522/9e2cd918-7edd-11e5-8419-e94dd0a3345d.png)

**Comment by smit-pb** [comment]
Задача - уже таки реализована ?

**Comment by smit-pb** [comment]
Актуальная проблема!

**Comment by OlgaTurenko** [comment]
Добрый вечер! принято. гляну и отвечу

**Comment by OlgaTurenko** [comment]
Спасибо за ожидание :) Наконец-то руки дошли проверить. Сейчас там ошибка при запросе к сервису:
2015-11-13_16:27:26.816 | ERROR | org.activiti.rest.controller.ActivitiExceptionController- REST API Exception: error during setTaskQuestions: null
org.activiti.rest.controller.ActivitiRestException: error during setTaskQuestions: null
        at org.activiti.rest.controller.ActivitiRestApiController.setTaskQuestions(ActivitiRestApiController.java:1295)
 
Попросила разработчика сервиса посмотреть что не так. Ожидаем

**Comment by OlgaTurenko** [comment]
Выяснился вопрос. Сейчас передается параметр nID_Process, а необходимо передавать, как описала в комментарии к задачке: https://github.com/e-government-ua/i/issues/889#issuecomment-155186234 Ольга:
возможные комбинации (в доке написано, но продублирую и здесь):

только sID_Order, задается в формате ХХХ-ХХХХХ, где первая часть -- это ид сервера (число), потом черточка-дефис, потом nID_Protected (зашифрованое ид задачи активити). также дописано, что если черточки нету, то впереди дописывается "0-" (по сути, это как вариант "только nID_Protected")
только nID_Protected -- по "старому образцу", nID_Server проставляется как 0.
nID_Protected и nID_Server

Тоесть необходимо параметр nID_Protected отправлять

**Comment by OlgaTurenko** [comment]
@nID_Protected  Сможете параметр добавить при вызове сервиса, пожалуйста?

**Comment by LamronNu** [comment]
дописан параметр nID_Process для "принятия" в сервисе setTaskQuestions, т.е.  ошибки 
>Exception: error during setTaskQuestions: null

не должно быть. 
задачу можно дальше проверять

**Comment by smit-pb** [comment]
![image](https://cloud.githubusercontent.com/assets/12965717/11265678/ff680850-8ea6-11e5-9793-7353b0f8c280.png)!
Актуально.
Номер заявки 71817175 
Браузер Хром и ФФ. кеш чистый. Проверял на test.igov.org.ua

**Comment by hordesalik** [comment]
Приходит ошибка:
{"code":"BUSINESS_ERR","message":"error during setTaskQuestions: Error happened when sending email"}
Я так понимаю, это нова на бекенд вопрос

**Comment by OlgaTurenko** [comment]
@hordesalik да, на формах где не прописана почта граждан, такая ошибка. аналитики добавят это поле во все бп. Пока просьба тестировать задачу на формах, где указан имейл гражданина.

**Comment by OlgaTurenko** [comment]
Имейлы проставили в бизнес-процессах. можно продолжать тестировать.

**Comment by OlgaTurenko** [comment]
Починка отображения чекбоксов на фронте в процессе, просьба протестировать сам функционал (отправку письма гражданину и уточнение поле + отображение уточненных полей на форме чиновника).

**Comment by smit-pb** [comment]
хорошо, проверим это.

**Comment by hordesalik** [comment]
#963 - Чекбоксы починил, поставил тест

**Comment by IrynaAndronik** [comment]
![image](https://cloud.githubusercontent.com/assets/16196477/11668604/b9203322-9e00-11e5-8e55-e42d55123979.png)

**Comment by IrynaAndronik** [comment]
Выбрала checkbox написала коментарий, нажимаю кнопку "Отправить зауваження" ничего не происходит.

**Comment by smit-pb** [comment]
Да - пофиксили проблему с кучей галлочек - зауваження.
Но - по нажатию - відправити зауваження - ничего не происходит.

**Comment by hordesalik** [comment]
@smit-pb не могу повторить так же, как на скрине. У меня 1 раз вышло получить ошибку 403. По ИД на скрине тоже ничего не находит.

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/12020687/cdb5d350-ad87-11e5-8c87-7e42e4468102.png)

Все ок, ток текст письма кривоват

**Comment by bvv4ik** [comment]
@dmitrijzabrudskij
Дима, если таки работает - прошу закрыть таску

@VadimGulich
по поводу текста - красоту будем наводить отдельными тасками

**Comment by VadimGulich** [comment]
ок, тогда работает, можно закрывать

**Comment by dmitrijzabrudskij** [comment]
@VadimGulich а вписать текст после перехода по ссылке из письма получилось?
она связана с вот этой: https://github.com/e-government-ua/i/issues/834 таской. если можно, простестируй их обе сразу

**Comment by RoOmel** [comment]
При тестировании задачи https://github.com/e-government-ua/i/issues/1042 нашёл баг.
Некорректно работает кнопка отправки замечаний при создании заявки справки о несудимости:
https://test.igov.org.ua/service/1/general и дальнейшей её обработке на https://test.region.igov.org.ua/tasks (в дашборд заходил под kermit\kermit).
После нажатия кнопки отправки замечания ничего не происходит, при этом все поля заполнены.
Пробовал даже при активных чекбоксах и заполненых полях для уточнений - после нажатия кнопки отправки - ничего не происходит.
