### ISSUE TITLE
Реализовать на бэке .при отсылке почты - "умный тэг справочника"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#839]
1) в патернах на регионе (wf-region)
должен находиться патерн-справочник, например по пути: /patterns/dictonary/MVD_Department.csv

в котором, через точку с запятой должны быть данные по строкам. например:

23423421;Запорожская обл.;Адрес1
23423422;Днепропетровская обл.;Адрес2
23423423;Киевская обл.;Адрес3

2) в теле письма должен быть тег, типа:
[pattern_dictonary:MVD_Department.csv:23423421:2]
где по коду "23423421" должна искаться строка в справочнике (всегда по первой колонке)
а подставляться вместо тега значение из колонки "2" (т.е. "Днепропетровская обл.")
при этом файл справочник должен браться MVD_Department.csv
находящийся по пути: /patterns/dictonary/

**Comment by ASkosyr** [comment]
Для тестирования нужно тег вида [pattern_dictonary:23423421:2] добавить в имейл в бизнес процессе. 
Важно: замена полей происходит если у таски навешан какой-либо из следующих компонентов.
activiti:delegateExpression="#{MailTaskWithAttachments}"
activiti:delegateExpression="#{MailTaskWithoutAttachment}"
activiti:delegateExpression="#{mailTaskWithAttachment}"

Файл словарь находится в проекте wf-base по пути wf-base/src/main/resources/patterns/dictionary/MVD_Department.csv

Для тестирования я добавлял тег [pattern_dictonary:23423421:2] в процесс _test_autosend_printform.
При успешном рассмотрении заявки в теле письма тег заменяется на номер области - http://prntscr.com/8m6vv1

**Comment by bvv4ik** [comment]
@kurbpa  Паша, можеш тестить)

**Comment by nazarenkod** [comment]
Работает согласно описанию.
![zapobl](https://cloud.githubusercontent.com/assets/13256486/10218741/c96b411c-6841-11e5-80e2-2dc35e834c2c.jpg)

**Comment by ASkosyr** [comment]
Подправил тег.
Теперь в теге нужно указывать путь к справочнику
Например, [pattern_dictonary:MVD_Department.csv:23423421:2]

**Comment by bvv4ik** [comment]
важно убедиться, что таки реально работает, т.к. Павел не мог проверить

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/10358807/cf4c2ce6-6d9a-11e5-9929-91f693a3bf7d.png)
проверено- работает согласно описанию , ток название обл. нужно указывать на УКР.
