### ISSUE TITLE
Доработать поддержку типа поля textArea в заявке гражданина

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#84]

**Comment by dr1v3** [comment]
Отпишитесь, пожалуйста, как задача будет готова. Выполню аналогичную на фронте.

**Comment by maxtmn** [comment]
в задачу добавьте описание параметров поля

**Comment by bvv4ik** [comment]
Dimension("150","300");
[10:40:40] Дащенко Инна: но можно изменить
[10:41:17] Дащенко Инна: TEXT_AREA{
  /**
   * Возвращает размер текстового окна для ввода текста
   */
  @Override
  public Dimension getDimension() {   
   return new Dimension("150","300");
  }
 };


если будут еще вопросы, лучше уточнить у Инны Дащенко, т.к. она уже реализовала поддержку этого поля на бэке

**Comment by bvv4ik** [comment]
это поле уже ест ьв бизнес-процессе: CivilCopyDocRequest ("Додаткова iнформацiя")
на этом тестовом: http://52.17.126.64:5588/
