### ISSUE TITLE
На бэке реализовать авто-подмену в полях с типом markers - значение из файлов из /bpmn/markers/motion/

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#840]
Пример содержимого поля(в атрибуте value):
[/bpmn/markers/motion/standart.json]

вместо него должно оказаться его содержимое.

Причем этот контент должен подставляться даже на этапе стартовой формы, чтоб уже на стартовую форму пришел замененный контент.

**Comment by dmaidaniuk** [comment]
@bvv4ik где это можно проверить на портале (центральном/региональном) после реализации?

**Comment by ASkosyr** [comment]
@dmaidaniuk, а вы начали уже этим заниматься?
а то я забыл на себя заассайнить таску
я вот сейчас могу начать активно ее делать

**Comment by dmaidaniuk** [comment]
@ASkosyr Увы, но я уже работаю над ней тоже.

**Comment by ASkosyr** [comment]
ок

**Comment by ASkosyr** [comment]
а этот вопрос еще актуален?

>> где это можно проверить на портале (центральном/региональном) после реализации?

или помощь какая-то нужна по задаче?

**Comment by dmaidaniuk** [comment]
@ASkosyr да, вопрос еще актуальный. Хотелось бы узнать, где можно проверить новую функциональность на правильность работы? Да и тестерам будет инфа, как тестить.

**Comment by bvv4ik** [comment]
Например, тестовая услуга: _test_dependence_form
https://test.igov.org.ua/service/671/general

ну, естественно, из поля markers контент нужно будет вынести в файл, и уже оставить в поле только ссылку на него, в соответствии с задачей..

а какой-то прогресс по задаче уже есть?

**Comment by dmaidaniuk** [comment]
@bvv4ik Прогресс есть. Постараюсь за сегодня-завтра доделать все до конца и запушать.

**Comment by bvv4ik** [comment]
гуд, спасибо!

**Comment by bvv4ik** [comment]
может помочь в чем-то нужно?

**Comment by dmaidaniuk** [comment]
@bvv4ik проблема только в свободном времени. Но тут вряд ли кто может помочь :) . 

К слову, есть один вопрос по спецификации: что делать со старой реализацией? Особенно в части фронт-энда? Пока я на беке сделал разветвление если обнаружена конструкция в value поля по типу [/bpmn/markers/motion/***.json]. Но это скорее переходный вариант.

**Comment by bvv4ik** [comment]
не совсем понял вопроса...

а зачем что-то менять на фронте? ведь на фронте что раньше, что сейчас будет приходить один и тот-же контент в value

**Comment by dmaidaniuk** [comment]
Это я наверное что-то напутал после нашего с @ASkosyr разговора в skype недавно. Подумал, что фронт-энд тоже будет меняться. 
Запушал изменения. Надеюсь, что правильно понял что должно было изменится. Изменил процесс _test_dependence_form.

**Comment by bvv4ik** [comment]
отлично, спасибо, проверяем!

**Comment by dmaidaniuk** [comment]
@bvv4ik Есть какие-то новости по задаче? Все верно или нужно что-то (все...) изменить?

**Comment by bvv4ik** [comment]
такс, видать у БА руки до нее не дошли, хотя я передавал ссылку...
значит сейчас попросим коллег тестерв проверить

**Comment by VadimGulich** [comment]
Похоже что не реализовано или сломали/откатили 

![image](https://cloud.githubusercontent.com/assets/12964120/10660083/11bec63e-78ad-11e5-9aa1-d1f7010ae586.png)

**Comment by dmaidaniuk** [comment]
@VadimGulich ок, спасибо. Гляну, что там случилось.

**Comment by kurbpa** [comment]
@bvv4ik 

Путь к  файлу с маркерами не был прописан в процессе. Добавил. Однако не подтягивается что-то информация из тестового json...

**Comment by bvv4ik** [comment]
@dmaidaniuk есть какие-то подозрения уже?

**Comment by dmaidaniuk** [comment]
@bvv4ik Без логов Томката сложно что-либо предполагать. Буду настраивать у себя локально полностью фронт-ендовую и бек-ендовую части и разбираться.

**Comment by bvv4ik** [comment]
Вот тут есть ссылка на ФТП-шки наши, где размещаются логи:
https://github.com/e-government-ua/i/wiki/%D0%9D%D0%B0%D1%88%D0%B5-%D1%85%D0%BE%D0%B7%D1%8F%D0%B9%D1%81%D1%82%D0%B2%D0%BE


Логи на FTP (по Tomcat и NodeJS):

Тест-альфа-централ: test.igov.org.ua 
протокол: sftp 
логин: sftpuser 
пароль: zaqxswcde
Тест-альфа-регион: test.region.igov.org.ua 
протокол: sftp 
логин: sftpuser 
пароль: zaqxswcde

при чем и по ноде и по яве

не стоит тратить время на разворачивание всего этого у себя...

**Comment by bvv4ik** [comment]
Добрый день,
ну как, есть какое-то продвижение по таске?
 а то у нас уже вот-вот деплой версии на продакшин и крайне важно чтоб эта доработка туда попала..

**Comment by dmaidaniuk** [comment]
@bvv4ik Добрый день. Был занят другими делами последние несколько дней. За сегодня-завтра задачу доделаю точно.

**Comment by bvv4ik** [comment]
Спасибо!)

**Comment by dmaidaniuk** [comment]
Увы, моих познаний в Activiti маловато пока чтобы сделать данную задачу.

**Comment by dmaidaniuk** [comment]
@BorisEfimenko Дякуюємо за реалізацію! 

Налаштуйте, будь ласка, на майбутнє у Вашій IDE правила форматування коду, прийняті на проекті та описані [тут] (https://github.com/e-government-ua/i/wiki/%D0%9D%D0%B0%D1%88%D0%B8-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D1%8B#0-%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-java-%D0%BA%D0%BE%D0%B4%D0%B0up).

І реалізація не зовсім збігається із задуманим.
Очікувалося отримати формат:

```
<activiti:formProperty id="markers2" name="extended_marker" type="markers" default="[/bpmn/markers/motion/testmarkers.json]"></activiti:formProperty>
```

а отримали:

```
<activiti:formProperty id="markers2" name="extended_marker" type="markers" default="${markerService.loadFromFile('testmarkers.json')}" writable="false"></activiti:formProperty>
```

@bvv4ik @OlgaTurenko Це задовільний результат для задачі?

**Comment by BorisEfimenko** [comment]
@OlgaTurenko Закрываем?

**Comment by OlgaTurenko** [comment]
Проставила лейбл тестирования. Пусь еще тестировщики на последок протестирую и закроем :)

**Comment by NizhnikAlex** [comment]
Заодно проверим отработает ли, если поместить в файл маркер размером больше 4000 знаков. С этим, вроде, проблемы.

**Comment by BorisEfimenko** [comment]
Про ограничения не подумал :(. Действительно, при более 4000 байт будет ошибка, надеюсь только при сохранении. Это ограничение таблицы ACT_RU_VARIABLE.
Первоначально предполагалось, что свойства формы с тэгом writable="false" не будут сохраняться сервере (как это реализовано в activiti-explorer).

Нужно попросить фронтэндщиков, чтобы поправили. Я, к сожалению, не силен в angular.

**Comment by BorisEfimenko** [comment]
Создал баг.
https://github.com/e-government-ua/i/issues/953
