### ISSUE TITLE
На главном портале реализовать в обїекте markers, подобьекте motion - поддержку нового сценария "присваивания признака записываемости полей" (writible=true)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#841]
назвать его: "WritableFieldsOnCondition"
реализовать по образу и подобию: "ShowFieldsOnCondition_"
(т.е. возможные названия вариаций: WritableFieldsOnCondition_1, WritableFieldsOnCondition_Tax, WritableFieldsOnCondition_temp1)

Реализовать  возможность  динамически  присваивать/убирать признак обязательности к заполнению полей
Примеры сценария:
если выполняется условие 1 - Writable должно быть поля1
если выполняется условие 2 - Writable  должно быть поля2
если выполняется условие 3 - поля 1 и 2  not Writable
если выполняется условие 4 - поле 1 Not Writable для заполнения при печати в дашборде, поле 2 - обязательное для заполнения при печати.

на текущий момент учитывается только атрибут Writable в полях формы, а этот метод должен, если Writable=false позволять считать его как true

Пример:
```json
{
    "motion": {
        "WritableFieldsOnCondition_1": {
            "aField_ID": ["info1", "file1"],
            "asID_Field": {
                "sClient": "client"
            },
            "sCondition": "[sClient] == 'attr1'"
        }
    }
}
```

**Comment by serdyuk-alex** [comment]
Работает по такому принципу:
Если данное поле упоминается в каком либо aField_ID [..] из WritableFieldsOnCondition_* объектов, то мы делаем поле редактируемым/не редактируемым если возвращается true/false соотв. из eval первого подходящего кондишина

**Comment by olyv** [comment]
Можете добавить рекомендации по тестированию? Что проверяем и где?

**Comment by RoOmel** [comment]
Прошу уточнить сценарий для тестирования.

**Comment by bvv4ik** [comment]
@kurbpa Павел, прошу подключиться к проверке

**Comment by kurbpa** [comment]
@RoOmel 
@bvv4ik 

прописал указанный маркер в тестовом процессе - https://test.igov.org.ua/service/785/general

Поле отображается и доступно для ввода при выполнении условия маркера.
Если условие не выполняется, поле вообще скрывается, вместо того чтобы просто становиться неактивным для ввода.

**Comment by bvv4ik** [comment]
"Если условие не выполняется, поле вообще скрывается, вместо того чтобы просто становиться неактивным для ввода."

оно и должно скрываться, а уже отображаться в виде лэйбла...
просто, коль данных там и нет, то в итоге пусто...  а если-б предустановленные данные были-бы, то и отображение выглядело-бы нормально (в виде не редактируемого лэйбла)

**Comment by bvv4ik** [comment]
а вот с дублированием - действительно не порядок
чето попробуем решить..

**Comment by serdyuk-alex** [comment]
Пофиксил дублирование

**Comment by kurbpa** [comment]
Проверил. Работает !
