### ISSUE TITLE
На бэке (wf-central), при фильтрации по местам в сервисе getServicesTree - фильтровать в т.ч. и ServiceData по этим критериям

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#842]
чтоб пересчитывались в т.ч. и счетчики доступных и тестовых услуг

**Comment by bvv4ik** [comment]
т.е. выбрав в интерфейсе фильтр по региону - все услуги и их статусы должны вывестись исключительно в контексте этого фильтра

**Comment by RoOmel** [comment]
По запросу
https://test.igov.org.ua/wf/service/services/getServicesTree?asID_Place_UA=1200000000,1210100000
я должен получить ответ от сервера по всем услугам и их статусам по региону Днепропетровска.
Но в ответе среди всех отображаемых услуг я не смог определить к какому региону относится данный список.

**Comment by brunneng** [comment]
Регион или город не предаются напрямую в ответе. Т.к. эти данные находятся на уровне сущности ServiceData, которые исключаются из ответа (данные отсекаются на уровне Service). Для проверки можете воспользоватся методом getService.
Например, на запрос выше вернется  в том числе такая услуга (Service)

{
                        "sSubjectOperatorName": "Державна Автомобільна Інспекція",
                        "subjectOperatorName": "Державна Автомобільна Інспекція",
                        "nID": 159,
                        "sName": "Реєстрація авто з пробігом в МРЕВ",
                        "nOrder": 100,
                        "nSub": 2,
                        "nStatus": 2,
                        "nID_Status": 0
},

запоминаем. "nID": 159, и делаем запрос с таким nID,
https://test.igov.org.ua/wf/service/services/getService?nID=159

В ответе будет видно, что данная услуга есть в Днепропетровске. И аналогично можно проверить для других услуг.

**Comment by RoOmel** [comment]
Ок
