### ISSUE TITLE
На главном портале организовать поддержку авто-наложения ЭЦП на оформленную заявку гражданина, сразу после заполнения заявки и нажатии кнопки сабмита.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#843]
- [ ] 1) ВАЖНО! Отрабатывать такой алгоритм только
- [ ] 1.1) при наличии на форме поля, которое имеет тип file, и его id=form_signed
(при этом само такое поле скрывать на форме)
- [ ] 1.2) при отмечании чекбокса (рядом с кнопкой сабмита), с названием "Наложить ЭЦП" (сам чекбокс отображать только при наличии условий п.1.1

- [ ] 2) При нажатии кнопки сабмита (после заполнения гражданином заявки) - формировать HTML-вариант єтой заявки (со всеми полями, кроме сканкопий).
Использовать при єтом минимальній набор стилей. Буквально только "Лєйбл+описание и правее - значение"

- [ ] 3) после формирования HTML - отправлять его мультипартфайлом посредством сервиса, согласно инструкции по наложению ЭЦП тут(стр.21: "Модуль наложения ЭЦП на заявку"):
https://drive.google.com/file/d/0B25HjS4OnHuPTHhIY29PaldpbWc/view

- [ ] 4) после подписания и возврата контента - прикреплять его в виде атача (как обычную сканкопию), в поле формы, которое имеет так-же тип file, и его id=form_signed

- [ ] 5) после успешного прикрепления - производить обычный дальнейший сабмит формы (но уже как-бы с прикрепленным этим файлом, с наложенным ЭЦП)

Тестировать можно на тестовой услуге:
https://test.igov.org.ua/service/1389/general

**Comment by AleksejDomash** [comment]
Еще необходимо доделать:
1. Проверить как заполняются типы полей file и scan при восстановлении формы
2. Обработка ошибок
3. Возможно стоит делать нередактируемыми все поля
4. Проверить почему не дизейблится кнопка submit, если не установлен checkbox с подписью

**Comment by bvv4ik** [comment]
"1. Проверить как заполняются типы полей file и scan при восстановлении формы"
- сейчас коллег попрошу проверить и отписаться тут...

"2. Обработка ошибок"
- может пока давай запустим так, и уже в конце - этим можно будет заняться, в рамках общей задачи по наследованию ошибок?

"3."
 - как вариант, но мне кажется, что проще было-бы проще пока скрывать все эти поля и писать общую надпись, типа "Ожидайте, пожалуйста... накладывается ЭЦП!"

"5. Скрівать поле подписи (почему оно не invisible ?)"
- так тамжеж тип "file", и он нужен чтоб біла дальнейшая его корректная обработка...
но, кстати, на фронте стоит реализовать скрітие єтого поля, т.к. мі его и так идентифицироуем по началу ИД

"6. Что делать с полями для файлов в html форме, которая идет в ПДФ"
- просто скипать

**Comment by kurbpa** [comment]
**Проверить как заполняются типы полей file и scan при восстановлении формы**
* вроде бы всё ок. см скрин 
![image](https://cloud.githubusercontent.com/assets/11442397/10579801/f03f19d6-7682-11e5-9411-e76afa6a2b40.png)


**2) При нажатии кнопки сабмита (после заполнения гражданином заявки) - формировать HTML-вариант єтой заявки (со всеми полями, кроме сканкопий).
Использовать при єтом минимальній набор стилей. Буквально только "Лєйбл+описание и правее - значение"**

* а вот тут проблема. ХТМЛ-вариант заявки формируется и при этом в нём подтягивается ещё футер, который создавали сугубо для справки о несудимости (см. скрин). Также отображаются поля сканкопий.

![image](https://cloud.githubusercontent.com/assets/11442397/10579891/628b0a40-7683-11e5-808e-a9d4697b2531.png)

**Comment by bvv4ik** [comment]
футер, это да... он явно не нужен...
убрал

**Comment by NizhnikAlex** [comment]
Судя по всему, неправильно была поставлена задача изначально.[attach_6810096.pdf](https://github.com/e-government-ua/i/files/18315/attach_6810096.pdf)

**Comment by bvv4ik** [comment]
-убрал поля типа file и markers
-подставил корректное название Услуги

-попытался подправить неверное отображение энума
т.к.
https://github.com/e-government-ua/i/files/18315/attach_6810096.pdf
вот тут видно, что энум некорректно отображается в поле с лэйблом "Юридична особа діє на підставі:"

**Comment by bvv4ik** [comment]
я так понимаю - нужно таску закрывать...

**Comment by NizhnikAlex** [comment]
Можно закрывать. ТЗ в рамках таски выполнено

**Comment by bvv4ik** [comment]
да, отлично, закріваем
