### ISSUE TITLE
В дашборде, при формировании принтформы заменять null в значении поля на пробел

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#844]
при передаче в принтформу незаполненного поля (сейчас там значение null) подменять его на пробел (это необходимо корректного отображения печатных форм)

Проверить можно на заявке №: 55550091
(https://test.region.igov.org.ua/tasks)
логин/пароль: dn200986zda

**Comment by uazure** [comment]
Пофикшено же, верно?

**Comment by bvv4ik** [comment]
да

**Comment by RoOmel** [comment]
На печатных формах значение null не отображается
