### ISSUE TITLE
На главном портале, при заполнении формы услуги и наличии в ней поля с id=sID_UA - автоматически проставлять в него это значение при собмите формы, в соответствии с выбранным городом/областью

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#845]
организовать проброску в поле sID_UA (invisible) - кода КОАТУУ, который соответствует тому месту что человек выбрал

(тестовый процесс на альфе - "_test_sID_UA")

**Comment by bvv4ik** [comment]
@kurbpa Павел, проверь  плиз и напиши сюда результат

**Comment by RoOmel** [comment]
Нет возможности при заполнении "Бажана дата візиту до МРЕВ:" закончить оформление заявки
![bug_igov_19_01](https://cloud.githubusercontent.com/assets/12996514/10422538/80ebbada-70c4-11e5-9a23-96da39659ff9.jpg)
т.к. нет выбора вариантов из выпадающего списка.
Проверял на альфа и бета-версиях.

**Comment by bvv4ik** [comment]
@kurbpa Павел, прошу подтвердить/опровергнуть работоспособность
и подсказать коллеге - как тестировать

**Comment by kurbpa** [comment]
@RoOmel 
@bvv4ik 

в теле такси было указано ведь **тестовый процесс на альфе - "_test_sID_UA"** - https://test.igov.org.ua/service/785/general

в этом процессе нет никаких электронных очередей и нет никаких визитов в МРЭВ.

после подачи крайне короткой заявки на емейл заявителя приходит письмо с значением кода для выбранного города.

**Comment by kurbpa** [comment]
@bvv4ik 
@RoOmel 
https://test.igov.org.ua/service/785/general - подал заявку.
Выбран город Днепропетровск.

**Ожидаемый результат в емейле**
выбран город - 1210100000

**Фактический результат**
выбран город - 1200000000

в переменную sID_UA было передано значение не выбранного города, а выбранной области.

**Comment by bvv4ik** [comment]
деплоится фикс, через 2 минуты можно будет проверять

**Comment by kurbpa** [comment]
Проверил.

Для Днепропетровска приходит "выбран город - 1210100000".
Работает.

**Comment by RoOmel** [comment]
Согласен, работает корректно
