### ISSUE TITLE
На дашборде отрефакторить модуль формирования принтформы

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#846]
Тот механизм, что связан с кнопкой "Роздрукувати"

**Comment by uazure** [comment]
Внес много исправлений в инфраструктуру, связанную с распечаткой форм. На мой взгляд теперь значительно лучше, чем было, хотя и тоже не идеально. Проверял работу функционала связанного с печатью кастомных и дефолтной формы - вроде все работает.

**Comment by OlgaKotova** [comment]
@bvv4ik @uazure а что сдесь тестить? как проверить эту таску?

**Comment by uazure** [comment]
@OlgaKotova поклацать все что можно и найти места где не работает. Нового функционала или исправления вненего поведения системы тут нет. Если все что касается печати работает как ожидается (как ранее), значит все ок.

**Comment by smit-pb** [comment]
![image](https://cloud.githubusercontent.com/assets/12965717/10329920/de97e5bc-6ccf-11e5-8ff4-0477a03b20e8.png)
Как то не очень хорошо - ДАТА отображается.

**Comment by OlgaKotova** [comment]
Нашла заявку, в которой, при заполнении всех полей и нажатии на "Роздрукувати", появляется ошибка, что не все поля заполнены
![2015-10-07_1145](https://cloud.githubusercontent.com/assets/5013971/10332991/af10ab3e-6ce9-11e5-8cb9-fcbf352944d7.png)

**Comment by uazure** [comment]
@smit-pb - fixed
@OlgaKotova - это не баг. Поле оплаты за услугу обязательное. Без оплаты - любые операции с формой не имеют смысла. Поле будет заполнено автоматически после оплаты пользователем стоимости услуги.

**Comment by bvv4ik** [comment]
после рефакторинга "работы с принтформами" немного койче поламалось.

а именно:
там был такой функционал, который если находит определенный тип поля (type="file"), и id поля, начинающийся с "PrintForm_" (например "PrintForm_1")
то тогда из названия этого поля (например: name="File label;File title;print/dndz_cnap_186_print.html") - брался путь к патерну
и формируя(заполняя) его, это в виде атачмента крепилось к данной юзертаске, чтоб потом отправиться почтой гражданину...

и сейчас, оно вроде отправляет, но там вместо нормальной заполненной указанной принтформы, например:
[7 жовтня 2015 р. 16:12] Грек Дарья Алексеевна: 

<<< https://drive.google.com/open?id=0B6mOkUg9oq1zekhlb2F5VE4weXF2WkZWVnV0TFZqX3VNdS1v
тестовая услуга для проверки: _test_autosend_printform

Проверить так:
зайти сюда: https://test.igov.org.ua/service/784/general
заполнить и сабмить форму, получив № заявки
потом в дашбоард
и найди эту заявку в закладке не взятых
взять в работу
и перейдя в необработанные - уже обработай ее-же
должно на электронку прийти письмо
в котором будет поломанный контент прикрепленной принтформы
Например:
https://drive.google.com/open?id=0B6mOkUg9oq1zekhlb2F5VE4weXF2WkZWVnV0TFZqX3VNdS1v

**Comment by uazure** [comment]
@bvv4ik так что, последний коммитик пофиксил проблему? У меня пока не было времени потестить.

**Comment by OlgaKotova** [comment]
@bvv4ik вот что у меня получилось после теста:

1) Замечание:
на странице регистрации услуги https://test.igov.org.ua/service/784/general , после логина и заполнения всех полей и попытки зарегистрировать услугу, в случае, если поля заполнены некорректно вылазит ошибка "помилкаSYSTEM_ERR For input string: "qqq", Пользователь ее не видит и не поймет соответственно, т.к., она находится вверху страницы, а страница прокручена вниз.
Прикрепляю скрин ошибки, но уже после исправления внесенных данных и регистрации услуги
![2015-10-11_1040](https://cloud.githubusercontent.com/assets/5013971/10415878/f2a8b23c-7005-11e5-8d43-e7e5e26e1fc9.png)

2) в письме, которое приходит на почту, отсутствует № заявки
![2015-10-11_1051](https://cloud.githubusercontent.com/assets/5013971/10415884/404276b8-7006-11e5-87f1-42d02e5a7e5f.png)

3) ну и вот, собственно, скрин самого вложения в письмо(тот самый контент)
![2015-10-11_1054](https://cloud.githubusercontent.com/assets/5013971/10415887/85e162c4-7006-11e5-9d03-83918e1cf628.png)

**Comment by uazure** [comment]
fixed

**Comment by nazarenkod** [comment]
с вложенным письмом все ок
![leter](https://cloud.githubusercontent.com/assets/13256486/10423447/5947e64c-70cf-11e5-9c75-b6044db847d6.jpg)
осталась проблема с номером заявки
![zay](https://cloud.githubusercontent.com/assets/13256486/10423484/8e18e236-70cf-11e5-9ed5-0656028b4120.jpg)
фикс будет в рамках этой задачи?

**Comment by OlgaKotova** [comment]
@uazure @bvv4ik я вот по поводу этого комментария:
 uazure commented 2 days ago
это не баг. Поле оплаты за услугу обязательное. Без оплаты - любые операции с формой не имеют смысла. Поле будет заполнено автоматически после оплаты пользователем стоимости услуги.
Для услуги "Реєстрація авто з пробігом в МРЕВ | Надання послуги: Огляд авто", еще один пример заявки №56926735.

Там просто ошибка вылазит, что "Не все поля заполнены", может изменить ее текст, например, на "Оплатите за услугу" или что-то подобное с описанием ошибки, а то как-то не ясно какие поля не заполнены...

**Comment by nazarenkod** [comment]
@OlgaKotova это рабочая среда чиновника, он не должен ничего оплачивать.Оплата будет туда сама подтягиваться(насколько я понял).Навероно имеет смысл писать что то вроде "Услуга не оплачена или что то подобное", но это наверно в будущем

**Comment by bvv4ik** [comment]
ребята, тюнингом будем заниматься отдельно...

важно чтоб принципиально работал функционал

**Comment by nazarenkod** [comment]
@bvv4ik функционал работает. осталась проблема с отсутствием номера заявки.фикс будет в рамках этой задачи?

**Comment by bvv4ik** [comment]
но номеру заяви, там стоит в теле письма:
${reestr_numb}

т.е. это обычный параметр, и если он не отображается - значит он пустой...

тем более что там:
        <activiti:formProperty id="reestr_numb" name="Реєстраційний номер" type="string" default=" "></activiti:formProperty>
        <activiti:formProperty id="reestr_numb" name="Реєстраційний номер" type="string" writable="false"></activiti:formProperty>

и дефолтом пустота, а параметр не врайтабельный

**Comment by nazarenkod** [comment]
понял.значит все ок, закрываю
