### ISSUE TITLE
Доработать поддержку типа поля textArea в заявке гражданина

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#85]
реализация на бэке по этой-же задаче, в issue:
https://github.com/e-government-ua/i/issues/84

**Comment by bvv4ik** [comment]
Dimension("150","300");
[10:40:40] Дащенко Инна: но можно изменить
[10:41:17] Дащенко Инна: TEXT_AREA{
/**

Возвращает размер текстового окна для ввода текста */ @Override public Dimension getDimension() {
return new Dimension("150","300"); } };

это класс,TextAreaFormPropertyRenderer который отображает это поле с типом TextArea

если будут еще вопросы, лучше уточнить у Инны Дащенко, т.к. она уже реализовала поддержку этого поля на бэке

это поле уже есть в бизнес-процессе: CivilCopyDocRequest ("Додаткова iнформацiя")
на этом тестовом: http://52.17.126.64:5588/

**Comment by bvv4ik** [comment]
на тестовом: http://52.17.126.64:5588/
БП:CivilCopyDocRequest - Звернення громадян стосовно надання копій документів
Поле textArea:
Id - textArea
Type - textArea
Name - Додаткова iнформацiя

**Comment by bvv4ik** [comment]
сервис аплоада файла в Редис, чтоб получить его ИД
/file/upload_file_to_redis

**Comment by loveitgroup** [comment]
готово

**Comment by bvv4ik** [comment]
так не видно, чтоб это воле стало textArea
http://52.17.126.64:5588/site/definition?id=CivilCopyDocRequest%3A16%3A77507

**Comment by dr1v3** [comment]
Почему, textarea же
![screenshot](http://i.imgur.com/C1maZPH.png)

**Comment by bvv4ik** [comment]
это только что наконец удалось продеплоить
