### ISSUE TITLE
Причесати док "Як-почати-роботу"

### ISSUE THREAD

**Issue by yurikoles** [e-government-ua/i#861]
[Як-почати-роботу](../wiki/Як-почати-роботу)
Пропоную інфу, яка специфічна для WEB-розробників відокремити у відповідний документ.

**Comment by bvv4ik** [comment]
крупные блоки по локальной установке  и так вынесены, там осталось только основное и нужное для получение инфы(со ссылками) по 90% кейсов при начале работы.

а вообще, все предложения прошу писать в ишью репозитория iForum
