### ISSUE TITLE
На бэке (wf-base) реализовать новый тип тега "приоритетной подстановки полей" в класс-системтаски формирования письма для отправки

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#865]
1) Тэг в виде value{[название переменной]}
где вместо "название переменной" должно быть название переменной, которую нужно будет взять из текущей юзертаски, при этом value != enum.
Например:
value{[bankIdFamily]}

2) класс, в котором это нужно будет интегрировать:
Abstract_MailTaskCustom

3) Отрабатывать этот тег сразу после отработки тега:
TAG_sPATTERN_CONTENT_COMPILED = Pattern.compile("\\[pattern/(.*?)\\]");

4) Описать в документации(со ссылкой на эту таску):
https://github.com/e-government-ua/i/wiki/%D0%9D%D0%B0%D1%88%D0%B8-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D1%8B#111-%D1%82%D1%8D%D0%B3-value%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9-%D1%8E%D0%B7%D0%B5%D1%80%D1%82%D0%B0%D1%81%D0%BA%D0%B8up

**Comment by OlgaTurenko** [comment]
https://test.igov.org.ua/service/670/general  услуга для тестироания. В тело письма прошивается фамилия и имя

**Comment by OlgaKotova** [comment]
@OlgaTurenko я так понимаю, после успешной регистрации услуги "Ваше звернення №59575010 успішно зареєстровано, Результати будуть спрямовані на Ваш e-mail " должно прийти письмо на указаный имейл? 
Ничего не приходит

**Comment by kurbpa** [comment]
@OlgaKotova 
не совсем так. Тестовую заявку нужно обработать тестовым пользователем (прикрепить файл) и только после этого отправляется письмо.

Я свои заявки обработал и Вашу тоже, так что письмо должно быть.

**Comment by OlgaTurenko** [comment]
Судя по описанию Павла в форме отработанных тасок и стартовой форме не было найдено поля с ид = region
В таком случае меняем тег на пустую строку. что собственно и случилось. А есть пример процесса с которым это случилось? Посмотрю.

**Comment by kurbpa** [comment]
@OlgaTurenko 

применить пытаемся в процессе для Житомира zt_region_cnap_182
ссылка на услугу - https://test.igov.org.ua/service/763/general

**Comment by OlgaTurenko** [comment]
Я вижу в этом процессе поле с ид = region (в стартовом кубике). При этом оно скрытое и не обязательное. У меня подозрение, что это поле формы просто не заполнено в нашем случае. Не подскажете, пожалуйста, на каком этапе в это поле добавляется значение, так как вот так сразу я не нахожу этого места?

**Comment by kurbpa** [comment]
это поле заполняется на стартовом же шаге в зависимости от выбранного  тут же значения в **area**

Логика заполнения описана на этом же шаге в маркере: marker4:

{"motion":{"ValuesFieldsOnCondition_1":{"aField_ID":["region"],"sValue":"1","asID_Field":{"sReason":"area"},"sCondition":"[sReason] == 'andrush'"},"ValuesFieldsOnCondition_2":{"aField_ID":["region"],"sValue":"2","asID_Field":{"sReason":"area"},"sCondition":"[sReason] == 'baran'"}}}

**Comment by msvidran** [comment]
убрали на переменной region readable "false" и вот что получилось
![3](https://cloud.githubusercontent.com/assets/7354990/10338800/a26fe0a8-6d10-11e5-9183-0e7013d71f99.png)
номер строки передается, а со справочника данные не подтягиваются

**Comment by OlgaTurenko** [comment]
Ага. Сейчас вижу что все ок. В письме все корректно

**Comment by kurbpa** [comment]
Работает!

**Comment by RoOmel** [comment]
После подачи заявки по ссылке https://test.igov.org.ua/service/763/general
на почту пришло 3 письма:
1. Ваша заявка 62478381 прийнята!
Ви завжди зможете переглянути її поточний статус у розділі "Статуси". Також на кожному етапі Ви будете отримувати email-повідомлення. 

2. Ваш запит був успішно зареєстрований у нашій системі.
Залишайтеся з нами.
Відділ з питань надання адміністративних послуг Андрушівської районної державної адміністрації
Адреса:
10014, м. Житомир, вул. Михайлівська, 4
Графік роботи ЦНАП-у:
Понеділок - п'ятниця з 8.00 до 20.00
Субота з 8.00 до 15.00
Вихідний - Неділя
Без перерви на обід

3. Шановний(-а) колего!
У Вас в черзі на обробку зареєстровано нове звернення щодо "Надання рішення міської ради про надання дозволів на розробку проектів землеустрою щодо відведення земельних ділянок".
Заявник: ДУБІЛЕТ ДМИТРО ОЛЕКСАНДРОВИЧ
Опрацюйте, будь ласка, це звернення на порталі.

По ссылке https://test.region.igov.org.ua/ 
нет задачи которую я должен обработать ни в одной из рубрик.

Вопросы:
1) Прошу уточнить сценарий для тестирования;
2) Какой должен быть ожидаемый результат;
3) Описать в документации(со ссылкой на эту таску) - не реализовано

**Comment by bvv4ik** [comment]
@kurbpa так работает, или нет?
прошу подсказать коллеге - как и на чем можно перепроверить

**Comment by kurbpa** [comment]
@bvv4ik 
@RoOmel 

адрес и график работы во  втором письме это уже значение вытянутое именно из справочника с использованием тега приоритетной подстановки.
4 дня назад всё проверено и уже внедрено в процессах.
