### ISSUE TITLE
На центральном портале, в форме заполнения услуги - встроить поддержку вспомогательного поля департамента, с учеетом которого и производить перезагрузку списка доступных дат электронной очереди

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#866]
- [ ] 1) находить на форме "исходное поле электронной очереди"(с типом "queueData") и по тому, какой у него id - искать поле "ИД департамента электронной очереди", с id, равным "nID_Department_"+(id найденного поля с типом "queueData")
Например:
есть поле с типом "queueData", и id="visitDate",
значит ищем поле с id="nID_Department_visitDate"

- [ ] 2) Каждый раз при выборе нового значения в поле, найденного по п.1 ("ИД департамента электронной очереди"):
- [ ] 2.1) отчищать списоки в комбобоксах, связанных с исходным полем ("исходное поле электронной очереди"),
- [ ] 2.2) сбрасывать его значение на null
- [ ] 2.3) и переформировывать список в комбобоксе с датой

- [ ] 3) При загрузке списка дат "исходного поля электронной очереди" - передавать вспомогательный параметр, из поля, найденного в п.1 с "названием nID_SubjectOrganDepartment"
(именно в конечный явовский сервис /buildFlowSlots)

- [ ] 4) если значение в найденном поле п.1 налловое или поле вообще не найдено, то в п.3. второй параметр как и сейчас - не передавать.

- [ ] 5) "исходных полей электронной очереди" может быть в будущем больше чем одно, потому предусмотреть и обработку такого кейса.

**Comment by RoOmel** [comment]
"встроить поддержку вспомогательного поля департамента"
Не реализовано.

**Comment by bvv4ik** [comment]
проверять нужно на тестовой услуге:
_test_queue_cancel
т.е. там, где это поле фигурирует

**Comment by RoOmel** [comment]
Бізнесу: Будівництво, нерухомість, земля
услуга " _test_queue_cancel" не реализована

**Comment by bvv4ik** [comment]
https://test.igov.org.ua/service/756/general
вот она

**Comment by RoOmel** [comment]
Вспомогательное поле департамента реализовано, с учётом которого и производится  перезагрузка списка доступных дат электронной очереди.
Но при переключении департаментов видно, что электронная очередь доступных дат одна, т.е. общая.

**Comment by hordesalik** [comment]
так. а что на меня заасайнили то? ) что мне делать? я зашел - там вообще нет дней доступных

**Comment by OlgaTurenko** [comment]
слоты сегодня сгенерируют до конца дня и  можно будет проверять.

**Comment by hordesalik** [comment]
Слотов по прежнему нет

**Comment by OlgaTurenko** [comment]
Для тестирования можно использовать: https://test.igov.org.ua/service/159/general
для Днепропетровска.

там 2 разных МРЭО (  те же 2 департамента) Слоты там создали

**Comment by hordesalik** [comment]
ну вот я вижу, что там загружаются 2 не одинаковых списка слотов. Если выбрать одно время в одном отделе, а в другом выбрать тот же день и открыть список доступных слотов по времени - доступны все, т.е. списки работают независимо

**Comment by hordesalik** [comment]
что с этим? кто то тестирует?

**Comment by VadimGulich** [comment]
Все ок , закрываем
