### ISSUE TITLE
На главном портале реализовать профиль для Тернопольской ОДА

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#868]
1) по аналогии с Киевом
test.kiev.igov.org.ua
сделать чувствительность на домен:
test.ternopol.igov.org.ua

2) на основании ТЗ: https://docs.google.com/spreadsheets/d/1sA0S8tTwZFmj0dio2SUPlrUxX1gtNiCxvHsA5B0_gjU/edit?usp=sharing
и изображений:
https://drive.google.com/folderview?id=0B-TXzbaEvbw9ZzJuZWZyVnk3MGc&usp=sharing

2.1) Вставить хеадеры
2.2) оставить только те пункты меню что там указаны
2.3) Отсылать дефолтный фильтр Места (для каталога услуг) - Тернопольской обл. и г.Тернопол-я

**Comment by kelnerira** [comment]
Добрий день! Дякую за тестову сторінку! Зауваження - потрібно додати до послуг Тернопільської області також загальнодержавні.  Як це було передбачено у ТЗ. Цитую: "На порталі розміщуються усі послуги, доступні для замовлення онлайн, у т.ч. загальнодержавні - як посилання на сторінки відповідних сервісів."

**Comment by kelnerira** [comment]
@glebzhebrakov Добрий
