### ISSUE TITLE
На бэке (wf-base) при отработке Эскалации, в классе-хэндлере отсылки письма - подставлять в письме не ИД юзертаски а ИД заявки (nID_Protected)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#869]
1) в письме по эскалации указывать номер заявки, а не номер таски, как сейчас.
2) Очень желательно давать на нее ссылку

**Comment by ASkosyr** [comment]
Добавил в заголовок и тело письмо номер заявки вместо номера задачи
http://prntscr.com/8qm6hg

Ссылка в письме есть, но на данный момент не работает - необходимо доработка сторефронта.
По этому номеру можно искать заявку вводя его в поле 'Введіть № звернення для пошуку'
http://prntscr.com/8qm7nt

**Comment by VadimGulich** [comment]
Подскажите , как получить письмо  эскалации  ? 
При каких условия

**Comment by ASkosyr** [comment]
процедура обработки эскалаций запускается вызовом
https://test.region.igov.org.ua/wf/service/escalation/runEscalation

однако в правилах эскалации находятся имейлы Д. Дубилета и П.Курбацкого

я себе для тестирования добавлял свое мыло, но после завершения тестирования убрал свой имейл

как вариант - могу отфорвардить пачку имейлов, которые мне тогда свалились

**Comment by LamronNu** [comment]
можно еще добавить "свое" правило эскалации (сервис setEscalationRule, емейл обязательно в одинарные кавычки "завернуть") -- запустить эскалацию только для этого правила (runEscalationRule?nID=[nID]), а потом удалить это правило (removeEscalationRule).

более подробно написано тут: https://github.com/e-government-ua/i/issues/658#issuecomment-138097284 и ниже по комментам.. там есть примеры запросов

**Comment by VadimGulich** [comment]
По идее уже и на бою , задача так отпразднует и второй НГ))) 
закрываю
