### ISSUE TITLE
Сверстать остальные страницы i.gov.ua  igovua-documents.psd и igovua-documents-expand.psd

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#87]

**Comment by dr1v3** [comment]
Завтра сверстаю остальное

**Comment by bvv4ik** [comment]
А можно плиз список оставшихся файлов? я создам задачу

**Comment by dr1v3** [comment]
igovua-documents-notify, igovua-journal, igovua-profile-step

**Comment by bvv4ik** [comment]
отлично, создал последнюю задачу:
https://github.com/e-government-ua/i/issues/92

эту закрываю!
Спасибо!
