### ISSUE TITLE
На дашборде не отображать поиск тасок по ИД и тексту в закладке "Отработанные"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#870]

**Comment by VadimGulich** [comment]
Ошибка при поиске по тексту:
![image](https://cloud.githubusercontent.com/assets/12964120/10571246/1077714a-7646-11e5-9948-b828916dca09.png)

во всех вкладках

**Comment by smit-pb** [comment]
![image](https://cloud.githubusercontent.com/assets/12965717/10578716/81082ec8-767c-11e5-8423-92bfaca6b213.png)

По идее  -эти 2-а поля вообще не должны отображаться ?

**Comment by smit-pb** [comment]
А ответ или фикс или хоть что-то - Будет ?

**Comment by bvv4ik** [comment]
просто непонятно, как это отночится к данной задаче?

если есть глобальная проблема, ну тогда уже стоит отдельную таску создать и даже можно кинуть мне в личку ссылку, чтоб ускорить.. но колеги вроде не обращались с проблемой.

По данной таске - реализовано? (т.к. эти элементы убраны из соотв. закладки?)

**Comment by smit-pb** [comment]
На дашборде "НЕ" отображать поиск тасок по ИД и тексту в закладке "Отработанные"
- но эти 2-а поля то - ОТОБРАЖАЮТСЯ в отработанных !

**Comment by smit-pb** [comment]
Или я не корректно понимаю поставленную задачу.

**Comment by OlgaTurenko** [comment]
Вы понимаете задачу корректно. Нужно было скрыть окошки для поиска. Они отображаются. Ждем пока поправят.

**Comment by smit-pb** [comment]
спасибо. А то я уже решил что : что-то было написано между строк, а я этого не увидел.
ждем тогда реализации.

**Comment by bvv4ik** [comment]
не актуально
