### ISSUE TITLE
Доработать на бэке сервис получения статистики /getStatisticServiceCounts, чтоб появилось дополнительное поле nTimeHours, с отражением среднего времени жизни заявки

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#871]
1) для этого получив строку с услугой (в т.ч. по nID_Service) - находить ее БП и на региональном сервере подсчитывать среднее время отработки заявки.
2) БП можно находить через связанные сущности ServiceData, где в поле есть ссылка на БП, а строку ServiceData можно найти по nID_Service и nID_Region / nID_City (в будущем sID_UA)
3) Для получения списка задач по БП есть сервис(на региональном): /download_bp_timing
там только нужно задавать параметр bDetail=false, чтоб не тянуть массу ненужніх подробностей.
И там есть нужніе исходніе данніе для подсчета среднего времени.
4) Указывать период за последние 3 месяца

**Comment by bvv4ik** [comment]
Все-же, я подумал.... стоит эти подсчитанные данные по таймингу каждой таски кешировать в отдельном поле этой сущности...

т.е. встроить подсчет тайминга при закрытии таски, в классе Interceptor, и сохранять итог в поле nTimeHours

и уже в этом методе вывода статистики - брать данные из этого поля, вместо постоянного пересчета...

это так-же позволит избежать коллизий с ненахождением тасок в хистори, по разным ServiceData

**Comment by ASkosyr** [comment]
Данные о времени выполнения задачи сохраняются в хистори ивент после завершения обработки запроса. При выполнении запроса вычисляется среднее время обработки услуги

https://test.igov.org.ua/wf/service/services/getStatisticServiceCounts?nID_Service=1

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/10629162/1f8deda4-77d5-11e5-8e6e-7fba2a3f21d2.png)

 есть минусовое время, я думаю такого быть не должно )) 
{"nCount":1,"nRate":0,"nTimeHours":-1,"sName":"Львівська"}

**Comment by VadimGulich** [comment]
если нет активности то должен быть 0 , а не -1

**Comment by ASkosyr** [comment]
Подправил, теперь 0 если нет статистики.

**Comment by VadimGulich** [comment]
Уточните пож-ста, если  -1  до этого выводился для городов у которых нет статистики , то для кого тогда выводился ноль , для услуг которые были обработаны быстрее 1 часа ?

**Comment by ASkosyr** [comment]
> ноль , для услуг которые были обработаны быстрее 1 часа ?
да

**Comment by VadimGulich** [comment]
понял , спасибо . задачу закрываю
