### ISSUE TITLE
403 Forbidden - fidobank.ua/BankId

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/i#872]
Привет Ребята! Я не знаю в какую ветку этот вопрос.
https://igov.org.ua/documents/user/bankid
Вообщем нашел что при нажатии на кнопку fidobank перебрасывает на страницу с 403 ошибкой.

**Comment by bvv4ik** [comment]
это бок в ФидоБанке

**Comment by VadymVolos** [comment]
Без понятия что такое "бок" но если он не работает, нужно убрать со списка.
Это людей обнадеживает, они видят свой банк, начинают радоваться, а потом нажимают а оно не работает.

**Comment by bvv4ik** [comment]
БанкИД - это не наше)))

Жуку Сергею можно написать...

но важно - не писать в репозитории "i" такие таски... тут только то, что дается непосредственно в реализацию...
иначе разработчики путаются и не могут самостоятельно брать таски...

**Comment by VadymVolos** [comment]
Ок. Буду знать что сюда только на реализацию. Если б я это знал я б и не постил сюда.
