### ISSUE TITLE
На портале фильтр, как делится ссылкой на услугу/ги?

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/i#878]
На портале в фильтре, хочу поделится ссылкой на выбранный мной фильтр, например “Управління праці та соціального захисту населення”, а не могу, так как ссылка сверху https://igov.org.ua

Это круто что фильтр работает без перезагрузки страницы, но как делится ссылкой?
Нужно как то придумать чтоб люди могли поделится ссылкой на ту услуги/министерство которое выбрано в фильтре.

**Comment by bvv4ik** [comment]
Вадим, просьба все это в iForum, (эту закрой плиз)
а то тут свалка получается, вместо уже готовых отобранных задач по разработке...

по вопросу: со временем, возможно, но не факт что так реализуем... там просто есть варианты реализации, через обычные параметры или хэш... потому вначале занимаемся наиболее приоритетными задачами...

**Comment by VadymVolos** [comment]
Ок. Перенес сюда (https://github.com/e-government-ua/iForum/issues/30), и тут закрываю.
