### ISSUE TITLE
Реализовать на централе вывод поля nTimeHours в статистике

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#881]

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/10629162/1f8deda4-77d5-11e5-8e6e-7fba2a3f21d2.png)

Что то реализовано , но вот что должно показывать , есть минусовое время ))

**Comment by VadimGulich** [comment]
перенес в задачу по беку https://github.com/e-government-ua/i/issues/871
эту закрываю

**Comment by ASkosyr** [comment]
-1 выводится для регионов, где нет статистики
