### ISSUE TITLE
На бэке wf-base реализовать сервис удаления задачи по nID_Protected

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#882]
1) /removeTaskActiviti
2) параметр: nID_Protected - номер-ИД заявки 
3) в ответ 200 тый код если все гуд
или обьект с ошибкой, и соотв. не 200-тым кодом статуса

наверняка есть готовый сервис или метод Activiti, который можно будет найти гдето в документации..
например:
http://www.activiti.org/userguide
или, есть еще pdf-ник с докой гдето в нете...

ВАЖНОЕ ДОПОЛНЕНИЕ:

при удалении таски важно еще отмечать это в журнале и истории
@LamronNu знает - какие сервисы за это ответственны (еще ест ьна вики, но проще пообщаться с @LamronNu)
Ольга прошу помочь)

Сообщения писать что-то типа "Задание было удалено (логин удалившего)"

Для этлго еще одним опциональным параметром добавить поле sLogin

**Comment by ASkosyr** [comment]
http://www.activiti.org/userguide/#_delete_a_process_instance

**Comment by bvv4ik** [comment]
спасибо)
только беда в том, что нам-то нужна обертка, которая будет воспринимать nID_Protected

**Comment by tivv** [comment]
А какой это сервис/контроллер? Я сходу nID_Protected нашел только в HistoryEvent_Service.
Кстати, рассматривая реализацию getHistoryEvent_Service в контроллере, появилось пару вопросов:
 * Почему EntityNotFound преобразовывается в 403 а не 404?
 * Зачем RuntimeException оборачивается в ActivitiRestException? Остальные методы таким не заморачиваются.

**Comment by tivv** [comment]
И, кстати, в некоторых контроллерах remove* это GET, а в некоторых DELETE. Что использовать?

**Comment by LamronNu** [comment]
>А какой это сервис/контроллер?

сервис-то как раз нужно создать) но если это модуль wf-base -- то нужно смотреть, какие там контроллеры "уже есть" и куда можно добавить этот. Наиболее "подходящим" мне кажется ActivitiRestApiController -- там есть уже похожие сервисы, для работы с задачами активити...

>nID_Protected

nID_Protected  -- это nID процесса активити, зашифрованное алгоритмом Луна. подробнее про него и про сущность HistoryEvent_Service  можно почитать в доке: https://github.com/e-government-ua/i/blob/test/docs/specification.md#17_workWithHistoryEvent_Services
насчет самого сервиса getHistoryEvent_Service  -- он сейчас переделывается, поэтому его логика немного поменяется.

> Почему EntityNotFound преобразовывается в 403 а не 404?

404 -- это "страница не найдена", в нашем же случае нету запрашиваемой сущности... Хотя, по самим кодам ответов вопрос не был принципиален, т.е. "пока ставим 403 -- потом (при необходимости) будем детализировать". Главное, чтобы возвращало код ошибки (а не 200-й), который можно "распознать". 

>Зачем RuntimeException оборачивается в ActivitiRestException?

про это здесь: [Наши стандарты](https://github.com/e-government-ua/i/wiki/%D0%9D%D0%B0%D1%88%D0%B8-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D1%8B#1_)
но, опять-таки, каждый "сам себе режиссер"..

>в некоторых контроллерах remove* это GET, а в некоторых DELETE. 

см. предыдущие два ответа.

Проект писался не одним и не двумя разработчиками, с разным уровнем скиллов и представлениями "как правильно писать". 

Сейчас, когда уже сложилось более-менее  понимание того, что мы имеем и куда стремимся -- то мы пытаемся все систематизировать. Страничка "наши стандарты" для этого и создана, также недавно было приведение к единому форматированию кода (пункт 0 в Стандартах). 
Но понятно, что все это "не сразу происходит", потихоньку, т.к. есть более приоритетные задачи...

**Comment by tivv** [comment]
OK, спасибо. А почему "тупое перебрасывание" не реализовать глобально на Spring MVC. А то придется добавлять BoilerPlate кода в каждом контроллере с try/catch

**Comment by tivv** [comment]
Создал https://github.com/e-government-ua/i/pull/909

**Comment by bvv4ik** [comment]
сори, еще важное дополнение(я сразу как-то этот момент упустил)

при удалении таски важно еще отмечать это в журнале и истории
@LamronNu знает - какие сервисы за это ответственны (еще ест ьна вики, но проще пообщаться с @LamronNu)
Ольга прошу помочь)

Сообщения писать что-то типа "Задание было удалено (логин удалившего)"

Для этого еще одним опциональным параметром добавить поле sLogin

**Comment by tivv** [comment]
Не вопрос. Там рядом контроллер на cancelTask, полагаю в нем это есть (что-то такое видел) - посмотрю там. Заодно как насчёт отрефакторить таски в отдельный контроллер, а тоив этом куча всего?

**Comment by bvv4ik** [comment]
по перераспределению тасок в разные контролеры - задача стоит, но это не делаем пока, т.к. поламается клиент если не делать это синхронно... в этом году все такие темы должны уже закрыть.

**Comment by bvv4ik** [comment]
а на счет сохранения в журнале и истории:

вот есть пример в классе:
org.activiti.rest.interceptor.RequestProcessingInterceptor
методе:
private void saveHistory(HttpServletRequest request, HttpServletResponse response, boolean saveHistory)

где есть, например:
            if (isSaveTask(request, sResponseBody)) {
                saveNewTaskInfo(sRequestBody, sResponseBody, mParamRequest);
            } else if (isCloseTask(request, sResponseBody)) {
                saveClosedTaskInfo(sRequestBody);
            } else if (isUpdateTask(request)) {
                saveUpdatedTaskInfo(sResponseBody);
            }


покапавшись там можно понять как допилить и для этого метода...

ключевой момент в том, что вызываться должен именно сервис, т.к. этот журнал и история находятся на центральном сервере... а таски удаляются на региональном

**Comment by tivv** [comment]
А чего клиент поломается то? Я говорю о том, чтобы методы намапленые на "/task" вынести в отдельный класс из текущего уберконтроллера в стиле "на всеируки мастер". Для клиента ничего не поменяется.

**Comment by bvv4ik** [comment]
значит я неверно понял)
если просто попереносить методы классов, и внешние пути останутся прежними - можно и досрочно... но, по приоритету яб определил так:
1) допилить эту таску
2) эксепшины
3) перекомпоновка сервисов

**Comment by LamronNu** [comment]
только добралась до просмотра гитхаба)
возможно, задача уже решена... но все же: есть, есть ли какие-то вопросы?

по истории -- также можно глянуть сервисы setTaskQuestions или setTaskAnswers (в ActivitiRestApiController). 
При вызове сервиса updateHistoryEvent_Service запись в Моем журнале создается автоматом. Точнее, две записи: одна по изменению состояния задачи (возможно, такого будет достаточно... там "шаблон" вида "задача изменила состояние на %название_состояния%), вторая запись -- для предыдущих двух сервисов.

насчет "перекомпоновки сервисов" -- поддерживаю. Еще помню, что была такая таска, по "упорядочиванию" контроллеров.. #728 вроде.

**Comment by LamronNu** [comment]
@bvv4ik , кстати. может, тут уже сразу делать для нового формата номера задачи, т.е. не только nID_Protected учитывать, а и sID_Order и nID_Server? (по таске #889)
?
или позже?..

**Comment by bvv4ik** [comment]
да, но комментировать это в данной тишью не стоит.. чтоб не запутаться потом...
просто опциональные параметры к сервису допилить и все)

**Comment by tivv** [comment]
Добавил. Заодно вынес работу с history even service в отдельный клас.
Странности:
 * Текущая реализация cancelTask на ошибки ведет себя "особенно" - вместо возвращения json, возвращает строку с сообщение
 * При вызове history event service добавляются разные параметры, этим  сервисом не обрабатываемые
 * Интересным параметром является sAccessKey, который когда добавляется а когда нет и судя по всему еще и ложится куда-то в базу.

**Comment by bvv4ik** [comment]
"Текущая реализация cancelTask на ошибки ведет себя "особенно" - вместо возвращения json, возвращает строку с сообщение"
ну, просто это метод вызываться будет клиентом из письма, и ему нужно будет выводить хоть какой-то человекочитаемый текст. Со временем думали туда даже HTML-шаблон выводить...

"При вызове history event service добавляются разные параметры, этим сервисом не обрабатываемые"
сдалано на перспективу... со временем заюзаются или уберутся.

"Интересным параметром является sAccessKey, который когда добавляется а когда нет и судя по всему еще и ложится куда-то в базу."
это элемент варианта авторизации, там все норм... таким образом создаются разовые авторизации, позволяющие допустить вызов из, например, письма, которое было выслано гражданину... ведь авторизация-то нужна там..

**Comment by tivv** [comment]
ОК, я вмержу Pull Request, опишу для тестировщика и поставлю лейбл.

По cancelTask: В любом случае какой-то UI на это нужен, тем более, что метод POST, напрямую линком не вызовешь. Да и нехорошо это по линкам делать действия без подтверждения (мало ли какой почтовик захочет prefetch сделать). А UI может и JSON распарсить.

**Comment by bvv4ik** [comment]
"тем более, что метод POST, напрямую линком не вызовешь."
там форма, которая нормально шлет пост...

" В любом случае какой-то UI на это нужен,"
UI там в виде ХТМЛ-а в письме, и вполне приличный... осталось только приличный ответ в ХТМЛ-виле отдавать.

"Да и нехорошо это по линкам делать действия без подтверждения (мало ли какой почтовик захочет prefetch сделать)."
там подтверждением является уникальный одноразовый код (кстати тот самый sAccessKey)
который встраивается в тот запрос, который шлется персонально гражданину в мыло... так что все норм..

и, таким образом, избавляемся от лишнего клика...

"А UI может и JSON распарсить."
там человеку и не нужно особо ничего, кроме готовой ХТМЛ-ины, с текстом типа "Ваша заявка "22222 - отменена!".

**Comment by tivv** [comment]
OK, merged.
Для тестера:
В wf_base появился вызов /rest/tasks/removeTask?nID_Protected=VALUE&sLogin=OPTIONAL_VALUE удаляющий задачу в Activity и создающий об этом запись в wm_cental hostory event service вида "Заявка была удалена (OPTIONAL_VALUE)". Если sLogin не указан - скобки не добавляются. Если указан неверный nID_Protected - код возврата 403.
Если все ОК - код 200.

**Comment by OlgaKotova** [comment]
@tivv Напишите, пжл, подробнее как тестировать задачку(полный текст запросов на удаление и проверку записи в журнале)? 

я отсылала запрос - https://test.region.igov.org.ua/wf/service/rest/tasks/removeTask?nID_Protected=45735489&sLogin=kermit - такого типа, сейчас там стоит верный номер задачки, получила в ответ код 200, потом nID_Protected поменяла на "что-попало" и тоде получила код 200. 
 В журнале никакой записи не было...

Опишите пожалуйста задачку подробнее, чтобы понять что я делаю не так?

**Comment by tivv** [comment]
Да, извиняюсь, забыл уточнить, что метод не GET а DELETE:
`curl --user activiti-master:PASSWORD_MASKED -X DELETE https://test.region.igov.org.ua/wf/service/rest/tasks/removeTask?nID_Protected=123`
выдает 403 `{"code":"BUSI NESS_ERR","message":"CRC Error"}` как и ожидалось.
Вообще там на /rest/tasks слегка странный мапинг
/rest/tasks/aaa - вызов getTasksByAssignee(aaa)
/rest/tasks/getTasksByText - вызов getTasksByText
в результате: assignee "getTasksByText" вызовет ошибку и любая опечатка в урле или неверный метод просто вернет [] с помощью getTasksByAssignee

**Comment by LamronNu** [comment]
@tivv , опишите, пожалуйста, этот сервис еще в доке: https://github.com/e-government-ua/i/blob/test/docs/specification.md
скорей всего, @bvv4ik  забыл упомянуть про это в описании задачи..
только я пока не могу сообразить, куда лучше.
или во втором пункте (про Активити), или пока допишите пунктом 42 -- потом, при правке документации, уже перенесется в нужный раздел..
Что писать -- там есть примеры. По сути, все то же самое, что Вы в комментарии написали)
можно позже, когда будет время
спасибо

**Comment by OlgaKotova** [comment]
@tivv С неверным nID_Protected код возврата 403 - прошла тест.
проделывая операцию с другим номером заявки -  https://test.region.igov.org.ua/wf/service/rest/tasks/removeTask?nID_Protected=45735489&sLogin=kermit (метод DELETE) - получаю ошибку {"code":"BUSINESS_ERR","message":"Record not found"}. Номер заявки взяла из test.region.igov.org.ua. 

![2015-10-29_1439](https://cloud.githubusercontent.com/assets/5013971/10818556/2a2ed634-7e4b-11e5-8537-058456ac990c.png)

Может другой номер нужен? или откуда этот номер брать вообще?

**Comment by tivv** [comment]
Похоже нумерация на test.region.igov.ua и test.region.igov.ua/wf разная, это вроде как центральный и региональный сервера, насколько я понимаю.
Список  wf тасок можно взять например тут: https://test.region.igov.org.ua/wf/service/rest/tasks/kermit
Интересуют те, у которых processInstanceId не пустой.
Проблема в том, что его нужно преобразовать по спец. алгоритму, который добавляет еще один знак. Возможно для теста проще перебрать все 10 вариантов, на неправильные должен выдавать CRC Error.
Например, для "processInstanceId":"5275131" перебрать от 52751310 до 52751319

**Comment by OlgaKotova** [comment]
@tivv протестировала 2 таски(5275131+5 и 6997505+9), при неверном nID_Protected, выдает 403 ошибку - ОК. 
Но, при тестировании верного nID_Protected(как я поняла из подстановки - это тот nID_Protected, который не дает 403 ошибку), в ответ приходит ошибка 500 Internal Server Error c сообщением - {"code":"SYSTEM_ERR","message":"The task cannot be deleted because is part of a running process"}.

**Comment by tivv** [comment]
Тут мои познания в Activiti заканчиваются. @bvv4ik, можешь помочь?

**Comment by OlgaKotova** [comment]
@tivv Прошу прощения, я тут в предыдущем комментарии с запросом немного натупила ((
В общем, ситуация следующая:
метод removeTask удаляет таски с любым nID_Protected(валидным и невалидным). Например отправляя запрос следующего типа 
https://test.region.igov.org.ua/wf/service/rest/tasks/removeTask?nID_Protected=123&sLogin=kermit
в ответ получила 200ОК с текстом "[]".
Такой же ответ пришел и при подстановке этих двух nID_Protected - 5275131+5 и 6997505+9.

**Comment by tivv** [comment]
А точно DELETE? Я только что попробовал `curl   -X DELETE https://test.region.igov.org.ua/wf/service/rest/tasks/removeTask?nID_Protected=123&sLogin=kermit` получил `{"code":"BUSINESS_ERR","message":"CRC Error"}`
Просто по GET оно будет выдавать 200 []

**Comment by OlgaKotova** [comment]
@tivv блин... а я посмотрела, что метод removeTask и подумала, что наверное нужно было get-ом удалять, думала, что существует метод для удаления(перед этим тестила сервис, где удаление было методом get). Тогда все остается на своем месте... 
Только что перепроверила методом DELETE, вопрос остается тот же:
при тестировании верного nID_Protected(как я поняла из подстановки - это тот nID_Protected, который не дает 403 ошибку), в ответ приходит ошибка 500 Internal Server Error c сообщением - {"code":"SYSTEM_ERR","message":"The task cannot be deleted because is part of a running process"}.

**Comment by RoOmel** [comment]
Сценарий:
1) По ссылке
https://test.region.igov.org.ua/wf/service/rest/tasks/kermit
в списке задач поиском нашёл номер (например 5275131) с значением параметра processInstanceId
2) С помощью онлайн Алгоритм Луна
http://planetcalc.ru/2464/
Преобразовал найденный номер в nID_Protected (например 52751315)
3) Проверил nID_Protected запросом
https://test.region.igov.org.ua/wf/service/rest/tasks/getTasksByOrder?nID_Protected=52751315
Получил ответ
[
    "5275181"
]
4) Отправил запрос методом DELETE
https://test.region.igov.org.ua/wf/service/rest/tasks/removeTask?nID_Protected=52751315&sLogin=kermit
Получил ответ
{
    "code": "SYSTEM_ERR",
    "message": "The task cannot be deleted because is part of a running process"
}
Пробовал задачи с другими номерами - тоже самое.

**Comment by BorisEfimenko** [comment]
Извините, что вмешиваюсь...
А для чего предполагается использовать данную функциональность?
В каком состоянии будет находиться процесс, если удалить из него текущую задачу? Он же не перейдет на предыдущую и сгенерирует новую. Процесс зависнет.
А если убить уже выполненную задачу из предыдущих этапов - то это кроме путаницы при разборе полетов ничего не даст.
И, удаление задачи не меняет сохраненные этой задачей переменные в скопе (в т.ч. введенные поля формы usertask).

Если создаваемая функциональность является аналогом "я передумал получать эту услугу через iGov", то это реализуется через runtimeService.deleteProcessInstance. 

И, в реальном мире, не каждый процесс, который человек запустил, он может сам остановить. Так что имеет смысл подумать относительно сохранения, в таких случаях, в переменных процесса переменной isDuncanMacLeodProccess, после установки которой запрещать удалять этот процесс.

**Comment by OlgaTurenko** [comment]
Вмешивайтесь-вмешивайтесь :)

Судя по сервису, который предоставили для написания обертки: http://www.activiti.org/userguide/#_delete_a_process_instance мы удаляем весь процесс целиком, а не таску. (не смотря на текст задачи, так как там действительно речь о таске)

**Comment by BorisEfimenko** [comment]
Судя по коду, там taskService.deleteTasks, а не  runtimeService.deleteProcessInstance.

**Comment by RoOmel** [comment]
Я так понял, что данную задачу надо снять с тестирования, т.к. сама концепция постановки подлежит сомнению.

**Comment by OlgaTurenko** [comment]
Э... тогда плохи дела. Совершенно согласна, что удалять задачи - очень сомнительное действие. Сняла лейбл тест. В рамкках задачи действительно ожидалось удаление всего процесса целиком.    Нужно получается докрутить... Тоесть в рамках задачи удалять весь процесс.

**Comment by tivv** [comment]
@bvv4ik Можете подтвердить изменение формулировки задачи?

**Comment by OlgaTurenko** [comment]
Добрый день! Владимир в отпуске :) Отдыхает. Я с ним этот вопрос обсудила, он подтвердил, что речь шла об удалении процесса всего. Подразумивал в задаче это.

**Comment by tivv** [comment]
Ok, переделаю.

**Comment by OlgaTurenko** [comment]
Добрый день! Подскажите, пожалуйста, как дела обстоят с этой задачкой?

**Comment by tivv** [comment]
Переделал. 
Новый формат вызова: curl -X DELETE https://test.region.igov.org.ua/wf/service/rest/delete-process?nID_Protected=47529212&sLogin=kermit
Добавился необязательный параметр sReason - причина удаления. Передается в activiti и как часть сообщения в history

**Comment by RoOmel** [comment]
Сценарий:
1) По ссылке
https://test.region.igov.org.ua/wf/service/rest/tasks/kermit
в списке задач поиском нашёл номер (например 5275131) с значением параметра processInstanceId
2) С помощью онлайн Алгоритм Луна
http://planetcalc.ru/2464/
Преобразовал найденный номер в nID_Protected (например 52751315)
3) Проверил nID_Protected запросом
https://test.region.igov.org.ua/wf/service/rest/tasks/getTasksByOrder?nID_Protected=52751315
Получил ответ
[
"5275181"
]
4) Отправил запрос методом DELETE
https://test.region.igov.org.ua/wf/service/rest/delete-process?nID_Protected=52751315&sLogin=kermit&sReason=Test
Получил ответ
{
200 OK
}
5) Повторно проверил nID_Protected запросом
https://test.region.igov.org.ua/wf/service/rest/tasks/getTasksByOrder?nID_Protected=52751315
Получил ответ
{
    "code": "BUSINESS_ERR",
    "message": "Record not found"
}
Реализовано согласно ТЗ
