### ISSUE TITLE
Доработать сервис бэка явы getServicesTree так, чтоб фильтр по региону включал также услуги общенациональные...

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#884]

**Comment by VadimGulich** [comment]
Уточните как и где проверять задачу , для оперативной проверки нужно конкретное описание

**Comment by OlgaTurenko** [comment]
На портале гражданина при выборе любого региона в списке всегда должны быть общенациональные услуги. пока такая услуга одна на тестовом: https://test.igov.org.ua/service/654/general   "Отримання субсидії на оплату житлово-комунальних послуг"
