### ISSUE TITLE
Проставить Сонар для проверки кода Java

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#886]
Поставить sonarqube на какой то свободный сервак tech.igov.org.ua

**Comment by bvv4ik** [comment]
https://sonar.igov.org.ua

**Comment by bvv4ik** [comment]
@brunneng  прошу проверить и подтвердить/опровергнуть нормальную его работоспособность

**Comment by brunneng** [comment]
Работает!

**Comment by bvv4ik** [comment]
Спасибо всем, коллеги!
