### ISSUE TITLE
Реализовать на главном портале возможность заполнять заявки от имени гражданина, референтность

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#888]
1) Выглядеть это должно так:
https://docs.google.com/document/d/1H5Vg6fxvMtmY84jdyg6VCWSEkBi-v93yelUx7RhMLpc/edit

2) при нажатии чекбокса значения в полях с ФИО должны переноситься в поля сверху а из исходных полей они должны убираться (там всего три поля с ФИО)

3) при переходе в режим референта, все поля, ИД которых начинаются с "bankId" должны отчищаться и становиться редактируемыми

**Comment by bvv4ik** [comment]
Коллеги, ка оказалось - не работает (выяснилось на боевом), когда отмечен чекбокс

пришлось даже специально скрыть этот чекбокс, чтоб на боевом его не отмечали, и не писалась ошибка..

прошу максимально тщательно оттестировать и пофиксить

**Comment by bvv4ik** [comment]
сделал видимым чекбокс

**Comment by kurbpa** [comment]
@bvv4ik 
@nazarenkod 
на альфе работает нормально.

**Comment by msvidran** [comment]
@bvv4ik 
@nazarenkod 
Отрабатывает, если не прикреплять файлы. Если встречаются процесс где нужно прикрепить файл - то файл не прикрепляется.
Тестировал на услуге соцпомощи https://test.igov.org.ua/service/774/general

**Comment by VadimGulich** [comment]
Нормально отработало на альфе

**Comment by msvidran** [comment]
@VadimGulich отрабатывет только в том случае если не прикреплять файл. 
Шаги:
1. Поставить галочку в чекбоксе "Заповнення референтом"
2. Заполнить все поля
3. Прикрепить файл

Файл не прикрепляется
Если не заполнять от имени референта - файл прикрепляется.

**Comment by VadimGulich** [comment]
По этой услуге https://test.igov.org.ua/service/774/general вроде норм подал с референтом

**Comment by Sokhatsky** [comment]
Послуга https://test.igov.org.ua/service/774/general , якщо подаєш перший раз з референтом, то проходить. Якщо подаєш другий раз з референтом може проходить,а може і не проходити.
Послуга https://test.igov.org.ua/service/1414/general однозначно не проходить з референтом і без. 
Додання файлу в послугах є обов'язковим (інакше послугу не замовити).
Якщо входити в послугу під профілем Дубілет, то чекбокс є в наявності. Якщо ж входити під власним профілем - чекбокс відсутній.
В послузі https://test.igov.org.ua/service/1414/general не відбувається сортування країн, які починаються на букви Є та І.

**Comment by Sokhatsky** [comment]
Послуга працює. Але сортування країн, які починаються на букви Є та І не відбувається. Баг репорт на цю помилку заведений беклогі
