### ISSUE TITLE
На бэке wf-base реализовать учет индекса регионального сервера, в т.ч. при работе с сущностью HistoryEvent_Service

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#889]
- [x] 1) добавить в проперти-файл AS.propertyies параметр: "general.nID_Server=0"
и в классе generalConfig реализовать его поддержку (в т.ч гетеры и сетеры)
ВАЖНО: если параметра "general.nID_Server" в пропертях обнаружено не будет, то метод класса "generalConfig" должен по дефолту возвращать "0"

 - [x] 2) в классах работы с сущностью HistoryEvent_Service
2.1) добавить два поля:
 - [x] 2.1.1) sID_Order - обязательный - уникальный
- этот параметр уже может содержать в себе значение вида "2-6546553", где то что до дефиса - этот ИД сервера, а то что после, фактически nID_Protected (т.е. ИД процесса активити, с добавлением с права цифры(контрольной суммы) , по алгоритму Луна)
Первично в это поле занести все значения из nID_Task. с добавлением туда вначале "0-".

 - [x] 2.1.2) nID_Server - опциональный
- этот параметр ИД сервера

2.2) реализовать унифицированные два метода:
 - [x] 2.2.1) getOrgerByID(String sID_Order)
 - [x] 2.2.2) getOrgerByProcessID(Long nID_Process, nID_Server)
 - [x] 2.2.3) getOrgerByProtectedID(Long nID_Protected, nID_Server)

 - [x] 2.3) при реализации п.2.2, для обратной совместимости проверять - если пришедший ИД-шник  (в параметре sID_Order) не содержит дефиса, то подставлять там слева "0-"

 - [x] 3) реализовать в соответствующих сервисах (гетерах/сетерах) поддержку новых параметров:2.1.1 и 2.1.2, и при передаче параметров в которые использовать новые методы по п.п.2.2

 - [x] 4) в классе org.activiti.rest.interceptor.RequestProcessingInterceptor
задействовать новый параметр и для этого просматривать наличие параметра "nID_Server", которій если отсутствует - считать его равным "0" (по умолчанию)

 - [x] 5) все старые использование методов из других классов - заменить на новые (желательно 2.2.1 или 2.2.2)
Мест там несколько, искать проще по фразе "nID_Protected"

 - [x] 6) Поправить документацию

**Comment by bvv4ik** [comment]
добавил в п.п.1:
ВАЖНО: если параметра "general.nID_Server" в пропертях обнаружено не будет, то метод класса "generalConfig" должен по дефолту возвращать "0"

**Comment by LamronNu** [comment]
дока обновлена.
по сути, везде, где был один параметр nID_Protected, стало три: sID_Order, nID_Protected и nID_Server.
т.е. реализовано с целью "обратной совместимости".
возможные комбинации (в доке написано, но продублирую и здесь):
- только sID_Order, задается в формате ХХХ-ХХХХХ, где первая часть -- это ид сервера (число), потом черточка-дефис, потом nID_Protected (зашифрованое ид задачи активити). также дописано, что если черточки нету, то впереди дописывается "0-" (по сути, это как вариант "только nID_Protected") 
- только nID_Protected -- по "старому образцу", nID_Server проставляется как 0.
-  nID_Protected и nID_Server

сейчас все заявки хранятся на 0-сервере, поэтому при подстановке других серверов будут ошибки вида "Record with nID_Server=%s and nID_Process=%s not found!"

для теста нужно проверить по вышеуказанным комбинациям следующее:
1) работоспособность обновленных сервисов add, update и get обьектов событий по услугам, [ссылка на доку]  (https://github.com/e-government-ua/i/blob/test/docs/specification.md#17_workWithHistoryEvent_Services)

2) работоспособность сервисов по уточнению полей: [setTaskQuestions](https://github.com/e-government-ua/i/blob/test/docs/specification.md#38_setTaskQuestions) и  [setTaskAnswer](https://github.com/e-government-ua/i/blob/test/docs/specification.md#39_setTaskAnswer), а именно в части сохранения события по услуге (подробнее в этом комменте: https://github.com/e-government-ua/i/issues/808#issuecomment-144450238, пункт 1. т.е. нужно просто убедиться, что событие сохраняется (его потом можно "найти" по get) и сами сервисы по уточнению не "поломались".

3) работоспособность сервиса по фидбеку [setMessage](https://github.com/e-government-ua/i/blob/test/docs/specification.md#12_workWithMessages), а именно в части проставления оценки задаче.

если будут вопросы или неточности где-то -- пишите сюда, будем разбираться)

**Comment by RoOmel** [comment]
sID_Order задается в формате ХХХ-ХХХХХ, где первая часть -- это ид сервера (число)
Вопрос: где можно узнать ид сервера (число), чтобы протестировать подставляя разные параметры?

**Comment by LamronNu** [comment]
сейчас, насколько я знаю, только один сервер -- "основной", который по умолчанию 0.
другие ид-шки будут, когда запустятся другие сервера (вроде киевский в планах), но когда это будет -- не подскажу..
на другие номера сейчас, по идее, должно только "ругаться", что такой записи нету

**Comment by RoOmel** [comment]
Спс, понял, тестирую.

**Comment by RoOmel** [comment]
Протестировал подстановку всех параметров.
Реализовано согласно ТЗ.
