### ISSUE TITLE
Доработать сервис getServicesTree так, чтоб при упоминании в параметре-фильтре saID_Place_UA - ид-шек регионов, включать в выборку в т.ч. и все связанные с этим регионом города, и т.д. + сразу перевести работу на унифицированный обьект Place (вместо разрозненных City & Region)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#898]
так-же, везде, где в бэке будут использоваться старые обьекты Region & City - позаменять их на новый унифицированный Place
ВАЖНО: За исключением
- вывода этих объектов в сервисе getPlaces,
- в самой сущности ServiceData
 (пока что, для обратной совместивости, и как только переведем полностью фронт - избавимся от нее окончательно)

**Comment by brunneng** [comment]
По сути изменения затронули одно место. 
/services/getServicesTree
поиск по параметру asID_Place_UA
Протестируйте пожалуйста согласно документации по rest api для этого сервиса.

**Comment by nazarenkod** [comment]
Протестировано согласно документации
