### ISSUE TITLE
Сервис getFlowSlotDepartments 

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#899]
1) Параметры:
sID_BT - строка-ИД БизнесПроцесса, по которому находить записи сущности Flow_ServiceData
2) Отдавать массив объектов SubjectOrganDepartment
3) дописать документацию на вики

**Comment by taaraora** [comment]
Добавил описание ресурса - https://github.com/e-government-ua/i/issues/899

**Comment by nazarenkod** [comment]
Работает согласно описанию
