### ISSUE TITLE
S5 - Ошибка в слове пропозиції

### ISSUE THREAD

**Issue by NikitaLyah** [e-government-ua/i#902]
В футере сайта в разделе "Зауваження та пропозиції" в слове "пропозіції" нужно изменить букву на "пропозИції"
![screenshot_3](https://cloud.githubusercontent.com/assets/12964328/10604098/dcb41bca-772a-11e5-967e-0f0d513853c2.jpg)

**Comment by VadimGulich** [comment]
исправлено на тестовом
