### ISSUE TITLE
S3 - Не работает кнопка "Зберегти"

### ISSUE THREAD

**Issue by NikitaLyah** [e-government-ua/i#903]
Шаги:
1. Зайти в любую не запущенную услугу
2.В поле "Залиште свій email. Ми Вас поінформуємо, як тільки ця послуга буде доступна"  ввести email
3. Нажать кнопку "Зберегти"

Фактический результат:
По нажатию на кнопку ничего не происходит
![screenshot_4](https://cloud.githubusercontent.com/assets/12964328/10604248/ca8fd32a-772b-11e5-97a9-af8cd21ef04e.jpg)

Ожидаемый результат:
Почта сохраняется

**Comment by bvv4ik** [comment]
давно работает
