### ISSUE TITLE
Реализовать интеграцию iGov и ГРИС по оказанию услуг

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#906]
- [ ] 1) Будет один унифицированный БП, со стандартным набором полей:
https://docs.google.com/spreadsheets/d/1rRcuLgaJrC4RW2VAZ_96ZUaMxFgK3-ilYkNlRz9i1lA/edit#gid=0
Для тестирования БП:
https://test.igov.org.ua/service/1394/general
id БП - _test_gris

- [ ] 2) У нас на дашборде будет кнопка "Отправить в ГРИС"(именно для этого БП), при клике на который через сервис Сережи Жук-а оно будет отсылаться в ГРИС и получаться уникальный ИХ номер заявки (в т.ч. сохраняться у Сережи Жук-а в базе связка нашего номера и их)

- [ ] 3) Сервер Сережи Жук-а еженочно будет дергать их сервис и проверять измененность заявки, а как только она окажется отработанной - будет в наш сервис передавать итог, и таким образом отрабатывать таску.

**Comment by kurbpa** [comment]
https://test.igov.org.ua/service/1394/general - ссылка на процесс на альфе.
id  БП - _test_gris

**Comment by BorisEfimenko** [comment]
Хотелось бы больше подробностей.

**Comment by OlgaTurenko** [comment]
Для начала вам надо будет дернуть вот за это
http://10.56.0.214:29927/Translator/services
получите список услуг GRIS-ов
Вам нужно будет у себя провести соответствие ваших ID  - услуг и ID услуг
грисов.
Я естественно буду ждать ID услуг грисов, договаривались что в протоколе
это будет serviceNumber

Для подачи заявки сначала необходимо пройти авторизацию на BankId и
получить токен
Затем(как и в BankId) с токеном и вашим clientId  в заголовке
"Authorization", "Bearer 13642001-9f31-43f2-8d7a-16045967b1c3, Id
9b0e5c63-9fcb-4b11-84ff-31fc2cea8801"
идете сюда
http://10.56.0.214:29927/Translator/checked/sendClaim
в теле вот что
{
   "total":0,
   "start":0,
   "size":0,
   "data":[
      {
         "formProperties":[
            {
               "claimNumber":"1234567",
               "serviceNumber":"32",
               "bankIdfirstName":"Petr",
               "bankIdmiddleName":"Petrovich",
               "bankIdlastName":"Petrenko",
               "bankIdPassport":"AE 6878435487",
               "bankIdemail":"petr@mail.ua",
               "bankIdphone":"+38065454654"
            }
         ]
      }
   ]
}

(Кстати там добавил еще поля в гоглдоке bankIdPassportIssue,
bankIdPassportDate, bankIdInn )

Ответ положительный
{"Data":123,"ErrorMessage":"No data to process","ErrorID":3}
"Data":123 - реф грисов

Ответ отрицательный если проблемы с токеном
{"error":"access_denied","error_description":"Access is denied"}

Ответ отрицательный если ошибка от грисов
{"state":"err","code":"GRIS02","desc":"Помилка при надсиланнi заявки No
data to process"}

2015-11-05 23:08 GMT+03:00 BorisEfimenko <notifications@github.com>:

**Comment by OlgaTurenko** [comment]
По поводу авторизации по банк-ид... ведем переговоры что-бы отказаться от
такой авторизации, так как это лишние переходы и ввод лишних данных...

6 ноября 2015 г., 0:53 пользователь Olga Kuzminova <
olga.kuzminova87@gmail.com> написал:

**Comment by lesha1980** [comment]
Нет коннекта к http://10.56.0.214:29927/Translator/services : Connection timed out: connect

**Comment by lesha1980** [comment]
А каков ID приложения iGov на BankID? Ведь он нужен для прохождения авторизации и получения кода подтверждения, который, насколько я понимаю, должен быть обменен на токен, который, в свою очередь, должен быть использован для дальнейшей работы...

**Comment by OlgaTurenko** [comment]
Приложение igov еще не регистрировали на стороне комплекса-посредника между
нами и ЦНАП.

7 ноября 2015 г., 20:17 пользователь lesha1980 <notifications@github.com>
написал:

**Comment by lesha1980** [comment]
Извините. А что тогда указано вами в следующем:

"Bearer 13642001-9f31-43f2-8d7a-16045967b1c3,
 Id 9b0e5c63-9fcb-4b11-84ff-31fc2cea8801"

под id? И в примере получения запроса в документации по авторизации через BankID в виде параметра client_id = dniprorada? Это лишь примеры не относящиеся к сути дела? Я правильно понимаю? Тогда получить токен еще нельзя...А как же тогда функционирует авторизация через BankID здесь https://test.igov.org.ua/service/1394/general? Я пока чего-то недопонимаю.

Ведь здесь авторизация проходит, а значит какой-то id-шник есть, чтобы получить код подтверждения от сервера авторизации и обменять его на токен...

**Comment by BorisEfimenko** [comment]
![_test_gris_recomended](https://cloud.githubusercontent.com/assets/15231644/11119165/47995428-8950-11e5-91f6-37200963401f.png)
На рассмотрение. 
Вариант, как задачу можно сделать средствами activiti, без дополнительной кнопки на фронтэнде. Слабые места: я пока не знаю,  как пройти авторизацию. В случае, если от удаленного сервера нет ответа по заявке, а хочется заявку в ручную обработать, все равно нужно будет писать кнопку "Отменить ожидание обработки в ГРИС"

В любом случае, чтобы начать писать, необходимо уточнить эти вещи:

1. Как проходит авторизация в обе стороны (ГРИС же нам тоже должен отсылать информацию о закрытых задачах. Как мы идентифицируем, что это нужный нам сервер данные посылает?). 
2. Вместо адресов типа http://10.56.0.214:29927/Translator/services поставить реальные адреса (не 10-я сетка).

**Comment by lesha1980** [comment]
Все верно. На одном сервере проходит авторизация, где клиент получает токен. А уже с этим токеном он может выполнять задачи обращаясь к другому серверу. Но чтобы получить токен, приложение должно быть зарегистрировано в том сервисе, чьи услуги собирается использовать, так как по клиентскому id получает идентификатор, который и обменивается на токен...

**Comment by bvv4ik** [comment]
в каком состоянии сейчас таска?

**Comment by bvv4ik** [comment]
@BorisEfimenko

**Comment by bvv4ik** [comment]
я так понимаю, раелизация была по этой таске?
https://github.com/e-government-ua/i/issues/956
