### ISSUE TITLE
Реализовать в сервисе получения таймингов по таскам  (/file/download_bp_timing) - механизм "настраиваемых полей"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#907]
- [x] 1) так-же, как и в сервисе /file/downloadTasksData добавить опциональный параметр saFields, который может содержать список полей и формул их расчета (разделенные точкой с запятой). Итоги которых должны добавляться как доп-поля итоговой отдаваемой таблицы

- [x] 2) формат каждого элемента поля такой(на примере):
"nAccepted=(nMinutes>&&sAssignedLogin!=null?1:0)"
где:
- nAccepted - название того поля, которое получит итоговое вычисленное значение
"nMinutes>&&bAssigned=true?1:0" - это та формула, которая должна вычислиться
- nMinutes - переменная, которая хранит в себе значение уже существующего или посчитанного поля формируемой таблицы
- sAssignedLogin - переменная, хранящая в себе системное значение (в данном случае догин сотрудника, на которого ассайнута юзертаска, о которой будет написано ниже)

- [x] 3) Вычисление формулы должно произвожиться методами js, как это реализовано при эскалации(пример):
Класс: org.wf.dp.dniprorada.base.service.escalation.EscalationHelper
Метод:
private boolean getResultOfCondition(Map<String, Object> jsonData,

- [x] 4) Создать системные переменные, участвующие в вычислениях:
- [x] 4.1) "sAssignedLogin" - в которую нужно сохранять логин ассайнутого сотрудника на обрабатываемую юзертаску
- [x] 4.2) "sID_UserTask" - в которую нужно сохранять ИД юзертаски

- [x] 5) В итоге, параметр saFields может содержать примерно такое значение:
"nAccepted=(nMinutes>&&sAssignedLogin!=null?1:0);nCount=(sID_UserTask='usertask1'?1:0);nRejected=(sSolution='reject1'?1:0)"
и это добавит вконце таблиці такие поля(колонки): nAccepted;nCount;nRejected
с соответствующими вычеслинными значениями

- [x] 6) Дописать доку на вики

**Comment by ASkosyr** [comment]
Добавил описание задачи

https://github.com/e-government-ua/i/blob/test/docs/specification.md#16_getWorkflowStatistics

**Comment by RoOmel** [comment]
Сведение полей тестировал ранее.
Без проверки параметров saFields, saFieldSummary
Реализовано согласно ТЗ
