### ISSUE TITLE
Добавить вспомогательную сущность FlowLink связанную с Flow_ServiceData, и доработать сервис /getFlowSlots_ServiceData

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#908]
- [x] 1) поля сущности:
nID - ИД-номер уникальный
nID_Flow_ServiceData - ИД-номер 
nID_Service - ИД-номер сервиса //опциональный

- [x] 2) в сервис добавить поле:
nID_Service - ИД-номер сервиса //опциональное
при задаче которого, и нахождении по нему хотя-бы одной записи, подтягивать по его nID_Flow_ServiceData - соответствующий элемент сущности
иначе искать по существующему алгоритму...

- [ ] 3) поправить документацию

**Comment by OlgaKotova** [comment]
@bvv4ik А какие доработки должны были быть с сервисом getFlowSlots_ServiceData? Опишите, пжл, подробнее задачу для тестирования.
Сейчас я отправляю запрос(пример из вики по сервису) https://test.igov.org.ua/wf/service/flow/getFlowSlots_ServiceData?nID_ServiceData=1 и получаю в ответ - {"aDay":[]} -  со статусом 200ОК.

Если честно, не очень понимаю, что это за параметры и где их брать?

    nID_ServiceData - ID сущности ServiceData (обязательный если нет sID_BP)
    sID_BP - строка-ИД бизнес-процесса (обязательный если нет nID_ServiceData)
    bAll - если false то из возвращаемого объекта исключаются элементы, содержащие "bHasFree":false "bFree":false (опциональный, по умолчанию false)
    nDays - колличество дней от сегодняшего включительно(или sDateStart, если задан), до nDays в будующее за который нужно вернуть слоты (опциональный, по умолчанию 177 - пол года)
    nFreeDays - дни со слотами будут включаться в результат пока не наберется указанное кол-во свободных дней (опциональный, по умолчанию 60)
    sDateStart - опциональный параметр, определяющие дату начала в формате "yyyy-MM-dd", с которую выбрать слоты. При наличии этого параметра слоты возвращаются только за указанный период(число дней задается nDays).

**Comment by RoOmel** [comment]
При запросе
https://test.region.igov.org.ua/wf/service/flow/setSheduleFlowInclude?nID_Flow_ServiceData=1&sName=Вечерний прием&sRegionTime=14:00-17:00&sDateTimeAt=2015-06-01 19:00:00&sDateTimeTo=2015-10-30 23:00:00&saRegionWeekDay=mo-fri&nID=&nLen=&sLenType=&sID_BP=dnepr_subsidies

сервер возвращает ответ
{
    "sData": null,
    "bExclude": false,
    "sName": "Вечерний прием",
    "sRegionTime": "14:00-17:00",
    "saRegionWeekDay": "mo-fri",
    "sDateTimeAt": "2015-06-01 19:00:00",
    "sDateTimeTo": "2015-10-30 23:00:00",
    "nLen": null,
    "sLenType": "",
    "nID": 37932,
    "nID_FlowPropertyClass": {
        "sPath": "org.wf.dp.dniprorada.base.service.flow.propertyHandler.DefaultFlowSlotScheduler",
        "sBeanName": "defaultFlowSlotScheduler",
        "nID": 1,
        "sName": "DefaultFlowSlotScheduler"
    }
}

**Comment by Koffeek** [comment]
Задача работает согласно описанию. Спасибо.
