### ISSUE TITLE
Сделать удобный инсталлятор окружения

### ISSUE THREAD

**Issue by elcreator** [e-government-ua/i#912]
С учетом того, что планируется привлекать новичков, а поддержка в плане первичной настройки энвайрмента практически отсутствует, нужно сделать удобный инсталлятор пакетов нашего приложения. Буду опираться на следующие требования:
- наглядность прогресса установки. Если что-то зафейлилось в процессе инсталляции - должно быть сразу видно, что именно. Сама инсталляция по возможности продолжается.
- инсталлятор должен работать по возможности независимо от того, стоят у пользователя те или иные пакеты, или нет. Повторный запуск также не должен ничего ломать - а при изменении версий - еще и апдейтить.

Начал работу в отдельном репозитории, чтобы не затрагивать существующую файловую структуру. Планирую сделать всю конфигурацию приложения, включая копирование конфигфайлов, отдельно от установщика самих пакетов.

https://github.com/elcreator/egov-ua-devops/blob/master/ubuntu/package-installer.sh - рабочий вариант инсталлятора пакетов под Ubuntu.

**Comment by bvv4ik** [comment]
дело в том, что самые значительные сложности у нас как раз при инсталляции на винде...

кроме того, у нас есть Vagrant, и в нем предусмотрена тоже полная установка всего(отрабатывали установку всех проектов)... беда в том, что его так и не довели до ума... т.е. в ряде случаев он не отрабатывает до конца.

и главное: нужно актуализировать и минимизировать видеоролики по полному процессу установки..

потому предлагаю просто довести до ума его, вместо того чтоб опять с нуля что-то делать..
(т.к. по ниму и доки написаны и видео есть и у ряда людей он вполне работает)

**Comment by elcreator** [comment]
Я предлагаю просто давать ссылку на скачивание бесплатного VMware player (есть и под Linux, и под Windows)
https://my.vmware.com/web/vmware/free#desktop_end_user_computing/vmware_workstation_player/12_0|PLAYER-1200|product_downloads
и на дистрибутив Ubuntu, который используется у нас
http://releases.ubuntu.com/14.04/ubuntu-14.04.3-server-amd64.iso
Скачать плеер и установить Ubuntu несложно, можно краткое видео сделать.

А дальше просто в WebStorm указываем IP виртуалки, логин/пароль, которые при установке ввели, папку для закачивания делаем /project - и все.
WebStorm закачает репозиторий в папку /project, и будет автоматически закачивать любые изменения в файлах.
Однажды только нужно зайти на виртуалку и запустить инсталлятор, о котором тут речь.

**Comment by elcreator** [comment]
Отличие от текущего решения в том, что никаких shared папок между хостовой и виртуальной машиной тут нет.
То множество проблем, с которыми сталкивается пользователь при попытке поднять наше приложение при помощи Vagrant, имея Windows на хосте (ошибки в Windows 7 и  Windows 10 еще и разные) - в основном связано с некорректной работой с файловой системой. Зафиксить такие вещи на уровне вагрантовских скриптов невозможно в принципе - т.к. они на уровне драйверов файловой системы.

**Comment by bvv4ik** [comment]
но WebStorm только-ж для наших двух проектов NodeJS подойдет.. а ведь у нас еще как минимум wf-base & wf-region - явовские... где в т.ч. томкэт нужен.. а так-же может понадобиться и установка базы PostgresSQL (и даже Redis+Mongo)

**Comment by elcreator** [comment]
Под IDEA есть аналогичный плагин - https://plugins.jetbrains.com/plugin/7374?pr=idea , только что проверил на работоспособность в Windows 10, Idea Community Edition, все нормально заливает. Нужно указать протокол SFTP, адрес и креды, на виртуалке поднимать ничего не надо.
Сами пакеты Tomcat, Redis у меня ставятся, а вот установки Postgres и Mongo ни в вагрантфайле, ни в текущем prepare_machine.sh вообще нет.

**Comment by bvv4ik** [comment]
"а вот установки Postgres и Mongo ни в вагрантфайле, ни в текущем prepare_machine.sh вообще нет."
там может этого и нет, но там это можно допилить... и каая есть этому альтернатива - даже и не знаю..

вообщем, создавать кучу разрозненных инструментов - смысла нет... гораздо ценнее довести до ума один... если кроме вагранта есть еще лучшая альтернатива, которую получится заюзать сразу для всего комплекса преложений - я буду только за...(но только после полной реализации и протестированности мы сможем написать доки, видео и отказатья от предыдущего варианта... и, понятно, если есть желание - прошу, буду/будем только благодарен, если удастся самостоятельно этот участок реализовать "от и до"


но так, рази 1-2х приложений создавать езе один раздел с описаниями - смысла не вижу..

**Comment by elcreator** [comment]
А есть где-то список требуемых на сейчас пакетов, которые должен уметь ставить инсталлятор?
По которому можно было бы делать и сам инсталлятор, и тесты полученного в результате энвайрмента написать.

**Comment by bvv4ik** [comment]
все наше хозяйство, в статье "Наше хозяйство" на вики
если ест ьжелание довести до ума вагрант, чтоб он легко и на винде поднимался и на остальных средах - был-бы благодарен... а так, радикально что-то менять, без перспективы даже получит ь то что уже есть сейчас - смысла не вижу
