### ISSUE TITLE
[S4] Проблема с установкой центрального портала граждан

### ISSUE THREAD

**Issue by edamov** [e-government-ua/i#914]
При установке портала согласно [инструкции] (https://github.com/e-government-ua/i/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D1%86%D0%B5%D0%BD%D1%82%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BE%D1%80%D1%82%D0%B0%D0%BB%D0%B0-%D0%B3%D1%80%D0%B0%D0%B6%D0%B4%D0%B0%D0%BD-(central-js,-frontend)) возник ряд проблем:

1) Если запустить файл `/i/central-js/_/_0_install_build_run.sh` не из дериктории, в которой лежит сам скрипт, а из любой другой, то возникнет ошибка:
`./_/_0_install_build_run.sh: line 6: ./_1_build_run.sh: No such file or directory`,
причина которой относительный путь к скрипту `./_1_build_run.sh`  внутри файла `_0_install_build_run.sh`.

2) Если избежать ошибки из п.1 путем запуска скрипта `/i/central-js/_/_0_install_build_run.sh` из той же директории, в которой он находится, то возникают следующие ошибки:
- `./_build.sh: line 3: gem: command not found`
![log1](http://dl1.joxi.net/drive/0004/3622/269862/151024/2a20a1b08d.jpg)

- `grunt-cli: The grunt command line interface. (v0.1.13)
Fatal error: Unable to find local grunt.`
![log2](http://dl2.joxi.net/drive/0004/3622/269862/151024/7c60de3b5b.jpg)

**Comment by bvv4ik** [comment]
запускать скрипт нужно находясь в этой папке со скриптом... (это нормально)
а относительные пути там стоят потому что у каждого на компьютере они все разные.

**Comment by edamov** [comment]
Предлагаю указать это в вики (так как не совсем очевидно это), либо нашел следующее [решение](http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in?rq=1):
в скрипте в котором вызывается другой скрипт достаточно написать `cd $(dirname $0)` перед непосредственным вызовом, т.о. будет корректная текущая директория, относительно которой можно запускать скрипты.

**Comment by bvv4ik** [comment]
ну такое не пишут)
и так понятно, что папку в которой идет попытка запуска нужно делать выбранной)

а если уже человек хочет на базе существующих скриптов писать свои(обобщающие), то он-то уж должен разбираться как это работает, и что перед запуском скрипта нужно вначале войти в эту папку (cd $(dirname $0))

такие пояснения только будут загромождать вики...

**Comment by edamov** [comment]
Хорошо, по первому пункту ясно. А со вторым я так и не разобрался...

**Comment by bvv4ik** [comment]
по п.2
ну явно на компе не проставлен какой-то компонент, согласно инструкции на вики

**Comment by edamov** [comment]
вы эту [инструкцию] (https://github.com/e-government-ua/i/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D1%86%D0%B5%D0%BD%D1%82%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BE%D1%80%D1%82%D0%B0%D0%BB%D0%B0-%D0%B3%D1%80%D0%B0%D0%B6%D0%B4%D0%B0%D0%BD-(central-js,-frontend)) имеете ввиду?

**Comment by elcreator** [comment]
gem: command not found
это глюк в инсталляторе, аналогично воспроизводился и у меня. 
https://github.com/elcreator/egov-ua-devops/blob/master/ubuntu/package-installer.sh посмотрите решение, начиная с 74 строки. Там доставляется актуальная версия nodejs и npm, затем ставится корректная версия инсталлятора руби, и команда становится доступной.

**Comment by elcreator** [comment]
Также нужно предварительно удалить существующие nodejs и npm.

**Comment by bvv4ik** [comment]
я так понял - все норм
