### ISSUE TITLE
На базе примеров существующих сервисов - скомпоновать отдельный сервис, проверяющий наличие наложенной ЭЦП на атаче-файле, и отдающий объект с ее описанием.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#915]
- [x] 1) в сервисе download_file_from_db найти участок, который получает контент файла

- [x] 2) в сервисе setDocumentFile найти участок, который получает soSignData, по результатам проверки контента файла (п.1)

- [x] 3) написать сервис checkAttachSign, который будет принимать параметры:
nID_Attach - номер-ИД файла-атача (активити)
nID_Task - номер-ИД таски (активити)
и отдавать объект с подписью:
soSignData
или, если подписи нет возвращать в нем "{}"

- [x] 4) Написать доку в вики

**Comment by taaraora** [comment]
Добавил описание - https://github.com/e-government-ua/i/blob/test/docs/specification.md#43_check_attachment_sign

**Comment by RoOmel** [comment]
Сервис работает, но для проверки работы необходимо :
1) Ответ для существующей таски (nID_Task)
Для проверки нужны nID_Task и nID_Attach заведомо корректные;

2) Ответ для несуществующего атачмента (nID_Attach)
Проверить будет несложно после выполнения п. 1;

3) Ответ для атачмента который не имеет наложеной ЭЦП
Для проверки нужен атачмент который не имеет наложеной ЭЦП

**Comment by bvv4ik** [comment]
@taaraora и @GrekD - прошу помочь примером для теста...

**Comment by taaraora** [comment]
@RoOmel 

Можно создать услугу: https://test.igov.org.ua/service/720/general
(при ее заполнении будет видно: скан паспорта:
Завантажено із BankID... так вот он с ЭЦП как раз)

и зайти в дашбоард потом: https://test.region.igov.org.ua
под: tester/tester
найдя там эту заявку (по ее номеру, который после сабмита формы будет) - выбрать ее в списке..

справа она откроется...
и вконце(внизу) будет видно атачи, в т.ч. скан паспорта (он с ЭЦП)

кликнуть на него, для загрузки
при этом в фаербаге будет виден запрос этого атачмента, и в этом запросе будет в т.ч. id таски и ид атача

**Comment by nazarenkod** [comment]
"справа она откроется...и вконце(внизу) будет видно атачи, в т.ч. скан паспорта (он с ЭЦП)"
не вижу файла аттача
![clip2net_151202141005](https://cloud.githubusercontent.com/assets/13256486/11530584/71ae91ac-98fe-11e5-87f2-a1ffc4f0aec3.jpg)

**Comment by taaraora** [comment]
@RoOmel если ещё есть вопросы, давайте спишемся в скайп, так будет быстрее, мой скайп taaraora.

**Comment by RoOmel** [comment]
При запросе
https://test.region.igov.org.ua/wf/service/rest/file/check_attachment_sign?nID_Task=6092647&nID_Attach=6092649
получил ответ от сервера  3-мя блоками данных.
Вопрос: по какому из параметров мне должно быть ясно, что копия защищена ЭЦП?

**Comment by taaraora** [comment]
А блок signatureData присутствует, он заполнен информацией об подписи?

**Comment by RoOmel** [comment]
Да блок signatureData присутствует и заполнен данными
"signatureData": {
            "name": "АЦСК ПАТ КБ «ПРИВАТБАНК»",
            "serialNumber": "0D84EDA1BB9381E80400000079DD02004A710800",
            "timestamp": "08.10.2015 13:16:21",
            "code": true,
            "desc": "ПІДПИС ВІРНИЙ",
            "dateFrom": "13.08.2015 11:24:31",
            "dateTo": "12.08.2016 23:59:59",
            "sn": "UA-14360570-1"
        }

**Comment by RoOmel** [comment]
Задача реализована согласно ТЗ.
