### ISSUE TITLE
Реализовать в сервисе получения таймингов по таскам  (/file/download_bp_timing) - механизм "одноуровневое сведения полей" (как в Экселе)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#916]
- [ ] 1) так-же, как и в сервисе /file/downloadTasksData добавить опциональный параметр saFieldSummary, который может содержать список сводимых полей и правил их расчета (разделенные точкой с запятой). Результат по которым должен выводиться вместо обычного списка строк с исходными данными, в итоговой отдаваемой таблице
ВАЖНО:
- если параметр "saFieldSummary" не задан, то отрабатывать формирование и отдачу исходного списка, как обычно.
- тот элемент, который задан первым в параметре saFieldSummary - является "ключевым полем"

- [ ] 2) формат каждого элемента поля такой(на примере):
"nSum=sum(nMinutes)"
где:
- sum - "оператор сведения"
- nMinutes - переменная, которая хранит в себе значение уже существующего или посчитанного поля формируемой таблицы
- nSum - название поля, куда будет попадать результат

- [ ] 3) полный перечень поддерживаемых "операторов сведения":
count() - число строк/элементов (не содержит аргументов)
sum(fiels) - сумма чисел (содержит аргумент - название обрабатываемого поля)
avg(field) - среднее число (содержит аргумент - название обрабатываемого поля)

- [ ] 4) Значение "ключевого поля" переносится в новую таблицу без изменений в виде единой строки, и все остальные сводные поля подсчитываются исключительно в контексте значения этого ключевого поля, и проставляютя соседними полями в рамках этой единой строки.

- [ ] 5) В итоге, параметр saFieldSummary может содержать примерно такое значение:
"sRegion;nSum=sum(nMinutes);nVisites=count()"
и это сформирует в итоге таблицу из трех полей(колонок): sRegion;nSum;nVisites
с соответствующими вычеслинными значениями
Напрример:
sRegion;nSum;nVisites
Бабушкинский;435;5
Кировский;343;3

- [ ] 6) Дописать доку на вики

**Comment by LamronNu** [comment]
дока: https://github.com/e-government-ua/i/blob/test/docs/specification.md#16_getWorkflowStatistics

**Comment by LamronNu** [comment]
еще комментарий к тестированию.
сначала подберите БП и выгрузите список задач по нему за определенный период (т.е. запрос без нового параметра saFieldSummary)
я брала _test_queue_cancel, т.к. по нему нашлись задачи.. если возьмете другой БП, будет даже лучше.
потом добавляете новый параметр saFieldSummary со своими условиями -- и сверяете список задач с тем результатом, который у Вас получится.

**Comment by RoOmel** [comment]
Порбовал делать запросы
https://test.region.igov.org.ua/wf/service/rest/file/download_bp_timing?sID_BP_Name=common_mvd_1&sDateAt=2015-06-01&sDateTo=2015-11-01
, согласно доки
https://github.com/e-government-ua/i/blob/test/docs/specification.md#16_getWorkflowStatistics
с разными БП, но каждый раз ответ сервера один и тот же
""nID_Process","sLoginAssignee","sDateTimeStart","nDurationMS","nDurationHour","sName""

**Comment by OlgaTurenko** [comment]
Добрый день! Видимо по этой услуге за данный период нет данных. Попробовала по рекомендованной Ольгой услуге: https://test.region.igov.org.ua/wf/service/rest/file/download_bp_timing?sID_BP_Name=_test_queue_cancel&sDateAt=2015-06-01&sDateTo=2015-11-01   
Данные есть.

**Comment by RoOmel** [comment]
Согласен, по этому БП есть данные.

**Comment by RoOmel** [comment]
При запросе
https://test.region.igov.org.ua/wf/service/rest/file/download_bp_timing?sID_BP_Name=_test_queue_cancel&sDateAt=2015-06-01&sDateTo=2015-11-01
получил ответ
"nID_Process","sLoginAssignee","sDateTimeStart","nDurationMS","nDurationHour","sName","bankIdPassport","bankIdfirstName","bankIdlastName","bankIdmiddleName","biometrical","date_of_visit","date_of_visit1","email","finish","have_passport","initiator","phone","urgent","visitDate"
"5207501","kermit","2015-09-25:12-18-28","1433990","0","обробка дмс","АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002","ДМИТРО","ДУБІЛЕТ","ОЛЕКСАНДРОВИЧ","attr1_no","2015-10-09 09:00:00.00","dd.MM.yyyy HH:MI","nazarenkod1990@gmail.com","attr1_ok","attr1_yes","","38","attr1_no","{""nID_FlowSlotTicket"":27764,""sDate"":""2015-10-09 09:00:00.00""}"
"5215001","kermit","2015-09-25:13-03-29","75259","0","обробка дмс","АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002","ДМИТРО","ДУБІЛЕТ","ОЛЕКСАНДРОВИЧ","attr1_no","2015-10-14 11:15:00.00","dd.MM.yyyy HH:MI","nazarenkod1990@gmail.com","attr1_ok","attr1_yes","","38","attr1_no","{""nID_FlowSlotTicket"":27767,""sDate"":""2015-10-14 11:15:00.00""}"
"5215055","dn200986zda","2015-09-25:13-05-22","1565056","0","обробка дмс","АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002","ДМИТРО","ДУБІЛЕТ","ОЛЕКСАНДРОВИЧ","attr1_no","2015-09-28 08:15:00.00","dd.MM.yyyy HH:MI","dmitrij.zabrudskij@privatbank.ua","attr2_missed","attr1_yes","","38","attr1_no","{""nID_FlowSlotTicket"":27768,""sDate"":""2015-09-28 08:15:00.00""}"
"5215122","kermit","2015-09-25:13-08-27","1303914473","362","обробка дмс","АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002","ДМИТРО","ДУБІЛЕТ","ОЛЕКСАНДРОВИЧ","attr1_no","2015-10-16 10:45:00.00","dd.MM.yyyy HH:MI","nazarenkod1990@gmail.com","attr1_ok","attr1_yes","","38","attr1_no","{""nID_FlowSlotTicket"":27769,""sDate"":""2015-10-16 10:45:00.00""}"
"5250221","kermit","2015-09-25:16-13-53","273295","0","обробка дмс","АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002","ДМИТРО","ДУБІЛЕТ","ОЛЕКСАНДРОВИЧ","attr1_no","2015-10-06 09:30:00.00","dd.MM.yyyy HH:MI","nazarenkod1990@gmail.com","attr2_missed","attr1_yes","","38","attr1_no","{""nID_FlowSlotTicket"":27777,""sDate"":""2015-10-06 09:30:00.00""}"
"5250458","kermit","2015-09-25:16-20-05","139606","0","обробка дмс","АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002","ДМИТРО","ДУБІЛЕТ","ОЛЕКСАНДРОВИЧ","attr1_no","2015-10-06 09:30:00.00","dd.MM.yyyy HH:MI","nazarenkod1990@gmail.com","attr2_missed","attr1_yes","","38","attr1_no","{""nID_FlowSlotTicket"":27777,""sDate"":""2015-10-06 09:30:00.00""}"

При запросе
https://test.region.igov.org.ua/wf/service/rest/file/download_bp_timing?sID_BP_Name=_test_queue_cancel&sDateAt=2015-06-01&sDateTo=2015-11-01&saFieldSummary=sRegion;nSum=sum(nMinutes);nVisites=count()
в ответе только 
"sRegion","nSum","nVisites"

**Comment by LamronNu** [comment]
@RoOmel , у Вас параметр saFieldSummary равен "sRegion;nSum=sum(nMinutes);nVisites=count()", это значит, что нужно группировать по полю sRegion, которого в выборке нету (поля -- это первая строка в csv-файле). поэтому Вы получаете только заголовки в ответе (этот случай я описала в доке).

возьмите группировку по тем полям, которые есть. я брала поле *email* (для этой услуги), т.к. оно есть и имеет несколько значений. также можно попробовать другие колонки, например *bankIdlastName* -- хотя это поле везде одинаковое, т.е. должна быть только одна строка в ответе.

насчет значения других колонок, например, *nSum=sum(nMinutes)*, то поле *nMinutes* также должно существовать, иначе будет "подсчитываться" 0 (в доке написано и про этот случай). тут можно взять поле phone, оно будет считаться "числовым" (потому что там везде 38).

сейчас попытаюсь вспомнить, какой бп я еще брала для теста, т.е. где находила данные.. если вспомню -- отпишусь.

**Comment by LamronNu** [comment]
нашла вот бп-шки, в котором есть записи:
dnepr_subsidies
и 
dnepr_mvd_1

если что, то я "перебирала" бп из файла [EscalationRule.csv](https://github.com/e-government-ua/i/blob/test/wf-base/src/main/resources/data/EscalationRule.csv) , во многих нету задач, но в этих двух я нашла какие-то записи..

**Comment by RoOmel** [comment]
Согласен, при запросе
https://test.region.igov.org.ua/wf/service/rest/file/download_bp_timing?sID_BP_Name=dnepr_subsidies&sDateAt=2015-06-01&sDateTo=2015-11-01&saFieldSummary=email;nSum=sum(nDurationHour);nVisites=count();nAvg=avg(nDurationHour)
явно видно что подсчёт есть 
"email","nSum","nVisites","nAvg"
"LisovoyV@ukr.net","329.0","29","11.344827586206897"
"nazarenkod1990@gmail.com","618.0","4","154.5"
"email@email.com","316.0","3","105.33333333333333"
"msvidran@gmail.com","0.0","1","0.0"
"LisovoyV@i.ua","126.0","2","63.0"
"dmitrij.zabrudskij@privatbank.ua","421.0","9","46.77777777777778"
