### ISSUE TITLE
На базе примеров существующих сервисов - скомпоновать отдельный сервис, проверяющий наличие наложенной ЭЦП на файле(хранящегося в Redis), и отдающий объект с ее описанием.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#917]
- [ ] 1) в сервисе /download_file_from_redis_bytes найти участок, который получает контент файла

- [ ] 2) в сервисе setDocumentFile найти участок, который получает soSignData, по результатам проверки контента файла (п.1)

- [ ] 3) написать сервис checkFileRedisSign, который будет принимать параметры:
sID_File_Redis - номер-ИД файла в Redis
и отдавать объект с подписью:
soSignData
или, если подписи нет возвращать в нем "{}"

- [ ] 4) Написать доку в вики

**Comment by taaraora** [comment]
добавил описание API - https://github.com/e-government-ua/i/blob/test/docs/specification.md#44-Проверка-ЭЦП-на-файле-хранящемся-в-redi

**Comment by RoOmel** [comment]
Сервис работает, но для проверки работы необходимо :
1) Ответ json описывающий ЭЦП
Для проверки нужен sID_File_Redis заведомо корректный 
2) Ответ для несуществующего ключа (sID_File_Redis)
Проверить будет несложно после выполнения п. 1
3) Ответ для файла который не имеет наложеной ЭЦП
Для проверки нужен заведомо без ЭЦП

**Comment by bvv4ik** [comment]
@taaraora и @GrekD - прошу помочь примером для теста...

**Comment by GrekD** [comment]
тестировать можно на услуге
https://test.igov.org.ua/service/1411/general
после заполнения всех полей, внизу поставить чек бокс "накласти ецп" - замовити послугу

зайти в дашборд
https://test.region.igov.org.ua/tasks
логин-пароль:test_eds

сейчас я там создала 1 заявку ее номер
76025452
там есть автосформированный файл с ецп: signedForm.pdf
