### ISSUE TITLE
При отработке правила эскалации (формулы) - добавить еще один системный параметр sLoginAssigned, который должен в себе содержать логин ассайнутого пользователя

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#918]
Класс org.wf.dp.dniprorada.base.service.escalation.EscalationService
Метод: private Map<String, Object> getTaskData(Task oTask) {//Long nID_task_activiti

там так-же задаются другие системные параметры:
nElapsedDays
nElapsedHours
и т.д.

**Comment by bvv4ik** [comment]
теперь можно в файле:
EscalationRule.csv
в каком-либо из правиле, в поле "sCondition" (формуле)
задействовать параметр "sLoginAssigned"
например
вместо:
"nElapsedDays >= nDaysLimit"
написать:
"nElapsedDays >= nDaysLimit && sLoginAssigned == null"
и при 'том посмотреть - отработается-ли 'скалация на не взятую таску (в рамках этого БП и ИД юзертаски, по которым настроено это правило)

**Comment by OlgaKotova** [comment]
@bvv4ik я взяла пример создания правила эскалации из Вики - test.region.igov.org.ua/wf/service/escalation/setEscalationRule?sID_BP=zaporoshye_mvk-1a&sID_UserTask=*&sCondition=nElapsedDays==nDaysLimit&soData={nDaysLimit:3,asRecipientMail:['test@email.com']}&sPatternFile=escalation/escalation_template.html&nID_EscalationRuleFunction=1

1) Создала правило с nID=40675
2) Редактировала его, добавив sLoginAssigned == null (долго не могла понять в чем дело, т.к. sLoginAssigned не добавлялся, оказывается нужно было заменить & на t%26), на выходе получила 
{
    "sID_BP": "zaporoshye_mvk-1a",
    "sID_UserTask": "*",
    "sCondition": "nElapsedDays==nDaysLimit&sLoginAssigned==null",
    "soData": "{nDaysLimit:3,asRecipientMail:['test@email.com']}",
    "sPatternFile": "escalation/escalation_template.html",
    "nID": 40675,
    "nID_EscalationRuleFunction": {
        "sBeanHandler": "EscalationHandler_SendMailAlert",
        "nID": 1,
        "sName": "Отсылка уведомления на электронную почту"
    }
}

3) подскажите, пжл, как проверить этот пункт "и при 'том посмотреть - отработается-ли 'скалация на не взятую таску (в рамках этого БП и ИД юзертаски, по которым настроено это правило)"?

**Comment by LamronNu** [comment]
@OlgaKotova 
попробуйте через сервис runEscalationRule, здесь он описан подробнее: https://github.com/e-government-ua/i/issues/658#issuecomment-138097284, в доку я тоже скорей всего это запишу, чтобы осталось "на будущее" (просто тогда сделала его "для теста", думала, что потом удалю... сейчас вижу, что иногда нужна возможность запускать правила "по отдельности"..)

т.е. запрос примерно такой: test.region.igov.org.ua/wf/service/escalation/runEscalationRule?nID=[your_nID]
так Вы сможете запустить свое правило и проверить... только я не очень поняла, что именно нужно проверять, надеюсь, Вам виднее)

**Comment by OlgaKotova** [comment]
@LamronNu Спасибо за подсказку, правило запустила, получила в ответ 200ОК, но письмо на почту не пришло.
Что проверить, так и не поняла... 
@bvv4ik помогите, пжл. Подскажите, как проверить этот пункт -  "и при 'том посмотреть - отработается-ли 'скалация на не взятую таску (в рамках этого БП и ИД юзертаски, по которым настроено это правило)"?

**Comment by OlgaTurenko** [comment]
Нужно было прописать в условия эскалации дополнительный параметр sLoginAssigned. Сделала для nID=616 . Плюс по ссылке запустить: https://test.region.igov.org.ua/wf/service/escalation/runEscalationRule?nID=616 

Но письмо действительно не приходит, так как в результате нет найденных тасок. Из лога:
function getResult() {    return nElapsedDays > nDaysLimit && sLoginAssigned == null;}
2015-11-23_12:09:31.256 | INFO | org.wf.dp.dniprorada.base.util.JSExpressionUtil- >>>>------SCRIPT RESULT=false

Хотя есть задачи, которые попадают под условия.

**Comment by ASkosyr** [comment]
по комментарию @OlgaTurenko и запросу
https://test.region.igov.org.ua/wf/service/escalation/runEscalationRule?nID=616

в системе не находятся таски. сейчас попробую создать тестовую, чтобы проверить.

по комментарию @OlgaKotova - насколько я вижу при создании правила используется некорректное имя переменной в выражении - nDaysLimitt (t должна быть одна в конце)
