### ISSUE TITLE
На главном портале, в механизме авто-наложения ЭЦП на заполненную форму реализовать возможность выбора патерна принтформы, при формировании того ХТМЛ-а, на который потом накладывается ЭЦП (уже файл pdf)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#919]
- [ ] 1) Сама реализация наложения ЭЦП была по таске:
https://github.com/e-government-ua/i/issues/843
т.е. "вклиниться" нужно в этап формирования шаблона HTML:
\i\central-js\server\api\process-form\form.template.js

- [ ] 2) Параметр с путем к патерну брать из "value" поля с id, начинающимся с "PrintFormAutoSign_" (в БП его нужно проставлять с типом invisible)

- [ ] 3) Значение будет вида "printform/subs.html" (вообще поискать или создать в ресурсах wf-region, в подпапке patterns соотв. файл-шаблон)

- [ ] 4) Подгружать контент файла на фронте через сервис /getPatternFile, при этом вызывая его именно с того-же регионального сервера, на котором и находится услуга

- [ ] 5) вместо текущей автоматической генерации шаблона (на основании всех имеющихся полей в форме) - подставлять в HTML-е только те поля, которые будут найдены. при этом в шаблонах поля будут выглядеть в виде:
"обычный текст [field1] продолжение текста"
где "field1" - id поля формы, значение из которого нужно подставить вместо этого тэга "[field1]"
Такое уже реализовано на дашборде, и пример можно глянуть:
\i\dashboard-js\client\components\print\PrintTemplateProcessor.js
(и в соседних файлах этой папки)

- [ ] 6) Если поле п.2. не будет обнаружено или будет пустым - формировать форму по текущей схеме.

**Comment by hordesalik** [comment]
потестил, вроде все ок. форму получаю, параметры заменяю на те, что пришли в форме. пдф получил.
нужна тестовая услуга где будут поля в форме соответствовать полям в шаблоне для пдф

**Comment by hordesalik** [comment]
тестовая услуга
https://test.igov.org.ua/service/770/general

я проверил, поля заполняются, пдф проходит проверку эцп

**Comment by RoOmel** [comment]
1) Путь к какому типу ключа нужно указать SSH-1 (RSA), SSH-2 RSA или SSH-2 DSA?

**Comment by hordesalik** [comment]
1) Путь где? )) Во время наложения подписи на документ? Там нужно указать ключ к сертификату ЭЦП. Можно сгенерировать в приват24

**Comment by RoOmel** [comment]
При проверке тестовая услуга
https://test.igov.org.ua/service/770/general
После заполнения всех полей и нажатия на кнопку, открывается новое окно, в кот. необходимо указать (загрузить) ключ, ввести пароль к нему и что-то выбрать из выпадающего списка.
Какой ключ из SSH-1 (RSA), SSH-2 RSA или SSH-2 DSA нужен?
Для генерации пользуюсь puttygen.

**Comment by hordesalik** [comment]
ой не знаю подходит ли этот сертификат на сайте приватбанка у себя в личном кабинете. Как это делать описано тут:
https://github.com/e-government-ua/i/wiki/%D0%9D%D0%B0%D1%88%D0%B0-%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0#%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D0%AD%D0%A6%D0%9F-%D0%AD%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%BE%D0%BD%D0%BD%D0%BE%D0%B9-%D0%A6%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%BE%D0%B9-%D0%9F%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D0%B8-%D0%BD%D0%B0-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B5-%D0%9F%D1%80%D0%B8%D0%B2%D0%B0%D1%8224

**Comment by RoOmel** [comment]
Для генерации пользуюсь puttygen.
Значит вопрос переадресую bvv4ik

**Comment by OlgaTurenko** [comment]
Добрый день, RoOmel Вы наверное говорите про паблик и прайвет ключах, а не про ЭЦП (это немного разные вещи). Чтоб получить электронно цыфровую подпись ее рекомендую сгенерировать как вариант из П24 по вышеприсланному описанию.

**Comment by RoOmel** [comment]
Это слишком долгая процедура, у меня нет на это времени.
Сорри

**Comment by hordesalik** [comment]
@bvv4ik может есть тестовая ЭЦП?

**Comment by NizhnikAlex** [comment]
Процедура получения ЭЦП в П24 занимает около 5 мин. Это долго?

**Comment by RoOmel** [comment]
5 минут?
Там процедура из 5 шагов, при этом дважды надо ходить в отделение банка.

**Comment by hordesalik** [comment]
Да никуда там ходить не нужно. Я сделал все минут за 10

**Comment by NizhnikAlex** [comment]
Заходишь Р24
Усі послуги - Бізнес - Замовити, додати сертифікат.
Вводишь желаемое название сертификата, галочка "Сусловиями согласен",  Сформировать заявку. Вводишь пароль с подтверждением и путь куда кидать. Ждешь 1-2 минуты. Все, сертификат получен.

**Comment by RoOmel** [comment]
Сорри, но не получается, т.к. GoogleChrome 46.0 просит обновить JRE, хотя у меня установлена последняя версия, а Firefox 42.0 блокирует все попытки запустить Java-приложение даже когда разрешаешь.

**Comment by hordesalik** [comment]
Хром больше вообще не поддерживает Java апплеты... А вот в ФФ я нормально сделал все.

**Comment by GrekD** [comment]
@RoOmel напишите Сергею Жуку (скайп szhuk75) - у него есть тестовый ЕЦП

**Comment by NizhnikAlex** [comment]
Так а в чем вообще проблема?

Если проверка наложения ЭЦП на подставляемую принтформу - еще дня 4 назад проверили, все накладывалось. Кривовато из НТМЛ в ПДФ перебивает, но это, насколько я понимаю, другая задача.
Со вчерашнего дня проблема, описанная в таске https://github.com/e-government-ua/i/issues/954

**Comment by hordesalik** [comment]
Ну так это я с тобой проверяли... А тестеры то нет

**Comment by RoOmel** [comment]
С n-ной попытки добыл этот сертификат.
Теперь при нажатии "Замовити послугу" сайт отображает
"An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.
If you are the system administrator of this resource then you should check the error log for details.
Faithfully yours, nginx."

**Comment by OlgaTurenko** [comment]
ЭЦП починили на тестовых серверах. Прошу проверить данную задачку.

**Comment by RoOmel** [comment]
Повторил проверку по ссылке https://test.igov.org.ua/service/770/general
Пришло 2 письма.
Первое:
 Ваше звернення щодо Підтвердження відомостей про юридичну особу (форма 6) успішно зареєстроване.
Ви отримаєте відповідь протягом трьох днів.

Якщо у Вас з`явились питання, Ви можете звернутись до ЦНАП Дніпропетровської міськради Лівобережний
49051, Дніпропетровська обл., м. Дніпропетровськ, просп. Газети "Правда", 42
Понеділок, середа з 9.00 до 18.00
Вівторок, четвер з 9.00 до 20.00
П'ятниця з 9.00 до 16.45
Субота з 10.00 до 16.00
Вихідний - Неділя
Телефон для довідок: (056) 726-30-69

З повагою,
Державна реєстраційна служба,
Команда Порталу державних послуг iGov 

Второе:
Ваша заявка 73253203 прийнята!
Ви завжди зможете переглянути її поточний статус у розділі "Статуси". Також на кожному етапі Ви будете отримувати email-повідомлення. 

Прошу уточнить ожидаемый результат, т.к. по файлу формата pdf с ЭЦП я сценарий не понял.

**Comment by NizhnikAlex** [comment]
PDF падает на дашборд чиновника, к письму не прикрепляется

**Comment by RoOmel** [comment]
Ну так а как мне проверить факт получения PDF чиновником с моей ЭЦП?

**Comment by hordesalik** [comment]
@RoOmel Зайдите чиновником в дашбоард и там у задачи должен быть прикрепленный файл

**Comment by RoOmel** [comment]
Проверил PDF по номеру задачи в дашборде - файл действительно прикреплён.
Содержание файла соответствует заполненной форме, а вот само оформление PDF требует доработки, т.к. многие поля сдвинуты, строки налазят друг на друга, не совсем понятно что к чему относится.

**Comment by bvv4ik** [comment]
по поводу форматирования - єто ограниченность самого конвертера, которій работает в рамках сервиса, которій мі юзаем... тут ничего поделать нельзя (єто изначально біл осознанній шаг)
Просто напросто шаблоні будут делаться максимально примитивніе, с минимумом стилей, и тогда єто уже проблемой не будет.

@NizhnikAlex Прошу упростить шаблон, приблизив его максимально к реальному виду использования на боевом... (просто поубирать стили, на сколько это только возможно)
и по готовности отписаться тут, чтоб мы могли уже в бой запускать...

**Comment by NizhnikAlex** [comment]
Это и есть реальный шаблон с боевого. Скорее всего, буду действительно верстать с минимумом стилей, но при сложных формах задача практически не выполнима.

Запускаем на боевой - этот вариант все равно лучше варианта дефолтной принтформы. По возможности, поставить задачу найти более точный конвертер. Если мы хотим приучить службы к электронному документообороту - такой конвертер нам будет нужен очень сильно.

**Comment by hordesalik** [comment]
@NizhnikAlex думаю можно стилизировать так, чтобы ширина документа подходила под ширину генерируемого пдф файла, а внутри уже размещать контент, тогда он будет влазить

**Comment by NizhnikAlex** [comment]
Дело в том, что ширину документа не мы задаем - это все формы, утвержденные кабмином и т.д.

**Comment by hordesalik** [comment]
я думаю они все расчитаны на А4
