### ISSUE TITLE
Реализовать в форме таски кнопку "Проверить ЭЦП", на против прикрепленного файла-атача

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#920]
При этом вызывать сервис, реализованный в таске:
https://github.com/e-government-ua/i/issues/915

- Если там пустой объект ("{}"), то выводить диалог "ЭЦП отсутствует"

- Если там не пустой объект, то выводить точно такой-же диалог, которы йреализован на главном портале, при наложеной ЭЦП на документе (в Мои Документы)

![2015-10-24 18 49 04](https://cloud.githubusercontent.com/assets/4208821/10711339/a0912c9c-7a80-11e5-8912-a389452c15e1.png)

Пример можно найти тут: \i\central-js\client\app\documents\content.html

**Comment by GrekD** [comment]
добрый день. Вцелом работает.
Проверила на двух разных ЕЦПшках - для физ лица (выдано ПБ в Приват24) и для ФОП (выдано АЦСК ТОВ "Центр сертифікації ключів "Україна").
Для физ лица все ок - 
При нажатии на кнопку "перевірити підпис" - проверяет, все данные указаны корректно.
При загрузке на комп локально - тоже все ок.
Для ФОПа не все ок - 
При нажатии на кнопку "перевірити підпис" - проверяет, все данные указаны корректно.
Но если загрузить принтформу на комп локально и проверить уже там, то пишкт что подпись не верна, хотя это может и не относится к этой таске
![default](https://cloud.githubusercontent.com/assets/10836093/12414232/d98416c6-be9c-11e5-9b99-abe76f8bf20c.jpg)
Если ЕЦП не неаложено, то появляется всплывающее окно "Немає підпису"

**Comment by bvv4ik** [comment]
проверяет сервис Банк ИД, так что там ддолжно быть все норм... или у Сереги спросить можно...

**Comment by GrekD** [comment]
уточнила - все дело в моей программе, которой я проверяла ЕЦП локально - она не все ецпшки кушает.
с таской все ок - работает
