### ISSUE TITLE
Реализовать в маркерах новый тип валидатора для ЭЦП

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#921]
- Пример:
validate:{
      FileSign: {
        aField_ID: ['file_Passport']
      }
}

- Использовать для валидации сервис, написанный по таске:
https://github.com/e-government-ua/i/issues/917

- При этом в поле с типом file брать значение, которое будет являться ИД-шником Redis-а

- В случае невалидности выводить сообщение: "Подпись невалидна"

- При валидности, выводить справа от поля с файлом "Автора подписи"
как помечено в приведенном примере:
![image](https://cloud.githubusercontent.com/assets/4208821/10711403/c0fd4d88-7a82-11e5-94ac-fa19af01d173.png)

Пример использования полей объекта с подписью можно найти тут:
\i\central-js\client\app\documents\content.html

- ВАЖНО: Производить проверку только единажды, сразу после аплоада файла в форму...(ну и сразу после повторных аплоадов)

**Comment by nazarenkod** [comment]
как можно проверить?

**Comment by kurbpa** [comment]
Подготовил услугу для тестов - https://test-version.igov.org.ua/service/1416/general
На стартовой таске есть 2 файла для загрузки
```
<activiti:formProperty id="bankId_scan_inn" name="тест скан инн" type="file"></activiti:formProperty>
<activiti:formProperty id="signed_attach" name="тест скан с ЭЦП " type="file"></activiti:formProperty>
```
Подключен соответствующий маркер
```
{
"validate":{
	"FileSign":{
		"aField_ID":["form_signed","bankId_scan_inn","bankId_scan_passport"]
				}
			}
}
```
При загрузке файла, которые необходимо валидировать на  ЭЦП наблюдаю следующее поведение:
1. Если ЭЦП  наложен - отображается инфо  по этому ЭЦП ( название организации )
2. Если загружается файл без ЭЦП - при попытке отправить заявку отображается надпись "Підпис не валідний або відсутній". 
3. Если после этого загрузить подписаный ЭЦП файл, то отображается и надпись огранизации и сообщение "Підпис не валідний або відсутній".  - это не очень корректно.
