### ISSUE TITLE
Реализовать сущность Server и заполнить ее как минимум одной записью наших серверов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#923]
- [x] 1) Поля сущности:
nID - номер-ИД (уникальный/автоиттеррируемый)
sID - строка-ИД
sType - строка типа сервера
sURL_Alpha - строка URL сервера-альфа
sURL_Beta - строка URL сервера-бета
sURL_Omega - строка URL сервера-омега
sURL - строка URL сервера-продакшин

- [x] 2) Server.csv заполнить данными:
nID;sID;sType;sURL_Alpha;sURL_Beta;sURL_Omega;sURL
0;Common_Region;Region;https://test.region.igov.org.ua/wf;https://test-version.region.igov.org.ua/wf;https://master-version.region.igov.org.ua/wf;https://region.igov.org.ua/wf

- [x] 3) Создать сервис getServer с параметром nID, по которому отдавать объект найденной сущности или ошибку "Record Not Found":

- [x] 4) Дополнить сущность ServiceData опциональнім полем:
nID_Server - номер-ИД сервера

- [x] 5) Описать доку на вики

**Comment by brunneng** [comment]
Для теста проверить что соответствует документации:
https://github.com/e-government-ua/i/blob/test/docs/specification.md#45_getServer

**Comment by VadimGulich** [comment]
Реализовано , ток в доке тот запрос возвращает 404 , нужно использовать 
{
    "sID": "Common_Region",
    "sType": "Region",
    "sURL_Alpha": "https://test.region.igov.org.ua/wf",
    "sURL_Beta": "https://test-version.region.igov.org.ua/wf",
    "sURL_Omega": "https://master-version.region.igov.org.ua/wf",
    "sURL": "https://region.igov.org.ua/wf",
    "nID": 0
