### ISSUE TITLE
Провести адаптацию портала под мобильные устройства, согласно отчета:

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#932]
- [x] 1) Устранить замечания по доку:
https://docs.google.com/document/d/1EOqlnQy-T8U-HBNYTawBCdlexFV6TvCRGIG1ftVVnVs/edit

- [x] 2) Так-же необходимо устранить:
https://www.facebook.com/photo.php?fbid=10204681842240079&set=p.10204681842240079&type=3&theater

Для помощи/ассестирования просьба обращаться к:
тестувальник, Віталій Сохацький

или

Сич Антон Вікторович

**Comment by OlgaTurenko** [comment]
Дорогие, волонтеры, просьба взять эту задачку. Уже очень горит. К сожалению из-за некоторых недочетов невозможно пользоваться мобильной версией igov :(

**Comment by bvv4ik** [comment]
@Iryna K прошу попробовать реализовать хотябы 1-2 пункта, и сообщить - на сколько задача "по силам"

**Comment by Irynka** [comment]
1) - сделано.

**Comment by Irynka** [comment]
2) - сделано.
Посмотрите, не мелколи.

**Comment by VadimGulich** [comment]
Сохацский  Виталий отписал по отчету, баги исправлены

**Comment by MaksKnight** [comment]
![screenshot_2016-03-18-22-41-11](https://cloud.githubusercontent.com/assets/17780607/13897972/719e88de-edcc-11e5-9674-8fdf2d861211.png)
![screenshot_2016-03-18-22-41-17](https://cloud.githubusercontent.com/assets/17780607/13897976/719f2492-edcc-11e5-8203-38fdc0289c04.png)
![screenshot_2016-03-18-22-42-12](https://cloud.githubusercontent.com/assets/17780607/13897974/719eab48-edcc-11e5-915c-91d110109bc7.png)
![screenshot_2016-03-18-22-42-58](https://cloud.githubusercontent.com/assets/17780607/13897973/719ec1dc-edcc-11e5-93d0-04bca1cff23f.png)
![screenshot_2016-03-18-22-43-03](https://cloud.githubusercontent.com/assets/17780607/13897977/719fa1ce-edcc-11e5-9142-3958af4bff04.png)
![screenshot_2016-03-18-22-45-26](https://cloud.githubusercontent.com/assets/17780607/13897975/719efac6-edcc-11e5-89cf-fe656e5396ca.png)
плывет верстка на устройстве lenovo A5000, android 5.0.2

**Comment by Irynka** [comment]
@MaksKnight  поисковая строка исправленно положения фильтра и иконки очистить поле. проверьте пожалуйста.

**Comment by Irynka** [comment]
@MaksKnight Таблица статистики адаптирована. Проверяйте.

**Comment by MaksKnight** [comment]
Теперь все ок.

**Comment by bvv4ik** [comment]
готово)

**Comment by Irynka** [comment]
Poligon под iPhone 5 не очень.

2016-03-31 1:48 GMT+03:00 bvv4ik <notifications@github.com>:
