### ISSUE TITLE
Реализовать сервис проверки наличия таски определенного БП, указанного гражданина

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#933]
- [ ] 1) Реализовать на wf-central и назвать getLastTaskHistory

- [ ] 2) Поля сервиса:
nID_Subject - номер-ИД субьекта 
nID_Service - номер-ИД услуги
sID_UA - строка-ИД места Услуги

- [ ] 3) по заданным параметрам:

- [ ] 3.1)  находить в сущности HistoryEvent_Service.csv последнюю запись (по nID_Subject + 
nID_Service + sID_UA):

- [ ] 3.2) возвращать найденную запись виде объекта, или возвращать ошибку "Record not found, если не найдено ничего"

- [ ] 4) Описать сервис в Вики

П.С.: на вики есть описание наших стандартов, каак создавать сервисы и работать с сущносями

**Comment by bvv4ik** [comment]
Привет,
как там успехи по таске?)

**Comment by kr110666kai** [comment]
Готов принять в работу. Вообщем-то эту задачу я уже сделал, я на ней как-раз потренировался.

**Comment by OlgaTurenko** [comment]
Добрый день! Отлично :) Тоесть эта задачка готова?

**Comment by kr110666kai** [comment]
Да. Я просто без assigned к задаче не стал идти дальше.

**Comment by OlgaTurenko** [comment]
Ага. здорово. Мы Вам еще приглашение в команду ж не отправляли? Без этого Вас исполнителем поставить не могу. Не могли бы почту свою, пожалуйста, дать. Вышлю Вам приглашение в команду.

**Comment by OlgaTurenko** [comment]
мой скайп если что: olia.kuzminova

**Comment by OlgaTurenko** [comment]
Выливать задачку можно в веточку test если что.

**Comment by LamronNu** [comment]
@kr110666kai 
пожалуйста, допишите еще документацию по этому сервису, сюда: https://github.com/e-government-ua/i/blob/test/docs/specification.md#17_workWithHistoryEvent_Services
там есть примеры, как писать.

**Comment by kr110666kai** [comment]
Документацию дописал https://github.com/e-government-ua/i/blob/test/docs/specification.md#46_getLastTaskHistory можно тестировать.

**Comment by OlgaTurenko** [comment]
благодарю!

**Comment by nazarenkod** [comment]
Протестировано согласно документации
