### ISSUE TITLE
Создать в маркерах унифицированный валидатор проверки кодов/номеров(с кастомным сообщением), с заданным количеством и последовательностью знаков, а также реализовать на его базе инструкцию валидации кадастрового номера.

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#934]
Пример:
    validate: {
      CustomFormat_NumberKadastr: {
        aField_ID: ['landNumb'],
        sFormat: 'хххххххххх:хх:ххх:хххх'
        sMessage: 'При неправильном введении выводить ошибку "Невірний кадастровий номер, введіть кадастровий номер у форматі хххххххххх:хх:ххх:хххх"'
      }
   }

* Исходная информация по валидации кадастрового номера:
id: landNumb
type: string
формат: 10 цифр:2 цифры:3 цифры:4 цифры (хххххххххх:хх:ххх:хххх) 
При неправильном введении выводить ошибку "Невірний кадастровий номер, введіть кадастровий номер у форматі хххххххххх:хх:ххх:хххх"

**Comment by nazarenkod** [comment]
Не выводится кастомное сообщение при неправильном вводе кадастрового номера.
проверял на БП: "Внесення до Державного земельного кадастру відомостей (змін до них) про земельну ділянку"
![clip2net_151202135334](https://cloud.githubusercontent.com/assets/13256486/11530322/4bef634e-98fc-11e5-91d6-a27d79589d10.jpg)

**Comment by NizhnikAlex** [comment]
1. Валидация кадастрового номера, насколько я понял, создана отдельно. Поэтому не может браться для теста.
2. Универсальный валидатор не отрабатывает. В БП добавлялась строка:
{"validate":{"CustomFormat_NumberKadastr":{"aField_ID":["landAddress"],"sFormat":"х:х","sMessage":"Невірний кадастровий номер, введіть кадастровий номер у форматі хххххххххх:хх:ххх:хххх"}}}. Итог - пропускается любая конструкция.

3. Проверить можно на услуге https://test.igov.org.ua/service/99/general
Строчка "Місце розташування земельної ділянки:". БП "dnepr_cnap_231"

**Comment by nazarenkod** [comment]
не реализовано
![clip2net_151207214949](https://cloud.githubusercontent.com/assets/13256486/11637856/8d4fce3a-9d2c-11e5-86a5-787aef30b6a9.jpg)

**Comment by bvv4ik** [comment]
@rostag  глянь плиз, это то о чем я писал

**Comment by bvv4ik** [comment]
пофиксино отображение мессаджа
![image](https://cloud.githubusercontent.com/assets/4208821/11768916/e7a024be-a1e3-11e5-8426-2e23e98a65a0.png)

прошу перепроверить

**Comment by rostag** [comment]
Проблему з валідатором кадастрового номеру вирішено не до кінця. Ось скріншот, який показує проблему: зараз у якості такого номеру валідується не номер, а адреса земельної ділянки (номер валідується також, але завдяки work-around'у з останнього коміту ( #ffedc57 ):

![image](https://cloud.githubusercontent.com/assets/451410/11781314/9d277110-a271-11e5-98a2-81d997fd6d2d.png)


Причина цього - у невірній конфігурації, що приходить з бекенду. Так, якщо у файлі servicebuiltinbankid.controller.js розкоментувати рядок 
```
console.log('data.formData.params = ', JSON.stringify($scope.data.formData.params, null, '  '));
```

То, серед іншого, побачимо ось що:

"marker_validate": {
    "value": "{\"validate\":{\"CustomFormat_NumberKadastr\":{\"aField_ID\":[\"landAddress\"],\"sFormat\":\"х:х\",\"sMessage\":\"Невірний кадастровий номер, введіть кадастровий номер у форматі хххххххххх:хх:ххх:хххх\"}}}"
  }

Хіба landAddress має валідуватися як номер? Це ж адреса, так? Отже, зараз вона "забирає" на себе валідацію від поля "landNumb", і тоді валідатор наче не працює... я думаю, валідатор не запрацює правильно, поки ми не змінимо цю конфігурацію.

Якщо її змінити - то не знадобиться work-around, валідатор запрацює як треба.

**Comment by NizhnikAlex** [comment]
можно тестировать. Лишние строки убрали.

**Comment by nazarenkod** [comment]
Работает согласно описанию
