### ISSUE TITLE
url "фокусы"

### ISSUE THREAD

**Issue by irungentootoo** [e-government-ua/i#95]
простите конечно но выглядит как шлюха которую бросают с адреса на адресс переадресациями туда сюда. днепро.дп - какой то мигнул урл (подозрительно) я уже на банкид.орг.юа потом я уже на сайте привата, а дальше кликать не стал... 
"Все гениальное просто! Не нужно усложнять, если можно сделать все просто"

**Comment by bvv4ik** [comment]
я, если честно, не совсем понял о чем Вы... о авторизации через БанкИД?

**Comment by kadimgh** [comment]
@irungentootoo так працює розподілена авторизація, через редіректи. Щодо підозрілості, то потрібно довіряти тому сайту, на якому ви вводите чутливі дані (в даному випадку pbank), при коректній реалізації довіри між всіма посередниками. 

Що конкретно можна зробити простіше на вашу думку, без втрати загальності?

**Comment by irungentootoo** [comment]
просто вспоминаються времена когда ты случайно наводиш мышкой на боковой блок рекламы, и тут открываються окна. в которых страшные урл-ы редирект за редиректом, заработок на трафике и прочие неприятности.

**Comment by kurbpa** [comment]
так в чём заключается конкретное предложение?

**Comment by vbolshutkin** [comment]
Я сам не вижу в редиректах большой проблемы. Более того, так сделано во многих эквайрингах и особо никто не жалуется. Избавиться от них нельзя, скрыть во фрейме можно, но это потенциальная дыра для фишинга, так как пользователь более не видит URL провайдера аутентификации и валидность сертификата... Думаю, единственное, что можно сделать - вместо пустых редиректов сделать аккуратные странички с 3 секундным таймаутом и говорящими заголовками. Ну и в будущем же там, возможно, будут другие варианты переходов - типа MobileId кроме BankId, выбор банка вместо редиректа на приват.

**Comment by bvv4ik** [comment]
конструктивных альтернатив не поступило)
Предлагаю придерживаться золотого правила "Критикуешь - предлагай!")
