### ISSUE TITLE
Скрывать на дашборде "Эскалации", "Электронные очереди", кропку "Замечания" для продакшина (на тестовом должно остаться отображаться (завязаться на флаг)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#950]

**Comment by serdyuk-alex** [comment]
>Привет,
>я добавил параметр:
>
>{
>  "env": {
>"bTest": "true"
>...
>
>в process.json на серверах тестовых...
>
>на боевом:
>,"bTest": "false"

Нужно добавить новый параметр bTest или же использовать существующий NODE_ENV?
```json
  "env": {
    "NODE_ENV": "production",
```
"Эскалации" - нашел в навигейшн баре, а остальные не вижу( где они?

**Comment by bvv4ik** [comment]
"Электронные очереди" = Раздел "сервис" (вверху, на уровне закладок, но справа от них)
![image](https://cloud.githubusercontent.com/assets/4208821/11761443/d4f7503a-a0cb-11e5-8c32-8132d1bafe6c.png)

Кнопка "Зауваження", появляется рядом с кнопкой "отработать", в выбранной задаче, среди тех , что в закладке "В роботе"
![image](https://cloud.githubusercontent.com/assets/4208821/11761444/e8f71dfe-a0cb-11e5-8c39-31f092c7260b.png)

**Comment by bvv4ik** [comment]
"Нужно добавить новый параметр bTest или же использовать существующий NODE_ENV?"
нужно только заюзать новый параметр (,"bTest": "true"), который я добавил в серверный фвйл (process.json, в подкетку обьекта "env": {)... и,  видимо, в проекте тоже добавить этот элемент в этот-же файл.... ну и пробросить где нужно, чтоб начать его юзать...

**Comment by bvv4ik** [comment]
чтоб проверить нужно на сервере(альфе) подменить профиль(/sybase/dashboard-js/process.json) с test-alpha на production (параметр NODE-ENV) и ребутнуть дашбоард(/sybase/dashboard-js_restart.sh)... компоненты  исчезнут... потом вернуть обратно и ребутнуть - вернутся...

я лично тестил - работало, но можно перепроверить
