### ISSUE TITLE
Автогенерация документации.

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#951]
Организовать автогенерацию документации по контролерам с помощью SpringDoclet (https://mestachs.wordpress.com/tag/spring-mvc/ ).. По каждому контроллеру проекта в документации необходимо чтоб присутствовали:

1)тип метода (get, post и тд)
2)параметры хедера
3)параметры запроса
4)пример вызова сервиса
5)пример ответа

Учесть также, что контроллеры есть в модулях wf-base (доступны для вызова на центральном и региональном серверах), wf-central (доступны для вызова только на центральном сервере). Документация по ним желательно чтоб находилась в одном общем файле. Возможно как-то удастся промаркеровать сервиса (доступен только на централе или же из регионального тоже).

**Comment by dgroup** [comment]
Попытаюсь сделать демку в ближайшее время... После чего предлагаю обсудить результаты.

**Comment by OlgaTurenko** [comment]
Отлично! Очень разумное предложение! Тут еще предлагали альтернативные инструменты, которые позволили и тестовые запросы отсылать ииз доки: swagger или IO docs

**Comment by dgroup** [comment]
Cделал демку, обсудили с @OlgaTurenko.  SpringDoclet  (в текущей версии, 0.0.1) не удовлетворяет наши хотелки:
2. параметры хедера
3. параметры запроса
4. пример вызова сервиса
5. пример ответа

Буду смотреть в сторону:
- http://petstore.swagger.io/
- http://www.mashery.com/api/io-docs

**Comment by dgroup** [comment]
+ Забавная презенташка по поводу построения АРІ:
http://www.slideshare.net/Mansilladev/maintainable-api-docs-and-other-rainbow-colored-unicorns

**Comment by kr110666kai** [comment]
Я тут параллельно просмотрел еще пару вариантов: springfox и rest-doclet.

1. rest-doclet (https://github.com/calrissian/rest-doclet) имеет два варианта:
  1.1. Создает отдельный html-файл на этапе generate-resources при отработке плагина maven-javadoc-plugin
       пример: doclet-simple.zip https://drive.google.com/file/d/0B4_nhAYzTtL6Sk9LbGtnUmRFdzQ/view?usp=sharing
  1.2. Создает swagger приложение, как часть основного приложения. Использует устаревшую версию swagger
       

2. springfox (http://springfox.github.io/springfox/) работает на основаии swagger2
  2.1. Создает swagger2 приложение, как часть основного приложения. Использует новую версию swagger2
       пример: wf-central.war https://drive.google.com/file/d/0B4_nhAYzTtL6d09TdjJrVnB2d0U/view?usp=sharing
       запуск: localhost:8080/wf-central/service/api-docs/swagger-ui.html
       git: https://github.com/e-government-ua/i/tree/test-swagger2 
       Основана на перехватчике события маппинга сервисов. Отрабатывает один раз во время маппинга сервисов, а далее просто выводит все в красивом виде.

  2.2. Есть вариант с созданием статик документации как результат теста. Но этот вариант пока не удается запустить:
       вылетает ошибка тестирования наших сервисов просто при добавлении:
```
 <dependency>
     <groupId>io.springfox</groupId>
     <artifactId>springfox-staticdocs</artifactId>
     <version>2.2.2</version>
</dependency>
```

**Comment by dgroup** [comment]
### На данный момент было внедрено 
> 1.1. Создает отдельный html-файл на этапе generate-resources при отработке плагина maven-javadoc-plugin
Потому что это минимальный, самый быстрый способ получить документацию.

Билд прошел успешно:
https://jenkins-new.igov.org.ua/view/new/job/central_alpha/2326/console

Пока автоматическая генерация документации работает на новом, тестовом дженкинсе:
https://jenkins-new.igov.org.ua/view/new/job/central_alpha/ws/wf-central/target/site/apidocs/index.html

Также pmd отчет есть:
https://jenkins-new.igov.org.ua/view/new/job/central_alpha/ws/wf-central/target/site/pmd.html

### Что касается остальных моментов:
> 1.2. Создает swagger приложение, как часть основного приложения. Использует устаревшую версию swagger

Делал по нему демку, мне не понравилось, ибо там надо делать дополнительные телодвижения  при связывании "этого нового приложения" и нашего ресурса. 

> springfox (http://springfox.github.io/springfox/) работает на основаии swagger2

Буду смотреть в эту сторону, мне нравится этот подход.

**Comment by bvv4ik** [comment]
В доку по АПИ добавлены вначале две ссылки:
https://github.com/e-government-ua/i/blob/test/docs/specification.md

**Comment by bvv4ik** [comment]
domash [9:54 PM] 
еще на devoxx узнал про очень полезную либу по генерации документации из кода

domash [9:56 PM] 
пришлю сейчас ссылку на выступление

​[9:56] 
и на проект на гихаб

может быть идеи из выступления и из этой либы помогут. Там есть интеграция со спрингом

​[9:57] 
https://www.youtube.com/watch?v=oDpdaXt0HQI
YouTube
Devoxx 2015
Software architecture as code by Simon Brown
  

​[9:57] 
https://github.com/structurizr/java

GitHub
structurizr/java
java - Java tools

**Comment by kr110666kai** [comment]
По springfox ( http://springfox.github.io/springfox/ ) доделал вариант с генерацией статической документации в виде html и/или pdf-формата.

Пример: 
  wf-base html: https://drive.google.com/file/d/0B4_nhAYzTtL6UlRWbXZXSUJOc3c/view?usp=sharing
  wf-base pdf: https://drive.google.com/file/d/0B4_nhAYzTtL6ODkzVTVoR1JvZzg/view?usp=sharing
  wf-central html: https://drive.google.com/file/d/0B4_nhAYzTtL6RHU0WHN2eWc5ZzQ/view?usp=sharing
  wf-central pdf: https://drive.google.com/file/d/0B4_nhAYzTtL6N3ZzMm5FZlJnYVE/view?usp=sharing

Документация генерируется в два этапа:
  1. Во время отработки теста SpringfoxScenario в каталоге src/main/asciidoc формируется документация в формате asciidoc. 
  2. На этапе generate-resources в каталоге target/generated-docs формируется документация в html формате*.  Так же на этом этапе возможно формирование документации в pdf-формате (проверено - работает, но из-за доволно долгого времени работы отключено).

* Есть вариант формирования прямо из теста.

Поскольку этап тестирования идет после generate-resources, то для формирования html-документации нужно два прохода maven.
  Например: mvn test generate-resources 

wf-base.html/pdf - содержит данные только wf-base
wf-central.html/pdf - содержит данные wf-central и wf-base

git: https://github.com/e-government-ua/i/commits/test-springfox

**Comment by dgroup** [comment]
@kr110666kai Добрый вечер.
Можно ли с вами созвонится завтра по этому поводу?Хотел бы задать пару вопросов.

**Comment by dgroup** [comment]
@kr110666kai , выкачал Вашу ветку
> git: https://github.com/e-government-ua/i/commits/test-springfox

Собирал командой:
```cmd
mvn clean pmd:pmd install site -U -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true
```
Получил ошибку компиляции:
```cmd
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:testCompile (default-testCompile) on project wf-central: Compilation failure
[ERROR] /G:/Development/i-gov/wf-central/src/test/java/org/springfox/SpringfoxConfiguration.java:[12,30] cannot find symbol
[ERROR] symbol:   class ApplicationSwaggerConfig
[ERROR] location: package org.springfox
```
Как Вы собираете приложение? Интересуют оба варианта (с веб версией и html/pdf файликом). 

Спасибо,
Юра

**Comment by kr110666kai** [comment]
Здравствуйте. Для создания pdf - надо раскоментировать в wf-central/pom.xml   и в wf-base/pom.xml

                 <execution>
                        <id>generate-pdf-doc</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                        <configuration>
                            <backend>pdf</backend>
                            <sourceHighlighter>rouge</sourceHighlighter>
                            <attributes>
                                <icons>font</icons>
                                <pagenums />
                                <toc2 />
                                <idprefix />
                                <idseparator>-</idseparator>
                            </attributes>
                        </configuration>
                    </execution> 

собирал простым 
mvn install (это полный цикл)

а так достаточно 
mvn test generate-resources

По ошибке компиляции:
Такая ошибка у меня выскакивала, как ушла я так и не понял. Но подозрение на то, что  имена   и теста и конфигуратора в base и в central совпадают, а пакет один и тот-же. Я перепроверю и наверное просто переименую.

PS. Созвониться можно

**Comment by bvv4ik** [comment]
смотрел пример автогенерации - отлично!
что нужно, чтоб прикрутить это к нашим джобам при авто-сборке?

**Comment by kr110666kai** [comment]
Достаточно слить изменения из test-springfox в ветку test. Надо уточнить три момента:

1. Выходной каталог target/generated-docs так и оставить?
2. Делать html и/или pdf?
3. /service/api-docs/swagger-ui.html наверное только в альфе нужен?

Хочу обратить внимание, что все наши желания этот вариант автогенерируемой документации, построенный на перехвате события маппинга сервисов, не удовлетворит. Получить можно только то, что может дать сервис в момент маппинга.

**Comment by bvv4ik** [comment]
1. да, можно так
2. лучше все-же html
3.пока что  - да

"А в онлайн сделал несколько групп cм. класс wf-base: org.springfox/ApplicationSwaggerConfig.java"

глянул, вроде понятно, можно будет постепенно так сгруппировать все...

Прошу тогда мержить в ветку тест, и после автосборке в джобе - маякнуть ,чтоб можно было вывести ссылку на вики

**Comment by kr110666kai** [comment]
На онлайн документации https://test.region.igov.org.ua/wf/service/api-docs/swagger-ui.html не все сервисы видны, можно как-то посмотреть {tomcat}/log/catalina.out?

**Comment by LamronNu** [comment]
>На онлайн документации https://test.region.igov.org.ua/wf/service/api-docs/swagger-ui.html не все сервисы видны, можно как-то посмотреть {tomcat}/log/catalina.out?

конечно, можно)
в [Нашем хозяйстве](https://github.com/e-government-ua/i/wiki/%D0%9D%D0%B0%D1%88%D0%B5-%D1%85%D0%BE%D0%B7%D1%8F%D0%B9%D1%81%D1%82%D0%B2%D0%BE) есть "явки-пароли" :
Логи на FTP (по Tomcat и NodeJS):
Тест-альфа-централ: test.igov.org.ua 
протокол: sftp 
логин: sftpuser 
пароль: zaqxswcde
Тест-альфа-регион: test.region.igov.org.ua 
протокол: sftp 
логин: sftpuser 
пароль: zaqxswcde

**Comment by dgroup** [comment]
@OlgaTurenko интеграция между rest-doclet и igov завершена.

Примеры документации сгенерированной с javadoc-ов:
- https://jenkins-new.igov.org.ua/job/central_alpha/ws/wf-central/target/site/apidocs/index.html
- https://jenkins-new.igov.org.ua/job/central_alpha/ws/wf-base/target/site/apidocs/index.html

Репозиторий с rest-doclet адаптированной под igov:
https://github.com/e-government-ua/rest-doclet

Джоба на дженкинсе для сборки адаптированной версии rest-doclet:
https://jenkins.igov.org.ua/job/rest-doclet-igov

**Comment by nazarenkod** [comment]
а не подскажите как можно проверить?

**Comment by bvv4ik** [comment]
реализовано
