### ISSUE TITLE
Перестал собираться на альфе и бете клиент.

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#952]
Перестал собираться на альфе и бете клиент портала граждан и дашборд чиновников.
https://jenkins.igov.org.ua/view/new/job/central_alpha/5315/console

Похоже ошибка связана с правками в плагине, который используется. А именно imagemin.

Вот тут пишут люди об этой же проблеме:
https://github.com/gruntjs/grunt-contrib-imagemin/issues/325
Очень нужно починить...

**Comment by michaelsanford** [comment]
Нотабене: https://github.com/gruntjs/grunt-contrib-imagemin/issues/325#issuecomment-155192072

**Comment by OlgaTurenko** [comment]
Спасибо! починили.
