### ISSUE TITLE
Поправить разметку на страницах внутри сервиса: выбор места, инструкция, статистика

### ISSUE THREAD

**Issue by tseshevsky** [e-government-ua/i#955]
Было бы неплохо улучшить внешний вид и юзабилити выбора места услуги.

Я сделал модель того, как это должно выглядть:
Сначала: http://www.codeply.com/go/bp/aUjnGaSjCx
А после выбора места вот так: http://www.codeply.com/go/bp/70S2jcZisz

На мой взгляд стоит убрать рамки (list-group) вокруг элементов на странице.

**Comment by bvv4ik** [comment]
только-только случаянно заменил эту ишью)
т.к. в основном они создаются одними и теми-же людьми, чтоб более контроллируемый процесс был...

определенно что-то полезное в идее есть, но чтоб лучше оценить - хотелось-бы все-же увидеть ккакой планируется внешний вид вместе с остальными элементами, в виде выбора мест и кнопок авторизации...?
