### ISSUE TITLE
Написать сервис /sendProccessToGRES

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#956]
Написать сервис /sendProccessToGRES, который будет на входе принимать ид таски, по таске получать ид бизнес-процесса и форму в активити с полями по данной таске, все 3-и сущности (ид таски, ид процесса и объект с формой) упаковывать в Map и пока что возвращать эту мапу клиенту. (следующим этапом сделаем вызов стороннего сервиса, куда в тело запроса поместим этот объект, но это уже в рамках другой задачи).

**Comment by ASkosyr** [comment]
Добавил информацию.
В выходной мапе 3 поля:
- startFormData: значения полей стартовой формы
- nID_Task: task ID
- nID: process ID

Example of query
``
https://test.region.igov.org.ua/wf/service/rest/sendProccessToGRES?nID_Task=7112622
``

**Comment by RoOmel** [comment]
Запрос
https://test.region.igov.org.ua/wf/service/rest/sendProccessToGRES?nID_Task=7112622
Ответ сервера
такой же как в примере выше, но из примера непонятно какой должен быть ожидаемый результат.
Текст выше:
"В выходной мапе 3 поля:
1) startFormData - значения полей стартовой формы
2) taskFormData - значение полей формы задачи
3) nID_Task - task ID
4) nID_Process - номер бизнес процесса(заявки)
5) sProcessDefinitionKey - ID бизнесс процесса
6) sProcessName - название бизнесс процесса"
к чему вообще относится?

Я вижу 6 параметров, из которых:
 - nID_Process - вообще нигде не используется;
 - nID_Task - используется как в запросе, так и в ответе;
остальные 4 параметра используется в ответе.

В условии задачи сказано, что сервис /sendProccessToGRES будет на входе принимать nID_Task и в ответе получать nID_Process и форму в активити с полями по nID_Task.
Реализация данной таски требует доработки, т.к. полученный результат не соответствует ожидаемому.

**Comment by bvv4ik** [comment]
@OlgaTurenko  Ольга, работает так как ожидалось?

**Comment by OlgaTurenko** [comment]
Все работает, все гуд. Только один момен все же поправить стоит. Обратила внимние, что в ответе не json формат для 2-х параметров. В коде это выглядит так:
res.put("startFormData", startFormValues.toString());
res.put("taskFormData", taskFormValues.toString());

В ответе так:
{"startFormData":"{text=Замовляючи послугу Ви надаєте згоду на обробку Ваших персональних даних та підтверджуєте їх актуальність., phone=380661112222, bankIdfirstName=ДМИТРО, text3=-------------------, fioUA=фываыв, text4=-------------------, bankIdmiddleName=ОЛЕКСАНДРОВИЧ, bankId_scan_passport=7112624, text1=-------------------, bankIdinn=3119325858, bankIdPassport=АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002, birthLoc=CALIFORNIA, goal=Здійснення усиновлення, встановлення опіки (піклування), створення прийомної сім'ї або дитячого будинку cімейного типу, resident=Україна, email=askosyr@gmail.com, bankIdlastName=ДУБІЛЕТ, birthDate=01.02.2000, res_type=Прошу надати довідку в паперовому та електронному вигляді (з ЕЦП), fioRU=фывафыв}","sProcessDefinitionKey":"dnepr_mvd_1","nID_Proccess":"7112557","sProcessName":"Днепропетровск - Надання довідки про відсутність або наявніcть судимості","nID_Task":"7112622","taskFormData":"{phone=380661112222, bankIdfirstName=ДМИТРО, fioUA=фываыв, bankIdmiddleName=ОЛЕКСАНДРОВИЧ, bankIdinn=3119325858, bankIdPassport=АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002, birthLoc=CALIFORNIA, goal=Здійснення усиновлення, встановлення опіки (піклування), створення прийомної сім'ї або дитячого будинку cімейного типу, resident=Україна, bankIdlastName=ДУБІЛЕТ, birthDate=01.02.2000, res_type=Прошу надати довідку в паперовому та електронному вигляді (з ЕЦП), fioRU=фывафыв}"}

Нужно поубирать .toString() в них и класть мапы. Тогда при отдаче они сконвертируются в хорошенький json формат.

**Comment by bvv4ik** [comment]
@ASkosyr 
Александр, плиз, я думаю 20 минут займет правка у тебя, как у автора...
сделай плиз, чтоб уже могли закрыть таску "на веки вечные")

**Comment by ASkosyr** [comment]
Код подправил.
Теперь результат по запросу 
https://test.region.igov.org.ua/wf/service/rest/sendProccessToGRES?nID_Task=7112622
приходит в таком виде

```{"startFormData":{"text":"Замовляючи послугу Ви надаєте згоду на обробку Ваших персональних даних та підтверджуєте їх актуальність.","phone":"380661112222","bankIdfirstName":"ДМИТРО","text3":"-------------------","fioUA":"фываыв","text4":"-------------------","bankIdmiddleName":"ОЛЕКСАНДРОВИЧ","bankId_scan_passport":"7112624","text1":"-------------------","bankIdinn":"3119325858","bankIdPassport":"АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002","birthLoc":"CALIFORNIA","goal":"Здійснення усиновлення, встановлення опіки (піклування), створення прийомної сім'ї або дитячого будинку cімейного типу","resident":"Україна","email":"askosyr@gmail.com","bankIdlastName":"ДУБІЛЕТ","birthDate":"01.02.2000","res_type":"Прошу надати довідку в паперовому та електронному вигляді (з ЕЦП)","fioRU":"фывафыв"},"sProcessDefinitionKey":"dnepr_mvd_1","nID_Proccess":"7112557","sProcessName":"Днепропетровск - Надання довідки про відсутність або наявніcть судимості","nID_Task":"7112622","taskFormData":{"phone":"380661112222","bankIdfirstName":"ДМИТРО","fioUA":"фываыв","bankIdmiddleName":"ОЛЕКСАНДРОВИЧ","bankIdinn":"3119325858","bankIdPassport":"АМ765369 ЖОВТНЕВИМ РВ ДМУ УМВС УКРАЇНИ В ДНІПРОПЕТРОВСЬКІЙ ОБЛАСТІ 18.03.2002","birthLoc":"CALIFORNIA","goal":"Здійснення усиновлення, встановлення опіки (піклування), створення прийомної сім'ї або дитячого будинку cімейного типу","resident":"Україна","bankIdlastName":"ДУБІЛЕТ","birthDate":"01.02.2000","res_type":"Прошу надати довідку в паперовому та електронному вигляді (з ЕЦП)","fioRU":"фывафыв"}}
```

**Comment by OlgaTurenko** [comment]
спасибо! все отлично.

**Comment by RoOmel** [comment]
Раелизовано согласно ТЗ
