### ISSUE TITLE
Доработать отображение статистики на странице статистика

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#958]
На портале гражданина на странице статистика: https://igov.org.ua/service/1/statistics

1. Отображать время не в формате "485 годин", а в формате "20 днів, 5 годин" если уже есть хоть один полный день, или же "5 годин" в противном случае (тоесть без днів).
2. В заголовке этой колонки убрать надпись (годин). Вместо него поставить значок (?), при наведении на который показывается подсказка: "Середній час між початком та закінченням процесу".

**Comment by zhernovoj** [comment]
https://github.com/e-government-ua/i/issues/970

**Comment by bvv4ik** [comment]
Добрый день,
есть уже понимание того - работает как запланировано или нет?

**Comment by VadimGulich** [comment]
работает , все ок , можно в бой
