### ISSUE TITLE
Ответ с вырезкой из газеты

### ISSUE THREAD

**Issue by kor27** [e-government-ua/i#959]
На заявку на компенсацию комуналки ,пршол ответ что процент компенсации во вложении ,а там оказалась газетная вырезка из урядового курьера,что бы это значило?

**Comment by bvv4ik** [comment]
прошу такого рода вопросы писать в:
https://github.com/e-government-ua/iForum/issues

т.к. данный репозиторий только для тасок разработки...
(и когда тут свалка - очень тяжело работать)
