### ISSUE TITLE
Отображение текущего пользователя на портале

### ISSUE THREAD

**Issue by DimasSup** [e-government-ua/i#96]
я залогинился через BankId на https://dniprorada.egov.dp.ua *во время "Видача картки обліку об’єкта...", перешел на основную страницу, опять зашел -  оно заполнило те поля которые вернулись от банка, но нигде не показано что я там залогинен. Ну и вопрос -  будет ли  кнопка чтобы сбросить мои данные на сайте(Logout)

**Comment by bvv4ik** [comment]
да, все это будет, конечно.. да и сессия не будет вечной)

**Comment by bvv4ik** [comment]
кроме того, при входе в любой другой сервис, пока сессия еще жива - так-же подтянутся персональные данные пользователя в форму...
