### ISSUE TITLE
Создать новые поля по фидбеку и обеспечить сохранение данных в них

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#961]
В сущность SubjectMessages добавить новое поле sBody_Indirectly 
В сущность НistoryEventService добавить новое поле nID_Rate_Indirectly
Создать сервис в ActivitiRestSubjectMessageController /setMessageFeedback_Indirectly по сохранению этих полей. 
На входе nID_Protected, nID_Proccess_Feedback , sBody_Indirectly, nID_Rate_Indirectly. Находить по nID_Protected, nID_Proccess_Feedback запись в таблице HistoryEvent_Service и записывать в нее новое поле с оценкой. Аналогично с комментарием в табличке SubjectMessages.
 
Создать сервис-таску с ид setMessageFeedback_Indirectly: 
@Component("setMessageFeedback_Indirectly")
public class SetMessageFeedback implements JavaDelegate {
 @Override
    public void execute(DelegateExecution execution) throws Exception {
 }
}
Из сервис-таски в методе execute вычитывать 2 переменные процесса (nID_Rate_Indirectly, sBody_Indirectly) и вызывать сервис /setMessageFeedback_Indirectly.

Протестировать можно будет из процесса, созданого по задаче https://github.com/e-government-ua/iBP/issues/281

**Comment by ASkosyr** [comment]
Добавил новые поля sBody_Indirectly и nID_Rate_Indirectly в сущности SubjectMessage и НistoryEvent_Service соответственно.

Добавил метод /setMessageFeedback_Indirectly в сервис ActivitiRestSubjectMessageController. На данный момент происходит только обновление НistoryEvent_Service (для SubjectMessage ищется решение как идентифицировать существующий объект).

Добавил новый компонент SetMessageFeedback_Indirectly

**Comment by bvv4ik** [comment]
по сути - реализовано
