### ISSUE TITLE
В сущность HistoryEvent_Service добавить еще 2-а необязательных поля и обеспечить их сохранение

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#962]
- [x] 1). На централе:
В сущность HistoryEvent_Service добавить еще 2-а необязательных поля
nID_Proccess_Feedback
nID_Proccess_Escalation (это поле на перспективу для следующего тз по эскалации)

Добавить в метод изменения истории в классе RemoteHistoryEventService эти 2-а поля. 
Учесть тот факт, что они могут быть наловыми. Добавить в сервис /updateHistoryEvent_Service эти поля. 
Обеспечить их сохранение в таблицу.

- [x] 2) В интерцептор org.activiti.rest.interceptor.RequestProcessingInterceptor при закрытии всего процесса (смотреть как проверить, что процесс закрыт в getTotalTimeOfExecution) в случае, если процесс не системный  (название процесса не начинается с "system") запускать новый процесс по отработке фидбеков (ид процесса взять после реализации задачи https://github.com/e-government-ua/iBP/issues/281). 
В стартовую таску передать все необходимые поля (взять значения из закрытого процесса). 

ид процесса для запуска:
system_feedback

переменные процесса:
bankIdlastName
bankIdfirstName
bankIdfirstName
phone

nID_Protected - взять из таски
processName - название процесса 
processID - ид процесса (уникальный идентификатор)

organ - название группы, которая отработала закрываемую таску

- [x] 3)  После запуска процесса в вызов метода updateHistoryEvent передавать также 
дополнительное поле nID_Proccess_Feedback, куда помещать ид запущенного процесса

Связанная задача: https://github.com/e-government-ua/i/issues/961

**Comment by LamronNu** [comment]
для теста:
1) запустить любой бп и пройти его "до конца", т.е. отработать все задачи.
например, если это справка о несудимости, то там только одна задача с результатом дать/не дать справку. результат не важен -- важно, чтобы процесс был завершен.
после завершения перейти во вкладку "Необроблені" и убедиться, что стартовал бп "Відпрацювання зворотного зв’язку /обробка волонтером", в котором заполнены поля:
-ФИО
-телефон
-ид бп (равен номеру заявки завершенного бп без последней цифры)
-название услуги
-орган (тот, кто обработал заявку. если их несколько, то пишутся через запятую)

2) убедиться, что ид процесса по фидбеку (номер бп без последней цифры) сохранился в HistoryEvent_Service завершенного процесса, например, таким запросом:  https://test.igov.org.ua/wf/service/services/getHistoryEvent_Service?nID_Server=0&nID_Process=7602501
где nID_Process -- это ид завершенного процесса (в дашборде это поле в бп по фидбеку называется "ID бізнес-процесу")
или запросом: https://test.igov.org.ua/wf/service/services/getHistoryEvent_Service?nID_Protected=xxx , где nID_Protected -- это номер заявки

также в этом пункте сразу смотрим, что в полученном обьекте есть два новых поля из п.1 этой таски (nID_Proccess_Feedback и nID_Proccess_Escalation)

3) проверить, что после завершения процесса фидбека (т.е. "взять в работу" -- а потом "опрацювати") -- новый процесс фидбека НЕ стартует (ограничение, что процесс должен быть не системным)

**Comment by nazarenkod** [comment]
Проверено на справке о несудимости. Все работает корректно. Новые поля присутствуют. После завершения процесса фидбека новый процесс фидбека не стартует.
