### ISSUE TITLE
Починить отображение чекбоксов при внесении замечания

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#963]
https://test.region.igov.org.ua/tasks  Если сюда зайти, зайти на вкладочку "Вроботі" и ввести в окошке-поиске 71817175 ид задачи и по задаче нажать кнопочку Внести зауваження, то много чекбоксов внизу отобразится.

По завершению просьба отписаться в задачке https://github.com/e-government-ua/i/issues/835#issuecomment-157986734, что можно продолжать тестирование. Также в этой задачке есть скрин с данной ситуацией.

**Comment by VadimGulich** [comment]
yes fixd
