### ISSUE TITLE
Доработать реализацию в задачке: https://github.com/e-government-ua/i/issues/584 возможностью добавлять в форму более одного поля sCountry_UA

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#964]
Доработать реализацию в задачке: https://github.com/e-government-ua/i/issues/584 возможностью добавлять в форму более одного поля sCountry_UA. Тоесть дать возможность добавлять поля на форму sCountry_UA, sCountry_UA_1, sCountry_UA_2 и тд., которые на клиенте будут иметь поведение, аналогичное, как сейчас реализовано для sCountry_UA.

**Comment by bvv4ik** [comment]
не актуально, т.к. перенесено в другие ишью:
https://github.com/e-government-ua/i/issues/969
https://github.com/e-government-ua/i/issues/980
https://github.com/e-government-ua/i/issues/979

**Comment by GrekD** [comment]
работает
