### ISSUE TITLE
Создать сущность Currency и сервисы к ней

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#966]
Источник данных:
http://search.ligazakon.ua/l_doc2.nsf/link1/FIN14565.html

1) Сущность Currency
nID - ИД-номер Код внутренний (уникальный-ключ, автоитерируемый, long)
sID_UA - ИД-номер Код, в Украинском классификкаторе (уникальный-ключ, String < 10 символов)
sName_UA - название на украинском (уникальный, String < 200 символов)
sName_EN - название на английском (уникальный, String < 200 символов)

Пример объкта сущности:
{
   nID,3
, "sID_UA ":"008 "
, "sName_UA":"Лек"
, "sName_EN":"Lek "
}

2) сервисы:

2.1) getCurrencies - отдает массив объектов сущности, подпадающих под критерии
параметры:
sID_UA //опциональный
sName_UA//опциональный
sName_EN//опциональный

2.2) setCurrency - апдейтит элемент(если задан один из уникальных-ключей) или вставляет (если не задан nID), и отдает экземпляр нового объекта
параметры:
nID //опциональный, если другой уникальный-ключ задан и по нему найдена запись
sID_UA //опциональный, если другой уникальный-ключ задан и по нему найдена запись
sName_UA//опциональный, если nID задан и по нему найдена запись
sName_EN//опциональный, если nID задан и по нему найдена запись

2.3) removeCurrency - удаляет элемент(по ОБЯЗАТЕЛЬНО заданому одому из уникальных-ключей)
параметры:
nID //опциональный, если другой уникальный-ключ задан и по нему найдена запись
sID_UA //опциональный, если другой уникальный-ключ задан и по нему найдена запись

3) Наполнить данными csv

4) Добавить документацию

**Comment by grigoriy-romanenko** [comment]
добавил документацию: https://github.com/e-government-ua/i/blob/test/docs/specification.md#50
можно тестировать

**Comment by nazarenkod** [comment]
Работает согласно описанию

**Comment by bvv4ik** [comment]
@grigoriy-romanenko
оказывается, у нас так и не заполнен полностью справочник по валютам из классификатора?

сможешь до-заполнить плиз? а то не можем начать юзать...

**Comment by grigoriy-romanenko** [comment]
согласно ТЗ сущность Currency должна иметь уникальный ключ sID_UA.
источник данных содержит 2 валюты с одинаковым кодом 0: UIC-Franc, Gold-Franc.
нужно переписать ТЗ или не добавлять эти 2 валюты.
как поступить?

**Comment by grigoriy-romanenko** [comment]
еще проблема:
в источнике данных 2 записи для российского рубля с разными кодами: 643 и 810

**Comment by GrekD** [comment]
UIC-Franc, Gold-Franc. - не добавляйте
Рубль - числовой код — 643 (в банковской системе по-прежнему используется старый 810)
оставьте, пожалуйста, только 643
если что  - я 810 сама добавлю

**Comment by grigoriy-romanenko** [comment]
@GrekD 
проверил на дубликаты источник данных.
нашел еще повтор. запись: валюта - Квача, коды - 454 и 894
которую удалить?
больше дубликатов нет

**Comment by GrekD** [comment]
@grigoriy-romanenko 
добавьте, пожалуйста, обе.
в скобочках добавить страну
Квача (Малави)
Квача (Замбия)
спасибо большое!

**Comment by grigoriy-romanenko** [comment]
готово

**Comment by RoOmel** [comment]
1) Проверил ниличие в базе валюты с кодом 777 запросом
https://test.igov.org.ua/wf/service/services/getCurrencies?sID_UA=777
Ответ сервера
200 OK

2) Добавил новую валюту по запросу
https://test.igov.org.ua/wf/service/services/setCurrency?sID_UA=777&sName_UA=Тест&sName_EN=Тest
Ответ сервера
{
    "sID_UA": "777",
    "sName_UA": "Тест",
    "sName_EN": "Тest",
    "nID": 44820
}
3) Повторил пункт 1)
Ответ сервера
[
    {
        "sID_UA": "777",
        "sName_UA": "Тест",
        "sName_EN": "Тest",
        "nID": 44820
    }
]
4) Удалил созданную валюту запросом
https://test.igov.org.ua/wf/service/services/removeCurrency?sID_UA=777
Ответ сервера
200 OK
5) Повторил пункт 1)
Ответ сервера
200 OK

Реализовано согласно ТЗ.
