### ISSUE TITLE
Создать сущность SubjectOrganJoinTax и сервисы к ней

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#967]
1) Название сущности: SubjectOrganJoinTax
nID - ИД-номер Код внутренний (уникальный-ключ, автоитерируемый, long)
sID_UA - ИД-номер Код, в Украинском классификкаторе (уникальный-ключ, String < 30 символов)
sName_UA - название на украинском (уникальный, String < 100 символов)
nID_SubjectOrganJoin - ИД-шник корневой записи сущности SubjectOrganJoin, для каждой области - свой. (обязательное поле)

Пример объекта сущности:
{
   nID,3
, "sID_UA ":"008 "
, "sName_UA":"Служба боротьби з контрабандою та порушеннями митних правил"
, "nID_SubjectOrganJoin":45
}

3) сервисы:

3.1) getSubjectOrganJoinTax - отдает массив объектов сущности, подпадающих под критерии
параметры:
sID_UA //опциональный
sName_UA//опциональный

3.2) setSubjectOrganJoinTax - апдейтит элемент(если задан один из уникальных-ключей) или вставляет (если не задан nID), и отдает экземпляр нового объекта
параметры:
nID //опциональный, если другой уникальный-ключ задан и по нему найдена запись
sID_UA //опциональный, если другой уникальный-ключ задан и по нему найдена запись
sName_UA//опциональный, если nID задан и по нему найдена запись

3.3) removeSubjectOrganJoinTax - удаляет элемент(по ОБЯЗАТЕЛЬНО заданому одому из уникальных-ключей)
параметры:
nID //опциональный, если другой уникальный-ключ задан и по нему найдена запись
sID_UA //опциональный, если другой уникальный-ключ задан и по нему найдена запись

4) Наполнить данными csv
4.1) в сущности SubjectOrgan и Subject - пробрасываем связанные друг с другом записи общего органа-субъекта "Таможня"
4.2) в сущности SubjectOrganJoin - добавляем по записи для каждой области (например: "Митниця Житомирськой області", "Митниця Дніпропетровськой області" и т.д., и подвязываем к единой записи в сущности SubjectOrgan.
Для кейса, когда это какие-то общеукраинские таможенные органы, то тогда в SubjectOrganJoinTax будет что-то вроде "Митниця - загальнодержавний орган"

4.3) Заполняем из справочника данные в SubjectOrganJoinTax.csv
Описание:
- скопировать через буфер обмена список в эксель: http://sfs.gov.ua/baneryi/mitne-oformlennya/subektam-zed/reestri-ta-klasifikatori/klasifikatori/vidomchi-klasifikatori-informatsii-z-pi/62554.html
- там по удалять ненужные строки
- поменять местами колонки
- дать названия колонок
- сохранить в виде CSV, разделенного ";"

Другие источники данных:
http://search.ligazakon.ua/l_doc2.nsf/link1/MK060542.html
http://www.mdoffice.com.ua/pls/MDOffice/aMDOClassDic.html?dic_num=10

5) В комментариях внести описания сервиса и его параметров с выводом (в т.ч. пример объекта), и убедиться что после деплоя - автосгенерируется документация по АПИ
(в одной из первых двух ссылок тут: https://github.com/e-government-ua/i/blob/test/docs/specification.md)

**Comment by kalu44i** [comment]
Доробити:
1) Тести
2) Валідні дані з джерел

**Comment by bvv4ik** [comment]
Добрый день,
пламался билд сегодня с утра:
после этого комита:

github BOT [8:29 AM] 
[i:test] 1 new commit by Nick:
9211131: #967 Add "TaxOrgan" Model, Controller - Nick
https://github.com/e-government-ua/i/commit/9211131a3925f023ad13c09a26550c94fb898980

вот отчет:
https://jenkins.igov.org.ua/view/new/job/central_alpha/5825/console

**Comment by bvv4ik** [comment]
нужно срочто починить, а то ни кто деплоить не может...

и, прошу маякнуть мне в скайп belyavtsevw, т.к. не нашел Ваших контактов у нас...

**Comment by kalu44i** [comment]
Добрий день, смотрю

**Comment by kalu44i** [comment]
Готово

**Comment by kalu44i** [comment]
To Do:
1) Дістати валідні дані з джерела http://search.ligazakon.ua/l_doc2.nsf/link1/MK060542.html
пс: Дані в джерелі 
2) Додати тести
3) Проапдейтити доки

**Comment by bvv4ik** [comment]
по п.1
рекоммендую скопировать через буфер обмена список в эксель:
http://sfs.gov.ua/baneryi/mitne-oformlennya/subektam-zed/reestri-ta-klasifikatori/klasifikatori/vidomchi-klasifikatori-informatsii-z-pi/62554.html

там поудалять ненужные строки
поменять местами колонки
дать названия колонок
и сохранить в виде CSV, разделенного ";"

это будет более быстрый и удобный способ...

**Comment by bvv4ik** [comment]
следующим пунктом лучше доку написать
а уже в последнюю очередь тесты

**Comment by bvv4ik** [comment]
еще такой вопрос, конечно, особо не надеюсь, но все-же, если есть ккой-то шанс, то пока не сильно поздно - хочу попробовать воспользоваться...

дело в том, что немного упустил момент, когда именовали сущность (я был как раз не доступен в тот период времени)
я стараюсь придерживаться определенной системы в именовании, чтоб потом было легче ориентироваться...

Очень хотелось-бы фразу в сущности и названиях методов:
"TaxOrgan"
заменить на:
"SubjectOrganJoinTax"

скорей всего останутся после этого "бесхозными" старые названия табличек созданных, в базе, но я-бы их ручками поприбывал... все-же лучше, т.к. в боевом уже все будет красиво...

**Comment by bvv4ik** [comment]
как только будет все ок - прошу маякнуть, и я поправлю в этой ишью, чтоб небыло путанницы...

**Comment by kalu44i** [comment]
Done:
1) "TaxOrgan"замінено на: "SubjectOrganJoinTax"
2) Додано файл з данними SubjectOrganJoinTax.csv (джерело - http://sfs.gov.ua/baneryi/mitne-oformlennya/subektam-zed/reestri-ta-klasifikatori/klasifikatori/vidomchi-klasifikatori-informatsii-z-pi/62554.html)

**Comment by kalu44i** [comment]
1. Обмеження поля sName_UA встановив 190 символів, так як найбільша назва митного органу має 189 символів
2. Таблиця митних органів тут http://sfs.gov.ua/baneryi/mitne-oformlennya/subektam-zed/reestri-ta-klasifikatori/klasifikatori/vidomchi-klasifikatori-informatsii-z-pi/62554.html розділена на розділи по регіонам і тим самим у нас повторюються назви митного органу, наприклад "Відділ митних платежів", тим самим sName_UA є не унікальний. Можемо додавати до назви митного органу назву регіону, типу "Відділ митних платежів (Київська регіональна митниця)", або ж нормалізувати сутність створивши окрему таблицю з регіонами (якщо такої немає) з nID, nName_Reg і додати в сутність SubjectOrganJoinTax нове поле nID_Reg, яке посилатиме на назву регіону. Що думаєте на рахунок цього?

**Comment by bvv4ik** [comment]
замечательно,
осталась малость - дока, и уже в спокойном режиме - тесты...

**Comment by bvv4ik** [comment]
[12:31:15] A Nick Veremeichyk: Доброго дня. Хотілося б пролити світло на питання про повторюваність назв митних органів, якщо можна. Я поки не представляю, що це за послуга і як вона виглядає в UI, але мабуть користувач буде вибирати певний митний орган, куди від хоче відіслати запит. Проте сервіс повертає нам митні органи, назви яких повторюються по регіонам. Як з цим бути?
[12:35:43] A Nick Veremeichyk: Тут http://sfs.gov.ua/baneryi/mitne-oformlennya/subektam-zed/reestri-ta-klasifikatori/klasifikatori/vidomchi-klasifikatori-informatsii-z-pi/62554.html, один орган належить до певного регіону і при цьому є унікальні назви, котрі не повторюються, але є назви стандартні для кожного регіону, наприклад “Відділ митних інформаційних технологій” зустрічається в 27 зонах діяльності.

**Comment by bvv4ik** [comment]
Так, общими усилиями в ситуации разобрался...
Решение такое:
1) в сущности SubjectOrgan и Subject - пробрасываем связанные друг с другом записи общего органа-субьекта "Таможня"
2) в сущности SubjectOrganJoin - добавляем по записи для кажной области (например: Таможня Житомирской области, Таможня Днепропетровской области и т.д., и подвязываем к единой записи в сущности SubjectOrgan
3) добавляем обязательное поле nID_SubjectOrganJoin, куда записывается ИД-шник корневой записи сущности SubjectOrganJoin, для каждой области - свой.

**Comment by bvv4ik** [comment]
таску поправил

**Comment by kalu44i** [comment]
Що записувати в сутності SubjectOrganJoin в колонки sID_Privat, sID_Public? 
Відповідно чи треба  заповнити колонки sGeoLongitude, sGeoLatitude реальними координатами?

**Comment by bvv4ik** [comment]
может я могу помочь с раскидыванием данных по csv?

**Comment by kalu44i** [comment]
Дякую. Дані вже готові. Залишилось зв'язати поля.

**Comment by kalu44i** [comment]
Враховуючи новий апдейт з додаванням нового поля nID_SubjectOrganJoin в таблицю SubjectOrganJoinTax зараз сервіс повертає список у вигляді 
```
{
"nID":1,
"nSubjectOrganJoin":
 {
"subjectOrganId":284,
  "nID":1152,
  "sNameUa":"Київська регіональна митниця",
  "sNameRu":"Київська регіональна митниця",
  "sID_Privat":"130000000",
  "sID_Public":"130000000",
  "sGeoLongitude":" ",
  "sGeoLatitude":" ",
  "nID_Region":null,
  "nID_City":null,
   "sID_UA":"10000 00 00"},
"sID_UA":"10000 00 01",
"sName_UA":"Служба боротьби з контрабандою та порушеннями митних правил"
}
```
і т.д.

**Comment by bvv4ik** [comment]
(дубль)
все-же тело, корневого обьекта, особо и не нужно... а учитывая то, что как правило будет возвращаться список, то этот лишний большой под-обьект серьезно все утяжелит...
потому лучше вернуться к исходно-описанному в ишью обьекту...
разве что ИД-шник корневого обьекта стоит выводить (вроде в ишью он написан)

**Comment by kalu44i** [comment]
Готово: 
1) https://test.igov.org.ua/wf/service/services/getSubjectOrganJoinTax
повертає список об'єктів у форматі:
```
{
nID,3
, "sID_UA ":"008 "
, "sName_UA":"Служба боротьби з контрабандою та порушеннями митних правил"
, "nID_SubjectOrganJoin":45
}
```
2) https://test.igov.org.ua/wf/service/services/setSubjectOrganJoinTax?nID=1
Апдейтить або повертає елемент
3) https://test.igov.org.ua/wf/service/services/removeSubjectOrganJoinTax?nID=1
Видаляє елемент.

To Do:
Проапдейтити сервіс getSubjectOrganJoinTax, щоб при наявності параметра nID_SubjectOrganJoin повертав список об'єктів з відповідним значенням nID_SubjectOrganJoin.

**Comment by kalu44i** [comment]
1. https://test.igov.org.ua/wf/service/services/getSubjectOrganJoinTax
Повертає весь список
2. https://test.igov.org.ua/wf/service/services/getSubjectOrganJoinTax?nID_SubjectOrganJoin=1152
Повертає список об'єктів, які відносяться до певного SubjectOrganJoin
3. https://test.igov.org.ua/wf/service/services/setSubjectOrganJoinTax?nID=2
Повертає об'єкт
4. https://test.igov.org.ua/wf/service/services/setSubjectOrganJoinTax?nID=2&sName_UA=test
Апдейтить sName_UA об'єкта з визначеним nID
5. https://test.igov.org.ua/wf/service/services/setSubjectOrganJoinTax?nID=2&sName_UA=test&sID_UA=10000 00 02
Апдейтить sName_UA and sID_UA об'єкта з визначеним nID
6. https://test.igov.org.ua/wf/service/services/setSubjectOrganJoinTax?sName_UA=test&sID_UA=99900%2000%2002&nID_SubjectOrganJoin=1152
Додає новий запис, якщо sID_UA не існує. 
7. https://test.igov.org.ua/wf/service/services/removeSubjectOrganJoinTax?nID=2
Видаляє елемент по nID або sID_UA.

**Comment by bvv4ik** [comment]
Красота)
спасибо!

передаю коллегам для реализации фронта..

**Comment by RoOmel** [comment]
1) При запросе
https://server:port/wf/service/services/setSubjectOrganJoinTax?nID=&sID_UA=&sName_UA=
т.е. параметры без значений - запрос "зависает";
2) При запросе
https://test.igov.org.ua/wf/service/services/getSubjectOrganJoinTax?nID=42980&sID_UA=99900 00 02&sName_UA=test&nID_SubjectOrganJoin=1152
выдаёт полный массив. при этом учитывается выборка только по параметру nID_SubjectOrganJoin, остальные значения параметров не учитываются;
3) При запросе
https://server:port/wf/service/services/setSubjectOrganJoinTax?nID=1111&sID_UA=22222&sName_UA=Test&nID_SubjectOrganJoin=999999
ответ сервера "зависает"
4) Запросы
https://test.igov.org.ua/wf/service/services/setSubjectOrganJoinTax?nID=2
https://test.igov.org.ua/wf/service/services/setSubjectOrganJoinTax?nID=2&sName_UA=test
https://test.igov.org.ua/wf/service/services/setSubjectOrganJoinTax?nID=2&sName_UA=test&sID_UA=10000
https://test.igov.org.ua/wf/service/services/setSubjectOrganJoinTax?sName_UA=test&sID_UA=99900 2000 2002&nID_SubjectOrganJoin=1152
https://test.igov.org.ua/wf/service/services/removeSubjectOrganJoinTax?nID=43758
возвращают ответы сервера согласно описания

**Comment by bvv4ik** [comment]
результатом работы будет завершенность и проверенность таски:
https://github.com/e-government-ua/i/issues/994
