### ISSUE TITLE
Создать сущность ObjectCustoms и сервисы к ней

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#968]
Источник данных в приложении:
https://drive.google.com/file/d/0Bzn9Xk_GDNRUa3NLUk5vRXBkc2s/view?usp=sharing

1) Название сущности: ObjectCustoms
nID - ИД-номер Код внутренний (уникальный-ключ, автоитерируемый, long)
sID_UA - ИД-номер Код, в Украинском классификкаторе (уникальный-ключ, String < 30 символов)
sName_UA - название на украинском (уникальный, String < 200 символов)
sMeasure_UA - мера  (String < 20 символов)

Пример объкта сущности:
{
  nID:3
, "sID_UA":"008 "
, "sName_UA":"Пряжа"
, "sMeasure_UA" : "кг"
}

2) сервисы:

2.1) getObjectCustoms - отдает массив объектов сущности, подпадающих под критерии
параметры:
sID_UA //опциональный
sName_UA//опциональный

2.2) setObjectCustoms - апдейтит элемент(если задан один из уникальных-ключей) или вставляет (если не задан nID), и отдает экземпляр нового объекта
параметры:
nID //опциональный, если другой уникальный-ключ задан и по нему найдена запись
sID_UA //опциональный, если другой уникальный-ключ задан и по нему найдена запись
sName_UA//опциональный, если nID задан и по нему найдена запись

2.3) removeObjectCustoms - удаляет элемент(по ОБЯЗАТЕЛЬНО заданому одому из уникальных-ключей)
параметры:
nID //опциональный, если другой уникальный-ключ задан и по нему найдена запись
sID_UA //опциональный, если другой уникальный-ключ задан и по нему найдена запись

3) Наполнить данными csv

4) В комментариях внести описания сервиса и его параметров с выводом (в т.ч. пример объекта), и убедиться что после деплоя - автосгенерируется документация по АПИ
(в одной из первых двух ссылок тут: https://github.com/e-government-ua/i/blob/test/docs/specification.md)

**Comment by lesha1980** [comment]
Подскажите. При наполнении csv нужно все записи из источника добавить? Их больше 1500.
Как я понимаю, sID_UA — это код УКТЗЕД? 
Что заносить в sName_UA? Вторая колонка, представленного источника содержит описание к коду, которое больше 200 символов, что отведены под sName_UA.
Как определить меру измерения для товара, если она не всегда указана в описании источника? Можно ли по смыслу? Или просто оставлять незаполненным поле sMeasure_UA?

**Comment by GrekD** [comment]
Как я понимаю, sID_UA — это код УКТЗЕД?  - да
Что заносить в sName_UA? - опис товару (2 колонка), думаю надо увеличить количество допустимых символов (если это возможно)

Можно ли по смыслу? - там много всяких странных мер 
http://www.mdoffice.com.ua/pls/MDOffice/aMDOClassDic.html?dic_num=14
трудно будет просто по смыслу подставить, мне кажется

Или просто оставлять незаполненным поле sMeasure_UA?
да, наверное, пока оставить незаполненным

**Comment by BorisEfimenko** [comment]
Коллеги, один и тот же товар может быть в разных  единицах измерения. По опыту, клей встречался в литрах, кг, единицах, тюбиках, бутылках и т.д. 
Поэтому на сущности, на которой предполагается ссылка на продукцию должна быть и ссылка на справочник единиц измерения. И если и иметь ссылку со справочника продукции на измерение, то только в роли "единица измерения по умолчанию".

**Comment by lesha1980** [comment]
Честно говоря, не знаю можно ли изменить значение ограничения числа символов. Пока что закрепил 200 за sName_UA согласно условиям таски.

**Comment by lesha1980** [comment]
Интересно. Получается, что в  УКТЗЕД основной единицей измерения считается килограмм, однако есть ряд дополнительных единиц и такая единица как "штука" — одна из дополнительных единиц измерения... А многие товарные позиции вообще не имеют единицы измерения, что обозначается прочерком "-".

**Comment by lesha1980** [comment]
Ну что ж... Я пока сделаю так (так как нет точного ответа и если принимающая работу сторона будет согласна) увеличу ограничение параметра sName_UA, а в поле sMeasure_UA каждой товарной позиции проставлю прочерк "-".

**Comment by bvv4ik** [comment]
"Честно говоря, не знаю можно ли изменить значение ограничения числа символов. Пока что закрепил 200 за sName_UA согласно условиям таски."

точно можно)

200 пока хватит, всегда отдельным чанджсетом сможем это в будущем поправить

**Comment by bvv4ik** [comment]
еще вопрос - сущность уже создана?

**Comment by bvv4ik** [comment]
если не создана. или не создано еще очень много, то прошу сущность и соответствующие методы вместо:
ProductСode
назвать:
ObjectCustoms
(я смогу подправить в таске)

**Comment by lesha1980** [comment]
1)еще вопрос - сущность уже создана?

Уже и сущность создал и сервисы: выборка значений, установка новых и апдейт, удаление записи. Создал также несколько тестов. 

2)200 пока хватит, всегда отдельным чанджсетом сможем это в будущем поправить

Изменил на 5000  и в чанджсете и в сущности. Ряд описаний товарных позиций зашкаливает за 4000 символов. Проблема сейчас в наполнении реальными значениями из источника данных. Вчера допоздна сидел придумывал как справиться с некоторыми неприятностями, связанными с самим УКТЗЕД, у которого есть специальный разделительный знак ";", а сепаратор для csv как раз этот разделитель, поэтому чтение из сущности не происходит корректно. Если взять в двойные кавычки описание, имеющее разделитель точку с запятой, то все читается нормально. Однако проблема в том, что часть описаний в источнике взята в кавычки, а часть нет. Поэтому хочу справиться с этой проблемой и протестить на реальных данных, чтобы уже затем коммитить.

3)если не создана. или не создано еще очень много, то прошу сущность и соответствующие методы вместо:
ProductСode
назвать:
ObjectCustoms
(я смогу подправить в таске)

Думаю, что смогу поменять названия методов.

**Comment by bvv4ik** [comment]
отлично, спасибо!

по п.2 рекомендую залить просто весь контент справочника из источника - в вордовский файл, и там реплейсом позаменять массово все ненужное...

потом скопировать в эксель,
дать название колонок
поменять местами колонки
и сохранить в формат csv, с разделителями ";"

это будет и легче и быстрее и надежней...

**Comment by bvv4ik** [comment]
я тогда сейчас в ишью заменю: ProductСode на: ObjectCustoms

**Comment by lesha1980** [comment]
по п.2 рекомендую залить просто весь контент справочника из источника - в вордовский файл, и там реплейсом позаменять массово все ненужное...

Обнаружил, что в справочнике есть неуникальные УКТЗЕД: например, 1-я запись и 8-я совпадают по номеру УКТЗЕД, но отличаются по описанию... Проект не желает собираться, так как sID_UA сделал уникальным. Попробую отсеять неуникальные....

**Comment by bvv4ik** [comment]
а там точно нули в начале не сократились?

**Comment by lesha1980** [comment]
Если брать по ссылке то это записи 3 строка и 11

**Comment by lesha1980** [comment]
5509320010

**Comment by bvv4ik** [comment]
да, вохоже этот источник не совсем классификатор... а просто каталог, связывающий классификатор
стоит поискать в нете оригинальный классификатор

**Comment by lesha1980** [comment]
Хм. Такая же история со второй товарной позицией 6912009000

**Comment by bvv4ik** [comment]
этот источник  - явно не классификатор... в нете нужно поискать...

**Comment by lesha1980** [comment]
http://sta-sumy.gov.ua/dovidniki--reestri--perelik/dovidniki-/54000.html

Посмотрите. Думаю должно подойти "Державна фіскальна служба". Там в doc файле и все собрано по группам и в отдельные таблицы.

**Comment by lesha1980** [comment]
Я так понимаю, что этот документ нуждается в дополнительной обработке, кроме того, что его нужно сделать в формате csv.

**Comment by bvv4ik** [comment]
да, это уже верный классификатор,
и теперь важно будет уточнить у БА - им именно классификатор товаров нужен, или конкретно тот  справочник номенклатуры, по каждой позиции которого происходит отождествление с базовыв классификаторам...

вообщем, это сейчас уточню, а пока и правда - стоит переименовать...

сразу отпишусь...
Спаасибо

**Comment by GrekD** [comment]
добрый день. нужен именно классификатор товаров
его  название  должен выбрать заявитель - потом это название и код должно передаваться в принтформу

**Comment by bvv4ik** [comment]
@lesha1980 а можно плиз напомнить логин в скайпе и полное ФИО на украинском?

**Comment by lesha1980** [comment]
1) @lesha1980 а можно плиз напомнить логин в скайпе и полное ФИО на украинском?

skype: lesha8021
ФИО: Ієвенко Олексій Олексійович

2.  Вопрос только. Как быть с классификатором?

**Comment by bvv4ik** [comment]
спасибо,

"Вопрос только. Как быть с классификатором?"

как и сказала Дарья и как я предполагал - берем именно этот корректный классификатор, правда тут чтоб получить вменяемые названия - придется попотеть с импортом данных... правда это уже можно делать в самом конце. а, когдато такой штукой занимался (именно приводил в нормальный вид наш национальный классификатор товаров) - тут эксель очень сильно поможет со своими чудными формулами работы с текстом... я смогу помоч, если будут сложности в этом...

**Comment by lesha1980** [comment]
Пока сделал плоский список в csv формате. Но единственной трудностью пока остаются пустые ячейки кодов некоторых обобщающих названий вида "коні" а далее конкретизация в виде кода и конкретного названия типа "на убой". У записи "коні" отсутствует номерной код так как сама запись исполняет роль родителя последующих конкретных записей. 

пример

код               назва
                   -- коні
11000         ---на убой
11001         --- інші

что-то в этом духе...
и таких записей немало... думаю обобщающие лишенные кода записи перенести к потомкам  с кодом

**Comment by lesha1980** [comment]
Пришел к выводу, что в УКТЗЕД как минимум должно быть 5 связанных таблиц в соответствии со структурой кода. Да...работки много с подготовкой данных...! Придется и сервисную часть переделывать, так как делал ее под простой список одной таблицы...

**Comment by bvv4ik** [comment]
ненужно там сложной структуры...
нужно просто во всех записях типа "---на убой"
вместо "---" продублировать вышестоящие участки дерева... 
это реализуется через формулы в экселе, я такое делал, в свое время...

**Comment by lesha1980** [comment]
ненужно там сложной структуры...
нужно просто во всех записях типа "---на убой"
вместо "---" продублировать вышестоящие участки дерева... 
это реализуется через формулы в экселе, я такое делал, в свое время...

Т.е. оставить одной таблицей, простым списком записей. А то я сел уже делать несколько таблиц: "Разделы", "Группы", "Товарная позиция"... Ок. тогда просто отредактирую записи. Соответственно записи с пустыми кодами я удалю, так как проект воспримет их как неуникальные с неуникальными значениями...

**Comment by bvv4ik** [comment]
"Т.е. оставить одной таблицей, простым списком записей."
да)
"А то я сел уже делать несколько таблиц: "Разделы", "Группы", "Товарная позиция"..."
ни в коем случае) если мы каждый раз, ради наших классификаторов общенациональных начнем плодить сущности - зашьемся...

"А какие формулы вы использовали, если помните..?"
там это нужно делать через разнесение данных по нескольким колонкам, в каждой колонке только  значение для одного уровня, например там где "---" вначале... или "--", и т.д.
а потом в еще одной колонке это все собирается... копируется как значения в еще одной колонке новой страницы и туда другие статичные даннные (коды), и потом сохраняется в csv

есть формулы, которые возвращают значение, находящееся от ячейки, со смещением строки и колонки...

**Comment by lesha1980** [comment]
Минусы не удается оставить, так как разделяю текст по разделителю "-", однако для отображения нескольких вхождений можно принять как разделитель  ":" (двоеточие) — он используется там, где указывается следующее уточнение. Если уточнения нет и соответственно нет подуровня, то нет и двоеточия.

**Comment by bvv4ik** [comment]
ну, можно и так)

хотел уточнить - в принципе, я так понял - сама реализация уже готова и остается только переформатировать данные для csv?
если так, то я просил-бы пока просто пролить десяток строк для теста, чтоб можно было уже передать в работу производную таску по фронту (чтоб не терять время)
а уже тем временем, не спеша доделать списки и до пролить их...

**Comment by lesha1980** [comment]
Все почти готово, но приходится вносить некоторые корректировки, так как например более понятным стал sID_UA — делаю под него регулярное выражение и вношу изменения в метод извлечения данных, sMeasure теперь также стал более определенным, поэтому все допустимые единицы измерения забил в массив, чтобы можно было проверить корректность введенной единицы измерения, однако сам sMeasure_UA в таблице остается "-", так как не встретил графы единицы измерения в самом УКТЗЕД у товарных позиций. С единицей измерения еще нужно урегулировать вопрос, так как в сущности поле есть, а по сути оно не используется. Также, вносимые изменения необходимо проверить. Затем буду отправлять....

**Comment by bvv4ik** [comment]
"С единицей измерения еще нужно урегулировать вопрос, так как в сущности поле есть, а по сути оно не используется."
пока достаточно выдавать его отдельным элементом каждого объекта сущности... уже усложнять будем по мере необходимости..

"более понятным стал sID_UA — делаю под него регулярное выражение и вношу изменения в метод извлечения данных"
т.е. при создании новой записи он будет валидировать по регексу формат?
думаю - не стоит пока на это тратить время, т.к. со временем реализуем более унифицированный подход к валидации таких вот идентификаторов, в рамках общеукраинских классификаторов...

важнее завершить основу задачи, чтоб можно было начать делать фронт

**Comment by lesha1980** [comment]
Вытолкнул... Вроде задеплоилось. Только с документацией не получилось, так как параметры есть, а пояснений по ним нет (вида опциональный)...

**Comment by lesha1980** [comment]
Для тестирования контроллера сервисов создал ряд тестов в файле ActivitiRestObjectCustomsControllerTest.java

**Comment by bvv4ik** [comment]
Супер! Спасибо!
ну. теперь можно спокойно фронт прикручивать)

**Comment by RoOmel** [comment]
Запрос
https://test.region.igov.org.ua/wf/services/getObjectCustoms?sID_UA="0101"&sName_UA=
возвращает html-страницу вместо списка объектов

При запросе
https://test.region.igov.org.ua/wf/services/setObjectCustoms?nID=&sID_UA=9999 99 99 99&sName_UA=test&sMeasure_UA=
возвращает html-страницу

**Comment by lesha1980** [comment]
Прошу в доке ActivitiRestObjectCustomsControllerTest.java прописать host, т.к. неясно по корректному ли пути идут запросы .
------------------------------------
Вытолкнул... Коментарии в доке должны будут обновиться. 
Я тестировал на запросах вида http://localhost:8080/wf/service/services/getObjectSubjects?

У вас в URL отсутствует service после wf.... Хост указывать вам не могу, так как я работаю лишь с локальным хостом.

**Comment by RoOmel** [comment]
Ну так правильно, потому что так в доке написано
/services/getObjectCustoms
а в комменте
/wf/service/services/getObjectCustoms
Скорректировал URL, но по запросу
https://test.region.igov.org.ua/wf/service/services/getObjectCustoms?sID_UA="0101"&sName_UA=
попрежнему возвращается html-страница, что совсем непохоже на ответ в примере дока.

**Comment by lesha1980** [comment]
lesha1980
"У вас в URL отсутствует service после wf"
Ну так правильно, потому что так в доке написано
/services/getObjectCustoms
а в комменте
/wf/service/services/getObjectCustoms
Скорректировал URL, но по запросу
https://test.region.igov.org.ua/wf/service/services/getObjectCustoms?sID_UA="0101"&sName_UA=
попрежнему возвращается html-страница, что совсем непохоже на ответ в примере дока.

Вы его на региональном тестируете, но я делал его для wf-central, т.е. хост должен быть test.igov.org.ua

**Comment by RoOmel** [comment]
1) По запросу
https://test.igov.org.ua/wf/service/services/setObjectCustoms?nID=44354&sID_UA=9999 99 99 99&sName_UA=Test&sMeasure_UA=-
Добавлена запись 
{
    "sID_UA": "9999 99 99 99",
    "sName_UA": "Test",
    "sMeasure_UA": "-",
    "nID": 44354
}

2) По запросу
https://test.igov.org.ua/wf/service/services/getObjectCustoms?sID_UA=9999 99 99 99&sName_UA=
Отображается запись
[
    {
        "sID_UA": "9999 99 99 99",
        "sName_UA": "Test",
        "sMeasure_UA": "-",
        "nID": 44354
    }
]
Реализовано согласно ТЗ

**Comment by lesha1980** [comment]
Закончил наконец с УКТЗЕД. Всего получилось 14403 позиции. Также, проверил наличие ошибок. Надеюсь, что все ошибки, которые допустил при обработке УКТЗЕД заметил и исправил. Увеличил также размер sName_UA. Очень важно при добавлении или обновлении в поле sID_UA убирать у добавляемой строки передний и задний пробелы, иначе может быть потеряна уникальность значения. Также, важно брать в кавычкм строку добавляемую в sName_UA, если в ней есть "точка с запятой" — ";". Эти фильтры по-моему лучше делать на фронте, поэтому не писал их.
