### ISSUE TITLE
При выборе Харьковской области, город Харьков для вкладки "Услуги", в выпадающем списке "Мета отримання довiдки" имеется ошибка в написании одного из пунктов.

### ISSUE THREAD

**Issue by zhernovoj** [e-government-ua/i#970]
[S5]
Windows 7 (x32), Google Chrome V46.0.2490.86 m
https://test.igov.org.ua/service/1/general
1. Во вкладке "Послуга"  выбираем Область - "Харкiвська", Мiсто - "Харкiв".
2. Вход в систему через BankID -> ПриватБанк -> Логин: +380102030405, пароль: value, SMS: 123456.
3. Смотрим информацию в выпадающем списке "Мета отримання довiдки"
ОР - пункт №4 - Имеет следующий вид - "Надання в установи iноземних держав, працевлаштування за кордоном."
ФР - пункт №4 - Имеет следующий вид "ОНадання в установи iноземних держав, працевлаштування за кордоном."

**Comment by bvv4ik** [comment]
@kurbpa Павел, глянь плиз, или попроси кого...

@zhernovoj спасибо, но прошу в будущем, такого рода находки писать в:
https://github.com/e-government-ua/iForum/issues

т.к. данный репозиторий только для тасок разработки...
(и когда тут свалка - очень тяжело работать)
