### ISSUE TITLE
Ошибка в инструкции по Dropbox   

### ISSUE THREAD

**Issue by yurikoles** [e-government-ua/i#971]
>* 4.3. Зарегистрируйтесь в DropBox [по приглашению] (https://db.tt/Nsnjd895), и можно будет "Вас расшарить" общую папку по eGov.ua, через которую можно оперативно обмениваться для работы важными и полезным фичам, компонентами и мануалами.

А если человек уже там зарегистрирован, например? Прошу учесть этот вариант в инструкции.

Ну и вообще перейти на Google Drive, вероятность наличия Google Account`а у человека на много выше, что упрощает процесс. Тем более вы сами это признаёте, т.к. даже не учитываете вариант наличия аккаунта Dropbox.

**Comment by bvv4ik** [comment]
нет общей папки вне дропбокса, есть дропбокс... можно дописать фразу "если у Вас уже зарегистрирован дропбокс, то просто обратитесь в скайп к belyavtsevw"
