### ISSUE TITLE
Доработать сущность FlowLink для поддержки учета департамента, по мимо услуги

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#973]
1) Добавить в сущность FlowLink поле nID_SubjectOrganDepartment
(дописывать в отдельном чанджсете бэйсового xml-а

2) Доработать метод /getFlowSlots_ServiceData, чтоб передаваемый параметр nID_SubjectOrganDepartment так-же опционально учитывался и с переданным параметром 
nID_Service (как это чейчас реализовано для параметра nID_ServiceData)

т.е.чтоб если передан параметр nID_Service, возможны только два сценария:
1. при не переданном дополнительно параметре nID_SubjectOrganDepartment выбирается первая строка из сущности FlowLink по nID_Service
2. при переданном дополнительно параметре nID_SubjectOrganDepartment выбирается строка из сущности FlowLink по nID_Service и указанному nID_SubjectOrganDepartment

3) Дописать документацию АПИ

**Comment by BorisEfimenko** [comment]
Обновил документацию
https://github.com/e-government-ua/i/blob/test/docs/specification.md#18_workWithFlowSlot

**Comment by Koffeek** [comment]
При тестировании на альфе работает, согласно ТЗ. Спасибо!

**Comment by RoOmel** [comment]
Сервис реализован, но работает некорректно.

1) Ссылка
https://test.region.igov.org.ua/wf/service/flow/getSheduleFlowIncludes?sID_BP=kiev_mreo_1
в доке
https://github.com/e-government-ua/i/blob/test/docs/specification.md#18_workWithFlowSlot
не относится к сервису getFlowSlots_ServiceData, не понял зачем она в примере.

2) При отправке запроса
https://test.igov.org.ua/wf/service/flow/getFlowSlots_ServiceData?nID_ServiceData=1&nID_Service=&sID_BP=&nID_SubjectOrganDepartment=true&bAll=false&nDays=177&nFreeDays=60&sDateStart=2015-06-01
при этом значения параметра nID_SubjectOrganDepartment подставлялись "true" и "false",
От сервера был получен ответ
{
    "code": "SYSTEM_ERR",
    "message": "Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"true\""
}
хотя без параметра nID_SubjectOrganDepartment ответы сервера возвращаются  с 200 ОК и в теле переданы записи:
{
    "aDay": [
        {
            "sDate": "2015-06-08",
            "bHasFree": true,
            "aSlot": [
                {
                    "bFree": true,
                    "nID": 20576,
                    "sTime": "08:00",
                    "nMinutes": 15
                },
               ....................... и так далее

**Comment by bvv4ik** [comment]
"при этом значения параметра nID_SubjectOrganDepartment подставлялись "true" и "false","
с чего-бы это?
там должен быть ИД-шник департамента

@Koffeek подтверди/опровергни плиз что работает

**Comment by RoOmel** [comment]
Написано автором:
 "Обновил документацию
https://github.com/e-government-ua/i/blob/test/docs/specification.md#18_workWithFlowSlot"
В доке есть запись:
"nID_SubjectOrganDepartment - ID департамента субьекта-органа (опциональный, по умолчанию false)"
Это же не я придумал.

**Comment by bvv4ik** [comment]
там только опечатка в документации по поводу "по умолчанию false", но ведь тамжеж и написано что он опциональный (т.е. его не нужно задавать)

и главное - описание-то параметра недвусмысленное "ИД департамента" - как-же ИД-шник может быть true или false (тут-жеж стоит вникнуть, прежде чем шо угодно подставлять)

@Koffeek подтверди/опровергни плиз что работает

**Comment by Koffeek** [comment]
@RoOmel 
У меня на боевых процессах всё работает нормально. Несколько разных услуг под одним департаментом ведутся по одному потоку без задвоений слотов. Это работает как для разных департаментов у каждого из которых свой поток и для двух разных потоков у одного департамента. При необходимости уточнить тестовые случаи готов дать БП на которых всё работает

**Comment by bvv4ik** [comment]
закрываем тода что-ли?
