### ISSUE TITLE
Добавить поддержку при формировании принтформы, для типа enum, отображение кастомного значения

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#974]
Если в значении переменной типа "enum" присутствует символ "|", то в качестве значения выводить только то, что находится справа от этого символа.

Например, значение: "Бабушкинский|03"
Выводить только "03"
а если: "Бабушкинский"
то "Бабушкинский"

**Comment by maximshe** [comment]
взял в работу

**Comment by maxymshg** [comment]
PR #978 : Если все ок проливайте, но нужна проверка. Так как действовал в слепую, без локальных проверок

**Comment by GrekD** [comment]
можно ли уже проверять?

**Comment by bvv4ik** [comment]
да, проверять - нужно)

**Comment by bvv4ik** [comment]
ну как, протестено?

**Comment by GrekD** [comment]
извините, был завал с координацией волонтеров. обещаю до 9.12.2015 протестить

**Comment by GrekD** [comment]
работает. спасибо!

подскажите, еще пожалуйста: можно  ли сделать так чтоб при прописывании определенных условий - передавалось  либо то что до черты либо то что после?
к примеру:
name="Переміщення товарів за державним кредитом|33"
в одно место принтформы я хочу передать цифру "33"
в другое место принтформы - хочу передать "Переміщення товарів за державним кредитом"
из одного и того же источника
