### ISSUE TITLE
В форме услуги, для типа label, при использовании маркеров проставления значений по условию - реализовать поддержку ХТМЛ (как это реализовано для статичных значений)

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#975]
Если  при использовании маркеров в поле с типом label приходит  html код, необходимо  парсить егои отображать в виде ХТМЛ . Сейчас отображается в виде текста. https://www.dropbox.com/s/d48cu5tqcpyf9tc/html%20in%20markers.PNG?dl=0 

![image](https://cloud.githubusercontent.com/assets/4208821/11437356/d12c5dec-94f5-11e5-9a2f-33c8df817e7b.png)

тестовый процесс: https://test.igov.org.ua/service/671/general

в лейбл "посилання" ссылка подтягивается из маркера после выбора значения в выпадающем списке

**Comment by kurbpa** [comment]
https://test.igov.org.ua/service/671/general - подготовил тестовый процесс.

**Comment by hordesalik** [comment]
Дело в том, что знения в маркерах приходят с закодированными хтмл-элементами вот так:
&lt;a href=&quot;https://google.com.ua&quot; target=&quot;blank&quot;&gt;сплатити онлайн&lt;/a&gt;
JavScript и angularjs не имеют нативной поддержки декодирования символов обратно в хтмл-сущности, поэтому я предлагаю переложить эту задачу на бекенд, чтобы сохарнялись эти маркеры без кодирования хтмл-сущностей, вот так:
<a href="https://google.com.ua" target="blank">сплатити онлайн</a>

**Comment by kurbpa** [comment]
@bvv4ik 
@hordesalik 

После реализации функционала доработки и проверки его на тестовом процессе, попробовал её проверить на нормальном БП, где ранее вместо ссылки  в лейбле  отрисовывался просто текст. - https://test.igov.org.ua/service/1414/general (для Волинской области)

В момент перехода на страницу услуги ( после авторизации) теперь отображается множетво сообщений об ошибке "помилка unterminated string literal (caused by "undefined")"

**Comment by hordesalik** [comment]
@kurbpa @bvv4ik 
Проверил, дело не в этой задаче. Сделал вот так:
```
 $scope.htmldecode = function(encodedhtml)
  {
    return encodedhtml;
  }
```
Т.е. значение не обрабатывается никак, а ошибка все равно есть...

**Comment by kurbpa** [comment]
@hordesalik 
Вы похоже правы... 
https://test.igov.org.ua/service/1414/general (для Волинской области) - убрал из процесса полностью маркеры , но ошибка на фронте всё также осталась.

@bvv4ik - чтото изменили в процессе парсинга фронта ?

**Comment by kurbpa** [comment]
проблема была в процессе самом. Нашел. Исправил - проблема исчезла.

**Comment by hordesalik** [comment]
Так что? закрываем?

**Comment by kurbpa** [comment]
@hordesalik 
Да. всё работает !
Спасибо!

**Comment by VadimGulich** [comment]
Все работает
