### ISSUE TITLE
Доработать сервис /getLoginBPs так, чтоб группа в БП вида "dnepr_cnap_${area}" была равноценна маске "dnepr_cnap_*" где "*" - лубой текст...

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#976]
таким образом, 
если юзер будет находится в группе с такой маской - ему этот БП отобразится...

Привер: 
Группа: "dnepr_cnap_${area}"

а пользователь находится в группе: 
"dnepr_cnap_123"
- БП ему отобразится по этому сервису
а если "dnepr_cnap11_123", то нет

ТЕСТИРОВАТЬ НА:
БП: dnepr_cnap_266.bpmn
зайти под логином-паролем: teplikcnap
на: https://test.region.igov.org.ua/tasks

это новый юзер, и там одна заявка в отработанных по процессу "внесенння до державного кадастру...."
зайти в "звіти", вторую дату ставим 2015-12-01

в віпадающий список подтягивается список БП и среди них нет этого "внесенння до державного кадастру...."

после доработки он там должен появиться.

**Comment by RoOmel** [comment]
Прошу уточнить сценарий для тестирования, т.к. попробовал по шагам, приведённым выше, но не получилось.

**Comment by ASkosyr** [comment]
я повторил шаги тестирования - там процесс есть

http://prntscr.com/9bw4y1

**Comment by RoOmel** [comment]
"вторую дату ставим 2015-12-01" в поле к блоку "Експорт" или к блоку "Статистика"?

**Comment by ASkosyr** [comment]
я так понимаю разницы нет
процесс появляется и в Еспорт и в Статистика

**Comment by RoOmel** [comment]
Совершенно верно, при этом до и после установки указанной даты.

**Comment by ASkosyr** [comment]
здесь не очень корректно указан путь тестирования в описании задачи.
В рамках задачи подправлялось, чтобы пользователю был доступен указанные бизнес процесс.
Он соответственно доступен в обоих выпадающих списках.
Выбор даты на это не влияет

**Comment by RoOmel** [comment]
Я не совсем понимаю какой должен быть ожидаемый результат, т.е. что должно быть при определённых действиях, а чего быть не должно.

**Comment by GrekD** [comment]
@RoOmel 
попробуйте тестировать на
БП: _test_Country
услуга
https://test.igov.org.ua/service/688/general
зайти под логином-паролем: teplikcnap
на: https://test.region.igov.org.ua/tasks

**Comment by RoOmel** [comment]
Чтобы тестировать надо знать ожидаемый результат.

**Comment by GrekD** [comment]
ожидаемый результат: заходите в дашборд чиновника, там есть раздел "звіти"
внизу подраздел статистика ставите даты с 2015-06-01 по 2015-12-01 в выпадающем списке должны быть только 2 процесса по тем заявкам которые находятся в папке "оброблені":
"внесення до державного земельного кадастру...."
"_test_country...."
остальных процессов типа "реєстрація громадського об'єднання"  - быть не должно

**Comment by RoOmel** [comment]
Коллеги, прошу определиться с задачей, т.к. комменты ASkosyr и GrekD противоречат друг другу, а мне теперь непонятно что было задумано, как должна быть реализована задача, что получилось на самом деле и как я должен её тестировать?
GrekD:
 - варианты выпадающего списка никак не зависят от даты установленной в нижних полях подраздела статистики на вкладке "звіти"; 
 - в дашборде информация вкладки "Задачи" не зависит от "Звіти"

**Comment by bvv4ik** [comment]
@dmitrijzabrudskij  Дима, ты обещал группы поменять везде...
замени плиз, а то ведь деплой скоро на боевой

**Comment by dmitrijzabrudskij** [comment]
@bvv4ik какие группы нужно завести?

**Comment by GrekD** [comment]
@bvv4ik Мы группы уже позаводили в некоторых процессах.
что дальше можем сделать?
