### ISSUE TITLE
Доработать сервис /downloadTasksData, добавив туда функционал из сервиса таймингов

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#977]
- [x] 1) Реализовать механизм при котором если не задан параметр saFields (сделать его опциональным), то выдавать полный перечень полей, как это реализовано в сервисе таймингов (/download_bp_timing). 
Добавить опциональный параметр bHeader (по умолчанию false), указывающий выводить хедер с названиями колонок в выходной файл.
Добавить опцию в перечислении полей, при которой каждому описываемому полю сожет быть добавлен префикс, например "HeaderName=", перед описанием поля, которое и станет хеадером.
Пример:
saFields=HeaderName\=${nID_Task};HeaderName2\=${sDateCreate};HeaderName3\=${area};;;0;HeaderName4\=${bankIdlastName} ${bankIdfirstName}
HeaderName, HeaderName2 - будут вставляться в выходной файл как заголовки для первой и второй колонок значений.

- [x] 2) добавить в сервис функционал из таски (опциональный параметр позволяющий добавлять кастомные вычисляемые поля):
https://github.com/e-government-ua/i/issues/907

- [x] 3) добавить в сервис функционал из таски (опциональный параметр позволяющий выдавать агрегаты/сводные данные):
https://github.com/e-government-ua/i/issues/916

**Comment by ASkosyr** [comment]
Example of request for part 1 of the ticket

``
https://test.region.igov.org.ua/wf/service/rest/file/downloadTasksData?&sID_BP=dnepr_spravka_o_doxodax&sID_State_BP=usertask1&sDateAt=2015-06-01&sDateTo=2015-10-01&bHeader=true
``

Custom header names
``
https://test.region.igov.org.ua/wf/service/rest/file/downloadTasksData?&sID_BP=dnepr_spravka_o_doxodax&sID_State_BP=usertask1&sDateAt=2015-06-01&sDateTo=2015-10-01&bHeader=true&&saFields=${nID_Task};${sDateCreate};${area};;;0;${bankIdlastName} ${bankIdfirstName} ${bankIdmiddleName};4;${aim};${date_start};${date_stop};${place_living};Passport\=${bankIdPassport};1;${phone};${email}
``

**Comment by ASkosyr** [comment]
Первый пункт сделан

**Comment by bvv4ik** [comment]
отлично!
сможешь сориентировать по оставшимся двум? вообще на сколько это будет проблематично?

**Comment by ASkosyr** [comment]
Example of request for the second part of the ticket

```https://test.region.igov.org.ua/wf/service/rest/file/downloadTasksData?&sID_BP=dnepr_spravka_o_doxodax&sID_State_BP=usertask1&sDateAt=2015-06-01&sDateTo=2015-10-01&saFieldsCalc=%22nCount=(sID_UserTask==%27usertask1%27?1:0);nTest=(sAssignedLogin==%27kermit%27?1:0)%22
```

**Comment by ASkosyr** [comment]
Пример запроса для 3 пункта
https://test.region.igov.org.ua/wf/service/rest/file/downloadTasksData?&sID_BP=dnepr_spravka_o_doxodax&sID_State_BP=usertask1&sDateAt=2015-06-01&sDateTo=2015-10-01&saFieldSummary=email;nVisites=count()&bHeader=true

Пример ответа
```email;nVisites
vidokgulich@gmail.com;2
kermit;1
rostislav.siryk@gmail.com;4
rostislav.siryk+igov.org.ua@gmail.com;3
```

**Comment by RoOmel** [comment]
1) Реализован и работает корректно

2) Запросы с параметром saFieldsCalc неудалось проверить, т.к. значение параметра в примере выше в зашифрованном виде.
Прошу значение параметра показать без шифрования, а также мне необходимо знать ожидаемый результат.

3) Реализован и работает корректно

**Comment by bvv4ik** [comment]
не понял вопроса

**Comment by RoOmel** [comment]
2) Запросы с параметром saFieldsCalc неудалось проверить, т.к. значение параметра в примере выше в зашифрованном виде.
В запросе
https://test.region.igov.org.ua/wf/service/rest/file/downloadTasksData?&sID_BP=dnepr_spravka_o_doxodax&bHeader=true&sID_State_BP=usertask1&sDateAt=2015-06-01&sDateTo=2015-10-01&saFieldsCalc=%22nCount=(sID_UserTask==%27usertask1%27?1:0);nTest=(sAssignedLogin==%27kermit%27?1:0)%22
значение параметра saFieldsCalc задано
 %22nCount=(sID_UserTask==%27usertask1%27?1:0);nTest=(sAssignedLogin==%27kermit%27?1:0)%22
а нас амом деле что должно быть?

**Comment by bvv4ik** [comment]
этот "зашифрованный вид", на самом деле - расшифровывается в браузере...
цифра после процента - это шестнадцатеричный код символа
 %27 - код знака '

**Comment by RoOmel** [comment]
Мы тратим драгоценное время на никому ненужную переписку и преобразование шестнадцатеричных кодов в символы - по сути топчемся на месте, а надо двигаться дальше.
Вместо этого можно было сразу написать ссылку в нормальном виде для тестирования и избежать всего этого.
