### ISSUE TITLE
Встроить механизм запуска нового процесса по отработке эскалации волонтерами.

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#981]
- [x] 1) Ночью по шетдулеру по эскалаци сейчас отправка идет письма на почту. Встроить туда же механизм запуска нового процесса по отработке данной эскалации волонтерами. При старте процесса передавать ид таски, название группы на которой данная таска зависла и форму чиновника со всеми данными (сконвертированную в json формат).

Поля, которые передать в сартовую таску:
переменные процесса:
bankIdlastName
bankIdfirstName
bankIdmiddleName
phone
nID_Protected - взять из таски
processName - название процесса 
processID - ид процесса (уникальный идентификатор)
organ - название группы, которая отработала закрываемую таску
data - не обязательное поле.

Смежная задача по созданию процесса: https://github.com/e-government-ua/iBP/issues/282

- [x] 2) При создании экземпляра БП
- [x] 2.1) записать в сущности HistoryEvent_Service ИД процесса, в поле nID_Proccess_Escalation
- [x] 2.2) добавить запись в сущность EscalationHistory, со статусом:
2;BP_Created;БП создан
(сущность реализуется по ишью: https://github.com/e-government-ua/i/issues/984)

- [ ] 3) В интерцепторе, при отработке и закрытии этого БП
добавить запись в сущность EscalationHistory - соответствующими статусами
3;BP_Process;БП в процессе
или
4;BP_Closed;БП закрыт

(определять, что это именно этот БП, узнавая по ИД-процесса его ИД-БП)

**Comment by bvv4ik** [comment]
Ольга, я дополнил эту таску пунктами по сохранению информации о событиях БП - в истории...

так что можно пока делать, а я, для ускорения процесса - передам задачку по реализации тех двух смежных сущностей - другому коллеге..

**Comment by LamronNu** [comment]
ок, идею поняла. пока буду делать часть без истории, а как только будет готова история -- дополню реализацию.

**Comment by bvv4ik** [comment]
таску по истории уже взяли)
так что, думаю совсем скоро и это будет готово...
как там успехи?

**Comment by LamronNu** [comment]
успехи есть) 
правда, на выходных не было времени доделать, но там все равно без "истории" осталось пару штрихов..
поэтому хорошо, буду уже допиливать "основу" и потихоньку писать "каркас" под историю)

**Comment by bvv4ik** [comment]
хорошая новость: задача по сущностям истории - реализована!)

**Comment by LamronNu** [comment]
схема теста:

0) создаем новую заявку: https://test.igov.org.ua/service/176/general, днепропетровская область, запоминаем ее номер и введенные данные (телефон, фио, дата создания и т.п.).

1) создаем правило эскалации с обработчиком nID_EscalationRuleFunction=2:
https://test.region.igov.org.ua/wf/service/escalation/setEscalationRule?sID_BP=dnepr_dms_passport&sID_UserTask=*&sCondition=nDaysLimit%3E0&soData={nDaysLimit:3}&sPatternFile=escalation/escalation_template.html&nID_EscalationRuleFunction=2

сИД_БП указываем **dnepr_dms_passport**, т.к. для задач по нему уже запущены бп эскалации и новые бп будут создаваться только в случае новых заявок (для этого и был п.0)

2) в респонсе предыдущего запроса получаем сущность EscalationRule:
```json
{
	"sID_BP":"dnepr_dms_passport",
	"sID_UserTask":"*",
	"sCondition":"nDaysLimit>0",
	"soData":"{nDaysLimit:3}",
	"sPatternFile":"escalation/escalation_template.html",
	"nID":60028,
	"nID_EscalationRuleFunction":{
		"sBeanHandler":"EscalationHadler_StartEscalationProcess",
		"nID":2,
		"sName":"Запуск бп эскалации"
	}
}
```
запоминаем её **nID:60028** (у Вас будет свой, здесь оставила свои номера, чтобы было понятней, где какие ид-шки прописывать)

3) запускаем правило на выполнение
https://test.region.igov.org.ua/wf/service/escalation/runEscalationRule?nID=60028

что должно произойти.
 -- когда правило запускается первый раз по какой-то заявке указанного бп, то создается новый БП отработки эскалации волонтерами, куда передаются параметры, указанные в таске (фио, телефон и т.п.)
 -- если же процесс уже был запущен ранее, то ничего не происходит

 проверить, был ли запущен по данной заявке бп эскалации, можно запросом
https://test.igov.org.ua/wf/service/services/getHistoryEvent_Service?nID_Protected=79675057 
где nID_Protected-- это номер нашей заявки

респонс:
```json
{
	"sID":null,
	"nID_Task":7967505,
	"nID_Subject":20045,
	"sStatus":"Заявка подана",
	"sID_Status":"обробка дмс",
	"sDate":"2015-12-08 22:12:43.634",
	"nID_Service":176,
	"nID_Region":1,
	"sID_UA":"1200000000",
	"nRate":null,
	"soData":"[]",
	"sToken":null,
	"sHead":null,
	"sBody":null,
	"nTimeHours":null,
	"sID_Order":"0-79675057",
	"nID_Server":0,
	"nID_Proccess_Feedback":null,
	"nID_Proccess_Escalation":8157823,
	"sID_Rate_Indirectly":null,
	"nID_Protected":79675057,
	"nID":43046
}
```
в любом случае после запуска эскалации поле **"nID_Proccess_Escalation":8157823** должно быть не пустым.

4) проверяем, были ли переданы нужные параметры. заходим в админку чиновника: 
https://test.region.igov.org.ua/tasks
ищем нужный бп в Необроблених (должен быть в самом верху после выбора фильтра "від найновіших"), называется "Відпрацювання ескалації. обробка волонтером",
 сверяем данные из исходной заявки и в форме бп.

5) проверяем историю эскалаций (п.3 в таске)
5.1) после создания бп. должен быть статус "бп создан", нИД=2
используем один из следующих запросов (любой, т.к. их результат должен быть одинаковый):
- https://test.region.igov.org.ua/wf/service/escalation/getEscalationHistory?nID_Process_Root=79675057
(ид исходного процесса, т.е. номер заявки без последней цифры)
- https://test.region.igov.org.ua/wf/service/escalation/getEscalationHistory?nID_Process=8157823
(ид, которое nID_Proccess_Escalation из п.3 этого комментария)

должна быть хотя бы одна запись:
```json
{
	"sDate":"2015-12-12 16:13:18.951", 
	"nId":60010, 
	"nIdProcess":8157823, 
	"nIdProcessRoot":79675057, 
	"nIdUserTask":7918136, 
	"nIdEscalationStatus":2
} 
```
5.2) отрабатываем бп. (сначала в Необроблених нажимаем "почати опрацювання" -- переходим к заявке -- нажимаем "опрацювати").
после обработки в дашборде чиновника -- должны появиться записи с нИД=3 (в работе) и/или нИД=4 (закрыт)

6) после всех манипуляций не забываем удалить это правило (нужные правила будут настраиваться отдельно другими людьми):
 https://test.region.igov.org.ua/wf/service/escalation/removeEscalationRule?nID=60028
 
 примечание 1. если в Необроблених не видно процесса, а количество записей 500 -- то сначала нужно провести несколько других заявок в работу  (поскольку там установлен лимит на отображение записей), а потом уже искать "свой" бп.
 примечание 2. если при нажатии на одну из других заявок выдает какую-то ошибку -- берем другую заявку (там есть "битые" бп, это все "издержки" процесса разработки)

будут вопросы/уточнения -- задавайте, отвечу)

**Comment by RoOmel** [comment]
1) Создал новую заявку 86450017 по ссылке https://test.igov.org.ua/service/176/general;
2) Создал правило эскалации по запросу
https://test.region.igov.org.ua/wf/service/escalation/setEscalationRule?sID_BP=dnepr_dms_passport&sID_UserTask=*&sCondition=nDaysLimit:3&soData={nDaysLimit:3}&sPatternFile=escalation/escalation_template.html&nID_EscalationRuleFunction=2
Получил ответ сервера
{
    "sID_BP": "dnepr_dms_passport",
    "sID_UserTask": "*",
    "sCondition": "nDaysLimit:3",
    "soData": "{nDaysLimit:3}",
    "sPatternFile": "escalation/escalation_template.html",
    "nID": 60711,
    "nID_EscalationRuleFunction": {
        "sBeanHandler": "EscalationHadler_StartEscalationProcess",
        "nID": 2,
        "sName": "Запуск бп эскалации"
    }
}
3) Запустил парвило по запросу 
https://test.region.igov.org.ua/wf/service/escalation/runEscalationRule?nID=60709
Получил ответ сервера
{
    "code": "SYSTEM_ERR",
    "message": "\nnDaysLimit:3\n ^"
}

4) Проверяю запуск БП по заявке 86450017 по запросу
https://test.igov.org.ua/wf/service/services/getHistoryEvent_Service?nID_Protected=86450017
Ответ сервера
{
    "sID": null,
    "nID_Task": 8645001,
    "nID_Subject": 20045,
    "sStatus": "Заявка подана",
    "sID_Status": "Заявка подана",
    "sDate": "2015-12-18 08:46:08.025",
    "nID_Service": 176,
    "nID_Region": 1,
    "sID_UA": "1200000000",
    "nRate": null,
    "soData": "[]",
    "sToken": null,
    "sHead": null,
    "sBody": null,
    "nTimeHours": null,
    "sID_Order": "0-86450017",
    "nID_Server": 0,
    "nID_Proccess_Feedback": null,
    "nID_Proccess_Escalation": null,
    "sID_Rate_Indirectly": null,
    "nID_Protected": 86450017,
    "nID": 44403
}
Ожидаемый результат по пунктам 3 и 4 не соответствует актуальному.
Прошу уточнить (скорректировать) и прокомментировать.

**Comment by LamronNu** [comment]
>Я не понял какое значение должно быть у параметра sCondition "nDaysLimit:3", "nDaysLimit>3" или какое-то другое?

сорри, копировала из строки хрома, не заметила "подмены" символов. 
там должно быть nDaysLimit>0 (это условие, по которому запустится эскалация)

обновите свою запись запросом:
https://test.region.igov.org.ua/wf/service/escalation/setEscalationRule?sID_BP=dnepr_dms_passport&sID_UserTask=*&sCondition=nDaysLimit>0&soData={nDaysLimit:3}&sPatternFile=escalation/escalation_template.html&nID_EscalationRuleFunction=2&nID=60709

(если Вы ее еще не удалили), убедитесь, что условие sCondition обновилось, а потом дальше по пунктам.

**Comment by RoOmel** [comment]
Скорректировал запросы - пункты 3 - 4 тестирования прошёл.
При прохождении "4) проверяем, были ли переданы нужные параметры. заходим в админку чиновника: https://test.region.igov.org.ua/tasks"
ожидаемый БП отсутствует, кроме этого отображается сообщение
![2015-12-18_11-56-17](https://cloud.githubusercontent.com/assets/12996514/11894316/08fdffc0-a57f-11e5-8463-73d11f38a56c.jpg)

**Comment by LamronNu** [comment]
>примечание 1. если в Необроблених не видно процесса, а количество записей 500 -- то сначала нужно провести несколько других заявок в работу (поскольку там установлен лимит на отображение записей), а потом уже искать "свой" бп.
примечание 2. если при нажатии на одну из других заявок выдает какую-то ошибку -- берем другую заявку (там есть "битые" бп, это все "издержки" процесса разработки)

1) вижу на скриншоте, что бп в Необроблених -- 500 штук. какая самая "крайняя" дата, из последних? нужно "попроводить" другие заявки, чтобы отобразился Ваш бп..
2) эта ошибка -- в каком-то из старых бп возникает. просто нажмите Ок и выберите другой бп

**Comment by LamronNu** [comment]
апд. только что попроводила часть заявок -- сверху появилось два бп по эскалации -- возможно, это Ваши)

**Comment by RoOmel** [comment]
Ок.
Помню последнее число на момент написания коммента было 16.12.2015

**Comment by RoOmel** [comment]
Нашёл свою заявку, правда номер стал другой
2015-12-18 11:51 №86525323 Відпрацювання ескалації | Обробка волонтером

**Comment by RoOmel** [comment]
Проверяю 5.1)
По запросу
https://test.region.igov.org.ua/wf/service/escalation/getEscalationHistory?nID_Process_Root=8645001
ответ сервера
[
    {
        "sDate": "2015-12-18 11:51:04.308",
        "nID": 60713,
        "nID_Process": 8652532,
        "nID_Process_Root": 8645001,
        "nID_UserTask": 8645063,
        "nID_EscalationStatus": 2
    }
]
По запросу
https://test.region.igov.org.ua/wf/service/escalation/getEscalationHistory?nID_Process=8652532
ответ сервера
[
    {
        "sDate": "2015-12-18 11:51:04.308",
        "nID": 60713,
        "nID_Process": 8652532,
        "nID_Process_Root": 8645001,
        "nID_UserTask": 8645063,
        "nID_EscalationStatus": 2
    }
]

**Comment by RoOmel** [comment]
Трабатываю 5.2)
Нажал "Взяти в роботу" -> "Почати опрацюывання задачи" -> "Опрацювати"
Увидел в "Оброблені" свою завку.
Но не понял как проверить "после обработки в дашборде чиновника -- должны появиться записи с нИД=3 (в работе) и/или нИД=4 (закрыт)"

**Comment by RoOmel** [comment]
6) Удалил правило запросом
https://test.region.igov.org.ua/wf/service/escalation/removeEscalationRule?nID=60709
Ответ
200 ОК

**Comment by RoOmel** [comment]
Вцелом задача реализована согласно ТЗ
Остался у меня вопрос по проверке 5.2

**Comment by LamronNu** [comment]
> вопрос по проверке 5.2 

у Вас появилась вторая запись в Истории эскалаций, с "nID_EscalationStatus": 4 -- именно это я и имела ввиду, извините за такую расплывчастую формулировку (под нИд подразумевалось nID_EscalationStatus). этот статус (нИд=4) значит "бп закрыт", нИд=2 значит "бп создан" (исходя из таски #984).

надеюсь, я ответила на Ваш вопрос

**Comment by RoOmel** [comment]
Ок
