### ISSUE TITLE
Создать новую "связанную сущность" SubjectOrganJoinAttribute и доработать сервис getSubjectOrganJoins

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#982]
- [x] 1) Создать сущность SubjectOrganJoinAttribute с полями:
nID_SubjectOrganJoin - ИД-номер индекса связанной записи сущности SubjectOrganJoin
sName - строка названия атрибута (уникальный в паре с nID_SubjectOrganJoin)
sValue - строка значения атрибута

ВАЖНО: только через новый отдельный чанджсет в liqbase

- [x] 2) заполнить ее csv такими данными:
nID_SubjectOrganJoin;sGroup;sName;sValue
1;sFilial;ВОЛИНСЬКА;
1;Address;Волинська обл., м. Луцьк, вул.Винниченка, 11;
1;WorkTime;_workTime_;
1;MFO;303440;
1;Bill;26001060316317;
1;BillOKPO;36277731
1;PaySum_Days5;12
1;PaySum_Days20;6
1;PaySum_Days30;0
1;PaySum;=[nDays]=5?[PaySum_Days5]:[nDays]=20?[PaySum_Days20]:[Pay_Days30]
2;sFilial;ВОЛИНСЬКА1;
2;Address;Волинська обл., м. Луцьк, вул.Винниченка, 111;
2;WorkTime;_workTime_1;
2;MFO;3034401;
2;Bill;260010603163171;
2;BillOKPO;362777311
2;PaySum_Days3;14
2;PaySum_Days15;7

- [x] 3) Доработать метод getSubjectOrganJoins так, чтоб если задан дополнительный (опциональный) параметр bIncludeAttributes=true, то в обїект каждого відаваемого єлемента (SubjectOrganJoin) - добавлять єлемент-массив aAttribute, вида:
aAttribute:[
{
sName:"sFilial"
,sValue:"ВОЛИНСЬКА"
}
,{
sName:"MFO"
,sValue:"303440"
}]

- [x] 4) Добавить в метод getSubjectOrganJoins опциональный параметр
mAttributeCustom, в который может передаваться JSON-обьект вида
{
"nDays":"5"
,"sMisc":"test"
,"sMisc2":"test2"
}

- [ ] 5) Доработать метод getSubjectOrganJoins так, чтоб если задан опциональній параметр п.3. и при этом в массивах aAttributesCustom(общий для всех элементов) и aAttributes(для конкретного элемента джоин-а), что по п.3 и п.4, найдено значение в поле sValue, которое начинается с символа "=", то производить вічисление формулы js, находящейся в єтом значении. При этом все встретившиеся элементы, заключенные в квадратные скобки [], заменить на реальные значения из общего неймспейса mAttributeCustom+aAttributes. А уже результат вычисления вернуть в качестве значения (sValue).

Подсказка: явовский механизм выполнения js-формул уже использовался при реализации эскалаций. Пример:
Пєкєдж: org.wf.dp.dniprorada.base.service.escalation
Класс: EscalationHelper
Метод: checkTaskOnEscalation
...
            conditionResult = new JSExpressionUtil().getResultOfCondition(jsonData, mTaskParam, sCondition);
...
где:
sCondition - формула js (типа: "nElapsedDays >= nDaysLimit")
jsonData и mTaskParam - мапы с параметрами ()
а исходный soData (который потом конвертится в мапу jsonData), может содержать объект приблизительно такого вида:
{nDaysLimit:3, asRecipientMail:['dmitrij.zabrudskij@privatbank.ua']}

- [ ] 6) Все пришедшие кастомные атрибуты - не возвращать в виде элементов масива атрибутов, каждого из джоинов, кроме тех, в которых находятся формулы

Пример:
https://test.igov.org.ua/wf/service/services/getSubjectOrganJoins?nID_SubjectOrgan=284&sID_UA_=1&mAttributeCustom={%22n1%22:%225%22,%22n2%22:%223%22,%22n0%22:%22=[n1]%3E3?111:222%22,%22sMisc%22:%22test%22}&bIncludeAttributes=true

- вернет только атрибут с формулой (вычесленный)

- [ ] 7) В комментариях внести описания сервиса и его параметров с выводом (в т.ч. пример объекта), и убедиться что после деплоя - автосгенерируется документация по АПИ
(в одной из первых двух ссылок тут: https://github.com/e-government-ua/i/blob/test/docs/specification.md)

**Comment by kurbpa** [comment]
SubjectOrganJoinAttribute.csv - создан на wf-central на альфе

**Comment by D-Zhuravlyov** [comment]
Спасибо

**Comment by bvv4ik** [comment]
сложности какие-то намечаются, или пока без осложнений?)

**Comment by kurbpa** [comment]
@bvv4ik 
@D-Zhuravlyov 

Коллеги, на каком этапе задача ?

**Comment by bvv4ik** [comment]
Работает, теперь на запрос:

https://test.igov.org.ua/wf/service/services/getSubjectOrganJoins?nID_SubjectOrgan=284&sID_UA_=1&mAttributeCustom={%22nDays%22:%225%22,%22sMisc%22:%22test%22}&bIncludeAttributes=true

отдает:

[
{
"subjectOrganId": 284,
"aAttribute": [
{
"subjectOrganJoinId": 1167,
"nID": null,
"sName": "nDays",
"sValue": "5"
},
{
"subjectOrganJoinId": 1167,
"nID": null,
"sName": "sMisc",
"sValue": "test"
}
],
"nID": 1167,
"sNameUa": "Тернопільська митниця",
"sNameRu": "Тернопільська митниця",
"sID_Privat": "40300 00 00",
"sID_Public": "40300 00 00",
"sGeoLongitude": " ",
"sGeoLatitude": " ",
"nID_Region": null,
"nID_City": null,
"sID_UA": "6100000000"
},
{
"subjectOrganId": 284,
"aAttribute": [
{
"subjectOrganJoinId": 1174,
"nID": null,
"sName": "nDays",
"sValue": "5"
},
{
"subjectOrganJoinId": 1174,
"nID": null,
"sName": "sMisc",
"sValue": "test"
}
],
"nID": 1174,
"sNameUa": "Луганська митниця",
"sNameRu": "Луганська митниця",
"sID_Privat": "70200 00 00",
"sID_Public": "70200 00 00",
"sGeoLongitude": " ",
"sGeoLatitude": " ",
"nID_Region": null,
"nID_City": null,
"sID_UA": "4400000000"
},

**Comment by bvv4ik** [comment]
а по такому запросу(с формулой: "=[n1]/[n2]"):
(полный параметр: mAttributeCustom={"n1":"5","n2":"3","n0":"=[n1]/[n2]","sMisc":"test"})

https://test.igov.org.ua/wf/service/services/getSubjectOrganJoins?nID_SubjectOrgan=284&sID_UA_=1&mAttributeCustom={%22n1%22:%225%22,%22n2%22:%223%22,%22n0%22:%22=[n1]+[n2]%22,%22sMisc%22:%22test%22}&bIncludeAttributes=true

получится:
[
{
"subjectOrganId": 284,
"aAttribute": [
{
"subjectOrganJoinId": 1167,
"nID": null,
"sName": "n1",
"sValue": "5"
},
{
"subjectOrganJoinId": 1167,
"nID": null,
"sName": "n2",
"sValue": "3"
},
{
"subjectOrganJoinId": 1167,
"nID": null,
"sName": "sMisc",
"sValue": "test"
},
{
"subjectOrganJoinId": 1167,
"nID": null,
"sName": "n0",
"sValue": "1.6666666666666667"
}
],
"nID": 1167,
"sNameUa": "Тернопільська митниця",
"sNameRu": "Тернопільська митниця",
"sID_Privat": "40300 00 00",
"sID_Public": "40300 00 00",
"sGeoLongitude": " ",
"sGeoLatitude": " ",
"nID_Region": null,
"nID_City": null,
"sID_UA": "6100000000"
},
...........

где:
"sName": "n0",
"sValue": "1.6666666666666667"
(т.е. вычеслино)

**Comment by bvv4ik** [comment]
Для теста можно вызвать:
https://test.igov.org.ua/wf/service/services/getSubjectOrganJoins?nID_SubjectOrgan=284&sID_UA_=1&mAttributeCustom={%22n1%22:%225%22,%22n2%22:%223%22,%22n0%22:%22=[n1]%3E3?111:222%22,%22sMisc%22:%22test%22}&bIncludeAttributes=true

и покомбинировать с формулой

+ с задаваемым ИД-шником СубьектаОргана

**Comment by RoOmel** [comment]
При запросе
https://test.igov.org.ua/wf/service/services/getSubjectOrganJoins?nID_SubjectOrgan=284&sID_UA_=1&mAttributeCustom={"n1":"5","n2":"3","n0":"=[n1]/[n2]","sMisc":"test"}&bIncludeAttributes=true
Ответ сетвера
[
    {
        "subjectOrganId": 284,
        "aAttribute": [
            {
                "subjectOrganJoinId": 1167,
                "nID": null,
                "sName": "n0",
                "sValue": "1.6666666666666667"
            }
        ],
        "nID": 1167,
        "sNameUa": "Тернопільська митниця",
        "sNameRu": "Тернопільська митниця",
        "sID_Privat": "40300 00 00",
        "sID_Public": "40300 00 00",
        "sGeoLongitude": " ",
        "sGeoLatitude": " ",
        "nID_Region": null,
        "nID_City": null,
        "sID_UA": "6100000000"
    },
....... и так далее

При запросе
https://test.igov.org.ua/wf/service/services/getSubjectOrganJoins?nID_SubjectOrgan=284&sID_UA_=1&mAttributeCustom={"n1":"5","n2":"3","n0":"=[n1]/[n2]","sMisc":"test"}&bIncludeAttributes=false
ответ сервера
[
    {
        "subjectOrganId": 284,
        "aAttribute": [],
        "nID": 1167,
        "sNameUa": "Тернопільська митниця",
        "sNameRu": "Тернопільська митниця",
        "sID_Privat": "40300 00 00",
        "sID_Public": "40300 00 00",
        "sGeoLongitude": " ",
        "sGeoLatitude": " ",
        "nID_Region": null,
        "nID_City": null,
        "sID_UA": "6100000000"
    },
....... и так далее

**Comment by RoOmel** [comment]
При запросе
https://test.igov.org.ua/wf/service/services/getSubjectOrganJoins?nID_SubjectOrgan=284&sID_UA_=1&mAttributeCustom={ "nDays":"5" ,"sMisc":"test" ,"sMisc2":"test2" }&bIncludeAttributes=true
ответ сервера
[
    {
        "subjectOrganId": 284,
        "aAttribute": [],
        "nID": 1167,
        "sNameUa": "Тернопільська митниця",
        "sNameRu": "Тернопільська митниця",
        "sID_Privat": "40300 00 00",
        "sID_Public": "40300 00 00",
        "sGeoLongitude": " ",
        "sGeoLatitude": " ",
        "nID_Region": null,
        "nID_City": null,
        "sID_UA": "6100000000"
    },
.......... и так далее

**Comment by RoOmel** [comment]
5) Значение в поле sValue, не начинается с символа "=", хотя значение параметра в ответе присутствует.

**Comment by bvv4ik** [comment]
проверено уже в действвующем механизме
