### ISSUE TITLE
Создать две связанные производные сущности от эскалаций, по сохранению истории эскалации и соответствующие сервисы

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#984]
- [x] 1) Создать сущность EscalationStatus
- [x] 1.1) с такими полями:
nID - номер-ИД (уникальный-автоитерируемый)
sID - строка-ИД (уникальный)
sNote - строка-описание

- [x] 1.2) такими данными в csv
nID;sID;sNote
1;MailSent;Отослано письмо
2;BP_Created;БП создан
3;BP_Process;БП в процессе
4;BP_Closed;БП закрыт

- [x] 1.3) и таким сервисом:
- getEscalationStatuses - получить массив объектов сущности (и кодом статуса 200, при успехе)

- [x] 2) Создать сущность EscalationHistory
- [x] 2.1) с такими полями:
nID - номер-ИД (уникальный, автоитерируемый)
sDate - дата
nID_Process - номер-ИД процесса
nID_Process_Root - номер-ИД процесса (корневого, из-за которого запущена эскалация)
nID_UserTask - номер-ИД юзертаски
nID_EscalationStatus - номер-ИД статуса эскалации

- [x] 2.2) такими данными в csv
nID;sDate;nID_Process;nID_UserTask:nID_EscalationStatus
1;2015-11-20 12:12:12;444444;343555;4

- [x] 2.3) и таким сервисом:
- getEscalationHistory - получить массив объектов сущности (и кодом статуса 200, при успехе)
с задаваемыми параметрами:
nID_Process - номер-ИД процесса //опциональный
nID_Process_Root - номер-ИД процесса (корневого) //опциональный
nID_UserTask - номер-ИД юзертаски //опциональный
sDateStart - дата начала выборки //опциональный, в формате YYYY-MM-DD hh:mm:ss
sDateEnd - дата конца выборки //опциональный, в формате YYYY-MM-DD hh:mm:ss
nRowsMax - максимальное число строк //опциональный, по умолчанию 100 (защита - не более 5000)

- [x] 3) В комментариях внести описания сервиса и его параметров с выводом (в т.ч. пример объекта), и убедиться что после деплоя - автосгенерируется документация по АПИ
(в одной из первых двух ссылок тут: https://github.com/e-government-ua/i/blob/test/docs/specification.md)

**Comment by kalu44i** [comment]
1. https://test.igov.org.ua/wf/service/escalation/getEscalationStatuses
Повертає список статусів
```
[{"sNote":"Отослано письмо","nID":1,"sID":"MailSent"},
{"sNote":"БП создан","nID":2,"sID":"BP_Created"},
{"sNote":"БП в процессе","nID":3,"sID":"BP_Process"},
{"sNote":"БП закрыт","nID":4,"sID":"BP_Closed"}]
```
2. https://test.igov.org.ua/wf/service/escalation/getEscalationHistory
Повертає всі записи з сутності EscalationHistory, але не більше 5000
```
{"sDate":"2015-09-09 21:20:25.000","nID":1,"nID_Process":9463,"nID_Process_Root":29193,"nID_UserTask":894,"nID_EscalationStatus":91}
...
```
3. https://test.igov.org.ua/wf/service/escalation/getEscalationHistory?nID_Process=6276&nID_Process_Root=57119&nID_UserTask=634&sDateStart=2014-11-24%2000:03:00&sDateEnd=2014-12-26%2000:03:00&nRowsMax=100
Повертає записи які попадають під критерії параметрів в запиті:
a) sDateStart - sDateEnd вказують період з якого будуть взяті записи
b) nRowsMax - обмеження на кількість записів, які будуть повернуті
c) Відсутність параметра в запиті - відсутність обмеження

**Comment by bvv4ik** [comment]
Супер, спасибо!
тогда, пора ставить лейбл тест на таске?

**Comment by RoOmel** [comment]
Результат тестирования:
1) https://test.igov.org.ua/wf/service/escalation/getEscalationStatuses
Список статусов возвращает - согласен, но исходя из чего?
Какие параметры должны быть на входе (если должны конечно)?

2) https://test.igov.org.ua/wf/service/escalation/getEscalationHistory
Список статусов возвращает - согласен, но исходя из чего?

3) https://test.igov.org.ua/wf/service/escalation/getEscalationHistory?nID_Process=&nID_Process_Root=&nID_UserTask=&sDateStart=2000-01-01 00:00:00&sDateEnd=2015-12-11 23:59:59&nRowsMax=5000
Возращает список записей, но всегда только 100 штук, независимо от значения параметра nRowsMax

**Comment by bvv4ik** [comment]
дока описана в комментах и автогенерируется (по указанной ссылке верхними двума пунктами указаны ссылки на автогенерируемую доку)

**Comment by RoOmel** [comment]
Пункт в постановке задачи написан
 "3) В комментариях внести описания сервиса и его параметров с выводом (в т.ч. пример объекта), и убедиться что после деплоя - автосгенерируется документация по АПИ
(в одной из первых двух ссылок тут: https://github.com/e-government-ua/i/blob/test/docs/specification.md)"
что и было указано.
Вопросы 1 и 3 выше остались без ответа.

**Comment by bvv4ik** [comment]
@kalu44i  прошу глянуть по п.3

@RoOmel п.1 тут тотже случай, когда стоит вначале просто вникнуть: это сервис получения массива существующих статусов... зачем там еще параметры? да и по доке-то-ж нет ни каких параметров и по таске...

**Comment by kalu44i** [comment]
По пункту 3. 
Додав до файлу з данними більше рядків (було 100). Наразі в базі 105 тестових записів.
1. https://test.igov.org.ua/wf/service/escalation/getEscalationHistory?nID_Process=&nID_Process_Root=&nID_UserTask=&sDateStart=2000-01-01%2000:00:00&sDateEnd=2015-12-11%2023:59:59&nRowsMax=5000
Повертає всі 105 записів
2. https://test.igov.org.ua/wf/service/escalation/getEscalationHistory?nID_Process=&nID_Process_Root=&nID_UserTask=&sDateStart=2000-01-01%2000:00:00&sDateEnd=2015-12-11%2023:59:59&nRowsMax=103
Повертає 103 записи
3. https://test.igov.org.ua/wf/service/escalation/getEscalationHistory?nID_Process=&nID_Process_Root=&nID_UserTask=&sDateStart=2000-01-01%2000:00:00&sDateEnd=2015-12-11%2023:59:59
Повертає 100 записів

**Comment by RoOmel** [comment]
3) Теперь возвращает больше 100 при параметре nRowsMax больше 100
