### ISSUE TITLE
Создать сущность ObjectEarthTarget и сервисы к ней

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#985]
- [x] 1) Создать сущность ObjectEarthTarget ,с полями:
nID - ИД-номер Код внутренний (уникальный-ключ, автоитерируемый, long)
sID_UA - ИД-номер Код, в Украинском классификкаторе (уникальный-ключ, String < 10 символов)
sName_UA - название на украинском (уникальный, String < 200 символов)

Пример объекта сущности:
{
   nID,3
, "sID_UA ":"02.05"
, "sName_UA":"Для будівництва індивідуальних гаражів"
}

- [x] 2) написать сервис
getObjectEarthTargets - отдает массив объектов сущности, подпадающих под критерии
параметры:
sID_UA //опциональный
sName_UA//опциональный (достаточно чтоб совпала часть названия)

- [x] 3) Наполнить данными csv
из источника данных:
http://www.neruhomist.biz.ua/classification.html

- [x] 4) В комментариях внести описания сервиса и его параметров с выводом (в т.ч. пример объекта), и убедиться что после деплоя - автосгенерируется документация по АПИ
(в одной из первых двух ссылок тут: https://github.com/e-government-ua/i/blob/test/docs/specification.md)

**Comment by grigoriy-romanenko** [comment]
для поля sName_UA нужно увеличить макс. длину, потому что значения из источника данных не вписываются в 200 символов. минимум нужно 385. я предлагаю 500

**Comment by grigoriy-romanenko** [comment]
еще вопрос насчёт сервиса getObjectEarthTargets
параметр sName_UA - достаточно чтоб совпала часть названия.
начало названия или не важно какая часть?

**Comment by bvv4ik** [comment]
для поля sName_UA нужно увеличить макс. длину, потому что значения из источника данных не вписываются в 200 символов. минимум нужно 385. я предлагаю 500

согласен

**Comment by bvv4ik** [comment]
еще вопрос насчёт сервиса getObjectEarthTargets
параметр sName_UA - достаточно чтоб совпала часть названия.
начало названия или неважно какая часть?

любая часть, т.к. по этому полю будет работать автокомплит...

**Comment by grigoriy-romanenko** [comment]
готово, можно тестировать

**Comment by bvv4ik** [comment]
потрясающе оперативно!
спасибо огромное, готовлю производную таску для фронта!
(это и позволит протестить полноценно)

**Comment by MichaelTkachuk** [comment]
Не уверен что пишу в нужном месте. Я сегодня начал изучать коди что происходит в проекте.

В этом таске и смжном с ним кодом есть прблемы с названиями.
Из EarthTarget тяжело догадаться о смысле. Должно быть LandUse или LandFunction

**Comment by bvv4ik** [comment]
эта тема большая и точно для отдельной ишью а не в этой
(только создавать ее не нужно, т.к. ее создание будет итогом устного предварительного общения)

на самом деле, все предложенные альтернативные участки названий - очень спорные и не однозначные... Вообще, использовать такие абстрактные слова как Type, Category, Function, т.к. кроме "целевого назначения земли" может быть еще миллион других типов, категорий и т.д. (например: ценовая категория, степень эрогзии, тип ландшафта, тип собственности, фактический тип использования, заповедник/не заповедник и т.д.)

вообщем, прошу в этой таске это не обсуждать (и новую не создавать), а просто войти в группу organisation, мониторить названия сущностей до их именования (в крайних случаях - после), и выходить на общение/обсуждение...

**Comment by skfd** [comment]
Доменные переменные уместно писать кирилицей `НазначениеЗемли` -- гораздо лучше надмозга `EarthTarget`.

Против: Сложнее набирать код. Зарубежный разработчик не сможет дорабатывать. Придётся терпеть шутки про "1С".

За: Название переменной выражает суть напрямую. 2015 год и уникод есть везде. Продукт расчитан исключительно на местных разработчиков и потребителей.

**Comment by bvv4ik** [comment]
@skfd со всем уважением, прошу это все в слаке обсуждать, в канале _organisation или _back
данная таска к этому не относится

**Comment by RoOmel** [comment]
Коллеги, в доке https://github.com/e-government-ua/i/blob/test/docs/specification.md
ни про ObjectEarthTarget, ни про getObjectEarthTargets информации не нашёл.
Для тестирования необходимо описание сущности и сервисов, ссылка для примера и ожидаемый результат.
Прошу доку дополнить.

**Comment by grigoriy-romanenko** [comment]
документация: https://jenkins.igov.org.ua//view/new/job/central_alpha/ws/wf-central/target/site/apidocs/index.html

**Comment by RoOmel** [comment]
Отлично, спс.

**Comment by RoOmel** [comment]
При запросе
https://test.igov.org.ua/wf/service/services/getObjectEarthTargets?sID_UA=03.03&sName_UA=
Ответ сервера
[
    {
        "sID_UA": "03.03",
        "sName_UA": "Для будівництва та обслуговування будівель закладів охорони здоров'я та соціальної допомоги",
        "nID": 25
    }
]
Согласно http://www.neruhomist.biz.ua/classification.html
03.03	Для будівництва та обслуговування будівель закладів охорони здоров'я та соціальної допомоги
Реализвано согласно ТЗ
