### ISSUE TITLE
Реализовать поддержку автокомплита для справочников ObjectEarthTarget

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#986]
По примеру (не полностью) задачи #584 - реализовать аналогичную поддержку автокомплита.
С обязательной поддержкой параллельного одновременного наличия нескольких таких полей в одной форме (хоть и с разными суффиксами).

- для сущности ObjectEarthTarget (https://github.com/e-government-ua/i/issues/985)

- id полей: sObjectEarthTarget, sObjectEarthTarget_1, sObjectEarthTarget_2 и т.д. (sObjectEarthTarget*)

- если в форме встречается поле c id, начинающимся с sObjectEarthTarget_789, то отрисовывать вместо него автокомплит с соответствующим контентом, при выборе элемента из которого - сохранять его sID_UA в поле c id=sID_UA_ObjectEarthTarget_789

**Comment by bvv4ik** [comment]
проверять по данным и тестовому БП этой таски:
https://github.com/e-government-ua/i/issues/994

**Comment by GrekD** [comment]
автокомплит работает
проверяла на вот этом процессе на альфе
https://test.igov.org.ua/service/143/general

**Comment by bvv4ik** [comment]
@GrekD
Дарья, если таки работает - прошу закрыть таску
