### ISSUE TITLE
В поиске документов, при ожидании ответа - отображать "анимацию ожидания"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#989]
Когда нажимаешь кнопку "Найти" при поиске документа по коду, какое-то врем яничего не происходит.

Хотелось бы показывать индикатор загрузки.
Особенно это важно, когда ищешь больше, чем 1 документ (тогда обновление ссылки для скачивания вообще не видно).

**Comment by Sokhatsky** [comment]
Индикатор загрузки в разделе Документы - Поиск документа за кодом отсутствует

**Comment by Sokhatsky** [comment]
[S4]
