### ISSUE TITLE
Заменить при загрузки документа надпись

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#990]
Для загрузки документа у нас сейчас отображается надпись "Квитанция оплаты". Давайте заменим на "Завантажити документ".
![2015-12-10 12 57 24](https://cloud.githubusercontent.com/assets/4208821/11713689/9afff24a-9f3d-11e5-8d9b-b0eb0a7a5d6b.png)

**Comment by VadimGulich** [comment]
есть , заменили
