### ISSUE TITLE
Реализовать страницу расширенного фидбэка по итогу оказания услуги, чтоб можно было оставлять комментарий

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#991]
- [ ] 1) Реализовать страницу с двумя параметрами /feedback?sID_Order=1-45425232&sToken=Igh09Ho8h
(например: https://test.igov.org.ua/feedback?sID_Order=45425232&sSecret=Igh09Ho8h)

- [ ] 2) при заходе на страницу вызвать через серверную часть ноды сервис явы(GET-запросом) /wf/messages/getMessageFeedbackExtended?sID_Order=1-45425232&sToken=Igh09Ho8h (передать пришедшие параметры)
(реализация по задаче: https://github.com/e-government-ua/i/issues/1012)
Если нет ошибки и в ответном объекте будет НЕ НАЛОВЫЙ элемент sDate, то выводить сообщение "Отзыв уже был оставлен: " и дальше писать содержимое этого элемента(дата отправки), и не выводить лейбл, поле текстареа и кнопку

- [ ] 3) по результатам вызова сервиса п.2 - взять содержимое поля "sHead" (по дефолту null)

- [ ] 4) Если п.2. пройден успешно, то отобразить пустую страницу (со стандартным  хеадером и футером сайта) и разместить там:
- вверху лэйбл с текстом: "Оставьте свой отзыв";
- ниже лэйбл с текстом: из переменной "sHead" (п.3), где если null, то текст не писать.
- текстовое поле (высота 5 строк, шириной 500 пикселей);
- кнопку "Отправить".

- [ ] 5) При нажатии на кнопку отправить:

- [ ] 5.1. вызвать через серверную часть ноды сервис явы(POST-запросом)
/wf/messages/setMessageFeedbackExtended?sID_Order=1-45425232&sToken=Igh09Ho8h (передать пришедший параметр)
(реализация по задаче: https://github.com/e-government-ua/i/issues/1012)
в теле передать параметр:
sBody=dfdfdsf (передать данные из текстового поля)

- [ ] 5.2. после успешной отправки - закрывать вкладку обозревателя.

- [ ] 6) Выводить ошибки:
- [ ] 6.1) Если при запросе одного из сервисов будет получена ошибка с текстом "Security Error", то выводить стандартный диалог с ошибкой "Ошибка безопасности!"
- [ ] 6.2) Если при запросе одного из сервисов будет получена ошибка с текстом "Record Not Found", то выводить стандартный диалог с ошибкой "Запись не найдена!"
- [ ] 6.3) Если при запросе одного из сервисов будет получена ошибка с текстом "Already exist", то выводить стандартный диалог с ошибкой "Отзыв уже был оставлен!"

Для теста специально создана тестовая запись, по смежной(бэковой задаче), потому должно открыть по ссылке:
https://test.igov.org.ua/feedback?sID_Order=0-4446&sSecret=TokenValue

**Comment by ASkosyr** [comment]
Я поменял УРЛ вызова метода с
/wf/message/getMessage_Feedback
на
/wf/messages/getMessage_Feedback

Так как контроллер, в который будет добавлятся метод, замаплен на /messages

**Comment by glebzhebrakov** [comment]
ага, спасибо!

**Comment by ASkosyr** [comment]
Закоммитил методы
Пример вызова:

https://test.igov.org.ua/wf/service/messages/getMessageFeedbackExtended?sID_Order=0-33&sToken=TokenValue

Возвращается 403 ошибка

https://test.igov.org.ua/wf/service/messages/getMessageFeedbackExtended?sID_Order=0-331&sToken=TokenValue

Возвращается 404 ошибка

**Comment by glebzhebrakov** [comment]
Отлично, спасибо, вечером буду прикручивать

**Comment by ASkosyr** [comment]
Пример запроса, который возвращает данные

https://test.igov.org.ua/wf/service/messages/getMessageFeedbackExtended?sID_Order=0-4446&sToken=TokenValue

```json
{"sHead":"head","sDate":"2015-12-21 12:09:56 235","sID_Order":"0-4446"}
```

**Comment by bvv4ik** [comment]
Для теста:
https://test.igov.org.ua/feedback?sID_Order=0-4446&sSecret=TokenValue
- уже поданный фидбек

https://test.igov.org.ua/feedback?sID_Order=0-5551&sSecret=TokenValue2
- еще не поданный

**Comment by Koffeek** [comment]
После проставления оценки идет переход на страницу для оставления комментария. После оставления комментария и нажатия кнопки "Залишити відгук" идет редирект на главную страницу портала. В процесс по фидбеку подтягивается оценка, но не подтягивается комментарий.

**Comment by bvv4ik** [comment]
2. он-то переходит но оценку не перезаписывает
1.коментарий и не должен подтягиваться...  а вот в статусах, в истории он будет по этой заявке

**Comment by Koffeek** [comment]
1. В закладке "Статусы" сохраняется только первая оценка, пишется что отзыв оставлен, но его содержимое не указывается. 
2. Оценка перезаписывается в порождаемом БП по фидбеку (только что проверил). В нем же из номера заявки исчезает последняя цифра, что делает невозможным поиск для волонтера. И поле под комментарий гражданина там заводилось.

**Comment by MaksKnight** [comment]
Подскажите пожалуйста как протестировать ?

**Comment by MaksKnight** [comment]
Все работает корректно.
