### ISSUE TITLE
Ссылку на раздел "Статусы" в письме о принятии заявки

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/i#993]
Когда я заказываю некоторую услугу мне приходит email следующего содержания:
"Ваша заявка 3375010 прийнята!
Ви завжди зможете переглянути її поточний статус у розділі "Статуси". Також на кожному етапі Ви будете отримувати email-повідомлення."

При этом в данном письме нет ни одной ссылки - ни на этот раздел, ни вообще даже на igov.org.ua. Нужно сделать чтобы слово "Статуси" было ссылкой на https:/igov.org.ua/order/search (ну или если письмо пришло с какого-то тестового сервера, то на что-то вроде https://test-version.igov.org.ua/order/search соответственно).

**Comment by bvv4ik** [comment]
ссылку-то добавили (пока на тестовый),

но коллеги, просьба:
"пожалуйста, не ставьте в этом репозитории таски", т.к. он исключительно для согласованных задач... если все будут сюда ставить свои задачи-пожелания, то работать станет вообще невозможно

для всех предложений есть репозиторий iForun

спасибо за понимание

**Comment by IrynaAndronik** [comment]
1) Зашла на сайт заказала успешно услугу - Отримання субсидії на оплату житлово-комунальних послуг. 
2)На e-mail пришло сообщение -Ваша заявка 3476591 прийнята!
Ви завжди зможете переглянути її поточний статус у розділі "Статуси". Також на кожному етапі Ви будете отримувати email-повідомлення. - Ссылка на этот раздел или сайт отсутствует.
3) Зашла на сайт, в вкладке Статусы ввела номер ID получила информацию о времени подачи и Статус - Заявка подана.
4) Зашла на сайт чиновника  https://test.region.igov.org.ua/tasks, запроса с таким ID не оказалось.

**Comment by OlgaTurenko** [comment]
по пункту 4 - это нормально. Вы под пользователем кермит заходите, видать этот процесс запускается на группу, в которой нет пользователя кермит. потому и не видите заявку.

**Comment by bvv4ik** [comment]
"1) Зашла на сайт "
на бету смержили только позавчера...
а изначально делали на альфе (как раз когда Вы тестили)

потому прошу перепроверить - ссылка уже должна быть
