### ISSUE TITLE
Создать унифицированный механизм работы с полями-селекторами (автокомплитами) в форме заполнения услуги

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#994]
- [ ] 1) Должно работать через унифицированный механизм для:
- https://github.com/e-government-ua/i/issues/979
(ObjectCustoms)
- https://github.com/e-government-ua/i/issues/986
(ObjectEarthTarget)
- https://github.com/e-government-ua/i/issues/980
(SubjectOrganJoinTax)
- https://github.com/e-government-ua/i/issues/969
(Currency)
- ну и Country

- [ ] 2) Дефолтно заменять, определяя по ИД поля(с названием) тип на "select"

- [ ] 3) на серверную часть ноды передавать только идентификатор сервиса и параметры (для безопасности)

- [ ] 4) Тестовый БП: _test_selectors

        id="bankIdsID_Country" type="invisible" default="UKR"
        
        id="sID_UA_Country" type="invisible"></activiti:formProperty>
        id="sCountry" type="select"></activiti:formProperty>
        id="sID_UA_Country_123" type="invisible"
        id="sCountry_123" type="select"
        
        id="sID_UA_ObjectCustoms" type="invisible"
        id="sObjectCustoms" type="string"
        id="sID_UA_ObjectCustoms_4" type="invisible"
        id="sObjectCustoms_4" type="string"
        
        id="sID_UA_ObjectEarthTarget" type="invisible"
        id="sObjectEarthTarget" type="string"
        id="sID_UA_ObjectEarthTarget_5" type="invisible"
        id="sObjectEarthTarget_5" type="string"
        
        id="sID_UA_SubjectOrganJoinTax" type="invisible"
        id="sSubjectOrganJoinTax" type="select"
        id="sID_UA_SubjectOrganJoinTax_6" type="invisible"
        id="sSubjectOrganJoinTax_6" type="string"
        
        id="sID_UA_Currency" type="invisible"
        id="sCurrency" type="string"
        id="sID_UA_Currency_7" type="invisible"
        id="sCurrency_7" type="select"

**Comment by GrekD** [comment]
1. при выборе из селекта ничего не записывает в само поле (sObjectCustoms, sObjectCustoms 4, sObjectEarthTarget, sSubjectOrganJoinTax)

2. sSubjectOrganJoinTax: повторяются одни и те же названия в селекте

3. sSubjectOrganJoinTax: можно ли сделать таким образом чтоб подтягивалось либо sName_UA либо sID_UA - в зависимости от того что надо будет в процессе?

**Comment by hordesalik** [comment]
1 - Да, видел, упустил, что нужно разобраться
2 - Что приходит с бека - то и выводится.
3 - Думаю можно будет организовать. Можно сделат обработку по ИД = sSubjectOrganJoinTaxName и добавить описание как обрабатывать этот тип на фронте

**Comment by GrekD** [comment]
@bvv4ik 
Владимир, а вот эти задвоения в справочнике мне нужно почистить?
53;1154;Відділ кадрової роботи;10200 00 02
88;1155;Відділ кадрової роботи;11000 00 02
113;1156;Відділ кадрової роботи;11200 00 02
....

**Comment by bvv4ik** [comment]
1.
да, тут поправить-бы...


"Владимир, а вот эти задвоения в справочнике мне нужно почистить?
53;1154;Відділ кадрової роботи;10200 00 02
88;1155;Відділ кадрової роботи;11000 00 02
113;1156;Відділ кадрової роботи;11200 00 02"

@GrekD я так понимаю это к п.2 относится?
@hordesalik тут действительно нужно еще и один параметр добавлять - nID_SubjectOrganJoin
, который, кстати, можно выбрать в этой-же тестовой таске (в конце вроде)
Это позволяет сузить список поиска, т.к. выдаст только подсубьектов в рамках определенной ветки...


"3. sSubjectOrganJoinTax: можно ли сделать таким образом чтоб подтягивалось либо sName_UA либо sID_UA - в зависимости от того что надо будет в процессе?"

@GrekD так это уже и реализовано... подтягиваются оба значения... просто можно будет скрвть поле с sID_UA (т.е. сделать его инвизибле), это временно оно видно, для теста...
А вот само название на человеческом языке должно быть всегда (для человека), хоть в самом БП можете его и не использовать...

**Comment by GrekD** [comment]
@bvv4ik 
- Владимир, а вот эти задвоения в справочнике мне нужно почистить?
- я так понимаю это к п.2 относится?
- да, это к п.2

**Comment by bvv4ik** [comment]
п.2
@@hordesalik  
кстати, именно в отдельной таске, по этому поводу сказано (в конце, там где "ВАЖНО:":
https://github.com/e-government-ua/i/issues/980

**Comment by bvv4ik** [comment]
"Владимир, а вот эти задвоения в справочнике мне нужно почистить?"
нет, ни в коем случае, ведь тамжеж все ИД-шники уникальные, каждый просто для своей области (точнее джоина/подразделения области)

**Comment by hordesalik** [comment]
ок. постараюсь сегодня поправить

**Comment by GrekD** [comment]
@bvv4ik Владимир, все корректно работает. Осталось сами справочники наполнить - валюта, товары - они не заполнены полностью.
