### ISSUE TITLE
Попытаться создать юнит тест загрузки бизнес процессов ативити.

### ISSUE THREAD

**Issue by brunneng** [e-government-ua/i#997]
Тест должен загружать бизнес процессы ативити, и если была обнаружена ошибка при загрузке - падать.
Предположительно за загрузку отвечает бин: processEngineConfiguration

**Comment by brunneng** [comment]
Для проверки как работает тест можно намеренно поломать какой то процесс *.bpmn , закоммитить, и убедится что на дженкинсе упал билд https://jenkins.igov.org.ua/view/new/job/regional-alpha/
потом откатить изменения.

**Comment by RoOmel** [comment]
1) Для того, чтобы закоммитить (поломать) какой то процесс *.bpmn мне необходимо знать какой именно процесс за что отвечает, чтобы потом проверить и сравнить актуальный результат с ожидаемым;
2) Кроме этого нужны права для скачивания из репозитория и деплоя изменённого проекта;
3) Нет информации какой клиент нужен для работы с репозиторием;
4) Убеждён, что задачи такого типа присущи разработчикам.
