### ISSUE TITLE
реализовать поддержку системного тэга [sDateTimeCreateProcess], [sDateCreateProcess] и [sTimeCreateProcess] в принтформе, вместо которого будет подставляться Дата создания процесса (в формате "YYYY-MM-DD hh:mm", "YYYY-MM-DD" и "hh:mm")

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#998]
по типу того, как реализовано в:
https://github.com/e-government-ua/i/issues/797

но только там берется дата Таски, а нужна дата Процесса (то с чего началась первая таска)

ВАЖНО: Для реализации таски использовать сервис, по ишью(для получения даты): https://github.com/e-government-ua/i/issues/1011
Вызывать его при открвтии таски (когда подгружаются все ее поля)
(путь: /wf/service/action/task/getTaskData описание в доке по АПИ)

Комит, в котором как раз правится нужный участок:
https://github.com/uazure/i/commit/796fe1e9d5e6deb2acf33b92c38fa9396cee8583

printTemplate = this.populateSystemTag(printTemplate, "[sDateCreate]", $filter('date')(task.createTime, 'yyyy-MM-dd HH:mm'));

только маркеры другие должены быть

**Comment by GrekD** [comment]
https://test.igov.org.ua/service/673/general
Винницкая область-Теплик
логин пароль: teplikcnap
номер заявки 95325013
для теста

**Comment by dmitrijzabrudskij** [comment]
при попытке втяжки даты подачи заявки в принтформу внутри процесса появляется такая ошибка: https://www.dropbox.com/s/7mdqck3bbi3szkn/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-02-18%2016.30.59.png?dl=0

Invalid Date

**Comment by bvv4ik** [comment]
какой номер заявки и номер таски?

**Comment by dmitrijzabrudskij** [comment]
111550012
11155321 или 11137504

**Comment by bvv4ik** [comment]
Вот в таком запросе:
https://test.region.igov.org.ua/wf/service/action/task/getTaskData?nID_Task=11155321

отдает все норм:

{
"sStatusName": "Взяти в роботу",
"oData": null,
"sID_Status": 11155321,
"oProcess": {
"sName": "Отримання субсидії на оплату житлово-комунальних послуг",
"sBP": "subsidiesUkraine:8:11137504",
"nID": 11155001,
"sDateCreate": "2016-02-18 16:29:22.755"
},
"


т.е. "sDateCreate": "2016-02-18 16:29:22.755" - есть

**Comment by dmitrijzabrudskij** [comment]
понятно. я использовал sDateCreateProcess
спасибо

**Comment by dmitrijzabrudskij** [comment]
логин/пароль: dn200986zda/dn200986zda

номер заявки 111550012. заявка в работе. выберите какое-то значение в поле "стан" и нажмите чуть ниже "роздрукувати" - в самом низу этой принтформы увидите ошибку

**Comment by hordesalik** [comment]
@dmitrijzabrudskij не вижу я поля sDateCreateProcess в принторме и ошибки тоже, подскажете подробнее ?

**Comment by hordesalik** [comment]
Шаблон: /testPrint.html
Содержит тег [sDateCreateProcess]
Заменяется успешно на дату 
![06213-70657fe2-8897-4b11-8dea-108c54618067 1](https://cloud.githubusercontent.com/assets/1492938/13184028/53543e78-d742-11e5-8566-246dc68fb227.png)
Заявка 0-112100053

**Comment by dmitrijzabrudskij** [comment]
Проверка тега

Invalid Date - он здесь

https://www.dropbox.com/s/ui2ausbqo1i8a12/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-02-23%2014.37.16.png?dl=0

у меня хоть убей не получается его увидеть. может, он с какой-то ролью появляется?

**Comment by hordesalik** [comment]
Так может в процессе дата указана кривая какая то? Вместо даты выводится "Invalid date", т.е. тег обрабатывается, но дата для форматирования не подходит

**Comment by dmitrijzabrudskij** [comment]
это та же заявка Заявка 0-112100053
логин/пароль dn200986zda

**Comment by bvv4ik** [comment]
"Так может в процессе дата указана кривая какая то? Вместо даты выводится "Invalid date", т.е. тег обрабатывается, но дата для форматирования не подходит"
ты можеш сюда написать тот обьект, который приходит на запрос, откуда и берется эта дата... чтоб было поняьтно в чем дело
?

**Comment by hordesalik** [comment]
Или открыть этот процесс для пользователя tester

**Comment by hordesalik** [comment]
FF не хочет "2016-02-18 14:35:58.455", он хочет "2016-02-18T14:35:58.455", нужно сделать правильный парсинг

**Comment by hordesalik** [comment]
Готово.

**Comment by dmitrijzabrudskij** [comment]
параметр тянется корректно. можно закрывать. спасибо

вопрос к @bvv4ik :
не получилось у меня скриптом в принтформе отформатировать дату на формат дд-мм-гггг
посмотри, пожалуйста, заявку 115525019  логин/пароль dn200986zda на альфе

**Comment by bvv4ik** [comment]
у тебя нет элемента с id=sDateCreateProcess
хотя я в примере в скайпе тебе писал этот кусок HTML
