### ISSUE TITLE
Error happened when sending email - Надання витягу з Єдиного державного реєстру МВС

### ISSUE THREAD

**Issue by imaginal** [e-government-ua/i#999]
При заказе выписки https://igov.org.ua/service/1397/general/place/built-in/region/0/city/0

стабильный результат для любых адресов (gmail.com, ukr.net, meta.ua)

ПОМИЛКА SYSTEM_ERR couldn't execute activity <serviceTask id="servicetask10" ...>: Error happened when sending email

**Comment by Vanuan** [comment]
Вот правильная ссылка https://igov.org.ua/service/1397/general

**Comment by bvv4ik** [comment]
просто, из-за резкого "наплыва желающих" - закончился лимит отсылаемых писем на день...

в связи с этим: по отключали не критичные рассылки, чтоб высвободить ресурс,
в течении суток все нормализуется... (т.е. как раз к официальному запуску - все будет в полном порядке по этой услуге)

П.С.: кстати, а откуда-ж появилась инфа о ее запуске?))

**Comment by Vanuan** [comment]
http://www.mvs.gov.ua/mvs/control/main/uk/index
Слева баннер белый текст на синем фоне
Ведет сюда: http://www.mvs.gov.ua/mvs/control/main/uk/publish/article/1748607

**Comment by Vanuan** [comment]
Предусмотрена только отправка на e-mail?

**Comment by bvv4ik** [comment]
да, на электронку только...

**Comment by Vanuan** [comment]
Из народных комментариев по поводу скорости ответа:

> iGov формирует sql запрос, отправляет, а дальше...
> - у начальника всея милиции уведомление "о-о" с смской
> - Леночка несет телефон младшему лейтенанту, тот высунув язык переписывает sql запрос в журнал, слюнявит карандаш время от времени
> - журнал передают во внутреннюю безопасность, те тщательно, с привлечением криминалистов исследуют запрос на предмет "как же тут сделать инъекцию, ведь шприца то нету!", садятся писать отчеты
> - 17:50 начальник всея милиции звонит местному админу "пойди забери там журнал с запросом, надо ответить срочно, показать что мы значит выполняем все требования и ваще идем в ногу значит со всеми, да и фото мое на сайте обнови"
> - 17:57 админ матюгаясь переписывает запрос, попутно переводя запись на язык здравого смысла, печатает ответ и несет начальнику

> ...остается еще проверить, заверить, подписать, сфоткать и отправить в iGov ММСку,
